### ISSUE TITLE
add a second ip for VPN connections

### ISSUE THREAD

**Issue by evlas** [home-assistant/android#100]
hi, i would like to know if it is possible to add a second ip for VPN connections.  I would like that the android vpn started automatically if the local ip does not belong to the ip range of the primary connection.

**Comment by EagleAdam** [comment]
Slightly similar request - but possibly a separate issue. My DSL provider's modem won't route packets for my external ddns address back to my home assistant instance. This means that if I'm on cellular data I can use my external url but on home WiFi I can't. In the iOS version of the HA app there is a possibility to have an internal and external url. Maybe an internal,external,and VPN url could be useful?

**Comment by balloob** [comment]
@EagleAdam that is not related to this issue and has already been implemented in the dev version.
