### ISSUE TITLE
"Phone State" for other Voice Call Apps

### ISSUE THREAD

**Issue by fti7** [home-assistant/android#1021]
**Describe the solution you'd like**
The Phone State Sensor only covers the native Cell Phone at the moment.
Nowadays people often use alternative Apps like Microsoft Teams, Whatsapp (Talk), Signal, Skype etc for "Voice Calls"
We should try to include this into "phone state" sensor or make an standalone one.
Im not sure how easy it is to detect this. But maybe its possible to Detect when Speaker + Microphone are in use?

**Comment by dshokouhi** [comment]
This is already possible using the audio mode sensor. It has a state for `in_communication`

**Comment by dshokouhi** [comment]
https://companion.home-assistant.io/docs/core/sensors#audio-sensors
