### ISSUE TITLE
Transparent  background does not work in app  for image

### ISSUE THREAD

**Issue by aladin2000** [home-assistant/android#1022]
**Home Assistant Android version:**
2.5.0-full
**Android version:**
10
**Phone model:**
One,+7t
**Home Assistant version:**
0.115.3
**Last working Home Assistant release (if known):**
?
**Description of problem:**
Pixel are black around object ( bulb)
Same image are ok wirh chrome on the same smartphone
**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![pixlr](https://user-images.githubusercontent.com/16690723/95465766-d5f28400-097b-11eb-8be2-8fe2ee43de1e.jpg)

**Additional information:**

**Comment by aladin2000** [comment]
Lovelace
'
type: image 
srtate_filter: null
On: '/local/images/lightbulb-on.png'
Off: local/images/lightbulb-off.png

**Comment by dshokouhi** [comment]
Check that Android system webview is up to date

**Comment by aladin2000** [comment]
I have the uptodate webview for Android 86.0.4240.75

I update it again without success

8 oct. 2020 16:15:37 Daniel Shokouhi <notifications@github.com>:

**Comment by dshokouhi** [comment]
What theme do you have set on the device, HA profile and App Configuration screen? I am looking for all 3 settings

**Comment by aladin2000** [comment]
Theme default

8 oct. 2020 20:17:39 Aladin <aladin@free.fr>:

**Comment by dshokouhi** [comment]
@aladin2000 in your HA profile there is a setting for Auto, Light and Dark (next to the default theme), in App Configuration page there is also a theme setting.  Likewise your actual device has its own theme in your device settings.  I am looking to see if its either dark, light or follow system theme.

**Comment by aladin2000** [comment]
I played a lot  before send bug report
I used all différent theme
Follow system settings gave me the same result

Auto light or dark too

8 oct. 2020 20:36:29 Daniel Shokouhi <notifications@github.com>:

**Comment by aladin2000** [comment]
Same from either app and from chrome  Android
See that icon is ok  but not transparent image

8 oct. 2020 22:50:09 Aladin <aladin@free.fr>:

**Comment by dshokouhi** [comment]
you see the same issue in chrome?

**Comment by aladin2000** [comment]
> you see the same issue in chrome?

No it Works  in chrome

**Comment by aladin2000** [comment]
No the image is ok using URL in  chrome

8 oct. 2020 23:01:34 Daniel Shokouhi <notifications@github.com>:

**Comment by aladin2000** [comment]
Another test on another tablette 
The transparent is ok   on  Android 7
Seems to ne linked to Android 10
Any Idea ?

**Comment by aladin2000** [comment]
Probably i changed something on my smartphone
Related to screen configuration
The problem id fixed. Then i close the issue

**Comment by aladin2000** [comment]
Probably i changed something on my smartphone
Related to screen configuration
The problem id fixed. Then i close the issue
