### ISSUE TITLE
Application doesn't send mobile_app_notification_dismissed event

### ISSUE THREAD

**Issue by bieniu** [home-assistant/android#1030]
**Home Assistant Android version:** 2.5.0-full

**Android version:** 10

**Phone model:** OnePlus 6

**Home Assistant version:** 0.116.2

**Last working Home Assistant release (if known):** unknown

**Description of problem:**
The application doesn't send `mobile_app_notification_dismissed` event to the Home Assistant after dismissing notification from app. According to the [documentation](https://companion.home-assistant.io/docs/notifications/notification-dismissed), app should send this event. I dismiss the notification by swipe left/right if it matters.
The app uses Nabu Casa remote access URL to connect to my HA server.

How can I debug this issue?

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
This is a beta feature not yet in production, please update to the latest beta which may not be in the play store yet. You can get the APK from the release tab too. The companion docs get updates once a feature hits the pubic beta.
