### ISSUE TITLE
Artifacts when scrolling

### ISSUE THREAD

**Issue by PhilippMundhenk** [home-assistant/android#1031]
**Home Assistant Android version:** 2.5.0-full

**Android version:** 10

**Phone model:** Galaxy S9

**Home Assistant version:** 0.116.2

**Last working Home Assistant release (if known):**

**Description of problem:**
When scrolling, to the very bottom of a page, a number of artifacts appear, buttons vanish, re-appear, etc.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![Screenshot_20201010-173542_Home Assistant](https://user-images.githubusercontent.com/4414560/95659604-7387b800-0b22-11eb-8998-f4af50153a69.jpg)

**Additional information:**
- Could not reproduce on Android 8, Galaxy A3.
- Tried also with all frontend plugins deactivated, same result.

**Comment by dshokouhi** [comment]
check that android system webview is up to date.....if it is see if it is reproducible in chrome for android on that device

**Comment by PhilippMundhenk** [comment]
Is up-to-date and issue does not happen in Chrome.

**Comment by dshokouhi** [comment]
do you have custom cards? try disabling them if you do, things like custom header or lovelace swipe etc..

**Comment by PhilippMundhenk** [comment]
I used custom-ui and mini-graph-card. Deactived them and renamed resources. I did not remove the cards using them.
No difference

**Comment by dshokouhi** [comment]
dont just deactivate, completely remove...they can also still be cached too

**Comment by PhilippMundhenk** [comment]
- removed all related files
- removed all related configuration
- rebooted HA
- rebooted phone
- cleared cache of HA app & WebView

No difference

**Comment by PhilippMundhenk** [comment]
Might be unrelated: I noticed when using Chrome that I can change scrolling direction any time anywhere on the page. But in some cases, when I scroll to the very bottom, I need to lift my finger to scroll up again, otherwise scrolling gets stuck. I can't reliable reproduce, yet.

**Comment by dshokouhi** [comment]
Did this issue exist before 0.116?

**Comment by PhilippMundhenk** [comment]
I did not notice it before. But I did skip a few versions, was still in the 0.90s somewhere (0.95?, 0.96?)

**Comment by dshokouhi** [comment]
you should definitely try and follow these steps: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

I did not realize how old your HA version was

**Comment by PhilippMundhenk** [comment]
Well, I could have thought of that myself after this big update, but was so focused to get the server side running again I forgot about reconnecting the mobile app.

Anyway: That did it, all artifacts are gone!

Thank you very much!! Love the speed the HA app improves btw! And all the new sensors! Been using it from the first day and it is plain amazing what is possible now! Made so many things a lot easier for me!
