### ISSUE TITLE
Input Number Missing Value Text

### ISSUE THREAD

**Issue by marieper** [home-assistant/android#1051]
**Home Assistant Android version:**
2.5.0-full
**Android version:**
10
**Phone model:**
Samsung A40 and Sony H8324
**Home Assistant version:**
0.116.1
**Last working Home Assistant release (if known):**

**Description of problem:**
Input Number Missing Value Text in HA native app, while displays correctly in browser (FF 80.0.2 @ Widows 7)
Icon, label and slidebar visible, only value text is not visible.
Lovelace cards used:
- entities (plain out of the box)
- vertical stacked card with entities sub-card
**Traceback (if applicable):**

```

```

**Screenshot of problem:**
Correct behavior in FireFox, Win7: 
![ha_input_number_win7](https://user-images.githubusercontent.com/72891849/96048778-58e17600-0e77-11eb-8f41-95f9247089c2.jpg)

Erroneous behavior in HA app: 
![ha_input_number_android](https://user-images.githubusercontent.com/72891849/96048740-4b2bf080-0e77-11eb-97fc-731da382652f.jpg)

**Additional information:**
Same probblem when using Chrome on Samsung device, browsing to HA dashboard

**Comment by dshokouhi** [comment]
> Same probblem when using Chrome on Samsung device, browsing to HA dashboard

This means that the issue belongs in the HA frontend repo: https://github.com/home-assistant/frontend

If it works in Chrome then it would be an issue in the app as all we are is a webview.  You can't compare desktop to mobile in this sense.

**Comment by marieper** [comment]
It does **not** work in Chrome on Andriod 10, as stated in the Additional Info above:
"Same problem when using Chrome on Samsung device..."

It does work in Chrome in Windows as well as in FF, for whatever that is worth...
It does work on Sony SPG511 (tablet); Android 6.0.1; HA App 2.5.0-full
It fails on Huawei BAH-W09 (tablet); Androd 7.0; FireFox Focus (no HA app installed)

Totally random behavior from my perspective.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/2905
