### ISSUE TITLE
Last Notification - remove dots from attribute names

### ISSUE THREAD

**Issue by scorpio862** [home-assistant/android#1052]
**Is your feature request related to a problem? Please describe.**
I'm tryging to use Last Notification sensor but I can't use the values from sensor attributes because they contain a dot in the names.

For example an attribute "android.text" when I try to create a template: 
`{{ states.sensor.oneplus8pro_last_notification.attributes.android.text }}`

Home Assistant shows an error:
`UndefinedError: 'mappingproxy object' has no attribute 'android'`

HA thinks that the attribute name is "android"

**Describe the solution you'd like**
Please change attributes naming so it doesn't contain dot. 
For example"android.text" change to something like "android_text" or maybe just "text".

**Comment by dshokouhi** [comment]
Why don't you use the recommended method?

https://www.home-assistant.io/docs/configuration/templating/

For example

`{{ state_attr('sensor.oneplus8pro_last_notification', 'android.text') }}`

**Comment by scorpio862** [comment]
Ok. I missed that. Thanks. But this solves only half of my problem. A lot to automations I do in Node Red and I had the same issue. Node red was thinking that the name of the attribute was just 'android' because of the dot

**Comment by dshokouhi** [comment]
Node Red may need to be updated to show attributes correctly or you may not be accessing the attribute correctly.  I don't use node red so you may need to get help from someone who does.

**Comment by dshokouhi** [comment]
Some of our attributes now contain a `package` name which those definitely have `.` in the name and removing them does not make sense, all packages in android have a `.` in them.  I am going to close this request now, Node Red either needs an update to handle these attributes or your templates need an update to handle them properly too.  There is also nothing in the HA dev docs about the naming convention for attribute names https://data.home-assistant.io/docs/states
