### ISSUE TITLE
Can't upload person image from phone

### ISSUE THREAD

**Issue by nick2525** [home-assistant/android#1071]
**Home Assistant Android version:**
0.116.4
**Android version:**
10
**Phone model:**
Xiaomi mi 9
**Home Assistant version:**
None
**Last working Home Assistant release (if known):**
None
**Description of problem:**
I can't upload person image from phone. Image picker doesn't work from phone. I gave permission for gallery and camera for HA. I can upload image only from computer
![Screenshot_2020-10-17-18-52-28-413_io homeassistant companion android](https://user-images.githubusercontent.com/569343/96347357-f58b5a00-10a9-11eb-963d-5b285419c000.jpg)

**Comment by dshokouhi** [comment]
This is fixed in the latest beta version that you can download from github, google has not reviewed the play store submission yet.
