### ISSUE TITLE
Custom sounds for notifications

### ISSUE THREAD

**Issue by Mincka** [home-assistant/android#1074]
**Is your feature request related to a problem? Please describe.**
I would like to trigger custom sounds for individual notifications, not only for a specific channel. 

Support for native device notification sounds would be great at first. It would be even more powerful when using sounds from app resources, local storage, or even "streamed" sounds from network. My idea would be to dynamically play generated TTS from integrations like [TTS](https://www.home-assistant.io/integrations/tts/) or [Google Cloud](https://www.home-assistant.io/integrations/google_cloud/). It would offer the highest flexibility.
Edit: As highlighted by @dshokouhi, TTS **from the device** is already [in beta](https://github.com/home-assistant/android/pull/1011).

I am not sure but I think there are some restrictions to play sounds that are not stored on the device or embedded in the app (as packaged from the store). I looked up a bit and maybe there are some workarounds for these.

**Describe the solution you'd like**
At least, as implemented in the iOS version of the app:
https://companion.home-assistant.io/docs/notifications/notification-sounds
The best would be to be able to specify URL and / or directly use TTS.

**Describe alternatives you've considered, if any**
Using custom settings for channels would work for a type of notification only. Maybe I could use Tasker to trigger a sound or TTS at the same time than the notification.

**Additional context**
Related issues:
https://github.com/home-assistant/android/issues/383
https://github.com/home-assistant/android/issues/561

**Comment by dshokouhi** [comment]
We actually added TTS notifications in the beta a lil bit ago, check the releases tab for current beta changes.

**Comment by AbDhops** [comment]
is it possible to set custome notification even for Channel (on Android ?)..

**Comment by dshokouhi** [comment]
@AbDhops yes you just need to use another app to place the files in the appropriate location then you will be able to set the sound.  This is a standard android feature for channels.

**Comment by Mincka** [comment]
I am still interested by this feature to specify custom sounds from HA and play them dynamically on the device. If it's technically not possible or not a priority, I will completely understand and I will not up this issue if it becomes stale again.

**Comment by dshokouhi** [comment]
@Mincka once a `channel` is set the app no longer has control over the notification being played.  Apps can only set the sound once, after that its all on the user to change the channel settings.  Was your intention to always have the sound to be dynamic?

**Comment by AbDhops** [comment]
Correct. Simply go into android settings and then select Apps. In it,
select Home Assitant -> Notifications. Here you shall see all the channels
which you can customize as per your needs. See my settings for example.

**Comment by Mincka** [comment]
Yes, I wanted to be able to dynamically play sounds. I know that my use case is a bit farfetched... I wanted to generate Google Cloud TTS sentences on HA and play them through notifications. The goal was to have a better TTS that the one embedded in the phone. I still think that's something that could be achieved now using custom commands, but it's really overkill for the added value.

Thank you for your feedback. In this case I close this request.

**Comment by Hukuma1** [comment]
Found this in 2022. As I read through, I'm understanding this is not possible on iOS devices to send custom audio/TTS as a notification?
