### ISSUE TITLE
URL does not preserve ?deviceID

### ISSUE THREAD

**Issue by tunerooster** [home-assistant/android#1080]
**Home Assistant Android version:**
2.5.0-full
**Android version:**
7.1.1
**Phone model:**
nexus9 (and others)
**Home Assistant version:**
0.115
**Last working Home Assistant release (if known):**
None known
**Description of problem:**
The HA componete browser_mod allows one to specify a deviceID in the URL to access Home Assistant.  This is useful because, otherwise it generated a random string which must me managed.

Somehow, the generated deviceID changed on me. This happened twice on two different devices. I have no idea what I did to cause this. I am using the custom alias to assign a name for the deviceID, but when the underlying generated deviceID changes, the alias does not pair.

To prevent this from happening, I see that I can specify deviceID in the Home Assistant URL. That sounded great but…

I am using the Home Assistant Android App:

* I went to App Configuration and entered Home Assistant URL: https://mydomain.com/?deviceID=test
* There is no “save” button I can see, so I hit the back arrow.
* I select App Configuration again, and the Home Assistant URL has reverted back to: https://mydomain.com (i.e., with no deviceID)
* Restarting the App makes no difference.
* So I cleared the App data and cache, ant reinitialized the App. I.e., it asked for the external URL during startup.
* Again I entered: https://mydomain.com/?deviceID=test
* Once initialized and logged in, I went to App Configuration and was disappointed to see it still reverted to: https://mydomain.com (i.e., with no deviceID)

This is not a browser_mod issue.  Any options append to the URL entry fails to persist.

Is there a way to get the App to preserve the ?deviceID= in the URL?

Thanks!
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Can you please tell me what other integration that is not a custom component that requires the URL to be modified?   This request sounds like its only for browser_mod which is a custom component and not part of HA itself.

**Comment by tunerooster** [comment]
Well, I wouldn't know this, but I can guess then something like:

You are hosted on amazon and you need to specify a password to access their system.

I expect there would be other cases...  What is the purpose of removing things from the URL?

**Comment by dshokouhi** [comment]
In all cases that are accepted into HA core if any integration requires additional information that is either provided in YAML or the config entry.  There is no URL modding.  For the app itself we use the URL you provide in lots of other places.  We use that same URL for the webview and all other communication made to your HA server.  We require the base URL and during onboarding it is all that is requested.  As this is a custom integration you may want to reach out and request another way to enter the device ID or just use a real browser for it as its also called `browser_mod` the app itself we are a webview and not really a browser.  Regarding hosting elsewhere that is more of a proxy thing and not related to the app to pop-up a username and password.  Still not an HA standard.

**Comment by tunerooster** [comment]
Thanks, I will pass this on to the browser_mod people.
