### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by wullewatz** [home-assistant/android#1081]
**Is your feature request related to a problem? Please describe.**
It is not posible to use the app over Tor-Network
(Only if I proxy the whole phone)

**Describe the solution you'd like**
A proxy setting in main configuration so that it is posible to use Orxy as proxy.

**Describe alternatives you've considered, if any**
 With Orbit as proxy is root needed on Android.

**Additional context**
-nope-

**Comment by dshokouhi** [comment]
see if these help: https://companion.home-assistant.io/docs/troubleshooting/networking

**Comment by CarlosGS** [comment]
@wullewatz Which solution did you end up using?

This proxy setting proposal makes a lot of sense, here is a comment making a good case for it https://github.com/home-assistant/android/issues/313#issuecomment-588988343 
Allowing this standard setting would have negligible overhead while allowing more flexibility for a variety of setups.

**Comment by dshokouhi** [comment]
Closing as this has been stale for over a year and we did not hear back from the author regarding the troubleshooting link
