### ISSUE TITLE
Sensor next alarm - time zone problems

### ISSUE THREAD

**Issue by tahlers93** [home-assistant/android#1085]
Hi,

i have the android app on my Poco X3 NFC. I want to use the next alarm sensor (I live in germany). The following value i get from the sensor:

**Actual alarm ist in german time:** 07:00
**value of the attribute 'next alarm':** 2020-10-22T04:00:00.000Z
**local time:** Thu Oct 22 06:00:00 GMT+02:00 2020
**convert local time with:** 2020-10-22 06:00:00

Next week, we have the change from summer to winter time:
**value of the attribute 'next alarm':** 2020-10-26T05:00:00.000Z
**local time:** Mon Oct 26 06:00:00 GMT+01:00 2020
**convert local time with:** 2020-10-26 06:00:00

I convert to local time with: {{ (as_timestamp(states.sensor.poco_x3_nfc_nachster_wecker.state)) | timestamp_local }}

Is that an issue from the app, from my phone or from me?

**Comment by dshokouhi** [comment]
Are you talking about daylight savings time?  You won't see the time change until your phones time will change.

**Comment by tahlers93** [comment]
My problem is, that the current alarm time is incorrect, too. I set my alarm to 07:00. I think, With the template "{{ (as_timestamp(states.sensor.poco_x3_nfc_nachster_wecker.state)) | timestamp_local }}" i have to get 07:00 too and not 06:00.

**Comment by dshokouhi** [comment]
Whatever time your phone sends to event is whatever time we get.  What alarm app are you using? Not all alarm apps send the correct time unfortunately.  If you try something like the Google clock that will report correct time.

**Comment by tahlers93** [comment]
I'm using the integrated app "Uhr" (com.android.deskclock). So, the problem is probably the app from the poco smartphone?

**Comment by dshokouhi** [comment]
Manufacturers have been known to override the default apps, you can try something like: https://play.google.com/store/apps/details?id=com.google.android.deskclock&hl=en_US

**Comment by tahlers93** [comment]
Okay, i will test it. Thanks!
