### ISSUE TITLE
Add support for on-device haptics

### ISSUE THREAD

**Issue by agneevX** [home-assistant/android#1091]
**Home Assistant Android version:** `2.5.0-full`
**Android version:** 11
**Phone model:** Google Pixel 4a
**Home Assistant version:** 0.115.3

**Description of ~problem~ feature request:**

~My phone supports haptics natively, but I get vibrations when tapping on buttons in the front-end.~

Google Pixel devices have haptics, similar to iPhone devices, and is measured in `ms`.
Instead of a single form of vibration, haptics provide subtle but differential feedback during interactions with the frontend such as tapping buttons or opening menus.

Per Apple's Human Interface Guidelines, the following options are available for haptics and is currently implemented by devs, so they're maximum compatible.

https://companion.home-assistant.io/docs/integrations/haptics#developers-integrating-haptics-into-custom-cards

<img width="500" alt="image" src="https://user-images.githubusercontent.com/19761269/96914012-0846ca00-14c2-11eb-817a-9e5dea25ac00.png">

**Additional information:**
N/A

**Comment by dshokouhi** [comment]
The frontend is what handles this as they control the Vibrate API on a website.  We don't have control here as this is a user profile setting which needs to be respected.  Also it may even be proper haptic just a longer and more powerful vibration.  You should see the same behavior in Chrome right?

**Comment by agneevX** [comment]
> We don't have control here as this is a user profile setting which needs to be respected. 

In case of iOS, IIRC, different levels of haptic were added to the app, per Apple's HIG.

Surely the app can pickup the frontend code e.g. `haptic: light` and apply that instead of the standard vibration. 

> Also it may even be proper haptic just a longer and more powerful vibration. 

It's shorter and much less powerful and varies in intensity (measured in `ms`).

At the moment, it seems there's no support for haptics from the Android app.

**Comment by dshokouhi** [comment]
I tried taking a look at this.  Android does not really support the constants defined by Apple.  Only a handful exist and thats only available to users on the latest version API 30.

https://developer.android.com/reference/android/view/HapticFeedbackConstants

I don't see apple defining how many `ms` each of the above is mentioned.  I think this feature was designed specifically for iOS so we may need to map our `ms` response for users who cant use teh constants up above.  Additionally it will not be as easy to map them to iOS and as of now the external bus sends back everything we see in the link so we can't really change that.

Some reference to use for older devices: https://stackoverflow.com/questions/25748230/confused-about-haptic-feedback-in-android

So we need to basically define what we expect them to do, does apple have the specific patterns documented?  We probably need to do our own thing here if we don't see anything defined.

**Comment by agneevX** [comment]
Thanks for looking into this @dshokouhi.

> So we need to basically define what we expect them to do, does apple have the specific patterns documented? We probably need to do our own thing here if we don't see anything defined.

Basically yeah. 

A couple of things that could be useful:

1. https://developer.apple.com/search/?q=haptic
2. https://developer.apple.com/documentation/corehaptics/chhapticevent/parameterid/3114595-hapticintensity
3. https://developer.apple.com/documentation/corehaptics/chhapticevent/parameterid/3114596-hapticsharpness

**Comment by dshokouhi** [comment]
Yup I did see those and that was when I realized we need to do our own thing lol.

Feel free to test out the debug apk from the action link below. It will install side by side the production/beta version.

https://github.com/home-assistant/android/actions/runs/541825248

**Comment by agneevX** [comment]
I just tried it. Still get the same vibration, no haptics.

**Comment by dshokouhi** [comment]
> I just tried it. Still get the same vibration, no haptics.

can you get the logs looking for `WebviewActivity` please

https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs

As you can see its sending either haptic or vibration (if we have it)

You should see this log line followed by whatever haptic was used

https://github.com/home-assistant/android/pull/1352/files#diff-76bbedb2918a5db79c7070e9bb2e01d9241388745f60b0719c0d1f74123d89bdR467

`success` `failure` and `selection` have haptic constants, the others use vibration effects as thats what android offers if you look at the links in the PR.

**Comment by agneevX** [comment]
Ah ok I use light, medium in the frontend code. Aren't these gonna be available?

**Comment by dshokouhi** [comment]
Every single one is used with a different constant that android supports, so yes in this case there are 2 different haptic ones being used.

https://developer.android.com/reference/android/view/HapticFeedbackConstants#constants_1
