### ISSUE TITLE
Battery Icon when 100% and not charging

### ISSUE THREAD

**Issue by SeLLeRoNe** [home-assistant/android#1094]
**Home Assistant Android version:**
beta-467-1fdbe71-full
**Android version:**
10
**Phone model:**
OnePlus Nord and Mi 9T Pro
**Home Assistant version:**
0.117.0b2
**Last working Home Assistant release (if known):**

**Description of problem:**
When a phone is charged to 100% the icon in use is: icon: mdi:battery-charging
When the phone is unplugged but still at 100% the icon is not changed on the battery_level sensor even while the battery_state sensor report "dischargin" with the "battery-minus" icon
**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/9599441/96984290-b5502f80-1520-11eb-9236-b8405d7bc2b5.png)
![image](https://user-images.githubusercontent.com/9599441/96984229-b1bca880-1520-11eb-9944-8ed5b3efbfb2.png)

This is just as reference to show that when Charging in my screenshot I have a message on the secondary info:
![image](https://user-images.githubusercontent.com/9599441/96984643-ce58e080-1520-11eb-81ee-0f33bb718d93.png)

**Additional information:**

**Comment by dshokouhi** [comment]
We no longer send updates to HA when the state hasn't changed so this is to be expected. I guess we can remove the battery charging part completely for this sensor. But we won't send an update just to change the icon.
