### ISSUE TITLE
Login not working on FireTV 4K

### ISSUE THREAD

**Issue by gitolicious** [home-assistant/android#1103]
**Home Assistant Android version:** 2.5.0

**Android version:** Fire OS 6.2.7.6

**Phone model:** FireTV 4K

**Home Assistant version:** 0.116.4

**Last working Home Assistant release (if known):** _n/a_

**Description of problem:**
I installed the Home Assistant Android APK from the Github releases page to my FireTV stick. It recognizes my installation automatically and I can select it. On the login screen though, I can not navigate or insert my credentials. Any button on the FireTV remote or the FireTV companion app is ignored.

**Traceback (if applicable):**
_n/a_

**Screenshot of problem:**
Selection (working fine)
![image](https://user-images.githubusercontent.com/26963495/97087459-b4a3c000-162a-11eb-8666-e336924572b2.png)
Login screen (not working)
![image](https://user-images.githubusercontent.com/26963495/97087479-db61f680-162a-11eb-9a7a-9c3c8ab8fe7a.png)

**Additional information:**

**Comment by dshokouhi** [comment]
Sorry the app does not support TV interface

**Comment by gitolicious** [comment]
Understood. Too bad as it would be a nice feature seeing Lovelace on the TV screen with  FireTv. Anyway, thanks for the quick response!
