### ISSUE TITLE
Bluetooth connection sensor attributes are strings not arrays

### ISSUE THREAD

**Issue by zachowj** [home-assistant/android#1105]
**Home Assistant Android version:** beta-477-495e022-full

**Android version:** 11

**Phone model:**  pixel2

**Home Assistant version:** 116.4

**Last working Home Assistant release (if known):**

**Description of problem:** 

These attributes of the Bluetooth connection sensor are being sent to HA as a string, that looks like an array but are not.
- connected_not_paired_devices
- connected_paired_devices
- paired_devices

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
This was a breaking change a few releases ago, are you not able to convert them back using templates?

**Comment by zachowj** [comment]
Not sure of which breaking change you're referring to. I looked back through the history of the Bluetooth sensor and I don't see any changes that changed the data type of those three attributes from array list to a string as they appear to always have been saved to the database as a string using the `toString` method of an ArrayList. 

I don't fully understand why you would pass the array list of device ids to HA as a string when HA can handle attributes with the data type of an array.  Then there would be no need to use templates to parse them back into arrays.

If this was a design choice could it at least be made into a string that is more universally parsable?

In its current implementation, it using the toString method of ArrayList which tacks on the `[` and `]` around a comma-delimited string. 

`[00:00:00:00:00:00, 00:00:00:00:00:00, 00:00:00:00:00:00]`

and an empty array

`[]`

**Comment by dshokouhi** [comment]
When we did https://github.com/home-assistant/android/pull/889 we did not account for attributes that were setup as a list like this sensor provides.
