### ISSUE TITLE
Add option to refresh

### ISSUE THREAD

**Issue by rchovan** [home-assistant/android#1106]
**Is your feature request related to a problem? Please describe.**
Some widgets are not loaded, or are not actual. Add option to reload current page/view/layout/dashboard.

**Describe the solution you'd like**
Options are with swipe, or with item in upper right menu, where is "Edit Dashboard and Help"

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
Duplicate of #31

**Comment by JBassett** [comment]
@rchovan as a side note the latest HA Core has a refresh option in the top right menu.

**Comment by rchovan** [comment]
Hi, @JBassett thanks for info, but I can't find it. I'm running 0.116.4 and I still see only Edit and Help. 

![image](https://user-images.githubusercontent.com/6713920/97185125-fc982380-179f-11eb-9b6c-89178430fce3.png)

Where should I look ?

**Comment by JBassett** [comment]
@rchovan Latest Beta HA Core has the option.  Forgot I am on the beta for my production server!
