### ISSUE TITLE
Not all widgets are loaded on start

### ISSUE THREAD

**Issue by rchovan** [home-assistant/android#1107]
**Home Assistant Android version:**
2.5.0-full
**Android version:**
9.0
**Phone model:**
Samsung S8
**Home Assistant version:**
0.116.4
**Last working Home Assistant release (if known):**

**Description of problem:**
Not all widgets are loaded during start. When I edit dashboard, widgets are loaded, and stay until app is reloaded. 

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
Dashboard on start:
![image](https://user-images.githubusercontent.com/6713920/97105232-9c2eb680-16b9-11eb-927c-78ec0ec487cf.png)

Dashboard on edit, 2 more widgets are added
![image](https://user-images.githubusercontent.com/6713920/97105265-d9934400-16b9-11eb-891f-db439268894a.png)

**Additional information:**
All graphs are widgets type of custom:mini-graph-card

**Comment by dshokouhi** [comment]
can you check that android system webview is up to date

**Comment by rchovan** [comment]
this is my version
Version 86.0.4240.110
Updated 20.oct.2020

**Comment by dshokouhi** [comment]
is this only happening with a custom card? does it happen on chrome for android?

**Comment by rchovan** [comment]
not using Chrome, I'm using Brave, and there it is working correctly

**Comment by dshokouhi** [comment]
can you please check in Chrome and also please let me know if its only this custom card

**Comment by rchovan** [comment]
Installed latest chrome. There it is working too. Yes, so far I just found, that only this type of widget is not loading, but I use this type widget for all temperature/humidity sensors on another dashboards, and there are loaded correctly.

**Comment by dshokouhi** [comment]
I am not sure there will be much we can do, this kinda sounds like bad caching possibly.  Could be an issue with the custom card since you don't see this issue with any other cards.  The app is just a webview and we don't do any special rendering.

**Comment by rchovan** [comment]
searching for similar issues in minigraph-card, and found this (https://github.com/kalkih/mini-graph-card/issues/476). You are right, it looks like problem with widget. 
Closing issue, thanks for help.
