### ISSUE TITLE
Next_Alarm sensor updates to current time + 10 minutes when phone is locked

### ISSUE THREAD

**Issue by NobleWolf** [home-assistant/android#1109]
**Home Assistant Android version:**
v2.5.0-full

**Android version:**
version 11
Security Update: October 5, 2020
Play system update: September 1, 2020
Baseband version: g670-00067-200702-B-6648702
Kernel version: 4.9.223-g51 b9e1042e59-ab67221 74 #0 Thu Jul 30 10:57:45 UTC 2020
Build number: RP1A.201005.004

**Phone model:**
Google Pixel 3a

**Home Assistant version:**
0.116.4

**Last working Home Assistant release (if known):**
Unknown, I just started using this sensor on current version

**Description of problem:**
The Home Assistant Companion app "next_alarm" sensor shows the correct next alarm when the phone is unlocked.
When the phone is locked the next_alarm changes to the current time plus 10 minutes. The update happens immediately after phone is locked, and updates to the correct next alarm immediately after unlock.
When the phone is unlocked the next_alarm does not change to 'current time + 10 minutes' (I watched for about 5 minutes to see if the change occurred and it did not.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
Not applicable

**Additional information:**
The issue does not occur when I set next_alarm sensor settings allow list to "com.google.android.deskclock"

**Comment by dshokouhi** [comment]
> The issue does not occur when I set next_alarm sensor settings allow list to "com.google.android.deskclock"

This is not a bug because without setting an Allow List the sensor will pull in any and all alarm events that get sent to that API.  The entire reason for the allow list to avoid situations like this.

You probably have some other app setting the alarm time when the screen changes.  Check the `package` attribute to see which app is using the Next Alarm API that android provides.

**Comment by NobleWolf** [comment]
@dshokouhi Thank you for dealing with us users. 🙇  Turns out the package that causing the issue was the app Tasker. 🤦  If you hadn't mentioned checking the `package` attribute I wouldn't have noticed it, because it only shows Tasker for less than a second after unlocking the screen.

I hope this exchange will help other users who use Tasker and the next_alarm sensor in the Home Assistant Android Companion app.

**Comment by dshokouhi** [comment]
No problem :)

yea we knew about Tasker when this sensor was first added, just needed to get the setting added to remove it :)

https://github.com/home-assistant/android/issues/748
