### ISSUE TITLE
Default dashboard missing in Android app menu

### ISSUE THREAD

**Issue by katonage** [home-assistant/android#1112]
**Home Assistant Android version:**
2.5.0 full
**Android version:**
9 pkq1 miui
**Phone model:**
Redmi note 6.
**Home Assistant version:**
116.4

**Last working Home Assistant release (if known):**

**Description of problem:**
Im working with a few days old new ha install on rpi4, official image. I've left the default dashboard "overview" untouched (besides this default naming of these could be improved). I've created a new dashboard "dashboard" and moved it to the top menu element. This order of items were sometimes maybe not perceived by ha. Seemingly resulted in a not matching menu in the app. 
![Screenshot_2020-10-26-23-24-43-066_com android chrome](https://user-images.githubusercontent.com/36854755/97236271-0a23cc80-17e5-11eb-9cf7-38221093fcca.jpg)
![Screenshot_2020-10-26-23-24-10-888_io homeassistant companion android](https://user-images.githubusercontent.com/36854755/97236284-10b24400-17e5-11eb-8ad6-94c36bdc51de.jpg)

Problem: "overview" not reachable from the app. menu.

Than I changed order of menu elements in the web interface (chrome), same time logged in from the same phone , and then restarted the app. Menu didn't changed in app. Setting the menu order in the app shows the changed order (except for the "overview") 

![Screenshot_2020-10-26-23-42-03-693_io homeassistant companion android](https://user-images.githubusercontent.com/36854755/97236572-a8b02d80-17e5-11eb-8f98-de5cb4e31275.jpg)

but clicking Done got me back to exact the first state: original order, no overview. 

Should be some bug how app updates changes to menu items... 
Issue is annoying but not critical. 

**Traceback (if applicable):**

```

`

**Screenshot of problem:**
Attached some 

**Additional information:**
There is only one admin account, 
only admin not checked on dashboards, 
everything is on Lan.

**Comment by dshokouhi** [comment]
> Than I changed order of menu elements in the web interface (chrome), same time logged in from the same phone , and then restarted the app. Menu didn't changed in app. Setting the menu order in the app shows the changed order (except for the "overview")

This is because the front end stores things on a per device basis.  The app and chrome act as separate devices to the front end and therefore changing one will not reflect on the other.

If you only update it in the app does it work as expected?

**Comment by katonage** [comment]
What an immediate reaction! Large expensive software could do after you! 

You are right, I could edit and reorder concentrating only to the app. I also found that "overview" was not the default dashboard in the app hence it was not visible. 

I find it unintuitive to store the 'default' flag per device in the lovelace dashboards config, and in general I have concerns with this 'default' flag what does it means.
* first dashboard to load on boot 
* automatically generated dashboard 
* seen in the menu 

*I'd create a toggle in the config / lovelace to control autogeneration (read only dashboard layout) (global) 
*Menu presence should be (only) controlled in the menu editor (could be per device) 
*First dashboard to load: I would store the last viewed one for each device (per device). 
Like this the current 'default' dashboard would keep the same appearance in the config as standard ones, having 'admin only flag' too and receiving a massive warning before switching on autogeneration for an already edited dashboard. And not mixing per device and global config elements in the lovelace config panel. 
 
An another annoying wth :
Small device screen (phone) , menu closes automatically. Editing the menu, then clicking away closes the menu (being edited). Then you can't use the menu, and _nothing warns you about this lock_. Clicking Edit brings back the menu, Done restores normal operation.
But in the middle of this sequence I felt locked vigorously pressing the menu with no result, took me a minute before I realized I'm locked by the menu editing state. 
This behavior is consistent in the web and app too.

You solved one issue and created an another two :-)

**Comment by dshokouhi** [comment]
All of these issues are front end issues and not app issues.  We are just a webview to the frontend, as you even mentioned its consistent in web and app too.  You will probably want to open them with the front end team to discuss.

https://github.com/home-assistant/frontend/issues/new/choose

**Comment by katonage** [comment]
Thx. moving them there.
