### ISSUE TITLE
Stream zoom functionality

### ISSUE THREAD

**Issue by T-bond** [home-assistant/android#1117]
**Is your feature request related to a problem? Please describe.**
I have multiple camera streams with high resolution. The new exoplayer working correctly displaying the H.265 stream which is great, as it does not work in the browser.
The only remaining problem is that I can't zoom into the camera view, which makes the cameras almost useless, as I can't see the details.
I tried with the new  0.117.0 which enables zooming, but it only works in the browser.

**Describe the solution you'd like**
I would like to zoom to the stream components / camera live views.

**Describe alternatives you've considered, if any**
There is no alternative, as the browser can't play the H.265 stream, and the app can't zoom in.

**Additional context**
I also tried enabling zoom with:
```Kotlin
webview.settings.setSupportZoom(true)
webview.settings.builtInZoomControls = true
```
which zooms correctly, but the exoplayer layer won't follow the zoom.

**Comment by T-bond** [comment]
Functionality still needed.

**Comment by dshokouhi** [comment]
So looks like to support something like this similar to what iOS does we may need to add some scaling options to App Configuration to handle this.  Looking at Webview docs I think we may need to use:

https://developer.android.com/reference/android/webkit/WebView#setInitialScale(int)

For those seeing this issue please note this isn't just to zoom on a particular card or video stream, its to zoom into the entire HA frontend.

**Comment by T-bond** [comment]
I think it won't be the best solution, as you said it will zoom into the whole frontend, but if it works I am in!
I am a bit worried if it will only scale the webview it won't modify the canvas of the exoplayer, as it happened with my test:
```
webview.settings.setSupportZoom(true)
webview.settings.builtInZoomControls = true
```

Unfortunately I am currently still don't have enough time to investigate it further.
Also, if you missed there was some problem with the now removed zoom feature on iOS: https://github.com/home-assistant/frontend/issues/8192 if this will be implemented the same way, maybe it would be a good idea to check for the same issues.
And a similar issues is also open for the frontend: https://github.com/home-assistant/frontend/issues/6612
But I think this maybe has to be handled differently because of the exoplayer.

**Comment by conorlap** [comment]
@uvjustin any progress on this? Pinch to zoom for video feeds would be fantastic!

**Comment by dshokouhi** [comment]
Hey all we just had #2252 deployed and I think that will satisfy this feature request, could someone please try the latest beta found on github to see if pinch to zoom is what was needed here?

**Comment by conorlap** [comment]
@dshokouhi yessss!! Just tried it out, works perfectly so far! Will update if any bugs. Thank you, I love this feature!! 🥳

**Comment by T-bond** [comment]
Thanks everyone. It seems to be working perfectly. :)
<3
