### ISSUE TITLE
Widget update when screen on while not connected

### ISSUE THREAD

**Issue by engrbm87** [home-assistant/android#1120]
**Home Assistant Android version:**
beta-482-b97a69a
**Android version:**
10
**Phone model:**
OnePlus 6t
**Home Assistant version:**
0.117
**Last working Home Assistant release (if known):**

**Description of problem:**
Following PR #1115 every time the screen is unlocked while there is no connection to HA the entity widget shows 'null' and a toast notification is displayed saying: `unable to fetch data for configured entity`.
I recommend that the widget only gets updated when the screen turns on if there is a connection to HA. Otherwise it should keep the last value (perhaps with an indication that this is not up to date). As for the toast notification I don't recommend displaying it every time the screen turns on.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
We need a way to tell the users that we couldn't update the widget. If we remove the toast then they have no way knowing it failed. We also only store entity information to retrieve the data. We added a toast recently to tell users when there is a problem updating widgets. You should not see this error unless your HA server is unreachable. At which point the error is informative.

**Comment by engrbm87** [comment]
I understand that the error appears when HA server is unreachable. In case for example the phone is not connected to wifi or mobile data this error will show up every time the phone is unlocked. For me, I don't like to keep seeing a toast notification every time I unlock my phone.

**Comment by dshokouhi** [comment]
So the issue with the text coming in as null has always been there but is now more prominent since we attempt to update via the screen on event.  It looks we will have to store the state information to our local db in order to avoid this issue because widgets are write-only and we can't read from them before the update.  Once a widget is told to update it must provide an update.

Regarding the toast message I can make it show up only if an active network connection is present.  Then it will show up if it can't connect to HA. If HA is down for a long period of time then this error will continue to show.

**Comment by dshokouhi** [comment]
@engrbm87 just submitted a fix for when the network connection is not active, the error will still appear if HA is unreachable.  If we need to do any extra handling there then we will need to take that on as part of #1033

**Comment by dshokouhi** [comment]
@engrbm87 would you find it useful if widgets updated when the network connection is restored? Trying to find ways to make them feel more up to date :)

**Comment by engrbm87** [comment]
That would be great. But I think it should only update if there is a successful connection to HA. Otherwise, if network is back but no connection to HA then just show a notification.
Once connection is established with HA show another notification that connection is back and update the widget.

**Comment by theCheek** [comment]
I'm getting this toast message even though I don't have any widgets installed. Running v3.0.0-full on Android 11 (Pixel 3XL) if it helps.

**Comment by EdwinekVG** [comment]
Same as with @theCheek here, I'm getting these messages all the time and I don't even have a widget on my home screen. It looks like I even get two in very quick succession.

This is extremely annoying.

Maybe interesting to know that I did have a widget until this morning, but removed it before updating to 0.117.5. I've tried rebooting and deleting cache, but that didn't make any difference.  I'm running v3.0.0-full on Android 11 (Pixel 4 XL).

**Comment by JBassett** [comment]
@theCheek and @EdwinekVG  if you go into App Configuration -> Manage Widgets do you see widgets listed there?  If you don't have any widgets this should be empty, if you see records open and delete them.

**Comment by theCheek** [comment]
> @theCheek and @EdwinekVG if you go into App Configuration -> Manage Widgets do you see widgets listed there? If you don't have any widgets this should be empty, if you see records open and delete them.

Thanks for this. Yes I had one widget listed there that I must have added to my home screen a while back but then removed. The toast seems to have stopped now so all good.

**Comment by EdwinekVG** [comment]
> @theCheek and @EdwinekVG if you go into App Configuration -> Manage Widgets do you see widgets listed there? If you don't have any widgets this should be empty, if you see records open and delete them.

Thanks for that, I never knew. There were three switches and two entity widgets, I've deleted them now. I hope that's enough to solve this.

**Comment by teemujalonen** [comment]
I'm connecting to HA using zerotier, and for some reason I was getting these toast messages every time when the screen was unlocked. So it seems that this update made widgets unusable for me. I'm ok with that, but I don't think that it was the intention for this change.

And why doesn't the toast message say that the message comes from HA? Suddenly these started showing up, and I didn't know which app they are coming from

**Comment by RonSpawnson** [comment]
Piling on - this is super annoying for me - it constantly draws this warning toast over my other applications over and over and over while I'm trying to use my phone. I'm debating removing the widgets entirely as this is unusable as-is sadly.

**Comment by teemujalonen** [comment]
Yeah, I removed my widgets already. Toast is so annoying
