### ISSUE TITLE
Websocket connections get never closed

### ISSUE THREAD

**Issue by SigmaPic** [home-assistant/android#1125]
**Home Assistant Android version:** 2.5.0-full

**Android version:** 9

**Phone model:** Xiaomi Mi A1

**Home Assistant version:** 0.115.3

**Last working Home Assistant release (if known):**

**Description of problem:**

The bug affects the websocket_api integration.
The bug only happens when I use the mobile app (no issue with the browser).

0. Nobody is connected => sensor.websocket_api = 0
1. I open the mobile app => sensor.websocket_api = 1
2. I press the back button from my Android phone => The app goes in background but sensor.websocket_api stay to 1. We can think that since app is in background, connection is still alived but,
3. I open again the mobile app by pressing on the icon => sensor.websocket_api = 2

You can do that several time and the number of connected client will increase every time.

The issue is that there is no timeout. The heartbeat of websocket connection never timeout. This means that the phone continue to respond to all hearbeat from all connections.

[https://github.com/home-assistant/core/blob/dev/homeassistant/components/websocket_api/http.py](https://github.com/home-assistant/core/blob/dev/homeassistant/components/websocket_api/http.py)

If I put the phone in plane mode, the connection get closed after the configured heartbeat of 55s.
`wsock = self.wsock = web.WebSocketResponse(heartbeat=55)`

According to this, I think the issue comes from the app.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
The connection closes after 5 minutes of inactivity.

**Comment by SigmaPic** [comment]
I don't have this behavior.
Connections never close on my phone.
Where is implemented this 5 minutes timeout ?

**Comment by dshokouhi** [comment]
Do you have picture entity cards as a live view card on your dashboard?

The 5 minute timeout is implemented by the HA frontend, check your user profile in the app for the "Automatically close connection" toggle

**Comment by SigmaPic** [comment]
No picture entity cards. But I have an automation that trigger a refresh of my platforms every seconds when at list one client is connected.

"Automatically close connection" is enabled in my profile.

Maybe it's an issue with HA config ?
When you say implemented by HA frontend what do you mean?
Where is implemented this timeout?

I have 4 clients since this morning. It never timeout.

**Comment by dshokouhi** [comment]
You need to check that toggle on each device as the setting is per device/app. When I say implemented by the frontend I mean they are the ones who take care of closing the connection and opening it when you connect to HA.  The app itself we are just a webview to the frontend.

**Comment by SigmaPic** [comment]
I have only one smartphone with HA. So, no issue there.

May you tell me where is implemented this timeout in HA front end.
I would like to instrument the code to check if the timeout occurs.

What I already checked, is the timeout of 55 second of the websocket implemented here:
[https://github.com/home-assistant/core/blob/dev/homeassistant/components/websocket_api/http.py](https://github.com/home-assistant/core/blob/dev/homeassistant/components/websocket_api/http.py)

While my smartphone has internet, this timeout doesn't occurs. In plane mode, it occurs.

So, I would like to check the timeout of 5 minutes you talk about

**Comment by dshokouhi** [comment]
check the code in this repo: https://github.com/home-assistant/frontend  I am not familiar where it is located

**Comment by SigmaPic** [comment]
I just tried again. Connections are not closed.

**Comment by dshokouhi** [comment]
The app does not create the websocket connection, we don't have one yet.  That is all handled by frontend.  You should probably open an issue over there as we can't correct that here.

**Comment by SigmaPic** [comment]
Ok I see what you mean. I will open a bug there.
