### ISSUE TITLE
HA App doesn't always fill in details in geocoded_location

### ISSUE THREAD

**Issue by i00** [home-assistant/android#1136]
## The problem

With the app; it creates _geocoded_location entities; on the odd occasion these don't have the information filled in fully:
![image](https://user-images.githubusercontent.com/1435262/97830954-5fe30200-1d1a-11eb-9634-9bd6309c2f72.png)

I can sort of understand that the service etc may not be returning this info correctly; but regardless the latitude and longitude should be set.

## Environment

- Home Assistant Core release with the issue: 0.117
- Last working Home Assistant Core release (if known): ?
- Operating environment (OS/Container/Supervised/Core): Container
- Integration causing this issue: Mobile App
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/mobile_app/

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by dshokouhi** [comment]
Per the docs from google on the geocoder API:

```
The amount of detail in a reverse geocoded location description may vary, for example one might contain the full street address of the closest building, while another might contain only a city name and postal code. 
```

https://developer.android.com/reference/android/location/Geocoder

So basically not all data is guaranteed, the app will send whatever we get if we get it.  For GPS coordinates the `device_tracker` is the entity you should be using, it also updates a lot faster.

Closing as this is not something we can fix.
