### ISSUE TITLE
Add option to never sleep device while HA app is open (active or inactive)

### ISSUE THREAD

**Issue by silviudc** [home-assistant/android#1142]
**Is your feature request related to a problem? Please describe.**

For my wall mounted tablets I use a combination of Fully Kiosk to have an always on display (that dims the screen after 30 seconds) and Ariela to send the tablet battery info to HA so that I can toggle the charging on and off.
Sometimes these apps have issues.

**Describe the solution you'd like**

I would like to be able to use the HA companion app to both display the HA UI and also send tablet sensor data back to HA without relying on third party apps (the sensor part is already a feature so no need to do anything there)

**Describe alternatives you've considered, if any**
Fully Kiosk/Ariela combination as work around.

**Additional context**

The current app would need:
- An option to keep the tablet screen always on and never allow the device to sleep

**Comment by skynetua** [comment]
It would also require some kind of motion detection (like capturing photos by frontal camera) to enable screen and some mechanism to control it from ha server (probably notifications).

**Comment by silviudc** [comment]
Split into two tickets now and created #1144 for the second part.
