### ISSUE TITLE
Excessive location requests on latest beta

### ISSUE THREAD

**Issue by gregg098** [home-assistant/android#1146]
**Home Assistant Android version:**
beta-492-df47e80-full

**Android version:**
10

**Phone model:**
Samsung Galaxy S10+

**Home Assistant version:**
0.117.4

**Last working Home Assistant release (if known):**
N/A - All of them

**Description of problem:**
I noticed the last few days that my location icon was always on at the top of the screen. I went into settings so it showed me last apps to request location and started force closing them to see which one would make the location request go away. It went away instantly after force closing the Home Assistant companion app. I tried this 3 different times yesterday since it keeps coming back and it was the app every time

**Traceback (if applicable):**

```
None to show
```

**Screenshot of problem:**

**Additional information:**
I saw some of the new accuracy and minimum duration settings for location, but I dont think it will matter. I'm mostly home each day and my location isn't changing. If I bump the minimum interval out, it will make it way slower when I go out.

**Comment by dshokouhi** [comment]
What happens if you disable the single accurate location sensor by itself? Do you still see the location lock happening?

**Comment by gregg098** [comment]
> What happens if you disable the single accurate location sensor by itself? Do you still see the location lock happening?

I just disabled it and the active location request did not stop. I went ahead and left it disabled and force closed the app and re-opened. Ill test today and report back. Thanks.

**Comment by dshokouhi** [comment]
> I just disabled it and the active location request did not stop.

Disabling the sensor does not stop the current request for this sensor, it either needed to be force stopped or the existing request would need to finish processing.  One thing to keep in mind is that this is the actual sensor that gets included in periodic updates and its also used when `message: request_location_update` is sent to the device.  So it works independently from the other 2 sensors.

**Comment by gregg098** [comment]
Turning off the single accurate location sensor did stop the location updates all the time. I can't test much beyond this right now though.

**Comment by dshokouhi** [comment]
You are still getting location reports correct? Just not seeing the location lock on the device?  I have also turned off the same sensor to perform a similar test.

**Comment by gregg098** [comment]
It appears so. My app sensors say updated a few minutes ago. I just haven't left home today to know how an actual location change is affected.

**Comment by dshokouhi** [comment]
so zone location tracking only sends updates when you enter/exit a zone, you can test that by force stopping the app and opening it up again and you can see the zone entry event: https://companion.home-assistant.io/docs/integrations/app-events

background location sets up a request at 60 second intervals (fastest is 30 seconds) with a max wait for 3 minutes....we also dont send an update if location remains the same for 15 minutes....when you leave your actual location you should see it change but at home it can seem to be slightly random intervals.

Single accurate location gets called with the sensor updates, the location command I mentioned up above and also when we dont get a location whose accuracy meets the requirement.

have you adjusted any of the other location sensor settings or left them on the default?

**Comment by gregg098** [comment]
Thanks for the info. Have not changed any settings other than what's discussed here. It was just surprising to see the GPS location on screen every time I looked at my phone. So maybe we need to look at if this setting is turned on by default? 

Ill mess around today to see if zones work OK.

**Comment by gregg098** [comment]
Everything seemed to work OK with the single accurate location sensor disabled and my phone is not constantly trying to get my location. I think that sensor should just be disabled by default if its not already or some kind of warning that it will consume battery. I've been on so many versions of the app I dont know what the defaults are, but I know this was enabled automatically at some point in updating.

**Comment by dshokouhi** [comment]
@gregg098 how many sensors do you have enabled? In particular do you have the Interactive sensor enabled?

**Comment by gregg098** [comment]
> @gregg098 how many sensors do you have enabled? In particular do you have the Interactive sensor enabled?

Right now everything is enabled except for single accurate location sensor. Seems to work as expected now. The location updates seemed to just become an issue in the last beta update.

**Comment by dshokouhi** [comment]
ok thanks for confirming. As this sensor is used for `message: request_location_updates` I don't think keeping it disabled by default makes sense but possibly we need to make including location updates with sensor updates optional.  We do make use of this sensor when the app detects an inaccurate report so its logic is useful in cases, just not with sensor updates such as interactive that reports when the screen turns on/off.
