### ISSUE TITLE
Action button to open a video in the media folder

### ISSUE THREAD

**Issue by engrbm87** [home-assistant/android#1148]
**Is your feature request related to a problem? Please describe.**
With the release of the Media browser feature, is there was to directly open a video file from the notification using an action button? This would be useful in case recordings from cameras are stored in the media folder.

**Describe the solution you'd like**
The option to configure an action button that opens a video file stored in the media folder directly on the mobile.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
So I don't know if this is exactly what you are looking for but this should now be doable using existing features and the new `command_activity` notification command

https://companion.home-assistant.io/docs/notifications/notification-commands#activity

Try to use this command following this guide from google to see if it will launch a video, may need some trial and error and research to get it right.

https://developer.android.com/guide/components/intents-common#Music
