### ISSUE TITLE
Tons of null values in Android 11's power menu

### ISSUE THREAD

**Issue by electrofloat** [home-assistant/android#1150]
**Home Assistant Android version:**
3.0.0-full

**Android version:**
11

**Phone model:**
Pixel

**Home Assistant version:**
Home Assistant 0.117.1

**Last working Home Assistant release (if known):**
-

**Description of problem:**
The new HA power menu configuration shows a lot of 'null' values

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
https://imgur.com/a/cznkBmr

**Additional information:**

**Comment by electrofloat** [comment]
None of my entities (according to developer tools->states) are in restored state.

Is there a quick and easy way to export the list of current entities I have? (so that I can attach it to here)

**Comment by JBassett** [comment]
@electrofloat do you have scenes, switches, scripts, etc that don't have a `friendly_name` attribute?

**Comment by electrofloat** [comment]
I don't have any scenes or scripts, and all of my switch entities have a 'friendly_name' attribute.

**Comment by dshokouhi** [comment]
can you check the rest of the supported domains listed: https://companion.home-assistant.io/docs/integrations/android-power-menu please?

**Comment by dshokouhi** [comment]
Scratch that request, figured it out :) thank you for reporting!

**Comment by electrofloat** [comment]
I have a ton of input_boolean, and input_numbers without friendly_name. Probably that is the issue.

**Comment by dshokouhi** [comment]
That is exactly the reason, after the linked PR is merged you will see the entity ID in those cases
