### ISSUE TITLE
Alarm clock state is unavailable if alarm clock is off.

### ISSUE THREAD

**Issue by SPEC1AL1ST** [home-assistant/android#1152]
**Home Assistant Android version:**
3.0.0-full
**Android version:**
10
**Phone model:**
Redmi note 8 pro
**Home Assistant version:**
0.117.4
**Last working Home Assistant release (if known):**
-
**Description of problem:**
Alarm sensor when the alarm is not turned on - the sending state "unavailable". But must send - "none" or "not set"

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![d1cf3-clip-18kb](https://user-images.githubusercontent.com/8482645/98404885-078e6600-2074-11eb-95b2-011692dace7c.png)
**Additional information:**

**Comment by dshokouhi** [comment]
This is to be expected as was also documented on our companion site: https://companion.home-assistant.io/docs/core/sensors#next-alarm-sensor

The value from the API actually comes in as `null` as it would if the alarm call would fail so we set the state to `unavailable` as it does not exist and therefore cannot be read.  This is part of the android system.

this is also a `timestamp` entity and we should not send a string for it.

https://developers.home-assistant.io/docs/core/entity#generic-properties

**Comment by SPEC1AL1ST** [comment]
> This is to be expected as was also documented on our companion site: https://companion.home-assistant.io/docs/core/sensors#next-alarm-sensor
> 
> The value from the API actually comes in as `null` as it would if the alarm call would fail so we set the state to `unavailable` as it does not exist and therefore cannot be read. This is part of the android system.
> 
> this is also a `timestamp` entity and we should not send a string for it.
> 
> https://developers.home-assistant.io/docs/core/entity#generic-properties

But now the system tells me that some kind of sensor is not available, so you can't leave it either.
