### ISSUE TITLE
Widgets show ERROR since App 3.0.0

### ISSUE THREAD

**Issue by membersound** [home-assistant/android#1158]
**Home Assistant Android version:**
3.0.0-full

**Android version:**
9

**Phone model:**
Huawei P10

**Home Assistant version:**
0.117.2

**Last working Home Assistant release (if known):**

**Description of problem:**
I had several widgets on my home screen before. Now they disappeared.
When I recreate them, I only see an "F E H" text on the widget, with probably means "ERR(or)".

My widgets are mainly scripts, switches or rest commands, like:
`script.shutter_all_open`
`rest_command.fountain_toggle`
`switch.toggle`

None of them work when recreating.

**Screenshot of problem:**

![Screenshot_20201107_113508](https://user-images.githubusercontent.com/5269630/98438863-5cba8e00-20ed-11eb-8518-c6f17f756001.jpg)

**Comment by traviz-pl** [comment]
Have the same issue.

**Comment by dshokouhi** [comment]
Can you share a screen shot of the widget configuration screen when you edit a widget with the issue?

**Comment by traviz-pl** [comment]
> Can you share a screen shot of the widget configuration screen when you edit a widget with the issue?

Here u are. 
![Screenshot_20201107_164922_io homeassistant companion android](https://user-images.githubusercontent.com/63699757/98445720-7d98d880-2119-11eb-80f5-820ce24d42b0.jpg)
![Screenshot_20201107_165036_com huawei android launcher](https://user-images.githubusercontent.com/63699757/98445722-825d8c80-2119-11eb-90b3-3a42ca24d487.jpg)

**Comment by andriej** [comment]
Whats that "," in entity namae? Have you tried without it?

**Comment by traviz-pl** [comment]
It shows up automaticaly when the entity is chosen from the list.

I accidentally reboot my phone and now the newly added widgets work as before HA app upgrade. Hope it will also work for @membersound.

**Comment by membersound** [comment]
Nice catch, that also fixed it for me.
Though I'm not sure whether to close this issue, because it then is clearly a bug?

**Comment by dshokouhi** [comment]
I think i see the cause of the issue, does this happen to newly created widgets or just existing ones you guys are editing?

**Comment by traviz-pl** [comment]
@dshokouhi in my case all old widgets gone after HA app update so I wanted to create a new ones. Then I found out that they don't work as usually. After phone reboot I have created a completely new widgets and now all are working correctly.

**Comment by dshokouhi** [comment]
@traviz-pl ok that makes sense and should be expected due to the breaking change. 

@membersound is that the same case for you too? or did the issue start after editing a widget?

**Comment by membersound** [comment]
All my old widgets are gone. And when recreating widgets I got that issue.

**Comment by dshokouhi** [comment]
did you make sure to delete the old widgets from the manage widget screen?

**Comment by PoVPoV29** [comment]
Hello,
Same issue and I did delete old widget. I don't have the issue when I am connected in the local network. Same for you?

**Comment by PoVPoV29** [comment]
The issue doesn't appears for some time after laughing the app. Same thing for you?

**Comment by PoVPoV29** [comment]
Error message when I click on widgets : "unable to send service call" Is it the same issue for you ?

**Comment by dshokouhi** [comment]
@PoVPoV29 that error shows up when the widget is unable to successfully send the service call to your server.
