### ISSUE TITLE
Show a breaking changes prompt or notification upon updating, if needed

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#1162]
**Is your feature request related to a problem? Please describe.**
We should try to better inform users about breaking changes so they know what is expected of them.  If possible, show the whole change log for the current version but breaking changes should be highlighted at the top.  Although we have a blog post detailing this, not all users see it so its a better experience to inform them some how.  We can even consider a notification as not all users will open the app after updating.

**Describe the solution you'd like**
As PR's come in we should mark them as a breaking change (if required) so we can identify them easily.  We should find a good way to prompt users about this.  I think a notification might make the most sense, but an in app prompt can also work to ensure they have seen it.  We should also include the blog post link in the play store release notes.

**Describe alternatives you've considered, if any**
The alternative is to expect all users will read either github change log or the blog post.

**Additional context**
I see users having issues in the forums, reddit and probably eventually on discord.  The better we can handle the situation the less upset people can be.

**Comment by dshokouhi** [comment]
This looks like it might be a viable library to use: https://github.com/AppDevNext/ChangeLog might be able to use a github action to pull in the changelog on each commit :)

**Comment by jrial** [comment]
Still an issue.
