### ISSUE TITLE
Notification History Enhancement

### ISSUE THREAD

**Issue by stipe76** [home-assistant/android#1165]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

It would be nice to render the HTML in the Notification History tab. Refer uploaded image

Cheers

![Screenshot_20201108-184708](https://user-images.githubusercontent.com/32793572/98459879-20715580-21f3-11eb-9a95-aa12fb763670.jpg)

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
Might be doable with: https://developer.android.com/reference/android/text/Html#fromHtml(java.lang.String,%20int)

Will need to test and see.
