### ISSUE TITLE
Increase Notification Volume when using alarm_stream_max without TTS

### ISSUE THREAD

**Issue by LucidityCrash** [home-assistant/android#1166]
Currently alarm_stream_max only increases the alarm volume when using TTS, I'd have thought having this happen for simple audio notifications would also be nice.

**Comment by dshokouhi** [comment]
So the reason why this works for TTS and not normal notifications is because for TTS we get notified when the speech starts and stops. We don't get that with a normal notification. The only way to proceed here is to introduce a command where users can adjust the volume on their own.

**Comment by LucidityCrash** [comment]
> Edit: also what happened to the feature request template?

sorry ... when I rased this I wasn't given an option to select "enhancement request" ... but when I click on new issue just now I get a choice of a bug or an enhancement ... very strange
