### ISSUE TITLE
Current speed sensor

### ISSUE THREAD

**Issue by stipe76** [home-assistant/android#1170]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Is there a possibility to add a current speed sensor? I'm looking to build a driving interface and would like to display the current speed, along with the geocoded location. 

Thanks

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
This is already an attribute of the `device_tracker` 

https://companion.home-assistant.io/docs/core/location#entity-attributes

You will need to setup a template sensor for it.
