### ISSUE TITLE
Power menu controls can no longer be added

### ISSUE THREAD

**Issue by ingenium13** [home-assistant/android#1172]
**Home Assistant Android version:** beta-509-4255ee1-full

**Android version:** 11

**Phone model:** Pixel 4 XL

**Home Assistant version:**

**Last working Home Assistant release (if known):** 3.0.1. Current beta broke it

**Description of problem:** It's not possible to add power menu controls. It tries to load them from Home Assistant and fails. 

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![Screenshot_20201108-202924](https://user-images.githubusercontent.com/3280458/98491187-0a1ec600-2202-11eb-8840-c5d486e37872.png)
![Screenshot_20201108-202514](https://user-images.githubusercontent.com/3280458/98491192-0ee37a00-2202-11eb-817d-ec0a6366eb43.png)

**Additional information:**

**Comment by dshokouhi** [comment]
Did the app crash when this happened? or was it still open? If you reboot your phone does it correct the issue?

**Comment by ingenium13** [comment]
The app doesn't crash. I'm able to switch back to it and remain on the same screen where I left off (didn't reload or anything).

I rebooted but the issue persisted.

**Comment by dshokouhi** [comment]
Do you have any errors in your HA logs when this happens? The only change in the beta for power menu controls was to default to the entity ID when the friendly name was not provided.  We may need to see if your entity ID's have any issues or if any restored ones would need to be deleted from your end.  The only other thing I can think of is maybe something got corrupted and in that case you'd need to start fresh: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by ingenium13** [comment]
No errors were in HA. 

I un-enrolled from the beta, uninstalled Home Assistant, and followed the linked instructions to remove the integration. I set it up again and added power menu controls. Then I re-enrolled in the beta and it seems to work now (I can load the list of lights and such and add new ones, and all but one function as expected).

There is another bug that I've had with the power menu controls, which I can open as a separate issue if you prefer. I have 3 identical lights added as power menu controls (z-wave dimmers, all the same model, connected via zwave2mqtt). Two of them work fine as power menu controls. The third consistently doesn't work right. When it's off, the status updates and shows it as off, and I can turn it on. At that point though, it just continues showing as "Off" and never updates. Tapping the button again does nothing (ie, the light doesn't turn off). If I exit the power menu and re-enter it, that light is stuck at "Loading..." and the button does not function. If I open the Home Assistant app, it shows the light as being on, and I can turn it off. So it's just the power menu button that's affected. When I turn it off again, then the status will update to "Off" in the power menu. So there is something with that light being "On" that prevents it from updating in the power menu, but not in the app itself. There is nothing in the Home Assistant logs when this happens, and the app itself has no problem showing the correct status. It's just the power menu button.

I've had the above issue since 3.0.0, and it's present in 3.0.1 and the current beta.

**Comment by dshokouhi** [comment]
You should see the state of the entities updating every 5 seconds (if not immediately) on the power menu screen, are you waiting those 5 seconds to see if its updating as expected? I have a few jumpy zwave lights myself so normally waiting those few seconds shows the correct state.  All we do is query HA for the state and display `on` or `off`.  You can also check the states that the entity changes to that might give us a hint too.  I havnet seen any lights get stuck on "loading..." but from time to time i have to wait a few extra seconds for them all to finish loading.  Sometimes its immediate and sometimes there is a delay.

**Comment by ingenium13** [comment]
Yeah I've waited a while. With the beta it's actually started doing it with another light too. The third one seems to be OK.

I made a video showing it. The HA app itself updates fine and always shows the correct status. It's just the power menu button that has the issue.

https://drive.google.com/file/d/1kDfQg5bnX2Jk2Lp4YCiOPzADhw0ZyRuW/view?usp=sharing

**Comment by dshokouhi** [comment]
Ok I dont want to confuse things here based on all the previous troubleshooting, could you please create a new issue and attach the video? Also please show us the state and attributes of the device when they are `on` and `off` and let us know if there are any other states it changes to when you turn them on and off.  The more info about the lights and the behavior the more helpful it will be, the model of the lights can be useful to.

**Comment by ingenium13** [comment]
I think I figured it out. It's only when the lights are at full brightness that it has the issue. If I dim them then it works. I'll write up a new bug report now.
