### ISSUE TITLE
Show Caller ID in HA

### ISSUE THREAD

**Issue by Okosotthon** [home-assistant/android#1173]
This idea is based on GSM gate openers.

When you call a number and the module recognizes you it will open the gate for you or anything.

Is it possible to somehow gather the caller id information fron an Android phone for example?

I've seen solutions with usb modems, but I have a ton of android devices wich I could use for that.

Thans in advance for your reply.

**Comment by dshokouhi** [comment]
Can you try the new Last Notification sensor and see if the data provided by your phone app is what you are looking for?

**Comment by haim-b** [comment]
The notification does show the caller name or ID, but there's no guarantee when it will be updates, and when using automation the incorporates the caller ID, the last notification cannot be trusted.

**Comment by dshokouhi** [comment]
Last notification updates anytime a notification gets posted to the status bar, thats about as trustworthy as it can get.
