### ISSUE TITLE
Add current time/timezone sensor

### ISSUE THREAD

**Issue by FuzzyMistborn** [home-assistant/android#1174]
**Is your feature request related to a problem? Please describe.**

Not a "problem" but something I'd like added to better allow some automating.

**Describe the solution you'd like**

A sensor that has the phone's current time and/or timezone.  Having one for current time as well as a separate sensor for timezone would be handy.

**Describe alternatives you've considered, if any**

**Additional context**

I'd like this to combine with the last_alarm sensor.  I control my phone alarm via HASS, and sometimes set an earlier alarm than my "normal" alarm, so I don't want my "normal" alarm reset until after that time has passed.  IE i set an alarm for 3am but my normal alarm is 6, I don't want to wake up at 3 and have my 6am alarm turned back on until after 6am has past).  I worked around this by having a reset at a later time of the day, but that's tied to my current timezone.  If i'm traveling there's the issue of timezones potentially screwing things up, so having the phone's current timezone/time would be useful.

**Comment by FuzzyMistborn** [comment]
#1182 adds the timezone, I was also looking for a sensor with the actual local time as well if that's possible.

**Comment by JBassett** [comment]
Due to how we we have to update the time sensor we won't be adding a current local time.  You should be able to derive the devices local time in Home Assistant by using the time zone information.

**Comment by FuzzyMistborn** [comment]
Understood. Thank you.
