### ISSUE TITLE
Some push notifications are delayed up to 10 min but Chrome push notifications are received immediately

### ISSUE THREAD

**Issue by dnedeltchev** [home-assistant/android#1175]
**Home Assistant Android version:**
3.0.1
**Android version:**
10
**Phone model:**
OnePlus 7T
**Home Assistant version:**
4.15
**Last working Home Assistant release (if known):**

**Description of problem:**
Some push notifications are delayed by up to 10 min. See attached image of one example. I am not sure when this started but I picked it up probably in the last month or so. I thought it was my device so I configured another Android device and same thing. I configured an iPhone and no problems there. Then I enabled Chrome push notification on my Android to compare with the app notifications and I noticed this experience. App notifications when they get relayed the Chrome notifications are spot on. What I have noticed is that when I unlock my phone, all delayed notifications come through. I have turned off all battery optimisations, I have turned off disconnecting from host, I have reinstalled the app - no luck. So I have switched my Android to Chrome push notifications as currently I cannot rely on app notifications. My setup is as follows
Smartthings hub for the battery, non-repeating sensors like Xiaomi door, motion, temperature sensors and a Pi4 with zzh running latest zigbee2mqtt which has all the powered devices like lights, power plugs, etc. But since Chrome push is OK I don't think it's the setup?
All components have the latest software versions apart from the zzh firmware which was released a few days ago but I have not come round to doing that as I am struggling to find time to take down the zigbee network.
**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/60453167/98564057-ced4d380-22a3-11eb-8c0d-5448f5f86bbf.png)

**Additional information:**

**Comment by dshokouhi** [comment]
please share yaml examples of what you are trying

**Comment by dnedeltchev** [comment]
Here is the automation that I have for the front door. The Chrome push is immediate, every time. While the app push come in late as per screenshot. Does this help?


alias: Notify front door open
description: ''
trigger:
  - type: opened
    platform: device
    device_id: xxxxxxxxxxxxxxxxxx
    entity_id: binary_sensor.front_door_contact_sensor_contact
    domain: binary_sensor
condition: []
action:
  - data:
      message: Front door open
    service: notify.mobile_app_oneplus_7t
  - service: notify.mobile_app_iphone
    data:
      message: Front door open
  - service: notify.mobile_app_oneplus_5
    data:
      message: Front door open
  - service: notify.hassio_oneplus_7t
    data:
      message: Front door open (Chrome)
mode: single

**Comment by dshokouhi** [comment]
Your delay is caused by not making use of `ttl` and `priority` parameters in your automation.  Please check the companion docs on critical notifications and follow the android examples to see how it is done:

https://companion.home-assistant.io/docs/notifications/critical-notifications

Here is one example:

```
message: test
data:
  ttl: 0
  priority: high
