### ISSUE TITLE
App freezing only navigation

### ISSUE THREAD

**Issue by cbear92** [home-assistant/android#1181]
**Home Assistant Android version:**
3.0.1-full

**Android version:**
11

**Phone model:**
Pixel 3a

**Home Assistant version:**
Home Assistant Core
0.117.5 (states 0.113.3 in configuration->info in app)

**Last working Home Assistant release (if known):**

**Description of problem:**
App has been freezing in odd way since the newest so update (I think). Navigation through scrolling doesn't work. You can go back via the phones back option, but the burger icon does not elicit any response. Some things can still be interacted with, e.g. typing in template. Webview does not freeze. Resolution is only upon closing and relaunching app. 

My HA version (0.113.3) was a bit old so I updated to latest version (0.117.5), but this has not fixed the issue. On a different but possibly related note, within the app/webview the HA version listed is the old version and not the newer version. 

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
First check that Android system webview is up to date. Then try https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by cbear92** [comment]
> First check that Android system webview is up to date. Then try https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app
Thanks for having a crack at it :) 

Well the front-end is not up to date according to the front-end, same as the hass version. It certainly doesn't look any different whatsoever from when it was on HA 0.113.3. Via pip I installed the latest version of the front-end, but this doesn't seem to help either. 
I did follow the steps in the provided link which did not solve the issue.

**Comment by dshokouhi** [comment]
Check in chrome for android, do you see the same stuff there?  It sounds like your upgrade did not go through if you started fresh and still see the old install stuff.  HA 0.117 has the new header too so it should be immediately apparent.  Double check that all custom cards and integrations are fully up to date too.

**Comment by cbear92** [comment]
Yeah I checked via mobile browser which is what made me dubious as the app being at fault. 

I think I have found the issue though. I have multiple installations of python and pip, and I have updated HA in pretty much every one now but the one I needed. I am not using docker or a venv so this one is on me for sure.
