### ISSUE TITLE
Launch Companion App to specific view

### ISSUE THREAD

**Issue by stipe76** [home-assistant/android#1195]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I'd like to launch the Companion App to specific view depending on a variable in Tasker. The current option is to launch the app directly. Can we add the ability to launch to specific view? This is what the action requires in Tasker..

![Screenshot_20201114-122317](https://user-images.githubusercontent.com/32793572/99135170-21800800-2675-11eb-854e-acb43d544a67.jpg)

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
I don't think we will be providing a solution for Tasker only on this.  This would probably be a notification [command](https://companion.home-assistant.io/docs/notifications/notification-commands) that will just launch the webview based on the provided data in the notification.  It would function very similar to `clickAction` and actionable notifications with the exception of no user intervention required it will just launch the app to the view upon receiving.

**Comment by stipe76** [comment]
Any working solution would be much appreciated. This one sounds perfect
