### ISSUE TITLE
Motion detection screen turn on

### ISSUE THREAD

**Issue by ybjlus** [home-assistant/android#1196]
**Is your feature request related to a problem? Please describe.**
When the app is on a wall mounted tablet, have the functionality to turn the screen on when motion is detected through the front cam. 

**Describe the solution you'd like**

Turn screen on when motion is detected through the front cam. 

**Describe alternatives you've considered, if any**

Fully kiosk browser, but I like to switch to the native HA companion app

**Additional context**

**Comment by rwarner** [comment]
Curious what the code would be required to implement issuing a screen turn on.

Saw this here, that might be relevant:

```
PowerManager powerManager = (PowerManager) context.getSystemService(context.POWER_SERVICE);
PowerManager.WakeLock  wakeLock = powerManager.newWakeLock(PowerManager.FULL_WAKE_LOCK | PowerManager.ACQUIRE_CAUSES_WAKEUP | PowerManager.ON_AFTER_RELEASE, "appname::WakeLock");

//acquire will turn on the display
wakeLock.acquire();

//release will release the lock from CPU, in case of that, screen will go back to sleep mode in defined time bt device settings
wakeLock.release();
```

With the permission `<uses-permission android:name="android.permission.WAKE_LOCK"/>`

https://stackoverflow.com/questions/30090589/turn-on-screen-programmatically-on-android

**Comment by StephenBrown2** [comment]
Perhaps fullykiosk browser is all that's needed?
Ref: https://www.reddit.com/r/homeassistant/comments/jw6g9m/now_lets_wall_mount_this_thing/gcph9yw/

**Comment by rwarner** [comment]
Was referenced as an alternative, but I agree with the OP would be helpful to utilize the app directly to interface with HA on the tablet:

```
Describe alternatives you've considered, if any:

Fully kiosk browser, but I like to switch to the native HA companion app```

**Comment by healeydave** [comment]
+1 for this.
I am currently using Fully Kiosk Browser but every day I have to turn the power off on the charger to a Fire 10 wall mounted tablet to get the screen back on because it won't wake from the camera or tapping on the screen. Simply flicking the switch to the adapter so the tablet goes to battery for a second before restoring the power seems to work but it shouldn't do this.

I haven't figured out if this is a problem with Fully Kiosk or just android in general (as this is my first android tablet simply for cost). Full screen in the Home Assistant app is just as good as Fully Kiosk except I can't take the screen by walking up to it or by tapping on the green with the HA app.

**Comment by jumate** [comment]
+1 for this.

**Comment by tomfrissen** [comment]
If this could be part of the companion app that would be awesome!

**Comment by R5fan** [comment]
+2 for this.
Although I do not want it triggered by the camera, I just want a method to turn on the screen whenever my lights are on, or when motion is detected by my PIR sensors.

For now, I do this with wallpanel. But wallpanel doesnt support a lot of useful things that companion does. It would be nice if I could get away using just one app that does it all.

So to please both OP and me, I would suggest a new sensor that triggers on a camera motion, and an independent method to control the screen. Then anyone can combine those as they see fit with an automation.

**Comment by dshokouhi** [comment]
> +2 for this.
> Although I do not want it triggered by the camera, I just want a method to turn on the screen whenever my lights are on, or when motion is detected by my PIR sensors.
> 
> For now, I do this with wallpanel. But wallpanel doesnt support a lot of useful things that companion does. It would be nice if I could get away using just one app that does it all.
> 
> So to please both OP and me, I would suggest a new sensor that triggers on a camera motion, and an independent method to control the screen. Then anyone can combine those as they see fit with an automation.
> 
> BTW, I think wallpanel supports motion detection via the camera, but when I last tried it, I found it to use a LOT of cpu cycles, causing the tablet to overheat and drain its battery almost as fast I could charge it.  Its also not very accurate due to the poor quality of most tablet front camera's in low light and their narrow FoV.

I guess you missed the blog post on the last release. This was also requested if you did a search on closed issues.

https://companion.home-assistant.io/docs/notifications/notification-commands#screen-on

**Comment by R5fan** [comment]
Indeed, I missed that post. I was thrilled initially that companion now allows me to turn on my screen, BUT if I read the docs correctly, Im limited to 150 notifications per day? Thats not enough. 

With wallpanel I sent an MQTT every 20 seconds to keep the screens of tablets  on for as long as the lights are on in that room (and whenever motion is detected).  

I dont want abuse the devs notification service, but I still really need unlimited / local control over my screen somehow. And since there is no "keep screen on" function, I need to keep sending it notifications to beat the screen time out. 

So close.... or am I missing something?

**Comment by dshokouhi** [comment]
> Indeed, I missed that post. I was thrilled initially that companion now allows me to turn on my screen, BUT if I read the docs correctly, Im limited to 150 notifications per day? Thats not enough.

The limit is actually 500 and notification commands do not count towards the limit.

https://companion.home-assistant.io/docs/notifications/notification-details

I noticed that we only called out a few commands and not all of them so submitted an update to clarify that it is every command on the below page

https://companion.home-assistant.io/docs/notifications/notification-commands

**Comment by 0n3-70uch** [comment]
+1 would be very nice. Using fully kiosk at the moment.

**Comment by healeydave** [comment]
I have a cheap Fire 10 tablet and had no end of problems with Fully Kiosk (which I paid for). I switched to Wall Panel (which is free) and that has been working great!

**Comment by JBassett** [comment]
After talking this over with some others we are going to close this enhancement.  The Companion app is going to be geared more towards a daily driver / mobile tablet rather than a wall mounted display.  With that being said, we are going to close this.  If you want a kiosk there is better software out there for that.

**Comment by badewanne1234** [comment]
> I have a cheap Fire 10 tablet and had no end of problems with Fully Kiosk (which I paid for). I switched to Wall Panel (which is free) and that has been working great!

my issue with the Fire 8 HD Tablet and Fully Kiosk is, that it takes 10 seconds to reload the page when the screen goes off and back on on motion with Fully Kiosk. Did you solve that issue?

**Comment by healeydave** [comment]
> > I have a cheap Fire 10 tablet and had no end of problems with Fully Kiosk (which I paid for). I switched to Wall Panel (which is free) and that has been working great!
> 
> my issue with the Fire 8 HD Tablet and Fully Kiosk is, that it takes 10 seconds to reload the page when the screen goes off and back on on motion with Fully Kiosk. Did you solve that issue?

I gave up on Fully Kiosk and dowloaded the free app called Wall Panel which has been working flawlessly for over a year. Its not as configurable as Fully Kiosk but I think that's the problem with Fully Kiosk, it's convoluted. Wall Panel does just enough for me, has camera detection for screen activation  etc.

**Comment by badewanne1234** [comment]
I also tried Wall Panel but have the same issue as soon as the page reloads... I also did set "keep connection open" in Home-Assistant user settings without luck. 
From your post, I assume you dont have this problem of reloading the page?

**Comment by healeydave** [comment]
No, I don't use it often to be honest, I use voice commands for most stuff through HomePod Mini's but the Wall Panel just sits there and works whenever I walk up to it. I have Dwains Dashboard  configured and its sits there for weeks. The only time I have to refresh the GUI is if I have rebooted HA or made changes to Dwains which is very infrequent but even then, its just a reload which takes a couple of seconds.

**Comment by Loic691** [comment]
+1 to get motion detection within the HA app.
Prefer use HASS App rather than FK

**Comment by rwarner** [comment]
Fwiw, for anyone else who comes across github issue again I have been using a Fire HD 10 tablet with Fully Kiosk Browser pointed to the HA web front end and it's been working great for the past few months with its' motion capability.

Initially I was also using WallPanel which was a great alternative, I'm just sick of setting up a different UI and a different app on top of connecting it to HomeAssistant. It just becomes too annoying to maintain in my opinion.

Fully Kiosk
- Using a black color screensaver, timeout
- Motion detection: 97
- Turn screensaver off on motion
- Auto reload on screensaver off
- Takes like half a second to refresh

**Comment by efaden** [comment]
You just leave the backlight on?  Any way to turn the backlight off and on....?

**Comment by rwarner** [comment]
Yeah, you can turn the screen on and off with other settings but I didn’t find it to be as reliable in my own experience.

**Comment by efaden** [comment]
Interesting.... Thinking about trying to use Alexa presence detection to
turn it on and off or something.

During the day I don't care, but in the bedrooms I need the backlights off
at night.

**Comment by theres** [comment]
> After talking this over with some others we are going to close this enhancement. The Companion app is going to be geared more towards a daily driver / mobile tablet rather than a wall mounted display. With that being said, we are going to close this. If you want a kiosk there is better software out there for that.

@JBassett I'd really love to reconsider this feature. The wallpanel is something common in the home automation world. It is also pretty common for HA users. But there is no build-in solution for that in HA, we need to use third-party solution, what is a shame.
