### ISSUE TITLE
Add HA to the share button, so that you can share "stuff" with HA other apps

### ISSUE THREAD

**Issue by Hellis81** [home-assistant/android#1197]
**Is your feature request related to a problem? Please describe.**
No, it's an enhancement. 

**Describe the solution you'd like**
I would like Home Assistant app to be available as "share" option. 
In HA and HA app you add helpers, input number and/or input text. 
When you press the share button from, say your email app or anywhere, you get HA listed and here you can choose what entity you want this to be set on.

The usage I'm thinking of is to let HA decide how to send a message. If the person I want to send a message is home then it could be better to announce on the speakers since we don't always look at our phones when we are home.
If the person is not home then the message is sent as a notification instead.
There are probably lots of good reasons to be able to share/set input text/numbers with values you can copy from your phone.

**Describe alternatives you've considered, if any**
Open the app and set the state manually from the services page. But since that is too much work it just doesn't happen.

**Additional context**

**Comment by dshokouhi** [comment]
Did you know that a share feature already exists?  You can share text to HA and it comes in as an event and from there you can set what ever automation you want to what ever entity you want.

https://companion.home-assistant.io/docs/integrations/sharing

**Comment by Hellis81** [comment]
I did not see that before. 
I tried using Waze to share the ETA with and that option was missing, then I opened Chrome and shared a webpage and HA was there. 
Now it's in Waze also.  (?)

Looks like what I need, it's just a shame you can't see the phone name.
It probably won't be that much of a issue but it would be nice to see that.
