### ISSUE TITLE
Geo location sensors not working on my phone One Plus 7T

### ISSUE THREAD

**Issue by oskretc** [home-assistant/android#1199]
**Home Assistant Android version:**
3.0.2-full
**Android version:**
10
**Phone model:**
HD1913
**Home Assistant version:**
0.117.6
**Last working Home Assistant release (if known):**

**Description of problem:**
Geolocation sensors not working
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**
It was working fine the last version
All other sensors are updated in HA, only the geo location sensors are not correct, both in the phone and nothing is sent to HA

**Comment by dshokouhi** [comment]
What do you mean by not working or not correct?  Did you make sure to leave the sensor enabled? Does the app still have proper permissions?  You will need to be more specific here.

**Comment by oskretc** [comment]
By not working I mean it's not sending any location information (e.g. GPS) to my HA instance, all other sensors are reported back to HA correctly. Yes, the sensor is enabled, and Yes the app has the correct permissions. Is there any access to logs so I can see what is being sent?

**Comment by oskretc** [comment]
After rebooting the phone, it started sending the location info to HA again, I will close for now and keep an eye on it to see if it comes back.
