### ISSUE TITLE
Freezes after being sent to the background.

### ISSUE THREAD

**Issue by walkerleigh** [home-assistant/android#1202]
**Home Assistant Android version:**
3.02-full
**Android version:**
11
**Phone model:**
Pixel 5
**Home Assistant version:**
0.117.6
**Last working Home Assistant release (if known):**
Not known
**Description of problem:**
The app freezes when opened after it has been sent to the background. Swiping it away or force closing then re-opening allows it to run normally until sent to the background again (e.g. with the home gesture). 
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**
Problem doesn't occur straight away if in the App Configuration section when sent to the background. It will not be frozen when opening again and the App Configuration section will still be functional, however app will then freeze when stepping back out of the App Configuration section.

Also happens on OnePlus 6T running Android 10.

**Comment by dshokouhi** [comment]
Do you get the same issue using chrome for Android?

**Comment by walkerleigh** [comment]
No, HA in Chrome for Android works as expected, doesn't freeze.

**Comment by dshokouhi** [comment]
Check that Android system webview is up to date including any and all custom cards

**Comment by walkerleigh** [comment]
Android System We view is version 86.0.4240.198 and was updated to that version one week ago. There are no pending updates for the custom cards I have.

**Comment by walkerleigh** [comment]
I should point out that this has been happening for a couple of months on my One Plus 6T but I was having similar issues with other apps on that phone so am only making the bug report now that it is also happening in the new device (Pixel 5).

**Comment by walkerleigh** [comment]
I have just noticed that the app doesn't freeze completely. I have a humidity sensor and the value was changing in response to someone showering.

It is just that the UI doesn't respond to clicks or swipes.

**Comment by dshokouhi** [comment]
does this only happen when you view the same entity? and the exact same entity in chrome does not have an issue?  This sounds like a frontend issue maybe wehn there are a lot of changes and its trying to view the graph.  I don't believe the app can fix this as we are just a webview to the frontend.

**Comment by walkerleigh** [comment]
No, it doesn't matter which entity or which dashboard is being viewed.

I just cleared data and cache from the app info settings and the freezing has stopped. I'll keep an eye on it, hopefully it's not a temporary fix.

**Comment by dshokouhi** [comment]
Closing issue as clearing data solved it, this is also a troubleshooting step:

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by walkerleigh** [comment]
I have discovered more about this issue. It occurs specifically when the 'Lock app' feature is switched on and a 'Session Timeout' is set. Swipes and clicks are not responded to when the app is resumed after being sent to the background. Swipe away or force close, then zero out the session timeout value and the problem goes away.
