### ISSUE TITLE
TTS should not be played when the Ringer Mode (audio_sensor) is not normal

### ISSUE THREAD

**Issue by Mincka** [home-assistant/android#1205]
**Home Assistant Android version:**
3.0.2-full

**Android version:**
10.0

**Phone model:**
Samsung S20+

**Home Assistant version:**
0.118

**Last working Home Assistant release (if known):**
n/a

**Description of problem:**
It looks like the TTS feature forces the usage of the ALARM_STREAM by default. Consequently, the TTS notification are read aloud even if the phone is on vibrate / mute.

Specifying `notification_stream` does not fix this. However, `notification_stream_max` is taken in account.
```
data:
  channel: notification_stream
```

The choice of the channel should be given to the user for "TTS" message type and not be on ALARM_STREAM by default.

Edit: I think my attempt to describe the issue may be wrong. Maybe the channel is correct but the TTS action itself is not related to the message. So it might be better to play the TTS only if the Ringer Mode is not "Normal". Bypass could be done with the usage of "alarm_stream" and "alarm_stream_max".

**Comment by dshokouhi** [comment]
Please make sure to read the documentation, this is working as expected.

https://companion.home-assistant.io/docs/notifications/notifications-basic#text-to-speech-notifications

**Comment by Mincka** [comment]
Yes, this is working as described but you did not get my point.

Why should the TTS "bypass" (as you wrote) the ringer mode in the first place?
It should be aligned with the standard behavior of the notification sounds.

If the ringer mode is `vibrate` or `silent`, why would it be expected to have the phone speak on a notification?

Currently, the only way to prevent the phone to speak is to mute the music volume. So I cannot listen to music and prevent the phone to speak on a TTS notification. Ok, there is a workaround that is to use the Ringer Mode state myself in the automation to prevent the TTS notification to be sent. 

I understand that the TTS needs to use the Music Stream. My original issue was poorly phrased.
What I say is that the feature could be conditionally triggered locally based on the ringer mode **by default**, because it's more logic from my point of view.

* Ringer Mode Normal
-> TTS notification is played

* Ringer Mode Vibrate or Silent
-> TTS notification is **not** played -> Because we don't expect the phone to disturb us, like for normal notifications.

* Ringer Mode Vibrate or Silence, but alarm_stream/_max specified
-> TTS notification is played

It does not prevent to send TTS message that can bypass the Ringer Mode / Music Stream Volume with alarm_stream/_max. It's what you do when you know in the first place that the notification you send is critical.
