### ISSUE TITLE
Notification attributes (array/list) not expanded (android.textLines and android.people.list) / Stacked messages

### ISSUE THREAD

**Issue by Mincka** [home-assistant/android#1206]
**Home Assistant Android version:**
3.0.2-full

**Android version:**
10.0

**Phone model:**
Samsung S20+

**Home Assistant version:**
0.118

**Last working Home Assistant release (if known):**
n/a

**Description of problem:**
When you get multiple messages from a single app, they can be grouped together.
In this case, even if the messages are all visible in the notifications on the phone, the only captured information as `android.text` is something like "4 new messages". The text itself in then stored in `android.textLines` but this object needs to be converted to something that can be read.

Similar issue regarding `android.people.list` where it's not possible to use the attribute because the list is not expanded.

In my case, I play TTS (Google Cloud) on my Google Home when I get WhatsApp notifications.
However, if I don't open the WhatsApp conversations, the messages are stacked and I am only able to retrieve a generic message which is "4 new messages". I would prefer to be able to use the latest `android.textLines` or the `android.text` if the first one is empty / not present.

```
android.appInfo: ApplicationInfo{5767c9 com.whatsapp}
android.infoText: null
android.largeIcon: null
android.people.list: [android.app.Person@213eede0]
android.progress: 0
android.progressIndeterminate: false
android.progressMax: 0
android.reduced.images: true
android.remoteInputHistory: null
android.showChronometer: false
android.showWhen: true
android.subText: null
android.summaryText: ‎4 nouveaux messages
android.template: android.app.Notification$InboxStyle
android.text: ‎4 nouveaux messages
android.textLines: [Ljava.lang.CharSequence;@97a1bd0
android.title: John Doe
package: com.whatsapp
friendly_name: Téléphone Julien Dernière notification
icon: mdi:bell-ring
```

Maybe related:
https://stackoverflow.com/a/50868911
https://stackoverflow.com/a/49181208

Suggested implementation:
Since the attribute size is limited to 255 characters, it would not be possible to use the same field for all the lines. I think multiple attributes could be created based on the array size:
* android.textLines_0: Message 1
* android.textLines_1: Message 2
* android.people.list_0: John Doe
* android.people.list_1: Jane Doe

**Comment by dshokouhi** [comment]
@Mincka can you try the latest beta with the new Active Notification sensor? I think it might provide each and every notification detail for you in the attributes.  I have seen that count jump when my whatsapp group is chatting away so I think it might be what your looking for :)

**Comment by Mincka** [comment]
Thank you for coming back on this.
I tried the lastest built APK and the "inner messages" are still not shown.


sensor.sm_g985f_active_notification_count | 2 | android.appInfo_com.samsung.android.messaging: ApplicationInfo{53e8cf0 com.samsung.android.messaging} android.appInfo_io.homeassistant.companion.android.debug: ApplicationInfo{cee0d8f io.homeassistant.companion.android.debug} android.conversationUnreadMessageCount_com.samsung.android.messaging: 0 android.hiddenConversationTitle_com.samsung.android.messaging: null android.infoText_com.samsung.android.messaging: null android.infoText_io.homeassistant.companion.android.debug: null android.isGroupConversation_com.samsung.android.messaging: false android.largeIcon_com.samsung.android.messaging: Icon(typ=BITMAP size=101x101) android.largeIcon_io.homeassistant.companion.android.debug: null android.messages_com.samsung.android.messaging: [Landroid.os.Parcelable;@c335269 android.messagingStyleUser_com.samsung.android.messaging: Bundle[mParcelledData.dataSize=456] android.messagingUser_com.samsung.android.messaging: android.app.Person@7466978f android.people.list_com.samsung.android.messaging: [android.app.Person@cd7c0432] android.progressIndeterminate_com.samsung.android.messaging: false android.progressIndeterminate_io.homeassistant.companion.android.debug: false android.progressMax_com.samsung.android.messaging: 0 android.progressMax_io.homeassistant.companion.android.debug: 0 android.progress_com.samsung.android.messaging: 0 android.progress_io.homeassistant.companion.android.debug: 0 android.reduced.images_com.samsung.android.messaging: true android.reduced.images_io.homeassistant.companion.android.debug: true android.remoteInputHistory_com.samsung.android.messaging: null android.remoteInputHistory_io.homeassistant.companion.android.debug: null android.selfDisplayName_com.samsung.android.messaging: ⁨Moi⁩ android.showChronometer_com.samsung.android.messaging: false android.showChronometer_io.homeassistant.companion.android.debug: false android.showWhen_com.samsung.android.messaging: true android.showWhen_io.homeassistant.companion.android.debug: true android.subText_com.samsung.android.messaging: null android.subText_io.homeassistant.companion.android.debug: null android.template_com.samsung.android.messaging: android.app.Notification$MessagingStyle android.text_com.samsung.android.messaging: Fjf android.text_io.homeassistant.companion.android.debug: null android.title_com.samsung.android.messaging: ⁨Julien android.title_io.homeassistant.companion.android.debug: Mise à jour des capteurs android.wearable.EXTENSIONS_com.samsung.android.messaging: Bundle[mParcelledData.dataSize=688] com.samsung.android.messaging_123_is_clearable: true com.samsung.android.messaging_123_is_ongoing: false com.samsung.android.messaging_123_post_time: 1609400824110 io.homeassistant.companion.android.debug_42_is_clearable: false io.homeassistant.companion.android.debug_42_is_ongoing: true io.homeassistant.companion.android.debug_42_post_time: 1609400824557 unit_of_measurement: notifications friendly_name: SM-G985F Active Notification Count icon: mdi:bell-ring
:-- | :-- | :--



sensor.sm_g985f_derniere_notification | ‎3 nouveaux messages | android.appInfo: ApplicationInfo{14cfe57 com.whatsapp} android.infoText: null android.largeIcon: null android.people.list: [android.app.Person@213eede0] android.progress: 0 android.progressIndeterminate: false android.progressMax: 0 android.reduced.images: true android.remoteInputHistory: null android.showChronometer: false android.showWhen: true android.subText: null android.summaryText: ‎3 nouveaux messages android.template: android.app.Notification$InboxStyle android.text: ‎3 nouveaux messages android.textLines: [Ljava.lang.CharSequence;@c30dbd6 android.title: Morgane is_clearable: true is_ongoing: false package: com.whatsapp post_time: 1609401148709 friendly_name: SM-G985F Dernière notification icon: mdi:bell-ring
:-- | :-- | :--

**Comment by dshokouhi** [comment]
Active notifications updates all the time however it does not send unless another sensor is sending data, otherwise this sensor will be sending data non-stop and due to its nature doesn't qualify for an allow list.  It literally updates any time anything is posted or removed from the status bar.  The sensor is also somewhat tied to last notification and last removed notification as a result because that is how those sensors work.  In order to get it to update as frequently as possible you want all notification sensors enabled and no allow list on them.  Keep in mind all sensors are subject to the state detection so if the active count does not change when we send data over then that sensor does not get included in the update.  Thats why everything needs to be sent which as you can tell is probably going to be bad battery drain since it will be updating all the time and its not advised.  One thing you can try is keeping the same allow list for all notification sensors to see if it updates better.

**Comment by Mincka** [comment]
Sorry for the delay but it looks like I stupidly closed the browser without sending my answer a few days ago...

Based on the described reporting behavior, the Active Notification will not do the trick in this case. I need to be able to reliably catch messages received in WhatApps that could be used later to trigger events / actions in HA.

Would you mind to test if you can expand the message content using this method?
https://stackoverflow.com/a/49181208

It would be perfect as an attribute "messages" of the "Last Notification" sensor with an array of all the stacked messages.

Another SO post I found about this:
https://stackoverflow.com/questions/29363770/how-to-get-text-of-stacked-notifications-in-android/29364414

**Comment by Mincka** [comment]
Still interested by this one.

**Comment by Mincka** [comment]
Still interested by this one.

**Comment by McSwindler** [comment]
I think this is the same issue I am having, trying to make an automation based off of food deliveries and not able to get the notification text whenever the notifications are grouped up. 
The only info provided by the last_notification sensor is the App name: 

```
state: com.dd.doordash
android.appInfo: ApplicationInfo{1c54eec com.dd.doordash}
android.reduced.images: true
is_clearable: true
is_ongoing: false
package: com.dd.doordash
post_time: 1646537352111
icon: mdi:bell-ring
friendly_name: Cybermouse Last Notification
```

**Comment by dshokouhi** [comment]
> I think this is the same issue I am having, trying to make an automation based off of food deliveries and not able to get the notification text whenever the notifications are grouped up. The only info provided by the last_notification sensor is the App name:
> 
> ```
> state: com.dd.doordash
> android.appInfo: ApplicationInfo{1c54eec com.dd.doordash}
> android.reduced.images: true
> is_clearable: true
> is_ongoing: false
> package: com.dd.doordash
> post_time: 1646537352111
> icon: mdi:bell-ring
> friendly_name: Cybermouse Last Notification
> ```

This is not related to this issue, in your case the application posting the notification did not seem to attach the text. The app sends in all provided attributes from the notification, if it is not given to us then we do not send it.

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt#L182-L188

Every app that posts a notification has different attributes so you need to investigate what data you get and go by that.  I know that Postmates and Instacart provide the actual text.

**Comment by jpelgrom** [comment]
I've opened a PR to fix this: #2482, but the technical implementation is a bit different than discussed here.

`android.textLines` will now include readable messages, and `android.messages` is readable as well and includes messages + the sender's name. If I've understood everything correctly, this will solve your issue. In testing I had no problems with very long attributes (>1000 characters), so it is still using one attribute.

People objects, such as those stored in `android.people.list`, will not change. This is just a class that happens to implement Parcelable, and as a result can be included in the bundle. Objects are converted to text using `toString()`, which unfortunately if not set doesn't give you anything usable, and the number of parcelable classes makes it unreasonable to add a function to describe them for each class. (As mentioned, there is still enough information in `android.messages` to solve the described issue, so I don't consider this a problem.)

**Comment by Mincka** [comment]
Thank you very much for this. I have this version already installed and I will let you know if I am able to get intermediate messages in the attribute.

**Comment by Mincka** [comment]
Confirmed as fixed. 👍 I am able to get the 7 latest individual messages of the conversation in Whatsapp.
`android.textLines: [Morgane: 😫, Morgane: 😔🐦, Morgane: 🫣, Morgane: 4, Morgane: 5, Morgane: 6, Morgane: Très cher chéri,]`

I don't know if #2478 is a good fit for this sensor because of the ',' issue. At the beginning, I thought it was great because I could create a template sensor to always get the latest message as it would be the latest list item of the textLines attribute. But if there is a comma in any of the last 7 messages, it will fall back as an array and my template will fail. If that's an array, I will have the same issue you have during the conversion, I will attempt to get the latest message after the latest comma but I won't be sure that I get the latest message or a part of it after a comma. The biggest "issue" would be to have this inconsistent behavior, sometimes a string with the array, sometimes that would be list. Maybe it would be better to avoid the conversion for sensors with non-predictable content may have a comma?

**Comment by jpelgrom** [comment]
Good point, inconsistent values also aren't great. Will consider this for the strings-to-list PR.

> But if there is a comma in any of the last 7 messages, it will fall back as an array (if I understood it correctly) and my template will fail. If that's an "array as a string" (`"[xx, y,y]"`) (...)

It would change to a string in the format you included if the separator ", " (note the space after the comma) is included in a message. Your example only has "," in the message so that one will still be a list. 

> Maybe it would be better to avoid the conversion for sensors with non-predictable content that may have a comma?

Right now it isn't really something that allows opting in/out, it is applied to all attributes at a higher level when saving data.

**Comment by Mincka** [comment]
Indeed, poor example but you got the idea. In the example of Whatsapp, there is a high probability that someone will put ", " (with the space) somewhere in a message.

I hope you'll find a way to get a proper enumeration of the items and maybe manage to escape the "," to be able to always convert the elements to list items. Then, you may also get issues with "-" in the messages. 😆 Good luck. 😛

**Comment by jpelgrom** [comment]
@Mincka Updated #2478 based on your comments, thanks! When Android provides an array/list, it will now always be sent to your server as a list.

Items _in_ the list are still limited to strings using `toString()` (and booleans/numbers) though;
 - `android.textLines` is a list of strings (messages) and works as expected
 - `android.messages` is a list of bundles, they are converted to a string and will still give you problems if a message includes ", " (possible workaround: use a regex to select text between `text=` and `, time=`)
