### ISSUE TITLE
power menu: improper value range for heaters/temperature

### ISSUE THREAD

**Issue by flyser** [home-assistant/android#1217]
**Home Assistant Android version:** 3.0.2-full

**Android version:** 11

**Phone model:** Google Pixel 3 XL

**Home Assistant version:**  0.118.4

**Last working Home Assistant release (if known):** none

**Description of problem:**
This is an usability issue and not a real bug. I am using the homeassistant app to control my heaters (via Homematic Integration) and would love to use the awesome new power menu for that as well. However the settable value range of 0 to 100°C does not really make sense for heaters, which are usually controlled between 5 and 30°C (or switched between: off, 5-30°, max).
Is that something that's in the control of the homematic app or is this actually a Homematic integration bug?

**Comment by dshokouhi** [comment]
@flyser does your thermostat have `min_temp` and `max_temp` attributes in the states panel?  This might allow us to provide a better range per entity.

Also 0-100 applies to fahrenheit too which in turn makes some sense but not fully ;)  The current range provides the best for both use cases lol

**Comment by flyser** [comment]
Hey @dshokouhi, thanks for the quick reply :)
Yes they have the min and max_temp attributes. Here is a list of all attributes:

     {'attributes': {'battery': 2.5,
                    'current_temperature': 18.2,
                    'friendly_name': ~,
                    'hvac_modes': ['auto', 'heat', 'off'],
                    'id': ~,
                    'interface': 'wireless',
                    'max_temp': 30.5,
                    'min_temp': 4.5,
                    'target_temp_step': 0.5,
                    'mode': 'Manual',
                    'preset_mode': None,
                    'preset_modes': ['boost', 'comfort', 'eco'], # I wonder what these are. Homematic doesn't have a comfort or eco setting
                    'rssi_peer': -68,
                    'supported_features': 17,
                    'temperature': 5.0,
                    'valve': 0},

**Comment by T-bond** [comment]
I would like to share information about my climate entities as well, maybe it can with the issues in the PR.
One is a car climate control (from a third party integration for [Volkswagen We Connect](https://github.com/robinostlund/homeassistant-volkswagencarnet))
```
hvac_modes: heat, off
min_temp: 7
max_temp: 35
current_temperature: null
temperature: 24
friendly_name: Car
icon: mdi:radiator
assumed_state: true
supported_features: 1
```
And the another one is the HA's generic termostat I set in the configuration for my homemade thermostat:
```
hvac_modes: heat, off
min_temp: 18
max_temp: 27
preset_modes: none, away
current_temperature: 23.5
temperature: 22.5
hvac_action: idle
preset_mode: none
friendly_name: Heating
supported_features: 17
```
It would be cool, if it could use the min, and max temps set by the thermostats, and not presets if possible.
I have all my values in Celsius.
