### ISSUE TITLE
Notification Bar on Updating Sensors

### ISSUE THREAD

**Issue by redflag237** [home-assistant/android#1220]
**Home Assistant Android version:**
3.0.2-full
**Android version:**
8.1.0
**Phone model:**
BQ Aquaris X Pro
**Home Assistant version:**
0.117.6
**Last working Home Assistant release (if known):**

**Description of problem:**
Home Assistant App for Android refreshes the Sensor Values every 15 Minutes. When so, my connected Smartwatch, Mi Band 5, shows an Notification telling "HA Refreshing Sensors". I love the notifications sent from my HA Automations, but don't want to see this Updating Notifications on my Smartwatch. The corresponding App (Mi fit) just grabs the Notification Area, i can select or unselect each single app. Unfortunately i cannot filter the Content of the notification. Can you implement a switch to disable the "Updating sensors" message to appear in notification area?
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
You can disable the sensor worker notification channel if you wish as your device is on Android Oreo, more about that was covered in the blog: https://www.home-assistant.io/blog/2020/09/12/android-240-release/#foreground-service-worker

and also mentioned in our documentation: https://companion.home-assistant.io/docs/core/sensors
