### ISSUE TITLE
picture-entity live view does not auto-play when opened

### ISSUE THREAD

**Issue by Flavien** [home-assistant/android#1225]
**Home Assistant Android version:** 3.0.2-full

**Android version:** 11

**Phone model:** Pixel 4a (5g)

**Home Assistant version:** 0.118.4

**Last working Home Assistant release (if known):** n/a

**Description of problem:** When clicking a picture-entity card configured with a camera to open the live view, the video will not autoplay. On the desktop web version, the video auto-plays, so something is preventing it from playing on the mobile app.

**Traceback (if applicable):** n/a

**Screenshot of problem:**

![Screenshot_20201205-211519](https://user-images.githubusercontent.com/296540/101265545-4b41c180-373f-11eb-830d-ee824d7d6319.png)

**Additional information:**

**Comment by dshokouhi** [comment]
This is to be expected, to save data usage auto play is disabled on mobile for the more info pop-up.  It does work on lovelace homepage however keep in mind there is an issue with high data usage: #979

**Comment by steppel** [comment]
Why not leave it up to the user. Just figured the same problem. Now the question is, why does it auto play on the iOS app. If you say it's power related than it should be on iOS and Android no? Can there not just be an option to enable disable it?
