### ISSUE TITLE
Application and WIFI

### ISSUE THREAD

**Issue by Jabol86** [home-assistant/android#1228]
Home Assistant Android version: 3.0.2-full

Android version: 10

Phone model: Xiaomi Redmi Note 3 Pro, POCO X3 NFC

Home Assistant version: 2020.12.6

Hello.

I have a problem with the application. The application, despite entering the correct name of the WiFi network in the settings of the application to which it connects, cannot connect to the server via the local IP address

**Comment by dshokouhi** [comment]
Check to make sure that location and GPS are enabled on the device, without that the app will never get the SSID from Android.  The latest beta contains logic to inform the user when they are hitting this issue.

**Comment by Touchertb** [comment]
Hello.
I have the same problem. The GPS is only activated if I use it. 95% it is disabled.
Why need Wlan identification an activ GPS?

Sorry for the english.

**Comment by dshokouhi** [comment]
> Hello.
> I have the same problem. The GPS is only activated if I use it. 95% it is disabled.
> Why need Wlan identification an activ GPS?
> 
> Sorry for the english.

Android requirement.

**Comment by dshokouhi** [comment]
Closing as 2021.1.1 is released with an explanation to the users on what they need to leave enabled.
