### ISSUE TITLE
Readd removed sleep as android integration 

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/android#1234]
While I understand that there's a need for a clean policy to integrate third party apps into HA, I don't understand why the already written integration isn't kept inside the app until the author has a chance to migrate it to the (yet to be published) policy how to integrate third party apps. 

There's no issue with leaking private information and the functionality is extremely useful for users of SleepAsAndroid. 

Please readd the functionality temporary, until there's the new official way established. 

https://github.com/home-assistant/android/pull/1149

**Comment by dshokouhi** [comment]
Sorry but we cannot add this back as it is not about the data but the precedent that gets set.  We will need to wait for the new method to get added before we can start integrating other apps.  What you saw was a brief experiment into how it would work but it was not meant for prime time.  The latest sleep as android beta has webhook support and it should give you everything this integration offered and then some as there are more intents now.  I am also the author who submitted the original PR and I am ok with it being pulled until this is ready.  Sorry you just have to wait like everyone else but at least the app has webhook support to offer the same thing.
