### ISSUE TITLE
Swipe navigation between views

### ISSUE THREAD

**Issue by muzzak123** [home-assistant/android#1237]
**Is your feature request related to a problem? Please describe.**
I have a number of different views such as lights, doors, climate, people etc. It can be a real pain having to scroll up to the top of the page every time you want to switch from one to the other.

**Describe the solution you'd like**
I would like a swipe navigation feature that allows you to switch from one view to another by swiping left or right. For example in the image below a left swipe would take you from "climate" view to "People" view, rather than having to go to the top and click on the actual text.

**Describe alternatives you've considered, if any**
None

**Additional context**
For example in the image below a left swipe would take you from "climate" view to "People" view, rather than having to go to the top and click on the actual text.
![Untitled](https://user-images.githubusercontent.com/51472089/102342670-8a400480-3fd4-11eb-9aeb-a728fd4210a7.png)

**Comment by JBassett** [comment]
Duplicate of https://github.com/home-assistant/android/issues/225

If you look in comments of other issue it has a custom card that can help.

**Comment by muzzak123** [comment]
OK Thanks
