### ISSUE TITLE
Push notification privacy questions

### ISSUE THREAD

**Issue by Extarys** [home-assistant/android#1243]
Reading issue #522 some questions popped up. As I am not familiar with Google Firebase and Gapps servers for push notification, please excuse my ignorance.

Background:
There have been some heated debate before about not using Google stuff and I know the devs didn't care to implement websocket for notification and geopositioning (or Server Sent Events, even if many open-source project does implement such features), but I'm using Home-Assistant to avoid giant companies (or any companies) to use, see, sell, etc my information. (Well I stopped using itfor a while when one dev said they didn't care about users complaining about Google, but an unfortunate turn of events pushed me to use HA for some urgent stuff) I believe my mind could be at ease with more information.

- When notification are sent through `https://mobile-apps.home-assistant.io/api/sendPush/android/v1`, what data which company can see? Is the content have some kind of encryption? How long does it stays on home-assistant server? On Google/Apple servers?
- On your [notification page](https://companion.home-assistant.io/docs/notifications/notification-details), in the Security section, it reads `All traffic between your Home Assistant instance, the push infrastructure, and Apple, is encrypted with SSL.`. What about Google?
- Since the servers belong to Google/Apple, even if the connection use SSL, they still can see the data, right? From what I understand, it's secure from "hackers" but not those companies, right?

I ask this here because knowledgeable people will be able to answer me, and since this seems to be a very recurring topic, other users will also be able to see that information. Thanks for your time.

**Comment by dshokouhi** [comment]
At the time that security page was created the android app did not exist.  You can find the code for the FCM server for your own inspection: https://github.com/home-assistant/mobile-apps-fcm-push

As to the other stuff I am not sure, you are more than welcome to run things on your own and keep your own FCM server and build the app for yourself with that server if privacy is of upmost concern. 

If you wish to get more info please consider creating a forum post for more discussion. Github is only meant for issues and feature requests.

**Comment by Extarys** [comment]
Thanks for the link, I understand. Yes, privacy is an issue.

I was sure FCM wasn't open source, I'll look into it.
