### ISSUE TITLE
Transfer to new phone keeps old phone identity, now 2 phones with same ID

### ISSUE THREAD

**Issue by brantlk** [home-assistant/android#1248]
**Home Assistant Android version:**
3.0.2-full

**Android version:**
11

**Phone model:**
LG G6
Google Pixel 5

**Home Assistant version:**
2020.12.1

**Last working Home Assistant release (if known):**
Unknown

**Description of problem:**
I got a new phone and to set it up I used the setup steps where I plugged a cable between them and everything was transferred. Afterwards I brought up HA app fine.
I've still got the old phone and maybe I'll use it as another HA remote or something, but I'm not keeping it on me anymore.
I wanted to set up location tracking to the new phone and I was confused since there's no new tracker for the new phone. The Integrations page in HA shows only the old phone.
From what I can tell based on zone history HA was getting updates from both phones for the same tracker and was switching between home & away.
The workaround was to delete all the data for the HA app. Then when I started it up again it asked me to configure it and login and the new Integration appeared, and device tracker, etc.

I think the correct behavior is when transferring the app between devices don't keep the same ID. Not transferring user data would also be fine by me.

**Traceback (if applicable):**
N/A

**Screenshot of problem:**
N/A

**Additional information:**
N/A

**Comment by dshokouhi** [comment]
Hmm so do we just stop auto back up? I wonder how restoring impacts widgets if android decides to give a new app widget ID.  Our app might not be a good candidate for backup/restore if we can't handle everything properly.

**Comment by dshokouhi** [comment]
Closing due to lack of response, restoring data is to be expected. If you want to use the app on both phones simply dont transfer data for the app or clear data and start over.
