### ISSUE TITLE
Notification Appearing and Disappearing every second

### ISSUE THREAD

**Issue by vautieri** [home-assistant/android#1249]
**Home Assistant Android version:**
Supervisor
Version
2020.12.7
Newest Version
2020.12.7
Channel
beta
**Android version:**
Latest?  These are the latest models of devices.  Android PIE?  (don't think it matters for this issue)
**Phone model:**
Samsung note 10 and tablet S7 show the same issue
**Home Assistant version:**
Supervisor
Version
2020.12.7
Newest Version
2020.12.7
Channel
beta
**Last working Home Assistant release (if known):**

**Description of problem:**
I think this has been an issue for a while.  IF you catch it at the right time you see "Updating Sensors".  Is very annoying as it makes your gui and icons constantly bouncing around.
**Traceback (if applicable):**

```

```
**Screenshot of problem:**
I will try to add a video of the issue?  if I cannot attach a video, I will try to make a link to the video if needed.
**Additional information:**

**Comment by dshokouhi** [comment]
This is not an issue, see the link below on how to stop it and why it exists.

https://www.home-assistant.io/blog/2020/09/12/android-240-release/#foreground-service-worker
