### ISSUE TITLE
A display bug

### ISSUE THREAD

**Issue by franklinbill** [home-assistant/android#1254]
**Home Assistant Android version: 3.0.2-minimal (521)**

**Android version: 8.0**

**Phone model: Google nexus 6**

**Home Assistant version: 3.0.2-minimal (521)**

**Last working Home Assistant release (if known):**

**Description of problem:**
Dear developer! In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the lower part of the text in the red box is blocked, so you can only see “Your Dxxxx”. It may be an adaptation problem.
App version is 3.0.2-minimal (521), my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **font size and display size are the largest**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![bug-home_172](https://user-images.githubusercontent.com/18572115/103084326-af0e2a80-4619-11eb-88e6-530bca5e169e.png)

**Additional information: It may be an adaptation problem.**

**Comment by dshokouhi** [comment]
What is that a screenshot of? It doesn't look like our application.

**Comment by franklinbill** [comment]
I've compressed the screenshot. This is the original one
![home_172](https://user-images.githubusercontent.com/18572115/103096192-176f0300-463e-11eb-9799-462c920d0294.png)
I downloaded it from f-droid https://f-droid.org/zh_ Hans/packages/ io.homeassistant.companion.android.minimal

**Comment by franklinbill** [comment]
It seems that this problem occurs when the font size and display size are the largest. It may be that the height of the component needs to be set to adaptive text.

**Comment by dshokouhi** [comment]
That does not look like our application.

Do any of these screenshots look like what your just shared?

play.google.com/store/apps/details?id=io.homeassistant.companion.android

**Comment by franklinbill** [comment]
I'm very sorry. I've got the wrong link.  This is not your app. Sorry!
