### ISSUE TITLE
Notification Images - Tap to open

### ISSUE THREAD

**Issue by tiaanv** [home-assistant/android#1257]
**Is your feature request related to a problem? Please describe.**
No ability to view/zoom images (camera) in notifications.

**Describe the solution you'd like**
Add the ability to open notifications with images in some viewer to zoom/pan etc.

**Describe alternatives you've considered, if any**
Fire of an Intent that will open the image file like Intent.ACTION_VIEW

**Additional context**
N/A

**Comment by dshokouhi** [comment]
This is actually already supported you just need to make use of either `clickAction` to go to the Image or actionable notifications to hit the URI.  By setting this URLs will open in chrome and then you can zoom/pan from there.

https://companion.home-assistant.io/docs/notifications/notifications-basic/#notification-click-action

https://companion.home-assistant.io/docs/notifications/actionable-notifications#building-automations-for-notification-actions

**Comment by tiaanv** [comment]
@dshokouhi 

Whilst both features you mention above are great and very flexible it does not cater ver well for cameras.

It does not work for my use case, as far as I know. I have looked at them before posting the feature request.

The basic notification grabs the image for the notification through the camera_proxy as can be seen below.  Even if this was an image that I saved, it would be overwritten for each notification. and the previous image would not be accessible.

```
    - service: notify.mobile_app_my_phone
      data:
        message: "Gate Closed"
        data:
          image: "/api/camera_proxy/camera.front_door"
          ttl: 0
          priority: high

```
In both cases above, executing the click action or actionable at the time of viewing the notification does not give me access to the camera image at the time of the event. Only the CURRENT one.  This is why my request ( in my mind) is still valid.  A way to access the image embedded into the notification is necessary.  This is already possible through the notification itself, but for camera images, the fidelity/resolution is not adequate on average phones.

As mentioned in my original post, either have a way where the image in the notification is accessbile via a URI, or just simply opening the image in default gallery by intent would be great.

**Comment by dshokouhi** [comment]
> Even if this was an image that I saved, it would be overwritten for each notification

This is purely dependent on how you save images, if you save them with a timestamp then it won't be overridden.

For what you want its actually a duplicate of #609 as it needs to be saved in order to be viewed by the gallery or even made into a URI.

One thing to keep in mind as well is that if your notification is delayed then using camera proxy the image can also be delayed as it only gets rendered when the app receives the notification.  If you use `ttl` and `priority` a lot then android will still deprioritize the notifications and then the image can be delayed.  Just some things to consider.

**Comment by tiaanv** [comment]
Thx @dshokouhi for the feedback.  Taking all of your comments into consideration, especially the potential delay of the camera proxy mechanism, I think I'll probably just go back to using pushover for now.  Implementing image captures with datestamps will become quite an elaborate script/automation and additional work for cleanup...  Much simpler just switching back to PO.

Much appreciate ALL your efforts in the APP.  The growth has been phenomenal!
