### ISSUE TITLE
Implement FIND3 indoor positioning

### ISSUE THREAD

**Issue by eifinger** [home-assistant/android#126]
Some home-assistant users use [FIND3](https://github.com/schollz/find3) for indoor positioning. The active scanning mode needs an android app. It would be great if that functionality could be implemented into the home-assistant-android app so we can get rid of too many apps.

The code can be found [here](https://github.com/schollz/find3-android-scanner), worth noting is the latest [PR](https://github.com/schollz/find3-android-scanner/pull/22)

**Comment by Knoxie** [comment]
Is that app still being worked on? I see several PR and no code updates since July?

**Comment by eifinger** [comment]
The owner does not seem to be responding to this repo anymore.

**Comment by psinide** [comment]
The app sends the 'signal level' parameter to home-assistant, but it doesn't update frequently. I noticed it updates everytime I hard close the app from memory and re-open it. 
This parameter could be useful to set thresholds to identify room presence if there is a frequent signal level update sent to home-assistant

**Comment by dshokouhi** [comment]
@psinide right now the wifi sensor updates as soon as a network state change occurs.  Can you try again in version 2.2.1 and see if it updates faster? I think this is as fast as we can get it to update without triggering scans and updates every few seconds.  If you have multiple AP's and move between them you will see the sensor update immediately to reflect that.
