### ISSUE TITLE
Latest beta slow and shows white screen

### ISSUE THREAD

**Issue by Nossnevs** [home-assistant/android#1266]
**Home Assistant Android version:**
beta-541-bd4a98e-full

**Android version:**
8

**Phone model:**
Samsung s7
**Home Assistant version:**
2020.12.1
**Last working Home Assistant release (if known):**

**Description of problem:**
Latest beta slow and shows white screen on almost every page load. I don"t see this on desktop.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Can you reproduce the issue in chrome for Android? Is Android system webview up to date?

**Comment by dshokouhi** [comment]
In addition to the above if that fails please also try [starting fresh](https://companion.home-assistant.io/docs/troubleshooting/faqs#starting-fresh-with-the-android-app)

**Comment by Nossnevs** [comment]
Hi i see that the problem now is only things in Supervisor and are both in chrome and the app. On a desktop i don't see that problem. If something have updated or if i did not look around that much i don't know.

**Comment by dshokouhi** [comment]
Then this is not a problem with the app but with the HA front end.  As they have an entire issue template for themselves with troubleshooting steps please open an issue there: https://github.com/home-assistant/frontend/issues/new?labels=bug&template=BUG_REPORT.md
