### ISSUE TITLE
Add built-in SSH tunneling

### ISSUE THREAD

**Issue by vampywiz17** [home-assistant/android#1267]
**Is your feature request related to a problem? Please describe.**

Secure remote access to HA with Android app now 4 way:

- Cloud (Nabu Casa) 
- SSL 
- VPN
- SSH Tunnel

First is easy, but need to pay (no problem, i already use it, but it is a fact), 

Second is a bit complicated (especially for beginners) and if you use it itself (without VPN or tunneling) no so secure (more precisely, it secure, with two factor auth and strong password, but attackable)

VPN i think is to "robust" if we only want to access a remote web interface... (and need a external app on Android or need to configure the Android default VPN client) 

The best option is the SSH tunneling. But if we want to use it with Android, it also need to use a external app (like [Terminus](https://play.google.com/store/apps/details?id=com.server.auditor.ssh.client&hl=hu&gl=US)). 

**Describe the solution you'd like**

But if the SSH tunneling would be a built in feature in HA app, it possible to access the remote server without any external app on your phone. (or not need to "stay alive" a VPN connection all the time)

Of course it would be good that is support Public Key Authentication, not only password one

**Comment by jakubjakubik** [comment]
@vampywiz17 https://github.com/home-assistant/android/pull/870 mutual TLS auth is the proper solution to what you're trying to accomplish here - public key auth for both ends (client and server)
IMHO there is no point in creating hacks like ssh tunnels inside the app as this is just a dirty workaround the missing cert support

**Comment by balloob** [comment]
SSH Tunnel is out of scope for the Android app.
