### ISSUE TITLE
Steps_sensor wrong data

### ISSUE THREAD

**Issue by caddyblack** [home-assistant/android#1269]
**Home Assistant Android version:**
HA android version 3.0.2-full
**Android version:**
8.0.0
**Phone model:**
SM-G930F
**Home Assistant version:**
2020.12.7
**Last working Home Assistant release (if known):**

**Description of problem:**
Phone counts the steps. The app shows only very few steps ( below 10 ) while the samsung health app gives > 5500 steps. The Samsung app uses the phone steps so I would expect the same number in Home Assistant. 
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
Problem
![20210101_164033.jpg](https://user-images.githubusercontent.com/48408773/103441737-18142480-4c50-11eb-9b0d-4544b4cf01c2.jpg)
Samsung app
![20210101_163632.jpg](https://user-images.githubusercontent.com/48408773/103441618-86a4b280-4c4f-11eb-8617-5d34debfc55b.jpg)
**Additional information:**

**Comment by dshokouhi** [comment]
The app only sends periodic requests to the android system and if there is an update it will send it to us.  If not it does not.  We can't compare to another app as those app have their own logic in counting and we do not hold on to the steps sensor, the android steps sensor resets at midnight other apps contain logic to get around it but we do not.  We make a request and if it has something we get it, if not we don't.  Its entirely dependent on when android decides to send it to us.  Some devices report steps more frequently than others.
