### ISSUE TITLE
Full screen mode for Android App

### ISSUE THREAD

**Issue by Misiakufal** [home-assistant/android#1274]
**Is your feature request related to a problem? Please describe.**
The Notification Bar from Android is visible when I use the App on my smartphone which is mounted on a wall. 

**Describe the solution you'd like**
I would like to have an option to set the App as a full screen app.

**Describe alternatives you've considered, if any**
When I switch to Full screen web browser to solve this issue, haptic feedback from all buttons is gone so there is no workaround that would be acceptable

**Additional context**

**Comment by dshokouhi** [comment]
This is already possible in App Configuration, just enable Fullscreen
