### ISSUE TITLE
Allow choosing between GPS and home/away tracker functionality

### ISSUE THREAD

**Issue by ugniuslt** [home-assistant/android#1276]
**Is your feature request related to a problem? Please describe.**

Currently the Android companion app for Home Assistant has a built-in GPS location tracker. It always sends the GPS coordinates to HA. The problem is that you can click the person's entity anywhere in the UI and see the exact location of that person at any given time. This is a major privacy concern. Any family member can track me 24/7 and I can track any family member if they use the app. But all I want to know is whether the user is home/away or in any other zone and run some automations based on that.

**Describe the solution you'd like**

I propose the following solution:
- During the onboarding process, ask the user what kind of location tracking he/she would like to use: GPS or zone-based (referred to as "stationary" in the docs). Privacy risks should be clearly described (i.e. that a Home Assistant admin will always be able to know your exact location at all times if you choose GPS).
- If a user chooses zone-based tracking, the app performs home/away/in zone calculation on the client side. It still gets the GPS location from the phone, then checks whether it belongs to any known zones (it has zone info) and calls **device_tracker.see** providing only **location_name** parameter and not providing the actual GPS coordinates.

**Describe alternatives you've considered, if any**

- Disabling precise location on your phone is not a solution. Cell-based location will still be reported to Home Assistant.
- Wifi connection based device trackers are not reliable, because the phone will disconnect from wifi when idle for a long time. Some family members like to use 4G instead of wifi.
- Some other users have achieved similar functionality with Tasker, but if it was built into the app, it would be much more convenient (and easier to convince family members).

**Additional context**

**Comment by dshokouhi** [comment]
> Currently the Android companion app for Home Assistant has a built-in GPS location tracker. It always sends the GPS coordinates to HA. The problem is that you can click the person's entity anywhere in the UI and see the exact location of that person at any given time. This is a major privacy concern. Any family member can track me 24/7 and I can track any family member if they use the app. But all I want to know is whether the user is home/away or in any other zone and run some automations based on that.

All mobile app device trackers are required to send in GPS coordinates.  The app has to provide them, even for zone logic this is required.

https://developers.home-assistant.io/docs/api/native-app-integration/sending-data#update-device-location

The app already offers a zone tracking toggle that will only update based on zone events and will not send continuous reports in.  So I don't know why you said its always constantly sending data, you don't have to use background tracking.  This is why we offer 3 toggles so it can be flexible.

Closing this issue as we already offer zone based tracking separately from backgroudn and the app is required to send in GPS coordinates.  HA is the one that determines if you are in a zone based off the provided coordinates.

**Comment by ugniuslt** [comment]
> All mobile app device trackers are required to send in GPS coordinates. The app has to provide them, even for zone logic this is required.

I understand there might be legacy requirements or limitations, but in the modern world of GDPR privacy is more important. Otherwise the app will only be used by other developers and enthusiasts. Other device trackers like NMAP don't provide GPS coordinates and work with home/not_home states directly. Perhaps the app can create multiple device trackers - GPS and zone based. 

> The app already offers a zone tracking toggle that will only update based on zone events and will not send continuous reports in. So I don't know why you said its always constantly sending data, you don't have to use background tracking. This is why we offer 3 toggles so it can be flexible.

Correct me if I am wrong, but current "zone based tracking" only sets up geofences so that location is updated more quickly when leaving/entering a zone. The app will still send a location update if I open it in the middle of the forest. And anyone at home can see that I am in that forest. This is bad, this breaks my privacy. 

All I need (and most people) is to know when someone leaves or enters the house. I don't need to know where exactly someone is when he/she is not at home. That is exactly what Google Home is offering in their presence sensing functionality: https://www.androidpolice.com/2020/10/22/the-google-home-app-has-a-new-presence-sensing-feature-heres-what-it-does/

It does not tell everyone at home - "hey, Peter is currently visiting his grandmother", because that is not relevant.

I have tried all combinations of the three location sensors and my GPS location is still disclosed if I open the app while I am not at home.

I hope this explains the problem more clearly.

**Comment by dshokouhi** [comment]
> Correct me if I am wrong, but current "zone based tracking" only sets up geofences so that location is updated more quickly when leaving/entering a zone. The app will still send a location update if I open it in the middle of the forest. And anyone at home can see that I am in that forest. This is bad, this breaks my privacy.

This is an incorrect assumption.  Background location tracking subscribes to frequent updates when its enabled and removes those subscriptions when its disabled.  Zone tracking only reports based on geofencing events around zones and thats it.  Enter and exiting a zone.  Please read the location sensor toggle descriptions in App Configuration.  They describe what each sensor does.

**Comment by ugniuslt** [comment]
> This is an incorrect assumption. Background location tracking subscribes to frequent updates when its enabled and removes those subscriptions when its disabled. Zone tracking only reports based on geofencing events around zones and thats it. Enter and exiting a zone. Please read the location sensor toggle descriptions in App Configuration. They describe what each sensor does.

It still reports my first location outside the zone. If I turn off my phone at home and I turn it back on in the middle of the forest, it will decide that I left the geofence and report my location to Home Assistant. 
This is an exaggerated example, but there can be many reasons when the "zone left" location update only happens when you are already far away from home and that gives away your private information.

**Comment by dshokouhi** [comment]
So if the app was killed by your phone and you reopen it we end up losing your zone subscription and we therefore need to make a new one at that time.  If your app was not killed then the zone subscription would not need to be made again and you wont get a random zone left event.  This is how android works and we can't keep track of these things so this is actually expected behavior that we can't control here.

**Comment by ugniuslt** [comment]
What I am trying to say is that many people (including me) need a very simple thing: phone in pocket, leave for work, HA is notified that I am away (without telling where exactly). Return from work, HA is notified that I am home. That's it. We don't need GPS coordinates going to the server for that. It's unfortunate that it is not possible to achieve this use case as the app is very useful and convenient otherwise.
I'll post a feature request on the forums, I think it requires a broader look at the whole picture.

**Comment by JBassett** [comment]
If you are only looking for home/away status there are plenty of other integrations that can provide that data.  https://www.home-assistant.io/integrations#presence-detection has a great list of integrations you can use if you don't want to use the companion app's device tracking.

**Comment by llamafilm** [comment]
This feature was added to iOS some time ago. So I suppose it could be done on Android the same way. https://github.com/home-assistant/iOS/pull/2015

**Comment by jpelgrom** [comment]
@llamafilm This was added to the Android app some time ago. Please check the documentation first before commenting on old issues like these :)
