### ISSUE TITLE
Android 11 Power menu endless loading if App is paused in background

### ISSUE THREAD

**Issue by MDXDave** [home-assistant/android#1277]
**Home Assistant Android version:**
3.0.2-full

**Android version:**
11

**Phone model:**
OnePlus 8 Pro

**Home Assistant version:**
0.118.4

**Description of problem:**
If the Android App is in background (and paused from the OS) the states in the power menu Just Show "loading" without finishing the loading any time soon. 
Only when I open the HA app manually the power menu loaded the data and is available for control again. 

**Screenshot of problem:**
![Screenshot_20210105-010715](https://user-images.githubusercontent.com/6099976/103592265-e2db3100-4ef2-11eb-9159-d840e606d408.jpg)

**Comment by dshokouhi** [comment]
Please make sure teh android app has access to run in the background and that it is exempt for any and all battery optimizations.  If you still experience this issue then we need the android crash logs.  If app is not running or the system does not allow the app to run then we cannot expect the app to run.

You can check background access in the app but it is up to the user to ensure the device is not killing the app prematurely.

dontkillmyapp.com is also a good place to understand how to prevent your OS from doing this.

To get the crash logs: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs

**Comment by pszafer** [comment]
I have same issue since update to Android 11 but with desktop widget. All battery optimization disabled I think.
Should I open new issue or can I attach log to this issue?

**Comment by dshokouhi** [comment]
> I have same issue since update to Android 11 but with desktop widget. All battery optimization disabled I think.
> Should I open new issue or can I attach log to this issue?

Please open a new issue and attach the logs with steps to reproduce.

**Comment by dshokouhi** [comment]
Closing due to lack of response
