### ISSUE TITLE
Reflect persistent notifications in the web interface as Android notifications

### ISSUE THREAD

**Issue by blkqi** [home-assistant/android#1279]
**Is your feature request related to a problem? Please describe.**

When using the Minimal Android Flavor it is not possible to use the mobile_app platform for notification since it relies on Firebase and therefore Google Play Services.

**Describe the solution you'd like**

The mobile app should be able to display an Android notification for every notification sent to a connected web interface via the Persistent Notification integration. This would allow notifications to be delivered to Android devices without the use of Google Play Services.

This solution additionally has benefits for all Android flavors, since it provides a convenient way of delivering notifications to *all* connected Android devices.

**Describe alternatives you've considered, if any**

An alternative solution might leverage Home Assistant Cloud (or another hosted service other than Firebase) to deliver the notifications. Besides being much more work, this alternative solution is less desirable since it must be a hosted service. An example of delivering Android notifications without Google Play Services exists in the Signal application.

**Additional context**

None to add.

**Comment by dshokouhi** [comment]
The android app is just a webview to the frontend.  The android app is unaware of anything posted there.  I don't think this will be possible without changes to the frontend and HA core.  You may need to start this request in the HA forums to begin with.

**Comment by blkqi** [comment]
Would it be reasonable to have the Android app interface directly with the Home Assistant websockets API?

**Comment by dshokouhi** [comment]
Reasonable sure, someone just needs to build it but it would still require changes in HA core to support this.  Battery life is also of concern since a constant connection will need to be maintained to get notifications.

**Comment by blkqi** [comment]
What changes would be required in core? Wouldn't this already be supported by using the websocket API to subscribe to the `persistent_notifications_updated` event?

**Comment by dshokouhi** [comment]
It doesn't make sense to link to an existing notification platform.  Then you need to build things into the app to let users turn it off and thats not how notifications are meant to work.  This should be something new and treated like a normal notification platform, much like we have today.

**Comment by blkqi** [comment]
As an end user, I think of the Android app as another manifestation of the frontend. The fact that it is merely a companion app like any other, or "just a webview to the frontend", is to me just an implementation detail.

So, while I sympathize with your approach, I also think it would be rather useful to (optionally) hook into the _persistent notification_ platform, which is the notifcation platform for the frontend.

For lack of a better example, it is not unlike how a web-based application (a board or chat; Discord, perhaps) can push its own notifications to your browser or system notification tray.

If this is not a direction the development team wants to go, then a websocket based alternative (or fallback) to FCM would also solve the root problem here, and I would highly encourage it.
