### ISSUE TITLE
option to change next_alarm state to local time

### ISSUE THREAD

**Issue by capstan1** [home-assistant/android#1280]
**Is your feature request related to a problem? Please describe.**
When building automations using next_alarm the time in the HA entity is one hour off for me currently because of the daylight savings time /winter time in europe. This means I would need to adjust all automations to delay by one hour compared to the sensor. And this will be causing another wrong time as soon as we get to summer.
Especially with all the new blueprints emerging, which simply let you choose one entity to define trigger time, this leads to problems.

**Describe the solution you'd like**
There should be an option inside the sensors settings to just put the local time in the entities state. I don't need UTC format.

**Describe alternatives you've considered, if any**

An option defining a "shift time". However, once we change change times/time zones, this would lead to problems.

**Comment by dshokouhi** [comment]
The sensor has an attribute for local time for just this very reason.  All `timestamp` device class sensors are required to send their state in UTC format per the dev docs: https://developers.home-assistant.io/docs/core/entity/sensor#available-device-classes

Sorry we cannot do this feature request but you should be able to use existing attributes to get what you need.
