### ISSUE TITLE
phone_state sensor doesn't report incoming call

### ISSUE THREAD

**Issue by Bodge-IT** [home-assistant/android#1284]
**Is your feature request related to a problem? Please describe.**
Kind of.  The phone_state sensor reports "idle" and "offhook", not when an incoming call is being received.

**Describe the solution you'd like**
The sensor to also report "ringing"

**Describe alternatives you've considered if any**
Tasker

**Additional context**
N/A

**Comment by dshokouhi** [comment]
`ringing` is a state

https://companion.home-assistant.io/docs/core/sensors#phone-state-sensor

**Comment by Bodge-IT** [comment]
Not working then

**Comment by dshokouhi** [comment]
Please provide as much information as possible including the crash logs and the device including if its a custom ROM etc...

![image](https://user-images.githubusercontent.com/1634145/104030064-a96b2580-517f-11eb-9ce4-e345584619f4.png)
