### ISSUE TITLE
External URL polled every 5-10 minutes when on Home Network

### ISSUE THREAD

**Issue by RobBrazier** [home-assistant/android#1285]
**Home Assistant Android version:** 3.0.2-full

**Android version:**  Oxygen OS 10.3.7.GM57AA (Android 10)

**Phone model:** OnePlus 7

**Home Assistant version:** 2021.1.0

**Last working Home Assistant release (if known):**

**Description of problem:**
When I am on my home network, I can see in my DNS resolver logs that the Home-Assistant android app is polling my 'main' (external) Home Assistant URL roughly every 5-10 minutes, even though it shouldn't be being used (I've confirmed that it's using my internal URL by disabling the port forwarding - the app still worked fine)

I've confirmed that it is actually the app, not something else on my phone by removing the 'external' configuration and the DNS polling stopped

I have the same URLs configured in my home assistant core configuration for external and internal that I am using in the app (if that makes a difference)

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
N/A

**Screenshot of problem:**
N/A

**Additional information:**
N/A

**Comment by dshokouhi** [comment]
So in order for the app to read the SSID the device needs location and GPS enabled otherwise we do not know you are on wifi and we just try both URL's.  Can you confirm that location and GPS are enabled on your device?  Basically the app tries to hit all URL's that we have to ensure we can send data so I am not sure if this is really an issue here.

**Comment by RobBrazier** [comment]
Ah, okay, yep - I've got both enabled
If you don't think it's an issue, that's fine - just thought I'd flag it up as I noticed a lot of DNS requests

**Comment by dshokouhi** [comment]
When it comes to making calls to HA for sending data home we actually try all URLs that we have:

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt#L191

In certain cases like checking authentication, the webview, loading images in notifications is when we try to prefer internal if possible to prevent loading issues

**Comment by RobBrazier** [comment]
Okay cool, that could explain it - I'll close this ticket then - thanks

**Comment by dshokouhi** [comment]
@RobBrazier just a FYI now that we have #1286 merged you should no longer see the external URL being hit first (unless of course the internal URL fails for whatever reason).  This is now in the latest beta version of the app.

**Comment by RobBrazier** [comment]
@dshokouhi ace, thanks for the update - I'll keep an eye out!
