### ISSUE TITLE
Fire open and close app event

### ISSUE THREAD

**Issue by ngohaiitdog** [home-assistant/android#1288]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I'd like to have the Android Companion fire an event when user open or close the app, like the "ios.entered_background" and "ios.became_active" in the iOS version. The use case will be to update certain template entities only if the app is active.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
So the android app actually does not get notified about when an app goes into the background/foreground to make the events meaningful.  What we can do is provide a sensor that will tell you the current state of the app which can be a number of different states asides from `foreground` or `background`.  In this case the sensor will be better served.

**Comment by ngohaiitdog** [comment]
Thanks! @dshokouhi

**Comment by ngohaiitdog** [comment]
@dshokouhi Thanks again! But it isn't working quite as intended. I am not sure if it is my problem or what, the `importance` can change to `foreground` almost immediately after I open the app. However it remains `foreground` for quite a long time, ranging from 5 minutes to 20 minutes even after I close the app.

**Comment by dshokouhi** [comment]
> @dshokouhi Thanks again! But it isn't working quite as intended. I am not sure if it is my problem or what, the `importance` can change to `foreground` almost immediately after I open the app. However it remains `foreground` for quite a long time, ranging from 5 minutes to 20 minutes even after I close the app.

Please re-read my comment for the Android limitations. This is the best we can do.

**Comment by dshokouhi** [comment]
> > @dshokouhi Thanks again! But it isn't working quite as intended. I am not sure if it is my problem or what, the `importance` can change to `foreground` almost immediately after I open the app. However it remains `foreground` for quite a long time, ranging from 5 minutes to 20 minutes even after I close the app.
> 
> Please re-read my comment for the Android limitations. This is the best we can do.

I take back my comment, will submit an update that forces a sensor update when the webview is paused and resumed.  This will force it to update the state immediately :)  Not a bad idea to keep things up to date when we resume the app or even pause it.
