### ISSUE TITLE
App freezes on unlock if power button pressed first

### ISSUE THREAD

**Issue by mdegat01** [home-assistant/android#1290]
**Home Assistant Android version:** beta-547-e604ad8-full

**Android version:** 11

**Phone model:** Pixel 3

**Home Assistant version:** 2021.1.1

**Last working Home Assistant release (if known):**

**Description of problem:**
My phone has a fingerprint scanner. If I put my finger on it the phone unlocks and the screen turns on at the same time. This works totally fine when I do this. The HA android application correctly updates my `interactive`, `device_locked` and `keyguard_locked` sensors and if I open the application functions normally.

However if my phone is locked and I just press the power button then the screen turns on but the phone does not unlock. If I then unlock it either by scanning my finger or typing in the passcode then the HA application freezes. The `interactive` sensor is set to `on` when the screen first turns on but the `device_locked` and `keyguard_locked` sensors remain `on`. And if I open the HA application then it is completely frozen (nothing I do registers). I have to close it by swiping it out of my recent applications then re-open it to get the sensors to update and to be able to interact with the application.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
I have logcat installed and set up but I don't see any logs from `homeassistant` during this interaction.

```

```

**Screenshot of problem:**
Not really much to screenshot, the app is just frozen when I bring it to the foreground after the interaction I described.

**Additional information:**

**Comment by dshokouhi** [comment]
Can you check that android system webview is up to date? Also we will still need the logs around the time of the issue to see whats going on even if you don't see anything about our app.  Without logs this is going to be very difficult to fix.

**Comment by mdegat01** [comment]
I have no updates pending in the play store, is that what you mean? Also I just remembered I have "Lock app" set to true. When I turn that off then the screen no longer freezes on open. However the sensors I mentioned remain incorrect.

Digging into logcat now to see what logs I can find

**Comment by dshokouhi** [comment]
> I have no updates pending in the play store, is that what you mean?

Yea just to make sure its up to date since some users had an outdated version and simply updating fixed a lot of issues


> Also I just remembered I have "Lock app" set to true. When I turn that off then the screen no longer freezes on open.

If the lock app feature is causing a freeze we will need to see the logs, if the app is frozen see if waiting ends up triggering a crash or something.  Normally a freeze comes with a crash so we can see where the issue is.

> However the sensors I mentioned remain incorrect.

those sensors only update with the screen on intent if the device is unlocked afterwards it wont update automatically, check the docs to see which sensors update upon a state change and which ones update with other sensors

**Comment by mdegat01** [comment]
Ah gotcha, didn't realize that. Also I didn't realize logcat had to be force closed and re-opened after changing adb permissions so that's my bad. I fixed that, reproduced the issue with locking turned on and here's what I got:
```
<<< log_count = 35 >>>
[01-10 23:24:12.527 1457:3554 I/ActivityTaskManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.homeassistant.companion.android/.launch.LaunchActivity bnds=[657,559][856,790]} from uid 10050

[01-10 23:24:12.581 1457:1517 D/ArtManagerInternalImpl]
/data/misc/iorapd/io.homeassistant.companion.android/547/io.homeassistant.companion.android.webview.WebViewActivity/compiled_traces/compiled_trace.pb doesn't exist

[01-10 23:24:17.479 1457:4215 W/AppOps]
Noting op not finished: uid 10001 pkg io.homeassistant.companion.android code 79 startTime of in progress event=1610339057236

[01-10 23:24:17.479 1457:4215 W/AppOps]
Noting op not finished: uid 10001 pkg io.homeassistant.companion.android code 79 startTime of in progress event=1610339057236

[01-10 23:24:20.212 1457:4187 W/AppOps]
Noting op not finished: uid 10001 pkg io.homeassistant.companion.android code 79 startTime of in progress event=1610339059960

[01-10 23:24:20.212 1457:4187 W/AppOps]
Noting op not finished: uid 10001 pkg io.homeassistant.companion.android code 79 startTime of in progress event=1610339059960

[01-10 23:24:23.323 1457:1471 I/ActivityTaskManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.homeassistant.companion.android/.launch.LaunchActivity bnds=[657,559][856,790]} from uid 10050

[01-10 23:24:23.411 1457:1517 D/ArtManagerInternalImpl]
/data/misc/iorapd/io.homeassistant.companion.android/547/io.homeassistant.companion.android.webview.WebViewActivity/compiled_traces/compiled_trace.pb doesn't exist

[01-10 23:24:30.585 1457:3511 I/ActivityTaskManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.homeassistant.companion.android/.launch.LaunchActivity bnds=[657,559][856,790]} from uid 10050

[01-10 23:24:30.641 1457:3511 I/ActivityTaskManager]
START u0 {cmp=io.homeassistant.companion.android/.webview.WebViewActivity (has extras)} from uid 10001

[01-10 23:24:30.738 1457:3511 D/ConnectivityService]
requestNetwork for uid/pid:10001/31141 NetworkRequest [ TRACK_DEFAULT id=2611, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10001 AdministratorUids: [] RequestorUid: 10001 RequestorPackageName: io.homeassistant.companion.android] ]

[01-10 23:24:30.738 1457:1906 D/WIFI_AWARE_FACTORY]
got request NetworkRequest [ TRACK_DEFAULT id=2611, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10001 AdministratorUids: [] RequestorUid: 10001 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5

[01-10 23:24:30.738 1457:1858 D/WifiNetworkFactory]
got request NetworkRequest [ TRACK_DEFAULT id=2611, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10001 AdministratorUids: [] RequestorUid: 10001 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5

[01-10 23:24:30.739 1457:1907 D/Ethernet]
got request NetworkRequest [ TRACK_DEFAULT id=2611, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10001 AdministratorUids: [] RequestorUid: 10001 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5

[01-10 23:24:30.739 1457:1858 D/UntrustedWifiNetworkFactory]
got request NetworkRequest [ TRACK_DEFAULT id=2611, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10001 AdministratorUids: [] RequestorUid: 10001 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5

[01-10 23:24:30.739 2226:2226 D/PhoneSwitcherNetworkRequstListener]
got request NetworkRequest [ TRACK_DEFAULT id=2611, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10001 AdministratorUids: [] RequestorUid: 10001 RequestorPackageName: io.homeassistant.companion.android] ] with score 60 and providerId 5

[01-10 23:24:30.818 1457:1517 D/ArtManagerInternalImpl]
/data/misc/iorapd/io.homeassistant.companion.android/547/io.homeassistant.companion.android.webview.WebViewActivity/compiled_traces/compiled_trace.pb doesn't exist

[01-10 23:24:30.819 1457:1517 I/ActivityTaskManager]
Displayed io.homeassistant.companion.android/.webview.WebViewActivity: +226ms

[01-10 23:24:30.826 31141:31141 I/WM-SystemFgDispatcher]
Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }

[01-10 23:24:30.835 1457:1457 D/BiometricService]
Package: io.homeassistant.companion.android Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 1

[01-10 23:24:30.838 1457:1457 V/FingerprintService]
startAuthentication(io.homeassistant.companion.android)

[01-10 23:24:30.838 1457:1457 V/FingerprintService]
starting client AuthenticationClientImpl(io.homeassistant.companion.android) targetUserId: 0 currentUserId: 0 cookie: 2106460118/2106460118

[01-10 23:24:30.873 1457:1457 W/FingerprintService]
client io.homeassistant.companion.android is authenticating...

[01-10 23:24:31.003 1457:2112 W/AppOps]
Noting op not finished: uid 10001 pkg io.homeassistant.companion.android code 79 startTime of in progress event=1610339070867

[01-10 23:24:31.003 1457:2112 W/AppOps]
Noting op not finished: uid 10001 pkg io.homeassistant.companion.android code 79 startTime of in progress event=1610339070867

[01-10 23:24:31.036 1457:1457 D/NotificationService]
0|io.homeassistant.companion.android|42|null|10001: granting content://settings/system/notification_sound

[01-10 23:24:31.037 1457:1457 D/NotificationService]
0|io.homeassistant.companion.android|42|null|10001: granting content://settings/system/notification_sound

[01-10 23:24:31.047 1965:1965 D/InterruptionStateProvider]
No bubble up: not allowed to bubble: 0|io.homeassistant.companion.android|42|null|10001

[01-10 23:24:31.048 1965:1965 D/InterruptionStateProvider]
No heads up: unimportant notification: 0|io.homeassistant.companion.android|42|null|10001

[01-10 23:24:31.100 1965:1965 D/InterruptionStateProvider]
No bubble up: not allowed to bubble: 0|io.homeassistant.companion.android|42|null|10001

[01-10 23:24:31.102 1965:1965 D/InterruptionStateProvider]
No heads up: unimportant notification: 0|io.homeassistant.companion.android|42|null|10001

[01-10 23:24:31.270 31141:31261 I/WM-WorkerWrapper]
Worker result SUCCESS for Work [ id=5981c5a4-b822-410f-bab8-617df83648a5, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]

[01-10 23:24:31.279 1457:1865 D/ConnectivityService]
releasing NetworkRequest [ TRACK_DEFAULT id=2611, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10001 AdministratorUids: [] RequestorUid: 10001 RequestorPackageName: io.homeassistant.companion.android] ] (release request)

[01-10 23:24:33.016 1457:1457 V/FingerprintService]
onAuthenticated(true), ID:192321785, Owner: io.homeassistant.companion.android, isBP: true, listener: com.android.server.biometrics.fingerprint.FingerprintService$BiometricPromptServiceListenerImpl@a26e142, requireConfirmation: false, user: 0

[01-10 23:24:33.018 1457:1457 V/FingerprintService]
Done with client: io.homeassistant.companion.android
```
No exceptions unfortunately, not sure if that helps.

**Comment by mdegat01** [comment]
Actually wait I did it again and this time I did get an exception. Not sure what changed:
```
[01-10 23:28:47.126 31141:31141 E/LaunchPresenter]
Issue updating Registration
io.homeassistant.companion.android.common.data.integration.IntegrationException
	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.updateRegistration(IntegrationRepositoryImpl.kt:114)
	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$updateRegistration$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
I didn't get it until after force-closing and re-opening though, it didn't happen on the freeze.

**Comment by dshokouhi** [comment]
We may need to see the full logs zipped up during that time period `01-10 23:24:30.585` to `01-10 23:24:33.018` but i dont see any errors here.

The exception you posted is safe to ignore it happens sometimes when we can't reach HA which happens upon app launch.  Its unrelated to this.  Its also a caught exception so the app wouldn't crash here.

**Comment by mdegat01** [comment]
So the logs from that exact period are gone unfortunately. Sorry I had pressed clear to reproduce to isolate each try. But I reproduced it again and here's the complete logs from that period:
[Logs 01-10 23-36-23.968 to 01-10 23-36-38.596.txt](https://github.com/home-assistant/android/files/5794029/Logs.01-10.23-36-23.968.to.01-10.23-36-38.596.txt)

**Comment by dshokouhi** [comment]
So when you hit this particular case, if I am understanding it correctly, you never get presented with the Biometric prompt when you open the HA because the app is frozen?

**Comment by mdegat01** [comment]
Yes, that's it. Everything seems to work fine if I turn off locking. I figure out how to change it to PIN only to see if its related specifically to the biometric lock or to any lock though.

**Comment by dshokouhi** [comment]
Ok I still need to look at the logs but I am unable to reproduce on my pixel 4 xl using face unlock or pattern. I'm always presented with the prompt when I open the app and it doesn't freeze following the steps you outlined. Have you tried clearing data and starting over again to see if it fixes it?

**Comment by mdegat01** [comment]
Actually yea, looks like that fixed it. I can't reproduce it anymore after clearing the data and refreshing. Looks like its all good then, thanks for your help!
