### ISSUE TITLE
Add command to turn on/off location setting 

### ISSUE THREAD

**Issue by cananda** [home-assistant/android#1291]
**Is your feature request related to a problem? Please describe.**
Currently, location is always enabled allowing some apps to collect data unnecessarily or save battery when location is not needed. Although, location permission can be granted on an app basis, it's ideal to turn on/off gps when needed.  

**Describe the solution you'd like**
Add a command to run on/off location just like DND/Bluetooth etc which can be then used in automation.  Some examples of automation:
- When leaving home (device tracker), enable location
- When sleep routine, disable location
- When in car, scan a NFC tag to invoke automation (arm house, turn off lights, enable location/bluetooth etc)

**Describe alternatives you've considered, if any**
None, I do this manually and it is annoying.

**Comment by dshokouhi** [comment]
I dont think android exposes location like that for us to programmatically turn it on/off like we can with DND and bluetooth etc...

Not to mention a lot of the app is dependent upon location being enabled for features like WiFi detection to work. Yes you need GPS and location enabled for the app to read the SSID when you are at home to use the home URL.  Do you use the internal conneciton URL? Do you use the WiFi sensors? If so those will cease to work when you turn off location.

**Comment by cananda** [comment]
Yes, I do use internal connection URL (I'm okay to use external URL when Wifi is off) and Wifi sensors (I'm ok if they are unavailable).

**Comment by dshokouhi** [comment]
> Yes, I do use internal connection URL (I'm okay to use external URL when Wifi is off) and Wifi sensors (I'm ok if they are unavailable).

There is no way to programmatically turn off location by Android API. Going to close this unless someone can point out the API docs to do this which I don't see as possible.
