### ISSUE TITLE
[Feature request] GPS Sensor is updated too slowly

### ISSUE THREAD

**Issue by sblantipodi** [home-assistant/android#1293]
Hi guys,
is it possible to select the maximum frequency between the updates?

My GPS data is sent too slowly.
I set the minimum time between updates to 60000 milliseconds but the position is updated, let's say, every 5 minutes if all is ok.

Is it possible to force an update every 60 seconds?

Thanks

**Comment by dshokouhi** [comment]
Sorry this is as frequently as we have it to remain battery friendly. If you use Google maps for navigation while driving it will update every 30 seconds as the location is passively received. We have a lot of logic around this.  Minimum time between update is still subject to a few checks as well.
