### ISSUE TITLE
Actionable notification URI lovelace redirect not working if app is open

### ISSUE THREAD

**Issue by muniter** [home-assistant/android#1295]
**Home Assistant Android version:** 3.0.2-full

**Android version:** 10QKQ1.190825.002

**Phone model:** Mi 9T Pro

**Home Assistant version:** 2021.1.1

**Last working Home Assistant release (if known):**

**Description of problem:**

Actionable Notification URI `clickAction` not working if application is already open. If the app is not open in the background the `clickAction: /lovelace/systems` works as expected, If the app is open in the background it opens the app but does not navigate to the view.

The video first shows the app closed, not in the background I click the notification and takes me to the correct lovelace location, then I change the page, move away from the app leaving it in the background and press another notification which is identical to the previous one, and It opens the app but does not navigate to the correct location.

The data the service was called with:

```json
title: "ClickAction Test"
message: "This notification clickAction:/lovelace/systems"
data:
  clickAction: "/lovelace/systems"
```

[![Video of the Issue](http://img.youtube.com/vi/lsjLh8CWWyI/0.jpg)](http://www.youtube.com/watch?v=lsjLh8CWWyI "Video of the Issue")

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**
Seems like the issue has been reported multiple times, but has been hard to reproduce? https://github.com/home-assistant/android/issues/467 https://github.com/home-assistant/android/issues/486

**Comment by dshokouhi** [comment]
I am unable to reproduce this following the steps provided.  The app always reloads to the tab regardless if the app is open or not.  Can you try and start fresh with the android app to see if that solves the issue?  https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by RichardUUU** [comment]
I am also having this problem.

**Comment by dshokouhi** [comment]
> I am also having this problem.

please see my above comment

**Comment by RichardUUU** [comment]
Right. Fixed.

**Comment by muniter** [comment]
> I am unable to reproduce this following the steps provided. The app always reloads to the tab regardless if the app is open or not. Can you try and start fresh with the android app to see if that solves the issue? https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

I have followed this instructions and tested around 20 times and **It's working without any issue**, thank you @dshokouhi for your help. And for your great work. I'll now close this issue.
