### ISSUE TITLE
status does not change from 'Home'.

### ISSUE THREAD

**Issue by oliverkurth** [home-assistant/android#1302]
**Home Assistant Android version:**
3.0.2-full

**Android version:**
8.1.0

**Phone model:**
Motorola G5

**Home Assistant version:**
2021.2.0.dev20210115

**Last working Home Assistant release (if known):**
n/a

**Description of problem:**
status does not change from "Home", although sensor.moto_g_5_plus_geocoded_location was updated.

I have an automation that should trigger when I leave home, but it does not work reliably. Weird is that in the history it shows it never left home, however the history for the geocoded location did. So it looks like the app did indeed notice that GPS changed, and therefore this does not seem to be an issue with GPS or the phone.

The address seen in the screenshot (North Bend) is more than 30 minutes away from home. I just came back from a hiking trip.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```
n/a

**Screenshot of problem:**

<img width="428" alt="Screen Shot 2021-01-17 at 6 14 39 PM" src="https://user-images.githubusercontent.com/6658518/104865390-b0690500-58f0-11eb-916a-9594932ba4d5.png">
<img width="419" alt="Screen Shot 2021-01-17 at 6 14 02 PM" src="https://user-images.githubusercontent.com/6658518/104865393-b232c880-58f0-11eb-8f4b-690746fec6fa.png">

**Additional information:**

n/a

**Comment by dshokouhi** [comment]
First please make sure to update to the latest production version that was pushed out yesterday. 2021.1.1-full

If that doesn't work please try https://companion.home-assistant.io/docs/troubleshooting/faqs#location-is-not-updating-in-android-app

**Comment by oliverkurth** [comment]
I have seen that FAQ. From the bug description it should be clear that it does not apply.

**Comment by dshokouhi** [comment]
Geocoded location sensor does not work the same way location tracking does. Can you please update the app first?

**Comment by oliverkurth** [comment]
Updated. Not sure when I will leave home again to see if it makes any difference.

**Comment by dshokouhi** [comment]
Make sure to follow the FAQ please those steps are there for a reason. The device tracker does not work in the same way the sensors do. We need to ensure the location tracking is enabled properly to get updates in the background. Geocoded location only polls for the last update known to the API which is not the same as subscribing to updates.

**Comment by oliverkurth** [comment]
Okay, I just checked:

* Ensure the app has location permissions granted, all the time.

check

* Ensure that location (GPS) is enabled on your device.

check

* Turn off battery optimizations for the app.

I don't think Android 8 has that. I don't see anything related in the Android settings.

* Ensure that all 3 of the Location toggles are enabled in App Configuration > Manage Sensors in the Android app.

check, all 3

* Turn on unrestricted data for the Android app.

I cannot find a setting. But I can manipulate my lights at home when I am away.

* Check that background access setting under App Configuration shows the app has proper access.

Again, I cannot find a setting.


One thing may be worth to note: I use OpenVPN to connect to my home network (and only for that). I don't *think* this is related, but who knows. But obviously the location was updated or HA (which is at home) wouldn't have known about it.

**Comment by dshokouhi** [comment]
> I don't think Android 8 has that. I don't see anything related in the Android settings

It does every device is different. You'll need to research your own device and find out where. Usually in Android settings for the app.



> I cannot find a setting. But I can manipulate my lights at home when I am away.

It's there you just have to find it. Check in Android settings.



> I cannot find a setting. But I can manipulate my lights at home when I am away.

It's in App Configuration screen for the Android app. Like where you manage sensors and see the connection URL etc...

**Comment by dshokouhi** [comment]
Going to close this now, if you still have issues with location trackign then please get us the device logs as mentioned in the issue template.  We need to look at the decision making process here to determine what to fix (if anything).

**Comment by oliverkurth** [comment]
Okay, I found the settings. Only one that was not on was "unrestricted data usage". Let's see if it makes a difference.
