### ISSUE TITLE
Save fails as Position YAML entry for domain:cover not set until ui element interacted with

### ISSUE THREAD

**Issue by rexbron** [home-assistant/android#1304]
**Home Assistant Android version:** 2021.1.1

**Android version:** 11 January 5th patch

**Phone model:** Pixel 3a

**Home Assistant version:** 2021.1.1

**Last working Home Assistant release (if known):** Unknown

**Description of problem:**

When editing an existing automation and adding a device action with Domain:cover, the UI editor sets the default position to 0 but does not add the Position: yaml until the ui is interacted with. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Can you reproduce on chrome for Android?

**Comment by rexbron** [comment]
Reproduced with Brave (Chromium based) on Android.

**Comment by dshokouhi** [comment]
> Reproduced with Brave (Chromium based) on Android.

Please open an issue in the frontend repo. They have their own issue template that asks for certain things to be checked. You'll need to fill that out fully so I am going to close this as it doesn't make sense to transfer given their template.

**Comment by rexbron** [comment]
I don't this the issue should be closed, but rather reference https://github.com/home-assistant/frontend/issues/7993 and marked won't fix or something else to denote that it is still an issue that needs to be fixed elsewhere.
