### ISSUE TITLE
Location popup persists even when all sensors are off

### ISSUE THREAD

**Issue by dougcwb** [home-assistant/android#1305]
I'm using a Xiaomi Redmi note 8 pro

Since the last android app update, everytime I open or switch back to the app, it shows a popup to enable location on the phone. 
I already tryed to switch off all the smartphone sensors, but the message still persists with the SSID option.
![Screenshot_2021-01-18-14-49-42-513_io homeassistant companion android](https://user-images.githubusercontent.com/28490586/105025302-eb238800-5a2b-11eb-9d2d-5e202f94747b.jpg)
Please remove this popup.
![Screenshot_2021-01-19-07-57-34-532_io homeassistant companion android](https://user-images.githubusercontent.com/28490586/105025595-4bb2c500-5a2c-11eb-832c-a12254385c9e.jpg)

**Comment by dshokouhi** [comment]
The pop-up tells you that you cannot use the internal connection URL while location is off.  So you did not follow the pop-up correctly.  Anything in the app that depends on the app knowing the connected SSID requires location and GPS enabled.
