### ISSUE TITLE
Add option to start Wireguard automatically when the home wifi SSID is not in use

### ISSUE THREAD

**Issue by antlarr** [home-assistant/android#1306]
**Is your feature request related to a problem? Please describe.**
When I leave home I need to start the Wireguard VPN on my phone to be able to connect to Home Assistant. The problem is sometimes I forget to start it so sensors/phone location are not updated in HA (so automations based on those sensors don't work) and push notifications do not reach my phone until I remember to turn on the Wireguard VPN.

**Describe the solution you'd like**
It would be nice if HA Companion started the Wireguard tunnel automatically when the internal url can't be reached, the home wifi SSID is not being used/detected, the location is outside the home zone, the external url is being used or any combination of those options you think it's appropriate (probably checking the SSID in use is the easiest case, might work good enough and I guess HA Companion already checks that so it wouldn't increase the power usage of the app).

To be more precise, some configuration options would need to be added:
* A "Start wireguard tunnel when outside home wifi" checkbox that enables all this.
* A "Wireguard tunnel name to start" option where the user can enter the name of the Wireguard tunnel to turn on.

Also, it might be worth adding a "Stop wireguard tunnel when home wifi detected" that disables the wireguard tunnel when the home wifi SSID is detected.

Just in case it helps to implement this feature, [this reddit comment](https://www.reddit.com/r/tasker/comments/fn6wou/wireguard_now_supports_control_by_remote_apps/fl93kw8/?utm_source=reddit&utm_medium=web2x&context=3)  explains how to turn on/off a wireguard tunnel from an external application using intents.

**Describe alternatives you've considered, if any**

A more generic alternative might be to provide configuration options so the user can define any intent to be sent to any application when the SSID is detected/not detected or when the phone goes in or out of a zone (an automation happening on the phone as there might be no connection to the HA core). In any case, just providing an option to start/stop a Wireguard tunnel might be enough for most users.

**Comment by dshokouhi** [comment]
Sorry we will not be hard coding and adding in the permissions for wireguard like that link.  If they accept broadcast intents you can use [command broadcast](https://companion.home-assistant.io/docs/notifications/notification-commands#broadcast-intent)

**Comment by antlarr** [comment]
> Sorry we will not be hard coding and adding in the permissions for wireguard like that link. If they accept broadcast intents you can use [command broadcast](https://companion.home-assistant.io/docs/notifications/notification-commands#broadcast-intent)

I understand that hardcoding the intent might not be wanted, that's why I mentioned maybe an alternative was a config option where the user could define any kind of intent (similar to what tasker does), instead of hardcoding the wireguard one.

In any case those kind of automations you proposed work on the Home Assistant core, so if HA Companion lost its connection to the core (which is the whole reason why one would want this intent sent to wireguard) there's no way the automation would be able to successfully execute the command_broadcast_intent action, right?

**Comment by dshokouhi** [comment]
Notifications use FCM: https://companion.home-assistant.io/docs/notifications/notification-details

**Comment by antlarr** [comment]
> Notifications use FCM: https://companion.home-assistant.io/docs/notifications/notification-details

I see. Very nice! I didn't know that.

Still, from what I can read from [this line of Wireguard source code](https://github.com/WireGuard/wireguard-android/blob/5b5ba88a97b5310c532b42b526f78d1c747965f8/ui/src/main/java/com/wireguard/android/model/TunnelManager.kt#L231) it seems wireguard needs to be passed the name of the tunnel to turn on as an extra and there's currently no support for that. So something like this might be needed to be added around this line (https://github.com/home-assistant/android/blob/fdd734a0e9cb6dad8325f56fea45664205e6b3f7/app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt#L358) in order to support generic Extra strings to be passed to an intent (please note I've never developed in kotlin so there might be some errors):

```kotlin
                    for (entry in data.entries) {
                        if (entry.key != "channel") {
                            intent.putExtra(entry.key, entry.value)
                        }
                    }

```

That way one would be able to use this as service data:

```yaml
message: "command_broadcast_intent"
title: "com.wireguard.android.action.SET_TUNNEL_UP"
data:
   channel: "com.wireguard.android"
   tunnel: "tunnel-name"
```

And the tunnel name would be added as an extra to the intent.

**Comment by rhpijnacker** [comment]
@antlarr This looks like an awesome feature!
Is there some documentation that describes in detail how to set this up?
I would really like to enable this for my phone too.

**Comment by evadim** [comment]
@rhpijnacker 

As I can understand, one should create HA automation to send spesial type of notification:  command broadcast.
Via this notification you can send request to enable Wireguard tunnel. As notifications use Google Firebase Cloud, they received whenever phone have internet connection.

For me this is showstopper as I have no plans to inform Google every time I enable VPN access (or anything in HA).
