### ISSUE TITLE
NFC Tag: Write NFC tag UID as HASS tag ID

### ISSUE THREAD

**Issue by kmdm** [home-assistant/android#1307]
**Is your feature request related to a problem? Please describe.**

When using the NFC tags at the moment the Home Assistant app generates a seemingly random tag ID and writes it to the NFC tag. This works fine when using the phone as the tag reader. 

However, for example, the PN 532 esphome solution only uses the tag UID for generating tag events for Home Assistant which leaves a potential for two tag IDs per tag in the solution depending on the reader used. 

**Describe the solution you'd like**

It would be great if the App could have an option to write the tag UID back to the tag as the Home Assistant tag ID, that way the ID would be consistent across readers. 

**Describe alternatives you've considered, if any**

I can write the UID back to the tag using the App by reading the tag, editing the tag ID and then using the "Duplicate" option since the text field isn't read only. 

This creates a tag configured as I'd like, however, it doesn't update the tag IDs in the Configure -> Tags settings area in Home Assistant (and there's no reason it should given I claimed I was duplicating the tag)!

**Additional context**

**Comment by dshokouhi** [comment]
Sorry this was a decision made to keep the companion apps in sync. This is so the apps can detect the tag easily and parse it. This is for Android and iOS.

**Comment by kmdm** [comment]
Presumably that means that it's not possible for the IOS app to do the same thing / have the same option? :(

**Comment by dshokouhi** [comment]
> Presumably that means that it's not possible for the IOS app to do the same thing / have the same option? :(

Yup Android and iOS companion apps.

**Comment by kmdm** [comment]
Sorry, what I meant was is it not possible in IOS to read the tag UID and then use that as the ID to write back in the home-assistant.io/... URI?

(I know nothing about Apple/IOS.)

**Comment by dshokouhi** [comment]
> Sorry, what I meant was is it not possible in IOS to read the tag UID and then use that as the ID to write back in the home-assistant.io/... URI?
> 
> (I know nothing about Apple/IOS.)

This is what I meant by a decision was made. The way you see it work today is the intended implementation.

**Comment by kmdm** [comment]
Yes. Sorry. I know it's the intended implementation, that's why I logged it as a feature request. 

Is there a place this can be discussed in the context of both apps (and the complete HASS ecosystem) for consideration?

**Comment by dshokouhi** [comment]
> Yes. Sorry. I know it's the intended implementation, that's why I logged it as a feature request.
> 
> Is there a place this can be discussed in the context of both apps (and the complete HASS ecosystem) for consideration?

Your can try the architecture repo

**Comment by kmdm** [comment]
I know it's not an accepted feature but in-case anyone is "playing along at home":

Rough and ready implementation https://github.com/kmdm/hass-android-companion/tree/nfc-use-tag-uid

(Go easy. I don't often do Android/Kotlin dev!)
