### ISSUE TITLE
Wifi location not updating when connecting to Home WIFI when arriving home.

### ISSUE THREAD

**Issue by WedHumpDay** [home-assistant/android#1309]
**Home Assistant Android version:**
2021.1.1-full

**Android version:**
Android 9 & Android 10

**Phone model:**
Note 8 & Galaxy S9

**Home Assistant version:**
2021.1.4

**Last working Home Assistant release (if known):**

**Description of problem:**
Arriving home both phones are not updating location to Home status when connecting to the Wifi. Have to wait until GPS updates location. Even while the phone is awake in use, it only updates via GPS.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Device tracker only updates via GPS, wifi is not taken to account here.  You can use wifi in your automations if it works better and faster for you.  For device tracker make sure zone tracking is enabled in the app as it should help with faster detection but in all honesty nothing will be as fast as the wifi connection sensor which sends a state update upon any change.
