### ISSUE TITLE
Possibility to refresh the app after restarting HA ?

### ISSUE THREAD

**Issue by browetd** [home-assistant/android#1310]
**Is your feature request related to a problem? Please describe.**

When I restart HA, sometimes (not always), there is a pop-up window with "Impossible to connect to Home Assistant" and three buttons: "Wait" "Refresh" "Parameters"... The pop-up windows stays like this for ever... The only way to have the app working again is to manually hit the "Refresh" button in that pop-up window...
**Describe the solution you'd like**

Two ways I would like to happen:
1. The App is detecting that the address is reachable again and execute a refresh automatically... (preferred method)
2. When HA is up at startup, send a "Refresh" command from an automation in HA to refresh the App on specific devices...
**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
The app does not get notified about HA being restarted however what I can tell you is that most of my devices recover successfully once HA is up and running.  I wonder if the app is hitting an edge case here as the pop-up should go away once it can reconnect. It should be checking every 10 seconds but seems we are not also canceling the pop-up during this interval if we reconnect.  I am not sure if the variable here updates as we expect 

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L932

**Comment by dshokouhi** [comment]
Another thing to check is how often the external bus sends this: https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L368

Not really sure how to get this to trigger again...

**Comment by tunerooster** [comment]
What is the status on this. What are the chances it will be fixed?

Thanks!

(Sorry if multiple posts.  I'm not sure what I am doing...  :)

**Comment by dshokouhi** [comment]
> What is the status on this. What are the chances it will be fixed?
> 
> Thanks!
> 
> (Sorry if multiple posts.  I'm not sure what I am doing...  :)

We are a group of volunteers it will get worked on whenever someone decides to work on it.

**Comment by tunerooster** [comment]
Thank you, I understand.  I wasn't trying to be pushy, just seeking available information.  ...really appreciate what you are doing.  HA is the best!

**Comment by tunerooster** [comment]
Further to the symptoms (in my case):

When the "Unable to connect WAIT, REFRESH, SETTINGS" message pops up...

* The process is completely hung.
* None of the sensors update.
* The camera feeds do not refresh.
* No changes in entity state are updates.
* It shows up as "Unavailable" in the browser_mod created entities:
  ...from another HA client (i.e., media_player, light, and sensor)
* There is no response to any of the browser_mod commands, like:
  . browser_mod.lovelace_reload
  . browser_mod.window_reload
  or even:
  . browser_mod.debug
* So, there is no way to refresh via Home Assistant, or otherwise.
* It requires manual intervention.

...in case any of this helps...

**Comment by dshokouhi** [comment]
can you guys check if this is fixed in HA 2021.2.1?

**Comment by tunerooster** [comment]
Yes, it appears to be fixed in 2021.2.1!

It has stayed up for over 24 hours straight now.

I did notice one instance where the message popped up, but it automatically refreshed immediately, and the message went away.

Thanks for fixing this!

**Comment by browetd** [comment]
I let my two instances run a few days with HA 2021.2.1...  I restarted many times and recovered automatically... Fixed for me too...  Thanks for your fix !  Great job !
