### ISSUE TITLE
Option to ignore "Location is disabled" question

### ISSUE THREAD

**Issue by cyclops1982** [home-assistant/android#1311]
**Is your feature request related to a problem? Please describe.**
The feature is related to https://github.com/home-assistant/android/pull/1187 (I commented there as well)

Since the update of the android app, the app keeps asking me to turn on location. It's annoying as it even happens when you quickly switch to another app.

I do not have my location on within android settings all the time. It's very specific choice i make. Before this pull request was merged, it meant that the sensors that were dependent on that didn't work - that was fine for me.

I use these sensors primarily to see the location of our family members. it's really practical as (when you want to) turn on GPS and then you can see on a map where the rest of the family is. I go for a run, which isn't that dangerous in itself, but it's a comforting feeling for my wife to know where i am. I can see when my wife is on here way back from wherever she was and start making food in time. 
Of course, i understand that tracking the location /requires/ GPS to be on, but i don't have GPS on all the time when i'm at home... or when i don't want to be tracked. If i'm away /with/ the family, then google doesn't have to know where i am.

**Describe the solution you'd like**
The current dialog shows yes, or no.
I'd like to add "no, don't ask me again, i know that the sensors won't work when i have location turned off" (or of course, a little checkbox that says "don't ask again"
This preference would ideally be stored in a setting that you can later undo again.

**Describe alternatives you've considered, if any**
Make a setting that would allow me to not perform the check.

**Additional context**
Overall, i'm a very happy HA user :-)

**Comment by chriss158** [comment]
I can understand that this popup is annoying. But i also think this message should be quite annoying :) because the app is is not set up correctly which can lead to certain users not noticing this.

The problem with this checkbox "don't ask again" is: Once this checkbox is clicked. This location check is basically turned off forever. 

An alternative would be to show a notification which cannot be cleared. So casual user can see that the app is not setup correctly. And can easy fix the problem.
On the other hand power user can mute the notification channel to remove the notification.
<img src="https://user-images.githubusercontent.com/12832850/105611851-2caf8c80-5db8-11eb-9ae6-df1107c94598.png" width="40%">

Maybe this would be a solution.

**Comment by dshokouhi** [comment]
> An alternative would be to show a notification which cannot be cleared. So casual user can see that the app is not setup correctly. And can easy fix the problem.
> On the other hand power user can mute the notification channel to remove the notification.

I think this is a great approach as for certain important things we do notify the user like when we detect a database corruption for example.  Also it would be similar approach to what #1265 is trying to achieve.

Notification channels are a prefect way to keep all users happy and informed I think :)

**Comment by cyclops1982** [comment]
Would i be able to disable that notification (without disabling other notifications from HA)?

Let's be clear - i spend most of my time at home and with the location turned off. It would mean that i primarily have a notification that would get in the way of other stuff right?

Maybe it's easier to just have a setting in the settings of the app, that goes "Disable permissions check before sensor reading" and it is disabled by default. This way, users who don't like it can just enable that. 
This means no change to the current behaviour, and people can choose what to do. it's also a choice that people have to make very clearly and would have to search for.

**Comment by chriss158** [comment]
> Would i be able to disable that notification (without disabling other notifications from HA)?

Yes you would be able to disable this notification without disabling other notifications. The notification uses a separate notification channel.

> Let's be clear - i spend most of my time at home and with the location turned off. It would mean that i primarily have a notification that would get in the way of other stuff right?

No if you disable this notification channel there is no "Location disable" notification.

**Comment by cyclops1982** [comment]
Sounds great!

**Comment by soxhi8** [comment]
I would like to add, that previously users could not know that they needed location services for e.g. the internal network address. Having the pop-up everytime someone looks at the very specific setting that they want to work, might already be enough.
Going from no clues to 100% full time pop-up is a little much for one change.
