### ISSUE TITLE
[Bug] MQTT Device Info

### ISSUE THREAD

**Issue by drinfernoo** [home-assistant/android#1312]
I was just randomly looking into one of my MQTT devices, and found that the "MQTT Info" view is apparently broken on Android:

![](https://imgur.com/hfqA5Uw.png)

The dialog is pretty much fine in landscape orientation, but not in portrait.

**Comment by dshokouhi** [comment]
Can you reproduce in chrome for android?

**Comment by drinfernoo** [comment]
Sure can!

![](https://imgur.com/Lfaifp2.png)

**Comment by dshokouhi** [comment]
Ok this is a HA frontend issue then.  Going to close this as that team has a different bug report template that needs to get filled out.  You should also double check the open issues to see if it doesn't exist first.

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=BUG_REPORT.md
