### ISSUE TITLE
Add the ability to exclude certain apps from "last notification" sensor

### ISSUE THREAD

**Issue by Vedeneb** [home-assistant/android#1315]
**Is your feature request related to a problem? Please describe.**

The "last notification" sensor does not have the option to **exclude** certain apps. Some (mostly persistent) notifications make the sensor worker update very frequently (see "Additional context").

**Describe the solution you'd like**
I'd like to be able to **exclude** certain apps from the last notification sensor. An option to be able to exclude all persistent/ongoing notifications would be fine too.
Besides, there should be some mechanism that makes sure, the sensor worker won't get triggered too frequently. It took me quite a while to figure out, what caused the sensor worker to update that frequently, so some sort of a warning that a special trigger causes the worker to update too frequently would be very helpful.

**Describe alternatives you've considered, if any**
Currently the user can **include** specific app in the sensor. Since I wan't to get notifications from almost any other app this solution is not ideal, especially because new apps don't get included by default. So when I download a new app I always would have to remember to enable it in the sensor settings.

**Additional context**

I'm using the app "Notify for Amazfit" to control my Amazfit Band 6. It displays my current heartrate, the battery state of the watch and some other information in a notification. Because I have set the band to measure my heartrate continuously, the notification updates very frequently - around once every two seconds. Now the problem: I'd like to use the home assistant app sensor "last notification", however every amazfit notification update triggers this sensor. So around every two seconds the Sensor Worker starts its work and thus my battery is drained extremely fast.

**Comment by dshokouhi** [comment]
Sorry we had decided upon only adding an Allow list here as this sensor can be very chatty and we even recommend in our documentation to use the allow list. Adding a block list complicates things and as this sensor is chatty by nature the allow list cuts down the noise a lot.
