### ISSUE TITLE
Support vacuum entities in the power menu

### ISSUE THREAD

**Issue by Edo78** [home-assistant/android#1318]
**Is your feature request related to a problem? Please describe.**

In the power menu I can see other entities but not the vaccum

**Describe the solution you'd like**

I'd like to control the vacuum from there (at least start/pause/stop)

**Describe alternatives you've considered, if any**

In the power menu I can switch between Home Assistant and (Google) Home so I can control the vacuum from there. Ironically the vacuum itself is exposed to the google assistant through home assistant.

**Additional context**

I'm not 100% sure if this is a feature request or a bug but I haven't found any issue related to vacuum

**Comment by dshokouhi** [comment]
So the toggle can only do 2 actions on the power menu so it didn't make sense to add it there. What would you expect it to do with a toggle? It's kinda weird to do just start and dock or start and pause.

**Comment by Edo78** [comment]
A tap to start and one to stop can be useful ...

**Comment by dshokouhi** [comment]
should it be `vacuum.stop` or `vacuum.return_to_base`? 🤔 

we also need to consider vacuums that do not have the new state model.

https://www.home-assistant.io/integrations/vacuum/
