### ISSUE TITLE
Wear OS app freezes when opening (TicWatch Pro)

### ISSUE THREAD

**Issue by changetotower** [home-assistant/android#1320]
**Home Assistant Android version:**
home-assistant-wear-beta-560-bdbf03b.apk
**Android version:**
Android 11 / Havoc
**Phone model:**
Xiaomi Mi MIX 3 5G / TicWatch Pro (2018)
**Home Assistant version:**
Home Assistant OS 5.10 / core-2021.1.5
**Last working Home Assistant release (if known):**
none
**Description of problem:**
When opening the Wear OS app on my TicWatch Pro (2018), it freezes at the Home Assistant Logo.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
The wear OS app actually has 0 functionality right now, I think as of now its just an APK and nothing more which is why its only on GitHub.

**Comment by LeonPro12** [comment]
When will the Wear OS functionality come?

**Comment by dshokouhi** [comment]
> When will the Wear OS functionality come?

When it's ready

**Comment by dshokouhi** [comment]
Closing as the app does not freeze, it just shows the app icon and thats it. There is no functionality now as only some groundwork has been laid out.  Once something is functional we should see the app published so you don't have to sideload it.
