### ISSUE TITLE
"Location is Disabled" popup is unnecessary and annoying

### ISSUE THREAD

**Issue by spacejim** [home-assistant/android#1322]
**Home Assistant Android version:**
2021.1.4

**Android version:**
All
**Phone model:**
All
**Home Assistant version:**
2021.1.4
**Last working Home Assistant release (if known):**

**Description of problem:**
In the latest android release the app introduced a popup titled "Location is disabled".  This is triggered any time you have your phones GPS switched off when the app starts up, is refreshed, or if you switch away from the app and come back.  These popups can also accumulate so you have to close several in a row.

It's common for phone users to have their GPS switched off to save battery and not only is this popup annoying & over-repeated, but its also unnecessary.  A quick look at the app on google play will show recent negative reviews complaining about this issue, and I agree with them that this popup completely ruins the experience and usability of this otherwise outstanding app.

**Screenshot of problem:**
https://gyazo.com/6edf5fedbcf99f4ea0fd29d8fd03e6a8

**Comment by dshokouhi** [comment]
Please check for open and closed issues before opening a new one. This had been changed to become a notification so users can control it's appearance.
