### ISSUE TITLE
Do not set to discharging while still plugged and the battery level reach 100%

### ISSUE THREAD

**Issue by SeLLeRoNe** [home-assistant/android#1324]
**Is your feature request related to a problem? Please describe.**

I remember having discussed this with someone, can't find the issue related tho, I find it very odd that the App set the battery status to "discharging" when battery level reache 100% while still plugged to mains power. It could be useful to report the real status, specially for automations and "live overview" I think. It is nto a specific problem related, at least for now.

**Describe the solution you'd like**

Having the App not to set the battery status to "discharging" when battery level reach 100% while still plugged.
The phone itself report the status as charging and so should do the App in order to have a real view in HA on the status.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
We report whatever the Android API tells us.  We will not modify the API result.  Also I don't see this issue on my pixel so this might be device specific. Please provide more information.

**Comment by SeLLeRoNe** [comment]
That's odd, I always noticed on my phone this behaviour (well not always but for a few months).
I have a OnePlus Nord.

My GF has a Xi Mi 9T Pro, but on that it is also true that the HA doesn't "stay open" no matter what I do and set on the Battery Optimizations, so I was never really able to have a consistent result from her phone (I might need to check on the issues if anyone is having it work on this phone, if not I'll might open a separate issue)

**Comment by dshokouhi** [comment]
Try looking at dontkillmyapp.com they have some good tips there. Make sure the sensor worker channel is left on maybe that's causing issues? I'm going to close this request as we will not be manipulating API data like this.

**Comment by SeLLeRoNe** [comment]
Sure, didn't mean to change the API, I tought the App was doing that on it's own, if that's coming from the APi I agree on not changing it.

I find only very odd seeing my phone with the "charging" simbol and HA saying it is not on a charging state :)

**Comment by SeLLeRoNe** [comment]
And thanks for the site, I'll take a look at that!

**Comment by SeLLeRoNe** [comment]
Found the issue, it goes to "full", that's why my UI was removing the "Charging" text info...

![image](https://user-images.githubusercontent.com/9599441/106157979-88489400-6183-11eb-84a2-3614606731d9.png)
![image](https://user-images.githubusercontent.com/9599441/106159112-c0040b80-6184-11eb-84d4-0716690540b6.png)

Sorry for the pointless issue!
