### ISSUE TITLE
Notification command to toggle wireguard tunnel

### ISSUE THREAD

**Issue by mdegat01** [home-assistant/android#1328]
**Is your feature request related to a problem? Please describe.**

I realize this one is probably kind of a long-shot since its specific to a not particularly popular app but figured it can't hurt to ask :)

I really like the community add-on for [wireguard](https://github.com/hassio-addons/addon-wireguard) and have been using it for a bit to meet my home VPN needs. Sometime last year the Wireguard team worked with Tasker to add support for toggling a tunnel from Tasker. They did it generically though, all tasker actually does is fire an intent that Wireguard is listening for which means the HA android app could do it too.

I am not able to find an obvious documentation site for the Wireguard android app unfortunately. This post [here](https://www.reddit.com/r/tasker/comments/fn6wou/wireguard_now_supports_control_by_remote_apps/fl93kw8/) by the lead developer does describe what Tasker had to do so we can borrow it. 

The intents themselves are pretty straightforward, broadcast `com.wireguard.android.action.SET_TUNNEL_UP` and `com.wireguard.android.action.SET_TUNNEL_DOWN` with `tunnel:<tunnel name>` in the extra to `com.wireguard.android`. The tricky bit is they permission locked the intent. So in order to do this the HA companion app would have to add this to the manifest and declare a new permission:
```
<uses-permission android:name="com.wireguard.android.permission.CONTROL_TUNNELS"/>
```
The first time you try to toggle a tunnel will require user interaction since it will pop-up a prompt asking the user to accept this permission. After that the tunnel can be toggled on/off without any user interaction required. I use it currently for turning on the tunnel when I'm on any wifi other then a fixed list of trusted networks.

**Describe the solution you'd like**

Would love a new command like:
```yaml
message: command_wireguard_tunnel
title: up/down or on/off
data:
  channel: <tunnel name>
```

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
This is similar if not identical to #1306 we will not be hard coding other app permissions into our app like they want, we tried something similar for another app but it was not accepted.  I was under the impression that enabling the `extras` for the broadcast intent should suffice for this?

Even Tasker said no to the permission prompt but seems they added it anyways? https://www.reddit.com/r/tasker/comments/fn6wou/wireguard_now_supports_control_by_remote_apps/flab7sz/

Honestly not really sure how to proceed here.  If we say yes to one app then we are saying yes to other apps.

**Comment by mdegat01** [comment]
Oh sorry, I didn't meant to create a duplicate, I forgot to remove the `is:open` filter when I searched, my fault.

Yea I understand the position. `extras` aren't enough for this particular task, they wanted an explicit permission to ensure that users really meant to grant this other app the ability to turn their VPN tunnel on and off. Which given the nature of the task I can't really blame them.

On one hand, it is an effective way of providing this kind of remote control functionality while maintaining security of the feature since it gives users case-by-case control over it. On the other hand it definitely puts app developers in a tough spot because as you correctly pointed out, if you add one of these then where does it end?

Perhaps if this issue or the other one get left open to gauge if there's enough interest to make it worthwhile? Adding every app-specific permission that gets requested isn't a good approach but if there is enough interest in one particular one then it could be ok.

**Comment by mdegat01** [comment]
Alternatively if you'd prefer to resolve issues this could be a candidate for a discussion. I don't see the discussion tab on this repo but I know some have it.

**Comment by dshokouhi** [comment]
We had a lot of interest in Sleep as Android which was added then pulled, just about as much interest as we see here with wireguard if not more.  Sleep as android did not even need permissions as it was only to register for intents but that was not accepted.  We can leave this open to see what others think.  

The only thing as you pointed out is where will the requests end for hard coded 3rd party code.  One thing we debated on doing was creating our own intent system for other app developers to integrate.  The intents that we currently do are perfect because HA does not need to be aware of them, only the user is.

**Comment by dshokouhi** [comment]
Based on this comment by the wireguard developer, Tasker never added the permission but wireguard added tasker integration

https://www.reddit.com/r/tasker/comments/fn6wou/wireguard_now_supports_control_by_remote_apps/fl93adk/

Unless I am mistaken?

**Comment by mdegat01** [comment]
So I'm not totally sure how it all works. But I can tell you I definitely saw the pop-up the first time I toggled the tunnel and had to accept it. And in permissions for tasker it says "additional permissions" that when clicked shows this
![Screenshot_20210128-015922](https://user-images.githubusercontent.com/2037026/106102006-bd65cf80-610c-11eb-8bd1-d8392df289a0.png)
So I think they did? Otherwise idk how else this would get here

**Comment by mdegat01** [comment]
> We had a lot of interest in Sleep as Android which was added then pulled, just about as much interest as we see here with wireguard if not more. Sleep as android did not even need permissions as it was only to register for intents but that was not accepted. We can leave this open to see what others think.
> 
> The only thing as you pointed out is where will the requests end for hard coded 3rd party code. One thing we debated on doing was creating our own intent system for other app developers to integrate. The intents that we currently do are perfect because HA does not need to be aware of them, only the user is.

I missed this response before. This is a cool idea. I wonder if there could be a tie in to integrations somehow? Like perhaps integrations which connect to a platform that has a mobile app with intents the corresponding mobile app supports and what notification commands to add to associate with those intents. Maybe that could be in the integration manifest? Or some other file.

This could then just become almost like another type of platform for integration developers to leverage. It would allow them to create services, switches, etc. which then communicated directly with the corresponding app on your phone for tasks. Then someone could just make a sleep as android integration and those that use it would get these options, those that don't wouldn't see it.

Although wireguard would still be tricky in this case due to the special permission. That really does kind of gum up the works unfortunately.

**Comment by dshokouhi** [comment]
So we had a quick and brief discussion, we still do not want to add 3rd party code at this time.  If that decision changes then we can look at what to do.  Until then I am going to close this request.

For now the broadcast intent and upcoming intent events allow users to send and receive intents that they want without the app having to know about it.

If wireguard wants to ensure the user is definitely using their app then they should allow users to get some kind of API key or some encrypted password from the app that they can then use to send in as intent extra.  That would solve the need for permissions and allow things to be more secure.

**Comment by mdegat01** [comment]
Makes sense. I was wondering about that too, seemed like a better way to do it. But I guess the challenge there is clearly any app can listen to intents (since that's exactly what Tasker does). So if you just throw an encrypted value in an extra then another app could grab that encrypted value and reuse it.

But the idea of password-protecting an intent makes a lot of sense. Seems like something android should add. Like a "secure extra" that manages encryption/security of that data for you and only allows the value to be read by the targeted package.
