### ISSUE TITLE
Not working on Google TV

### ISSUE THREAD

**Issue by jfiger** [home-assistant/android#1330]
**Home Assistant Android version:**
2021.1.1-full-555_minAPI21(arm64-v8a,armeabi-v7a,x86,x86_64)
**Android version:**
11
**Phone model:**
OnePlus 8
**Home Assistant version:**
2021.1.5
**Last working Home Assistant release (if known):**

**Description of problem:**

Not working on Google TV.
The authentification screen is displayed but cannot enter identifiers

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
We do not support android tv

**Comment by stbeep1** [comment]
> We do not support android tv

**When will the HA app support for Android tv officially? Do you have a timeline about that ? Thank you:)**
