### ISSUE TITLE
Open-source replacement for Google location services for minimal release

### ISSUE THREAD

**Issue by WPettersson** [home-assistant/android#1335]
**Is your feature request related to a problem? Please describe.**

The "minimal" app on f-droid does not do presence location, since the Google Play services are not distributed. This is mentioned on the f-droid page, but it's still functionality that I'd like to see in the f-droid variant.

**Describe the solution you'd like**

https://github.com/lostzen/LOST is an open-source alternative to Google Play services locations APIs. It is a 1:1 replacement for FusedLocationProviderApi, GeofencingApi, and SettingsApi. Including this in the minimal build should allow location services to work. I am happy to try to work on including LOST in the minimal build, I have a little android experience and this feels at the level of something I can do, and also something I can keep an eye on and maintain going forwards.

**Describe alternatives you've considered, if any**

I mentioned using LOST in only the minimal build. It would also be possible to use LOST for the full build. The bonus is that the code base is less split between minimal and full, but this does change a dependency in the full build. I don't know which alternative (LOST only in minimal, or LOST in full, minimal only differs by lacking notifications) is preferred.

**Additional context**

**Comment by dshokouhi** [comment]
Don't think this is going to be viable. Last release was 2017 and last commit was 2018, they are just not active lately. We need something kept up to date if we are going to switch and implement.

**Comment by WPettersson** [comment]
Aah, yeah, sorry, I forget to check how active that project it is. Seems it might have some issues with Android versions > Oreo as well, so probably not going to be viable. Sorry.

**Comment by dshokouhi** [comment]
Closing as the solution offered was not viable, if you do find one in the future please feel free to submit a new feature request for it.
