### ISSUE TITLE
Playing videos motioneye locking up Android Companion App only

### ISSUE THREAD

**Issue by sirweazel** [home-assistant/android#1340]
When running the Android Companion App to play motioneye videos via motioneye supervisor app, trying to play videos causes the connection to disconnect or long delays.

- Supervisor motionEye version: 0.11.0 
- Version core-2021.1.5 
- Version supervisor-2021.01.7 
- Android App Version 2021.1.1-full
- Home Assistant is ran in a VM using provided KVM image and both the guest, host, and home assistant CPU/Memory tools all report plenty of resources.
- Motioneye movies configuration H.264 (.mp4) saved to a samba share actually on the host machine. Videos are 1280x960. Samba performance is fine and i'm only talking about 22MB to 70MB files in testing.  Just few second clips when motion is detected.
- If i drop motioneye resolution to 640x480 videos appear to play fine in the companion App.

Issue only occurs in Andoid app only.  If i open up android chrome on the phone to get to home assistant, videos play fine without issue in motioneye.  Videos play fine from firefox and chrome on workstations.  This tends to indicate something is hanging when trying to play the higher resolution in the app maybe?

Please let me know what other info may be useful in troubleshooting or if i've provided enough info for someone to reproduce.

**Comment by dshokouhi** [comment]
Can you check that android system webview is up to date?  Also what device is this on?  Can you get us the crash logs from the device to see if anything is a miss?  Have you tried clearing data in the app to see if that fixes the issue?

**Comment by sirweazel** [comment]
Phone: Note 8 running Android Version 9
Android system webview: 79.0.3945.116 - but then it says that it's disabled, i think is because android switched to using Chromium based on what i read.
 i haven't tried clearing data yet, but i will. It is a fresh install of the app though.
It does run fine via chrome and the phones built in web browser.

After some more testing, it appears to just struggle with file size and resolution doesn't seem to matter as much.  I dropped back down to 640x480, and it struggles. Sometimes it plays, sometimes i get a disconnected message. If I'm super patient, it will play but with a spinning black circle over the video.  Network speed is not an issue, i'm on the lan and like i mentioned earlier other browsers from the phone appear to render the videos fine and in a quicker manner.

I will try and get you crash logs, but the app doesn't crash, it's really like it looses connection to the web server. This occurs when i get impatient and start tapping around the screen to get out of waiting.  If i wait, and prevent my phone from sleeping, it will eventually play with the spinning back circle.  Once played, i think it is cached locally somewhere and will play faster the next time, but still with the black circle.  Is it possible it is trying to download the whole file instead of streaming instantly like the phone browser or chrome does?
I will try clearing the data and some more testing. I'm not sure if this problem was present before i connected the cloud server, so i will also try disabling that. I do have my wifi network defined and the local lan address defined in the app though.

How would i get logs or enable logging from the app if it isn't actually crashing?

Sorry if i repeated my self a few times, i was typing and trying to reproduce my results at the same time as to not leave any details out.

**Comment by dshokouhi** [comment]
The app uses Android system webview, not sure what we can do if your system devices to disable it.

**Comment by sirweazel** [comment]
Looking into webview was the wrong path, but thank you.

**I think i found the problem:**
I think i found the problem. It's network related in combination with confusion on the app.  I'm trying the Nabu Casa cloud connection. When configuring the app you put in the home assitant url, Home network SSID, and internal connection url.  So after i put in the cloud url, when setting up the home network SSID it appears capitalization matters for the SSID.  I should of known this, but i guess overlooked it.  So if you put the network SSID in and capitalization is off, it uses the cloud connection.  Once i corrected and capitalized the SSID correctly, it is fast again.  I reproduced this a few times.  I also verified on cellular data as well.

So, now that i think i know the problem. How should we proceed?  I feel like the "Home Network WiFi SSID" option should let you pick from a list that your phone is already connected to, or make a descriptive warning that capitalization is important?  I also would like to track down the bottleneck, which i will do outside of this issue tracker.  I know i have sufficient bandwith on my lan/wan, so possibly slow down is with nabu casa [.](https://community.home-assistant.io/t/nabu-casa-cloud-throughput/229785)

Thoughts? Thank you for your help with this.

**Comment by dshokouhi** [comment]
> make a descriptive warning that capitalization is important?

We can add a note saying its case sensitive however by nature WiFi SSID's are ALWAYS case sensitive anywhere you use them.

Wont be able to help much with Nabu Casa as I don't use it.  Might need to ask in the forums or get help from Nabu Casa directly.

**Comment by sirweazel** [comment]
Sounds like a plan. Thank you.  I knew SSIDs were case sensitive, but just over looked it. I can see someone easily not knowing that though, or like me just overlooking and not thinking about it.  Especially since didn't home assistant start selling hardware? If so, i can see home assistant ending up in hands that might not know some of the more technical aspects.  

Is there an indication somewhere in the app if your connection is using cloud connect verses lan?  Maybe change the color of an icon, or add a notification somewhere about connection status? Just thoughts?  But the quickest/simplest is probably like you mentioned adding a note?

**Comment by sirweazel** [comment]
Other question... do you think the "Download" button should work out of the app? I'm able to play the videos, but not download them?

**Comment by dshokouhi** [comment]
> Is there an indication somewhere in the app if your connection is using cloud connect verses lan? Maybe change the color of an icon, or add a notification somewhere about connection status? Just thoughts? But the quickest/simplest is probably like you mentioned adding a note?

No the app does a best effort to use all URL's as we can so theres no real easy way to tell how its connected.  A user shouldn't be concerned with that, just giving us the proper URL's and valid SSID is good enough.



> Other question... do you think the "Download" button should work out of the app? I'm able to play the videos, but not download them?

currently not a supported feature

**Comment by sirweazel** [comment]
Thank you, last 2 questions.
1. Should this issue be left open until a note is added (I see you added a setting label), or should a feature request be opened or something?
2. Since downloads aren't a supported feature, should i open up a feature request for that?

Thanks again for your time. It's very much appreciated.

**Comment by dshokouhi** [comment]
> 1. Should this issue be left open until a note is added (I see you added a setting label), or should a feature request be opened or something?

we can leave it open



> 2\. Since downloads aren't a supported feature, should i open up a feature request for that?

yes new feature request please

**Comment by dshokouhi** [comment]
closing as wifi SSID is  case sensitive, no note needed.
