### ISSUE TITLE
Download functionality in the Android App Feature Request

### ISSUE THREAD

**Issue by sirweazel** [home-assistant/android#1341]
**Is your feature request related to a problem? Please describe.**

Yes, I currently use the motioneye supervisor add in and when I am viewing a video or photo, I'd like to ability to download to my phone.   Motioneye has a "Download" button, but when using it, it doesn't trigger anything in the app.  This is just one real world example that is bothering me.  

**Describe the solution you'd like**

Ideally any Download trigger or prompt should download a file.  Just like if using the phone native browser in Android or 3rd party browser such as Chrome or Firefox. 

**Describe alternatives you've considered, if any**

Current alternative is to use a web browser instead of the native app.  But this a work around not a seamless flow or integration.  it will also require education for other members using my home assistant.

**Additional context**

I have another ticket open regarding a different issue, but the contributor helping me with that ticket sugested i open up a feature request for this.   In the other ticket it was stated that Downloads are not supported at this time.  If this is a big issue to implement, maybe a pop up notification can be enabled that states downloads aren't supported when a download is triggered while the rest of the integration is developed?

**Comment by craigmdennis** [comment]
Related, there is no download option on any video in the media browser. Only "Playback Speed".

Pixel 5
Android: 12
App version: 2021.10.0-full

When I use the Media Browser to play a clip, the only option that is available is "Playback Speed

![Screenshot_20211204-233215](https://user-images.githubusercontent.com/725067/144727818-1f8139c7-967d-4873-9346-3955a8706f32.png)
".

**Comment by dshokouhi** [comment]
> Related, there is no download option on any video in the media browser. Only "Playback Speed".
> 
> Pixel 5 Android: 12 App version: 2021.10.0-full
> 
> When I use the Media Browser to play a clip, the only option that is available is "Playback Speed

do you get this option when using the browser on the device?

**Comment by craigmdennis** [comment]
Ah, good point. No, the option isn't available there either.

**Comment by dshokouhi** [comment]
> Ah, good point. No, the option isn't available there either.

the you'll need the frontend to support it first before the app can as its unrelated to this issue

**Comment by jpelgrom** [comment]
@sirweazel Are you still using the "Motioneye" supervisor add on? If so, could you help test a possible fix for the download issue?

You can download a test version of the app from [here](https://github.com/home-assistant/android/actions/runs/1792024643) and install the APK alongside the current app on your phone. Try downloading the video/photo file and let us know if it works, after testing you can remove the test version of the app without any consequences.

**Comment by sirweazel** [comment]
Yup, I'll test.

**Comment by jpelgrom** [comment]
If you're not sure and/or usually install the app from the Play Store, use `app-full-debug.apk` (and if tapping it doesn't trigger a download, make sure you're signed in to GitHub!)

**Comment by sirweazel** [comment]
I'll do more testing when home.  First indication is that the new feature is not working.  Screenshots attached.  I'm not sure if it's an android permission issue or other issue, but with the few minutes of testing i've done so far, i think something is wrong.  When i get a chance i'll try and provide more info.  Currently tested on a Pixel 4a with android 12.  When first launching i also got a "Firebase" error, I'm not sure if that is normal or not.
![Screenshot_20220203-182410](https://user-images.githubusercontent.com/24688999/152447688-603f37e2-e0f2-4ff8-b4d0-9e6fcb834a0f.png)
![Screenshot_20220203-184533](https://user-images.githubusercontent.com/24688999/152448141-0e96555c-327f-44ff-860a-2f318d81a45c.png)

**Comment by SkechyWolf** [comment]
> When first launching I also got a "Firebase" error, I'm not sure if that is normal or not.

As this is a debug build the needed files for cloud notifications are not included that's why a firebase error happens

**Comment by jpelgrom** [comment]
Did some basic testing with the backup settings button in [this version of a "Motioneye" add-on](https://addons.community/#motioneye) and it seems like the app needs to send some additional authentication when starting a download, assuming the same will apply to downloading photos/videos. @sirweazel Could you test [a newer version](https://github.com/home-assistant/android/actions/runs/1794592547) of the test app that includes changes for this?

**Comment by sirweazel** [comment]
Yes, I won't get a chance to test again until tomorrow (Sunday), but I'll
get it tested and report back as soon as possible.

**Comment by sirweazel** [comment]
I see that this is closed now, but thought I'd still post my results. It does work, but with one oddity, at least with my setup. Clicking download instantly downloads file, but I'm unable to click on the notification to open the file. What I noticed is that a ";" is getting appended to the file name causing issues. Screenshots attached.
![Screenshot_20220206-125018](https://user-images.githubusercontent.com/24688999/152694858-33bf44eb-dbf5-46f4-9082-07e1adb459ec.png)
![Screenshot_20220206-130117](https://user-images.githubusercontent.com/24688999/152694860-f0e8d5d3-564e-4d35-b804-0603d7ddb3f8.png)
![Screenshot_20220206-130322](https://user-images.githubusercontent.com/24688999/152694864-84a3380b-38fe-44ab-aa4a-2931ea1b062f.png)

**Comment by dshokouhi** [comment]
> Clicking download instantly downloads file, but I'm unable to click on the notification to open the file. What I noticed is that a ";" is getting appended to the file name causing issues.

Strange I do not see a `;` added to anything that I downloaded from HA core in the frontend. Do you see that being added when you download using chrome for android?

**Comment by sirweazel** [comment]
Works fine from chrome for Android. I feel like I've scene this before with a motioneye front end app someone developed for Android. I think I reported it but that was a long time ago, I'm not sure if that app is still in development.  I'll see if I can go through my emails to see if there was a resolution or what the cause was. Where else in HA can I download something to see if it's isolated to the motioneye aspect to compare?

**Comment by dshokouhi** [comment]
> Where else in HA can I download something to see if it's isolated to the motioneye aspect to compare?

Configuration > Addons, backups and supervisor > Backups > Pick any one > download

**Comment by sirweazel** [comment]
Thanks, found it. I was able to download backup tar files fine.  I looked through my emails, and I had this same issue on a different android platform (old Samsung phone at the time) and with a beta motioneye app from the play store. I followed up with my old email chain from 2 years ago, so i'll see if they reach back out what the issue was or if there was a solution.  I just tested some more, and any downloadable file out of the HA motioneye plugin appends a `;` to the file name from within the andoid HA app.  It doesn't matter if it's a log file, mp4, or backup out of motioneye.  Since I had this issue 2 years ago (before i ran HA) in another app and environment, chances are high its not directly related to HA.  But maybe an android oddity, or somehow a bug in motioneye.  What's weird is that it doesn't occur out of android chrome, all those files download fine.  So I'm not sure what that tells us? Let me know any testing you think might help?  Should I, or someone open up another issue?  Anything else i can provide to assist?  I'll do what I can.

**Comment by jpelgrom** [comment]
Looking at the settings backup I downloaded from the add-on two days ago, there's also a `;` at the end of the filename... I think this is related to the function that is used to determine the filename from the headers (which is provided by the system), Chrome probably has their own implementation which has a fix for this situation.

> so i'll see if they reach back out what the issue was or if there was a solution

If you get a response with a solution that would be very helpful!
