### ISSUE TITLE
All grid cards not working

### ISSUE THREAD

**Issue by tremosian** [home-assistant/android#1359]
**Home Assistant Android version:**  2021.1.1-full
**Android version:** 8.0.0
**Phone model:** Samsung Galaxy S7
**Home Assistant version:** core-2021.2.2
**Last working Home Assistant release (if known):** unknown

**Description of the problem:**
Any "grid" card on the phone, results in a red box showing the card's code. Inside the red box at the top "this.toggleAttribute is not a function".

Does not result in a crash - all grids are just unusable.

**Additional information:**
Attempted different fixes, same error -
- Attempted entity, media, button, gauge, grid cards.
- Single card in a grid
- Multiple cards in a grid
- Single column
- Multiple columns
- Render card as squares true
- Render card as squares false

All grids work normally while accessing them on Home Assistant through desktop/laptop.

**Screenshot of the problem**
![Screenshot_20210210-165032_Home Assistant](https://user-images.githubusercontent.com/31790406/107594041-d323cc00-6bc5-11eb-84e7-eac1eb7a087b.jpg)

Description of the screenshot:
The card above shows two entities listed on a single entity card, and then a second "grid" card with the same two entities listed separately.

**Comment by dshokouhi** [comment]
Does the issue exist in chrome on Android?

**Comment by tremosian** [comment]
That was it, thank you! I updated Chrome, followed by allowing javascript for the Home Assistant IP address.

My apologies for not knowing better.

**Comment by Normanras** [comment]
I know this is closed but it is still an issue for some on the HA forums, including me. I commented over there, but to share where it is and isn't working: 

**Working:**
iOS devices (ipad+iphone)
MacOS (chrome browser+chrome app) 
All OS completely updated, including HAOS and supervisor.
_Fire Tablets (7+10) in the silk browser_

**Not working:**
Two Fire Tablets (7+10) in the HA app. Both tablets have completely updated OS and HA app caches were cleared. 

Not sure why the only place it isn't working is the HA app on Fire devices, but it is still an issue. If this relates to another open issue, apologies and I can share this information over there.

**Comment by dshokouhi** [comment]
@Normanras  fire tablets use a version of android system webview that is very old and unfortunately not updateable so not much we can do there unfortunately. Amazon devices are not officially supported as we dont offer the app in the amazon app store, those devices lack google services alongside outdated webview. Its not as simple as installing from the play store either, it needs to be a system installed app.

**Comment by Normanras** [comment]
Got it. I appreciate the response. To think, all those YT videos showing a wall mounted dashboard using a Fire and custom cards, ha.

I know this isn't a support forum, but figure I'd ask: which non-iOS tablets are officially supported by Nabu Casa?
