### ISSUE TITLE
No sounds/LED/vibration from companion app notifications

### ISSUE THREAD

**Issue by sym0nd0** [home-assistant/android#1363]
**Home Assistant Android version:**
2021.1.1-full
**Android version:**
10
**Phone model:**
Samsung Galaxy S9
**Home Assistant version:**
2021.2.3
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
When companion app notifications fire on my phone there is no sound, LED or vibration - only an on screen notification/icon in notification bar
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20210214-075452_Settings](https://user-images.githubusercontent.com/55590428/107871494-14ec9500-6e9a-11eb-9d95-98d7d5a752f5.jpg)
**Additional information:**
All settings seem to be correct on my phone and the only affected app appears to be the companion app. This could be a Samsung One UI specific issue, as another Samsung user (S20) has posted about the same issue on Reddit.

Happy to test anything that might help. Thanks.

**Comment by dshokouhi** [comment]
Can you share the yaml example you used for the notification?

**Comment by sym0nd0** [comment]
Sods law, I raise an issue and test it...and it is now working as it should. 🤦🏼‍♂️

Sorry for wasting your time!
