### ISSUE TITLE
Android status bar is always light in dark theme

### ISSUE THREAD

**Issue by estevez-dev** [home-assistant/android#1365]
**Home Assistant Android version:** 2021.1.1-full

**Android version:** 11

**Phone model:** Pixel 3XL

**Home Assistant version:** 2021.2.3

**Last working Home Assistant release (if known):** unknown

**Description of problem:** After setting Android theme and Home Assistant Android app theme to dark and even after reboot the status bar and the bottom navigation bar are still light.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20210216-220005](https://user-images.githubusercontent.com/1819786/108115906-7d5a9280-70a3-11eb-886b-fc78410f5366.png)

**Additional information:** Not sure if it is connected with #272

**Comment by dshokouhi** [comment]
Is this a custom theme?  And to confirm you set it to dark in both the HA user profile and also under App Configuration?

**Comment by estevez-dev** [comment]
This is [kibibit](https://github.com/Kibibit/hass-kibibit-theme) theme. It has no dark or light variants.
I switched to the default HA theme and selected "dark" variant in profile settings:
![Screenshot_20210216-223539](https://user-images.githubusercontent.com/1819786/108118934-b5fc6b00-70a7-11eb-9c54-9bc3966d4ebf.png)
Then I chanked app configuration. The dark theme is selected there as well. Also, the status bar is dark when I'm in the app configuration:
![Screenshot_20210216-223616](https://user-images.githubusercontent.com/1819786/108119077-f2c86200-70a7-11eb-893d-528f54f19652.png)
But it is still light on the main screen:
![Screenshot_20210216-223529](https://user-images.githubusercontent.com/1819786/108119219-25725a80-70a8-11eb-8293-f8e78f243e0c.png)

**Comment by dshokouhi** [comment]
ok and what theme is your device set to in general? light?

**Comment by estevez-dev** [comment]
The device theme is also dark

**Comment by dshokouhi** [comment]
If you call https://www.home-assistant.io/integrations/frontend/#service-set_theme to `default` does the status bar change to what you expect?

**Comment by estevez-dev** [comment]
> If you call https://www.home-assistant.io/integrations/frontend/#service-set_theme to `default` does the status bar change to what you expect?

No, still light.

**Comment by estevez-dev** [comment]
> If you call https://www.home-assistant.io/integrations/frontend/#service-set_theme to `default` does the status bar change to what you expect?

Sorry, @dshokouhi , it works. Calling `frontend.set_theme` with `name: default` worked.

**Comment by dshokouhi** [comment]
Ah ok so it seems that another theme was set to default because we grab that value from the frontend: https://companion.home-assistant.io/docs/integrations/theming

As of now the app relies on this value but #272 has a linked frontend issue that should solve this when the user makes a change instead of it being a global default like the service call performs
