### ISSUE TITLE
Service "notify.mobile_app_" does not exist in HA

### ISSUE THREAD

**Issue by f45tb00t** [home-assistant/android#1367]
**Home Assistant Android version:** 2021.1.1 FROM F-DROID

**Android version:** LineAge v17.1 WITHOUT GAPPS!

**Phone model:** Xiaomi Mi8

**Home Assistant version:** 2021.2.3

**Last working Home Assistant release (if known): **None

**Description of problem:** Hi, I tried now mostly like anything to fix this. 
Surely I've checked also other resources and tried the fixed but without any luck. The Service notify.mobile_app_ is just not existing when I check HA. Even not under developer tools. There I have only notify.notify, notify.persistent_notification. That's it. Surely I would like to have the notifactions on my phone, too.
Could it be related that I am using the lite version of the companion app from F-Droid? And maybe furthermore because by Phone is no Gapps installed? I absolutely do not want to add the Gapps on my phone. But other software is working with push notifcations even without the Gapps. 

**Screenshot of problem:** none

**Additional information: **
- F-Droid companion app
- Phone has NO Gapps installed

**Comment by dshokouhi** [comment]
Notifications only work with the full version available in the Google play store.
