### ISSUE TITLE
Quick Access Device Controls - area in the subtitle

### ISSUE THREAD

**Issue by RouNNdeL** [home-assistant/android#1372]
**Is your feature request related to a problem? Please describe.**

I'd like to see the entity's area (if assigned) to be displayed in the Quick Access Device Controls from Android 11. 
Currently only the entity's `friendly_name` or it's `id` is shown in the title.

**Describe the solution you'd like**

I'd like to see the entity's area displayed under its name/id.

**Describe alternatives you've considered, if any**

I wanted to implement this myself and submit a PR, but I could not find any references in the code to the entity's area.

**Additional context**

The official documentation shows the use of a subtitle to display the room the device is in.

![image](https://user-images.githubusercontent.com/22538735/108836066-aeb9ed80-75d0-11eb-8aff-51b6536e30c2.png)

![image](https://user-images.githubusercontent.com/22538735/108837143-1fadd500-75d2-11eb-8852-89136304d854.png)

**Comment by dshokouhi** [comment]
> I wanted to implement this myself and submit a PR, but I could not find any references in the code to the entity's area.

This is because areas are not provided over the REST API and the app does not support websockets yet.

**Comment by RouNNdeL** [comment]
Oh, that's a bit disappointing. Are there some developer guidelines for this project I could follow to help out?

**Comment by dshokouhi** [comment]
We just use Android docs and also HA dev docs: https://developers.home-assistant.io/

**Comment by dshokouhi** [comment]
@RouNNdeL we have recently had websockets support added, if you wanted to take a crack at this you are more than welcome to :)  One thing to keep in mind is not all websocket calls are documented in HA dev docs. You'll have to inspect the HA core code base. For areas you can look at area registry and probably compare to the entity registry?

**Comment by dshokouhi** [comment]
Fixed in #2027
