### ISSUE TITLE
Use system provided theme on app configuration page

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#138]
The app configuration page should respect the theme on the device. If my device is set to dark mode, I would expect the app configuration page to reflect the same.  I don't think the HA theme has a role here?

**Comment by Knoxie** [comment]
I think the configuration page should reflect the theme you have set for HA. Not necessarily your device. Unless the whole app will reflect the device theme.  

Being that HA already has themes built in, i would think the app would respect those theme choices.

**Comment by dshokouhi** [comment]
Yea, that would be ideal but that would mean the app would need to be aware of all the themes that are set on the device, and which is active.  At least with dark/light theme this page becomes a lil easier to maintain.  I think theres already an issue to properly color the notification bar.

**Comment by ElleshaHackett** [comment]
> Unless the whole app will reflect the device theme.  

That I would like. Would love to have dark mode at night in mobile app and light during the day. Or have a setting in the mobile app for that. My main point is Dark Mode.

**Comment by dshokouhi** [comment]
Fixed in #717
