### ISSUE TITLE
Expose output of Android 10+ Low-Power Sleep Tracking API

### ISSUE THREAD

**Issue by jeffehobbs** [home-assistant/android#1383]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Android 10+ devices now have the ability to enable "low-power sleep tracking". This data would be fantastic to expose to the Home Assistant Companion app. 

Specifically, exposing the "sleep confidence" value would allow Android users to bring sleep data into Home Assistant.

**Describe alternatives you've considered, if any**

**Additional context**

More information is available on this API is here:

https://android-developers.googleblog.com/2021/02/low-power-sleep-tracking-on-android.html

Details API documentation here:

https://developers.google.com/location-context/sleep

**Comment by dshokouhi** [comment]
> Specifically, exposing the "sleep confidence" value would allow Android users to bring sleep data into Home Assistant.

Just a FYI its already possible to get sleep data into HA using Sleep as Android today.  They will also be updating their app to start consuming this new API.  Personally even if the app provides this data it wont be anywhere near as accurate as it can be with an actual sleep tracking app.  I love that Google has done something like this shoudl help making sleep tracking apps more accurate.
