### ISSUE TITLE
I cannot configure "ssid of the home Wi-Fi network"

### ISSUE THREAD

**Issue by jmarfer** [home-assistant/android#1391]
**Home Assistant Android version:** 2021.2.2-full

**Android version:** 8.0.0

**Phone model:** Huawei P10 lite

**Home Assistant version:** 2021.2.3

**Last working Home Assistant release (if known):**

**Description of problem:** In the android mvl app version of HA 2021.2.2-full I cannot configure "ssid of the home Wi-Fi network", in such a way that it puts me by default in the internal URL (in gray) the same as the external one. For this reason I cannot access HA from my mvl by local connection.

My son's HA 3.0.2-full android mvl app version checked, which has it without updating, if it allows ssid to be configured.

How could you solve this problem?

Thank you very much in advance

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Location permissions is required to be granted and enabled in order for the app to read the SSID please make sure to grant the permission and leave location on for this feature to work. This is a requirement from Google.

**Comment by jmarfer** [comment]
Muchas gracias, problema resuelto!

Un saludo
