### ISSUE TITLE
Add Indonesian (id) locale to Lokalise

### ISSUE THREAD

**Issue by lunmay** [home-assistant/android#1401]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Since Core and Frontend is mostly done for Indonesian, please add Indonesian (id) locale to Home Assistant Companion for Android project in Lokalise.
Thanks

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by robbiet480** [comment]
Added the language and enabled your account for translation, thank you!
