### ISSUE TITLE
On hi @tigattack  - it's not possible to set slower via the android API as 1hz is the slowest setting .

### ISSUE THREAD

**Issue by jking95** [home-assistant/android#1407]
hi @tigattack  - it's not possible to set slower via the android API as 1hz is the slowest setting .

Potentially we could looks at doing something like:
```
repeat:
  start transmitter (which takes a second or two to start)
  pause for x 
  stop transmitter
``` 
It feels like that may introduce problems, just a hunch though, and I'm not sure what this continual restarting would have on battery life.

Thanks for the suggestion though, I'll have a think on it.

_Originally posted by @Alfiegerner in https://github.com/home-assistant/android/issues/1400#issuecomment-791864170_

**Comment by dshokouhi** [comment]
looks like this was created on accident
