### ISSUE TITLE
Low resolution of widget icons

### ISSUE THREAD

**Issue by PaulAnnekov** [home-assistant/android#1409]
**Home Assistant Android version:** 2021.3.1-full

**Android version:** 11

**Phone model:** Samsung Galaxy S10

**Home Assistant version:** 2021.1.5

**Last working Home Assistant release (if known):**

**Description of problem:**

The resolution of icons for buttons is smaller than button size, so system scales them up which results in non-smooth view.

**Screenshot of problem:**

![Screenshot_20210307-014253_One UI Home.jpg](https://user-images.githubusercontent.com/1203892/110224741-f00e9f00-7ee6-11eb-852e-577946e448d0.jpg)

![Screenshot_20210307-014602_One UI Home.jpg](https://user-images.githubusercontent.com/1203892/110224745-f4d35300-7ee6-11eb-96d2-1360803512fb.jpg)

**Comment by dshokouhi** [comment]
Hmm I don't really see this level of blurriness on my pixel, wonder if this is a device specific issue or possibly even the launcher of the device.  Either way our icons are supplied by a dependency so we will be limited to that resolution I believe unless we decide to change it.

**Comment by PaulAnnekov** [comment]
It's default launcher of Samsung One UI. Maybe you use `com.maltaisn.iconpack` library incorrectly?

**Comment by dshokouhi** [comment]
> It's default launcher of Samsung One UI. Maybe you use `com.maltaisn.iconpack` library incorrectly?

If you feel it's incorrect feel free to submit a PR to correct it. As far as I can tell we are just displaying them and not altering them.

**Comment by backslashV** [comment]
Hi,
This still hasn't been fixed.
![Screenshot_20220303-221459_One UI Home.jpg](https://user-images.githubusercontent.com/8752221/156709929-aa98b34d-09a4-4296-ae86-04c16e24786d.jpg)
