### ISSUE TITLE
Entity data disappears from widget unpredictably

### ISSUE THREAD

**Issue by PaulAnnekov** [home-assistant/android#1410]
**Home Assistant Android version:** 2021.3.1-full

**Android version:** 11

**Phone model:** Samsung Galaxy S10

**Home Assistant version:** 2021.1.5

**Last working Home Assistant release (if known):**

**Description of problem:**

Usually entity widget displays data, but sometimes you may open the view with your widget and there will be no data. I can't find the precondition. Maybe it's related to some connection error. Anyway, I expect widget to not clear previous value until new value won't be received. 

**Screenshot of problem:**

OK:
![Screenshot_20210307-015306_One UI Home.jpg](https://user-images.githubusercontent.com/1203892/110224848-34e70580-7ee8-11eb-9757-970df04fe4b9.jpg)

Not OK:
![Screenshot_20210307-015250_One UI Home.jpg](https://user-images.githubusercontent.com/1203892/110224850-37e1f600-7ee8-11eb-99c3-16f7df4e444c.jpg)

**Comment by dshokouhi** [comment]
If the widget fails to update during the normal widget interval then it will be blank, all you have to do is tap on the widget for it to update on its own.  It is not stuck like that.

All widget data is dependent upon calls to HA and the state is not stored on the device, we only store the configuration for the widget as its required to fetch the data.

**Comment by PaulAnnekov** [comment]
It's definitely bad UX to show blank widget to user, taking into account that we had data to display. So you say it's not possible to not clear widget until successful response will arrive? Or it's not simple to do it?

**Comment by dshokouhi** [comment]
> It's definitely bad UX to show blank widget to user, taking into account that we had data to display. So you say it's not possible to not clear widget until successful response will arrive? Or it's not simple to do it?

I was only describing that the widget was not stuck like that and why it becomes blank.

**Comment by dshokouhi** [comment]
For this change we will need to save the data we pull from HA so we can return it when requested if the call fails.  This is required because widgets are write-only so we cannot read the data.  This issue impacts the entity state and template widget.  Testing a fix now, thanks for reporting.
