### ISSUE TITLE
Add room name in Device Control tiles

### ISSUE THREAD

**Issue by PaulAnnekov** [home-assistant/android#1432]
**Is your feature request related to a problem? Please describe.**

Currently only entity name is displayed. You end with 5 entities with name "Light" and can't figure out which is which.

**Describe the solution you'd like**
Add a room name to tile, like Google Home and Mi Home do. Also official docs shows tiles with a room name https://developer.android.com/guide/topics/ui/device-control.

**Additional context**
HA:
![Screenshot_20210313-145750_One UI Home.jpg](https://user-images.githubusercontent.com/1203892/111030721-7e65b200-840c-11eb-922d-f5ebf3aae163.jpg)

Google Home (arrows pointing to room names in russian):
![Screenshot_20210313-145926_GitHub.jpg](https://user-images.githubusercontent.com/1203892/111030774-c389e400-840c-11eb-9a59-8dba26f27a03.jpg)

Mi Home:
![Screenshot_20210313-150110_GitHub.jpg](https://user-images.githubusercontent.com/1203892/111030824-051a8f00-840d-11eb-84cc-a965e1fb0987.jpg)

**Comment by dshokouhi** [comment]
Duplicate of #1372
