### ISSUE TITLE
Blurred UI when opening specific HA url in fingerprint protected app

### ISSUE THREAD

**Issue by RoboMagus** [home-assistant/android#1433]
**Home Assistant Android version:** 2021.3.1-full

**Android version:** 11

**Phone model:** Samsung galaxy s10

**Home Assistant version:** 2021.3.4

**Last working Home Assistant release (if known):** 

**Description of problem:**
When opening a specific page (in my case /lovelace/3dp) through a notification click Action when the app fingerprint protection is enabled, the UI shows blurred but the fingerprint action does not show. Interaction is possible, but any page switched to remains blurred. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

https://user-images.githubusercontent.com/68224306/111039788-2ccf1e80-8430-11eb-98d4-c7d502ea4c91.mp4

**Additional information:**

Snippet that generates the notification:
```
service: notify.notify
data:
  title: OctoPrint 
  data:
    clickAction: /lovelace/3dp
```

**Comment by dshokouhi** [comment]
Do you have a timeout setting applied for the lock app? Can you try to list things in a step format so we can try to reproduce it? Can you also get the device logs so we can see what is going on? We should see some communication like if the unlock was successful etc...

**Comment by dshokouhi** [comment]
Actually does look like this issue occurs when a lock timeout is used as I am able to reproduce it. Logs are not needed.

**Comment by RoboMagus** [comment]
I do have a timeout set for the locking behavior, but I missed to mention that. It's set to 10 minutes. As shown in the video, the app is not locked nor blurred when opening it through the application icon.

The steps taken that result in the behavior on video are:
- Open home assistant app through app icon on homescreen. This loads default dashboard, no issues.
- Open home assistant through the click action on a persistent notification. This loads /lovelace/3dp in my case, which remains blurred. It also seems to show the loading of the app as is usually only shown when opening the app from 'fresh'

Further testing shows that after reopening the home assistant app (when not closed as a background process) the app remains in a blurred state.

I cannot currently access logs on my phone, but I'll try to attach them in the next couple of days.

**Comment by dshokouhi** [comment]
@RoboMagus logs are no longer needed, I was able to reproduce with a lock timeout :) fix also submitted but thank you for confirming

**Comment by RoboMagus** [comment]
Wow, thanks for the quick follow-up!

Great to see you've found the culprit so quickly :)
