### ISSUE TITLE
question: can I configure homeassistant / mobile to work with authelia

### ISSUE THREAD

**Issue by repomanz** [home-assistant/android#1437]
Hello -

I have my home assistant server externally accessible. However I am protecting homeassistant with authelia / reverse proxy.  When using the mobile app, it appears it doesn't want to work in this configuration and just hangs.

Are there settings I can enable on the homeassistant side to get this to work with the mobile client? Homeassistant url get's redirected to authelia url, user enters credentials and if successful hands over to the homeassistant url.

**Comment by dshokouhi** [comment]
How does the browser handle it? Have you tried looking at the crash logs mentioned in the issue template that you have removed?  There are no settings to enable in the app, this sounds more like a reverse proxy issue than an app issue.

**Comment by repomanz** [comment]
after looking through my reverseproxy configuration again; found the issue. Working now.
