### ISSUE TITLE
Position for covers in Android power button menu



### ISSUE THREAD

**Issue by Sissi91** [home-assistant/android#1439]
**Does anyone know how I could see the position of my blinds, or maybe also adjust the position of them in the Power menu?
I can controll my blinds, so open/close them. but I don't see a position in the Power menu and I also can't set the position.**

**On the picture I found it seems to be possible (button top row, right side)**

![image](https://user-images.githubusercontent.com/34167143/111825256-8da29f00-88e7-11eb-97d8-abc9fe241589.png)

**If somebody has done something in that way, that would be just great**

** **

**Comment by dshokouhi** [comment]
covers currently only support open/close, we will need to add support for the range template on supported devices

https://github.com/home-assistant/android/blob/bd2ebb0a65a10b0c173894d7af82084da24387e3/app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt#L60

We probably need to do something similar/identical to lights with brightness support

https://github.com/home-assistant/android/blob/020e590205f67455ac5e2fc7bdd6f014b6b205b7/app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt#L55

**Comment by Sissi91** [comment]
yes, something similar like the lights function would be perfect. I'm not familiar to Java and can only try the functionality 🙈

**Comment by dshokouhi** [comment]
> I'm not familiar to Java

actually the app is written in Kotlin...its not terrible to pick up if you want to give it a shot 😛

**Comment by Sissi91** [comment]
It took me an evening to install android studio and getting home assistant to run, but the result is like I want it.

![Screenshot_20210327-020337.png](https://user-images.githubusercontent.com/34167143/112706235-4ac26780-8ea3-11eb-9873-5040d4c2b6cb.png)

There are some tweaks which I will solve during the weekend. After I will publish it somehow to integrate it in the main app

**Comment by dshokouhi** [comment]
Awesome glad to see you got it going! If you need any help don't hesitate to ask in discord there is a dedicated mobile app development channel.

**Comment by Sissi91** [comment]
I will publish the new Code for Cover Control tomorrow. The experience is really nice now.
I've got one more question about this functionality:
![image](https://user-images.githubusercontent.com/34167143/112737553-b700a200-8f5b-11eb-9b86-c87525d50f1b.png)
source: https://developer.android.com/guide/topics/ui/device-control
If you use lights integrated in Google Assistant it's working as in this picture. If I use the Power Menu Button and use the Hassio functionality there is just the link to open the app.
Is it possible to use without going into the Hassio app?

**Comment by dshokouhi** [comment]
> I will publish the new Code for Cover Control tomorrow. The experience is really nice now.

Awesome! Looking forward to the PR :)



> If you use lights integrated in Google Assistant it's working as in this picture. If I use the Power Menu Button and use the Hassio functionality there is just the link to open the app.

I have an existing PR that will trigger the more info panel from the HA frontend #1446 



> Is it possible to use without going into the Hassio app?

It has to be our app since we need to provide a pending intent, my comment above shoudl solve it.  Unless you absolutely want a custom UI that will involve building a UI from scratch to display it here with all the data and everything.  Personally I think loading more info is as good as it will get here. What you see up above is an activity from the google home app.

**Comment by Sissi91** [comment]
I see, that is what I was looking for, nice job mate! I made a pull request for my code here: https://github.com/home-assistant/android/pull/1462
with that, we can close this issue 😊
