### ISSUE TITLE
iBeacon Transmitter - Only on Wifi or GPS zone

### ISSUE THREAD

**Issue by soloam** [home-assistant/android#1447]
**Is your feature request related to a problem? Please describe.**
No, more a improvement. It would be nice if iBeacon Transmitter would allow to only be active when connected to some specific networks (wifi) like the GPS and connections to bluethoot. For example I'm interested on traking the ble in my home, no need to drain my battery when I'm outside. Another good solution would be based on zones, like only track when my GPS position is inside some zones (Like Home)

**Describe the solution you'd like**
Add the ability to select what networks to be connected to transmit BLE, or zones to be active.

**Describe alternatives you've considered, if any**
Basicly, wifi networks or gps zones

**Additional context**
Nothing to add

**Comment by Alfiegerner** [comment]
Hi @soloam - just in case you've missed there is a notification command that allows you to achieve this via HA automations:

https://companion.home-assistant.io/docs/notifications/notification-commands#ble-beacon-transmitter

Possibly not what you were thinking of but worth a mention.

**Comment by muniter** [comment]
I personally use @Alfiegerner  recommendation, is just a simple automation to turn off the transmitter when the phone leaves home, pretty straightforward. Also the transmitter sensor will tell you if it's transmitting or not.

**Comment by Alfiegerner** [comment]
SeeaS as as a sa a bell so z aaa Az in az s was sz z says as sszdz

**Comment by soloam** [comment]
That works! I would prefer to have some control in the Android, like the bluetooth tracking! But on its absence, this work's!

**Comment by pjv** [comment]
Thanks @Alfiegerner for the heads up about the notification command.

It’s nice that you can use that notification command to turn the BLE beacon transmit off and on, but I agree with @soloam that it would be better (more reliable) to turn it off and on locally on the phone based on whether the device is connected to particular wifi networks or is in one of the defined GPS zones.

**Comment by Alfiegerner** [comment]
I won't be able to look at this anytime soon as in a crunch period with life and work generally, but when I have some more time I'll have a look.

It shouldn't be very hard, provided we keep the dependency on the other sensor simple, e.g:

Add new setting called 'active wifi ssid' that turns controls BLE transmitting state.
Transmitting state is off, unless both:
1. The wifi SSID sensor needs to be turned on
2. And it's state needs to match the setting

If anyone wants to have a go implementing this themselves I can help, could be a nice mini project for someone wanting to dip their toe into android development - I had no prior experience in this space before adding this and world encourage anyone with interest and time to give it a crack.
