### ISSUE TITLE
Find my android

### ISSUE THREAD

**Issue by henrikhjelm** [home-assistant/android#1450]
**Describe the solution you'd like**
"Find my android"

**Describe alternatives you've considered, if any**
do so the phone play a audio file. 
so you can locate the phone

**Comment by dshokouhi** [comment]
The app cannot trigger the "find my phone" intent as I had tried it previously.  Use the `alarm_stream` notification to make it sound when its on silent.

Follow the second android example on this page <https://companion.home-assistant.io/docs/notifications/critical-notifications>
