### ISSUE TITLE
Remove "Updating sensor" notice

### ISSUE THREAD

**Issue by Nihvel** [home-assistant/android#1459]
**Home Assistant Android version:**
All. Since release.
**Android version:**
All again.
**Phone model:**
All.
**Home Assistant version:**
Ever since Home Assistant is able to send notification
**Last working Home Assistant release (if known):**

**Description of problem:**
I wear a fitnessband, always. It is a Xiaomi miband. I enabled, among other applications, Home Assistant to show notification on my miband. These notifications tell me of possible doors open when i'm away and warn me about important, very important sensor in the house.
I have kept the Home Assistant app with all the sensors disabled ever since it was released long time ago. The issue is when a phone sensor updates, it shows a notification. I have never managed to see this notification on screen but, somehow, this notification is intercepted through the miband app and, every some minutes, the miband vibrates showing "updating sensor".

This is just annoying. I'm forced to disable sensors in the app because the miband keeps vibrating.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
You can turn off the notification channel for Sensor Worker.
