### ISSUE TITLE
Open on last viewed page

### ISSUE THREAD

**Issue by tunerooster** [home-assistant/android#1461]
This is more of a feature request...

I would like an option to have HA Companion start/open on the page last viewed.  I have an automation which shows previews of recent activities on a wall dashboard.  Eg, when I come home, I can instantly see who has visited.  If _Companion_ dies/restarts for any reason, I would like it to return to the "preview activity" page (which was active before the restart).  Instead it always starts on the "home" page.

In the same vein, it would also be useful to honor a command line argument (like chrome does) to specify the start page.  For example:

```
ssh ha-client am start io.homeassistant.companion.android/.launch.LaunchActivity -d /lovelace/activity
```
With the latter feature, I could implement the former, but both would be nice...

Thanks for all the great work for this app!

**Comment by dshokouhi** [comment]
There is already a feature where you can use a notification command to open the app to a specific page or dashboard. You can also set the default dashboard on a per device basis in the user profile.
