### ISSUE TITLE
Cannot connect to Home Assistant using TLSv1.3 (proxied by Nginx)

### ISSUE THREAD

**Issue by koterpillar** [home-assistant/android#1477]
**Home Assistant Android version:** 2021.3.1-full

**Android version:** 9

**Phone model:** Samsung Galaxy S8, SM-G950FD

**Home Assistant version:** core-2021.3.4

**Last working Home Assistant release (if known):** core-2021.3.4

**Description of problem:**

My Home Assistant is behind an Nginx HTTPS proxy configured to only support TLS 1.3 (`ssl_protocols TLSv1.3;`). When Android application is started, it detects the Home Assistant instance and asks for username and password, but then displays an "Unable to connect to Home Assistant." error.

Enabling TLS 1.2 alongside TLS 1.3 in Nginx configuration fixes the error.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

Nothing matching "homeassistant" when following the instructions via Logcat Reader.

**Screenshot of problem:**

![Screenshot_20210402-212724_Home Assistant](https://user-images.githubusercontent.com/140276/113408747-aa68c780-93fb-11eb-9607-898b272e1b81.jpg)

**Additional information:**

From Nginx side, these are the requests the application makes. A 200 response is sent to each, but nothing further is received from the application.

```
192.168.0.1 - - [02/Apr/2021:21:38:41 +1100] "POST /auth/login_flow HTTP/2.0" 200 176 "https://[redacted]/auth/authorize?response_type=code&client_id=https://home-assistant.io/android&redirect_uri=homeassistant://auth-callback" "Mozilla/5.0 (Linux; Android 9; SM-G950F Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36"
192.168.0.1 - - [02/Apr/2021:21:38:49 +1100] "POST /auth/login_flow/624f706c400b44c39d3207a9c6d2356e HTTP/2.0" 200 191 "https://[redacted]/auth/authorize?response_type=code&client_id=https://home-assistant.io/android&redirect_uri=homeassistant://auth-callback" "Mozilla/5.0 (Linux; Android 9; SM-G950F Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36"
```

**Comment by dshokouhi** [comment]
Your device does not support TLS 1.3 as it runs Android 9 and support was added by Google in Android 10

https://developer.android.com/about/versions/10/features#tls-1.3

We also already support the default modern TLS settings from OKHTTP: https://square.github.io/okhttp/4.x/okhttp/okhttp3/-connection-spec/#companion-object-properties

Also the logs for OKHTTP are only logged in a debug build so if you wanted to look at the actual error you need to grab any APK from the actions tab to inspect logcat there.
