### ISSUE TITLE
Allow the F-Droid minimal app to use non-Gapps push-notifications

### ISSUE THREAD

**Issue by initd0** [home-assistant/android#1480]
I understand that (push)notifications and location services do not work on the minimal version.
Although im fine with location services not working.  Having the HASS app and no notifications is not really that useful at the end of the day.

Can you make push-notifications work for the F-droid version without using google play services, just like Signal app has done?
Here is where they have implemented it: https://github.com/signalapp/Signal-Android/commit/1669731329bcc32c84e33035a67a2fc22444c24b

i think many would appreciate a feature like this while using a phone without Gapps, without sacrificing push notifications.  There has to be another way. The world shouldn't revolve around google just to get push notifications.

**Comment by dshokouhi** [comment]
if we are to do something like this it wouldnt just be for the minimal version but for all versions of the app, the app currently does not support websocket connections so someone will need to add support for that first. That may also require HA core changes to go as well too so wouldnt just be a request made here.

**Comment by T-bond** [comment]
I have seen that on Element Android someone opened a PR for [Unifiedpush](https://unifiedpush.org/) .
I haven't checked that project too extensively, but it seems like a good fit.

**Comment by sigfriedseldeslachts** [comment]
I would also be interested in seeing a notification option that doesn't use Google services. I don't have any Google stuff installed on my phone and thus I cannot send notifications. Signal and Telegram both have an alternative for this. The framework @T-bond might also be a good idea.
Perhaps it can be integrated on the Core project as an integration you have to setup?

**Comment by newhinton** [comment]
to expand this issue: there should be a general way to send back data to the android app, not only notifications. This would allow for the app to switch bluetooth or different settings controlled by HA.

This would also allow for a media notification, that provides a nice notification like the webui

**Comment by dshokouhi** [comment]
@newhinton some of that is already possible via notification commands, not all features yet but its been building out.  Whatever solution we decide to adopt here should be able to handle the existing commands.

**Comment by mathmaniac43** [comment]
If websocket support were added, would that allow the Android HA app to have Local Push capabilities like iOS and macOS? [The docs](https://companion.home-assistant.io/docs/notifications/notification-local/) mention Google Firebase but do not mention Android at all, and best I can tell the capability is not there yet.

**Comment by TheLastProject** [comment]
Still not resolved and still wanted by many people including me.

**Comment by Syntoxr** [comment]
I think like @T-bond already said that [UnifiedPush](https://unifiedpush.org/) would be a good solution. The advantage of a central push service would be that only one connection would need to be open, instead of separate connections for each service (Homeassistant and other services like Element, for example). This reduces Battery and data usage.

**Comment by pjv** [comment]
I know this is closed and the Android companion app now implements non-FCM push but here’s another thumbs up for implementing unified push.  Please devs, take a look here: https://unifiedpush.org/ where there is good documentation for including unified push in an app.

I am currently using a small app called ntfy (https://ntfy.sh/) which is capable of both handling my own custom notifications as well as acting as a local broker on android for push notifications for any apps that implement unified push. It is connected all the time, notifications are extremely quick, and it BARELY uses any battery at all. I have it connected to my own ntfy server instance which effectively allows me to manage my own generic alternative to FCM for ntfy itself and anything that implements unified push. At the moment for me that includes element (for matrix). If I could have any android fantasy future, that would also someday soon include Home Assistant and Signal. I know Moxie won’t listen to my pleas, but how about you all?

**Comment by OHDMax** [comment]
I would also like to see this feature in Home Assistant as my setup is very similar.

**Comment by PanderMusubi** [comment]
See also https://github.com/openhab/openhab-android/issues/3806

**Comment by Rudd-O** [comment]
https://github.com/home-assistant/android/issues/3206 is related, not sure that ticket was closed as "not planned".

Persistent connections is fine and dandy, but they are a huge battery drain compared to just having one app (NTFY) listening to notifications and forwarding them to the Companion app for action.
