### ISSUE TITLE
Option to manually change the "app background" color

### ISSUE THREAD

**Issue by BoneheadFraggle** [home-assistant/android#1496]
**Is your feature request related to a problem? Please describe.**

Since 2021.4.1 the top and bottom bars are always HA blue. I personally don't ever fancy that in apps with a app header.
But mainly but with a dark theme, I think the ambition of a dark mode is kind of put aside with blue top and bottom bars.

**Describe the solution you'd like**

I would recommend an option to change the bar color to the users preference.
Maybe 3 options:
1. Default: HA blue as today.
2. Follow system theme. I don't know if there's a standard system setting to utilise, but other wise the HA day/night background. Just not the header background, since it looks like a GIANT header when the header and top bar uses the same color.
3. User preference with a hex code or even better, a color picker with option to enter hex code.

**Describe alternatives you've considered, if any**

Use Nacho Notch, but I am trying to use as few additional apps as possible since my main mobile is company enrolled and hence minimal possibilities to adjust.

**Additional context**

Example 1, I have chosen a really dark theme, but the perception is not very dark due to the HA blue top and bottom

![image](https://user-images.githubusercontent.com/2287810/114139122-eaa1db80-990e-11eb-80dd-c581a7eed99f.png)

Example 2, I have chosen a really dark theme, and using Nacho Notch to make it look like pre-2021.4.1. Easier on the eyes at night.

![image](https://user-images.githubusercontent.com/2287810/114139310-2b99f000-990f-11eb-8afc-9238621d07e3.png)

Example 3, It doesn't make sense to have the HA blue when the user have chosen to use all dark mode.

![image](https://user-images.githubusercontent.com/2287810/114139636-977c5880-990f-11eb-8227-029caea23a19.png)

Example 4, An example that I think works really well is Gmail where the top and bottom bar have the same color as the app background and follows the day/night and the search bar is a discreet deviation.

![image](https://user-images.githubusercontent.com/2287810/114141872-7cf7ae80-9912-11eb-9bed-331c17d7cc71.png)

**Comment by chriss158** [comment]
Since 2021.4.1 the statusbar color is determined from the HA theme itself. If it's not found, it should follow the system settings or the theme set in the app preference.

Which theme are you using? What if you set the theme in the app preference to dark?

**Comment by alexfrolkin** [comment]
Same problem after upgrade.  The theme is dark.
![Screenshot_20210409-144603_Home Assistant](https://user-images.githubusercontent.com/77844696/114175141-56ea0280-9942-11eb-8cd8-1d97b772be2b.jpg)
![Screenshot_20210409-144553_Home Assistant](https://user-images.githubusercontent.com/77844696/114175152-58b3c600-9942-11eb-99cc-dbf9cca02633.jpg)

**Comment by chriss158** [comment]
@alexfrolkin 
you do not use a theme, just the dark mode of HA?

I did a quick test. With theme and with default dark/light mode of HA. No problems.

**Comment by chriss158** [comment]
Can both of you have a look at the log. there should be a line like "Try setting statusbar color with color string": Can you give me the value.

**Comment by BoneheadFraggle** [comment]
In example 1 above, I use HA default dark theme.

I get the logic in using the HA default color, I just dont think it is a good thing at all times. I know to little about themes to know the details about how it's setup, but personally I don't think I ever will want to have HA's header and the top bar in the same color. I just don't like the way it looks. It looks quite a lot before the header was made smaller some versions ago.

Real life examples with 2021.4.1.

Default light theme:

![image](https://user-images.githubusercontent.com/2287810/114153052-3a889e80-991f-11eb-9d4e-1ac21e539c87.png)

Default dark theme:

![image](https://user-images.githubusercontent.com/2287810/114153093-44aa9d00-991f-11eb-9d12-e23f590fb3df.png)

Addionally I may suffer from an edge case, but as an example, my phone has a punch hole camera (which I really don't like, but didn't get to choose). To make that less intrusive I always want to have a dark top bar. The black hole in the very blue top bar doesn't look appealing. 

![image](https://user-images.githubusercontent.com/2287810/114153192-5b50f400-991f-11eb-8b27-960618b41301.png)

I noticed I need to exit and kill the the app to really reload it.

**Comment by BoneheadFraggle** [comment]
I noticed I need to exit and kill the the app to really reload it, so I'll do new screenshots of the actual behavior.

In the mean time: 
Can't find anything like "Try setting statusbar color with color string" in the HA app log.
No match at all on "statusbar".

I'd prefer not to upload the complete log, but if you like any specifics from it, no problem.

**Comment by chriss158** [comment]
> I noticed I need to exit and kill the the app to really reload it, so I'll do new screenshots of the actual behavior.

Yes, currently you have to restart the app to set the color of the status bar.

I think I just understood you. You would prefer the color of the status bar and bottom bar to be slightly different from the color of the app content. Is that right?

**Comment by BoneheadFraggle** [comment]
Yes, exactly. In my case, always black to make it "hide" the punch hole camera and make the status bar separate from HA. 
But as always not everyone think alike, hence my configurability wish :-)

**Comment by chriss158** [comment]
In fact, I had it that way during development. But I decided against it, because many other apps, color the status bar the same as their content. E.g. google clock app. And also the gmail app.

But when I look at the design specifications of the material design (https://material.io/components/app-bars-top#status-bar), I see that the status bar slightly stands out somewhat from the content. 
In the current app settings this is currently also the case. 

When I think about it, I also tend to think that it should stand out a little from the content.

But your request is still a bit different. What does it look like without Nacho Notch? Should be a blue status bar, right?

**Comment by BoneheadFraggle** [comment]
Yep, blue status bar and "bottom bar".

![image](https://user-images.githubusercontent.com/2287810/114187209-07a6d080-9948-11eb-89a3-66f836eb497f.png)

Regarding the standard Google apps, I think one major difference is that those apps are really integrated designwise, with the menu in the bottom and very few design options (except light/dark).

I think quite a lot of apps that utilise the app color in the status bar hide the top menu when you scroll up which make it look a bit more fluid and a bit less "bulky" at the top. Like search bar in Gmail, Google Play Store, and LinkedIn, menu bar in Twitter and YouTube. Not sure if that would make sense in HA though.

**Comment by chriss158** [comment]
Btw: I personally find the blue layout prettier.
That the statusbar was black before, is because the color of the statusbar was determined by an API method. Unfortunately, this API method does not work correctly. Therefore the color was black. With the new version, I have fixed this and the color is determined from the theme variable `app-header-background-color`. Also the API method (if it would work) determines exactly this variable.

As a possible solution for your problem I could imagine that there is another item for the theme setting of the app.

- Light
- Dark
- Follow system settings
- **Follow HA theme settings** <--- New

The first two options (Light, Dark) forces the complete theme of the app independent of the set theme in HA. If you set Light, then it will be Light.

You could then set it to Dark and have your Dark status bar, independent to your HA theme.

Follow HA theme setting would then be the default. So that the statusbar adapts to the theme of HA.

**Comment by BoneheadFraggle** [comment]
That sounds great for me, and hopefully other would benefit from it as well!

Just being curious, my initial suggestion with a completely free choice (_user preference with a hex code or even better, a color picker with option to enter hex code_), is that out of the question? Might be a really bad idea designwise, it was just a thought to get total freedom.

**Comment by chriss158** [comment]
For me this is a very specific setting. I would also not introduce a new design language for the app. HA should decide the color (with its theme settings) and the app should automatically adapt to it. With this change you could customize the default behavior at least a little bit.

I think your case is rather the exception. 

But yes, your idea would certainly also be an option :+1:

@dshokouhi  What do you think about this?

**Comment by dshokouhi** [comment]
So is there a bug somewhere or is this a custom theme? Based on what I am understanding the default HA theme is picked and the user has the dark theme selected which is how my setup is and this is what I see.

![image](https://user-images.githubusercontent.com/1634145/114197106-e07bdf00-9906-11eb-9fbf-301e1392a325.png)

Can you guys who have this issue try to set the default theme using `frontend.set_theme` and see if that solves the issue?

I definitely don't see the HA blue like everyone else does so I think this might be something else personally, unless I misunderstood the issue?

> Also, quite a lot of apps that utilise the app color in the status bar hide the top menu when you scroll up which make it look a bit more fluid and a bit less "bulky" at the top. Like search bar in Gmail, Google Play Store, and LinkedIn, menu bar in Twitter and YouTube. Not sure if that would make sense in HA though.

The HA frontend would need to handle the hiding of the top bar.

I see there is also an app menetioned as Nacho Notch? Could that be causing a conflict? I don't have it installed on my pixel 4 xl.

**Comment by chriss158** [comment]
`frontend.set_theme` is not needed anymore, since color is determined directly from the webview HTML source. It's the same thing like in the iOS app.
As his theme is using a blue header bar color (defined in `app-header-background-color`), he will get a blue status bar. So this is not a bug. Correct behavior. 

about @alexfrolkin:  I think he just had to restart his app to make the colors work.

**Comment by dshokouhi** [comment]
Then yea I think maybe letting users pick what colors the status/nav bar are separately would be helpful to those users. Personally speaking if I had the choice I would probably let the status bar match the HA header but the nav bar I would keep black since its odd to have it as a separate color 😛

**Comment by BoneheadFraggle** [comment]
Sorry, when I posted this morning, I had not realised that a reload of the app was needed to really activate the new setting.
So the first screenshots are kind of confusing now.

My main issue is that the app now applies the main color (don't know the correct term), typically the header color around the actual app. In the top bar and the bottom bar. Just like in your screenshot above. I really don't want the background behind the clock and icons to be the same color as my HA header. I think that makes perfect sense with an app like Gmail, where the user can't affect the apps design at all.

But in HA everything is customizable, which for means it is not always the obvious choice to assume that the header color should be applied in the status bar and below the app window.

In my case, I want the HA blue header. It is a theme that I use on my desktop and it's working really well on mobile. But I really don't want the blue to be applied in the phone's status bar.

Maybe I can achieve what I want but customizing a theme?
Or by suggesting that the behavior to apply HA color to the status bar only should be done if HA app is in full screen mode?

I am totally open to suggestions. Just wanted to ask for an option where I can separate the phone's status bar color from the header color.

**Comment by chriss158** [comment]
The status bar and the bottom bar should be the same color. 
As seen here: https://material.io/components/app-bars-top

Currently the color is adapted from the theme of HA (Variable `app-header-background-color`). If this variable is set to pink, then both bars will be pink. 

The theme setting in app settings, are currently only color the app settings.

**Comment by alexfrolkin** [comment]
> `frontend.set_theme` is not needed anymore, since color is determined directly from the webview HTML source. It's the same thing like in the iOS app.
> As his theme is using a blue header bar color (defined in `app-header-background-color`), he will get a blue status bar. So this is not a bug. Correct behavior.
> 
> about @alexfrolkin: I think he just had to restart his app to make the colors work.

A hard restart of the application helped, the status bar turned dark. Thx.
