### ISSUE TITLE
SensorWorker notification since update to 2021.4.1-full

### ISSUE THREAD

**Issue by electrofloat** [home-assistant/android#1497]
**Home Assistant Android version:**
2021.4.1-full

**Android version:**
11

**Phone model:**
Pixel 5

**Home Assistant version:**
2021.3.1

**Last working Home Assistant release (if known):**

**Description of problem:**
Today, I updated to the 2021.4.1-full version. And since then I get a 'SensorWorker' notification very frequently, which disappears very quickly, but since my phone is configured to turn the screen on when a HA notification appears, this is very annoying.
I can see in the AppConfig logs that it is indeed starting a SensorWorker foreground service every time this happens:
SensorWorker: Updating all sensors.

I have my 'Enable 70 Sensors' turned off (every sensor was turned off before the update too), so why is the SensorWorker starting at all if all my sensors are turned off?

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
You can just disable the sensor worker notification channel and you won't see it again. The service is only promoted to the foreground if you have at least 1 sensor enabled.  You may just need to clear data if the system thinks you still have 1 sensor enabled.

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt#L64
