### ISSUE TITLE
Clear stale device from list of BT devices triggering High Accuracy Mode

### ISSUE THREAD

**Issue by crowedavid** [home-assistant/android#1515]
**Is your feature request related to a problem? Please describe.**

No, mostly cosmetic.

**Describe the solution you'd like**

Provide a way to clear a stale device (i.e. one that no longer appears in the list of paired BT devices) from the list of BT devices that trigger High Accuracy mode for location sensor. An automatic method to ask to remove the device if it no longer appears in the list of paired BT devices might be the best way but I'll be happy to have a button to clear all devices from the list and then reselect the desired devices.

**Describe alternatives you've considered, if any**

Reconnecting the device and clearing it from HA app would work but I no longer have the BT device I want to clear.

**Additional context**

I recently changed BT devices I use in my car and trigger the HA High Accuracy mode for location updates.  Unfortunately, I deleted the device from the Android BT configuration and noticed it still appears in the list with no way I see to remove it from the HA app.

**Comment by dshokouhi** [comment]
If you go back to the settings page and edit the list and click on it should update it. This is the only page we update the settings. Can you try that and see if it works?

**Comment by crowedavid** [comment]
i've gone into the settings to update the list and tried unselecting all (3) devices (4 devices total, 3 are currently paired) available from the list and it obediently removes the three devices unselected and leaves the one that no longer appears in the list of paired devices.

**Comment by stipe76** [comment]
> i've gone into the settings to update the list and tried unselecting all (3) devices (4 devices total, 3 are currently paired) available from the list and it obediently removes the three devices unselected and leaves the one that no longer appears in the list of paired devices.

I can confirm exact behaviour.

**Comment by dshokouhi** [comment]
can you guys share a screenshot of the issue please?  Does this stale device appear in the bluetooth connection sensor too?  Looking at the code the list preference should be resetting its values with the same values you get from bluetooth connection attributes.

**Comment by crowedavid** [comment]
below is a sequence of screenshots:

1. this shows the list of BT trigger devices - the BMW65774 device is the one that is no longer paired with my phone:
![Screenshot_20210415-120837](https://user-images.githubusercontent.com/4466952/114932827-cd787b80-9dec-11eb-8ba0-55eaa1cf58bd.png)

2. this shows the list of devices to select from - BMW65774 does not appear in the list:
![Screenshot_20210415-120908](https://user-images.githubusercontent.com/4466952/114933029-13cdda80-9ded-11eb-996e-f06e74b03a4b.png)

3. this shows the list of devices after i've deselected all:
![Screenshot_20210415-120930](https://user-images.githubusercontent.com/4466952/114933295-5c859380-9ded-11eb-9cb6-fd8c92115c50.png)

4. this shows the new list of BT trigger devices after clicking Ok on the empty list from above - note that BMW65774 is the only device in the list:
![Screenshot_20210415-120956](https://user-images.githubusercontent.com/4466952/114933455-876fe780-9ded-11eb-8e5f-03f24c738859.png)

5. this shows the list of devices to select from - BMW65774 still not in the list:
![Screenshot_20210415-121020](https://user-images.githubusercontent.com/4466952/114933656-c30ab180-9ded-11eb-9876-e52a9353bc7d.png)

6. this shows the list of devices after selecting the three correct devices - note that BMW65774 is still in the list:
![Screenshot_20210415-121051](https://user-images.githubusercontent.com/4466952/114933749-e2a1da00-9ded-11eb-8948-3f2e2131c7c0.png)


i hope this helps and am happy to gather info or try fixes.

**Comment by dshokouhi** [comment]
Ok this is helpful.  Looks like the issue here is that the `MultiSelectListPreference` is holding on to its `value` even though the new `entries` are overwritten.  That makes sense as to why its not clearing it properly because preferences are also meant to hold on to their values and even restore in app back up.  This also impacts any other sensor setting that uses a `MultiSelectListPreference` like for example a stale `zone` or even a stale installed app in the allow list. 

So to me this feels like a bug.  The bug is that the `MultiSelectListPreference` should have its values cleared out if we detect a mismatch between preference value and the provided entries. I will submit a fix for this, just keep in mind you'll need to reselect the bt devices to remove the stale value.
