### ISSUE TITLE
Samsung Gear S3 / Health Integration

### ISSUE THREAD

**Issue by iotemylabs** [home-assistant/android#1523]
**Is your feature request related to a problem? Please describe.**

Not related to a problem, a helpful idea

**Describe the solution you'd like**

An option in the companion app to read the state of Tizen OS Devices  (Battery State, Is_charging) and Samsung Health Statistics (similar the Fitbit Integration: Weight (int), Steps (int), Active Time (Int), Last Exercise (String), Last Exercise Time (Datetime object?), Last Exercise Calories Burned (Int), Food Calories (Int), Food Last Meal Type (String), Food Last Meal (String), Sleep Time Elapsed (Int or Datetime Object), Heart Rate (Int), Water (In Glasses, Int), Blood Glucose (Int), Blood Pressure (String, maybe an Int  Concatenation), and a lot more available.

Also, maybe services through home assistant to update sensors from other sources, if applicable (such as Fitbit, Withings Sleep Sensor, etc.) to update to Samsung Health as a "sub hub" of sorts.

**Describe alternatives you've considered, if any**

I have considered using a service called FitnessSyncer, because it uses a REST API and Updates through multiple areas, including Samsung Health, but also Google Fit and Fitbit, and synchronizes the other connections to the app, but it is a paid service.

**Additional context**

Samsung does have a REST API endpoint, but it is locked town to ONLY corporate customers, and not to 3rd party integrations. The only feasible way would be the Companion App, since it has the structure to do so.

Reference here (for Health): https://developer.samsung.com/onlinedocs/health/overview-summary.html

**Comment by dshokouhi** [comment]
I don't think we should do anything for a manufacturer this specific in the companion app. We should only use official Android API and for google fit there is already a custom component which is a better fit than the app.  Also the program is locked down to only approved partners.

![Screenshot_20210422-070614.png](https://user-images.githubusercontent.com/1634145/115728354-4cb00700-a339-11eb-97f2-187a31f55d50.png)

**Comment by iotemylabs** [comment]
Okay, how about Battery and Charging State of the Watch? It should be supported in the Android SDK, but for some reason it isn't, at least to my knowledge.

**Comment by dshokouhi** [comment]
There are plans for Android Wear OS but not for tizen which is Samsung specific and does it's own thing. You should try to research and see if there are any system intents you can listen to. If Samsung has one then you can extract the data from the intent.

**Comment by dshokouhi** [comment]
Closing as we won't be adding support for Samsung Health in the app as its locked out to partners only and if its a REST API may make more sense to add it to HA directly.

Tizen OS is not android and looking at hte API docs will require a tizen app to communicate back as its not built on android which is what this app/repo is about.

To achieve the watch portion of your request I recommend looking into the the various intents either Samsung apps offer or a third party app.  You will need to do your research to find out whats supported. From there you can use existing features in the app to send data back home.
