### ISSUE TITLE
Option to disable SSL/TLS checking.

### ISSUE THREAD

**Issue by abderraouf-adjal** [home-assistant/android#1524]
**Is your feature request related to a problem? Please describe.**
I'm using my own CA for my project with **.local** domains by using avahi-daemon on a raspberry-pi.
Android seems to have issues with detecting and working with those local domains for example Chrome browser cannot connect with an *DNS_PROBE_FINISHED_NXDOMAIN* error.
I would like to connect to an IP with SSL/TLS enabled for its domain name, but that will give an *SSL_ERROR_BAD_CERT_DOMAIN* error by default (eg. in Firefox on Linux).

**Describe the solution you'd like**
In Firefox it can ignore the BAD CERT DOMAIN error after consulting the user, and connect with an encrypted traffic.
Therefor adding an option to ignore SSL/TLS domain related errors in the Android app will be useful to some.

**Describe alternatives you've considered, if any**

Add option to ignore domain checking related errors but show the SSL/TLS cert info,
and if it valid on the CA trust system of the machine accept it, if it's not refuse to connect.

**Additional context**

This is important because IoT devices wireless traffic should be encrypted.

**Comment by dshokouhi** [comment]
Sorry we will not be bypassing or disabling this validation

see https://github.com/home-assistant/android/issues/448#issuecomment-724724968

**Comment by abderraouf-adjal** [comment]
I was able to get around it in my offline environment without using 3rd party services by using a SSL/TLS certificate that include both **DNS Name** and **IP Address** as a **Subject Alternative Name**, eg. _hub.local_ and _192.168.1.80_. then set the IP address _https://IP:port_ as my Android phone cannot work with mDNS of Avahi.

I hope this will be useful to users who use their own self-signed CA for home-assistant, thank you.
