### ISSUE TITLE
Flush DNS cache when app disconnects from HA

### ISSUE THREAD

**Issue by crashza** [home-assistant/android#1525]
**Is your feature request related to a problem? Please describe.**

Yes, My current network topology uses local DNS inside my lan to go directly to HA on Private IP and from outside my LAN HA uses Public IP for HA comms, When my phone switches to Wifi from 5G the companion app just disconnects and will not reconnect as its still trying the public IP, I can enable hairping NAT on my router to get around this but many people wont have this option on their routers, The only way to get the app to reconnect is completely closing it and re-opening

**Describe the solution you'd like**

Simple solution would be to refresh DNS record of HA URL when app gets disconnected, There is already an option that pops up saying refresh external URL but this too does not refresh the DNS.

**Describe alternatives you've considered, if any**

Enabling Hairpin NAT solves the issue but its not ideal in most situations. (Mikrotik NATS source IP so blacklisting etc from LAN will not be working as it should.)

**Additional context**

None

**Comment by dshokouhi** [comment]
> I can enable hairping NAT on my router to get around this but many people wont have this option on their routers, The only way to get the app to reconnect is completely closing it and re-opening



> Enabling Hairpin NAT solves the issue but its not ideal in most situations. (Mikrotik NATS source IP so blacklisting etc from LAN will not be working as it should.)

This is actually whats recommended for the companion apps and is suitable for most users.  Most users actually use Nabu Casa and don't have to worry about this.  The rest of us go by whats in the help docs:

https://companion.home-assistant.io/docs/troubleshooting/networking#hairpin-nat

**Comment by crashza** [comment]
Hi The docs also mention that the DNS split brain approach relies less on the cloud?

Haipin Nat relies on Wan network connection to be up and external DNS?

The docs mentioning Split brain should maybe then also mention that switching from external to internal DNS completely renders the app useless until a restart of the app.

**Comment by crashza** [comment]
Just to give you a scenario of how annoying this is when I get home I start opening the gate while my phone is on 4G then while the gate is opening my phone switches to wifi I am now unable to close the gate I have to first close the app and re-open very annoying, using chrome instead of the app i never had this issue it would show disconnected for around 1 second before reconnecting.

**Comment by pbzdyl** [comment]
I have the same issue and I don't have an option to enable Hairpin NAT. Implementing DNS flush would make my experience with the companion app much better.
