### ISSUE TITLE
Actionable notifications with URIs fail to open home assistant or display actions on Samsung A-115F/Android 10 

### ISSUE THREAD

**Issue by CloCkWeRX** [home-assistant/android#1528]
**Home Assistant Android version:**
2021.4.1-full

**Android version:**
10
One UI Core 2.0

**Phone model:**
Samsung A-115F

**Home Assistant version:**
core-2021.4.6

**Last working Home Assistant release (if known):**

**Description of problem:**
As per https://companion.home-assistant.io/docs/notifications/actionable-notifications/ I've tried describing a custom automation action:
```
service: notify.mobile_app_sm_a115f
data:
  data:
    actions:
      - action: URI
        title: View list
        uri: 'https://shoppinglist.google.com/lists/redacted'
  message: View shopping list
```
This successfully sends a notification, but is not translated into an action I can take. Pressing on the notification fails to launch the homeassistant app or present me with actions.

Viewing the home assistant data, the payload sent was:
```
{message=View shopping list, action_1_title=View list, action_1_key=URI, action_1_uri=https://shoppinglist.google.com/lists/redacted}
```

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
04-27 17:39:55.795 17606 17671 D UrlRepository: localUrl is: false and usesInternalSsid is: false
04-27 17:39:55.938 17606 17606 D SensorManager: unregisterListener ::   
04-27 17:39:55.938 17606 17606 D ProximitySensor: Proximity sensor listener unregistered
04-27 17:39:57.141 17606 17643 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=37546a80-8023-4f4e-b336-3ebb795cc48d, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
04-27 17:39:57.149 17606 17606 I WM-SystemFgDispatcher: Stopping foreground service
04-27 17:39:57.160 17606 17606 D ConnectivityManager: unregisterNetworkCallback; CallingUid : 10224, CallingPid : 17606
04-27 17:40:01.633 17606 21058 D MessagingService: From: 331041709873
04-27 17:40:01.638 17606 21058 D MessagingService: Message data payload: {message=View shopping list, action_1_title=View list, action_1_key=URI, action_1_uri=https://shoppinglist.google.com/lists/redacted}
04-27 17:40:01.649 17606 17606 D MessagingService: Creating notification with following data: {message=View shopping list, action_1_title=View list, action_1_key=URI, action_1_uri=https://shoppinglist.google.com/lists/redacted}
04-27 17:40:01.694 17606 17606 D MessagingService: Show notification with tag "null" and id "308331058"
04-27 17:40:03.001 17606 17606 D ViewRootImpl@9148a80[SettingsActivity]: ViewPostIme pointer 0
04-27 17:40:03.060 17606 17606 D ViewRootImpl@9148a80[SettingsActivity]: ViewPostIme pointer 1
04-27 17:40:03.101 17606 17606 D ScrollView: initGoToTop
04-27 17:40:03.199 17606 17606 D ViewRootImpl@9148a80[SettingsActivity]: Relayout returned: old=(0,0,720,1560) new=(0,0,720,1560) req=(720,1560)0 dur=10 res=0x1 s={true 3097278464} ch=false
04-27 17:40:03.205 17606 17606 D ActivitySM: Received activity update.
04-27 17:40:03.211 17606 17653 D LogcatReader: Read logcat for pid 17606
04-27 17:40:03.218 17606 17606 D ActivitySM: Received activity update.
```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/365751/116206996-8e4c1200-a77e-11eb-907c-081d03b67411.png)

![image](https://user-images.githubusercontent.com/365751/116206815-5a70ec80-a77e-11eb-8767-6016f796256e.png)

**Additional information:**
Not sure if it's more the case of the notification won't launch the home assistant app; or if it won't display actions in the notifications as it's Samsung's One UI Core rather than proper android; or a mix of both.

**Comment by dshokouhi** [comment]
Have you tried clearing data to see if it works?

**Comment by dshokouhi** [comment]
Based on the frist screen shot it looks like the action is present....can you click on the down arrow in the notification to properly expand the notification?

**Comment by CloCkWeRX** [comment]
Doh, you are right. Sometimes the simplest answers... (and I hadnt actually discovered that aspect of the notification UI, *facepalm*).

I think what confused me most was the notification not opening the app on interaction with it, and an expectation of a different UI presenting these (along the lines of the suggested text replies UX)
