### ISSUE TITLE
Android Sleep confidence freezing on android 11

### ISSUE THREAD

**Issue by bruvv** [home-assistant/android#1530]
**Home Assistant Android version:**
Beta-672-a016525-full and tried on 2021.4.1

**Android version:**
11

**Phone model:**
Oneplus 7 pro

**Home Assistant version:**
2021.4.6

**Last working Home Assistant release (if known):**
2021.4.6

**Description of problem:**
When I ran android 10 on my phone the sleep confidence worked perfectly fine. But for now, after upgrading 11 it works sometimes and then freezes.
I tried force stopping the application but that doesn't work. I tried removing the app and reinstalling everything. Didn't work
Only thing that works, rebooting the phone.  This is what you see in the screenshot.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![afbeelding](https://user-images.githubusercontent.com/3063928/116367060-744e1600-a7f6-11eb-8992-5e24968362fa.png)

Battery temps:
![afbeelding](https://user-images.githubusercontent.com/3063928/116367343-c98a2780-a7f6-11eb-9d6d-2b54524d92b4.png)

**Additional information:**
I made sure that the app isn't being killed and keeps running in the background. As can be seen, my battery temperature keeps working just fine.

**Comment by dshokouhi** [comment]
Any reason why you didn't show the logs as requested? We send whatever data we get when it comes. If your phone update caused the issue then it's definitely not a problem with the app.

**Comment by bruvv** [comment]
> 
> 
> Any reason why you didn't show the logs as requested? We send whatever data we get when it comes. If your phone update caused the issue then it's definitely not a problem with the app.

Shoot, good one I was on work and didn't check my phone to upload the logs. Here you go. And I tested it on 2 different phones both with android 11.
[homeassistant_companion_log_3-28-2021_16-16-0.txt](https://github.com/home-assistant/android/files/6392433/homeassistant_companion_log_3-28-2021_16-16-0.txt)

**Comment by dshokouhi** [comment]
> > 
> > 
> > Any reason why you didn't show the logs as requested? We send whatever data we get when it comes. If your phone update caused the issue then it's definitely not a problem with the app.
> 
> Shoot, good one I was on work and didn't check my phone to upload the logs. Here you go. And I tested it on 2 different phones both with android 11.
> [homeassistant_companion_log_3-28-2021_16-16-0.txt](https://github.com/home-assistant/android/files/6392433/homeassistant_companion_log_3-28-2021_16-16-0.txt)
> 

Just fyi it has nothing to do with Android 11 as my pixel 4 does not have this issue. I can also see the updates are coming without error accusing to the logs. This is not an app issue as our updates are coming in and we rely on Google to push those updates to us. If they don't push an update then nothing we can do. Since you said it started after the OS update is probably a device issue.

**Comment by dshokouhi** [comment]
Do these logs capture when the issue occurred?

**Comment by bruvv** [comment]
Thanks for the update, not exactly. The freeze of the sleep happened when I was sleeping. I will monitor it atm and see if it stops syncing again, then I will post another log.

**Comment by dshokouhi** [comment]
unless we see a specific crash that the app can handle I am not sure this is something we can fix.  All we do is register for updates and send them as google sends us the update.  Much like location.

**Comment by bruvv** [comment]
It happened again. Here a new log:
https://pastebin.com/8p3LGmsN
at 10:11 PM it received the last sleep status. Is there anything in the logs? Otherwise I will see if I can just format the whole phone and restart.

Would you mind removing the other log, as it included sensitive data :)

**Comment by bruvv** [comment]
Tha k you so much for your patience and elaboration. I'll close it for now.

**Comment by bruvv** [comment]
I am still debuging this cause, since it is fixed on 1 phone but the other is refusing to update it ;) anyway is this something I should worry about?
```
05-05 15:17:54.213  6036  6036 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
05-05 15:17:54.214  6036  6036 E mpanion.androi: Invalid ID 0x00000000.
05-05 15:17:54.215  6036  6036 I chatty  : uid=10472(io.homeassistant.companion.android) identical 8 lines
05-05 15:17:54.215  6036  6036 E mpanion.androi: Invalid ID 0x00000000.
05-05 15:17:54.215  6036  6036 E mpanion.androi: Invalid ID 0x00000000.
05-05 15:17:54.215  6036  6036 I chatty  : uid=10472(io.homeassistant.companion.android) identical 1 line
05-05 15:17:54.215  6036  6036 E mpanion.androi: Invalid ID 0x00000000.
05-05 15:17:54.215  6036  6036 E mpanion.androi: Invalid ID 0x00000000.
05-05 15:17:54.216  6036  6036 I chatty  : uid=10472(io.homeassistant.companion.android) identical 9 lines
05-05 15:17:54.216  6036  6036 E mpanion.androi: Invalid ID 0x00000000.
05-05 15:17:54.217  6036  6036 E mpanion.androi: Invalid ID 0x00000000.
05-05 15:17:54.217  6036  6036 I chatty  : uid=10472(io.homeassistant.companion.android) identical 2 lines
05-05 15:17:54.217  6036  6036 E mpanion.androi: Invalid ID 0x00000000.
```

**Comment by dshokouhi** [comment]
Looks like something that might get fixed by a device reboot?

**Comment by bruvv** [comment]
> 
> 
> Looks like something that might get fixed by a device reboot?

That was quick on the reply, thanks :) this was just after a reboot

**Comment by dshokouhi** [comment]
Looking online its not related to sleep confidence it seems to be related to a missing resource ID (i.e. translation) What language do you view the app in?

**Comment by bruvv** [comment]
> 
> 
> Looking online its not related to sleep confidence it seems to be related to a missing resource ID (i.e. translation) What language do you view the app in?

Device Language, which is set to English (Netherlands) (so dutch region settings, english language)

**Comment by bruvv** [comment]
After changing the app to different languages it doesn't change the error. The same keeps getting spammed. Would you like me to open a new issue about this since it's probably unrelated to each other ?

**Comment by bruvv** [comment]
After disabling automatically close connection the sleep stats have been working for about 12 hours now. Why is that ?

**Comment by dshokouhi** [comment]
> After changing the app to different languages it doesn't change the error. The same keeps getting spammed. Would you like me to open a new issue about this since it's probably unrelated to each other ?

No need, we don't know what the cause is and without steps to reproduce we wouldn't know how to fix it.  It doesn't seem to be causing any issues



> After disabling automatically close connection the sleep stats have been working for about 12 hours now. Why is that ?

Thats unrelated.  Thats a HA frontend setting and has nothing to do with sending sensor data back home or even registering for sleep events.  Maybe your device received a play services update that fixed it?

**Comment by bruvv** [comment]
> > After changing the app to different languages it doesn't change the error. The same keeps getting spammed. Would you like me to open a new issue about this since it's probably unrelated to each other ?
> 
> No need, we don't know what the cause is and without steps to reproduce we wouldn't know how to fix it. It doesn't seem to be causing any issues
> 
> > After disabling automatically close connection the sleep stats have been working for about 12 hours now. Why is that ?
> 
> Thats unrelated. Thats a HA frontend setting and has nothing to do with sending sensor data back home or even registering for sleep events. Maybe your device received a play services update that fixed it?

No I updated the play service 7 days ago. Didn't change anything apart from that. Perhaps it some weird hidden battery setting perhaps on OnePlus? I did double check that it is no optimised aka killed in the background and locked it into ram.... Anyway to make sure it isn't related I reenabled the setting. Let's see what will happen.

**Comment by dshokouhi** [comment]
I usually always refer people to dontkillmyapp.com as they do a lot of research on this topic.

https://dontkillmyapp.com/oneplus

Since you said only this one sensor is impacted and as the data is only provided by Google I don't suspect the issue is related ot the app being killed.  If that were the case then simply opening up the app will re-register with Google sleep API and data will continue but you mentioned you had to reboot the device for it to work so thats not really killing the app.  Sounds more like some type of corruption or software bug on Google's end.

**Comment by bruvv** [comment]
And to update this again. It stopped working again. Even though I didn't change anything....

**Comment by sdlafferty** [comment]
Hi

Just wanted to add that I've started seeing something similar. From sometime on the evening (AWST) of the 28th December, the granularity and update frequency of the sleep confidence value suddenly was reduced. As you can see in the screenshot before, there was no similar impact to the battery charge level graph. I am not aware of any changes I may have made at that time, though it is possible I installed an update to HA ot something.
 
![image](https://user-images.githubusercontent.com/29133534/148707234-c6bc083f-fd71-4f27-b2b9-b633de16509b.png)

**Comment by dshokouhi** [comment]
> Hi
> 
> Just wanted to add that I've started seeing something similar. From sometime on the evening (AWST) of the 28th December, the granularity and update frequency of the sleep confidence value suddenly was reduced. As you can see in the screenshot before, there was no similar impact to the battery charge level graph. I am not aware of any changes I may have made at that time, though it is possible I installed an update to HA ot something.

Its never a good idea to comment on an old and closed issue always good to make a new one.

The issue here is that we wait for Google to send the app an update and then we send that to HA. If there is any delay its from Google so nothing we can do about it. You can see in the logs when we get an update. Battery level is taken from the OS directly so we dont wait for an external response. The sleep sensors use Google APIs which is not part of Android itself.

https://developers.google.com/location-context/sleep

**Comment by sdlafferty** [comment]
Sorry, I hadn't noticed it was closed.

Just thought I'd add that it appears the issue ws because for some reason the Home Assistant app "Allow background activity" had been switched off. I switched it on and granularity has come back almost immediately. Not sure why that setting only affected the sleep confidence.
