### ISSUE TITLE
Quick Access Device Controls - Remove header on long press

### ISSUE THREAD

**Issue by Kvasenok** [home-assistant/android#1531]
**Home Assistant Android version:**
 2021.4.1-full

**Android version:**
Android 11

**Phone model:**
SM-G970F

**Home Assistant version:**
Home Assistant 2021.4.6

**Last working Home Assistant release (if known):**

**Description of problem:**
Now if you long-press on a quick access device control button (it's just a press on Samsung devices) it opens up a more info view of the entity, but it opens it with the app header visible, which makes it possible to navigate the HA app without actually opening it if you press the X on the header (blue background). 
I believe this is not intentional behavior since the more info view already has "exit" and "open app" buttons built-in. 
The app should somehow ignore the header on the long press and only open entity info view, which would prevent users from surfing the whole app within a more info window.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20210428-153716_Home Assistant](https://user-images.githubusercontent.com/44749170/116406896-d419e080-a839-11eb-8c41-42258397437e.jpg)
![Screenshot_20210428-153736_Home Assistant](https://user-images.githubusercontent.com/44749170/116406906-d67c3a80-a839-11eb-94f6-c59d4f8004f3.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
Sorry we will not manipulate the frontend like that
