### ISSUE TITLE
Notification sound changing, Android 11.

### ISSUE THREAD

**Issue by mattlward** [home-assistant/android#1533]
**Is your feature request related to a problem? Please describe.**

Yes, I am hearing challenged and need different sounds for notifications.
**Describe the solution you'd like**

I would love to have the ability to change the notification sound for this app versus for the device as a whole.
**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
You can change the notification channel sound for any notification channel that you create.  This can be done in your device settings.  Its different for every device so you will need to research it.  Most likely somewhere in device settings you will find the correct page.  On my Pixel its under Settings > notifications > home assistant

Here is how to create additional channels so you can configure each one to have a different sound

https://companion.home-assistant.io/docs/notifications/notifications-basic/#notification-channels

**Comment by mattlward** [comment]
Wow, I just did not dig deeply enough, the sound was buried 2 layers deep under Settings > notifications > home assistant, and it appeared that you could only turn on/off the sound until the last layer was opened.  

I will also dig into that link above as I would like a separate sound for shutdown/restart verses a common notification. 
Thanks
