### ISSUE TITLE
Battery drain after leaving the house

### ISSUE THREAD

**Issue by TheGabeMan** [home-assistant/android#1534]
<!-- READ THIS FIRST:
- Make sure you run the latest version of the Android app
- Make sure you run the latest version of Home Assistant
- Make sure to check the Companion docs for troubleshooting and configuration: https://companion.home-assistant.io/
- Make sure the bug you found is not already reported, we love to put work in bugfixes instead of closing duplicate bug reports
  DO NOT DELETE ANY

**Home Assistant Android version:**
2021.4.1-full

**Android version:*
OnePlus Oxygen 11.0.0.2

**Phone model:**
OnePlus 7 Pro

**Home Assistant version:**
2021 4.6
**Last working Home Assistant release (if known):**
n/a
**Description of problem:**
When leaving the house and getting into my car it seems the battery drain by the HA app is very high. It feels as if also linked to "Android Auto". But after closing Android Auto (leaving the car) the battery drain by HA is just as big. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**
Since it is not a crash, I'm not sure on which logs to get and how. How can I troubleshoot this?

**Comment by dshokouhi** [comment]
Please make sure to fill out the issue template you also need to be much more descriptive if you want any help here.

**Comment by TheGabeMan** [comment]
Hmmm, wrote this on my phone in the Github app and it seems to be empty now because I did fill out the template. 



**Home Assistant Android version:**
2021.4.1-full

**Android version:**
OxygenOS 11.0.0.2

**Phone model:**
OnePlus 7 Pro

**Home Assistant version:**
core-2021.4.6

**Last working Home Assistant release (if known):**
Have had this for a few release already.

**Description of problem:**
When out of the house the battery drain is much heavier than in house. Now I do have the feeling that this could be related to driving my car . When connected to my car I see the HA icon in the topbar constantly jumping. When I go out with my bike or for a walk, this doesn't happen.

Yesterday HA took 30% of my battery life, the next app was around 3%. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

Since there is no crash, I'm not sure if there are any crash logs.

**Screenshot of problem:**
n/a

**Additional information:**

**Comment by dshokouhi** [comment]
What sensors do you have enabled?

**Comment by TheGabeMan** [comment]
I think all sensors. That's about 68 for my phone.

**Comment by dshokouhi** [comment]
Try setting an allow list for the notification sensors. There's a note about this in the docs. Also make sure the bt transmitter sensor is not transmitting when you aren't at home that can cause drain too.

**Comment by TheGabeMan** [comment]
Will do. Thx

**Comment by JBassett** [comment]
Another thing to look out for is the fact that if you plug your phone into a vehicle that has Android Auto your phone will maintain a GPS lock even if you don't open Android Auto on your dash.  And since we listen for GPS events we will intern send that data back to Home Assistant consistently.

**Comment by dshokouhi** [comment]
Closing due to lack of response
