### ISSUE TITLE
Unable to connect to home assistant if not all ports opend on android

### ISSUE THREAD

**Issue by dflvunoooooo** [home-assistant/android#1535]
**Home Assistant Android version:**
2021.4.1-full
**Android version:**
10
**Phone model:**
PH-1
**Home Assistant version:**
core-2021.4.6
supervisor-2021.04.0
**Last working Home Assistant release (if known):**

**Description of problem:**
If I close all apparently unnecessary ports on the router I can not connect to my HA. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20210501-192029556](https://user-images.githubusercontent.com/32816598/116790026-747a3a00-aab2-11eb-9c90-bbf6d6228fcf.jpg)

**Additional information:**
I have an SSL certificate and NGINX reverse proxy up and running. If I forward all ports on my router to my HA instance the app is able to connect. If I only allow the ports configured in the NGINX addon, the app can no longer connect. I have no idea why that happens. Maybe I am missing something? Has anybody an idea?

**Comment by dshokouhi** [comment]
Did you run the same test in a browser? This doesn't seem to be an issue with the app.

**Comment by dflvunoooooo** [comment]
I just testet it in firefox, you are right, I am sorry. Will post elsewhere.
