### ISSUE TITLE
No access only on external connection in mobile app

### ISSUE THREAD

**Issue by cooltronicpl** [home-assistant/android#1537]
**Home Assistant Android version:** 2021.4.1-full

**Android version:** 11 (MSM Xtended ROM)

**Phone model:** Xiaomi Mi A2 Lite

**Home Assistant version:** 2021.4.6

**Last working Home Assistant release (if known):** -

**Description of problem:**

I'm using Nginx proxy on 443 port with a custom domain.
When I'm connecting in any browser on phone I was get connected properly in internal and external connection.
When I try to connect on an external connection I have "Unable to connect... Retry", but with an internal connection to an IP address from a WiFi network (unencrypted), it works without any problems.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
UrlRepository: Using external URL
UrlRepository: Using external URL
UrlRepository: Using internal URL
```

**Screenshot of problem:**

**Additional information:**
I tried to remove the device, clear all app data, nothing works.
The server works without any problems on an external web browser.

**Comment by dshokouhi** [comment]
is your certificate valid? anything else special about it? the app doesnt support TLS or anything like that just a valid SSL cert.

**Comment by cooltronicpl** [comment]
The certificate is valid, nothing in a log of the server and android app.
![cert](https://user-images.githubusercontent.com/35310568/117084623-f636c580-ad47-11eb-81cf-747a61689276.jpg)
This is a let's encrypt certificate.

**Comment by dshokouhi** [comment]
If you take out nginx and directly connect to HA does it work?

**Comment by cooltronicpl** [comment]
Yes, it works.
On another phone, it works without any problems.
On only desktop browser on one computer and it is some problems, it not working on a local network with a public address.
I assume there were some data are stored on the server side of HA. I tried to clear all data on this desktop browser and it doesn't fix anything.

**Comment by dshokouhi** [comment]
Since you mentioned it works when nginx is taken out of the loop this is not an app issue.  Try the forums or discord for more support on your network setup.

**Comment by cooltronicpl** [comment]
I changed the firmware of the phone to more stable, now it works without any problems with the internal connection to IP (with WLAN), and external with cellular.
