### ISSUE TITLE
App doesn't work with another System WebView

### ISSUE THREAD

**Issue by marrobHD** [home-assistant/android#1539]
**Home Assistant Android version:** 2021.4.1-full

**Android version:** Android 11 RKQ1.200826.002

**Phone model:** Xiaomi Mi 9

**Home Assistant version:** core-2021.5.0

**Last working Home Assistant release (if known):** core-2021.5.0

**Description of problem:**
When setting another WebView implantation in the Android Developer Settings (tested Bromite System WebView 90.0.4430.204)

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):** Logs later available

```

```

**Screenshot of problem:**
![Screenshot_2021-05-07-12-19-01-278_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/29308361/117435707-6f900d00-af2e-11eb-8c2d-6311f4707a13.jpg)

**Additional information:**
Bromite GitHub: https://github.com/bromite/bromite/releases

**Comment by dshokouhi** [comment]
We only support Android system WebView.
