### ISSUE TITLE
HA Android Companion app renders AA outgoing phone calls to non working

### ISSUE THREAD

**Issue by GSzabados** [home-assistant/android#1540]
**Home Assistant Android version:** 2021.4.1-full and 2021.5.1-full 

**Android version:** Android 10, One UI 2.5, 1st December 2020 Security patch

**Phone model:** Samsung Galaxy (S10 SM-G973F)

**Home Assistant version:** 2021.5.1

**Last working Home Assistant release (if known):** I believe that is more likely the app, but maybe the one before 2021.4.1-full

**Description of problem:**

Once the phone is connected to the Android Auto head unit (Mazda 6), the Android Companion app stops working. If I try to open the app only a white screen welcomes me with a blue header line, nothing else. Meanwhile if I try to make a phone call from the Android Auto screen, or from the phone itself, sometimes the ongoing call succeeds, but most of the time it even doesn't start the dialing. You may ask, why I think that it is due to the HA Android Companion app. If I go to the settings of the phone and then to apps and Force Stop the companion app the phone calls start to work immediately. Something hogs the system from HA Android Companion app to be able to start outgoing call.

Any advise would be welcome how to fix it.

 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

![Screenshot_20210511-164318_Home Assistant](https://user-images.githubusercontent.com/35445496/117835702-5f529780-b278-11eb-94e0-91681a577e7d.jpg)

**Additional information:** Other maybe related issues, the companion app hangs time to time and a system pop-up comes up and asking do I want to wait or kill. Since the update to 2021.4.1-full the single widget what I use time to time goes into a flashing state, changing icon from the set icon to a flash icon continuously without pressing it.
All sensors are enabled.

**Comment by GSzabados** [comment]
Today I tried to clear cache as well, but it changes nothing. 

How can I debug this issue?

**Comment by GSzabados** [comment]
I have just updated the app to 2021.5.1-full, the situation changed that much, that I could open the app when the phone is connected to AA, but scrolling is just incredibly slow, the app seems to hang.
But I still cannot start a phone call from the AA screen.

**Comment by GSzabados** [comment]
I've spent about an hour trying to turn on one by one the sensors in the up, as it was not showing any issues when I turned all of them off.

I managed to narrow down the issue to the notification related sensors, especially the following two:

- Active Notification Count
- Last Notification

This two sensors puts the app into a state what I mentioned above. It lags on each press or swipe and AA unable to make any outgoing phone calls.

As they are active notification related, I can guess AA active navigation or just AA active notification does something funny what the app cannot handle.

**Comment by dshokouhi** [comment]
You may just need to keep these sensors disabled if they are causing issues.  Any reason why you skipped over providing logs?

@JBassett  have you noticed this? I dont have an android auto car so cant really provide feedback here lol

**Comment by GSzabados** [comment]
@dshokouhi, actually there is no crash. So there isn't any crash log. And obviously on 2021.4.1-full, I couldn't even open the app to reach the log, when AA was running. 
With 2021.5.1-full, I thought that, as I can remember I enabled all the sensors when installed 2021.4.1-full, and what else could be at all. So a day after having 2021.5.1-full installed I had enough time to try to turn off (all) and on the sensors one by one and found those causing the lag on the device.
If you need logs let me know, I can navigate to produce some now, with those sensors on.
Otherwise when the pop-up comes with wait or kill, I sent a few logs already with that.

**Comment by dshokouhi** [comment]
can you try creating an allow list for last notification sensor and just not include android auto but only the apps you care for? if android auto is updating the status bar then we will get all those updates and send them all if they are different.

**Comment by GSzabados** [comment]
> can you try creating an allow list for last notification sensor and just not include android auto but only the apps you care for? if android auto is updating the status bar then we will get all those updates and send them all if they are different.

Sorry, I, a bit, lost you. Do you mean to disable the AA notification on Android level and try that way? And you would like to have a log with and without AA notifications included? Am I understand you correctly?

**Comment by dshokouhi** [comment]
No it's a setting for the sensor

https://companion.home-assistant.io/docs/core/sensors#last-notification

**Comment by GSzabados** [comment]
> No it's a setting for the sensor
> 
> https://companion.home-assistant.io/docs/core/sensors#last-notification

Oh, OK! I wasn't really aware of that setting there. I have just looked at the Active Notification Count as well and I see where things can go wrong with that one. I thought that might contain only the number of Notifications, but now I see it has an excessive list of attributes as well.

I will try to get some logs. The list of Notification for apps is a bit long. I will need to dig into it, what really I will need there.

Thanks for the reply!

**Comment by dshokouhi** [comment]
Just follow my advice and you will be fine. Setting an allow list cuts down on the amount of data being sent and will fix your issue. Active notifications only sends updates when other sensors have an update. It's also described in the docs at it went cause a slow down. The other could depending on what's triggering it.

**Comment by GSzabados** [comment]
Last week I was driving a lot and wanted to generate some logs for this issue, but currently I have another issue with the HA Android Companion app.
Now AA is working without any issue, and that is great, I can easily start phone calls. But the HA Android Companion app hangs a lot by itself. It seems like the sensor update causes the hangs, but I haven't had enough time yet to find out which sensor or sensors are the source of it. So when the app is opened hangs, the  when navigating in the menu it hangs again once a sensor update happens, then usable again.

**Comment by GSzabados** [comment]
@dshokouhi, unfortunately for a longer period I will have no chance to debug this issue, so I will close it for now, as removing those sensors initially fixed my problem and will be help for anyone who experiences the same. Once I have more time I will reopen it and send some logs.

**Comment by dshokouhi** [comment]
@GSzabados I hope if you do decide to open another bug you will have taken my advice earlier about using an allow list for this feature.  From the sound of things I don't think you did it and are just leaving the notification sensor enabled without an allow list, you need to set one if your device can't handle it.

**Comment by GSzabados** [comment]
@dshokouhi, I have disabled all the notification sensors. Something else causes the issue now. But AA is working this way.

![Screenshot_20210614-065212_Home Assistant](https://user-images.githubusercontent.com/35445496/121840778-3bea9480-ccdd-11eb-8903-a3f51cce3985.jpg)
