### ISSUE TITLE
Music Active Sensor only works when app is in foregrounnd

### ISSUE THREAD

**Issue by gary-reyes** [home-assistant/android#1542]
The music active sensor only seems to change status if the home assistant companion app is in the foreground or I press the power button to turn off the screen.

I waited for around 2 minutes while spotify music was playing and state didn't go from off to on until I did one of the two things above. 

I made sure that the companion is allowed to run in the background and all permissions are granted.

App Version: 2021.4.1-full
Android version: Android 11 (Pixel 5)
Android security update: May 5, 2021
Google Play System update: April 1, 2021

**Comment by dshokouhi** [comment]
Per the documentation this is expected. Try to enabled the notification sensors and keep the media apps in the allow list. More details can be found in the docs.  This sensor does not update upon state changes.

**Comment by gary-reyes** [comment]
Can you point me to the place in documentation where it talks about the allow list?

**Comment by dshokouhi** [comment]
https://companion.home-assistant.io/docs/core/sensors#last-notification

You can also access the right place in the docs by tapping on the help icon at the top right hand corner when you are on teh sensor details page.  The page where you set the allow list.
