### ISSUE TITLE
Missing "Turned off/Air mode" Phone State Sensor status

### ISSUE THREAD

**Issue by andrea-HA** [home-assistant/android#1544]
**Is your feature request related to a problem? Please describe.**

I tried to find a way to be sure if the phone is turned off or in airplane mode, in my case that would be helpful for presence detection, but the phone state sensor doesn't change when these two events happen, leaving all the Companion sensors on their last known state. 
**Describe the solution you'd like**

Well, I suppose there's a good a reason the state sensor doesn't detect the turned off / airplane status, but the best and more natural solution would be to detect these statuses changing the value sensor accordingly. 

**Describe alternatives you've considered, if any**

The only other alternative I'm trying to implement is to ping back my Home Assistant Hub in some ways, very likely Tasker or the like, to say the phone is still turned on, letting the sensor trigger when this ping stops being sent for a certain amount of time. 

**Additional context**

**Comment by dshokouhi** [comment]
This is not something we can handle in the app itself.  This is part of the `mobile_app` integration.  If the device cant send data then this wil never work.  We cant send an update saying "the phone is shut down" or even "airplane mode" being enabled.  You will need to raise a feature request for HA core in the community forums for this to work properly.
