### ISSUE TITLE
Missing background integration with dashboard

### ISSUE THREAD

**Issue by Crippe16** [home-assistant/android#1545]
**Is your feature request related to a problem? Please describe.**

I can see my phone in the dashboard, but it only updates the info when the app is on screen on my phone, otherwise it stays stuck.

**Describe the solution you'd like**

Background functionality without needing to open the app.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
You need to grant background access for the app and also depending on your manufacturer you will need to adjust more settings.  We cant tell you what else to adjust as each manufacturer does thigns differently. The below site may be of help

dontkillmyapp.com
