### ISSUE TITLE
Android 11 Power Menu, Light percent / slider no longer working

### ISSUE THREAD

**Issue by rwarner** [home-assistant/android#1546]
**Home Assistant Android version:**
2021.5.1-full

**Android version:**
Android 11

**Phone model:**
Pixel 3

**Home Assistant version:**
2021.5.4

**Last working Home Assistant release (if known):**
2021.4.6

**Description of problem:**

Originally, I used to be able to do the folllowing:

Unlock phone -> Hold Power Button -> Access quick controls for HA buttons -> Slide my finger left/right to control the light percentage on each Light Button.

It now seems as though all of the light buttons are ONLY buttons for off/on functionality and that, that former feature is gone?

Unsure why this would just disappear

https://companion.home-assistant.io/docs/integrations/android-power-menu
https://developer.android.com/guide/topics/ui/device-control

Seems to default now to a "ToggleTemplate" rather than a "ToggleRangeTemplate":

https://github.com/home-assistant/android/blob/cf27aa994fba0938aaaf6707a505421ef74d129b/app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt#L61-L82

**Comment by JBassett** [comment]
@rwarner I just validated on my zigbee lights and the slider is working as expected.  Are you sure that your light's show supporting brightness in Home Assistant?

**Comment by rwarner** [comment]
Interesting, yeah the lights show brightness in the entities areas. No issues using any of the sliders within the app or directly on HA. Just not supporting the feature in my power menu

**Comment by dshokouhi** [comment]
I also cannot reproduce this.  Maybe something is corrupted and needs to be reset? Have you tried any basic troubleshooting steps?

Also what @JBassett was mentioning is that your light needs to have `SUPPORT_BRIGHTNESS` feature supported in HA for the slider to show up.  If it shows in teh HA frontend more than likely the integration added support for that.

We will need more to go off on this issue but first try some basic troubleshooting steps outlined in the companion docs.

**Comment by rwarner** [comment]
```your light needs to have SUPPORT_BRIGHTNESS feature supported in HA ```

Where exactly can I check this? I'm in Developer Tools -> States -> I go to said light object/entity and in the attributes it has

supported_color_modes: brightness
color_mode:brightness
brightness: 254

just as a few attributes that include "brightness"

These are just hue lights connected through zigbee on HA, nothing special.

```Have you tried any basic troubleshooting steps?```

Yeah, but I will keep poking around and list everything I tried next.

**Comment by dshokouhi** [comment]
> Where exactly can I check this? I'm in Developer Tools -> States -> I go to said light object/entity and in the attributes it has

hard to describe it without looking at the code, youll `supported_features` in the attribute and the sum total will represent if brightness is included or not.


> Yeah, but I will keep poking around and list everything I tried next.

so you tried clearing app data and all that already?

**Comment by rwarner** [comment]
> hard to describe it without looking at the code, youll `supported_features` in the attribute and the sum total will represent if brightness is included or not.

Ah, we're talking about two different things I think. I'm mainly just talking about the HA instance dashboard and checking the attributes on there.

> so you tried clearing app data and all that already?

I have not cleared the app data or reinstalled it, mainly just:

 - Restarted HA instance
 - Double checked the brightness ability on HA not on the App
 - Double checked the brightness changes using the HA Android app outside of the power toggle
 - Removed the Power Toggle Buttons / widgets and re-added them

Was hoping to avoid more drastic measures, but I'll try something like that next.

**Comment by rwarner** [comment]
Okay, so I did the following and still have the lights not showing up as a brightness slider:

- Cleared Cache Data (Android)
- Cleared App Data (Android)
- Uninstalled, rebooted, re-installed (Android)

- Deleted Log file and database on HA instance (Linux)
- Restarted HA Instance (Linux)

After all this, also tried re-adding the light entities in the power menu area and no difference

**Comment by dshokouhi** [comment]
ah good catch on the light group, the code that you pointed out seems to be the issue here

**Comment by rwarner** [comment]
Thanks! Hopefully when that's resolved, I'm assuming this will be as well. Appreciate your time

**Comment by dshokouhi** [comment]
looks like we will need to update the app based on the following comment https://github.com/home-assistant/core/issues/50563#issuecomment-847251138

**Comment by dshokouhi** [comment]
@rwarner can you try the debug APK from: https://github.com/home-assistant/android/actions/runs/872637780 and let me know if it works for the light again?

**Comment by rwarner** [comment]
@dshokouhi just tried it and worked perfect with that apk. Both a single light and group of lights 👍🏼
