### ISSUE TITLE
Getting notification messages pop-up on-screen on Android

### ISSUE THREAD

**Issue by oywino** [home-assistant/android#1547]
**Is your feature request related to a problem? Please describe.**

Why is it that the Actionable Notifications demonstrated here: https://www.youtube.com/watch?v=TYxueq4X64U only works on an iPhone and not on an Android phone?

**Describe the solution you'd like**

I'd like to be able to have a pop-up message on the lock screen on my Android phone when I use the notify.mobile_app service (just like it does on an iPhone). And, I'd like to be able to add media entity ID's to a message.

**Describe alternatives you've considered, if any**

So far, the only alternative I've found - is to ditch my Galaxy and buy an iPhone  😢

**Additional context**

Is it by design (purposly) that the functionality of the iPhone companion app is so much more versatile than its Android counterpart?

**Comment by dshokouhi** [comment]
This is not something android has control over, this is a platform difference.  You will need to go in your device settings and see if there is a lock screen option to expand notifications there.  On my pixel this setting is off by default.  On your samsung who know they do a lot of non-standard android things unfortunately and its out of our control.
