### ISSUE TITLE
Companion app unable to connect to homeassistant (after initial login)

### ISSUE THREAD

**Issue by nabeelmoeen** [home-assistant/android#1549]
**Home Assistant Android version:**
2021.5.1-full 
(also tried the minimal version with same results)

**Android version:**
Android 10 - without GooglePlay services

**Phone model:**
S9+

**Home Assistant version:**
2021.5.4

**Last working Home Assistant release (if known):**

**Description of problem:**
When app is installed / (or data cleared and signed in again), the homeassistant UI loads correctly. After a some time the app goes ends up displaying a screen with the error message 'Unable to connect to Home Assistant. retry'
once the error appears the app is unable to connect irrespective of number of retries, until the app data is cleared and user signs in again. then the cycle repeats.
I am using a non-google play services android version, but the problem occurs both on the minimal (google free) and full version of the companion app.

home assistant is accessible via web browser on the same phone.
Also, all the sensors (phone sensors exposed by the app) continue to get updated on HA, as well as HA notifications appear on the phone. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
```
I/chromium: [INFO:CONSOLE(1)] "Uncaught (in promise) SecurityError: Failed to construct 'WebSocket': Access to this address is not allowed.", source: https://scsidashboard.duckdns.org/frontend_latest/core.7fd33a93.js (1)

```
```
Caused by: java.net.ConnectException: failed to connect to <duckdns domain name>/<IP address> (port 443) from /192.168.1.125 (port 33374) after 10000ms: isConnected failed: ECONNREFUSED
```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
your error message suggests your attempting to use HTTPS over an IP address? That won't work with the companion app.  I see you are using hte minimal version are you certain that you are using Googles provided Android System Webview and not the one your custom ROM provides? Those don't work either.

**Comment by nabeelmoeen** [comment]
I am using a URL to connect 
And as mentioned on first login the app logs in and does show the HA dashboard before eventually going into this "Unable to connect state"

**Comment by dshokouhi** [comment]
what about hte second part of my response? are you using a different webview or anything? the app only works with https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US&gl=US

I know by default this is not included in any custom ROM, they tend to use a different one

**Comment by nabeelmoeen** [comment]
Hi @dshokouhi ,
It appears this webview is not available for my ROM and also cannot be installed due to missing dependencies.

I am linking a screen grab video showing the app working (without the said webview) and then eventually crapping out.
i would assume it the webview were the issue it would prevent the app from running in the 'first logon' instance as well?
Screen grab video on Google Drive [https://drive.google.com/file/d/1j49lHlTnlgznZvtiGv2lN9Zyv_sN525o/view?usp=sharing](url)

**Comment by dshokouhi** [comment]
@nabeelmoeen it is your responsibility as a user to understand how your custom ROM works and how to install an app as a system level app.  You might be able to use xposed or something but that support is out of scope for this project.  You will need to ensure that you can use the proper version of webview to use the app.

**Comment by nabeelmoeen** [comment]
I still don't think its a web view issue, not sure if you viewed the video I linked above.
But I will try and trouble shoot a bit more and see if I can reproduce the issue on  a stock /OEM google ROM to provide more details
