### ISSUE TITLE
Blank ui-lovelace.yaml causes Android app to get stuck in "The Lovelace UI configuration for this dashboard was updated. Refresh to see changes?" loop

### ISSUE THREAD

**Issue by pmannk** [home-assistant/android#1550]
**Home Assistant Android version:**
2021.5.1-full

**Android version:**
10

**Phone model:**
Moto G9 Plus

**Home Assistant version:**
core-2021.5.5

**Last working Home Assistant release (if known):**
unknown

**Description of problem:**
After installing HA on a brand new Android phone (all software including WebView was up to date), the HA Android app was permanently stuck in a loop reporting "The Lovelace UI configuration for this dashboard was updated. Refresh to see changes?".
Refreshing did nothing and aside from the refresh popup, the app screen would remain blank.

This was the first time I installed the Android HA app after introducing yaml mode to /config/configuration.yaml
`lovelace:
  mode: yaml`
Also of note is my /config/ui-lovelace.yaml file exists, but is blank as I have a separate dashboard configured.

To work around the issue, I:
1. Removed the following from /config/configuration.yaml
`lovelace:
  mode: yaml`
2. Restarted HA core
3. Cleared the HA storage+cache on my Android phone
4. Went through the initial login/setup again on my Android phone
5. Android HA now, worked, so I changed my default dashboard over to my personalised one
6. Reverted back to lovelace yaml mode in /config/configuration.yaml and restarted HA core.
7. The Android app was unaffected 

It appears the Android app is unable to cope with lovelace in yaml mode when the configuration in /config/ui-lovelace.yaml is empty.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
How does chrome for Android handle the issue?

**Comment by pmannk** [comment]
In Chrome the page also rendered an initially blank dashboard with no menu, however you can at least change to the /profile URL and change the default dashboard which makes it usable, or as I often do, use the desired dashboard directly.
The lack on menu rendering in the Android app means you can never change the default dashboard in the app.

I reproduced this on my old phone just now too (Android 7, earlier WebView). Some screenshots for reference:

Chrome after initial logon:
![HA_Chrome_Before](https://user-images.githubusercontent.com/79073108/118935252-ae8e7b80-b98e-11eb-988e-ca0f28d377fd.png)

Chrome after you manually switch to /profile url and change the default dashboard:
![HA_Chrome_After](https://user-images.githubusercontent.com/79073108/118935264-b1896c00-b98e-11eb-8766-52fcacf06990.png)

Home Assistant Android app after initial logon (no way to escape this default dashboard)
![HA_AndroidApp](https://user-images.githubusercontent.com/79073108/118935275-b3ebc600-b98e-11eb-8877-61582cf5cb22.png)

**Comment by dshokouhi** [comment]
For the android app this is as designed.  When you use Lovelace in YAML mode with a blank UI the HA frontend should do any and all error handling.  There is no browser bar in the app and we will not be adding one.  Even according to the docs you need to have data entered.

https://www.home-assistant.io/lovelace/dashboards-and-views/#using-yaml-for-the-default-dashboard

If you still feel there is an issue feel free to open a discussion with the HA frontend as they should be handling this.

if you dont want to use this YAML file you should not use lovelace in YAML mode.

**Comment by pmannk** [comment]
OK thanks. I'll stick to a minimal markdown card so that it will at least render the menu bar.
