### ISSUE TITLE
Status bar colour slightly off

### ISSUE THREAD

**Issue by blair287** [home-assistant/android#1554]
**Home Assistant Android version:**

Latest on play store

**Android version:**

12 but also happening on 11

**Phone model:**

Pixel 5

**Home Assistant version:**

2021.5.5

**Last working Home Assistant release (if known):**

Not sure

**Description of problem:**

Status bar colour should match header colour but it's slightly off as can see a line.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

![Screenshot_20210520-215655](https://user-images.githubusercontent.com/44187409/119048052-9894b100-b9b6-11eb-9416-9d730926f55b.png)

**Additional information:**

**Comment by dshokouhi** [comment]
This is actually by design per Google's own material guidelines. See https://github.com/home-assistant/android/pull/1501

https://material.io/design/color/the-color-system.html

its meant to be distinguishable

**Comment by blair287** [comment]
> This is actually by design per Google's own material guidelines. See #1501
> 
> https://material.io/design/color/the-color-system.html
> 
> its meant to be distinguishable

Then they don't follow it themselves here's YouTube music status bar matches and in my opinion makes it look a lot cleaner.

![Screenshot_20210521-232606](https://user-images.githubusercontent.com/44187409/119203889-0ced5400-ba8c-11eb-9054-4cf7e49a5237.png)

**Comment by LasseRosenow** [comment]
@dshokouhi 

Google material design changed over the years and they did not always update all the specifications accordingly.
But gladly with Material 3 / Material You, which's specification just got published, they updated everything.

The status bar color should now always be the same color as the AppBar and the navigation bar color should be the same as either the bottom bar or the background. See:

![image](https://user-images.githubusercontent.com/10547444/140648082-c155abe6-6589-415c-a3eb-621da4cd596c.png)


Source: https://m3.material.io/styles/color/the-color-system/tokens

**Comment by LasseRosenow** [comment]
I opend a PR: #1882
