### ISSUE TITLE
Adjusting tiles crashes app

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/android#1556]
**Home Assistant Android version:**
2021.5.1
**Android version:**
11
**Phone model:**
Samsung S10plus
**Home Assistant version:**
Latest
**Last working Home Assistant release (if known):**

**Description of problem:**
As soon as I want to select the script to call in the tile configuration, the Android app crashes.
Names/labels are defined.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
We need the crash logs in order to fix the issue. Can you at least give us steps to reproduce? Can you show the script that's crashing?

**Comment by AleXSR700** [comment]
I will perform the steps again and send the crash log.

I cannot even select a script. When I press the menu item to select a script it crashes.

**Comment by dshokouhi** [comment]
The other day I noticed a few tile issues that I had submitted a PR to fix.  Can you try the debug APK at the link below and see if it works? You can install this version side by side the production version and it is safe to remove afterwards.  Just make sure to rename the device to something else so its easier to remove.

https://github.com/home-assistant/android/actions/runs/855202675

**Comment by AleXSR700** [comment]
![Screenshot_20210521-175406_Home Assistant](https://user-images.githubusercontent.com/57034871/119165271-9c2f4300-ba5d-11eb-8371-f8a946d3dd6a.jpg)

**Comment by dshokouhi** [comment]
can you check in HA that you have scripts to use and they are not corrupted?

**Comment by AleXSR700** [comment]
I will check them.
Just for my information: it is not possible to add a switch as a tile? Light the Android built-in torch that the triggers a HA switch?

**Comment by dshokouhi** [comment]
rigjht now only `script` and `scene` are supported

**Comment by AleXSR700** [comment]
Okay, I did not have a script or scene setup. So maybe there should be an error message rather than a crash? :)

I then setup a script and selected it. But after renaming the script in HA, the app does not list the renamed script and cannot call the script. Force closing also does not help. It just shows the non-existent script and does not show the newly renamed one. Is there maybe an update routine missing when clicking "Select a scene or script to call"?

**Comment by dshokouhi** [comment]
So the app will save teh script that you selected so if you renamed it then you need to update the tile data with the proper script, The list itself updates anytime the screen reloads so just go to another screen and come back to get the new list of entities.

I am workign on an update to hide the field if we don't get any valid entities as I thought that was the issue here so thanks for confirming :)

**Comment by dshokouhi** [comment]
if you are not seeing the updated script then try reloading scripts in HA to get the correct one.  The list of entities you see are those that your HA instance tells us.  Honestly if you rename an entity ID after already selecting it you should expect issues to occur until you correct them.  I tested this locally and my list of entities updates when I revisit the screen and reload scripts with a new name.

**Comment by AleXSR700** [comment]
The problem is that I cannot select the renamed script. I have only one script in HA which was named "lr_ambient". I selected that and updated the tile.
Then  renamed the script to "AmbientLight_LivingRoom".

But in the Android app I can still only select lr_ambient. The list is not updated no matter which screen I click or how often I close/force stop the Android app.

**Comment by dshokouhi** [comment]
entity IDs can only be lowercase, you are using an invalid format.

**Comment by dshokouhi** [comment]
the correct format for a script is `script.my_custom_name`

**Comment by dshokouhi** [comment]
can you show me the YAML and how the script entity ID looks in the states tab please?

**Comment by AleXSR700** [comment]
I am SOOOOOO sorry! I completely overlooked that in the app it does not show the friendly name/alias but the ID, which of course was not changed when I changed the alias.

So stupid of me!

Does the tile/app require a specific permission to be able to call the service? The "unable to send service call" when pressing the tile persists. Maybe I have some permission restrictions in place.

**Comment by dshokouhi** [comment]
No worries :) no special permission is needed, can you look at the log menu and get the actual error message for the failure? Is there an HA error log also at the same time?

**Comment by AleXSR700** [comment]
`05-21 21:47:33.665 25381 25381 I ViewRootImpl@7421ad3[SettingsActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
05-21 21:47:34.852 25381 25381 D TileService: onBind : mService = android.service.quicksettings.IQSService$Stub$Proxy@6259270, mTileToken = android.os.BinderProxy@b40c9d0
05-21 21:47:34.853 25381 25381 D TileService: onBind : mTile = android.service.quicksettings.Tile@33da9e9
05-21 21:47:36.039 25381 25381 D UrlRepository: localUrl is: false and usesInternalSsid is: false
05-21 21:47:36.096 25381 25381 E TileExtensions: Unable to call service
05-21 21:47:36.096 25381 25381 E TileExtensions: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request call_service
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.callService(IntegrationRepositoryImpl.kt:222)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$callService$1.invokeSuspend(Unknown Source:12)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at io.homeassistant.companion.android.qs.TileExtensions$Companion.tileClicked(TileExtensions.kt:96)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at io.homeassistant.companion.android.qs.TileExtensions.onClick(TileExtensions.kt:41)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:728)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at android.os.Looper.loop(Looper.java:246)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at java.lang.reflect.Method.invoke(Native Method)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
05-21 21:47:36.099 25381 25381 D Toast   : show: caller = io.homeassistant.companion.android.qs.TileExtensions$Companion$tileClicked$1.invokeSuspend:106 
05-21 21:47:36.099 25381 25381 I Toast   : show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1 isDexDualMode=false
05-21 21:47:36.099 25381 25381 I Toast   : show: isActivityContext = false
05-21 21:47:37.901 25381 25381 I SurfaceControl: release : mNativeObject = 518927850832 - Surface(name=Surface(name=4079c71 InputMethod)/@0xa75bfc4 - animation-leash)/@0x9ae9b7a / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154 
05-21 21:47:37.901 25381 25381 I SurfaceControl: nativeRelease nativeObject s[518927850832]
05-21 21:47:37.901 25381 25381 I SurfaceControl: nativeRelease nativeObject e[518927850832]
05-21 21:47:37.916 25381 25381 I ViewRootImpl@7421ad3[SettingsActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
05-21 21:47:37.916 25381 25381 D InputMethodManager: prepareNavigationBarInfo() DecorView@b2fcaac[SettingsActivity]
05-21 21:47:37.916 25381 25381 D InputMethodManager: getNavigationBarColor() -15658735
05-21 21:47:37.916 25381 25381 D InputMethodManager: prepareNavigationBarInfo() DecorView@b2fcaac[SettingsActivity]
05-21 21:47:37.916 25381 25381 D InputMethodManager: getNavigationBarColor() -15658735
05-21 21:47:37.916 25381 25381 V InputMethodManager: Starting input: tba=io.homeassistant.companion.android ic=null mNaviBarColor -15658735 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
05-21 21:47:37.917 25381 25381 D InputMethodManager: startInputInner - Id : 0
05-21 21:47:37.917 25381 25381 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
05-21 21:47:37.919 25381 25381 D InputTransport: Input channel constructed: 'ClientS', fd=186
05-21 21:47:37.919 25381 25381 D InputTransport: Input channel destroyed: 'ClientS', fd=185
05-21 21:47:40.214 25381 25381 I ViewRootImpl@7421ad3[SettingsActivity]: ViewPostIme pointer 0
05-21 21:47:40.272 25381 25381 I ViewRootImpl@7421ad3[SettingsActivity]: ViewPostIme pointer 1`

**Comment by AleXSR700** [comment]
`05-21 21:47:33.665 25381 25381 I ViewRootImpl@7421ad3[SettingsActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
05-21 21:47:34.852 25381 25381 D TileService: onBind : mService = android.service.quicksettings.IQSService$Stub$Proxy@6259270, mTileToken = android.os.BinderProxy@b40c9d0
05-21 21:47:34.853 25381 25381 D TileService: onBind : mTile = android.service.quicksettings.Tile@33da9e9
05-21 21:47:36.039 25381 25381 D UrlRepository: localUrl is: false and usesInternalSsid is: false
05-21 21:47:36.096 25381 25381 E TileExtensions: Unable to call service
05-21 21:47:36.096 25381 25381 E TileExtensions: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request call_service
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.callService(IntegrationRepositoryImpl.kt:222)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$callService$1.invokeSuspend(Unknown Source:12)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at io.homeassistant.companion.android.qs.TileExtensions$Companion.tileClicked(TileExtensions.kt:96)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at io.homeassistant.companion.android.qs.TileExtensions.onClick(TileExtensions.kt:41)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:728)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at android.os.Looper.loop(Looper.java:246)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at java.lang.reflect.Method.invoke(Native Method)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
05-21 21:47:36.096 25381 25381 E TileExtensions: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
05-21 21:47:36.099 25381 25381 D Toast   : show: caller = io.homeassistant.companion.android.qs.TileExtensions$Companion$tileClicked$1.invokeSuspend:106 
05-21 21:47:36.099 25381 25381 I Toast   : show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1 isDexDualMode=false
05-21 21:47:36.099 25381 25381 I Toast   : show: isActivityContext = false
05-21 21:47:37.901 25381 25381 I SurfaceControl: release : mNativeObject = 518927850832 - Surface(name=Surface(name=4079c71 InputMethod)/@0xa75bfc4 - animation-leash)/@0x9ae9b7a / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154 
05-21 21:47:37.901 25381 25381 I SurfaceControl: nativeRelease nativeObject s[518927850832]
05-21 21:47:37.901 25381 25381 I SurfaceControl: nativeRelease nativeObject e[518927850832]
05-21 21:47:37.916 25381 25381 I ViewRootImpl@7421ad3[SettingsActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
05-21 21:47:37.916 25381 25381 D InputMethodManager: prepareNavigationBarInfo() DecorView@b2fcaac[SettingsActivity]
05-21 21:47:37.916 25381 25381 D InputMethodManager: getNavigationBarColor() -15658735
05-21 21:47:37.916 25381 25381 D InputMethodManager: prepareNavigationBarInfo() DecorView@b2fcaac[SettingsActivity]
05-21 21:47:37.916 25381 25381 D InputMethodManager: getNavigationBarColor() -15658735
05-21 21:47:37.916 25381 25381 V InputMethodManager: Starting input: tba=io.homeassistant.companion.android ic=null mNaviBarColor -15658735 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
05-21 21:47:37.917 25381 25381 D InputMethodManager: startInputInner - Id : 0
05-21 21:47:37.917 25381 25381 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
05-21 21:47:37.919 25381 25381 D InputTransport: Input channel constructed: 'ClientS', fd=186
05-21 21:47:37.919 25381 25381 D InputTransport: Input channel destroyed: 'ClientS', fd=185
05-21 21:47:40.214 25381 25381 I ViewRootImpl@7421ad3[SettingsActivity]: ViewPostIme pointer 0
05-21 21:47:40.272 25381 25381 I ViewRootImpl@7421ad3[SettingsActivity]: ViewPostIme pointer 1`

**Comment by AleXSR700** [comment]
No error in HA log.

**Comment by dshokouhi** [comment]
is the script expecting a variable or something?  Can you test another app feature like the button widget and see if that is successful?

**Comment by AleXSR700** [comment]
It is a basic toggle script as it is only a light switch. 

`alias: LightSwitch_DR_Relay 0
sequence:
  - service: switch.toggle
    target:
      entity_id: switch.shelly_2_5_40f5443tfad_relay_0
mode: single
`

**Comment by dshokouhi** [comment]
What about a service call widget? Does that with?

**Comment by AleXSR700** [comment]
Same error message when I try to execute the script via widget.

**Comment by dshokouhi** [comment]
Anything special about your HA setup? It seems the app is having issues with the REST API.

**Comment by AleXSR700** [comment]
Not really. Normal, supervised setup.
Android app itself works without any issues.

**Comment by dshokouhi** [comment]
Can you call the HA REST API using the same url setup in the app?

**Comment by AleXSR700** [comment]
How do you mean? If I can reach HA using the same http://192......:8123? If so, yes, I can.

I just saw that the only issue I do have is that AppArmor is not running. This is simply because Raspberry OS does not support apparmor, so this would be the case for all RPi running Raspberry OS.

**Comment by dshokouhi** [comment]
No I mean the HA REST API https://developers.home-assistant.io/docs/api/rest/ I dont think app armor is the issue it most likely would be a network issue like maybe a proxy not configured properly?  I assume only the HA interface works, what about sensor updates, actionable notifications or power menu device control? Do those all work?

**Comment by AleXSR700** [comment]
How would I best go about testing the rest api?
