### ISSUE TITLE
supervisor panel is misaligned 

### ISSUE THREAD

**Issue by r3mcos3** [home-assistant/android#1559]
**Home Assistant Android version:**
2021.5.1-full
**Android version:**
11
**Phone model:**
Oneplus 8 Pro
**Home Assistant version:**
2021.6.0.dev0
**Last working Home Assistant release (if known):**
2021.6.0.dev20210519
**Description of problem:**

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
Can't access supervisor system panel because it's out off the screen i think 

```

**Screenshot of problem:**
![Screenshot_20210522-100559](https://user-images.githubusercontent.com/45529818/119220678-fc6cc600-baeb-11eb-8881-99d069d00256.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
How does it look in chrome for Android?

**Comment by r3mcos3** [comment]
Same problem see screenshot.

![Screenshot_20210522-112333.jpg](https://user-images.githubusercontent.com/45529818/119221553-3a6be900-baf0-11eb-9284-c7dfb530fd4a.jpg)

**Comment by dshokouhi** [comment]
This is not an Android bug please open one with HA frontend

**Comment by r3mcos3** [comment]
Issue is fixed already 
https://github.com/home-assistant/frontend/issues/9211#issue-896399616
