### ISSUE TITLE
Moving actions up and down inside of a repeat block doesn't work as intended 

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/android#1561]
**Home Assistant Android version:**
2021.5.1-full

**Android version:**
11

**Phone model:**
OnePlus 5T

**Home Assistant version:**
core-2021.5.5

**Last working Home Assistant release (if known):**

**Description of problem:**
When using the arrows next to an action which is inside of a repeat block not the action gets moved up and down, but the whole repeat block. 

Not sure if that's an android app issue or an home assistant issue. 

**Screenshot of problem:**

https://user-images.githubusercontent.com/614929/119274749-bc9ffe80-bc11-11eb-9aa4-51ccae4578fd.mp4

**Comment by dshokouhi** [comment]
This is a HA frontend issue, please check open issues first and if you don't see one create a new issue following their template
