### ISSUE TITLE
Switching tabs of dashboards is reordering them

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/android#1568]
**Home Assistant Android version:**

2021.5.1-full

**Android version:**

11

**Phone model:**

OnePlus 5T

**Home Assistant version:**

version: core-2021.5.5
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.9
os_name: Linux
os_version: 5.4.83-v8
arch: aarch64
timezone: Europe/Berlin

host_os: Home Assistant OS 5.13
update_channel: stable
supervisor_version: supervisor-2021.04.3
docker_version: 19.03.15
disk_total: 57.8 GB
disk_used: 14.9 GB
healthy: true
supported: true
board: rpi4-64
supervisor_api: ok
version_api: ok

**Last working Home Assistant release (if known):**

**Description of problem:**

Switching tabs while editing dashboards is unexpectedly switching their positions. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

https://user-images.githubusercontent.com/614929/119732794-f3c41900-be78-11eb-9cd0-58da20e503ef.mp4

**Additional information:**

**Comment by RubenKelevra** [comment]
You can also see, that I managed to switch to the other tab, but it was empty (which it isn't).

**Comment by dshokouhi** [comment]
do you see the same issue in chrome for android?

**Comment by RubenKelevra** [comment]
@dshokouhi yes

https://user-images.githubusercontent.com/614929/120919422-ccabe980-c6b9-11eb-8382-523e86149d79.mp4

https://user-images.githubusercontent.com/614929/120919436-de8d8c80-c6b9-11eb-9b9f-f27488a46df0.mp4

**Comment by dshokouhi** [comment]
Please open an issue with the HA frontend a this is blue an app issue.
