### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by rgzn-aiyun** [home-assistant/android#1570]
**Home Assistant Android version:beta-685-16f06a3

**Android version:9.0

**Phone model:**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem:**

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

When upgrading WebView to version 91.0.4472.77, opening the app crashes,

The WebView version is 90.0.4430.210 and the app can be opened normally.

**Comment by dshokouhi** [comment]
My webview hasnt updated yet so I can't check but if its crashing can you please grab the logs so we can see the error

**Comment by dshokouhi** [comment]
my device has updated to 91.0.4472.88 I suspect there was an issue with the version you listed....more than likely other webview based apps also had an issue....try to update only when google pushes an update to avoid getting a bad build.  Closing this now unless you can confirm the issue in the version I specified...then we will need a crash log to proceed.
