### ISSUE TITLE
[Request] Possible to remove/disable the "Updating Sensors" notification? Consistently causing false positives for notification monitor.

### ISSUE THREAD

**Issue by MostHated** [home-assistant/android#1572]
**Is your feature request related to a problem? Please describe.**

The Issue I am having is that the Android app randomly has a notification that shows up on the notification bar, assumingly on an interval, that says "Updating Sensors". I am using another app that monitors my notifications to allow me to have a custom color ring show up around the edge of my phones screen for various apps and notification types, but there is no way that I know of or can find to have it not pay attention to the "Updating Sensors" notification, so each time it shows up, even for the 1/8th of a second that it does, it triggers my phone screen to come on and do the notification color ring. The main issue is that it just happens relatively often and consistently, and gets extremely annoying when I am trying to rely on the notifications for other important things. 

**Describe the solution you'd like**
Allow disabling/removing of the "Updating Sensors" interval notification.

**Describe alternatives you've considered, if any**

Not sure?

**Additional context**

N/A

**Comment by dshokouhi** [comment]
Disable the sensor worker notification channel.

**Comment by MostHated** [comment]
You will have to forgive me, is that something that is to be done in the app, or is is that something I need to locate and disable in HomeAssistant?

Thanks,
-MH

**Comment by dshokouhi** [comment]
It's an Android feature go into device settings. Then access home assistant app info page then go to notifications and turn off sensor worker from there. Every device is different steps may not be the same.

**Comment by MostHated** [comment]
Ah, ok, I found it. Thanks for the quick resolution, I definitely appreciate it. :+1:
