### ISSUE TITLE
Tiles "Unable to send service call"

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/android#1573]
Home Assistant Android version:
2021.5.1
Android version:
11
Phone model:
Samsung S10plus
Home Assistant version:
Latest
Last working Home Assistant release (if known):

Description of problem:
Tile does not work properly.  When pressing a tile,  it only says "Unable to send service call".
This thread is a continuation of
https://github.com/home-assistant/android/issues/1556

The scripts are simple toggle a switch scripts and work from within the HA app. Just not via tiles.

> 05-21 21:47:33.665 25381 25381 I ViewRootImpl@7421ad3[SettingsActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
> 05-21 21:47:34.852 25381 25381 D TileService: onBind : mService = android.service.quicksettings.IQSService$Stub$Proxy@6259270, mTileToken = android.os.BinderProxy@b40c9d0
> 05-21 21:47:34.853 25381 25381 D TileService: onBind : mTile = android.service.quicksettings.Tile@33da9e9
> 05-21 21:47:36.039 25381 25381 D UrlRepository: localUrl is: false and usesInternalSsid is: false
> 05-21 21:47:36.096 25381 25381 E TileExtensions: Unable to call service
> 05-21 21:47:36.096 25381 25381 E TileExtensions: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request call_service
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.callService(IntegrationRepositoryImpl.kt:222)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$callService$1.invokeSuspend(Unknown Source:12)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at io.homeassistant.companion.android.qs.TileExtensions$Companion.tileClicked(TileExtensions.kt:96)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at io.homeassistant.companion.android.qs.TileExtensions.onClick(TileExtensions.kt:41)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:728)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at android.os.Looper.loop(Looper.java:246)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at java.lang.reflect.Method.invoke(Native Method)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
> 05-21 21:47:36.096 25381 25381 E TileExtensions: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
> 05-21 21:47:36.099 25381 25381 D Toast   : show: caller = io.homeassistant.companion.android.qs.TileExtensions$Companion$tileClicked$1.invokeSuspend:106 
> 05-21 21:47:36.099 25381 25381 I Toast   : show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1 isDexDualMode=false
> 05-21 21:47:36.099 25381 25381 I Toast   : show: isActivityContext = false
> 05-21 21:47:37.901 25381 25381 I SurfaceControl: release : mNativeObject = 518927850832 - Surface(name=Surface(name=4079c71 InputMethod)/@0xa75bfc4 - animation-leash)/@0x9ae9b7a / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154 
> 05-21 21:47:37.901 25381 25381 I SurfaceControl: nativeRelease nativeObject s[518927850832]
> 05-21 21:47:37.901 25381 25381 I SurfaceControl: nativeRelease nativeObject e[518927850832]
> 05-21 21:47:37.916 25381 25381 I ViewRootImpl@7421ad3[SettingsActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
> 05-21 21:47:37.916 25381 25381 D InputMethodManager: prepareNavigationBarInfo() DecorView@b2fcaac[SettingsActivity]
> 05-21 21:47:37.916 25381 25381 D InputMethodManager: getNavigationBarColor() -15658735
> 05-21 21:47:37.916 25381 25381 D InputMethodManager: prepareNavigationBarInfo() DecorView@b2fcaac[SettingsActivity]
> 05-21 21:47:37.916 25381 25381 D InputMethodManager: getNavigationBarColor() -15658735
> 05-21 21:47:37.916 25381 25381 V InputMethodManager: Starting input: tba=io.homeassistant.companion.android ic=null mNaviBarColor -15658735 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
> 05-21 21:47:37.917 25381 25381 D InputMethodManager: startInputInner - Id : 0
> 05-21 21:47:37.917 25381 25381 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
> 05-21 21:47:37.919 25381 25381 D InputTransport: Input channel constructed: 'ClientS', fd=186
> 05-21 21:47:37.919 25381 25381 D InputTransport: Input channel destroyed: 'ClientS', fd=185
> 05-21 21:47:40.214 25381 25381 I ViewRootImpl@7421ad3[SettingsActivity]: ViewPostIme pointer 0
> 05-21 21:47:40.272 25381 25381 I ViewRootImpl@7421ad3[SettingsActivity]: ViewPostIme pointer 1

**Comment by dshokouhi** [comment]
Please try the same script in a button widget so we can see what the issue. Using the HA frontend is not comparable here.

**Comment by AleXSR700** [comment]
A widget creates the same message. Unable to send service call

**Comment by dshokouhi** [comment]
Ok so this is not related to the tile directly but we're having issues with the REST API from home assistant. Are there any HA errors at the time you called the service? Anything special about your network setup like nginx proxy?

**Comment by AleXSR700** [comment]
The HA log does show anything.

I am not aware of anything special about my setup except it being a supervised install.
I am not using any proxies or similar.

**Comment by dshokouhi** [comment]
Can you try to call the service using the REST API directly?

https://developers.home-assistant.io/docs/api/rest/

I cant think of any reason as to why it's failing but I don't think this is an app issue.

**Comment by AleXSR700** [comment]
Seems to be working. I had to create a token, but it worked. I don't recall being asked to create a token in the app. I did not even have any long-lived tokens. Is this maybe the problem? Should the app ask for a token?

**Comment by AleXSR700** [comment]
I had to create a long-lived access token first as I did not have any, but then it worked.
Should the app maybe ask for such a token? Can I somehow check the REST Api from within the app rather than through widgets or tiles?

**Comment by dshokouhi** [comment]
The app gets one when you set it up. It's possible you may have accidentally removed it. Why don't you try clearing data and logging into the app to start fresh and see if that clears it up. If you haven't already. The service calls through widget and tiles both use the REST Api.

**Comment by AleXSR700** [comment]
That was it. Seemingly the app still had normal access via the IP but no longer to the REST API.
I uninstalled and re-installed.
Is it possible that the app keeps working if you change the password of a user but the token stops working? I may have change the password in between but don't recall whether I had to login again.

**Comment by dshokouhi** [comment]
I don't think those tokens expire when you change the password but they are easy to delete by accident under the user profile. The HA frontend and other features use a different method to communicate which is why those continued to work. In this case we just needed to follow basic troubleshooting to fix the issue.

**Comment by idealisms** [comment]
I ran into the same problem and was able to find this issue after using `adb logcat` to get the error message. Clearing app data and signing in again fixed the issue.

Would it be possible to add some sort of help message to the user to try clearing app data if they hit this error? It might be a bit of a stretch to ask everyone who encounters this to use `adb logcat` and find this issue. Should I file  a FR for this?

**Comment by dshokouhi** [comment]
@idealisms old and closed issues are not the place for this, the app should actually prompt the user when the token has expired and ask them to login again, when you open the app not when you click on a tile.  If you are not seeing that behavior then please file an issue for it, but make sure you are on the latest version with all the fixes before doing so. Clearing app data is a last resort or when data has become corrupted.

**Comment by idealisms** [comment]
I'm on the latest version of the app from the play store (2022.12.0-full), but I'm behind on Home Assistant itself. Does that mean I should file an issue for not being prompted when the token has expired?

**Comment by dshokouhi** [comment]
yes you can file an issue still, please make sure to list your HA core version and also the full error log, we do have logic already in place for revoking the token and requesting a new one but that only happens when we get an error from HA core letting us know the token expired.

https://github.com/home-assistant/android/blob/33fc6c3779f498379eb0b793fea317926481386a/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L1167
