### ISSUE TITLE
Notifications do not arrive until screen turns on

### ISSUE THREAD

**Issue by matejdro** [home-assistant/android#1574]
**Home Assistant Android version:** 2021.5.1-full

**Android version:** 11

**Phone model:** OnePlus 7 Pro (running LineageOS, so no bullshit OnePlus's battery limiters)

**Home Assistant version:** 2021.5.5

**Description of problem:**

For me, Home Assistant app has troubles delivering notifications when phone's screen is turned off. Notifications usually arrive considerably late. Turning the screen on, however, will immediately sync and deliver all pending notifications. I have some latency sensitive automatons (for example, upon pressing a physical button, HA will deliver notification to my phone, which in turn will display that text on my smartwatch) that get annoying even with couple of second delay.

Home Assistant app is added to battery exclusions. Telegram (which I used for these automatons up until now) does not have the same issues.

I can't find the source of the backend (is it open source?), but this smells to me like FCM notifications do not have high priority flag enabled: https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message . Without this flag, Android will often defer the delivery of notifications to conserve battery life.

**Comment by dshokouhi** [comment]
You need to set priority and ttl according to the docs

https://companion.home-assistant.io/docs/notifications/critical-notifications#android

**Comment by matejdro** [comment]
I see, thanks!

One note on the documentation: I've already read that page, but I've only read the text, not examples. The text does not mention priority in the Android section.

**Comment by dshokouhi** [comment]
The intention is for you to follow the example. Feel free to submit an update to make it more clear though.
