### ISSUE TITLE
Cannot connect to Home Assistant through reverse proxy

### ISSUE THREAD

**Issue by nvonbenken** [home-assistant/android#1580]
**Home Assistant Android version:** 2021.5.1

**Android version:** 11

**Phone model:** Pixel 5

**Home Assistant version:** core-2021.6.2

**Last working Home Assistant release (if known):** N/A

**Description of problem:** Cannot connect to reverse proxied HA. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:** 
![Screenshot_20210604-202815](https://user-images.githubusercontent.com/6497977/120874285-f6f38f00-c573-11eb-9b75-c89de3dd1828.png)

**Additional information:**
I can connect to my HA install while on my local network using my IP address just fine. I can also connect to my reverse proxied version (using nginx proxy manager and cloudflare) both on and off my network. The HA app will not connect to it however.

My reverse proxied URL looks like this: https://ha.server.xyz

**Comment by dshokouhi** [comment]
so if you take the proxy out of the loop its all working as expected?

**Comment by nvonbenken** [comment]
Right.

Works:
Connecting the app to my HA instance using IP and Port.
Directly accessing my HA instance from the browser using IP and Port.
Directly accessing my HA instance from the browser using the proxy.

Does not work:
Connecting the app to my HA instance using the proxy.

Is there some sort of regex URL validation going on that is having an issue with my URL being .xyz instead of .com or something? Not sure why else it would fail to parse the URL.

**Comment by dshokouhi** [comment]
So this is a proxy issue or networking issue and not an app issue, for reference my domain is .XYZ too but no proxy. Make sure you enter a properly formatted url including the https:// also you need to make sure you are forwarding everything correctly. If you need more help with setup you can look on the forums or in discord. There is also a small section in the companion docs to help out

https://companion.home-assistant.io/docs/troubleshooting/networking
