### ISSUE TITLE
Update sensors

### ISSUE THREAD

**Issue by uefik** [home-assistant/android#1581]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by uefik** [comment]
Add the ability to turn off sensor update notifications in the app?

**Comment by dshokouhi** [comment]
just turn off the sensor worker notification channel

**Comment by uefik** [comment]
Sensor update notification only, not all in-app notifications

**Comment by dshokouhi** [comment]
i already explained what you need to do, you may need to spend some time to understand what a notification channel is so you get what I am saying....every device is different.
