### ISSUE TITLE
Default value is spammed in field messing with the user input

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/android#1582]
**Home Assistant Android version:**

2021.5.1-full

**Android version:**

11

**Phone model:**

OnePlus 5t

**Home Assistant version:**

core-2021.6.2

**Last working Home Assistant release (if known):**

**Description of problem:**

Entering a value in the 'hours to show' field on the history graph is made extra hard by some weord automation. 

Additionally the field is marked as optional, but it's impossible to leave it blank. 

**Screenshot of problem:**

https://user-images.githubusercontent.com/614929/120919118-3e833380-c6b8-11eb-8bd5-a7529f06789f.mp4

**Additional information:**

**Comment by dshokouhi** [comment]
Can you reproduce in chrome?

**Comment by dshokouhi** [comment]
Actually this is a frontend issue, please open one there following their template.
