### ISSUE TITLE
Failure to load frontend 2021.0603.0 with "e.flat is not a function" line in logcat

### ISSUE THREAD

**Issue by gdt** [home-assistant/android#1587]
**Home Assistant Android version:**

2021.5.1-minimal (via F-droid)

**Android version:**

8.1 (lineage)

**Phone model:**

Pixel XL

**Home Assistant version:**

from pip freeze (running Core on NetBSD 9 amd64):
homeassistant==2021.6.3
home-assistant-frontend==20210603.0

**Last working Home Assistant release (if known):**

2021.5.something.  I did a update yesterday around 10 AM, and the app continued to work yesterday.   This morning I got the can't connect screen, and tried restarting almost everything (force-quite app, reboot phone, restart HA, checked HA's certs for validity).

**Description of problem:**

I get a "cannot connect" screen and offer to use external/refresh.   I see TCP traffic to my HA instance (I'm on the LAN), and firefox is fine.   The app still reports battery levels successfully, and was able to log in fresh after clearing data.   logcat indicates this is a crash when dealing with data, not a connectivity issue.

**Traceback **
Hostname redacted

```
2021-06-10 08:30:13.802 5740-5740/io.homeassistant.companion.android.minimal I/chromium: [INFO:CONSOLE(849)] "The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.", source: https://foo.example.com:8123/frontend_latest/app.bcb38ac1.js (849)
2021-06-10 08:30:13.824 5740-5740/io.homeassistant.companion.android.minimal I/chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) TypeError: e.flat is not a function", source: https://foo.example.com:8123/frontend_latest/app.bcb38ac1.js (2)
```

**Screenshot of problem:**

It's the "Unable to connect to Home Assistant" screen, with settigs/refresh-external/wait, just like one gets when it actually can't connect.

**Additional information:**

I realize this may be a frontend bug, but the frontend is working fine in firefox.

**Comment by gdt** [comment]
Just to be clear on sensor updates:  I had my HA open in firefox and when I pull the power cable on the phone the "is charging" sensor flips to false within about 2s, and back to true when I plug it in.  So the app is very clearly authenticated and connected (to the API, which I realize is different than frontend rendering).

**Comment by dshokouhi** [comment]
Make sure you are using the correct Android system WebView provided by google and not your custom ROM. Also Firefox is not the right test. You need to test on chrome for Android.

**Comment by gdt** [comment]
I'm just using lineage and not trying to do anything special about webview.  With "Browser" I get a blank screen.   I am guessing that this makes you think this is a frontend bug, and the only issue in the android app is that it's reporting a webview crash as "can't connect"?

**Comment by dshokouhi** [comment]
I don't think you get my point. Lineage does not ship with a properly supported webview. You need to use the proper one from Google

https://play.google.com/store/apps/details?id=com.google.android.webview

You also need to make sure it's the default one used, as a custom ROM user it's your responsibility to make sure you are using the proper apps that provide the proper API for Android webview.

If it doesn't connect in chrome on the device then the error might be different when going to the app. The cannot connect pop-up is due to the app not receiving the connected status from HA which means the frontend did not load and connect.

**Comment by gdt** [comment]
I was merely trying to suggest that differentiating two things would be useful to people
  - can't open TCP connection and negotiate SSL
  - after having something complicated run a pile of complicated javascript, it wasn't happy

It's now pretty clear to me that this issue isn't in the app.  Thanks for explaining.
