### ISSUE TITLE
Set notification timestamp from triggering notification event, not when it's received

### ISSUE THREAD

**Issue by charlesmunger** [home-assistant/android#1592]
**Is your feature request related to a problem? Please describe.**

When sending a notification, the time in the notification is always set to the time the notification was received, not the time the notification was sent by HomeAssistant. Due to network latency or other delays, the time between the actual detected event (say, a Frigate notification) and the time shown on the notification on device can be significant. 

**Describe the solution you'd like**

FCM includes an `event_time` parameter when making requests, and when the notification is received by the app it populates either the `RemoteMessage.Notification.getEventTime()` or `RemoteMessage.getSentTime()`. 

1. If event_time is not set when calling the service, populate with current time from homeassistant
2. Propagate the received timestamp to `NotificationCompat.Builder.setWhen()`

**Describe alternatives you've considered, if any**

Consider making an API to handle timestamps in the standard homeassistant format. I believe this template does that conversion:
`|timestamp_custom("%Y-%M-%dT%H:%M:%S.%fZ", False)` but it may be a sticking point for template authors.

**Additional context**

**Comment by dshokouhi** [comment]
The android app already makes use of the chronometer and `setWhen` feature via the chronometer notification option, you can set your template and options there

https://companion.home-assistant.io/docs/notifications/notifications-basic/#chronometer-notifications

also not sure if you are aware but you can speed up the delivery of the notification by following the critical notification example, given the nature of your request I assume this is what you are really after :) 

https://companion.home-assistant.io/docs/notifications/critical-notifications

**Comment by harmpter** [comment]
Stumbled across this while looking for another issue, but if you're still interested (4 years later lol) here's a way:
```
when: "{{ now().timestamp()|int + 60 }}"
when_relative: false
```
