### ISSUE TITLE
Caching / performance issue on loading dashboard

### ISSUE THREAD

**Issue by Alfiegerner** [home-assistant/android#1593]
**Home Assistant Android version:**
2021.6.3
**Android version:**
11
**Phone model:**
Samsung s21
**Home Assistant version:**
2021.6.3
**Last working Home Assistant release (if known):**
Not sure
**Description of problem:**

I am seeing very slow load time  for my main dashboard every time it is opened. Video below. 

The main dashboard has a large 6mb SVG file with many images for a floorplan. It may be that the chrome browser is caching this correctly but that the android app is not.

I think this may have been working correctly / better in past versions but not 100 on that.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

Video here: 

https://photos.app.goo.gl/QSWbVb3wio57Q1uQA

This shows:

  - HomeAssistant web page in Chrome switching fluently between main dashboard and a second one. The main SVG image heavy page loads quickly in the browser once it has been cached.
  - the android app taking a while to load main dashboard when flicking between the two.

**Additional information:**

**Comment by dshokouhi** [comment]
If you disable all custom cards does it load properly? Is Android system WebView up to date? The Android app respects the cache age that the HA frontend sets for all items. Caching is set to the webview default.

**Comment by Alfiegerner** [comment]
Thanks @dshokouhi  - I ran through it in debug and it worked fine, so re-installed main version and that worked fine too.  Some app caching issue or limit possibly?  Anyway, all working now, thanks for looking.

**Comment by Alfiegerner** [comment]
Hi @dshokouhi , this has resurfaced but I've found that forcing stop on the app and restarting resets the problem and performance becomes fine again. 

I think my installation is probably quite large relatively speaking, but performance is fine until app is open for some time.

**Comment by Alfiegerner** [comment]
My wife started reporting the same problems so I've switched her over to using a chrome page 'saved to home screen's, will see if we see same symptoms.

**Comment by dshokouhi** [comment]
make sure to check how it behaves with all custom cards disabled too

**Comment by Alfiegerner** [comment]
Hi @dshokouhi - my main dashboard is one big custom card so have left that for now. 

I downgraded my Android System Webkit to whatever was shipped with my phone and it's working fine again now.

**Comment by bmesuere** [comment]
I'm seeing the same problem on my pixel 3A. When starting the app, it takes a long time before the main view is loaded. Once it's loaded, switching between views is almost instant. It is as if the entire view needs to be downloaded again when starting the app and nothing is cached.

I checked the logs, and there's often a gap of 5 seconds in the timestamps. The first line after the gap is always `WebviewActivity: External bus {"type": "config_screen/show", "id": 3}`, the line before often is `WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for xx.xxxms`.

**Comment by dshokouhi** [comment]
Closing as the original issue was resolved and we do not have control over android system webview updates
