### ISSUE TITLE
Gesture for "back" and others very difficult to perform

### ISSUE THREAD

**Issue by Taomyn** [home-assistant/android#1594]
**Home Assistant Android version:**
2021.6.2-full

**Android version:**
11

**Phone model:**
Pixel 5

**Home Assistant version:**
core-2021.6.5
supervisor-2021.06.0
HA OS 6.0

**Last working Home Assistant release (if known):**
n/a

**Description of problem:**
With full gesture navigation enabled on the phone it's almost impossible to use the general "back" gesture on the right-side of the phone - the left-side is only slightly better. Compared to all other apps on my phone where I can pretty much navigate with one hand, I am always forced to hold the phone in one hand then use the other to carefully try to get "back" to work. Even the up-swipe to just dismiss the app gets "stuck".

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
n/a

**Additional information:**
I had to reset my phone last weekend so I have potentially eliminated any lingering issues, but the app has always behaved this way since I started using it, even on my old Pixel 3 that I replaced last year.

**Comment by dshokouhi** [comment]
I do not have this issue on my pixel 4. Do you see the same issue in chrome for Android?

**Comment by Taomyn** [comment]
> I do not have this issue on my pixel 4. Do you see the same issue in chrome for Android?

No, and only because Chrome is disabled as I use Brave and it does not have the issue - the browser behaves normally. Webview is still available though and up-to-date, though I wish I could disable that too.

**Comment by dshokouhi** [comment]
Can you please try chrome to see if it exists. Chrome and webview are very similar here and we are trying to determine if this is an app issue or frontend. Also are you on a custom ROM?

**Comment by Taomyn** [comment]
> Can you please try chrome to see if it exists. 

Unfortunately I can't because the last time Google asked me to do this when I reported another issue to them, I spent weeks trying to get rid of it as it kept re-installing itself and making itself default for dozens of apps/links.

And no, this is stock for the Pixel 5 and fully updated Android 11 - my days of custom ROMs and rooting are far behind me.

**Comment by dshokouhi** [comment]
Have you tried disabling all custom cards? You will need to try chrome to continue troubleshooting. We don't do comparisons to brave browser.

**Comment by dshokouhi** [comment]
Closing due to lack of response

**Comment by patriiiiiiiiiick** [comment]
I have the same issue in the companion app and using home assistant in Chrome and Brave as well.
