### ISSUE TITLE
App configuration view ignores language setting

### ISSUE THREAD

**Issue by derSeddy** [home-assistant/android#1595]
**Home Assistant Android version:**
2021.6.2-full

**Android version:**
7.1.2

**Phone model:**
OnePlus two

**Home Assistant version:**
core-2021.5.4

**Description of problem:**
The "App Configuration" view is presented in the devices language (german) instead of the one selected in that menu (english). The rest of the app seems to be in english as expected.

**Screenshot of problem:**
[Screenshot of the view](https://seddy.spdns.de/Screenshot_20210618-132539.png)

**Comment by dshokouhi** [comment]
That's really strange, have you tried restarting the device? Is this a custom ROM?

**Comment by derSeddy** [comment]
Restarting doesn't help. The rom is not stock, it's LineageOs 14.2 (which is quite old from 2018). It might actually be related to that, because I tried to reproduce the bug using my old Nexus 5, stock Android 6.0, where changing the language worked fine.

**Comment by derSeddy** [comment]
I checked the android log and I do get an exception when I change the language, but it sound unrelated and I get it independent of the language I select. But here it is anyway in case it helps:
```
06-18 19:38:38.930 D/SettingsFragment(15747): Unable to set the icon tint
06-18 19:38:38.930 D/SettingsFragment(15747): java.lang.IllegalStateException: Fragment SettingsFragment{68637e6} (01e3a152-8749-4409-bba0-f9fdd34e91ae)} not attached to a context.
06-18 19:38:38.930 D/SettingsFragment(15747): 	at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
06-18 19:38:38.930 D/SettingsFragment(15747): 	at io.homeassistant.companion.android.settings.SettingsPresenterImpl.handleInternalUrlStatus(SettingsPresenterImpl.kt:158)
06-18 19:38:38.930 D/SettingsFragment(15747): 	at io.homeassistant.companion.android.settings.SettingsPresenterImpl.access$handleInternalUrlStatus(SettingsPresenterImpl.kt:22)
06-18 19:38:38.930 D/SettingsFragment(15747): 	at io.homeassistant.companion.android.settings.SettingsPresenterImpl$onCreate$1.invokeSuspend(SettingsPresenterImpl.kt:148)
06-18 19:38:38.930 D/SettingsFragment(15747): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[...]
```

**Comment by dshokouhi** [comment]
Those are actually debug log statements. I think this is a custom ROM bug.

**Comment by derSeddy** [comment]
Probably. As I might be the only one affected and it doesn't bother me much, feel free to close the issue.
