### ISSUE TITLE
TTS voice and notification sound overlap, voice hard to understand

### ISSUE THREAD

**Issue by progman32** [home-assistant/android#1599]
**Home Assistant Android version:** 2021.6.2-full

**Android version:** 10

**Phone model:** ZenFone 6

**Home Assistant version:** core-2021.6.5

**Last working Home Assistant release (if known):**

**Description of problem:**

The TTS notification voice and notification tone overlap, making the voice hard to understand. I know I could turn the notification tone off, but I don't have the best hearing so keeping the notification tone is useful to get my attention. I'll often miss the voice unless I'm specifically listening for it.

Expected behavior: When I get a TTS notification, the phone's configured notification ringtone plays fully, then the TTS voice reads the notification title.
Actual behavior: The TTS voice and the phone's configured notification ringtone play at the same time.

I have no idea if Android gives feedback to the app when the ringtone stops playing, so maybe a configurable "TTS notification delay" menu option allowing the user to arbitrarily delay the onset of the TTS voice would bridge the gap and make the feature usable.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Are you receiving 2 notifications at the same time? TTS is only TTS and the nature of TTS is to use the music stream while notifications use the notification stream. Thats unfortunately out of our control there as we do not get notified when a notification ring has finished.  If you are intending to receive 2 notifications (TTS and normal)  you can probably just add an appropriate delay in your automation in between the 2 service calls.

**Comment by dshokouhi** [comment]
Closing due to lack of response
