### ISSUE TITLE
Calyx OS location services support

### ISSUE THREAD

**Issue by travisghansen** [home-assistant/android#1601]
**Is your feature request related to a problem? Please describe.**

I’d like to use the companion app with location services but not using google play. Calyx OS has privacy respecting options.

**Describe the solution you'd like**

- https://calyxos.org/about/faq/#how-do-you-handle-location-services-in-a-more-private-way

**Describe alternatives you've considered, if any**

Running alternative location provider apps such as owntracks etc
**Additional context**

- https://calyxos.org/news/2021/05/27/emulator-images/

Thanks for the consideration and great companion app!

**Comment by dshokouhi** [comment]
duplicate of #1511
