### ISSUE TITLE
Action Button on Android not working as expected

### ISSUE THREAD

**Issue by homeoneautomacao** [home-assistant/android#1602]
Hi, the code below should send a notification on the android phone and when the user clicks the "OPEN CAMERA" button the home assistant app should open and then the chosen entity "camera.garage" should open. This code works however when the user changes the "default" dashboard in user settings to another one, instead of opening the entity, it opens the dashboard.
I believe that if this is really an improvement, it should respect the notification link and not the default dashboard. The default dashboard should be the default that one specific user wants to use. But when one important notification is created to send to another way, i think this should be done.

service: notify.mobile_app_mi_9t
data:
__message: The garage door has been open for 10 minutes.
__title: Your Garage Door Friend
__data:
____actions:
______- action: URI
______title: OPEN CAMERA
______uri: entityId:camera.garage

**Comment by dshokouhi** [comment]
Can you show us the logs for when you click on the notification? You'll want to reproduce the issue then go to app configuration to get the logs. Just want to check and see what it is doing.  Also have you tried with disabling custom cards to ensure they are not causing an issue?

**Comment by dshokouhi** [comment]
Closing due to lack of response
