### ISSUE TITLE
[FR] Limit (history) data usage on metered connections

### ISSUE THREAD

**Issue by RoboMagus** [home-assistant/android#1605]
**Is your feature request related to a problem? Please describe.**
Last month I noticed a lot of data being used by the Home Assistant app, and though I cannot be sure of the culprit I'm guessing it has to do with the history page. By default it loads data from all available entities for the past 2 hours or so, which in my case is a LOT of junk I do not need to see most of the times when I'm opening the history page.
Even though the history page is not necesarilly the culprit of me blowing through my mobile data bundle, I did run into the bandwidth cap of my provider. This is the main reason for this FR: on terribly slow (metered) connections I would have to wait for the history page to load fully before I can enter the query of the entity and time range I'm actually interested in. This wastes a lot of time and data and I would prefer having no data loaded at all when initially opening that page, at least for when I'm using mobile data.

**Describe the solution you'd like**
It'd be a nice addition to block loading of (unnecessary) data, such as the inital loading of the history page, when the Home Assistant app detects that it's using a metered connection (mobile).

**Describe alternatives you've considered, if any**
It might be applicable to implement such a feature in the home assistant frontend instead, but knowledge about the connection type may not be available there.

**Comment by dshokouhi** [comment]
How many camera entities do you have?

**Comment by RoboMagus** [comment]
@dshokouhi None.
I specifically mentioned history here cause that's the thing that's terribly slow when on a limited bandwidth connection.

**Comment by hmmbob** [comment]
I can across this issue because I also noticed 800+ mb data use if HA app in the last month, and in the first 7 days of July I'm at 128Mb already. I do _not_ have any cameras setup (besides a more or less static Google Maps picture).

**Comment by dshokouhi** [comment]
> @dshokouhi None.
> I specifically mentioned history here cause that's the thing that's terribly slow when on a limited bandwidth connection.


Interesting, ok then this is not something that will be fixed by the android app but for the most part you can configure things to be more lightweight

> By default it loads data from all available entities for the past 2 hours or so, which in my case is a LOT of junk I do not need to see most of the times when I'm opening the history page.

https://www.home-assistant.io/integrations/history/

Time to trim down the stuff you dont care for



> I do _not_ have any cameras setup (besides a more or less static Google Maps picture).

This still counts as a downloadable image that will be grabbed when you open the app and susceptible to the same issue you mentioned.

Given that this request is about the history page specifically we cannot provide a fix here for that, your option is to trim down the amount of data stored or request it to the frontend.

**Comment by RoboMagus** [comment]
> https://www.home-assistant.io/integrations/history/
> 
> Time to trim down the stuff you dont care for

Most of these I actually do want as history though. Just not have it load up as soon as I open the history page on a slow connection. Hence the thought of limiting loading of this page when not on WiFi, such that a user is free to enter the query they are looking for without having to wait and waste data.

**Comment by dshokouhi** [comment]
> Most of these I actually do want as history though. Just not have it load up as soon as I open the history page on a slow connection. Hence the thought of limiting loading of this page when not on WiFi, such that a user is free to enter the query they are looking for without having to wait and waste data.

Its not a bad thought but because this issue will also exist in chrome for android, the issue needs to be handled by the frontend team.
