### ISSUE TITLE
Bluetooth device battery level as sensor

### ISSUE THREAD

**Issue by nevalain** [home-assistant/android#1607]
**Is your feature request related to a problem? Please describe.**
Just a wish. 

**Describe the solution you'd like**

Please add bluetooth device battery level as a sensor. I would love to have my headphones' battery level as a sensor. 

**Describe alternatives you've considered, if any**

-

**Additional context**

-

**Comment by dshokouhi** [comment]
duplicate of https://github.com/home-assistant/android/issues/916 check that thread for how to get your battery level from bluetooth devices
