### ISSUE TITLE
Widgets on android not working 

### ISSUE THREAD

**Issue by cylonr** [home-assistant/android#1614]
The widgets don't send the command to my HA server. Everything works OK, but the widgets don't. 
![Screenshot_20210719-101424_Nova_Launcher](https://user-images.githubusercontent.com/34467765/126135862-2148202e-11ad-4e8a-9a66-21addcdc62f6.png)
![Screenshot_20210719-101645_Home_Assistant](https://user-images.githubusercontent.com/34467765/126135927-13e34749-5cb3-470b-aba4-559977481e09.png)

App version : 2021.6.2-full

**Comment by dshokouhi** [comment]
Why did you remove the issue template and not provide all requested information? Please add it back so we can look into this.

**Comment by dshokouhi** [comment]
Still waiting on relevant data

**Comment by dshokouhi** [comment]
Closing due to lack of response
