### ISSUE TITLE
Add area dropdown to overview

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/android#1615]
**Is your feature request related to a problem? Please describe.**

Not a problem as much as a user experience improvement.

**Describe the solution you'd like**

In the Overview, make areas expandable/collapsable/dropdown.
Meaning, when you see the different areas, you have to scroll through an entire area to reach the next one. On a mobile device this is a bit tidious. 

How about making areas expandable/collapsable, so you can select which area to expand and see.

Grafana e.g. offers this very pleasant improvement.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
is this request meant for the HA frontend?

**Comment by AleXSR700** [comment]
Hello,
that would also be cool but I was thinking of the Android App.

If this is easier to implement in the frontend and then just use in the App, that would be cool also.

On a PC you see multiple columns, so scrolling is easy. On a mobile device (Android App) it is just one column and therefor collapsable areas would be great.

**Comment by dshokouhi** [comment]
the android app in terms of the HA frontend is just a webview, if you use chrome for android you will see its identical.  The app offers sensors, notifications and other android integrations.  You will want to take your request to the HA frontend repo.
