### ISSUE TITLE
Icon theming on Android 12

### ISSUE THREAD

**Issue by TheWhiteGandalf** [home-assistant/android#1618]
**Is your feature request related to a problem? Please describe.**
 on Android 12 Beta 3 the icon doesn't get themed and doesn't use system colors. 

**Describe the solution you'd like**

Adding the new material you theming to the icon. 
**Describe alternatives you've considered, if any**

**Additional context**

I know Android 12 is still Beta and only some Google apps get themed for now. I just want to make sure this app won't miss this.

**Comment by dshokouhi** [comment]
what specifically was done with icons in material you that we need in the app? The current app icon reflects that of the HA logo so not sure I am following the request here. The google app icons all look the same to me in the launcher.

**Comment by jpelgrom** [comment]
This will be possible in Android 13! https://developer.android.com/about/versions/13/features#themed-app-icons

**Comment by psbankar** [comment]
It is available in Android 12 as well and many third party apps already have implemented this change. For instance I tried apps like Authy, Sync for Reddit, Spotify, etc. and all of these have themed icons working on Android 12

**Comment by TheWhiteGandalf** [comment]
Any news on this?
