### ISSUE TITLE
Controlling Android via Home Assistant

### ISSUE THREAD

**Issue by bilogic** [home-assistant/android#1619]
**Is your feature request related to a problem? Please describe.**

Yes, I would like to be able to modify/mute the ringtone volume and vibration.
I'm able to get battery/temperature updates from Android today, but can't seem to do anything else.
For example, if I'm on a PC conference call, e.g. zoom etc and the phone starts getting a bunch of messages, I could open up a browser and mute them all. Setting/enabling/disabling the alarms will also be helpful.

**Describe the solution you'd like**

Exposed a volume/vibration control switch + sensor just like battery and temperature, with alarms as a bonus.

**Describe alternatives you've considered, if any**

Excusing myself from zoom, walking over to the offending device and going thru the authentication sequence etc and muting it.

**Additional context**

N/A

**Comment by dshokouhi** [comment]
You should probably get familiar with the docs: 

https://companion.home-assistant.io/docs/notifications/notification-commands
