### ISSUE TITLE
Qubino Smart Meter watt use widget on Android

### ISSUE THREAD

**Issue by klumpo** [home-assistant/android#1657]
**Is your feature request related to a problem? Please describe.**

I only get Ampere/current widget on my Android phone. I'd love to have Watt use instead so it is easier to get the info (no need to multiply the value with 230 in my head). I can see the Watt in Fibaro Home Center 2, but not in Home Assistant.

**Describe the solution you'd like**

I'd love an option to see the current Watt use by my Qubino Smart Meter in my widgets for Android Home Assistant Companion App.

**Describe alternatives you've considered, if any**

I couldn't find any alternatives.

**Additional context**

Following are some screenshots and links

https://qubino.com/products/smart-meter/
https://qubino.com/products/smart-meter/smart-meter-techold/

![Home Assistant Qubino smart meter mains ampere only](https://user-images.githubusercontent.com/88207948/127695704-b45213dd-1711-4509-b821-29a8e53e4859.png)

![Fibaro Home Center Qubino smart meter mains watt use](https://user-images.githubusercontent.com/88207948/127695714-55654344-3ca1-434a-9fff-9fbe0c00f39e.png)

![Home Assistant Qubino smart meter mains watt](https://user-images.githubusercontent.com/88207948/127695724-883b5eb0-f200-4f2b-8a14-a37010cbad89.png)

**Comment by dshokouhi** [comment]
Are you seeing this issue in Home Assistant web interface or just the widget? All the widget does is show state and attribute data based on how you set it up. If the data is missing in home assistant than you have placed this request in the wrong place.

**Comment by dshokouhi** [comment]
Closing due to lack of response
