### ISSUE TITLE
Custom icons not loading in view tab

### ISSUE THREAD

**Issue by ipetrovits** [home-assistant/android#1661]
**Home Assistant Android version:**
2021.6.2-full

**Android version:**
11

**Phone model:**
Samsung SM-G973F

**Home Assistant version:**
2021.7.4

**Last working Home Assistant release (if known):**
n/a

**Description of problem:**
Using some custom icons which are working well generally.
If I set a custom icon for a view, it is shown correctly on web frontend, however in Android there is only a blank space shown.

The icon can be loaded if I go to edit view and close editing, then the icon will show up in the tabs as it should - until the app is restarted, then he icon will be blank again.

In Android app, every other place the custom icons are shown correctly without any problems.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/50260134/127830035-4debc284-c2ae-45d7-8268-3adc07fcb2d7.png)
![image](https://user-images.githubusercontent.com/50260134/127830116-985648b1-e4cd-4d71-a68b-44509bf36471.png)

**Additional information:**

**Comment by dshokouhi** [comment]
Does the issue show up in chrome for Android?

**Comment by ipetrovits** [comment]
> Does the issue show up in chrome for Android?
> 
> Edit: Also is chrome for android and android system webview up to date?

Hi @dshokouhi,

Yes, exactly the same with chrome on both inside and outside urls.
Android System WEBview and Crome versions are the same: 92.0.4515.115

Thanks!

**Comment by dshokouhi** [comment]
As this issue occurs in chrome as well you will need to first take this up with the icon developer and then you can try with the HA frontend.

**Comment by ipetrovits** [comment]
> As this issue occurs in chrome as well you will need to first take this up with the icon developer and then you can try with the HA frontend.

Hi @dshokouhi,
This issue occurs with any custom icon and with downloades original MDI icons as well.
If you could give me a sample icon which is proven working, I'll be more than happy to contact the icon developer and any other icon developers as well.
Thanks,
Istvan
