### ISSUE TITLE
Dark theme not working in android app

### ISSUE THREAD

**Issue by meldarionqeusse** [home-assistant/android#1667]
Untill yesterday homeassitant had dark theme today when I opened the app it was white but when I went into the app configuration setting the setting menu was dark and theme settings was still set to dark. The only thing that I changed from yesterday on my phone is that I uninstalled Chrome. 

i have tried uninstalling reinstalling home assistant and clearing cache.

**Comment by dshokouhi** [comment]
We need more data to go by on this.  The issue tempalte normally gets presented when you create an issue, not sure why it is not here.

if you reinstall chrome does it come back? A lot of hte app is based on standard android webview APIs so you need chrome and/or android system webview fully updated.  If you are on a custom ROM you need to make sure you are on the correct versions as they often ship with incorrect ones.

**Comment by meldarionqeusse** [comment]
Ok i re-installed and updated chrome and now it works. Thanks for explaining I was not seeig any logical explanation why chrome should affect another app. I do not have custom ROM I uninstalled chrome cause I have been trying to move to vivaldi but somehow there's always something 'forcing' me to stick with chrome.

Regarding the issue template I am not sure why it did not come up I was surprised aswell but I thiugh this was a minor issue and someone would have an easy fix.
