### ISSUE TITLE
Remove number of tiles limitation

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/android#1668]
**Is your feature request related to a problem? Please describe.**

The maximum number of tiles is currently limited to maximum 5. More would be excellent.

**Describe the solution you'd like**

Let user enter a number for how many tiles he wants and create new tiles accordingly.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
Unfortunately we have to define the exact amount of tiles to use in our manifest so it cannot be user controllable.  How many more do you think we should add? We can pick a number now and if we feel we need more we can always add more :)

**Comment by AleXSR700** [comment]
Hello Daniel @dshokouhi ,
thank you for the offer :-)

I personally use it for my most used lights plus one or two sockets.
Not sure if this is Android wide or just on my phone, but I can habe 12 tiles per register.
So how about 12? That way you could have one register/screen for Home Assistant tiles :-)

**Comment by AleXSR700** [comment]
![Screenshot_20210807-063447_Firefox](https://user-images.githubusercontent.com/57034871/128588003-dbfcaece-5788-4fc6-8689-08246fca0f63.jpg)

**Comment by dshokouhi** [comment]
12 sounds reasonable I think, lets see if others have an opinion on more than that.

**Comment by AleXSR700** [comment]
After the addition of automations I have found that I could use more tiles :)

Is there any chance of simply letting the user enter the number of tiles he/she needs? That way they can be increased (or decreased) as needed.

**Comment by dshokouhi** [comment]
@AleXSR700 we have to define the amount of tiles see: https://github.com/home-assistant/android/issues/1668#issuecomment-894600299

Please open a new request with the amount you would like to have as this issue was closed sometime ago
