### ISSUE TITLE
Power saving white list on Samsung

### ISSUE THREAD

**Issue by Capsyatina** [home-assistant/android#1669]
Hi, I am using the latest Home Assistant app on my Samsung SM-A705FN phone.  When I turn on power saving mode, the phone starts limiting background apps.  and as a result, the geolocation data does not go from the phone to my server.  Samsung has a whitelist of "non-sleeping apps".  but I cannot add a home assistant there, because  it is not in the general list from where you can get any application. 
Perhaps the application is based on some kind of browser?  Maybe I can add it to the white list ..

**Comment by dshokouhi** [comment]
You need to check that the app has rights to run in the background and in addition to that you need to remove battery optimizations for the app.

You may need to try https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app and ensure you grant proper permissions to run in the background.

As samsung changes things from standard android you may need to play around with the settings to get it right, this site may be of help

https://dontkillmyapp.com/samsung
