### ISSUE TITLE
Combine options with High Accuracy Mode

### ISSUE THREAD

**Issue by Drealine** [home-assistant/android#1673]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add the possibility of combining the 2 options available for Bluetooth and zones.
For example, activate the Bluetooth option and choose the zone so that High Accuracy Mode is activated only when I am connected to the bluetooth of my car.

**Describe alternatives you've considered, if any**
No.
**Additional context**
No.

**Comment by Drealine** [comment]
> Should be an option to have both conditions (zone & ble) OR'ed or AND'ed.

YES! @dshokouhi , anothers news about this feature ?

**Comment by ThoSig** [comment]
Since i actually faced the same "issue" i decided to provide a PR for this. 
https://github.com/home-assistant/android/pull/2491

I hope this is helpful and can get approved.
