### ISSUE TITLE
Reconnecting on network change

### ISSUE THREAD

**Issue by lucidnx** [home-assistant/android#1675]
Hello! I'v noticed that after switching Home Assistant from Nabu Casa Cloud to my own public IP with SSL, App started having issues on network change from local wifi to mobile/other network.
I have set my domain to point A record on my public IP, and on local DNS I have same record pointing directly to local IP of HA server. 
This way, app keep connection over public IP when I connect to my WiFi, but that does not work because my ISP have set DST-NAT to my router instead giving my IP on router directly - this cause no connection to server (usual scenario for most people).
I have other apps like plex or deluge client and they have something implemented to always get new IP from DNS on network change. This also apply when I diaconnect from wifi (when IP change and past one is unreachable)
overriding this behavior with setting my wifi name and local IP in app did not work too, because SSL certificate is issued to my hostname and not IP.

edit: I have issues with reconnection even if I disabled SSL and tried local IP. app show reconnecting message or goes black.

**Comment by dshokouhi** [comment]
did you make sure to update your external URL in HA configuration? What other troubleshooting steps did you take?

**Comment by lucidnx** [comment]
I'v tried multiple combinations of HA's internal/external URL, in app URL's, combinations of nginx proxy/SSL without nginx and SSL... I'v already spent multiple hours on it.. 
It is pretty much new installation (2 weeks old, hyper-v appliance of HA) with some lights, esphome switches and integrations, so I guess there is no problem.
How it should be configured on my setup? Just in case if I missed something..

**Comment by dshokouhi** [comment]
In HA Configuration > General you should have external and internal URL filed in. In App Configuration in the android app itself you want make sure the URL is correct. Anything else outside of that (i.e. slow connection) is probably some networking issue on your end. Maybe try restarting a few things like router and host device and such?  If it connects then it connects.  If there are any delays you see you can try checking the logs under App Configuration to see if there is a failure.

**Comment by lucidnx** [comment]
I don't have slow connection, everything works well (I have multiple servers, VM's, firewalls, appliances, etc..), multiple plex streams simultaneously without dropping connection, site-to-site tunnels uptime in months....
What I am trying to say is that app does have some issue, because it did not get new IP from DNS on network change or keep connection even when IP has changed maybe until it finish some background tasks.. I see that it's some kind of HTTP wrapper, but why is this happening does not make any sense to me. when I open home assistant in chrome, it's connected almost immedialy (show reconnecting message at bottom for just 1 second and immedialy works). only app does have this issue...

**Comment by dshokouhi** [comment]
You said this happened after you switched URLs? Have you tried starting fresh?

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

Ensure that chrome and android system webview are fully up to date, also there is alot of data missing from this bug report such as the type of device and the HA version etc... We have an issue template that gets presented when a new issue is created but it seems to be missing here. It would be great to get all that data including the logs which I mentioned earlier.

**Comment by lucidnx** [comment]
Ah, sorry, I'v got direct link somewhere on pages..



**Home Assistant Android version: 2021.6.2-full

**Android version: 11 (OneUI 3.1)

**Phone model: Samsung Note 20 Ultra (Exynos, 5G)

**Home Assistant version: Hyper-V Appliance (HA OS6.2), core-2021.8.6

**Last working Home Assistant release (if known):**

**Description of problem: Reconnecting on network change for long time

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs): I am not able to use ADB now, if it would be really needed, I can do it later.

```

```

**Screenshot of problem: [Issue](https://streamable.com/aa0378) [Expected](https://streamable.com/u2w7up)

**Additional information: I think that everything was explained

**Comment by lucidnx** [comment]
ah, it's late here.. ;) it's attached to template

**Comment by dshokouhi** [comment]
It looks like there is an error regarding the phone SIM sensors, looks like your device reports it has them but it doesnt which is odd.

```
08-12 00:38:31.777 12511 12625 E SensorReceiver: Issue requesting updates for Phone Sensors
08-12 00:38:31.777 12511 12625 E SensorReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
08-12 00:38:31.777 12511 12625 E SensorReceiver: 	at io.homeassistant.companion.android.sensors.PhoneStateSensorManager.updateSimSensor(PhoneStateSensorManager.kt:116)
08-12 00:38:31.777 12511 12625 E SensorReceiver: 	at io.homeassistant.companion.android.sensors.PhoneStateSensorManager.requestSensorUpdate(PhoneStateSensorManager.kt:61)
08-12 00:38:31.777 12511 12625 E SensorReceiver: 	at io.homeassistant.companion.android.sensors.SensorReceiver.updateSensors(SensorReceiver.kt:156)
08-12 00:38:31.777 12511 12625 E SensorReceiver: 	at io.homeassistant.companion.android.sensors.SensorWorker$doWork$2.invokeSuspend(SensorWorker.kt:80)
08-12 00:38:31.777 12511 12625 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-12 00:38:31.777 12511 12625 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-12 00:38:31.777 12511 12625 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
08-12 00:38:31.777 12511 12625 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
08-12 00:38:31.777 12511 12625 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
08-12 00:38:31.777 12511 12625 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

Seeing other errors and oddities as well that shouldnt be there, have you tried the start fresh steps yet? Might just need to clear something out.

**Comment by lucidnx** [comment]
I'v did it twice. before and now again according to guide without luck. I don't see how does SIM issue affect app inability to connect to server.. there is just issue in app itself, not in my configuration. my wife's phone is doing this too. I'v found that when app is closed some time before switching network, it just connect immedialy. when I close it, wait for while, change network and open app, it does work. but not when it's open, or if it was open right before switching to wifi/5g.

**Comment by dshokouhi** [comment]
Repeated errors that show up multiple times can indeed cause delays in the app doing other things, I think you may have glossed over how many of these errors there are and how frequent they are. The app might be busy trying to get a response preventing it from continuing.

**Comment by lucidnx** [comment]
okay, then fix those errors... I can paste log again after fresh reset app according to guide. my phone is note 20 ultra (exynos 256GB variant) 
[homeassistant_companion_log_7-17-2021_20-22-57.txt](https://github.com/home-assistant/android/files/7002206/homeassistant_companion_log_7-17-2021_20-22-57.txt)

**Comment by dshokouhi** [comment]
Looks like the issue may be a connection issue 

```
08-17 20:10:03.733 18565 15197 E LocBroadcastReceiver: Could not update location.
08-17 20:10:03.733 18565 15197 E LocBroadcastReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: java.net.SocketTimeoutException: failed to connect to 
```

This would definitely cause delays in the reconnection and is not something the app can solve as it just can't connect.  Now that only happened once in this instance but something to consider.

Looking at the logs I see the HA frontend sends the app a disconnect message

```
08-17 20:20:53.370 18565  8715 D WebviewActivity: External bus {"type":"connection-status","payload":{"event":"disconnected"},"id":3}
```

followed by a connection nearly a minute later:

```
08-17 20:21:54.441 18565  8715 D WebviewActivity: External bus {"type":"connection-status","payload":{"event":"connected"},"id":1}
```

Since you said this issue started to happen after switching from Nabu Casa this highly suggests the issue is with your network setup and not the app because the app makes no distinction between what we are connecting to.  I suggest you take a look at the following page for some possible tips and you may want to do more research into the path you selected for hosting HA on its own to see what else yo can do to speed things up.

https://companion.home-assistant.io/docs/troubleshooting/networking

**Comment by lucidnx** [comment]
nope, it is not issue with network at all, it's just because connectivity has changed and that means different routing. you saw on video how it behave. If I don't have app open, right after I switch to wifi and open app after that, it loads immedialy...

**Comment by dshokouhi** [comment]
> Hello! I'v noticed that after switching Home Assistant from Nabu Casa Cloud to my own public IP with SSL, App started having issues on network change from local wifi to mobile/other network.

This statement suggests the issue is related to your own network, wouldn't you have seen this before you made the switch?

**Comment by lucidnx** [comment]
I see, but on nabu casa cloud, I had app set to use only cloud url. Now I had all combinations of URL config set and no one worked without this issue.
Whole issue is caused by active connections, when they time out, I can connect again without killing app but that take some time. Solution would be to reset all connections on network change (mobile/wifi/VPN) as I suggested before.

**Comment by lucidnx** [comment]
I have dns record home.something.com from internet pointing to my external IP (then NAT to local IP of HA), and local DNS record pointing to my local IP of server.
so if I am on wifi, home.example.com is translated to local IP and from internet to external IP. Problem begin, when there is active connection trough external IP not killed when switching to local wifi or VPN. or maybe app have cached server IP from DNS by name and don't change it immedialy because name is identical. solution would be to use different A record from inside but that would add issue with SSL certs and I think I'v tried this one and it did not worked.

**Comment by lucidnx** [comment]
or it's just because of some error.. I am not dev. so I don't understand what's exactly happening in app...

**Comment by dshokouhi** [comment]
Why dont we try to skip all networking configuration and just do a straight connection from the app to the server. Does it work then as you would expect without any local DNS or anything. If that works then it suggests the issue is related to your network setup and not something the app can control. To the app we just look at the URL and load that.

**Comment by dshokouhi** [comment]
Closing due to lack of response
