### ISSUE TITLE
Login Attempt Failed each time app is opened

### ISSUE THREAD

**Issue by ZephireNZ** [home-assistant/android#1676]
**Home Assistant Android version:** beta-712-2da4578-full

**Android version:** Android 11

**Phone model:** Samsung S21

**Home Assistant version:** 2021.8.3

**Last working Home Assistant release (if known):**

**Description of problem:**
Each time the app is started, Home Assistant is recording a failed login attempt. 

I have 2FA enabled if that is relevant. 

Logging into Web UI does not cause the issue. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Can you please provide the logs per the link in the issue template

**Comment by ZephireNZ** [comment]
Closing this off - I think it was actually being caused by a custom card
