### ISSUE TITLE
Add Hebrew language

### ISSUE THREAD

**Issue by tzagim** [home-assistant/android#1683]
English Name: Hebrew
Native Name: עברית

I translated all the software into Hebrew, now it's the app turn :)

**Comment by dshokouhi** [comment]
Hebrew has been added, let me know if you have any issues accessing it :)

**Comment by tzagim** [comment]
> 
> 
> Hebrew has been added, let me know if you have any issues accessing it :)

You probably need to add me manually, I do not see the Hebrew language when I am logged in

**Comment by dshokouhi** [comment]
Hmm I am not really sure how to do honestly, @JBassett will you be able to help out with this?

**Comment by JBassett** [comment]
@tzagim I see the language in lokalise and show you with access.  If you DM me on Discord with your email address I can validate it matches what I see.

**Comment by tzagim** [comment]
I don't know which of you took care of it, but I can edit now.
Thanks
