### ISSUE TITLE
Inconsistent text justification in reloading screen

### ISSUE THREAD

**Issue by mikevansighem** [home-assistant/android#1692]
**Home Assistant Android version:**
2021.8.8

**Android version:**
Android 10

**Phone model:**
Samsung Galaxy 8

**Home Assistant version:**
2021.6.2

**Last working Home Assistant release (if known):**
Unkown

**Description of problem:**
In the reload screen the text for reloading groups is centered while all other options are aligned on the left. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

NA

**Screenshot of problem:**

![Screenshot_20210829-165939_Home Assistant](https://user-images.githubusercontent.com/36593824/131255154-ae0901c3-45c0-4f9d-a0fb-e198ab0c4618.jpg)

**Additional information:**

NA

**Comment by dshokouhi** [comment]
This is a HA frontend issue and not app related. Please file a bug in the appropriate location.
