### ISSUE TITLE
Allow for configurable notification sounds (to distinguish different notification types)

### ISSUE THREAD

**Issue by JoomlaStats** [home-assistant/android#1700]
**Is your feature request related to a problem? Please describe.**
This is not about a problem, but an additional feature idea.

**Describe the solution you'd like**
Configurable notification sounds.

**Describe alternatives you've considered, if any**
Not sure if this can be done with android 'standard' notification, or should be handled with 'playing an audio file'.

**Additional context**
On your phone you'll be notified for 100 different reasons. Maybe you use a home assistant notification to inform about a breaking-in-attempt. Then you would like to hear a a different notification then oh-just-another-email.
It would be very informative when you could configure the audio file / notification type within HA. When the notification sound is on the remote device, this might be just the filename to be played?

**Comment by dshokouhi** [comment]
The app already supports notification channels which takes care of this.

**Comment by JoomlaStats** [comment]
As far as I read in the documentation only iOS allows for playing a customized sound (https://companion.home-assistant.io/docs/notifications/notification-sounds/). I have not found this feature for Android?
You can attach an audio file, but as I understand this will only play on manual trigger (https://companion.home-assistant.io/docs/notifications/notification-attachments).

So indeed being able to notify using an alarm channel is partly solving this issue, however if I'm correct it's not possible to have a notification with the sound of titanic for example (on Android).

**Comment by dshokouhi** [comment]
You want this:

https://companion.home-assistant.io/docs/notifications/notifications-basic/#notification-channels

Channels are a feature of android, for the app you specify a channel per sound you want. Send the notification then you go into your device settings and adjust it there.
