### ISSUE TITLE
local address can't be IP&PORT

### ISSUE THREAD

**Issue by earglass** [home-assistant/android#1701]
**Home Assistant Android version:** 2021.6.2-full

**Android version:** 11

**Phone model:** samsung s20+ (SM-G985F)

**Home Assistant version:** 2021.8.8

**Last working Home Assistant release (if known):** n/a

**Description of problem:** If you use android app and setup remote address (nabucasa domain), then if you try to add local address which is IP and port, validation fails as it requires domain in there. Currently no Android versions support mDNS so I can't add local domain. Please fix it so IP and port can be set as local address.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
The android app does indeed work with IP address and port locally, make sure to not use HTTPS as that will not be supported.

**Comment by dshokouhi** [comment]
Also double check that your HA Configuration contains the correct internal and external URLs
