### ISSUE TITLE
Home Assistant Android with Wear OS app with basic features (lights and switches)

### ISSUE THREAD

**Issue by hkusulja** [home-assistant/android#1706]
**Is your feature request related to a problem? Issue when trying to turn on/off light or switch, from wear os smartwatch.

**Describe the solution you'd like**

Existing Home Assistant Android application, should support to be installed also from Google Play store but for Wear OS (watches), and should be easy to have Tiles on a watch, for turning on/off lights, switches etc.

**Describe alternatives you've considered, if any**

I did not find any good alternatives at all.

**Additional context**

Since now Wear OS by Google 3.0 has been released for new smartwatches (like Samsung Galaxy Watch 4) , new features are requested for existing Google Play Store applications, and that is to support the app to be installed on a watch.

**Comment by imonlinux** [comment]
I would like to see this enhancement as well. I have a cumbersome work around where I installed Domoticz (which has a wearos app) as a vm on Hassio and then added the switches that I want to control on wearos to Domoticz via MQTT.

**Comment by dshokouhi** [comment]
Work has started on the standalone wear OS app but its going to take some time before its ready. Right now there is no functionality and there are some PRs open to add authentication to HA.

**Comment by hkusulja** [comment]
Thank you for confirmation. I do not understand or see reason why this would be a seperate Android app, instead one with all features and central GIT Repo like this one.
If there is some work, or PR's, can you reference them by link? Thank you

**Comment by dshokouhi** [comment]
> Thank you for confirmation. I do not understand or see reason why this would be a seperate Android app, instead one with all features and central GIT Repo like this one.
> If there is some work, or PR's, can you reference them by link? Thank you

You are free to explore GitHub to look at the work done, it's all in this repo. The decision was made for a stand alone app so the wear app can work even when the phone is not nearby but watch is connected to internet. The watch app will not have a dependency on the phone app meaning you will be able to do everything from the watch directly.

**Comment by hkusulja** [comment]
@dshokouhi ok, however still does not require it is separate app. Most watches use Bluetooth to Phone to access internet. Also if watch has direct internet, and is fully standalone, meaning it has to have lot of configurations (URL's, authentication etc.).
Anyway, with direct internet or not, still not clear, why is this not part of the same app, since (as I understand) is just manifest that specifies different behavior for watch, also maybe some things can be shared. Example is Microsoft Outlook for Android (which is not best example but still - one app on store, for both phone and watch use, direct or indirect internet).
I found PR - https://github.com/home-assistant/android/pull/1691

**Comment by dshokouhi** [comment]
Did you miss the wear folder on GitHub? It's part of the same code base.

**Comment by hkusulja** [comment]
No, I have found, just thinking, should it be, one manifest for one app supporting both device types (like Spotify and others does https://play.google.com/store/apps/details?id=com.spotify.music) 

https://github.com/home-assistant/android/blob/master/app/src/main/AndroidManifest.xml
https://github.com/home-assistant/android/blob/master/wear/src/main/AndroidManifest.xml

**Comment by dshokouhi** [comment]
@hkusulja we have already made our decision and moved forward. You are more than welcome to look at the merged PRs to look at that discussion and the decision that was already made.

**Comment by hkusulja** [comment]
ok, seem that I am too late, and all discussion and decision were made. Any ETA for publishing this another app for wear os on google play store?

**Comment by dshokouhi** [comment]
there is no ETA, it will be ready when its ready. There is no functionality now.  Also keep in mind it will still be able to share data wiht the phone and it shares a code base with the app.  Standalone is just terminology from google saying this app can work on its own without the requirement of a phone app. That means a user can install the app and do everything they need to do without needing the phone, the phone can still be used to make things easier like sharing URLs but the wear OS device needs its own authentication and should also be treated like its own device in HA. I am pretty sure you will get everything out of the app you expect once its ready.  Our goal is that if your watch is online and your phone is not around and you need to make any change to watch settings you can do it, dont need your phone to make that change.

More on standalone wear apps here: 
https://developer.android.com/training/wearables/overlays/independent-vs-dependent#identify

**Comment by hkusulja** [comment]
Yeah, i read the docs on given link. Thank you.
Leaving this github issue for feature request on light and switch on/off setting through wear os - Tiles..
i understand it is early.
Thank you all for contribution.

**Comment by hkusulja** [comment]
@JBassett i see you closed this github issue, can you please confirm that Home Assistant - Android WareOS is available on Google Play store, so my users can install it and test it ? Thank you

**Comment by hkusulja** [comment]
my android phone is stuck in "joining beta" for existing home assitant app, hope this will be resolved.
So please confirm, this will be this app, and not a new / separate app? https://play.google.com/store/apps/details?id=io.homeassistant.companion.android

**Comment by JBassett** [comment]
Yes it is published with the existing application.

**Comment by hkusulja** [comment]
Thank you, since related communication stated that it was decided that it will be standalone app, separate from current one.
Anyhow, now I am part of new Beta program on Google Play store, for this one/only app. And successfully installed on my Galaxy Watch 4 / Wear OS 3 and connected.

However, @JBassett , I think this GitHub issue should be still opened since:
* The app has just "scenes" and no direct mentioned switches or lights are possible to control via app
* Home Assistant app does not have any "Wear OS Tiles" as described above for easier run of the scene or lights https://developer.android.com/codelabs/wear-tiles

**Comment by hkusulja** [comment]
Ok, clear, but again, this issue is not resolved:
 * Mentioned Tiles, does not exist, so i have opened a new, separate GitHub issue / feature request - #1802
 * Lights are there for me (using Google Play Store Beta) but list is empty, opened separate GitHub issue / bug - #1803
 * Switches are not inside app as mentioned above
