### ISSUE TITLE
AuthenticationPresenter: unable to register code

### ISSUE THREAD

**Issue by duncf** [home-assistant/android#1708]
**Home Assistant Android version:** 2021.9.0-full

**Android version:** 11

**Phone model:** Pixel 4 XL

**Home Assistant version:** 2021.9.6

**Last working Home Assistant release (if known):** N/A, new setup

**Description of problem:**

I'm trying to get the android app working with a new HomeAssistant installation over https. When I try to connect, I get an error:

"Unable to connect to Home Assistant.
There was an error loading Home Assistant, please review the connection settings and try again. We will attempt to try another provided URL when you click on Refresh."

I have a rather elaborate reverse proxy setup involved, and that seems to be triggering the issue. When I try to connect directly to HA via IP address (either IPv4 or IPv6) to port 8123, I am able to connect.

I've used mitmproxy to try to isolate the issue, and the error occurs after a POST request to
`/auth/login_flow/<long hex string>` returns a successful gzip-encoded JSON response.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

The only log lines around the time of the error are:

```
09-13 01:19:09.759  6818  7256 D UrlRepository: localUrl is: false and usesInternalSsid is: false
09-13 01:19:09.759  6818  7256 D UrlRepository: Using external URL
```
(/auth/login_flow/... request happens)
```
09-13 01:19:10.058  6818  6818 E AuthenticationPresenter: unable to register code
```

**Screenshot of problem:**

**Additional information:**

I realize I'm on my own to debug my reverse proxy setup, but it would be nice if the app could provide a more helpful error message, or maybe the logs could provide a little more info on where to look.

**Comment by dshokouhi** [comment]
This troubleshooting section might be of help:

https://companion.home-assistant.io/docs/troubleshooting/networking

In terms of better logging, it looks like we can print the full stack trace which will give more clues to the issue.

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationPresenterImpl.kt#L44

The error message we have is generic as there are many reasons the failure can occur so its not as easy to put a better error message there but the stacktrace should provide more clues.

**Comment by dshokouhi** [comment]
@duncf can you try the debug APK from: https://github.com/home-assistant/android/actions/runs/1233977723

I have added some code to print the actual stack trace so once you reproduce the error get the logs again and look for `unable to register code` and just below that we should see the actual reason for the failure.

**Comment by duncf** [comment]
Thank you very much @dshokouhi, this is super helpful!

The debug app also shows full body requests and responses, making it much easier to figure out what's going on.

The issue I was having was that I was able to authenticate just fine within the WebView to get to and through the login screen, but my reverse proxy setup relies on cookies, and the cookies that are set during the WebView flow are not provided in the POST request to `/auth/token` to get a token.

Without the cookies, the proxy redirects to a error/login page. The app tries to parse the HTML as JSON, and, predictably fails.

```
09-14 21:51:56.081 32634 32634 E AuthenticationPresenter: unable to register code
09-14 21:51:56.081 32634 32634 E AuthenticationPresenter: com.fasterxml.jackson.core.JsonParseException: Unexpected character (
'<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
```

Would it make sense to update the documentation with info about the debug app? Do you think there would be interest in a PR that copies cookies from the WebView CookieManager to okHttp via an interceptor? (I can file a separate feature request.)

**Comment by dshokouhi** [comment]
> Would it make sense to update the documentation with info about the debug app?

its already mentioned in the project read me and also in the docs: https://companion.home-assistant.io/docs/core/android-flavors



> Do you think there would be interest in a PR that copies cookies from the WebView CookieManager to okHttp via an interceptor? (I can file a separate feature request.)

I am not sure on this one and I have never heard of a HA setup like this until this issue but regarding proxy setup we do have a troubleshooting section about it: https://companion.home-assistant.io/docs/troubleshooting/networking#addendum-reverse-proxy-via-nginx

**Comment by duncf** [comment]
I've sent https://github.com/home-assistant/android/pull/1797.

> I am not sure on this one and I have never heard of a HA setup like this until this issue but regarding proxy setup we do have a troubleshooting section about it: https://companion.home-assistant.io/docs/troubleshooting/networking#addendum-reverse-proxy-via-nginx

I admit this is a fairly uncommon setup, but it's also uncommon because it's not supported well right now. :-) I'm not the first to try this -- e.g. #151. (#1797 will not fix that issue, as Google oauth is AFAIK still not permitted in webview. I'm using github authentication with Cloudflare Access.)

I've also written up some of the motivation here: https://www.duncf.blog/2021/10/protect-home-assistant-from-no-auth.html
