### ISSUE TITLE
HomeAssistant access denied after short time.

### ISSUE THREAD

**Issue by Retroman445** [home-assistant/android#1712]
**Home Assistant Android version:**
2021.9.0-full

**Android version:**
11

**Phone model:**
PocoPhone X3 NFC with LineageOS 18 MicroG

**Home Assistant version:**
core-2021.9.6
supervisor-2021.09.0

**Last working Home Assistant release (if known):**
No change in versions. Same as above.

**Description of problem:**
The companion app seems to login fine. Then after a short while of completely normal use (varies from few to 20 seconds) I get the Unable To Connect to Home Assistant. Neither via Nabu Casa or locally logon.

**Traceback (if applicable):**
```
No crash... no traceback.
```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/51086501/133220491-2c6a41a1-ffbc-47a9-a652-853c1409c5f5.png)

**Additional information:**

**Important Logline**
It seems it is related to:
```
09-14 09:54:49.391  4769  4769 I chromium: [INFO:CONSOLE(1)] "Uncaught (in promise) SecurityError: Failed to construct 'WebSocket': Access to this address is not allowed.", source: https://mynabucasaidstringhere.ui.nabu.casa/frontend_latest/core.9dd583b2.js (1)
```
After which I get a LOT of these, obviously.

```
09-14 09:54:57.454  4769  4781 E mpanion.androi: failed to connect to jdwp control socket: Connection refused
```
See logfile for more detail.
[homeassistant_companion_log_8-14-2021_9-55-12.txt](https://github.com/home-assistant/android/files/7159937/homeassistant_companion_log_8-14-2021_9-55-12.txt)

**Related**
Seems to be related to the Bromite Webview. 
https://github.com/bromite/bromite/issues/822
A security measure: "@cvsickle Bromite does not allow a non-local address to access a local address; this is by design and not a bug in Bromite."

**Comment by Retroman445** [comment]
**Update new version Bromite**
I updated to a newer version of Bromite Webview and this resulted in a bit better description in regards of this error.

`09-14 13:39:57.355  4740  4740 I chromium: [INFO:CONSOLE(1)] "Uncaught (in promise) SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.", source: https://mynabucasalongstring.ui.nabu.casa/frontend_latest/core.9dd583b2.js`

My instance uses https by default. It seems that from the jsfile a http websocket is initiated, which is (rightly so in my optinion) blocked. I will look into this a bit further..

[homeassistant_companion_log_8-14-2021_13-40-50.txt](https://github.com/home-assistant/android/files/7161715/homeassistant_companion_log_8-14-2021_13-40-50.txt)

**Comment by dshokouhi** [comment]
Sorry bromite is not supported you must use googles version of Android system webview.

**Comment by Retroman445** [comment]
So insecure methods are a standard practice? Thats an easy copout.

Seems trivial to check if the http ot https protocols are used in the installatie and initiate the correct protocol.
If I can fix this myself, do you consider accepting the commit even if bromite is not supported (bromite is still chromium which is google webview...)

**Comment by dshokouhi** [comment]
> So insecure methods are a standard practice? Thats an easy copout.
> 
> Seems trivial to check if the http ot https protocols are used in the installatie and initiate the correct protocol.
> If I can fix this myself, do you consider accepting the commit even if bromite is not supported?
> (bromite is still chromium which is google webview...)

Bromite is blocking things in the HA frontend which is causing this issue and as the app is just a webview this means that Bromite is doing non-standard things.  Your screenshot is of the HA frontend and not a screen that the app provides. There is a reason why we support googles version and it just works without needing to do any changes. Not to mention the majority of users already have this on their device.  Custom ROMs also ship with non-standard versions of webview which cause other issues and those users switch to supported webview also. Simply switching to Googles version just works without any changes, so we stick to supporting that.  If you want to use non-standard webview that is your choice but you are on your own there.

**Comment by Retroman445** [comment]
Ah, ok. Understandable from a support and resources point of view.
From a security point of view I understand the Bromite reason for blocking this also. Same as http content in an https website. Which is now blocked out-of-the box in nearly every browser. Maybe this will change in webview also.

I'll leave it at that, thank you for responding to my "rant".

**Comment by cvsickle** [comment]
> 
> 
> Ah, ok. Understandable from a support and resources point of view.
> From a security point of view I understand the Bromite reason for blocking this also. Same as http content in an https website. Which is now standard blocked in some browsers. Maybe this will change in webview also.
> 
> I'll leave it at that, thank you for responding to my "rant".

Reporting this issue here gets the finger pointed at Bromite. Reporting it to Bromite gets the finger pointed here. I gave up trying to get this fixed a long time ago.

**Comment by Retroman445** [comment]
@cvsickle Yes I get that. A small workaround, to get rid of Bromite and let Home Asisstant app connect again here:

https://forum.xda-developers.com/t/rom-10-lineageos-17-1-18-1-official-trees-unofficial-build-surya-karna.4202533/post-85658101
