### ISSUE TITLE
Mobile Rx & Tx sensors reset when going from wifi to mobile and back

### ISSUE THREAD

**Issue by ghvader** [home-assistant/android#1714]
**Home Assistant Android version:**
2021.9.0-full
**Android version:**
11
**Phone model:**
Samsung galaxy s10+
**Home Assistant version:**
2021.9.6
**Last working Home Assistant release (if known):**
not known
**Description of problem:**
the sensors Mobile Rx & Mobile Tx sensors say that they show data since the last reboot.
however, when going from wifi to mobile, the counters start to tick up. when you transition back to wifi, they reset to zero
Total Rx and Tx include wifi data which I don't want (correct me if i'm wrong on that)
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**
I'm trying to monitor mobile/cellular data usage and am looking for a cumulative total that will be reset each month.
with the mobile tx and rx sensors resetting to zero when going to and from wifi, I can not get a cumulative total in HA

**Comment by dshokouhi** [comment]
So the sensors provide data from the Android API. It looks like in Samsung's case they may not respect how it is documented. I am not sure we can fix this. Personally I have not noticed this behavior on my pixel.

**Comment by ghvader** [comment]
@dshokouhi interesting. In my settings menu I have monthly data uses for both mobile and wifi. I guess it's proprietary.
I will close the ticket since it can't be fixed.
