### ISSUE TITLE
Incorrect behavior when clicking  on a notification 

### ISSUE THREAD

**Issue by new-kirte** [home-assistant/android#1721]
**Home Assistant Android version:** beta-731-c5e3d4a-full

**Android version:** Android  11

**Phone model:** Samsung Z FLIP 3

**Home Assistant version:** Home Assistant 2021.9.7

**Last working Home Assistant release (if known):**

**Description of problem:**
Clicking on a notification like below does nothing. Expected behaviour for Android is to redirect a user to a relevant part within the application. I  this case to Home Assistant Companion/ App Configuration/ Notification history.

service: notify.mobile_app_z_flip
data:
  message: >-
    Alex is up v2.0 '{{ trigger.to_state.attributes.motion_video_time }}', '{{
    trigger.from_state.attributes.motion_video_time }} {{
    as_timestamp(trigger.to_state.attributes.motion_video_time)-as_timestamp(trigger.from_state.attributes.motion_video_time)
    }}'
  title: Alex is up 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20210922-091901_Home Assistant](https://user-images.githubusercontent.com/10042655/134287469-d3d7f9b2-825f-4b0a-861c-119be99c1ba1.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
hmm wonder when this broke, the code itself hasnt changed in a while. Might be a consequence of some dependency update.

**Comment by dshokouhi** [comment]
@new-kirte until this gets fixed please make use of `clickAction` or actionable notifications. Those will let you override the default and navigate to any lovelace tab.

**Comment by dshokouhi** [comment]
the standard behavior without any `clickAction` set should take the user to the lovelace homepage, seems we may need to enforce a default here as currently it has no data to load.  Possibly related to the fix for #1472?
