### ISSUE TITLE
Incorrect time for motion sensor

### ISSUE THREAD

**Issue by raqua** [home-assistant/android#1725]
I have Xiaomi Aquara motion sensor connected through Zigbee2MQTT and the time after midnight says 24:15h instead of 0:15 in a details view. It is correct in HA web. Please see attached screenshot. 
Maybe relevant - my locale is Europe/Budapest.

![Screenshot_20210925-081052_Home_Assistant](https://user-images.githubusercontent.com/1541886/134764045-bace8bd2-dc6b-4f4b-9066-cd88dd17ab34.png)

**Comment by dshokouhi** [comment]
Did you set the language under app configuration? We don't control things like outside of the selected language.

**Comment by raqua** [comment]
I have set the app to device language and my device language is English(UK).

**Comment by dshokouhi** [comment]
What about in your user profile?

**Comment by raqua** [comment]
I am not sure what do you mean by that. My phone is set to use English everywhere. I have additional secondary language set to Slovak, but all apps, menus, rom of my phone is in English.

**Comment by dshokouhi** [comment]
Open the side menu and go to your HA user profile and there are additional settings there.

**Comment by raqua** [comment]
Aha, this is my settings. 

![2021-09-26_17-04](https://user-images.githubusercontent.com/1541886/134813313-38b18cc4-8a03-44c4-a35c-d57f4d24667b.png)

**Comment by dshokouhi** [comment]
So the app has no control over what shows up in the HA frontend. These settings here are not for the app.

**Comment by raqua** [comment]
I am not sure what you are asking. I have the same profile settings in app. If I click on my username, I get to the same settings with the same values. 
Please be more verbose on what information you need me to provide if any.

**Comment by dshokouhi** [comment]
Can you try in chrome for Android in the same device and see if the results are the same?

**Comment by raqua** [comment]
Sure. But currently I do not have any motion values after midnight. I will generate some today and respond afterwards.

**Comment by raqua** [comment]
In Chrome for Android I have the same issue.

**Comment by dshokouhi** [comment]
@raqua thanks for confirming, this means it is definitely not an app issue and is related to the HA frontend.  As the frontend team requires their own template you will need to open a new issue (after checking this one doesnt already exist) to continue.

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=bug_report.yml

**Comment by raqua** [comment]
OK, thanks. I have found that it is already reported there.
