### ISSUE TITLE
quick start

### ISSUE THREAD

**Issue by xaxexa** [home-assistant/android#1729]
Each time the application is launched, it first connects to the server, exchanges data, and only after that the main screen appears. it might be worth taking information from the cache, then connecting in the background and updating all the information, the launch would look faster

**Comment by dshokouhi** [comment]
This is as designed.  When the application launches the sensor worker starts up and teh frontend is shown.  A lot of data communicates early via the external bus from the frontend which for example tells the app that the frontend is connected.
