### ISSUE TITLE
sensor update

### ISSUE THREAD

**Issue by xaxexa** [home-assistant/android#1730]
I constantly see in the blind that the application is updating the sensors, I only have the "phone on charging" status active, the application wakes up and exchanges data with the server, in fact, it wastes battery power, maybe it is worth updating the sensors according to events, and others on time?

**Comment by dshokouhi** [comment]
The sensor worker runs on a 15 minute interval and reasoning for the notification can be found in the docs.

https://companion.home-assistant.io/docs/core/sensors

**Comment by xaxexa** [comment]
I read the link, and it turns out, in my work script only the "charging status" is used, what's the point of updating all the sensors every 15 minutes

**Comment by dshokouhi** [comment]
> I read the link, and it turns out, in my work script only the "charging status" is used, what's the point of updating all the sensors every 15 minutes

not all sensors are push based like battery level, and all sensors are part of the sensor manager workflow.  If you don't like the notification you can turn off the Sensor Worker notification channel.

**Comment by xaxexa** [comment]
no no that you, the application is great, I really like everything, I just thought it might be a useful idea to reduce the number of requests and more rare "awakenings" of the application

**Comment by dshokouhi** [comment]
> no no that you, the application is great, I really like everything, I just thought it might be a useful idea to reduce the number of requests and more rare "awakenings" of the application

Thats what i was trying to explain. Sensors all go through the manager which is part of the sensor worker which runs at the 15 minute interval. All sensors are apart of this as per our architecture, this allows to easily add sensors and other attributes.  In addition to this interval certain sensors also update push based.  Sensor updates do not contribute to a lot of drain, I have every sensor enabled at and the end of the day I never see the HA app in the battery list. There might be something else if you are seeing that. Some users may use Last Notification Sensor without any white list setup and that indeed can cause a drain as your phone receives a lot of notifications that you don't see.  Disabling the Sensor Worker notification channel doesn't stop the worker persay it just removes the notification as the worker is attached to a foreground process.  Without this foreground process sensor updates stop after sometime.

**Comment by xaxexa** [comment]
I do not understand android architecture, your last answer is exhaustive, thanks for everything
