### ISSUE TITLE
Next Alarm and Charger Type 'Unavailable' but expected 'Off' and 'Not Charging' or similar

### ISSUE THREAD

**Issue by mpsamuels** [home-assistant/android#1731]
**Home Assistant Android version:**
2021.9.0-full

**Android version:**
11

**Phone model:**
Samsung Galaxy S21 Ultra (SM-G998B)

**Home Assistant version:**
2021.9.7

**Last working Home Assistant release (if known):**
Unknown. This seems to have been the case since I migrated to the S21. I don't recall it being a problem with my previous androud phone, an older Samsung Galaxy model.

**Description of problem:**
When the phone has no alarm turned on and/or it is not connected to a charger the next_alarm and charger_type sensors are reported as 'unavailable' respectively.

I would expect the sensors to be able to report that the phone's alarm  'off' and/or that the charger type is 'disconnected' rather than reporting the sensor as 'unavailable', which implies there is a problem collecting data from the sensor itself rather than that the sensor simply has nothing of interest to report.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Next Alarm does indeed have a `unavailabe` state which is also mentioned in teh documentation.

Charger Type will show either: `ac`, `usb`, `wireless`, or `none`

Charging status will show: `full`, `charging`, `discharging`, `not_charging` and `unkonwn`
