### ISSUE TITLE
Service Button widget missing trigger data

### ISSUE THREAD

**Issue by iancg** [home-assistant/android#1732]
**Home Assistant Android version:**
2021.9.0-full

**Android version:**
11 (Oxygen OS 11..2.1.HD01BA)

**Phone model:**
Oneplus HD1913

**Home Assistant version:**
core-2021.9.6

**Last working Home Assistant release (if known):**

**Description of problem:**
Triggering a service using a service button widget doesn't include the trigger data when executed.

E.g. an automation:

- id: '1633009619154'
  alias: Test
  description: ''
  trigger: []
  condition: []
  action:
  - service: notify.mobile_app_my_phone
    data_template:
      data:
        tag: test
      title: Test
      message: Trigger Platform: {{ trigger.platform }}
  mode: single

Results in the notification "Trigger Platform: None"

In particular I was expecting to be able to access trigger.event.context.user_id but trigger doesn't appear to be populated correctly.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

N/A

**Screenshot of problem:**

**Additional information:**

To reproduce, create an automation as described above, then create a Home Assistant Service Button Widget on the phone and choose "automation.trigger" as the service and "automation.test" as the Entity ID.  Press Add Widget, then click on the Widget to invoke it.  Note that the result is "Trigger Platform: None" and that trigger value is otherwise empty.

**Comment by dshokouhi** [comment]
This is to be expected, triggering an automation will bypass the trigger (thats the point in the service call) , see `automation.trigger` service description

https://www.home-assistant.io/docs/automation/services/

**Comment by iancg** [comment]
Thanks, @dshokouhi . I can see that the documentation says it will bypass conditions. But thinking about it further I suppose I realise there is no event behind the triggering of the automation as the automation was triggered directly by the service.

Is there a way to trigger an automation from a android app widget such that the identify of the android app user is accessible to the automation?

**Comment by dshokouhi** [comment]
@iancg  I believe HA should be recording the context, check the history of the automation and see if it shows the user name there. Might be able to access that somehow.

Alternatively you can use a script and setup a variable so you can manually enter that in the widget and react off of its value.

https://www.home-assistant.io/integrations/script/#variables
