### ISSUE TITLE
unable to connect via reverse proxy

### ISSUE THREAD

**Issue by muggenhor** [home-assistant/android#1753]
**Home Assistant Android version:**
2021.9.0-full

**Android version:**
10

**Phone model:**
Fairphone 3

**Home Assistant version:**
2021.9.7 behind nginx 1.14 as reverse proxy with a Let's Encrypt certificate

**Last working Home Assistant release (if known):**
Exact same versions as above. Failure appeared _without_ an upgrade

**Description of problem:**

Up until this morning the app worked fine. Then in the morning it stopped being able to connect and I got a dialog with a message indicating I could wait and retry. I did that a few times, then got myself IP banned apparently.

I deleted the IP ban and restarted HomeAssistant. I kept getting these errors, so I reinstalled the app and tried again. From that point on forward I could never get further than the attached screenshot.

I did not upgrade any software, nor did the certificate rotate in between last night (when the app still worked) and this morning. I.e. nothing that I can think of changed.

**Screenshot of problem:**
![Screenshot_20211006-104924](https://user-images.githubusercontent.com/484066/136177091-fd4c979f-802d-4c8f-b095-8196ae42f311.png)

**Additional information:**
* Using the same (external) URL in either Chrome or Firefox (on the phone) succeeds without a hitch
* Connecting directly via the IP address of HomeAssistant itself on port 8123 without encryption does work
* When using the external URL, looking in the nginx logs the authentication appears to succeed. But then still shows the preceding screenshot:
```
<IP-elided> - - [06/Oct/2021:08:48:59 +0000] "POST /auth/login_flow HTTP/2.0" 200 183 "https://ha.custoft.eu/auth/authorize?response_type=code&client_id=https://home-assistant.io/android&redirect_uri=homeassistant://auth-callback" "Mozilla/5.0 (Linux; Android 10; FP3 Build/8901.3.A.0107.20210513; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.71 Mobile Safari/537.36"                                                                                                        
<IP-elided> - - [06/Oct/2021:08:49:12 +0000] "POST /auth/login_flow/XXXXXXXXXXXXXXXXXX HTTP/2.0" 200 190 "https://ha.custoft.eu/auth/authorize?response_type=code&client_id=https://home-assistant.io/android&redirect_uri=homeassistant://auth-callback" "Mozilla/5.0 (Linux; Android 10; FP3 Build/8901.3.A.0107.20210513; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.71 Mobile Safari/537.36"
<IP-elided> - - [06/Oct/2021:08:52:45 +0000] "POST /auth/login_flow HTTP/2.0" 200 184 "https://ha.custoft.eu/auth/authorize?response_type=code&client_id=https://home-assistant.io/android&redirect_uri=homeassistant://auth-callback" "Mozilla/5.0 (Linux; Android 10; FP3 Build/8901.3.A.0107.20210513; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.71 Mobile Safari/537.36"
<IP-elided> - - [06/Oct/2021:08:52:56 +0000] "POST /auth/login_flow/YYYYYYYYYYYYYYYYYYY HTTP/2.0" 200 189 "https://ha.custoft.eu/auth/authorize?response_type=code&client_id=https://home-assistant.io/android&redirect_uri=homeassistant://auth-callback" "Mozilla/5.0 (Linux; Android 10; FP3 Build/8901.3.A.0107.20210513; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.71 Mobile Safari/537.36"
```

This seems to have some symptomatic overlap with:
* #446
* https://www.reddit.com/r/homeassistant/comments/l5ydo9/android_app_error/
* https://community.home-assistant.io/t/suddenly-fail-to-connect-to-android-app/324672

**Comment by dshokouhi** [comment]
if you bypass nginx does the app work as expected?

**Comment by muggenhor** [comment]
> if you bypass nginx does the app work as expected?

Yes, as I mentioned:
> * Connecting directly via the IP address of HomeAssistant itself on port 8123 without encryption does work

**Comment by dshokouhi** [comment]
Ok since it works outside of hte proxy this means its either a setting with HA configuration or a proxy issue and not an app issue, this troubleshooting section as some help:

https://companion.home-assistant.io/docs/troubleshooting/networking#addendum-reverse-proxy-via-nginx

If this doesnt work you will want to look into recent breaking changes for HA as they had some for proxy users.

**Comment by muggenhor** [comment]
I tried both https://github.com/home-assistant/android/releases/tag/beta-1672-38c627f and https://github.com/home-assistant/android/releases/tag/beta-764-1573c2e and they both still give the same generic and useless error when I'm forcing an OCSP failure (out of date staple) or a wrong certificate (for another domain name).

**Comment by dshokouhi** [comment]
Can you share the logs please

**Comment by Kariton** [comment]
Im just here while looking for known ``OCSP`` problems...
My cert also ``must staple``.

```
# openssl s_client -connect example.com:443 -status |  grep 'OCSP response' -A7
OCSP response:
======================================
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = US, O = Let's Encrypt, CN = R3
```
As you see - it is valid.
Firefox (is _very picky_ with OSCP) does accept that too - Chrome does not care. :)

I can provide some logs later.

**Comment by dshokouhi** [comment]
logs will be needed but as this is a closed issue please open a new issue and make sure to fill out the issue template completely.

**Comment by muggenhor** [comment]
> Can you share the logs please

I assume you mean the app's logs? I'm not an Android developer, so have no clue how to obtain those. Does the app store something somewhere?

**Comment by dshokouhi** [comment]
> > Can you share the logs please
> 
> I assume you mean the app's logs? I'm not an Android developer, so have no clue how to obtain those. Does the app store something somewhere?

We can't get to them from the app if you can't login successfully so you will need to use an app like logcat reader and use a USB cable to grant the proper permission once prompted to gain access to the logs.

**Comment by Kariton** [comment]
Maybe #1934 is related to your problem. :)
I also got some logs.

I was logged in so: on the error screen is a button 'Settings' -> and at the bottom is a option to share / view the logs.
