### ISSUE TITLE
Consolidated User Agent for more strict firewall block rules

### ISSUE THREAD

**Issue by arthurgeek** [home-assistant/android#1762]
**Is your feature request related to a problem? Please describe.**

I understand (and agree with) that 2FA flows is not something you want to add (https://github.com/home-assistant/android/issues/45). This means, to increase security, we have to resort to generic firewall block settings. That's exactly what I'm doing in my Cloudflare domain, but the solution is not the most secure one.

**Describe the solution you'd like**

I'd like to be able to change the User Agent in the app settings to something that's unique to my app. This way I can have a firewall setting that checks for this User Agent and only enables HTTP calls  from my specific app. This would be the most secure firewall config I can think of, since it can be traced back to my specific app install.

**Describe alternatives you've considered, if any**

Like I mentioned above, there are some other firewall rules you can use, but they're not as restricted as having a custom user agent.

**Additional context**

**Comment by dshokouhi** [comment]
The app already provides a unique custom user agent string is this not enough to go by?  This differentiates it from any other app as it contains the app name and version number

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantRetrofit.kt#L48

**Comment by arthurgeek** [comment]
@dshokouhi thank you for looking into this. I should mention the above calls are only for the auth part of the app. I have not logged in or tried to send sensor data to check if there were UAs.

> Yes we can add the device model to the call to help differentiate it.

To be clear, I was thinking of the device name you set up when first open the app. That one has a higher chance of being unique than device model or app name.

**Comment by arthurgeek** [comment]
I wasn't able to get the calls to register or updating sensors, because I can only see blocked calls. If I'm able to update my firewall settings to take into consideration the new UA (as soon as it's sent from the WebView), I can give it another try to use the app and see if there will be any blocked calls.

**Comment by dshokouhi** [comment]
heres the latest update :) https://github.com/home-assistant/android/actions/runs/1339486249

**Comment by arthurgeek** [comment]
I believe the `/service_worker.js` call still uses the default WebView UA.

**Comment by dshokouhi** [comment]
> There's one small thing: the user agent is still not 100% consistent, WebView calls UA is `HomeAssistant/Android HA GitHub LOCAL-full` while webhook calls is `HomeAssistant/Android HA GitHub LOCAL-1`.

in production that last part will be the version name so it won't be an issue, only in debug builds will it read a bit odd. Otherwise it will always list the app version.



> I believe the `/service_worker.js` call still uses the default WebView UA.

This is something the HA frontend is serving, I can try to look and see if theres another location for this but thought we got them all 🤔  are you sure its from the debug build and not the production version?

**Comment by dshokouhi** [comment]
> I'm now certain the request comes from the HA app and not my Chrome Browser.

now to hunt down where this extra call is coming from 🤔

**Comment by arthurgeek** [comment]
No need to go hunting: Looks like it's just how ServiceWorkers and WebView works:

https://bugs.chromium.org/p/chromium/issues/detail?id=789769&q=WebView%20service%20worker%20user%20agent&can=2

Not sure if they implemented any method in the ServiceWorkerController as mentioned in the bug report.

**Comment by dshokouhi** [comment]
its coming from the HA frontend, we don't have control of that in the app.  You would need to file a separate request for the frontend. My guess is if its needed in chrome then its needed in the app as well.
