### ISSUE TITLE
Area support for lights in WearOS app

### ISSUE THREAD

**Issue by brewston** [home-assistant/android#1795]
**Is your feature request related to a problem? Please describe.**

Navigating the lights is slow due to them all being presented in a list.

**Describe the solution you'd like**

Please could you add support for Areas (eg Kitchen, Bedroom etc) and have this be the default view ? It would be much quicker to find the correct light to toggle this way.

**Describe alternatives you've considered, if any**

N/A

**Additional context**

None.

**Comment by dshokouhi** [comment]
This is going to have to wait until the app gains support for websockets as we cannot get the area using the current methods we have. There are other areas of the app which would also benefit from this so we do indeed want this :)

**Comment by leroyboerefijn** [comment]
In addition, we really need to think about the desired UX for the wear app. How will the typical user want to navigate through the app?

- By area, as proposed here?
- Just buttons on the home activity to go to sub lists (e.g. areas, scenes, lights, devices, etc.)
- A list with different categories, like we have now, but only show ~3 favorites per category + a 'more' button
- Any other smart ideas?

**Comment by dshokouhi** [comment]
I think favorites is a good approach here since most folks will want to use the watch for quick actions and may already have entities in mind for quick access.

**Comment by leroyboerefijn** [comment]
@brewston @dshokouhi and including @SkechyWolf @LasseRosenow since they were involved in previous UI/UX changes.

I think this is a good moment to discuss improvements to general layout of the Wear OS app. This is related to this issue, but mainly more general so sorry for hijacking this issue. I think everyone will agree that the list in the current main view is simply too long to be really useful. I'll make a suggestion below, but would really like as much input here as possible!

I would suggest the main view consists of:

- Favorites list as it is now, preferably made sortable in the future (similar to shortcuts tile?)
- Buttons for each section type (areas, scenes, lights, covers, etc.). Each will lead to a list in a separate view
- Settings button

The proposal above is the best I can think of right now. A slight alternative I still have in my mind is to split the favorites per category. The layout will then be very similar as it is now, but instead show only the favorites for each categories and a 'more' button. This would give a bit more structure if the user has a lot of favorites.

What do all of you think?

**Comment by dshokouhi** [comment]
> * Favorites list as it is now, preferably made sortable in the future (similar to shortcuts tile?)

So for this I was just playing around with this library to add drag and drop. Right now I have it sending wear the correct order but its not saving properly. I may submit later today to get some feedback if I remain stuck :)  I don't know of an easy way to achieve this on the watch, somethings are just easier done on the phone than watch. Although we could implement what we do for shortcut tiles today.

https://github.com/aclassen/ComposeReorderable



> * Buttons for each section type (areas, scenes, lights, covers, etc.). Each will lead to a list in a separate view

So my initial thought was to move the loading of all entities to another screen, so with this are we thinking of moving all entities but separating them by area/domain?



> * Settings button

Probably also a "Add favorites" button for users who have not set them up yet? Maybe we could even direct users to this page after onboarding?  But yea Log Out should be moved to Settings itself as well



> A slight alternative I still have in my mind is to split the favorites per category. The layout will then be very similar as it is now, but instead show only the favorites for each categories and a 'more' button. This would give a bit more structure if the user has a lot of favorites.

So for categories I don't think every user will have areas setup, personally I don't. I was thinking of making this more of a custom category where a user can enter whatever they like (if they want to categorize the list) and then we can split them up this way.

I think the overall goal for the app is how long of a time it takes someone to get to an entity. Personally I like favorites to remain a simple list with just some re-ordering so users can put what they want at the top.  I don't see too many users going to all entities once they customize their favorites.

**Comment by leroyboerefijn** [comment]
> So for this I was just playing around with this library to add drag and drop. Right now I have it sending wear the correct order but its not saving properly. I may submit later today to get some feedback if I remain stuck :) I don't know of an easy way to achieve this on the watch, somethings are just easier done on the phone than watch. Although we could implement what we do for shortcut tiles today.

Awesome! Can't wait to see it :)

> So my initial thought was to move the loading of all entities to another screen, so with this are we thinking of moving all entities but separating them by area/domain?

My proposal would be to split them indeed by area/domain (where areas will contain multiple domains obviously). Or do you have an alternative idea?

> Probably also a "Add favorites" button for users who have not set them up yet? Maybe we could even direct users to this page after onboarding? But yea Log Out should be moved to Settings itself as well

I was also thinking about an add favorites button and moving log out to settings indeed :)

The onboarding idea is nice as well! Maybe we should have a short introduction/tutorial flow?

> I think the overall goal for the app is how long of a time it takes someone to get to an entity. Personally I like favorites to remain a simple list with just some re-ordering so users can put what they want at the top. I don't see too many users going to all entities once they customize their favorites.

I agree

**Comment by brewston** [comment]
My personal preference would be to keep Favorites as a simple list but being able to re-arrange items would be very cool !
