### ISSUE TITLE
Last notification doesn't update entity unless I open the corresponding app menu

### ISSUE THREAD

**Issue by jeepotvin** [home-assistant/android#1801]
**Home Assistant Android version:** 2021.10.0.full

**Android version:** 11

**Phone model:** Pixel 2 XL

**Home Assistant version:** core-2021.10.6

**Last working Home Assistant release (if known):** Don't remember :(

**Description of problem:**
I have an automation based on the "Last notification" sensor. It used to work quite well.
Now it's like the entity `sensor.pixel_2_xl_last_notification` doesn't update unless I manually go in the HA Android App > App Configuration > Manage Sensors > Last Notification.

Here's a [screen recording](https://photos.app.goo.gl/ezDRJpmgUyzdFhoS9) to demonstrate the problem.

Key elements to look for are:
1- In the _Developer Tools_, the entity `sensor.pixel_2_xl_last_notification` has _Last updated_ set to `October 18, 2021, 9:24:22 AM` (time I installed the latest HA core-2021.10.6 and rebooted the system).
2- After going in the _App Configuration_ menu, the entity `sensor.pixel_2_xl_last_notification` has now _Last updated_ set to `October 18, 2021, 6:40:35 PM` (corresponding time of the Android system).

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

**Screenshot of problem:** Please see [screen recording](https://photos.app.goo.gl/ezDRJpmgUyzdFhoS9)

**Additional information:**

**Comment by dshokouhi** [comment]
The android app only sends state updates when the state of the entity has actually changed. In this case (hard to tell) it appears that the state has not changed? If so then this is working as designed.

**Comment by dshokouhi** [comment]
@jeepotvin the logic that I described up above has never changed since this sensor was introduced.  All sensors follow the same logic.

>This should have triggered the Last Notification sensor at that exact moment since the sensor have a filter to only allow that specific app.

As long as the state has not changed then we will not send a state update. Looking at the video the state of the sensor stayed the same the entire time right? 

Given that this is the only app in the allow list, if it always sends the same text then I am not sure how it was ever working unless of course there was a dropped off notification or something else that would cause the state to change in between notifications.

**Comment by jeepotvin** [comment]
Thanks for the advice. I now have Tasker posting a reset notification at a given time and added it to the Allow list. 

I would have prefer an automation to reset the state but I totally get it's an edge case being that the original notification always has the same text.

This was really helpful Daniel. I've been wonderingly about that problem for a while now. Closing the issue.
