### ISSUE TITLE
Wear OS support for Tiles with lights and switches

### ISSUE THREAD

**Issue by hkusulja** [home-assistant/android#1802]
**Is your feature request related to a problem? 

**Describe the solution you'd like**

"Tile" should be registered within the app for smartwatch, so we can faster trigger the "light on" or "switch on"
https://developer.android.com/codelabs/wear-tiles

**Describe alternatives you've considered, if any**

**Additional context**

Existing Home Assistant Android application has Wear OS support (in beta) and is working with scenes etc.

**Comment by leroyboerefijn** [comment]
@dshokouhi, this one can be closed :)
