### ISSUE TITLE
WearOS Beta client immadiately closes

### ISSUE THREAD

**Issue by chertvl** [home-assistant/android#1804]
**Home Assistant Android version: beta-1534-9f3f552-full**

**Android version: Android 11**

**Phone model: Galaxy S10**

**Home Assistant version: 2021.10.6**

**Last working Home Assistant release (if known):**

**Description of problem: I can not launch WearOS client, it immadiatelly closes in 3-4 sec, what am I doing wrong? Maybe are there minimum requirements for it work?  Tried to lauch with Galaxy Watch 4 (WearOS 3.0)**

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem: Attached a link to video below **

**Additional information: https://drive.google.com/file/d/1t_sCgYACZCVN94dO6w2FpV_vFeJHG8KF/view?usp=drivesdk **

**Comment by dshokouhi** [comment]
This was fixed in #1739 actually
