### ISSUE TITLE
Option to reset steps counter daily

### ISSUE THREAD

**Issue by atkulp** [home-assistant/android#1811]
**Is your feature request related to a problem? Please describe.**

When I view my steps from data in the Android app (on my Pixel 5) it shows an ever-growing number.  This number is very useful for counting daily activity

**Describe the solution you'd like**

It's behaving as intended, but it would be much more useful if it reset to show daily steps instead (or as a separate value).

**Describe alternatives you've considered, if any**

I'm not sure how I could make this work other than setting the phone to restart every night.  I suppose that's an option, but doesn't seem ideal.

**Additional context**

No more details to add, just not that helpful to see 100,000 steps in the visualization when it's counting an unknown number of days!

**Comment by dshokouhi** [comment]
You can actually use an existing HA integration to do this for you. The app reports the data from the Android API which in this case resets on device restart. Check the Android section at the link below for how to set it up

https://companion.home-assistant.io/docs/core/sensors#pedometer-sensors

**Comment by atkulp** [comment]
Thanks!  I did some searching but didn't notice that.  I understand that it could help with resetting the offset each day, but is it ok with it zeroing after device reboot?

**Comment by dshokouhi** [comment]
I believe it accumulates daily
