### ISSUE TITLE
Android 12 brings back High Accuracy mode notification lingers issue

### ISSUE THREAD

**Issue by crowedavid** [home-assistant/android#1813]
**Home Assistant Android version:**
2021.10.0-full

**Android version:**
12

**Phone model:**
Pixel 5

**Home Assistant version:**
core-2021.9.7

**Last working Home Assistant release (if known):**

**Description of problem:**
After upgrading to Android 12 the symptoms of issue #1509 have returned.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**
I didn't change any other settings in the app or Home Assistant itself - just upgraded to Android 12 yesterday.  I use BT devices to trigger High Accuracy mode and the notification will remain after the first connection and then go away after the second. This pattern has been consistently repeatable so far but only 24+ hours since I upgraded.

**Comment by dshokouhi** [comment]
Can you grab the logs next time this happens so we can see where the failure is this time?

**Comment by crowedavid** [comment]
will do.

**Comment by crowedavid** [comment]
two log files captured:
sequence for first: 

- BT device in High Accuracy trigger list connects
- High Accuracy notification appears
- media play for a bit and stop
- disconnect BT device
- High Accuracy notification stays
- enter HA app and grab log


[homeassistant_companion_log_9-21-2021_16-54-27.txt](https://github.com/home-assistant/android/files/7393463/homeassistant_companion_log_9-21-2021_16-54-27.txt)

second sequence a minute or so after first:

- same BT device in High Accuracy trigger list connects
- High Accuracy notification still there
- media play for a bit and stop
- disconnect BT device
- High Accuracy notification goes away
- enter HA app and grab log


[homeassistant_companion_log_9-21-2021_16-56-49.txt](https://github.com/home-assistant/android/files/7393467/homeassistant_companion_log_9-21-2021_16-56-49.txt)

i hope this helps - happy to gather more information.

**Comment by crowedavid** [comment]
it doesn't appear to change anything - same symptoms.

**Comment by chriss158** [comment]
Now that my Pixel 6 arrived, i suffered from this issue too. Should be fixed with #1854

**Comment by crowedavid** [comment]
sorry for commenting on a closed issue - if you want a new issue opened for this i'll be happy to.

not being sure when a new release was going to be pushed out i joined the beta in the play store and updated to beta-1626-edc4142.

while this update acts better it doesn't fully fix the issue.  the High Accuracy mode notification now lingers until i actually open the Home Assistant app.  this appears to be consistent in short testing today.

**Comment by chriss158** [comment]
Weird. Since this commit i have no problems at all. Just to make sure: The app is allowed to run in background?  maybe for more you need to open a new issue with new logs. Then i will have a closer look at this.
