### ISSUE TITLE
App does not work when client cert is required

### ISSUE THREAD

**Issue by tasmin** [home-assistant/android#1819]
**Is your feature request related to a problem? Please describe.**

Cannot lock down access on public IP with cloudflare setting that requires a client cert. The app displayes the cloudflare error 1020 Access Denied because "This website is using a security service to protect itself from online attacks."

**Describe the solution you'd like**

When the app opens the domain name proxied by cloudflare with client cert required, the app should prompt me to select one of the available certs in the OS, like a browser does, and use that to establish the connection.

**Describe alternatives you've considered, if any**

Alternative is not to use a client cert, but then my home system is accessible by everyone on the internet, and I find that scary.

**Additional context**

**Comment by dshokouhi** [comment]
Duplicate of #214 #442 #127 #1244
