### ISSUE TITLE
 ERROR (MainThread) [homeassistant.components.http.data_validator] Data does not match schema: extra keys not allowed @ data['device_id']

### ISSUE THREAD

**Issue by jiumoshou** [home-assistant/android#1828]
**Home Assistant Android version:2021.10.0-minimal

**Android version:11

**Phone model:OnePlus9

**Home Assistant version:0.103.6

**Last working Home Assistant release (if known):**

**Description of problem:**

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
 ERROR (MainThread) [homeassistant.components.http.data_validator] Data does not match schema: extra keys not allowed @ data['device_id']

```

```

**Screenshot of problem:**
![QQ截图20211024005820](https://user-images.githubusercontent.com/49447989/138592422-d4e78069-9866-4896-946e-80deb4b5306b.png)

**Additional information:**

**Comment by foice** [comment]
I have the same `[homeassistant.components.http.data_validator] Data does not match schema: extra keys not allowed @ data['device_id']` with HA  0.96.5.

```
arch | armv7l
-- | --
dev | false
docker | false
hassio | false
os_name | Linux
python_version | 3.5.3
timezone | Europe/Rome
version | 0.96.5
virtualenv | true
```

**Comment by dshokouhi** [comment]
> I have the same `[homeassistant.components.http.data_validator] Data does not match schema: extra keys not allowed @ data['device_id']` with HA  0.96.5.
> 
> ```
> arch | armv7l
> -- | --
> dev | false
> docker | false
> hassio | false
> os_name | Linux
> python_version | 3.5.3
> timezone | Europe/Rome
> version | 0.96.5
> virtualenv | true
> ```

You need to update HA or stick to a lower app version.
