### ISSUE TITLE
Any location update not working but geocoded location works

### ISSUE THREAD

**Issue by Zocker1999NET** [home-assistant/android#1833]
**Home Assistant Android version:** 2021.10.0-full

**Android version:** 11 (Lineage OS 18.1 for microG)

**Phone model:** OnePlus 3

**Home Assistant version:** 2021.10.6 (did not work on older versions too)

**Last working Home Assistant release (if known):** *no known*

**Description of problem:**

Home-Assistant for Android cannot access the GPS location on my phone while other apps can. In logcat, only the indicator "Received location update" pops up, but nothing further. Surrounding logs of the system confirm, that a correct location was send to the app.
But the Home-Assistant app can access the geocoded location and send it to the server as expected. The location was correct.

It seems that the app sees any reason to not further process the location but does not say anything about (if I understand the code correctly, if the accurency was not sufficient, this should be logged as well).

https://github.com/home-assistant/android/blob/ff20e4502b0f202d13323d4211c2c475c1d62bc8/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L445-L471

Any ideas on how to fix or further investige? I can post more logs if I know what would be helpful.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

If filtering for "LocBroadcastReceiver" (`adb logcat | grep -F LocBroadcastReceiver`), only "Received location update" pops up, not any other examples of the troubleshoot page:

```
10-25 11:07:15.882 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:07:15.889 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:08:15.852 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:08:15.865 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:08:15.880 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:08:15.888 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:08:15.895 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:09:15.850 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:09:15.856 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:09:15.869 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:09:15.874 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:09:15.884 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:11:13.131 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:11:13.154 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:11:13.166 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:11:13.177 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:14:16.652 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:14:16.665 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:14:16.681 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:14:16.693 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:14:16.696 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:16:11.124 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:16:11.136 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:16:11.173 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:16:11.226 22725 22725 D LocBroadcastReceiver: Received location update.
10-25 11:16:11.231 22725 22725 D LocBroadcastReceiver: Received location update.
```

Surrounding log messages indicate that the correct location was sent to the app (replaced coords with "48.XXXXXX" / "8.XXXXXX" for privacy reasons, X stands for any number; coordinates where different in lower digits each time as expected):

```
10-25 11:17:15.862  4802 24268 D GmsLocRequestHelper: sending Location: Location[network 48.XXXXXX,8.XXXXXX hAcc=792 et=+2h20m46s596ms vAcc=??? sAcc=??? bAcc=??? {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=GSM, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService, OTHER_BACKEND_RESULTS=[Location[network 48.XXXXXX,8.XXXXXX hAcc=54 et=+2h19m47s506ms vAcc=??? sAcc=??? bAcc=??? {Bundle[{SERVICE_BACKEND_PROVIDER=ichnaea, SERVICE_BACKEND_COMPONENT=org.microg.nlp.backend.ichnaea/.BackendService}]}]]}]}] to io.homeassistant.companion.android
10-25 11:17:15.867 22725 22725 D LocBroadcastReceiver: Received location update.
```

```
10-25 11:16:11.171  4802  4956 D GmsLocRequestHelper: sending Location: Location[network 48.XXXXXX,8.XXXXXX hAcc=792 et=+2h19m4
1s859ms vAcc=??? sAcc=??? bAcc=??? {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=GSM, SERVICE_BACKEND_COMPONENT=org.fitchfam
ily.android.gsmlocation/.GsmService, OTHER_BACKEND_RESULTS=[Location[network 48.XXXXXX,8.XXXXXX hAcc=54 et=+2h17m47s469ms vAcc=
??? sAcc=??? bAcc=??? {Bundle[{SERVICE_BACKEND_PROVIDER=ichnaea, SERVICE_BACKEND_COMPONENT=org.microg.nlp.backend.ichnaea/.Back
endService}]}]]}]}] to io.homeassistant.companion.android                                                                      
10-25 11:16:11.173 22725 22725 D LocBroadcastReceiver: Received location update.
```

```
10-25 11:16:11.128  4802  4956 D GmsLocRequestHelper: sending Location: Location[network 48.XXXXXX,8.XXXXXX hAcc=792 et=+2h19m4
1s859ms vAcc=??? sAcc=??? bAcc=??? {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=GSM, SERVICE_BACKEND_COMPONENT=org.fitchfam
ily.android.gsmlocation/.GsmService, OTHER_BACKEND_RESULTS=[Location[network 48.XXXXXX,8.XXXXXX hAcc=54 et=+2h17m47s469ms vAcc=
??? sAcc=??? bAcc=??? {Bundle[{SERVICE_BACKEND_PROVIDER=ichnaea, SERVICE_BACKEND_COMPONENT=org.microg.nlp.backend.ichnaea/.Back
endService}]}]]}]}] to io.homeassistant.companion.android                                                                      
10-25 11:16:11.131  3579  3579 D KeyguardViewMediator: keyguardGone                                                            
10-25 11:16:11.136 22725 22725 D LocBroadcastReceiver: Received location update.
```

**Screenshot of problem:**

*no good screenshot available*

**Additional information:**

I have installed a non-Googled Android flavor, [Lineage OS 18.1 for microG](https://lineage.microg.org/). I know that this version is not fully supported, however I think this is not the problem here because:
- I have found other users of Lineage OS for microG where Home Assistant does work as expected.
- Home-Assistant is the only app to have problems accessing the location on my phone, other working examples are "DB Navigator", "Öffi", "OsmAnd+" and "StreetComplete".
- Due to microG, other apps requiring Google Play Services are also working, e.g. "Corona-Warn-App", "Outlook", "Spotify". These apps have access to push notifications using Firebase and access to the location as well.
- The full Home-Assistant for Android build can even access the geocoded location on my phone and notifications show up in real time using Firebase.

**Comment by Zocker1999NET** [comment]
Okay. I accept, that this is not an issue per se because this app requires proper Google Play Services to work and I only have a replacement installed. Installing Google Maps does not help and Maps itself "cannot" access my location which proves that this is not a Home-Assistant specific issue.

However, would it not be feasible for Home-Assistant to change the implementation to be able to access the location not requiring Google Play Services? This would make Home-Assistant an even more privacy-friendly smart home solution, as it is possible as well. And it will increase support for other non-Google Android's from manufacturers like Huawei and Purism. For now I see no reason why this should be bad. Would you accept a PR for that or even add it as a "wishlist item"?

**Comment by dshokouhi** [comment]
> However, would it not be feasible for Home-Assistant to change the implementation to be able to access the location not requiring Google Play Services?

we already have a request in place #1511 



> Would you accept a PR for that or even add it as a "wishlist item"?

PR sure but don't expect volunteers to work on things they don't wish to work on. Most of us have google play services and google makes life much easier on developers by providing such APIs to use. You are more than welcome to submit a PR.
