### ISSUE TITLE
Actionable notifications not actioning on Android 12

### ISSUE THREAD

**Issue by afxefx** [home-assistant/android#1839]
**Home Assistant Android version:**
2021.10.6
**Android version:**
12 (final not beta)
**Phone model:**
Pixel 4 XL
**Home Assistant version:**
beta-1576-e1cc6c8-full
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
When clicking action button to open lovelace view, notification dismisses but companion app doesn't open.  logcat shows following error:

`NotificationService: Indirect notification activity start (trampoline) from io.homeassistant.companion.android blocked`

Relevant links:

https://developer.android.com/about/versions/12/behavior-changes-12#notification-trampolines
https://proandroiddev.com/notification-trampoline-restrictions-android12-7d2a8b15bbe2

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by GurtKnev** [comment]
Was also having this problem on Android 12 on mij pixel!
Tried setting the permission to display home assistant in front of other apps and everything is working now!

![image](https://user-images.githubusercontent.com/67710133/141739452-5415264c-6240-44c3-b6ff-86743f3b9645.png)

**Comment by dshokouhi** [comment]
I still haven't found a good solution for this to avoid asking all users to grant this permission. The problem with the trampoline fix mentioned in OP links is that we have extra logic than what is needed there. Not only can users launch the app but they can also launch a different application. We also have additional logic in place for properly cancelling grouped notifications, as HA allows the user to fully customize the notification experience we need to make sure we have no orphaned groups.
