### ISSUE TITLE
Android 11: Power Menu actions not executed, long press empty

### ISSUE THREAD

**Issue by soxhi8** [home-assistant/android#1841]
**Home Assistant Android version:**
2021.10.0-minimal (F-Droid)
**Android version:**
LineageOS MicroG 18.1-20211021 (Android 11)
**Phone model:**
OnePlus 3
**Home Assistant version:**
core-2021.10.6, Home Assistant Container
**Last working Home Assistant release (if known):**
/
**Description of problem:**
When executing actions on the Android 11 power  menu integration of Home Assistant, nothing happens. Presses are confirmed by the device vibrating.
When long-pressing an entity, a black and empty pop-up appears. Clicking the link on the top right opens Home Assistant and loads the normal landing page.
I also tested the Google Play-version of the companion app, it behaved the same.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:*
[homeassistant_companion_log_9-27-2021_13-17-58.txt](https://github.com/home-assistant/android/files/7425742/homeassistant_companion_log_9-27-2021_13-17-58.txt)
*

**Comment by dshokouhi** [comment]
Closing due to lack of response
