### ISSUE TITLE
ChromeOS - Change Volume Level

### ISSUE THREAD

**Issue by PoshAlchemist** [home-assistant/android#1863]
I'm trying to change the volume of my chromebook using Notifications with the "command_volume_level" Message as per the example here :
https://companion.home-assistant.io/docs/notifications/notification-commands#volume-level
I've tried all the streams (alarm, music, notification and ring) and none of them work.
I believe my yaml is ok as if i switch the entity to my pixel 4XL it works ok.  Here is the yaml below anyway, just incase:
`service: notify.mobile_app_chromebookName
data: 
  message: "command_volume_level"
  title: 0
  data:
    channel: "music_stream"
`
I'm assuming that the audio stream used by chromebook isnt one of the valid audio streams listed in the documentation?
I can confirm connection is ok as normal notification work.  I have also tested action notification which worked.
When i tested the TTS notification, while I do hear the output, the channel property seems like its not working as i can put anything in here and it still works.  If i use any of the xxxx_stream_max in this channel, it does NOT set the volume to max either.

As far as I can tell i have granted all permissions and have gone into the app settings and confirmed alll permissions are granted. However when i click on show all i dont see any specific permssions related to audio.

Im new to using chromebook and so im not ruling out i have done something wrong .  Im also not sure if chromebook is supported or not.
I've tried googling the issue but i dont seem to get many hits, i've also tried searching open issues here and dont see anything related to this.

I'm not sure how to debug this further to provide more useful information to help troubleshoot.  
If this isnt supported i would appreciate any pointers where i can look to resolve this myself as im comfortable digging around with code, and can share any findings i may come accross. 

Thanks
Steve

**Comment by PoshAlchemist** [comment]
ah ok make sense ... is there anyway i can test \ confirm that?

**Comment by dshokouhi** [comment]
Can you look at hte app configuration > Logs section? Maybe something is of use there. I do not have a chromebook so I cant check these things.

Google just made it so apps can run I dont htink they said anything about all the android API's :)

**Comment by PoshAlchemist** [comment]
Ok thanks, i will take a look, as you say i wont hold my breathe.  As i say im new to using chromebook myself, so still trying to figure it all out.   I think you can also change the volume using google assistant, so maybe i can try and come at it from that angle instead of using the app.  As is always the case with these things, something that i though would be as simple as install the app ... set up a simple little automation, turns out to be more complicated than first though haha

**Comment by dshokouhi** [comment]
i woudl definitely check the logs under app configuration as we do print when we receive and process a command so maybe there is an error there? or quite simply there is no API on the chromebook to do it

**Comment by PoshAlchemist** [comment]
ok so checked the logs and i can see it in there ... no errors though:

11-01 18:29:58.814  7155  8460 D MessagingService: From: 331041709873
11-01 18:29:58.814  7155  8460 D MessagingService: Message data payload: {title=20, channel=music_stream, message=command_volume_level}
11-01 18:29:58.816  7155  8460 D MessagingService: Processing device command

I just did a quick google to see if it does have an api and from the google dev site here:
https://developers.google.com/admin-sdk/directory/reference/rest/v1/customer.devices.chromeos.commands?hl=en

There does appear to be an api but only for kiost and managed guest sessions - for some reason.  Seems strange.
![image](https://user-images.githubusercontent.com/66186230/139723555-c4c8be60-5af9-4628-b47c-0613045e50a9.png)

There must be something under the hood that allows you to change the volume though as i read you can use google assistant to change the volume.  Im not tested that yet though, so maybe i should try that and see if that works

**Comment by dshokouhi** [comment]
yea this is probably going to be out of scope for the android app

**Comment by PoshAlchemist** [comment]
ok no worries, thanks for the pointers. 
I've tested and google assistant works to change the volume.
So i thought a simple TTS service call would work to change the volume, alas the chromebook doesnt appear as a device to send TTS too.  Oh well.
Anyway thats not your issue :P 
Might as well close this Issue, and home that chrome OS improves further down the line :)
