### ISSUE TITLE
Home Assistant stuck "Loading data" until Connectivity toggled on devices without gms

### ISSUE THREAD

**Issue by jannis3005** [home-assistant/android#1874]
**Home Assistant Android version:** 2021-10-0-full

**Android version:** 10

**Phone model:** HUAWEI Mate 40 Pro & HUAWEI MatePad Pro

**Home Assistant version:** 2021.11.0

**Last working Home Assistant release (if known):** 2021.10.6

**Description of problem:**

I've noticed yesterday that when I launch the Homeassistant App on my Phone or Tablet, it gets stuck at "Loading data" - after applying the theme - even though it had been working fine so far and I didn't update the App. It gets stuck when connected to wifi, but when I turn the wifi off while it is stuck it finishes loading. But when wifi is turned off, it still gets stuck, and when I turn wifi on while it's stuck, it finished loading. I did not do an update to the App though. I do still get Notifications though, even while the App is stuck. Logging in via the Browser works fine on all devices. Once I'm into the App though, everything works fine until i close it completely.

I've tried reproducing it on two other phones, on a HUAWEI P40 Pro (also without gms and with microg installed for notifications only) the same weird behaviour can be observed, but on a HUAWEI Mate 20 Pro with gms, this problem does not occur.

I did however update to 2021.11.0 yesterday. Rolling back to 2021.10.7 though, the problem still persists. Going back to 2021.10.6, the issue is resolved. Not quite sure if this is an issue with home assistant or the companion app.

I've attached two log files, one launching with WIFI turned on and then toggled off while stuck and one the other way round.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):** 

```
No Stacktrace
```

**Screenshot of problem:**

![Screenshot_20211104_183457_io homeassistant companion android](https://user-images.githubusercontent.com/38779449/140390359-ce7129ab-b9c6-41ad-8a03-2041114f6675.jpg)

**Additional information:**
[external-then-internal.txt](https://github.com/home-assistant/android/files/7477005/external-then-internal.txt)
[internal-then-external.txt](https://github.com/home-assistant/android/files/7477006/internal-then-external.txt)

**Comment by dshokouhi** [comment]
If changing the HA version has an impact on the app then that suggests the issue is not with the app. Did you check the behavior in chrome for Android? Also it takes 10 seconds for the app to realize if we should switch URL in case of failure

**Comment by jannis3005** [comment]
I've checked using brave browser on android - it works fine. I've left it loading for about 30 minutes and nothing happened.
Update: It just returned to being stuck even on 2021.10.6 where it was working fine before. It seems to be the case that it works while HA is starting and stops working once it finished starting or something like that. weird.

**Comment by dshokouhi** [comment]
brave browser is not good comparison, please check in chrome as that is what WebView is based off.

**Comment by jannis3005** [comment]
cannot install chrome on my phone - never could, it is missing some required libraries (com.google.android.trichromelibrary) - so I can't check that

**Comment by dshokouhi** [comment]
Also your logs are incomplete as I do not see the webview package being printed to the log to determine if you are using an acceptable webview package.

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L560


This error the app cannot solve and may be part of your problem, we cant fix failed to connect errors here.

`11-04 18:32:31.624 31809 31809 E WebViewPresenterImpl: Issue getting version/notifying of security issue.
11-04 18:32:31.624 31809 31809 E WebViewPresenterImpl: io.homeassistant.companion.android.common.data.integration.IntegrationException: java.net.ConnectException: Failed to connect to hooks.nabu.casa/35.169.63.195:443`



> cannot install chrome on my phone - never could, it is missing some required libraries (com.google.android.trichromelibrary) - so I can't check that

then that will definitely cause issues with webview, sounds like a custom ROM issue.  We only compare against chrome.

**Comment by jannis3005** [comment]
This looks to me like the webviewor the homeassistant app (not sure) cannot connect to hooks.nabu.casa. but I guess then I'm in the wrong place here, but thanks anyways :)

**Comment by dfsx1** [comment]
> This looks to me like the webviewor the homeassistant app (not sure) cannot connect to hooks.nabu.casa. but I guess then I'm in the wrong place here, but thanks anyways :)

I have the same issue after upgrading to HA-core 2021.11.0
My Android 10 tablet is firewalled and does not have internet.
It's only allowed local connections to my local HA-core docker instance.

Every time I start the Android companion app, it's stuck on "Loading data" forever.
Until I restart the HA-core docker container.
Then it says "Lost connection, reconnecting..." and starts without problem after the HA-core container is running again.

Beta-1626-edc4142 release also did not work for me.
Why did you close this issue, it's not fixed?

**Comment by dshokouhi** [comment]
> > This looks to me like the webviewor the homeassistant app (not sure) cannot connect to hooks.nabu.casa. but I guess then I'm in the wrong place here, but thanks anyways :)
> 
> I have the same issue after upgrading to HA-core 2021.11.0 My Android 10 tablet is firewalled and does not have internet. It's only allowed local connections to my local HA-core docker instance.
> 
> Every time I start the Android companion app, it's stuck on "Loading data" forever. Until I restart the HA-core docker container. Then it says "Lost connection, reconnecting..." and starts without problem after the HA-core container is running again.
> 
> Beta-1626-edc4142 release also did not work for me. Why did you close this issue, it's not fixed?

The loading data screen is not part of the app it's from the HA frontend which is why the issue closed

**Comment by dfsx1** [comment]
> The loading data screen is not part of the app it's from the HA frontend which is why the issue closed

You are correct, just checked and I see the same issue when I connect with Chrome from my tablet.
I'll try the upgrade to HA-core 2021.11.1 or open a issue in the home-assistant/core repo if that also doesn't work.
Thank you!
