### ISSUE TITLE
Can't swipe away grouped notifications

### ISSUE THREAD

**Issue by hansharhoff** [home-assistant/android#1877]
**Home Assistant Android version:**
 2021.10.0-full 
**Android version:**
 Android version 11 
 Oxygen os 11.0.8.8 in11ba 
**Phone model:**
One Plus 8 pro
 In2023
**Home Assistant version:**
core-2021.11.0

**Last working Home Assistant release (if known):**
None that I know of.
**Description of problem:**
When more than a couple of notifications are in the notification drawer they are made into a notification group.
I expect to be able to swipe these notifications away together as one.
This works on one phone I have, but on the other phone I have it refuses to swipe away in the same way some notifications from "running" applications cannot be swiped away.

Duplicate of this inactive bug:
https://github.com/home-assistant/android/issues/943 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/1460570/140463825-6c50fcbd-4249-43a1-b4ee-0b24e2f3a567.png)
![image](https://user-images.githubusercontent.com/1460570/140463849-49a0e5b5-ce9b-4aa5-ae99-e4767e140e95.png)

**Additional information:**

**Comment by dshokouhi** [comment]
I think this might be android 11 behavior, as far as I know there isnt anything in the app that prevents this. The device you said that is working I assume is not on android 11 or higher right?

**Comment by hansharhoff** [comment]
The device that works is also on Android 11 and is a OnePlus 6t.

On both phones all other notification groups can be swiped away.

**Comment by dshokouhi** [comment]
can you share the YAML you used to reproduce this issue? on my Pixel 6 pro I can send 4 notifications back to back that creates the autogenerated group and it can swipe away just fine.  Are you able to reliably reproduce this? The fact that it works on one device but not another suggests an issue with the device.

Here is the yaml I used:

Sent 4 times creates the group
```
service: notify.mobile_app_dannys_pixel_6_pro
data:
  message: test
```

I even tested by creating my own group and sent this one 6 times and it worked

```
service: notify.mobile_app_dannys_pixel_6_pro
data:
  message: test
  data:
    group: test
```

**Comment by hansharhoff** [comment]
Interesting, I am able to swipe away messages as a group if generated by
this yaml:

service: notify.mobile_app_iosplus8
data:
  message: test

While notifications generated by this and similar yaml will be (reliably)
grouped and the groups cannot be swiped away on one phone but can be swiped
away on the other.

service: notify.notify
data:
  title: Dryer has finished!
  message: >-
    The power consumption of the dryer is less than 100 which indicates
    completion.

**Comment by dshokouhi** [comment]
Can you get us the on device logs when you reproduce this? Make sure the logs capture everything including each notification so we can see what's happening.

**Comment by dshokouhi** [comment]
Closing due to lack of response

**Comment by SgtBatten** [comment]
I am struggling with this. 

I have two automations that trigger multiple notifications per day based on motion alerts from cameras. One group I can swipe away, the other I can only swipe away individual events after expanding the group.

**Comment by Hooolm** [comment]
Bump. Have the same issue!

**Comment by dshokouhi** [comment]
this issue was closed almost 1 year ago, if you are still experiencing the same issue please open a new issue and fill out the issue template completely with steps to reproduce.  Also check to see its not the same as #2204
