### ISSUE TITLE
Cannot update when running in background

### ISSUE THREAD

**Issue by steven52880** [home-assistant/android#1879]
**Home Assistant Android version:**
2021.10.0-minimal
**Android version:**
Android 9
**Phone model:**
Redmi Note 8 Pro
**Home Assistant version:**
2021.10.6
**Description of problem:**

The server is running in http and a cdn with https before. The app works well.

 However, when I set up HTTPS on hass server and configured a new SSL certificate, the client can only send information to the server when running in the foreground. When the client switches to the background, it cannot update the sensor.

It seems like something wrong with the SSL certificate.

**Traceback**

[homeassistant_companion_log_10-7-2021_0-24-26.txt](https://github.com/home-assistant/android/files/7490863/homeassistant_companion_log_10-7-2021_0-24-26.txt)

**Comment by dshokouhi** [comment]
Looks like the CA is not verified or missing, you'll need to correct that on your own as the app does not solve SSL errors

https://developer.android.com/training/articles/security-ssl#CommonProblems

Regarding issue in the foreground, make sure the app has access to run in the background. There is a section in App Configuration to check this.

**Comment by dshokouhi** [comment]
Closing as we cannot solve the SSL error, if you check closed issues you may find a solution that works for you as we had some others with this issue too.

**Comment by steven52880** [comment]
The web pages can open normally in chrome. And there is no problem when the program runs in the foreground.
So I guess there should be no problem with SSL.

The app can normally send data in the background before. I haven't modified the settings of the client, and I have given enough background operation permissions. I only configured the server. 

This error only occurs when I close the app.

I wonder if different request components are used when the program runs in the background
