### ISSUE TITLE
Wear OS - Manually add entities to be shown in the wear os app

### ISSUE THREAD

**Issue by HunterX86** [home-assistant/android#1881]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add the entities you want to be shown in the wear os app

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
#1875 will allow you to select favorites that are pinned to the top. I think that will satisfy this request

**Comment by HunterX86** [comment]
#1875 yes and also that you can categorize them.

**Comment by dshokouhi** [comment]
categorize them?

**Comment by HunterX86** [comment]
Lights, scripts, switches, etc.

**Comment by dshokouhi** [comment]
they are already listed like that, am I missing anything else? :)

**Comment by HunterX86** [comment]
No, your right
