### ISSUE TITLE
Wear OS - Ability to re-order categories

### ISSUE THREAD

**Issue by brewston** [home-assistant/android#1885]
Is your feature request related to a problem? Please describe.
Ease of use.

Describe the solution you'd like :

In settings, the ability to re-order categories. eg be able to place Scenes first, Switches second etc

Describe alternatives you've considered, if any : currently the categories are alphabetical only.

Additional context

**Comment by dshokouhi** [comment]
Re-order and maybe even allow to hide certain categories too?

**Comment by brewston** [comment]
Yes, I think being able to hide catergories would be good too.

**Comment by dshokouhi** [comment]
So we had some discussion here and we think a better user experience would be move to the loading of all entities to another screen. What do you think about applying this request to the favorites section? That means we would split the favorites by the category which you can then move around with this request. This would allow for us to load those entities faster so the initial launch experience is better on the home screen.  To check out the new favorites section you would need to be on the latest beta which is not in the play store yet.

**Comment by brewston** [comment]
So will favorites have sub-sections too ? I was expecting just a short list of entities. I think I'll wait and see the next beta this weekend, if that's OK ? Thanks.

**Comment by leroyboerefijn** [comment]
@dshokouhi Any ideas on the best flow for this in settings? On the phone I would propose a drag-drop list, but on wear I'm not sure if that works well. We could also do something similar to the flow for the shortcuts Tile, but it might be a bit limited for reordering categories...

**Comment by dshokouhi** [comment]
> So will favorites have sub-sections too ? I was expecting just a short list of entities. I think I'll wait and see the next beta this weekend, if that's OK ? Thanks.

for now its one section but yes we can split it up to be sub-sections.



> Any ideas on the best flow for this in settings? On the phone I would propose a drag-drop list, but on wear I'm not sure if that works well. We could also do something similar to the flow for the shortcuts Tile, but it might be a bit limited for reordering categories...

Since we are defining the categories shown I was thinking something like: first category, second category etc... lol

**Comment by dshokouhi** [comment]
The loading of all categories has been moved to another screen now, re-ordering favorites will be possible in #1963 closing this request as the home screen has changed.
