### ISSUE TITLE
Password manager not available at login

### ISSUE THREAD

**Issue by gotson** [home-assistant/android#189]
**Home Assistant Android version:** 1.3.1

**Android version:** 9

**Phone model:** one plus 6t, Samsung galaxy tab s5e

**Home Assistant version:** 0.103.3

**Last working Home Assistant release (if known):** 

**Description of problem:** the password manager of android (bitwarden in my case) is not available at login

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by tristandegroof** [comment]
I can confirm this is still an issue in 3.0.2, as I had to reset the app after updating for some reason. Since passwords etc have become much more complicated, password manager support is important, I think :-)

**Comment by dshokouhi** [comment]
Should've caught this earlier, duplicate of: https://github.com/home-assistant/frontend/issues/3133
