### ISSUE TITLE
Add Wear OS complications

### ISSUE THREAD

**Issue by leroyboerefijn** [home-assistant/android#1898]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add support for watchface complications. I'm thinking of the following:

- Entity state
- Entity attribute value
- Template value
- Template text

**Describe alternatives you've considered, if any**
N.a.

**Additional context**

**Comment by barrymossel** [comment]
And sensor data please.

**Comment by barrymossel** [comment]
More information here: https://developer.android.com/training/wearables/watch-faces/adding-complications

**Comment by Vedeneb** [comment]
Are there plans on implementing this feature? If there isn't anybody working on it already, I might eventually have a look into this myself, I have developed a Wear OS with complication support before, however it was written in Java (never started to like Kotlin...) and I'm not familiar with the HA code base at all so it would definitely be a challenge :D

**Comment by leroyboerefijn** [comment]
@Vedeneb I have it on my list to start working on, but cannot give you any guarantees on timing ;)

If you feel like contributing, then please feel free to work on it! I think the entity state widget will give an example of the type of information we could set in a complication. Also, we're always happy to support over on the discord :)

**Comment by sepodele** [comment]
This would be awesome. Here's a link to 'Exposing your Data to Complications': https://developer.android.com/codelabs/data-sources#0

**Comment by marazmarci** [comment]
I think it would be useful to be able to update the complication on demand, eg. with a notification command sent to the phone, that will forward it to the Wear OS app. But I admit that implementing a periodically updating complication that shows an entity's state would be simpler based on the already implemented Tile's code.

**Comment by jpelgrom** [comment]
> I think it would be useful to be able to update the complication on demand, eg. with a notification command sent to the phone, that will forward it to the Wear OS app. 

If this is implemented, it should probably [match the notification command for Apple Watch users](https://companion.home-assistant.io/docs/apple-watch/complications#manual-updates) to make it easier to handle multiple devices / blueprints.

**Comment by leroyboerefijn** [comment]
@marazmarci @jpelgrom I suggest that a new feature request is made for that once the complication PR is merged

**Comment by dshokouhi** [comment]
Now that initial support has been added should we close this request or is there more to be done still?

**Comment by leroyboerefijn** [comment]
My original plan was to also add attribute support instead of just state support. But maybe it makes sense to just close this indeed

**Comment by dshokouhi** [comment]
ok lets close this one and get new requests created for anything else we want to add.
