### ISSUE TITLE
Show power in energy panel

### ISSUE THREAD

**Issue by dw0rak** [home-assistant/android#1904]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add possibility of power measured in Watts in energy panel. This entity should be possible to show as a sum of other entities as three phases entities or if someone desires separate devices power. 

**Describe alternatives you've considered, if any**
Provide a template which could generate sum of other entities to use as a card anywhere in HA. 

**Additional context**
Self explanatory

**Comment by dshokouhi** [comment]
Feature requests for home assistant itself are only made in the forums. This repository is for the Android app only.
