### ISSUE TITLE
Wear OS - Wrong icon for light entities in quick setting tiles

### ISSUE THREAD

**Issue by HunterX86** [home-assistant/android#1915]
**Home Assistant Android version:**
beta 1666
**Android version:**

**Phone model:**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem:**
When i have added a light entity to the quick setting tile, the mdi:palette is shown. That's the worng icon.
![palette](https://user-images.githubusercontent.com/1310016/141646717-2c88003d-228e-47f8-b264-9d61d751c9fd.png)

Instead the mdi:lightbulb has to be shown.
![lightbulb](https://user-images.githubusercontent.com/1310016/141646741-2e332472-6798-4f9d-8afd-ee7a75027bfc.png)

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
so the reason for this is because the entity itself did not provide the `icon` the app has to use the same logic that we do on the home screen.

https://github.com/home-assistant/android/blob/master/wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt#L25-L38

**Comment by pandemixxx** [comment]
I can confirm this. Added mdi icons to entities, but wear os app didn't sync, deleted cache, data, reinstalled the app - same outcome.

**Comment by dshokouhi** [comment]
> I can confirm this. Added mdi icons to entities, but wear os app didn't sync, deleted cache, data, reinstalled the app - same outcome.

Please create a new issue with all requested information instead of commenting on an already closed issue. Make sure to provide as much information as possible.
