### ISSUE TITLE
Wear OS Your device isn't compatible with this version.

### ISSUE THREAD

**Issue by Sabbath92** [home-assistant/android#1918]
Fossil Gen 6. 
![20211113_202936](https://user-images.githubusercontent.com/44825970/141667013-7c3e1e3d-6e7f-438b-9e07-6a60053f8050.jpg)

**Comment by dshokouhi** [comment]
Are you on the beta?

**Comment by Sabbath92** [comment]
Yes 👍.

**Comment by dshokouhi** [comment]
Hmm weird might be a play store listing issue, for now you should be able to sideload the APK from the GitHub release tab

**Comment by JBassett** [comment]
What phone, OS version, phone app version are you running?  From the play console we see the device supported. 
![Screenshot_20211114-115458](https://user-images.githubusercontent.com/1051414/141690818-98e69a97-2aa6-4013-8b20-04f6921fc7ce.png)

**Comment by Sabbath92** [comment]
Samsung Galaxy S21 5G. 
Android 11 One UI: 3.1 Build Number: RP1A.200720.012.G991USQS4AUIN.  
beta-1666-1e5534d-full 

It is now showing.  I installed it and when I open it, the HA logo appears and then disappears and it doesn't start.

**Comment by dshokouhi** [comment]
@Sabbath92 that is actually a known issue #1916 Can you first try and install this version, login and then update. We have a bug to fix :)

https://github.com/home-assistant/android/releases/tag/beta-1662-3d909c6

Closing as the original issue resolved
