### ISSUE TITLE
Add lock domain to wear os app please

### ISSUE THREAD

**Issue by blair287** [home-assistant/android#1935]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Add lock domain to wear os app just like lights and switches.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
@leroyboerefijn in order to add the `lock` domain to the tiles we need to read the state to send the proper service call. I don't think tiles currently reads the state right?

**Comment by leroyboerefijn** [comment]
At the moment we don't indeed. But we can check the state in the broadcast receiver if it is a lock type

**Comment by blair287** [comment]
I don't know how to write apps but willing to learn, anything I can do to help let me know please

**Comment by leroyboerefijn** [comment]
@blair287 I'm going to implement the support for lock. Unfortunately I don't have any locks myself, so could you help me?

What is the entity state when the lock is locked and unlocked?

And after implementation, it would be great if you could help me test!

**Comment by leroyboerefijn** [comment]
@blair287 please give PR #1959 a try!

**Comment by blair287** [comment]
> @blair287 please give PR #1959 a try!

Anyway to build the app? I see can install the action apk but I don't want 2 of the app on phone or watch.

**Comment by blair287** [comment]
> @blair287 I'm going to implement the support for lock. Unfortunately I don't have any locks myself, so could you help me?
> 
> What is the entity state when the lock is locked and unlocked?
> 
> And after implementation, it would be great if you could help me test!

The states are locked and unlocked.

**Comment by dshokouhi** [comment]
> > @blair287 please give PR #1959 a try!
> 
> Anyway to build the app? I see can install the action apk but I don't want 2 of the app on phone or watch.

the debug apk installs side by side the production app and its a good way for us to tell when a feature is working. You can install the app and uninstall after the test. It won't impact anything and it has a red icon so easy to distinguish.

**Comment by dshokouhi** [comment]
Closed via #1959

**Comment by blair287** [comment]
> Closed via #1959

Could it be reopened the lock and unlock works but the switch in the app doesn't show any feedback to if its locked or unlocked.

Or shall I open a new issue?

**Comment by leroyboerefijn** [comment]
Ah you're right, forgot to change this line:
https://github.com/home-assistant/android/blob/9fd3164583ad99983510404ae672207ba893db3c/wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt#L45
