### ISSUE TITLE
App Not Properly Fitting Screen

### ISSUE THREAD

**Issue by austinbeam** [home-assistant/android#1947]
**Home Assistant Android version:**
2021.10.0-full
**Android version:**
11 (Kernel 4.19.113-22299651)
**Phone model:**
Galaxy S20+
**Home Assistant version:**
2021.11.4
**Last working Home Assistant release (if known):**
Not sure, don't remember seeing this issue
**Description of problem:**
The app is overflowing underneath the navigation bar rather than being bound to the visible part of the screen. Not sure of a better way to describe this. It is most annoying when attempting to modify or confirm something and the buttons are directly behind the navigation bar. To see them, I have to rotate the screen.

Another symptom is when the keyboard is needed, the app appears to have a large unused area directly above the keyboard (about the same height as the keyboard itself) which makes many input fields unusable. A good example is the file editor addon, which used to work reasonably well on mobile and now is completely unusable.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20211119-235903_Home Assistant](https://user-images.githubusercontent.com/1715252/142716433-a8cd4d22-b698-4c27-b1e8-4fe903451b66.jpg) 
![Screenshot_20211119-235910_Home Assistant](https://user-images.githubusercontent.com/1715252/142716437-3d86a284-abc3-4f4b-9dfd-2660dfa82932.jpg)

![Screenshot_20211120-000126_Home Assistant](https://user-images.githubusercontent.com/1715252/142716438-88f683a9-b4e6-4df1-9fd3-c50f9f7ad500.jpg)
![Screenshot_20211120-000131_Home Assistant](https://user-images.githubusercontent.com/1715252/142716442-4265cab4-800e-488b-8b9b-fa786686973f.jpg)

**Additional information:**
I am not having these issues with any other apps, so it appears to be HA app specific. If I access HA via the browser, I do not have these issues. Only when accessing via the app.

**Comment by dshokouhi** [comment]
Is Android system WebView up to date? 

Did this issue start after an HA update?

Can you provide steps to reproduce the first screenshot?

**Comment by dshokouhi** [comment]
I am unable to reproduce the file editor issue

![Screenshot_20211119-224554.png](https://user-images.githubusercontent.com/1634145/142717471-fcfc6ff7-0cef-4f58-9785-b51ae18fd584.png)

**Comment by austinbeam** [comment]
Android WebView is up to date.

This did start after the update to 2021.11.

Any parameter edit dialog with confirmation buttons at the bottom was showing the same issue.

Maybe it was just late and I didn't think to try it last night, but it seems like a force close and restart of the app resolved this. Appreciate your feedback @dshokouhi , sorry for the unneeded bug report.
