### ISSUE TITLE
Unable to get latest_notification to populate

### ISSUE THREAD

**Issue by Viss** [home-assistant/android#1948]
**Home Assistant Android version:**
2021.10.0-full

**Android version:**
android 11 / oxygenOS 11.0.4.gm21aa  (oneplus 7 pro)

**Home Assistant version:**
core-2021.11.4
supervisor-2021.10.8
I'm running the raspberry pi variant - the downloaded image from the homeassistant site

**Description of problem:**

I've spent the last two days troubleshooting why the latest_notification sensor doesnt exist in my installation. I've reinstalled the companion app, I've gone through every permission and turned it on, I've removed the mobile integration and reinstalled it, I've rebooted homeassistant, I made sure to upgrade to the newest version, and I've spent several hours going through the existing github issues with other folks that had the same problem - nothing I've done seems to get it to come to life.

I get the other sensors - I can sit in developer tools and unplug/replug a usb cable from my phone and watch it update charging vs not charging - just for some reason the one sensor that I'm after isnt in homeassistant at all and I can't figure it out.

Any help would be most welcome!

**Comment by dshokouhi** [comment]
do you have an allow list set for the sensor? The sensor only shows up once we have data to send so if you set it to a certain app you have to wait until that app posts a notification. You also need to make sure you granted the special permission for the app.

**Comment by Viss** [comment]
Ah, sorry, I'd forgotten to mention this - I haven't been able to find the example documentation or configs on where to create an allow list or how to do that at all. I'd be happy to try that next, if you can aim me at a walkthrough or example!

**Comment by Viss** [comment]
also during the installation of the companion app I wasnt ever presented with a dialog of any sort that indicated anything like "give this app permission to read notifications", so I'm not sure where that is

**Comment by dshokouhi** [comment]
https://companion.home-assistant.io/docs/core/sensors#notification-sensors

you only get the permission prompt when you enable the sensor, it does not show up when you install the app.  If you denied the permission then you need to manually grant it.

**Comment by Viss** [comment]
So that documentation provides the guidance on what the allow list is, but doesnt say where to enable it, how to get to it, or shows any example configuration. I can't find where do do the allow list. Is it in home assistant or the companion app?

**Comment by dshokouhi** [comment]
if you read the top of teh page we talk about going to App Configuration > Manage Sensors.  You should take a moment to read everything in the docs if you are unfamiliar with the app.

**Comment by Viss** [comment]
ah ha - perfect, thanks!
i had been control-f'ing around trying to find stuff relating to the actual sensor name and skimmed right over that paragraph.
It might not be a bad call to add some text in that paragraph that folks would gravitate to naturally like "how to enable sensors on android" or something really plain-english.

**Comment by dshokouhi** [comment]
> ah ha - perfect, thanks! i had been control-f'ing around trying to find stuff relating to the actual sensor name and skimmed right over that paragraph. It might not be a bad call to add some text in that paragraph that folks would gravitate to naturally like "how to enable sensors on android" or something really plain-english.

At the bottom of the page there is an Edit button. Feel free to make whichever edits you feel would be more helpful in the future. The docs only get better as users update them alongside their experiences :)

**Comment by Viss** [comment]
oh, good call! I'll go do that
