### ISSUE TITLE
Intent Extras cannot contain `:` and `,`

### ISSUE THREAD

**Issue by mvn23** [home-assistant/android#1949]
**Home Assistant Android version:**
2021.10.0-full

**Android version:**
11 (LineageOS 18.1 unofficial)

**Phone model:**
Samsung Galaxy S9

**Home Assistant version:**
2021.10.6

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**
When using `command_broadcast_intent` with extras in the `group` parameter, there is no support for extras containing `:`, `,` or both.
This becomes a problem when receiving applications expect e.g. a json string in the extras. One example of this is Gadgetbridge, where some features in the latest development version require such extras.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
N/A
```

**Screenshot of problem:**
N/A

**Additional information:**
The lack of support for `:` in extras can easily be fixed by changing https://github.com/home-assistant/android/blob/40e7907dbd742809c043479a081ed8e19dd9efa8/app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt#L517 to something like `val pair = item.split(":", ignoreCase = false, limit = 2)`.
The case of the `,` is another matter entirely and will probably require a more thorough rework of the extras feature.

**Comment by dshokouhi** [comment]
So part of the reason for this is because Android returns a flat map and we need to define the parameters in the firebase repo. So what we decide to do should keep that in mind. I'm surprised to see a comma and colon being used. Not sure what's a better way to split things. Whats the actual extra that gadgetbridge wants? First I'm hearing of this format when compared to official Google apps and examples.

**Comment by mvn23** [comment]
Gadgetbridge is implementing custom widgets on the watchface of the Fossil Hybrid HR. Their content can be set through an intent, which should contain json-formatted extras as described [here](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Fossil-Hybrid-HR#custom-widgets-firmware-dn1-0-2-20r-and-newer).

**Comment by mvn23** [comment]
I have been thinking about this, how about a feature where we allow extras to be urlencoded or base64 encoded? Maybe through an additional extra (something like `EXTRA_EXTRAS_ENCODING:url`), although urldecoding should be pretty safe to do on plain text strings as well. That way we don't break existing functionality and allow any special character to be sent.
If this is an acceptable solution, I'd be willing to put some effort in the implementation over the next days.

**Comment by dshokouhi** [comment]
> I have been thinking about this, how about a feature where we allow extras to be urlencoded or base64 encoded? Maybe through an additional extra (something like `EXTRA_EXTRAS_ENCODING:url`), although urldecoding should be pretty safe to do on plain text strings as well. That way we don't break existing functionality and allow any special character to be sent. If this is an acceptable solution, I'd be willing to put some effort in the implementation over the next days.

as long as its a string sent to the same parameter and we can safely make it all work I think it should be ok
