### ISSUE TITLE
 want you to add Japanese Android and iOS to Lokalise.

### ISSUE THREAD

**Issue by yohru** [home-assistant/android#1984]
The Japanese translation of the front end and core is almost finished, so I tried to translate the android and iOS, but there was no Lokalise in Japanese.

English Name: Japanese
Native Name: 日本語
Subtag: ja

**Comment by dshokouhi** [comment]
hi what is your user name on Lokalize so I can add the language for you? Also you will need to make a separate request for iOS

**Comment by dshokouhi** [comment]
you should now have access to the requested language, for iOS please create a separate request in that repo please

**Comment by yohru** [comment]
The Japanese base for Lokalise in Android has been added, but it cannot be edit(translated).
Not authorized?
The Lokalise username is the same as here.

**Comment by dshokouhi** [comment]
my bad, should be good now I hope :)
