### ISSUE TITLE
Entering a specific page to URL

### ISSUE THREAD

**Issue by DaveeKol** [home-assistant/android#1985]
Hallo,

please I would like in Andoid app to specify the page to open when app is start.
Example:
https://xxxccxxcccxxxxx.ui.nabu.casa/lovelace-desk/home
but every time I write URL - go back to HA - again to App settings it overwrites me on basic URL https://xxxccxxcccxxxxx.ui.nabu.casa

I have latest APP and HA. Please is somethink wrong on my side? Or is it possible? 

Thank you.

**Comment by dshokouhi** [comment]
you need to set this in HA user profile

![image](https://user-images.githubusercontent.com/1634145/144549827-91e7f5ef-9228-4922-bc65-82c7714b560e.png)

**Comment by DaveeKol** [comment]
Thank you very much!
