### ISSUE TITLE
Next Alarm sensor

### ISSUE THREAD

**Issue by TopdRob** [home-assistant/android#1990]
**Home Assistant Android version:**
versie beta-1744-9fd3164-full
**Android version:**
11
**Phone model:**
OnePlus Nord AC2003
**Home Assistant version:**
2021.12.0b0
**Last working Home Assistant release (if known):**
2021.11.4
**Description of problem:**
Invalid date/datetime: sensor.robert_s_one_plus_nord_next_alarm provide state 'unavailable', while it has device class 'timestamp'
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
Exception in _handle_update when dispatching 'mobile_app_sensor_update': ({'unique_id': 'next_alarm', 'state': 'unavailable', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': '', 'Package': '', 'Time in Milliseconds': 0}, 'webhook_id': '5c151a9ceae93e25553b5a27fd82b9422e148dd84a2f51f9e4f3a494dfddd9c7'},)
Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sensor/init.py", line 388, in state value = ciso8601.parse_datetime(str(value))

ValueError: Invalid character while parsing year ('u', Index: 0)

The above exception was the direct cause of the following exception: Traceback (most recent call last):

File "/usr/src/homeassistant/homeassistant/components/mobile_app/entity.py", line 112, in _handle_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 502, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 535, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 508, in _stringify_state if (state := self.state) is None:

File "/usr/src/homeassistant/homeassistant/components/sensor/init.py", line 390, in state
  raise ValueError(

ValueError: Invalid date/datetime: sensor.robert_s_one_plus_nord_next_alarm provide state 'unavailable', while it has device class 'timestamp'
```

**Screenshot of problem:**

<details
![Screenshot_20211204-081656](https://user-images.githubusercontent.com/9911541/144701332-9de73f24-24b7-4844-9dd7-511af07f04f8.jpg)
</details>

**Additional information:**

**Comment by balloob** [comment]
The mobile app integration doesn't currently allow setting sensors to unavailable. Instead it was sending `unavailable` as state.

**Comment by balloob** [comment]
I think the easiest solution is that we implement an available property for mobile app. Should it be a new attribute or are we going to compare the sensor state to `"unavailable"` ?

**Comment by dshokouhi** [comment]
> I think the easiest solution is that we implement an available property for mobile app. Should it be a new attribute or are we going to compare the sensor state to `"unavailable"` ?

So we do use `unavailable` as a state in a few different sensor.

* Last reboot - When we are unable to determine the date
* Next Alarm - When we fail to get an update or there is no next alarm state
* Media Session - When there are no media sessions
* Phone SIM Sensors - When we fail to get the SIM status

I am ok with changing the value `None` if thats more appropriate for us.

**Comment by balloob** [comment]
`None` would become `unknown` in Home Assistant. That seems more appropriate except for next alarm. There was an open issue about next alarm state but no solution yet.
