### ISSUE TITLE
Add notification command to turn WiFi on/off

### ISSUE THREAD

**Issue by pedrolamas** [home-assistant/android#2003]
**Is your feature request related to a problem? Please describe.**

I would like to be able to turn WiFi off when I'm away from home (outside a radius from home) and then turn it back on when I'm inside.

**Describe the solution you'd like**

Allow to send a notifications to turn WiFi on/off.

**Describe alternatives you've considered, if any**

Using tasker maybe?

**Additional context**

None.

**Comment by dshokouhi** [comment]
This is not possible anymore in recent versions of android, so we cannot add this feature.

https://developer.android.com/reference/android/net/wifi/WifiManager#enableNetwork(int,%20boolean)

`Compatibility Note: For applications targeting Build.VERSION_CODES.Q or above, this API will always fail and return false`

**Comment by pedrolamas** [comment]
Fair enough, wasn't aware of that limitation! Thanks for clearing that @dshokouhi! 🙂
