### ISSUE TITLE
Allow App to be moved to SD card.

### ISSUE THREAD

**Issue by andrewstech** [home-assistant/android#2005]
**Is your feature request related to a problem? Please describe.**

The App cannot be moved to sd card so is using internal storage.
**Describe the solution you'd like**

The ability to move the app to the sd card.
**Describe alternatives you've considered, if any**

From checking the android docs it seems to be set in an xml file.
**Additional context**

Docs about install locations: https://developer.android.com/guide/topics/data/install-location

**Comment by andrewstech** [comment]
Feel free to close this issue if you think it would be a waste of time.

**Comment by JBassett** [comment]
Based on the criteria they say shouldn't install to sdcard [here](https://developer.android.com/guide/topics/data/install-location#ShouldNot) I don't think we should enable this.

**Comment by dshokouhi** [comment]
I agree, looks like it will mess with sensor updates when device is restarted

**Comment by dshokouhi** [comment]
Closing this as we should not enable this.
