### ISSUE TITLE
Dashboards Page non selected page not shown

### ISSUE THREAD

**Issue by williamkennyAK** [home-assistant/android#2006]
**Home Assistant Android version:**
beta-1748-ab6cf026-full
**Android version:**
11
**Phone model:**
SM-G986U1
**Home Assistant version:**
core-2021.12.0
**Last working Home Assistant release (if known):**

**Description of problem:**
On dashboards Page, if dashboards selected, resources label cannot be seen and vice versa.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20211212-001034_Home Assistant](https://user-images.githubusercontent.com/73054266/145706858-d4c5402e-0c87-4f49-adb1-074e3201e740.png)
![Screenshot_20211212-002152_Home Assistant](https://user-images.githubusercontent.com/73054266/145706982-c1ab8a72-5ce9-4837-a249-260a0b027f0e.png)

**Additional information:**

**Comment by dshokouhi** [comment]
Can you reproduce in chrome for Android?

**Comment by dshokouhi** [comment]
ok I see it, this is an HA frontend issue, please open an issue with the HA frontend.

**Comment by williamkennyAK** [comment]
Well don't I feel dumb now.  I'll repost this issue in the proper place.
