### ISSUE TITLE
HA on VmWare. Access on same hardware works, but not on other devices in same network

### ISSUE THREAD

**Issue by RensDuijsens** [home-assistant/android#2014]
**Home Assistant Android version:**
2021.10.0-full and also beta-1776-c149dd-full

**Android version:**
Android 11 and also Android 9

**Phone model:**
Samsung Galaxy Fold 3 and also Samsung Galaxy Note 8

**Home Assistant version:**
Home Assistant 2021.12.1

**Last working Home Assistant release (if known):**
n.v.t.

**Description of problem:**
Home assistant runs on VmWare machine.
Accessing via browser on the laptop where the VmWare is running) works fine.
Accessing via any phone or other laptop in the same Wifi network does not work no matter which browser is used of which Home Assistant App is used.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

Please assist met in getting the required logs
```

```

**Screenshot of problem:**
![HomeAssistantIssue](https://user-images.githubusercontent.com/48952829/146059075-fc6e3d4f-8cdb-4999-9b98-73665189090a.png)

**Additional information:**

**Comment by dshokouhi** [comment]
> Accessing via any phone or other laptop in the same Wifi network does not work no matter which browser is used of which Home Assistant App is used.

As this issue occurs on a laptop in a browser then it is not related to the app but something else so I am closing this issue.  In terms of networking issues we do have a troubleshooting page that may be of help. But until you can get it to work in a browser you cannot expect it to work in the app.

https://companion.home-assistant.io/docs/troubleshooting/networking

This would also be more of either a HA core or HA OS issue if all troubleshooting steps fail.
