### ISSUE TITLE
Include odb2 data into sensors for companion app

### ISSUE THREAD

**Issue by augustodinizl** [home-assistant/android#2015]
I've not detected any issue or something "similar"
**Is your feature request related to a problem? Please describe.**

Not a real problem, but is just a idea for a better integration since a lot of users have the "same pain" passing odb2 data into HA.
**Describe the solution you'd like**

My idea is to turn "the car" (a lot of users have android multimedia devices and include a odb2 scanner into them is a "breeze") into a device entity, with maybe a "odb2" section into the sensors already existent in companion app.
That will prevent users to "adapt things" to have car telemetry data into HA
**Describe alternatives you've considered, if any**

there's a lot of "paths" already taken, but them involve a lot of "third-party" apps and addons...
**Additional context**

**Comment by dshokouhi** [comment]
> My idea is to turn "the car" (a lot of users have android multimedia devices and include a odb2 scanner into them is a "breeze") into a device entity, with maybe a "odb2" section into the sensors already existent in companion app.
That will prevent users to "adapt things" to have car telemetry data into HA

Umm can you point us to official android documentation? 

AFAIK OBD2 sensors require a separate app which already has its own integration

https://www.home-assistant.io/integrations/torque/

If you can't use this app then you need to look and see if your current app that works with OBD2 fires android intents. If it does then you can look into forwarding those events using the Last Update sensor

https://companion.home-assistant.io/docs/core/sensors#last-update-trigger-sensor

**Comment by augustodinizl** [comment]
> > My idea is to turn "the car" (a lot of users have android multimedia devices and include a odb2 scanner into them is a "breeze") into a device entity, with maybe a "odb2" section into the sensors already existent in companion app.
> > That will prevent users to "adapt things" to have car telemetry data into HA
> 
> Umm can you point us to official android documentation?
> 
> AFAIK OBD2 sensors require a separate app which already has its own integration
> 
> https://www.home-assistant.io/integrations/torque/
> 
> If you can't use this app then you need to look and see if your current app that works with OBD2 fires android intents. If it does then you can look into forwarding those events using the Last Update sensor
> 
> https://companion.home-assistant.io/docs/core/sensors#last-update-trigger-sensor

i was trying not to use torque, but if that's the easier path, i will try it, thanks a lot!!!
