### ISSUE TITLE
Missing configuration button for non-administrator account

### ISSUE THREAD

**Issue by MaciejR89** [home-assistant/android#2019]
**Home Assistant Android version:** 2021.10.0

**Android version:** 10

**Phone model:** Xiaomi Mi 9 Lite

**Home Assistant version:** 2021.12.2

**Last working Home Assistant release (if known):**All versions before 2021.12.0

**Description of problem:**
In HA version 2021.12 there was a change in access to settings and now the non-admin accounts has no option to enter the Companion app settings by the sidebar button.

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/76744089/146436391-2a04a372-5d82-4616-b7d4-6755ef304aca.png)

**Additional information:**

**Comment by dshokouhi** [comment]
Fixed in HA core 2021.12.2
