### ISSUE TITLE
Grouped Switches opens detailed view

### ISSUE THREAD

**Issue by kiss81** [home-assistant/android#2021]
Before a "grouped" switch was just displayed as a normal switch. Now when I want to turn on or off those grouped switches it will open up a detailed view first where I see all the individual switches. Of course it still works but it means an extra clock. If I wanted to see the individual switches I can configure it to do so.

**Home Assistant Android version: 2021.10.0-full **

**Home Assistant version: 2021.12.0 **

**Android version: 11 **

**Phone model: samsung s20**

**Comment by dshokouhi** [comment]
what is the behavior in chrome for android? can you reproduce there?  Also you are not on the latest version of HA core you should update and retest as well.

**Comment by kiss81** [comment]
Same behavior on the android chrome browser, so it's a home assistant core related issue. I was on the latest version a few days ago, but will check it before posting this issue in the HA core github. Thanks

**Comment by dshokouhi** [comment]
Not HA core but HA frontend, closing as this is not an issue with the app

https://github.com/home-assistant/frontend/issues
