### ISSUE TITLE
App keeps crashing when no connection to HA

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/android#2022]
**Home Assistant Android version:**
Latest

**Android version:**
11

**Phone model:**
Samsung S10 plus

**Home Assistant version:**
Latest 12.2

**Last working Home Assistant release (if known):**

**Description of problem:**
The companion app keeps crashing when I am away from home. So whenever I have no connection to my HA setup, the companion app crashes.
Since the latest update (not sure if app or core update), the app also crashes when I try to open it without HA available.
In the past I would get a screen asking me if I wanted to wait for a connection or cancel. Now it just crashes right away.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20211217-162703_GitHub.jpg](https://user-images.githubusercontent.com/57034871/146567790-364d5f74-4856-46b4-8c0a-1b540dc17b67.jpg)
**Additional information:**

**Comment by dshokouhi** [comment]
Please list the version of the app has `latest` can mean anything because we have a beta and production version.

Are you able to get us the crash log?

**Comment by AleXSR700** [comment]
![Screenshot_20211217-163349_Settings.jpg](https://user-images.githubusercontent.com/57034871/146569060-ad4d2149-627f-40a0-8e30-4cfc484524f9.jpg)

I will try to enable the in-app logging when I get home. Can't open it to do so (as it keeps crashing without network connection to HA).

**Comment by dshokouhi** [comment]
pleas update to the latest beta.....beta 1626  is super old!!!! We are at BETA 1784 now.  The play store has BETA 1776

**Comment by AleXSR700** [comment]
I truly apologize and this thread can be deleted.

I had signed up for latest betas and for some reason updates were not installed.
I downloaded directly from github now and it seems to have fixed the issues.
I am guessing there was some breaking change with the december updates?

**Comment by dshokouhi** [comment]
> I am guessing there was some breaking change with the december updates?

There was a HA core breaking change where they had removed the discovery API completely and the app was updated to account for that.  This why one of our troubleshooting steps is to make sure both HA core and the app are up to date.

Glad the update solved your issue.

**Comment by sunnyd24** [comment]
This issue is still open. It still happens on android with v2022.6.full when connection to HA Web address is not accessible; in my case it was that no-ip address had expired and not accessible.

**Comment by jasonprovencher** [comment]
I am having this issue as well on v2022.6.full. I have wall panels up in the house and restart my router monthly to clear the noise. Anytime this happens all of my screen HA apps quit. This does happen randomly as well on a HA restart etc. Has there been any work around for this?

**Comment by JohannCR** [comment]
Also having this problem, app crashes constantly when HA is offline. Both are up to date.
Any pointer ?

**Comment by dshokouhi** [comment]
All if you still see an issue please open a  new one. Do not comment on old and closed issues as nobody pays attention to them and they will not be reopened. The best way to move forward is to update to the latest version and if the issue still exists to submit a new issue making sure to fill out the issue template completely including the part about the logs.
