### ISSUE TITLE
Changing users/passwords in HA,  App only gives a blank screen rather than login screen

### ISSUE THREAD

**Issue by gbrissey** [home-assistant/android#203]
**Home Assistant Android version: 1.3.1**

**Android version: 9**

**Phone model: Moto G7**

**Home Assistant version: 0.102.3**

**Last working Home Assistant release (if known): 0.102.3**

**Description of problem: 
This app has been working just fine. Then I decided I needed to move away from the Home Assistant (HA) _legacy_api_password_ and use the HA user/password.  Upon the switch the App just wouldn't connect. I then uninstalled and reinstall the app thinking this would remove any cached information. I manually re-entered the URL https://myHAdomain.com, then a new blank screen appeared, I would of expected a user and password entry screen at this point but only get a blank screen. There appears nothing I can do at this point.   
I've _cleared_ both the _data_ and _cache_ for the app. still no difference, just a blank screen**

**Traceback (if applicable):**

```

```

**Additional information: 
**

**Comment by JBassett** [comment]
@gbrissey Can you retry with the latest release and see if things are functioning for you?

**Comment by dshokouhi** [comment]
Closing as we have not heard back in quite some time, if the issue still exists please open a new issue.
