### ISSUE TITLE
Login with custom ca certificate

### ISSUE THREAD

**Issue by a-waider** [home-assistant/android#2050]
**Home Assistant Android version:**
2021.12.0-full
**Android version:**
Android 11
**Phone model:**
OnePlus 7T
**Home Assistant version:**
2021.12.4
**Last working Home Assistant release (if known):**

**Description of problem:**
Maybe someone is so kind to add the Wear OS label.

I just joint the beta for the new Wear OS app. I tried to login to my home assistant instance but there is a very basic problem. I'm using home assistant via a https proxy with a custom ca certificate. Until now I couldn't find any way to install this certificate into the OS of my watch. So my question is either if and how to install this certificate or if not possible, to allow login with an self signed certificate. 
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
CA certs are not supported. Don't think self signed will work on wear os either but it should support it if you can import the certificate on the watch.

**Comment by dshokouhi** [comment]
for self signed certificate you can try this troubleshooting step https://companion.home-assistant.io/docs/troubleshooting/faqs/#using-a-self-signed-certificate-leads-to-a-blank-page-in-android

I am not sure if those steps will work on Wear OS but that is all we can do.
