### ISSUE TITLE
Android 12 Widgets, Device Controls, Quick Action Tiles broken

### ISSUE THREAD

**Issue by CampCray** [home-assistant/android#2051]
I also posted this issue in the community forum:
[https://community.home-assistant.io/t/android-12-widgets-device-controls-quick-action-tiles-broken/369699](url)

Home Assistant Android version:
2021.12.0-full

Android version:
12.0

Phone model:
Pixel 3
OS: Stock
Build number: SP1A.210812.015
(Just force flashed all partitions back to stock 2 days ago, no modifications, no root, locked bootloader, so this issue is not related to firmware.)

Home Assistant version:
Core: 2021.12.4
Supervisor: 2021.12.2
Host: Home Assistant OS 7.0
Nabu Casa Cloud for remote control

Last working Home Assistant release (if known):
n/a

Description of problem:
I have a Pixel 3 running Android 12, and I normally use Device Controls, (which used to be on the power menu in Android 11 but have been moved to the Quick Actions panel in Android 12.) The states of these devices are all shown accurately, but when I tap on any device, it say “Error, try again.” I investigated and found this response to be the same on the quick actions triggers and widget triggers. I tried turning battery usage to unrestricted and enabling unrestricted data usage, but that made no difference. Opening the app still works fine and I can still control devices through my google home. It seems the app isn’t fully compatible with Android 12. I would like to know if others are having the same issue, and if anyone is working on patching this function. Photos included for reference
![Screenshot_20211221-124936](https://user-images.githubusercontent.com/36041572/146984552-cb693326-03ba-4000-93a3-1579e059f22a.png)
![Screenshot_20211221-124818~2](https://user-images.githubusercontent.com/36041572/146984553-d3eb0908-0d28-4187-9d28-faffba87af5d.png)
.

**Comment by dshokouhi** [comment]
This issue is missing the issue template, please copy the template from a new issue and supply all requested information. We can't proceed with out it.

On my pixel 6 everything is working as expected.

**Comment by CampCray** [comment]
> 

Just updated with all relevant info. Sorry about that.

**Comment by dshokouhi** [comment]
Still missing the logs which is required for us to continue

**Comment by CampCray** [comment]
> Still missing the logs which is required for us to continue
[logcat.txt](https://github.com/home-assistant/android/files/7763296/logcat.txt)

I tried about 7 requests in a row, and they're all at the bottom.

**Comment by dshokouhi** [comment]
```
12-22 08:40:56.812  1075  1075 E HaConProService: Unable to control or get entity information
12-22 08:40:56.812  1075  1075 E HaConProService: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request call_service
```

What entity did you try to control? Can you show us the state and attributes? 

Also can you get the logs from widgets and quick setting tiles too? I just want to confirm the issue there. Currently I only see logs for device control.

In the future you can get the logs by going to App Configuration > show and share logs. This will grab the logs from our app only, this was mentioned in the issue template that requested the logs :)

**Comment by CampCray** [comment]
[homeassistant_companion_log_11-22-2021_8-59-26.txt](https://github.com/home-assistant/android/files/7763369/homeassistant_companion_log_11-22-2021_8-59-26.txt)
Performed widget and quick setting tile as requested. Here's the log from inside the app.

**Comment by dshokouhi** [comment]
are there any HA errors at the time you performed the actions? 

Can you confirm that this service call works when you execute it manually in the HA services tab?

```
12-22 08:58:12.713  1075  1075 D ButtonWidget: domain: light
12-22 08:58:12.713  1075  1075 D ButtonWidget: service: turn_on
12-22 08:58:12.713  1075  1075 D ButtonWidget: service_data: {"entity_id":["light.bulb_1","light.bulb_2"]}
```

the calls all fail for the same reason, failure to execute the service call

**Comment by dshokouhi** [comment]
The app is even having an issue registering sensors:

```
12-22 08:58:32.974  1075 10850 E SensorReceiver: Issue registering sensor: geocoded_location
12-22 08:58:32.974  1075 10850 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor
```

Lets try the start fresh steps: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

Please execute them in order without skipping a step

**Comment by CampCray** [comment]
Just got home and reset the app and that fixed it! I should have tried that before opening an issue but thanks so much for your help.
