### ISSUE TITLE
WearOS - Multi-factor Authentication

### ISSUE THREAD

**Issue by ch4d1** [home-assistant/android#2055]
**Is your feature request related to a problem? Please describe.**

The WearOS companion app currently does not seem to have implemented multi-factor authentication. Logging in with an account that has this activated is therefore not possible.
**Describe the solution you'd like**

Implementation of multi-factor authentication
**Describe alternatives you've considered, if any**

Authentication via the smartphone app. Entering login information via the WearOS keyboard is a pain.
**Additional context**

**Comment by dshokouhi** [comment]
You can actually login using your phone already and that works with MFA

**Comment by mikkelzzz3** [comment]
@dshokouhi You can login on the Wear OS app using your phone? How does that work. I only have option to input username and password, and then it says afterwards it couldn't connect. (Because I have MFA)

**Comment by dshokouhi** [comment]
> @dshokouhi You can login on the Wear OS app using your phone? How does that work. I only have option to input username and password, and then it says afterwards it couldn't connect. (Because I have MFA)

Open the phone app, go to App configuraiton or configuration > companion app. Then go to Wear OS Settings and once it finds your device login from there.  MFA doesnt work directly from the watch yet but using the phone app we can perform MFA as the phone app has support for it so it can forward that to the watch

**Comment by ch4d1** [comment]
> > @dshokouhi You can login on the Wear OS app using your phone? How does that work. I only have option to input username and password, and then it says afterwards it couldn't connect. (Because I have MFA)
> 
> Open the phone app, go to App configuraiton or configuration > companion app. Then go to Wear OS Settings and once it finds your device login from there. MFA doesnt work directly from the watch yet but using the phone app we can perform MFA as the phone app has support for it so it can forward that to the watch

It works but should be mentioned somehow when setting the app up.

**Comment by dshokouhi** [comment]
> It works but should be mentioned somehow when setting the app up.

We shouldn't mention a workaround in the UI, we should actually fix the issue which is getting the MFA prompt on a wearable. Workarounds for issue trackers to help users get by until things are fixed.

**Comment by ch4d1** [comment]
> > It works but should be mentioned somehow when setting the app up.
> 
> We shouldn't mention a workaround in the UI, we should actually fix the issue which is getting the MFA prompt on a wearable. Workarounds for issue trackers to help users get by until things are fixed.

Sure thing, but it would be best to offer the workaround as an official method, as the default wear os keyboard is missing symbols. Also typing in longer passwords is still a pain.
