### ISSUE TITLE
No album Art when play music

### ISSUE THREAD

**Issue by raptr55** [home-assistant/android#206]
**Home Assistant Android version:**
1.3.1 (57)

**Android version:**
Android 10
**Phone model:**
Samsung Galaxy 10
**Home Assistant version:**
0.103.4
**Last working Home Assistant release (if known):**

**Description of problem:**
No album Art when play music, the companion app shows blank picture. on web instead are show the correct album art
**Traceback (if applicable):**

```

```

**Additional information:**
### **Screenshot taken on Chrome**
![Screenshot_20191226-103904_Chrome](https://user-images.githubusercontent.com/49353954/71471011-5e79ac80-27ce-11ea-9217-bfd2d39d0c57.jpg)

### **Screenshot taken on App**
![Screenshot_20191226-103911_Home Assistant](https://user-images.githubusercontent.com/49353954/71471013-63d6f700-27ce-11ea-8bb5-898cc6eedaba.jpg)

**Comment by os131** [comment]
I have the same problem. The album art is served in http. It is also available as https at the same link. Just add an 's' in the entity picture and you would see the album art in the app.
`entity_picture: http://lh3.googleusercontent.com/xxxx`
Is it possible to patch the media player to serv this picture as https when it comes from google's servers?

**Comment by dshokouhi** [comment]
Does this happen with any media player or just certain ones? We just had a similar issue where the user needed to ensure `https` was used.  I dont know if this is something we can correct in the app side if its for a specific media player.

**Comment by os131** [comment]
I'm using google play music which appear to serve the album art using http only (we can see it in the developer's tools, looking for the attributs of the media player). It's no longer an issue, since the app shows the album art since months, although the album art is still served as http only.
