### ISSUE TITLE
About instant update of IP sensors

### ISSUE THREAD

**Issue by hanzch** [home-assistant/android#2065]
**Is your feature request related to a problem? Please describe.**

Hello, at present, it seems that the IP sensor can only be uploaded synchronously when the first APP is opened and initialized. Even when the APP is turned on and the WIFI/4G switch is switched, can't update instantly. I waited about 5 minutes.

**Describe the solution you'd like**

May I ask whether it can be achieved. When the APP is running in the background, the update is uploaded with the WIFI change.

**Describe alternatives you've considered, if any**

Or upload regularly, the parameters can be set manually (for example, update once in 60s).

**Additional context**

APP version: 2021.10.0-full
HASS version: 2021.12.4
Android version: MIUI 12.5 (Android 11)
Phone model: Xiaomi 9

**Comment by dshokouhi** [comment]
Instant update of public IP address is not possible as there is no corresponding android intent.  Try to enable more sensors to get poll based sensors to update more frequently.

I also see you mention that it doesn't update until you open the app, make sure the app has proper permissions to run in the background as well.

Sensor updates also trigger on a 15 minute interval which is the fastest offered.

**Comment by hanzch** [comment]
Thank you for your patient reply.
