### ISSUE TITLE
Wear OS - HomeAssistant as card

### ISSUE THREAD

**Issue by Eodun** [home-assistant/android#2069]
Make it possible to add HA Wear OS app as a card (the ones tha appear with wipe from right to left at the main screen). Like [this ones](https://www.xatakandroid.com/tutoriales/como-personalizar-tu-reloj-wear-os-sus-nuevas-tarjetas/amp)

**Comment by dshokouhi** [comment]
These are called tiles. You set them under Settings in the wear OS app, they are the lsat section under settings. Then you can add the tile and see your entities. The app already supports this :)

**Comment by Eodun** [comment]
Uh, the app is working perfectly and it doesn't appear for me. But oh, well. It could be that my watch is old (Huawei watch 1)

**Comment by dshokouhi** [comment]
So you were able to set your tile entities in settings but you dont know how to add the HA tile is that right?

**Comment by Eodun** [comment]
Knowing the app allows it, that I had tiles but it only let me add the original ones, I investigated a bit more. It seems it needs a Wear OS version newer than my watch officially supports (2.52). So sorry for this but hope it's useful for people in my situation.
