### ISSUE TITLE
Home assistant google app does not connect remotely 

### ISSUE THREAD

**Issue by djelimon** [home-assistant/android#2074]
Logging in through nabu casa website still works
Tried refreshing remote url, no good
Latest version of home assistant and the app

**Comment by dshokouhi** [comment]
Hi this is not enough information to go by. There is an issue template that gets presented when you create a new issue please copy that template and add it here with your information. Without proper template and error message we cannot continue with troubleshooting.

**Comment by djelimon** [comment]
Didn't see a template but I will close and try to submit again
