### ISSUE TITLE
Release of Android version code

### ISSUE THREAD

**Issue by shilonit** [home-assistant/android#2078]
In order to automatically build versions of the application using the FDroid server, it is required to obtain the version code of the latest release, but since the version code is not published, the automatic script code c'not obtain it.

In PR I got the following answer
"If they can publish a file with the version code or just put the version code in the release note we can extract it."

[Link to PR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10283)

**Comment by shilonit** [comment]
@JBassett

**Comment by dshokouhi** [comment]
Can't they pick up the version from the tags we create? Just skip any version that says beta. We had already agreed to being published in f-droid given we don't have any changes to make for it.

**Comment by shilonit** [comment]
@dshokouhi 
Android version is the version number, for example release 2021.12.3 its version number 1854, it was [created using CI](https://github.com/home-assistant/android/blob/master/.github/actions/create-release-number/action.yml).


Is there a place where the version number (1854) appears? Not the version name (2021.12.3)

**Comment by dshokouhi** [comment]
> @dshokouhi 
> Android version is the version code, for example release 2021.12.3 the version code is 1854, it was [created using CI](https://github.com/home-assistant/android/blob/master/.github/actions/create-release-number/action.yml).
> 
> 
> Is there a place where the **version code** (1854) appears? NOT the release name (2021.12.3)

The version code is included in the beta file name. If you don't see it in the file name then you can assume the latest beta is the release version. All we do is promote latest beta to release.

**Comment by JBassett** [comment]
So I'm going to reopen, the beta and release version codes aren't identical.  I don't think uploading a `version.txt` file to the release assets is horrible.

**Comment by linsui** [comment]
Thanks for your help! But we are not able to check that file since there is no static link to it. We can check from the latest release page but the release files don't have a static url. Is that possible to add the version code in the file name directly?
