### ISSUE TITLE
Changing default dashboard hides original default dashboard

### ISSUE THREAD

**Issue by jamesmyatt** [home-assistant/android#2082]
**Home Assistant Android version:**

2021.12.3-full

**Android version:**
9

**Phone model:**

Samsung Galaxy S8 (SM-G950F)

**Home Assistant version:**

2021.12.5

**Last working Home Assistant release (if known):**

Not known

**Description of problem:**

When I change the default dashboard configuration, the original default dashboard ("overview" or whatever) is not accessible in the sidebar.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

N/A

**Screenshot of problem:**

Default configuration:

![photo_2021-12-27_15-44-32](https://user-images.githubusercontent.com/1047337/147487002-26ffb8dc-587a-4c6a-a195-c0ef32345bb2.jpg)

With "Default dashboard = Minimalist"

![photo_2021-12-27_15-28-59](https://user-images.githubusercontent.com/1047337/147486999-7229e1e9-728d-463a-954c-3cfe30531638.jpg)

**Additional information:**

N/A

**Comment by dshokouhi** [comment]
Does this issue exist in chrome from Android?

**Comment by dbalazuc** [comment]
I can reproduce this on Windows's Chrome and Firefox with HA  2021.12.5 as well. It doesn't seem related to the Android app. I actually thought that was a feature at first and there was a toggle somewhere to keep "Overview" visible but never found said toggle.

**Comment by dshokouhi** [comment]
Closing as this is a frontend issue, please check for open issues in the HA frontend repo and create an issue if it doesn't already exist.

**Comment by jamesmyatt** [comment]
Ok. Thanks
