### ISSUE TITLE
Last Notification / Last Removed Notification Not Updating

### ISSUE THREAD

**Issue by OCT0PUSCRIME** [home-assistant/android#2083]
Shortly after the latest update (2021-12-3-full) the notification sensors have not been updating and have been stuck on the same notification / notification count.

**Comment by dshokouhi** [comment]
In our recent release we had a breaking change where we are now enforcing the allow list. Please go to sensor settings for each sensor and set an allow list for applications you wish to receive notifications from. Alternatively you can opt to disable the allow list in settings however keep in mind without an allow list you will experience battery drain which is the reason for the allow list enforcement.

**Comment by CheeseySandal** [comment]
Hi,

I appreciate the breaking change, but I still seem can't get the received notification to work again. 

I've tried the allow list, and allow all. The sensor just never updates within Homeassistant.

Strangely, last removed sensor is working as expected, using both allow list or allow all.

**Comment by dshokouhi** [comment]
> Hi,
> 
> I appreciate the breaking change, but I still seem can't get the received notification to work again. 
> 
> I've tried the allow list, and allow all. The sensor just never updates within Homeassistant.
> 
> Strangely, last removed sensor is working as expected, using both allow list or allow all. 

If you set an allow list then you need to wait for the application in the allow list to post a notification in order to get the update. Otherwise do not set an allow list and only disable it in settings.

**Comment by CheeseySandal** [comment]
That makes sense, however I have set up com.whatsapp in the allow list, WhatsApp has definitely posted numerous notifications in the last couple of days yet sensor.xxx_last_notification hasn't been updated since Dec 25th.

Edit: Upgraded to 2021.12.6 and all working. Maybe my system just needed a restart.

Cheers
