### ISSUE TITLE
All states stop updating after phone sleeps, can still call services. See new states in websocket logs. Need to force-close app to resume working.

### ISSUE THREAD

**Issue by progman32** [home-assistant/android#2086]
**Home Assistant Android version:** 2021.12.3-full

**Android version:** 11

**Phone model:** Oneplus Nord N10 5G BE2028

**Home Assistant version:** 2021.12.6

**Last working Home Assistant release (if known):** 2021.12.6 worked at some point I think, so not sure.

**Description of problem:**

As of this morning, all my sensors stop updating in Companion if I leave the phone's screen off for a few minutes. They work fine indefinitely if I keep the screen on. In the error state, I can still navigate between pages and call services via buttons, modify light brightnesses, etc. Toggle switches kind of work but since the underlying state changes don't propagate back to the phone, the switch jumps back to its original position after a second (though the lights do toggle once, for example). Charts backed by Recorder also update fine. The only way I can get the app to work properly is to force-stop it and restart.

The only recent change I can think of is that I added 67 entities related to electrical power monitoring, updating at a ten-second cadence. Perhaps the rate of state changes is overwhelming the app while backgrounded?

I do see websocket messages coming in with the latest state values, for example:
```
12-28 13:02:35.752 11914 20630 D WebSocketRepository: Websocket: onMessage (text)
12-28 13:02:35.752 11914 20630 D WebSocketRepository: Message number 21 received: {"id": 21, "type": "event", "event": {"event_type": "state_changed", "data": {"entity_id": "sensor.main_panel_emon_1_ct6_current_circuit_ai", "old_state": {"entity_id": "sensor.main_panel_emon_1_ct6_current_circuit_ai", "state": "14.21", "attributes": {"state_class": "measurement", "unit_of_measurement": "A", "device_class": "current", "friendly_name": "Main Panel EMON 1-CT6 Current - Circuit AI"}, "last_changed": "2021-12-28T21:02:26.335348+00:00", "last_updated": "2021-12-28T21:02:26.335348+00:00", "context": {"id": "4d29a9909a5b02b1128755e6962f9146", "parent_id": null, "user_id": null}}, "new_state": {"entity_id": "sensor.main_panel_emon_1_ct6_current_circuit_ai", "state": "13.96", "attributes": {"state_class": "measurement", "unit_of_measurement": "A", "device_class": "current", "friendly_name": "Main Panel EMON 1-CT6 Current - Circuit AI"}, "last_changed": "2021-12-28T21:02:36.330041+00:00", "last_updated": "2021-12-28T21:02:36.330041+00:00", "context": {"id": "399a57b5f6819fb29f8882e383deae36", "parent_id": null, "user_id": null}}}, "origin": "LOCAL", "time_fired": "2021-12-28T21:02:36.330041+00:00", "context": {"id": "399a57b5f6819fb29f8882e383deae36", "parent_id": null, "user_id": null}}}
12-28 13:02:35.781 11914 20630 D WebSocketRepository: Websocket: onMessage (text)
```

But the UI doesn't show the new value, in my case it's permanently stuck at 14.02 (which is neither the old nor new value in the websocket message above).

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

I don't see any crash traces in the logs. I'm sure I could have missed something, but the only thing I see so far in the logs that is suspicious is a couple dozen messages like:

```
12-28 13:02:37.744 11914 11914 E mpanion.androi: Invalid ID 0x00000000.

```

**Screenshot of problem:**

Attached is an example of an entity which has been wedged at a value of `14.02` but as you can see from the chart, has a current value of below 5. Additionally, the sensor has definitely updated within the last minute, so the "12 minutes ago" is not accurate.

![Screenshot_20211228-125330](https://user-images.githubusercontent.com/48895/147607708-9b349090-76e1-441b-af6d-5aa36668921b.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
Does the issue exist in chrome for Android?

**Comment by dshokouhi** [comment]
The websockets from app configuration logs are not for the HA frontend, they are for app specific features only like widgets. What you are seeing is the HA frontend and not part of the app.

**Comment by dshokouhi** [comment]
actually there is already a frontend issue here so closing in favor of: https://github.com/home-assistant/frontend/issues/11038 where the issue creator also mentions that it does indeed happen in chrome for android too.

**Comment by progman32** [comment]
Aha. I could not reproduce my issue on my computer but I was running Firefox. I will test this out with Chrome on Android and PC for my own curiosity.
