### ISSUE TITLE
Android APP issue after security update december 2021

### ISSUE THREAD

**Issue by Chicho976** [home-assistant/android#2087]
**Home Assistant Android version:**
2021.12.3-full
**Android version:**
11 RKQ1.210503.001   MIUI 12.5.12 Stable   Android security 2021-12-02
**Phone model:**
Xiaomi 11 T Pro
**Home Assistant version:**
core-2021.9.7   (Not updated to version core-2021.12.6 because Tuya does not work, but a week ago it worked with the same version)
**Last working Home Assistant release (if known):**
core-2021.9.7
**Description of problem:**
Everything worked perfectly until an Android security patch was applied.
Now, if I try to connect to the local Wi-Fi network (https://192.x.x.32:8123) or with the external url (https://domain.duckdns.org:8123) the Androd app crashes.
In order to connect I need to enter the url in my browser.
I have deleted the data from the APP and the problem continues in all my devices.
Any idea how to fix it?
Are the developers of the Android APP dealing with the problem?
Thank you very much in advance
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Where are the requested logs from teh i ssue template? Please dont skip important information like that.  Also `https` over local IP will never work.  In order to continue troubleshooting we need logs.  Also what troubleshooting steps have you tried?

**Comment by M4TH1EU** [comment]
Hi, I have the exact same issue running A12 with december security patch aswell, I've tried retrieving the logs but I don't have access to the "Show and share logs" as the app is freshly installed, I've tried with a logcat viewer but there was hundreds of events in a matter of seconds so I didnt think it would help you. 
Please tell me how to send you the appropriate logs.

Happy new year!

**Comment by dshokouhi** [comment]
> Hi, I have the exact same issue running A12 with december security patch aswell, I've tried retrieving the logs but I don't have access to the "Show and share logs" as the app is freshly installed, I've tried with a logcat viewer but there was hundreds of events in a matter of seconds so I didnt think it would help you. Please tell me how to send you the appropriate logs.
> 
> Happy new year!

filter by `homeassistant` and then look at the errors that are usually marked as `E` if you see they all have the same failure....then any oen will do. If you are unsure you can still attach a snippet of the logs.

**Comment by M4TH1EU** [comment]
Here is what I found by filtering by homeassistant:

```
[01-03 16:54:11.716 1711:1818 I/ActivityManager]
Start proc 20976:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0/u0i156 for  {io.homeassistant.companion.android.minimal/org.chromium.content.app.SandboxedProcessService0:0}

[01-03 16:54:11.738 1711:1738 D/ConnectivityService]
requestNetwork for uid/pid:10348/19900 activeRequest: null callbackRequest: 3677 [NetworkRequest [ REQUEST id=3678, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10348 RequestorUid: 10348 RequestorPkg: io.homeassistant.companion.android.minimal] ]] callback flags: 0 order: 2147483647

[01-03 16:54:11.741 1711:2087 D/UntrustedWifiNetworkFactory]
got request NetworkRequest [ REQUEST id=3678, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10348 RequestorUid: 10348 RequestorPkg: io.homeassistant.companion.android.minimal] ]

[01-03 16:54:11.741 1711:2087 D/OemPaidWifiNetworkFactory]
got request NetworkRequest [ REQUEST id=3678, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10348 RequestorUid: 10348 RequestorPkg: io.homeassistant.companion.android.minimal] ]

[01-03 16:54:12.781 1711:4172 W/ActivityManager]
Scheduling restart of crashed service io.homeassistant.companion.android.minimal/org.chromium.content.app.SandboxedProcessService0:0 in 1000ms for connection

[01-03 16:54:12.979 21039:21039 F/DEBUG]
Cmdline: io.homeassistant.companion.android.minimal

[01-03 16:54:12.979 21039:21039 F/DEBUG]
pid: 19900, tid: 19900, name: android.minimal  >>> io.homeassistant.companion.android.minimal <<<

[01-03 16:54:13.000 1711:21042 W/ActivityTaskManager]
  Force finishing activity io.homeassistant.companion.android.minimal/io.homeassistant.companion.android.onboarding.OnboardingActivity

[01-03 16:54:13.017 1711:5446 I/ActivityManager]
Process io.homeassistant.companion.android.minimal (pid 19900) has died: fg  TOP 

[01-03 16:54:13.018 1711:2112 D/ConnectivityService]
releasing NetworkRequest [ REQUEST id=3678, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10348 RequestorUid: 10348 RequestorPkg: io.homeassistant.companion.android.minimal] ] (release request)

[01-03 16:54:13.019 1711:3034 I/WindowManager]
WIN DEATH: Window{b37053e u0 io.homeassistant.companion.android.minimal/io.homeassistant.companion.android.launch.LaunchActivity}

[01-03 16:54:13.019 1711:3034 W/InputManager-JNI]
Input channel object 'b37053e io.homeassistant.companion.android.minimal/io.homeassistant.companion.android.launch.LaunchActivity (client)' was disposed without first being removed with the input manager!

[01-03 16:54:13.023 1711:2212 I/WindowManager]
WIN DEATH: Window{17e051c u0 io.homeassistant.companion.android.minimal/io.homeassistant.companion.android.onboarding.OnboardingActivity}

[01-03 16:54:13.023 1711:2212 W/InputManager-JNI]
Input channel object '17e051c io.homeassistant.companion.android.minimal/io.homeassistant.companion.android.onboarding.OnboardingActivity (client)' was disposed without first being removed with the input manager!

[01-03 16:54:13.040 1711:1816 W/UsageStatsService]
Unexpected activity event reported! (io.homeassistant.companion.android.minimal/io.homeassistant.companion.android.launch.LaunchActivity event : 23 instanceId : 131586444)

[01-03 16:54:13.047 1711:1818 I/ActivityManager]
Start proc 19901:io.homeassistant.companion.android.minimal/u0a348 for top-activity {io.homeassistant.companion.android.minimal/io.homeassistant.companion.android.launch.LaunchActivity}

[01-03 16:54:13.081 19901:19901 V/GraphicsEnvironment]
ANGLE Developer option for 'io.homeassistant.companion.android.minimal' set to: 'default'

[01-03 16:54:13.081 19901:19901 V/GraphicsEnvironment]
ANGLE GameManagerService for io.homeassistant.companion.android.minimal: false

[01-03 16:54:13.234 1711:10999 I/ActivityTaskManager]
START u0 {cmp=io.homeassistant.companion.android.minimal/io.homeassistant.companion.android.onboarding.OnboardingActivity (has extras)} from uid 10348

[01-03 16:54:13.314 1711:1802 I/ActivityTaskManager]
Displayed io.homeassistant.companion.android.minimal/io.homeassistant.companion.android.onboarding.OnboardingActivity: +80ms

[01-03 16:54:13.423 1711:10999 W/InputManager-JNI]
Input channel object 'f88659e Splash Screen io.homeassistant.companion.android.minimal (client)' was disposed without first being removed with the input manager!

[01-03 16:54:13.501 1711:1805 W/ActivityTaskManager]
Activity top resumed state loss timeout for ActivityRecord{a010984 u0 io.homeassistant.companion.android.minimal/io.homeassistant.companion.android.onboarding.OnboardingActivity t-1 f}}

[01-03 16:54:13.867 1711:5446 I/InputDispatcher]
Monitor swipe-up (server) is stealing touch from [91e56c2 io.homeassistant.companion.android.minimal/io.homeassistant.companion.android.onboarding.OnboardingActivity (server), ]

```

**Comment by dshokouhi** [comment]
I don't see an error here. If you remove the filter and look at the time are there any tracebacks? Also what device is this? I see that the minimal version is being used.

**Comment by M4TH1EU** [comment]
Ok so by looking again at the logs without the homeassistant filter, i've found a lot of error coming from the android webview and this error stood out : 
```Version mismatch between V8 binary and snapshot.
#   V8 binary version: 9.6.180.21
#    Snapshot version: 9.1.269.36
# The snapshot consists of 47229 bytes and contains 1 context(s).
```

I had others issue related more or less to the webview and uninstalling updates of the app (webview) solved the issues for me.

Sorry if this was not related to OP's post.

**Comment by dshokouhi** [comment]
> I had others issue related more or less to the webview and uninstalling updates of the app (webview) solved the issues for me.

you actually are not the first person to report this, seems like some caching issue is hitting users here.

@Chicho976 can you try the steps above and if that fails try the start fresh steps: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by dshokouhi** [comment]
Closing as we had not heard back from the author
