### ISSUE TITLE
WearOS: Application crashes on startup

### ISSUE THREAD

**Issue by vveloso** [home-assistant/android#2090]
**Home Assistant Android version:** 2021.12.3

**Android version:** 10

**Android Wear version:** 2.35.0.325323493

**Phone model:** Huawei P20 Pro

**Watch model:** LG Watch Urbane

**Home Assistant version:** 2021.12.7

**Last working Home Assistant release (if known):** n/a

**Description of problem:** Android Wear application crashes on launch. Does not get past the splash screen.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
2021-12-30 13:05:26.697 15075-15075/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.homeassistant.companion.android, PID: 15075
    java.lang.NumberFormatException: For input string: "public int android.view.ViewConfiguration.getScaledScrollFactor()"
        at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
        at java.lang.Float.parseFloat(Float.java:459)
        at io.homeassistant.companion.android.util.RotaryEventDispatcherKt$scrollHandler$1.invoke(RotaryEventDispatcher.kt:29)
        at io.homeassistant.companion.android.util.RotaryEventDispatcherKt$scrollHandler$1.invoke(RotaryEventDispatcher.kt:21)
```

Full logs:
[ha-wearos-crash.log](https://github.com/home-assistant/android/files/7792904/ha-wearos-crash.log)

**Screenshot of problem:** n/a

**Additional information:**

The Android Wear application was fully configured using the Home Assistant Android application on the phone because my installation uses MFA.

The Home Assistant installation is still in its infancy. Only one light is configured there.

**Comment by dshokouhi** [comment]
hmm does this watch have a bezel?

**Comment by vveloso** [comment]
The watch does not have a working/rotary bezel if that's what you mean.
See: https://www.lg.com/us/smart-watches/lg-W150-lg-watch-urbane

Daniel Shokouhi ***@***.***> escreveu no dia quinta,
30/12/2021 à(s) 20:21:

**Comment by dshokouhi** [comment]
yup thats what I meant, thanks for the logs :)

**Comment by dshokouhi** [comment]
if you are willing and able to could you test the debug Wear APK from here?

https://github.com/home-assistant/android/actions/runs/1638577350

just make sure the app doesnt crash and no weird scrolling behavior :) it will install side by side the production version and wont impact it (even if its non-functional in its current state)

**Comment by vveloso** [comment]
Thank you @dshokouhi. I installed the debug version and can confirm that it started and presented the option to configure an instance. Scrolling behavior looked fine to me.

**Comment by vveloso** [comment]
One more thing @dshokouhi: I looked at #2092 and it looks like the call to `invoke()` on the `Method` instance returned by `getDeclaredMethod()` is missing. `toString()` is invoked directly on the `Method` instance, which will never produce the float value you're looking for.

Take a look at [the implementation of `ViewConfigurationCompat`](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/oreo-dev/compat/java/android/support/v4/view/ViewConfigurationCompat.java) for an example.

Maybe it is a good idea to use `ViewConfigurationCompat` instead? 😉

**Comment by dshokouhi** [comment]
> One more thing @dshokouhi: I looked at #2092 and it looks like the call to `invoke()` on the [`Method` instance returned by `getDeclaredMethod()`](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getDeclaredMethod-java.lang.String-java.lang.Class...-) is missing. `toString()` is invoked directly on the `Method` instance, which will never produce the float value you're looking for.
> 
> Take a look at [the implementation of `ViewConfigurationCompat`](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/oreo-dev/compat/java/android/support/v4/view/ViewConfigurationCompat.java) for an example.
> 
> Maybe it is a good idea to use [`ViewConfigurationCompat::getScaledVerticalScrollFactor`](https://developer.android.com/reference/androidx/core/view/ViewConfigurationCompat#getScaledVerticalScrollFactor(android.view.ViewConfiguration,%20android.content.Context)) instead? 😉 

Many people are using this current workaround while we wait for Google to add native rotary support. As of now this is just temporary and we are even using Google's recommendation here. If you feel it's better feel free to submit a PR, we are open source. For those of us with working bezels the code is working for us as is.

**Comment by vveloso** [comment]
The root cause is not about rotary bezels, feelings, or whether it is
better or worse. It's really a backward compatibility issue.

The vertical scrolling factor reading code, as it is written today, does
not work with older Android/Wear versions because the Java reflection API
is being used incorrectly. The mistake is easy to overlook but also easy to
fix.

I'll submit a PR next week.

Happy new year.

A sexta, 31 de dez de 2021, 17:20, Daniel Shokouhi ***@***.***>
escreveu:
