### ISSUE TITLE
Last Notification Sensor not updating

### ISSUE THREAD

**Issue by greghesp** [home-assistant/android#2096]
**Home Assistant Android version:**
2021.12.3-full

**Android version:**
12

**Phone model:**
Pixel 6 Pro

**Home Assistant version:**
2021.12.7

**Last working Home Assistant release (if known):**
N/a

**Description of problem:**
As discussed in Discord. Last notification sensor is not updating after the allow list change, due to missing/invalid if condition.

https://discord.com/channels/330944238910963714/562408603345092636/926333020884066314

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20211231-035857](https://user-images.githubusercontent.com/768908/147804086-b2a0c1b7-ebbf-42d2-8ceb-7f473096088e.png)
![Screenshot_20211231-035906](https://user-images.githubusercontent.com/768908/147804088-cc6d3ec4-aedf-438b-8918-609a6f23967a.png)
![Screenshot_20211231-041346](https://user-images.githubusercontent.com/768908/147804089-a10ea24d-3e0d-4e2a-829b-70cdd04ecf40.png)

**Additional information:**
https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt#L114-L115

**Comment by bhyatyab** [comment]
Looks like it's not reading the "allowe list". 

Only works if "disable allow list requirement" is selected

**Comment by dshokouhi** [comment]
> Looks like it's not reading the "allowe list".
> 
> Only works if "disable allow list requirement" is selected

yea it was a logic error fix has been submitted to account for an empty list alongside the disable setting
