### ISSUE TITLE
Last_notification not updating

### ISSUE THREAD

**Issue by Hellis81** [home-assistant/android#2100]
**Home Assistant Android version:**
2021.12.3-full

**Android version:**
11

**Phone model:**
Motorola G9 play

**Home Assistant version:**
2021.12.6

**Last working Home Assistant release (if known):**
I would say it was working yesterday or perhaps the day before that. 
I believe it was on the same version as I currently have.

**Description of problem:**

The last notification sensor is not updating anymore. 
According to the sensor it seems it has not been updated in at least a full day (I only have one day recording).

I have tried to reload the integration in integrations menu. 
I have force closed and reopened the app on one of the phones.
I have restarted one phone.
I have restarted Home Assistant.

I don't find anything in Home Assistants log that seems relevant.
The app logs has noting that seems related either

Other sensors seems to be working as it should, the GPS sensor works for sure and others seems to be working, such as:
![image](https://user-images.githubusercontent.com/61010215/147856921-c5aa18ad-bf33-454e-8b50-477bddf0615e.png)

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/61010215/147856970-8be4b787-0dd7-417e-972c-da12ec7c129f.png)

![image](https://user-images.githubusercontent.com/61010215/147856987-8421c141-1e9b-418f-a372-06de868ca67b.png)

**Additional information:**

**Comment by dshokouhi** [comment]
This is fixed in the latest beta via #2097 There was also a breaking change recently where we now enforce an allow list so if you did not have one and want things back to the way they were you will need to explicitly disable it in the sensor settings screen

**Comment by sveip** [comment]
Dear @dshokouhi, can you please elaborate on "you will need to explicitly disable it in the sensor settings screen", how do I do this? Is this on the phone or in HA?
