### ISSUE TITLE
Connexion slowdown S21 Android 12

### ISSUE THREAD

**Issue by Mick51** [home-assistant/android#2103]
**Home Assistant Android version:**
Version 2021.12.3.full
**Android version:**
Android 12
**Phone model:**
SM-G991B  Galaxy S21
**Home Assistant version:**
2021.12.7
**Last working Home Assistant release (if known):**

**Description of problem:**
Some connection slowdown on Galaxy S21 on Android 12 that I don't have on my Tab S7 on Android 11 .......
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Please be more descriptive and provide steps to reproduce and what troubleshooting steps you have tried already. There is not much to go by here.

**Comment by Mick51** [comment]
Hello in fact I found the problem, I had the DNS of the S21 which made a
redirection on dns.adguard.com.  By removing it everything is back to
normal.
Thanks

Le lun. 3 janv. 2022 à 01:26, Daniel Shokouhi ***@***.***> a
écrit :

**Comment by Mick51** [comment]
[image: Capture d’écran 2022-01-06 095934.jpg][image: Capture d’écran
2022-01-06 095953.jpg]

Hello I think I found a big problem at the level of the cycles which makes
this function useless because pit

Le lun. 3 janv. 2022 à 08:23, Daniel Shokouhi ***@***.***> a
écrit :

**Comment by dshokouhi** [comment]
> [image: Capture d’écran 2022-01-06 095934.jpg][image: Capture d’écran 2022-01-06 095953.jpg] Hello I think I found a big problem at the level of the cycles which makes this function useless because pit

if you tried to post a screenshot it failed so I have no idea what you are referring to

**Comment by Mick51** [comment]
![guyw](https://user-images.githubusercontent.com/40418405/148419239-b35b80da-1bd5-4426-b05e-a0218499b822.jpg)
![n79v](https://user-images.githubusercontent.com/40418405/148419246-994edf8f-b49c-4797-9d7c-34d5df677953.jpg)

**Comment by dshokouhi** [comment]
This has nothing to do with the android app ;)
