### ISSUE TITLE
Widget for starting conversation

### ISSUE THREAD

**Issue by anarchking** [home-assistant/android#2104]
**Is your feature request related to a problem? Please describe.**

Need a widget for starting conversation from ui
**Describe the solution you'd like**

**Describe alternatives you've considered, if any**

**Additional context**

Would be cool to see the whole conversation in the widget and one just for talking into with some kind of indication of processing and listening.

**Comment by dshokouhi** [comment]
You mean from the HA frontend? If so that is not possible because widgets cant display the webview which is where that button is. Google took that away a while ago.

**Comment by dshokouhi** [comment]
@anarchking could you please confirm what you are looking for in this widget? If your desire is to show a piece of the HA frontend then we will not be able to do that due to android limitation.

**Comment by anarchking** [comment]
Yes I was looking at a way to have a widget that's just a microphone icon and when you click it, it automatically does the same thing as if you were to click the three dots at the top right then click the start conversation button. I also think it would be cool to use that same icon widget to  click the button for in intercom but I feel like that should mostly be controlled and built in to HA not the app.

**Comment by dshokouhi** [comment]
Ya we can't do that sorry.

**Comment by jay-gates** [comment]
Is it possible to have a widget or shortcut that opens the companion app directly to the conversation feature, or perhaps have an Android intent that invokes the conversation feature? Conversation + Almond is great, but having it buried like it is now requires too many interactions to make it really useful vs. having a spoken wake-word.

**Comment by caladrien** [comment]
I see this closed. So is there now a chance to have a Mic Icon on Android home screen to start directly a conversation? 

Jay-gates:

> Conversation + Almond is great, but having it buried like it is now requires too many interactions to make it really useful vs. having a spoken wake-word.

Totaly agree with this!

**Comment by dshokouhi** [comment]
> Is it possible to have a widget or shortcut that opens the companion app directly to the conversation feature, or perhaps have an Android intent that invokes the conversation feature?

> So is there now a chance to have a Mic Icon on Android home screen to start directly a conversation?

if you would like to interact with the new assist feature you can create a [shortcut](https://companion.home-assistant.io/docs/integrations/android-shortcuts) to point to any lovelace path with `?conversation=1` appended to the end of the URL. So for example: `/lovelace/home?conversation=1`

**Comment by caladrien** [comment]
Ok, this brings me 99% to the target. If now the conversation would immediately start to listen it would be perfect. Still one click to much. Are there any other arguments accepted than "=1"?

**Comment by jay-gates** [comment]
For the record, when the page displays, with the Assist input box open, it is waiting for text input; the user still has to click on the "voice input" icon for it to start listening. I think there would need to be an additional parameter passed to the page to get it to start listening on opening (ex., ?conversation=1&listen=1). So this would be a front-end feature request.

**Comment by dshokouhi** [comment]
We will not reopen this. Frontend feature request go on the forums.
