### ISSUE TITLE
Home Assistant app crashes on load - Wear OS (Samsung Galaxy Watch 4 )

### ISSUE THREAD

**Issue by Juliafin** [home-assistant/android#2116]
**Home Assistant Android version:**
2022.1.1
**Android version:**
10
**Phone model:**
Samsung Galaxy S20 Ultra
**Home Assistant version:**
N/A - My Home assistant instance is on the way!
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
Home
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

Hello everyone! I'm a software engineer just getting into home automation and I'm getting my home assistant hardware next week. In the meantime, I was playing around with the android app on both my smartphone and galaxy watch 4. Unfortunately, I noticed that the watch version (running latest wear OS) crashes on startup. I've updated it several times, uninstalled and reinstalled with the same result. I'm not really sure how to obtain a log from the smart watch but maybe someone can post below how to troubleshoot this issue, or maybe there is some other thing I haven't tried. Also, I would be interested in getting into android development and helping with the home assistant project. Thanks for any assistance!

**Comment by SkechyWolf** [comment]
Have you used android studio before?

I'm probably not the best help right now as I'm not home but I'll see what I can do

**Comment by dshokouhi** [comment]
> Also, I would be interested in getting into android development and helping with the home assistant project. Thanks for any assistance!

We should hopefully have everything laid out in the project readme to get started :) If you get stuck or have any questions you can also reach out on Discord in #devs_mobile_apps

**Comment by leroyboerefijn** [comment]
@Juliafin, do you still suffer from this? I also have the Galaxy Watch 4 and have never had the app crash on opening

**Comment by rerospo** [comment]
Ciao a tutti, ho il gear 4 classic, mi capita dopo che si collega alla pagina di login, inserendo il nome e password nel'orologio mi appare una schermata con "guarda il registro e sotto SM-R895F, se ritendo appare per un momento attendi la registrazione dell'applicazione in corso e poi ritorna indietro. Dal telefono e web non mai avuto problemi. Ho un vecchia versione di HA, ma che non ha dato mai problemi. Grazie in anticipo del Vostro aiuto\

**Comment by dshokouhi** [comment]
> Ciao a tutti, ho il gear 4 classic, mi capita dopo che si collega alla pagina di login, inserendo il nome e password nel'orologio mi appare una schermata con "guarda il registro e sotto SM-R895F, se ritendo appare per un momento attendi la registrazione dell'applicazione in corso e poi ritorna indietro. Dal telefono e web non mai avuto problemi. Ho un vecchia versione di HA, ma che non ha dato mai problemi. Grazie in anticipo del Vostro aiuto\ 

We cannot help you unless it's in English

**Comment by rerospo** [comment]
Hello everyone gear 4 classic, it happens to me after I connect to the login page, by entering the name and password in the watch I register, a screen appears with "look at the record and under SMR895F, it appears again for a moment wait for the registration of the application in progress and then back. From phone and web never had problems. I have an old version of HA, but it never gave any problems. Thanks in advance for your help \

**Comment by rerospo** [comment]
Hello everyone gear 4 classic, it happens to me after I connect to the login page, by entering the name and password in the watch I register, a screen appears with "look at the record and under SMR895F, it appears again for a moment wait for the registration of the application in progress and then back. From phone and web never had problems. I have an old version of HA, but it never gave any problems. Thanks in advance for your help \

**Comment by dshokouhi** [comment]
> a screen appears with "look at the record and under SMR895F

I am not really sure what you mean here, can you share a screen shot? Nothing in our app says "Look at the record"



> it appears again for a moment wait for the registration of the application in progress and then back.

what do you mean by "and then back"



> I have an old version of HA

what version?

**Comment by dshokouhi** [comment]
Closing due to lack of response
