### ISSUE TITLE
Toggle-able entities not toggling

### ISSUE THREAD

**Issue by kg333** [home-assistant/android#2120]
**Home Assistant Android version:**
2022.1.1-full
**Android version:**

**Phone model:**
Pixel 5a
**Home Assistant version:**
core-2021.12.3
**Last working Home Assistant release (if known):**
Unknown
**Description of problem:**
Toggles on entities cards no longer toggle in the Android app.  For example, on the web front end, if you click on the toggle on the right side of an automation entity, the automation turns on and off.  Clicking on the automation name or icon brings up the Info dialog.

Previously, the Android app behaved the same way.  Now, clicking on the toggle also brings up the Info dialog instead of turning on and off.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
N/A

**Screenshot of problem:**
Tricky to screenshot, but I took a video capture: https://imgur.com/a/YMoHH5p

**Additional information:**

**Comment by dshokouhi** [comment]
Update HA core to 2022.1.8 to fix this issue

**Comment by kg333** [comment]
Updating to core-2021.12.8 does fix the issue.
