### ISSUE TITLE
Last app sensor nearly always reads as Home Assistant app

### ISSUE THREAD

**Issue by zmarties** [home-assistant/android#2126]
**Home Assistant Android version:**
b7e4fb7b9b4b2ada30c23eeb42c255b7f082e619

**Android version:**
varies

**Phone model:**
varies

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem:**

The last app sensor is implemented using the usage stats that Android produces.  However, it simply takes the last app that was reported as being in use.

On the devices I've run this on, this has no relationship to the app that the user thinks they are using, and in fact nearly all the time the last used app reported by the sensor is the Home Assistant app itself.  This makes perfect sense - in order to send out the sensor data, the Home Assistant app has been woken up (and hence is in use in the background), and thus has the most recent usage stats record.  I guess there is some asynchronisity to the usage gathering, since just occasionally another app is given as the last used one (perhaps it depends on what other apps are running at the same time, and whether they also do lots of background processing).

Looking via Git, I can see that during development this sensor was changed from returning the app package, to returning the app label if available, only falling back to the app package if not.  I can understand that that gives a better display string, but it's fundamentally flawed; the app label is not unique - for example I have multiple apps on my phone that call themselve "Maps" or "Camera".  For this sensor to be useful, it needs to return the package name which has uniqueness that allows scripts to be written knowing that they have identified the correct app.  By all means also include additional information about the app as additional attributes, such as the app version, the display name, the app publisher etc.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
> The last app sensor is implemented using the usage stats that Android produces. However, it simply takes the last app that was reported as being in use.\n\nOn the devices I've run this on, this has no relationship to the app that the user thinks they are using, and in fact nearly all the time the last used app reported by the sensor is the Home Assistant app itself. This makes perfect sense - in order to send out the sensor data, the Home Assistant app has been woken up (and hence is in use in the background), and thus has the most recent usage stats record. I guess there is some asynchronisity to the usage gathering, since just occasionally another app is given as the last used one (perhaps it depends on what other apps are running at the same time, and whether they also do lots of background processing).

It's reporting just fine for me running in the background

![Screenshot_20220108-073337.png](https://user-images.githubusercontent.com/1634145/148650179-157902c4-4175-4a40-9a29-8b0a66e64588.png)

If you want to include more info we can do that but that is a feature request and not a bug.

It's also really hard to troubleshoot without knowing what device this is. For example of you run a custom ROM they normally don't run precise API data.

**Comment by zmarties** [comment]
I don't use devices with custom ROMs.

This behaviour shows on on all the devices I've tried, including the latest stock Android 12, on a Pixel 3a.

I saw your screen shots were from a Pixel 6 Pro - is that the only device you have tested this working on?  I wonder whether such a high end device has more cores, so the usage stats may well be different if truly more apps can be running simultaneosly on different cores.

**Comment by dshokouhi** [comment]
> I saw your screen shots were from a Pixel 6 Pro - is that the only device you have tested this working on? I wonder whether such a high end device has more cores, so the usage stats may well be different if truly more apps can be running simultaneosly on different cores.

It also works as expected on my Oculus quest

![Screenshot_20220108-080621.png](https://user-images.githubusercontent.com/1634145/148651222-5e2851a0-0646-4806-94c5-e6d78c2ab46c.png)

**Comment by zmarties** [comment]
I've put some extra diags in to a local build of the code.  I think the sensor should probably be using lastTimeVisible rather than lastTimeUsed.  (I'm also worried that the maxByOrNull will have random behaviour if two apps have the same lastTime value - I've just seen an example where there were 1 apart, so tiny differences are possible, possibly zero). Got to go now, but will try and investigate a bit more later.

**Comment by dshokouhi** [comment]
> I think the sensor should probably be using lastTimeVisible

https://developer.android.com/reference/android/app/usage/UsageStats#getLastTimeVisible()

If we decide to switch this variable then lets try to keep it backwards compatible because this attribute was added in API 29 but the sensor is shown to users on Android 6 or higher. With that said this change would probably work better and not have the `maxByOrNull` issue that you have seen.

Also based on the description from `lastTimeUsed` I am not sure why the HA app shows up as often as it does for you in the sensor. Now if you launch the HA app then yes I would expect to see it here but when the app is in the background we should not be seeing it as the Activity should not have been used for sometime.

https://developer.android.com/reference/android/app/usage/UsageStats#getLastTimeUsed()

One thing about this sensor is that it is poll based as there was no intent to use to get it to update immediately. Ideally the sensor will update as soon as an app is launched :) For these sensors its best to ensure that the app has background access but also the more sensors that are enabled the more often updates will trigger to keep it more up to date.

Appreciate you taking the time to look into this :)

**Comment by dshokouhi** [comment]
I found some time to test out `lastTimeVisible` and the results are not as consistent for me when switching apps. I would personally expect every time I take a screenshot of the sensor screen then only the HA app would be visible but it is not.

![image](https://user-images.githubusercontent.com/1634145/152618252-23ec9233-139f-4778-ab30-e97d63e149b2.png)

![image](https://user-images.githubusercontent.com/1634145/152618260-51fda118-a045-48f6-8945-24bccb57c35c.png)

When I switch back to using `lastTimeUsed` everything goes back to reporting as I would expect.

![image](https://user-images.githubusercontent.com/1634145/152618439-f762aa11-7b73-4ed5-aa77-362ed1bd81f6.png)

Also going to revert back to package name for the state to make it more unique.

**Comment by RulerOf** [comment]
> It also works as expected on my Oculus quest

@dshokouhi does this still work for you? I try to enable this sensor on my Quest 3S and it complains about permissions and just loads the general settings page; like it's trying to dive into a menu hierarchy that doesn't exist.

**Comment by straxhaber** [comment]
@RulerOf @dshokouhi did you find a way to enable the required permission? I keep getting directed to the general Settings page as well.

**Comment by RulerOf** [comment]
@straxhaber no, I never got this to do what I wanted.
