### ISSUE TITLE
Notifications doesn't close on back button press

### ISSUE THREAD

**Issue by lindhe** [home-assistant/android#2129]
**Home Assistant Android version:** Version 2022.1.1-full

**Android version:** 12

**Phone model:** Samsung Galaxy S21

**Home Assistant version:** 2021.12.7

**Last working Home Assistant release (if known):** none

**Description of problem:** The notification tray for persistent notifications do not close if I press the back button on my phone. I can only close it by pressing the little arrow  in the top right.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):** n/a

```

```

**Screenshot of problem:**
![screenshot](https://user-images.githubusercontent.com/7773090/148661614-a48431ae-e8e5-41d2-aac9-4e36300eefa9.jpg)

**Additional information:** Expected behaviour is for any panel that pops-up or slides out like that to close on a back button press.

**Comment by dshokouhi** [comment]
does this issue exist in chrome for android?

**Comment by lindhe** [comment]
Don't know. I don't want to accept the chrome terms of service, so I cannot try it.

**Comment by dshokouhi** [comment]
> Don't know. I don't want to accept the chrome terms of service, so I cannot try it.

Well we need to test this to make sure. Android WebView is actually based off of chrome. Right now we are trying to determine if its a frontend issue or not and thats the only way to tell. Maybe try another mobile browser?

**Comment by dshokouhi** [comment]
Found time to test this myself, this is a frontend issue. Please file an issue with HA frontend making sure to complete their template.

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=bug_report.yml
