### ISSUE TITLE
WearOS + Samsung Digital Dashboard Watch Face Sensor

### ISSUE THREAD

**Issue by pironic** [home-assistant/android#2135]
**Is your feature request related to a problem? Please describe.**

Not so much a problem as a nice to have. I utilize one of the default Samsung provided watch faces on my Galaxy Watch 4.0. [Digital Dashboard](https://galaxystore.samsung.com/geardetail/com.samsung.watchface-digitaldashboard) allows apps to hook into the watch face and show stats on the front of the watch face.

**Describe the solution you'd like**

 I've seen apps such as Voice Recorder, Google Fit, and of course Samsung Health show metrics in this watch face. What would be great is if I could select any of my Home Assistant sensors on my watch face. I imagine it could be to select a single "Home Assistant Sensor" from the watch face customizer, then select which sensor should be viewable via the home-assistant companion app. 

**Describe alternatives you've considered, if any**

No alternatives considered.

**Additional context**

https://galaxystore.samsung.com/geardetail/com.samsung.watchface-digitaldashboard

We might need to specify a range in the home-assistant app as well... if you pick a metric like thermostat it might make sense to have it a range between 15-25. Regardless of what sensor is selected it can act as a shortcut to the home-assistant wear os app.

**Comment by dshokouhi** [comment]
As this is a wear OS device I dont think we should do anything specific for a single watch/manufacturer. I think in this case a custom HA watch face makes the most sense so all users can benefit.  I dont even see developer documentation for this watch face, seems the apps mentioned are system installed apps which makes sense for them to offer those.

**Comment by pironic** [comment]
I'm not opposed and in-fact a Home-Assistant Watch Face could be great... I'm not sure about design though. The power of Home-Assistant is the versatility to create a dashboard unique to your own home with all of the metrics and control you want. Extending that to a watch face is idyllic but difficult. 

Thoughts on renaming this issue to something along the lines of "custom ha watchface"? maybe we should just kill this one and make a new one?

**Comment by pironic** [comment]
one additional note... i found this post on the samsung developer forum that has a samsung rep giving instructions on how to hook into this particular watch-face: https://forum.developer.samsung.com/t/recreating-digital-dashboard-watch-face/17681/3

**Comment by jpelgrom** [comment]
That forum post suggests that the watch face supports standard Wear OS complications, which could be supported by the app. Not sure if that is only for the one below the current time or also for the ranges on the edge of the display, do you see any non-Google or -Samsung apps in the settings for those?

**Comment by pironic** [comment]
I didn't realize Complications were a non-samsung thing... i dont have a lot of apps on my watch (home-assistant is among a very elite list)... If you know of any apps that have any complications in them, I could install to verify.

**Comment by dshokouhi** [comment]
> Thoughts on renaming this issue to something along the lines of "custom ha watchface"? maybe we should just kill this one and make a new one?

This might actually be a duplicate of https://github.com/home-assistant/android/issues/1898

**Comment by pironic** [comment]
The deeper I get, the more I agree. This appears to be a duplicate. I will close. :) 

Thank you for your help to both of you.
