### ISSUE TITLE
Dark mode doesn't display integration screen correctly

### ISSUE THREAD

**Issue by hdsheena** [home-assistant/android#2150]
**Home Assistant Android version:**

**Android version:**

**Phone model:**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem:**

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

![Screenshot_20220116-074910](https://user-images.githubusercontent.com/1909814/149667182-aa406bc6-b29c-47c0-8c25-e44ca6484595.png)

**Additional information:**

When trying to add a tuya integration , the text is hidden in dark mode.

**Comment by dshokouhi** [comment]
Does this happen in chrome for Android?

**Comment by dshokouhi** [comment]
And what happened to the issue template? All important info is missing here.

**Comment by hdsheena** [comment]
Sorry, I submitted from mobile and I guess it didn't pre populate.. I'll load it up on my pc later and fix it

**Comment by dshokouhi** [comment]
> Sorry, I submitted from mobile and I guess it didn't pre populate.. I'll load it up on my pc later and fix it

what about my first question, testing on chrome for android?

**Comment by hdsheena** [comment]
In trying to load in chrome on android, it will spin and never bring up the modal window. It does the same on chrome on my mac, and other integrations load with the helper text visible, so now I suspect my Tuya integration/HA is the problem, not the app! So sorry for wasting your time!
