### ISSUE TITLE
Tracking / GPS Position not working since Android 12 update

### ISSUE THREAD

**Issue by pinkfloydFR** [home-assistant/android#2152]
Hi,

For long time, have not problem with android phone tracker ( Samsung S20+ ans Samsung S10+ )

But since Android 12 update, it's not working on both phone

My son phone, in Android 11 continue working without problem.

**Comment by thombreeder** [comment]
Same issue, but it seems that only value of the device_tracker isn't updating. 
The geocoded_location sensor seems to be working and update the correct location

**Comment by dshokouhi** [comment]
https://companion.home-assistant.io/docs/troubleshooting/faqs#location-is-not-updating-in-android-app

First check these steps then if that fails we need the logs. Also what happened to the issue template? All the important requested information is missing here. Please grab the template from a new issue and copy it here with all information filled in so we can help.

**Comment by pinkfloydFR** [comment]
Sorry for the lack of information, will do it after my reunion !

**Comment by pinkfloydFR** [comment]
Ensure the app has location permissions granted, all the time. (Users on Android 12 will need to ensure Precise location is given during the prompt)
**-> GOOD**

Ensure that location (GPS) is enabled on your device.
**-> GOOD**

Turn off battery optimizations for the app.
**-> GOOD**

Under Configuration > Companion App > Manage Sensors ensure that the following Location Sensors are enabled: Background Location, Location Zone and Single Accurate Location
**-> !! OUPS, the the three are disabled, enalbed it, have the day for testing... !!**

**Comment by dshokouhi** [comment]
Closing issue as the location sensors were disabled, if you still an encounter an issue please file a new issue and make sure to fill out the issue template along with providing the requested logs.

**Comment by Yarninator** [comment]
I have the same problem. Device_tracker is not updating while the geocoded_location is correct. I have checked all the steps mentioned above and it still doesn't update.
Everything worked last month but stopped working since a few weeks.

**Comment by Yarninator** [comment]
Seems to be solved after restarting the android devices.
