### ISSUE TITLE
Allow to open whitelisted urls within the app

### ISSUE THREAD

**Issue by dannyyy** [home-assistant/android#2159]
**Is your feature request related to a problem? Please describe.**

1. I like to protect my Home Assistance with an additional layer of security. This could be either a reverse proxy or a cloud service (Cloudflare Access). In both cases new visitors of homeassistant.mydomain.com must authenticate against e.g Google, Azure AD, ...
In this case the Android app opens the default browser, which does not share application data such as cookies with this app. Therefore I'm successfuly logged in in the browser but not in the app.

2. Website which are embedded through iframes have an additional layer of authentication.
In this case the redirect leads to a ERR_BLOCKED_BY_RESPONSE because all major authentication provider force the X-Frame-Options: DENY header.

**Describe the solution you'd like**

1. Allow to redirect within the app after opening the app to have the authentications cookies available. Must be tested whether service workers were an additional obstacle, but should not.

2. Allow to open links (e.g. markdown card) inside the app. This would allow to open the protected website and to authenticate. Because it's not in a iframe the site is not blocked and the cookies properly set afterwards.

**Describe alternatives you've considered, if any**

- Share cookie states with the default Andriod browser or just Chrome ;)
- Configure webview to ignore such headers
- Any other solution that supports the described scenarios.

Maybe configurable as a additional option to not change the default behavior and only for experts.
Urls could be whitelisted to just allow those for the respective use case.

**Additional context**

If neccesary I'm happy to provide further information or to get involved to provide such a demo environment to test.

**Comment by dshokouhi** [comment]
Duplicate of #2001 and #1438

In the future please do not combine mutliple requests into one, instead create a separate request for each one after checking existing open/closed issues

**Comment by dannyyy** [comment]
@dshokouhi Unfortunately you have closed my issue and referenced to one unrelated #2001 and one partially related #1438 issue.

I read your answers in the referenced issues and guess reverse proxy especially with authentication capabilities are not your special subjects. And they don't have to be.

I proposed a (simple) solution to overcome the issues. And they have to be fixed in the app.

First of all, webview is up to date and similar apps handle the case in a way I proposed. To be honest basic auth and similar browser related mechanism have nothing to with my mentioned issue.
I just started a request to open links within the app even they have another domain.

With this workaround, a way will exist to "pre-authenticate" protected websites by clicking a link a do the login. After that the iframe has no issue because all the relevant cookies are available and sent.

I appreciate if people ask for additional explanation if they do not understand a subject in deep. Just closing and linking any non related issues is rude.

**Comment by dshokouhi** [comment]
In #1438 it is mentioned:

```
Allow to open links (e.g. markdown card) inside the app. This would allow to open the protected website and to authenticate. Because it's not in a iframe the site is not blocked and the cookies properly set afterwards.
```

In your first point you mention:

```
In this case the Android app opens the default browser, which does not share application data such as cookies with this app. Therefore I'm successfuly logged in in the browser but not in the app.
```

As both are stating the app needs to handle it inside without opening another browser they are the same and thus a duplicate.

Regarding #2001 I must've misunderstood I apologize but its also the reason why we ask requests to get split up so we don't talk about multiple things at once.



> 2\. Allow to open links (e.g. markdown card) inside the app. This would allow to open the protected website and to authenticate. Because it's not in a iframe the site is not blocked and the cookies properly set afterwards.

Once in the HA frontend any link that is not part of the domain will open in a new browser. We do not have any tabs nor maintain browsing history in the webview. It is meant to purely show the HA frontend and any link outside of that should not open in the app.


> Maybe configurable as a additional option to not change the default behavior and only for experts.
> Urls could be whitelisted to just allow those for the respective use case.

Having these advanced options will confuse new users and lead to more bug reports from users changing things they dont understand so its not a good idea here.

**Comment by dannyyy** [comment]
Thank you @dshokouhi for the feedback.

I have an additional idea. If you think this approach is feasible then I will create a new feature.
Could you offer in the Android app configuration a debug flag? Which allows debugging the app through Chromes dev tools?
https://developer.chrome.com/docs/devtools/remote-debugging/webviews/

I guess even I provide a working  PR for any of this requests it's unlikly that they get acceppted. Maintaining a fork is cumbersome and only the last I want to do. One official and a second that address more advanced users and security concerns.

**Comment by dshokouhi** [comment]
> Could you offer in the Android app configuration a debug flag? Which allows debugging the app through Chromes dev tools?

I think thats fine, normally today we ask users to load a debug build to do chrome remote debugging. This only impacts the frontend and the setting will not available until after the user logs in as we will need to place it in settings.
