### ISSUE TITLE
Provide a debug flag setting to enable UI debugging

### ISSUE THREAD

**Issue by dannyyy** [home-assistant/android#2162]
**Is your feature request related to a problem? Please describe.**

Enable the possibility to debug the UI through the Chrome DevTools in the official app build.

**Describe the solution you'd like**

Offer a new setting inside the app to toggle debug state on and off.

**Describe alternatives you've considered, if any**

**Additional context**

Idea was discussed in #2159 and evaluated as feasible.

**Comment by dshokouhi** [comment]
@dannyyy just for clarity based on your [comment](https://github.com/home-assistant/android/issues/2159#issuecomment-1016138056) were you planning on creating a PR for this request? Just want to avoid conflicting PRs if thats the case :)
