### ISSUE TITLE
Companion App as Rhasspy Satellite

### ISSUE THREAD

**Issue by erd82** [home-assistant/android#2178]
**Is your feature request related to a problem? Please describe.**

My problem is that I have no adequate satellites for my Rhasspy installation and I don't like to have more devices / installations either which I have to maintain on top. Ideally I would like to reuse the existing devices, such as my mobile phone, wall mounted tablet or my smart watch.

**Describe the solution you'd like**

[Rhasspy ](https://rhasspy.readthedocs.io/en/latest/)is an excellent offline voice assistant for those who don't want their private data (e.g. conversations, personal voice, etc.) stored in the cloud. Rhasspy can be already installed as an add-on to the Home Assistant host (or as standalone) which acts as a server.

It would be amazing, **if the Home Assistant Companion app could act as a Rhasspy satellite** so that your mobile, your wall mounted tablet or your smart watch can easily take spoken commands and forward this to the Rhasspy server.

This would be a perfect complement for all people who actually like to have a voice assistant, but **only offline**. And you wouldn't need to install an additional app, but just configure Home Assistant Companion app for Rhasspy.

**Describe alternatives you've considered, if any**

I am already following [rhasspy-mobile-app on github](https://github.com/razzo04/rhasspy-mobile-app) for more than a year now. The idea is great, but the app is not really usable for production. The current version is quite buggy and unfortunately nothing moves forward. 

Unfortunately I'm not developer enough to contribute to the development. Please let me if I can do anything else.

**Additional context**

**Comment by dshokouhi** [comment]
Looking at the docs the definition of a satellite is a device with the server running like a Raspberry Pi. The app linked seems to be something very specific and not something we should consider for the app. The app already offers a way to perform TTS on the speech via notifications.

https://companion.home-assistant.io/docs/notifications/notifications-basic/#text-to-speech-notifications

What you want to do sounds like a better job for Tasker than the app itself.

**Comment by erd82** [comment]
Hello @dshokouhi, 

NO NO! Rhasspy satellites are not only limited to Raspberry PIs. I trust you only read this page [Server with Satellites](https://rhasspy.readthedocs.io/en/latest/tutorials/#server-with-satellites) (on the Rhasspy documentation).
![image](https://user-images.githubusercontent.com/63564291/150637386-58dd77b6-89aa-4fb6-96ef-63e88ee3ce31.png)

Check here: https://github.com/koenvervloesem/awesome-rhasspy
On this page you can see that there are also other **[Custom satellites](https://github.com/koenvervloesem/awesome-rhasspy#custom-satellites)** beside the standard [Server with Satellites](https://rhasspy.readthedocs.io/en/latest/tutorials/#server-with-satellites)
- [ESP32 Rhasspy Satellite](https://github.com/Romkabouter/ESP32-Rhasspy-Satellite)
- [rhasspy-mobile-app](https://github.com/razzo04/rhasspy-mobile-app)

Currently there is no suitable way for "ready-to-use-hardware" to run a Rhasspy satellite. Instead you have to assemble different hardware components and possibly print / invent your own case (it shouldn't look like a prototype).

Why not using the existing devices like mobile phone, tablet or your smart watch?

But finally I also understand, that you need to concentrate on the core features of companion app.

Cheers
