### ISSUE TITLE
Feature request - transparent background for widgets

### ISSUE THREAD

**Issue by philipmjones** [home-assistant/android#2181]
First of all, huge thanks for this fantastic app. It makes control of home assistant so much faster and smoother, particularly using widgets on my phone screen.

The only gripe - and it's not a biggie - is that when I add a Home Assistant widget to my phone (Pixel 4a, latest version of Android) it has a solid white background, which sticks out and looks a lot less elegant than the other icons and widgets which have transparent backgrounds.

Please could you add an option in the widget settings to make the background transparent?

![Screenshot_20220121-202037](https://user-images.githubusercontent.com/6922930/150595201-0583d6c4-e3ba-43e6-9d9f-384a3f6a2608.png)

Thanks!

**Comment by dshokouhi** [comment]
duplicate of #1852 currently the background respects the device/app theme so either white or black.
