### ISSUE TITLE
WearOS - Support icons in templates

### ISSUE THREAD

**Issue by brewston** [home-assistant/android#2191]
**Is your feature request related to a problem? Please describe.**
No, feature request

**Describe the solution you'd like**
It would be more efficient, from a screen real estate perspective, if the template screen would allow icons. eg if I have a template for my hallway thermostat a thermometer icon is neater than the words describing the value.

**Describe alternatives you've considered, if any**
I've in dev tools to see if there is a way a template will natively render an icon and I can't seem to find it :(

**Additional context**
N/A

**Comment by jpelgrom** [comment]
I don't really use HA templates so I'm not sure if this would be possible, but as a potential workaround for now you can use emoji because that is also considered text 🌡️

**Comment by dshokouhi** [comment]
I think the emojis would be the right way to go. If we do anything in the app that means we are going to modify the output of the template. Currently the app displays whatever it is you see in the template editor. By using emojis the app wont have to override any characters.

**Comment by brewston** [comment]
Ah, that works for me :) and keeps it simpler all round. Closing.
