### ISSUE TITLE
Add Wear OS next_alarm sensor

### ISSUE THREAD

**Issue by deliantwo** [home-assistant/android#2208]
**Is your feature request related to a problem? Please describe.**

I would like to use the next_alarm sensor in some automation. Since I use the alarm on my smartwatch there's no alarm on my phone.

**Describe the solution you'd like**

Add the next_alarm sensor on the wear app

**Describe alternatives you've considered, if any**

I've heard you can do something with tasker but I would like a first-party solution

**Additional context**

**Comment by dshokouhi** [comment]
This will come sometime after #2033 has been finished and merged. After that we will be reviewing all phone app sensors and adding the ones which work. We have to get a UI for enabling sensors and adding sensor settings before we can add this one.

**Comment by janstadt** [comment]
Any updates on new sensors being added for wearos devices @dshokouhi now that #2033 has been merged? Would love to get the geo_location sensor on the GW4 going. :-)

**Comment by dshokouhi** [comment]
For this sensor I think it may be ok for initial release not to have sensor settings because on a wearable an allow list will not be a good experience. Hopefully it won't result in too much unwanted data but we will need to see how it fairs for users.
