### ISSUE TITLE
Pushing config for user to mobile devices for each person

### ISSUE THREAD

**Issue by fribse** [home-assistant/android#2209]
**Is your feature request related to a problem? Please describe.**
I have seperate lovelace interfaces set up for different users and devices. The current method works, but is extremely clumsy.
I have removed all menus from the phone (kiosk mode) as it takes up a lot of 'real estate' on small screens (kiosk mode).
So to set / change their dedicated lovelace interface, I have to disable kiosk mode, set the user as administrator, set the dedicated lovelace ui as 'standard' for this device, doing it twice, both for local access and for nabu casa access, then activate the kiosk mode again, and then remove the administrator role.

**Describe the solution you'd like**
If it instead was that the default webpage, device name, sensor settings was settable for each user device, it would simplify setup, and make it settable from 'admin' instead of it being a user setting.

**Describe alternatives you've considered, if any**
A proper MDM would be even better, but that's a lot more work.

**Additional context**

**Comment by dshokouhi** [comment]
Most if not all of these changes need to be done in HA core first before the app can consider it.

**Comment by dshokouhi** [comment]
Actually all of this needs to be done in HA core first before the Android app can consider doing it. Closing this request until that gets done first.
