### ISSUE TITLE
Add fans as toggleable items (f.e. for whirlpools :)) for Wear OS

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [home-assistant/android#2211]
**Is your feature request related to a problem? Please describe.**
No Problem.

**Describe the solution you'd like**
Add fans as toggleable items, to Wear OS since I would like to control my whirlpool fans from my watch (Balboa integration)

**Describe alternatives you've considered, if any**

It would be possible to create a template switch, but it would be nicer to add this natively.

**Additional context**
I guess it would be easy to add this items, since fans are able the same way as switches with toggle on/off.

Thanks! ❤️ 

Edit: Hope this is the right repo for this?

**Comment by dshokouhi** [comment]
> Edit: Hope this is the right repo for this?

Yup this is the correct repo 🙂

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thank you so much!! ❤️
