### ISSUE TITLE
Can you provide the wear OS APK? Google in China is not friendly

### ISSUE THREAD

**Issue by mengyu-520** [home-assistant/android#2214]
Can you provide the wear OS APK? Google in China is not friendly！

**Comment by dshokouhi** [comment]
The APK is on the GitHub release tab

**Comment by mengyu-520** [comment]
Whether making APK was found, to provide accurate APK

**Comment by mengyu-520** [comment]
@dshokouhi Whether making APK was found, to provide accurate APK

**Comment by dshokouhi** [comment]
> @dshokouhi Whether making APK was found, to provide accurate APK

I'm sorry this makes no sense. I already said where the APK is.

**Comment by mengyu-520** [comment]
@dshokouhi Hello, I am the oppo based watch 2, does not support wear OS APK installation, whether can extract wear OS APK into Android APK?

**Comment by dshokouhi** [comment]
@mengyu-520 if you cant install an APK on the watch then we wont be of help, sorry.
