### ISSUE TITLE
Companion app with Nabu Casa URL

### ISSUE THREAD

**Issue by ACJUK** [home-assistant/android#2220]
**Home Assistant Android version:**
2022.1.1-full

**Android version:**
12

**Phone model:**
Google Pixel 3a

**Home Assistant version:**
core-2021.12.10

**Last working Home Assistant release (if known):**
Not known

**Description of problem:**
When logging into the app and using a Nabu Casa URL, the process goes to login and then the dashboard without asking for the phone model and asking for location services to be turned on.  This means that the mobile app integration doesn't get installed and none of the tacking entities get created

In turn, this also means that the Companion App settings option doesn't appear under Configuration.

I've tried this on 2 different servers.  One outside my network and one inside.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
This isn't necessarily related to Nabu Casa yet. We still need the logs as mentioned in the issue template. I can tell you that I have setup and used Nabu Casa on other devices with success as well so the issue still might be something else.

**Comment by ACJUK** [comment]
[logcat_01-31-2022_21-55-34.txt](https://github.com/home-assistant/android/files/7974515/logcat_01-31-2022_21-55-34.txt)

I ran the command, went through setting up, and browsed to one of the pages that comes up blank.  I had a look but I have no idea what I'm looking at, I'm afraid!

**Comment by dshokouhi** [comment]
we need to see the logs from when you register with the app using the external URL please, so clear data and then login to the app using the URL that doesn't work and attempt to go to configuration > Companion App and then get the logs for us please

**Comment by ACJUK** [comment]
[logcat_01-31-2022_22-04-16.txt](https://github.com/home-assistant/android/files/7974570/logcat_01-31-2022_22-04-16.txt)

Sorry, I thought that's what I did.

This one, I started recording, switched to the companion app, entered the Nabu Casa URL, logged in, went to config.  Stopped recording

**Comment by dshokouhi** [comment]
Noticed the following post on the forums

https://community.home-assistant.io/t/new-android-device-does-not-keep-connection-info-between-uses-with-the-companion-app/382766/25?u=dshokouhi

Can you check what URL you used @ACJUK did you by chance include the full URL to a lovelace path instead of just the base nabu casa URL? it should end in `nabu.casa`
