### ISSUE TITLE
Addons repository button cover the last item

### ISSUE THREAD

**Issue by brusarp** [home-assistant/android#2221]
**Home Assistant Android version:**
2022.1.1-full

**Android version:**
9

**Phone model:**
Samsung Galaxy Note 8

**Home Assistant version:**
2021.12.10

**Last working Home Assistant release (if known):**

**Description of problem:**
The button to open the addons repository cover the addons under him that is difficoult to view/press

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20220201-073149_Home Assistant.jpg](https://user-images.githubusercontent.com/14950532/151923931-89c816bc-d1d0-4e5f-a897-2b417cdf697e.jpg)
**Additional information:**

**Comment by dshokouhi** [comment]
Do you see the same issue in chrome for Android on the same device?

**Comment by brusarp** [comment]
Yes (a little bit less), this screenshot is from Chrome 97 on the same device

![20220201_080544.jpg](https://user-images.githubusercontent.com/14950532/151926301-6dbe44d8-5b7f-4946-bb5a-acca033cbad3.jpg)

**Comment by dshokouhi** [comment]
This is a HA frontend issue, please file an issue here: https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=bug_report.yml

First double check open issues to make sure it doesnt exist already

**Comment by brusarp** [comment]
👍🏻 ok, thank you!
