### ISSUE TITLE
Dropdowns don't expand on touch

### ISSUE THREAD

**Issue by kongo09** [home-assistant/android#2235]
**Home Assistant Android version:**
beta-2000-2e0700f7-full

**Android version:**
12

**Phone model:**
Pixel 5

**Home Assistant version:**
core-2022.2.0

**Last working Home Assistant release (if known):**
non-beta Android app

**Description of problem:**
When I touch on a dropdown to expand it, it only briefly flashes and then collapses again. It is almost impossible to select an item. Sometimes, however, it drops.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
https://user-images.githubusercontent.com/640121/152444047-762d8dbd-a44d-49f2-ae87-52c8333789d7.mp4

**Additional information:**

**Comment by therealhalifax** [comment]
Same for me.

**Comment by dshokouhi** [comment]
do you see the same issue in chrome for android on the same device?

**Comment by SkechyWolf** [comment]
Same happens on chrome for android so seems to be a frontend issue

**Comment by dshokouhi** [comment]
As this issue also impacts the HA frontend and they have a different template please open a new issue here: https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=bug_report.yml
