### ISSUE TITLE
Websockets notifications is killing my battery

### ISSUE THREAD

**Issue by ljmerza** [home-assistant/android#2236]
**Home Assistant Android version:**
Beta-2000-2e0700f7-full
**Android version:**
12
**Phone model:**
S21 ultra
**Home Assistant version:**
02.2022
**Last working Home Assistant release (if known):**

**Description of problem:**
The last beta install drains my phone battery. 
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Have you changed the websocket setting at all?

**Comment by ljmerza** [comment]
Yes I had to turn it off completely

**Comment by dshokouhi** [comment]
What do you mean by "turn off completely" did you actually change the setting or just turn off the notification channel? There were 3 options for websockets and turn off is not one of them :)

**Comment by ljmerza** [comment]
"Never" I assume is off is it not? Either way, this new feature drains the battery very fast.

**Comment by dshokouhi** [comment]
Yes `Never` will turn it off. We do have a change in our detection of the screen turning on in the latest beta that will be in the play store on Saturday. Please give it a try then and also keep in mind that it is expected to have some battery drain with this feature, more drain if you set it to always. FWIW on my pixel 6 pro I keep it on `Always` and I do not see massive drain.

can you also share a screenshot of the battery usage graph so we can see how much time was used by the app?

**Comment by ljmerza** [comment]
![image](https://user-images.githubusercontent.com/4085765/152569024-4c99ea2d-4cf8-4ef0-b5d6-0336895b3b30.png)

**Comment by dshokouhi** [comment]
Thanks @ljmerza  if you click on Home Assistant does it give any additional details like how long the app was running for? I am a bit surprised that active time shows as 1m I thought it would be much higher but maybe there are other details we are not seeing on this screen :)

**Comment by ljmerza** [comment]
active is 1min but background was 19h 26m

**Comment by dshokouhi** [comment]
> active is 1min but background was 19h 26m this was with websocket set to while screen on

thanks for checking, after saturdays beta push you should expect this number to more closely match the amount of time the screen is actually in use.

**Comment by dshokouhi** [comment]
Just checking in to see if the latest beta improved the situation

**Comment by dshokouhi** [comment]
Closing as this should be fixed in the latest release
