### ISSUE TITLE
Add support for OnePlus's "Alert Slider"

### ISSUE THREAD

**Issue by cromefire** [home-assistant/android#2239]
**Is your feature request related to a problem? Please describe.**

When I toggle the do not disturb switch on my OnePlus (7T) phone, it is not being registered by the DnD sensor (because it uses a different API).

**Describe the solution you'd like**

DnD should indicate the state of the alert slider on OnePlus devices (with maybe a setting to opt-out of the alert slider, if present)

**Describe alternatives you've considered, if any**

- You could toggle the Android DnD via Assistant, but that defeats the whole purpose of the hardware switch

**Additional context**

The global setting for the slider is `three_Key_mode` with it's values being:
3 -> Ring == `off`
2 -> Vibrate == `vibrate` (~= `priority_only`?)
1 -> Silence == `alarms_only`

Basic sample:
```kotlin
contentResolver.query(Settings.Global.CONTENT_URI, null, null, null, null).use {
    it!!.moveToFirst()
    val res = try {
        Settings.Global.getInt(
            applicationContext.contentResolver,
            "three_Key_mode"
        )
    } catch (e: Settings.SettingNotFoundException) {
        findViewById<TextView>(R.id.txt).text = "No alert slider"
        return@use
    }
    findViewById<TextView>(R.id.txt).text = when (res) {
        1 -> "alarms_only"
        2 -> "vibrate"
        3 -> "off"
        else -> "unknown"
    }
}
```

**Comment by dshokouhi** [comment]
I'm sorry but we should not add stuff specifically for one manufacturer when it uses a non standard Android API.

**Comment by cromefire** [comment]
Okay I should have rephrased that: They do use a standard Android API as you can see in the sample, but they use a non-standard key (as does DnD it seems like). This makes sense because this feature doesn't replace DnD, but complements it. The settings API is specifically designed to be extended in this way for new hardware that isn't defined by the SDK itself.

**Comment by dshokouhi** [comment]
How does this hardware switch relate to our notification command that controls DND? I assume it also doesnt work as you would expect because its a hardware switch?

https://companion.home-assistant.io/docs/notifications/notification-commands#do-not-disturb

**Comment by cromefire** [comment]
On the technical side it is different from DnD in that it isn't a one-off toggle, but does support 3 positions: off, vibrate and silent (except alarms, they always ring). This fiction is present on pretty much every OnePlus phone since about 6 years I think. You can toggle DnD seperately.

On the practical side nobody uses the Android built-in DnD mode because the slider gives you more granular control (3 steps instead of 2) and it's easier to use because you can toggle it without turning on the screen.

The use-case would be to be able to also mute/suppress some smart home actions based on the slider position which provides you basically with a portable switch that can control the phone and the Smarthome.

This is what it looks like on the hardware side:
![Alert Slider](https://user-images.githubusercontent.com/26320625/152593856-ce59059e-134e-4b18-8474-2cd1134f874e.jpg)

I'll test the code from the PR to see whether that might actually take this already into account. I don't think it'll work though, because OnePlus is usually a bit more reluctant to modify the android system itself (which would probably be required, because of the technical separation between DnD and the alert slider above).

**Comment by dshokouhi** [comment]
> On the technical side it is different from DnD in that it isn't a one-off toggle, but does support 3 positions: off, vibrate and silent (except alarms, they always ring). This fiction is present on pretty much every OnePlus phone since about 6 years I think. You can toggle DnD seperately.

According to android documentation `vibrate` is not an option and there are a total of 5 different DnD states and not just limited to 3.  While the quick setting toggle only gives you 2 options using notification commands you can actually put the device in all 5 states.

Remember this is a DnD sensor and command as opposed to OnePlus making a new Alert Slider which has states that are not part of DnD. What OnePlus did here seems to be some type of combination of DnD and Ringer Mode however for us the 2 are different.

The use case is just too specific here, if this was a standard android feature across all android devices the argument would be different.

**Comment by jpelgrom** [comment]
I also don't have a OnePlus device, but this does sound very similar to the [AudioManager.getRingerMode()](https://developer.android.com/reference/android/media/AudioManager.html?hl=en#getRingerMode()) which is already available as the "Ringer Mode" sensor.

@cromefire Did you check this sensor to see if it responds to the alert slider?

**Comment by cromefire** [comment]
Sure

**Comment by cromefire** [comment]
Yes this works indeed, thank you very much.
