### ISSUE TITLE
error spamming the logs 

### ISSUE THREAD

**Issue by lsdlsd88** [home-assistant/android#2245]
**Home Assistant Android version:**
2022.1.1-full
**Android version:**
7.0
**Phone model:**
Lenovo K33A48
**Home Assistant version:**
2022.2.2
**Last working Home Assistant release (if known):**
2022.2.2
**Description of problem:**
Log gets filled with errors
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```
[homeassistant_companion_log_1-5-2022_11-13-14.txt](https://github.com/home-assistant/android/files/8008462/homeassistant_companion_log_1-5-2022_11-13-14.txt)

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
These logs are not directly from the app. You can ignore them. Android logs are chatty by nature.

**Comment by lsdlsd88** [comment]
hello thanks for the reply.
I'm trying to understand an issue with the location tracker but being filled up with those errors means i don't see the part I'm interested in.

**Comment by dshokouhi** [comment]
Your logs are less than 2 minutes you need at least 10 minutes of logs to observe issues. Try to force stop the app and open it again then wait 5 minutes and look at the logs.

Did you already look at the location troubleshooting steps on the companion docs?

**Comment by lsdlsd88** [comment]
will do thanks

**Comment by lsdlsd88** [comment]
sorry to reopen this. left the app open for a few hours, went for a drive etc, to get some info on the location tracking but still only get a few minutes on the log (is there a max lines limit??) filled up with that error therefore useless 
[homeassistant_companion_log_1-13-2022_21-5-19.txt](https://github.com/home-assistant/android/files/8056553/homeassistant_companion_log_1-13-2022_21-5-19.txt)

thanks for your help

**Comment by dshokouhi** [comment]
can you force stop the app, open it again and then immediately go to logs and share that?

**Comment by lsdlsd88** [comment]
here it is. went into the log as quickly as possible after force stop and reopen.
[homeassistant_companion_log_1-13-2022_21-34-44.txt](https://github.com/home-assistant/android/files/8056582/homeassistant_companion_log_1-13-2022_21-34-44.txt)

**Comment by dshokouhi** [comment]
this is strange I dont even see our webview call or sensor updates or anything I would expect to see, can you follow these steps and see if it changes things?

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

Also anything special about this device? Custom ROM? 

The only app relevant log there is the last line which comes from us, if this persists you may need to use another app like Logcat Reader to get the logs and see if the calls are showing up.

By force stopping the app and reopening it I would expect to see log lines mentioning that we are requesting updates and I dont see that.

**Comment by lsdlsd88** [comment]
hello, I tried following the starting fresh section, deleted the mobile intergration from the server, cleared app data and so on.

no appreciable difference.

phone is a standard rom Lenovo but I understand it's pretty old so might be some sort of incompatibility.

I see there are a few thread on similar errors 

https://stackoverflow.com/questions/65411169/android-log-is-littered-with-warnings-regarding-resource-address-entry-index

[homeassistant_companion_log_1-13-2022_21-52-33.txt](https://github.com/home-assistant/android/files/8056636/homeassistant_companion_log_1-13-2022_21-52-33.txt)

**Comment by dshokouhi** [comment]
Can you install logcat reader and grant the app the requested USB permissions? Then from there look at the logs for `LocBroadcastReceiver` that should hopefully show something. If not try and filter by `homeassistant` and see if any errors show up. This starting to look like a device specific issue

**Comment by lsdlsd88** [comment]
will have a play with logcat reader tomorrow thanks for your help
