### ISSUE TITLE
Last used app sensor again

### ISSUE THREAD

**Issue by chertvl** [home-assistant/android#2249]
**Is your feature request related to a problem? Please describe.**
Some changes with last used app sensor non human readable

**Describe the solution you'd like**
I prefer to see app name

**Describe alternatives you've considered, if any**
We can put app name in sensor attrubutes maybe

**Additional context**
Hello all,
in continuation of https://github.com/home-assistant/android/pull/2243
I would like to ask:
Is it possible to put old-look of Last Used App sensor, which shows human-readable name of the app instead package name, for example in attributes of this sensor?
I very used to see app name in HA UI, but since last companion changes I cant understand anymore what app is currently running, for some developers, the package name does not contain the name of the application.

Thanks you so much for understanding and your time!

<details><summary>BIG SCREENSHOT</summary>

![Screenshot_20220207-222552_Home Assistant](https://user-images.githubusercontent.com/38353584/152867520-020c84df-d9e4-4be2-ae78-021538e6c878.jpg)

</details>

**Comment by dshokouhi** [comment]
Sure we can add the label back as a attribute of the sensor
