### ISSUE TITLE
Alarm state sensor (mobile phone alarm clock)

### ISSUE THREAD

**Issue by Timmiej93** [home-assistant/android#2256]
**Is your feature request related to a problem? Please describe.**

I want to use different alarm states (stopped, ringing, snoozed) in my automation. With the information that the `next_alarm` sensor provides, I can't effectively differentiate between these states.

**Describe the solution you'd like**

I would love to see a state sensor for the alarm on your phone, as an addition to the 'next alarm' sensor we already have.

States would be something like:
- Stopped: Default state. No alarm is ringing, and no alarm is in "snoozed" state.
- Ringing: Any alarm is ringing.
- Snoozed: Any alarm is snoozed.
- Off (maybe?): No alarms are active at all. This one I'm still debating if it's even required, but it may be nice to have.

**Describe alternatives you've considered, if any**

I've tried determining these states from the `next_alarm` sensor, but I can't reliably do that. I considered installing other apps to provide this data to HA, but that's not really something I'm interested in.

**Additional context**

**Comment by dshokouhi** [comment]
Not possible using the google API, use Sleep as Android as it already provides these features.
