### ISSUE TITLE
No negative value possible for BLE Transmitter setting "Measured Power" 

### ISSUE THREAD

**Issue by PepperPhil** [home-assistant/android#2260]
**Home Assistant Android version:**
2022.1.1-full

**Android version:**
Android 10

**Phone model:**
Samsung Galaxy S9

**Home Assistant version:**
core-2022.2.5

**Last working Home Assistant release **
not known

**Description of problem:**
No negative entry possible in BLE Transmitter sensor setting "Measured Power" (even if default was negative -59).

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20220211-183221_Home Assistant.jpg](https://user-images.githubusercontent.com/69075397/153640920-f6c3b140-f936-4f94-9106-563ee305ed66.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
This is actually fixed in the latest beta by https://github.com/home-assistant/android/pull/2158

**Comment by PepperPhil** [comment]
Wow, you are fast! Thx for the info!

**Comment by PepperPhil** [comment]
> This is actually fixed in the latest beta by https://github.com/home-assistant/android/pull/2158 

Wow, you are fast! Thx for the info!
