### ISSUE TITLE
Service Widget Drops Leading Zero (0)

### ISSUE THREAD

**Issue by arroyobass** [home-assistant/android#2264]
**Home Assistant Android version:**
2022.1.1-full

**Android version:**
12
**Phone model:**
Galaxy s20 5G
**Home Assistant version:**
2022.2.6
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
When entering a code for a security alarm service call in the service button widget, the leading zeros are removed from the code after saving the changes to the widget. 

Eg: "0123" is changed to "123"

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
related: https://github.com/home-assistant/android/issues/709

**Comment by ioangogo** [comment]
This issues title probably needs editing to include a numeric 0 so that people searching for the issue using a 0 instead of Zero can find it

**Comment by ioangogo** [comment]
I dont fully understand Koltin or the structure of the project, but i think this is in the flow of the data and might be the cause of the code truncation

https://github.com/home-assistant/android/blob/50a8b9eee2cadac86546dc152d09de471328b36c/app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt#L201

**Comment by dshokouhi** [comment]
Looks like you are close. Apparently the `trim()` call just above is responsible for this behavior.

https://github.com/home-assistant/android/blob/50a8b9eee2cadac86546dc152d09de471328b36c/app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt#L200C1-L200C1

Maybe we should only apply the trim to boolean and string values instead of integers?

Example:
https://pl.kotl.in/7pK1_wTcf

**Comment by dshokouhi** [comment]
Deleted my last comment as it was incorrect. It seems `toInt()` does remove the leading 0 here. Need to think of a good replacement here as we do need to make sure we send strings and numbers appropriately.

Example: https://pl.kotl.in/OlbdJ0h6h

**Comment by xPudda** [comment]
As today, the problem still appears.. I was trying to add a disarming alarm widget and the code starts with zero.. The widget truncated it

**Comment by blackhead1981** [comment]
Unfortunately, the problem still persists. I am an absolute beginner in programming, but wouldn't it be easiest to ensure that everything is interpreted as a string using (toString), so that the leading zero is not lost?

**Comment by dshokouhi** [comment]
> However, I haven’t had the chance to test it yet. Please let me know your thoughts on this approach.

As soon as the acton finishes successfully a debug APK will generate in the artifact where you can do testing (assuming you dont have android studio setup)

https://github.com/home-assistant/android/actions/runs/11300553360

**Comment by blackhead1981** [comment]
After a brief check in the debug APK, it seems to be working so far. At least a PIN code with a leading zero works without any issues. I will conduct further tests tomorrow. I kindly ask for your additional testing as well.
