### ISSUE TITLE
WebSocket SSL certificate validation fails if CNAME ist used

### ISSUE THREAD

**Issue by PeterBurner** [home-assistant/android#2272]
**Home Assistant Android version:** 2022.2.0-full

**Android version:** Android 11 (MIUI 12.6 by xiaomi.eu 21.11.3 Beta)

**Phone model:** Xiaomi Mi 10 Ultra

**Home Assistant version:** 2022.2.6

**Last working Home Assistant release (if known):** 2022.2.6

**Description of problem:**
After creating a custom domain for my Home Assistant server the Android app can no longer connect via WebSocket. Login from within the Android app still works (HTTP request reach Home Assistant Core). WebApp on the same phone works too.  
What I did:
1. create a CNAME record (my-cname.example.com) for the DynDNS subdomain of my router (unique-dyndns-subdomain.myfritz.net)
2. set server port of Home Assistant to 443
3. enable port forwarding for 443 at my router
4. allow NAT loopback for the custom domain at my router
5. setup Home Assistant Let's Encrypt addon for custom domain
6. open Home Assistant WebApp over custom domain on PC --> works, SSL valid
7. set custom domain in Android app and reload --> error (see screenshot)
8. clear Android app data
9. login in the Android app --> works till loading screen, then same error
10. see in the WebApp that new Android app entities were created
11. open Home Assistant WebApp over custom domain on phone --> works
12. disable WiFi/enable mobile data and open Home Assistant Android app --> works
13. disable mobile data/enable WiFi and start Android ADB LogCat --> seems like SSL certificate is validated against DynDNS domain name (logs below)

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
02-12 18:34:32.357 23197 23646 D WebviewActivity: External bus {"type":"config/get","id":1}
02-12 18:34:32.357 23197 23197 D WebviewActivity: externalBus({"id":1,"type":"result","success":true,"result":{"hasSettingsScreen":true,"canWriteTag":true,"hasExoPlayer":true}});
02-12 18:34:32.366 23197 23197 D UrlRepository: localUrl is: false and usesInternalSsid is: false
02-12 18:34:32.366 23197 23197 D UrlRepository: Using external URL
02-12 18:34:32.367 23197 23197 D WebviewActivity: Callback null
02-12 18:34:32.368 23197 23197 E WebviewActivity: Cannot set status bar color 0. Skipping coloring...
02-12 18:34:32.368 23197 23197 E WebviewActivity: Cannot set navigation bar color 0. Skipping coloring...
02-12 18:34:32.489 23197 23356 I cr_X509Util: Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
02-12 18:34:32.490 23197 23359 E chromium: [ERROR:ssl_client_socket_impl.cc(995)] handshake failed; returned -1, SSL error code 1, net_error -202
02-12 18:34:32.497 23197 23197 E WebviewActivity: onReceivedHttpError: primary error: 3 certificate: Issued to: CN=unique-dyndns-subdomain.myfritz.net;
02-12 18:34:32.497 23197 23197 E WebviewActivity: Issued by: CN=unique-dyndns-subdomain.myfritz.net;
02-12 18:34:32.497 23197 23197 E WebviewActivity:  on URL: wss://my-cname.example.com/api/websocket
```

**Screenshot of problem:**
![Screenshot_2022-02-12-19-17-49-167_io homeassistant companion android](https://user-images.githubusercontent.com/15011953/153723274-4b525347-7edc-4aa9-bdfb-39be50e0abb5.jpg)

**Additional information:**
 - my real domains where replaced in the text above
 - my router is a `FRITZ!Box 6490 Cable`
 - my router provides its own DynDNS service --> myfritz.net

**Comment by PeterBurner** [comment]
Thanks for the hint with the trust anchor. I will look into it.  
Regardless the Android App behaves different than the WebApp in the mobile browser. Shouldn't this be consistent?

**Comment by dshokouhi** [comment]
> Regardless the Android App behaves different than the WebApp in the mobile browser. Shouldn't this be consistent?

The Android app has more features than the browser does. It has widgets, sensors, notifications etc... The behavior will indeed be different as it uses different communication methods than a browser does.
