### ISSUE TITLE
Websocket persistent notification: allow setting only on Home WiFi

### ISSUE THREAD

**Issue by RoboMagus** [home-assistant/android#2279]
**Is your feature request related to a problem? Please describe.**
Since the latest release its possible to keep an active Websocket communication open. However I'm not interested in this when away from home. When at home however this is a nice feature to have. 

**Describe the solution you'd like**

I'd like the option to set the persistent Websocket communication to only be active on home wifi, or generic wifi only maybe? 

**Describe alternatives you've considered, if any**

Toggling it by hand, but that's a real nuisance. 

**Additional context**

-

**Comment by dshokouhi** [comment]
For this we should make use of Home WiFi SSID as defined in app settings
