### ISSUE TITLE
Wear OS onboarding via phone

### ISSUE THREAD

**Issue by Kisty** [home-assistant/android#2281]
**Is your feature request related to a problem? Please describe.**

When you first connect to Home Assistant, it's difficult to enter login on a small screen and there are some symbols that don't appear on wear OS keyboard 

**Describe the solution you'd like**

Either share log in auth with phone app if available or show a button to prompt entering log in credentials on the phone.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
We already have sign in on phone feature 🙂

**Comment by SkechyWolf** [comment]
There is also a button on the watch that says "Sign in on phone" on the onboarding page

**Comment by Kisty** [comment]
Where's that button? I didn't see it

**Comment by Kisty** [comment]
Aah, I didn't see any discovered instances which is probs related to #1866
