### ISSUE TITLE
Non-URI Actions in Notifications do not work

### ISSUE THREAD

**Issue by AdmiralNemo** [home-assistant/android#2296]
**Home Assistant Android version:** 2022.2.1-minimal

**Android version:** 12 (SP1A.210812.016.C1)

**Phone model:** Pixel 3

**Home Assistant version:** 2022.2.6

**Last working Home Assistant release (if known):** N/A

**Description of problem:**

Tapping a button in a notification does nothing unless the `action` value is `"URI"`.  For `URI` actions, tapping the button opens the specified URI as expected.  For `REPLY` actions, the input box appears when the button is clicked, but when the send button is tapped, it turns into a spinner and nothing happens.  In all other cases, tapping the button does literally nothing.  The notification does not get dismissed, and no event is sent to Home Assistant.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

The log below covers from the time I clicked _Call Service_ in the Home Assistant Developer Tools UI until the time I took the screenshot below.  I tapped the _click_ button in the notification before taking the screenshot, but absolutely nothing was logged when I did.

```
--------- beginning of main
02-17 16:37:11.638  1501  1707 W IorapForwardingService: No service published for: iorapd
02-17 16:37:12.643  1501  1707 W IorapForwardingService: No service published for: iorapd
02-17 16:37:12.882   984  2284 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0xd
02-17 16:37:13.650  1501  1707 W IorapForwardingService: No service published for: iorapd
02-17 16:37:13.931  4998 15784 D WebSocketRepository: Websocket: onMessage (text)
02-17 16:37:13.946  4998 15784 D WebSocketRepository: Message number 183 received: {"id": 183, "type": "event", "event": {"message": "test 0efb84dc", "data": {"actions": [{"action": "MYACTION", "title": "click"}]}, "hass_confirm_id": "8140e0d0d04d5192c8b7a8a1f09baf22"}}
02-17 16:37:13.968  4998  5035 D WebSocketRepository: Sending message 307: {type=mobile_app/push_notification_confirm, webhook_id=78a700eeec9e5d5a630ba595de3ade7fd5f9c525afa0a9ff6750a117296638c8, confirm_id=8140e0d0d04d5192c8b7a8a1f09baf22, id=307}
02-17 16:37:13.968  4998  5035 D WebSocketRepository: Message number 307 sent
02-17 16:37:13.976  4998 15784 D WebSocketRepository: Websocket: onMessage (text)
02-17 16:37:13.977  4998 15784 D WebSocketRepository: Message number 307 received: {"id": 307, "type": "result", "success": true, "result": null}
02-17 16:37:14.002  4998  4998 D MessagingService: Creating notification with following data: {action_1_key=MYACTION, action_1_title=click, action_1_uri=null, message=test 0efb84dc}
02-17 16:37:14.039  4998  4998 D MessagingService: Show notification with tag "null" and id "164959635"
--------- beginning of system
02-17 16:37:14.277  1501  1501 W NotificationHistory: Attempted to add notif for locked/gone/disabled user 0
02-17 16:37:14.295  2244  2244 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|io.homeassistant.companion.android.minimal|164959635|null|10153
02-17 16:37:14.297  2244  2244 W NotifBindPipeline: Row is not set so pipeline will not run. notif = 0|io.homeassistant.companion.android.minimal|164959635|null|10153
02-17 16:37:14.297  2244  2384 D PeopleSpaceWidgetMgr: Sbn doesn't contain valid PeopleTileKey: null/0/io.homeassistant.companion.android.minimal
02-17 16:37:14.653  1501  1707 W IorapForwardingService: No service published for: iorapd
02-17 16:37:14.881   984  2284 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0xd
02-17 16:37:15.656  1501  1707 W IorapForwardingService: No service published for: iorapd
02-17 16:37:15.691   977  1017 D VSC     : @ 21848.205: [Significant Motion] Stop motion_detect
02-17 16:37:15.691   977  1017 D VSC     : @ 21848.206: [Significant Motion] Request accel, interval 20.0 ms, latency 3200.0 ms
02-17 16:37:15.691   977  1017 D ASH     : @ 21848.215: SensorType 195 resampler quality 0
02-17 16:37:16.666  1501  1707 W IorapForwardingService: No service published for: iorapd
02-17 16:37:16.897   984  2284 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0xd
02-17 16:37:17.597   962   962 I android.hardware.health@2.0-service.crosshatch: Entry state_: 1 charger_status: Charging batteryLevel: 100
02-17 16:37:17.597   962   962 I android.hardware.health@2.0-service.crosshatch: Exit state_: 1 batteryLevel: 100
02-17 16:37:17.670  1501  1707 W IorapForwardingService: No service published for: iorapd
02-17 16:37:17.944   977  1017 D VSC     : @ 21850.469: [WO] Proposed rotation: 1, flat angle threshold: 40
02-17 16:37:17.944   977  1017 D VSC     : @ 21850.469: [WO] orientation angle 46, orientation 1
02-17 16:37:17.944   977  1017 D VSC     : @ 21850.469: [WO] Gyro angle integrated: 44.257637
02-17 16:37:17.944   977  1017 D VSC     : @ 21850.469: [WO] rejected by isOrientationAngleAcceptable
02-17 16:37:18.680  1501  1707 W IorapForwardingService: No service published for: iorapd
02-17 16:37:18.908   984  2284 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0xd
02-17 16:37:19.691  1501  1707 W IorapForwardingService: No service published for: iorapd
02-17 16:37:19.937   977  1017 D VSC     : @ 21852.462: [WO] Proposed rotation: 1, flat angle threshold: 40
02-17 16:37:19.937   977  1017 D VSC     : @ 21852.463: [WO] orientation angle 45, orientation 1
02-17 16:37:19.937   977  1017 D VSC     : @ 21852.463: [WO] Gyro angle integrated: 64.808731
02-17 16:37:19.937   977  1017 D VSC     : @ 21852.463: [WO] rejected by isOrientationAngleAcceptable
02-17 16:37:19.957  1501  1737 V DisplayPowerController[0]: Brightness [0.10676457] reason changing to: 'automatic', previous reason: 'automatic [ dim ]'.
02-17 16:37:20.125  4998  4998 D TileExtensions: Tile: tile_1 is in view
02-17 16:37:20.127  4998  4998 D TileExtensions: Attempting to set tile data for tile ID: tile_1
02-17 16:37:20.131  4998  4998 D TileExtensions: Tile data set for tile ID: tile_1
02-17 16:37:20.131  2244  2384 D ControlsListingControllerImpl: Subscribing callback, service count: 2
02-17 16:37:20.354  2244  2384 D ControlsListingControllerImpl: Unsubscribing callback
02-17 16:37:20.694  1501  1707 W IorapForwardingService: No service published for: iorapd
02-17 16:37:20.905   984  2284 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0xd
02-17 16:37:21.369  1501  2035 V KeyCombinationManager: Performing combination rule : KEYCODE_VOLUME_DOWN + KEYCODE_POWER
```

**Screenshot of problem:**

![image](https://user-images.githubusercontent.com/988596/154583588-eab2b783-b69f-4867-ac75-fbc35f957153.png)

**Additional information:**

Service call:

```yaml
service: notify.mobile_app_pixel_3
data:
  message: test 0efb84dc
  data:
    actions:
    - action: MYACTION
      title: click
```

This is the first time I have been able to use notifications in the mobile app, as I use the F-Droid builds and do not have Google Play Services on my phone.  I am excited to get them working with the new WebSocket connection!

**Comment by dshokouhi** [comment]
Are there any HA core errors at the time of the error?  Have you tried listening for the event in HA `mobile_app_notification_action`? The call itself is not failing here.

more details on how actionable notifications work here:
https://companion.home-assistant.io/docs/notifications/actionable-notifications#building-notification-action-scripts

if the event failed to call I would expect to see the following error message from the app logs: https://github.com/home-assistant/android/blob/e21d0951950826b0293b5a7eb7144db3f3d8554f/app/src/main/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt#L88

**Comment by AdmiralNemo** [comment]
Nothing logged on the server.

I've tried listening for the `mobile_app_notification_action` (and `mobile_app_notification_cleared`) using both Developer Tools/Events as well as Automations, but nothing ever happens. No events are received.  Nothing is logged anywhere.

**Comment by dshokouhi** [comment]
Can you also get us the logs for the reply action too? Also try and give it a few seconds after clicking the button and getting the logs because the logs above are only 1 second after the notification panel was pulled down. Make sure to check them in Companion App > Logs too, so the last log line should be a line we print.

**Comment by AdmiralNemo** [comment]
Sure thing.  Here you go.

```yaml
service: notify.mobile_app_pixel_3
data:
  message: test df78baf9
  data:
    actions:
    - action: REPLY
      title: REPLY
```
[adb-logcat.txt](https://github.com/home-assistant/android/files/8093155/adb-logcat.txt)
[homeassistant_companion_log_1-17-2022_18-31-27.txt](https://github.com/home-assistant/android/files/8093156/homeassistant_companion_log_1-17-2022_18-31-27.txt)

**Comment by dshokouhi** [comment]
I dont see any of our log lines I would expect to see if the intent was received by the app and the call failing. Can you try the start fresh steps to rule out bad data? https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by AdmiralNemo** [comment]
Thanks for continuing to help me troubleshoot this.  I really appreciate it!

> Can you try the start fresh steps to rule out bad data? https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

After clearing app storage, removing the integration from Home Assistant, and re-configuring the app, the behavior remains the same: URI actions work fine, but others do nothing.

[homeassistant_companion_log_1-17-2022_19-33-18.txt](https://github.com/home-assistant/android/files/8093537/homeassistant_companion_log_1-17-2022_19-33-18.txt)

I also tried on another Android device (Galaxy Tab S5e running LineageOS 17.1 (Android 10), and it behaves the same way.

[homeassistant_companion_log_1-17-2022_19-37-40.txt](https://github.com/home-assistant/android/files/8093545/homeassistant_companion_log_1-17-2022_19-37-40.txt)

> I dont see any of our log lines I would expect to see if the intent was received by the app and the call failing.

Is there a way to verify that the buttons are _sending_ an intent?

**Comment by dshokouhi** [comment]
are both devices running the same custom ROM on those devices? this issue is sounding like a custom ROM issue. Try to verify on a stock ROM please. Your logs indicate nothing is being sent, if it was sent we would see a failure or an event in HA.

**Comment by AdmiralNemo** [comment]
No, they are completely different. LineageOS 17.1 vs GrapheneOS 2022021415.

I don't have any trouble with any other app with notification actions on either device.

I don't have access to any device with preinstalled spyware right now.

**Comment by dshokouhi** [comment]
thanks for bearing with me during troubleshooting, can you try the debug minimal APK from: https://github.com/home-assistant/android/actions/runs/1862225834

it will install side by side the production version and you can uninstall it after the test, just make sure to pick a unique device name :)

**Comment by AdmiralNemo** [comment]
Awesome, that works! Thanks for figuring it out so quickly!

**Comment by mwilky** [comment]
I am getting the opposite to this:

I see events when they are anything other than `URI` actions, and the notification clears on action click. 

BUT - If I use a `URI` action, the `URI ` action works fine (for example open app or open web page), but no events come back into HA and the notification doesn't get cleared.

**Comment by dshokouhi** [comment]
@mwilky please do not comment on old and closed issue. Instead open a new one.  There are no events on URI actions.  You probably want #2524
