### ISSUE TITLE
Keyboard down-arrow key bug

### ISSUE THREAD

**Issue by Didgeridrew** [home-assistant/android#2297]
**Home Assistant Android version:**
beta-2044-1689a5b3-full

**Android version:**
10 and FireOS 5.6.9.0

**Phone model:**
Blu b130dl, Amazon Fire HD 8 (7th Gen) Tablet, Samsung A7 tablet

**Home Assistant version:**
2022.2.8

**Last working Home Assistant release (if known):**
Before 2021.1... I don't remember exactly when I first noticed it.

**Description of problem:**
When using a keyboard in the Services, Template, and Event tools or in VSC addon pressing the down arrow key inserts a TAB instead of moving the cursor down.  

I do not have this issue when using the same equipment and accessing HA tools/addons using Brave, Chrome, Tor, Firefox, or DuckDuckGo browser apps or when using the same equipment in other non-browser apps.  

This appears to be exclusively an issue with HA companion for Android.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
@N/A
**Additional information:**

**Comment by dshokouhi** [comment]
We do indeed map D-pad down to the Tab key as this is a workaround for android TV devices otherwise the controls from a remote control will not work as desired.

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L1310

**Comment by OpSparkk** [comment]
But this is a permanent or will be fixed later?
I love working on home assistant on my tablet with a keyboard.
Would really like to use the arrow down button
