### ISSUE TITLE
Sensor toggles

### ISSUE THREAD

**Issue by OptimusGREEN** [home-assistant/android#2299]
**Is your feature request related to a problem? Please describe.**

Unable to create automation to toggle sensors

**Describe the solution you'd like**

app to provide enable/disable toggles for each sensor in the app

**Describe alternatives you've considered, if any**

**Additional context**

Basically I want to have an automation that turns ble transmitter on when i get home and off when i leave, to preserve battery.

**Comment by dshokouhi** [comment]
> Nice one, didn't realise.
> I do think the app providing integration toggles would be far less cumbersome though. Thanks. 

Home assistant core needs to support switches for the mobile app integration first. Until then we have notification commands.
