### ISSUE TITLE
When URI opens media folder you cant go back to main view

### ISSUE THREAD

**Issue by Minglarn** [home-assistant/android#2305]
**Home Assistant Android version:**
beta-2098-7e3d5aa1-full
**Android version:**

**Phone model:**
Samsung Note10+
**Home Assistant version:**
2022.02.9
**Last working Home Assistant release (if known):**

**Description of problem:**
When using URI to direct to media folder from a notification, you cant go back to main view in HA App.. 

```
     - action: URI
        title: EVENTS
        uri: >-
          /media-browser/browser/app%2Cmedia-source%3A%2F%2Ffrigate/video%2Cmedia-source%3A%2F%2Ffrigate%2Ffrigate%2Fevent-search%2Fclips%2F%2F%2F%2F%2F%2F/video%2Cmedia-source%3A%2F%2Ffrigate%2Ffrigate%2Fevent-search%2Fclips%2F.today%2F1644966000%2F%2F%2F%2F 
```

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
N/A.
```

**Screenshot of problem:**

![1](https://user-images.githubusercontent.com/58695742/155099427-0ae2a3b1-519a-4aef-ac0a-2e44fe426575.PNG)
![2](https://user-images.githubusercontent.com/58695742/155099440-d6bb5704-0bd9-4be4-bbbc-465ae63a8327.PNG)
![3](https://user-images.githubusercontent.com/58695742/155099447-2afb37d2-1bb7-438e-b745-e5f5eac4c08b.PNG)

**Additional information:**

**Comment by dshokouhi** [comment]
There is no page to go back to here so this is working as designed
