### ISSUE TITLE
Persistent Connection Settings menu not scrolling

### ISSUE THREAD

**Issue by greencardigan** [home-assistant/android#2321]
The Persistent Connection settings menu won't allow scrolling. Content down the bottom is unreachable in portrait and landscape orientation. 

![Screenshot_20220226-165517_Home Assistant](https://user-images.githubusercontent.com/5628514/155831543-6973b559-2a39-4404-89f9-a8d34be8462d.jpg)

![Screenshot_20220226-170134_Home Assistant](https://user-images.githubusercontent.com/5628514/155831593-7cd30b79-bd5d-431a-bda5-12a169eb0c3b.jpg)

**Comment by dshokouhi** [comment]
This is fixed in the latest beta
