### ISSUE TITLE
Turn on/off the persistent websocket connection via a notification command.

### ISSUE THREAD

**Issue by eyager1** [home-assistant/android#2323]
**Is your feature request related to a problem? Please describe.**

I like the speed of the persistent websocket connection, but the battery drain is a bit excessive when it comes to standby battery drain, especially when I'm at home and I don't need instant notifications.  But if I'm away from home I would like the instant notifications and am willing to accept the higher battery drain.   Right now the only solution is to manually change it in the app configuration.  It would be nice to be able to automate this.

**Describe the solution you'd like**

The simplest way to allow the persistent websocket connection to be automated to use a notification command and let home assistant handle the automation conditions.   Create something like `command_persistent_websocket`.   

**Describe alternatives you've considered, if any**

A tick-able list of conditions in the app configuration could be helpful as well.  A persistent websocket connection based on conditions like "When connected to charger", "When not in Home zone" or "When connected to wifi" could handle many of the most common use cases.

**Additional context**

**Comment by dshokouhi** [comment]
> A tick-able list of conditions in the app configuration could be helpful as well. A persistent websocket connection based on conditions like \"When connected to charger\", \"When not in Home zone\" or \"When connected to wifi\" could handle many of the most common use cases.

So we did just add when on home wifi as a new option. I think if we continue to add more options this page will become more confusing. It might be best to just add a notification command to account for all the other cases.
