### ISSUE TITLE
Android app ask URL everytime

### ISSUE THREAD

**Issue by GiacomoCorti** [home-assistant/android#2326]
**Home Assistant Android version:** 2022.2.1-full

**Android version:** 12

**Phone model:** Xiaomi mi 9

**Home Assistant version:** core-2022.2.9

**Last working Home Assistant release (if known):**

**Description of problem:** Every time i open the app on my phone ask to manually type the url of homeassistant server. The login is correctly saved but the url not. And also in the configuration panel I don't have the phone settings to control phone sensor. The configuration menu is exactly the same I have on my PC, i don't have the add section for android phone setting

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**.

```

```

**Screenshot of problem:**.

**Additional information:**.

**Comment by dshokouhi** [comment]
Where are the requested logs that you skipped over?

**Comment by GiacomoCorti** [comment]
What log should I attach. Of me installing an app off of google play and keep asking for url?

**Comment by GiacomoCorti** [comment]
The phone model is written in the first message, it's running Pixel Experience Rom based on android 12.
Now it's actually working as it should, so the url is found automatically and there is the companion app setting. I don't know what was the problem before

**Comment by dshokouhi** [comment]
Without logs it will be very difficult to troubleshoot, glad you got it solved maybe it was just a fluke. Closing this issue as now it no longer occurs.

**Comment by poulp0** [comment]
I have the same problem after creating a dashboard for mobile and using the url of the dashboard in the app.
