### ISSUE TITLE
Persistent notification page goes off screwn

### ISSUE THREAD

**Issue by sym0nd0** [home-assistant/android#2327]
**Home Assistant Android version:**
2022.2.1-full
**Android version:**
12
**Phone model:**
Samsung Galaxy S22 Ultra (SM-S908B/DS)
**Home Assistant version:**
2022.2.9
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
Persistent notification page goes off screen, unable to scroll down
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20220227-171649_Home Assistant.jpg](https://user-images.githubusercontent.com/55590428/155892792-ef94294b-7df0-4219-84c8-3d10987b8458.jpg)
**Additional information:**

**Comment by dshokouhi** [comment]
Fixed in the latest beta
