### ISSUE TITLE
No haptic feedback/vibrationEffect when refreshing a template tile on Wear OS

### ISSUE THREAD

**Issue by seagri** [home-assistant/android#2330]
**Home Assistant Android version:**
2022.2.1-full
**Android version:**
Android 12
**Phone model:**
Samsung S10
**Home Assistant version:**
2022.2.9
**Last working Home Assistant release (if known):**

**Description of problem:**
There is No haptic feedback/vibrationEffect when refreshing a template tile on Wear OS. At least not on samsung galaxy watch4.

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Looks like this feature was never added to template tile, so this is an enhancement request and not a bug

**Comment by seagri** [comment]
Okay, that's why then.
it would be a really good enhancement as it is hard to know if I hit or missed it.

**Comment by seagri** [comment]
Even better could be to have it automatically if you scroll to that tile. Then it could update automatically.

**Comment by seagri** [comment]
What do you think of this one @leroyboerefijn ?

**Comment by leroyboerefijn** [comment]
> Even better could be to have it automatically if you scroll to that tile. Then it could update automatically.

This is not possible unfortunately. But haptic feedback is definitely possible, good suggestion! :)
