### ISSUE TITLE
High Accuracy mode doesn't update location

### ISSUE THREAD

**Issue by QBANIN** [home-assistant/android#2336]
**Home Assistant Android version:**
All 2022.x version affected. Last bug-free was 2021.12.3

**Android version:**
10

**Phone model:**
Samsung Note20 Ultra

**Home Assistant version:**
2022.2.9 but hits bug is core independent. After downgrade Android app to 2021.12.3 everything works fine

**Last working Home Assistant release (if known):**
any

**Description of problem:**
Since 2022.x Android Companion version high accuracy mode is broken. Even if it's on and high accuracy sensor value is true (reporting interval set to 5s), and it's reporting current position in notification, position updates are not being sent to Home Assistant or sent with huge delay such as 10 or 15 min. It behaves pretty much like if high accuracy mode was disabled. Because of this my location-based scripts doesn't work as expected. The funny part is that sometimes it does work like it should but it most cases don't.

Tried to downgrade few versions back and it appears that all 2022.+ Companion App versions are broken. Last correctly working version is 2021.12.3 .

**Additional information:**

**Comment by dshokouhi** [comment]
Where are the logs?

**Comment by QBANIN** [comment]
I couldn't grab any logs while driving a car and now when I'm home can't reproduce the issue. The only location related entry I see now is 

> 03-04 15:47:18.252  8653  8735 E RequestManager_FLP: [FusedLocationApi] Location batching request  50912bb(PendingIntent) PRIORITY_BALANCED_POWER_ACCURACY interval=60000 maxWaitTime = 200000 from io.homeassistant.companion.android (10395 foreground)

I'll be investigating further and let you know.

**Comment by dshokouhi** [comment]
We are definitely going to need logs in order to continue here. At least 10 minutes of logs to see if location requests are coming in.  Also would be helpful to know how you are turning high accuracy mode on and off.

**Comment by QBANIN** [comment]
> We are definitely going to need logs in order to continue here. At least 10 minutes of logs to see if location requests are coming in. Also would be helpful to know how you are turning high accuracy mode on and off.

Are we talking about Android logcat logs or logs from Home Assistant server?

**Comment by dshokouhi** [comment]
Logcat logs, the same ones in the issue template where you removed the section.

**Comment by QBANIN** [comment]
> Logcat logs, the same ones in the issue template where you removed the section.

I can't post entire log here due to sensitive location data, but there message keep repeating in the log when described issue occurs:

> 03-06 23:57:12.627 11666 11666 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = true
> 03-06 23:57:12.630 11666 11666 D LocBroadcastReceiver: Last Location: 
> 03-06 23:57:12.630 11666 11666 D LocBroadcastReceiver: Coords:(XX.XXXXXX, XX.XXXXXX)
> 03-06 23:57:12.630 11666 11666 D LocBroadcastReceiver: Accuracy: 6.0
> 03-06 23:57:12.630 11666 11666 D LocBroadcastReceiver: Bearing: 273.0511
> 03-06 23:57:12.630 11666 11666 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
> 03-06 23:57:12.630 11666 11666 D LocBroadcastReceiver: Skipping location update that came from the future. 1646607437630 should always be greater than 1646607437999
> 03-06 23:57:15.618 11666 11666 D LocBroadcastReceiver: Received location update.

High Accuracy was acrive but no location updates was sent to HA server.

**Comment by dshokouhi** [comment]
```
03-06 23:57:15.626 11666 11666 D LocBroadcastReceiver: Skipping location update that came from the future. 1646607440626 should always be greater than 1646607440999
```

Interesting in our app we add a 5 second lead time to checking the time posted with a location update and it seems here the count is off by a few milliseconds. We have to evaluate the time to make sure its real and not fake because we do indeed receive false reports from google that we need to skip based on the time.

https://github.com/home-assistant/android/blob/3d6f50a867b5e3f7a466991058bc1c1c12a24dc7/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L594-L597

Whats happening here is that your devices time is a few seconds off from google. And you say sometimes it works and sometimes it doesnt? I wonder if based on the logs if its always this close during the time comparison, we could consider increasing the lead time a few seconds to prevent this.  The only thing that changed here since 2021.12 is maybe a dependency update but the update logic has not changed in some time.

**Comment by QBANIN** [comment]
> (...) And you say sometimes it works and sometimes it doesnt? I wonder if based on the logs if its always this close during the time comparison, we could consider increasing the lead time a few seconds to prevent this. The only thing that changed here since 2021.12 is maybe a dependency update but the update logic has not changed in some time.

Yeah... Sometimes it does work from the start till the end of driving, sometimes it works for a minute so and then suddenly stop updating, sometimes it doesn't update position at all. While I was using pre 2022.x version I didn't notice such behavior.

BTW. Can you remove +5000 ms as minimum update interval? :)

**Comment by dshokouhi** [comment]
> BTW. Can you remove +5000 ms as minimum update interval? :)

no that is there so we cannot hammer things too much we had an issue where too many updates were sent causing issues so we had to tone that done.

**Comment by QBANIN** [comment]
> > BTW. Can you remove +5000 ms as minimum update interval? :)
> 
> no that is there so we cannot hammer things too much we had an issue where too many updates were sent causing issues so we had to tone that done.

Or at least set it to somewhat lower value such as 2-3s? Perhaps as "yes-i-know-what-am-i-doing" checkbox? :)

**Comment by dshokouhi** [comment]
sorry we wont be able to do that.

**Comment by QBANIN** [comment]
> sorry we wont be able to do that.

Ok, I'll be waiting for a fix then.
