### ISSUE TITLE
location won't appear on map card / case sensitive

### ISSUE THREAD

**Issue by finnzz** [home-assistant/android#2339]
Android app: 2202.2.1-full
home assistant: 2202.2.6

The geocoded location entity doesn't appear on the Lovelace map card because it is case sensative to the attributes Longitude / Latitude.

Most entities use all lowercase attribute labels.  Perhaps the HA companion app should be using lowercase attributes as well?

Or at least change the Latitude / Longitude attribute labels to latitude / longitude?  Right now the only user solution seems to be creating a new sensor to relabel the attribute names for those two.

**Comment by dshokouhi** [comment]
> Right now the only user solution seems to be creating a new sensor to relabel the attribute names for those two.

Did you already test this theory to confirm it works? I didn't know attributes had to be lowercase. Don't see the HA dev docs saying this but we can make this change for these attributes so it plays nicely if you confirm the casing was the issue.

**Comment by finnzz** [comment]
Yes, there is a thread about the geocoded_coded entity from the app not showing on the map card because it's looking for latitude/longitude, rather than Latitude/Longitude. And after creating a mirrored sensor with lowercase longitude/latitude attribute names it shows up on the map.

https://community.home-assistant.io/t/lovelace-map-card-not-displaying-geocoded-entities/210947

I can also confirm that if go into developer tools / states and set the geocoded location entity attribute to lowercase longitude/ latitude that it appears on the map card.

I don't actually know if lower case attribute names is official HA etiquette, but after seeing that thread I looked over a bunch of my entities, and I couldn't find any that use uppercase letters.

The case sensitivity seems a little unnecessary, but maybe there is a good reason for it?

**Comment by dshokouhi** [comment]
Ok we will fix it for these attributes

I was pointed to some more correct HA core code:
https://github.com/home-assistant/core/blob/777ae584d49e45a074f74cdff47f0706597907c8/homeassistant/const.py#L434-L435

thanks for raising the issue :)

**Comment by finnzz** [comment]
Thank you!

**Comment by dshokouhi** [comment]
lets leave this open until the PR is merged :)
