### ISSUE TITLE
Persistent connection on home WiFi app notification bug

### ISSUE THREAD

**Issue by dnestico** [home-assistant/android#2345]
The problem
So I have to set to show the persistent notification but only on home WiFi and for some reason even though I have my home WiFi set in the app it's not showing.

Any idea why?

What version of Home Assistant Core has the issue?
2022.3.0

![156896906-a6c005b2-cab8-4d38-9604-aa4e4875bd66](https://user-images.githubusercontent.com/3034555/156914308-ed5836cc-a684-4f49-92ab-37f6aceca2d8.png)

![156896905-10f34462-ee8a-481a-8160-c8e94e024723](https://user-images.githubusercontent.com/3034555/156914318-27822da7-01ab-4437-b8f7-0f8f3fbed2db.png)

**Comment by dshokouhi** [comment]
What did the issue template get removed? It contains important information to help you out like logs and the app version. Please don't skip over items in the template.

**Comment by dnestico** [comment]
Ok so I switched it back to "On home WiFi only" and refreshed the log then switched back to "Always". here's the companion all log:


LOG:

https://drive.google.com/file/d/1uZfTDz6WEwcDFfeEXP0exJDFElFzw7oJ/view?usp=drivesdk

**Comment by dshokouhi** [comment]
Are you using the internal URL? Looks like it's blank according to the log.

```
03-06 17:01:36.940 10587 10587 D UrlRepository: localUrl is: false and usesInternalSsid is: true
```

**Comment by dnestico** [comment]
Yes there's the internal url filled out there, should I switch it to the "homeassitant.local" url instead of the nabu casa url and that will solve it?


![Screenshot_20220306-173700.png](https://user-images.githubusercontent.com/3034555/156945097-20103a39-70c9-4169-a48e-3d74936864e6.png)

**Comment by dshokouhi** [comment]
Interesting for some reason it's blank in the apps storage. Try editing the field and saving it to get it to save. I would also remove the screenshot in your comment.

**Comment by dnestico** [comment]
I wonder if this has something to do with it.... not sure why I always get this error when trying to login through home assistant cloud on some devices 

<img width="642" alt="Screen Shot 2022-03-06 at 5 45 53 PM" src="https://user-images.githubusercontent.com/3034555/156945467-8c28ffd5-2ccf-4d23-a440-4ada959c3fd3.png">

**Comment by dshokouhi** [comment]
That looks like its failing due to trusted networks and the device not being allowed.  Thats not related to this issue. 

Your issue is that the app is reporting the local URL as blank or null when for some reason the settings screen shows it has it. If you could click on the internal URL field and either change it to be your correct local address or just click ok it should hopefully save properly and fix your issue.

**Comment by dnestico** [comment]
This fixed it!

I replaced it with the "homeassisitant.local" URL and it worked.

**Comment by dnestico** [comment]
This fixed it!

I replaced it with the "homeassisitant.local" URL and it worked.
