### ISSUE TITLE
Update location on gps change 

### ISSUE THREAD

**Issue by bschatzow** [home-assistant/android#2346]
**Is your feature request related to a problem? Please describe.**

I use the mobile app to track my location using Waze for example. It would be nice to see location change when gps changes.

**Describe the solution you'd like**

Driving , gps changes, information sent to home assistant.
**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
have you considered using an automation that looks at the state of the detected activity sensor and when it changes to `in_vehicle` you enable high accuracy mode? You can then have it turn off high accuracy mode when it no longer detects you `in_vehicle`

The app requests location updates based on time, there is no setting to register for gps changes and send updates from there. You may need to be more explicit in the ask here as its not much to go by.

https://developer.android.com/training/location/change-location-settings#location-request

**Comment by JBassett** [comment]
If you are suggesting that we listen for whenever the device gets a new location, we already do that. The app should send an update every 30 seconds in the background if another app is requesting the location.

**Comment by bschatzow** [comment]
On the gps logger app there is a setting to send points based on a location change.  This is users set in meters.  It can be any number you want.  Mine is set at 25.  If no change no data is sent.  You also set how often to log.  I.e 60 seconds if no distance change.  
I don't know how the mobile app works.  It just seems like the information is not updated that often based on using the Waze app.  This maybe an incorrect assumption on my part.

What I was hoping to be able to see real time movement similar to google maps on my phone.

**Comment by dshokouhi** [comment]
> I don't know how the mobile app works. It just seems like the information is not updated that often based on using the Waze app. This maybe an incorrect assumption on my part.

You should see updates come in every 30 seconds when using Waze. Do you not see that frequency?

> What I was hoping to be able to see real time movement similar to google maps on my phone.

If you use high accuracy mode you'll see updates every 5 seconds which is frequent enough to see it move in near real time.

**Comment by bschatzow** [comment]
I was not.  I'll try again and get back to you on this.

**Comment by dshokouhi** [comment]
> I was not. I'll try again and get back to you on this.

ok lets look at the logs to see if those events are being skipped, make sure to capture a few minutes of waze being open so we can see what the on device logs look like.

**Comment by bschatzow** [comment]
The reason I thought it wasn't as while I was driving Waze was not updating the time. I have set it for two minutes as well as creating a script to update now. I thought if Waze wasn't updating it was not getting updated GPS readings.  If you are sending every 30 seconds it must be something else.  Also I do not need a change as every 30 seconds is good enough.
