### ISSUE TITLE
Geocoded location now also appears on map (duplicating device as the device tracker is also there)

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/android#2348]
**Home Assistant Android version:**
beta-2142-2a2422b6-full

**Android version:**
12

**Phone model:**
Galaxy A52 5G (SM-A526B)

**Home Assistant version:**
2022.3.1

**Last working Home Assistant release (if known):**
n/a

**Description of problem:**
Since the latest HA Companion app upgrade (latest beta), a new device shows in the Home Assistant frontend map pane. This is duplicate information, as the `device_tracker` entity _also_ shows in the map. I actually don't see the added value of the `geocoded location sensor` showing in the map, as one cannot attach it to a person (`person` only allows `device_tracker` devices) and it now duplicates information. Furthermore, the sensor also isn't hidden in the home zone:

![image](https://user-images.githubusercontent.com/33529490/157061454-4c8c9a79-b86a-4e9a-9d3e-c5fadc8640d7.png)

"Geocoded location" to me insinuates that the source (GPS coordinates) are taken and modified/calculated towards the sensor state value. I don't see why these GPS coordinates should be attributes of this sensor, because they cause the side effect of being shown on the map with no way to turn this behavior off.

Probable regression of https://github.com/home-assistant/android/pull/2341 (which tried to fix https://github.com/home-assistant/android/issues/2339)

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
n/a

**Screenshot of problem:**

![image](https://user-images.githubusercontent.com/33529490/157061915-4e5db090-d1e5-4296-89fb-3cf70cc39683.png)

Same device, twice on the map

**Additional information:**

**Comment by dshokouhi** [comment]
> You cannot hide this on the map pane (!= map card) as a user - it will show as a duplicate device.

That still doesn't mean the map panel has a potential bug. Looking at the description it should only show  device trackers: https://www.home-assistant.io/integrations/map/

>  Functionality wise this now changes how this sensor is published / used / presented.

That doesn't really matter the attributes were incorrectly cased and were not able to be used by HA core or the HA frontend at all so they needed to be fixed.

> My point is more; having these attributes makes the sensor appear in the map pane. It shouldn't, as the device_tracker is already there (with the same lat/long attributes). Why does this sensor need to have these lat/long attributes? It's duplicating the same information (in both the device_tracker and the sensor)

This sensor has existed for years even with the iOS app which existed before the android app, we should not remove these attributes just because they seem to duplicate the device tracker. These attributes describe the state of the sensor which is the exact purpose of an attribute

> edit: oh, and actually they aren't even providing the same accuracy in the GPS coordinates, with the device_tracker having slightly better accuracy

Thats fine the sensor has always reported like that, thats a separate issue from the issue filed here.

**Comment by hmmbob** [comment]
Hmm, fair. Let me file an issue with core.

Thinking `frontend` repo, as the `map` component is rather tiny (https://github.com/home-assistant/core/blob/dev/homeassistant/components/map/__init__.py) - would you agree?

**Comment by dshokouhi** [comment]
Thanks for filing the bug there, lets see what comes of it.

**Comment by hmmbob** [comment]
Not much yet, that's for sure. :-(

**Comment by AdmiralStipe** [comment]
Would pleeeeeeease someone look at this, it's so anoying...

**Comment by dshokouhi** [comment]
This issue has been closed for sometime and this is not the team that will be fixing the issue, best to ask in the open issue that has been placed in the appropriate repo.
