### ISSUE TITLE
Android App trying to connect to Nabucasa

### ISSUE THREAD

**Issue by kingpepe85** [home-assistant/android#2351]
**Home Assistant Android version:**
2022.2.1-full

**Android version:**
12

**Phone model:**
Samsung Galaxy A52

**Home Assistant version:**
2022.3.3

**Last working Home Assistant release (if known):**
2022.3.3

**Description of problem:**
When I want to connect my Android App to Home Assistant via a duckdns URL it still tries to use my old Nabucasa URL (which I don't use anymore). 
I have changed both the internal and external URL in the configuration frontend. When I then manually put in the URL again in the Android App configuration it works. But the app somehow still "knows" my Nabucasa URL which should't be the case.
I think the same happens with my connected WearOS app, but there I can't make the connection happen because it only says "loading entities" but has no way to take a look at the configuration during that.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20220308-131006_Home Assistant](https://user-images.githubusercontent.com/34244805/157236735-3181e483-04ea-41a5-b300-b39f5c993839.jpeg)
![Screenshot_20220308-131102_Home Assistant](https://user-images.githubusercontent.com/34244805/157236733-83dd1d1e-3e7b-4e26-8308-2574218b1cc3.jpeg)

**Additional information:**
I know this might be two different issues but I felt like putting them together because they might be the same bug.

**Comment by dshokouhi** [comment]
Try these steps https://companion.home-assistant.io/docs/troubleshooting/faqs#starting-fresh-with-the-android-app

**Comment by kingpepe85** [comment]
I already did. Sorry I didn't mention it. I also completely reinstalled both, the smartphone and the watch app.

**Comment by dshokouhi** [comment]
Reinstall is not the same as following the steps in the link, its important to follow the steps in the link precisely as they avoid auto back up

**Comment by kingpepe85** [comment]
I know, that's why i tried both. ;)

**Comment by dshokouhi** [comment]
hmm are you still logged into the cloud?

**Comment by dshokouhi** [comment]
> When I then manually put in the URL again in the Android App configuration it works. But the app somehow still "knows" my Nabucasa URL which should't be the case.

Are you saying after changing the URL again in App settings that it reverts back to the Nabu Casa URL or are you saying its not right that it picked up the old URL?

Our app also gets URLs from HA which I suspect is happening because your nabu casa account is still logged into HA and/or the remote URL is still activated.

**Comment by kingpepe85** [comment]
> hmm are you still logged into the cloud?

Yes, I think that was he case. But I couldn't see a way to log out. Then yesterday I deleted my nabucasa account which at first didn't make any difference. Today it said that it couldn't verify my credentials so it logged me out. Now it works fine. So that must have been the problem.
I still think this is a bug, because HA shouldn't have used the Nabucasa remote URL or it should at least be possible to switch that behavior off.

**Comment by dshokouhi** [comment]
> I still think this is a bug, because HA shouldn't have used the Nabucasa remote URL or it should at least be possible to switch that behavior off.

This is by design, when you register with HA core it updates the app with all URLs including the cloud to make it easier for new users. We will not be changing that behavior as logging out of the account is the correct solution.
