### ISSUE TITLE
Location bug on the HA

### ISSUE THREAD

**Issue by SlyFoxeh** [home-assistant/android#2360]
**Home Assistant Android version:**

**Android version:**

**Phone model:**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem:**

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

After update HA to the latest (at least latest 2 releases) i got troubles with a location.
Now i have Home Assistant 2022.3.3:
My setup have 3 connected devices with installed HA app:
- Pixel 3a, Android 12L beta
- Huawei P Smart Z Android 10 (API 29)
- Huawei 7C Android 8.0 (API 26)

What's is going on?
- On pixel 3A user's geolocation works okay and updates on the map and triggers automatisation well
- On the Huawei P Smart Z dosn't have any users on the map, no location appear, but tracker sensor present 
- On the Huawei 7C no location updates, user stuck on the last location where been before last update HA setup.
All of the phones have latest application from the Google Play

**Comment by dshokouhi** [comment]
Please do not delete the issue template when you create an issue. All requested information is important in order to help you out. Please add it back.

**Comment by dshokouhi** [comment]
https://companion.home-assistant.io/docs/troubleshooting/faqs#device-tracker-is-not-updating-in-android-app

Try these steps. Make sure to fill out the issue template and don't skip a step please.

**Comment by dshokouhi** [comment]
I see that the template was added but none of the information was supplied, we will not be able to help you if you do not get us the requested information in addition to the comment above.

**Comment by dshokouhi** [comment]
Closing due to lack of response
