### ISSUE TITLE
Add a sensor for the CarConnection API to detect if the app is connected to Android Auto

### ISSUE THREAD

**Issue by Mincka** [home-assistant/android#2367]
**Is your feature request related to a problem? Please describe.**
I would like the ability to detect if the phone is connected to Android Auto (either through USB or Wi-Fi).
In my case, I would find it useful to use it as a condition to open the gate when I am coming home in the car, as an additional control with location.

**Describe the solution you'd like**
Would it be possible to use the `CarConnection` API ([documented here](https://developer.android.com/training/cars/apps#car-connection)) to add a sensor to the app?
This API needs to be available without having the app itself supporting Android Auto (#791)
[This should be the case](https://stackoverflow.com/questions/70051192/how-to-detect-android-auto-is-connected-with-android-12#comment126203680_71384066) but it needs to be confirmed.

It should work for Android Auto over USB and Wi-Fi.
With this kind of sensor, the user could use an automation to use it as a trigger or a condition.

**Describe alternatives you've considered, if any**
Using activity detection and or car Wi-FI AP / BT detection (but that can be disabled, not configured...).

**Additional context**
This could avoid implementing additional rules in the High Accuracy sensor as requested in #1516

**Comment by dshokouhi** [comment]
The comment says you don't have to design for Android auto but in order to use the API we need to create a car session and use the car libraries. This may not be doable given we need to create a car session.

**Comment by Mincka** [comment]
From I found while looking into this matter, `UiModeManager` was the "previous" way to identify the usage of Android Auto. It was used by Tasker but it seems that it's broken in Android 12.
There is an [open issue](https://issuetracker.google.com/issues/207389461) about this but the workaround is again to use the Connection API, which seems to also have a pitfall:
https://issuetracker.google.com/issues/207389461#comment8

**Comment by penright** [comment]
Not sure what the etiquette is to upvote a request :-)  I was looking to see if there was a Bluetooth open issue that I had and ran across this.

This would be useful to me, The first thing I do is plug my phone into my AA. That would tell me I am on the move. :-)

**Comment by Mincka** [comment]
Just thank you. ❤
