### ISSUE TITLE
Bug when entering double-digit numbers in input_datetime fields

### ISSUE THREAD

**Issue by MuellerNicolas** [home-assistant/android#2384]
**Home Assistant Android version:**
2022.3.0-full
**Android version:**
11 RKQ1.200826.002
**Phone model:**
Xiaomi Mi 9T Pro (using MIUI Global 12.5.1)
**Home Assistant version:**
core-2022.3.5
Home Assistant OS 7.5
**Last working Home Assistant release (if known):**

**Description of problem:**
I have encountered a problem when entering double-digit numbers into `input_datetime` fields. When I open the input field, the keyboard appears. After I type in the first digit, the keyboard closes itself. For example, if i want to enter the value `31` in the input `minute` field, the keyboard closes itself, after typing a `3` and adds a leading `0`. If I click into the input `minute` field again and type in a `3`, it doesn't close and i can type the `3` and `1`.

Further behaviour:
1. Start typing the first digit `3`, it closes itself and adds a leading `0`.
2. Open again and start with antoher first digit than `3`, it closes itself and adds a leading `0`.

The configuration hasn't changed since 2 years and worked till now. It looks like this:
configuration.yaml:

```yaml
input_datetime: !include_dir_merge_named input_datetimes/
```

/config/input_datetimes/alarm.yaml:

```yaml
alarm_time:
  name: Uhrzeit
  has_date: false
  has_time: true
```

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
1. Click in Input field:
![image](https://user-images.githubusercontent.com/49995854/159171399-6a604d40-1e9c-41bd-b309-7101a542b815.png)
2. Enter `3`
3. Keyboard closes, adds leading `0` and looks like this:
![image](https://user-images.githubusercontent.com/49995854/159171466-47185145-930b-43c1-b47b-7380cc0bd2ff.png)

**Additional information:**

**Comment by dshokouhi** [comment]
Does this issue exist in chrome for Android on the same device?

**Comment by MuellerNicolas** [comment]
> Does this issue exist in chrome for Android on the same device?

Yes

**Comment by dshokouhi** [comment]
> > Does this issue exist in chrome for Android on the same device?
> 
> Yes

Ok please open an issue with the HA frontend
