### ISSUE TITLE
Headphones sensor no longer works

### ISSUE THREAD

**Issue by rigrig** [home-assistant/android#2387]
**Home Assistant Android version:** 2022.2.1-minimal

**Android version:** 11 (LineageOS 18.1-20220314-NIGHTLY-oneplus3)

**Phone model:** OnePlus 3T

**Home Assistant version:** 2022.3.5

**Last working Home Assistant release (if known):** Not sure.

**Description of problem:** The headphones sensor still reports `false` when I plug in my headphones.

**Traceback:** Log of plugging in and unplugging headphones
```
03-21 15:34:34.891  9411  9411 D SensorReceiver: Received intent: android.intent.action.HEADSET_PLUG
03-21 15:34:35.149  9411 16544 D NextAlarm: Next alarm is scheduled by com.android.deskclock with trigger time 1647897720000
03-21 15:34:35.237  9411 16544 D SensorReceiver: Nothing to update
03-21 15:34:35.581  9411 16544 D LogcatReader: Read logcat for pid 9411
03-21 15:34:35.618  9411 16544 D LogcatReader: Done reading logcat for pid 9411
03-21 15:34:36.742  9411  9424 E android.minima: failed to connect to jdwp control socket: Connection refused
03-21 15:34:37.530  9411  9411 D SensorReceiver: Received intent: android.intent.action.HEADSET_PLUG
03-21 15:34:37.785  9411 16544 D NextAlarm: Next alarm is scheduled by com.android.deskclock with trigger time 1647897720000
03-21 15:34:37.845  9411 16544 D SensorReceiver: Nothing to update
03-21 15:34:38.674  9411 16544 D LogcatReader: Read logcat for pid 9411
```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/2941436/159286998-9edfcccf-ccce-4577-96d7-afb0270ac7e9.png)

**Additional information:**
The headphones work fine: music is played through them, and Android shows a little "headphones connected" icon in the status bar.

I know it was working before:
I have an automation which is triggered by this and other sensors, but only recently noticed it never triggers from the headphones any more. Because the other triggers still run, usually at the same time, I'm not sure when this sensor stopped working. I know I tested the sensor at the time I wrote the automation though.

**Comment by dshokouhi** [comment]
AS you are on lineage OS its more than likely a custom ROM issue because the app simply reports the value from an android API. Wouldn't be the first time a custom ROM reports an incorrect value.

**Comment by rigrig** [comment]
Thanks, that pointed me in the right direction:
https://github.com/home-assistant/android/blob/e3a96d588eb8ca4d0edb5eda71a572098258fea9/app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt#L174-L177
should be
```kt
val audioDevices = audioManager.getDevices(AudioManager.GET_DEVICES_OUTPUTS)
```

**Comment by dshokouhi** [comment]
wow we havent change the logic for this sensor since it started, oops. Good catch :)
