### ISSUE TITLE
Webview gesture quickbar is triggered on 3 finger touch, not 3 finger swipe down

### ISSUE THREAD

**Issue by Mincka** [home-assistant/android#2392]
**Home Assistant Android version:**
beta-2188-e24712dc-full

**Android version:**
12

**Phone model:**
Galaxy S20+

**Home Assistant version:**
2022.3.5

**Last working Home Assistant release (if known):**
Don't know

**Description of problem:**
As soon as I touch the screen with 3 fingers, the quickbar appears, no need to swipe down. I cannot tell when it started to act like that. I tried with and without pinch to zoom enabled, same result. Also, the blue circle of one the finger stays displayed on all screens, not all the time.

https://imgur.com/9PNEctC

I tried to find relevant things in the logs but didn't find any. The original logging was removed in the PR. If you tell me what I need to search I can post an extract.

Original PR: https://github.com/home-assistant/android/pull/1356/commits
Code is still the same in master.

Side note: I add a look at the implementation and this [comment](https://github.com/home-assistant/android/pull/1356/commits/fc1362c4bfef37f891c02475096ca35316f09e26#r573195504). And indeed, I can add `e` every time there is an input field by using 3 finger touch. 😅

**Comment by Mincka** [comment]
It even looked like this in your original [video](https://photos.google.com/share/AF1QipML8n2zINpir2LBTLB8Ehj2cxpCJNYo8mYWg_w9Q7jMDd5_DCnheR1kLuQQ7cNLUQ?key=YzdfVU51RVpUZGJBNFBXVmh0RWNaRU40WkF1amlB). Can you confirm it requires swipe down on your side?

I tried with a Galaxy Z Flip 3, exactly same result.

By the way, the constant used is [deprecated](https://developer.android.com/reference/android/view/MotionEvent#ACTION_POINTER_3_DOWN) in the docs.

**Comment by dshokouhi** [comment]
> It even looked like this in your original [video](https://photos.google.com/share/AF1QipML8n2zINpir2LBTLB8Ehj2cxpCJNYo8mYWg_w9Q7jMDd5_DCnheR1kLuQQ7cNLUQ?key=YzdfVU51RVpUZGJBNFBXVmh0RWNaRU40WkF1amlB). Can you confirm it requires swipe down on your side?

As long as android reports the conditions its working as designed, can you confirm you didn't move your fingers a fraction of a millimeter :)  (thats a trick question as its impossible to tell lol)



> By the way, the constant used is [deprecated](https://developer.android.com/reference/android/view/MotionEvent#ACTION_POINTER_3_DOWN) in the docs.

deprecated does not mean its not working.

if you want to debug it feel free to add logs for the touch event and look at the actions being sent. For the purpose of the feature the code is working as designed.  I think in a future HA version the quick bar will be triggered by a search button on the header and at that point we will remove this workaround.

**Comment by JBassett** [comment]
I was able to also reproduce,  any 3 finger event triggers the menu.   Looks like we need to be more specific when dealing with the event.

**Comment by jpelgrom** [comment]
> as long as the android system reports the expected action we will show the quick bar gesture 
https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L239

I think `DOWN` in the constant actually refers to the action of a finger being detected on/pressed down on the screen, otherwise there probably also would've been a left/right instead of only down/up. As mentioned in the documentation: ["Pointer movements are described by motion events with `ACTION_MOVE`"](https://developer.android.com/reference/android/view/MotionEvent#device-types), full sequence is down -> (move ->) up/cancel.

**Comment by Mincka** [comment]
> As long as android reports the conditions its working as designed, can you confirm you didn't move your fingers a fraction of a millimeter :) (thats a trick question as its impossible to tell lol)

It happens when I start the movement from the bottom so literally a swipe up. Opening a ticket for an option to disable it like Pinch to Zoom.
