### ISSUE TITLE
Bypass lock app feature when command_webview is used

### ISSUE THREAD

**Issue by Coolie1101** [home-assistant/android#2408]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
If possible, wake the phone (turn screen on), launch app, auto login, and display the view based on the automation action/title.
RE: https://community.home-assistant.io/t/webview-auto-login/405367

**Describe alternatives you've considered, if any**
I don't know of an alternative.

**Additional context**

**Comment by dshokouhi** [comment]
> If possible, wake the phone (turn screen on),

We already have a command for that



> launch app, auto login, and display the view based on the automation action/title.

This means that the user has enabled the lock app option in Companion App configuration and they are requesting to bypass it only when `command_webview` is used

**Comment by dshokouhi** [comment]
We have recently added a notification command to control the app lock feature. As this now allows the user to control when this happens I am going to close this request.  You should be able to use this command to turn off the lock and then turn it back on again once the user leaves the app. You can detect that with the app importance sensor to see if its in the `foreground` or not.

https://companion.home-assistant.io/docs/notifications/notification-commands#app-lock

https://companion.home-assistant.io/docs/core/sensors#app-importance-sensor
