### ISSUE TITLE
View in Dashboards when an object was updated

### ISSUE THREAD

**Issue by alexfrolkin** [home-assistant/android#2409]
**Is your feature request related to a problem? Please describe.**

In one of the latest updates of the assistant for Android, the ability to view the update time of the object data in the interface has disappeared. Is that how it was intended? It was very convenient to quickly see if data is coming from the phone by its location.
**Describe the solution you'd like**

Return this functionality
**Describe alternatives you've considered, if any**

No
**Additional context**

![Снимок экрана 2022-03-26 104617](https://user-images.githubusercontent.com/77844696/160230283-5d1facb5-c218-4e06-a478-d2432bb1b05b.png)

**Comment by dshokouhi** [comment]
do you see the same issue in chrome for android on the same device?

**Comment by alexfrolkin** [comment]
> do you see the same issue in chrome for android on the same device?

yes, there is also no pop-up window through the browser.  I checked on several devices, they also do not have this window

**Comment by dshokouhi** [comment]
ok as this issue occurs in a browser, please file an issue with the HA frontend (after ensuring one doesnt already exist there)

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=bug_report.yml

Closing this issue as it is not one the app can solve.
