### ISSUE TITLE
Wear OS App incorrect battery temperature/units

### ISSUE THREAD

**Issue by finity69x2** [home-assistant/android#2414]
**Home Assistant Android version:**

2022.3.0-full

**Android version:**

12

**Phone model:**

Galaxy S21 Ultra / Galaxy Watch 4 Classic

**Home Assistant version:**

2022.3.5

**Last working Home Assistant release (if known):**

**Description of problem:**

The battery sensor in the Wear OS app reports temperature in Celsius but the "unit of measurement" of the sensor reports as F.

My HA default temperature units are in F

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

![image](https://user-images.githubusercontent.com/32221243/160446312-9d40255b-8b2f-407c-a723-84d32f0cd688.png)

**Additional information:**

The screenshot above is with the watch sitting on a nightstand in my bedroom so the temperature is definitely not 23.7F! :)

**Comment by dshokouhi** [comment]
This is actually a HA core bug, as the issue is locked please create a new issue in HA core with all details and link to the bug below.

https://github.com/home-assistant/core/issues/57085
