### ISSUE TITLE
WearOS Shortcuts Tile button press feedback.

### ISSUE THREAD

**Issue by ruifung** [home-assistant/android#2419]
**Is your feature request related to a problem? Please describe.**

When pressing buttons on the shortcut tile in WearOS, there does not appear to be any kind of noticable feedback that the command was sent successfully. Which is slightly annoying when trying to open a gate since it might send several button presses.

**Describe the solution you'd like**

Perhaps a visual / vibratory indicator that the button was pressed. Or a command was sent.

**Describe alternatives you've considered, if any**

Maybe a toast message would work too, but might be suboptimal on a watch sized screen.

**Additional context**

This is something I noticed when trying out using HASS to control autogate switch relays via my Galaxy Watch 4.

**Comment by dshokouhi** [comment]
Go to settings in the app and turn in haptic feedback or toast notifications.
