### ISSUE TITLE
Alarm label as attribute next alarm

### ISSUE THREAD

**Issue by arnoeneva** [home-assistant/android#2428]
**Is your feature request related to a problem? Please describe.**

When using the next alarm sensor from the android app in a automation the automation is started when you set a alarm with the standard app. You can set mutiple alarms in android now there is no way you can differentiate witch 

**Describe the solution you'd like**

Add the alarm label as attribute to the next alarm sensor or make every (active) alarm available from the android device. 

**Describe alternatives you've considered, if any**

Using extra conditions (time window) in the automation witch is not perfect and use a alternative alarm app for only this function.

**Additional context**

I'm using the automation to a wake-up light in home assistant and now it will start the automation based on every next alarm.

**Comment by jpelgrom** [comment]
Unfortunately, the alarm label isn't visible to other apps. See #777 and the issues linked there, which is the same request.

**Comment by dshokouhi** [comment]
Closing per above comment and linked issue
