### ISSUE TITLE
Devices connected with TuyaSmart do not register as off correctly

### ISSUE THREAD

**Issue by IBeTheBlueCat** [home-assistant/android#2433]
I am using simple button cards, when the lights are on, I am able to turn them off with the cards, but the card doesn't update to show that the light is off, meaning I cannot turn the light back on with the card, rather I have to go to "More info" which I have as the long press action, then turn the toggle switch in that menu off and back on again.

This may be a problem with my setup, but I don't have the issue on my PC in a web browser, so I thought I should report it just in case.

**Comment by dshokouhi** [comment]
Can you reproduce the issue in chrome for Android on the same device?

**Comment by IBeTheBlueCat** [comment]
I attempted to reproduce this issue in chrome, but the card worked as intended.
Additionally, when I went back to the app, the issue had been fixed.
Not entirely sure how this happened, sorry for any inconvenience, I will make sure to open another issue if the problem persists.
