### ISSUE TITLE
Android Next Alarm is periodically changing to now for approximately 4 minutes

### ISSUE THREAD

**Issue by galacticat** [home-assistant/android#2434]
**Home Assistant Android version:**
2022.3.0-full
**Android version:**
Android 12
**Phone model:**
Pixel 6
**Home Assistant version:**
2022.3.8
**Last working Home Assistant release (if known):**

**Description of problem:**
The "Next Alarm" sensor is periodically changing to Now for approximately 4 minutes

[Screenshot of sensor](https://i.imgur.com/4oh8APp.png)
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

`Logs rolled over before I could capture the place where the Next Alarm value changed. I'll update with logs if I can capture it`

**Comment by dshokouhi** [comment]
Do you have an allow list set for the sensor? You may need to research the offending `package` in the attribute and stop it from setting an alarm. All the sensor does is report the next alarm, we cannot remove alarms. It sounds like you have another app messing with it.  Closing this issue as the sensor is reporting real values, it is up to the user to find the offending package and stop using them. If you search for alarm issues in github you will see a lot of discussion saying the same thing.  You shoudl be able to use `package` and allow list to make this easiser.
