### ISSUE TITLE
Service calls

### ISSUE THREAD

**Issue by joostlek** [home-assistant/android#2444]
**Is your feature request related to a problem? Please describe.**

Currently I am using Bixby actions to unite my phone at 5 am so my mom can call me awake when I'm oversleeping myself. But when I'm at my girlfriends place, she gets annoyed with all my notifications sounding since 5 in the morning. But Bixby does have location support to enable and disable routines.

**Describe the solution you'd like**

Can we maybe support more actions for mobile devices so Home assistant can turn into a good alternative for IFTTT and Bixby routines?
**Describe alternatives you've considered, if any**

I am willing to help develop such features, although it's unclear for me if this ever has been tried before or why it wasn't implemented yet. Also, where do we discuss these kind of architectural things?

**Additional context**

**Comment by dshokouhi** [comment]
This is a very vague request, can you please try to be more explicit in to what you want to achieve? You can already have a service call widget and you can have a lot of sensors to automate things already. You can even adjust the ringer mode and do not disturb setting on your device.

**Comment by joostlek** [comment]
On my instance if I create an automation, the only thing I see is sending a notification, am I missing something?

**Comment by dshokouhi** [comment]
Yup check out this page

https://companion.home-assistant.io/docs/notifications/notification-commands

**Comment by dshokouhi** [comment]
Closing until we get a more precise request
