### ISSUE TITLE
High battery usage

### ISSUE THREAD

**Issue by JoshuaGarrison27** [home-assistant/android#2456]
**Home Assistant Android version:**

version 2022.3.0-full

**Android version:**

Android 12 — SP2A.220405.003

**Phone model:**

Pixel 5

**Hom Assistaent version:**

Home Assistant 2022.4.2

**Last working Home Assistant release (if known):**

Unknown

**Description of problem:**

High battery usage

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

![Screenshot_20220413-071907.png](https://user-images.githubusercontent.com/1706923/163170310-19453f1d-8883-4bc8-84ca-85d98720ba0f.png)

**Additional information:**

**Comment by dshokouhi** [comment]
What are you settings for the Persistent Connection and Sensor Update Frequency?

**Comment by dshokouhi** [comment]
what sensors do you have enabled?

**Comment by JoshuaGarrison27** [comment]
> what sensors do you have enabled?

Is there a way to export those? Otherwise, its just the basics, network information, and location (Standard, not high accuracy)

**Comment by JoshuaGarrison27** [comment]
> Do you have any of the notification sensors enabled?

No sir, these are all disabled:

- Active Notification Count
- Last Notification
- Last Removed Notification
- Media Session

**Comment by dshokouhi** [comment]
ok try these steps and lets see if that clears up the issue for you https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by JoshuaGarrison27** [comment]
Okay, I will look over that document.

These are all the sensors that I have turned on.

Activity Sensors:
- Detected Activity

Alarm Sensor:
- Next Alarm

Audio Sensors:
- Speakerphone

Battery Sensor:
- Battery Health
- Battery Level
- Battery State
- Battery Temperature
- Charger Type
- Is Charging

Bluetooth Sensors:
- Bluetooth Connection
- Bluetooth State

Geolocation Sensors
- Geocoded Location

Last Reboot Sensor
- Last Reboot

Last Update Sensor
- Last Update Trigger

Location Sensors
- Background Location
- Location Zone
- Single Accurate Location

Network Sensors
- ALL

Phone Sensor
- Phone State
- SIM 1
- SIM 2

Power sensors
- Phone State
- Interactive
- Power Save

Proximity Sensor
- Proximity Sensor

Storage Sensors
- Internal Storage

Time Zone Sensor
- Current Time Zone

**Comment by dshokouhi** [comment]
Do you see a lot of updates under the Last Update sensor when you saw this issue?

**Comment by JoshuaGarrison27** [comment]
> Do you see a lot of updates under the Last Update sensor when you saw this issue?

I honestly didn't think to check that before I followed the steps you suggested. Once I get my phone charged back up and it drains a bit, I'll report if that worked or not.

**Comment by JoshuaGarrison27** [comment]
So after a day, it seems like your recommended for [starting-fresh-with-the-android-app](https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app) has likely alleviated my issues. Thank you for the support! I will report back if the problem returns.
