### ISSUE TITLE
Allowing app to work in background cause crash of  camera apps everytime

### ISSUE THREAD

**Issue by boguslawb** [home-assistant/android#2458]
**Home Assistant Android version:**
2022.3.0-full

**Android version:**
8.1.0

**Phone model:**

Swift 2.x

**Home Assistant version:**
 core-2022.4.3

**Last working Home Assistant release (if known):**
not known

**Description of problem:**
Every time I allow HomeAssistant app to work in background I cannot use phone camera because everytime it crashes. After removing Home Assistant app and restart phone and flushing cache of camera app all is working again. If privilege to run at  background is not granted then camera is working fine.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
This is strange, our app does not touch the camera at all.  Do you see this issue with other apps running in the background? Are you running a custom ROM?  To run in the background our app uses standard android API behavior.  Can you look at the crash report from the camera to show that it comes from our app?  Have you tried any troubleshooting steps like starting fresh?

**Comment by boguslawb** [comment]
Camera app (every one I installed and the original from system) simply do not open and there is error that camera is occupied by other application. This happens immediately after I turn on HA app priviledge to run in background
It's original ROM updated from Android 7.1 Nougat, no custom ROM. Phone is Wileyfox Swift 2.x

**Comment by boguslawb** [comment]
Like I posted the procedure to regain access to camera is simply remove HA app and then flush cache and other settings of camera app. Doing the same without removing HA app do nothing - camera crashes everytime on startup

**Comment by dshokouhi** [comment]
please try these steps: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by dshokouhi** [comment]
Closing due to lack of response
