### ISSUE TITLE
Drop down menu hide last items when portait mode

### ISSUE THREAD

**Issue by daufinsyd** [home-assistant/android#2463]
**Home Assistant Android version:**
20220405.0 - latest
**Android version:**
MIUI 12.5.8
**Phone model:**
Poco f3
**Home Assistant version:**
2022.4.4
**Last working Home Assistant release (if known):**
Probably none
**Description of problem:**

When trying to add an entity to let's say a sensor panel, the last entities are hidden and can't be accessed in portait mode.
Turing the phone to landscape mode display them.
Cf Screenshots.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
Landscape: we see the battery, humidity and temperature of the same entity Temperature **extérieur **
![Screenshot_2022-04-17-09-22-15-200_io homeassistant companion android](https://user-images.githubusercontent.com/1218113/163705109-f8b3d7c8-727e-4c91-bf25-50ba9ad23eca.jpg)

Portrait we can only see the battery of the temperature **extérieur** entity
![Screenshot_2022-04-17-09-21-17-362_io homeassistant companion android](https://user-images.githubusercontent.com/1218113/163705140-33d55979-8859-4e1e-9588-b5d669b1b778.jpg)

**Additional information:**
Thanks for the app btw :)

**Comment by dshokouhi** [comment]
Does this issue also exist in Chrome for android on the same device? This definitely sounds like a HA frontend issue

**Comment by daufinsyd** [comment]
I tried using Firefox (on the mobile), the thing is, with firefox when the keyboard disappears, the item list is still displayed above the entity field, hence there is no issue.
However with the app, scrolling through the list make the keyboard disappears and the list item being display under the entity field.

**Comment by dshokouhi** [comment]
Can you please try Chrome for Android? Firefox is not based off Chromium which Androids WebView so it provides a better comparison. This still sounds like a HA frontend issue though as we do not have control over the appearance of drop down items. Did you check HA frontend issues to see if this already exists there?

**Comment by daufinsyd** [comment]
I tried with chrome and I also don't have the issue here
![IMG_20220422_090735](https://user-images.githubusercontent.com/1218113/164624062-7311d1a3-b048-4c1f-bebc-5d7e2e470c38.jpg).

**Comment by dshokouhi** [comment]
So the app still doesn't control this part of the HA frontend, we need to file a new issue with the HA frontend so they can take a look at it.  Looking at open HA issues I do see some related to elements being hidden so I suggest you take a look at those open issues to see if they are the same.  If you don't see a similar issue created there then please create a new issue and fill out the issue template completely.

https://github.com/home-assistant/frontend/issues
