### ISSUE TITLE
Sms Gateway feature

### ISSUE THREAD

**Issue by iciubotarasu** [home-assistant/android#2464]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use the app as an sms gateway. I am looking for some time now for an app that is able to act as an sms gateway and I couldn't find any to trust.

**Describe the solution you'd like**

Since the app supports already push notifications, maybe you can add the possibility for the app to send sms using the phone sim. This would help for example automating sending birthday messages or other automated interractions. This will enable users from all of the world to use their local providers to send smses locally on their behalf.

**Describe alternatives you've considered, if any**

There are some paid alternatives and some current integrations already in HA but those are sending mesaages from short numbers and not all of the cell providers allow sending sms messages by smtp.

**Additional context**

**Comment by dshokouhi** [comment]
The app can compose a SMS already but it cannot send an SMS. Sending an SMS is a restrictive permission reserved for apps set as the Default SMS app which we do not have. As this is a restrictive permission that we do not qualify for I am closing this request. If you would like to compose a message you can look into using `command_activity`.
