### ISSUE TITLE
Modification of the UUID, the Minor and the Major Bluetooth in HA Companion from HA server.

### ISSUE THREAD

**Issue by AxokGit** [home-assistant/android#2470]
**Is your feature request related to a problem? Please describe.**

I would like to change the UUID, minor and major of the Bluetooth iBeacon transmitter on an Android device from a Home Assistant server service. On the one hand for anonymity reasons (rotating UUID) and for security reasons.
And if possible, a system that would modify the UUID autonomously without dependence on the Home Assistant server (more details in the following)

**Describe the solution you'd like**

To do this we can use the Notification Commands like changing the transmission power. There would be one command for the UUID, one for the minor and one for the major.

**Describe alternatives you've considered, if any**

Another solution would be to modify our UUID autonomously on the Android application side without dependency on the server (thus functional without internet on the phone) using the Google Authentificator principle. From a given key and a time stamp, a key could be generated and would allow to have an unpredictable rotating UUID.

**Additional context**

My idea would be to unlock a front door by identifying ourselves from the signal our phone emits in Bluetooth. By rotating our UUID more or less frequently and unpredictably, this would prevent someone from impersonating us by listening to their UUID otherwise by duplicating the signal, anyone could enter.
In order to make this system battery efficient, we could imagine a system that changes our UUID using the principle of Google Authentificator. Everything would be on the phone without having an internet connection to update the UUID.

**Comment by Hellis81** [comment]
Love the idea.
The only thing I would want to add is a communication back to HA that the app has changed the UUID, or make the UUID a sensor so that the automation that sends the new UUID can make sure it's set or try again.

**Comment by dshokouhi** [comment]
The UUID is already an attribute for the sensor, this request is for a notification command to change the UUID which will also reflect in the attribute.

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt#L255

**Comment by lapodomo** [comment]
had the same idea , would be nice if we could change the UUID (temporary) by notification command.
if we use a esp32 to detect the original UID then send a generated UUID by the esp to the phone so the esp can check if the generated uid matches the UUID send out.
