### ISSUE TITLE
Device controls do not work ("Compatible controls unavailable")

### ISSUE THREAD

**Issue by TheDevFreak** [home-assistant/android#2481]
**Home Assistant Android version:**
beta-2234-6c64b31f-full

EDIT: I noticed that the play store was serving an old version of the beta, grabbed the APK for beta-2278-ec6ae434-full -- issue persists.
**Android version:**
Android 13 Beta 1 (Though, this issue also existed on Android 12L Beta)
**Phone model:**
Pixel 6 Pro
**Home Assistant version:**
2022.4.6

**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
I cannot use any device controls, it results in "Compatible controls unavailable" being shown when I go to "Add Controls", despite having set up one of them with a light entity.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
04-27 11:41:33.897  4978  6581 E HaConProService: Error getting list of entities
04-27 11:41:33.897  4978  6581 E HaConProService: java.lang.IllegalArgumentException: Mode 4 not supported in flag.
04-27 11:41:33.897  4978  6581 E HaConProService: 	at android.service.controls.templates.TemperatureControlTemplate.<init>(TemperatureControlTemplate.java:188)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at io.homeassistant.companion.android.controls.ClimateControl.provideControlFeatures(ClimateControl.kt:86)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at io.homeassistant.companion.android.controls.HaControl$DefaultImpls.createControl(HaControl.kt:43)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at io.homeassistant.companion.android.controls.ClimateControl.createControl(ClimateControl.kt:18)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at io.homeassistant.companion.android.controls.HaControlsProviderService$createPublisherForAllAvailable$1$1.invokeSuspend(HaControlsProviderService.kt:82)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
04-27 11:41:33.897  4978  6581 E HaConProService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665
```

**Screenshot of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
The error suggests that the current mode of a climate entity (`heat_cool` in Home Assistant, `MODE_HEAT_COOL` in Android) isn't actually supported by that entity.

Could you use the developer tools on your Home Assistant instance to get the state of your climate entity/entities and the attributes? Example:
![image](https://user-images.githubusercontent.com/8148535/165535498-5d7c8f33-8d0d-480c-b9f4-38bc69333e7e.png)

**Comment by jpelgrom** [comment]
`heat_cool` while it only supports `off` 🤯

> I feel like the android app should handle these kinds of errors perhaps?

I agree and have submitted a potential fix. Would you be open to installing a test version of the app, re-enabling the `climate.computime_slt2_f2e30702_thermostat` entity, and checking if it now allows you to add device controls? You can download it from [here](https://github.com/home-assistant/android/actions/runs/2233952302) (use the file app-full-debug.apk), the test version installs alongside the current app and you can remove it after testing without any problems.

**Comment by TheDevFreak** [comment]
> `heat_cool` while it only supports `off` 🤯

Yeah, these hive devices are certainly something haha..


> > I feel like the android app should handle these kinds of errors perhaps?
> 
> I agree and have submitted a potential fix. Would you be open to installing a test version of the app, re-enabling the `climate.computime_slt2_f2e30702_thermostat` entity, and checking if it now allows you to add device controls? You can download it from [here](https://github.com/home-assistant/android/actions/runs/2233952302) (use the file app-full-debug.apk), the test version installs alongside the current app and you can remove it after testing without any problems.

Tested this and it works fine. 👍

Interestingly this has lead me to another bug that is when I press and hold on a control it completely crashes systemui, this could be related to Android 13 Beta I spose, but press and hold works fine for controls from the Google Home app, although I suppose that's for another bug report

**Comment by dshokouhi** [comment]
> Interestingly this has lead me to another bug that is when I press and hold on a control it completely crashes systemui, this could be related to Android 13 Beta I spose, but press and hold works fine for controls from the Google Home app, although I suppose that's for another bug report

its a known issue actually https://github.com/home-assistant/android/issues/2251 was introduced in a monthly security update

**Comment by TheDevFreak** [comment]
> its a known issue actually #2251 was introduced in a monthly security update

Ah ok, good to know it's already known.
