### ISSUE TITLE
Backend-selected Theme Not Changing with set_theme

### ISSUE THREAD

**Issue by pnichols77** [home-assistant/android#2483]
**Home Assistant Android version:**
2022.3.0-full

**Android version:**
9

**Phone model:**
Samsung Galaxy S8

**Home Assistant version:**
Home Assistant 2022.4.7

**Description of problem:**

I have some automations that use the set_theme service. On two different computers this results in the theme changing instantly. However, on the mobile app it stays stuck at the one theme. I can invoke the theme service on my mobile, and see my laptop theme change. It's as if the app isn't respecting the backend theme being changed. 

All platforms have the theme set to back-end selected. I can manually change the device theme in the app by picking from the list in HA settings.

**Comment by dshokouhi** [comment]
What happens in chrome for Android on the same device?

**Comment by pnichols77** [comment]
> What happens in chrome for Android on the same device?

Exactly the same behaviour. Theme stays the same on the phone, but changing it on the phone updates the theme on my laptop which also has theme as backend selected. 

I'm not choosing any 'light' or 'dark' theme modes with the theme service call and its set in the mobile in both the app and browser to auto select.

**Comment by dshokouhi** [comment]
> Exactly the same behaviour.

As this issue also occurs in chrome for android that means this issue is related to the HA frontend and not the app. Please check for open issues and if you don't see one please create a new issue making sure to complete the issue template.

https://github.com/home-assistant/frontend/issues
