### ISSUE TITLE
Unable to open URL using the clickAction feature of Notifications

### ISSUE THREAD

**Issue by HairyHook** [home-assistant/android#2486]
Hi there,

I'm unable to open URLs from notifications.  I've been following this set of instructions:
https://companion.home-assistant.io/docs/notifications/notifications-basic?_highlight=clickaction#opening-a-url

It used to work flawlessly but now when clicking in the notification, Android opens a new instance of the Home Assistant app. I have sticky: true in my notification, so I can click on it as many times as I want without the notification disappearing. If I click on it 3 times, I will have 3 HA apps open that can be seen when opening the active apps menu (where you can close them). 

If I take the same URL and I paste it in the browser, it opens as expected. I unchecked "open supported links" in the Android app settings for Home Assistant just in case. 

Running everything up to date, both HA and the Companion app.

Thanks in advance

**Comment by dshokouhi** [comment]
please share the YAML that you used., also there should've been an issue template when you created this issue. Seems it is missing. Please copy the template from a new issue and provide all requested information.

**Comment by HairyHook** [comment]
Thanks for your quick response. I'm using this inside a Blueprint (that I have not modified and used to work fine). The notification portion is the following:

      - service: notify.{{ group_target }}
        data:
          message: A {{ label }} was detected on the {{ camera_name }} camera.
          data:
            tag: '{{ id }}'
            group: frigate-notification-{{ camera }}
            sticky: True
            url: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
            clickAction: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
            image: /api/frigate/notifications/{{id}}/thumbnail.jpg?format=android
            sound: none
            attachment:
              url: /api/frigate/notifications/{{id}}/thumbnail.jpg
            actions:
            - action: URI
              title: View Clip
              uri: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
            - action: URI
              title: View Snapshot
              uri: '{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg'
            - action: silence-{{ camera }}
              title: Silence Notifications
              destructive: true

Let me work on the template, I did not get any prompt.

**Comment by dshokouhi** [comment]
umm a lot of those variables are not supported by android, please provide a basic example to rule out a blueprint issue.

**Comment by HairyHook** [comment]
Okay, let me work on creating something basic to rule out the blueprint and I'll paste the code.

**Comment by HairyHook** [comment]
A really simple notification works as expected. I did not create the blueprint, so let me work on simplifying it and I'll keep testing. Closing the issue for now. Thanks a lot for time.

**Comment by HairyHook** [comment]
Confirmed issue with the blueprint, it is working now as expected. Thanks again.
