### ISSUE TITLE
Realme Quick Actions framed page in Android 12 not working with Home Assistant.

### ISSUE THREAD

**Issue by wrt54g** [home-assistant/android#2487]
**Home Assistant Android version:**
2022.3.0-full
**Android version:**
12
**Phone model:**
realme 8
**Home Assistant version:**
2022.5.0b1
**Last working Home Assistant release (if known):**

**Description of problem:**
The Realme control elements on Android 12 have a quick device preview. This is for fast control without having to open the entire app. It opens the app in a frame with a back and an open in app button. This preview only shows a white page. When I click the Full Screen button, the app loads up correctly. See the screenshot attached below.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_2022-04-27-22-04-22-32_b5a5c5cb02ca09c784c5d88160e2ec24](https://user-images.githubusercontent.com/85389871/165624645-c059a5a5-22e0-427d-a190-a163f1bcaf67.jpg)
![Screenshot_2022-04-27-22-04-34-97_b5a5c5cb02ca09c784c5d88160e2ec24](https://user-images.githubusercontent.com/85389871/165624648-ba4135fa-2619-48f3-af2f-e900732b110f.jpg)

**Additional information:**
It is working when the app is already on foregroud.

**Comment by jpelgrom** [comment]
When you tap on the 'open in app' button, does it still open the dialog with entity info, or does it start the app like when you started the app normally (including splash screen)?

After opening the app using the 'open in app' button, can you check the logs in Configuration > Companion app to see if there are any errors?

**Comment by wrt54g** [comment]
> When you tap on the 'open in app' button, does it still open the dialog with entity info, or does it start the app like when you started the app normally (including splash screen)?
> 
> After opening the app using the 'open in app' button, can you check the logs in Configuration > Companion app to see if there are any errors?
> 
> Edit: I also noticed you're using core 2022.5.0b0. Just to make sure that isn't causing any issues, do you know if it worked before?

The Open In App button shows the entity dialog.

**Comment by wrt54g** [comment]
![Screenshot_2022-04-27-22-46-20-36_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/85389871/165628050-b800332f-dd5b-41c8-ab5d-049204ea897d.jpg)

**Comment by wrt54g** [comment]
It is at least trying to load as I see a part of the Home Assistant logo for less then 1 second when I hold the device control button.

**Comment by dshokouhi** [comment]
Lets look at the logs that @jpelgrom mentioned. I wonder if the app is still loading in the background even though the device shows a blank screen. We can expect to see some log statements that print that would show the app is loading, just hidden. Best to reproduce the issue and then grab the logs shortly thereafter.

**Comment by wrt54g** [comment]
> When you tap on the 'open in app' button, does it still open the dialog with entity info, or does it start the app like when you started the app normally (including splash screen)?
> 
> After opening the app using the 'open in app' button, can you check the logs in Configuration > Companion app to see if there are any errors?
> 
> Edit: I also noticed you're using core 2022.5.0b0. Just to make sure that isn't causing any issues, do you know if it worked before?

I found 1 error in the log:
![Screenshot_2022-04-27-22-53-42-36_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/85389871/165629240-e7898e36-6b8b-492b-bd8f-307abb59133a.jpg)
I don't know if this is related to the blank page issue.

**Comment by dshokouhi** [comment]
Can you please grab the log text? Its incredibly difficult to look at a screenshot of an error :) but please first reproduce the error and then get the full logs. We need to see debug messages as well.

**Comment by wrt54g** [comment]
> Can you please grab the log text? Its incredibly difficult to look at a screenshot of an error :) but please first reproduce the error and then get the full logs. We need to see debug messages as well.

04-27 22:52:50.929 29785 14693 E NetworkSM: Error getting response from external service
04-27 22:52:50.929 29785 14693 E NetworkSM: java.net.SocketTimeoutException: timeout
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:335)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at java.lang.Thread.run(Thread.java:920)
04-27 22:52:50.929 29785 14693 E NetworkSM: Caused by: java.net.SocketException: Socket closed
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at java.net.SocketInputStream.read(SocketInputStream.java:209)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okio.InputStreamSource.read(JvmOkio.kt:90)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
04-27 22:52:50.929 29785 14693 E NetworkSM: 	... 20 more
04-27 22:52:52.739 29785 29785 E mpanion.androi: Invalid ID 0x00000000.

**Comment by wrt54g** [comment]
I just noticed that when the app is on foregroud and the button is held, it just puts the current page in a frame😁

**Comment by jpelgrom** [comment]
> I just noticed that when the app is on foregroud and the button is held, it just puts the current page in a frame😁

Is this after you opened the app using the 'open in app' button? It should show up twice in recent apps then.

To test, can you try removing Home Assistant from your recent apps first, then start it normally, and then long press on a control/button? It now should no longer show the current page.

This sounds like Realme's skin acts as if we've set [FLAG_UPDATE_CURRENT instead of FLAG_CANCEL_CURRENT](https://github.com/home-assistant/android/blob/ec6ae4345c562b877212b2749fe025b306d6b179/app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt#L26), because when using update instead of cancel the app re-uses an activity and the contents instead of properly (re)loading the data. Wouldn't be too bad if we fixed that, than we can close #2251 as well...

**Comment by wrt54g** [comment]
> Can you please grab the log text? Its incredibly difficult to look at a screenshot of an error :) but please first reproduce the error and then get the full logs. We need to see debug messages as well.

1. I hold the button for 5 seconds.
2. The device controls/shutdown panel appears.
3. I hold the device control for 1 second
4. The framed Home Assistant page appears with a blank screen.
5. When the Open In App button is clicked, the Home Assistant app will load up normal with the entity dialog.

**Comment by wrt54g** [comment]
> > I just noticed that when the app is on foregroud and the button is held, it just puts the current page in a frame😁
> 
> Is this after you opened the app using the 'open in app' button? It should show up twice in recent apps then.
> 
> To test, can you try removing Home Assistant from your recent apps first, then start it normally, and then long press on a control/button? It now should no longer show the current page.
> 
> This sounds like Realme's skin acts as if we've set [FLAG_UPDATE_CURRENT instead of FLAG_CANCEL_CURRENT](https://github.com/home-assistant/android/blob/ec6ae4345c562b877212b2749fe025b306d6b179/app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt#L26), because when using update instead of cancel the app re-uses an activity and the contents instead of properly (re)loading the data. Wouldn't be too bad if we fixed that, than we can close #2251 as well...

When I click the Open in app button, it completely reloads the web page in the app.

**Comment by wrt54g** [comment]
And note that this is only in Android 12 which I updated to today. The frame is in the new realme UI 3.0

**Comment by wrt54g** [comment]
I just noticed that the phone UI crashed when I tried to open the framed Home Assistant app. This did not happen a second time.

**Comment by wrt54g** [comment]
> > I just noticed that when the app is on foregroud and the button is held, it just puts the current page in a frame😁
> 
> Is this after you opened the app using the 'open in app' button? It should show up twice in recent apps then.
> 
> To test, can you try removing Home Assistant from your recent apps first, then start it normally, and then long press on a control/button? It now should no longer show the current page.
> 
> This sounds like Realme's skin acts as if we've set [FLAG_UPDATE_CURRENT instead of FLAG_CANCEL_CURRENT](https://github.com/home-assistant/android/blob/ec6ae4345c562b877212b2749fe025b306d6b179/app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt#L26), because when using update instead of cancel the app re-uses an activity and the contents instead of properly (re)loading the data. Wouldn't be too bad if we fixed that, than we can close #2251 as well...

The framed app quits right away when I press the Recent apps button

**Comment by wrt54g** [comment]
I was not able to capture it happening with Screen Recording. The Screen Recording does not show the frame.

**Comment by wrt54g** [comment]
> I just noticed that the phone UI crashed when I tried to open the framed Home Assistant app. This did not happen a second time.

The UI crashes with any device except for the ceiling light (the one that shows the frame)

**Comment by dshokouhi** [comment]
> This sounds like Realme's skin acts as if we've set [FLAG_UPDATE_CURRENT instead of FLAG_CANCEL_CURRENT](https://github.com/home-assistant/android/blob/ec6ae4345c562b877212b2749fe025b306d6b179/app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt#L26), because when using update instead of cancel the app re-uses an activity and the contents instead of properly (re)loading the data. Wouldn't be too bad if we fixed that, than we can close #2251 as well...

The problem that I last faced with that change was the consistency issue, we still have that open bug with Google really hope they can fix that as it was working perfectly before that one security update where it broke :(

**Comment by wrt54g** [comment]
> When you tap on the 'open in app' button, does it still open the dialog with entity info, or does it start the app like when you started the app normally (including splash screen)?
> 
> After opening the app using the 'open in app' button, can you check the logs in Configuration > Companion app to see if there are any errors?
> 
> Edit: I also noticed you're using core 2022.5.0b0. Just to make sure that isn't causing any issues, do you know if it worked before?

@jpelgrom  it never worked before since I updated to Android 12 the day I opened this issue.

**Comment by jpelgrom** [comment]
Is your device on the February 2022 security patch (or newer) by any chance?

If so, could you try a test version of the app from [here](https://github.com/home-assistant/android/actions/runs/2294853655) to see if that solves the issue for you? Download the file `app-full-debug.apk` (you need to be logged in), you can install it alongside the existing app and will need to re-add the controls for the test version of the app.

**Comment by jpelgrom** [comment]
Thanks for the quick response!

You also previously mentioned that "[t]he UI crashes with any device except for the ceiling light", is that also still true while using controls from the test version?

**Comment by dshokouhi** [comment]
I wonder if this is a device specific issue. The logs that were provided earlier only showed a single crash. I am actually interested to see if the webview code is being reached when the blank white window is shown. Can you try these steps to confirm that our code is being reached? Force stop the app. Open the app. Go to Device Controls. Reproduce the issue. Then go back to the app and go to the logs and grab all the logs for us instead of a small section. We need to look at all the logs to look at the everything loading. Feel free to mask any personally identifiable information like GPS data

If we see that our code is being reached then this might be a device specific issue we may not have any control over so lets look at the logs to see what causes the blank white window. As of now I cannot reproduce on my pixel 6 pro.

**Comment by wrt54g** [comment]
> I wonder if this is a device specific issue. The logs that were provided earlier only showed a single crash. I am actually interested to see if the webview code is being reached when the blank white window is shown. Can you try these steps to confirm that our code is being reached? Force stop the app. Open the app. Go to Device Controls. Reproduce the issue. Then go back to the app and go to the logs and grab all the logs for us instead of a small section. We need to look at all the logs to look at the everything loading. Feel free to mask any personally identifiable information like GPS data
> 
> If we see that our code is being reached then this might be a device specific issue we may not have any control over so lets look at the logs to see what causes the blank white window. As of now I cannot reproduce on my pixel 6 pro.

It might be an issue with the realme ui.

**Comment by wrt54g** [comment]
Okay it's fixed
