### ISSUE TITLE
Android App Crashes after few seconds

### ISSUE THREAD

**Issue by saniho** [home-assistant/android#2501]
**Home Assistant Android version:**
beta-2300-f33743dc-full

**Android version:**
Android 6.0.1

**Phone model:**
Galaxy Tab 2 10

**Home Assistant version:**
2022.4.0

**Last working Home Assistant release (if known):**

**Description of problem:**
after few second, and view the HA lovelace, the application closed, and return to android home page.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
no log write
```

```

**Screenshot of problem:**
<no screen shot>

**Additional information:**

**Comment by dshokouhi** [comment]
We definitely need to see the crash log for the cause of the failure here. Can you please use an app like Logcat Reader to get us the crash log? If you decide to use Logcat Reader you will need to follow its instructions to granting the special permissions it requires.

**Comment by saniho** [comment]
Solved with Android 7
