### ISSUE TITLE
Problem with loading of history-graph

### ISSUE THREAD

**Issue by PetrMa** [home-assistant/android#2514]
**Home Assistant Android version:**
2022.3.0-full

**Android version:**
8.0

**Phone model:**
Tablet Huawei Mediapad T5 10,1

**Home Assistant version:**
Home Assistant Core 2022.5.3
Home Assistant Supervisor 2022.05.0

**Last working Home Assistant release (if known):**

**Description of problem:**
Hello,
today I installed Home Assistant to the new Android tablet device.
The configuration of environment is:
- HA is accessed through the external address via Nabu Casa
- the user logged in the tablet is without admin rights and set as Login allowed only from internal network
- All version are up-to-date, HA, Android app etc.

The problem is that in this configuration the user is not able to show history-graph on any Lovelace. Every time I lick on any Lovelace which includes history-graph I´ve got an error message Login Failed .....
I have got some investigation and found the issue with the user settings "Login allowed only from internal network". If I uncheck this settings, everything works fine and history-graph is loaded successfully. With this settings I´ve got the Login failed error every time.
But I want to ensure that the user which is logged on the tablet can access HA only from internal network.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
I'm not sure using the Nabu Casa URL will qualify as "local", does this work correctly when you open the Nabu Casa URL in Chrome and try to sign in with the same user? If it also doesn't work there, this would be an issue for the frontend or core.

**Comment by PetrMa** [comment]
Hi @jpelgrom
I can confirm that in Android application with this setup work everything except the history-graph.

I also tried connect to the nabu casa URL in web browser with the same account on the tablet and also everything works fine when local login is allowed.

So after these tests my opinion is that this is Android app specific issue.

**Comment by jpelgrom** [comment]
I've been testing this with a local only admin user connecting directly to the instance and cannot get any errors with the history-graph card in the app, using a simple configuration:
```
type: history-graph
entities:
  - entity: sensor.motion_sensor_temperature
hours_to_show: 12
```

Could you try connecting directly to your instance locally using the IP or hostname (for example, `192.168.1.x` or `homeassistant.local`), to make sure the Nabu Casa remote UI isn't causing any problems?

Are there any relevant errors in the app's logs? Could you share a screenshot of the error message you get?

**Comment by dshokouhi** [comment]
Closing due to lack of response
