### ISSUE TITLE
Widget Manager does not show more than 24 items 

### ISSUE THREAD

**Issue by martusi61** [home-assistant/android#2521]
The problem
In my Android 10 tablet Teclast M40 Widget Manager does not show more than 24 items. I created 46 widgets, but from companion app settings ver.2022.3.0 full, I only see 24.

What version of Home Assistant Core has the issue?
2022.5.3

What was the last working version of Home Assistant Core?
No response

What type of installation are you running?
Home Assistant in Docker container

Integration causing the issue
Mobile App ver.2022.3.0 full

Link to integration documentation on our website
No response

Diagnostics information
No response

Example YAML snippet
No response

Anything in the logs that might be useful for us?
No response

Additional information
No response

**Comment by dshokouhi** [comment]
This issue is missing the issue template that gets presented when a new issue is created. Please copy it from a new issue and fill it out completely so we can look into this issue. Please make sure to supply screenshots of the issue as well. We may also need to see the logs too.

**Comment by martusi61** [comment]
> This issue is missing the issue template that gets presented when a new issue is created. Please copy it from a new issue and fill it out completely so we can look into this issue. Please make sure to supply screenshots of the issue as well. We may also need to see the logs too.

Done, it's allright?

**Comment by jpelgrom** [comment]
Could you also provide a screenshot, and get the logs by opening the widget settings first and then selecting 'Show and Share Logs' from the app settings?

Are all widgets functional? If a widget doesn't show up in the app's settings it probably also won't work.

I just tested creating ~35 template widgets and they did all work and show up, but I found another issue where scrolling only works on the part of the screen where there are buttons. So if your widgets have short names, make sure to scroll on the side of the screen where there are buttons and not in the blank space.

**Comment by martusi61** [comment]
> 

Excuse me, I checked better and I realized that the scrolling works, you had to do it on the left side where there are the widgets and not on the empty part on the right. On small smartphone screens this is less noticeable, but on a tablet it is more pronounced. Thanks for your assistance and sorry again.

**Comment by jpelgrom** [comment]
No need to apologize and thanks for reporting, otherwise the scrolling issue probably wouldn't have been found! 

(It has been fixed in the latest beta so you should be able to scroll anywhere on the screen soon)

**Comment by martusi61** [comment]
:+1:
