### ISSUE TITLE
Speakerphone showing on even speakerphone is not enabled and not even in call

### ISSUE THREAD

**Issue by ashoktvm** [home-assistant/android#2522]
Speakerphone is showing as on even if it not on while there is no call is going on
In the picture below u can see the phone is idle, but the speakerphone still says its on, even though its not. I am using Oneplus 8T by the way

![image](https://user-images.githubusercontent.com/45116583/168218850-5874d246-c076-4419-b04b-8f6dc6ff9b6d.png)

**Comment by dshokouhi** [comment]
This issue is missing the issue the template that gets presented when a new issue is created. Please copy the template from a new issue and fill it out completely including the logs when you turn the speakerphone on and off on the device.

**Comment by dshokouhi** [comment]
Closing due to lack of response
