### ISSUE TITLE
Missing Energy dashboard in Android app 

### ISSUE THREAD

**Issue by marekbrezina** [home-assistant/android#2523]
**Home Assistant Android version:**
2022.3.0-full
**Android version:**
8.0.0
**Phone model:**
Galaxy A5 (2017) model SM-A520F

**Home Assistant version:**
Home Assistant Core 2022.5.4
Home Assistant Supervisor 2022.05.1 

**Last working Home Assistant release (if known):**

**Description of problem:**
The Energy dashboard is not visible in the left menu. I can use it from the web broswer, but the app does not have the Energy dashboard.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**
I have checked my config and there is a line with default_config: available as noted here https://www.home-assistant.io/docs/energy/faq/

**Comment by dshokouhi** [comment]
Did you by chance remove the energy dashboard from the side menu on that device? You may need to try and rearrange the items to see if that happened by accident.

https://www.home-assistant.io/dashboards/sidebar/

**Comment by marekbrezina** [comment]
Ooops, you are right- The menu was hidden and changing the configuration worked so the dashboard is now available. 
Many thanks and sorry for a false bug report. We can close the ticket now.
