### ISSUE TITLE
Sensor for current time zone reports wrong timezone

### ISSUE THREAD

**Issue by FrankLandrock** [home-assistant/android#2530]
Samsung A71 with Homeassistant companion 2022.3.0-full

It is May 2022, my Phone is located in Central Europe.

The current time zone sensor delivers this (taken from Developer-Tools/States): 

Sensor:                                                 
sensor.sm_a715f_current_time_zone

State:                                              
Central European Standard Time   

Attributes:
in_daylight_time: true	
time_zone_id: Europe/Berlin
time_zone_short: GMT+02:00
uses_daylight_time: true
utc_offset: 7200000
icon: mdi:map-clock
friendly_name: SM-A715F Current Time Zone

I am happy with the attributes, but the state is just wrong, it has to be "Central European Summer Time" (NOT "Standard"!). 
There is no such thing as "Central European Standard Time", it is either "Central European Time" (when daylightsaving=false) or "Central European Summer Time" (when daylightsaving=true).

**Comment by dshokouhi** [comment]
The app in this case simply returns the API data from the TimeZone display name using the english locale. I do not think we can correct this as we simply return the data from the API.

https://developer.android.com/reference/java/util/TimeZone#getDisplayName(boolean,%20int,%20java.util.Locale)

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/TimeZoneManager.kt#L52

**Comment by FrankLandrock** [comment]
@dshokouhi Thanks for looking into that....

So, it looks like I have to report this issue on some other bug tracker, right? As it seems to be a general Android issue, rather than a HA-compnaion issue? Can you give me a hint on where to do that? 

P.S.: I am new to the show...

**Comment by jpelgrom** [comment]
Time zone data is provided and updated by your device manufacturer. I'm also seeing these time zones names in an emulator so it's probably an error somewhere in a common data source (but I don't know which).

FYI, I'm submitting a fix to change the time zone name to a different value if the device is currently in summer/daylight savings time.

**Comment by dshokouhi** [comment]
Are we good to close this now? I think the original issue is now solved in the latest beta.
