### ISSUE TITLE
only display the dashboard on the screen

### ISSUE THREAD

**Issue by pbanj** [home-assistant/android#2531]
**Is your feature request related to a problem? Please describe.**
we have a dedicated phone for the app as we have an autistic child so we had to remove the actual switches from the walls. we have a problem with the app and im not sure if a fix could be done/added . the issue is we cant hide the top bar, the one with the hamburger menu, dashboard title, and search. so hes constantly clicking around in the app messing with the settings

**Describe the solution you'd like**
if possible could you add a way to hide that from the ui and only show the chosen/allowed dashboard

**Describe alternatives you've considered, if any**
ive tried multiple ways of blocking that area but none of them seem to work on android 11. would really like to not have to buy 
an ios device to do it.
**Additional context**

thaks for taking the time to read this even if it doesnt/cant get added.

**Comment by RoboMagus** [comment]
Hi @pbanj,

Have you installed HACS in your home assistant instance?
If so, the following Frontend plugin would be perfect for your use case: [kiosk-mode](https://github.com/maykar/kiosk-mode).

Otherwise you could also add a (fingerprint) lock when opening the app. This can be found under the security section of the companion app settings. Not quite what you asked for, but given your situation it could help ;)

**Comment by jpelgrom** [comment]
The app doesn't control the top app bar on dashboards, the easiest way to solve this would probably be a custom module/plugin like suggested above (also without HACS!).

**Comment by pbanj** [comment]
> Hi @pbanj,
> 
> Have you installed HACS in your home assistant instance? If so, the following Frontend plugin would be perfect for your use case: [kiosk-mode](https://github.com/maykar/kiosk-mode).
> 
> Otherwise you could also add a (fingerprint) lock when opening the app. This can be found under the security section of the companion app settings. Not quite what you asked for, but given your situation it could help ;)

Oh that's perfect

**Comment by pbanj** [comment]
@RoboMagus just wanted to say thanks. i finally had time to mess with it. i ended up going with https://github.com/Shreyas-R/lovelace-wallpanel-screensaver instead. so i was able to get rid of an app i had to dim the screen but not lock it and have it just shows the switches.
