### ISSUE TITLE
Easy onboarding of ESPhome and Tasmotta devices.

### ISSUE THREAD

**Issue by NF8C** [home-assistant/android#2538]
**Is your feature request related to a problem? Please describe.**
Easy ESPhome onboarding.

**Describe the solution you'd like**
Under app setting I would place a button to pair ESPhome devices. Most ESP home and Tasmotta devices create a wireless access point so they can be added to local WiFi.  Once the pairing button was pressed the app would scan for WiFi access points.  The user would be presented with a list of access points.  From that they would choose the access point of the device to be added.  A good example is the Kauff bulbs pre-flased with ESPhome.  They create an access point that looks something like kaufxxxxxxx.  Similarly there are devices sold by a retailer called cloudfree.  Those use Tasmotta but onboard is the same.

Later more complex variations could also help enter important details like MQTT credential for devices running Tasmotta but in short term the app could simply find the network ip address of the new device after connecting it to the main network and open it for the user. 

**Describe alternatives you've considered, if any**
Alternately this same process could be done through the device running HomeAssistant but it seems a better place in the app to me because we don't know if the device running HomeAssistant even has WiFi to start the process.

Here are a couple places for smart devices flashed with ESPhom and Tasmotta.  I think this would open up thing a little for those that don't want to flash their own devices if pairing was simple.
https://cloudfree.shop/ 
https://kaufha.com/products/

**Comment by dshokouhi** [comment]
As Tasmota and ESPHome can be used independently from Home Assistant I think this request would be better fit in the respective repositories instead of with the official HA app.

**Comment by NF8C** [comment]
I agree with you those developers should be involved however no device can onboard itself.

They require that to be done from a laptop, computer, tablet, or phone.  For example the Alexa app helps onboard Amazon devices.  The Google Home app helps onboard Google devices. I could onboard my Chromecast using a browser sure but that's not easy for the user.

Since ESPhome was acquired by Nabu Casa it makes sense their official app would support onboarding at least for ESPhome.

**Comment by dshokouhi** [comment]
I didn't mean the device to onboard itself. I meant a separate app unrelated to HA so any user of ESPHome can use it. You don't need Home Assistant to use ESPHome.

**Comment by dshokouhi** [comment]
Lets close this request for now and have the author create requests at the individual repositories as this is best to be handled separate from HA. I do agree it would be nice to have as its own thing but not part of the HA app as HA is not a requirement to use either product.
