### ISSUE TITLE
Home Assistant app on Fire HD 10 tablet is dimmed after few minutes (almost unusable as dashboard)

### ISSUE THREAD

**Issue by foosmate** [home-assistant/android#2539]
**Home Assistant Android version:** 2022.2.0-minimal

**Tablet model:** Amazon Fire HD 10 (11th Gen)

**Description of problem:**

When I saw that the Home Assistant app was officially released in the Amazon appstore, I ordered 4x Amazon Fire HD 10 tablets. I expected this solution to give me a great dashboard on the wall with little effort and without having to root or otherwise tinker with the device.

A first test has now shown that even in always-on mode (easy to activate via the developer options), the display stays on forever but dims so much (after a few minutes) that you can barely see anything in daylight. You have to tap the display with your finger so that the set brightness (100% w/o auto-dim in my case) is activated again for a few minutes.

This behavior can apparently be controlled by the app, e.g. in the Kindle app the display is not dimmed at all (even if you configure the timer in the system settings to 30s).

For this reason, I would like to suggest adding a configurable always-on option in the Home Assistant app. Otherwise, unfortunately, you can't use this great app on an Amazon Fire HD as wall display without rooting the device.

**Screenshot of problem:**

![Walldisplay-Dimmed-Resized](https://user-images.githubusercontent.com/81085491/169695404-43392b6e-91cc-44b8-a6b9-0b506dbce03e.jpg)

**Comment by dshokouhi** [comment]
Have you considered enabling the keep screen on option under companion app settings?

**Comment by foosmate** [comment]
I thought I had checked all the settings and didn't see the option. It works right if you do it right. Thanks for the quick reaction. 👍 

To at least contribute something useful, it would be interesting to allow configuring a timeframe (like a night mode). If you configure Always-On in the system settings, the display would dim at night (see photos) and shine with full power during the day. The advantage would be 1 instead of 4 watts of power consumption and less stress to the device.

**Comment by dshokouhi** [comment]
Changing screen brightness requires special permission to write to settings which I don't think we will be doing. Something like this is more of a job for tasker or fully kiosk.

**Comment by foosmate** [comment]
For the Amazon devices you don't need to change the brightness, since this is done automatically if always-on is configured on device level (system settings).

In other words, assuming that the Companion app has a timeframe excluding the night **and** keep-awake is configured in the system settings, the screen will be dimmed in the night automatically (for the timeframe that is excluded in the Companion app).

**Comment by dshokouhi** [comment]
> For the Amazon devices you don't need to change the brightness, since this is done automatically if always-on is configured on device level (system settings).

you are referring to a developer option, which is intended for testing purposes only and not an actual feature to depend on. The app makes use of the actual system feature to keep the screen on while the app is open. The developer option is to keep the device awake while it is plugged in.

I don't think this is a feature request we will be fulfilling, this sounds more like a job for fully kiosk then the companion app.  The companion apps primary focus is for the mobile devices that follow you instead of wall mounted tablets.

**Comment by foosmate** [comment]
Ah ok good point, thanks for the detailled feedback. 👍 

Just another thought: Even on a regular tablet, it may be helpful to have the device on all day and off all night and tap the screen once in the morning to have it back on all day. Many people pay attention to power consumption and this tap-once-in-the-morning idea sounds not too bad for me (especially since the Companion app pops up in the Amazon store).

**Comment by dshokouhi** [comment]
you can control the keep screen on option to achieve a similar effect

https://companion.home-assistant.io/docs/notifications/notification-commands#screen-on

**Comment by foosmate** [comment]
That's fantastic! 

Thank you so much and have a nice evening.
