### ISSUE TITLE
Quest 2 sensors not reflecting when device is off

### ISSUE THREAD

**Issue by Sian-Lee-SA** [home-assistant/android#2545]
**Is your feature request related to a problem? Please describe.**

The app should be detecting whether the device is shutting down via flat battery or manual turning off and change sensors to reflect this state (especially in_use sensor)

**Describe the solution you'd like**

**Describe alternatives you've considered, if any**

Can do this with Tasker and webhook but seems like an unnecessary step

**Additional context**

**Comment by dshokouhi** [comment]
If the headset is still being worn when it shut down then the intent that the app receives will never be so we cannot update the state there. Also the android shutdown event does not always give applications enough time to fire an event so this request may not be possible. Even the android app on the phone suffers from this as well. Luckily battery level is an easy to discern this.  If you take the headset off and then shut down manually that will report the correct state. This sensor relies on the Quest hardware to communicate when the headset is on or off so we should stick to that logic.

**Comment by dshokouhi** [comment]
We could try to register for the shutdown event so users can see when that happens but android does not offer any guarantees for data to be sent or for apps to even be active so it may not be viable.

https://developer.android.com/reference/android/content/Intent#ACTION_SHUTDOWN

**Comment by Sian-Lee-SA** [comment]
I felt that could be the case but with tasker seeming to do this very consistently then I assume the shutdown event that android would send should suffice. But my basis is that Tasker possibilities should be the same for any other app as it has no special privilege's.

**Comment by dshokouhi** [comment]
So Tasker will be sending 1 command at that point....the app itself will get triggered to send an update for every enabled sensor so the likelihood of the app relaying that may not happen. We can add the intent to get notified when the shutdown occurs but as you have seen with Android documentation there is no guarantee that data will be allowed to be sent.

**Comment by Sian-Lee-SA** [comment]
That's all understandable

**Comment by dshokouhi** [comment]
For the time being go ahead and enable the Last Update sensor. Then on that same page add an intent under the settings and add the below text as the intent. Once you saved it close and open the app again. That is the sensor you will need to use to see if the shutdown is detected and this "workaround" is actually what the fix will become for most part :)

```
android.intent.action.ACTION_SHUTDOWN
```

This will also become the state to detect when a shutdown has an occurred. You will be able to see how reliable the fix will be while a PR gets ready.

**Comment by Sian-Lee-SA** [comment]
I get the intent passed as android.intent.action.ACTION_SHUTDOWN when this has shudown but the in_use is still stuck on "on" and this would also be because the device is still technically being in use during a shutdown. It seems either the App or more preferable the component on HA should probably internally toggle the in_use to false if the shutdown intent was detected?

For now I'm still trying to find the best way to handle the shutdown action as the in_use sensor is used for my conditions both in front end and automations. Is there a way I can force in_use to false if the last_update_sensor was android.intent.action.ACTION_SHUTDOWN?

Alternatively I could create a boolean help then change that value on shutdown then group the in_use sensor but feels very cumbersome.

**Comment by Sian-Lee-SA** [comment]
I think I over thought my previous problem but in short, I solved the current issue with a binary_sensor template:

```yaml
template:

  binary_sensor:
    - name: "Quest 2 In Use"
      state: >
        {% if is_state('binary_sensor.quest_2_in_use_ref', 'on') and not is_state('sensor.quest_2_last_update_trigger', 'android.intent.action.ACTION_SHUTDOWN') %}
          True
        {% else %}
          False
        {% endif %}
```

But if it so happens to be internally integrated where the toggle for in_use will change based on the shutdown event then I'll be happy to resort to that instead.

**Comment by jpelgrom** [comment]
The in_use sensor intentionally doesn't change because it cannot be guaranteed that the app will receive the shutdown intent and is able to update the sensor. The sensor will always display the value provided by Android, if you want to transform it to also use other information a template sensor like you posted is probably the way to go 👍

(See the linked PR above your comments for a short discussion on this)
