### ISSUE TITLE
Cannot add new Intent to Last Update Trigger sensor

### ISSUE THREAD

**Issue by marazmarci** [home-assistant/android#2550]
**Home Assistant Android version:** beta-2300-f33743dc-full

**Android version:** 11

**Phone model:** Poco X3

**Home Assistant version:** 2022.5.5

**Last working Home Assistant release (if known):** 2022.5.5

**Description of problem:**
Currently, I have 15 Intents registered in the Last Update Trigger sensor. When I turn on the Add New Intent toggle, it stays turned on indefinitely and won't allow me to add a new Intent. Previously, a new entry was added immediately whenever I tapped on the Add New Intent toggle. Before it stopped working, I was adding 2 or 3 more Intents, but then I removed them, and probably this is why it stopped working. Swipe-closing or force-stopping the app doesn't help.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
I checked the in-app logs and logcat via ADB, but there was nothing interesting.

**Additional information:**
Aside from the bug, this Add New Intent functionality is far from optimal from a UX perspective IMHO. Can't it be implemented differently? Or is there some sort of a technical limitation?

**Screen recording of the problem:**
https://user-images.githubusercontent.com/1349654/171994081-0fede94b-c223-46db-93b6-f2c23244b48a.mp4

**Comment by dshokouhi** [comment]
are all of the intents supplied? did any numbers skip?

**Comment by marazmarci** [comment]
Yes, all Intent entries are non-empty.
I can see a problem with the numbering: `Intent 2` is missing, but `Intent 1` and `Intent 3` are present.

**Comment by dshokouhi** [comment]
ah yea the only workaround for now would be to start fresh with the app, intents are currently added sequentially but there seems to be an issue when one is being removed and then added back. You can also try removing a few of the last ones but not sure that will work.

**Comment by marazmarci** [comment]
I looked up the relevant parts of the code. I think [this](https://github.com/home-assistant/android/blob/2384f0f84db16e5dc03fdaf154ca945efaa8b3fd/common/src/main/java/io/homeassistant/companion/android/common/sensors/LastUpdateManager.kt#L79-L82) can be extended to keep the continuity of the sequence by renumbering them. Or something similar, it's just my first idea.

I think I can fix it, I'll open a PR when it's done 🙂

**Comment by marazmarci** [comment]
If we have a list of [Intent 1, Intent 3, Intent 4], when adding a new Intent, the new list should be ...
a. [Intent 1, **_Intent 2_**, Intent 3, Intent 4]
b. [Intent 1, Intent 3, Intent 4, **_Intent 5_**]

Which approach do you prefer?

**Comment by dshokouhi** [comment]
I think that option c would make the most sense to an end user and I also agree it should be updated immediately :) Thank you for offering to take this on!

Regarding:



> Aside from the bug, this Add New Intent functionality is far from optimal from a UX perspective IMHO. Can't it be implemented differently? Or is there some sort of a technical limitation?

I do agree the UX is not the best, previously this was a preference screen so we didn't have much options in terms of design but now that we are using Compose we can probably make it function more like a button.  This would impact a few sensors that make use of the `toggle` setting, the WiFi BSSID sensor also uses the toggle in a similar fashion.

**Comment by marazmarci** [comment]
Haha, I had an almost finished comment that I just wanted to send 😄
It would have been this:
I'd prefer to go with the **b.** approach because it's the most straightforward to implement, and the existing entries in the DB don't need to be modified.

This would have been the lazy solution for sure 😄

But now, as I'm thinking a bit more about it, my idea is to do **b.** under the hood, for the DB IDs, and have a continuous numbering implemented on the UI layer, with keeping the order of the DB entries, so from the visual perspective, it would be **c.**.

For the under-the-hood part, I already have a working implementation, but the UI numbering part may be non-trivial because I don't know the codebase very much. Let me find it out. Or please stop me if you're sure in advance that it will be a dead-end.

**Comment by marazmarci** [comment]
> I do agree the UX is not the best, previously this was a preference screen so we didn't have much options in terms of design but now that we are using Compose we can probably make it function more like a button. This would impact a few sensors that make use of the `toggle` setting, the WiFi BSSID sensor also uses the toggle in a similar fashion.

OK, I see. I have an idea: I think we could move away from the current approach that - as you mentioned - is heavily inspired by the limitations of a Preference screen. The sensor settings list view shows items that have a state stored in the DB, but a button doesn't have a state that needs to be stored in a DB, so I suggest moving the button out from the list, probably above the list. And we have the `BasicSensor` class, and at first glance, it seems like an appropriate place to store the fact if a sensor has an action, that would be displayed as a button by the UI.
(And a side note: this could be another PR, but not necessarily.)
WDYT?

**Comment by dshokouhi** [comment]
> I'd prefer to go with the **b.** approach because it's the most straightforward to implement, and the existing entries in the DB don't need to be modified.

this would fix the current bug and keep the logic the same as it is now :) up to you if you want to do that here



> The sensor settings list view shows items that have a state stored in the DB, but a button doesn't have a state that needs to be stored in a DB, so I suggest moving the button out from the list, probably above the list.

yea I think a new setting type for ` button` would be doable here to get rid of the toggle and make it more like a form



> And we have the `BasicSensor` class, and at first glance, it seems like an appropriate place to store the fact if a sensor has an action, that would be displayed as a button on the UI.

not sure how that would work if a sensor ends up needing multiple actions?



> (And a side note: this could be another PR, but not necessarily.)

the smaller the PR the easier it is to review, bug fix PR's generally get merged faster than feature adding ones :)

**Comment by marazmarci** [comment]
I investigated the code a bit, and it's clear now that my idea of doing the sequential numbering in the UI logic is not feasible, because of the very generalized logic present in `SensorDetailViewModel.getCleanedKey(String)` that assembles the `"Intent $n"` strings displayed in the list. So my implementation needs to update the underlying DB because the UI is tightly coupled to the sequence numbers found in the DB. I need some time to come up with a good enough implementation.

**Comment by marazmarci** [comment]
> not sure how that would work if a sensor ends up needing multiple actions?

We could have a list of `Button`s.

> yea I think a new setting type for button would be doable here to get rid of the toggle and make it more like a form

IMHO the optimal solution would be to separate the sensor settings from the sensor attributes. Sensors could have their own UI (optionally of course, because not every sensor needs custom settings). Do you know of any other sensor that could benefit from a sensor-specific custom settings UI? (Maybe a sensor planned in the future?) You mentioned `WiFi BSSID`, which would be definitely a good candidate for a `Button`. If a `Button` is all we would ever need for all other sensors, keeping YAGNI in mind,  I can think of adding something like a `List<SensorSettingButton>` to `BasicSensor`, and let the appropriate `<sensor name>Manager` class handle the button click.

> the smaller the PR the easier it is to review, bug fix PR's generally get merged faster than feature adding ones :)

I'm leaning towards keeping this PR only a bug fix PR 🙂

**Comment by dshokouhi** [comment]
> IMHO the optimal solution would be to separate the sensor settings from the sensor attributes.

They are separated from attributes, they are just attached to the sensor ID in the database so its easy to retrieve all sensor specific data.


> Sensors could have their own UI (optionally of course, because not every sensor needs custom settings). Do you know of any other sensor that could benefit from a sensor-specific custom settings UI? (Maybe a sensor planned in the future?)

Not sure I follow, they already have their own UI and it doesn't make sense to move settings anywhere else in the UI. You have to enable a sensor from the details page so thats the logical place to put the settings for a sensor. Several sensors have settings like Next Alarm, Location, WiFi, Notification, Bluetooth etc... You should probably spend a few moments checking out each sensor to see what it has to offer in terms of settings. 



> If a `Button` is all we would ever need for all other sensors

Definitely not the case now :) and settings will probably only become more complex as time goes on. The most complex set of settings now is related to High Accuracy Mode which is part of Background Location sensor.



> I'm leaning towards keeping this PR only a bug fix PR 🙂

Personally I always try to separate bug fixes from enhancements unless the fix must be an enhancement lol.
