### ISSUE TITLE
WearOS template tile html tags

### ISSUE THREAD

**Issue by chertvl** [home-assistant/android#2551]
Is it possible to add HTML Tags feature to template tile for WearOS app? It would be great to stylize my favorite feature a little bit (font color, bold/italic, etc, like it realized in Template widget for Android).

Thanks!
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by jpelgrom** [comment]
Based on a quick search and some experimentation, I don't think this is feasible.

The function used right now for text [only accepts a plain String and settings for style (no mixed styling)](https://developer.android.com/reference/kotlin/androidx/wear/tiles/LayoutElementBuilders.Text.Builder?hl=en), and there isn't really a good way to convert HTML to [the required format that accepts multiple 'text parts with styling'](https://developer.android.com/reference/kotlin/androidx/wear/tiles/LayoutElementBuilders.Spannable.Builder?hl=en).
