### ISSUE TITLE
Prioritize Internal URL Does Not Fall Back Gracefully

### ISSUE THREAD

**Issue by mstarks01** [home-assistant/android#2564]
**Home Assistant Android version:**
2022.3.0-full

**Android version:**
12

**Phone model:**
Google Pixel 6

**Home Assistant version:**
Home Assistant Core 2022.5.5

**Last working Home Assistant release (if known):**

**Description of problem:**
Under "Prioritize Internal URL" the text states that it will try the internal URL first. The problem is that it just errors out when off the home network instead of trying the internal URL, then refreshing with the external URL after a short timeout. It simply displays, "Unable to connect to Home Assistant." Tapping "REFRESH EXTERNAL URL" doesn't help.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
You will need to hit the refresh button a few times if you are using this feature, that is intended here.  Can you try to hit the refresh once to twice more?

**Comment by dshokouhi** [comment]
This feature is intended for those that typically leave location off and are ok with hitting the refresh button a few times

**Comment by mstarks01** [comment]
Hitting refresh does work, thank you. Perhaps this can be handled more gracefully in the background?

**Comment by dshokouhi** [comment]
> Hitting refresh does work, thank you. Perhaps this can be handled more gracefully in the background?

theres no way to reliably tell when it fails like that which is exactly the reason for having the refresh button there and having it change between URL's so we can cycle through.
