### ISSUE TITLE
Fitbit spams HA sensor notifications

### ISSUE THREAD

**Issue by darylvL** [home-assistant/android#2571]
**Home Assistant Android version:**
20220504.1

**Android version:**
9

**Phone model:**
Motorola Moto G6 Plus

**Home Assistant version:**
2022.5.5

**Last working Home Assistant release (if known):**
2022.4.?

**Description of problem:**
My Fitbit is configured to show me my Home Assistant notifications that are sent to my phone. This has been working flawlessly for over a year, but since about a month or so my Fitbit started spamming me with Home Assistant notifications that I'm not meant to see. More specifically I'm seeing notifications that the companion app uses for updating the sensor values. This is very annoying because sometimes there are a lot of notifications. Note that I only get these notifications on my Fitbit but not on my phone (at least not noticeable).

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**
These are some of the notifications I'm receiving on my Fitbit:

Title:
Updating sensors
Content:
ifications.view

Title:
Updating sensors
Content:
3

Title:
Updating sensors
Content:
ion_popup.view

**Comment by dshokouhi** [comment]
Try to turn off the notification channel for the sensor worker, otherwise you'll need to use Fitbit app to block those notifications. This is all you can really do. The app will not be removing the update notification as its required to keep the app running.

**Comment by darylvL** [comment]
The thing is: I only started receiving these notifications a few weeks ago, I used to only get the HA notifications that I configured in my automations. So I assume something must have changed in how these sensor notifications are sent/handled.
Blocking the notifications on the fitbit app would mean blocking all Home Assistant notifications so that's not really a solution.
Wouldn't turning the sensor worker notification channel off cause my phone sensors to stop working?

**Comment by dshokouhi** [comment]
> The thing is: I only started receiving these notifications a few weeks ago, I used to only get the HA notifications that I configured in my automations.  So I assume something must have changed in how these sensor notifications are sent/handled.

The "Updating Sensors" notification has been there for years, it doesn't just start showing up unless you had all sensors disabled and started to enable sensors.



> Wouldn't turning the sensor worker notification channel off cause my phone sensors to stop working?

No sensor updates will still occur it will just be harder to troubleshoot if updates are still being sent.

Its quite possible that fitbit was ignoring foreground service notifications and some update to their app caused that to stop but the notification itself has not changed in some time.
