### ISSUE TITLE
Build project

### ISSUE THREAD

**Issue by nisbi** [home-assistant/android#2578]
Hi
when i want to build a project it gives me this error
Cannot convert relative path io.homeassistant.companion.android\daemon\7.3.3 to an absolute file.
please how i can resolve this issue ,thanks

**Comment by dshokouhi** [comment]
did you make sure to follow all of the steps outlined here: https://github.com/home-assistant/android#setup-app-development-environment

**Comment by nisbi** [comment]
Yes, 
I solved the problem by following these steps:
I go to File ⇒ Settings ⇒ Build, Execution, Deployment ⇒ Build Tools ⇒ Gradle, and  i change gradle user home to C:/Program Files/Android/Android Studio/jre/bin/io.homeassistant.companion.android instead of ~/.gradle.

To spread the benfit

Thanks

**Comment by nisbi** [comment]
you can mention as remark at the end of step 7

**Comment by jpelgrom** [comment]
Moving the Gradle _user home_ to a random app-specific folder in the Program Files folder doesn't make much sense to me as a recommendation though? The project follows the default settings provided by Gradle (not hardcoded in the project to a specific directory), if it doesn't work it is more likely something related to the folder you're trying to access / IDE / operating system / ...
