### ISSUE TITLE
FR: sensor reporting "metered_connection" or "unmetered_connection"

### ISSUE THREAD

**Issue by FrankLandrock** [home-assistant/android#2586]
**Is your feature request related to a problem? Please describe.**
Currently, I operate HA companion differently, when I am on mobile data or on WiFi. I do not want to waste too much data when I am on mobile data. I query "sensor.mymobilephone_wifi_connection" and operate differntly when it is set. However, there is a little snag here: when I use tethering to my work phone, my HA companion phone believes to be on Wifi and thus uses too much data. 

**Describe the solution you'd like**
Android phones (and, afaik, iPhones too) sense if you are on a metered connection or not. And there is an API to query that state. I'd love to have a sensor for that in HA companion, with the states "metered_connection" and "unmetered_connection".

**Describe alternatives you've considered, if any**
As described abobe querying the state of the wifi_connection kind of works but fails short if that is a wifi via tethering to another phone (on a mobile data plan). 

**Additional context**

**Comment by dshokouhi** [comment]
I wonder if the metered connection would be better fit as an attribute for something like the transport sensor maybe? I suppose we could make a whole new sensor too but it feels like it describes the current connected network.

**Comment by FrankLandrock** [comment]
What about adding an Attribute to  "sensor.mymobilephone_wifi_connection" named "metered_connection" that can either be true or falls?

**Comment by jpelgrom** [comment]
Connections other than WiFi can also be metered, so the Network Type sensor would probably be the better option.
