### ISSUE TITLE
Force stopping does not work

### ISSUE THREAD

**Issue by jalbstmeijer** [home-assistant/android#2588]
**Home Assistant Android version:** 2022.3.0-full

**Android version:**  12

**Phone model:** OnePlus 8

**Home Assistant version:** Home Assistant Core 2022.5.5

**Description of problem:** Sometimes the app becomes unresponsive or lags heavily while scrolling. When trying to force stop the app, the app just won't stop. Only way to fix it is to reboot my phone.

**Comment by dshokouhi** [comment]
This doesn't sound like a bug with the app, more like some oddity with the device. Try starting fresh

https://companion.home-assistant.io/docs/troubleshooting/faqs#starting-fresh-with-the-android-app

**Comment by dshokouhi** [comment]
Closing due to lack of response from author.
