### ISSUE TITLE
Notification styling does not seem to work

### ISSUE THREAD

**Issue by RoboMagus** [home-assistant/android#2590]
**Home Assistant Android version:**
2022.3.0-full

**Android version:**
Android 12 (One UI 4.1)

**Phone model:**
Galaxy S10

**Home Assistant version:**
2022.6.2

**Last working Home Assistant release (if known):**
?

**Description of problem:**
HTML styling of notifications does not seem to work. See screenshot below.

However when looking at this notification in the notification history, styling is present in the data as well as being correctly applied to the notification.

**Screenshot of problem:**
![Screenshot_20220606-133711_Home Assistant](https://user-images.githubusercontent.com/68224306/172153773-ad2f572b-129a-4849-99b5-a17b12944f6c.jpg)
![Screenshot_20220606-133647_Home Assistant](https://user-images.githubusercontent.com/68224306/172153784-91fc66ff-66e5-4841-aa3c-09972ed03aa1.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
Works for me ![Screenshot_20220606-075644.png](https://user-images.githubusercontent.com/1634145/172186854-f0dc851a-19b7-45e2-8459-e67e7e264564.png)

**Comment by jpelgrom** [comment]
This might be a limitation imposed by Samsung. Using the [sample notification with HTML formatting from the documentation](https://companion.home-assistant.io/docs/notifications/notifications-basic/#notification-message-html-formatting), I can see markup on my device (a Google Pixel 4a, also on Android 12):
![image](https://user-images.githubusercontent.com/8148535/172186483-677c7fbe-0921-4d74-9cdc-63df3778012e.png)

Do you happen to have any other devices you could use to test and/or know of another app where this does work?

([Seeing a similar report on Samsung's developer forum, but unfortunately no responses](https://forum.developer.samsung.com/t/not-working-html-notification-on-galaxy-s10/12939))

**Comment by RoboMagus** [comment]
Thanks for that info. I only have Samsung phones and tablets to my disposal that I could test on, so if Samsung is the one breaking things here I won't be able to compare it.

I'll keep a look out for how other apps style their notifications, sadly not something that can be done on demand.

**Comment by dshokouhi** [comment]
It looks like Samsung is not processing all of the tags upon closer look at this issue. We can see the break line tags are working but not the other tags. As this seems to be out of our apps control I am going to close this issue.
