### ISSUE TITLE
Create automation overlaps menu

### ISSUE THREAD

**Issue by 532910** [home-assistant/android#2594]
**Home Assistant Android version:**
2022.3.0-minimal

**Android version:**
Lineage+microG 18.1 on android 11

**Phone model:**
OP3T

**Home Assistant version:**
Latest docker image

**Description of problem:**
Create automation button overlaps edit automation button:

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/14617699/172508660-38a28c0a-8251-4080-84e5-d79fc012e25e.png)

**Comment by dshokouhi** [comment]
Can you reproduce in Chrome for Android? 

Please also make sure that Android system webview is Googles version found in the play store and that it is set as default, lineage OS typically uses a different webview that is sometimes outdated.

**Comment by 532910** [comment]
I have no Gapps and no Chrome, sorry.

**Comment by dshokouhi** [comment]
You will need to test in chrome to confirm the behavior and you will need to use google version of android webview on your device otherwise we will not be able to help you.

**Comment by 532910** [comment]
Webview is "Android system WebView" with chromium icon:
![image](https://user-images.githubusercontent.com/14617699/172509176-13a58b5f-4bfd-4616-9654-86116bba1c11.png)

**Comment by dshokouhi** [comment]
it needs to be googles version with the package name as `com.google.android.webview` and testing in Chrome confirms if the issue is with the HA frontend which this most likely is as the app does not control the display of the frontend.

**Comment by 532910** [comment]
Here you are:
![image](https://user-images.githubusercontent.com/14617699/172509424-708dbc3c-a429-4c77-8802-69096e26b992.png)

```
% apt policy google-chrome-stable 
google-chrome-stable:
  Installed: 102.0.5005.61-1
  Candidate: 102.0.5005.61-1
  Version table:
 *** 102.0.5005.61-1 500
        500 https://dl.google.com/linux/chrome/deb stable/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by dshokouhi** [comment]
ok so this is an HA frontend issue, as they request different information you'll need to create a new issue supplying all requested information.

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=bug_report.yml

**Comment by 532910** [comment]
Could you just move, please to that project?

**Comment by dshokouhi** [comment]
As their template requests more data than we do its best not to move and have you open a new issue there.  I would also start by looking at open issues to make sure you are not opening a duplicate.
