### ISSUE TITLE
Alarm sensor becomes "unavailable" when there is no active alarm - should it be "none"?

### ISSUE THREAD

**Issue by BoneheadFraggle** [home-assistant/android#2618]
**Home Assistant Android version:**
2022.6.0-full

**Android version:**
12
**Phone model:**
Pixel 6 and Samsund S10e
**Home Assistant version:**
Home Assistant Core 2022.6.6
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2
**Last working Home Assistant release (if known):**
--
**Description of problem:**
Alarm sensor becomes "unavailable" when there is no active alarm. 
There is probably a good reason for why it reports "unavailable", but In my opinion, it would be more appropriate to report "none" or even null since unavailable (at least for me) indicates that there is something wrong.
The sensor shouldn't be unavailable just because there is no active alarm set.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
The sensor reports unavailable when it fails to get alarms out when there are none set.
