### ISSUE TITLE
BSSID sensor supposed to update instantly, but doesn't.

### ISSUE THREAD

**Issue by aaamoeder** [home-assistant/android#2621]
**Home Assistant Android version:** 2022.6.0-full

**Android version:** 11 / 12 / 13

**Phone model:** X3PRO / Oneplus 8 / Pixel 6 Pro

**Home Assistant version:** 2022.6.6

**Last working Home Assistant release (if known):** /

**Description of problem:** The BSSID sensor is supposed to update instantly according to the sensor info but doesn't. Only when turning on/off "Get current BSSID" does the sensor update. (while AP has already been switched).

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):** N/A

```

```

**Screenshot of problem:**

**Additional information:** I'm trying to use this as a presence detection so I can see which smartphones are connected to which AP so fast sensor updates is rather necessary.

**Comment by dshokouhi** [comment]
Can you please get the logs? On my pixel 6 pro it updates instantly

**Comment by aaamoeder** [comment]
> Can you please get the logs? On my pixel 6 pro it updates instantly

I'll get them tomorrow .. it's mainly my son's phone (x3pro) that has the issue, might not be the same for other devices.. assumed so but might have been overzealous..

**Comment by aaamoeder** [comment]
have tried to recreate the issue but for some reason it seems to work now.
I was probably doing something wrong.

 Closed...
