### ISSUE TITLE
Internal Storage sensor only updating once on app start

### ISSUE THREAD

**Issue by marazmarci** [home-assistant/android#2637]
**Home Assistant Android version:** beta-2422-766e879d-full

**Android version:** 12

**Phone model:** S20FE 5G, S21 5G

**Home Assistant version:** 2022.6.6

**Last working Home Assistant release (if known):** Judging based on the code, it's been like this since the feature's introduction.

**Description of problem:** The Internal Storage sensor should be updated regularly. Instead, it's only updated on app start, because the values are stored in a `companion object` of `StorageSensorManager`, and only calculated once when the `companion object` is being initialized.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:** 

**Additional information:**

**Comment by dshokouhi** [comment]
The state is not stored in the companion object, it is determined each time the sensors are updated.

https://github.com/home-assistant/android/blob/aaef43ae386661f236593e207fb3279397bbd453/app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt#L92-L110

**Comment by marazmarci** [comment]
It's okay 🙂 This app will come in handy for testing the issue and the fix:
https://play.google.com/store/apps/details?id=com.arumcomm.fillstorage
