### ISSUE TITLE
Notification command shows text in front end

### ISSUE THREAD

**Issue by davidrustingha** [home-assistant/android#2660]
**Home Assistant Android version:**
beta-2478-0883ada4-full
**Android version:**
11.1
**Phone model:**
Oppo Reno 4Z 5G
**Home Assistant version:**
core-2022.6.7
**Last working Home Assistant release (if known):**
core-2022.6.6
**Description of problem:**
WHen I fire a notification command, specifically the BLE transmitter command, it shows the command in text in the front-end. I think it also fires the command, but i'm not a 100% sure about that.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![WhatsApp Image 2022-07-04 at 10 51 51 PM](https://user-images.githubusercontent.com/62120423/177215547-fc713dfb-5cbe-49a2-9f22-f7cdb275a332.jpeg)

**Additional information:**

**Comment by dshokouhi** [comment]
The command has changed in the latest beta, please refer to the companion app docs and look at the beta label for the updated format.
