### ISSUE TITLE
Only 2 dashboards are visible

### ISSUE THREAD

**Issue by antoweb** [home-assistant/android#2664]
**Home Assistant Android version:**
2022.6.0-full
**Android version:**
11
**Phone model:**
Xiaomi Mi 10t
**Home Assistant version:**
2022.7.1
**Last working Home Assistant release (if known):**
never
**Description of problem:**

I have 3 dashboards but only two are visible on home assistant companion app..Ho to shows all dashboards or almost choose wath are visible?

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
APP
![photo_2022-07-09_12-50-54](https://user-images.githubusercontent.com/32364871/178102599-2b65436b-6346-48ee-863c-774370ef3185.jpg)

Browser
![Cattura](https://user-images.githubusercontent.com/32364871/178102616-1a522784-240c-48bf-813b-bc47f8d41216.PNG)

**Additional information:**

**Comment by jpelgrom** [comment]
Did you maybe edit the menu and remove the dashboard? Tap and hold on the 'Home Assistant' title to enable editing, removed items are listed at the bottom.

**Comment by antoweb** [comment]
Yes i can remove dashboard "SCHEDE" in fompanion app but i want to add dashboard "Panoramica" (default dashboard) but i cant see it.

**Comment by antoweb** [comment]
> Did you maybe edit the menu and remove the dashboard? Tap and hold on the 'Home Assistant' title to enable editing, removed items are listed at the bottom.

At the bottom i cant see "Panoramica" dashboard

**Comment by jpelgrom** [comment]
Is the missing dashboard visible in Settings > Dashboards? If so, is 'Show in sidebar' enabled for it and, if you're not logged in with an admin user, is 'Admin only' turned off?

(The app doesn't change the visibility of dashboards or handle them differently, it's like in any browser.)

**Comment by antoweb** [comment]
So the problem is that the missing dashboard is the overview that was hidden because i have set default another dashboard in my android device. Reset to default dashboard to the "Review" now i can see apl dashboard in side bar

**Comment by dshokouhi** [comment]
This sounds like a HA frontend issue, can you reproduce using chrome for android on the same device?

**Comment by antoweb** [comment]
I think is not an issue because documentation says that if i set default another dashboard the O erbiew was hidden

**Comment by dshokouhi** [comment]
Yup that is correct, closing this issue now
