### ISSUE TITLE
Add Notification Channel as an attribute to the Last Notification Sensor 

### ISSUE THREAD

**Issue by carlos-48** [home-assistant/android#2675]
**Is your feature request related to a problem? Please describe.**

Not a problem, just a minor feature

**Describe the solution you'd like**

I'm ussing the Last Notification Sensor to be able to play by TTS some notifications from my phone apps. But I need to have a new attribute in that sensor to identify the Notification Channel. There are several attributes and I also identify the Android Package in order to trigger different automations for different apps, but I don't want to make the same actions for all the notifications from the same app, I want to filter with the Android Notification Channel.

**Describe alternatives you've considered, if any**

**Additional context**

Sorry about screenshots in Spanish. First one is the HA Developer Tools showing all the attributes of the sensor and an example with a Glovo App notification. Second one is all the available Notification Channels in that Glovo App.
![Screenshot_20220713-213306](https://user-images.githubusercontent.com/63410909/178816672-9f2c3138-ac24-4fa8-8909-3d6999702831.png)
![Screenshot_20220713-213317](https://user-images.githubusercontent.com/63410909/178816674-0600f0c9-0e96-43ba-aea8-4b21fb7ccebe.png)

**Comment by dshokouhi** [comment]
Looks like we can also add `group_id` and `category` from the notification data provided by the API, for this change we might as well add the data to all 3 notification sensors.
