### ISSUE TITLE
"Enable all sensors" option missing under Configuration\Companion App\Manage Sensors

### ISSUE THREAD

**Issue by mkanet** [home-assistant/android#2689]
**Version:** 2022.6.0-full

The Android Home Assistant Companion app used to have a very useful option to enable all sensors at the top/right of the screen under `Configuration\Companion App\Manage Sensors`.  I normally enable all sensors; and, disable the ones I don't want for all our mobile devices in our household.

This option isn't there anymore (at least I can't find it); hence, requiring me to manually enable each sensor one by one.. which takes a VERY long time; especially on multiple Android devices.

How can I enable all sensors with one click like I used to?

**Comment by mkanet** [comment]
Thank you for the very quick reply!  I am still on an older version of Home Assistant.  I plan to upgrade soon.  

Just so I understand correctly...
I will be able to enable/disable any/all sensors on any mobile phone (from the Home Assistant webpage) even if they aren't enabled in the Android apps?  **Are you sure all these entities would be displayed under Settings > Devices > Entities; even if they have never been enabled before in the respective mobile app?**


in the HA webpage unless they were already enabled once before.

**Comment by jpelgrom** [comment]
Yes, starting with Home Assistant 2022.6 **all** available sensors will be synced to your server and show up as enabled/disabled depending on their state in the app. If you're still on Home Assistant 2022.5 or before it'll only sync sensors that have been (previously) enabled.

If you enable a sensor on your server, the app will notice this and also enable the sensor if it has the required permissions. For example: if you enable a location sensor on the server, but the app doesn't have location permission, the app will ignore this and show a notification that this sensor can only be enabled on the phone.

**Comment by jpelgrom** [comment]
You'll get a notification for each sensor that the app wasn't able to enable, tapping on it will open the settings for that specific sensor where you can enable it and grant the required permission(s) 🙂

**Comment by mkanet** [comment]
You guys are awesome!  Thank you so much. I think this way is even better than the original method since I can easily enable/disable sensors from the web interface... at least the ones that don't need permissions.
