### ISSUE TITLE
Virtual keyboard appears then disappears immediately

### ISSUE THREAD

**Issue by neopilou** [home-assistant/android#269]
**Home Assistant Android version:**
1.4.0

**Android version:**
9

**Phone model:**
Samsung Galaxy S5e
Samsung Galaxy S9+
Samsung Galaxy A10

**Home Assistant version:**
0.104.1

**Description of problem:**
If I click on an input zone, to enter the alarm code for example (Panel Card Alarm: https://www.home-assistant.io/lovelace/alarm-panel/) the virtual keyboard appears then disappears immediately.

Edit : After much research, "custom: layout-card" is the issue. When the keyboard appears this changes the size of the webview (or of the content of the webview) and "custom: layout-card" causes the page to reload in order to adapt the size of the columns.

**Comment by dshokouhi** [comment]
Closing as the issue was with a custom card
