### ISSUE TITLE
Moving between pages rearranges pages instead

### ISSUE THREAD

**Issue by mariawarnes** [home-assistant/android#2692]
**Home Assistant Android version:**
2022.6.0-full

**Android version:**
12

**Phone model:**
Google Pixel 3a

**Home Assistant version:**
Home Assistant 2022.7.5
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.1 - latest

**Last working Home Assistant release (if known):**
Unknown

**Description of problem:**
Tapping between mobile lovelace pages seems to be actioned as if the rearrange arrows were being pressed instead.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:** 
https://user-images.githubusercontent.com/36001658/179774140-fc68bc3d-5f2e-4510-9340-c3c0466a3996.mp4

**Additional information:**
Changing the pages I have not visible to visible does not seem to make any difference, the issue persists.

**Comment by dshokouhi** [comment]
can you reproduce this issue in chrome for android on the same device?

**Comment by mariawarnes** [comment]
It does also happen in my mobile Opera Browser. Can download Chrome and check on mobile too if you want that to check that specific browser.

**Comment by dshokouhi** [comment]
So that means this is a HA frontend issue and not app related. Please first check for open issues and if you don't see an existing issue file a new issue there. The HA frontend repo requires a different template to be filled out so its best to start with a new issue.

https://github.com/home-assistant/frontend

**Comment by mariawarnes** [comment]
Thanks @dshokouhi ! Will do
