### ISSUE TITLE
Location Sensors missing

### ISSUE THREAD

**Issue by Pixdigit** [home-assistant/android#2694]
**Home Assistant Android version:**
2022.6.0-minimal
**Android version:**
11 (Lineage OS 18.1)
**Phone model:**
Fairphone 3
**Home Assistant version:**
2022.7.5
**Last working Home Assistant release (if known):**
I recall it working some time ago but I I don't recall when.
**Description of problem:**
In the settings for sensors of the companion app under "Manage Sensors" there are no location sensors listed at all.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
not applicable
```

```

**Screenshot of problem:**
irrelevant
**Additional information:**
I tried reinstalling the app and/or resetting app data without effect.

**Comment by dshokouhi** [comment]
Location tracking is not available on the minimal version, will be available after #1511

**Comment by Pixdigit** [comment]
Oh, that was quick, thank you. Is that documented somewhere because I found no info about this except "some sensors are not shown when not available"? I think it might be beneficial to mention this somewhere in the docs or the app description in F-Droid.

**Comment by Pixdigit** [comment]
Oh my bad, it was already written there. Sorry for the inconvenience.
