### ISSUE TITLE
Notification Command clear_notification should trigger mobile_app_notification_cleared event

### ISSUE THREAD

**Issue by soloam** [home-assistant/android#2701]
**Is your feature request related to a problem? Please describe.**
When A "clear_notification" is triggered, I would like to catch that action (It could be originated by other terminal) and I would like to catch that event to make the automation act, for example stop waiting in all devices.

**Describe the solution you'd like**
When the app recieves a "clear_notification" command, it should trigger a "mobile_app_notification_cleared" event, or another event. It could contain in the data that it was triggered by the service

**Describe alternatives you've considered, if any**
None

**Additional context**
All included above

**Comment by dshokouhi** [comment]
Why is this request necessary? As long as you use critical notification format it will clear immediately and you can clear from all devices.

**Comment by soloam** [comment]
I have automatons that act on some messages being cleared, and without this event, or some that I can l monitor, I can't know that a notifications was cleared when it's from the app. Sure I could do a script that calls the clear notification and trigger a event, but I think that it would be the best solution that if a notifications is cleared (even that it's from a service) that it should trigger this event (or other with a different name)

**Comment by dshokouhi** [comment]
> I have automatons that act on some messages being cleared, and without this event, or some that I can l monitor, I can't know that a notifications was cleared when it's from the app.

But you don't need an event here, simply sending the message is good enough on your part to know it was cleared as that is your action to clear it. The event being sent is sent based on user and/or device behavior, the clear command is already something you use to trigger from HA.

**Comment by jpelgrom** [comment]
> But you don't need an event here

I can imagine two relevant scenarios:

 - It's possible that the notification is cleared either by the user or by an automation, being able to use the same trigger for both could be useful.
 - It's possible that an automation requests clearing the notification but it was already cleared.

**Comment by dshokouhi** [comment]
So now we would need to check if the notification still exists and then send the event in those cases? That begins to overcomplicate the clear command which simply clears the notification as soon as the command is received regardless of the notification being present.

Now I can see a benefit in the app sending an event to confirm receipt of any notification but not just for a notification clear command being received and processed. That to me seems repetitive, if you send an automation to clear the notification then you should be assured its already cleared as that was the purpose of the command. Its a fair assumption to continue with the script as the command gets processed immediately, it will add a delay in that command just to send an event.  The original event gets sent when a user performs an action to clear the notification, HA sending an automation is identical to that behavior.

**Comment by soloam** [comment]
I understand your point. At the moment you only clear send the command to clear the notification, regardless of the fact that the notification exists or not To make this work it would need to check if the notification exists, so that it does not send a cleared notification when nothing happened, because the notification didn't existed, or simply was already cleared.

Now your idea of sending a replay that the command was received is very interesting and in the end would be a lot better than the original idea. It would solve my problem and a lot more!

**Comment by dshokouhi** [comment]
ok submitted a PR to add a setting to fire an event when a notification is received.

This will also match up functionality with the HTML5 notify platform which also fires an event in this case: https://www.home-assistant.io/integrations/html5/#received-event

**Comment by soloam** [comment]
This is great! Tks

**Comment by dshokouhi** [comment]
Just a FYI @soloam this functionality is going to change with #2899 you will then need to specify when a notification should send a received event.
