### ISSUE TITLE
Fetched image previews in notifications do not use mTLS

### ISSUE THREAD

**Issue by charlesmunger** [home-assistant/android#2706]
**Home Assistant Android version:**
version beta-2500-f8d0d461-full

**Android version:**
12

**Phone model:**
Pixel 6

**Home Assistant version:**
2022.7.6

**Last working Home Assistant release (if known):**

**Description of problem:**
Notification `image` URLs do not use mTLS and so they don't load if mTLS is required. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
07-23 19:41:29.328 23688  3325 D UrlRepository: localUrl is: true and usesInternalSsid is: false
07-23 19:41:29.328 23688  3325 D UrlRepository: Using external URL
07-23 19:41:30.236 23688  3325 E MessagingService: Couldn't download image for notification
07-23 19:41:30.236 23688  3325 E MessagingService: java.io.FileNotFoundException: https://<url redacted>:8808/api/frigate/notifications/1658616858.243185-7e068v/thumbnail.jpg?format=android
07-23 19:41:30.236 23688  3325 E MessagingService: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
07-23 19:41:30.236 23688  3325 E MessagingService: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
07-23 19:41:30.236 23688  3325 E MessagingService: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
07-23 19:41:30.236 23688  3325 E MessagingService: 	at io.homeassistant.companion.android.notifications.MessagingManager$getImageBitmap$2.invokeSuspend(MessagingManager.kt:1276)
07-23 19:41:30.236 23688  3325 E MessagingService: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-23 19:41:30.236 23688  3325 E MessagingService: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-23 19:41:30.236 23688  3325 E MessagingService: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
07-23 19:41:30.236 23688  3325 E MessagingService: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
07-23 19:41:30.236 23688  3325 E MessagingService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
07-23 19:41:30.236 23688  3325 E MessagingService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07-23 19:41:30.236 23688  3325 E MessagingService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
07-23 19:41:30.236 23688  3325 E MessagingService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
07-23 19:41:30.242 23688 23688 D MessagingService: Show notification with tag "null" and id "773113062"
```

**Screenshot of problem:**

**Additional information:**

https://github.com/home-assistant/android/blob/44d4d564860cc9825c3aaf2fe9c40576b8a90f3c/app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt#L1272

This should be updated to use OkHttpClient like the other networking in home assistant. The effect of this is that notifications do not show images.

**Comment by dshokouhi** [comment]
This issue is missing the issue template that gets presented when a new issue is created. Please fill out the template without skipping anything.

**Comment by charlesmunger** [comment]
Done, sorry. The create-issue-from-line flow doesn't prompt for a template.

**Comment by dshokouhi** [comment]
Did you use a relative path in your automation?  Hard to tell since an example was not shown.  Relative URLs means the app will add auth, otherwise a full URL will not use auth.

**Comment by charlesmunger** [comment]
Relative URL. The authorization added based on relative/absolute is the authorization header, separate from client auth. I believe all other network communication in the app goes through WebView or okhttp, both of which are set up to use mTLS if configured - looks like this one-off network connection was just missed.

**Comment by dshokouhi** [comment]
> looks like this one-off network connection was just missed.

its possible this call and maybe others, if you are able to check other app features that would be great. If you see anything else please report them in a separate issue. I believe this is the first issue on TLS since the feature was merged recently into the beta.  Not a lot of users have TLS setup on their end so the testing scope here was limited to users and the contributor.

@magicbuffer FYI in case you can help out here :)

**Comment by Rogue136198** [comment]
Beat me to the punch on opening this issue.

I noticed this issue when I implemented mTLS. For the time being I have worked around the issue by only performing mTLS auth on the main URL and not on /api, /media or /local

Here is an example of my Nginx config
<details>
<summary>Nginx config</summary>
<br>

```
server {
    listen 443 ssl http2;
    # enable for IPv6 support
	#listen [::]:443 ssl;

    server_name ha.example.lan;

    include /config/nginx/ssl.conf;
	
    proxy_redirect off;
    proxy_buffering off;
	
	ssl_client_certificate /config/keys/ca.0b1.ca.crt;
	ssl_verify_client optional;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        if ($ssl_client_verify != SUCCESS) {
			return 403;
		}
		
	# enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app homeassistant;
        set $upstream_port 8123;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
    
    location ~ ^/(api|local|media)/ {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app homeassistant;
        set $upstream_port 8123;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```
</details>

As an aside, if you are using integrations like Sonos for TTS announcements you will need to either bypass your reverse proxy and connect directly to the HA IP or create a separate reverse proxy entry (e.g. ha-lan.example.url). If you go the reverse proxy route this separate domain should only allow connections from your LAN IP range.

@dshokouhi I see an issue in my above example where someone has mTLS configured using `ssl_peer_certificate:` in `configuration.yaml` They would have no workaround to bypass mTLS. In which repository should I open an issue/FR to add an IP/subnet whitelist to bypass mTLS in order to resolve this?

**Comment by dshokouhi** [comment]
> @dshokouhi I see an issue in my above example where someone has mTLS configured using `ssl_peer_certificate:` in `configuration.yaml` They would have no workaround to bypass mTLS. In which repository should I open an issue/FR to add an IP/subnet whitelist to bypass mTLS in order to resolve this?

sounds like a request for HA core?

**Comment by jpelgrom** [comment]
Hi 👋

I've updated the code that downloads notification images to use the `OkHttpClient` used elsewhere in the app to support the certificate setup, and in my testing it works. I don't normally use mTLS though, so if you're able to install a test version of the app to confirm it works for you as well that'd be helpful: https://github.com/home-assistant/android/actions/runs/2809522658. (It will install alongside the existing version of the app.)

**Comment by Rogue136198** [comment]
Just gave your test build a go and unfortunately it does not appear to be working. I validated that the video works when not using mTLS. 

When running debug it throws the following error:

```
2022-08-06 12:39:29.241 1336-16884/? E/StagefrightMetadataRetriever: Unable to instantiate an extractor for 'https://MY_URL.CA/media/local/test.mp4'.
2022-08-06 12:39:29.244 16035-16611/io.homeassistant.companion.android.debug E/MessagingService: Couldn't download video for notification
    java.lang.RuntimeException: setDataSource failed: status = 0x80000000
        at android.media.MediaMetadataRetriever._setDataSource(Native Method)
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:281)
        at io.homeassistant.companion.android.notifications.MessagingManager$getVideoFrames$2.invokeSuspend(MessagingManager.kt:1403)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-08-06 12:39:29.480 1835-4302/? E/ActivityManager: Cannot find package for uid: 1013
2022-08-06 12:39:29.480 1336-1505/? E/MediaPlayerService: Couldn't open fd for content://settings/system/notification_sound
2022-08-06 12:39:29.480 2467-18063/? E/MediaPlayerNative: Unable to create media player
```

**Comment by dshokouhi** [comment]
> Just gave your test build a go and unfortunately it does not appear to be working. I validated that the video works when not using mTLS.

Just a FYI but the original issue mentions `image` is not working but I see you tested `video`.  Could you test that `image` is working in that build now?

**Comment by jpelgrom** [comment]
That is a video, not an image 😉 I haven't made any changes there so I guess you discovered a new bug.

**Comment by Rogue136198** [comment]
Touché

I just assumed they would be the same. They in fact are not. 

Images are working fine when using mTLS.
