### ISSUE TITLE
Subnet

### ISSUE THREAD

**Issue by 80805504141995613430** [home-assistant/android#2708]
--- 24 de jul. de 2022 04:22:42
--- IP (rmnet_data0) 2804:214:8488:9607:908d:586a:c689:279f 
--- IP (rmnet_data0) 100.71.81.30 
--- IP (rmnet_data2) 2804:214:814e:491c:1:2:66c3:b13 
--- Connection: LTE

Subnet scan from 100.77.181.1 to 100.77.181.254

100.77.181.2
100.77.181.3
100.77.181.4
100.77.181.6
100.77.181.12
100.77.181.13
100.77.181.17
100.77.181.18
100.77.181.21
100.77.181.25
100.77.181.32
100.77.181.34
100.77.181.35
100.77.181.40
100.77.181.43
100.77.181.44
100.77.181.50
100.77.181.51
100.77.181.62
100.77.181.65
100.77.181.66
100.77.181.68
100.77.181.69
100.77.181.72
100.77.181.76
100.77.181.77
100.77.181.81
100.77.181.83
100.77.181.87
100.77.181.89
100.77.181.96
100.77.181.97
100.77.181.99
100.77.181.100
100.77.181.102
100.77.181.103
100.77.181.105
100.77.181.108
100.77.181.109
100.77.181.112
100.77.181.113
100.77.181.115
100.77.181.116
100.77.181.117
100.77.181.122
100.77.181.127
100.77.181.130
100.77.181.132
100.77.181.134
100.77.181.136
100.77.181.139
100.77.181.144
100.77.181.145
100.77.181.146
100.77.181.147
100.77.181.152
100.77.181.154
100.77.181.155
100.77.181.156
100.77.181.164
100.77.181.167
100.77.181.171
100.77.181.172
100.77.181.174
100.77.181.175
100.77.181.177
100.77.181.180
100.77.181.186
100.77.181.187
100.77.181.188
100.77.181.193
100.77.181.196
100.77.181.198
100.77.181.199
100.77.181.200
100.77.181.210
100.77.181.211
100.77.181.212
100.77.181.218
100.77.181.219
100.77.181.229
100.77.181.234
100.77.181.235
100.77.181.243
100.77.181.244
100.77.181.245
100.77.181.246
100.77.181.247
100.77.181.250
100.77.181.252

**Comment by dshokouhi** [comment]
This issue is missing the issue template that gets presented when you create an issue. There is no relevant information here.
