### ISSUE TITLE
Update Material Design Icons to 7.0.96

### ISSUE THREAD

**Issue by jpelgrom** [home-assistant/android#2709]
**Is your feature request related to a problem? Please describe.**

On Discord there was [a message](https://discord.com/channels/330944238910963714/377667559303938050/9996141964361892340) about Material Design Icons 7.0.96, which will be included in the next frontend release and includes [breaking changes](https://dev.materialdesignicons.com/changelog#version-7.0.96). The app should be updated to the latest version to handle these changes and provide a good experience.

**Describe the solution you'd like**

Update the Material Design Icons included in the app to version 7.0.96 or newer.

One icon used by the app should be renamed to `mdi:microphone-message`:
https://github.com/home-assistant/android/blob/f9ceeb0d651074675ef833f23040af8e0a53aca9/app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt#L221

MDI icons are used and provided by two libraries:

1. [Android-Iconics](https://github.com/mikepenz/Android-Iconics), currently on 6.4.95 and no update available. Main + Wear app. <br> It shouldn't be too hard to create a PR here and update it, [@leroyboerefijn suggested he might do it](https://discord.com/channels/330944238910963714/377667559303938050/999753602224623716).

2. [Icon Picker Dialog](https://github.com/maltaisn/icondialoglib), currently on 5.3.45 and no update available - library hasn't been updated in ~2 years. Main app only. <br> Updating it is difficult because it depends on [this file](https://github.com/PeterShaggyNoble/MDI-Sandbox/blob/master/json/icons.json) which also is out of date, and there doesn't appear to be any activity. @goyney, a MDI contributor, offered to look into it [and said](https://discord.com/channels/330944238910963714/377667559303938050/1000565719991332905):

> Okay, so we have no connection to either of those libraries, so unfortunately, I have no pull to get them updated. I can tell you though, that they should have never been using that PeterShaggyNoble link. His work wasn't anything official and he had personal things come up that has severely limit his time to help out now or in the future.
>
> My suggestion would be to either fork or create a new library and use the official libraries we provide, specifically @mdi/svg. It contains meta.json that will always be up-to-date with out latest releases: https://github.com/Templarian/MaterialDesign-SVG/blob/master/meta.json
> 
> It can be installed and version controlled via NPM.

**Describe alternatives you've considered, if any**

No realistic alternatives

**Additional context**

Including two libraries with these icons also feels redundant, perhaps a better solution would be to start bundling the icons ourselves and create a simple wrapper and icon picker [like the frontend](https://www.home-assistant.io/blog/2021/11/03/release-202111/#the-icon-picker)?

**Comment by goyney** [comment]
I'm not an Android dev and my free time is a little limited at the moment due to family, but please let me know if I can be of any assistance on the MDI side of things.

**Comment by jpelgrom** [comment]
@NotWoods I noticed that you had done some work on a Compose-based icon dialog for the Android-Iconics icons [on a branch in your repository](https://github.com/NotWoods/android/tree/compose-icon-dialog) - was that related to this issue by any chance? At first glance it's a nice start.

**Comment by NotWoods** [comment]
It's for this issue, I just didn't have it working yet and got pulled to other projects. I'll take another stab for hacktoberfest :)

**Comment by jpelgrom** [comment]
It looks like my PR to update MDI for Android-Iconics was merged a few hours ago, so library 1 from the issue description should be updated soon.

**Comment by NotWoods** [comment]
Currently I'm running into backwards-compat issues. The dialog works but its not clear how to convert between the IDs each library uses. MDI uses unicode codepoints but Iconics uses some arbitrary hex values.

**Comment by jpelgrom** [comment]
If I understand it correctly, the reason characters are remapped in Iconics to a different range is because of compatibility issues on some devices. It does use the same icon names as the official MDI which you're supposed to use (see: all places in the app where Iconics is currently used). 

However, the existing Icon Picker Dialog doesn't include any information about codepoints at all I think and is using even more arbitrary IDs? It seems inevitable to include a (generated) file that simply maps one ID to another.

**Comment by NotWoods** [comment]
The existing dialog does at least have a file in its source code with a mapping. I'll look at using the names, thanks!
