### ISSUE TITLE
Feature Request: Modify phones call forwarding setting

### ISSUE THREAD

**Issue by Ziris85** [home-assistant/android#2717]
Hello All,

Sadly I'm not an Android developer (or much of a developer at all heh), so I'm just submitting this as a feature request (please let me know if there is a more appropriate way to do this!). I think it would be very handy if the homeassistant android app could interact with my phones call forwarding settings, such that I can conditionally enable/disable/modify them with automations. There are plenty of android apps in the play store that appear to be able to modify this setting so it does at least appear to be possible. Right now I'm doing a clunky setup with an NFC tag by my charger to dial the special number to enable forwarding, and have to manually disable forwarding when I grab it again. It would be really cool and useful if I could just write an automation to enable forwarding when my phone is plugged in, and disable it when it's unplugged!

I didn't see any previous similar discussions about this, so if this is a duplicate request, then I apologize.

Thanks for your time, consideration, and everything you all do! I love HA and thinking of new ways to utilize it.

**Comment by dshokouhi** [comment]
I think this may already be supported using `command_activity`

https://companion.home-assistant.io/docs/notifications/notification-commands#activity

You have to grant the app all the permissions it requests to do so. 

```
service: notify.mobile_app_dannys_pixel_6_pro
data:
  message: command_activity
  data:
    tag: android.intent.action.CALL
  title: "tel:4444"
```

Replace `4444` with the dialer code you use.

**Comment by dshokouhi** [comment]
if you are on the beta version of the app the command format has changed, the new details are in the link above

**Comment by Ziris85** [comment]
Hey, thank you! Yeah, this appears to be what I'm looking for! Sadly though, it doesn't quite work in this way. At least for my carrier (t-mobile) but [possibly for the rest](https://www.makeuseof.com/tag/call-forwarding-iphone-android/), the special code requires a trailing # that gets stripped out when the call is actually made. My yaml that I used in the devtools:

```
service: notify.mobile_app_my_phone
data:
  message: command_activity
  data:
    tag: android.intent.action.CALL
  title: tel:**21*12345678901#
```

However, the phone will end up just trying to call `**21*12345678901`. Similarly I need to dial `##21#` to turn off forwarding, but when I try that, all that happens is my phone complains "Call not sent, no valid number entered", probably meaning the trailing # was removed again.

It's worth mentioning that the NFC tag app I'm using actually has the same problem, so instead of having it call the number automatically, I just have it dial the number (which seems to work and leaves the trailing # ) and then I have to actually place the call myself. Definitely not ideal for automations, but maybe there's some sort of restriction in the Android OS (or my built-in dialer app specifically) that's prohibiting placing those special calls automatically? If this issue can be worked around then I think this will do exactly what I'm looking for.

**Comment by dshokouhi** [comment]
>   title: tel:**21*12345678901#

can you try `title: "tel:**21*12345678901#"` instead? to make sure the whole string is there?

> However, the phone will end up just trying to call `**21*12345678901`. Similarly I need to dial `##21#` to turn off forwarding, but when I try that, all that happens is my phone complains "Call not sent, no valid number entered", probably meaning the trailing # was removed again.

Can you look at the Companion App logs and confirm the data being sent to the app is correct? You should see log lines for the command coming in and all that.  We have to see if the app has the correct data or something else



> It's worth mentioning that the NFC tag app I'm using actually has the same problem, so instead of having it call the number automatically, I just have it dial the number (which seems to work and leaves the trailing # ) and then I have to actually place the call myself. Definitely not ideal for automations, but maybe there's some sort of restriction in the Android OS (or my built-in dialer app specifically) that's prohibiting placing those special calls automatically? If this issue can be worked around then I think this will do exactly what I'm looking for.

if another app has the same issue then most likely its android causing this but lets look at the logs and see whats going on.

Try to use Google Dialer instead of your stock dialer (if not using googles already)

**Comment by Ziris85** [comment]
Yeah, after I posted that I started playing around with some different things. Quotes had no effect on the result, and the companion app logs do confirm that the right number is being sent along. For fun I tried doing `android.intent.action.DIAL` and on the built-in app it correctly displays the number. Interestingly, with the Google Dialer app and another one I tried (True Phone), the trailing # is removed in **both** cases (DIAL and CALL). I also tried playing around with the number, adding extra # 's and numbers after it, and it seems everything after that is just stripped away. In fact, if I even try to just DIAL the `##21#` number, literally nothing is displayed (with the exception of the built-in dialer, which will display the first # but nothing after it).

I did some more googling research and found that others were having to URI-encode the # , so I modified my yaml to:

```
service: notify.mobile_app_my_phone
data:
  message: command_activity
  data:
    tag: android.intent.action.CALL
  title: tel:**21*12345678901%23
```
...and now it works perfectly (on all three apps, too)! Similarly to turn it off I just have to call `%23%2321%23`, and it turns it off.

My research did hint at an android intent that might directly interact with call forwarding settings without having to call the special number, but I wasn't able to glean one that I might be able to use within HA. In any case, this appears to be doing exactly what I want, so for now I suppose I can close this one up. I know the HA docs state that you can launch **_ANY_** activity this way, so it might be a tall ask, but it might be useful to expose at least some of them as selectable options within HA, and then provide a comprehensive list somewhere for the rest?

**Comment by dshokouhi** [comment]
> I know the HA docs state that you can launch ANY activity this way, so it might be a tall ask, but it might be useful to expose at least some of them as selectable options within HA, and then provide a comprehensive list somewhere for the rest?

That's out of scope for the Android app, more of a HA core feature request.
