### ISSUE TITLE
Status Bar doesn't always match theme

### ISSUE THREAD

**Issue by JBassett** [home-assistant/android#272]
Currently the status bar theme is pulled from the current globally set theme.  In order to get the theme set for the device an enhancement has been requested of the front end to provide that information.

Depends on: https://github.com/home-assistant/home-assistant-polymer/issues/4220

**Comment by dgtal1** [comment]
+1 to this

**Comment by agneevX** [comment]
This is very nice feature and I hope it'll get added.

**Comment by barrymossel** [comment]
**Home Assistant Android version:**
beta-580-5ee48f2

**Android version:**
Android 11

**Phone model:**
Pixel 5

**Home Assistant version:**
core-2021.2.2
supervisor-2021.02.6

**Last working Home Assistant release (if known):**

**Description of problem:**
When setting theme through frontend.set_theme (mode: light) the Android status bar gets the expected color. After a restart of Home Assistant, the status bar switches to the default color though (blue for Android light mode and black for Android dark mode). The theme itself stays the theme I set it too. Theme follows dark mode (mode: dark) as expected, but status bar does not. When status bar color changes to "default" theme (after restart) it follows the Android dark mode though.
Theme in profile is set to back-end selected (as that is used for following dark mode).

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**
When status bar has uses default color after HA restart and setting my **dark theme**

```
    - service: frontend.set_theme
      data:
        name: thuis-dark
        mode: dark

```
The status bar changes to the **light theme** primary color.
