### ISSUE TITLE
Connected not paired devices 

### ISSUE THREAD

**Issue by guarddog13** [home-assistant/android#2726]
**Is your feature request related to a problem? Please describe.**

The Bluetooth sensor recognizes connected not paired devices but they don't show up as devices that can trigger high accuracy mode within the app. 

**Describe the solution you'd like**

Could this be set up in the companion app so that i can choose these connected not paired devices? 

**Describe alternatives you've considered, if any**

I currently use a template automation based on the mac address from the Bluetooth sensor. 
**Additional context**

![Screenshot_20220729-084451_Home Assistant](https://user-images.githubusercontent.com/31947215/181765172-4e8af650-214c-4ab0-b3d6-524167c18207.jpg)

![Screenshot_20220729-084940_Home Assistant](https://user-images.githubusercontent.com/31947215/181765225-1c6fa994-3723-4604-82db-8fbc2513b079.jpg)

**Comment by guarddog13** [comment]
I have a couple of use cases with this, especially if I Fi can get their collars to connect to the bases better than they do phones. Devices like the Fi collar and the Roav charger I use in my truck are connected via BLE.

1. My thought when Fi pushes their update is that when my Husky isn't connected to his base High Accuracy Mode is on, on my phone. This does one of two things...it ensures that I'm tracked when he's with me, this keeps the Fi app on the ready working with Google Fused location. If he takes off as he's prone to do then I have at least the distance of my BLE to keep faster than 60 second tracking. He tends to stay in a visible range and bolts when you get close. Any time I can gain is gold as we live near a busy freeway and highway. 

2. The other is to have the app see the Roav devices to trigger the Companion as mentioned before. I work in a rural county and having an automation do it may not always be possible...although I was surprised to see the high accuracy automation run with nearly zero internet connection....when a webhook didn't go to my server in the exact same spot.

**Comment by dshokouhi** [comment]
Can you test out the debug APK from: https://github.com/home-assistant/android/actions/runs/2764064862 make sure to use the full version. Should let you select the device. Make sure the devices are connected when you select the device because thats the only way the app knows it exists :)

**Comment by guarddog13** [comment]
That seems to work. When the Roav charger is on it connects and gives it a name. When it's off it gives it it's MAC addy. The only thing and this may because of it being a debug app...

I had to open the app to get it to recognize the toggles. If the app was already open, I had to close and reopen it to recognize the toggles.

**Comment by dshokouhi** [comment]
> I had to open the app to get it to recognize the toggles. If the app was already open, I had to close and reopen it to recognize the toggles.

what toggles are you referring to? You should be able to install the app, login and select the device immediately after turning on high accuracy mode in settings.

**Comment by dshokouhi** [comment]
Actually can you check in the production version when the device has actually been connected, it should pick it up when its actively connected.  When I checked this issue and thought I reproduced it my device was not connected when I checked the setting. Now that it is connected I can see it.

**Comment by guarddog13** [comment]
You're right it works. I had to make sure to open the roav app once and go back after it connected but it's working.

**Comment by dshokouhi** [comment]
Awesome! Thanks for confirming 👍
