### ISSUE TITLE
Wear OS Shortcut feedback

### ISSUE THREAD

**Issue by Kisty** [home-assistant/android#2728]
**Is your feature request related to a problem? Please describe.**

It's hard to know when an action is executed (e.g. start a timer) when I click on a shortcut button in the tile on my watch. Each time, I have to check on the phone or web to check that I've started a timer. Sometimes the action doesn't happen because the watch's connection to the internet (via phone or wifi) is not very reliable. (Huawei Watch 2 Classic)

**Describe the solution you'd like**

A toast message shows up once it executes successfully. Similar to what happens when you click on an entity or favourite in the wear app.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
hmm i thought the toast messages and haptic feedback also apply in the shortcut tile

**Comment by jpelgrom** [comment]
Would you expect this immediately when tapped, like in the app or for vibrations, or when the command was executed? I'm thinking about request #2687 - if not careful we'll get multiple confirmations and I'm not sure that's helpful.

**Comment by Kisty** [comment]
I hadn't seen that request yet I did do a thorough search. That's precisely
what I would like. Feedback on successfully executed.

**Comment by jpelgrom** [comment]
In that case this should be treated as a duplicate, let's use #2687 to keep track of it and close this one.
