### ISSUE TITLE
Removing a person's device is impossible in the app

### ISSUE THREAD

**Issue by klaernie** [home-assistant/android#2741]
**Home Assistant Android version:**
2022.6.0-full (installed from Google Play store)

**Android version:**
12

**Phone model:**
Pixel 6 Pro

**Home Assistant version:**
2022.07.0

**Last working Home Assistant release (if known):**
not known

**Description of problem:**
Removing one of the devices assigned to a person does not work.

Step 1: Go to Settings -> People
Step 2: Choose a Person
Step 3: Scroll to the devices
Step 4: Delete one of the devices using the `X` at the right of the textbox. The text in this line item changes to the suggestion text "Track Device".
Step 5: Click `Update`
Step 6: Go back into the same person and observe the deleted entry still remains

Deleting the same device on a desktop browser works.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
Device list before touching it:
<image src="https://user-images.githubusercontent.com/5636383/182043404-853c008e-f2f9-4bd6-aa30-55f482130bfc.png" width="300" />
Device list after deleting, but before saving
<image src="https://user-images.githubusercontent.com/5636383/182043422-af2fb170-7f66-4a2a-abfd-076227f3f02e.png" width="300" />

I've opted to not include the screenshot going back after saving, since it would be identical to the first screenshot.

**Additional information:**
In contrast to the desktop browser the app does not seem to delete the entire dropdown/text combobox, but just clears it's content.

**Comment by dshokouhi** [comment]
Can you please check in chrome for Android on the same device? That's a better comparison than desktop to app.

**Comment by klaernie** [comment]
Chrome on Android behaves the same as the app. That is `Chrome 103.0.5060.129`

**Comment by dshokouhi** [comment]
Ok that means this is a HA frontend issue and not an app issue. Please first check open issues and if it doesn't already exist open a new one. Make sure to complete the issue template there.

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=bug_report.yml

**Comment by klaernie** [comment]
Thanks for the triage, @dshokouhi !

**Comment by klaernie** [comment]
Found the underlying issue as already reported in https://github.com/home-assistant/frontend/issues/13226
