### ISSUE TITLE
Ability to set intent flags on actionable notifications

### ISSUE THREAD

**Issue by mwilky** [home-assistant/android#2748]
**Is your feature request related to a problem? Please describe.**

If launching an app or intent from notification actions, if the notification shade is fully expanded, the app launches behind the notification shade rather than coming into view.

**Describe the solution you'd like**

It would be great if we could define flags to launch intents with - for example `Intent.FLAG_ACTIVITY_REORDER_TO_FRONT`

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
This intent you refer to cannot be used for our `PendingIntent` which is used for actionable notifications

https://developer.android.com/reference/android/app/PendingIntent#getBroadcast(android.content.Context,%20int,%20android.content.Intent,%20int)

**Comment by dshokouhi** [comment]
Those intents could be applied to our notification commands for `command_start_activity` and `command_broadcast_intent` but those may not really need to be changed as they may cease to work.

**Comment by dshokouhi** [comment]
Google had also deprecated our old intent that we used which can no longer be used. Android will not decide when the shade should be closed.

https://developer.android.com/reference/android/content/Intent#ACTION_CLOSE_SYSTEM_DIALOGS

closing as we cannot do this request
