### ISSUE TITLE
Clicking notifications spawns multiple app instances

### ISSUE THREAD

**Issue by gfduszynski** [home-assistant/android#2749]
**Home Assistant Android version:** 2022.6.0-full

**Android version:** 12

**Phone model:** SM-G73F (Samsung Galaxy S10)

**Home Assistant version:** 2022.4.5

**Last working Home Assistant release (if known):** Unknown

**Description of problem:**

When using `clickAction` pointing to `'/lovelace-intercom/0'` new instance of app is being launched for every click of notification.
In my opinion it would be ideal to open the said dashboard in already opened app if present.

Below is the result of clicking the notification 3 times.

![image](https://user-images.githubusercontent.com/1913102/182443392-4fbc318b-2757-4f31-bc93-a8ef972761ab.png)

**Comment by dshokouhi** [comment]
For our case the app needs to request a new activity because we have a WebView instance which can at times get stuck and not update to the correct view/dashboard consistently. In order to ensure taht the correct dashboard will indeed load consistently we have done this change.  Some launchers just like to show the multiple activities instead of an app instance, annoying but out of our control.

**Comment by dshokouhi** [comment]
Example of an old issue that I am referring to: https://github.com/home-assistant/android/issues/486, another fix was in #477

Going to close this for now as its intended behavior for the feature to work consistently.

**Comment by gfduszynski** [comment]
I understand why, however please note this can create issues as in my case with SIP card. 
Unintended consequence is that user can end with a situation when call is answered in several web views at once and its something I'm looking for workaround for.
Have you considered terminating old WebView after spawning the new one ? (If that is even possible)

**Comment by dshokouhi** [comment]
> Have you considered terminating old WebView after spawning the new one ? (If that is even possible)

this would then result in webview reloading from the dashboard when the app is started as opposed to opening from the last viewed page. You're now asking the app not to retain its view when user swipes to the home screen.

**Comment by dshokouhi** [comment]
One thing that may be of help. If you enable the [App Importance sensor](https://companion.home-assistant.io/docs/core/sensors#app-importance-sensor) you can then detect when teh application is actually open on the device. That should help you to determine what to do in those cases?

**Comment by gfduszynski** [comment]
I think I can work with that, thank you :+1:
