### ISSUE TITLE
Three finger swipe to open Quick Bar not working 

### ISSUE THREAD

**Issue by adabelleleiram** [home-assistant/android#2758]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The three finger swipe gesture to access the Quick Bar doesn't work any more in the companion app.

### Describe the behavior you expected

What is described under Swipe Gestures:
https://companion.home-assistant.io/docs/integrations/android-webview/#swipe-gestures

### Steps to reproduce the issue

1. Swipe down with 3 fingers in the companion app on Android

### What version of Home Assistant Core has the issue?

2022.7.5

### In which browser are you experiencing the issue with?

Companion App (2022.6.0-full)

### Which operating system are you using to run this browser?

Google Pixel 6, Android 12

**Comment by dshokouhi** [comment]
duplicate https://github.com/home-assistant/android/issues/2686

Sorry this gesture is only supported on Home Assistant core 2022.6 or earlier.
