### ISSUE TITLE
Scaling different than standard chrome

### ISSUE THREAD

**Issue by barrymossel** [home-assistant/android#276]
**Home Assistant Android version:**
81
**Android version:**
10
**Phone model:**
Galaxy S10
**Home Assistant version:**
104.2
**Last working Home Assistant release (if known):**

**Description of problem:**
Scaling is just a little different compared to normal chrome. Look at the text...

Chrome:
![Screenshot_20200118-143413_Chrome](https://user-images.githubusercontent.com/10389401/72664560-ef275f00-39ff-11ea-9df4-1dd23036b050.jpg)

Companion app (text a bit larger)
![Screenshot_20200118-143420_Home Assistant](https://user-images.githubusercontent.com/10389401/72664562-f3ec1300-39ff-11ea-96ad-c142c4e603ab.jpg)

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by fernandex00** [comment]
Sorry if this is out off topic, but how do you managed to match the color of the theme with your status bar?I'm om s10+ Android 10, ha 104.2, ha Android 81

**Comment by barrymossel** [comment]
> Sorry if this is out off topic, but how do you managed to match the color of the theme with your status bar?I'm om s10+ Android 10, ha 104.2, ha Android 81

Check "testing releases" and follow instructions: https://github.com/home-assistant/home-assistant-android#testing-dev-releases
