### ISSUE TITLE
External Access with NGINX and Cloudflare Maps Don't Load

### ISSUE THREAD

**Issue by glintux** [home-assistant/android#2765]
I run my setup through Cloudflare and NGINX to get external network access. Using a web browser, this works fine - everything loads successfully. But in the Android app, the maps are not loading. I think it has to do with the way the app is interpreting the domains security policy because internally it works fine when it bypasses both Cloudflare and my NGINX server. 

The following is the NGINX settings I have for the subdomain I run it through:

>     add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
>     ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
>     ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
>     ssl_prefer_server_ciphers on;
>     ssl_session_cache shared:SSL:10m;
> 
>     server_tokens off;
>     add_header X-Frame-Options SAMEORIGIN;
>     add_header X-Content-Type-Options nosniff;
>     add_header X-XSS-Protection "1; mode=block";
>     add_header Content-Security-Policy "default-src 'self'; img-src 'self' https://basemaps.cartocdn.com/; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' wss://(mysubdomain).(mydomain).org/;";
>     add_header Referrer-Policy 'origin';
> 
>     proxy_buffering off;
> 

I believe the issue is with the app because I had to modify the Content Security Policy to get it to load correctly with this: img-src 'self' https://basemaps.cartocdn.com/, but it seems the app does not read that or I am missing something else here?

I hope I am filing this correctly. Thank you!

**Comment by dshokouhi** [comment]
This sounds like a network configuration issue than an app issue. All the app does is load the URLs.

**Comment by glintux** [comment]
I was able to confirm with the chrome network browser that I had an issue with the Content Security Policy because it emitted an error about that there. Does the app store logs or connection errors that could help diagnose this?

**Comment by dshokouhi** [comment]
> Does the app store logs or connection errors that could help diagnose this?

Yes android logcat can be found in Configuration > Companion App > Show and share logs

Its best to first reproduce the issue then check the on device logs as they do not go far back.

Given that you are only seeing certain pieces of the frontend loading you may need to try Chrome Remote Debugging by first enabling Webview debugging and then following the steps here:

https://developer.chrome.com/docs/devtools/remote-debugging/

If you need to inspect the dev console you will want to follow the chrome debugging steps.

**Comment by glintux** [comment]
Okay, so that is perfect as it shows the same error I was seeing using desktop web browsers:

> Refused to load the image 'https://basemaps.cartocdn.com/rastertiles/voyager/(...)' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

However, I confirmed that this is now being set. I will do some digging, but it seems WebView is ignoring the img-src for some reason.

**Comment by glintux** [comment]
Digging further into it, I can see that new requests are pulling the correct headers but it seems the maps URL is always pulling a cached header that does not contain the updated security policy. I'm not clear if the issue is that my headers are not setting a timeout or if the app should be clearing caches in some way?

**Comment by dshokouhi** [comment]
> I'm not clear if the issue is that my headers are not setting a timeout or if the app should be clearing caches in some way?

The app respects the caching set by the HA frontend which does very heavy caching, I suggest looking into fixing things on your network first. If you changed those headers after installing the app then you may need to try clearing app cache or starting fresh to clear out any bad data that may persist.

**Comment by glintux** [comment]
Thanks! I've done some more digging and experimenting and found the following:

1. Clearing App cache does not help
2. Clearing WebView cache and data does not help
3. Clearing system cache does not help
4. Clearing Home Assistant App Data is what did it finally

At this point, on my phone, I have the new headers pulled and it is loading the Maps correctly. That said, I am concerned that cache is seemingly never cleared. I have not performed step 4 on another phone that has the old headers and am continuing to see when/if they are eventually cleared. 

It has now been almost a week, but I'm not sure if this is intended behaviors. I get the need to cache certain things, but not refreshing cache periodically is not a great design decision in general. Unless CSP on the server side should / could somehow be getting a TTL type setting that I'm missing?

As far as my network settings - it works fine on new installs and on any web browser both inside and outside my network. So it seems the issue is one of the following:
1. Home Assistant Android App header caching is too aggressive 
2. My CSP headers need a TTL type setting
3. Android Webview header caching is too aggressive 
Is there somewhere else I should be looking here?


Thank you!

**Comment by dshokouhi** [comment]
> It has now been almost a week, but I'm not sure if this is intended behaviors.

The heavy caching on the frontend is intended behavior. This is more of a HA frontend question than an app one if it feels too aggressive, we don't adjust the caching level we stick to the defaults and just load the URL in our WebView instance.

**Comment by glintux** [comment]
I see, thank you for clarifying and responding here. Should I open a ticket in the frontend repo or can this be transferred there somehow?

**Comment by dshokouhi** [comment]
> I see, thank you for clarifying and responding here. Should I open a ticket in the frontend repo or can this be transferred there somehow?

the HA frontend has a different template that gets presented when you create a new issue. Its best to provide all that info they request and you can reference this PR for additional info :)
