### ISSUE TITLE
High (mobile) data usage

### ISSUE THREAD

**Issue by Wummeke** [home-assistant/android#277]
**Home Assistant Android version:**
1.4.0(77)

**Android version:**
10

**Phone model:**
Google Pixel 3A

**Home Assistant version:**
0.104.2

**Last working Home Assistant release (if known):**

**Description of problem:**
I noticed that the app uses a lot of data when I do not actively use it. For example, my phone reports that the app has used over 1.5 GB of mobile data since 1-1. I am quite sure that I don't use the app very often when I am not connected to a WiFi network, so this high number surprises me. I suspect that it has something to do with a few camera integrations I use (I cannot think of something else, to be honest).

I thought of disabling background data, but then location tracking doesn't work anymore.

**Comment by JBassett** [comment]
I've noticed that too, for me it happened when I opened a view of the camera and didn't close it before locking the phone.  We should look into freezing the frontend when the UI isn't being displayed.

**Comment by dshokouhi** [comment]
It must be the camera not closing because when I opened my PiP bug I made sure to close the window. My data usage has been super low from the start.

![Screenshot_20200118-082312](https://user-images.githubusercontent.com/1634145/72666971-d7ce7e80-39cb-11ea-98a7-6a05aaea99e1.png)

![Screenshot_20200118-082107](https://user-images.githubusercontent.com/1634145/72666975-ddc45f80-39cb-11ea-9a68-03e95ecffa3e.png)

**Comment by balloob** [comment]
Freezing the web UI should be the way to go. This sounds like it kept streaming the camera in the background

**Comment by sverleysen** [comment]
Is it possible this issue is back again? My app used 7.45gb in a few days in the background

**Comment by JBassett** [comment]
This will be fixed with this change in the frontend: https://github.com/home-assistant/frontend/pull/6149
I'm not sure what release that fix is targeting however.

**Comment by dshokouhi** [comment]
Looks like it'll be in 0.112

**Comment by dshokouhi** [comment]
Fixed in 0.112.x

**Comment by fiLLLip** [comment]
I updated to 0.112.x when it came out. This is still a issue on the android app. The last 24 hours I have had a usage of 1.76GB in background (86MB in foreground). My solution for now is to restrict data usage in background.

**Comment by DrBlokmeister** [comment]
I also suffer from the main issue, albeit a different app

**Comment by bendikrb** [comment]
Same here... 

![Screenshot_20200809-044559_Settings](https://user-images.githubusercontent.com/152300/89723832-af57b180-d9fb-11ea-985d-3c4706bc2757.jpg)

**Comment by dshokouhi** [comment]
Check that "automatically close the connection" is enabled in your user profile in HA.

**Comment by balloob** [comment]
Please open a new issue if it still happens.
