### ISSUE TITLE
Allow changing sensor update frequency for each individual sensor or change Geocoded Location polling to update instantly

### ISSUE THREAD

**Issue by mkanet** [home-assistant/android#2770]
**Is your feature request related to a problem? Please describe.**

I noticed some mobile phones have trouble updating a 15 minute polling sensor I.E., **Geocoded Location** (for whatever reason).  The sensor will show as "Unknown" until the next polling interval...15 minutes... which isn't very useful if we actually have to depend on the data.

**Describe the solution you'd like**

Allow to change the update frequency of a specific sensor like Geocoded Location to update instantly...instead of changing the update frequency for **ALL** active sensors... which would completely drain the mobile device's battery.  

**Describe alternatives you've considered, if any**

Or, at least change the default polling interval for Geocoded Location to update instantly.
**Additional context**

**Comment by dshokouhi** [comment]
The geocoded location sensor will be updating every time the app receives a location update for the device tracker now that #2757 is merged. This is now available in the beta on Github and eventually on the play store after review.

The state of `unknown` on the geocoded sensor is actually correct. We do indeed send `unknown` during [certain situations](https://github.com/home-assistant/android/blob/master/app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt#L109).

Most sensors will update instantly if they can, sensor update frequency really only impacts poll-based sensors.

Some sensors cannot update instantly so that is not easy to do but in the case of geocoded location it is now possible.

Closing as geocoded location now updates with location tracking updates. Make sure your device tracker is properly configured to enjoy these updates.

https://companion.home-assistant.io/docs/troubleshooting/faqs/#device-tracker-is-not-updating-in-android-app

**Comment by mkanet** [comment]
Thank you so much for taking the time to answer my request so quickly.  Looking forward to seeing The enhancement from https://github.com/home-assistant/android/pull/2757 in the Google Play Store.  Do you know approximately when that might be?  I think this would really help in my case.

BTW: I'm curious if I have a phone that sometimes shows "unknown" for **ONLY** the Geocoded Location sensor while moving from one location to another, what is the most likely issue ...considering I have ready verified the below items from the link you provided?

_4. Under Configuration > Companion App > Manage Sensors ensure that the following Location Sensors are enabled: Background Location, Location Zone and Single Accurate LocationTurn on unrestricted data for the Android app. (Samsung users will need to disable data saver for Home Assistant as well.)_

Thank you so much for all your development effort and time.

**Comment by dshokouhi** [comment]
> Do you know approximately when that might be? I think this would really help in my case.

Not sure, depends on Google and the review process. Usually its fast but sometimes the review can slow things down. You are more than welcome to download the APK off the github releases tab to get the latest beta while you wait. It will install over the production version.



> BTW: I'm curious if I have a phone that sometimes shows "unknown" for **ONLY** the Geocoded Location sensor while moving from one location to another, what is the most likely issue ...considering I have ready verified the below items from the link you provided?

Quite simple, the API does not return a `address` which is used for the state. Nothing you are doing wrong just how the API works. More of a google question than an app question at this point.

https://developer.android.com/reference/android/location/Address#getAddressLine(int)

`Returns a line of the address numbered by the given index (starting at 0), or null if no such line is present.`

**Comment by mkanet** [comment]
Thanks again! I think i can wait if it's the Play Store version will be available in the next month or so.  But,.in case I don't want to wait, if I install the latest beta over the Production version, will the upcoming Production version  automatically install over the beta version?

**Comment by dshokouhi** [comment]
yes you will always get the latest version in the play store

**Comment by mkanet** [comment]
@dshokouhi 

My apologies for bugging you about this.  I successfully upgraded to the beta mobile app on all my mobile devices per your suggestion.  

Just to clarify, Google Maps **is** able to consistently display the correct/precise location for all my mobile devices via the mobile devices' location services.  However, fairly frequently, Home Assistant Companion will simultaneously display "UNKNOWN" for its respective geocoded location sensor on the same devices.  

Is there anything I can do to force the API (or Home Assistant Companion) to clear whatever is stuck; and try acquiring this data from the API again from scratch (clearing any temporary caches)?  I'm not sure why the mobile devices' location services consistently have the correct latitude/longitude; however, the API doesn't seem to offer this information relatively frequently; it's hit or miss.

> > BTW: I'm curious if I have a phone that sometimes shows "unknown" for **ONLY** the Geocoded Location sensor while moving from one location to another, what is the most likely issue ...considering I have ready verified the below items from the link you provided?
> 
> Quite simple, the API does not return a `address` which is used for the state. Nothing you are doing wrong just how the API works. More of a google question than an app question at this point.
> 
> https://developer.android.com/reference/android/location/Address#getAddressLine(int)
> 
> `Returns a line of the address numbered by the given index (starting at 0), or null if no such line is present.`

**Comment by mkanet** [comment]
@dshokouhi 

My apologies for bugging you about this.  I successfully upgraded to the beta mobile app on all my mobile devices per your suggestion.  Just to clarify, Google Maps **is** able to consistently display the correct/precise location for all my mobile devices via the mobile devices' location services.  However, fairly frequently, Home Assistant Companion will simultaneously display "UNKNOWN" for its respective geocoded location sensor on the same device.  

Is there anything I can do to force the API (or Home Assistant Companion) to clear whatever is stuck; and try acquiring this data from the API again from scratch (clearing any temporary caches)?  I'm not sure why the mobile devices' location services have the correct latitude/longitude; however, the API doesn't seem to sometimes offer this information.

> > BTW: I'm curious if I have a phone that sometimes shows "unknown" for **ONLY** the Geocoded Location sensor while moving from one location to another, what is the most likely issue ...considering I have ready verified the below items from the link you provided?
> 
> Quite simple, the API does not return a `address` which is used for the state. Nothing you are doing wrong just how the API works. More of a google question than an app question at this point.
> 
> https://developer.android.com/reference/android/location/Address#getAddressLine(int)
> 
> `Returns a line of the address numbered by the given index (starting at 0), or null if no such line is present.`

**Comment by dshokouhi** [comment]
There is nothing for you to do. Not all coordinates will have an address. Google even mentions this in developer documentation. `unknown` is simply the result of the API.
