### ISSUE TITLE
App crashes on remembering iframe logins

### ISSUE THREAD

**Issue by konscii** [home-assistant/android#2775]
Using an iframe http:// tab to a webui on lan ip with username and password (tried tvheadend and 2 kodi installs): I can login without saving info, but checking the "remember" box crashes app reliably after hitting Ok. Home Assistant log doesn't see the event, and I'm unsure if this is an issue the app itself, or some backend.
If it just can't (because it's http, not https), a warning, or greyed-out / removed remember box would be clearer. On linux, chromium doesn't offer the option of saving login details.
Android app from Play Store, version 2022.6.0-full.  
Home Assistant 2022.8.2, Supervisor 2022.07.0, Operating System 8.4, Frontend 20220802.0 - latest

**Comment by jpelgrom** [comment]
> On linux, chromium doesn't offer the option of saving login details.

To clarify, is this a remember checkbox on the page itself, or some popup you get? If it is on the page I don't quite understand why it doesn't always show up. A screenshot would be helpful.

**Comment by konscii** [comment]
@jpelgrom - It's the same standard popup for all iframe logins. Kodi and tvheadend have the same identical popup. I would have assumed it was something the app was generating.
![Screenshot_2022-08-08-18-04-23](https://user-images.githubusercontent.com/97887088/183524005-0f7d6d97-7fd7-4853-8cc5-37b821ae248c.png)
@dshokouhi - Sorry, I still don't see your issue template, but I'm new to github. Here's the [companion log](https://github.com/home-assistant/android/files/9285331/homeassistant_companion_log_7-8-2022_18-12-29.txt) - the home assistant log has no record of the event, or anything near that timeframe. Please let me know if I didn't submit something correctly. Thanks!

**Comment by dshokouhi** [comment]
I am seeing some API errors for the webkit which shouldnt happen and are out of our apps control 

```
08-08 18:08:48.456 16088 16088 I zygote64: Rejecting re-init on previously-failed class java.lang.Class<br2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
```

I see the device is using Chrome instead of WebView

```
08-08 18:08:50.656 16088 16088 D WebviewActivity: Current webview package com.android.chrome and version 103.0.5060.129
```

You didn't by chance disable webview? I know some devices have it disabled by default (which is ok in those cases) but if a user disables it then that can cause issues.

I am also seeing play services errors.

```
08-08 18:08:51.397 16088 16088 E ActivitySM: Failed to register for sleep updates
08-08 18:08:51.397 16088 16088 E ActivitySM: com.google.android.gms.common.api.ApiException: 16: 
```

Is the device running a custom ROM? Try checking for device and/or app updates to make sure things like Chrome and everything else are up to date.

**Comment by konscii** [comment]
Thanks! I haven't disabled webview, and am not using a custom rom (although it does seem like webview is disabled?).. It's clearly something on my end, though, so I won't drag it out. I'll close this, and figure out what's going on with my phone. Cheers
