### ISSUE TITLE
Could we get a sensor to indicate fast-charge v normal charge

### ISSUE THREAD

**Issue by kenguest** [home-assistant/android#2796]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be useful if the android app could report whether a phone is charging over a fast-charge connection.
Use cases are for presence detection (only fast charger is in the home office, standard chargers elsewhere), and can also indicate if a fast-charge cable is worn out and only delivering a standard charge.

The entity could be sensor.<phone_name>_is_fast_charge (=0/1)

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
Looks like in this case we need to look at the current supplied to `BatteryManager` this means the sensor will not be instant, but when paired with any other battery sensor it should basically be instant.  Here is a stackoverflow post I found describing how to achieve this.

https://stackoverflow.com/questions/38912585/how-to-test-battery-charging-speed

If we do add this it will probably just be a raw value so the user can make their own decision. Seems there is no direct API to determine if fast charging or not. Will the raw value be helpful to you?

In my own personal setup I use a wireless charger in the bedroom and that helps me differentiate between my other chargers because of the `charger_type` sensor

**Comment by dshokouhi** [comment]
We might be able to cheat and decipher fast charging using a native API that tells us how much longer to charge the device? 😂 

https://developer.android.com/reference/android/os/BatteryManager#computeChargeTimeRemaining()

**Comment by jpelgrom** [comment]
> We might be able to cheat and decipher fast charging using a native API that tells us how much longer to charge the device? 😂 

This might be unreliable because 'fast' charging usually slows down when charging is closer to 100%.

**Comment by dshokouhi** [comment]
> This might be unreliable because 'fast' charging usually slows down when charging is closer to 100%.

in that case then even going by the `current` will not suffice right?

https://developer.android.com/reference/android/os/BatteryManager#BATTERY_PROPERTY_CURRENT_NOW

**Comment by jpelgrom** [comment]
I don't know what exactly decreases (volts or amperes), sounds like something to experiment with 🙂. It also might be worth it to look at the AOSP source to find out how it determines the 'fast charging'/'charging'/'charging slowly' text on the lock screen - it will probably not cover OEM-specific fast charging but it is a good starting point.

**Comment by dshokouhi** [comment]
looks like they go by wattage, so both LOL. At least thats what this led me to when I found the string `battery_info_status_charging_fast`

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/packages/SettingsLib/src/com/android/settingslib/fuelgauge/BatteryStatus.java;drc=2d579af880afae96239c80765b11c7dbc2c1b264;l=83

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/packages/SettingsLib/src/com/android/settingslib/fuelgauge/BatteryStatus.java;drc=2d579af880afae96239c80765b11c7dbc2c1b264;l=159

**Comment by jpelgrom** [comment]
Code comments say:

```
     * Threshold in micro watts above which a charger is rated as "fast"; 1.5A @ 5V
```

 and

```
     * Threshold in micro watts below which a charger is rated as "slow"; 1A @ 5V
```

Which sounds quite low, 7.5W is something most chargers will provide? 

I feel like it may be best if we can supply voltage/amperage/wattage in a sensor (perhaps as an attribute?), and let the user decide for themselves if it is fast or not.

**Comment by dshokouhi** [comment]
> I feel like it may be best if we can supply voltage/amperage/wattage in a sensor

I think we can get away with 1 sensor whose state is `wattage` and attributes are `voltage` and `amperage`  I think its ok to add 1 battery sensor which increases our default. The sensor won't update immediately but should be good enough given our battery intents.


> (perhaps as an attribute?)

Not sure which battery sensor state it would be describing 🤔 



> and let the user decide for themselves if it is fast or not.

I agree let them figure out how to proceed with the supplied data

**Comment by dshokouhi** [comment]
its a good thing we found this code anyways since it seems some of the `EXTRAS_*` are not documented so we have all the data we need to replicate it. Great suggestion as usual @jpelgrom 😃
