### ISSUE TITLE
Android TV D-pad not working

### ISSUE THREAD

**Issue by wrt54g** [home-assistant/android#2803]
**Home Assistant Android version:**
2022.6.0
**Android version:**
Android TV 9.0
**Phone model:**
Xiaomi Mi TV P1 32 inch
**Home Assistant version:**
2022.8.5
**Last working Home Assistant release (if known):**

**Description of problem:**
When I plug in a mouse to the TV usb port, the app works fine. But it does not work with the D-pad on the remote control. Every other feature works.
The APK file is sideloaded since there is no play store app available for the mi tv.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Sorry android TV is not supported, there are some workarounds but thats about it. The HA frontend is not optimized for D-pad navigation either. The HA frontend needs to support that interface before the app can.
