### ISSUE TITLE
screen brightness control

### ISSUE THREAD

**Issue by gmcaesar** [home-assistant/android#2816]
**Is your feature request related to a problem? Please describe.**

I can control so much of the phone through notification but not the brightness

**Describe the solution you'd like**

command notification to turn on and off auto brightness and one to set the brightness %

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
I believe the permission required here is a protected permission that the app may not qualify for.

**Comment by gmcaesar** [comment]
could it not be a permissions request? i know I can do it with other apps, but i'd rather not send mqtt to automate and send control notifications

**Comment by gmcaesar** [comment]
opps accidently closed.... but could this not be added with a permission request? i know I can give admin permissions to apps, I just would rather not have to send mqtt to automate and control notifications to the companion when one app could do it all

**Comment by dshokouhi** [comment]
this is what I meant

![image](https://user-images.githubusercontent.com/1634145/189234111-7aab8abd-994c-4e7d-a465-7cac79debd3d.png)

We may not qualify for it given that we do not qualify for things related to the phone call log and SMS sending etc...

We can keep this open for now but it is indeed a protected permission.

**Comment by marazmarci** [comment]
I think this functionality can be hacked together with Tasker 🙂
You can send an Intent with the `command_broadcast_intent` notification command (with the desired brightness included as an extra), and catch it in Tasker using its `Intent Received` event handler, then use the `Display Brightness` action.

**Comment by dshokouhi** [comment]
> I think this functionality can be hacked together with Tasker 🙂 You can send an Intent with the `command_broadcast_intent` notification command (with the desired brightness included as an extra), and catch it in Tasker using its `Intent Received` event handler, then use the `Display Brightness` action.

Yea this would be a valid workaround if we don't qualify for the permission, its still worth it to give it a shot I think. IMO our app should qualify for all permissions that tasker qualifies for but unfortunately that was not the case when we tried to add the last caller sensor.
