### ISSUE TITLE
Language issue in latest app update

### ISSUE THREAD

**Issue by gsolem** [home-assistant/android#2821]
**Home Assistant Android version:**
2022.8.0

**Android version:**
12

**Phone model:**
Asus ZenFone 8 

**Home Assistant version:**
2022.8.6

**Last working Home Assistant release (if known):**
2022.8.6

**Description of problem:**
Funny language for selected options in last HA Android app update. See enclosed example. This also goes for copy/paste menu.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20220826-111953276](https://user-images.githubusercontent.com/15731163/186872850-fa113f95-1dcd-42ba-baa4-e383fd370dbc.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
Strange I also see this but I don't see this string "Khansela" on Lokalise or even in our project. Where is it coming from? Looks like this word means "Cancel" in Zulu but we don't even have that language on Lokalise. 🤔 

BTW you may want to consider enabling background access in case you noticed things not updating as they should be like sensor updates and what not when the app is in the background.

**Comment by gsolem** [comment]
![Screenshot_20220826-160130707_1](https://user-images.githubusercontent.com/15731163/186921361-6fca6fb0-e268-4fcd-b7c7-8418c4290c7d.jpg)

![Screenshot_20220826-160128107_1](https://user-images.githubusercontent.com/15731163/186921388-87590faf-2211-4b03-9015-3f90dd62817b.jpg)

**Comment by dshokouhi** [comment]
Now try to edit your `Home Assistant URL` does it look correct to you? Because as soon as I viewed that pop-up the others showed the correct language 🤔 🤯 

After doing those steps I can no longer reproduce the issue, even if I force stop the app. Seems like some odd caching occured?

**Comment by jpelgrom** [comment]
> Strange I also see this but I don't see this string "Khansela" on Lokalise or even in our project. Where is it coming from? Looks like this word means "Cancel" in Zulu but we don't even have that language on Lokalise. 🤔

Both of the dialogs in the screenshots are managed by the system (`PreferenceFragment` items that show dialogs), and the text selection menu is also system-managed, so it's probably using the device's translation

**Comment by gsolem** [comment]
That is strange, because my device language is English. My HA URL is also correct as I see it.

**Comment by jpelgrom** [comment]
Sorry for any confusion - I wasn't suggesting that your device is set to Zulu, just trying to explain where the strings might come from ☺️

**Comment by dshokouhi** [comment]
> My HA URL is also correct as I see it.

Oh I didn't mean the URL itself I meant that when I viewed the URL by selecting it the prompt ended up showing the correct translation. Then at that point all the other translations were correct.

**Comment by gsolem** [comment]
Ah ok, understand. No, I am not using Zulu as my device language :)

**Comment by ciltocruz** [comment]
Same for me. Since Last update (yesterday)

**Comment by dshokouhi** [comment]
I am not sure this is something the app can fix as we don't provide those translations. Seems like this might be an issue in some dependency provided by Google that was updated in the recent release.

**Comment by joshuaspence** [comment]
I'm seeing the same issue on Android 13

**Comment by illie0** [comment]
Yep, same issue on a Pixel 6 running Android 13 with HA App 2022.10.2-full. Language set to English in HA user profile, and HA Companion App. Android OS language is English (Canada). This Zulu only appears in text edit dialogs for the HA app.
