### ISSUE TITLE
command_dnd broken: notification instead of changing DND setting

### ISSUE THREAD

**Issue by gitawayu** [home-assistant/android#2826]
Home Assistant on my Android phone was updated to "Version 22.08 - Phone".

When my automation sent command_dnd off, or command_dnd priority_only, *before* this update, my Android device would switch the Do Not Disturb (DND) setting according to the command.

Now, after the update, my Android device does not change the DND setting.  Instead I just get a notification on my phone that says:

off
command_dnd

or:-

priority_only
command_dnd

I am not aware of any changes to any parts of the system, other than the Companion App update, which happened automatically overnight.

**Comment by dshokouhi** [comment]
The format has changed in the recent update. This was also mentioned in the change log prompt as a breaking change. Please refer to the documentation for updated format

https://companion.home-assistant.io/docs/notifications/notification-commands#do-not-disturb
