### ISSUE TITLE
Optical tile feedback Wear OS

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/android#2827]
Good morning,
I just received my Galaxy 5 Pro and immediately installed Home Assistant :)

What I noticed is that the tiles do not give any feedback. So if I trigger a remote action, si do not see that I triggered it. 
Would it be possible to change the color/flash the tile for a second so I can see that the command was sent?

E.g. if I am not in my home network, the button will not trigger and since there is no color change or notification, the status remains unknown.

Thank you for your consideration :)

Alex

**Comment by dshokouhi** [comment]
You can go into settings in the app and enable haptic feedback and/or toast notifications for confirmation.

**Comment by AleXSR700** [comment]
After eneabling Toast Notifications I see nothing.
Haptic feedback works but it gives feedback whether the task was successful or not.
E.g. if I am outside the reach of my wifi (e.g. certain parts of the garden) then the tile vibrates but nothing happens.

On Android OS I get a notification if it fails.

**Comment by dshokouhi** [comment]
Oh I see then this is a duplicate of either #2687 or #2045

**Comment by AleXSR700** [comment]
Hmmmm, not sure I would have directly seen it as such, but it is probably related :)
