### ISSUE TITLE
Is the upgrade to SDK #26 necessary on WearOS ?

### ISSUE THREAD

**Issue by docgalaxyblock** [home-assistant/android#2833]
Greetings, I own some older WearOS based smartwatches.

Is the switch to SDK 26 necessary or could you still get everything to work with SDK 25?

I have a Huawei Watch gen 1 codename sturgeon, two Moto360 gen 2 codename carp/smelt, a ASUS ZenWatch 2 codename wren/sparrow and a special watch named LG Watch W7 is on the wishlist.

All of my and many other watches based on eg the Snapdragon wear 400 are incompatible with the latest 2022.8.0 update since they only run Android 7.1.1

I would love if you all could still support these great *bang for the buck* smartwatches

*I consider this more as a feature request then a bug report*

Have a nice day 👋🇩🇪

```
root@test:~# adb push home-assistant-wear-2022.8.0.apk /sdcard/app.apk && adb shell pm install /sdcard/app.apk
AsteroidOS/home-assistant-wear-2022.8.0.apk: 1 file pushed. 3.7 MB/s (14874341 bytes in 3.793s)
Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl827038902.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #26 (current version is #25)]
```

**Comment by jpelgrom** [comment]
I'm afraid this is currently a requirement due to the complications support. I don't think we can make this optional / not support complications on SDK 25. Almost all the watches you mention are 5+ years old at this point so I'm not sure this is feasible to support or drop a feature for. @leroyboerefijn Do you have any more insight?

**Comment by leroyboerefijn** [comment]
If i remember correctly, we have at least two libraries requiring SDK 26 (complications and tiles?). Though I have to say, I'm not sure if it's possible to work around it by only requiring SDK 26 for parts that use it, never looked into that before

**Comment by docgalaxyblock** [comment]
That sound not great ...
As an idea: Are those libs required by the wear companion and the phone companion or only by the phone one

Unfortunately something like LineageWear does not exist ... - even my galaxy s5 has android 11 that way.

**Comment by jpelgrom** [comment]
It's a requirement for libraries specific to the Wear app - the phone app currently has a minimum SDK of 21

**Comment by dshokouhi** [comment]
You could just use older versions of the app, they will still work. If you want to enjoy new features then you'll need to upgrade the device. It does not make sense to support multiple versions of the app. The app is open source so you can always modify a fork if you want.

**Comment by dshokouhi** [comment]
> So, I also have an older watch that I use. How do I find the last wear apk that is SDK 25? Is it in this repository?
> 
> Thanks!

i believe the google play store will give what version is available for your device, but yes it will exist in this repo too.

**Comment by backcountrymountains** [comment]
Yes but how do I search for the latest SDK 25 wear app in this repo? The first post said that 2022.8.0 didn't work, so is 2022.6.0 the last SDK 25?

Thanks

**Comment by dshokouhi** [comment]
yes 2022.6.0 is on SDK 25, any beta version before #1898 was merged will work as well
