### ISSUE TITLE
command_media notifications not working on 22.8.0

### ISSUE THREAD

**Issue by lordsnipe1** [home-assistant/android#2834]
Home Assistant Android version: 22.8.0

Phone model: Samsung Galaxy S8+

Home Assistant version: 22.8.7

Description of problem: Sending a command_media notification from the HA Server to the HA Companion App with the changed message format does not work for me (the notification appears on the phone as a normal notification, no action is performed). I have tried to use both device notification actions and the notification service (which is the example used in the HA documentation), both result in the same notification message being sent to the phone, and both are logged as invalid.

The previous HA companion app and old message structure worked fine with the device notification action until this latest update.

**Device notification action:**
device_id: xxxxx
domain: mobile_app
type: notify
message: command_media
data:
  media_command: next
  media_package_name: com.kodarkooperativet.blackplayerex

**Service notification action:**
service: notify.mobile_app_XXXXX
data:
  message: command_media
  data:
    media_command: next
    media_package_name: com.kodarkooperativet.blackplayerex

Home Assistant log (bolded lines of relevance):
**08-30 16:39:04.965 21443 21524 D WebSocketRepository: Message number 1 received: {"id":1,"type":"event","event":{"message":"command_media","data":{"media_command":"next","media_package_name":"com.kodarkooperativet.blackplayerex"},"hass_confirm_id":"XXXX"}}**
08-30 16:39:04.965 21443 21524 D WebSocketRepository: Websocket: onMessage (text)
**08-30 16:39:04.966 21443 21524 D WebSocketRepository: Message number 1 received: {"id":1,"type":"event","event":{"message":"command_media","data":{"media_command":"next","media_package_name":"com.kodarkooperativet.blackplayerex"},"hass_confirm_id":"YYYY"}}**
08-30 16:39:04.967 21443 21560 D WebSocketRepository: Sending message 3002: {type=mobile_app/push_notification_confirm, webhook_id=ZZZZ, confirm_id=XXXX, id=3002}
08-30 16:39:04.968 21443 21560 D WebSocketRepository: Message number 3002 sent
08-30 16:39:04.972 21443 21524 D WebSocketRepository: Websocket: onMessage (text)
08-30 16:39:04.972 21443 21524 D WebSocketRepository: Message number 3002 received: {"id":3002,"type":"result","success":true,"result":null}
08-30 16:39:04.974 21443 21474 D MessagingService: Processing device command
08-30 16:39:04.975 21443 21474 D WebSocketRepository: Sending message 3003: {type=mobile_app/push_notification_confirm, webhook_id=ZZZZ, confirm_id=YYYY, id=3003}
08-30 16:39:04.975 21443 21474 D WebSocketRepository: Message number 3003 sent
08-30 16:39:04.977 21443 21443 D UrlRepository: localUrl is: false and usesInternalSsid is: false
**08-30 16:39:04.979 21443 21443 D MessagingService: Invalid media command received, posting notification to device**
08-30 16:39:04.980 21443 21524 D WebSocketRepository: Websocket: onMessage (text)
08-30 16:39:04.985 21443 21524 D WebSocketRepository: Message number 3003 received: {"id":3003,"type":"result","success":true,"result":null}
08-30 16:39:04.988 21443 21443 D MessagingService: Show notification with tag "null" and id "-303598573"
08-30 16:39:04.988 21443 21474 D MessagingService: Processing device command
08-30 16:39:04.991 21443 21443 D UrlRepository: localUrl is: false and usesInternalSsid is: false
**08-30 16:39:04.993 21443 21443 D MessagingService: Invalid media command received, posting notification to device**
08-30 16:39:04.999 21443 21443 D MessagingService: Show notification with tag "null" and id "-303598559"

**Comment by dshokouhi** [comment]
Not near a computer to submit a PR but looks like there was a mistype in the first condition for this command where `command` was expected but later on we look for `media_command` which is what was documented. 🤦‍♂️

**Comment by jpelgrom** [comment]
@lordsnipe1 Workaround for now: if you include `command: x` where `x` is the same as your `media_command` in the notification data it should work again. Full example:

```
service: notify.mobile_app_XXXXX
data:
  message: command_media
  data:
    command: next
    media_command: next
    media_package_name: com.mediaplayer
```

**Comment by lordsnipe1** [comment]
> @lordsnipe1 Workaround for now: if you include `command: x` where `x` is the same as your `media_command` in the notification data it should work again. Full example:
> 
Thanks @jpelgrom, I will give this a try.

**Comment by ScottG489** [comment]
For anyone else also experiencing this for `command_bluetooth`, `title` was replaced with `command`. 

In my case my original data request looked like this:
```yaml
message: command_bluetooth
title: turn_off
```
And applying the same fix above for my request now looks like this:
```yaml
message: command_bluetooth
data:
  command: turn_off
```
And this seemed to do the trick.

This change is documented [here](https://companion.home-assistant.io/docs/notifications/notification-commands/#bluetooth).

However, I didn't see this in the [full release changelog](https://github.com/home-assistant/android/releases/tag/2022.8.0). 

Was it missed being added there or is there a better place I can go to see changes? I read over the HA changes every release and try to do the same for the companion app so I don't miss stuff like this, so I just want to make sure :)

**Comment by lordsnipe1** [comment]
It's part of "Breaking Change: Switch notification command parameters by @dshokouhi" in https://github.com/home-assistant/android/pull/1759

**Comment by dshokouhi** [comment]
> Was it missed being added there or is there a better place I can go to see changes? I read over the HA changes every release and try to do the same for the companion app so I don't miss stuff like this, so I just want to make sure :)

as soon as you open the app there is a changelog prompt, it was also mentioned in there that the commands were all updated.

**Comment by ScottG489** [comment]
Yeah just saw some of my other ones broke. I was looking for the BT command specifically, but I see now it's that all of them were updated. I think I missed it reading over the full changelog, but as you said, the in app one looks like it has a more concise list, so I'll be sure to check out first next time :) Thanks!
