### ISSUE TITLE
command_ble_transmitter stopped working!

### ISSUE THREAD

**Issue by garv3** [home-assistant/android#2840]
**Home Assistant Android version:**
2022.8.0-full

**Android version:**
10 QKQ1.190828.002

**Phone model:**
Xiaomi Mi Mix 3

**Home Assistant version:**
2022.8.7

**Last working Home Assistant release (if known):**
2022.8.x

**Description of problem:**
When sending a notification with the title "turn_on" or "turn_off" and the message "command_ble_transmitter", the message is shown on the phone instead of the BLE transmitter being turned on or off. This happens since the last Android app update which made some other breaking changes to the notify workflow.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
n.a.

**Screenshot of problem:**
n.a.

**Additional information:**
Not sure if the same problem exists for other notification commands listed here:
https://companion.home-assistant.io/docs/notifications/notification-commands

**Comment by garv3** [comment]
Never mind. Just found that the documentation for this command changed in the example. Did not see any mentioning of the breaking change though.

**Comment by jpelgrom** [comment]
After updating there should have been a dialog when opening the app that mentioned the breaking change. Good to hear you found the updated documentation anyway!
