### ISSUE TITLE
Android Shortcut opens new app instance/refreshes UI when opening

### ISSUE THREAD

**Issue by johannes-z** [home-assistant/android#2843]
**Home Assistant Android version:** 2022.8.0-full

**Android version:** Android 12 / LineageOS 18.1

**Phone model:** Xiaomi Mi Mix 2s

**Home Assistant version:** 2022.08.5

**Last working Home Assistant release (if known):** -

**Description of problem:** Sometimes I check Developer Tools or other pages in the app, but it's quite a hassle to get back to the home screen - sometimes I need to go there **fast** to turn off/turn on stuff.
So I created a Shortcut to the home view of my Home Assistant (`/lovelace`, also tried `/lovelace/home`). Whenever I press the shortcut, it takes quite a long time to open the page and I can see the page flash. It looks like the whole page is completely loaded from scratch. When opening the app normally (without shortcuts) multiple times, it doesn't fully reload the page.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:** The reloading looks like it would on desktop when you press ctrl+f5

**Comment by dshokouhi** [comment]
This is intended behavior for shortcuts to work reliably.
