### ISSUE TITLE
Please give widgets the ability to make 2 service calls.

### ISSUE THREAD

**Issue by mattlward** [home-assistant/android#2845]
**Is your feature request related to a problem? Please describe.**

Again, kind of.  When controlling my main tv and receiver there are occasions where it would be very nice to make 2 service calls.  For example change the receiver input and the tv input for a given source.  Another case would be to change the receiver input to a game console input and also bump the volume down because the console outputs a much higher level than my other sources.   

**Describe the solution you'd like**

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
Why don't you just use a script that houses both service calls?

**Comment by mattlward** [comment]
Honestly... I have been running HA for several years and am fairly good at complex automations, but I really suck at templates and scripts because I am not a coder.  I know, but at 57 years old with 2 kids and other family and a full time job I have not had time or energy to learn scripting.  Sounds lazy, maybe is... but such is life.

**Comment by dshokouhi** [comment]
When I say script, I meant:

https://www.home-assistant.io/integrations/script/

**Comment by mattlward** [comment]
And I have avoided these for years... why?  I love writing automations using the choose actions... I am going to have to give this some thought.  Thanks for the tip!

I do still think that due to the simple nature of the widgets, this would still see good use by many people that might otherwise not make as much use of HA.

**Comment by mattlward** [comment]
> When I say script, I meant:
> 
> https://www.home-assistant.io/integrations/script/
> 
> Edit: think of scripts like the action sequence of an automation. You can also add conditions etc...

I am trying my hand at the script, but I am having serious problems with a template error.  If possible, could you please review this post and see if you can spot what I am doing wrong?
[https://community.home-assistant.io/t/could-really-use-some-help-with-a-script-that-uses-an-is-state-attr-template/456726](url)

Thanks Matt

**Comment by mattlward** [comment]
Nevermind... someone replied on the forum and I have it working!!!

**Comment by dshokouhi** [comment]
Going to close this request as the correct approach is to use a script to house multiple service calls
