### ISSUE TITLE
Wear os companion areas and domains wont load anything

### ISSUE THREAD

**Issue by blair287** [home-assistant/android#2858]
Running latest beta home assistant wear os app will show favorites fine but when opening the chips for areas or domains like light they just show a black screen with the name and no entities unable to scroll or do anything other than go back.

All entities shows everything OK and works.

![20220906_073937](https://user-images.githubusercontent.com/44187409/188564575-8a6825d5-6263-4c21-a88f-459361ed8adb.jpg)
![20220906_073927](https://user-images.githubusercontent.com/44187409/188564586-8c0a05db-c480-4d25-aa95-ea33126d6e7a.jpg)

**Comment by HunterX86** [comment]
I suffer from that too. It happened yesterday after i updated the galaxy watch 4 to One UI 4.5, Wear OS 3.5 . There may not be support for that yet.

**Comment by HunterX86** [comment]
@blair287 please add the label "wearos" and "bug" to the issue.

**Comment by jpelgrom** [comment]
Could you grab the bug report template from a new issue, add it here and fill it in? That provides some useful info that might help solve the issue, like app and Home Assistant version. 

> I can confirm that. It happened yesterday after i updated the galaxy watch 4 to Wear OS 3.5 with One UI 4.5 . There may not be support for that yet.

The app shouldn't have to do anything special to support Samsung's latest software. Did you perhaps also update the app and/or Home Assistant around the same time?

**Comment by HunterX86** [comment]
**Home Assistant Android version:**
beta-2676-45cdaeb7

**Android version:**
12

**Watch model:**
Galaxy Watch 4
WearOS 3.5
OneUI 4.5

**Home Assistant WearOS version:**
beta-2676-45cdaeb7

**Last working WearOS version (if known):**
WearOS 3.2
OneUI 4.0

**Description of problem:**
> Running latest beta home assistant wear os app will show favorites fine but when opening the chips for areas or domains like light they just show a black screen with the name and no entities unable to scroll or do anything other than go back.
All entities shows everything OK and works.

**Comment by dshokouhi** [comment]
are you able to get us the on device logs by any chance? You'll need to use ADB to pull them, might be easier with android studio if you have that setup already.

**Comment by HunterX86** [comment]
W/System: A resource failed to call release. 
I/SurfaceFlinger: id=3012 Removed Surface(name=9b07acf InputMethod)/@0x20e003a - animation-leash#0 (45)

**Comment by HunterX86** [comment]
there is nothing else strange to see in the logs

**Comment by dshokouhi** [comment]
ok I see the same behavior in Beta 2646 from the play store, there are also no logs being shown in my case as well. Thanks for confirming.

**Comment by jpelgrom** [comment]
This appears to be a side effect of recent changes that collapse lists by default to make using the app easier if you have lots of entities, except in this screen the app will not use a collapsible header if there's only one list which means you can't 'open it':
https://github.com/home-assistant/android/blob/45cdaeb7646c73afce48c01f42d81470bc96b259/wear/src/main/java/io/homeassistant/companion/android/home/views/EntityListView.kt#L44-L52

I've submitted a PR to fix this and 'open' these lists, sorry!
