### ISSUE TITLE
Add back button to the "history" and "logbook" page.

### ISSUE THREAD

**Issue by HunterX86** [home-assistant/android#2863]
**Is your feature request related to a problem? Please describe.**
There is no back button on the history and logbook page.
Both on the website and in the app.

**Describe the solution you'd like**
Add a back button to the "history" and "logbook" page so that you can navigate back to the previous page.

**Describe alternatives you've considered, if any**
n/a

**Additional context**

![Schermafbeelding 2022-09-07 142452](https://user-images.githubusercontent.com/1310016/188886014-6d1ee3ea-00de-4967-8ff9-63b124efe282.png)
![Schermafbeelding 2022-09-07 142603](https://user-images.githubusercontent.com/1310016/188886022-ff797b84-645f-4dd8-8948-2783d162622c.png)

**Comment by HunterX86** [comment]
> The app does not control these screens, only the HA frontend does.

I know that, but if you look at these 2 pages in the app, i got the option to open the menu.
And not go back to the previous page with a back button.

**Comment by dshokouhi** [comment]
> > The app does not control these screens, only the HA frontend does.
> 
> I know that, but if you look at these 2 pages in the app, i got the option to open the menu. And not go back to the previous page with a back button.

That is still out of the apps control, we don't control the frontend we just display it.  Please open a request with the HA frontend for this.

**Comment by jpelgrom** [comment]
Also if you're using Android, you should be able to use the system back button 😉

**Comment by HunterX86** [comment]
> Also if you're using Android, you should be able to use the system back button 😜😉

I already know that 😜
