### ISSUE TITLE
Huawei: App crashes when you enter homeassitant instance. (wear os)

### ISSUE THREAD

**Issue by jaanusmiemis** [home-assistant/android#2873]
PS! It is a Huawei watch 3 pro - So if it is not relevant then please close this issue.

**Home Assistant Android version:**
Latest
**Android version:**
Harmony OS 2.1
**Phone model:**
Huawei Watch 3
**Home Assistant version:**
Latest
**Last working Home Assistant release (if known):**

**Description of problem:**

When you start the app first time then it gives the option to select your Homeassitant server or enter it manually. 

After selecting (and also entering manually) Application crashes.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

**_Logs from the device are added to google drive: [drive link]_**(https://drive.google.com/file/d/1bnr4PaCWEpmecYpxHeG09EzDTKm2xNA6/view?usp=sharing)

**Comment by dshokouhi** [comment]
Harmony OS is not Wear OS 2.0+ right? It seems to be its own thing

**Comment by dshokouhi** [comment]
```
09-10 16:45:10.768  9255  9255 E AndroidRuntime: FATAL EXCEPTION: main
09-10 16:45:10.768  9255  9255 E AndroidRuntime: Process: io.homeassistant.companion.android.minimal, PID: 9255
09-10 16:45:10.768  9255  9255 E AndroidRuntime: android.view.InflateException: Binary XML file line #2 in 
```

looks like you did not install the watch app on this device, but the minimal version which is alos not correct. Were you unable to install the wear OS from the play store?

**Comment by jaanusmiemis** [comment]
> Harmony OS is not Wear OS 2.0+ right? It seems to be its own thing

Right thats totaly different thing.

HarmonyOS is basicly huawei android these days.

**Comment by jaanusmiemis** [comment]
> ```
> 09-10 16:45:10.768  9255  9255 E AndroidRuntime: FATAL EXCEPTION: main
> 09-10 16:45:10.768  9255  9255 E AndroidRuntime: Process: io.homeassistant.companion.android.minimal, PID: 9255
> 09-10 16:45:10.768  9255  9255 E AndroidRuntime: android.view.InflateException: Binary XML file line #2 in 
> ```
> 
> looks like you did not install the watch app on this device, but the minimal version which is alos not correct. Were you unable to install the wear OS from the play store?

Hmm so i failed. No playstore for huawei (USA and china thing). Could you be so kind and share the right APK with me?

**Comment by dshokouhi** [comment]
> Hmm so i failed. No playstore for huawei (USA and china thing). Could you be so kind and share the right APK with me?

go to the github release tab and grab the APK that has `wear` in the  title

here is the latest published release

https://github.com/home-assistant/android/releases/download/2022.8.0/home-assistant-wear-2022.8.0.apk

**Comment by jaanusmiemis** [comment]
> > Hmm so i failed. No playstore for huawei (USA and china thing). Could you be so kind and share the right APK with me?
> 
> go to the github release tab and grab the APK that has `wear` in the title
> 
> here is the latest published release
> 
> https://github.com/home-assistant/android/releases/download/2022.8.0/home-assistant-wear-2022.8.0.apk

Thankyou for APK.
geting error on installing, but while it is HarmonyOS and not WearOS then i will close this "BUG" while it is not an bug :)

error that harmonyOS is geting (Probably related with sanctions that Huawei has): 

adb install hswear.apk
adb: failed to install hswear.apk: Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY: Reconciliation failed...: Reconcile failed: Package io.homeassistant.companion.android requires unavailable shared library com.google.android.wearable; failing!]

**Comment by jaanusmiemis** [comment]
No Bug, had wrong APK and isssue is related with Huawei itself.

**Comment by NaZawsze** [comment]
Home Assistant Android version:
Latest
Android version:
ColorOS(Android 8.0)
Phone model:
OPPO Watch 1(Chinese)
Home Assistant version:
Latest

My watch runs a custom Android system. It is not wear OS, nor Google
The following is an error report

adb install wear-release.apk

db: failed to install wear-release.apk: Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY: Package couldn't be installed in /data/app/io.homeassistant.companion.android-R90NxdSzGVFjbyQ59JlYQQ==: Package io.homeassistant.companion.android requires unavailable shared library **com.google.android.wearable**; failing!]

Prompt does not have '**com. google. android. wearable**'
Because app-minimal-release.apk runs slowly on my device.
So I wonder if there can be a Android version of with out Google?
 It was only a passing idea.

**Comment by dshokouhi** [comment]
Also the watch needs to be Android

**Comment by NaZawsze** [comment]
> Also the watch needs to be Android

I am using minimal version.
However, the watch runs slowly due to its poor performance.
Is it the same as wear os, but it doesn't need Google's version?

**Comment by NaZawsze** [comment]
I see. Thank you very much for your answer. ^_^
