### ISSUE TITLE
Disable all sensors and stop updating

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/android#2875]
**Is your feature request related to a problem? Please describe.**

To prevent unnecessary network traffic, database entries etc. I would like to be able to disable all sensors on my mobile apps without having to disable them one by one inside the app.
I would also prefer to have the option to disable updating or set it to "Only manual".

**Describe the solution you'd like**

- Disable all button or "Select all" on long press of any sensor and then disable/enable option.
- Additional button "Manual only" or "Disable sensor updates"

**Describe alternatives you've considered, if any**

Manually disabling/removing everything, which is unpractical.

**Additional context**

Thank you :)

**Comment by dshokouhi** [comment]
You can disable the sensors from the HA frontend the app got rid of the disable /enable all sensors feature and it will not be coming back. It does not make sense to add disable all on its own. We removed enabled all as it gave a false impression on battery life. There are only 7 sensors enabled by default as well.

**Comment by AleXSR700** [comment]
But disabling in the app would (hopefully) disable the updating also. If I disable in HA, then the mobile will continue to send updates all the time.
I would like to completely disable all updates. Either with a dedicated setting or by disabling all devices in the companion app.

**Comment by dshokouhi** [comment]
The app only does a small check once every 15 minutes. It only checks to see what sensors are enabled it does not send that much traffic nor does it have an impact on battery life. This is part of app logic.

**Comment by AleXSR700** [comment]
Any particular reason why this cannot be disabled if not needed/wanted?

**Comment by dshokouhi** [comment]
1. Our sensor worker is designed to start on device boot and remain on schedule, this will not be changing.
2. HA core will have no way of enabling a device or even knowing that sensors are disabled entirely. Other integrations that add sensors a user is requested to just disable them and they will not receive updates. The mobile app works the same way, disable the sensors you don't wish to get updates for and those sensors will not be updated.  Vast majority of android app users want sensors and recent changes were done to make it easier to enable and disable sensors from HA core. This is why they are kept in sync with the server.
3. Simply turn off the notification channel, that is what you should do to avoid seeing the updates. This is why its a separate channel exists.

**Comment by AleXSR700** [comment]
1. Okay. I don't agree with this approach but of course this is not my decision :)
Blocking the processing of an incoming information is an approach that to me is the wrong way around. We install Tasmota and other firmware to get full control. Companion app is one of those awesome tools that should give us maximum control over the information we share. So disabling sharing of mobile phone information should be available. One button to disable all (e.g. in update frequencies).
2. To me, HA core does not need to know if a device or sensor is enabled or disabled unless the source sends this information (e.g. for switches). This is the business of the device. So to me, the companion app should be the one to decide if a sensor is active and its data is being sent.
If I disable in HA core, then the data is still being sent. This is what I do not want. This will also prevent me from deleting the integration/device. If the mobile app keeps sending a life signal, HA core will keep adding the mobile phone. This should be up to the user (IMHO).
3. Of course I disabled all these notifications right away. But I am not trying to "not see" that the app is sending information without my consent, I am trying to prevent the app from sending information I do not want to share. I am looking at what is being received by HA core and want to clean up my devices. I am trying to have maximum control about what and when a device sends information.

**Comment by jpelgrom** [comment]
> If I disable in HA core, then the data is still being sent.

This is not correct, if a sensor is disabled the data will not be collected and is also not sent. If you disable all sensors, the only data exchanged is the list of sensors (which are all disabled in your case), after that it'll finish because nothing is enabled.
