### ISSUE TITLE
Player is drawing over notification and navigation bar when in full screen

### ISSUE THREAD

**Issue by felipecrs** [home-assistant/android#2876]
**Home Assistant Android version:** beta-2692-8713bb96-full

**Android version:** 12

**Phone model:** Samsung S20 FE 5G

**Home Assistant version:** 2022.9.2

**Last working Home Assistant release (if known):** N/A

**Description of problem:** When entering in full screen by clicking the full screen icon in any of the players, such as the Picture Glance one, the player draws over the notification area and also over the the navigation bar, while not hiding any of them.

I initially submitted this issue to https://github.com/dermotduffy/frigate-hass-card/issues/817, but then we realized there is nothing which can be made from either the card or the HA frontend, since APIs for handling these bars in Android does not seem to be exposed by the browser.

- https://developer.android.com/develop/ui/views/layout/immersive
- https://developer.android.com/develop/ui/views/layout/display-cutout

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):** N/A

**Screenshot of problem:**

![ha](https://user-images.githubusercontent.com/29582865/188486805-9bb75add-fda2-42a2-b0e4-a26cccab694e.jpg)

https://user-images.githubusercontent.com/29582865/188494573-156cb2ce-09c8-4e06-83cc-b6e826a471ce.mp4

**Additional information:**

I have two suggestions:

1. Somehow wrap these Android APIs and expose them to the HA frontend, which then can control based on their desire/contents. This can take a very long time to implement.
2. As a short term measure, when the frontend requests full screen, the Android app should automatically hide the navigation bar. The Android app should also NOT allow contents to be displayed over notch, since it may produce undesirable behaviors (it should only be allowed when number 1 gets implemented).

**Comment by dshokouhi** [comment]
Can you reproduce the issue in chrome for android on the same device?

**Comment by felipecrs** [comment]
Slightly: on the same device, on Chrome, the navigation bar and the notification bar hide properly. Ideally it should also NOT draw over the notch as well, but that's ok since it can be controlled by CSS (https://www.w3.org/TR/css-round-display-1/#viewport-fit-descriptor).

**Comment by felipecrs** [comment]
https://user-images.githubusercontent.com/29582865/189950548-d8d86029-b63f-466d-bfbf-7d40d664f70d.mp4

**Comment by dshokouhi** [comment]
ok then I think in this case if the app can't detect the video went to full screen then we will still need the HA frontend to notify the app that it should go into full screen mode via the external bus like all other frontend communication. For now we do have a setting you can enable to go into full screen mode when in the app to avoid this behavior.

**Comment by felipecrs** [comment]
> ok then I think in this case if the app can't detect the video went to full screen then we will still need the HA frontend to notify the app that it should go into full screen mode via the external bus like all other frontend communication.

I see.

> For now we do have a setting you can enable to go into full screen mode when in the app to avoid this behavior.

This unfortunately does not help in my use case, but thanks anyway.

**Comment by dshokouhi** [comment]
Ok I think I see the actual bug, seems going full screen is not working even with the setting that I had mentioned. I do also see our webview has code specific to hiding the system UI when a video goes full screen. I suspect fixing the setting issue may also fix this issue. Thanks for reporting!

**Comment by dshokouhi** [comment]
I have submitted a PR to fix the issue, you can test the debug APK from the below link to see if it is working in the card now.

https://github.com/home-assistant/android/actions/runs/3047355994

I was able to confirm both the setting and going full screen from picture entity card player are working as expected.

**Comment by felipecrs** [comment]
Awesome, it works as expected now!


https://user-images.githubusercontent.com/29582865/189982066-0f53cd0c-b7da-4a3f-8be6-35e4f4825b9a.mp4

**Comment by felipecrs** [comment]
Hm... except of a corner case.

1. Let the app in full-screen (working good)
2. Lock the phone
3. Unlock the phone

The app returns in full-screen but both the navigation bar and notification bar are now shown (not hidden as they should be).

**Comment by dshokouhi** [comment]
That issue may have existed before the code changes so that would be separate issue from this one. In this issue we only changed the method for going to full screen and coming out of full screen. Did you leave the app open in your test? If you go to the home screen and come back does it correct the issue?

**Comment by felipecrs** [comment]
> Did you leave the app open in your test?
Yes, never switched to other apps during the test.

> If you go to the home screen and come back does it correct the issue?
Pressing the home button causes the app to open PiP mode. Clicking in the full-screen button from the PiP window, it returns to the faulty full-screen state (i.e. does not correct the issue).

**Comment by dshokouhi** [comment]
oh wait you locked the app while a video is playing/present on screen? You should not do that as you will hit #979 and incur data charges and battery drain

I have tried following your steps  with locking the phone and opening but on my pixel 6 pro the system bars continue to be hidden when the app is back in focus.

**Comment by felipecrs** [comment]
> You should not do that as you will hit https://github.com/home-assistant/android/issues/979 and incur data charges and battery drain

Thanks to the Frigate Hass Card, [it unloads the media as soon as the window becomes hidden](https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0#:~:text=all%20on%20any%20opportunity%20to%20lazily%20unload), so I don't think this issue affects me.

I will try to record a video demonstrating the issue later.

**Comment by dshokouhi** [comment]
I think I see the issue, we just need to account for when a video is full screen when we regain focus.

**Comment by felipecrs** [comment]
Thanks for the tip!

**Comment by dshokouhi** [comment]
> I think I see the issue, we just need to account for when a video is full screen when we regain focus.

Should be fixed now: https://github.com/home-assistant/android/actions/runs/3047642040

This bug was probably always there as we never checked for a video in full screen during the focus change.

**Comment by felipecrs** [comment]
Confirmed, it fixes the issue. Awesome!
