### ISSUE TITLE
Google Pixel Now Playing Sensor

### ISSUE THREAD

**Issue by holdestmade** [home-assistant/android#2879]
**Is your feature request related to a problem? Please describe.**

The on screen Now Playing Song Identification would be great as a sensor

**Describe the solution you'd like**

Google Pixel Now Playing Song Identification  as a sensor

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
There is no API data available for this. Current app implementations actually use the same API the [Last Notification sensor](https://companion.home-assistant.io/docs/core/sensors#last-notification) does. So you should be able to use that sensor to get the data.

Have you tried using this sensor yet?
