### ISSUE TITLE
tablet screen won't turn off

### ISSUE THREAD

**Issue by Beestkiller** [home-assistant/android#2881]
**Home Assistant Android version:**
Beta-2692-8713bb-96-full  problem same as in the stable version

**Android version:**
Android 10 

**Phone model:**
Lenovo tab M10 FHD Plus  TB-X606F

**Home Assistant version:**
2022.9.2

**Last working Home Assistant release (if known):**
unknown

**Description of problem:**
Tablet screen is not turning off after time out time has been reached not even when option keep screen on is turned off in the app configuration. while beeing idle in the app configuration the screen turns off but not when on a dashboard.

**Comment by dshokouhi** [comment]
I am unable to reproduce on my pixel 6 pro, are there any errors in the logs? Have you tried any other troubleshooting steps yet/

**Comment by dshokouhi** [comment]
Other things I would check are custom cards and cards that play a video stream to see if those are whats stopping the screen from going to sleep.

**Comment by Beestkiller** [comment]
>

> I am unable to reproduce on my pixel 6 pro, are there any errors in the logs? Have you tried any other troubleshooting steps yet/

There are no errors in the logs.

> Other things I would check are custom cards and cards that play a video stream to see if those are whats stopping the screen from going to sleep.

I have a live camera feed in the dashboard, would this be android related then?

**Comment by dshokouhi** [comment]
> I have a live camera feed in the dashboard, would this be android related then?

See what happens if the camera feed is not visible on a different dashboard.

Do you have any custom cards on that dashboard?

**Comment by Guy-Falkes** [comment]
> Other things I would check are custom cards and cards that play a video stream to see if those are whats stopping the screen from going to sleep.

That's it for me... I had these pretty animated backgrounds (which are basically small youtube video's) running. When i one day opened another tab which did not have those everything worked as expected. So I removed the animated video's/backgrounds and that did the trick...
Still, would be nice to have both working...

**Comment by dshokouhi** [comment]
Closing due to lack of response from author and the comment above mentions what fixed it for them.

**Comment by nomailme** [comment]
Anyone managed to figure out can you have camera video that won't prevent device from turning off the screen?

I have a dashboard with picture entity. If I use "auto" mode then device turns off screen after screen timeout. Although in this case camera feed updates an image once every ~10s.
If I have picture entity card in live mode, then video is using either hls or webrtc and is continuous .  But the screen won't dim and turn off after screen timeout

Any help would be appreciated

**Comment by raldred** [comment]
Seeing the same with my nest camera.
I can't use "auto" because it just shows a blank view. 
When using "live" the screen never dims.
Removing the camera from the dashboard the screen dims and turns off as i would expect.
