### ISSUE TITLE
Samsung device tracker not updating reliably 

### ISSUE THREAD

**Issue by seanr2109** [home-assistant/android#2882]
When home assistant restarts the device tracker entity seems to start working but only updates for a short time (maybe a day or two if lucky but sometimes not even that long) before it seems to just stop updating until the next restart.

 I was using this for automations such as when returning home at night turn outside lights on and heating etc as it was updating faster than geocoded location which often takes a while to  update and doesn’t seem as accurate. 
 
Is there any way to make this reliable again and prevent it from only working occasionally

**Comment by dshokouhi** [comment]
This issue is missing the issue template that gets presented when you create a new issue. Please copy the template from a new issue and complete all requested information including the logs in order to continue.

**Comment by dshokouhi** [comment]
Closing due to lack of response
