### ISSUE TITLE
Home Assistant Android Companion App Greek Translation

### ISSUE THREAD

**Issue by MariosMpalas** [home-assistant/android#2897]
I would like to contribute in Home Assistant Companion App for Android translation but my language isn't included in the Lokalise project.

My language info:
English Name: Greek
Native Name: Ελληνικά

I hope my language will be added soon, since it is already included in frontend, backend and iOS projects.

**Comment by dshokouhi** [comment]
I have added the Greek langauge to the project but having some difficulty finding your user in Lokalise, can you see the langauge now?

**Comment by MariosMpalas** [comment]
I can see the language now in language list but I can't see it in language editor.
My name in Lokalise is Thunderstrike 116

**Comment by dshokouhi** [comment]
ok I have added it for your user now
