### ISSUE TITLE
Scheduler time not adjustable

### ISSUE THREAD

**Issue by Scorpoon** [home-assistant/android#2917]
**Home Assistant Android version:** 2022.9.1-full

**Android version:** 13

**Phone model:** Pixel 6

**Home Assistant version:** 2022.9.6

**Description of problem:** Scheduler time is only adjustable when on top of the grid, otherwise it will always scroll instead of setting the time.

**Comment by dshokouhi** [comment]
can you reproduce the issue in chrome for android on the same device?

**Comment by Scorpoon** [comment]
Good point, with chrome on android it doesn't work at all.

**Comment by dshokouhi** [comment]
then that means it is a HA frontend issue, can you please create the issue over there? they have a different issue template that requests additional information

**Comment by Scorpoon** [comment]
Yeah sure, thanks for guiding me to the right project ;)
