### ISSUE TITLE
Entities unavailable when restoring from background mode

### ISSUE THREAD

**Issue by deanfourie1** [home-assistant/android#2919]
**Home Assistant Android version:**
2022.9.1-full
**Android version:**
12
**Phone model:**
Galaxy S10
**Home Assistant version:**
Home Assistant 2022.9.6
Supervisor 2022.09.1
Frontend 20220907.2 - latest
**Last working Home Assistant release (if known):**
the one before this one.
**Description of problem:**
When restoring the app from background mode, I cannot use entities, usually switches for ESPHome devices. They just do nothing, no error, nothing. When I completely close and reopen the app, everything works as expected. If I send the app to background mode, and reopen, they dont work again.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
Cant really screenshot it. The button (simple button calling a service or entity) just does nothing. Not even a error.
**Additional information:**

**Comment by dshokouhi** [comment]
Check that Android system WebView is up to date. Try disabling any custom cards you have installed too.

**Comment by dshokouhi** [comment]
I would also check that the app has proper access to run in the background

**Comment by dshokouhi** [comment]
Closing due to lack of response
