### ISSUE TITLE
Misleading login text about https://home-assistant.io/android getting access to my local HA instance

### ISSUE THREAD

**Issue by cjaone** [home-assistant/android#2921]
**Home Assistant Android version:** 2022.9.1-full

**Home Assistant version:** 2022.9.6

**Description of problem:**

I installed my own HA instance. When starting the companion app for the first time the following text appears at manual login:

_"You're about to give https://home-assistant.io/android access to your Home Assistant instance."_

This sounds like the app will send my credentials to a web service located at home-assistant.io which then in turn will remotely log into my local Home Assistance instance.

What really happens is: The Android app will simply try to login to my local Home Assistant instance using clientId "https://home-assistant.io/android".

I think this the text is misleading (nearly discouraged me from using the app) and should be changed so that it is made clear that only the companion app will simply get access to my Home Assistant instance.

**Comment by dshokouhi** [comment]
This is not controlled by the android app, it is the HA frontend please open an issue there.

**Comment by cjaone** [comment]
Hi @dshokouhi, is the clientId provided by the HA frontend?

**Comment by dshokouhi** [comment]
No the app provides it so the frontend knows the request comes from the android app, this is a requirement for the app from HA core

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationService.kt#L14

the app still does not control the language on this screen as it only presents what the HA frontend wants to show. We just supply the requested data.

https://developers.home-assistant.io/docs/auth_api#clients

**Comment by cjaone** [comment]
Thanks for the info!
