### ISSUE TITLE
problem with home assistant app vers. 2022.9.1-full

### ISSUE THREAD

**Issue by rastalasa** [home-assistant/android#2927]
**Home Assistant Android version:**
2022.9.1-full
**Android version:**
7.0
**Phone model:**
HUAWEI MediaPad M3 Lite 10
**Home Assistant version:**
Home Assistant 2022.9.7, Supervisor 2022.09.1, Operating System 9.0, Frontend 20220907.2 - latest
**Last working Home Assistant release (if known):** 
none
**Description of problem:**
after entering the external URL, the login screen appears. I enter the login data and then the error appears in the attachment
![photo1664292626](https://user-images.githubusercontent.com/114416391/192585380-314402d4-b114-403e-b90f-66620962fd09.jpeg)

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
This is an error for you as a user to solve, looks to be some issue with your SSL certificate. I can't read the error but you will need to solve the error displayed.

**Comment by rastalasa** [comment]
I have already checked the validity of the SSL certificate and there are no problems. Also on other devices the same app works again. This error only comes from this device.

**Comment by dshokouhi** [comment]
Its possible the device does not know the CA used for the certificate. Its hard to tell without looking at the logcat error but you may need to add the CA or regenerate the certificate with one that the device trusts. Each device may do things differently here.

https://developer.android.com/training/articles/security-ssl#UnknownCa
