### ISSUE TITLE
Beacon monitor attribute format

### ISSUE THREAD

**Issue by leroyloren** [home-assistant/android#2928]
**Home Assistant Android version:**
beta2732
**Android version:**
13

**Phone model:**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem:**
This PR https://github.com/home-assistant/android/commit/603e4118233c8d54e66571ac760a13e46413e136
broke work with attribute e.g. in NodeRED, it would be possible to use "uuid_minor_major" format? 
at the moment is "uuid minor.major"

I know I can use a function in NodeRED, but working via a trigger is elegant for these purposes

![obrazek](https://user-images.githubusercontent.com/57643470/192595942-4648a894-7c42-4cad-8d6b-c2152b4e697c.png)

vs.

![obrazek](https://user-images.githubusercontent.com/57643470/192595979-624f617d-2552-40f8-a48b-37914d28d40a.png)

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by leroyloren** [comment]
Ok, thanks for the explanation. I will use the function

`msg.data.event.new_state.attributes["b5b182c7-eab1-4988-aa99-b5c1517008d9 1.55963"];`

**Comment by leroyloren** [comment]
It's a shame that this format cannot be edited/changed. Solved with the author of the HA integration into NodeRED and unfortunately the format is incompatible. I believe that once the Beacon Monitor feature expands I won't be the only one wanting to drive via NR.

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions/667

**Comment by dshokouhi** [comment]
I don't know why this issue was re-opened. The app will indeed be sticking to the format defined by HA core.

**Comment by jpelgrom** [comment]
Actually reading your linked discussion, it is weird that the app was able to create an attribute with a space in the name while other integrations cannot. I have only ever seen basic ASCII letters and underscores in entities.

Could it be a bug in core that the app can create these attributes? It looks like most integrations [slugify attributes, and it's test clearly shows that spaces are not supported](https://github.com/home-assistant/core/blob/c9cc2eb7c8357ab556f41a4386b0ddcf86e1e454/tests/util/test_init.py#L39).

**Comment by dshokouhi** [comment]
> I don't understand the reason to separate the minor major from the title with a space.

it is to match the formatting that HA core uses to keep them in sync, if the app changes this then HA core should also be updated for the new format first.

**Comment by jpelgrom** [comment]
> There is nothing defined in HA documentation about what the format for attributes must be. We did have a PR to remove spaces from some attributes but in this case we wanted to follow the HA core format to keep the app in sync. This seems to be an issue specific to Node RED as the attributes are accessible in HA core via templates, I use it today.

HA core doesn't seem to mind (there are more sensors with spaces in attributes right now, like the BLE Transmitter or Next Alarm), but that doesn't mean it is _supposed_ to work. Like mentioned above basically every other integration doesn't use spaces. I also can't find any documentation but have posted a question in the [#devs_core channel on Discord](https://discord.com/channels/330944238910963714/330990195199442944/1024701868032659596) in case there is an unwritten rule :).

**Comment by leroyloren** [comment]
It would really be good to reconsider that format, because it's nice that it's something "supported in HA" but incompatible with anything else.

The attribute is still primarily for retrieving the distance, minor_major should be as part for identification.

**Comment by dshokouhi** [comment]
We updated the attribute to keep things in sync with HA core, if we update it again then I would like to get HA core updated first. Otherwise we will get another request to keep it in sync so users can use it in automations without having to reformat things.

**Comment by dshokouhi** [comment]
Had a [discussion](https://discord.com/channels/330944238910963714/1012073425638015037/1024719158199468042) with some team members and we will be updating both HA core and the app to the new format of `uuid_major_minor`.

**Comment by dshokouhi** [comment]
Thanks for your patience on this @leroyloren
