### ISSUE TITLE
input_select list not shown

### ISSUE THREAD

**Issue by ced1442** [home-assistant/android#2929]
Hi,
I just figured out that my input_select propose me only the actual selection, not all the list..
I can't select any options from the app companion for now. 
Is it the same for you ?
![Screenshot_2022-09-28-16-50-06-93_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/54055635/192811558-9b4b7503-87ea-4ca1-958f-79cee608f066.jpg)

**Comment by dshokouhi** [comment]
This is a HA frontend issue, please check open issues there and if one does not exist create an issue there.

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=bug_report.yml
