### ISSUE TITLE
Open Settings in the App ?!?

### ISSUE THREAD

**Issue by whyisthisbroken** [home-assistant/android#2946]
Sorry for this maybe stupid question - but where i enter the setting in the app ?
I own a Pixel 5 with Android 13 - but i dont see any settings...
I´ve seen this only one time to change my network adress...and now its gone...
The app is always in Fullscreen and the back gesture or something else doesnt bring the menu

can anyone tell me if i´m dumb ?

**Comment by jpelgrom** [comment]
You can find it in the menu > Settings > Companion app.
