### ISSUE TITLE
IMEI sensor?

### ISSUE THREAD

**Issue by alexiri** [home-assistant/android#2947]
**Is your feature request related to a problem? Please describe.**

My wife's phone was recently stolen and we needed the IMEI to report the theft. Sadly, the phone's box has long since been lost, and we hadn't kept track of the IMEI.

**Describe the solution you'd like**

Her phone had the Home Assistant app installed and it would have been super useful if it had reported the phone's IMEI as a sensor. Kind of a weird request, I know, but perhaps it would be useful in other situations.

**Describe alternatives you've considered, if any**

Not throwing away phone boxes anymore. :)

**Additional context**

**Comment by jpelgrom** [comment]
IMEI access is not available [on Android 10 or newer](https://developer.android.com/about/versions/10/privacy/changes#non-resettable-device-ids), limiting the number of modern devices where this sensor is supported.

**Comment by alexiri** [comment]
Ah, I see. It makes sense that that isn't available, honestly. Too bad!
