### ISSUE TITLE
Add Screentimeout via Notification

### ISSUE THREAD

**Issue by kc3577** [home-assistant/android#2948]
**Is your feature request related to a problem? Please describe.**
Since Android cannot scan Nfc tags in the locked state, it is not possible without additional intervention, for example starting a "good night" routine.

**Describe the solution you'd like**
Since it doesn't seem to be possible to lock the screen directly, the possibility to change the screen timeout via the notifications would be a great relief. You could then simply set the time, in an automation, to one second and then back again after a certain delay.

**Describe alternatives you've considered, if any**
none

**Additional context**
Thus, one would circumvent the limitations of Android and scan NFC tags and put the cell phone into sleep mode.
I was told that it would be possible in a similar way to the new screen brightness sensor and its commands from the latest beta.
https://developer.android.com/reference/android/provider/Settings.System#SCREEN_OFF_TIMEOUT

**Comment by dshokouhi** [comment]
For this one we should mimic what was done for screen brightness, so 1 new notification command and 1 new sensor
