### ISSUE TITLE
Support input_select for device contols

### ISSUE THREAD

**Issue by Hobbit44** [home-assistant/android#2951]
Please could you add input_select to the list of supported entity types that I can use with device controls. It's currently available with the Google assistant integration but not directly through the app.

**Comment by jpelgrom** [comment]
The Google Assistant integration isn't the same as what is supported via device controls. Google Assistant isn't exposed directly to device controls, you can of course say things like "set [entity] to [value]", but the device controls are handled by the Google Home app in Google's ecosystem.

As you can see from my link, device controls only offer a limited set of controls, and something like a dropdown or selector control isn't one of them.

**Comment by jpelgrom** [comment]
Closing this as it currently is not feasible, if this changes in the future it will almost certainly be added 👍
