### ISSUE TITLE
Support for control 2 Home Assistance

### ISSUE THREAD

**Issue by ghost** [home-assistant/android#296]
Hi
Is any chance to add support for two instance Home Assistant on other address ?

**Comment by dshokouhi** [comment]
Even better if it can handle one of those instances being down usually like a dev instance

**Comment by jes1417** [comment]
I was hoping for this as well, in my use case I have an instance at home and at work and I wanted to control both of them. I ended up getting this working by setting up a work profile on my phone which shows me to have separate apps, works perfectly!

**Comment by balloob** [comment]
We are still working on building out basic functionality of the app, so this is not on the roadmap. Once we feel like we're in a good place we would gladly accept a pull request!

**Comment by tescher** [comment]
I'd like to give a +1 for this enhancement also.

**Comment by mishoco** [comment]
This is a very important feature... any update for this?

**Comment by T-bond** [comment]
If anybody like me on a Samsung phone without multiple profiles:
You can use GPlay and F-Droid to install 2 instances (F-Droid is only the minimal favour)
(Or maybe use Secure Folder)

I hope this can get implemented in the near future, as I can't think about anything missing, other than this.
So thank you everybody who worked on this project!

@balloob may I ask you, is the project reached into a state to allow pull request for this? Or is there an estimate for it?
Thank you, very much!

**Comment by teras** [comment]
Hello.
I think the problem is not solved like this.
With two instances we have two notifications, double resources and the auto-update is a problem especially with f-droid. And what if I need three or more instances?

I strongly believe that this issue should be reopened. The similar iOS issue is still pending :grimacing:

**Comment by balazs111** [comment]
Similar  issue here. Already has 2 system and the third is coming.

**Comment by robbiet480** [comment]
Hey all, I ran a poll on our Twitter account this week trying to determine how many people actually have multiple instances. Based on the results of the poll we (@JBassett, @dshokouhi and I) still feel that there’s not enough people who would benefit from the immense effort it would take to rework the app core to support multiple instances vs the effort is takes for developers to keep adding features and fixing things.

As I’ve said before, if a developer came along that wanted to add this functionality (in concert with Justin and others) and was willing to maintain it, we’d be open to that. But for now, there’s far more people who benefit from incremental changes than dropping everything to support a small but vocal minority.

Sorry y’all. Will revisit this again in the future.

**Comment by tescher** [comment]
Twitter poll? Who here monitors the HA Twitter feed?

**Comment by robbiet480** [comment]
You’re right that I failed to alert this issue when I posted the poll, I’m sorry for that. I did alert the same issue in the iOS repo. The poll had 2232 respondents which I think is a good sample size. [You can see results and comments here](https://twitter.com/home_assistant/status/1367226483966504960).

**Comment by teras** [comment]
With all my respect, having an Android-related poll on a iOS-related group is not a match. Also let's make a poll to see how many people prefer HA instead of Google Home or whatever. Is this the correct spirit?

Moreover this issue is not solved - thus it shouldn't be closed.

**Comment by olylak** [comment]
+1

**Comment by wabbastang** [comment]
Seems odd how much talk there is around this on iOS but not much on Android. Definitely a worthwhile feature; obviously it's a select group that runs multiple servers but I think if the ability was there at the top level there would be more utilization. I used to run a dev server to sandbox in, but was such an inconvenience that gave it up. Now have two physical locations and just doesn't play well.

**Comment by ocalvo** [comment]
> Hey all, I ran a poll on our Twitter account this week trying to determine how many people actually have multiple instances. Based on the results of the poll we (@JBassett, @dshokouhi and I) still feel that there’s not enough people who would benefit from the immense effort it would take to rework the app core to support multiple instances vs the effort is takes for developers to keep adding features and fixing things.
> 
> As I’ve said before, if a developer came along that wanted to add this functionality (in concert with Justin and others) and was willing to maintain it, we’d be open to that. But for now, there’s far more people who benefit from incremental changes than dropping everything to support a small but vocal minority.
> 
> Sorry y’all. Will revisit this again in the future.

Hello. Up until now I have been running only one instance, but this year we are building a new vacation home in Costa Rica.

I have some experience with Android development and I would love the challenge add support for multiple homes to the Android home.

I will start by setting my developer environment.

**Comment by dshokouhi** [comment]
> Hello. Up until now I have been running only one instance, but this year we are building a new vacation home in Costa Rica.
> 
> I have some experience with Android development and I would love the challenge add support for multiple homes to the Android home.
> 
> I will start by setting my developer environment.

Thats excellent news and congrats on the new vacation home!  If you have any questions or need any help don't hesitate to ask us on discord in #devs_mobile_app

**Comment by rhinot** [comment]
> Hey all, I ran a poll on our Twitter account this week trying to determine how many people actually have multiple instances. Based on the results of the poll we (@JBassett, @dshokouhi and I) still feel that there’s not enough people who would benefit from the immense effort it would take to rework the app core to support multiple instances vs the effort is takes for developers to keep adding features and fixing things.
> 
> As I’ve said before, if a developer came along that wanted to add this functionality (in concert with Justin and others) and was willing to maintain it, we’d be open to that. But for now, there’s far more people who benefit from incremental changes than dropping everything to support a small but vocal minority.
> 
> Sorry y’all. Will revisit this again in the future.

@robbiet480 Thanks for being transparent and engaging here. 

Reading through the comments of the twitter poll, it seems there are two main categories of users with 2+ HA instances:

1. Devs hacking around things that may not currently work for them in HA (examples: services needing multiple accounts, extending range of ZigBee, testing services before deploying them)
2. Users with multiple locations

For the second case, I wonder if the use cases can be further broken out, and perhaps there is a primary use case which is much less work to implement & maintain.

For example, **could it be that most users who have HAs in multiple locations really just need location reported to multiple HAs**? The use case being that their HAs can respond to where they are in concert. Let's say such a user is en route to their parents home, a winter cottage, or work from where they live. They'd like their home to go into away mode and their parents home/winter cottage/work to switch to home/present mode without manually switching URLs & accounts on their mobile app.

If this is a primary use case, there may be simpler solutions than allowing users to switch between instances on the fly:

- Pushing location to a list of HA servers provided in app
- Allowing HA instances to push location to other HA instances

I originally thought the first option was already possible when I first read this line in [the location docs](https://companion.home-assistant.io/docs/core/location/#overview):

> location data is sent directly from your phone to your Home Assistant instances


The first option seems simpler, although (after a quick glance through the repo) I couldn't find the code that is responsible for pushing location data to an HA instance to see how simple this actually is. Also, https://github.com/home-assistant/iOS/issues/161#issuecomment-791808487 makes me believe it may not be as easy as anticipated, but perhaps I'm misreading.

Nonetheless, sharing this with you as you may:
a) Want to further understand the use cases behind this request to see if one will solve most requesters primary need
b) See an even simpler solution than those outlined here (assuming my example primary use case is correct)

Also, if it's helpful, I can file a separate enhancement request to push user location to multiple HAs with the detail here. I held off as I wasn't sure if that would just get rolled back into this request. LMK.

Hope this helps.

**Comment by albalaing** [comment]
What is your twitter account?

**Comment by tescher** [comment]
@albalaing that was an issue - it wasn't really announced so not sure how it could be considered a useful poll

@rhinot - Thanks, that would be useful, but would only solve a tiny part of my use case. I can get presence other ways, such as router IP address detection. What I really need is a way to switch easily between my 3 instances on my phone for general usage.

**Comment by Vinndimon** [comment]
So... The iOS version now supports multiple servers. What about Android?

**Comment by JBassett** [comment]
I'll say this, we are working towards being able to support multiple instances but we still have a long way to go.  Like Zac said for iOS it was basically touching every aspect of the app.  The same applies to us.  For now we can reopen this ticket, but I wouldn't expect results tangible results in the near term, still a lot to do in the background to get ready for this.

**Comment by jkrenzer** [comment]
Thanks, @JBassett . Maybe a good approach would be identifying the tasks and breaking the work into adoptable chunks so people without insight into the complete app structure could contribute, too.

**Comment by skylord123** [comment]
If you need another HA instance without all the stuff the companion app adds you can just add the other locations to home screen from the web browser on Android. 

I have my home's HA on the app and my work's HA running through the web-browser just added to my home screen. Works great (and was how apps were supposed to function but blame Google and Apple for going the monetary route with app stores and severely limiting PWA functionality).

You could also use [AppCloner](https://appcloner.app/) to duplicate the app. I use this already for my Riot/Matrix chat server (since I have one for work and one for home).

**Comment by ctml91** [comment]
Subscribing for updates on this one =)

**Comment by VaR63** [comment]
Scrivo solo per segnalare che anche io e alcuni amici abbiamo la necessità di usare 2 istanze HA con l'app Android. 
Io spero che sarà considerata l'implementazione.

**Comment by advorsky73** [comment]
More than one HA instance does make sense if you own multiple homes/houses or maintain the ones from your family.
I would really like to see that feature as I am maintaining 2 instances already and this number could raise to 3 in the near future...

**Comment by tescher** [comment]
> More than one HA instance does make sense if you own multiple homes/houses or maintain the ones from your family. I would really like to see that feature as I am maintaining 2 instances already and this number could raise to 3 in the near future...

That's exactly my use case. I have 3.

**Comment by makitsune** [comment]
I just set up my second home on my iPhone and my spouse can't on her Pixel. I hope this gets added soon, same 3 finger swipe gesture as on iOS.

**Comment by VaR63** [comment]
Thank you, I will try it.

**Comment by teras** [comment]
> On Android, you can use two instances by utilising the Work profile - 

Unfortunately my Samsung phone doesn't provide this functionality. I've seen some Xiaomi phones who do this. Samsung reserves this only for communication apps, like Whatsapp and Viber

**Comment by ctml91** [comment]
My work profile has restrictions (from my work), so it's not an option. It's similar to the app cloning but at the end of the day it is still just a work around and poor UX. However as the devs said a lot of refactoring is required to support this change natively in the app but it sounds like it's on the roadmap, fingers crossed it comes sooner than later 😃

**Comment by advorsky73** [comment]
same here, work profile is not an option. fingers crossed it will be created soon

**Comment by T-bond** [comment]
Please everyone stop spamming the thread.

Use reactions to say that you want this feature. Use the subscribe button to get notifications about updates, and stop spamming more than 23 people. Thank you.

**Comment by jpelgrom** [comment]
Hi all,

Support for multiple servers is hopefully coming soon to the Android app :) I have submitted a pull request with a first version of the feature, so please make sure to read [the description](https://github.com/home-assistant/android/pull/3332) and [documentation updates](https://github.com/home-assistant/companion.home-assistant/pull/910) to understand what is and isn't supported at this point.

If you'd like to test before multiserver support is included in the beta, great! Log in to your GitHub account, download the [artifact file from here](https://github.com/home-assistant/android/actions/runs/4157523372), unzip it to get the apk file, and install it on your device. The [full flavor](https://companion.home-assistant.io/docs/core/android-flavors/) offers support for location tracking. The test version will install alongside the existing version of the app but only supports push notifications using a persistent connection, which may increase battery usage. If you encounter crashes, bugs or other weirdness, let me know via a comment on the pull request linked above this comment.
