### ISSUE TITLE
Next Alarm Sensor not sending correct alarms between 00:00 and 10:00 am

### ISSUE THREAD

**Issue by coxtor** [home-assistant/android#2972]
**Home Assistant Android version:** 2022.10.0-full
**Android version:** 13
**Phone model:** Samsung s21 Ultra
**Home Assistant version:**  Home Assistant 2022.10.3 Frontend 20221010.0 - latest 
**Last working Home Assistant release (if known):** -

**Description of problem:**

When using the next alarm sensor alarms between 00:00 and 10:00 are interpreted incorrectly. When setting an alarm at 10:00 am in any android alarm app (google , native samsung alarm clock) the sensor sends the next alarm at 12:00 AM. Setting the alarm earlier makes the sensor not update at all. Therefore alarms between 00:00 and 10:00 am are not detected. 

The issue must be here somewhere, however I can't see it.

https://github.com/home-assistant/android/blob/2384f0f84db16e5dc03fdaf154ca945efaa8b3fd/app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Where are the logs?

**Comment by dshokouhi** [comment]
Also please let us know if you are using an allow list or not with the Next Alarm sensor

**Comment by coxtor** [comment]
Hi, I'm using it without an allow list. Unfortunately I'm using a managed device and can not enable usb-debugging, therefore I can't provide logs. I've tried to reproduce the issue on a pixel 7 pro, however I'm unable to. 
From here - I guess we'll need to close the issue, or do you have any suggestions?

**Comment by dshokouhi** [comment]
Please go to Settings > Companion App > show and share logs

**Comment by coxtor** [comment]
[homeassistant_companion_log_9-17-2022_23-38-50.txt](https://github.com/home-assistant/android/files/9804758/homeassistant_companion_log_9-17-2022_23-38-50.txt)

sure thanks for the hint.

**Comment by dshokouhi** [comment]
looks like its picking up an event already

```
10-17 23:38:30.014 21222 21283 D NextAlarm: Next alarm is scheduled by com.android.providers.calendar with trigger time 1666044000000
```

**Comment by dshokouhi** [comment]
One thing to keep in mind about this sensor and the API used is that it is very literal. It only reports the next scheduled alarm which can be set by any app at any time for any time the app wants to set. You will need to wait for that scheduled alarm to pass to see the next alarm. The API only returns 1 event.

**Comment by coxtor** [comment]
Yes,  it works very well and nearly instantaneously, however the issue persists that the events are not triggered for the times between 00:00am and 10:00am. I'm using node red to process the event using the HA status change node. Debug nodes always fire except between the times mentioned. Anything else I can provide?

**Comment by dshokouhi** [comment]
we will need the logs at the time of the issue to see what is going on, there is nothing in the code base about not returning events at a certain time. Its possible some other issue is occurring at that time. Have you ensured the app has background permissions?

**Comment by coxtor** [comment]
Ok, I have rebooted my phone multiple times and the issue has appeared to have resolved itself. This is quite odd. Thank you very much for taking the time to look into this with me - greatly appreciated.
