### ISSUE TITLE
Companion app no longer uses dark theme if companion app settings are "Dark" or "Follow System Settings" but Home Assistant is set to "Auto"

### ISSUE THREAD

**Issue by jgillula** [home-assistant/android#2985]
**Home Assistant Android version:** 2022.10.2-full

**Android version:** 10

**Phone model:** Pixel 3a

**Home Assistant version:** 2022.10.5

**Last working Home Assistant release (if known):** note that it's the companion app that's the problem, and the last known working version of that is 2022.10.0-full

**Description of problem:** 
In Android Companion App > Settings > Companion App > Theme I choose either "Dark" or "Follow System Settings" (which should be equivalent to "Dark" on my system). While the companion app settings screen stays in dark mode, the rest of Home Assistant within the app is light. (Home Assistant's theme itself is set to "Auto" in "My User" > Theme.)

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):** N/A

```

```

**Screenshot of problem:**
The settings page is dark, which is correct:
![settings page is dark](https://user-images.githubusercontent.com/6627267/197348448-d8193704-1a11-4d39-801e-2e31f9c405dc.png)

...but hitting the back button and going to the rest of Home Assistant in the companion app ignores the chosen "Dark" theme.
![but the rest of home assistant is light](https://user-images.githubusercontent.com/6627267/197348494-99b59640-a191-4a50-8898-3777e3806076.png)

**Additional information:**
[PR 2923](https://github.com/home-assistant/android/pull/2923) is almost certainly the culprit, and I'm guessing it has something to do with "Removing webview force dark settings"

**Comment by jpelgrom** [comment]
What is the version of your WebView?

**Comment by jgillula** [comment]
Stupid question: how do I tell? I can't find it in the companion app settings anywhere, but I'm probably looking in the wrong place. :-)

**Comment by jgillula** [comment]
I think I found the answer. com.android.webview on my device is version 89.0.4389.105

**Comment by jpelgrom** [comment]
Probably the old version is the cause of it not working correctly, can you try updating it? If you [open the Play Store](https://play.google.com/store/apps/details?id=com.google.android.webview&gl=US) it should show an update button.

**Comment by jgillula** [comment]
I just updated WebView to 106.0.5249.126, and the behavior is the same. Dark companion + auto Home Assistant front end (or dark Android system + system settings companion + auto Home Assistant front end) results in the companion app settings screen being dark, but the rest of Home Assistant being light.

**Comment by jgillula** [comment]
Huh, I may have spoken too soon. If I got to Android System Settings > System > Developer Options > WebView implementation, I see both the old version and the new version of WebView, the old one is selected and I cannot select the new one. Let me see if I can figure this out.

**Comment by dshokouhi** [comment]
> Huh, I may have spoken too soon. If I got to Android System Settings > System > Developer Options > WebView implementation, I see both the old version and the new version of WebView, the old one is selected and I cannot select the new one. Let me see if I can figure this out.

Are you running a custom ROM? the package you listed is typically from custom ROM and those are often out of date.

**Comment by jgillula** [comment]
Yes, I'm running Lineage. I guess the out of date WebView is the culprit after all.

**Comment by dshokouhi** [comment]
Yup that will do it, you'll need to set the correct and supported WebView for the device. How you do that is a question for the custom ROM.

**Comment by jpelgrom** [comment]
What Android version are the Amazon tablets on?

**Comment by jpelgrom** [comment]
Looks like that Fire OS version is based on Android 9, which does not offer native dark theme support. It works on normal Android but Amazon is probably doing something differently...

@dshokouhi If I remember correctly you had an Amazon tablet, any chance you could check and probably reproduce this?

**Comment by jpelgrom** [comment]
Follow Home Assistant and Follow System Settings behaved identically on the latest versions.

You're probably affected by another change in the same PR which (shouldn't have) impacted the WebView theming.

**Comment by jpelgrom** [comment]
In case you hadn't thought of it as a workaround: you can also set the time in your profile settings.

**Comment by dshokouhi** [comment]
> @dshokouhi If I remember correctly you had an Amazon tablet, any chance you could check and probably reproduce this?

I have a few lol, been dealing with an outage here so will get a chance to take a closer look around Monday.

**Comment by csidirop** [comment]
I'll just jump in here: I have the same issue after the last update (gplay) and I am on a custom ROM here. I tried everything till I cam here to open an issue.

Let me know if I can help!

**Home Assistant Android version:** 2022.10.2-full
**Android version:** 11 (LineageOS18.1)
**Phone model:** Zenfone 8
**Webview:** 96.0.4664.104

**Comment by jpelgrom** [comment]
@csidirop Can you also try updating your webview to a recent version (105/106)?

**Comment by csidirop** [comment]
Unfortunately there haven't been any updates since February: https://opengapps.org/

Btw. My Android Webview does not receive any updates from gplay store. Ill need to manually update it.

**Comment by jpelgrom** [comment]
The related [Chromium issue/feature](https://bugs.chromium.org/p/chromium/issues/detail?id=1253990#c9) says this was implemented in stable version 101, several months ago, so I guess this issue is a combination of forks like Amazon's deciding to do whatever they want and outdated (unupdateable?) webviews.

At first glance there don't appear to be any downsides to re-implementing the code. Google says it won't work anymore, but if the webview isn't working like it should in the first place with no way to update it for some it might help 🤷

Could anyone that is affected download a test version of the app with that code [from here](https://github.com/home-assistant/android/actions/runs/3307327374) and report back (you need to be signed in to download, the test version will install alongside the existing app)?

**Comment by csidirop** [comment]
> Could anyone that is affected download a test version of the app with that code [from here](https://github.com/home-assistant/android/actions/runs/3307327374) and report back (you need to be signed in to download, the test version will install alongside the existing app)?

Worked as before. (I tried the minimal debug) Light made it light, dark made it dark and system settings dark like my system settings.

**Comment by jgillula** [comment]
Same here--the test version of the app fixed the problem and worked correctly for me, like  2022.10.0-full and earlier.

**Comment by dshokouhi** [comment]
> when will the fix arrive in a stable release (which would be 2022.10.3, right)?

I don't think there will be a 2022.10.3 release, most likely it will be included as part of 2022.11.0. 

We have had quite a bit of things get added into this current beta cycle so we usually like to let things beta for a lil bit to make sure no last minute surprises show up. The play store beta did not update last week either so we lost some beta time there.

You are more than welcome to either join the beta or install the APK off the releases tab in the meantime :)

**Comment by dshokouhi** [comment]
> Can you guide me (link) on how to get a beta? Is it sideloading (coexistence with the stable one) or replacing the stable APK? Same for the releases tab download. I'm not using Play Store by the way.

From the github releases tab: https://github.com/home-assistant/android/releases you can select the flavor you currently have installed, the labels will match the version you installed. We also use the same APK signature so it should install as an update.



> Otherwise: 2022.11.0 will ship next week already right?

for the app we dont have a set release date yet, really depends on beta feedback

**Comment by jgillula** [comment]
FWIW 2022.11.0 fixed the issue for me. Can you confirm what you have for both of these settings in the companion app?
* Settings > Companion App > Theme
* YourUsername > Theme

I have "Follow System Settings" and "Auto", and with my phone's system settings set to dark mode it works for me.

**Comment by jgillula** [comment]
Sorry--@bcutter I was going to ask what your settings were, but I see you explained them quite clearly in the new issue you opened. :-)

FWIW I've got (Settings > Companion App > Theme = Dark) + (My User > Theme = Auto) with webview version 89.0.4389.105 on an Android 10 (Lineage) device and 2022.11.0 is working properly for me.

**Comment by csidirop** [comment]
FYI: Mine works as expected again after the update

**Comment by csidirop** [comment]
> > FYI: Mine works as expected again after the update
> 
> Which
>     * device
>     * Android version
>     * WebView version
> 
> ?

> I'll just jump in here: I have the same issue after the last update (gplay) and I am on a custom ROM here. I tried everything till I cam here to open an issue.
> 
> Let me know if I can help!
> 
> **Home Assistant Android version:** 2022.10.2-full 
> **Android version:** 11 (LineageOS18.1) 
> **Phone model:** Zenfone 8 
> **Webview:** 96.0.4664.104

Except its the December update now. Both manual and auto "follow system settings" are working. 

But as mentioned in #3107 , auto mode may unfortunately still be an issue for FireOS users.

**Comment by emansom** [comment]
Is this in the latest beta?

Running Android 9 and currently running into this issue.

**Comment by dshokouhi** [comment]
> Is this in the latest beta?

no the fix is already live in production but fire OS devices are still impacted due to them running an old version of webview

**Comment by emansom** [comment]
> > Is this in the latest beta?
> > Mobile phone has Android 9 and currently running into this issue.
> 
> Do you use Fire devices? What devices are you running with Android 9?

moto e6 plus. Mostly stock Android afaict.

**Comment by emansom** [comment]
> no the fix is already live in production but fire OS devices are still impacted due to them running an old version of webview

@dshokouhi Running latest WebView on this Android 9 device, with the latest beta Home Assistant app and still observing the issue.

It seems to ignore what HA's dark/light mode preference entirely.

![Screenshot_20221213-001642~2.png](https://user-images.githubusercontent.com/981494/207180969-58502597-7cf1-4085-823e-bdba44d4245d.png)

**Comment by dshokouhi** [comment]
Can you check the companion app logs to see which webview package and version are being used? We print that statement in the logs. Settings > companion app > show and share logs

**Comment by emansom** [comment]
> Can you check the companion app logs to see which webview package and version are being used? We print that statement in the logs. Settings > companion app > show and share logs

Done 👍🏻 

https://gist.github.com/emansom/704ba4c06d18dc54415016427b522d92

**Comment by emansom** [comment]
Ignore the connection issues in the logs, I disable WiFi on the device when it's not in use.

**Comment by dshokouhi** [comment]
Looks like these logs do not contain the line I am looking for. Can you force stop the app, open the app and get the logs again please? We only print this statement once when the app is open which is why it seems to be missing.

**Comment by emansom** [comment]
> Looks like these logs do not contain the line I am looking for. Can you force stop the app, open the app and get the logs again please? We only print this statement once when the app is open which is why it seems to be missing.

👍🏻 

https://gist.github.com/emansom/a09d6196fe17b52f2cb38b68e36fcd6f

**Comment by dshokouhi** [comment]
Was android system webview installed by default on your device or just chrome? On your device looks like Chrome is set as the default webview.

```
12-13 00:43:43.040  2082  2082 I WebViewFactory: Loading com.android.chrome version 108.0.5359.79 (code 535907923)
```

You didnt by chance disable chrome did you?

There are a lot of webkit issues on this device but also other missing libraries too.

**Comment by emansom** [comment]
> Was android system webview installed by default on your device or just chrome? On your device looks like Chrome is set as the default webview.

Installed by default. No uninstall or install button is even available for that app on my device in the Play Store.

> You didnt by chance disable chrome did you?

It's enabled, but I do have Firefox set as default browser.

**Comment by dshokouhi** [comment]
Your issues do not seem to be related to this issue but something else entirely. There are a lot of missing class errors in the logs you provided which look to be a device issue with missing libraries. 

This one is related to missing geocoder libraries so unrelated to webview but still an issue for this sensor. These libraries are included by default in android so not sur why its failing here
```
12-13 00:43:42.266  2082  2082 I mpanion.androi: Rejecting re-init on previously-failed class java.lang.Class<io.homeassistant.companion.android.sensors.GeocodeSensorManager$getFromLocationAwait$2$1>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/location/Geocoder$GeocodeListener;
```

These are the actual issue as the webview is having issues even loading properly
```
12-13 00:43:43.491  2082  2082 I mpanion.androi: Rejecting re-init on previously-failed class java.lang.Class<di2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
```

```
12-13 00:43:50.845  2082  2082 I mpanion.androi: Rejecting re-init on previously-failed class java.lang.Class<androidx.webkit.internal.WebViewRenderProcessClientFrameworkAdapter>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/WebViewRenderProcessClient;
```

**Comment by emansom** [comment]
> This one is related to missing geocoder libraries so unrelated to webview but still an issue for this sensor. These libraries are included by default in android so not sur why its failing here
> 
> ```
> 12-13 00:43:42.266  2082  2082 I mpanion.androi: Rejecting re-init on previously-failed class java.lang.Class<io.homeassistant.companion.android.sensors.GeocodeSensorManager$getFromLocationAwait$2$1>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/location/Geocoder$GeocodeListener;
> ```

Location reporting functions fine, so I guess it's falling back. I do disable location on Android most of the time.

![Schermafdruk van 2022-12-13 01-51-22](https://user-images.githubusercontent.com/981494/207199849-1f42cf38-a524-4921-81fd-8a95de1bbc87.png)

> These are the actual issue as the webview is having issues even loading properly
> 
> ```
> 12-13 00:43:43.491  2082  2082 I mpanion.androi: Rejecting re-init on previously-failed class java.lang.Class<di2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
> ```
> 
> ```
> 12-13 00:43:50.845  2082  2082 I mpanion.androi: Rejecting re-init on previously-failed class java.lang.Class<androidx.webkit.internal.WebViewRenderProcessClientFrameworkAdapter>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/WebViewRenderProcessClient;
> ```

If it isn't loading properly, then how does the app render?

![Screenshot_20221213-015703](https://user-images.githubusercontent.com/981494/207200256-1ca4b8f2-30fe-4eb2-865e-41ef12b36a9b.png)

**Comment by dshokouhi** [comment]
> Location reporting functions fine, so I guess it's falling back on something. I do disable location on Android most of the time.

Weird your logs suggest otherwise, at least at times :)

```
12-13 00:43:47.272  2082  2082 E GeocodeSM: Somehow location is null even though it was successful
```

> If it isn't loading properly, then how does the app render?

Well parts of the webview are working, other parts are not. Your log for example is missing our statement where we print what package and version are being used on the device.

You shouldn't expect to see any missing class errors like that
https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L670

So if we are not seeing log statements as such then its possible that other webkit code will also not work as expected.

**Comment by emansom** [comment]
> > Location reporting functions fine, so I guess it's falling back on something. I do disable location on Android most of the time.
> 
> Weird your logs suggest otherwise, at least at times :)

Android location was disabled when I captured this log.

> 
> ```
> 12-13 00:43:47.272  2082  2082 E GeocodeSM: Somehow location is null even though it was successful
> ```
> 
> > If it isn't loading properly, then how does the app render?
> 
> Well parts of the webview are working, other parts are not. Your log for example is missing our statement where we print what package and version are being used on the device.
> 
> You shouldn't expect to see any missing class errors like that https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L670
> 
> So if we are not seeing log statements as such then its possible that other webkit code will also not work as expected.

The theme colors get changed in the page correctly (see the dot on the menu in the screenshot), so DOM manipulation works afaict. Is more required to change theme?

What other WebKit code are you referring to? Is the app using some evil memory injection techniques?

**Comment by dshokouhi** [comment]
> Then this statement is equal to false on my device:

Android SDK O is Android 8, you are on Android 9 so I would hope its `true` ;)



> What other WebKit code are you referring to?

The logs for one which is probably failing because its missing the necessary library to provide the data. That could be why we see those errors.



> Is the app using some evil memory injection techniques?

can you elaborate more on this please? feel free to inspect the code to see if anything is not right.

**Comment by emansom** [comment]
> > Then this statement is equal to false on my device:
> 
> Android SDK O is Android 8, you are on Android 9 so I would hope its `true` ;)

It has to be `false`, otherwise it'd print the log. Or something is wrong with the log capture.

https://github.com/home-assistant/android/blob/e9fe00917ce6f44f77c9b4e25e4b42e53bc15302/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L668-L671

> 
> > What other WebKit code are you referring to?
> 
> The logs for one which is probably failing because its missing the necessary library to provide the data. That could be why we see those errors.

Then the app would crash, that isn't the case.

> > Is the app using some evil memory injection techniques?
> 
> can you elaborate more on this please? feel free to inspect the code to see if anything is not right.

Some apps hijack application memory to override behavior of third party libraries.

**Comment by OZ1SEJ** [comment]
I'm using the Companion app on a Lenovo Tab M10 FHD Plus (Android 10), and while the theme in the "App Configuration" part actually reflects the choices made regarding light or dark theme, as soon as I return to the Overview, it always reverts back to light theme. Everything is up to date.

One interesting bit is that I am _not_ logged in as myself on the tablet - I've created a "user" (_not_ a "person") for use with the tablet. It occurs to me that either way, the display shouldn't revert back to "light" theme when either "dark" or "follow system settings" is chosen.

**Comment by IoSonoAndreaZ** [comment]
On a very old android phone I want to use as desk stand, I solved this issue installing [WebView Canary](https://play.google.com/store/apps/details?id=com.google.android.webview.canary&gl=US).
Then open it and android should ask you to set it as default. Do it and companion app is again in dark mode
