### ISSUE TITLE
Bedtime Mode and Theater Mode isn't working on GW4

### ISSUE THREAD

**Issue by SkechyWolf** [home-assistant/android#2990]
**Home Assistant Android version:**
[beta-2820-58bd438e](https://github.com/home-assistant/android/releases/tag/beta-2820-58bd438e)

**Android version:**
11
**Phone model:**
Samsung Galaxy Watch 4
**Home Assistant version:**
2022.10.4
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
The Bedtime and Theater Mode sensors don't report/error to HA because the Global Vars Samsung uses are different than those added in the PR
I've talked with @dshokouhi on discord about this
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
![image](https://user-images.githubusercontent.com/37350695/197407219-a25a1939-f7b1-4c9f-b0bd-7f93fa3cddf8.png)

**Screenshot of problem:**
Look Above

**Additional information:**
Vars being used by Samsung
Theater Mode:
`setting_theater_mode_on`
Bedtime Mode:
`setting_bedtime_mode_running_state`

**Comment by dshokouhi** [comment]
Let's confirm if the Galaxy watch 5 users the same globals. Also if someone has another brand like fossil or monteblac we should confirm the same from them.

Hopefully we don't have too many differences to account for.
