### ISSUE TITLE
Companion app Android Intents as automation trigger!

### ISSUE THREAD

**Issue by dsantos21** [home-assistant/android#3032]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Be able to launch automations from Home Assistant Companion App Android shortcuts. For example, that would allow me to trigger home assistant from bixby routines!

**Describe alternatives you've considered, if any**

Using bixby routines only for phone automations.

**Additional context**

**Comment by dshokouhi** [comment]
If you are referring to [shortcuts](https://companion.home-assistant.io/docs/integrations/android-shortcuts) then this is only to be used for launching the frontend. What other shortcut are you referring to?

**Comment by dsantos21** [comment]
Yes, Im refering to shortcurt. Today they can be used only to navigate the frontend (open specific dashboard or entity).

What I'm suggesting is the ability to use it just as a trigger (for example, to start an automation, or something like change states or call services).

Why all of this? :) Cause in Samsung smaryphones you can start app intents from bixby routines. I could, for example, set an routine in bixby to fire an automation in home assistant for alarm or panic when I unlock my phone using an specific fingerpriny :) (like attached picture - portuguese, sorry...)

![Screenshot_20221102-190515_Bixby Routines](https://user-images.githubusercontent.com/44759158/199611426-4f03291f-5ab9-4945-a091-f57f7d6b369a.png)

**Comment by dshokouhi** [comment]
> Yes, Im refering to shortcurt. Today they can be used only to navigate the frontend (open specific dashboard or entity).
> 
> What I'm suggesting is the ability to use it as a trigger too (for example, to start an automation, or even something like change states or call services, if possible, but as a trigger would be enought to all other use cases).

Shortcuts are meant to be linked to an Activity, we decided against doing an app action because that becomes a hack to add a blank activity screen for it.  They are meant for the UI so they only load the UI.

**Comment by dsantos21** [comment]
Ok, thanks!
