### ISSUE TITLE
Refresh tokens not constrained to box

### ISSUE THREAD

**Issue by sym0nd0** [home-assistant/android#3037]
**Home Assistant Android version:**
2022.10.2-full
**Android version:**
13
**Phone model:**
Samsung Galaxy S22 Ultra 
**Home Assistant version:**
2022.11.1
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
Long strings are breaking out of the table and forcing the page to scroll horizontally. Also, the trash icon isn't aligned. 
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
N/A
```

**Screenshot of problem:**
Github is having an issue with uploading images, I'll add it later when resolved. 

Whilst Github gets itself sorted out:

![Imgbb link](https://i.ibb.co/0QYBY9D/Screenshot-20221104-130602-Home-Assistant.jpg) 
**Additional information:**

**Comment by dshokouhi** [comment]
Can you reproduce in chrome for Android on the same device?

**Comment by sym0nd0** [comment]
> Can you reproduce in chrome for Android on the same device?

Hadn't thought to check, but yes same happening in Chrome.

! (https://i.ibb.co/PwCSfs8/Screenshot-20221104-140641-Chrome.jpg)

**Comment by dshokouhi** [comment]
Ok that means this is not an app issue but a HA frontend issue.

**Comment by sym0nd0** [comment]
Ah OK, thanks. I'll close and reopen it in the right repo.
