### ISSUE TITLE
Tap Template Widget to Open HA App

### ISSUE THREAD

**Issue by mathmaniac43** [home-assistant/android#3040]
**Is your feature request related to a problem? Please describe.**

I have a template widget on my home screen that displays some text. I would like to be able to interact by tapping it, like with widgets for other apps.

**Describe the solution you'd like**

A simple and intuitive action would be to open HA to a specified Dashboard path. This is consistent with many weather apps, for example: simple summary in the widget, then tap to open the app for more details.

**Describe alternatives you've considered, if any**

I have used some of and looked at all of the other HA widgets, and do not believe that any support navigating into the app. Apologies if I am missing something.

**Additional context**

**Comment by dshokouhi** [comment]
Tapping on a widget is reserved for updating the state of the widget.

https://companion.home-assistant.io/docs/integrations/android-widgets

 If you wish to open the application to a specified dashboard you need to use a shortcut for that on the home screen.

https://companion.home-assistant.io/docs/integrations/android-shortcuts
