### ISSUE TITLE
Wear OS complication for a current sensor value

### ISSUE THREAD

**Issue by dreimer1986** [home-assistant/android#3047]
**Is your feature request related to a problem? Please describe.**

Please add sensor status output to the complication support.

**Describe the solution you'd like**

I would like to see a way to use the current complication support for one specific output of a sensor for blood sugar. This one comes from the nightscout integration.

**Describe alternatives you've considered, if any**

The current xDrip complication support is not working and when it works for a few weeks it seems to get broken again. This way I could realize my goal by using Home Assistant which already has these information in my case anyways

**Additional context**

**Comment by dshokouhi** [comment]
There is already support HA sensor status as a complication, did you try adding the complication for the entity already?

**Comment by dreimer1986** [comment]
Then I am looking on the wrong part...
I see buttons, covers, lights, scenes, scripts and switches. Sensors are not there.

**Comment by dshokouhi** [comment]
are you sure you are adding a complication by editing the watchface, selecting an existing complication to replace and selecting Entity State from teh list of app provided complications?

**Comment by dreimer1986** [comment]
Omg. Now I found it. I am new with smart watches. Just realized that you can edit the complications on the watch too. Nvm. Mean culpa and thanks for the hint ^^
