### ISSUE TITLE
Home Assistant App connect/reconnect Problem

### ISSUE THREAD

**Issue by Penumbra168** [home-assistant/android#3053]
**Home Assistant Android version:**
 home-assistant-minimal-2022.10.2
**Android version:**
5.1.1
**Phone model:**
Samsung Galaxy j2  (Used as a dashboard for the HA server)
**Home Assistant version:**
2022.11.2
**Last working Home Assistant release (if known):**

**Description of problem:**
At the first launch, the application successfully connected to HA via WI-FI , but if you close the Home Assistant App, then during repeated and subsequent launches, the Home Assistant App cannot connect to the Home Assistant. If you specify an external address in the Home Assistant App options, the Home Assistant App successfully connects to HA, but if you close the Home Assistant App, then during repeated and subsequent launches, the Home Assistant App cannot connect to the Home Assistant. If I change the IP address of the phone in the router settings, then the Home Assistant App successfully connects to HA, but if you close the Home Assistant App, then with repeated and subsequent launches, the Home Assistant App cannot connect to the Home Assistant.

The most interesting thing is that the Home Assistant server at the same time sees the sensors from the phone

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Where are the logs? We need to see the logs when it cannot connect so we can determine what the app can do (if anything) to fix the issue.

**Comment by Penumbra168** [comment]
**that's all there is**

logcat: invalid option -- -
Unrecognized Option
Usage: logcat [options] [filterspecs]
options include:
  -s              Set default filter to silent.
                  Like specifying filterspec '*:s'
  -f <filename>   Log to file. Default to stdout
  -r [<kbytes>]   Rotate log every kbytes. (16 if unspecified). Requires -f
  -n <count>      Sets max number of rotated logs to <count>, default 4
  -v <format>     Sets the log print format, where <format> is one of:

                  brief process tag thread raw time threadtime long

  -c              clear (flush) the entire log and exit
  -d              dump the log and then exit (don't block)
  -t <count>      print only the most recent <count> lines (implies -d)
  -t '<time>'     print most recent lines since specified time (implies -d)
  -T <count>      print only the most recent <count> lines (does not imply -d)
  -T '<time>'     print most recent lines since specified time (not imply -d)
                  count is pure numerical, time is 'MM-DD hh:mm:ss.mmm'
  -g              get the size of the log's ring buffer and exit
  -b <buffer>     Request alternate ring buffer, 'main', 'system', 'radio',
                  'events', 'crash' or 'all'. Multiple -b parameters are
                  allowed and results are interleaved. The default is
                  -b main -b system -b crash.
  -B              output the log in binary.
  -S              output statistics.
  -G <size>       set size of log ring buffer, may suffix with K or M.
  -p              print prune white and ~black list. Service is specified as
                  UID, UID/PID or /PID. Weighed for quicker pruning if prefix
                  with ~, otherwise weighed for longevity if unadorned. All
                  other pruning activity is oldest first. Special case ~!
                  represents an automatic quicker pruning for the noisiest
                  UID as determined by the current statistics.
  -P '<list> ...' set prune white and ~black list, using same format as
                  printed above. Must be quoted.

filterspecs are a series of 
  <tag>[:priority]

where <tag> is a log component tag (or * for all) and priority is:
  V    Verbose
  D    Debug
  I    Info
  W    Warn
  E    Error
  F    Fatal
  S    Silent (supress all output)

'*' means '*:d' and <tag> by itself means <tag>:v

If not specified on the commandline, filterspec is set from ANDROID_LOG_TAGS.
If no filterspec is found, filter defaults to '*:I'

If not specified with -v, format is set from ANDROID_PRINTF_LOG
or defaults to "brief"
[homeassistant_companion_log_10-9-2022_16-29-42.txt](https://github.com/home-assistant/android/files/9972102/homeassistant_companion_log_10-9-2022_16-29-42.txt)

**Comment by dshokouhi** [comment]
ok hten on our device it is not working, I see you are using the minimal version so I assume you are using a custom ROM? Without logs to see the actual issue we are not able to do much of anything here.  We will need to see Logcat logs from the device.

**Comment by Penumbra168** [comment]
I'm reinstalling the full version now.

**Comment by dshokouhi** [comment]
a screenshot of your issue will also be helpful, keep in mind installing the full version does not mean the logs will show.

**Comment by Penumbra168** [comment]
Reinstalled to full version. The first time the application started. On the following launches, the App cannot connect to Home Assistant. If you click update the internal address, the application freezes
[logcat.zip](https://github.com/home-assistant/android/files/9972496/logcat.zip)
![изображение_viber_2022-11-09_17-05-14-747](https://user-images.githubusercontent.com/114436833/200871935-eef8c755-0ce0-4879-99e2-5ddbfcfc8db4.jpg)
![изображение_viber_2022-11-09_17-05-15-171](https://user-images.githubusercontent.com/114436833/200871978-b5340db0-63ba-4588-9744-ce7fcf958796.jpg)
![изображение_viber_2022-11-09_16-51-45-305](https://user-images.githubusercontent.com/114436833/200872010-7203d2e1-6ca5-43fe-a3ad-6653646f87e5.jpg)

**Comment by Penumbra168** [comment]
oh, not that

**Comment by Penumbra168** [comment]
The log is exactly the same as above. Can I still download some log from the phone's file system?

**Comment by Penumbra168** [comment]
I took a tambourine and went to dance over Android Studio....  and smoke the manual...   I will after I figure it out
