### ISSUE TITLE
High Accuracy only when connected to BT

### ISSUE THREAD

**Issue by guarddog13** [home-assistant/android#3057]
**Home Assistant Android version:**
2022.10.2

**Android version:**
Both Android 12 and 13

**Phone model:**
3 different models of Samsung Galaxy phones. 

**Home Assistant version:**
2022.11.2

**Last working Home Assistant release (if known):**
2022.10.??

**Description of problem:**
I have my high accuracy mode turn on based on connecting via BT devices as seen in the screenshot. This method quit working reliably sometime during the Oct releases. To get this method to work properly now you have to often open the app to get it to connect. 

![Screenshot_20221111_075002_Home Assistant](https://user-images.githubusercontent.com/31947215/201344344-f3b51049-635e-45cc-bdc6-63bd0ef5a602.jpg)

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
We need to see the logs when the issue occurs

**Comment by dshokouhi** [comment]
> To get this method to work properly now you have to often open the app to get it to connect.

Can you also check that the app has proper permissions to run in the background? I see you are also using a Samsung device so you may need to check a few more device specific settings to ensure the app is able to continue to run in the background.

**Comment by guarddog13** [comment]
Next time it happens I'll grab the logs. You need the one from the app or HA?

I have the proper permissions and this was working previously..somewhere during oct releases it started doing this on all the phones.

**Comment by dshokouhi** [comment]
> You need the one from the app or HA?

App logs please

**Comment by Hellis81** [comment]
What do you mean with connect?
Do you mean the phone connect to the BT device? Or HA "connect" high accuracy.
The first one is probably not HA related.

**Comment by guarddog13** [comment]
![Screenshot_20221112_023644_Home Assistant](https://user-images.githubusercontent.com/31947215/201463097-012fd92b-3775-4d9d-9ca4-b29981ec271e.jpg)

Here...i have it set if my phone connects to one of two devices it's supposed to turn on high accuracy mode. I have an automation set as a backup using the bt sensor and a template but this isn't accurate in areas with limited internet connectivity. I'm going to disable the automation tomorrow and reproduce it so i can pull the logs.

**Comment by Hellis81** [comment]
Why is the setting switched off?
That is an issue

**Comment by guarddog13** [comment]
> Why is the setting switched off? That is an issue

No thats the design. When my phone connects to one of those 2 devices below then it turns on. It's not doing this periodically unless I open the app. I wasnt connected to one of those devices when I took the screenshot so it should be off.

**Comment by dshokouhi** [comment]
are you by chance using `command_high_accuracy` at times?

https://companion.home-assistant.io/docs/notifications/notification-commands#high-accuracy-mode

If you do not use this command then in actuality the above setting will not remain greyed out but will remain on. High accuracy mode itself will handle the constraints untouched. If you did end up using that command then it will override the constraints. Take a read on the docs so you know which command to use for your use case.

when all the settings are greyed out like that it means high accuracy will not turn on.

Something seems a bit off here. We are still waiting on the requested logs too.

**Comment by dshokouhi** [comment]
Closing due to lack of response
