### ISSUE TITLE
Recent Crash: GMS: API Exception 22: API failed to connect while resuming due to an unknown error.

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#3060]
**Home Assistant Android version:**

latest master

**Android version:**

13

**Phone model:**

Pixel 7 Pro

**Home Assistant version:**

2022.11.2

**Last working Home Assistant release (if known):**

n/a

**Description of problem:**

Noticed the following crash overnight with the below stacktrace, this one is not easy to tell where its coming from :/ 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
2022-11-11 00:35:47.662: com.google.android.gms.common.api.ApiException: 22: API failed to connect while resuming due to an unknown error.
    at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.0.1:3)
    at com.google.android.gms.common.api.internal.ApiExceptionMapper.getException(com.google.android.gms:play-services-base@@18.0.1:1)
    at com.google.android.gms.common.api.internal.zag.zad(com.google.android.gms:play-services-base@@18.0.1:1)
    at com.google.android.gms.common.api.internal.zabq.zaE(com.google.android.gms:play-services-base@@18.0.1:7)
    at com.google.android.gms.common.api.internal.zabq.zaD(com.google.android.gms:play-services-base@@18.0.1:2)
    at com.google.android.gms.common.api.internal.zabq.zaw(com.google.android.gms:play-services-base@@18.0.1:6)
    at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(com.google.android.gms:play-services-base@@18.0.1:47)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)
    Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a41589f, Dispatchers.Main]
```

**Screenshot of problem:**

**Additional information:**

**Comment by sahad0** [comment]
i am also facing this issue whats wrong :

can you please post the error?

[Error: 22: API failed to connect while resuming due to an unknown error.] Why am i getting this error?

**Comment by dshokouhi** [comment]
> can you please post the error?

the error is already posted above



> Why am i getting this error?

We do not know at this point, we just know the app crashed due to this error.

**Comment by jlandyr** [comment]
Same problem here using FirebaseUI with "Sign Out" function as described in [documentation](https://firebase.google.com/docs/auth/android/firebaseui#sign_out). 
This is the error Im getting back: com.google.android.gms.common.api.ApiException: 22: API failed to connect while resuming due to an unknown error.

**Comment by androidreactdev** [comment]
I was also facing same issue
Just check first that build or apk you are using is created with same SHA-256 that you configured in firebase project settings

To configure SHA-256 , you need to fetch it first so you may use this command to fetch SHA-256
keytool -list -v -keystore <keystore path> -alias <key alias> -storepass <store password> -keypass <key password>

You may read this article to understand this
https://docs.getsocial.im/knowledge-base/android-signing-key-sha256/

after getting SHA-256 , copy it and paste in firebase project configuration

-> Go to firebase console 
-> Select Project in which you need to configure
-> Select setting icon showing after "Project Overview" at top left side and one popup will show over there
-> Select "Project Settings" option from popup menu
-> Select "General" tab which is select bydefault and located at 1st
-> Scroll down "Your apps" section and select "Android Apps"
-> Add your SHA-256 key in "SHA certificate fingerprints" section

**Comment by yschimke** [comment]
I'm not sure the cause of the error, but it seems more like a Play connection issue if it's transient.

There is a reference to the same "22: API failed to connect while resuming" here https://issuetracker.google.com/issues/257765160

If it's crashing the app, you should be catching that, any Play operations can fail for distributed systems reasons, and instead show an error, possibly retry.

**Comment by dshokouhi** [comment]
> I'm not sure the cause of the error, but it seems more like a Play connection issue if it's transient. If it's completely reproducible, then probably the signing key issue.
> 
> There is a reference to the same "22: API failed to connect while resuming" here https://issuetracker.google.com/issues/257765160
> 
> If it's crashing the app, you should be catching that, any Play operations can fail for distributed systems reasons, and instead show an error, possibly retry.

@yschimke Thank you for taking the time to explain what the issue could potentially be along with linking to the appropriate issue 🙏  I have now submitted a PR to catch potential failures from play services.

Potential areas of impact:

- Geocoded location sensor
- Activity sensors
- Android auto connection sensor
- Location Sensors (including high accuracy mode)
- Wearable communication services between watch and phone

Hopefully that captures it all, it looks like we did catch a few errors but only in areas we knew would crash. Now its good to know that most of these can fail for any reason.
