### ISSUE TITLE
Entity history flatlines/freezes on Chrome for desktop/Android

### ISSUE THREAD

**Issue by tombadog99** [home-assistant/android#3062]
**Home Assistant Android version: 2022.10.2-full

**Android version: 13

**Phone model: Pixel 5

**Home Assistant version: 2022.11.1

**Last working Home Assistant release (if known): unknown - at least a couple of months ago

**Description of problem: Climate entity history graph freezes at random times which causes the graph to flat line for a while until it randomly recovers. However, when viewing on desktop, everything is displayed on desktop and the issue does not manifest itself.

```

```

**Screenshot of problem: 
![Screenshot_20221113-075002](https://user-images.githubusercontent.com/70843749/201535944-3689ead3-deba-4898-8202-0ae7fad7f88e.png)

**Additional information:**

**Comment by dshokouhi** [comment]
what about chrome for android? do you see the same issue there on the same device?

**Comment by tombadog99** [comment]
Displaying fine on Chrome for Android as well.

**Comment by dshokouhi** [comment]
ok this is still a bit out of our control as we just display the site in our webview and thats it. Can you check that android system webview is up to date?  

Also there is a HA frontend change in 2022.11.2 might want to update to that as well as it could be fixed there.

**Comment by tombadog99** [comment]
Just tried on another android device and it displayed fine. So I thought I'd try reinstalling HA app on my phone. Now it is displaying fine. Will monitor to see if it stays fixed!

**Comment by dshokouhi** [comment]
ah so it couldve been a cache issue :) it happens from time to time

**Comment by tombadog99** [comment]
Still not fully solved. The issue still exists but seems to be some sort of cache issue. Clearing the cache and reopening the app works initially but then the issue represents itself.

**Comment by dshokouhi** [comment]
so our app respects the caching level set by the HA frontend, thats why I asked you to test in Chrome for android because it will probably exhibit the same issue eventually.

**Comment by jpelgrom** [comment]
Is it possible that the connection is lost or the app is suspended at some point? I've seen the graph in the more info dialog stop updating after reconnecting before (also in a browser).

**Comment by tombadog99** [comment]
Yes, confirmed now that it does occur on Chrome for Android.

**Comment by tombadog99** [comment]
> Is it possible that the connection is lost or the app is suspended at some point? I've seen the graph in the more info dialog stop updating after reconnecting before (also in a browser).

Don't think this is what happening in this instance.

**Comment by tombadog99** [comment]
> > Is it possible that the connection is lost or the app is suspended at some point? I've seen the graph in the more info dialog stop updating after reconnecting before (also in a browser).
> 
> Don't think this is what happening in this instance.

Scratch that. I think this is sort of what's happening. It seems if I fully close the app and reopen it seems to work. Furthermore, I have now also seen this behaviour on chrome for desktop. Essentially what seems top happen is that when the page is left open, whether it be in the app or desktop, the graph doesn't fully reload properly. This requires a manual refresh of the page or  fully closing/reopening the Android app. Have updated to HA 2022.11.2 - no difference. Pretty sure this never used to be an issue until circa 2 months ago.

**Comment by dshokouhi** [comment]
> Yes, confirmed now that it does occur on Chrome for Android.


please file a new issue with the HA frontend, I would also check for open issues to make sure its not already filed.

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=bug_report.yml
