### ISSUE TITLE
After opening notifications on the sidebar, then it always pops up when using back button

### ISSUE THREAD

**Issue by vojtechj** [home-assistant/android#3073]
Home Assistant Android version: 20221108.0

Android version: 12, One UI 4.1

Phone model: Samsung Galaxy S10e SM-G970F/DS

Home Assistant version: 2022.11.2

Last working Home Assistant release (if known): It was always like that

Description of problem: After clicking on Notifications on the sidebar, then hiding the notification window/list with clicking on < then it always pops up when using android's back button. For example clicking on sensor card and then going back with android's back button. The dashboard is there, but it's hidden under the notification window.

Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):

```

```

Screenshot of problem:

![image](https://user-images.githubusercontent.com/38255592/201853033-86c595e7-de71-408d-8483-304f1aa6f1ac.png)
![image](https://user-images.githubusercontent.com/38255592/201853089-83f2a2f3-bf1e-4c74-b8e8-3c1c32f56347.png)
![image](https://user-images.githubusercontent.com/38255592/201853114-da1b39f8-e703-436b-a210-b0b4a3178903.png)
![image](https://user-images.githubusercontent.com/38255592/201853144-6848cd16-bc1f-4527-8fad-4827d919b293.png)

Additional information:

**Comment by dshokouhi** [comment]
Do you see the same issue using chrome for Android on the same device?

**Comment by vojtechj** [comment]
yes

**Comment by jpelgrom** [comment]
As you're also seeing this in a browser, this is not an app-specific issue. Please open an issue [for the frontend instead](https://github.com/home-assistant/frontend/) to have this fixed.
