### ISSUE TITLE
Widget with entity state and call service combined into one

### ISSUE THREAD

**Issue by levkanm** [home-assistant/android#3078]
**Is your feature request related to a problem? Please describe.**
At present, the button widgets can only be used to call services, and the entity state widgets can only be used to view entity status. I hope to control entities and display entity status on one widget.

**Describe the solution you'd like**
Add a widget with entity state and call service widgets combined into one.

**Comment by dshokouhi** [comment]
So you want a widget with entity state and call service widgets combined into one? Please next time you file an issue or enhancement do not remove the template. It is there for a reason.

**Comment by GSzabados** [comment]
+1 to this request.

I see a brilliant use case for Garage Door or Gate openers. When you press it, it opens/closes the Garage Door/Gate and updates the state of the widget according the Open/Close sensor's state.

**Comment by Misiu** [comment]
This would be super useful. I now have a pair of two widgets, one to call a service and a second to show the state of an entity.
Having two gates and six lights requires 16 widgets (8 to call service and 8 to show the state) on the screen! With that change, I could have only eight.

**Comment by jpelgrom** [comment]
Trying to implement this as a simple action to choose, like the frontend:

https://github.com/home-assistant/android/assets/8148535/4cf4d479-bddb-459b-80d9-a117bf835828

Any thoughts?
