### ISSUE TITLE
Wear settings in phone uses a different server/credentials than the Wear app

### ISSUE THREAD

**Issue by jpelgrom** [home-assistant/android#3086]
**Home Assistant Android version:** latest / [`62ebb90`](https://github.com/home-assistant/android/commit/62ebb90f2e60789456c49e0ec95d8bd4cc3e0eff)

**Android version:** 13, Wear OS 3.0

**Phone model:** not relevant

**Home Assistant version:** not relevant

**Last working Home Assistant release (if known):** none

**Description of problem:** While logging in to a test server I noticed that the Wear device settings in the main app showed favorites of my production server. This is due to the fact that the Wear settings in the main app use the main app data for fetching favorites, which can be a different server!

https://github.com/home-assistant/android/blob/62ebb90f2e60789456c49e0ec95d8bd4cc3e0eff/app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt#L105-L107

https://github.com/home-assistant/android/blob/62ebb90f2e60789456c49e0ec95d8bd4cc3e0eff/app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt#L120-L121

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):** not applicable

**Screenshot of problem:**

The Wear app only shows lights in the set favorites screen, which is correct:

![Wear app screen titled 'Set favorites', with one category 'Lights'](https://user-images.githubusercontent.com/8148535/202781794-5fcbd115-524a-4749-a0cd-e5a2e5b2020e.png)

But the main app is showing different entity types and different entities:

![Main app screen titled 'Favorite entities', showing multiple entities in categories 'Button', 'Fan', 'Input Boolean', 'Light', ...](https://user-images.githubusercontent.com/8148535/202782245-a0cc7fb1-a594-4be6-9806-e5d7ba4fe495.png)

**Additional information:** 

Is this the first multi-server bug before we have multi-server support?

**Comment by dshokouhi** [comment]
Nice find! this will be an interesting one to solve lol

**Comment by jpelgrom** [comment]
Once we add multi-server support I think this shouldn't be too difficult to fix, the Wear app will be just another server (where we have to read the data from the watch)
