### ISSUE TITLE
Allow High Accuracy mode based on detected activity 

### ISSUE THREAD

**Issue by pluskal** [home-assistant/android#3088]
**Is your feature request related to a problem? Please describe.**

Location tracking via Home Assistant seems a natural choice when using HA for home automation. Constant High Accuracy mode consumes too much battery, low accuracy is insufficient for cases such as commuting to work by car. 

**Describe the solution you'd like**

It would be awesome to have the ability to set `High Accuracy` mode based on the `Detected Activity` in the companion app.

**Describe alternatives you've considered, if any**

Using automation to trigger a notification that triggers `high accuracy` using tasker.

**Additional context**

During the winter months, it would be a relief to have an option to automatically and accurately track location during high-risk activities such as `in_vehicle` or perhaps even `walking` (for elderly people).

**Comment by dshokouhi** [comment]
There is already a notification command to control high accuracy mode as there can be many other cases for when it should enable.

https://companion.home-assistant.io/docs/notifications/notification-commands#high-accuracy-mode

Use this along with the detected activity sensor and any other conditions you feel necessary in a automation to control high accuracy mode.

This allows the app support a variety of use cases.
