### ISSUE TITLE
Weird Spacing in Button Widget

### ISSUE THREAD

**Issue by tanishqmanuja** [home-assistant/android#3093]
**Is your feature request related to a problem? Please describe.**

The spacing/margin/padding in button widget seems very unnatural to look at. Although it may not impact the working anyhow but significantly drops the polished impression we usually expect from great apps.

**Describe the solution you'd like**

- The top and bottom padding/margin should be equal.
- If the Label text is empty string i.e. "", It should not be rendered or 'android:visibility' should be adjusted. Then the icon will be centered in the widget.

**Describe alternatives you've considered, if any**

N/A

**Additional context**

![a](https://user-images.githubusercontent.com/40914272/203506493-8a783105-12b8-4eec-88c9-7f276e9a8ddd.jpg)
![b](https://user-images.githubusercontent.com/40914272/203506523-3363912d-22fc-4bfd-93bf-041489837d42.jpg)

**Comment by jpelgrom** [comment]
I agree these don't look great everywhere. The preview images for older Android versions do look like they are correctly spaced, so I'm guessing different screen sizes / no text wasn't considered originally 😉

**Comment by jpelgrom** [comment]
Playing with this:

 - Centering the icon when there is no label should be relatively easy to do.
 - "Equal spacing" when there is a label is a bit more difficult. With your example it'd look OK, but what if the device uses a taller grid? Should there be a larger gap in the middle (1), or should a larger top/bottom padding be used (2)? Especially on tablets even the smallest 1x1 widget can already be quite large. The current solution (3), while not perfect, at least comes somewhat close to the layout of an app icon and label. Example for demonstration, with exaggerated height:

![A screenshot showing widgets with layouts 1, 2, and 3 from the text above](https://user-images.githubusercontent.com/8148535/203639598-7870061a-04a0-4741-8c1f-88c9856e146e.png)

**Comment by tanishqmanuja** [comment]
As per UX concerns option (2) should be out of the question because the widgets support transparent background also, this makes apparently invisible touch spots.
For the same reason option (1) is scores the highest on UX as user knows the touch area perfectly, but option (3) looks the best in my opinion 😁.

**Comment by tanishqmanuja** [comment]
> Playing with this:
> 
>  - Centering the icon when there is no label should be relatively easy to do.
>  - "Equal spacing" when there is a label is a bit more difficult. With your example it'd look OK, but what if the device uses a taller grid? Should there be a larger gap in the middle (1), or should a larger top/bottom padding be used (2)? Especially on tablets even the smallest 1x1 widget can already be quite large. The current solution (3), while not perfect, at least comes somewhat close to the layout of an app icon and label. Example for demonstration, with exaggerated height:
> 
> ![A screenshot showing widgets with layouts 1, 2, and 3 from the text above](https://user-images.githubusercontent.com/8148535/203639598-7870061a-04a0-4741-8c1f-88c9856e146e.png)
> 

Also as option (3) is the current implemented method, but still it doesn't provide equal top and bottom spacing on small screen size as mentioned. So there should be a minimum top padding which is equal to the fixed bottom padding of label.

**Comment by tanishqmanuja** [comment]
After a little tinkering with the code, here is what I was able to get.
Could not figure out a solution for multiline text when height is very less example in landscape.

Landscape
![land](https://user-images.githubusercontent.com/40914272/203750046-553754b1-da29-4b33-bcd2-34364d99c19b.jpg)

Portrait
![port](https://user-images.githubusercontent.com/40914272/203750197-f360c95b-4f5a-4802-ad28-b741ec289614.jpg)

PS: The rightmost icon is from Stock Home Assistant App kept for comparison.
