### ISSUE TITLE
Making app available/port to Samsung Appstore.

### ISSUE THREAD

**Issue by Dvalin21** [home-assistant/android#3094]
Requesting for this app to be available/ported to the Samsung Appstore.  Samsung Smartwatches that are Watch 4 and higher have the google appstore, but watch 3 and older don't use Wear OS, but Tizen OS which only can use Samsung AppStore. This way all samsung smartwatches (at least those with LTE) will be able to be used for device tracking in Home Assistant the same way cell phones are. Even if it just had that feature, it would make more watches (more affordable ones at that even if they are older) to be used for tracking. Thanks in advance.

**Comment by SkechyWolf** [comment]
Doing a quick google search Tizen doesn't support Android apps so I'm guessing a new Flavor of HA would have to be made for Tizen but then also go through the process of being put on the Galaxy Store
Someone like @dshokouhi might have more info on the dev side of things

**Comment by jpelgrom** [comment]
Isn't Tizen a completely different OS, and a completely different app? I'm not sure there is any relation with Android aside from that you would usually pair a Tizen watch to an Android device. The Wear OS app shares a lot of code with the main/phone app.

**Comment by dshokouhi** [comment]
Yes Tizen is not Android so the app will not be made available there. Someone else will need to build a completely separate app for that which is out of scope for the Android app.

**Comment by ChrisLetuyn** [comment]
It's also strange that, for example, the Wearable app on an android connects to the watch. My watch appears in HA also. Some sensors are passed on through the Health app to HA. Just not the battery state of the watch. While Health offers a 'tunnel', Wearable does not. I'm no coder, but a Wearable bridge would be nice.
