### ISSUE TITLE
External Url not running.

### ISSUE THREAD

**Issue by MikeFlare303** [home-assistant/android#3101]
2022.11.0-full

External url is not reachable anymore.
I'm on roaming.

![Screenshot_20221125_165153_Home Assistant](https://user-images.githubusercontent.com/109216505/204020353-ea6c4cb5-89a0-42ec-aa43-1c2ae3c3da6b.jpg)

Sorry but there aren't more information.
My mobile did the new app update and now my home assistant isn't reachable by that app without wifi.

If I use any browser with the same external url it works fine.
I use a tunnel by cloudflare to reach my homeassistant. 

Saludos, 
Mike

**Comment by jpelgrom** [comment]
Hi 👋 Could you copy the template that is shown when creating a new issue into your comment to provide more information? The error message shown by the app would be the minimum to be able to say anything meaningful about this and logs would be helpful to quickly figure out what is happening.

**Comment by jpelgrom** [comment]
In the message that is shown, can you tap on the settings button and verify that the external URL is still correct?

At the end of the settings there should also be an option to view the logs, this should contain more technical details about which URL it is using and why it cannot connect which would be helpful to view. You can redact any URLs if they are included.

**Comment by MikeFlare303** [comment]
After a complete de- and reinstall it works again.
