### ISSUE TITLE
[Q] command_bluetooth remove, alternatives?

### ISSUE THREAD

**Issue by SamJongenelen** [home-assistant/android#3110]
**Is your feature request related to a problem? Please describe.**

Since the last HA companion update, notification of command_bluetooth does not work anymore. 
First, I am using Android 13 pixel 6a and the command was working for me. 
Second, maybe this is Android change, any link where i can read up? couldn't find a reason for the change.
Third, the docs still have example of using the command and should be updated :)
Fourth, is there any alternative way for me to control bluetooth on my phone?

**Describe the solution you'd like**

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by SamJongenelen** [comment]
Docs with example:
https://companion.home-assistant.io/docs/notifications/notification-commands/#bluetooth

**Comment by dshokouhi** [comment]
The docs are correct but I think you missed this bit

![image](https://user-images.githubusercontent.com/1634145/204155988-60d07718-f990-42fe-9603-d723aa71aff2.png)

yes this is an android change they removed this feature in Android 13 once an app targets the latest SDK

https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#enable()

not sure if Tasker will still be able to do this but that would be the only way now, Blueooth now has the same restriction as Wifi where apps are not allowed to control it anymore.

**Comment by SamJongenelen** [comment]
https://github.com/home-assistant/companion.home-assistant/pull/865

**Comment by SamJongenelen** [comment]
For reference, same question on SO

https://stackoverflow.com/questions/74533260/how-to-disable-bluetooth-in-android-api-33

**Comment by SamJongenelen** [comment]
@dshokouhi i think that _disable_ is only removed from the api. Couldn we still have the `command` for enabling? That would still work for me.

My use case is to disconnect an audio device after x time, to make it go to powersave mode

**Comment by dshokouhi** [comment]
> @dshokouhi i think that _disable_ is only removed from the api. Couldn we still have the `command` for enabling? That would still work for me.
> 
> My use case is to enable and connect an audio device at X time and then disconnect after x time. and thus make it go to powersave mode

did you read the link I posted?

`Starting with Build.VERSION_CODES.TIRAMISU, applications are not allowed to enable/disable Bluetooth.`

This same note is shown for both `enable()` and `disable()`
