### ISSUE TITLE
request_location_update only works when the app is in the foreground

### ISSUE THREAD

**Issue by moritzbeck13** [home-assistant/android#3113]
**Home Assistant Android version:**
2022.11.0-full

**Android version:**
12

**Phone model:**
Samsung S21 FE 5G

**Home Assistant version:**
2022.11.4

**Last working Home Assistant release (if known):**
-

**Description of problem:**
After sending the message `request_location_update` via the `notify` service, the `device_tracker` sensor is only updated when the app is already opened in the foreground. When the app is in the background, I can still receive normal push notifications, but the sensor is only updated every 15 minutes.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
I have to close the app to test this, but when I open it again to look at the logs, they immediately get flushed with other messages. Since those also include the location update that is sent when opening the app, I cannot pinpoint the exact entry for my manual request.
```

```

**Screenshot of problem:**

**Additional information:**
I have followed the guide for starting fresh and for if the Device Tracker is not updating.

**Comment by dshokouhi** [comment]
can you share an example of the notification? did you make sure to follow the critical notification format to speed up delivery?

https://companion.home-assistant.io/docs/notifications/critical-notifications#android

**Comment by moritzbeck01** [comment]
Yes, tried it both with and without
```
ttl: 0
priority: high
```
for the data option.

My service call looks like this:
```
service: notify.notify
data:
  message: request_location_update
```

**Comment by dshokouhi** [comment]
can you please show the complete notification with the critical format? please also confirm the app is not battery optimized and any other power saving features from Samsung are also disabled for the app.

**Comment by dshokouhi** [comment]
the correct format here would be:

```
service: notify.notify
data:
  message: request_location_update
  data:
    ttl: 0
    priority: high
```

**Comment by moritzbeck01** [comment]
```
service: notify.notify
data:
  message: request_location_update
  data:
    ttl: 0
    priority: high
```
I have:
- default settings for the location sensors
- location permission on always allow and high accuracy
- allow background data usage
- exempt from data saving
- disable battery optimization

Home Assistant does show up in `recent access` list of the Android location settings menu after I send a request. I could also try to add it to the "apps that are never in standby" list.

**Comment by dshokouhi** [comment]
> I could also try to add it to the "apps that are never in standby" list.

yes you need to disable all battery optimization settings, samsung likes to add a bunch of different ones than just one thing so hard to tell exactly what you need to disable.

dontkillmyapp.com usually has some good tips here.

**Comment by moritzbeck01** [comment]
> yes you need to disable all battery optimization settings, samsung likes to add a bunch of different ones than just one thing so hard to tell exactly what you need to disable.

See my previous edit, Home Assistant is not even in that list, probably because some other setting includes this one already.

> dontkillmyapp.com usually has some good tips here.

FWIW (since the guide is not updated for Android 12 yet) I have already done that.

**Comment by dshokouhi** [comment]
> but the sensor is only updated every 15 minutes.

Has your position changed? we dont send updates if the location has not changed for 15 minutes. You should be seeing updates in teh logs every few minute for normal requests.

here a deeper explanation to how location tracking works: https://companion.home-assistant.io/docs/core/location#android-location-sensors

**Comment by moritzbeck01** [comment]
> Has your position changed? we dont send updates if the location has not changed for 15 minutes. You should be seeing updates in teh logs every few minute for normal requests.

I can't say for sure, I have tried with a GPS location faker which didn't change anything.
Why do I get updates then if my position didn't change when the app is in the foreground?

**Comment by dshokouhi** [comment]
> Why do I get updates then if my position didn't change when the app is in the foreground?

this suggests the app does not have access to remain running in the background

**Comment by moritzbeck01** [comment]
Yes, I suspect that aswell. But I don't know of any other setting I could probably change.

You said that a location update is only send if it differs from the previous one. But if the app is opened, I still get updates, even though it does not differ.

**Comment by dshokouhi** [comment]
if its been 15 minutes or if we detect too much time has passed since our last received update we will make a new request for updates....the fact that it happens after you open the app suggests the app is not able to do what it needs to do in the background

**Comment by moritzbeck01** [comment]
Well the automatic update every 15 minutes does work, just not the manual request.

**Comment by dshokouhi** [comment]
in your case most likely the manual request is not coming in until later, I am not sure what we can do here if your device is not allowing the app to run in the background

**Comment by moritzbeck01** [comment]
Since I can see Home Assistant in the Android location request history every time I send a message, I think the issue has something to do with sending back the data.

**Comment by dshokouhi** [comment]
we need to see the logs to determine that

**Comment by moritzbeck01** [comment]
Is it possible that, if my GPS accuracy is very bad, the result gets discarded or is just alwayays the same?

**Comment by dshokouhi** [comment]
yes and the logs will show if things are getting discarded. You can try using an app like Logcat reader to look at historical logs that our app may not have.

**Comment by rindlerblabla** [comment]
@moritzbeck01 Did you ever solve this?

I am also trying to send `request_location_update` and it works just fine when the app is open, but when it is in the background nothing is happening. Other commands like the `command_screen_on` works if I just change message text but keep everything else the same. And yes, HA is authorized to always be allowed to use location data.

Am using the service

```
service: notify.mobile_app_*******
data:
  message: request_location_update
  data:
    priority: high
    ttl: 0
```

**Comment by moritzbeck01** [comment]
Not really. I think when in the app is in the background and those flags are set, the location should still be sent, even if the last time was recent. @dshokouhi

**Comment by rindlerblabla** [comment]
Okey. Too bad. The background location is generally updated so the companion app is for sure authorised to use location data, even in the background.

**Comment by frlequ** [comment]
I can confirm the same behavior using Samsung S21 - S23 phones. I've disabled all power and battery-saving options, as well as data saver and sleeping apps. 

Other notifications work fine, like SCREEN ON or UPDATE SENSORS; all triggers in the background when the phone screen is off or in the lock state. However, request_location_update does not.

In the log, the single accurate location fires only when the app is opened.

**Comment by dshokouhi** [comment]
As this is an old issue closed over a year ago please submit a new issue filling out the issue template completely. We should not reopen old and closed issues

**Comment by moritzbeck13** [comment]
@rindlerblabla @frlequ I encourage you to create a new issue. This doesn't seem like a feature to me. Maybe unlike me you are able to get logs and attach them.

**Comment by MaasOne** [comment]
I had the same issue on Samsung tablet with Nabu Casa cloud. The problem was the "persistent connection" setting. 
So at Settings > Companion App > Select your server > Persistent connection > Always

So it works with "Local Push" via websocket API. Don't know why the Firebase Cloud Messaging is not working in this case.
