### ISSUE TITLE
High battery usage from GPS even if location sensors are disabled

### ISSUE THREAD

**Issue by cascer1** [home-assistant/android#3118]
**Home Assistant Android version:**  `2022.11.0-full`

**Android version:** `12`

**Phone model:** Sony Xperia 5 II

**Home Assistant version:** `2022.11.4`

**Last working Home Assistant release (if known):** N/A

**Description of problem:**

The Android app uses 10-20% of my battery in a day, most of which goes to GPS according to GSam Battery Monitor. I used to have no problem even with the background location and location zone sensors enabled (even sometimes using high accuracy mode) but now it happens even when I disable all location sensors.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

N/A, there is no crash

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/7243299/204524746-bdaf82f2-8c28-47f7-a76c-dcd4035467ad.png)

![image](https://user-images.githubusercontent.com/7243299/204524790-ed12f22f-0fce-481f-9e41-6198e9d66ed4.png)

**Additional information:**

I'm not sure when this started happening but it might've been after the update to `2022.11`. the battery drain does not seem to change much between days where I'm mostly at home or where I'm switching between zones a lot.

**Comment by dshokouhi** [comment]
please start with these steps

https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-app-battery-drain

**Comment by cascer1** [comment]
@dshokouhi thanks, I went through the recommendations on that page and it looks like I had already set the options there correctly.

**Comment by dshokouhi** [comment]
can you get us the on device logs when you see the drain occurring? Try to get us like 10 minutes of log time by keeping the app open.

Settings > Companion App > Show and share logs.

this will let us know if location trackng is still happening or something else is causing the drain.

**Comment by cascer1** [comment]
Hey @dshokouhi 

Thanks for your patience while I procrastinated 😬 I've collected the logs [here](https://gist.github.com/cascer1/8a935b6def854712287b221a554affaf)

thanks

**Comment by dshokouhi** [comment]
There is no GPS usage here in the logs, at this point I would suggest starting fresh maybe something got corrupted.

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by cascer1** [comment]
Thanks, I'll give that a try and will update this issue in a few days with my findings.

**Comment by makuser** [comment]
I have the same issue with the minimal flavor, and there isn't even a way to setup location tracking in that flavor (unfortunately).

**Comment by cascer1** [comment]
In my case, the issue was resolved after starting fresh. I'll leave the issue open for @makuser

**Comment by dshokouhi** [comment]
Closing as the original reporter has resolved the issue
