### ISSUE TITLE
Quick Setting (Tile) vibration feedback

### ISSUE THREAD

**Issue by icegothic** [home-assistant/android#3119]
Hi, 

It would be nice to have a vibration feedback (customizable in duration) when pressing on one of the companion app’s quick setting (tile).

Note: I used to do that with Tasker & QuickTask but Home Assistant Companion tiles are way more reactive.

**Comment by dshokouhi** [comment]
vibration duration does not sound like something we should add, we should just use a success or failure vibration if the user enabled it.

**Comment by icegothic** [comment]
Could you point me to a link explaining how to do this?

**Comment by dshokouhi** [comment]
this was more about implementation details for an app update more than something for the user to do :)

**Comment by icegothic** [comment]
Oh ok :-)
