### ISSUE TITLE
Quick Settings (Tiles) state not refreshing properly

### ISSUE THREAD

**Issue by icegothic** [home-assistant/android#3120]
**Home Assistant Android version:** 
2022.11.0-full

**Android version:** 
13 (or 12)

**Phone model:** 
Galaxy S22

**Home Assistant version:** 
2022.11.4

**Last working Home Assistant release (if known):** 
It never worked

**Description of problem:** 
The state of the Quick Settings (Tiles) seems not to refresh properly (not changing color) when tapped. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
[homeassistant_companion_log_10-29-2022_11-20-21.txt](https://github.com/home-assistant/android/files/10115003/homeassistant_companion_log_10-29-2022_11-20-21.txt)

```

```

**Screenshot of problem:**
Here's a video of the issue, We can see that the state updates well when when we turn off the light, but it does not update when turning on unless we reopen the panel

https://user-images.githubusercontent.com/16883752/204583356-0248dd2e-0655-44e4-89ce-3e5d6d614f13.mp4

**Additional information:**
Notes: The light is toggling properly but the state (color) of the tile is not refreshed; we have to close and reopen the QuickSettings panel to see the real state of the device on the tile. Note: I noticed that Tasker can do it with QuickTask tiles (https://play.google.com/store/apps/details?id=com.balda.quicktask) but they are not as reactive as HA Companion tiles.

**Comment by dshokouhi** [comment]
why was the issue template removed here? All the requested information is important especially the part about logs. The active state of the tile will update however its possible something failed.

**Comment by icegothic** [comment]
Hi, sorry for the template; I fixed it and added a video of the issue and the log file. Is there a way I can provide more information?

**Comment by icegothic** [comment]
How can I make it more obvious so the state of the tile update when the lights turns on?  (sorry I'm kinda new to Home Assistant)

**Comment by dshokouhi** [comment]
have you considered using device controls? They are identical to tiles but way more interactive as they let you control the brightness level etc...

**Comment by icegothic** [comment]
That seems nice but I never could find the option to activate/access those... :-(

**Comment by icegothic** [comment]
I'll check it out and see if it fits my needs :-) thank you for the suggestion

**Comment by dshokouhi** [comment]
There is a quick setting tile called "Device Controls" you can get to it from there. Samsung may have also moved things around.

https://companion.home-assistant.io/docs/integrations/android-device-controls

**Comment by icegothic** [comment]
They seem more interactive but the reactive surface of the device controls buttons are smaller than the tiles and accessing the device requires pressing 1 more button each time... So I'll stick with tiles; so is there anything I can do to update the state of the tiles?

**Comment by dshokouhi** [comment]
> so is there anything I can do to update the state of the tiles?

just wait for the PR I linked to be reviewed/merged and it will update the state whenever the tile is visible and the state changes

**Comment by icegothic** [comment]
That's great, thank you :-)
