### ISSUE TITLE
Energy distribution card are not displayed correctly

### ISSUE THREAD

**Issue by jvcsw** [home-assistant/android#3124]
**Home Assistant Android version:**
2022.11.0

**Android version:**
??

**Phone model:** 
Fire HD 8

**Home Assistant version:**
2022.11.5

**Last working Home Assistant release (if known):**
??

**Description of problem:**
The energy distribution card are not displayed correctly, missing color lines, missing card borders, etc
Sometimes crash the app after a few hours showing this card.
The card is displayed correctly in other devices (desktop, mobile, etc) and **in the same tablet using Chrome**.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![imagen](https://user-images.githubusercontent.com/37216513/204925230-2f3409e3-10d4-44e0-9629-f1d435cb8f5c.png)

**Additional information:**

**Comment by dshokouhi** [comment]
is this a custom card or stock card? Fire tablets unfortunately do not have an up to date webview so there will be differences there unfortunately.

**Comment by jvcsw** [comment]
Hi,

is a card included by default in HA (Energy distribution card): 
https://www.home-assistant.io/dashboards/energy/

whats is the meaning that webview do not have an up to date?

This is the normal view (with color libes):
![imagen](https://user-images.githubusercontent.com/37216513/205001994-dbcc92c8-2f5d-4b8d-a9ee-34ebc1981548.png)


Thanks

**Comment by dshokouhi** [comment]
> whats is the meaning that webview do not have an up to date?

on Amazon devices there is no way to update the WebView, the android app does not control anything related to how a card will display. That is dependent upon WebView. Its like having an outdated browser that you cannot update as updates are controlled by Amazon.

I see you said sometimes it crashes the app? Are you certain the app is crashed due to the card? Next time it crashes please go to Settings > Companion App > Show and Share logs and check to see if there is a Recent Crash tab as that may give us a clue as to what happened.

**Comment by jvcsw** [comment]
I'm not sure, but the next time I will see the logs. Thanks.

Going back to the main problem, are you telling me to use the web browser instead of the app in my case?

**Comment by dshokouhi** [comment]
more than likely this will be a HA frontend issue rather than one the app can solve.

**Comment by jvcsw** [comment]
> > whats is the meaning that webview do not have an up to date?
> 
> on Amazon devices there is no way to update the WebView, the android app does not control anything related to how a card will display. That is dependent upon WebView. Its like having an outdated browser that you cannot update as updates are controlled by Amazon.
> 
> I see you said sometimes it crashes the app? Are you certain the app is crashed due to the card? Next time it crashes please go to Settings > Companion App > Show and Share logs and check to see if there is a Recent Crash tab as that may give us a clue as to what happened.

Houston!! we have a problem with logs!! 

![imagen](https://user-images.githubusercontent.com/37216513/205344602-2689c8dc-b649-407d-b9a5-834189382060.png)

**Comment by dshokouhi** [comment]
Must be a very old fire tablet if it doesn't support the logs. That will also explain the WebView issue because those tablets are stuck on an old version until Amazon updates them. If they decide to update it. Unfortunately the only way to get the logs off that device is to use adb logcat.

**Comment by dshokouhi** [comment]
Closing as the app will not be able to fix this, most likely this will be fixed by amazon releasing a more up to date webview and/or a HA frontend fix.
