### ISSUE TITLE
*Mmap playback* partial wakelock battery problem

### ISSUE THREAD

**Issue by nortuzar** [home-assistant/android#3135]
**Home Assistant Android version: 2022.11.0-full**

**Android version: 12**

**Phone model: Samsung galaxy s22 ultra**

**Home Assistant version: 2022.11.5**

**Description of problem:**

At night the phone start consuming a lot of battery. Using the following settings at night
```
Power saving ON
Mobile data OFF
Do not disturb
Always on display OFF
Location OFF
Bluetooth OFF
Wifi ON (good signal)
```
I checked the companion docs for troubleshooting, so I disable bluethoot ble beacon, delete some HACS cards that I was using in the main view, also the video feeds I change from LIVE to AUTO, but still the problem remains.

Using Better battery stats app I found that there is a process call `Mmap playback` that wont allow the phone to go deep sleep.

**Screenshot of problem:**
![Screenshot_20221203-042000](https://user-images.githubusercontent.com/55258023/205640466-17b2c002-a5c0-4ebf-8208-0ae0096a8c79.jpg)
![Screenshot_20221129-215723_Device care](https://user-images.githubusercontent.com/55258023/205640531-fbd8dc59-0060-439a-816b-3f5b27a8783a.jpg)

**Additional information:**
I checked my wife iphone and the same happen, hours and hours of background of the home assistant app.
I cant identify from where is this partial wakelock coming. The word **playback** is a hint for multimedia like video? Running eyemotion on anothe machine and using the motionEye add-on 

Here is the link I post in the community were dshokouhi was helping, but I share here to see if someone else could help or is suffering the same
https://community.home-assistant.io/t/background-usage-no-deep-sleep/495887/3

Any help or tip to found the problem is well received

**Comment by dshokouhi** [comment]
> also the video feeds I change from LIVE to AUTO, but still the problem remains.

Actually you need to make sure taht you do not leave the app with any of the videos in view. You need to move them to another tab and make sure you are on a tab without a video playing.

Looking at what `mmap` is it is indeed multimedia.

https://source.android.com/docs/core/audio/aaudio



> delete some HACS cards that I was using in the main view

please try to disable all of them for this test and not just some.

**Comment by nortuzar** [comment]
> > also the video feeds I change from LIVE to AUTO, but still the problem remains.
> 
> Actually you need to make sure taht you do not leave the app with any of the videos in view. You need to move them to another tab and make sure you are on a tab without a video playing.
> 
> Looking at what `mmap` is it is indeed multimedia.
> 
> https://source.android.com/docs/core/audio/aaudio
> 
> > delete some HACS cards that I was using in the main view
> 
> please try to disable all of them for this test and not just some.

About your suggestions:
- I have the two videos on different views, not in the main one. So I return to the main one and then close the app
- I just have mushroom cards in the main view


I did a lot of troubleshooting today and I find something interesting. I have the webcams integrated in 3 ways, Generic camera, ONVIF and Motioneye. So I test changing the source of the picture-glance card and I found that the problem only appear when using the GENERIC CAMERA integration. Switching to the other sources makes the wakelock problem disappear.

Will do a long test tonight and share the results tomorrow

**Comment by nortuzar** [comment]
So I did the test and finally the problem is gone. I don't know if this is a issue/bug or a feature, but not using the camera generic integration feed on the cards fix the problem

Should I close this issue or can I help troubleshooting more regarding this?

@dshokouhi thanks for your help and patience

**Comment by dshokouhi** [comment]
This is not something the app can solve, I suspect you may see a similar issue using Chrome for android. Even if it doesnt exist in Chrome for android it is still a HA frontend issue as all the app does is load the site in WebView.
