### ISSUE TITLE
Android app very slow after upgrade to 2022.12

### ISSUE THREAD

**Issue by kongo09** [home-assistant/android#3146]
**Home Assistant Android version:**
2022.11.0-full

**Android version:**
13

**Phone model:**
Pixel 5

**Home Assistant version:**
Home Assistant 2022.12.1
Supervisor 2022.11.2
Frontend 20221208.0 - latest

**Last working Home Assistant release (if known):**
2022.11

**Description of problem:**
Android app loads very slowly, at first start but also when displaying cards. Sometimes, timeout dialogue shows at startup. Edge browser on same phone is very fast.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![Screenshot_20221210-101655](https://user-images.githubusercontent.com/640121/206842938-02e10bb0-4b59-4796-a0e6-943c9a83bb53.png)
![Screenshot_20221210-101658](https://user-images.githubusercontent.com/640121/206842940-699742ce-f8c9-4349-a30b-19b5b72075d2.png)

**Additional information:**

**Comment by thecobra666** [comment]
I have this issue on my galaxy s21 after a few days. Then I have to restart the phone for it to go away. All the other apps work just fine. Closing the app does not resolve it.

**Comment by MarcoNica** [comment]
Same here. Restart of phone solves the problem for a few days.
