### ISSUE TITLE
Quick Settings icon not reflecting the entity icon

### ISSUE THREAD

**Issue by stezak77** [home-assistant/android#3155]
**Home Assistant Android version:**
2022.11.0-full

**Android version:**
13

**Phone model:**
Samsung Galaxy A53 5G

**Home Assistant version:**
2022.11.5

**Description of problem:**
According to the documentation, an icon does NOT seem to be mandatory when setting up a tile, only label and entity seem to be mandatory:
https://companion.home-assistant.io/docs/integrations/android-quick-settings

> The app currently offers 12 tiles to setup. Each tile must have a label set and on Android 10 or newer can optionally have a sublabel set. A custom icon **can** also be used to help differentiate between the tiles. **After a label and entity have been selected you will be able to update the tile data.**
Once a tile has been added, the state, label and icon will update to reflect the entity's state and tile settings.

I don't find a way not to set an icon, and have the tile icon automatically reflect the entity icon which might dynamically change based on the entity state.

**Comment by jpelgrom** [comment]
This appears to be an oversight in the documentation - it is not possible to have the icon match the icon in Home Assistant automatically, also because the icons used for the tiles are a different version from what is used on your server probably.

Trying to use a custom icon if set like we do for device controls is a good feature request however :)

**Comment by stezak77** [comment]
Thanks for explaining. Definitely an enhancement to consider.
For the time being I'd suggest to correct the documentation as follows, to avoid misunderstandings:

> The app currently offers 12 tiles to setup. Each tile must have a label set and on Android 10 or newer can optionally have a sublabel set. A custom icon ~~can~~ **must** also be used to help differentiate between the tiles. After a label **, icon** and entity have been selected you will be able to update the tile data.
> Once a tile has been added, the state, label and icon will update to reflect the entity's state and tile settings.

**Comment by dshokouhi** [comment]
> For the time being I'd suggest to correct the documentation as follows, to avoid misunderstandings:

Please feel free to click on the Edit this page link at the bottom of the docs to submit any changes that should be added :)
