### ISSUE TITLE
Wear OS: Sensor update delay

### ISSUE THREAD

**Issue by adamaze** [home-assistant/android#3156]
**Home Assistant Android version:**
2022.11.0-full
**Android version:**
13
**Phone model:**
Pixel 6
**Watch model:**
Samsung Galaxy Watch 4
**Home Assistant version:**
2022.12.3
**Last working Home Assistant release (if known):**
not sure
**Description of problem:**
There are long stretches of time where none of the sensors from my watch send updates to HA. if i wake the watch and swipe around, I don't get any updates, but as soon as i open the HA app on the watch, it sends an update

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/9576629/207925572-1304083f-e6c6-4d94-b0e7-086194969127.png)

**Additional information:**

**Comment by dshokouhi** [comment]
We will need to see the logs of when this issue occurs to see what we can do.  Are the updates stopping completely or do they randomly start again? Have you checked to ensure teh app has background access in the samsung app?

The symptoms sound like the app is unable to run in the background here.

**Comment by adamaze** [comment]
I haven't been opening the app on the watch lately, so I'm not sure that would explain the updates. As you can see on the graph in my screenshot, it would seem that updates often restart shortly after the watch starts charging.

I just went in and set the "Galaxy Wearable" app to not have a battery restriction on my phone... so maybe that is the solution...

if it isnt the solution, when would it be useful to grab logs? next time I haven't seen updates for multiple hours?

**Comment by dshokouhi** [comment]
Well we do an intent based update when the device is charging and other times that we can. Our Sensor worker is responsible for setting the schedule to update frequently, roughly every 15-60 minutes but times will always vary there. If the app is killed then our schedule stops too. Can you confirm the app has background access in the samsung wearable app? I think you need to whitelist the Home Assistant app inside of that app. I dont have a Samsung device but I have seen a few users mention they can do that in that app.

**Comment by adamaze** [comment]
that sounds like it going to be the fix. i didn't even know that was an option, but i just set it.  If it sounds good to you, I'll wait a few days to be sure, and then come back and close this issue

**Comment by dshokouhi** [comment]
sure thats fine with me :)

**Comment by adamaze** [comment]
Looks good so far. Thanks for the help
