### ISSUE TITLE
Increase number of supported tiles 

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/android#3166]
**Is your feature request related to a problem? Please describe.**

As described in https://github.com/home-assistant/android/issues/1668#issuecomment-894600299 and first solved in https://github.com/home-assistant/android/pull/1744 , I would like to request another increase in tiles.

Now that automations are supported, I suggest increasing the number of available tiles to 30.

As the number of tiles need to be defined in the manifest, I was wondering if the amount of tiles can be very large and then in the companion app they are added when needed?

I.e., in the manifest 50 are defined.
In the companion app you see only one and one you hit a + sign, another one is created. And in the same way you can delete them via a -.
That way you do not need to search which tile is in use because in the app you only see those in use.

Do you know what I mean? Is this feasible?

Thank you :)

**Describe the solution you'd like**

See above :)

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by jpelgrom** [comment]
> In the companion app you see only one and one you hit a + sign, another one is created.

This is sort of how it works on Android 13: for tiles that haven't been added to the quick settings panel, you will be asked to add the tile to the quick settings panel if not already when saving it. On older Android versions, the app cannot prompt you to add a tile to the panel.

> And in the same way you can delete them via a -.

The app cannot delete tiles from the quick settings panel, so this seems unfeasible.

**Comment by AleXSR700** [comment]
> > In the companion app you see only one and one you hit a + sign, another one is created.
> 
> This is sort of how it works on Android 13: for tiles that haven't been added to the quick settings panel, you will be asked to add the tile to the quick settings panel when saving it *the button will show 'Add tile'. On older Android versions, the app cannot prompt you to add a tile to the panel.
> 
> > And in the same way you can delete them via a -.
> 
> The app cannot delete tiles from the quick settings panel, so this seems unfeasible.

In both cases I was taking companion app. The Android tiles will still all be there, waiting to be added. But in the app you will not see 50 tiles in the dropdown (unlike now where you see all 12 tiles whether they are in use or not).

So, defined number for Android OS but flexible number for companion app (with max being the number defined in manifest)

**Comment by AleXSR700** [comment]
And I was talking about setting up the tiles. You cannot see which tile is already in use. You have to go through them one by one to see which is the next empty spot.

But of course you can keep it as it is if you prefer. 


Then please increase the number of tiles to anything between 25 and 50 :)

**Comment by jpelgrom** [comment]
> You cannot see which tile is already in use. You have to go through them one by one to see which is the next empty spot.

Finding the next empty tile is easy when you add the tile to the quick settings panel, they are numbered for a reason :) The app could maybe do something to make it more obvious but that's another request.

**Comment by AleXSR700** [comment]
They have names once you use them, not numbers anymore. And you cannot delete the name. You have to define a name. So I would need to name them by their number.
Seems like a pretty unpretty approach to me ;)

**Comment by jpelgrom** [comment]
After removing tiles from the quick settings panel they should show the number again - but let's not discuss that here in depth.

**Comment by dshokouhi** [comment]
So whats a good amount to increase here? Currently we decided upon 12 because some devices show 12 tiles on a full screen. On my pixel I only have 8 per page.  Should we just stick to the highest number mentioned in this thread at 50?

**Comment by AleXSR700** [comment]
50 sounds good to me. I also see 12 per page. And with the growth of my systems, I think going bigger is better :)

**Comment by jpelgrom** [comment]
Wouldn't 50 add a lot of clutter to the tile list in the QS panel for most users who don't want to use that many tiles?

**Comment by dshokouhi** [comment]
[AutoNotification](https://play.google.com/store/apps/details?id=com.joaomgcd.autonotification&hl=en_US&gl=US) adds 40 to the list 🤷‍♂️  its only clutter for users wanting to add a tile and needing to scroll past the HA app list of tiles. 

Personally it doesn't bug me because I am not adding QS tiles all that often :)

**Comment by AleXSR700** [comment]
> Wouldn't 50 add a lot of clutter to the tile list in the QS panel for most users who don't want to use that many tiles?

As @dshokouhi said. Plus, Android kind of forces this "clutter" by not allowing on-the-fly creation of additional tiles.

**Comment by jpelgrom** [comment]
After testing it looks like the app might be able to enable/disable tiles (services) on request. It still needs to declare a number of tiles in advance, but this can be a high number now and hidden until needed.

**Comment by jpelgrom** [comment]
@AleXSR700 I've implemented the increased tiles changes as described in the previous comment, if you want to test it you could download the 'artifact' zip [from here](https://github.com/home-assistant/android/actions/runs/3802727388) and install the APK.
