### ISSUE TITLE
Integrated login of IP camera always fails

### ISSUE THREAD

**Issue by bravoJ456** [home-assistant/android#3169]
![1671613670246](https://user-images.githubusercontent.com/82761845/208865850-9087cfc4-8a9e-4a1b-89cf-cf10bdc42b41.png)
![1b0e8055c6be7a69006d8a1f11c8730](https://user-images.githubusercontent.com/82761845/208865861-97444fca-7afe-4ac5-bb2a-8a29852931e7.png)
![664d83746c416ed485861c75d9fc9f2](https://user-images.githubusercontent.com/82761845/208865868-3b640249-51e9-4dcf-9df5-53a8b4f577de.jpg)

**Comment by bravoJ456** [comment]
you eat shit

**Comment by jpelgrom** [comment]
This is not related to the Android companion app, please open an issue [in core](https://github.com/home-assistant/core/issues) for the integration instead.

**Comment by lcy-0408** [comment]
> you eat shit

OK honey, after eating it .I will kiss you
