### ISSUE TITLE
SM sending using the companion app

### ISSUE THREAD

**Issue by taczirjak** [home-assistant/android#3170]
**Is your feature request related to a problem? Please describe.**
I would like to use paid parking automation. In Hungary, we can start a car parking session by sending SMS to a specific phone number with the zone id of the parking zone. 

**Describe the solution you'd like**
I would like to be able to send SMS through my Android phone using a notification command like command_send_sms. It would ask for the phone number (+3620.....) and the message itself.

https://companion.home-assistant.io/docs/notifications/notification-commands/

**Describe alternatives you've considered, if any**
The alternative solution is using Joaoapps join, but for that, I would need to install an extra third party app.
https://www.home-assistant.io/integrations/joaoapps_join

**Additional context**
No

**Comment by dshokouhi** [comment]
Sorry our app does not qualify to send sms. You can only compose it using `command_activity`
