### ISSUE TITLE
Notify command_bluetooth only sends readable notification and no action

### ISSUE THREAD

**Issue by gypsydangr** [home-assistant/android#3171]
**Home Assistant Android version:**
2022.11.0-full
**Android version:**
13
**Phone model:**
Pixel 5a
**Home Assistant version:**
2022.12.7
**Last working Home Assistant release (if known):**
unknown
**Description of problem:**
when sending this service call it sends the notification as a readable message notification and not a command. Same issue as this previous one but with bluetooth this time not ble transmitter https://community.home-assistant.io/t/enable-ble-transmitter-via-notification-command-dont-work-anymore/396224

`service: notify.mobile_app_josh_pixel_5a
data:
  message: command_bluetooth
  data:
    command: turn_on`

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
This command is no longer available to devices running android 13 or newer due to new restrictions from Google.

https://companion.home-assistant.io/docs/notifications/notification-commands#bluetooth

More discussion on this in https://github.com/home-assistant/android/issues/3110

**Comment by gypsydangr** [comment]
Thank you for your reply. This is unfortunate, but understandable. I completely missed that "Android 12 or older"
