### ISSUE TITLE
Add Malayalam language

### ISSUE THREAD

**Issue by arunshekher** [home-assistant/android#3176]
Feature request related to adding Malayalam language translation.

Language name: Malayalam
Name in native script: മലയാളം
ISO 639-1 Code: ml

Have almost finished Home Assistant frontend Malayalam translation. I can join the translation team in Lokalise if this language is added there. 

Thanks & Regards

**Comment by dshokouhi** [comment]
The language has been added but I am having some difficulty finding your user name to grant you access to it. What is your lokalise user name?

**Comment by arunshekher** [comment]
Thank you so much for adding the language. I joined the android translation team in Lokalise and am able to create translations there. If my email id used in Lokalise is still needed for some admin purposes it is skepticautonetic 🤖 gmail.com

**Comment by dshokouhi** [comment]
as long as you are able to add translations i dont need to do anything else, we have some users who I need to add them as a contributor to the language before they can add updates so I have a habit of adding that :)
