### ISSUE TITLE
Quick settings buttons don't work

### ISSUE THREAD

**Issue by c7v** [home-assistant/android#3177]
View at buttons behavior and app: https://youtube.com/shorts/cdTrCt0kA6Y
maybe I missed some setting? Google translate :)

**Comment by jpelgrom** [comment]
Could you add the information from the issue template like versions, device model, and logs? That will allow us to help you faster.

Based on the video it looks like the app doesn't have network access when it is in the background, which makes the toggles unresponsive. Can you get the logs from the app (Settings > Companion app >Show and share logs) and see if there are any failures? Can you check in your phone's settings if there are any background limits for the app enabled, and if so reduce/disable them?

**Comment by c7v** [comment]
I'm sorry, this problem is on my side. There are two points to this problem. 1: reboot your phone. 2: make sure that the home assistant has access to the local network via HTTPS. Please request this «report».****
