### ISSUE TITLE
Vulnerability issue with Quick Settings on locked device

### ISSUE THREAD

**Issue by stezak77** [home-assistant/android#3183]
**Home Assistant Android version:**
2022.11.0-full

**Android version:**
13

**Phone model:**
Samsung Galaxy A53 5G

**Home Assistant version:**
2022.12.8

**Description of problem:**
Executing a tile action from the Quick Settings should require unlocking the device if it's locked.
Currently, if the phone is locked, anyone can click any Home Assistant configured tile and the related action takes place without requesting the user to unlock the phone.
This potentially represents a security issue for home automation.

According to Android Quick Settings guidelines:
https://developer.android.com/develop/ui/views/quicksettings-tiles#perform-only

> **Perform only safe actions on securely-locked devices**
> Your tile may display on top of the lock screen on locked devices. If the tile contains sensitive information, check the value of [isSecure()](https://developer.android.com/reference/android/service/quicksettings/TileService.html?utm_campaign=adp_series_quicksettingstiles_092916&utm_source=medium&utm_medium=blog#isSecure()) to determine whether the device is in a secure state, and your TileService should change its behavior accordingly.
> 
> If the tile action is safe to perform while locked, use [startActivity()](https://developer.android.com/reference/android/content/ContextWrapper#startActivity(android.content.Intent)) to launch an activity on top of the lock screen.
> 
> If the tile action is unsafe, use [unlockAndRun()](https://developer.android.com/reference/android/service/quicksettings/TileService#unlockAndRun(java.lang.Runnable)) to prompt the user to unlock their device. If successful, the system executes the [Runnable](https://developer.android.com/reference/java/lang/Runnable) object that you pass into this method.

I would expect that, after clicking on a tile of a locked phone, by default the user is promped to unlock it before the tile action gets executed.
Code should properly use mentioned [unlockAndRun()](https://developer.android.com/reference/android/service/quicksettings/TileService#unlockAndRun(java.lang.Runnable)) API for the described purpose.

**Comment by jpelgrom** [comment]
IMO this is not a security vulnerability but a feature request; I wouldn't consider something like toggling a light to be sensitive, but this will obviously depend on what action you've added to the tile.

An option was implemented for the device controls to choose what controls are available while locked (on Android 13, previous versions were always or never available when locked depending on the version), we could add something similar here.

**Comment by dshokouhi** [comment]
I agree this is indeed a feature request and not a bug. Probably needs to be handled on a per tile basis as only the user can determine what they want to cause an unlock action and what can be done without needing to unlock.

**Comment by stezak77** [comment]
Thank you. I agree this could be per tile basis.
I hope it can be implemented soon as I'm currently exposing sensitive actions to anyone who might take my even locked phone :-)
This is how the new setting could look when configuring the tile:

![image](https://user-images.githubusercontent.com/49878007/210062133-b6b63b34-41d5-4c67-a91d-8085886b1266.png)
