### ISSUE TITLE
On Android 11 the app crashes (even in background) when the defined URL is blocked at DNS level

### ISSUE THREAD

**Issue by bg1987** [home-assistant/android#3184]
Home Assistant Android version:
2022.11.0-full

Android version:
11

Phone model:
Samsung Galaxy S10E 5G

My public url is on the duckdns domain, and my workplace blocks duckdns domains, and all blocked domains are redirected to a "site blocked" landing page, 
even pinging the duckdns returns the ip of the "blocked" page. so im assuming its on the DNS level.

this usually simply caused the app to not function, which is expected.
but since the few latest updates (currently on 2022.12.0-full, android 11, galaxy s10e) the app enters a crash loop which keeps showing notification about it crashing every once in a while (once or twice at least pre day though)

**Comment by jpelgrom** [comment]
Can you check if the app recorded a crash log (Settings > Companion app > Show and share logs > Recent crash tab) and share it here?

**Comment by bg1987** [comment]
@jpelgrom I dont have a Recent Crash tab, just the full logs, which id rather not share right now as they contain too much sensitive info.

**Comment by jpelgrom** [comment]
When there's no tab the app wasn't able to save a crash log or the crash was >12 hours ago, it can happen. If you're comfortable using logcat (with an app or a computer) you can use that to search for crashes. Otherwise it will take a bit longer as the crash first needs to be reproduced 😉

**Comment by bg1987** [comment]
@jpelgrom 
I had a crash today, it happened in the background. 
and I realized that it ONLY happens while in background,
still no "recent crash" tab though in the app.

**Comment by jpelgrom** [comment]
There's no need to @ mention me every time.

Good to know it only happens while in the background. Does the app show an error message when it happens in the foreground?

Like I mentioned it can happen that the app is unable to save a crash log.

**Comment by bg1987** [comment]
it doesnt crash in the foreground, just shows a message the url cant be reached. and to try again or wait.

**Comment by Devenda** [comment]
I have a similar issue, I use a private IP address and when I leave home the connection does not work any more (as expected). However, every so often the app crashes showing the options to wait or kill the app.

I think the relevant part in the logs is included below (redacted IP address):
```log
01-06 15:38:55.970 11080 11163 E LaunchPresenter: Issue updating Registration
01-06 15:38:55.970 11080 11163 E LaunchPresenter: io.homeassistant.companion.android.common.data.integration.IntegrationException: java.net.SocketTimeoutException: failed to connect to /192.168.2.7 (port 80) from /xxx.xx.x.xxx (port 46074) after 10000ms
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.updateRegistration(IntegrationRepositoryImpl.kt:141)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$updateRegistration$1.invokeSuspend(Unknown Source:15)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: Caused by: java.net.SocketTimeoutException: failed to connect to /192.168.2.7 (port 80) from /xxx.xx.x.xxx (port 46074) after 10000ms
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at libcore.io.IoBridge.connect(IoBridge.java:179)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at java.net.Socket.connect(Socket.java:646)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-06 15:38:55.970 11080 11163 E LaunchPresenter: 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by dshokouhi** [comment]
if the error is indeed a failed to connect then it seems this is a duplicate or very closely related to #3152 

Should we really be using `throw` instead of just printing the exception/error? As I understand it `throw` will close the app

https://github.com/home-assistant/android/blob/e5191aed513b17d354b99fc7a822495ac9ab78a5/common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt#L141

https://github.com/home-assistant/android/blob/e5191aed513b17d354b99fc7a822495ac9ab78a5/common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt#L743

just to list a couple examples

One thing this doesn't answer is why is this an issue now as we had this code for a while now, maybe something changed in a dependency like a kotlin update?

In my case the URL is not blocked probably just hit an edge case in spotty service but the symptoms remain the same.

**Comment by Devenda** [comment]
Honestly, I have had this error for a very long time.
I'm not even sure that this has ever worked correctly.

**Comment by dshokouhi** [comment]
> Honestly, I have had this error for a very long time. I'm not even sure that this has ever worked correctly.

please in the future be sure to report issues immediately so the team can be aware to fix it.

**Comment by Devenda** [comment]
Don't get me wrong, this has only been a minor nuisance.
It does seems to have happened more often in the past with some moments of less frequent issues, but it has never appeared to be gone.

**Comment by jpelgrom** [comment]
Do you have the geocoded location sensor enabled by any chance? It looks like the app may not be handling exceptions properly for that one.

**Comment by Devenda** [comment]
Hmm, I had the 'geocoded location' sensor enabled.
My girlfriend, however, has this sensor disabled and does not have this error.

I will try disabling this sensor and will report back!

**Comment by dshokouhi** [comment]
> Hmm, I had the 'geocoded location' sensor enabled.

did you by chance have the "update with location sensors" setting enable for that sensor?

**Comment by Devenda** [comment]
I think not as this is not enabled by default but I'm not 100% sure.

**Comment by Devenda** [comment]
> Hmm, I had the 'geocoded location' sensor enabled. My girlfriend, however, has this sensor disabled and does not have this error.
> 
> I will try disabling this sensor and will report back!

Sadly

**Comment by Devenda** [comment]
Ok, it seems this is becoming more frequent. Did something change? Given that there is no real issue when this happens a crash and throw should not be happening I guess?

**Comment by Devenda** [comment]
I just found this issue:
#3226

So it seems that disabling all location sensors might be a workaround.

I will give that a try.

**Comment by dshokouhi** [comment]
As it looks like this issue maybe location related we had some changes go in the recent beta. I would suggest retesting against the latest beta. As we have not heard back from the original author on the crash log I am going to close this issue.
