### ISSUE TITLE
Prevent cloned/forked instances of the app from appearing in Sentry

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#3188]
**Is your feature request related to a problem? Please describe.**

Currently the app is storing the [Sentry ingest URL](https://github.com/home-assistant/android/blob/master/app/src/full/java/io/homeassistant/companion/android/CrashHandling.kt#L32) and anybody who forks the repo or clones the app  will also have all of the Sentry data sent over under our account.

**Describe the solution you'd like**

Prevent these forks/clones from appearing in Sentry as we do not need to care about them.

**Describe alternatives you've considered, if any**

No alternatives, I think here we need to use the keystore to prevent this? I am not entirely sure how to solve this but it would be nice to remove this clutter from Sentry.

**Additional context**

Note the package names:

![image](https://user-images.githubusercontent.com/1634145/210103950-1350ffe3-b567-47fb-af15-2112be234294.png)

**Comment by jpelgrom** [comment]
Would forks be enough or would it also have to handle weird app cloning tools like in #3187? For forks the DSN could be put in a config file or environment variable instead like for Firebase URLs / version names (with an invalid default value).

**Comment by dshokouhi** [comment]
Honestly I am not sure, I have seen these odd packages in Sentry for a while now and after seeing the same package in #3187 it made me want to create this issue. I discussed this very briefly with @JBassett previously but I am not sure if the variable will work with the cloning tool 🤔
