### ISSUE TITLE
Device not connected to local push notifications

### ISSUE THREAD

**Issue by tonyt2975** [home-assistant/android#3194]
**Home Assistant Android version:**
2022.12.0

**Android version:**
13

**Phone model:**
Pixel Pro 7

**Home Assistant version:**
2022.12.8

**Last working Home Assistant release (if known):**

**Description of problem:**

When using notify.notify I am not seeing a notification on my Pixel Phone.  I have recently changes to this phone from a OnePlus 9 which worked ok.
If I use notify and directly target the pixel, it will work.
I have tried the fresh app onboarding but have not gone as far as deleting the app.  I have also enabled and disabled persistent notification.  I have had some great guidance from the HA community but so far nothing is showing itself.
Logs show Websocket and fire base are starting but I just keep getting the above error.

Any help greatly appreciated.

As always thank you for the great work

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Please try the start fresh steps and ensure that all devices no longer in use are also removed from the integration list.

https://companion.home-assistant.io/docs/troubleshooting/faqs#starting-fresh-with-the-android-app

Please do not skip a step in the above process it's designed to avoid auto backup. Also please test with the actual device service call instead of the generic `notify.notify` call

**Comment by tonyt2975** [comment]
Followed the steps and adding the device again had no problems. 
The notify.notify is still not working on this device.  
If I use the actual device service call, it will work fine, so this may have to be my workaround.
As always, many thanks for you assistance in trying to sort this.

**Comment by dshokouhi** [comment]
> The notify.notify is still not working on this device.\nIf I use the actual device service call, it will work fine

In this case it sounds like an issue for HA core as the actual service call works.

**Comment by dshokouhi** [comment]
Closing as this issue seems to be HA core related since the app provided service call works.
