### ISSUE TITLE
Three sensors cannot be activated in mobile app

### ISSUE THREAD

**Issue by dreimer1986** [home-assistant/android#3197]
**Home Assistant Android version:**
Beta 3044

**Android version:**
11 Wear OS

**Phone model:**
Samsung Galaxy Watch 5 Pro

**Home Assistant version:**
2023.1.0

**Last working Home Assistant release (if known):**
None

**Description of problem:**
The phone state sensors, sim sensors and mobile data sensors cannot be switched on. Trying to do so just does nothing and the switch stays on off 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
We will need to see logs in order to investigate this issue.

**Comment by dshokouhi** [comment]
It is also possible you may have skipped the permission prompt the first time it showed up, android will not show the permission prompt again in cases like that. Please check the app has the phone permission otherwise the sensors will indeed not turn on.

**Comment by dreimer1986** [comment]
All rights are enabled over here. That was the first thing I verified.
I created two logcats. One quite... complete and one I tried to slim down. Both show starting app, go to sensor settings and selecting the three sensors several times.
[2x logcat.zip](https://github.com/home-assistant/android/files/10336447/2x.logcat.zip)

**Comment by dshokouhi** [comment]
Can you please check if one of hte app permissions is for Phone? Based on the symptoms, as I don't see any crashes or caught errors in the logs, it seems its still not granting the permission. The only thing related I see in the log is.

```
01-03 12:56:39.944  8421  8421 V GrantPermissionsActivity: Permission grant result requestId=-3333353091258395562 callingUid=10142 callingPackage=io.homeassistant.companion.android permission=android.permission.READ_PHONE_STATE isImplicit=false result=1
```

part of sensor logic is not to enable a sensor if permissions are not granted but required for the feature.

**Comment by dreimer1986** [comment]
I think I found the problem. Yes, I activated all permissions for the app you can... But in my case app permissions look like this:
![PXL_20230104_002755825 MP](https://user-images.githubusercontent.com/29841368/210463297-02a3abbf-89fc-4ab6-a6aa-e8faa61c1d3e.jpg)
The app is not listed in phone permission list in permission manager either. So there seems to be no way to enable phone permissions at all?

**Comment by dshokouhi** [comment]
I think I see the issue, we forgot to declare the permission in our manifest as well 🤦‍♂️  I just submitted #3200 to address this. Thanks for reporting!

**Comment by dshokouhi** [comment]
@dreimer1986  can you please test the debug APK as I do not have a LTE watch so the sensors do not show up on my device. You'll need to download the artifact from

https://github.com/home-assistant/android/actions/runs/3834155765

then extract it and install the wear APK, you may also need to install the full phone apk as well for this test. You'll want to make sure to give the devices a different name than what is in HA and it will be safe to delete after testing. Just enable the sensors and see if they turn on and stay on for this test.

**Comment by dreimer1986** [comment]
Installed both debug full on phone and wear on watch. Right now I can confirm that the three settings can be selected and stay on. But like quite a few more these sensors just stay on unknown state. I keep them running side by side to the non debug builds for a while now and after I am back home and managed to charge the watch I will give the final state. Maybe you want another logcat? Like from reboot to see what the app does regarding the unknown state sensors?

**Comment by dshokouhi** [comment]
> But like quite a few more these sensors just stay on unknown state.

yea known core issue, it will correct itself the next time the state changes or the app re-registers the sensors

https://github.com/home-assistant/core/issues/79837

thanks for confirming the fix works :)

**Comment by dreimer1986** [comment]
We will see ^^ I had to shut down the watch now as I tinkered a bit too much today and thus the battery is dead. If the watch really sends me the SIM provider after a while on the charger, I can happily confirm it working fine. But yes, the main reason for this report if successfully fixed ^^

**Comment by dshokouhi** [comment]
> If the watch really sends me the SIM provider after a while on the charger, I can happily confirm it working fine.

it wont send an update then, only will send an update on a state change for the sensor itself or when sensors get re-registered which happens anytime the app is updated or HA core is updated. We do a version check every 4 hours to test if HA core was changed to re-register.

The only way to really check the state sent now is to look at debug logging from the mobile app integration as you will see the update and register statements but since these sensors dont update often youd need to disable and re-enable. Its ok if you dont want to test it, its the same API from the phone and its running android so I have faith the state will be fine :)

just knowing the sensor will remain enabled is good enough given the described issue :)

**Comment by dreimer1986** [comment]
Alright. Then I wait for the final non debug version. I already use some sensors the debug app calls unknown and I compared the results of the debug and non debug and can confirm it has WAY less unknown. Or more precisely only one unknown state can be found there. The device tracker. But this is another report ^^ So I think we can close this one.
