### ISSUE TITLE
Sensor With Device Mac Address

### ISSUE THREAD

**Issue by soloam** [home-assistant/android#3199]
**Is your feature request related to a problem? Please describe.**

No, it's a feature to improve information provided to Home Assistant, and allow to use in automations 

**Describe the solution you'd like**

A sensor containing the wifi Mac Address of the phone, this could be either the random Mac Address or the device Mac address, also it could have a attribute that would be true or false if the mac address is random, or not 

**Describe alternatives you've considered, if any**

No real alternative, a sensor is the best approach 

**Additional context**

None

**Comment by dshokouhi** [comment]
I am not sure how doable this will be

https://developer.android.com/training/articles/user-data-ids#mac-addresses

`
For these reasons, to protect user privacy, on Android versions 6 and higher, access to MAC addresses is restricted to system apps. Third-party apps can't access them.
`

**Comment by dshokouhi** [comment]
Closing as this is not feasible, it will only work on the lowest supported version which has less than 1% user base.
