### ISSUE TITLE
Implement UnifiedPush (NTFY) notifications

### ISSUE THREAD

**Issue by Rudd-O** [home-assistant/android#3206]
Those of us that use the F-Droid version / no Google Play Services can get notifications (service `notify.notify`) just fine when we are in our LAN.  But when we go mobile — even if a VPN is on — Home Assistant does not reconnect in the background to the websocket push notification endpoint, no matter what the settings may be.

This feature request is to ask for the implementation of UnifiedPush (like several open source Android apps already do, such as Element).  UnifiedPush allows the app to register a "channel" with an open notification server (which may be self-hosted) and then tell the server (in this case, Home Assistant) to route notifications through said channel.  The local Android system (in most cases a local install of NTFY) is then connected to the notification server, and any notifications coming through the "channel" get relayed to the relevant app (in this case, the Companion app).

This would solve the problem of getting no notifications unless married to the Firebase messaging system that Google Play Services implements.

Thank you.

**Comment by Rudd-O** [comment]
No, it's not a bug the Companion app can work around.

If I disconnect from my Wi-Fi and then connect to the VPN, Home Assistant won't notify me.

If I **then** open Home Assistant Companion, from then on, Home Assistant will notify me — provided that my VPN does not disconnect and reconnect.

This is not something the Companion app can fix, because the Companion app is *not running* right after I connect to VPN, so it can't know to reestablish the websocket push.

**Comment by applesoff** [comment]
Any new info on unified push. Home assistant is drawing 42% of my daily battery usage on graphene is and I would like to not have persistent connection turned on

**Comment by GloriamSemper** [comment]
This would be such an awesome addition. HA android app is the ONLY app on my phone that still requires google FCM to receive notifications. It's the only reason I have the gapps on my phone. I'm tempted to just fork the app and then create an addon for the HA server to get this going.

**Comment by Rudd-O** [comment]
Echoing @applesoff here, my phone has one massive battery drain which is Home Assistant Companion (minimal) because I must use the "always on" setting for persistent connections, I cannot get notifications to the app otherwise, and this is causing enormous battery drain.

The requisite that HA Core support NTFY is already met — HA Core already has NTFY support now.

**Comment by Rudd-O** [comment]
I've opened a thread on Discord offering to fund the development of this feature:

https://discord.com/channels/330944238910963714/1284965926336335993/threads/1454856120664588368
