### ISSUE TITLE
High accuracy mode outside zone did not work well in version 2022.12

### ISSUE THREAD

**Issue by jbrepogmailcom** [home-assistant/android#3207]
**Home Assistant Android version:**
2022.12

**Android version:**
12

**Phone model:**
Samsung

**Home Assistant version:**
some

**Last working Home Assistant release (if known):**
2022.11

**Description of problem:**

I have generally high accuracy mode turned off and activated only if I approach extended zone of my home, but not home zone, which is inside extended zone. It worked correctly, but next day after upgrade to 2022.12, the high accuracy mode turned on when I was in my home zone. I checked on the device position and it was correctly showing at home. The high accuracy mode should be turned off as was alwas with version 2022.11, because I entered home zone, which is inside extended zone.

I upgraded to latest beta and so far high accuracy mode is off, so solved for time being.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
In order to help troubleshoot we need the logs from when teh issue occurred. Otherwise we will not be able to help because teh logs will tell us why it turned on.

Given this last statement I am going to close this bug

> I upgraded to latest beta and so far high accuracy mode is off, so solved for time being.

If you still experience issue please reply back with the logs so we can open and investigate.
