### ISSUE TITLE
Wear Home assistant Huawei watch 3 pro

### ISSUE THREAD

**Issue by onorbe** [home-assistant/android#3223]
its possible get home assistant waer version for huawei watch 3 pro?
I try a lot of way but i cant install it.

Thanks in advance.

**Comment by dshokouhi** [comment]
This is not a wear os device, sorry we can't support it.

**Comment by onorbe** [comment]
but is android. you can work with apks.
you can install whatsapp and different things.
i installed home-assistant but cant login.

**Comment by R0nd** [comment]
Actually getting it to run on HarmonyOS isn't that much work, GMS is only used for the onboarding process. It would even be possible to fix onboarding if the phone app integrated HMS in addition to GMS.
Check out my degoogled version, I run it on my Watch 4 Pro but the auth token has to be typed in manually

**Comment by asporykhin** [comment]
@R0nd Is it possible to get your degoogled version as an apk for Watch 3 Pro? Thank you.

**Comment by asporykhin** [comment]
@R0nd Would it be possible for you to share the apk file? I'd like to test it on Watch 3 Pro.  Thanks in advance!

**Comment by onorbe** [comment]
Also with me??

**Comment by MomosX** [comment]
Hi @R0nd , i just bought a Huawei Watch 4 Pro.  Would you be so kind as to share the apk ? 

Thank you !

**Comment by dshokouhi** [comment]
Guys I'm going to lock this issue soon, we are not a support thread for another app.

**Comment by Tehral** [comment]
is it usable with gt 4 huawei?
