### ISSUE TITLE
Enter the conversation feature's transcribed text into a Home Assistant sensor

### ISSUE THREAD

**Issue by keassol** [home-assistant/android#3224]
**Is your feature request related to a problem? Please describe.**

Trying to send some open ended transcribe text to a remote API.  The Rhasspy like voice assistants only transcribed words it has been trained on but the conversation function in the companion app already does full transcription so it would be helpful to get that entered into a sensor that HA can interact with.

**Describe the solution you'd like**

Say something into my phone (HA companion app) with the conversation feature active and have that sentence/phrase be entered into a sensor on the HA server.

**Describe alternatives you've considered, if any**

**Additional context**

See: [this post](https://community.rhasspy.org/t/how-to-get-rhasspy-not-to-ignore-words-that-are-not-in-sentance-when-spoken-into-the-microphone/4247) on the Rhasspy forum and [this post](https://community.home-assistant.io/t/how-to-get-data-spoken-into-the-companion-app-conversation/517903) on the Home Assistant forum

**Comment by dshokouhi** [comment]
This is actually out of scope for the app. For this you will want to create a conversation agent like [almond](https://www.home-assistant.io/integrations/almond/) to get the data you need from conversations.

**Comment by keassol** [comment]
Thank you for the response.  It looks like almond is no longer active.  Cannot be installed in HA and the URL to the project no longer works: https://almond.stanford.edu/  Looks like it is maybe in the process of being replaced with Genie https://genie.stanford.edu/  I will look into that.  Thank you.

**Comment by synesthesiam** [comment]
Hi @keassol, what @dshokouhi means is that you should create a custom conversation agent [like the almond add-on did](https://github.com/home-assistant/core/blob/8dadbe45fa3f566f10ec125a059c7a2aec52ac68/homeassistant/components/almond/__init__.py#L251), including a call to `conversation.async_set_agent` to register it. Then, you can do anything with the text in `async_process` within the agent's class.

**Comment by keassol** [comment]
Im afraid thats just a bit, well frankly, a lot out of my league. Maybe this is out of the scope of this feature request but let me ask a question, maybe its already happening and I missed something in the documentation.

So I open up the companion app, press the 3 dots and click "start conversation".  I hear the prompt and say "How many moons does Saturn have" and it fully transcribes "How many moons does Saturn have" in the dialog box representing my end of the conversation.  Does that "How many moons does Saturn have" get sent to the HA server to check for intents as an event or sensor update or something?  

I mean, If I say "turn off the office light" it sends something to HA to check for intents.  Is there anyway to get that raw sentence into HA? Is there any way to have a default/fall over intent so that anything that isnt understood by the other intent is run against this default one?

Sorry to tack onto a closed ticket, Im just so darn close to accomplishing this. Thank you for all the excellent work your doing!!

**Comment by dshokouhi** [comment]
> Does that "How many moons does Saturn have" get sent to the HA server to check for intents as an event or sensor update or something?

Correct we send that transcription to the HA API and then show the result

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt#L597


> I mean, If I say "turn off the office light" it sends something to HA to check for intents. Is there anyway to get that raw sentence into HA?

its already being sent to HA, if you want to get the response then you need create the agent as mentioned above.

>  Is there any way to have a default/fall over intent so that anything that isnt understood by the other intent is run against this default one?

Unrelated to the android app, more of a feature request in the HA forums for the `conversation` integration itself

**Comment by keassol** [comment]
> Correct we send that transcription to the HA API and then show the result

Great that exactly what I need. How can it be accessed in HA?  I dont see any events fired or entities updated.  If it is being sent to HA shouldnt there be a way for HA to interact with it?

> if you want to get the response then you need create the agent as mentioned above

Im not interested in the response because with these open ended questions the response from HA is always going to be "Sorry, I didnt understand that" which is fine since Im only interested in the transcript of the original question that gets asked.

Im sorry, Im afraid Ive gone in a circle here because I am back to my original feature request here.  If you are already sending the data to HA, couldnt you just make an additional webSocket call to update a sensor with that text or fire an event that can be listened for?

Thanks again!

**Comment by dshokouhi** [comment]
Sorry but we will not be able to do this, the correct way to do it was already mentioned up above.

**Comment by keassol** [comment]
OK.  Thank you very much for taking the time to answer my questions.
