### ISSUE TITLE
Wear OS Favorite Entities selections keep disappearing

### ISSUE THREAD

**Issue by Qoheleth** [home-assistant/android#3243]
**Home Assistant Android version:** 2022.12.0-full

**Android version:** 13

**Phone model:** Galaxy Fold 4 (SM-F936U)

**Home Assistant version:**

**Last working Home Assistant release (if known):** This has been an issue since I've tried using it (~2022.6)

**Description of problem:** When I set these on my phone, they appear as they’re supposed to on my watch (Samsung Galaxy Watch 5). Some time later, they start to disappear from my watch, often several at a time, but not all at once, inevitably they all disappear, sometimes even while I'm viewing them on the watch.
If I go back to the Companion app on my phone and re-select them, they’ll show up again until they start disappearing again some time later. This process my take a day or two to start, but always finishes within a few minutes.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:** (Left as it should be. Right after disappearence)
![ha-watch](https://user-images.githubusercontent.com/2237808/213516767-1d32d23e-1fb4-4cd4-ae07-813180301bfd.png)

**Additional information:** none

**Comment by dshokouhi** [comment]
Interesting the only time the favorites _should_ be removed is when the server does not respond with them in the list of entities we retrieved

https://github.com/home-assistant/android/blob/5cd74c0179f13b617de517273ec860215a8259ba/wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt#L126

Strange so some responses don't have the entities but some do? Wonder what would cause that 🤔 either way not a good experience if actual entities are getting removed.

**Comment by dshokouhi** [comment]
Confirmed with HA core developers that websocket responses are not paginated so the response should always have all entities. This is going to be tough to investigate where the potential loss is. One thing I wonder, when this issue happens do you see the entities in their respective area/domain after the removal? Part of me wonders if instead of trying to delete the entity we keep it as a `chip` without state data as its possible the chip will update later on with state data. We do offer a delete all option so users can clean up entities on their own without us trying to delete it when we believe the entity no longer exists

**Comment by Qoheleth** [comment]
Just a follow up with more data:
When my favorites disappear. I also can't find some entities under Areas. (For example, I can only see a scene in my Living Room, and only a light in my Dining Room.)  I can, however, find them all under More Entities which groups them by type (buttons, covers, etc.)

**Comment by dshokouhi** [comment]
Thanks for commenting back, this is helpful. I would've expected the same entity to be missing entirely instead of just from areas.

**Comment by dshokouhi** [comment]
So I wonder whats a good fix here, Its a bit unexpected for the same entity to be missing from Area but not the domain at the same time. I wonder if the entity was added back to the Area after checking the domain. 

Thinking about the fix I am thinking in the meantime lets just not delete a favorite and only create chips for entities we found after we got all the states. Its possible the entity will appear later if there was some type of pagination occurring that we are not expecting.

**Comment by jpelgrom** [comment]
> I can find my lights (Hue bulbs, light strip, and Bedroom Hue Group) in the "Bedroom" Area which is where it is set and in "All Entities" but looking in the "Lights" Domain those entities are all missing. 

Entities that are in areas don't show up in the domain (light) on the main screen, only in the area and all entities. This matches how the generated dashboard handles it.

Shouldn't influence the favorites though ...

**Comment by kiwikern** [comment]
I've had this issues from the beginning as well. One detail I wanted to add: For me, sometimes only some of my favorites disappear, the rest remains. However, the remaining ones will eventually also go missing.

**Comment by dshokouhi** [comment]
@kiwikern  please do not comment on old and closed issues. Instead open a new one if the issue still exists after updating to the latest version 2023.3.0
