### ISSUE TITLE
Android Auto Beta - Hidden Entities Appear in AA Home Assistant App UI

### ISSUE THREAD

**Issue by Nerwyn** [home-assistant/android#3250]
**Home Assistant Android version:**
beta-3074-d7ee3953-full

**Android version:**
13, Security Update December 5, 2022

**Phone model:**
Google Pixel 7 Pro

**Home Assistant version:**
Home Assistant 2023.1.6
Supervisor 2022.12.1
Operating System 9.4

**Last working Home Assistant release (if known):**
NA

**Description of problem:**
Hidden entities appear in the Android Auto Home Assistant UI.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
NA
```

```

**Screenshot of problem:**
Here are the lights in Android Auto
![PXL_20230121_031434434](https://user-images.githubusercontent.com/43071698/213841323-5348cdfc-8a4e-4245-a96c-998ca921d59c.jpg)

And here are my light entities. Note how the bulbs and UI created group are hidden.
![image](https://user-images.githubusercontent.com/43071698/213841340-a7e5fabf-fc28-471e-ad7d-562af977c54d.png)

**Additional information:**
NA

**Comment by jpelgrom** [comment]
This is correct as the Android Auto interface doesn't read any data from the entity registry yet, it is more like the large entities list without any filters. 

Changing the label to mark this as a feature request.
