### ISSUE TITLE
High Battery Usage and Logs Flooded "Faking releaseBufferCallback"

### ISSUE THREAD

**Issue by mike-lloyd03** [home-assistant/android#3258]
**Home Assistant Android version:**
2022.12.0-full

**Android version:**
13

**Phone model:**
Pixel 5

**Home Assistant version:**
 Home Assistant 2023.1.7 

**Last working Home Assistant release (if known):**

**Description of problem:**
Android app is using high battery and logs show hundreds of the following entry per second:

```
01-23 11:49:14.226 28853 28879 E BLASTBufferQueue: [VRI[SettingsActivity]#17](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
```

Full log dump here:
https://pastebin.com/CCMa9YXy

I'm not sure what this log entry means but I looked through the issues page here and only saw one other issue referencing it and it seems unrelated.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**
Running latest Graphene OS with Sandboxed Google Play services.

**Comment by dshokouhi** [comment]
I dont think that error message is related to the battery drain, please check these steps first for battery life issues

https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-app-battery-drain

Also as you are using a custom ROM the only supported version of the app is Minimal version.

**Comment by dshokouhi** [comment]
Based on your logs, more than likely your battery drain associated to the persistent connection being enabled (step 3 from above link). Given you are on a custom ROM you probably need that enabled for notifications? So its up to you if you want to use that feature or not given the battery drain you are experiencing.

**Comment by mike-lloyd03** [comment]
Thank you. I am using the persistent connection but I've been using it for months and it hasn't been an issue. These log entries are what I'm more curious about. 

I'll try switching notifications back to FCM and see if battery goes back down. 

One question on the sensor toggles: does "high accuracy mode" mean I am enabling a higher accuracy location feature, or is it just a sensor that shows whether "precise location" permission has been granted from the OS?

**Comment by dshokouhi** [comment]
> These log entries are what I'm more curious about.

the logs are unrelated, I see them too and do not experience any additional drain. I think they showed up after a google dependency update but haven't figured out from where. We don't use the buffer queue mentioned in our code.



> Thank you. I am using the persistent connection but I've been using it for months and it hasn't been an issue. These log entries are what I'm more curious about.
> 
> I'll try switching notifications back to FCM and see if battery goes back down.
> 
> One question on the sensor toggles: does "high accuracy mode" mean I am enabling a higher accuracy location feature, or is it just a sensor that shows whether "precise location" permission has been granted from the OS?
> 
> I had that on and that could have been the culprit.

the sensor reflects the state of [high accuracy mode](https://companion.home-assistant.io/docs/core/location#high-accuracy-mode), based on your logs it looks off at this time

```
01-23 11:45:20.740 28853 28853 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
```

**Comment by mike-lloyd03** [comment]
Okay thanks so much for the quick help. I think I saw the high battery and the flooded logs and assumed something was configured wrong on my end. All good now. Thanks.
