### ISSUE TITLE
Deactivate location in android tablet

### ISSUE THREAD

**Issue by yoghevos** [home-assistant/android#3259]
**Home Assistant Android version:** 2022.12-full

**Android version:**  13

**Phone model:* Samsung Tab A8

**Home Assistant version:** 2023.1

**Last working Home Assistant release (if known):**

**Description of problem:**

Hello.
I have an android tablet that I use at home and it’s almost never getting out of there.
Therefore I don’t see any reason why to use the location, so it’s toggle is always turned off, mostly because it doesn’t make any sense, and also to save power.

But the HA app refuses to open in that case, regardless to the fact that all of the device sensors of my tablet at the companion app, including the location sensors, are shut down.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
The location disabled notification will explain which feature you have enabled that is causing the issue. I am going to take a guess that you also had the Home Wifi SSID entered? If so that will not work when location is off as location is required to read the Wifi SSID. You will need to set the external URL and only that URL can be used.

**Comment by yoghevos** [comment]
Hello Daniel,

I did as you told me, I removed the SSID, and it worked.
And that raises the question, why?

If I have a mobile device that is just home use why I can't keep the SSID
and conact directly through the home network, without toggle the location
on all the time long.


בתאריך יום ג׳, 24 בינו׳ 2023, 00:01, מאת Daniel Shokouhi ‏<
***@***.***>:

**Comment by dshokouhi** [comment]
> Hello Daniel, I did as you told me, I removed the SSID, and it worked. And that raises the question, why? If I have a mobile device that is just home use why I can't keep the SSID and conact directly through the home network, without toggle the location on all the time long. 

That's a question for Google and not the app, it's an Android requirement.
