### ISSUE TITLE
Add support for CarInfo

### ISSUE THREAD

**Issue by superm1** [home-assistant/android#3260]
**Is your feature request related to a problem? Please describe.**

Add support to the mobile application for Android to request [CarInfo](https://developer.android.com/reference/androidx/car/app/hardware/info/CarInfo) information when connected to Android Auto.

Of particular interest to me is what the current connected car is and what the EV battery level is, but I can see tons of opportunity with other things that can be reported as well.

**Describe the solution you'd like**

Add sensors to indicate Car Information.

**Describe alternatives you've considered, if any**

Using EVNotify and OBD2 dongle to get EV level.  This is functional but a bit clunky and insecure.  Since Android auto offers such an API, it makes sense to me that the HA AA application should use it!

**Additional context**

This was found as part of reading through the [announcement for HA android auto support](https://www.home-assistant.io/blog/2023/01/20/android-auto/) and looking at the API documentation for AA.

**Comment by OzGav** [comment]
+1 this would be next level. I am also trying to pull info from the car using an OBD dongle but it is flaky at best. Access to EV battery level is also what I am after as well as total km (odometer)
