### ISSUE TITLE
Persistent notifications not apprearing on wear

### ISSUE THREAD

**Issue by alexd321** [home-assistant/android#3261]
**Home Assistant Android version:**
beta-3104-96cf4f82-full
**Wear app version**
beta-3104-96cf4f82
**wear OS version**
3.5
**wear model**
Samsung Galaxy watch 4 classic (8XMM)
**Android version:**
13
**Phone model:**
Samsung S21 Ultra 5G
**Home Assistant version:**
2023.1.6
**Last working Home Assistant release (if known):**
Unknown
**Description of problem:**
Not sure if this is a feature, but when

```persistent: true```

is set for a notification, it is not shown on android wear?

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
No crash
```

**Screenshot of problem:**
N/A
**Additional information:**
If you add to notification service persistent: true, nothing shows works on watch

**Comment by dshokouhi** [comment]
the app does not control relayed notifications, that is part of Wear OS.

**Comment by alexd321** [comment]
Ah OK,  seems to just be persistent ones, is it a wear bug/feature then?

**Comment by dshokouhi** [comment]
> is it a wear bug/feature then?

its a feature

https://developer.android.com/training/wearables/notifications/bridger#non-bridged

Closing as this is how its intended to work.
