### ISSUE TITLE
Add Sensor to support Samsung Modes

### ISSUE THREAD

**Issue by seanmccabe** [home-assistant/android#3263]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
See a sensor that reports the current phone mode. These modes I beleive are Samsung only and have the following defaults:

- Sleep
- Driving
- Exercise
- Relax
- Work

_There is likey another default mode which the phone is in by default_

This would be helpful to receive into HA to build out automations depending on what mode the phone has gone into. 

It would be great if the app supported changing those modes, but I know that may not be possible as its likely no exposed on the standard Android API

**Describe alternatives you've considered, if any**
N/A

**Additional context**
Can provide further information, images and testing if required (currently running beta version of app).

**Comment by dshokouhi** [comment]
These states are already available via the detected activity sensor which is available to all play certified devices and not just Samsung

https://companion.home-assistant.io/docs/core/sensors#activity-sensors

We will not be adding Samsung specific APIs here, if the Samsung app allows for intents you can use the existing intent system to integrate there.

Closing this request for now as the data is already available.

**Comment by seanmccabe** [comment]
These modes aren't the same as the "activity" sensor that is built into Android. These are akin the modes found on the old Nokia phones.
They allow setting the phone in a specific way based on triggers.

As setting the mode isn't an app, I can't see any intent option here.

**Comment by dshokouhi** [comment]
Unless its a documented android feature its not likely we will be able to add that. 

You can try to see if inspecting logcat when changing the modes leads to any intents. The on device logs will be the only way to tell unless Samsung has the intents documented in their own stuff. If it sends an intent you will see it printed in logcat.
