### ISSUE TITLE
Allow Tile to Trigger an Automation

### ISSUE THREAD

**Issue by bretterer** [home-assistant/android#3264]
**Is your feature request related to a problem? Please describe.**

Not related to a problem

**Describe the solution you'd like**

I would love to be able to trigger an automation through one of the tiles.  Right now, when using tiles towards an automation, it just enables/disables the automation vs triggering.

**Describe alternatives you've considered, if any**

I currently use widgets to call a webhook

**Additional context**

**Comment by dshokouhi** [comment]
have you considered using a `script` for the same `action` sequence of the automation? For the tile it would require some consideration to change from toggling the entity as opposed to triggering the entity. The `script` domain takes the same action sequence and can be used on the tile.

**Comment by jpelgrom** [comment]
All toggle-able entities toggle when using the quick settings tile, changing this for one entity type makes little sense to me. Even more so when considering the actions are also used in other places like device controls and the Wear app.

**Comment by dshokouhi** [comment]
Closing this request, if you really want this functionality move the automation action sequence to a script and just call the script from the tile. We should not change the way toggling entities work as it will have a wider impact. The correct approach is to use a script as scripts use the same sequence/syntax as the action part of an automation.
