### ISSUE TITLE
"Changes will be lost" warning missing when using Android system back button

### ISSUE THREAD

**Issue by deosrc** [home-assistant/android#3278]
**Home Assistant Android version:** 2022.11.0-full

**Android version:** 12

**Phone model:** OnePlus 9 Pro (LE2123) 

**Home Assistant version:** 2022.12.8

**Last working Home Assistant release (if known):** 

**Description of problem:**

When editing an automation, pressing the android system back button does not warn that changes will be lost. This is very easy to lose changes accidentally if you have a select open and instinctively press the back button to close it the select. Instead, all changes are lost. 

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

Steps to reproduce:

1. Open an existing automation for editing
2. Duplicate the automation using the options menu
3. Make some changes to the automation
4. Press the built-in android back button (not the back button within HA). 
5. The title of the automation will change indicating the new automation has been discarded and you are editing the original automation again.

There are other ways to trigger this but I believe this is the simplest and also most confusing as you could end up editing the wrong automation.

**Comment by dshokouhi** [comment]
Can you reproduce in chrome for android on the same device? most likely this is a HA frontend issue

**Comment by dshokouhi** [comment]
you should also update HA core to see if the issue is not solved in the recent release.

**Comment by deosrc** [comment]
> Can you reproduce in chrome for android on the same device? most likely this is a HA frontend issue

Just gave it a try in Firefox and the issue is there as well so I think you're right. I'll open this in the frontend repo.

Thanks

**Comment by deosrc** [comment]
> you should also update HA core to see if the issue is not solved in the recent release.

...after updating to latest
