### ISSUE TITLE
Calendar page is completely broken in Android app

### ISSUE THREAD

**Issue by ArcaEge** [home-assistant/android#3279]
**Home Assistant Android version:**
2023.1.7
**Android version:**
13
**Phone model:**
Pixel 4
**Home Assistant version:**
Supervisor 2023.1.1 Home assistant OS 9.4
**Last working Home Assistant release (if known):**
None
**Description of problem:**
When I open calendar page none of the buttons and checkboxes are responsive and no events are shown on the calendar.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Do you see the same issue in chrome for Android? I think this may be a frontend issue.

**Comment by dshokouhi** [comment]
duplicate of https://github.com/home-assistant/frontend/issues/15130

**Comment by ArcaEge** [comment]
Yes, it's broken on chrome as well. In fact, it's broken in chrome for desktop if the screen width is small enough so the navbar collapses
