### ISSUE TITLE
inability to log in using the enabled password in nginx

### ISSUE THREAD

**Issue by kva4991** [home-assistant/android#3283]
**Home Assistant Android version: 2023.1.1**

**Android version: 10.0.0**

**Phone model: redmi Note 7**

**Home Assistant version: 2023.1.7**

**Description of problem: 
In the "home assistant" there is an extension "Nginx Proxy Manager", which includes the function "Access Lists->Edit access list->Authorization-> [login: password]"
, which displays the authorization window in the browser when accessing HA.
When this setting is active (enable), it is impossible to log in to the Android application, I constantly see the authorization window, enter the credentials and see the authorization window again.
When the setting is disabled, everything works fine.
PS: everything works as expected normally in the browser. **

![изображение](https://user-images.githubusercontent.com/31066698/215355849-7022ee90-cf56-4017-8fd0-fee21543ecc9.png)

**Comment by dshokouhi** [comment]
Looks like this might be an add-on issue. The android app will only show this prompt any time the browser indicates its request HTTP authorization

https://developer.android.com/reference/android/webkit/WebViewClient#onReceivedHttpAuthRequest(android.webkit.WebView,%20android.webkit.HttpAuthHandler,%20java.lang.String,%20java.lang.String)

**Comment by dshokouhi** [comment]
closing due to lack of response
