### ISSUE TITLE
[FR] - Add Search function to Favorite Entities

### ISSUE THREAD

**Issue by seanmccabe** [home-assistant/android#3286]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add a search function to the Favorite Entities for the Wear OS app in the companion app. 
Very difficult to find what you want with hundreds of entries.

Whilst there, perhaps update the spelling to English, from Favorite to Favourite ;)

**Describe alternatives you've considered, if any**
No alternatives.

**Comment by dshokouhi** [comment]
> Add a search function to the Favorite Entities for the Wear OS app in the companion app.

In the phone app this should be doable, on the wearable itself not so much as the UI is not really built for search.



> perhaps update the spelling to English, from Favorite to Favourite ;)

HA documentation is to be in American-English the app should also be translated as such.

**Comment by jpelgrom** [comment]
> > perhaps update the spelling to English, from Favorite to Favourite ;)
> 
> HA documentation is to be in American-English the app should also be translated as such.

You could add it to the British English translation on Lokalise

**Comment by seanmccabe** [comment]
> > Add a search function to the Favorite Entities for the Wear OS app in the companion app.
> 
> In the phone app this should be doable, on the wearable itself not so much as the UI is not really built for search.
> 

No worries, I tend to use the phone for such things anyway due to the larger screen real-estate and speed.

> > perhaps update the spelling to English, from Favorite to Favourite ;)
> 
> HA documentation is to be in American-English the app should also be translated as such.

Should the app not be translated to localised? I.e. surely if I want it in German it's in German, should the same not be applied to English?

**Comment by seanmccabe** [comment]
> > > perhaps update the spelling to English, from Favorite to Favourite ;)
> > 
> > 
> > HA documentation is to be in American-English the app should also be translated as such.
> 
> You could add it to the British English translation on Lokalise

Would be happy to contribute, do you have a link of where to do this?

**Comment by dshokouhi** [comment]
> Should the app not be translated to localised? I.e. surely if I want it in German it's in German, should the same not be applied to English?

yes it should be



> Would be happy to contribute, do you have a link of where to do this?

https://lokalise.com/public/145814835dd655bc5ab0d0.36753359/

and also in general for anything translation related in HA you can find the lokalise sign up links: 

https://developers.home-assistant.io/docs/translations/

**Comment by jpelgrom** [comment]
This was actually implemented with the new entity picker in #3662 :)
