### ISSUE TITLE
Question: why google-services.json is not included?

### ISSUE THREAD

**Issue by rluvaton** [home-assistant/android#3288]
Why does the current `google-services.json` is not included?

If it's security concern Anyway, this file is in the apk at the end

**Comment by dshokouhi** [comment]
@rluvaton you should follow the project readme for setup instructions. Step 5 is different for every user. This is required for those developing notifications which requires a firebase setup. Its all explained in the readme.

**Comment by rluvaton** [comment]
Yeah, I read the README, but step 5 will have different file content based on their firebase project, but If I wanna use the  firebase project that the production app is using I can't

**Comment by dshokouhi** [comment]
> but If I wanna use the firebase project that the production app is using I can't

You should not be using that in a fork. You need to use your own.
