### ISSUE TITLE
Login attempt failed, ONLY happens on Android companion app not IOS app

### ISSUE THREAD

**Issue by dnestico** [home-assistant/android#3289]
**Home Assistant Android version:**
2023.1.1-full

**Android version:**
Android 13 (TQ1A.230105.002)

**Phone model:**
Pixel 7 Pro

**Home Assistant version:**
2023.1.7

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**
So I am paying and subscribed to the HA Cloud using Nabu Casa, it works fine when away on my Dads iPhone, it even sends us both notifications, the problem is ONLY THE ANDROID APP which is what I am using doesn't work when I open the app to see my dashboard. My Dad's iPhone companion app does not seem affected somehow.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:81
Integration: HTTP (documentation, issues)
First occurred: January 29, 2023 at 11:03:40 AM (69 occurrences)
Last logged: 7:14:04 PM

Login attempt or request with invalid authentication from localhost (127.0.0.1). Requested URL: '/auth/token'. (Home Assistant/2023.1.1-3124 (Android 13; Pixel 7 Pro))
Login attempt or request with invalid authentication from localhost (127.0.0.1). Requested URL: '/api/websocket'. (Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro Build/TQ1A.230105.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.50 Mobile Safari/537.36 Home Assistant/2023.1.1-3124 (Android 13; Pixel 7 Pro))

```

**Screenshot of problem:**
Here is a link to a screenshot. https://photos.app.goo.gl/S9aePy5NXnxBASt47 

**Additional information:**

Even though the app works on my Dads iPhone the log still did throw this, but again it still works and connects on his iPhone, unlike my Pixel 7 Pro which does not work.

```
Logger: frontend.js.latest.202301100
Source: components/system_log/__init__.py:256
First occurred: January 28, 2023 at 6:29:14 PM (43 occurrences)
Last logged: 7:27:37 PM

http://192.168.2.117:8123/homekit-infused/home?external_auth=1:0:0 Uncaught
http://192.168.2.117:8123/homekit-infused/home:0:0 Uncaught
http://192.168.2.117:8123/config/dashboard:0:0 Uncaught
https://URL/frontend_latest/app.c86c7218.js:850:114174 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "stack-in-card" has already been used with this registry
https://URL/frontend_latest/app.c86c7218.js:850:114174 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "swipe-card" has already been used with this registry
```

**Comment by dshokouhi** [comment]
Please double check the URL settings for the app by selecting "Settings" in the screenshot you shared, they may not be correct.

**Comment by dnestico** [comment]
Here is a screenshot in app, and as you can see the URL is correct, I am using this same URL on the IOS app.

![Screenshot_20230131-001616~2.png](https://user-images.githubusercontent.com/3034555/215672064-c724c867-7770-43e2-bbf0-aa91fee7e6d0.png)

And just to make sure here is a URL from my computer, working fine.

**Comment by jpelgrom** [comment]
Does the app work correctly when at home / when using the internal connection URL, or does it never work?

**Comment by dnestico** [comment]
The app works correctly at home yes, as soon as I get back on Wi-Fi the persistent connection starts again and the app works. Just once I switch that data connection on or leave my houses Wi-Fi the app stops working.

**Comment by dshokouhi** [comment]
What is the error in the companion app logs when you reproduce the issue? Is it trying the correct URL there or failing for a different URL?

**Comment by dnestico** [comment]
Sorry, it was late and I went to sleep.

The problem here is this doesn't always happen and it sometimes works so I haven't been able to recreate the error today I just tried, please keep this issue open because I will try again later since it seems to happen a lot on my phone.

**Comment by dshokouhi** [comment]
```
01-31 13:13:32.810  9897 28617 E WebSocketRepository: Unable to authenticate
01-31 13:13:32.810  9897 28617 E WebSocketRepository: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
```

I am seeing timeout errors here.

Did you always have Nabu Casa cloud setup or only recently? Can you try checking the external URL in app to see if its of an old value? It should be replaced with the cloud when you select that option but might be helpful to know if there is some other URL there.

**Comment by dnestico** [comment]
I have had nabu casa for probably a year now, also in the app I just use the "Use Home Assistant cloud" option I never put any external URL in

**Comment by jpelgrom** [comment]
Using the Nabu Casa URL from the original log file, I noticed that it defaults to using a trusted network. Do you remember if you logged in to the app using that or using a username/password?

**Comment by dnestico** [comment]
I do currently have trusted network setup and I think that might be the issue here, but only affects my Android. 

I just wanted to make it so no password is required locally but whenever I try to login remotely it says device not allowed so that might be blocking HA Cloud.

I can show my config if needed it might be wrong.

**Comment by dnestico** [comment]
How can I login to the app again? Is there a log out button I wasn't aware of this whole time lol

**Comment by jpelgrom** [comment]
You can log out on your profile, halfway down the page (red text).

**Comment by dnestico** [comment]
Ok so before I can continue what should I do here since it defaults to trusted network

![Screenshot_20230202-131922.png](https://user-images.githubusercontent.com/3034555/216412360-cc3102d1-0154-4d14-af87-ce8a73744ce4.png)

**Comment by jpelgrom** [comment]
You can tap on "Or log in with: Home Assistant Local" at the bottom of the page to log in using a username

**Comment by dnestico** [comment]
Ok I have now logged in with my username and password. I did notice though there is a notification that says Login Attempt Failed on the side even though I logged in with the username and password.

Here is what the HA log looks like but again Im logged in with the username and password so it worked.

<img width="1009" alt="Screen Shot 2023-02-02 at 1 25 47 PM" src="https://user-images.githubusercontent.com/3034555/216415191-a2120910-2c77-4f63-ba48-3b3dc6d13362.png">

**Comment by jpelgrom** [comment]
When logging out from the app it might generate a failed log in attempt, you can ignore it.

Does the app work correctly now when away (or disabling WiFi)?

**Comment by dnestico** [comment]
I just turned off the wifi and tested it on mobile data and it seems to have worked, will still be keeping an eye on it over the weekend as it seems to work the first time then if I come to the app again, later on, to check on it, it doesn't work anymore.

So ill let you know what happens soon.

**Comment by dnestico** [comment]
So this appears to be fixed after your solution, thanks!

Currently in the process of moving from an RPI4 to unRAID with Home assistant as a VM so I hope when I back up and restore there shouldn't be any issues again.

**Comment by simonlirwin** [comment]
For people coming here trying to look for other answers on this. I had login errors constantly blocking my IP. Spent months looking for a solution. Finally uninstalled the android app and created a new device name when I reinstalled. All worked fine after that.
