### ISSUE TITLE
Background Location sensor is not working properly when high accuracy mode is disabled.

### ISSUE THREAD

**Issue by fabrizioromanelli** [home-assistant/android#3295]
**Home Assistant Android version:** 2023.1.1-full

**Android version:** 12 SP1A.210812.016

**Phone model:** M3 Poco Pro 5G

**Home Assistant version:** Home Assistant 2023.1.7

**Last working Home Assistant release (if known):** none

**Description of problem:** The Background Location sensor is not working properly when high accuracy mode is not active. The permissions for location permission is "Allow all the time" for the Home Assistant App. This is what happens: when I activate the Location access on the phone (with high quality modality) the Home Assistant App does not access the Location and all the location services connected to the App does not work; in particular the Automations linked to the Background Location sensor of the phone could not work properly.
Similarly, when the Background Location sensor is enabled and the High accuracy mode is on with 10 seconds update interval, the location is always updated and it does not respect the update interval (the Location is always on, on the phone). In this modality, however, the Automations linked to the Background Location sensor work sometimes.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```
No crash to be reported.
```

**Screenshot of problem:** 
![image](https://user-images.githubusercontent.com/26959336/216029171-eec18a0e-6899-48ad-80c5-b26612dab19f.png)

**Additional information:** The MIUI version is: MIUI Global 13.0.7 stable

**Comment by dshokouhi** [comment]
Please get the logs and make sure they are about 10 minutes long so we can see what location is doing.

**Comment by dshokouhi** [comment]
closing due to lack of response
