### ISSUE TITLE
Notification does not restart the application and are received 15 minutes after the automation sent it

### ISSUE THREAD

**Issue by didrocks** [home-assistant/android#3296]
**Home Assistant Android version:** 2022.12.0-full

**Android version:** 11 RKQ1.201004.002 (running MIUI Global 12.0.2 Stable)

**Phone model:** Redmi Note 8

**Home Assistant version:**
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230110.0 - latest

**Last working Home Assistant release (if known):** None

**Description of problem:**

Notifications are received very late through the home assistant companion application. For instance, I have a reolink camera with person detection. The person detection event notification is received right away from reolink on my phone. The home assistant notification triggered by the same event is received many minutes later, up to 16 minutes in the last run.

I have checked that the automation triggers and sends right away the notification to the client. The notification is sent with `ttl: 0` as per documentation.

For instance, my automation has sent at 15:47 this notification:
```yaml
service: notify.notify
data:
  title: Some title
  message: Some message
  data:
    color: yellow
    notification_icon: mdi:ab-testing
    tag: foo
    visibility: public
    actions:
      - action: SOMETHING
        title: Something
    timeout: 300
    data:
      ttl: 0
      priority: high
```

At the same time, my device wakes up and show the Reolink notification that someone is detected. However, there is no notification from the Home Assistant side.

At 16:03, The phone wakes up and I finally receive the home assistant notification.

I have check for the permissions of Reolink vs Home Assistant applications: they can both run in the background (settings in the companion apps confirms that it can run in the background), I gave he OS the permissions to start the application too.

I didn’t enable the permanent connection described in https://companion.home-assistant.io/docs/notifications/notification-local, as it seems that Google sends them right away with the `ttl: 0` and `priority: high` as in https://companion.home-assistant.io/docs/notifications/critical-notifications?_highlight=ttl#android. In addition to that, between 15:47 and 16:03, my phone was turned on, and not stationary.

In the journal of the application, it seems that that the firebase cloud event through Google push did only starts the application at 16:03. Is there any reason the reolink app is able to be waken up by the notification framework from Google and the companion application is not despite the notification configuration?

Here are the logs for that period of time:

```
02-01 14:18:16.368 13075 13140 W FileUtils: Slow Operation: fsync took 434ms procState=10
02-01 14:18:16.369 13075 13075 W QueuedWork: Slow Operation: QueueWork waitToFinish took 255ms
--------- beginning of main
02-01 16:03:20.635 13075 13075 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-01 16:03:20.713 13075 13111 D UrlRepository: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
02-01 16:03:20.716 13075 13107 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=8c6f4be4-02a9-41cd-a116-5ce918b1cd76, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
02-01 16:03:26.240 13075 13075 D SensorReceiver: Received intent: android.os.action.DEVICE_IDLE_MODE_CHANGED
02-01 16:03:26.241 13075 13075 D SensorReceiver: Sensor is_idle corresponding to received event android.os.action.DEVICE_IDLE_MODE_CHANGED is disabled, skipping sensors update
02-01 16:03:26.957 13075 12302 W FirebaseMessaging: Unable to log event: analytics library is missing
02-01 16:03:26.957 13075 12302 D FCMService: From: 331041709873
02-01 16:03:26.970 13075 13075 D MessagingService: Creating notification with following data: {notification_icon=mdi:ab-testing, timeout=300, tag=foo, color=yellow, title=Some title, message=Some message, action_1_title=something, action_1_key=SOMETHING, visibility=public}
02-01 16:03:27.023 13075 13075 D MessagingService: Show notification with tag "foo" and id "101574"
```

**Screenshot of problem:**

No screenshot as this is not directly related to the UI.

**Additional information:**

I think one workaround would keep the permanent connection for local push, but the effect on battery would be more than noticeable. Also, the fact that other apps receives instant notification shows that there is probably a way to get the notification faster to the device, waking up the application on demand?

**Comment by dshokouhi** [comment]
You are using an invalid format for critical notification.

https://companion.home-assistant.io/docs/notifications/critical-notifications#android
