### ISSUE TITLE
How do I add the assist tile

### ISSUE THREAD

**Issue by danielbrunt57** [home-assistant/android#3302]
**Home Assistant Android version:**
2023.1.1-full
**Android version:**
13
**Phone model:**
Galaxy S22 Ultra
**Home Assistant version:**
2023.2.1
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
I cannot see or follow this...
After [installing the companion app](https://companion.home-assistant.io/docs/getting_started/) and connecting it to your Home Assistant, visit the Android WatchOS app and click “Add tile” inside the Tiles area. Select the “Assist” tile to add it to your watch.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**
N/A
**Screenshot of problem:**
N/A
**Additional information:**

**Comment by dshokouhi** [comment]
Hi the issue template that gets presented when you create an issue is important. Please add it back with all requested information so we can help you out. We do not know what app version or device you have for example.

**Comment by danielbrunt57** [comment]
Sorry, see above...

**Comment by dshokouhi** [comment]
what Wear OS watch is this?

**Comment by danielbrunt57** [comment]
TicWatch Pro 3 GPS

**Comment by dshokouhi** [comment]
First make sure the Wear OS app on the watch is updated in the play store. Then just add the tile like you normally would, same as any other tile from any other app. Here are some steps that Google provides, it may be slightly different on your TicWatch.

https://support.google.com/wearos/answer/9314375?hl=en

**Comment by danielbrunt57** [comment]
It was current already.  Finally remembered how to add a tile and now see Assist, which says `You must be on at least Home Assiatnt 2023. and have the conversation integration enabled`.  I have added `converation:` to my configuration.yaml since I do not have `default:` (as there is one I do not want) and restarting.  That should take care of it.  Sorry to have "cried wolf" and thanks for setting me straight!
