### ISSUE TITLE
Assist Tile on WearOS only works in English

### ISSUE THREAD

**Issue by Johnson145** [home-assistant/android#3308]
**Home Assistant Android version:**
2023.1.1-full

**Android version:**
13

**Phone model:**
Samsung Galaxy S22

**Smartwatch model:**
Samsung Galaxy Watch5 Pro

**Home Assistant version:**
2023.2.1

**Last working Home Assistant release (if known):**
none, feature is new and had this problem right from the beginning

**Description of problem:**
The new _Assist_ Tile on WearOS does not seem to respect the local language setting. My Android phone, smartwatch and app are set to German. However, the Assist tile only reacts to English statements.

When speaking German I only get the `Sorry, I couldn't understand that` response. It's literally the quoted English sentence, not sure whether that already indicates a wrong language usage? When opening the tile, there is a German sentence (`Noch keine Ergebnisse` meaning `No results yet`) though.

Doesn't matter which keyboard I use (tested Samsung keyboard and Gboard). Doesn't matter whether the keyboard language is set to German or English.

The Assist conversation in the web UI of home assistant correctly reacts to German.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

not applicable

**Screenshot of problem:**

not applicable

**Additional information:**

PS: From time to time, the Assist tile also just turns into a black screen. I guess that's an unrelated problem, but who knows. Couldn't figure out a reproducable pattern for this bug though.

**Comment by dshokouhi** [comment]
Are you using simple command like turn on the light? That is all that is really supported right now.

**Comment by dshokouhi** [comment]
Also is the speech recognition properly detecting your language before you accept the confirmation? It should stick to the default locale set on the device.

**Comment by Johnson145** [comment]
Yes, I'm just trying to turn on/off a light. On the watch, it works, if I say "Turn on the light in the kitchen.", but it does not work if I say "Schalte das Licht in der Küche ein.". When using the web UI, both sentences work.

Speech recognition performed by the keyboard is correctly detecting my language. The determined written sentence is correct. I can also just skip the speech recognition and enter the text manually with the same result. Result is also the same if I explicitly change the language of the keyboard.

To me it looks like the watch app isn't recognizing my localization correctly and instead tries to interpret all input as an English sentence.

**Comment by dshokouhi** [comment]
Can you please share a screenshot of the output and your response?

If speech recognition is properly detecting the language then the watch is recognizing it correctly and the issue may be on the server end.

**Comment by Johnson145** [comment]
Just started taking some screenshots, and suddenly it's working. I'm confused. I tested this a hundred times and it failed consistently before. You didn't publish any update for the watch yet, did you? In the meantime, I updated HA to 2023.2.2. Maybe that fixed it? Not sure. I'll close this issue and re-open it in case the error re-occurs. Thanks for you support!

**Comment by gelse** [comment]
I have the same problem, i hope it somehow automagically gets solved as well

**Comment by Slaw3km** [comment]
Same issue. Are there any plans to introduce other languages in WearOS?
