### ISSUE TITLE
Wear OS Notifications no vibration.

### ISSUE THREAD

**Issue by itkfilelor** [home-assistant/android#3310]
**Home Assistant Android version:**
**Phone:** 2023.1.1-full(3124) **Watch:** 2023.1.1(3125
**Android version:**
**Phone:** 12 **Watch:** 2.59.0.476832730.gms
**Phone model:**
**Phone:** Pixel 6  **Watch:** TicWatch Pro 3 GPS
**Home Assistant version:**
2023.2.0
**Last working Home Assistant release (if known):**
unknown
**Description of problem:**
Notifications to watch are do not make the watch vibrate. I can't say whether it makes noise or not as my watch only ever makes a sound for timers and alarms. /shrug
This is not an issue when I send the notification to my phone instead, both notify as intended
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by itkfilelor** [comment]
> Strange on my pixel watch it does vibrate but only when I am wearing the watch. Make sure to send the notification with the critical format so it speeds up delivery. Maybe the device doesn't vibrate if the notification is received when the screen turns on? As of now we don't have support for custom notification patterns so it goes by device default. Based on the comment regarding no sound unless it's a timer it may be related to that as well. What is the state of the ringer mode sensor on the watch?
OOPS! I meant to take that out before I sent! :grin: I forgot that when I got the watch I turned everything but alarms off for sound. And yes I thought of that. made no difference. 
Critical also did nothing, alarm_stream. nada.
hmm.

**Comment by dshokouhi** [comment]
hmm can you try checking the notification channel on the watch? Maybe try turning it on and off to see if that will change the behavior?

**Comment by dshokouhi** [comment]
hmm can you try checking the notification channel on the watch? Maybe try turning it on and off to see if that will change the behavior?

**Comment by itkfilelor** [comment]
> hmm can you try checking the notification channel on the watch? Maybe try turning it on and off to see if that will change the behavior?

That was one of the first things I tried :smile: Even tried using a custom channel still nothing :crying_cat_face:

**Comment by dshokouhi** [comment]
When I look online I see a lot of people with this particular issue needed to mess with their device settings. Some found the vibration was weak and could adjust the vibration in notification settings. Some found that needed to disable "do not disturb when off wrist" others even need to reset their watch.

**Comment by dshokouhi** [comment]
Can you try creating a new `channel` that you do not have currently and in addition to that set the [`vibration_pattern`](https://companion.home-assistant.io/docs/notifications/notifications-basic#notification-vibration-pattern)as well. The docs do not mention this is supported but really it has not been tested but it may work. 

on my pixel watch I do get a vibration but I just noticed that some devices may default to have it off if a vibration pattern is not set.

**Comment by itkfilelor** [comment]
> Can you try creating a new `channel` that you do not have currently and in addition to that set the [`vibrationPattern`](https://companion.home-assistant.io/docs/notifications/notifications-basic#notification-vibration-pattern)as well. The docs do not mention this is supported but really it has not been tested but it may work.
> 
> on my pixel watch I do get a vibration but I just noticed that some devices may default to have it off if a vibration pattern is not set.

Ok, so we have something!
setting vibrationPattern allows it to vibrate. however it doesn't want to accept custom values. Anything from an empty string to a complicated [stringified]array/ only ever yields a 1sec burst. progress is better than nothing =) At least its now a viable option for me. 
Also to note, once a notification is sent on that channel it seems to retain the vibration ability. Persistent thru restart.

**Comment by dshokouhi** [comment]
> Ok, so we have something!
> setting vibrationPattern allows it to vibrate. however it doesn't want to accept custom values. Anything from an empty string to a complicated [stringified]array/ only ever yields a 1sec burst. progress is better than nothing =) At least its now a viable option for me.

interesting on my pixel watch the vibration pattern is accepted and works as expected. What vibration pattern did you send? I was able to use a short pattern like `100` and also longer `1000` and both work. Did you make sure to use a new channel not used before when changing the pattern?



> Also to note, once a notification is sent on that channel it seems to retain the vibration ability. Persistent thru restart.

that is how notification channels work, settings can only be set the first time the channel is created which is why for the test I had asked you to create a new channel. So if you try a different vibration pattern then you need to use a new channel that has not been created. If you look at the [docs](https://companion.home-assistant.io/docs/notifications/notifications-basic/#specific-channel-properties) you can see the note mentioning about which settings only take place during channel creation.

I am not really sure how to proceed here, part of me thinks its best to let the device use its own default as we do offer options for these things. This might be best to leave it in the hands of the user as the app cannot predict device behavior.

In the meantime I have submitted an update to the docs to mention that we can set the vibration pattern.

**Comment by itkfilelor** [comment]
> > Ok, so we have something!
> > setting vibrationPattern allows it to vibrate. however it doesn't want to accept custom values. Anything from an empty string to a complicated [stringified]array/ only ever yields a 1sec burst. progress is better than nothing =) At least its now a viable option for me.
> 
> interesting on my pixel watch the vibration pattern is accepted and works as expected. What vibration pattern did you send? I was able to use a short pattern like `100` and also longer `1000` and both work. Did you make sure to use a new channel not used before when changing the pattern?
> 
> > Also to note, once a notification is sent on that channel it seems to retain the vibration ability. Persistent thru restart.
> 
> that is how notification channels work, settings can only be set the first time the channel is created which is why for the test I had asked you to create a new channel. So if you try a different vibration pattern then you need to use a new channel that has not been created. If you look at the [docs](https://companion.home-assistant.io/docs/notifications/notifications-basic/#specific-channel-properties) you can see the note mentioning about which settings only take place during channel creation.
> 
> I am not really sure how to proceed here, part of me thinks its best to let the device use its own default as we do offer options for these things. This might be best to leave it in the hands of the user as the app cannot predict device behavior.
> 
> In the meantime I have submitted an update to the docs to mention that we can set the vibration pattern.

Yes I created a (several actually as i suspected this was static after creation) new channel(s) I started with the example of 100,1000,100,1000... then for giggles reversed it, added variations etc. every attempt was a 1 second burst. Annoying but usable. I am hoping that when (if theyve been saying it for almost 2 years now) my watch gets the WearOs3 update it will fix things.

**Comment by jpelgrom** [comment]
> I started with the example of 100,1000,100,1000... then for giggles reversed it, added variations etc. every attempt was a 1 second burst. Annoying but usable. I am hoping that when (if theyve been saying it for almost 2 years now) my watch gets the WearOs3 update it will fix things.

On a Samsung Galaxy Watch 4 (with Wear OS 3) custom vibration patterns also aren't used so it looks like a 50/50 chance right now :)

**Comment by dshokouhi** [comment]
So it sounds like a couple things going on here:

- different manufacturers have different defaults for notification channels, some will vibrate and some will not
- vibration pattern will enable vibration but a custom pattern is not really accepted, will vary from device to device

I think the best way to move forward is to just mention this in the docs that if vibration is not used then the user will need to supply a vibration pattern

**Comment by dshokouhi** [comment]
updated my existing docs PR to mention this

https://github.com/home-assistant/companion.home-assistant/pull/904
