### ISSUE TITLE
Error handling message: Unauthorized (unauthorized) - subscribe_trigger requires admin

### ISSUE THREAD

**Issue by woniol** [home-assistant/android#3313]
### The problem

Since some time I get following error in the log:
_[547003404144] Error handling message: Unauthorized (unauthorized) from 192.168.0.1 (Home Assistant/beta-3146-9d8055f8-3146 (Android 13; SM-A525F))_
I think this might be related to the Android app communication part. As I remember, since some time the way android tiles are updated has changed to reflect the real state of the entity in the real time.

This is only happening if the user used for login is **not** Administrator

Please see the log below. Is it by desing that 'subscribe_trigger' method from websocket API work only with Admin users?

### What version of Home Assistant Core has the issue?

2023.2.2

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

WebSocket API

### Link to integration documentation on our website

https://developers.home-assistant.io/docs/api/websocket/

### Anything in the logs that might be useful for us?

```txt
2023-02-05 17:57:50.486 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547005097552] Received {'type': 'subscribe_trigger', 'trigger': {'platform': 'state', 'entity_id': ['cover.gate_garage']}, 'id': 38}
2023-02-05 17:57:50.487 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547005097552] Error handling message: Unauthorized (unauthorized) from 192.168.0.1 (Home Assistant/2023.1.1-3124 (Android 13; SM-A525F))
2023-02-05 17:57:50.495 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547005097552] Sending {"id":38,"type":"result","success":false,"error":{"code":"unauthorized","message":"Unauthorized"}}
```

**Comment by balloob** [comment]
`subscribe_trigger` requires admin access because a trigger can listen to any MQTT topic, any event etc.

**Comment by Eirik78** [comment]
> `subscribe_trigger` requires admin access because a trigger can listen to any MQTT topic, any event etc.

Do you say that having a non-admin being able to toggle a light or show a sensor state as an widget on the phone creates this error?

**Comment by dshokouhi** [comment]
> > `subscribe_trigger` requires admin access because a trigger can listen to any MQTT topic, any event etc.
> 
> Do you say that having a non-admin being able to toggle a light or show a sensor state as an widget on the phone creates this error?

No its just that in the app we use `subscribe_trigger` to update an entity without needing to subscribe to all updates (less chatty). We didn't realize its admin only when we started using it. Now that we know it needs to remain restricted we need to update our logic to use an API that a user can use.

**Comment by Eirik78** [comment]
Ah ok. Then I understand. Thank you!
