### ISSUE TITLE
Support "Night Mode" setting on/off - Android API call

### ISSUE THREAD

**Issue by ErgoPraxis** [home-assistant/android#3341]
**Is your feature request related to a problem? Please describe.**

No, this feature would add new functionality; the ability to turn on the blue screen filter (Night Mode) for the Android system. 

**Describe the solution you'd like**

Call the Android API to turn on/off Night Mode: [Dev Doc Link](https://developer.android.com/reference/android/app/UiModeManager#setNightMode(int))
This could use the Notification Commands, similar to how other screen settings can be set: [HA Companion Doc Link](https://companion.home-assistant.io/docs/notifications/notification-commands#auto-screen-brightness)

**Describe alternatives you've considered, if any**

No alternatives appear possible. This feature would have to make an Android API call.

**Additional context**

(ref discussion: https://community.home-assistant.io/t/activate-android-systems-night-mode-companion-app/536299)

**Comment by dshokouhi** [comment]
I assume for this request we should also add an accompanying sensor so the state can be [read](https://developer.android.com/reference/android/app/UiModeManager#getNightMode()) and used in automations

**Comment by jpelgrom** [comment]
Trying to modify the night mode gives me the following error (Android 13, Pixel device):

`2023-02-21 21:31:53.047  1790-5190  UiModeManager           system_server                        E  Night mode locked, requires MODIFY_DAY_NIGHT_MODE permission`

which has a [protection level of `signature|privileged`](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/AndroidManifest.xml#5859) so we're not qualifying for that. It does make sense to me, wouldn't want random apps modifying system settings.

**Comment by dshokouhi** [comment]
would be nice if Google updated the docs around this lol

**Comment by jpelgrom** [comment]
I think that's why the text is in italics but I'm not 100% sure. It also works if you're an OEM or developing the device software 😉

Should this issue be closed or changed to a feature request for a sensor to get the device's dark mode status (not sure how it would be useful personally)?

**Comment by dshokouhi** [comment]
I am personally leaning towards closing this issue as I also dont see the sensor being useful in this situation.

**Comment by ErgoPraxis** [comment]
Dang. Welp, time for HA community to become an OEM. Jk.

Agreed with leaning towards closing issue.

There could be a small use case for HA reacting to phone settings.
- User takes 1 step to active Night Mode on phone, HA runs automation for rest of environment.

But stuff like schedules from HA would be useless and/or other HA inputs. I feel like this would be the majority of use cases.

**Comment by dshokouhi** [comment]
Lets close this for now until a user who actually has a need for that sensor makes the request

**Comment by Bendoon** [comment]
Hi!

I was hoping that I would be able to use "bedtime mode" on android to start automations, would it be worth reopening this FR and seeing if the landscape has changed for this today?

**Comment by DeBendeBurcht** [comment]
I also would like to reopen this FR for a sensor that detects bedtime mode on android or wear os as my pixel watch automatically turns it on when i fall asleep, so i can run automations when that happens, havent found a good way to do this any other way yet

**Comment by kdkavanagh** [comment]
I have the exact same use case. It's so annoying when it turns on at some specified time when I really only want it when actually in bed. 

@dshokouhi thoughts on reopening?
