### ISSUE TITLE
Map: hours_to_show shows no plot

### ISSUE THREAD

**Issue by callerpj** [home-assistant/android#3348]
**Home Assistant Android app version(s):2023.1.1-full**

**Android version(s):13**

**Device model(s):Pixel 6**

**Home Assistant version:2023.2.5**

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:hours_to_show in maps doesn't show lines**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
This issue is missing a lot of data. Did you also check the issue in chrome for Android on the same device?

**Comment by callerpj** [comment]
You are right, it doesn't work in Chrome on same device either

**Comment by dshokouhi** [comment]
That means this is a frontend issue. As there is not enough data in this issue and the frontend has a different template. Please create a new issue with the HA frontend and make sure to fill out their template completely.
