### ISSUE TITLE
Valid values for Screen Brightness Level

### ISSUE THREAD

**Issue by nando63** [home-assistant/android#3356]
**Home Assistant Android app version(s):**
2023.1.1-full

**Android version(s):**
11 RKQ1

**Device model(s):**
XIAOMI MI 9T

**Home Assistant version:**
2023.2.1

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Notification commands - Screen Brightness Level
Valid values are between 0 and 255 ... but my phone max level is 4036

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**
![1676983619694](https://user-images.githubusercontent.com/17594925/220348931-82738cc9-3759-422f-886a-e476770266b2.jpg)

**Comment by dshokouhi** [comment]
According to Android official documentation accepted values are only between 0 and 255

https://developer.android.com/reference/android/provider/Settings.System#SCREEN_BRIGHTNESS
