### ISSUE TITLE
New Update UI Lights Switches Beta

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/android#3363]
**Device model(s):**
Samsung

**Screenshot or video of problem:**
![Screenshot_20230223-015808_Home Assistant.jpg](https://user-images.githubusercontent.com/42905545/220799832-8d93dee5-6b26-4265-a7cf-2e549c2a1f49.jpg)

**Additional information:**
Please delete attributes only on phones (look so bad or move to settings) or move to bottom, make switch bigger and add more to middle for bigger phones are very harder to controls with one hand.

**Comment by dshokouhi** [comment]
Please open an issue with the HA frontend, the android app does not control this

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=bug_report.yml

**Comment by milandzuris** [comment]
On this screen it can be seen better 
![Screenshot_20230223-022136_Home Assistant.jpg](https://user-images.githubusercontent.com/42905545/220801130-2505e76e-9651-4a75-afd0-2a065cd59f6e.jpg)

**Comment by milandzuris** [comment]
On this screen it can be seen better 
![Screenshot_20230223-022136_Home Assistant.jpg](https://user-images.githubusercontent.com/42905545/220801130-2505e76e-9651-4a75-afd0-2a065cd59f6e.jpg)

**Comment by milandzuris** [comment]
https://github.com/home-assistant/frontend/issues/15555
