### ISSUE TITLE
Beacon monitor (BackgroundScanPeriod)

### ISSUE THREAD

**Issue by leroyloren** [home-assistant/android#3367]
**Is your feature request related to a problem? Please describe.**
The background beacon setting does not respect the set value

**Describe the solution you'd like**
To match the scan period to the settings, at the moment the set scan interval only seems to work when the application is in the foreground

**Describe alternatives you've considered, if any**
If the scan interval is set to e.g. 1s, scan both in the foreground and in the background.

**Additional context**
https://altbeacon.github.io/android-beacon-library/javadoc/org/altbeacon/beacon/BeaconManager.html#setBackgroundMode(boolean)

**Comment by dshokouhi** [comment]
This method is deprecated and I think we already do this in the code.

**Comment by leroyloren** [comment]
Well it's hard to say, but it scans in the background for about 10+ sec, definitely not according to the set period.

**Comment by dshokouhi** [comment]
Are you using the beacon monitor sensor to determine that? Or something else?

We already have the sensor as part of a foreground service too.

**Comment by leroyloren** [comment]
Yes, beacon monitor sensor, de/activated by command_beacon_monitor

**Comment by dshokouhi** [comment]
Have you checked the logs to determine an error is not showing up at that time?

**Comment by leroyloren** [comment]
There are no errors, only the scan is considerably delayed, the expected 1s period is realistically min. 10s

**Comment by dshokouhi** [comment]
Are you seeing this behavior on phone or watch?

**Comment by leroyloren** [comment]
Phone

**Comment by dshokouhi** [comment]
Looking at the code we are indeed using the same scan period and interval for both foreground and background

https://github.com/home-assistant/android/blob/db63a38cd5fc2b26ecd02f8cb8b157bcd0aa110d/common/src/main/java/io/homeassistant/companion/android/common/bluetooth/ble/MonitoringManager.kt#L45-L48

Looking at altbeacon docs we may need to look into using a foreground service scan but this will mean a notification will be present. Your symptoms seem to be described here as well.

https://altbeacon.github.io/android-beacon-library/foreground-service.html

We do have our own foreground service for updating sensors but we may need a second one based on what I am reading here.

**Comment by dshokouhi** [comment]
Since it sounds like you are able to reproduce this pretty reliably I would appreciate it if you could test the debug APK by downloading the artifact from the below link.

https://github.com/home-assistant/android/actions/runs/4271958665

This will create a foreground service that will show a silent notification indicating scanning is in progress, as of now I want to check that it is continuing to scan in the background for long periods of time. Keep in mind you may see more battery drain as a result but that seems to be expected given the bug/feature request

**Comment by leroyloren** [comment]
The behavior seems to be the same. Scans come in between 10-30+sec.

Stable version:
![obrazek](https://user-images.githubusercontent.com/57643470/221403883-260ff8d1-6047-472f-8a24-6d15baa57583.png)

Artifact test:
![obrazek](https://user-images.githubusercontent.com/57643470/221403947-62ffc4be-3e35-4c2b-83ff-4e11512f5fbb.png)

**Comment by leroyloren** [comment]
So after further attempts I can say that it is definitely better, almost ideal. So I take back the previous message.

**Comment by dshokouhi** [comment]
Thank you for testing :)

**Comment by leroyloren** [comment]
I thank you and look forward to the beta release. ;-)
