### ISSUE TITLE
Add a few built-in notification sounds.

### ISSUE THREAD

**Issue by TRusselo** [home-assistant/android#3370]
**Is your feature request related to a problem? Please describe.**

Android does not allow custom notification sounds to be SENT to the device to play.
We cannot send a Doorbell sound to the phone to play for a Doorbell notification.
We cannot send an ALARM sound for ALARM type notifications.

iphones can...  (wow.. i  dont say that often... that hurt..)
https://companion.home-assistant.io/docs/notifications/notification-sounds

**Describe the solution you'd like**

Android CAN use custom notification sounds built into the app playing the notification.  (nest doorbell does it, discord does)
So add a few notification sounds:

A few basic bells, beeps and chirps for basic notifications.  (this is where Home Assistant team can be creative and set a flavor)
**_1 Default "Home Assistant" notification sound_**.
A doorbell chime.
An ALARM SOUND.  for critical alerts: alarm, flood, fire, smoke, CO

**Describe alternatives you've considered, if any**

Yes, currently, i do have a doorbell sound setup on my android device. MINE,  not every phone in the house...

1. i downloaded from a website, 
2. moved sound file to the /notifications folder on the android phone flash,  
3. home assistant automation for Doorbell notification is set to custom CHANNEL: Doorbell
4. then on the phone, android settings, notifications, home assistant, notification categories , find the doorbell channel, set a custom sound... 

Like yes it can be done... but do i really have to do that for every phone in the house???  (we dont have iphones)

And i just integrated an offline Security System into HA, and really want some ALARM notifications...  that is just going to require me to customize each phone in the house with custom files put onto the phone.

**Additional context**

ONE ADDED BONUS:
creating custom sounds for Home Assistant companion app for both ANDROID and IOS, can create some consistency, and can spark some friendly conversations when you are standing in line at the coffee shop and hear that "home assistant default notification" coming from the pocket of the guy next to you...  (even if it's an iphone)

My current Setup:

![image](https://user-images.githubusercontent.com/1154815/221393813-6dc01ebc-c346-4c4b-be37-60aa6d9b87f1.png)
![image](https://user-images.githubusercontent.com/1154815/221393871-ac7558e2-7d02-4de7-842f-8956a912ef58.png)

**Comment by dshokouhi** [comment]
> but do i really have to do that for every phone in the house??? (we dont have iphones)

yes you do have to do it on every phone in the house, although the app can provide custom sounds its up to the user to actually set them as the notification channel sound. We may be able to set them once during channel creation but that would be it.  Notification channels are designed for the user to be in control of the notification appearance and behavior, not so much on the app.  This is one of the platform differences between iOS and Android.

So would you still use this feature if you have to manually edit your notification channels? Also if the app tries to be "smart" and use a "Doorbell" notification channel that will not work for a user who already has that. I think at this point we can just add the sounds and let the users modify their existing channels, if that is what is desired. Not to mention this will also increase our app size depending on how many sounds we need to bring over. I think iOS has quite a bit of custom sounds.

**Comment by dshokouhi** [comment]
Looking at the list of apps that currently supply their own notification sounds on my phone I see a lot of duplicates. It seems the app needs to copy it's own audio to the correct location but given every single app has duplicates then our own list may get out of hand. I don't think we can delete audio once copied over either. I am not sure if this is something we should add support for given that users have complete control using channels.

![Screenshot_20230226-092550.png](https://user-images.githubusercontent.com/1634145/221426292-3c6c38db-fdc1-4a4e-b4be-0828d9c8dde7.png)

**Comment by TRusselo** [comment]
That appears to be something specific to slack
My phone has zero files added from other apps.
I cannot see nor use the notification sound provided by nest or discord.

**Comment by TRusselo** [comment]
My phone only has the built-in sounds from Samsung and the two files I copied into the notification folder myself.

You seem to be special

![Screenshot_20230227-165034_SecSoundPicker](https://user-images.githubusercontent.com/1154815/221715617-33068bff-ea08-44b6-84fc-90959b754805.jpg)

**Comment by dshokouhi** [comment]
> That appears to be something specific to slack.
> I don't use slack so I can't confirm.

Ring is there as well as old hangouts sound lol



> By chance were you editing notification sounds for the slack app when you grabbed that screenshot?

nope, actually picked a random HA notification to edit. All the sounds listed are available for any notification.



> I cannot see nor use the notification sound provided by nest nor discord.

So there is a difference when an app creates a channel and specifies a local file to the app directory vs. when an app copies the files to the appropriate location so they can be selected anywhere. The issue with channels is that once set a user has full control so if there is an app provided sound and the user changes the sound they cannot go back to app provided without clearing app data.

**Comment by TRusselo** [comment]
a user wouldn't need to change an existing sound file. They would just go into the app notification settings and choosing custom sound, as I have already done.

Many apps have default sounds, but allow you to set custom sounds

But I think we're getting far away from the point

 I'm not exactly requesting that the sound files be added for this one specific situation.  Channels might not be the best way to make use of built-in notifications. Or it might be...  To make full use of custom integrated sounds it might require a change to home assistant notify or something so you could pick one of the default sounds easily via the GUI for idiots.

I am just putting in a feature request, giving an example of a situation where it could be useful to people.

And yes I am totally able to edit every phone in my house and set them all up the way I want them to but I thought it might be easier for people (who aren't me) to have a few sounds to play with easily without any fuss.


But really the only reason I made the request is because...
I think it would be very nice if home assistant had "a default sound" regardless of platform. It could theoretically be played in the web UI as well.  And adding a few sounds directly in the app gives a few ways for people to get started, they can take it further from there if they want to go full custom.

**Comment by dreimer1986** [comment]
If I got things right you can in theory play custom sounds, but only if they are inside the app. I wonder why is that so? Why can't you just add a sounds panel where you can select sounds off internal NAND and apply these external audio files the same way as a internal one then? I don't see a reason for this not to work. Maybe someone can enlighten me here OR if the "idea" of mine is valid, maybe think about this as a not app bloating way to do that?

**Comment by dshokouhi** [comment]
> Channels might not be the best way to make use of built-in notifications

Channels are a requirement for all android apps posting a notification on a device running Android 8 or later. There is no way around that.



> If I got things right you can in theory play custom sounds, but only if they are inside the app. I wonder why is that so?

No you misunderstand. Apps can either provide their own sound for a new channel that they create or apps can copy local sound files to a specific location on the device so a user can access it to select the audio file. The first method means the app provides the sound and once a user changes it the app can no longer add back the audio, the latter method has the potential to clutter up a device and take up unneeded space as seen with some apps like Slack that uploads multiple copies of the same file.



> Why can't you just add a sounds panel where you can select sounds off internal NAND and apply these external audio files the same way as a internal one then?

thats the latter method and channels already take care of that.

As users on Android have channels they can add any sound they want to customize their own notification. If we add custom sounds now we may get more and more requests to add more sounds which can increase app size and may even potentially have a copyright issue. I am going to close this request as users can make use of existing android features to do the same thing. If the goal of this request was to have a unique Home Assistant specific ping then please file a request in the forums then once added to HA core we can look into adding into the app.
