### ISSUE TITLE
Microphone used binary sensor

### ISSUE THREAD

**Issue by bkbilly** [home-assistant/android#3371]
**Is your feature request related to a problem? Please describe.**

When I am on a call there is a sensor that says if the phone status is onhook or offhook, but this doesn't apply on other applications like messenger, viber, whatchapp, skype, etc...

**Describe the solution you'd like**

I would like to have a binary sensor on home assistant that checks if the microphone is used on my phone. This would be useful so that I can pause my music on my PC, or lowering the volume of my speakers.

**Describe alternatives you've considered, if any**

**Additional context**

It might also be useful a video used sensor.

**Comment by dshokouhi** [comment]
you can use the Audio Mode sensor which has either `in_communication` or `in_call` state for that purpose

https://companion.home-assistant.io/docs/core/sensors#audio-sensors

**Comment by bkbilly** [comment]
Thanks for pointing that out. Didn't notice it. :)
