### ISSUE TITLE
FR: Double tap camera widget to open app

### ISSUE THREAD

**Issue by conorlap** [home-assistant/android#3372]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

It would be nice to be able to double tap on the camera widget to fully open the HA app (will allow me to get into the live video feed to hear audio etc)

**Describe alternatives you've considered, if any**

N/A
**Additional context**

N/A

**Comment by dshokouhi** [comment]
I don't think double tap is a native feature of Android widgets. Tapping the widget is already reserved for updating the image.

**Comment by conorlap** [comment]
I see a few references on Google (albeit very outdated) about double tap to open an app on Android widgets

https://stackoverflow.com/questions/26871308/android-app-should-open-when-we-double-tap-on-widget
https://stackoverflow.com/questions/5070413/widget-double-click

Not sure if still possible but looks like it was in the past?

**Comment by dshokouhi** [comment]
Counting clicks sounds like a hack. There is no indication that it needs to happen quickly leaving it to app logic. I don't think we should do this. 

If you want to open the app from the home screen you should use features that support it like shortcuts.

**Comment by conorlap** [comment]
No problem, thanks for your feedback - in that case, I'll close this one out!
