### ISSUE TITLE
Allow the camera widget to resize based on image aspect ratio

### ISSUE THREAD

**Issue by conorlap** [home-assistant/android#3373]
**Is your feature request related to a problem? Please describe.**

It would help with the aesthetics - the camera widget could look more polished.
 
**Describe the solution you'd like**

Allow the camera widget to resize based on image aspect ratio so there are no black/grey bars and the widget looks more polished. 

**Describe alternatives you've considered, if any**

N/A

**Additional context**

N/A

**Comment by dshokouhi** [comment]
This may not be as easy as intended, we have to set a minimum size for the widget that fits the needs for most cameras on the average home screen size, currently its set for a 2x2 grid. Maybe it makes more sense for us to offer a transparent theme like the other widgets that offer theming? 

That should also address the design concerns too I think.

We do also resize the image

https://github.com/home-assistant/android/blob/f7cec0e5a2bb04b46a5d45464c8f53ac8dd23619/app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt#L156

Initially I was thinking we just needed to use the below API but I am not sure that will work as intended given the minimum widget size https://developer.android.com/reference/android/widget/ImageView.html#attr_android:adjustViewBounds

**Comment by conorlap** [comment]
Yeah the transparent theme would help if it gets rid of the grey/black bars! Although then the image wouldn't have rounded corners?

Is there a reason for 1024x600 for sizing? Would it not be preferable to use something like 1280x720 to maintain the common 16:9 aspect ratio for the image?

**Comment by dshokouhi** [comment]
> Yeah the transparent theme would help if it gets rid of the grey/black bars! Although then the image wouldn't have rounded corners?

corners won't be rounded

> Is there a reason for 1024x600 for sizing? Would it not be preferable to use something like 1280x720 to maintain the common 16:9 aspect ratio for the image?

the cameras I was using for testing when I added this feature did not play nice with other resolutions, it fit oddly into the default size.

**Comment by conorlap** [comment]
Perhaps an option to choose/set the resolution in the widget settings menu then? (the same menu where you select the camera Entity ID) - that way we'd still have the nice rounding and people can set resolutions that match best with each camera they have.

**Comment by dshokouhi** [comment]
@conorlap  would you be able to test my PR to see if most if not all of your concerns are addressed?

You will need to download the artifact from the below link, extract it and install the debug version then create new widgets.  

https://github.com/home-assistant/android/actions/runs/4285893764

**Comment by conorlap** [comment]
It allows me to have a 16:9 image without the grey/black bars. 🥳
Although the lack of rounded corners makes it look a little less polished, is there any way to have this back?

It's actually made one of my 4:3 ratio cameras look worse, the screenshot below is the largest that I could make this camera image. I would ideally like to be able to make that image larger to fit the screen width. 

Maybe re-adding the resizing but at 1280 x 720 this time would help? I know it will stretch a 4:3 image but I reckon that's better than the current result. Or perhaps add widget options for the user to set their own re-size resolution if they desire? 

<img width="273" alt="Screenshot 2023-02-27 at 19 47 09" src="https://user-images.githubusercontent.com/57415184/221667357-4e474755-83ee-49de-8d67-249e5a661833.png">

Thanks for the speedy turn around! 🥳

**Comment by dshokouhi** [comment]
> Although the lack of rounded corners makes it look a little less polished, is there any way to have this back?

Let me see if I can add that back, the rounding would still be dependent upon how the image fits in teh widget so you may need to resize the widget to get it work as intended. If you are on Android 12+ you should already see rounding but it depends on how the image fits in the widget size.

> It's actually made one of my 4:3 ratio cameras look worse, the screenshot below is the largest that I could make this camera image. I would ideally like to be able to make that image larger to fit the screen width.

have you tried changing the widget size to see if it looks better on a resize? so it may need to be larger or smaller as there is no resizing and the view respects the aspect ratio of the image

> Maybe re-adding the resizing but at 1280 x 720 this time would help? I know it will stretch a 4:3 image but I reckon that's better than the current result. Or perhaps add widget options for the user to set their own re-size resolution if they desire?

I would prefer us not to have to resize anything and to just take a raw image and just display it

**Comment by dshokouhi** [comment]
Here is the link to the artifact with background restored and set to transparent:

https://github.com/home-assistant/android/actions/runs/4286408244

Before I had just set the background color on its own now this takes rounding into account

**Comment by conorlap** [comment]
I'm on Android 12 yeah, I've played around with the widget size but can't get rounded corners at all. I tried the latest artifact too but no luck.



> have you tried changing the widget size to see if it looks better on a resize? so it may need to be larger or smaller as there is no resizing and the view respects the aspect ratio of the image

Yeah I've played around with this also but can't get the image any bigger, you can see I've set the widget to a very large size here:

<img width="290" alt="Screenshot 2023-02-27 at 20 15 45" src="https://user-images.githubusercontent.com/57415184/221673871-7ee42bf7-1b49-4772-b23f-337e61a80525.png">

----------------------------------------------------------------------------------------------------------------


The old style widget in between the new style, showing how the 4:3 camera fills up more of the screen because it's been resized:

<img width="292" alt="Screenshot 2023-02-27 at 20 15 21" src="https://user-images.githubusercontent.com/57415184/221673836-6b9e6f94-327d-4587-be0a-f27e620ab291.png">



Resize might be the best solution in terms of allowing for both 4:3 and corner rounding? I think the widget would be much more polished with the corner rounding and ability to set to full display width if user wishes.

**Comment by dshokouhi** [comment]
> Yeah I've played around with this also but can't get the image any bigger, you can see I've set the widget to a very large size here:

no you need to go smaller in this case because you are sending in a low resolution image to be displayed on a high resolution device, go smaller and you will see it behave as expected.



> Resize might be the best solution in terms of allowing for both 4:3 and corner rounding? I think the widget would be much more polished with the corner rounding and ability to set to full display width if user wishes.

I would prefer to not touch the image nor resize it and let the user supply the proper image for their device. Resizing feels very arbitrary to me. It was previously added as I was unaware of the current options used today. What is the resolution of the camera you are testing with? 

Maybe using camera proxy will be a better approach? https://www.home-assistant.io/integrations/proxy/

**Comment by dshokouhi** [comment]
Stand by I think I found the issue but would like for you to test and confirm :)

**Comment by dshokouhi** [comment]
ok please try this artifact, it should resize as you would expect 🤞 

https://github.com/home-assistant/android/actions/runs/4286839528

**Comment by conorlap** [comment]
> What is the resolution of the camera you are testing with?

The main camera I want this feature for has a sub-stream of 720x576 and a main stream of 1920x2560. For the above tests I was using the substream. 

> Maybe using camera proxy will be a better approach? https://www.home-assistant.io/integrations/proxy/

I tried this but it won't let me override aspect ratio so doesn't make any difference.


> ok please try this artifact, it should resize as you would expect 🤞

This is getting closer for sure! See the below screenshots, I'm now able to get the doorbell image sitting nicely - thank you!!
The 16:9 indoor camera still isn't rounding though, you can see the 'widget area' is too large around the image so the rounding isn't getting applied to the image. I've tried to make the widget smaller but still won't cause rounding (see 2nd screenshot)

I know you're trying to avoid resizing but it really seems like some sort of dynamic resizing of the widget camera image to fill the 'widget size' would be the best solution? Even if it distorts the original image's aspect ratio a little.


![WhatsApp Image 2023-02-27 at 9 32 59 PM](https://user-images.githubusercontent.com/57415184/221690635-a03a10c2-503d-4d58-ada5-e4526d4cc77c.jpeg)

![WhatsApp Image 2023-02-27 at 9 43 19 PM](https://user-images.githubusercontent.com/57415184/221692541-62a9f18a-3f01-4600-956a-192275cb08e4.jpeg)

**Comment by dshokouhi** [comment]
> I know you're trying to avoid resizing but it really seems like some sort of dynamic resizing of the widget camera image to fill the 'widget size' would be the best solution? Even if it distorts the original image's aspect ratio a little.

Right now Android is in control of it resizing dynamically based on aspect ratio, widget size and probably even resolution.

I don't think distorting aspect ratio is a good way forward. I think the current changes are a big improvement over what is currently offered. The rounding is also system controlled in this instance too.

**Comment by conorlap** [comment]
What about centre cropping the image within the widget view so that it fills the entire widget-view? This way it's not actually resizing or adjusting aspect ratio of the given image?

 `android:scaleType="CenterCrop"` ([I think!](https://developer.android.com/reference/android/widget/ImageView.ScaleType#CENTER_CROP))

instead of:

`android:scaleType="fitCenter" `

**Comment by dshokouhi** [comment]
> `android:scaleType="CenterCrop"` ([I think!](https://developer.android.com/reference/android/widget/ImageView.ScaleType#CENTER_CROP))
> 
> instead of:
> 
> `android:scaleType="fitCenter" `

this will not work as the image will be cut off in many instances, have already looked into that.

**Comment by conorlap** [comment]
Fair enough yeah, I guess the only option to get the entire card filled without losing any image is [FIT_XY](https://developer.android.com/reference/android/widget/ImageView.ScaleType.html#FIT_XY)? but this will distort aspect ratio depending on what size the user has set their widget.

Personally I think a slight distort of the aspect ratio would be preferable to make the widgets look more 'polished' (rounded corners) and fit in with other Android widgets users may have setup. I'd be frustrated with weird aspect ratios on my cameras within the HA dashboard itself but for the sake of a widget on my home screen it would be a good price to pay for a visually cohesive widget experience IMO.

Thanks for your changes on the other bits, much appreciated 😀
