### ISSUE TITLE
Provide option to chose/set resolution for camera widget

### ISSUE THREAD

**Issue by conorlap** [home-assistant/android#3374]
**Is your feature request related to a problem? Please describe.**

I think the camera widget is great but could look more polished

**Describe the solution you'd like**

Request to provide an option to choose/set the image resolution in the camera widget settings menu (the same menu where you select the camera Entity ID) - that way people can set the resolution that matches best with their camera.

**Describe alternatives you've considered, if any**

N/A

**Additional context**

This would alleviate the grey/black bars on the camera widget as currently the widget resizes all images to 1024x600 which may not match most cameras which are likely to have 16:9 or 4:3 aspect ratios.

**Comment by dshokouhi** [comment]
Submitted a PR to remove resizing and makes the background transparent
