### ISSUE TITLE
Cache problem? Persistent Notification Images not refreshing in app side panel

### ISSUE THREAD

**Issue by vegedb** [home-assistant/android#3382]
**Home Assistant Android app version(s):**

**Android version(s):**
13
**Device model(s):**
Pixel 6a
**Home Assistant version:**
2023.2.5
**Last working Home Assistant release (if known):**
nil
**Description of problem, include YAML if issue is related to notifications:**
Persistent Notification Images not refreshing
yaml automation:
1) `service: persistent_notification.dismiss`
2) `service: persistent_notification.create`
`data:
  message: "![image](/local/snapshot.jpg)"
    `

Whenever snapshot.jpg is being overwritten, notification appears as expected BUT the image is using an old one. I assume its a cache problem within the app as this happens on the browser and solvable when cache is deleted from history.

**Comment by dshokouhi** [comment]
This is actually not app controlled. The HA frontend uses very heavy caching techniques. To avoid this issue you need to use a unique image file name.
