### ISSUE TITLE
Entity State widget ignores precision setting

### ISSUE THREAD

**Issue by bdr99** [home-assistant/android#3397]
**Home Assistant Android app version(s):**
2023.1.1-full
**Android version(s):**
13
**Device model(s):**
Pixel 7
**Home Assistant version:**
2023.3.1
**Last working Home Assistant release (if known):**
N/A
**Description of problem, include YAML if issue is related to notifications:**
If I change the precision of a sensor entity using the new feature introduced in HA 2023.3, the Entity State widget ignores this change and still shows the default precision.

**Companion App Logs:**
N/A

**Screenshot or video of problem:**
N/A

**Additional information:**
N/A

**Comment by dshokouhi** [comment]
I am not sure if this data is passed back to the app when we get entity data as it does not appear to be part of the attributes once set. I believe this change was purely for the HA frontend based on the blog post so we will need to implement this in the widget itself if desired. Either way this is a feature request and not a bug :)

**Comment by dshokouhi** [comment]
Looks like the data is provided in the entity registry so it seems the app will be responsible for checking the precision setting and performing rounding from there.

**Comment by jpelgrom** [comment]
Might be nice to integrate [`Entity.friendlyState`](https://github.com/home-assistant/android/blob/aaef25497d3d7c00a14e076bc491ae12496ebe3d/common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt#L451) at the same time to match how the frontend translates common states as well.

**Comment by Ernst79** [comment]
I have recently removed the rounding option from BLE monitor (a custom integration for BLE sensors) and moved to the `suggested_display_precision` in the code. But one of the users has reported that the widgets do not respect the default setting. His temperature sensor is now displayed as 20.0232232542 in a widget, in stead of the default for temperature sensors in BLE monitor (`suggested_display_precision = 1`). It would be good is this feature request can be added.

**Comment by jpelgrom** [comment]
> If this is ever fixed for the Entity State widget, will that also automatically mean it starts working for Wear OS complications

Yes, the fix will also work for complications. It should be available in the next release.
