### ISSUE TITLE
Debugging help - persistent logs or crash report access? 

### ISSUE THREAD

**Issue by ndom91** [home-assistant/android#3404]
Hi folks, so I'm having frequent crashes ~1-2min after opening the app and am having trouble narrowing it down.

I see in the companion app settings we have access to logs, but it doesn't persist between app starts. I also noticed I have crash reports on, but don't seem to have any access to those.

Any tips on debugging this? Couldn't find much in the docs other than pointing to github :/

**EDIT**:

#### Home Assistant Android app version(s):
2023.1.1-full 

#### Android version(s):
13

#### Device model(s):
OnePlus 9

#### Home Assistant version:
2023.3.1

**Comment by jpelgrom** [comment]
If the app is able to save the crash log, there will be a tab 'Recent crash' in Settings > Companion app > Show and share logs.

How do you know the app is crashing? Are you doing anything in particular or does it 'just happen'? What version of the app are you using? What device are you using? Is this a recent problem or has this always happened for you? Please keep the original template that is shown when creating an issue - it helps us help you.

**Comment by ndom91** [comment]
Thanks for the tip! 

The app actually crashes, i.e. closed and restarts. It seems to not be linked to any action, i.e. I can stay on the first screen the app opens, or navigate around to a different lovelace dashboard, settings, etc. and every time it'll crash ~1-2min in. 

So I'm thinking it's some start-up action of the app or some other thing it loads every time on "boot up" of the app. 

I recently added a few new devices and widgets to love lace dashboards, but as I said I don't need to navigate to those dashboards (or I can even be in the settings or anywhere else) and it still crashes. 

I'm on a oneplus9 with the latest play store version (not beta channel) and my homeassistant is a 2023.03.01 supervisor install on up-to-date debian

**Comment by dshokouhi** [comment]
> Also I chose the \"blank template\", maybe you can remove that option if you don't want folks using it 😉👍

It is turned off on the desktop seems there is a mobile app bug. Either way please copy the template from another issue and paste it back with all requested data.

**Comment by ndom91** [comment]
Edited my initial post with the required info fields. 

Unfortunately I can't find the recent crash info in the companion app menu. Seems like it wasn't able to save anything :/

**Comment by dshokouhi** [comment]
@ndom91 if the app is unable to save the recent crash then we will need to see logcat from the device. There is no easy way to get the logs from the device other than using Android Studio or an app like Logcat Reader. Both of which will require you to use a computer with USB to connect to the device (and grant permissions if required).

Alternatively you can try the beta on the play store to see if the issue is resolved there.

**Comment by ndom91** [comment]
I updated to beta and the issue disappeared, closing now. Thanks for the tips!
