### ISSUE TITLE
App at times disregard proxy bypass settings in device and fails to connect to locally running HA instance

### ISSUE THREAD

**Issue by KamalW** [home-assistant/android#3419]
**Home Assistant Android app version(s):**
2023.1.1-minimal (f-droid)
**Android version(s):**
13
**Device model(s):**
Samsung Galaxy F13
**Home Assistant version:**
2023.1.7
**Description of problem, include YAML if issue is related to notifications:**
I have configured a manual proxy server in the phone WIFI settings with bypass URLs for the LAN. When connecting via WIFI to the internal URL of HA, the app sometimes fails to connect. When this happens I see in the proxy server logs connection attempts being received by it which should not have happened. The app appears to disregard the proxy bypass URLs. This doesn't happen always. But when this happens, disconnecting from WIFI and reconnecting usually solves the problem but not always.

**Additional information:**
My device setup includes NetGuard running and I also use a private DNS server. They don't appear to cause this problem. Everywhere, I use the local IP address of the HA instance (within the app and also as a bypass URL in the WIFI proxy settings). When the problem occurs, if I use a web browser in the same phone and access the HA internal URL, the login screen appears as expected. It's only the app that appears to disregard the proxy bypass URLs at certain times.

**Comment by dshokouhi** [comment]
You had skipped over the logs in the issue template so how are we supposed to look at the error to determine if it is something we can indeed fix?
