### ISSUE TITLE
Tiles show wrong status for non-admin users (missing first toggle), websocket error

### ISSUE THREAD

**Issue by danielb42** [home-assistant/android#3421]
**Home Assistant Android app version(s):** 2023.1.1-full

**Android version(s):** 11

**Device model(s):** Samsung A41 (both the admin and the non-admin device)

**Home Assistant version:** 2023.3.4

**Last working Home Assistant release (if known):** unknown

**Description of problem, include YAML if issue is related to notifications:**
When assigning `switch` actions to Quick Settings Tiles, the toggled state is not updated when pressed for the first time (i.e. Tile doesn't change color). Any subsequent toggle updates the status correctly, but of course it's always wrong by then, as the first state transition was missed.

This only affects non-admin users. Logging in as admin user on the "faulty" phone immediately brings desired behaviour to the Tiles.

On the non-admin device, after closing and reopening the Quick Settings the states are shown correctly after being wrong. But then the first toggle is missed again....

I'm appending a suspicious log line which is only generated with the non-admin account.

**Companion App Logs:**

```
03-15 22:09:05.074 13125 13125 D TileExtensions: Tile: tile_4 is in view
03-15 22:09:05.074 13125 13125 D TileExtensions: Attempting to set tile data for tile ID: tile_4
03-15 22:09:05.075 13125 28282 D WebSocketRepository: Websocket: onMessage (text)
03-15 22:09:05.076 13125 28282 D WebSocketRepository: Message number 241 received
03-15 22:09:05.077 13125 13125 E WebSocketRepository: Unable to subscribe to subscribe_trigger with data {trigger={platform=state, entity_id=[switch.tz3000_2putqrmw_ts011f_switch]}}   #  <---- admin account doesn't log this error
```

**Screenshot or video of problem:**

**Additional information:**
Tried connecting via internal and external URL, no difference.

**Comment by jpelgrom** [comment]
The log error you posted is a duplicate of #3313, for which a fix is pending approval. I think loading the initial state should still work though, do you also have logs for when the tile is clicked?

**Comment by danielb42** [comment]
Hi @jpelgrom, indeed #3313 looks very related, thanks.

> maybe I'm misunderstanding and it does show the status correctly on first load, in that case the issue I linked fully covered this report.

Yes, the initial status (after pulling down the Quick Settings menu) is always correct. Also, every transition (pressing a tile) *after the first one* updates correctly. But the state is always inversed then.

So, if this issue is related to #3313, which explains admin requirements to that API (if I understand it right), then why is only the first action affected and not the subsequent ones?

Do you still want more logs or do you see this fully covered by #3313?

**Comment by danielb42** [comment]
> When you tap on a tile for a switch, a toggle action is sent and the tile state is temporarily changed to reflect the interaction. After that it is supposed to be updated to the correct state by the subscription but that obviously doesn't work, which is why you get a tile that isn't showing the correct state but still toggles.

I see, makes sense, thanks.

Just tried the test version, created a new tile from within (so it shouldn't have mixed up with the existing non-debug Tiles) and it's looking good - toggles fine and updates the Tile correctly!

So I guess this is issue is already resolved then (or will be with coming updates).. thanks again. :)
