### ISSUE TITLE
Physical audio button media control

### ISSUE THREAD

**Issue by MCManiac52** [home-assistant/android#343]
When a media control panel is open, if it supports volume control, have the physical audio buttons control it.

**Comment by robbiet480** [comment]
This will require frontend work. @balloob maybe just a function on the external bus to the device to forward hardware events and let the frontend decide what to do? e.g. `volume_up`, `volume_down`

**Comment by balloob** [comment]
Maybe could work if a more info of a media player is open. Don't consider this a priority.

**Comment by gerthass** [comment]
Or an option in the app condiguration to select a media_player.entity that can be controlled by the physical volume buttons
