### ISSUE TITLE
Home Assistant is not responding

### ISSUE THREAD

**Issue by Thorsten1982** [home-assistant/android#3433]
If I'm not at home in the WLAN then I very often get the message "Home Assistant not responding" on my cell phone. When I'm at home in the wifi, the message does not come.
![Screenshot_20230324-143554](https://user-images.githubusercontent.com/1064965/227551839-72c76549-0b73-4c92-b08f-7e0cb012d8ce.png)

**Comment by Thorsten1982** [comment]
Thank you, I hope it works with the new version. The error appears to only occur when I have no connection to HomeAssistant.

Android version(s):** Android 13

**Device model(s):** Pixel 6

**Home Assistant version:** Version 2023.1.1-full

**Last working Home Assistant release (if known):** it didn't work with any version

**Comment by dshokouhi** [comment]
@Thorsten1982 are you use the location sensors? Is your HA instance remotely accessible? 

If you answered yes to the first question and no to the second question then there is no reason to keep location sensors enabled. You will never be able to get the state to update as the data will never be able to be sent home to show you are not at home. Although the crashing will stop in the next version those sensors are not functional in that scenario so you can save some battery life by leaving it off.

**Comment by dshokouhi** [comment]
@Thorsten1982 Please update to the latest version 2023.3.0 and see if the issue is resolved, the release went live in the Play Store yesterday.

**Comment by Thorsten1982** [comment]
Yes thank you
