### ISSUE TITLE
Notifications not working with 2023.3.0?

### ISSUE THREAD

**Issue by alexisml** [home-assistant/android#3444]
**Home Assistant Android app version(s):** 2023.3.0

**Android version(s):** 13

**Device model(s):** Galaxy S22 (SM-901E)

**Home Assistant version:** 2023.3.6

**Last working Home Assistant release (if known):** previous Android version (It automatically updated today for me)

**Description of problem, include YAML if issue is related to notifications:**
Notifications are not working at all. I'm manually triggering from service to try it out:

```
service: notify.mobile_app_celular_alexis
data:
  message: Test
```

However I get nothing on my phone.

**Companion App Logs:**
[homeassistant_companion_log_2-31-2023_10-45-25.txt](https://github.com/home-assistant/android/files/11122456/homeassistant_companion_log_2-31-2023_10-45-25.txt)

**Screenshot or video of problem:**
![image](https://user-images.githubusercontent.com/16224395/229138141-073b0845-7a02-41ec-a710-8822c9b6098d.png)

**Comment by jpelgrom** [comment]
Can you do a force stop of the app, and re-open it? That should trigger it to send the latest FCM registration to your server, which is needed for push notifications.

**Comment by alexisml** [comment]
Update: I found out that there were some issues with the server by loooking into the 404 in the logs. Somehow many things were fcked up, and restarting it AGAIN made it work. Now notifications are working. 
The unfortunate thing is that I didn't have any indications server side of issues :( 

Thanks for the help
