### ISSUE TITLE
Android: Work Profile Sensor flaky / detects as "off" event though profile is still active.

### ISSUE THREAD

**Issue by s256** [home-assistant/android#3448]
**Home Assistant Android app version(s):**
2023.3.0
**Android version(s):**
13 - Build TQ1A.230205.002 
**Device model(s):**
Pixel 6 Pro
**Home Assistant version:**
Home Assistant 2023.3.6 
Supervisor 2023.03.3 
Operating System 9.5 
Frontend 20230309.1 - latest 
**Last working Home Assistant release (if known):**
None
**Description of problem, include YAML if issue is related to notifications:**
The Work Profile sensor is not detecting the state properly. The work profile is activated on my phone automatically Monday til Friday at 08:00am and deactivated at 5pm. But: most of the time the sensor is showing that the profile is not active after 10 minutes of activating the profile. Manually activating the profile does not improve the detection/"measurement" of the sensor.
Attached is a screenshot of last week. One can see that not every activation of the profile was recognized. One can also see, that the profile is detected as "off" although it was still active.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![image](https://user-images.githubusercontent.com/1517486/229279719-47e666eb-7717-4fe8-839d-32c936ec7ff9.png)
![image](https://user-images.githubusercontent.com/1517486/229279761-6d2bc078-adcc-4a1c-bd88-c8fcf6d1342f.png)
![Screenshot_20230401-122031](https://user-images.githubusercontent.com/1517486/229280480-3cc3d1a3-2460-45c9-9bb5-06baca76660f.png)

**Additional information:**
My plan was to use the data from the sensor to keep track of my working hours, I'm not in the office everyday, but I do use my phone during working hours. If the sensor would reflect the actual state, I could pull the time data and use it to automate my time tracking which I have to do for my company.

**Comment by dshokouhi** [comment]
There is unfortunately no state to actually read here. The app updates based on the intent received from Android, if unknown it does default to false or off as the state cannot be queried at any time. Are you able to get the device logs from when the issue happens?

**Comment by s256** [comment]
Thanks for the fast reply. I'll check if I can get the logs in the app. When I created the github issue, there was no mention of the work profile in the logs. Waiting for the issue to reappear.

**Comment by dshokouhi** [comment]
> When I created the github issue, there was no mention of the work profile in the logs.

you wont see that, we are looking for the intents that get fired when the profile gets enabled/disabled and those don't mention the profile specifically.

**Comment by s256** [comment]
Ah ok. So Device Log actually means the Android OS logs and not Companion App log. Obviously as soon as I created this github issue, it now works flawless ;) When it didn't for weeks.
I'll try and setup a wireless adb bridge to collect the device logs throughout the day.
Can you give me an example of the log event? 
In the code I found `Intent.ACTION_MANAGED_PROFILE_AVAILABLE` and `Intent.ACTION_MANAGED_PROFILE_UNAVAILABLE`

**Comment by dshokouhi** [comment]
> Obviously as soon as I created this github issue, it now works flawless ;) When it didn't for weeks.

Closing as we have not heard back from the author since this comment
