### ISSUE TITLE
Next Alarm sensor issue

### ISSUE THREAD

**Issue by KotBayun69** [home-assistant/android#3451]
**Home Assistant Android app version(s):**

2023.1.1-full

**Android version(s):**

13 TKQ1.220829.002

**Device model(s):**

Poco 3

**Home Assistant version:**

Home Assistant 2023.3.6
Frontend 20230309.1 - latest

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

After switching to Daylight Saving Time Next Alarm `Local Time` attribute still has value of Standard Time if an alarm on the phone is set at time  more than one hour from now. For example local, time now is 19:23, the alarm is set at 20:24. That what I get in Developers Tools for Next Alarm:

```
Local Time: Sun Apr 02 19:24:00 GMT+03:00 2023
```
After the system clock changed to 19:24 it shows 
```
Local Time: Sun Apr 02 20:09:00 GMT+03:00 2023
```
I'm reporting these numbers in real time during writing this. 

In my opinion, the Next Alarm sensor can't be used in any automation. Please fix it.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
The next alarm sensor shows the next alarm from any app, as the name suggests. Can you check the package attribute to see if it matches your alarm clock app? Especially the 20:09 time suggests there's another app interfering with your expected next alarm.

**Comment by KotBayun69** [comment]
@jpelgrom 
Thank You for Your replay.
The package attribute is
```
Package: com.android.deskclock
```
I don't use any other apps for the alarm and Next Alarm Sensor is enabled only on my Android phone. It's disabled on my wife's same model phone and on my iPad

**Comment by jpelgrom** [comment]
Thanks for checking. Odd that it shows a 20:09 alarm then. Can you verify the time zone is correct (there's a time zone sensor)?

> I don't use any other apps for the alarm

You may not, but other apps might mis-use the alarm feature of Android and as a result change what is the next alarm on your phone.

> It's disabled on my wife's same model phone and on my iPad

Those don't influence your phone's sensors anyway

**Comment by KotBayun69** [comment]
@jpelgrom 

Here we go:

| Attribute               | Value                   |
|---------------------|-------------------|
| Current Time Zone | Israel Daylight Time |
| in_daylight_time | true |
| time_zone_id | Asia/Jerusalem |
| time_zone_short | GMT+03:00 |
| uses_daylight_time | true |
| utc_offset | 10800000 |

Will it help?

**Comment by KotBayun69** [comment]
>You may not, but other apps might mis-use the alarm feature of Android and as a result change what is the next alarm on your phone.
It behave the same if I change alarm time by myself.

**Comment by dshokouhi** [comment]
HA has come a long way since this attribute was added. I don't think it really serves a purpose anymore, maybe its time to remove it? 

You should be using the actual state of the sensor as opposed to its attributes either way in automations.

**Comment by KotBayun69** [comment]
@jpelgrom 

Funny thing - I just hovered with my mouse over Your nick and a pop-up showed. It shows Your local time and it says You are one hour behind, but the actual difference is two hours :)

**Comment by KotBayun69** [comment]
@dshokouhi 

I set my alarm to 22:03 at 21:03. That what I get in state column in Developers Tools:
```
2023-04-02T18:48:00+00:00
```
Check the minutes value.
Any suggestions how to use it in automation? LOL

**Comment by dshokouhi** [comment]
can you try  using a different alarm clock like Google Clock or Sleep as Android? Most likely the issue stems from your own alarm app setting a random time. I have seen issues with that package in the past.  In fact Xiaomi is one of hte manufacturers known to do this. If you check closed issues you can see many users mentioning that.

Unfortunately these values you see is exactly what this clcok app is setting, its strange but its coming from that app :)

**Comment by KotBayun69** [comment]
@dshokouhi 

You are absolutely right about it. Disabled an alarm from Xiaomi and installed Clock app from Google. All values are correct. Thank You very much.
>If you check closed issues you can see many users mentioning that.

I did performed the search on GitHub and in Home Assistant forum with `next alarm` key words, but nothing came out, that why I opened this issue. I'm new to this staff. Any suggestion how should I perform a search in the future? Any help will be appreciated.

**Comment by dshokouhi** [comment]
> I did performed the search on GitHub and in Home Assistant forum with `next alarm` key words, but nothing came out,

There are 67 closed issues taht meet those results :) its ok if you can't find them we will reference them as needed. Thanks for reporting back that its working as expected using other apps.
