### ISSUE TITLE
Combine foreground service notifications 

### ISSUE THREAD

**Issue by RoboMagus** [home-assistant/android#3452]
**Is your feature request related to a problem? Please describe.**

With the beacon monitor also in a foreground service, just like the persistent background connection, there are now multiple HA persistent notifications active for "foreground services". It would be neat to limit this to one, if at all possible. 

Future potential needs for foreground services could then also use the existing one. 

**Describe the solution you'd like**

A single combined minimal notification instead of one for each purpose. 

**Describe alternatives you've considered, if any**

N/a

**Additional context**

Spouse feedback, with some added thoughts of my own. ;)

**Comment by dshokouhi** [comment]
Each foreground service serves its own purpose. Its best to keep them separate and let the system manage them. You can chose to hide them as a user since each one has its own notification channel. Not to mention one of the services is tied to WorkManager and the other is linked to service from a 3rd party library. They should remain separate.

**Comment by RoboMagus** [comment]
It's fine that it's not on the roadmap right now, but I feel the issue is closed prematurely. Lets just see how others weigh in on this when more users see more persistent notifications clogging up our notification drawer.

I already have silenced and minimized these notifications, but alltogether I have between 7 and 12 of these _minimized_ notifications at the bottom of my notifications list at all times so reducing this to what is absolutely required is definately desirable. (Plus all the other ones only show one foreground service notification per app). 
If actually not showing any of these notifications at all using the Android notification settings would still allow the foreground service to function propperly I'd use that option, but from what I can tell that's not how Android plays.

Somewhat related to issue #2266 (And all its related and referenced issues) is that users want to customize any notification that has to be there anyway. Since that issue was _not_ closed within a day of it appearing I'll take that those ideas are still open for concideration. 

I get that from a development / SW Architecture point of view combining these services into a single notification is not desirable, but from a user standpoint the situation is different. And from what I can tell this is not an impossible request, merely something that you'd not like to implement.

**Comment by jpelgrom** [comment]
> If actually not showing any of these notifications at all using the Android notification settings would still allow the foreground service to function propperly I'd use that option, but from what I can tell that's not how Android plays.

That should actually work, why do you think it doesn't?
