### ISSUE TITLE
App crash when SSL certificate comes with phishing google warning

### ISSUE THREAD

**Issue by Loic691** [home-assistant/android#3458]
**Home Assistant Android app version(s):**
Last one March 23th 2023 

**Android version(s):**
13

**Device model(s):**
Samsung Galaxy S22

**Home Assistant version:**
2023.3.6

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
The android app crash at starting when the HA server protected with SSL certificate (HTTPS) and come with an google SSL Warning of phishing.
When accessing HA server with web chrome navigator. The navigation is OK but we have to bypass warning red page advertisement.
Note this is a valid letsencrypt certificate.
I had no problem before google mark it as phishing warning...
This is a full domain name without using of dynamic DNS. The IP address behind my domain name is static.

**Companion App Logs:**
can't provide logs because app crash at the starting
```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by Loic691** [comment]
I want to see it.
Yes it seams the same issue.
But without fixes

**Comment by Loic691** [comment]
I saw on android dev pages that's possible to disable google safe browsing in app codes.
Maybe a solution ?

**Comment by jpelgrom** [comment]
> But without fixes

Yes it's an open issue :)

Closing this one too keep discussion in one place

**Comment by Loic691** [comment]
Bonjour
Le problème que j'ai, je viens de m'en rendre compte, c'est qu'en
désactivant le flux audio dans synology, je n'ai plus le flux vidéo live
sur mon système domotique home assistant...
Avez vous une solution alternative ?

*Pierre-Loïc Carette+33 (0)6 75 60 19 07*


Le jeu. 6 avr. 2023 à 10:41, Joris Pelgröm ***@***.***> a
écrit :
