### ISSUE TITLE
Add LONG_TEXT Wear OS Complication Type for existing entity state complication

### ISSUE THREAD

**Issue by chertvl** [home-assistant/android#3463]
**Is your feature request related to a problem? Please describe.**
Unable to use Companion Complication in some fields of watchface settings, that want another type of it, so HA Entity Complication is non an list to select.

**Describe the solution you'd like**
It would be wonderful to have LONG_TEXT type of complication. It is not possible to add HA Complication to some places of many watch faces.

I use HA complication with my template sensor (named "i" for short) to display many other states (and emojies) of my home and devices.
Many of watchfaces have a great big flat field for LONG_TEXT complication, i would like to use it.

Also it would be very nice to be able to not display the name and slash of the entity that is used in the state complication, and display only the state of object (for normal name of sensor.* in backend instead of my "i", and additional space on watch screen).

Maybe other complication types might be useful to someone else.
https://developer.android.com/training/wearables/watch-faces/adding-complications#types-fields

**Describe alternatives you've considered, if any**

**Additional context**
![image](https://user-images.githubusercontent.com/38353584/230659818-a3e6f482-31a1-40bd-a827-6e0613550c7c.png)

**Comment by dshokouhi** [comment]
> Also it would be very nice to be able to not display the name and slash of the entity that is used in the state complication, and display only the state of object (for normal name of sensor.* in backend instead of my "i", and additional space on watch screen).

existing feature request for this https://github.com/home-assistant/android/issues/3190

> Maybe other complication types might be useful to someone else.

We already have an existing request for another one, we should make sure not to combine multiple requests to the same one. For this request we will stick to `LONG_TEXT`

https://github.com/home-assistant/android/issues/3091

**Comment by jpelgrom** [comment]
Ha, great timing! I was actually working on this and have just submitted a PR for it: #3465.

I haven't tested with all the watchfaces you included in the screenshot, in my experience some want an image instead which won't be as easy to implement.

**Comment by chertvl** [comment]
> Ha, great timing! I was actually working on this and have just submitted a PR for it: #3465.
> 
> I haven't tested with all the watchfaces you included in the screenshot, in my experience some want an image instead which won't be as easy to implement.

Now I can use complication even with my own watchface, wich I abandoned because it did not support HA complication. And now it's back!

Thank you so much!

![photo_2023-04-09_17-41-12](https://user-images.githubusercontent.com/38353584/230779436-0c93ccaf-2cd8-4841-8d62-09430b95434c.jpg)
![photo_2023-04-09_17-41-12 (2)](https://user-images.githubusercontent.com/38353584/230779438-6074e0ce-9a1e-4fe5-b00d-415bc895fbe9.jpg)
![photo_2023-04-09_17-41-13](https://user-images.githubusercontent.com/38353584/230779439-bf62cfca-b3db-4491-b8d5-d6e0a7f80fb2.jpg)
