### ISSUE TITLE
"Alway show first view on app start" not working

### ISSUE THREAD

**Issue by ministryofsillywalks** [home-assistant/android#3467]
I always had the feaute "Always show first view on app start" enabled as my first screen is the starting point for everything.
However as of late this option doesn't seem to work anymore.
Correct me if I'm wrong but I seem to remember that as soon as I toggled switched away from the app for a while and then launched it again I would be taken to the first view.
This is now not the case. Even after a few hours of inactivity I get taken back to the last page I was on.
Only closing the app completely (removing it from recents) and opening it again takes me to the first view but this is also the case when the toggle for "Always show...." is disabled.
Would be glad if this could be implemented again or to know if something is incorrect on my end.

HA version: 2023.4.0
App Version: beta-9876-e592c334-full & 2023.3.0

**Comment by jpelgrom** [comment]
This was broken due to changes in 2023.4. Fixed in #3459 - join the beta or wait for the next app release!
