### ISSUE TITLE
Add Card button not locked to bottom of screen as expected 

### ISSUE THREAD

**Issue by schale01** [home-assistant/android#3472]
When editing a dashboard the add card button should stay locked to the bottom of the screen.  I stead when scrolling the dashboard the add card button scrolls with the dashboard.  See attached images

Top of dashboard 
![Screenshot_20230413-002207](https://user-images.githubusercontent.com/7923426/231652624-537040c4-9956-4046-bcfd-957839a80c57.png)

After scrolling down 
![Screenshot_20230413-002511](https://user-images.githubusercontent.com/7923426/231653275-c7539101-18f4-481a-a64e-bf02652fe332.png)

**Comment by dshokouhi** [comment]
Can you reproduce the issue using Chrome for Android on the same device?

**Comment by schale01** [comment]
Yes.  Just tested in chrome.
Same result
![Screenshot_20230413-002847](https://user-images.githubusercontent.com/7923426/231653694-a4db3c94-60b0-49dd-a114-a4770d0eaef6.png)

**Comment by dshokouhi** [comment]
Please open an issue with the HA frontend and make sure to fill out the issue template completely

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=bug_report.yml
