### ISSUE TITLE
Menu Button Position

### ISSUE THREAD

**Issue by jploz24** [home-assistant/android#3485]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered, if any**

**Additional context**

Hello and thank you for all the work done.
I would like to submit an idea on the ergonomics of the mobile version.
Is it possible to choose where the menu button should be (left or **right**).
Indeed, a right-handed person to reach the menu must use the other hand on a large smartphone.
by positioning the menu on the right, everything will be directly accessible.

Best Regards

JP

**Comment by dshokouhi** [comment]
This request needs to be handled by the HA frontend, please submit a feature request in the community forums
