### ISSUE TITLE
Zone names truncated in high accuracy zone menu

### ISSUE THREAD

**Issue by kg333** [home-assistant/android#3486]
**Home Assistant Android app version(s):**
2023.3.0

**Android version(s):**
13

**Device model(s):**
Pixel 5a

**Home Assistant version:**
2023.4.2, Core install

**Last working Home Assistant release (if known):**
Unknown

**Description of problem, include YAML if issue is related to notifications:**
Zones configured in Home Assistant with an underscore in the entity name are truncated at the underscore in the zone list in the Background Location sensor menus.

To reproduce:
* Create a zone in the Home Assistant Map UI with a space in the name, resulting in an underscore in the entity name
* Navigate in the Android app to:
* * Settings
* * Companion App
* * Manage Sensors
* * Background Location
* * High accuracy mode only when entering zone
* Observe the truncated zone name.

**Companion App Logs:**

N/A

**Screenshot or video of problem:**

Home Assistant:
![image](https://user-images.githubusercontent.com/4220833/233526936-d126061e-f9bf-460a-8fa1-6d5c6a4bb1e9.png)

Android App:
![image](https://user-images.githubusercontent.com/4220833/233526971-ca45f4de-a9ed-4fcb-a463-3f60019de3a3.png)

**Additional information:**
N/A

**Comment by jpelgrom** [comment]
Thanks for the bug report! I've submitted a fix which should be included in the app soon.

In the meantime: the data is stored correctly, it is just the name that is truncated. The list is sorted alphabetically which should allow you to determine which one is which.

**Comment by kg333** [comment]
Thanks for the fix and the workaround!
