### ISSUE TITLE
Stuck "+ ADD CARD" button when editing a dashboard

### ISSUE THREAD

**Issue by returnedinformation** [home-assistant/android#3487]
**Home Assistant Android app version(s):**
2023.3.0-full
**Android version(s):**
13
**Device model(s):**
OnePlus 8
**Home Assistant version:**
2023.4.5
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Stuck "+ ADD CARD" button when editing a dashboard

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![photo_2023-04-21_22-39-56](https://user-images.githubusercontent.com/57621749/233730601-5c5f7870-e0bc-4cb6-ab12-3762d26a4e65.jpg)
![photo_2023-04-21_22-39-59](https://user-images.githubusercontent.com/57621749/233730597-1c376ff4-793e-49ed-bbe6-2105843a5ceb.jpg)
![photo_2023-04-21_22-40-00](https://user-images.githubusercontent.com/57621749/233730592-2be986a9-0667-419c-b2f3-379d3a60be08.jpg)
**Additional information:**

**Comment by dshokouhi** [comment]
Can you reproduce the issue using chrome for Android on the same device?

**Comment by returnedinformation** [comment]
Yes, I can, it happens just the same

**Comment by dshokouhi** [comment]
Ok then this issue should be filed with the HA frontend as the app cannot fix it.

**Comment by returnedinformation** [comment]
Thank you, I will file it
