### ISSUE TITLE
 Android Service Button Widgets not working or saving entity

### ISSUE THREAD

**Issue by smcbn** [home-assistant/android#3497]
**Home Assistant Android app version(s):**
 2023.3.0-full

**Android version(s):**
13

**Device model(s):**
Pixel 7 Pro

**Home Assistant version:**
Home Assistant 2023.4.6 
Frontend 20230411.1 - latest 

**Last working Home Assistant release (if known):**
Recently updated both the app and the server, before these updates the service buttons worked as expected

**Description of problem, include YAML if issue is related to notifications:**
Previously working Service Widgets and new Service Widgets no longer work.

1. When a Service Widget is pressed the dialogue `Unable to send service call` appears. The device does not toggle.
1. Editing the Widget shows the entity is no longer present

**Companion App Logs:**
Full logs from the app:
[homeassistant_companion_log_3-27-2023_22-44-56.txt](https://github.com/home-assistant/android/files/11348277/homeassistant_companion_log_3-27-2023_22-44-56.txt)

Snippet from the above logs:
```
04-27 22:44:02.134  6152  6152 D ButtonWidget: Broadcast received: 
04-27 22:44:02.134  6152  6152 D ButtonWidget: Broadcast action: io.homeassistant.companion.android.widgets.button.ButtonWidget.RECEIVE_DATA
04-27 22:44:02.134  6152  6152 D ButtonWidget: AppWidgetId: 33
04-27 22:44:02.137  6152  6152 D ButtonWidget: Saving service call config data:
04-27 22:44:02.137  6152  6152 D ButtonWidget: domain: switch
04-27 22:44:02.137  6152  6152 D ButtonWidget: service: toggle
04-27 22:44:02.137  6152  6152 D ButtonWidget: service_data: {"entity_id":["switch.0x680ae2fffe3e6778"]}
04-27 22:44:02.137  6152  6152 D ButtonWidget: require_authentication: false
04-27 22:44:02.137  6152  6152 D ButtonWidget: label: switch 
04-27 22:44:02.604  6152  6152 I Choreographer: Skipped 54 frames!  The application may be doing too much work on its main thread.
04-27 22:44:02.616  6152 18780 D OpenGLRenderer: endAllActiveAnimators on 0xb4000071e84fe260 (RippleDrawable) with handle 0xb4000070f82fac60
04-27 22:44:04.795  6152  6152 D ButtonWidget: Broadcast received: 
04-27 22:44:04.795  6152  6152 D ButtonWidget: Broadcast action: io.homeassistant.companion.android.widgets.button.ButtonWidget.CALL_SERVICE
04-27 22:44:04.795  6152  6152 D ButtonWidget: AppWidgetId: 33
04-27 22:44:04.795  6152  6152 D ButtonWidget: Calling widget service
04-27 22:44:04.796  6152  6152 D ButtonWidget: Service Call Data loaded:
04-27 22:44:04.796  6152  6152 D ButtonWidget: domain: switch
04-27 22:44:04.796  6152  6152 D ButtonWidget: service: toggle
04-27 22:44:04.796  6152  6152 D ButtonWidget: service_data: {"entity_id":["switch.0x680ae2fffe3e6778"]}
04-27 22:44:04.797  6152  6152 D ButtonWidget: Sending service call to Home Assistant
04-27 22:44:04.798  6152  6152 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
04-27 22:44:04.820  6152  6152 E ButtonWidget: Could not send service call.
04-27 22:44:04.820  6152  6152 E ButtonWidget: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request call_service
04-27 22:44:04.820  6152  6152 E ButtonWidget: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.callService(IntegrationRepositoryImpl.kt:269)
04-27 22:44:04.820  6152  6152 E ButtonWidget: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$callService$1.invokeSuspend(Unknown Source:15)
04-27 22:44:04.820  6152  6152 E ButtonWidget: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-27 22:44:04.820  6152  6152 E ButtonWidget: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-27 22:44:04.820  6152  6152 E ButtonWidget: 	at android.os.Handler.handleCallback(Handler.java:942)
04-27 22:44:04.820  6152  6152 E ButtonWidget: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-27 22:44:04.820  6152  6152 E ButtonWidget: 	at android.os.Looper.loopOnce(Looper.java:201)
04-27 22:44:04.820  6152  6152 E ButtonWidget: 	at android.os.Looper.loop(Looper.java:288)
04-27 22:44:04.820  6152  6152 E ButtonWidget: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
04-27 22:44:04.820  6152  6152 E ButtonWidget: 	at java.lang.reflect.Method.invoke(Native Method)
04-27 22:44:04.820  6152  6152 E ButtonWidget: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-27 22:44:04.820  6152  6152 E ButtonWidget: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Screenshot or video of problem:**
![homeassistant-service-widget-broken](https://user-images.githubusercontent.com/39912103/235000695-f477ee0c-8187-4150-9d36-6048c8515349.gif)

**Additional information:**

**Comment by dshokouhi** [comment]
any errors in HA core at the time of tapping the widget?

**Comment by smcbn** [comment]
> any errors in HA core at the time of tapping the widget?

Nothing related to this.

<img width="1518" alt="Screenshot 2023-04-27 at 23 07 44" src="https://user-images.githubusercontent.com/39912103/235001815-fee1db22-9f7d-4d74-87f7-e29ddd70371e.png">

**Comment by dshokouhi** [comment]
> 2\. Editing the Widget shows the entity is no longer present

known issue: #3484 based on the above logs the data is saved just not showing in the UI

can you also confirm if the service call works in HA directly? sometimes an integration doesn't support `switch.toggle` so good to check that is not the case here

**Comment by smcbn** [comment]
> > 2. Editing the Widget shows the entity is no longer present
> 
> known issue: #3484 based on the above logs the data is saved just not showing in the UI
> 
> can you also confirm if the service call works in HA directly? sometimes an integration doesn't support `switch.toggle` so good to check that is not the case here

Yes works in HA directly. My switch widgets worked before recently updating and no longer work

I seen #3484 but I couldn't see the same stack trace that was visible in my logs, so wasn't sure if it was exactly the same

**Comment by dshokouhi** [comment]
ok just took a look at your full logs I see the issue now.

```
04-27 22:43:30.466  6152  6152 E IntegrationRepository: Issue getting new version from core.
04-27 22:43:30.466  6152  6152 E IntegrationRepository: io.homeassistant.companion.android.common.data.integration.IntegrationException: retrofit2.HttpException: HTTP 410 Gone
```

410 gone suggests the integration is no longer linked correctly to the `mobile_app` entry, this may happen if the integration was deleted in HA. I can even see sensor updates failing as well.

Can you try logging out of the app and log back in to see if that corrects the issue? If asked for device name, use the same device name.

**Comment by smcbn** [comment]
> ok just took a look at your full logs I see the issue now.
> 
> ```
> 04-27 22:43:30.466  6152  6152 E IntegrationRepository: Issue getting new version from core.
> 04-27 22:43:30.466  6152  6152 E IntegrationRepository: io.homeassistant.companion.android.common.data.integration.IntegrationException: retrofit2.HttpException: HTTP 410 Gone
> ```
> 
> 410 gone suggests the integration is no longer linked correctly to the `mobile_app` entry, this may happen if the integration was deleted in HA. I can even see sensor updates failing as well.
> 
> Can you try logging out of the app and log back in to see if that corrects the issue? If asked for device name, use the same device name.

That worked - its back to working again - thank you!
