### ISSUE TITLE
Huge delay between location request and response when app in background

### ISSUE THREAD

**Issue by larena1** [home-assistant/android#3505]
**Home Assistant Android app version(s):** 2023.3.0

**Android version(s):** LOS 13

**Device model(s):** OP7T

**Home Assistant version:** 2023.5.0

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
I am observing a huge delay between requesting a location and the app responding with a location when it is in background.
In foreground the response is instant. App is allowed to always access location and excempted from battery optimizations.

**Companion App Logs:**

```
05-02 09:12:17.517 19873 19873 D MessagingService: Request location update
05-02 09:16:00.219 19873 19873 D LocBroadcastReceiver: Got single accurate location update: Location[fused ]

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by larena1** [comment]
The app has proper access. It is receiving the location request instantly and logging that from MessagingService but it'll usually only answer that up to a few minutes later.

**Comment by dshokouhi** [comment]
That delay could be coming from Google and not the app. As your device is on a custom ROM we can't guarantee that. Custom ROM only sorry the minimal version which had no location tracking.

**Comment by larena1** [comment]
Why are you closing this? I think you are confusing that with the minimal version which is meant to be used on devices without Google Play Services.

That is not the case here. I'm using the full version directly from Play Store.

**Comment by dshokouhi** [comment]
Custom ROM is only supported on the minimal version. We do not offer support on the full version if you have a custom ROM. We can't account for all the difference in the varying play services that get offered in those ROM.
