### ISSUE TITLE
"Home Assistant - Updating Sensors" is constantly showing

### ISSUE THREAD

**Issue by gfn256** [home-assistant/android#3515]
**Home Assistant Android app 2023.3.0-full**

**Android 13**

**oneplus nord ce 5g**

**latest**

**all before**

**After recent frontend update/reload the "Home Assistant - Updating Sensors" is constantly showing in phone**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
Can you provide more information, like app logs? How many sensors do you have enabled? Is your server reachable? 

Frontend updates shouldn't cause issues, assuming you also updated core :) Versions for that would also be helpful.

**Comment by gfn256** [comment]
After about 1-2 hours issue disappeared.
By the way, I don't have any (app) sensors set up.
Must have been some server issue, that settled itself in the end.
Thanks for help.
