### ISSUE TITLE
Matter + Thread device commissioning via BLE in the Home Assistant Companion for Android

### ISSUE THREAD

**Issue by lboue** [home-assistant/android#3516]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Could you add Matter Thread device commissioning via BLE in the Home Assistant Companion for Android.

**Describe alternatives you've considered, if any**

**Additional context**

BLE has a couple of benefits. Because mobile devices generally support BLE, the mobile device can communicate directly with the joining device using a point-to-point connection over BLE. This ensures the mobile and joining device can transfer information whenever they are in physical proximity (which is the typical scenario when commissioning smart home devices).

![Screenshot_20230505-183604_Google Play services](https://user-images.githubusercontent.com/938089/236517886-eb2612e9-85c2-4192-b214-c5f87a937ef0.jpg)

**Comment by jpelgrom** [comment]
The app is using Google's API for Matter commissioning which also will handle Thread credentials. Have you tried it yet? It does support joining Thread-only devices to a Matter fabric so I think it covers your feature request.

**Comment by jpelgrom** [comment]
The screenshot you've added now shows Google's flow which is already implemented: https://www.home-assistant.io/integrations/matter#add-a-device-using-the-android-companion-app

**Comment by lboue** [comment]
> The app is using Google's API for Matter commissioning which also will handle Thread credentials. Have you tried it yet? It does support joining Thread-only devices to a Matter fabric so I think it covers your feature request.

When I try to add my device with Google Home app, it detects my Matter BLE device but also asks for a QR Code.
I tried with Home iOS native app and I just have to enter the pairing ping without scanning any QR Code.

**Comment by jpelgrom** [comment]
If you want to use a pairing code, tap on 'Set up without QR code' (why though? all Matter devices have a QR code). Google Home app is outside of this issue's scope but flow is the same for Home Assistant.

For more information on Matter commissioning and troubleshooting steps if it's failing, please refer to the documentation I've linked above.
