### ISSUE TITLE
Notification/Popup on Android Auto

### ISSUE THREAD

**Issue by luizfelipepg** [home-assistant/android#3520]
**Is your feature request related to a problem? Please describe.**

It is not related to any problem but a suggestion on how to enhance some of the automations we have using home assistant.

**Describe the solution you'd like**

When connecting my android to my car, I normamly get some popups on screen from different apps like maps and whatsapp. I would like to get popups from my android home assistant automation if possible so I can automate some popups to easy access like:
Do you wish to open your garage door ? (when getting close to your home )
Would you like to turn off your office ? (when leaving the house)
etc.....
At the moment I am already sending those notifications to my android but they are not showing up on my android auto screen. That would make it much more secure if I could interact with the android auto device instead of my mobile.

**Describe alternatives you've considered, if any**

At the moment, I have to get my mobile and click on the automations I have set to send notifications/popups but that represents a security risk as I am driving while looking at my phone

**Additional context**

Thanks a lot for the amazing work you are putting into this 👏

**Comment by Bushrider** [comment]
I'd really like to have this feature enabled too. I think that would be a great improvement to, at least, get notifications to android auto screen, actionable or not.
Thx a lot for this fantastic work!

**Comment by Jinsin456** [comment]
+1 for this, the fact Home Assistant is on Android Auto is amazing but it has the potential to be incredible.

A way of selecting 'favourites' / dashboard and actionable notifications would make this a game change

Thanks to everyone for all their great work :)

**Comment by penright** [comment]
+1 
First, let me echo the fact it is on AA is so cool. Great job.
actionable notifications +1 I would assume to wire all that through would be a huge task, but it would be cool.
You have the default tabs, for example, covers, buttons, etc. Could we create a tab with the buttons and covers that are important to the user? Then show it by default if exist, then the back key can take you to the screen with all the tabs. I can create a different request for this if needed.

**Comment by jpelgrom** [comment]
> Could we create a tab with the buttons and covers that are important to the user?

There is an open feature request for favorites which is basically what you're describing: #3219

**Comment by jpelgrom** [comment]
Implementing this in #3642:
 - having a notification show up is as simple as adding `car_ui: true` to the notification
 - tapping a notification from Android Auto will open the driving interface
 - [actions](https://companion.home-assistant.io/docs/notifications/actionable-notifications) are supported however, so you could add simple buttons (they will currently always show a Home Assistant icon in pop up, but we can add options to change that later, action text is visible when you view notifications); ![image](https://github.com/home-assistant/android/assets/8148535/8be5936b-b052-41bb-a210-1af639a67138) ![image](https://github.com/home-assistant/android/assets/8148535/7b5ba627-d38d-4508-88e9-72820186060b)

Example notification would be:
```yaml
service: notify.mobile_app_<your_device_id_here>
data:
  title: "Door unlocked"
  message: "Everyone left home but the door is still unlocked"
  data:
    car_ui: true
    notification_icon: "mdi:door-open"
    channel: "Door unlocked"
    importance: high
    actions:
      - action: CLOSE_DOOR
        title: "Close door"
```

**Comment by luizfelipepg** [comment]
Wowww !!!
That is awesome !!!
Thanks for looking into this !!!

I have soo many use cases ❤️

**Comment by dshokouhi** [comment]
@jpelgrom  I think we forgot to update FCM repo for this new parameter right? 😂

**Comment by dshokouhi** [comment]
@Jinsin456 please try again in about 10 minutes, should be fixed by then 🤞 thanks for reporting!

**Comment by Bushrider** [comment]
This worked for me 👍 
`alias: Notification garage ouvert
description: ""
trigger:
  - platform: state
    entity_id:
      - **<your_entity>**
    from: closed
    to: opening
condition: []
action:
  - service: notify.mobile_app_**<your_device>**
    data:
      message: Le garage est ouvert
      data:
        car_ui: true
        notification_icon: mdi:garage-open
        channel: garage opened
        importance: high
        actions:
          - action: null
            title: Ouvrir garage

**Comment by garysargentpersonal** [comment]
Thanks @Bushrider that worked. Turns out I'd been stupid and used "car-ui" not "car_ui"!

**Comment by tmason818** [comment]
> * having a notification show up is as simple as adding `car_ui: true` to the notification

This is so slick! Only took me a few minutes to whip up some Notification Automations that briefly that show my Garage Door actively is Closing and then Closed- and I even have the [notifications clear](https://companion.home-assistant.io/docs/notifications/notifications-basic/#clearing) when the garage is _confirmed_ Closed. Masterful!

> * [actions](https://companion.home-assistant.io/docs/notifications/actionable-notifications) are supported however, so you could add simple buttons (they will currently always show a Home Assistant icon in pop up, but we can add options to change that later, action text is visible when you view notifications);

I had no idea how new these changes were. I'd imagine the icon for the Actions are still limited to the Home Assistant icon and there is no way to change those as of yet?

Either way **really nice work!**

**Comment by Namanhuu** [comment]
Hi guys,

I've used example code above. Notifications are showing up on Android Auto but i can't see the actionable buttons. Is there something else i need to do to make the actionable buttons show up on the Android auto notiification.

**Comment by dshokouhi** [comment]
> Hi guys,
> 
> I've used example code above. Notifications are showing up on Android Auto but i can't see the actionable buttons. Is there something else i need to do to make the actionable buttons show up on the Android auto notiification.

It should show up when you view the actual notification like the screenshot above

**Comment by Namanhuu** [comment]
> It should show up when you view the actual notification like the screenshot above

Thanks Daniel, my notification shows up as per the first screenshot, if i tap the notification it opens the Home Assistant app.  How do I "view" the notification. I tried swiping up, down. etc.

**Comment by dshokouhi** [comment]
> 
> > It should show up when you view the actual notification like the screenshot above
> 
> Thanks Daniel, my notification shows up as per the first screenshot, if i tap the notification it opens the Home Assistant app.  How do I "view" the notification. I tried swiping up, down. etc. 
> 

Are you sure the action syntax is correct?

**Comment by Namanhuu** [comment]
This is what i've got for it

action:
  - alias: Set up variables for the actions
    variables:
      action_openg1: "{{ 'openg1' ~ context.id }}"
      action_opengg2: "{{ 'opengg2_' ~ context.id }}"
  - alias: Ask to Open Gate?
    service: notify.mobile_app_namanh_phone
    data:
      message: You are nearly home, would you like to?
      data:
        car_ui: true
        notification_icon: mdi:garage-open-variant
        channel: CAR
        importance: high
        actions:
          - action: "{{ action_openg1 }}"
            title: OPEN GATE
          - action: "{{ action_opengg2 }}"
            title: OPEN GATE & GARAGE

**Comment by dshokouhi** [comment]
@Namanhuu ok your syntax looks correct. The first screenshot is actually when the notification appears as a pop-up, you should still see the action icons to the side. The second screenshot is when you view your notifications by clicking on the numbered badge at the bottom right hand corner next to cell signal and the clock. That detailed view should show the actions for you there. If it doesn't try checking notification history details to make sure the app received the action appropriately.

**Comment by tmason818** [comment]
Is there a way currently to change the display Icon for the Actions in the Android Auto message view or will they always default to the Home Assistant icon? Something like:

```
actions:
  - action: "{{ action_garage }}"
    title: "Yes"
    icon: mdi-arrow-up     #Actionable item icon?
  - action: "{{ action_front_door }}"
    title: No, Unlock Front Door
tag: open_doors_notify
channel: ask_open_doors
notification_icon: mdi:garage
importance: high
car_ui: true
timeout: 120
```

**Comment by jpelgrom** [comment]
> Is there a way currently to change the display Icon for the Actions in the Android Auto message view

No, this is not yet supported

**Comment by mdzhigarov** [comment]
> This is what i've got for it
> 
> ```
> action:
>   - alias: Set up variables for the actions
>     variables:
>       action_openg1: "{{ 'openg1' ~ context.id }}"
>       action_opengg2: "{{ 'opengg2_' ~ context.id }}"
>   - alias: Ask to Open Gate?
>     service: notify.mobile_app_namanh_phone
>     data:
>       message: You are nearly home, would you like to?
>       data:
>         car_ui: true
>         notification_icon: mdi:garage-open-variant
>         channel: CAR
>         importance: high
>         actions:
>           - action: "{{ action_openg1 }}"
>             title: OPEN GATE
>           - action: "{{ action_opengg2 }}"
>             title: OPEN GATE & GARAGE
> ```

Can you elaborate what is context.id? I suppose this should reference the garage opener cover which in my case is `entity: cover.garage`. Is that it?

**Comment by henfri** [comment]
Hello,

I have the same intention: 
When being close to home, HomeAssistant should open (1) and I should get the option to open the Garage Door.

It seems @mdzhigarov, @Namanhuu that you have some practical experience.

Does it work satisfactory? 

On the opening of HA (1): Does a Pop-Up prominently come to the front, or is it like on the phone, that I need to "pull down" the notifications? 
The first would be better, because otherwise the distraction would be too high.
Also: how well does the Location-Trigger work?

Greetings,
Hendrik

**Comment by stever29** [comment]
To anyone arriving here struggling to get this to work like I did - just adding `car_ui: true` to an existing automation notification doesn't seem to work (at least for me) without also specifying the `channel: XYZ` tag with any channel name you like

**Comment by stboch** [comment]
Yeah probably need to add a note/caveat to the https://companion.home-assistant.io/docs/notifications/notifications-basic/ page

**Comment by dshokouhi** [comment]
actually the original Channel "General" needs to have the "pop on screen" setting in order to also show up as a notification in Android Auto. The new channel created probably has that by default which is why it seemed like it worked. We also recommend using a new channel for this feature too.

This is also mentioned in the docs: https://companion.home-assistant.io/docs/android-auto/#notifications

**Comment by stever29** [comment]
> actually the original Channel "General" needs to have the "pop on screen" setting in order to also show up as a notification in Android Auto. The new channel created probably has that by default which is why it seemed like it worked. We also recommend using a new channel for this feature too.
> 
> This is also mentioned in the docs: https://companion.home-assistant.io/docs/android-auto/#notifications

Ah yes, thanks for clearing that up. You're right, I now have the pop-ups on my phone for this notification

I assume there's no easy way around this? Generally I have pop-up turned off on my phone, but still have the android top of the screen pop-up-but-not-a-pop-up drawer notification thing. It would be nice to be able to not have the dialog on the phone just to get the android auto notifications working. e.g. things like whatsapp don't exhibit the same behaviour. 

Thanks!
