### ISSUE TITLE
MP4 Video File are hiden because "incompatible message" in multimedia browser on Android Companion APP

### ISSUE THREAD

**Issue by Electronlibre2012** [home-assistant/android#3524]
Hello,

i can browse and play my file in all www browser when i am home in my computers, with windows 11 or Ubuntu 22.04,

but when i use the companion Android APP the mp4 files are "hiden for incompatibility". no difference if i am on wifi or mobile data like 3 or 4G.

Is there a way to solved that please?

My phone is a Galaxy Note 20 Ultra 5G, Android 13, One UI 5.1.

Of course, the most interesting is to play my camera records when i am not home, with my Android with mobile data.

File are mostly from Agent NVR, with encodind in h264_vaapi. Some others cam are from Reolink NVR, all have a .mp4 extension.

Solution is to use a www browser on my phone, like Samsung one or Chrome or Mozilla but i prefere to use Companion.

**Comment by jpelgrom** [comment]
Hi, could you add information from the template please? App version / any relevant logs could be helpful.

When you say "www browser", do you mean HA's media browser or something else? The app doesn't have any code to explicitly hide stuff in the frontend.

**Comment by Electronlibre2012** [comment]
thanks for your reply,

Yes HA media browser then local media

For HA's media browser, check your output device (icon in the bottom right corner). ---------> SORRY, i feel so stupid noob...i forget to select the output device "web browser"...it was select on a Google Home...

All work as expected!

Sorry again, and thanks for your time!
