### ISSUE TITLE
Assist speech to text fails when using an internal URL

### ISSUE THREAD

**Issue by Steltek** [home-assistant/android#3525]
**Home Assistant Android app version(s):**

2023.5.2

**Android version(s):**
13

**Device model(s):**

Samsung Galaxy S21 Ultra

**Home Assistant version:**
2023.5.2

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

I have the companion app configured to use an external (HTTPS) URL when outside my network, and an internal (HTTP-only) URL when on my Wi-Fi.
When on my Wi-Fi: Using the Assist functionality and tapping the microphone to do speech to text, the latter fails due to the connection to Home Assistant being HTTP instead of HTTPS.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

[will try capture this once I am home again]

**Additional information:**

The only workaround I can think of would be to make the app always use the external (HTTPS-enabled) URL for the Assist voice functionality, and avoid the Internal Connection URL.

This could be classified as a feature request as there are workarounds that could be implemented by me (make the internal URL use HTTPS as well with a private CA and manually installed CA certs on all devices, split DNS using the internal IP on my LAN for the external hostname, ...).

**Comment by Steltek** [comment]
My case differs from the referenced issue in that there IS an HTTPS connection available. The app just isn't using it.

**Comment by jpelgrom** [comment]
I'm not sure how that's different? You control which URL is used, and choose to use HTTP. The frontend/Assist doesn't know about the different options.

**Comment by Steltek** [comment]
The companion app controls which URL is used. It could thus "fall back" to the HTTPS URL (despite being on the Wi-Fi that makes it use the HTTP URL) when I open Assist, no?

**Comment by jpelgrom** [comment]
No it can't, as Assist is part of the frontend. The app can't really detect it at the moment (though that could be solved), and can't switch without a full reload .

**Comment by Steltek** [comment]
I see. Split DNS it is then.
