### ISSUE TITLE
IBeacon not works in galaxy watch 5

### ISSUE THREAD

**Issue by DAVIZINH0** [home-assistant/android#3534]
Hello,

Since a few months i am using the ibeacon sensor in my wear os (galaxy watch 4), and works fine. The sensor i activate is "BLE TRANSMITTER"

Now, my wife bought a galaxy watch 5. I enable the "ble transmitter" and i can see in the server the "ble transmitter" as transmitting.
But i cant see the "ibeacon:xxxx" with my espresense esp32 devices.

With the galaxy watch 4 I see perfectly the ibeacon, but with the watch 5 not apears.

In both case I install the app in the watch, log out, and log in again. In watch 4 it works fine, in watch 5 not apears.
I both cases the app crashes ussually :-(
How can i obtain the logs if the app crashes in the watch :-( ?

**Home Assistant Android app version(s):** beta-10008-d81913b7

**Android version(s):**  android 13

**Device model(s):** galaxy fold4 + galaxy watch 4.  and galaxy flip4 + galaxy watch 5

**Home Assistant version:** 2023.5.3 in docker core

**Comment by dshokouhi** [comment]
you probably need to make adjustments to either the sensor settings or your detection software settings to get it to work.  The reason why it works on one watch is because that watch works with default values. You will need to make your own adjustments to settings either using notification commands sent to the watch or changing the espresence settings to find the watch. What settings you need depends on your own setup.

**Comment by dshokouhi** [comment]
try to use a different beacon monitoring app like from the phone to see if the beacon is being detected, that will tell you if the beacon is transmitting or not.

also make sure to grant the app background access in the samsung companion app for the watch

**Comment by DAVIZINH0** [comment]
can you recomend some app for android phone to detect the ibeacon with his name ibeacon:XXXXXXXX-100-1 ??

I use ble scanner and nrf connect and can detect the watch 4 with the phone where is paired the watch (in the details of one devies, i can see the UUID is like the ibeaconxxxxx but not exactly with the full ID).

When i try to find the watch5 i cant find it. in this case i use the phone where the watch5 is paired, and cant find the ibeacon.

I think the problem is the watch is not transmittion the ibeacon, but i want to confirm it. if you tell me a app that detects the ibeacon:xxxx i can confirm and continue with other test :-)

thanks a lot!!!

**Comment by StandingOwl** [comment]
@DAVIZINH0 , I followed @dshokouhi advice and espresense immediately started picking up my wife's galaxy watch 5. 

First I made sure made all the wear app permission were enabled (which they already were, tried that weeks ago). Then I used notification commands to change the advertise and transmit settings on the galaxy watch 5 using a script. 

[Notification Commands | Home Assistant Companion Docs](https://companion.home-assistant.io/docs/notifications/notification-commands/#ble-beacon-transmitter)

The key setting seems to be power which I set to "high".  This made the watch show up immediately in espresense.

For adversitse mode I tried both "low_latency" and "balanced". The watch updated it's room presense rather rapidly with balanced so I just left it that way. I haven't extensively tested other setting to see if it will still function on lower power settings yet. 

<img width="525" alt="image" src="https://github.com/home-assistant/android/assets/66896763/262cb138-e33c-4623-9fbf-1b1566a00fe5">

**Comment by DAVIZINH0** [comment]
i can confirm that works
for walaxy watch 5 you must setup the ibeacon with this parameters!!
thanks a lot for the information!

**Comment by Gil80** [comment]
> @DAVIZINH0 , I followed @dshokouhi advice and espresense immediately started picking up my wife's galaxy watch 5.
> 
> First I made sure made all the wear app permission were enabled (which they already were, tried that weeks ago). Then I used notification commands to change the advertise and transmit settings on the galaxy watch 5 using a script.
> 
> [Notification Commands | Home Assistant Companion Docs](https://companion.home-assistant.io/docs/notifications/notification-commands/#ble-beacon-transmitter)
> 
> The key setting seems to be power which I set to "high". This made the watch show up immediately in espresense.
> 
> For adversitse mode I tried both "low_latency" and "balanced". The watch updated it's room presense rather rapidly with balanced so I just left it that way. I haven't extensively tested other setting to see if it will still function on lower power settings yet.
> 
> <img alt="image" width="525" src="https://user-images.githubusercontent.com/66896763/239618834-262cb138-e33c-4623-9fbf-1b1566a00fe5.png">

Hi. 
I'm having the same issue with the galaxy watch and I tried using your explanation to get the ibeacon to work but I don't know how to do it.
Does iBeacon refer to the watch transmitting its BLE data?

I use the mqtt_room with espresense.
all I can find is `"md:0006:21"` referring to my galaxy watch 5, I believe.
the only ibeacon I see is of the espresense itself.

The `"md:0006:21"`  doesn't update the distance correctly, so I assume it's not working well for me.
Any help is greatly appreciated.
