### ISSUE TITLE
Android App Minus (-) not available

### ISSUE THREAD

**Issue by sebastianbraun6** [home-assistant/android#3556]
When trying to set up automations using the android app, when I for example want to type in Above or Below values, the only number keyboard that opens has no option for a minus (-), so I cant set up automations where the values are minus. The numbers keyboard that automaticly opens should be changed.

**Comment by dshokouhi** [comment]
Sounds like a HA frontend issue, can you reproduce the issue using chrome for android on the same device?

**Comment by sebastianbraun6** [comment]
With Samsung Internet and Chrome for Android the issue is the same, the number keyboard opens which has no option for minus.

**Comment by dshokouhi** [comment]
thanks for confirming, please file an issue with the HA frontend making sure to fill out the issue template completely so they can look into this. I also recommend checking open issues to make sure its not a duplicate

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

**Comment by jpelgrom** [comment]
This might also be because of the selected keyboard app, I do get a `-` with Gboard:

![Screenshot_20230526-202543.png](https://github.com/home-assistant/android/assets/8148535/be340e49-9e08-4d3d-9069-76d9441ef10a)

(Frontend is still the best place to report!)
