### ISSUE TITLE
Time zone inconsistencies

### ISSUE THREAD

**Issue by bnuttall** [home-assistant/android#3557]
My home is in GMT+0 and I'm currently on holiday in GMT-5.

Various UI components don't seem to know what time it is in my time zone, and display general weirdness. Please see attached: the solar forecast curve seems to be correct (home time) , but the solar production bar charts are off (local time). 

Ideally I'd see everything displayed in home time. 

![Screenshot_20230527_073647_Home Assistant](https://github.com/home-assistant/android/assets/1512012/c35f52e5-9bb2-439e-8fa8-50639aca8261)

**Comment by jpelgrom** [comment]
This looks like a HA frontend issue, can you reproduce the issue using Chrome on the same device?

**Comment by bnuttall** [comment]
![Screenshot_20230527_164022_Edge](https://github.com/home-assistant/android/assets/1512012/99e07c1d-0128-4fc7-a11b-c648d363aa2a)
Edge Android same device, accessed via nabu casa link

**Comment by jpelgrom** [comment]
That's odd as the app should show the same as a browser. However, could you check in Chrome as that is a closer match for the WebView used by the app than Edge? I don't expect a difference but good to be 100% sure.

Is it just graphs or are other timestamps (like in the logbook) also affected?

**Comment by jpelgrom** [comment]
Home Assistant (core) 2023.7 includes changes to timezone handling in the UI, does this issue still exist after updating to 2023.7.0 or later?

**Comment by jpelgrom** [comment]
Closing due to no response. If you're still experiencing issues and are up-to-date, add a comment to reopen this.
