### ISSUE TITLE
Blank screen after selecting server

### ISSUE THREAD

**Issue by adamsatyr** [home-assistant/android#3563]
**Home Assistant Android app version(s):** 2023.3.0-full

**Android version(s):** GrapeneOS 13 (TQ2A.230505.002)

**Device model(s):** Pixel 6

**Home Assistant version:**   2023.5.2

**Last working Home Assistant release (if known):** None

**Description of problem, include YAML if issue is related to notifications:**

Home Assistant app turns on, detects instance of HA and after selecting it app goes fully black and then white, nothing else can be done.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Please make sure your custom ROM has Googles version of Android system WebView and that it is up to date and set as the default WebView for the device. Sometimes custom ROMs ship with incompatible WebView that results in the login screen not displaying or functioning incorrectly.

**Comment by chytrak-house** [comment]
Hi, I encountered same issue on the GrapheneOS. 

1. The sole instalkation of WebView does not work for me.
2. What is the exact problem @dshokouhi please? Its a bit unfortunate that HA is not working on GrapheneOS by default. Is it something that can be fixed by HA or the Graphene people?

**Comment by inobrevi** [comment]
@chytrak-house 

For me it works perfecly on newest GrapheneOS (Pixel 6), I just installed WebView from Google store.

Try that, reboot the phone, (maybe reinstall the HA app) and it should work.

**Comment by dshokouhi** [comment]
> 1. The sole installation of WebView does not work for me.

you need to not only install WebView but also select it as the default webview on your device, on some devices you may even need to install it as a system wide app

> 2\. What is the exact problem @dshokouhi please? Its a bit unfortunate that HA is not working on GrapheneOS by default. Is it something that can be fixed by HA or the Graphene people?

they are shipping an incompatible version of webview that is not updatable and sometimes contain adblocking that does not work with HA frontend.

**Comment by chytrak-house** [comment]
Thanks for replies. 

I did install WebView but when I tried to set it up as default only Vanadium was an option. Maybe I am not really aware of all Androids settings but are you talking about the Browset app basically?

----

> they are shipping an incompatible version of webview that is not updatable and sometimes contain adblocking that does not work with HA frontend.

And do you know what exact error it is causing, maybe there is workaround around this? If its some adblocking stuff mabye HA can adjust for it.

**Comment by dshokouhi** [comment]
> I did install WebView but when I tried to set it up as default only Vanadium was an option. Maybe I am not really aware of all Androids settings but are you talking about the Browset app basically?

if you dont see it as an option then you may need to look into installing it as a system app so it can be selected there, how you do that I am not sure it depends on your device/ROM I think there might be an xposed module for it?



> And do you know what exact error it is causing, maybe there is workaround around this? If its some adblocking stuff maybe HA can adjust for it.

its an incompatible version of WebView often at times the version itself is very old. The workaround is to use a compatible version of WebView.
