### ISSUE TITLE
Android Navigation Back gesture activates buttons on dashboard

### ISSUE THREAD

**Issue by Tau-Neutrino** [home-assistant/android#3565]
**Home Assistant Android version:**
2021.10.0-full

**Android version:**
Android 12 (SPA1A.210812.015)

**Phone model:**
Pixel 4a

**Home Assistant version:**
core-2021.10.6

**Last working Home Assistant release (if known):**
all affected

**Description of problem:**
The android back gesture seems to activate the button which is present below the trace of the finger while performing the gesture (on finger lift-off). 
This is not the case for other apps i tested (e.g outlook, twitter, calculator, etc), therefore it seems to be an issue with the app.

**Screenshot of problem:**
Here is a screen record, which shows the issue (around 5 sec at the shield icon, which triggers the error message on the bottom):
https://photos.app.goo.gl/BT5ZShqgiFELMuxn7

**Comment by charlie969** [comment]
Same issue here (Android 13 on Pixel 7). Very frustrating when I accidentally turn devices on and off while navigating around my dashboards!

**Comment by Jazza159** [comment]
This is a daily occurrence on Android 13, Samsung s22 ultra. I've had to design dashboards with double tap actions on the items near the bottom of the screen to avoid issues. Doesn't help if you have scrolled down at all.

I've also noticed picture cards (cameras) are more sensitive and almost always open.

No issues using the dash in chrome. Just HA companion app.

**Comment by Tau-Neutrino** [comment]
Meanwhile changed phone to pixel 7, Android 13 lates version. Same issue still present. The HA app is nearly unusable with Android gestures in my opinion....

**Comment by VNRARA** [comment]
> This also impacts the burger side bar menu (3 lines in the top left). it should be possible to swipe diagonally from the left screen edge to open the side bar menu however this doesn't work in the HA app on Android

This swipe to open menu has been disabled thankfully as it was getting interfered by the back gesture causing the whole menu to be stuck one pixel out. Even if swiping diagonally is a bit different it's to precise of an action to put in the app imo.

**Comment by venator85** [comment]
After some experimentations with the app source, I think that this issue is caused by the fact that the back gesture, as soon as it started by the user, causes a `touchstart` event on the cards, which toggles the card state. This odd behavior looks like a WebView/Android bug to me, so I don't think that the HA app developers can do much about it.

A quick but ugly workaround that I'm currently using is to add a margin to the dashboard content, with a value that is sufficient to have the cards not placed in the edge areas of the screen where the back gesture happens. For example (last line):

    title: Home
    views:
      - theme: Backend-selected
        path: default_view
        title: Home
        icon: mdi:home-assistant
        type: custom:grid-layout
        subview: false
        layout:
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr))
          grid-template-rows: auto
          margin: 0px 40px

**Comment by VNRARA** [comment]
> After some experimentations with the app source, I think that this issue is caused by the fact that the back gesture, as soon as it started by the user, causes a `touchstart` event on the cards, which toggles the card state. This odd behavior looks like a WebView/Android bug to me, so I don't think that the HA app developers can do much about it.

So I opened my instance via reddit which opens a webview tap. Tried the bug. Didn't occur. Is this not the same webview?

**Comment by iDontWantAUsername** [comment]
Conversely if this is an Android/WebView defect could someone with knowledge with how to replicate log a defect in the Android project https://issuetracker.google.com/issues and link back to this ticket?

**Comment by itpeters** [comment]
> A quick but ugly workaround that I'm currently using is to add a margin to the dashboard content, with a value that is sufficient to have the cards not placed in the edge areas of the screen where the back gesture happens. For example (last line):

Thank you so much for this @venator85 . I think I would have gone crazy without this workaround.

**Comment by jwildman16** [comment]
> ```
>     layout:
>       grid-template-columns: repeat(auto-fit, minmax(250px, 1fr))
>       grid-template-rows: auto
>       margin: 0px 40px
> ```

Yes, thank you, @venator85! I didn't have `layout` in my dashboard code, so I just added these four lines and the back gesture is no longer triggering switches!

**Comment by venator85** [comment]
> > ```
> >     layout:
> >       grid-template-columns: repeat(auto-fit, minmax(250px, 1fr))
> >       grid-template-rows: auto
> >       margin: 0px 40px
> > ```
> 
> Yes, thank you, @venator85! I didn't have `layout` in my dashboard code, so I just added these four lines and the back gesture is no longer triggering switches!

You don't need the two lines starting with `grid-template`, you can remove them 😉

**Comment by patriiiiiiiiiick** [comment]
This just changed sides for me: it was problematic on the right. It now is on the left side. 

I upgraded to Android 14, in case it matters.

**Comment by Lackmake** [comment]
This is still an issue. Affects both type: button and [type: custom:button-card ](https://github.com/custom-cards/button-card). But it does not affect other types of cards eg entity-switches do not get toggled when I perform the back gesture over them. Since other cards work correctly that should mean that it is fixable for the button card, no?

**Comment by RafaelSchridi** [comment]
> After some experimentations with the app source, I think that this issue is caused by the fact that the back gesture, as soon as it started by the user, causes a `touchstart` event on the cards, which toggles the card state. This odd behavior looks like a WebView/Android bug to me, so I don't think that the HA app developers can do much about it.
> 
> A quick but ugly workaround that I'm currently using is to add a margin to the dashboard content, with a value that is sufficient to have the cards not placed in the edge areas of the screen where the back gesture happens. For example (last line):
> 
> ```
> title: Home
> views:
>   - theme: Backend-selected
>     path: default_view
>     title: Home
>     icon: mdi:home-assistant
>     type: custom:grid-layout
>     subview: false
>     layout:
>       grid-template-columns: repeat(auto-fit, minmax(250px, 1fr))
>       grid-template-rows: auto
>       margin: 0px 40px
> ```

Sadly doesn't work on bottom swipes if the page is longer than the device view.

**Comment by v6ak** [comment]
As mentioned earlier (see
https://github.com/home-assistant/android/issues/3565#issuecomment-1571719516
), it seems to be WebView's feature, not a bug.

**Comment by jwildman16** [comment]
> This just changed sides for me: it was problematic on the right. It now is on the left side.
> 
> I upgraded to Android 14, in case it matters.

Same here. Actually, the problem has reappeared on both sides for me, even though I have additional margins added. Screen recording: 

https://github.com/home-assistant/android/assets/29931390/d075cdf6-8909-47ae-a6b7-4ea56e521e6c

> @v6ak 
> it seems to be WebView's feature, not a bug.

The way I read the subsequent replies is that other webviews don't manage it this way, so it does seem to be specific to Home Assistant.

**Comment by CasperVerswijvelt** [comment]
> > This just changed sides for me: it was problematic on the right. It now is on the left side.
> > I upgraded to Android 14, in case it matters.
> 
> Same here. Actually, the problem has reappeared on both sides for me, even though I have additional margins added. Screen recording:
> 
>  screen-20231205-160819.2.mp4 
> > @v6ak
> > it seems to be WebView's feature, not a bug.
> 
> The way I read the subsequent replies is that other webviews don't manage it this way, so it does seem to be specific to Home Assistant.

As said in my earlier comment (https://github.com/home-assistant/android/issues/3565#issuecomment-1696064752), the issue can be reproduced in both chrome and in the home assistant app.

I believe that the 'touchcancel' event is just handled incorrectly in the home assistant frontend

**Comment by TheYves** [comment]
I'm wondering why the cards listen to three different events (`click`, `touchstart `and `touchend`) in order to trigger the corresponding action. In my opinion, it would be sufficient to only listen to `click` and maybe `touchend`. 

As far as I understand the problem, the issue comes from the `touchstart `event:

1. User moves finger from edge of device upwards into the app => `touchstart` is being triggered, because this is what the event is made for
2. User lifts finger up. Normally this would call `touchend`, but since Android recognizes this as a "special OS action", it doesn't trigger the `touchend` event but instead executes the corresponding OS action.
3. Since `touchstart` has been triggered, the action of the card is being executed.

I haven't tested this, it's just a conjecture. Maybe it's better to just use the `click` event and don't listen to `touchstart/touchend`. Or, as previously stated, to handle the touch events correctly, if possible.

**Comment by RafaelSchridi** [comment]
> I'm wondering why the cards listen to three different events (`click`, `touchstart `and `touchend`) in order to trigger the corresponding action. In my opinion, it would be sufficient to only listen to `click` and maybe `touchend`.
> 
> As far as I understand the problem, the issue comes from the `touchstart `event:
> 
> 1. User moves finger from edge of device upwards into the app => `touchstart` is being triggered, because this is what the event is made for
> 2. User lifts finger up. Normally this would call `touchend`, but since Android recognizes this as a "special OS action", it doesn't trigger the `touchend` event but instead executes the corresponding OS action.
> 3. Since `touchstart` has been triggered, the action of the card is being executed.
> 
> I haven't tested this, it's just a conjecture. Maybe it's better to just use the `click` event and don't listen to `touchstart/touchend`. Or, as previously stated, to handle the touch events correctly, if possible.

That's what I was thinking too, is there _any_ reason to listen to `touchstart` ?

**Comment by Ongion** [comment]
The action doesn't actually seem to trigger during `touchstart`, but during `touchend` _or_ `touchcancel`. Both events trigger `element.actionHandler.end`, which cancels the ripple animation and calls the tap/hold/doubletap event as appropriate.

Why does `touchcancel` cause the button to trigger the event? The touch was _canceled_, so at best it should just cancel the ripple animation.

When Android starts the special Back Gesture action, does it send a `touchend` event, or does it send a `touchcancel`? I would imagine it sends `touchcancel`, but I don't know for sure. If it _does_ send touchcancel, then can't we just update the handler to _not_ trigger actions on `touchcancel`?

**Comment by Lackmake** [comment]
I didn't look into the source, but can't we just look at the implantation of other cards? Most handle it correctly, for me it's just the button card that's triggered falsely

**Comment by Ongion** [comment]
I have just done some local testing. Android _does_ send `touchcancel` when it starts the Back Gesture, and making `touchcancel` return early in `actionHandler.end` gets rid of this problem. I don't know for sure if this causes any other side-effects, but I haven't found any issues so far in my own testing.

**Comment by itpeters** [comment]
@Ongion any more updates? Assuming things are still working well, are you going to open a PR?

**Comment by Lackmake** [comment]
Just to bumb this thread again: The 'tile' card has this issue too

**Comment by Ongion** [comment]
@itpeters So far I haven't had any issues. I'll look into opening a PR with this change, though it may take a bit to get my development environment set up again.

**Comment by parkkralle** [comment]
Hi, can you give us instructions on how to manually insert the change in HA OS? I can't find the file via SSH or File Editor.

**Comment by Ongion** [comment]
I was never able to actually test it on the base HomeAssistant frontend
controls. When I first encountered this issue, it was with the Custom
Button Card entity, which apparently copied or forked this code from
HomeAssistant.

With that custom control, I was able to manually add this fix, and it
worked as I would expect. But I'm not sure where you'd make this change for
a base HomeAssistant install. Presumably it's packed together with the rest
of frontend.

**Comment by michalowskil** [comment]
Motorola Edge 30 Neo. Android 13. Home Assistant Core 2023.12.4. Home Assistant Operating System 11.2.

I confirm, swiping up will click the items at the bottom of the dashboard.

**Comment by alexeiw123** [comment]
> So, I have a change that I believe would fix this, but I haven't been able to figure out how to run the test suite for frontend in my dev environment. I feel like that's probably a requirement for the PR. I'm going to try to figure this out, but if anyone who has developed for frontend before thinks they can get it done sooner, [here's the commit from my fork](https://github.com/Ongion/hass-frontend/commit/afeb2754a31d80fb9b53afd03c4ceeaf2c793b58).

How has your testing of this gone? It's like having a ghost in our house with us all being on androids that use the back gesture. Does this fix it and if so, can a PR be created?

It's amazing to me that such a glaring UX bug has been present for so long and it doesn't seem to generate any noise!

**Comment by dbaq** [comment]
Any updates on this?  Should we open a linked issue on https://github.com/home-assistant/frontend? 

Adding a 40px margin on both sides does work but we are losing some valuable space.

**Comment by mattyway** [comment]
> So, I have a change that I believe would fix this, but I haven't been able to figure out how to run the test suite for frontend in my dev environment. I feel like that's probably a requirement for the PR. I'm going to try to figure this out, but if anyone who has developed for frontend before thinks they can get it done sooner, [here's the commit from my fork](https://github.com/Ongion/hass-frontend/commit/afeb2754a31d80fb9b53afd03c4ceeaf2c793b58).

I have tested the change from this commit and it fixes swiping back on a tile triggering the "tap" behaviour for me. I tested with a Pixel 7 running Android 15 with Home Assistant app version 2024.10.3-full.

Before: https://github.com/user-attachments/assets/5a4aedd0-7013-47e3-9dda-77a66aedfd6c

After: https://github.com/user-attachments/assets/a2fcc3f4-1fd9-4de3-a03e-25b3057c8262

**Comment by dbaq** [comment]
Shoutout to @mattyway for fixing this!

**Comment by dshokouhi** [comment]
Wow big shout out there!!! Thank you @mattyway and @Ongion  ! As this is fixed I am going to close the bug now. This is merged so will be in HA core 2024.12

**Comment by trashbytes** [comment]
This is still or again happening constantly. Anything we can do about that?

**Comment by ghost** [comment]
Seeing similar behaviour myself
