### ISSUE TITLE
Support Android 14's new Device Control feature to embed a custom activity 

### ISSUE THREAD

**Issue by Hupro** [home-assistant/android#3566]
**Is your feature request related to a problem? Please describe.**
Home Assistant currently supports the Android's Device Control feature which works great. Android 14 (and possibly 13 QPR3) adds a new feature to allow an app to add a custom embedded activity as a part of Device Controls called [META_DATA_PANEL_ACTIVITY](https://developer.android.com/reference/android/service/controls/ControlsProviderService#META_DATA_PANEL_ACTIVITY).  

**Describe the solution you'd like**
Allow for a users lovelace dashboard to be an embedded activity when opening Android' Device Control feature to provide a more consistent experience.    

**Describe alternatives you've considered, if any**
Leaving the Device Control implementation as is. The current implementation works good but I believe supporting this new feature when it's ready would make the experience nicer.   

**Additional context**
This feature has been shown with the Google Home app on the upcoming Pixel tablet. According to this [9to5Google article](https://9to5google.com/2023/05/10/google-pixel-home-panel-controls/), Pixel devices should be getting this feature this month so it seems like the feature may start working with Android 13 QPR3 and may not require Android 14.  [This article also shows](https://9to5google.com/2023/03/28/google-home-device-controls-redesign/) the Google Home app initially testing the change and it working on the 13 QPR3 beta.

**Comment by jpelgrom** [comment]
I think this should be presented as an option controlled by the user to prevent a breaking change, if possible. 

(Personally I also like the more focused, super fast native experience instead of having to build a dashboard.)

**Comment by dnestico** [comment]
+1 please support this!

**Comment by jpelgrom** [comment]
aka ['Home Panel' for Google Pixels with QPR3](https://blog.google/products/pixel/feature-drop-june-2023/#:~:text=Quick%20access%20to%20smart%20home%20controls)

**Comment by jpelgrom** [comment]
Working on this right now.

Looks like you actually need to remove all existing controls before the new panel activity is shown. Still, the app settings will allow you to choose between the existing controls with multiserver/lock screen integration, or a dashboard panel as controls.

https://github.com/home-assistant/android/assets/8148535/d5440098-8053-4fcf-aadb-7889a074e5d2

**Comment by dnestico** [comment]
Awesome man, it looks like it's working great! 👍

I might create a subview just for this so that way the top nav bar disappears, but that's imo.
