### ISSUE TITLE
open My Home Assistant Links in App

### ISSUE THREAD

**Issue by Aaroneisele55** [home-assistant/android#3568]
Hello,
I have the idea that My Links should be opened in the Home Assistant App because with MFA enabled, it is annoying to have to log in every time I open such a link.

Best regards
Aaron

**Comment by dshokouhi** [comment]
The app is registered to handle those links actually. If you check app info you should see it.

**Comment by Aaroneisele55** [comment]
I have checked, it is registered but it still opens the browser for those links
![Screenshot_2023-06-04-08-26-45-42_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/home-assistant/android/assets/87670899/8937d5e8-8686-4115-ab07-abccfc650b91)

**Comment by dshokouhi** [comment]
That sounds like a device issue then rather than a feature request. We will need more info on the device and possibly network setup to troubleshoot.

**Comment by Aaroneisele55** [comment]
Ok, I have a OnePlus Nord with the latest Android 12 Version and the HA App from Play Store

**Comment by dshokouhi** [comment]
@Aaroneisele55 we will need more info than that. If you create a new issue there will be an issue template presented that contains all the data we need to investigate. We also need to understand your networking setup like if you have a proxy or something else.

**Comment by unhold** [comment]
Automatic forwarding from Android browser to app was disabled in most browsers. HomeAssistant can't change that.

In Firefox for Android, you can go to: Menu -->Open in app.
In Chrome for Android, use the sharing menu find the url-registered app on top.

**Comment by jpelgrom** [comment]
> Automatic forwarding from Android browser to app was disabled in most browsers.

This was changed in Firefox recently but it should still ask you if you want to open the app, and it should still work automatically with Chrome (as the screenshot shows, the system has verified the links/checked ownership).

Knowing which browser is used will be useful :)

**Comment by Aaroneisele55** [comment]
Closing this as I found the setting in the Opera Browser that fixes this:

Person icon at the bottom (or top depending on setttings) -> gear icon -> Privacy and security -> site settings -> external app -> my.home-assistant.io -> toggle "always open in app"
