### ISSUE TITLE
Thread credentials synchronization not working

### ISSUE THREAD

**Issue by LogimacGER** [home-assistant/android#3582]
### Describe the issue you are experiencing

Im using Multiprotocol with SkyConnect. ZHA working fine.
Matter, Thread and Open-Thread-Border-Router is visible under "devices".
Last week i got a EVE energy matter device. When i want to add it with HA android app i get a message "border router needed".
I don't have any other border-router (Homepod or Nest hub) in my network.

<img width="462" alt="Unbenannt" src="https://user-images.githubusercontent.com/121462834/230588919-a02a73ed-f576-40fe-bbce-928d18ade8ea.PNG">

![Screenshot_2023-04-07-11-52-31-60_f7aa348215f5d566f9e4ca860f474209](https://user-images.githubusercontent.com/121462834/230590072-da5d6b34-3d83-498d-8ec8-9306b8053dcb.jpg)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

1.1.1

### Steps to reproduce the issue

1. Adding a Matter Thread device.

## System Information

version | core-2023.4.1
-- | --
installation_type | Home Assistant OS

dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.31.0
Stage | running
Available Repositories | 1251
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.0
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 219.4 GB
disk_used | 9.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), Terminal & SSH (9.6.1), ArgonOne Active Cooling (29c), SSH & Web Terminal (13.1.0), Matter Server (4.2.0), Silicon Labs Multiprotocol (1.1.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 1. April 2023 um 14:42
-- | --
current_recorder_run | 7. April 2023 um 07:54
estimated_db_size | 700.81 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by agners** [comment]
@LogimacGER have you been able to resolve this issue? If not, what type of installation are you running?

**Comment by LogimacGER** [comment]
@agners this issue is still present. I'm running the latest version of Homeassistant OS on a raspberry pi 4 4GB (with M.2 SATA SSD) with sky connect (ZigBee devices working without problems). Also Matter and silicon laps multiprotocol is up to date. It seems my phone can't finde open thread boar router on my network. Homeassistant is connected via LAN and my phone with wifi of course. I tried another android phone but without success.

Once I did a clean install of Homeassistant but that did not work .

**Comment by agners** [comment]
@LogimacGER can you check the questions in comment https://github.com/home-assistant/android/issues/3582#issuecomment-1590599468?

It seems that the App has difficulties reaching Home Assistant for these particular requests. What type of HA installation do you use?

**Comment by LogimacGER** [comment]
@agners What are you meaning with "type of HA installation"? HA OS on a Raspberry pi. 
I don't have problems using the app.

**Comment by jpelgrom** [comment]
For anyone still experiencing issues, could you download the latest update for the Android app (available now from the Play Store, version 2023.7.5), manually sync Thread credentials in Settings > Companion app > Troubleshooting and post the result here? That should make it easier to understand where it's failing.

**Comment by LogimacGER** [comment]
Homeassistant prefer a different network than my phone does. Maybe become HA rund over LAN and my phone over WiFi?

When I'm at home I set up Homeassistant over WiFi only.

![Screenshot_2023-07-13-08-16-25-25_680d03679600f7af0b4c700c6b270fe7](https://github.com/home-assistant/android/assets/121462834/c7b7161c-38be-40b6-8c42-60b1c6503d47)

**Comment by jpelgrom** [comment]
> Homeassistant prefer a different network than my phone does. Maybe become HA rund over LAN and my phone over WiFi?

LAN/WiFi shouldn't matter, this is about Thread networks :) Not sure why your device prefers a different (non-existent?) Thread network named 'home-assistant'.

Unfortunately there is no way change the preferred Thread network on Android devices currently. The only 'solution' we know about is to clear all data for the Google Play Services app (system settings > Apps > All apps > Google Play Services > Storage & cache > Manage space), which stores the Thread networks. Keep in mind that clearing this will also clear other Google data that only exists on your device such as your Google Wallet cards (😥).

**Comment by jpelgrom** [comment]
Closing this as the original author has resolved the issue, and the app has received several updates to improve Thread credentials sync:

- Manually sync and view results in settings menu to help with troubleshooting (in stable release 2023.7.5-full)
- Improved updating/removing of credentials previously added by the app during sync (in beta release)

If anyone is still facing issues with Thread sync to Android, feel free to open a new issue with the output of the manual sync option while using the latest beta (or next stable) release of the app, and information about your setup.
