### ISSUE TITLE
Please! Remove Driving mode from AAOS Companion app!

### ISSUE THREAD

**Issue by HWiese1980** [home-assistant/android#3587]
**Is your feature request related to a problem? Please describe.**
Kind of. I think the Driving Mode of the AAOS companion app is nonsense, counterproductive, makes things worse instead of more safe. It is clunky, inconvenient, confusing and ugly. It does not make sense to force me into this mode where I have to dig through ugly menues until I find what I'm looking for instead of letting me operate the dashboard I've built myself particularly for the car. Instead of pressing one big button blindly because I know where it is, I have to press three, four buttons that I have to find first, while looking at the screen, to simply open my garage. Or instead I just grab my phone. 

That is, if it works at all. Most of the time when I'm on the road I just see a spinner indicating that it's (not) loading. 

It makes things worse, seriously. Ditch it if you can! Please, I beg you!

**Describe the solution you'd like**
Native mode only. I have a dedicated account in my HA for the car, and I have a dedicated dashboard solely for the car. It's quick, convenient, clear, concise and does not distract me at all. It does not force me to take my eyes off the road and it does not make me grab my phone instead. 

**Describe alternatives you've considered, if any**
Haven't considered any yet. I don't think there are any. Please ditch the driving mode! 

**Additional context**
No additional context. Just my pure initial experience with the app. Even the integrated Google Maps is more distracting than a sophisticated custom home assistant dashboard, and Maps has no forced driving mode. Really, please drop it if you can!

**Comment by dshokouhi** [comment]
This is not something we have control over. Google explicitly requires us to have this particular screen which is actually all that Android Auto users currently get.

https://developer.android.com/training/cars/apps/iot
https://developer.android.com/docs/quality-guidelines/car-app-quality?category=iot#app_categories

There is no getting around this. In fact we got approval for the Automotive app to be able to switch to your dashboard when in park and that is not given to all apps per my understanding

I believe your frustrations with the grid screen will be resolved once the following issue is resolved: https://github.com/home-assistant/android/issues/3219

**Comment by HWiese1980** [comment]
What a goddamn shame... I literally can't stop shaking my head about this ridiculous amount of preemptive obedience. It's really a gnawing feeling of powerlessness that comes along, facing such utter loss of reality by those who decide nonsense like this... It *could* be absolutely perfect if it wasn't for the idiocy of such office sitters. They dictate, destitute of any sanity and sense of reality, based on pure guesswork and fear - and the result is laughter and a punch in the face of everyone who really has a clue. 

A shame... a real goddamn shame... That's why we can't have cool stuff!

Well... I guess I'll have to live and cope with this bullshit and for my own safety rather grab the phone instead of relying on what Google's small-time academics force upon us. 

**Thanks anyway for your great work, guys, even if it is horribly stifled and crippled by cowards and idiots. Your time, your effort and your understanding for a deeply frustrated and disappointed old man is really appreciated!**
