### ISSUE TITLE
Home Assistant freeze on "Initializing"

### ISSUE THREAD

**Issue by gsanhaji** [home-assistant/android#3591]
Android 9.0
App version:  2023.3.0
Device: Akuvox C319
HAOS: 2023.6.2

The Companion app lunch but after choosing the server, it freezes on "Initializing"
I reinstalled the device and th app but the problem is still the same.
When i lunch HA on a web browser from the same device, it works...

![IMG_6054](https://github.com/home-assistant/android/assets/110345517/f55db1b2-6f7e-4f4d-ab0b-566a20063217)

**Comment by jpelgrom** [comment]
Please do not delete the template. It includes questions that provide useful information.

Did it work previously or is this the first time using the app on this device? If it previously worked correctly, what changed?

Can you try updating to the latest version of the app?

Is the WebView on your device up-to-date? The frontend is encountering an error which suggests it may not be.

**Comment by gsanhaji** [comment]
Hi, 
Thank you for this quick answer.
Yes, it was working before. The only thing that changed is the update to the new version of HAOS.
I just updated to the new version of the app and it's still doing the same problem. I did it with installing from F-Droid and also by downloading directly the .apk from APKcombo.

**Comment by gsanhaji** [comment]
Please how can i check if the WebView is up-to-date?

**Comment by jpelgrom** [comment]
You can check the WebView version in your system settings > Apps > Android System WebView. Version numbers follow Chrome so I believe 114 is the latest, but anything from the last few months or so should be fine.

**Comment by gsanhaji** [comment]
Sadly on this device, we do not have access to that and it was working couple days ago with the previous core of HAOS

**Comment by gsanhaji** [comment]
@jpelgrom 
I updated the WebView and i still have the problem...

**Comment by jpelgrom** [comment]
Do you know if it's using the WebView you updated? To make things more complicated you device may have multiple apps providing a WebView 😅. This can be checked in developer options.

**Comment by gsanhaji** [comment]
No, i don't have access to that on the OS of the device.

**Comment by jpelgrom** [comment]
I'm afraid there is not much more that the app can do if your device is so locked down. The initializing screen comes from the frontend, you could try [opening an issue for it](https://github.com/home-assistant/frontend/issues) but they'll also want things like a webview version number/might conclude it is simply too old and unsupported.

**Comment by expec8** [comment]
Hello, i had the same problem yesterday and solved it by installing chrome canary from the play store, which also installed "webview dev tools", then you have to go to settings > develor options > webview implementation (or something like this), and change the webviewer to the chrome canary. This solved my problem.

Cheers

**Comment by Lico-Tom** [comment]
I had a similar problem, except that one android phone could connect, but other android devices could not.
