### ISSUE TITLE
Complications do not update via TTW (tilt to wake) on WearOS

### ISSUE THREAD

**Issue by DaZeroXB** [home-assistant/android#3592]
**Home Assistant Android / WearOS app version(s):**
2023.6.0-full / 2023.6.0
**Android / WearOS version(s):**
13 / 3.5
**Device model(s):**
Google Pixel 7 Pro / Google Pixel Watch
**Home Assistant version:**
2023.6.0
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
According to https://companion.home-assistant.io/docs/wear-os/ -> **Complications**:
 `The complications are updated automatically whenever the screen is turned on and roughly every 15 minutes. You can force a complication to update by tapping it on the watchface.`

However, this does not work in combination of **AOD + TTW**. When moving your wrist the display goes on but the complications won't update. With **AOD off** and **TTW on** it is working. If **AOD and TTW on** and you **tap** the display to wake it, it is also updating as expected.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
https://photos.app.goo.gl/jtpB5sxGQL8z6gGX6

**Additional information:**
Since I do not know how to add labels, feel free to add one. Thnx.

**Comment by jpelgrom** [comment]
The app relies on the system to tell that the screen is turned on. If the system isn't sending that information to the app when using tilt to wake... Not sure if there's something that can be done about it except noting it in the documentation. Technically it's not wrong, the display doesn't turn off 🤔

https://github.com/home-assistant/android/blob/b285c9525dd4837a82db931c1b2321c0511494e6/wear/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt#L107

Doing the same on a Galaxy Watch 4, it does get updated when tilting to wake + always-on display, so it might be device-specific.

@dshokouhi As you have a Pixel Watch any chance you could see if it does fire other intents in the described situation?

**Comment by DaZeroXB** [comment]
As far as I remember it worked a couple weeks ago. It might stopped working
after the Pixel Watch June Update or the HA release from 12. of June

Joris Pelgröm ***@***.***> schrieb am Sa., 17. Juni 2023,
09:07:

**Comment by dshokouhi** [comment]
I am indeed getting the screen on intent when tilt to wake is enabled and I tilt my wrist. My Pixel Watch is also on the latest QPR3 june update and the android app is on the latest beta version.

```
2023-06-20 10:16:58.354  6843-6843  SensorReceiver          io.homeassistant.companion.android   D  Received intent: android.intent.action.SCREEN_ON
2023-06-20 10:16:58.373  6843-6843  LastUpdate              io.homeassistant.companion.android   D  Last update is android.intent.action.SCREEN_ON
2023-06-20 10:16:58.459  9391-9929  ScreenEventListener     com...le.android.wearable.assistant  I  screenStateReceiver - android.intent.action.SCREEN_ON, conditions: isScreenOn=true, isKeyguardLocked=false, action:screenOn
```

**Comment by jpelgrom** [comment]
> I am indeed getting the screen on intent when tilt to wake is enabled

But also when always on display is enabled in addition to tilt to wake, as the combination is said to be the issue?

**Comment by dshokouhi** [comment]
> But also when always on display is enabled in addition to tilt to wake, as the combination is said to be the issue?

oops missed that, heres a better run down of what I see

AOD ON + TTW ON = No screen on intent when tilting wrist
AOD OFF + TTW ON = Yes screen on intent when tilting wrist
AOD OFF + TTW OFF = Yes screen on intent on tap
AOD ON + TTW OFF = Yes screen on intent on tap

**Comment by jpelgrom** [comment]
Any other intents for "AOD ON + TTW ON" we could register for or should we note this exception in the docs instead?

**Comment by dshokouhi** [comment]
I didnt see any intents at all get fired, im gonna assume its a bug in Wear OS for pixel watches. I know there have been a few AOD related bugs in the past.

**Comment by DaZeroXB** [comment]
Thanks Daniel for digging into it. I believe this is a Pixel Watch bug introduced in QPR3 June release.

**Comment by dshokouhi** [comment]
in that case its out of scope for our app, we will need to Google to fix that bug so it can continue to work again.

**Comment by DaZeroXB** [comment]
For sure, nothing to be done on your end. I've created a bug report in Google's issue tracker for WearOS.

https://issuetracker.google.com/issues/288303230

**Comment by dshokouhi** [comment]
closing as the app cannot make any changes here
