### ISSUE TITLE
BUG: device_class for battery_power sensors should be energy_storage instead of power

### ISSUE THREAD

**Issue by rrozema** [home-assistant/android#3599]
**Home Assistant Android app version(s):**
2023.6.0-full

**Android version(s):**
13 TKQ1.220829.002

**Device model(s):**
M2011K2G

**Home Assistant version:**
Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.3
Frontend 20230608.0 - latest

**Last working Home Assistant release (if known):**
N/A

**Description of problem, include YAML if issue is related to notifications:**
The battery_power sensors for the phones in my household show up in my power usage graphs, where they shouldn't. The sensors to show in these graphs are selected by their device_class having a value of 'power'. The battery sensors for our phones are however not power sensors, they are energy storage sensors.

**Companion App Logs:**
N/A

**Screenshot or video of problem:**
N/A

**Additional information:**
- Go into Developer Tools.
- Select the STATES tab
-In the Attributes column's search field, enter "device_class: power"
- observe that the battery_power sensors have a device_class of power, amidst real power consuming/producing device sensors.

Expected behavior
The battery_power devices should have device_class: energy_storage.
https://developers.home-assistant.io/docs/core/entity/sensor/#available-device-classes

**Comment by dshokouhi** [comment]
Actually the battery power sensor measures the current power used on the device. It's not about capacity in this regard like the docs mention. It's about usage.

**Comment by rrozema** [comment]
ok, that does match the fact that unit_of_measurement is set to W. If somehow state of charge was measured, the unit should have been Wh or something similar. So on second thought I think I have to agree this issue can be closed after a dev can confirm that this is indeed the intended purpose of the sensor. (and I'll just remove the sensor from my phones to not have them show in my "home power usage" graphs).

**Comment by dshokouhi** [comment]
Here is the original PR

https://github.com/home-assistant/android/pull/2799
