### ISSUE TITLE
Cannot add template widget (Android)

### ISSUE THREAD

**Issue by rolex86** [home-assistant/android#3601]
**Home Assistant Android app version(s):**
2023.6.0-full
**Android version(s):**
12 SKQ1.211006.001
**Device model(s):**
Xiaomi Mi10T
**Home Assistant version:**
Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.3
Frontend 20230608.0 - latest
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Cannot add new template widget in Android. The add widget button is grayed out. The jinja code I insert in developer tools works without problem, but not in android template widget (error when rendering template). 

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![1687506012791](https://github.com/home-assistant/android/assets/92719346/fd2d4926-a573-4ab6-8dcb-ebc94f3ab8b8)

**Additional information:**

**Comment by jpelgrom** [comment]
Could you try adding the template, and then check the app logs for any errors? That might give a clue as to what is causing the issue.

Does the default value (that is shown when creating the widget) work correctly?

**Comment by rolex86** [comment]
this is the part of the log that seems to be related to the widget bug:

`06-23 10:13:55.885 21321 21321 E TemplateWidget: Unable to render template: Zde zadejte šablonu
06-23 10:13:55.885 21321 21321 E TemplateWidget: io.homeassistant.companion.android.common.data.integration.IntegrationException: retrofit2.HttpException: HTTP 410 Gone
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.renderTemplate(IntegrationRepositoryImpl.kt:199)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$renderTemplate$1.invokeSuspend(Unknown Source:15)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at android.os.Handler.handleCallback(Handler.java:938)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at android.os.Looper.loopOnce(Looper.java:210)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at android.os.Looper.loop(Looper.java:299)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at android.app.ActivityThread.main(ActivityThread.java:8293)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at java.lang.reflect.Method.invoke(Native Method)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
06-23 10:13:55.885 21321 21321 E TemplateWidget: Caused by: retrofit2.HttpException: HTTP 410 Gone
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
06-23 10:13:55.885 21321 21321 E TemplateWidget: 	at java.lang.Thread.run(Thread.java:1012)`

HTTP 410 Gone - I don't know what could be causing this error. The only thing I can think of is if it's not a problem that I'm connected via VPN (I'm not on the home network where my HA server is physically located).

**Comment by jpelgrom** [comment]
HTTP 410 Gone usually means that the webhook used by the app is no longer available. Other functionality such as sensors will also have stopped working. Is the app still listed in Settings > Devices & services > Mobile app?

The easiest way to fix this, is to log out and back in again so that a new registration is made.

**Comment by rolex86** [comment]
Logging out and logging back in has really solved the problem. The template widget is already working and it shows what I need. Thanks!
