### ISSUE TITLE
Android app crash when using with Android Auto

### ISSUE THREAD

**Issue by sakos** [home-assistant/android#3633]
**Home Assistant Android app version(s):**
2023.6.0-full

**Android version(s):**
13
Security update (YYYY-MM-DD): 2023.06.01 

**Device model(s):**
Samsung Galaxy S22
Ford Sync3

**Home Assistant version:**
2023.6.3
User interface 20230608.0

**Last working Home Assistant release (if known):**
Never worked

**Description of problem, include YAML if issue is related to notifications:**
I want to control gate opener via Android Auto interface of HA.
Touching any button on the Android Auto interface leads to immediate restart of the HA application on the phone.
Not only the gate opener entity but touching any (Switch, Button, Lamps, etc) icon on the screen makes the app crashing.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**
I am not familiar with debug log collection method, however I am ready to reproduce the issue and collect whatever logs based on your instructions.

**Comment by dshokouhi** [comment]
If the app is crashing we will need logs from either Android studio or an app line logcat reader both will require USB to a computer. We do have some crash fixes going out in the next beta so if you join the beta from the play store you can get those fixes sooner. Not sure if those will fix this issue but quite possible based on the description.

**Comment by sakos** [comment]
The issue is not present with the current beta version of the app. 
Nevertheless, the usability should be improved to get quick access to the needed 1-2 buttons and get rid of browsing menus and among unused icons. I think it is covered by https://github.com/home-assistant/android/issues/3250 hence this ticket can be closed.

**Comment by ingenika** [comment]
https://androidautorepair.github.io/repair
