### ISSUE TITLE
App always tries to connect to local HA address, even when I'm not using WIFI

### ISSUE THREAD

**Issue by Misiu** [home-assistant/android#3659]
**Home Assistant Android app version(s):** 2023.6.0-full

**Android version(s):** 10 (EMUI 12)

**Device model(s):** Huaweii P20 (EML-L29)

**Home Assistant version:** Home Assistant 2023.7.1

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
I set up Companion App some time ago, but recently I've tried to set up an internal connection URL. I use the settings shown below:

![Screenshot_20230713_100726_io homeassistant companion android](https://github.com/home-assistant/android/assets/1741838/acba7900-88b2-44ec-8ac6-14597eb3a68d)

I've set up an external URL (this works fine), then I've entered SSID's of my local networks and my local instance URL.

Sadly every time I try to open the app I get this error message:

![Screenshot_20230713_101305_io homeassistant companion android](https://github.com/home-assistant/android/assets/1741838/db974996-551f-42bb-bbd4-8dd1bd134d01)

and after clicking `Wait` I get this:

![Screenshot_20230713_100545_io homeassistant companion android](https://github.com/home-assistant/android/assets/1741838/9672dd39-ba88-4b68-9090-07196da0f464)

As you can notice the Companion App is trying to connect to my local instance, even I'm not connected to WIFI.

I thought that the app checks if I'm connected to WIFI, then it checks the name of the network I'm connected and only if the name is on the list it tries the local instance URL.
I've cleaned the app files, reinstalled it, but that didn't help.

**Companion App Logs:**

```
--------- beginning of main
07-13 10:04:29.182 15533 15533 E libc    : Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
07-13 10:04:29.183 15533 15533 E mpanion.androi: LoadAppImageStartupCache enabled : 1
07-13 10:04:29.187 15533 15533 E mpanion.androi: Not starting debugger since process cannot load the jdwp agent.
07-13 10:04:29.229 15533 15551 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
07-13 10:04:29.346 15533 15569 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@5a72877
07-13 10:04:30.634 15533 15533 E GeocodeSM: Somehow location is null even though it was successful
07-13 10:05:36.911 15533 15533 E WebviewActivity: onReceivedError: errorCode: -8 url:http://192.168.0.10:8123/
07-13 10:06:00.202 15533 15533 E HwViewGroupImpl: parse speed value length error
07-13 10:06:00.289 15533 15533 E GeocodeSM: Somehow location is null even though it was successful

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Please provide more logging, the logs actually show which URL is attempted to be used and the decision making process behind it.

Please also confirm what option you selected under Settings > Companion App > Select your server > Home Network WiFi SSID > When loading dashboard and unknown if connected ....

**Comment by Misiu** [comment]
@dshokouhi thank you for the reply.
Sadly I see nothing more in logs, I have only one server configured as shown on screens in my initial message.

One thing I noticed: I just restarted my phone, **enabled localization (GPS)**, and the app seems to detect which URL to pick correctly.

So the question is: do I must have localization enabled all the time to have this working correctly?

**Comment by jpelgrom** [comment]
Yes, location is required to determine the WiFi connection.

When location is off, the app should warn you and will use the setting in _Settings > Companion App > Select your server > Home Network WiFi SSID > When loading dashboard and unknown if connected to Home Network WiFi_ to choose between Home Assistant URL and internal connection URL instead.

**Comment by Misiu** [comment]
I didn't notice that the section below WiFi SSID's is an option list:
![ha_app](https://github.com/home-assistant/android/assets/1741838/034a7827-434e-4e06-a4d1-780171d7cda0)
When I set that option everything works as expected.
