### ISSUE TITLE
hacs不显示

### ISSUE THREAD

**Issue by gky008** [home-assistant/android#3664]
感觉是内核问题，用chome浏览器显示正常…求修复

**Home Assistant Android app version(s):**

**Android version(s):**

**Device model(s):**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Please update the post and fill in the issue template otherwise we won't be able to help

**Comment by jpelgrom** [comment]
Putting the title and text through a translation tool... Something about HACS not being visible. Have you already tried clearing the cache as instructed?

**Comment by dshokouhi** [comment]
closing due to lack of response from author
