### ISSUE TITLE
High Accuracy Mode Turns on only when leaving Home zone, Never when approaching Home Zone

### ISSUE THREAD

**Issue by rtorchia** [home-assistant/android#3677]
**Home Assistant Android app version(s):**
2023.7.5-full
**Android version(s):**
Android 12
**Device model(s):**
Samsung Galaxy S10 
**Home Assistant version:**
Home Assistant 2023.7.2
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
High accuracy is not turning on whenever I approach my Home Zone, it only turns on whenever I leave my Home Zone.
Trigger zone range is set to 1000 m, and Home zone to 180 m.
Home Assistant records several GPS locations within the trigger zone whenever I am arriving home, but Hight Accuracy never turns on.

I did see that this was reported by others and that it should have been corrected with the last app release, but it is still not working with my devices.

The app does have 2 servers registered with it. One Home and one Office, but the office one I don't have background location turned of for it, only my Home.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
please open hte app and reproduce the issue and get the companion app logs, we wont be able to help without them

**Comment by dshokouhi** [comment]
Closing due to lack of response from author
