### ISSUE TITLE
App temporarily freezes after showing sensor history

### ISSUE THREAD

**Issue by jbrepogmailcom** [home-assistant/android#3680]
**Home Assistant Android app version(s):**
2023.7.5-full

**Android version(s):**
12

**Device model(s):**
Samsung A52

**Home Assistant version:**
latest

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

Hello.

This is new behavior that started after upgrade HA and Companion app.

When I click on sensor history, it is displayed, but then the application freezes for about half minute, and nothing can be tapped. The OS is telling that app does not respond and is asking if I want to kill the app or wait.

Before the app worked fine. I tried to delete whole sensor history in home-assistant_v2.db, but it did not help

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Please open an issue with the HA frontend, this is not an app issue. Make sure to complete their issue template as they request additional information

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

Ref: https://community.home-assistant.io/t/app-started-freezing-with-2023-7-5-full/592702
