### ISSUE TITLE
Long-pressing power does not start recording if the assist dialog is already open

### ISSUE THREAD

**Issue by chatziko** [home-assistant/android#3690]
**Home Assistant Android app version(s):** 2023.06.05.1

**Android version(s):** Android 13

**Device model(s):** Oneplus Nord

**Home Assistant version:** 2023.07.1

**Description of problem, include YAML if issue is related to notifications:**

The latest companion app allows to launch assist and immediately start recording by long pressing the power button (after configuring it as the default android assistant). This is very convenient since it works from any app (and also from the lock screen), so assist is always just one click away.

Now, after giving a command, it is likely that the user might want to give a __second command__. A normal reaction would be to long-press the power button again, which is what the user has learned to do to launch assist. However, when assist is __already open__, long-pressing the power button gives a haptic vibration feedback, the dialog stays open, but the microphone __does not start recording__. To start recording the user needs either to tap the microphone icon (a different action than what he did the first time), or to close the dialog and reopen it again by long-pressiong power (tedious).

I think the expected behaviour for users would be long-pressing power to immediately start recording, even when the dialog is already open.

**Comment by jpelgrom** [comment]
Agreed, looks like Google Assistant just completely starts over but we can start the microphone input again. Submitted a change for this.

**Comment by chatziko** [comment]
Awesome, thank for the quick fix.

Quick note, the same behaviour happens in the following scenario:
- open assist
- lock the phone while assist is open by pressing power
- long press power while the phone is locked.

This brings back assist but without the mic recording.

**Comment by jpelgrom** [comment]
That scenario will also be handled by the submitted change.
