### ISSUE TITLE
alarm time incorrect.

### ISSUE THREAD

**Issue by harry7474** [home-assistant/android#3696]
**Home Assistant Android app version(s):**

**Android version(s):** 
10

**Device model(s):**
galaxy S9

**Home Assistant version:**
2023.7.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
when i set the alarm on the phone to 5:30, s9_next_alarm shows 5:25. when i set it to 6:30, s9_next_alarm shows 6:25. IOW, always 5 minutes earlier.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
Are you using an allow list?

Keep in mind this sensor is leterally what it says: the _next_ alarm. Android doesn't provide any other information, or allow Home Assistant to get a list of alarms. The attribute will tell you which app scheduled the alarm. Some apps, notably including some Samsung default apps, misuse alarms and schedule other alarms that you may not see in the UI.

**Comment by dshokouhi** [comment]
Closing due to lack of response from author
