### ISSUE TITLE
Wifi SSID and Wifi BSSID not reporting status after deprecation fixes

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#3704]
**Home Assistant Android app version(s):**

latest master

**Android version(s):**

13

**Device model(s):**

Pixel 7 pro

**Home Assistant version:**

2023.7.x

**Last working Home Assistant release (if known):**

N/A

**Description of problem, include YAML if issue is related to notifications:**

After running the latest master branch Wifi SSID and BSSID are no longer being retrieved

**Companion App Logs:**

```
n/a
```

**Screenshot or video of problem:**
![image](https://github.com/home-assistant/android/assets/1634145/55c60b86-ba11-4e08-afc9-2d277650ee1c)

**Additional information:**
all other wifi data is present

**Comment by jpelgrom** [comment]
Somehow I didn't catch this during testing...

It looks like 'location information' like the (B)SSID [is only available in the callback version](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#FLAG_INCLUDE_LOCATION_INFO). I tried making this kind of-synchronous with a `suspendCoroutine`, but if the network doesn't exist it is never called and needs to rely on a timeout which isn't a great experience, especially as it previously was instant. I suggest returning to using a deprecated function for this and hope Google doesn't take it away in future Android versions.

**Comment by dshokouhi** [comment]
> hope Google doesn't take it away in future Android versions.

🤞
