### ISSUE TITLE
WearOS - control Bedtime mode

### ISSUE THREAD

**Issue by velaar** [home-assistant/android#3709]
It would be nice to have an ability to control Bedtime Mode on WearOS via notification interface. We can already control DND move but on my watch it doesn't disable the auto backlight functionality. 

There were multiple issues related to sensors but none for controlling the variable. I wonder if there is an alternative to do it via intents but was unable to find any relevant documentation.

**Comment by dshokouhi** [comment]
We actually dont have access to overriding Ringer Mode or anything like that on Wear OS. I dont think we will be able to change bedtime mode as that will require write settings permissions which is not available on Wear OS

**Comment by dshokouhi** [comment]
the only notification commands currently supported on Wear OS are bluetooth and TTS related a lot of the others wont qualify because the special permission does not exist on wear OS

**Comment by dshokouhi** [comment]
Unless android allows us to write to system settings in Wear OS this will not be possible. Closing for now.

**Comment by velaar** [comment]
@dshokouhi sorry for bugging you but will this implementation be possible? https://github.com/rhaeus/dnd-sync

**Comment by dshokouhi** [comment]
> @dshokouhi sorry for bugging you but will this implementation be possible? https://github.com/rhaeus/dnd-sync

we need to avoid directing users to ADB commands which is exactly what that app is doing. There needs to be an official way to do this.
