### ISSUE TITLE
Controls for alarm domain in Android Auto

### ISSUE THREAD

**Issue by sparkydave1981** [home-assistant/android#3710]
**Is your feature request related to a problem? Please describe.**

No problem, just no current ability to control the alarm domain in Android Auto
**Describe the solution you'd like**

Ability to control the `alarm_control_panel` domain from Android Auto HA app
**Describe alternatives you've considered, if any**

Currently planning to create a template sensor to display current status of alarm, then scripts for arming and disarming.
**Additional context**

https://community.home-assistant.io/t/home-assistant-coming-for-your-car/522288/189?u=sparkydave

**Comment by dshokouhi** [comment]
This might be a domain where we can switch between `disarmed` and `armed_away` I think but I am not sure how that will work when there is a code for `alarm_control_panel` that will need some thought given to it. Personally speaking I don't use a code for my own `alarm_control_panel` but still need to consider it.

**Comment by dshokouhi** [comment]
This request will require some extra thought as we do indeed need to provide the alarm code if a code is required. Unfortunately we cannot prompt the user to enter the code, this will need to be stored app side. This will be a larger change than originally thought.

**Comment by sparkydave1981** [comment]
It would be nice if it can at least display the current state of `alarm_control_panel`, then we can use scripts to arm/disarm.

**Comment by sparkydave1981** [comment]
Something I just tested but doesn't work: I created a template sensor to show the status of the `alarm_control_panel.house` entity however the Companion app won't let me add anything from the `sensor:` domain as  a n Android Auto favourite.

W would need to have `sensor:` allowed in order for the work-around to be feasible (using a sensor to display current status and scripts to arm/disarm)

**Comment by jpelgrom** [comment]
> the Companion app won't let me add anything from the `sensor:` domain as a n Android Auto favourite.

Can you check your app version? This requires the latest beta release to work (>= 2023.8.0, may not yet be available from the Play Store).

**Comment by sparkydave1981** [comment]
> an you check your app version? This requires the latest beta release to work

It seems my phone installed an update overnight and now I can select sensors.  Thanks!

**Comment by dshokouhi** [comment]
> > an you check your app version? This requires the latest beta release to work
> 
> It seems my phone installed an update overnight and now I can select sensors. Thanks!

next beta will include support for alarm control panels without needing to create a sensor :) only alarms without a code are actionable

**Comment by pergolafabio** [comment]
Hi @dshokouhi , i have Android Auto since a week, i exposed the alarm entrity as a favorite, however , i wasnt able to change the state of the alarm when clicking on the entity in my car ?

i dont have a code for my system, i dont need to enter a code in HA, also the attribute "code arm required: false"

any idea?

![image](https://github.com/user-attachments/assets/7931ae96-c5ce-407e-bc0e-c3bfa4a794e0)

**Comment by pergolafabio** [comment]
i dont have a default code set in my entity, i dont need to , to disable from HA itself

**Comment by pergolafabio** [comment]
i also see this in the docs: 

`If a code is not required will allow for `arm_away` & `disarm``

is it because my alarm is "armed_away" instead of "arm_away" ?? arent those 2 the same?

**Comment by Xeovar** [comment]
> > > an you check your app version? This requires the latest beta release to work
> > 
> > 
> > It seems my phone installed an update overnight and now I can select sensors. Thanks!
> 
> next beta will include support for alarm control panels without needing to create a sensor :) only alarms without a code are actionable

Hmm its November now, any luck? I still get read only control panel icon in android auto on no-code alarm :(

**Comment by dshokouhi** [comment]
> > > > an you check your app version? This requires the latest beta release to work
> > > 
> > > 
> > > It seems my phone installed an update overnight and now I can select sensors. Thanks!
> > 
> > next beta will include support for alarm control panels without needing to create a sensor :) only alarms without a code are actionable
> 
> Hmm its November now, any luck? I still get read only control panel icon in android auto on no-code alarm :(

It's been out for quite sometime. This is an old and closed issue please open a new one if you have an issue. The alarm panel needs to support armed_away state in addition to not requiring any code.

**Comment by Xeovar** [comment]
> > > > > an you check your app version? This requires the latest beta release to work
> > > > 
> > > > 
> > > > It seems my phone installed an update overnight and now I can select sensors. Thanks!
> > > 
> > > 
> > > next beta will include support for alarm control panels without needing to create a sensor :) only alarms without a code are actionable
> > 
> > 
> > Hmm its November now, any luck? I still get read only control panel icon in android auto on no-code alarm :(
> 
> It's been out for quite sometime. This is an old and closed issue please open a new one if you have an issue. The alarm panel needs to support armed_away state in addition to not requiring any code.

My bad, sorry, I thought it made it to the release version.

**Comment by dshokouhi** [comment]
> > It's been out for quite sometime. This is an old and closed issue please open a new one if you have an issue. The alarm panel needs to support armed_away state in addition to not requiring any code.
> 
> My bad, sorry, I thought it made it to the release version.

it did, i said

> It's been out for quite sometime.

your alarm panel may not report it supports `armed_away` either way this an old issue, if you believe you have an issue please file a new bug with the issue template filled out completely.
