### ISSUE TITLE
Android Switch Widget can't deal with `off` as hvac value, value gets "converted" to `false`

### ISSUE THREAD

**Issue by harrybin** [home-assistant/android#3715]
**Home Assistant Android app version(s):**
2023.7.5-full
**Android version(s):**
13 (5. July 2023)
**Device model(s):**
Pixel 7 pro
**Home Assistant version:**
2023.5.4
**Last working Home Assistant release (if known):**
--
**Description of problem, include YAML if issue is related to notifications:**
- Create a switch widget like
  - service: climate.set_hvac_mode
  - EnityId: climate.myHeating
  - Hvac Mode: off
- save the widget
- try it, it will no work
- edit the widgest again
- --> you will see the `Hvac Mode: off` chaged to `Hvac Mode: false`

**Additional information:**
I also tried `'off'` and `"off"`, those are not "converted" to `false`, but still the switch does not work.
If I set `heat` as mode it works as expeted, but I'm not able to set `off` which changed to `false`on saving the widget.

**Comment by dshokouhi** [comment]
can you please get us the companion app logs when you save the widget and tap on it? it contains the service data we send so its good to look at what the app is trying.

**Comment by harrybin** [comment]
Hi,
please find the log attached.
It seems like the value is converted by the UI:
![image](https://github.com/home-assistant/android/assets/15869006/3ed0e75a-c440-4cd5-bcb3-b7c4e9a502f5)

[homeassistant_companion_log_6-26-2023_18-30-0.txt](https://github.com/home-assistant/android/files/12175050/homeassistant_companion_log_6-26-2023_18-30-0.txt)

**Comment by jpelgrom** [comment]
This appears to be 'intentional':

https://github.com/home-assistant/android/blob/d9db8a06dfb3d6bdeffd29bd799f08e41a3926f4/app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt#L212

**Comment by harrybin** [comment]
right, seems to some general conversion.
But wrong in this case.
However meanwhile I helped myself by creating a script to trigger the `off` mode instead of the HVAC_mode change action in the widget:
```yaml
domain: climate
entity_id: climate.pool_heizung
type: set_hvac_mode
hvac_mode: "off"
```
