### ISSUE TITLE
Selection of domains to be dispayed in Android Auto 

### ISSUE THREAD

**Issue by woniol** [home-assistant/android#3721]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

After introduction of Favourits in AA, I think the next step woud be to allow user to select the domains to be displayed. I do not thik we need stuff like helpers or scripts to be visible in AA. An option to display Favourites list if no domain is selected for displayvwould be very helpfull as well. This way we could create very simple view  containig only entieties defined in Favourites.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by jpelgrom** [comment]
There is an open PR to update the home screen to immediately show your favorites when the app is open by default, and hide all domains in a submenu. Have you seen it / would it help for your request?

**Comment by dshokouhi** [comment]
With favorites being added we don't need to worry about other categories.
