### ISSUE TITLE
Can't play video content in an iframe from android compagnon app

### ISSUE THREAD

**Issue by nmoreau33** [home-assistant/android#3722]
**Home Assistant Android app version(s):**2023.7.5-full

**Android version(s):**12

**Device model(s):**Fairphone 4

**Home Assistant version:**2023.7.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
I'm using a connected video doorphone from reolink. It supports the onvif profile T protocol, which enables me to have an audio backchannel in the rstp stream.
This rstp stream is entered in go2rtc.
Next, I create a local go.html page in my www folder containing the following:

<html>
    <head>
    </head>
    <body>
          <iframe src="https://sub.mydomain.org:8123/webrtc.html?src=reolink&media=video+audio+microphone" allow="microphone *" frameborder="0" style="overflow:hidden;overflow-x:hidden;overflow-y:hidden;height:100%;width:100%;position:absolute;top:0%;left:0px;right:0px;bottom:0px" height="100%" width="100%"></iframe> 
          <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    </body>
</html>

Then, in lovelace, I call up the page in question via :

type: iframe
url: https://sub.mydomain.org:8123/local/go.html
aspect_ratio: 50%
title: Doorbell

As my domain is published through a nginx reverse proxy, the microphone is switched on by default in my browser.
This works correctly from a PC via different browsers.
This worked in June on my Android cell phone via the companion app, but has since stopped working without the configuration having been changed.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Does this work in chrome for Android on the same device?

**Comment by nmoreau33** [comment]
No, it doesn't.

**Comment by dshokouhi** [comment]
This sounds like a frontend issue, the app won't be able to fix it. Have you looked at open frontend issues?

**Comment by nmoreau33** [comment]
I just checked. It seems that there is no open frontend issues about this issue.

**Comment by dshokouhi** [comment]
As long as you are not using a custom card you should open an issue there

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

Closing as we cannot fix this here
