### ISSUE TITLE
Add English (United Kingdom) to Lokalise

### ISSUE THREAD

**Issue by danbishop** [home-assistant/android#3727]
**Is your feature request related to a problem? Please describe.**
The home assistant frontend supports English (United Kingdom) but the android app does not.

**Describe the solution you'd like**
Please could we add English (United Kingdom) to the Lokalise project so that work can begin? Many thanks!

**Describe alternatives you've considered, if any**
N/A

**Additional context**
N/A

**Comment by dshokouhi** [comment]
looks like we previously had that language added but it was not showing, added it back and also updated your user to have access to it.

@JBassett  did we remove this language for any particular reason? Not sure if it caused issues or anything before :)

**Comment by JBassett** [comment]
I believe it was just because it was identical to the default English or because it was empty.
