### ISSUE TITLE
Android Auto: last-changed values no longer update

### ISSUE THREAD

**Issue by qupada** [home-assistant/android#3751]
**Home Assistant Android app version(s):** 2023.7.8-full

**Android version(s):** 12

**Device model(s):** Sony XQ-AT52 (Xperia 1ii)

**Home Assistant version:** 2023.7.3

**Last working Home Assistant release (if known):** Android app 2023.7.7

**Description of problem, include YAML if issue is related to notifications:**

Tiles on headunit display no longer update last-changed time when interacted with.  Button still read "22h ago" after tapping, even though the action was performed.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![image](https://github.com/home-assistant/android/assets/4470/c4aa5ff4-ad24-487c-81bf-0f60d68a5d56)

**Additional information:**

**Comment by jpelgrom** [comment]
This was fixed in #3736, and will be included in the next beta.

**Comment by qupada** [comment]
Apologies, I actually had intended to check once - as well as getting logs out of the app, which seemed to have eluded capturing the actual event - more but I got the enter key in the wrong field and logged the ticket.
