### ISSUE TITLE
Combine Sensors on Tablets with multiuser Mode 

### ISSUE THREAD

**Issue by Dreamtrailtv** [home-assistant/android#3759]
**Is your feature request related to a problem? Please describe.**

I have a tablet with 3 users and have the problem that when I install the Homeassistant app for each user, it creates the same device 3 times and accordingly also displays the battery status etc. 3 times.

**Describe the solution you'd like**

The problem could be solved by a possibility for the app to recognize if it is a multiuser device and then to check if this device already exists and then to use the sensors that already exist for this device.

**Describe alternatives you've considered, if any**

Another possibility would be, for example, in the settings of the instance to offer the possibility to combine devices with all sensors and to mark them as one device. Then the latest data is always displayed, since only one user can be logged in at a time on a tablet.

**Additional context**
![image](https://github.com/home-assistant/android/assets/51512219/bf4857ab-8b07-4c2d-87dc-0788ad2c8655)

**Comment by dshokouhi** [comment]
This is as designed. If you login as a new user it will create a new device for that user.  Keep 1 user logged in at a time.
