### ISSUE TITLE
Service call widget hanging forever following a temporary network unreachability

### ISSUE THREAD

**Issue by doron1** [home-assistant/android#3761]
**Home Assistant Android app version(s):**
2023.7.5-full
**Android version(s):**
10
**Device model(s):**
Fairphone 3+
**Home Assistant version:**
2023.7.2
**Last working Home Assistant release (if known):**
n/a
**Description of problem, include YAML if issue is related to notifications:**
Configured a service call widget. It calls a service that applies a scene. Normally this works perfectly. At one point there was a brief network outage, just when I pushed the widget button (phone switched from WiFi to LTE or something). The widget failed to connect, showing an animated swirling circle ("waiting"). 
The network connection renewed a moment later; the HA application comes up with no issue; however the widget area keeps swirling, endlessly (hours). Only a phone restart set it back to normal.

I believe there needs to be a timeout of sorts for the completion of a service call, and a failure indication if that's the case, rather than an endless wait.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
The widget should reset the state the next time screen turns off and on. Logs of the issue will be helpful.

**Comment by doron1** [comment]
It didn't. Unfortunately I restarted the phone. Do I still have access to
the logs pre-restart? If so, how?
Thanks!

**Comment by dshokouhi** [comment]
No you won't have access to them, you'll need to reproduce the issue to grab them

**Comment by dshokouhi** [comment]
Also we do have a timeout set for all API calls

**Comment by dshokouhi** [comment]
Closing due to lack of response from author
