### ISSUE TITLE
New functions on wear os

### ISSUE THREAD

**Issue by Filip-HA** [home-assistant/android#3763]
1. I propose to add a new tile which by default will have a logo with the inscription and after clicking it, the image from selected cameras that are added in homeassistant opens and add up and down arrows with the option of moving the camera preview. It would be something cool, especially for people like me who, when going outside, take only the watch with the LTE function

2. Add the ability to expand templates, e.g. automatic refresh every 3 seconds, add the ability to add colorful texts, and add the ability to add a tile with picture elements.

**Comment by dshokouhi** [comment]
Please file a separate request for the requested change to the template tile. One request each please do not combine multiple request into the same one like the picture element request.

Moving the camera is not something all cameras support so that may not happen.

**Comment by jpelgrom** [comment]
Also tile updates are limited by the system to ~once a minute, so the app can't do live refresh/every 3 seconds as requested.

**Comment by dshokouhi** [comment]
Closing as the request has not been split up, please feel free to update this request to be about 1 feature instead of multiple and I can reopen. Feel free to also submit multiple request for each additional feature
