### ISSUE TITLE
App crashes every time I select "Android Auto Favourite" or Quick Setting Tiles

### ISSUE THREAD

**Issue by brentk7** [home-assistant/android#3770]
**Home Assistant Android app version(s):**
2023.8.1-full 
**Android version(s):**
13
**Device model(s):**
Galaxy S23 Ultra (SM-S918B)
**Home Assistant version:**
2023.8.1
**Last working Home Assistant release (if known):**
This feature has never worked for me
**Description of problem, include YAML if issue is related to notifications:**
Every time I try to add an "Adroid Auto Favourite" the app crashes and restarts approx 1 second after I select "Android Auto Favourites" (the list does not populate)

**Companion App Logs:**
[homeassistant_companion_log_7-8-2023_10-30-51.txt](https://github.com/home-assistant/android/files/12286071/homeassistant_companion_log_7-8-2023_10-30-51.txt)
```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
the logs actually dont show the crash here, do you have access to logcat?

Also are you able to use features like quick setting tiles or shortcut to entities or do you also see the same crash?

**Comment by brentk7** [comment]
I've never used logcat - if you can provide a link on how to use it I'm sure I can figure it out (if it works from Windows).
I have just tried selecting "Manage Tiles" and also see a similar crash and restart a second or 2 later

**Comment by dshokouhi** [comment]
The easiest way to get setup with logcat is to install Android Studio. It has a logcat window and once you enable USB debug logging in your phone you can view the logs. From there you can reproduce the issue and find the crash log (icon at the bottom left hand side). 

You can also use an app like Logcat Reader. Both methods require you to hook up the phone to the computer

https://developer.android.com/studio
https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_US&gl=US

Good to know hte app crashes in both of those places so its not unique to this screen. 

I am wondering if maybe there was an error when the server was originally created. Can you tell me if you have configured any additional servers in the app? If not can you try logging out and back in to see if it works?

**Comment by brentk7** [comment]
I only have one server configured. I don't have any option to log out - do you mean Delete Server in the app? Alternatively I could delete the data for the app in Android and set up again. Please let me know which would be better

**Comment by dshokouhi** [comment]
> I don't have any option to log out - do you mean Delete Server in the app?

Not delete server. Go to your user profile in HA using the app and there is a Log Out option there



> Alternatively I could delete the data for the app in Android and set up again. Please let me know which would be better

we dont need to do that yet :) but correct steps to follow are

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by brentk7** [comment]
OK - logged out and back in. Still crashes on both "Android Auto Favourites" and "Manage Tiles" - although both had the "spinning circle" for a bit longer before crashing this time.

**Comment by dshokouhi** [comment]
ok please get us the crash logs using one of the above methods :)

**Comment by brentk7** [comment]
Here is the log - I have tried to filter it for entries with homeassistant
[logcat_08-08-2023_13-37-25.txt](https://github.com/home-assistant/android/files/12287046/logcat_08-08-2023_13-37-25.txt)

**Comment by dshokouhi** [comment]
thnk I found the crash, how many entities would you say you have?

```
[08-08 13:33:12.934 13868:13930 E/AndroidRuntime]
FATAL EXCEPTION: queued-work-looper-data
Process: io.homeassistant.companion.android, PID: 13868
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 1292136 free bytes and 1261KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by dshokouhi** [comment]
If possible please also get us the unfiltered logs from the same time of the crash `13:33:12` there may be additional logging above to help

**Comment by brentk7** [comment]
Your question regarding number of entities has helped me solve my issue - I had 166363 device tracker entities!
I have also been trying to troubleshoot an issue with Node Red and came across [this](https://community.home-assistant.io/t/node-red-cannot-connect-to-home-assistant/438962/11). I removed known_devices.yaml and restarted HA and now I can add an entity to Android Auto Favourites.

Maybe some error handling still needs to be added to limit the number of entities the app tries to return?

**Do you still want me to send any further logs?**

**Comment by jpelgrom** [comment]
There are limits on the number of entities that are displayed (75 maximum, and you type to search), but it still needs to load information about all of them to be able to build that list. It was tested with thousands of entities but not sure if it should handle this amount 😅.

**Comment by dshokouhi** [comment]
> Do you still want me to send any further logs?

No thank you, we know what the issue is now. I do need to admit that amount of device trackers with a location is unexpected lol

**Comment by brentk7** [comment]
Thanks for your help on this
