### ISSUE TITLE
Feature request: Add possibility to change locking PIN on HA Android app

### ISSUE THREAD

**Issue by Grandma-Betty** [home-assistant/android#3791]
**Is your feature request related to a problem? Please describe.**

This feature request is not really based on a problem, but on security concerns about the current implementation of PIN/biometric lock.
Currently it is only possible to use the same PIN as the device's main unlocking PIN, which can not be changed for for only the HA Android app.
Here are two scenarios, where this can be a security risk:

- First scenario: As it is not uncommon to sometimes share a device with other people for whatever reason, which can make it necessary to share also the device's main PIN to unlock the device.
- Second scenario: A device's main unlocking PIN is obviously the most frequent used PIN on the according device, so the more frequent a PIN is being used, the higher the risk for other (unwanted) people to find out that PIN.

For both scenarios, the risk is to make HA accessible for every person that is aware of the device's main PIN.

**Describe the solution you'd like**

To add an aditional layer of security: This is a feature request to make the HA app its locking PIN independent from the device's main locking PIN. So it would be possible to change the HA Andoid app locking PIN independetly from the device's main PIN.

**Describe alternatives you've considered, if any**

Alternatively (or even better: additionally) it would also help and add more flexibility if users optionally could get rid of the HA app locking PIN completely and use biometrical-only options to unlock the HA Android app instead.

**Additional context**

- If you would like to check a free app solution from a vendor that has implemented a PIN lock independent from the device's main PIN lock for their apps: All Android apps from "Synology" are offering that extra layer of security.
- If you would like to check a free app solution from a vendor that implemented biometrical-only lock for their app: The Android "WhatsApp" app is offering that extra feature of security.

**Comment by dshokouhi** [comment]
Duplicate of https://github.com/home-assistant/android/issues/1198
