### ISSUE TITLE
Assist error "Oops, an error has occurred" using Wyoming/faster-whisper

### ISSUE THREAD

**Issue by simowilso** [home-assistant/android#3792]
**Home Assistant Android app version(s):** 2023.7.5-full

**Android version(s):** 13

**Device model(s):** Pixel 6a

**Home Assistant version:** 2023.8.2

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:** 
Updated rhasspy/faster-whisper and rhasspy/piper to latest versions, but now companion app immediately shows "Oops, an error has occurred" before even trying to speak a command

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
can you please post a screenshot, also can you reproduce the issue using chrome for android on the same device?

**Comment by jpelgrom** [comment]
For Assist issues, it is also helpful to check the debug info in Settings > Voice assistants > (your assistant) > overflow/three dots in top right > Debug, to determine if this is an app issue or core issue.

**Comment by dshokouhi** [comment]
can you please also list the app version, just noticed its missing in the template

**Comment by simowilso** [comment]
![image](https://github.com/home-assistant/android/assets/15340247/a46795cf-3cdd-4982-9287-820cd2a852b3)

**Comment by simowilso** [comment]
If I use chrome I don't get the error, but, I have a red warning on the microphone because I don't have https connection

**Comment by jpelgrom** [comment]
Can you check your assistant settings to make sure STT is set and has a voice/language? I remember that at some point my language setting was removed which caused immediate errors with nothing in the debug view.

> If I use chrome I don't get the error, but, I have a red warning on the microphone because I don't have https connection

To confirm: does it work if you use text input in the app?

**Comment by simowilso** [comment]
STT is set (and works) language is set to English.
It does work if I type the command in the app, yes.

**Comment by jpelgrom** [comment]
Hmm not something easy then 🤔

It would be helpful if you can check logs after using Assist, and share relevant information here:
 - the main logs in Settings > System > Logs (which might contain a more technical error message)
 - the app logs in Settings > Companion app > Troubleshooting > Show and share logs (which will tell what the app is trying to do and where the error is coming from)

**Comment by jpelgrom** [comment]
```
08-14 17:35:25.091 19913 19913 E WebSocketRepository: Unable to subscribe to assist_pipeline/run with data {start_stage=stt, end_stage=tts, input={sample_rate=44100}, conversation_id=null, pipeline=01h2wx39sfey4etd7n888xd3vv}
```

suggests that the error happens on the server as that does look correct, is there a more detailed error in the main logs or nothing at all?

**Comment by simowilso** [comment]
[home-assistant_2023-08-14T17-38-58.443Z.zip](https://github.com/home-assistant/android/files/12337960/home-assistant_2023-08-14T17-38-58.443Z.zip)

**Comment by jpelgrom** [comment]
Unfortunately I agree, nothing to see in those logs.

The only thing I can think of at this point is updating the Android app, the latest version which is currently in beta but is expected to release later this week contains some fixes for Assist.

I see you've created a core issue as you've also tried it on another device and couldn't get it to work. Usually that would be the point to close the Android-specific issue. You should add more info about your config and diagnostics, if possible, to get better help.

**Comment by jpelgrom** [comment]
Closing as the mentioned core issue was also closed
