### ISSUE TITLE
Globally stored templates

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/android#3793]
**Is your feature request related to a problem? Please describe.**

This might well be a #frontend FR, not sure:

Under dev - templates, the templates are currently stored local in the browser used. 
It would be far more convenient if they were stored per user account. That way templates could be worked on in e.g. mobile phones when traveling or other workstations. 

**Describe the solution you'd like**

Templates stored per user rather than locally per browser

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
This is a request for the HA frontend the app should not handle this but I agree.

**Comment by AleXSR700** [comment]
https://github.com/home-assistant/frontend/discussions/17580

:)
