### ISSUE TITLE
Android Automotive Sensors

### ISSUE THREAD

**Issue by dgomes** [home-assistant/android#3796]
**Is your feature request related to a problem? Please describe.**

Android Automotive provides many sensor values that are beneficial to users

**Describe the solution you'd like**

Basically a mashup between HA Companion and https://github.com/Ixam97/CarStatsViewer

**Describe alternatives you've considered, if any**

Use https://github.com/Ixam97/CarStatsViewer and have web hooks send information back to HA server

**Additional context**

**Comment by Emacee** [comment]
This would be awesome!

**Comment by ivancea** [comment]
This has been created as the starting point to integrate Automotive sensors: https://github.com/home-assistant/android/pull/4122

Only existing Auto car sensors are added there, and only in the "full" version (Non-google play) of Hass AAOS, but it's a starting point. After that, I was planning in adding some extra useful sensors, but I guess (Or wish) it will be easier to contribute new sensors after it

**Comment by dgomes** [comment]
Any feedback from google on the chances of making this available for the google play version ?

**Comment by dgomes** [comment]
there is currently https://play.google.com/store/apps/details?id=de.ixam97.carStatsViewer.carApp&hl=en published on the Play Store, sure we can't leverage that to get a build with support for sensors published in the Play Store ?

**Comment by dshokouhi** [comment]
All existing android auto/automotive sensors are now available for all users. Play store users will have access starting in the beta from this Saturdays beta push. I am going to close this issue now. If any additional sensors are wanted please file an additional request so it can be considered.
