### ISSUE TITLE
SSL Handshake error behind reverse proxy with different external IP than instance

### ISSUE THREAD

**Issue by JackPala** [home-assistant/android#3800]
**Home Assistant Android app version(s):**

**Android version(s):**13

**Device model(s):**Note 20 Ultra

**Home Assistant version:**Latest

**Last working Home Assistant release (if known):**Latest

**Description of problem, include YAML if issue is related to notifications:**
Home Assistant is running inside a VM in a hypervisor with a CGNAT public IP. For this reason, a Zerotier tunnel has been established between an EC2 instance in which the EC2 instance running caddy serves a reverse proxy to home assistant to allow public facing internet access with SSL. It works flawlessly on iOS App, Android Web Browser, Desktop Browser, however it throws an SSL handshake error on Android and crashes back to home on log attempts. This issue has been replicated on multiple Android devices. The cipher is compatible and the cert chain is good, as I have another instance with the same configuration, but running with a public IP in the same subnet instead of a Zerotier tunnel.

**Companion App Logs:**

```

```

**Comment by dshokouhi** [comment]
SSL handshake errors are not ones the app will be able to solve

**Comment by dshokouhi** [comment]
if you can post the actual logcat error we can help direct to a possible solution

**Comment by JackPala** [comment]
> if you can post the actual logcat error we can help direct to a possible solution

Oddly enough the iOS app does not have SSL errors, nor does the Webpage - Cipher is android compatible, but logging causes app to crash to home on two different devices (Note 20 Ultra stock unmodified ROM, and Note 10.1 with LineageOS)

**Comment by dshokouhi** [comment]
> > if you can post the actual logcat error we can help direct to a possible solution
> 
> Oddly enough the iOS app does not have SSL errors, nor does the Webpage - Cipher is android compatible, but logging causes app to crash to home on two different devices (Note 20 Ultra stock unmodified ROM, and Note 10.1 with LineageOS)

The Android app will behave differently than iOS and even the browser here. We still need the error log in order to proceed.

**Comment by dshokouhi** [comment]
Closing as we have not received logs yet
