### ISSUE TITLE
Phone state sensor stopped behaving correctly with new update

### ISSUE THREAD

**Issue by ea5522** [home-assistant/android#3801]
**Home Assistant Android app version(s):** latest

**Android version(s):**  13, latest

**Device model(s):** SM-G998U (galaxy s21 ultra 5g verizon)

**Home Assistant version:** latest

**Last working Home Assistant release (if known):** latest

**Description of problem, include YAML if issue is related to notifications:**
Phone state sensor changes status only on SIM calls. Before the update, it used to change status when calls were placed via different apps, such as whatsapp. 

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Nothing changed for this sensor in how it gets the state. Also you can use the audio mode sensor to do the same thing. Those apps have the state of in communication.

**Comment by jpelgrom** [comment]
> Nothing changed for this sensor in how it gets the state. Also you can use the audio mode sensor to do the same thing. Those apps have the state of in communication.

That's not correct, the API that is used was changed. It was overlooked that it now only gets the state for the default subscription instead of any calls, which may be for another subscription (multi SIM) or not linked to a subscription at all (VOIP like WhatsApp).

**Comment by dshokouhi** [comment]
My bad forgot we changed the depreciation there

**Comment by ea5522** [comment]
So this will be fixed in new update? Awesome, thank you gentlemen. that was quick.

**Comment by jpelgrom** [comment]
>  So this will be fixed in new update?

Yes, in version 2023.8.3 and newer.
