### ISSUE TITLE
Next alarm sensor with samsung sleep mode

### ISSUE THREAD

**Issue by eemil-h** [home-assistant/android#3806]
**Android version(s):**
13, One UI 5.1
**Device model(s):**
S21 FE, probably all Samsung's
**Home Assistant version:**
OS 10.4
**Last working Home Assistant release (if known):**
None
**Description of problem, include YAML if issue is related to notifications:**
With Sleep mode schedule set in modes and routines samsung clock app will show alarm with also sleep mode start time and companion app reports also the start time as an alarm for next alarm sensor.

**Companion App Logs:**
08-20 21:46:00.104 11924 11977 D NextAlarm: Next alarm is scheduled by com.sec.android.app.clockpackage with trigger time 1692558000000
08-20 21:46:00.121 11924 11961 D NextAlarm: Next alarm is scheduled by com.sec.android.app.clockpackage with trigger time 1692558000000
```

```

**Screenshot or video of problem:**
![Screenshot_20230820_211542_Home Assistant](https://github.com/home-assistant/android/assets/127330297/12185e12-c744-41b1-b2b7-ae52cef6559c)
![Screenshot_20230820_211503_Clock](https://github.com/home-assistant/android/assets/127330297/3244318f-3b0d-4f5b-b5c9-794c751ad8b9)

**Additional information:**

**Comment by dshokouhi** [comment]
This is how the feature works, if the app uses it to set different alarms the HA app will still pick it up. Samsung apps are known to report a lot of different times.
