### ISSUE TITLE
"General" notification channel importance

### ISSUE THREAD

**Issue by jackb007** [home-assistant/android#3807]
It seems a "General" notification channel is created by the HA Companion App when the application is installed. This channel appears to be created with an original importance of either "default" or "low".  This means a notification will make a sound ONLY if the phone screen is on. This setting can be modified by going to "Settings -> Notifications -> App Notifications -> Home Assistant -> Notification Categories -> General" and then enabling "Show as pop-up". 

As far as I can tell, alerts always use the "General" channel regardless of what channel is requested. This means there is a risk a user will create an important alert and, assuming the alert notifications will always produce a sound, as most SMS and email applications do, will miss an important notification due to his screen being off at the time the notification is received. In my opinion the "General" channel should be created with an importance of "high" by default.

I'm using HA 2023,8.2, Android 13, and the latest Android HA Companion App.

**Comment by jpelgrom** [comment]
Can you give an example of notifications not respecting other channels? Please don't remove the template - logs, last known version working, device, etc, is useful information to have.

The general channel matches the default importance of many other apps, so this is unlikely to change. It should make sound even if the screen is off, if it doesn't that sounds like a device specific change as the normal importance is supposed to make sound. If you want it to pop up on screen you can always change it.

**Comment by jackb007** [comment]
I've just turned all the options in the "General" channel on, namely:
- Allow notifications
- Show as pop-up
- Sound (Disco Toms)
- Vibrate
- Lock screen -> show content
- App icon badges
The alert will produce sounds for a few seconds -- perhaps even a minute -- after the screen has gone black. After that, no more sounds. The alert notifications will keep accumulating as messages, but I won't get a sound until I unlock the screen.

**Comment by jackb007** [comment]
The code below will work perfectly fine inside an automation, even when the screen is black:

#######################################

action:
  - service: notify.mobile_app_galaxy_xcover
    data:
      title: ALARM
      message: The house alarm has been triggered
      data:
        ttl: 0
        enabled: true
        priority: high
        channel: "General"

#######################################

but the same notification sent through an alert will only produce sounds while the phone screen is on. After many attempts, I've managed to make the phone produce a sound by triggering an alert while the screen was black on one occasion. I haven't got a clue why. So it seems the "General" channel is working fine when not used under alerts, but alerts will use the "General" channel by default (and only option).

**Comment by jpelgrom** [comment]
What do you mean when you say alerts? The app only supports notifications. If you want a special "alert" behavior, you'd use a different channel for it.

**Comment by jackb007** [comment]
There's an alert integration that will send you notifications at fixed intervals until the condition that triggered the alert is cleared:
https://www.home-assistant.io/integrations/alert/

**Comment by jackb007** [comment]
So I misdiagnosed the problem originally. The problem wasn't the "General" channel not being set to the correct importance. The problem is the "Alert" integration not being able to use the "General" channel correctly for some reason. Sounds will only be produced while the screen is on.

**Comment by jackb007** [comment]
So I misdiagnosed the problem originally. The problem wasn't the "General" channel not being set to the correct importance. The problem is the "Alert" integration not being able to use the "General" channel correctly for some reason. Sounds will only be produced while the screen is on.
