### ISSUE TITLE
Android Automotive - App Settings cannot be accessed, CarInfo sensors unusable

### ISSUE THREAD

**Issue by thehedgefrog** [home-assistant/android#3810]
**Home Assistant Android app version(s):**
2023.8.2

**Android version(s):**
Automotive

**Device model(s):**
Polestar 2

**Home Assistant version:**
2023.8.3

**Description of problem, include YAML if issue is related to notifications:**
The CarInfo sensors that were implemented cannot be turned on, since Native Mode has been removed (I understand this was at Google's request).  Consequently, I cannot turn on the sensors to report battery/charging status.

Perhaps these could be added at onboarding, like Location access, or within a specific tile.  For now, even though those sensors are implemented, they are unusable.

**Comment by dshokouhi** [comment]
Unfortunately we need to wait for Google to approve us to add back the native mode. Until then play store users will need to wait to use these features. Also these sensors are not currently available for automotive, the docs mention this as well.

**Comment by Borales** [comment]
The only "hack" to get to the "native mode" I could find was sending a notification to the car and opening it from the notification menu. This gets me straight to the home page of HA. 

<img width="830" alt="Screenshot 2024-02-03 at 22 03 05" src="https://github.com/home-assistant/android/assets/1118933/39359f4e-54f0-428e-9c00-568b14799925">

**Comment by kst84** [comment]
@Borales thanks, that 'hack' makes it finally usable, at least when you have a ton of entities, you can add some of them to favourites.

**Comment by mariwing** [comment]
Is it possible for you to share the yaml for the notification? I tried this but when clicking the notification it opens the app with all the categories (same screen as if I open the app normally) and not the hidden setup screen.

**Comment by dshokouhi** [comment]
> Is it possible for you to share the yaml for the notification? I tried this but when clicking the notification it opens the app with all the categories (same screen as if I open the app normally) and not the hidden setup screen.

make sure car is in park

**Comment by mariwing** [comment]
Never mind - figured it out! Omitted the entire data section and then it worked! Thank you 🙏🏻
