### ISSUE TITLE
Added fields on Service Button widget are lost if widget is re-edited

### ISSUE THREAD

**Issue by glynaunac** [home-assistant/android#3812]
**Home Assistant Android app version(s):** 2023.8.2-full

**Android version(s):** 11

**Device model(s):** Moto g9 play

**Home Assistant version:** 2023.8.3

**Last working Home Assistant release (if known):**Latest

Description of problem, include YAML if issue is related to notifications:

If you add fields to a service button widget and then go back into the setup for the widget after saving, the added fields are not displayed.

If you then exit the widget settings page without saving, the fields and values are retained and any actions work as expected.

If, however, you click 'Update Widget', even without making any changes, the fields and values are removed.

Companion App Logs:

**Comment by dshokouhi** [comment]
Can you please post your app version?

I thought this was fixed in #3514

**Comment by glynaunac** [comment]
Sorry, the app version is 2023.8.2-full.

**Comment by jpelgrom** [comment]
> I thought this was fixed in #3514

Looks like this issue relates to custom/added fields, normal fields exposed by the service work correctly, so I think this has been broken for quite some time.

**Comment by glynaunac** [comment]
Yes, I am using added fields to pass parameters to a script.

**Comment by jpelgrom** [comment]
Fix submitted.

@dshokouhi I spoke too soon: it does look like this wasn't handled properly in the mentioned PR, the widget code was simplified with multiserver and no longer accounted for custom fields.
