### ISSUE TITLE
Shortcuts to different servers

### ISSUE THREAD

**Issue by Inglan** [home-assistant/android#3823]
**Is your feature request related to a problem? Please describe.**

I have multiple home assistant servers, and need to switch between them a lot. I have two always needing fingerprint and one that needs fingerprint when not on home wifi. When I open the app, it opens the last server I had open. This is annoying because it will ask for fingerprint, and this can be inconvenient at times, when I am on home wifi.
**Describe the solution you'd like**

I would like the ability to add shortcuts to the home screen to different servers.
**Describe alternatives you've considered, if any**

Alternatively, adding a way to select a default server, or asking for a server when the app starts would also solve this problem.
**Additional context**

Example using tasker shortcut widget (Android beta broke app shortcuts)
![Screenshot_20230827-090848](https://github.com/home-assistant/android/assets/96573515/ae7f9869-df82-4c80-8840-5a1e98709dbf)

**Comment by dshokouhi** [comment]
This is already possible using the existing shortcut feature

https://companion.home-assistant.io/docs/integrations/android-shortcuts

![Screenshot_20230826-163055.png](https://github.com/home-assistant/android/assets/1634145/b9dd5f57-d4c3-48a3-adc4-ba4a340392a9)
