### ISSUE TITLE
Thread credentials not changing

### ISSUE THREAD

**Issue by Zoneykid** [home-assistant/android#3832]
**Home Assistant Android app version(s):**
2023.8.4 
2023.8.5-beta.0.5+a9b7dfd-full
**Android version(s):**
13 (OneUI 5.1)
**Device model(s):**
Galaxy S23 Ultra
Galaxy Tab S9
**Home Assistant version:**
2023.8.4
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Unable to sync thread credentials, every time I try it just says Home Assistant and device prefer different networks (device prefers: MatterServer)

**Companion App Logs:**

```
08-29 19:14:25.612 19212 19212 D ThreadManagerImpl: Thread: device doesn't prefer core preferred dataset
08-29 19:14:25.617 19212 19212 D ThreadManagerImpl: Thread: device doesn't prefer dataset from app
```

**Screenshot or video of problem:**

**Additional information:**
I currently have two thread networks, the home-assistant network which has unique credentials, and the MatterServer network which somehow is still holding over from a previous beta of the OTBR addon and the nanoleaf app always prefers for some reason.

For a while I was using nanoleaf shapes as an OTBR to get around this until HA added support to directly commission bulbs using homekit over thread, at which point I just disabled thread routing on the shapes.

Then I got some matter nanoleaf bulbs and they refused to ever pair to home assistant, so I re-enabled the border routing on the shapes (which now can't be disabled in newer firmwares) and use the insecure MatterServer network as the nanoleaf app never lets me select another thread network, even though it can see the home-assistant network in the thread network viewer.

After that I got a nest hub as well, which is also acting as a border router for the MatterServer network, which I was hoping it would at least let me pick which thread network I wanted, but it just defaulted to that.

I decided to go down this rabbit hole again and found that there's a troubleshooting option to sync thread credentials, which based on another pull request should also remove any old or obsolete credentials. However, every time I try to use it on my phone or tablet it just says the same thing, server and device prefer different networks. I even tried to clear play services data on my tablet and no luck, still the same issue.

**Comment by jpelgrom** [comment]
Thanks for the report. There are changes in the upcoming beta to resolve syncing issues, if you're able to please test with version 2023.8.5-full or newer once it releases this weekend.

Additionally, the app is not able to change the preferred network, only the system can. Your logs suggest another app added the preferred network: that app should remove it. If you're unable to, clearing all data for Google Play Services should also resolve it but now that this will also clear things like your saved Google Pay cards.

**Comment by jpelgrom** [comment]
> Is there a way to figure out which app set the credentials?

No, I don't believe so. It is not exposed to Home Assistant and unless Google added UI I haven't found yet, there is no way for you to find it either.

**Comment by jpelgrom** [comment]
Closing bacause this is out of scope for the companion app, Google needs to provide a way for users to manage credentials or allow changing the preferred credential (both of which seem unlikely at this point).
