### ISSUE TITLE
Android Automotive favorites - no way to set them up?

### ISSUE THREAD

**Issue by mariwing** [home-assistant/android#3833]
I love that in version 2023.8 it is possible to setup favorites for Android Auto - thanks! According to the documentation (https://companion.home-assistant.io/docs/android-auto/) it should be accessible through settings in the app. I am using Android Auto**motive** and no such settings exists in that app. Is there any way to setup favorites directly on Android Automotive? If not - I think it should be.

**Comment by mariwing** [comment]
Thank you for a quick response. Will it be possible to set this up if I get hold of a "normal" Android phone and set it up there? Will those settings carry over to Automotive or is this a per device thing?

**Comment by dshokouhi** [comment]
Automotive is a separate app. You can still run Android auto but requires the app installed on an Android phone
