### ISSUE TITLE
Security camera snapshot notification does not update image

### ISSUE THREAD

**Issue by SeuRobo** [home-assistant/android#3861]
*Home Assistant Android app version(s):  2023.8.2-full

*Android version(s): 12

*Device model(s): moto g200 5g

*Home Assistant version: 2023.09.2

*Last working Home Assistant release (if known):*

*Description of problem, include YAML if issue is related to notifications:
Hello everyone, first of all I would like to thank all the developers, this project is incredible!

I created an automation so I could take a photo from the security camera and send a notification with the image to my Andoird and my wife's iPhone when someone closed the video intercom. However, on Android and IOS the image is not always updated, sometimes it updates and sometimes it ends up with an old image.
I always look at the image saved by the snapshot in the /config/www/images/ folder and it is always correct so I believe it is a bug in the Android and iOS app.

*Companion App Logs:*

```

```

*Screenshot or video of problem:*

*Additional information:*
alias: "Notificação ao tocar campainha "
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.sensores_esp_campainha_do_portao
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0
condition: []
action:
  - service: camera.snapshot
    data:
      filename: /config/www/images/ruaFundos.jpg
    target:
      entity_id: camera.rua_fundos
  - service: camera.snapshot
    data:
      filename: /config/www/images/ruaEntrada.jpg
    target:
      entity_id: camera.rua_entrada
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: notify.mobile_app_moto_g200_5g
    data:
      message: TOCARAM O INTERFONE
      title: "Camera Rua fundos "
      data:
        image: /local/images/ruaFundos.jpg
        clickAction: /lovelace/monitoramento
  - service: notify.mobile_app_moto_g200_5g
    data:
      message: TOCARAM O INTERFONE
      title: "Camera Rua Frente "
      data:
        image: /local/images/ruaEntrada.jpg
        clickAction: /lovelace/monitoramento
  - service: notify.mobile_app_iphone_de_lorena_f_correa_rosa
    data:
      message: TOCARAM O INTERFONE
      title: "Camera Rua fundos  "
      data:
        image: /local/images/ruaFundos.jpg
        clickAction: /lovelace/monitoramento
  - service: notify.mobile_app_iphone_de_lorena_f_correa_rosa
    data:
      message: TOCARAM O INTERFONE
      title: "Camera Rua Frente  "
      data:
        image: /local/images/ruaEntrada.jpg
        clickAction: /lovelace/monitoramento
mode: single

**Comment by dshokouhi** [comment]
This is actually as designed. HA uses very heavy caching techniques and you need to use a unique file name in order for a new image to load.
