### ISSUE TITLE
Widget template using markdown

### ISSUE THREAD

**Issue by Falci** [home-assistant/android#3864]
**Is your feature request related to a problem? Please describe.**
More like an improvement, quality of life.

**Describe the solution you'd like**
I'd like to create a widget using templates that supports markdown

**Describe alternatives you've considered, if any**

**Additional context**
The current template widget doesn't support even break lines, which makes it hard to use with some more complex templates.

**Comment by jpelgrom** [comment]
Markdown renders to HTML, which [is already supported](https://companion.home-assistant.io/docs/integrations/android-widgets#template). For example for a line break you can use `<br>`.

**Comment by Falci** [comment]
> Markdown renders to HTML, which [is already supported](https://companion.home-assistant.io/docs/integrations/android-widgets#template) (most text related tags, more is difficult due to Android limitations). For example for a line break you can use `<br>`.

That's a progress.
Any chance to support alignment (instead of just center) and maybe a table?

**Comment by jpelgrom** [comment]
Text alignment is also already supported but you need to use `start`, `center` and `end` :)

![Screenshot of template widget with text 'Start' aligned to the left and 'End' aligned to the right](https://github.com/home-assistant/android/assets/8148535/941c5fb2-2938-4d5e-93d2-97cba43d852b)

```
<p style="text-align: start">Start</p>
<p style="text-align: end">End</p>
```

Table support doesn't seem viable with the current widget based on a quick search as it isn't text and other views that might support it (like WebView for proper HTML rendering) are not allowed in widgets.

**Comment by Falci** [comment]
Thanks for that.
