### ISSUE TITLE
Wear OS Sleep Tracking

### ISSUE THREAD

**Issue by Krispkiwi** [home-assistant/android#3866]
Hey there,

I'm in the market for a smart watch and have been looking at the Galaxy Watch 6 however after talking to people in the Home Assistant discord I'm being told sleep tracking isn't a feature with the Home Assistant app so they haven't been able to pull the data into Home Assistant which with my fitbit I'm able to.  I've had a look through previous feature requests and it seems like you got something similar at https://github.com/home-assistant/android/pull/2981 however I just want to clarify before dropping the money on it.

**Is your feature request related to a problem? Please describe.**
 Not related to a problem per say, just something good to track and inform me of as part of the Home Assistant morning routine.

**Describe the solution you'd like**
The wear os app to be able to track when I fall asleep and for how long.

**Describe alternatives you've considered, if any**
The fitbit watch currently supports this which is what I'm using however It's old and I'd rather upgrade.

**Additional context**
No additional information.

**Comment by dshokouhi** [comment]
Already supported you want to enable the activity state sensor.

https://companion.home-assistant.io/docs/wear-os/sensors#health-services

**Comment by Krispkiwi** [comment]
Thanks :)
