### ISSUE TITLE
On body sensor constantly reports as "on" on TicWatch Pro 5

### ISSUE THREAD

**Issue by blakadder** [home-assistant/android#3880]
**Home Assistant Android app version(s):** 
Android - 2023.9.2-full
Wear OS - 2023.9.2-11226

**Android version(s):** Android 12, Wear OS 3.5

**Device model(s):** Pixel6, TicWatch Pro 5

**Home Assistant version:** 2023.9.2

**Description of problem, include YAML if issue is related to notifications:**

On body sensor reports as on all the time regardless of actual state.

**Companion App Logs:**

[logcat.txt](https://github.com/home-assistant/android/files/12674513/logcat.txt)

additional lines when taking off watch
```
09-20 16:52:01.594  2416  2416 D WCS     : [LlobDetector]onSensorChanged: [0.0]
09-20 16:52:01.594   957   957 D DeviceIdleController: onSensorChanged: [0.0]
09-20 16:52:01.594  2416  2416 I chatty  : uid=10020(com.google.android.wearable.app) identical 2 lines
09-20 16:52:01.594  2416  2416 D WCS     : [LlobDetector]onSensorChanged: [0.0]
09-20 16:52:01.594  2416  2416 D WCS     : [DynamicRingerWriter]onUpdateOnBody: false
09-20 16:52:01.595  2416  2416 I WCS     : [DynamicRingerWriter]Writing disableDynamicRinger status = 'true', DR feature enabled[true], OnBody[false], PluggedIn[false], PowerSaveMode[false]
09-20 16:52:01.595  2416  2416 D WCS     : [ListenableDataApiWriter]Writing data items with uri=wear:/dynamic_ringer/status
09-20 16:52:01.595 12022 12022 D OnBodySensor: onbody state: false and 0.0
09-20 16:52:01.595  2416  2416 D WCS     : [OnBodyDetectionLogger]offBodyStateChange: false
09-20 16:52:01.595  2416  2416 D WCS     : [NotifCollectorService]requestDisableEffects: 4
09-20 16:52:01.597  2416  2416 I WCS     : [KeyGOffBodyController]OffBodyEventsHandler: Received OffBody callback, onBody = false, isOobeComplete = true
09-20 16:52:01.597   957   957 I DeviceIdleController: updateQuickDozeFlagLocked: enabled=true QuickDozeBlocked =false
09-20 16:52:01.597   957   957 D DeviceIdleController: becomeInactiveIfAppropriateLocked(): isScreenBlockingInactive=false (mScreenOn=false, 
```
```
09-20 16:52:01.632   503   503 I sensors-hal: activate:185, mobvoi_rri/2052 en=0 completed
09-20 16:52:01.634  2416  2416 I WCS     : [KeyGOffBodyController]OffBodyEventsHandler: Detected off-body, shouldLockImmediately = true
09-20 16:52:01.634 12022 12022 D SensorReceiver: Received intent: io.homeassistant.companion.android.UPDATE_SENSORS
09-20 16:52:01.635  1742  1868 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
09-20 16:52:01.636 12022 12022 D LastUpdate: Last update is io.homeassistant.companion.android.UPDATE_SENSORS
```

**Comment by jpelgrom** [comment]
The log file you included contains a line suggesting that the watch is on the body.

The "when taking off the watch" logs show a line suggesting that the watch is off the body: `OnBodySensor: onbody state: false and 0.0`. Is there anything in the logs after your last line from the excerpt (last update is ...)? So far it appears to work, but any issues sending the update would come after that one :)

**Comment by blakadder** [comment]
Logcat file was taken while the watch was charging aka not on body. In home assistant state of the sensor is always on so while the log is suggesting something that is not reflected in the sensor state

**Comment by jpelgrom** [comment]
The log statement I mentioned for off body is coming from the app, which is why is was asking for more logs. It looks like the update never reaches your server and I'm interested to know why.

**Comment by blakadder** [comment]
[logcatmore.txt](https://github.com/home-assistant/android/files/12677362/logcatmore.txt)

**Comment by blakadder** [comment]
And weirdly, today, after two days its working fine and responds in seconds
![image](https://github.com/home-assistant/android/assets/5904370/913f743f-29e9-4c9e-bb00-58e1650a5ac4)

**Comment by jpelgrom** [comment]
Also not seeing any erros in the logs or other indication that it isn't working. Going to close the issue as it now updates immediately again, feel free to respond if it stops again.
