### ISSUE TITLE
Wear OS: Shortcut tiles not working when not connecting to the HASS local network 

### ISSUE THREAD

**Issue by ciclapt** [home-assistant/android#3889]
**Home Assistant Android app version(s):**
2023.9.2

**Android version(s):**
13
Wear OS 4

**Device model(s):**
Samsung S20 Ultra
Samsung Galaxy Watch 4

**Home Assistant version:**
OS 10.5

**Last working Home Assistant release (if known):**
Don't know

**Description of problem, include YAML if issue is related to notifications:**
Shortcut tiles activation of any shortcut on the watch work while connected to the wifi of the local network and do not work while not connected to the wifi.
If the watch is connected to the wifi and the phone is disconnected from the wifi, they work. If the watch is disconnected from the wifi and the phone is connected to the wifi, it works. If they are both disconnected from the wifi, it doesn't work, with internet connectivity from cellular network. Access to HASS works normally from the phone with and without local WIFI connectivity.

**Comment by dshokouhi** [comment]
unfortunately the attached logs are not valid,, they are from the phone and will not contain the failure occurring on the watch. This also does not sound like an issue teh app can solve. Wear OS does its own proxying that the apps do not handle and as such may cause issues. In some cases we have seen enabling NAT loopback on the router to fix the issue.

**Comment by ciclapt** [comment]
> unfortunately the attached logs are not valid,, they are from the phone and will not contain the failure occurring on the watch. This also does not sound like an issue teh app can solve. Wear OS does its own proxying that the apps do not handle and as such may cause issues. In some cases we have seen enabling NAT loopback on the router to fix the issue.
> 
> https://developer.android.com/training/wearables/data/network-access#network-access

Thanks for the reply. I don't think the issue is because of NAT loopback. It works perfectly with the phone inside and out. Any way i can get the logs only from the watch app? Thanks

**Comment by ciclapt** [comment]
If i open the app in the watch, it works correctly with or without wifi. I can activate whatever switches i have available with only the bluetooth connection. The bug only happens in the Shortcut tiles.

**Comment by dshokouhi** [comment]
> Any way i can get the logs only from the watch app?

easiest way is using Android Studio and connecting the watch to teh PC and looking at Logcat there.

**Comment by dshokouhi** [comment]
Can you do me a favor and check that the companion app has background access in the samsung companion app on your phone?  That needs to be enabled in order for the app to work in the background

**Comment by ciclapt** [comment]
> Can you do me a favor and check that the companion app has background access in the samsung companion app on your phone?  That needs to be enabled in order for the app to work in the background

Yes. It has full unrestricted access.

**Comment by ciclapt** [comment]
> > Any way i can get the logs only from the watch app?
> 
> easiest way is using Android Studio and connecting the watch to teh PC and looking at Logcat there. 

I will try to do that.

**Comment by ciclapt** [comment]
[logcat.txt](https://github.com/home-assistant/android/files/12709990/logcat.txt)
Sending logcat from the watch.

**Comment by dshokouhi** [comment]
The only error I see is a failed to connect message, which is not something the app can solve. Although it looks unrelated for sensor status I would imagine the same error occurs for the shortcut tiles. I assume your sensors also do not update then too right?

```
2023-09-25 01:00:46.640 22506-23719 SensorReceiver          io.homeassistant.companion.android   E  Error while getting core config to sync sensor status
                                                                                                    io.homeassistant.companion.android.common.data.integration.IntegrationException: java.net.ConnectException: Failed to connect to hass.example.com/XX.XXX.XXX.XXX:8123
```

**Comment by ciclapt** [comment]
That's right. But only on the shortcuts tiles. If i open the app, everything works fine.

**Comment by dshokouhi** [comment]
So the actual error we should expect to see which I imagine has the same error has above will be from the following line.

https://github.com/home-assistant/android/blob/2c20baf0f54897c720099b34e57cf78eaa70fedb/wear/src/main/java/io/homeassistant/companion/android/tiles/TileActionReceiver.kt#L40

**Comment by ciclapt** [comment]
I will try to catch the full log. The problem is the debug is through wifi and the problem arises when on bluetooth proxying from the phone disconnected from the wifi. Android studio is not getting logs from when it is not connected. Will investigate further.

**Comment by dshokouhi** [comment]
There should be a way to request debug logs from possibly the Samsung companion app watch. Best to reproduce the issue a couple times then make the request for those logs. You should get a dump of things in a zip, we only need to see the logcat entries so you should be able to search by the URL to quickly find them.

**Comment by ciclapt** [comment]
[logcatfull.txt](https://github.com/home-assistant/android/files/12710246/logcatfull.txt)
I think i got the logcat. Another thing i found is if i try to use the shortcut tile and right after i open the app, it executes the command.
Thanks

**Comment by dshokouhi** [comment]
Yup looks to be the same connection error that the app will not be able to solve.  Your symptoms still describe battery optimization as you say it works when the app is just opened.  Are you certain that you granted the app background access from inside the Samsung Companion app from your phone? Its a different process than the phone app and this setting does confuse some users so good to double check it and anything else Samsung may have added with a different name.

```
2023-09-25 02:13:36.553 29840-29840 TileActionReceiver      io.homeassistant.companion.android   E  Cannot call tile service
                                                                                                    io.homeassistant.companion.android.common.data.integration.IntegrationException: java.net.ConnectException: Failed to connect to hass.example.com/XX.XXX.XXX.XXX:8123
```

**Comment by ciclapt** [comment]
Yes I'm sure. That was my first guess also. ![Screenshot_20230926_152630_Galaxy Watch4 Manager.jpg](https://github.com/home-assistant/android/assets/106331254/60e0f6e2-e04d-402b-a215-c8d853815bd1)

Am i the only one with this issue? Samsung recently upgraded from wear os 3.5 to 4. Maybe something changed...

**Comment by dshokouhi** [comment]
So far yes you seem to be only the user with this issue. We have another member who has a Samsung watch on Wear OS 4 and has not noticed communication stopping in the background. Sensors still update but your logs indicate they are not updating while this issue occurs.

I do see the following logs.

```
2023-09-25 01:05:42.112   563-1351  ActivityManager         system_server                        W  Background started FGS: Disallowed [callingPackage: io.homeassistant.companion.android; callingUid: 10150; uidState: TRNB; intent: Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }; code:DENIED; tempAllowListReason:<null>; targetSdkVersion:32; callerTargetSdkVersion:32; startForegroundCount:0; bindFromPackage:null]
2023-09-25 01:05:42.112   563-1351  ActivityManager         system_server                        W  startForegroundService() not allowed due to mAllowStartForeground false: service io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService
2023-09-25 01:05:42.612   563-1351  ActivityManager         system_server                        W  Background start not allowed: service Intent { act=ACTION_STOP_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService } to io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService from pid=22506 uid=10150 pkg=io.homeassistant.companion.android startFg?=false
2023-09-25 01:21:00.257   563-718   ActivityManager         system_server                        W  Background started FGS: Disallowed [callingPackage: io.homeassistant.companion.android; callingUid: 10150; uidState: TRNB; intent: Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }; code:DENIED; tempAllowListReason:<null>; targetSdkVersion:32; callerTargetSdkVersion:32; startForegroundCount:0; bindFromPackage:null]
2023-09-25 01:21:00.258   563-718   ActivityManager         system_server                        W  startForegroundService() not allowed due to mAllowStartForeground false: service io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService
2023-09-25 01:21:28.786   563-2290  ActivityManager         system_server                        W  Background start not allowed: service Intent { act=ACTION_STOP_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService } to io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService from pid=22506 uid=10150 pkg=io.homeassistant.companion.android startFg?=false
```

Maybe Samsung added some more settings to check in the Watch itself to disable?

**Comment by ciclapt** [comment]
I was investigating. Tried to reinstall the app both in the phone and in the watch. The home assistant app crashes more with wear os 4. I still think it's a bug in the app. If the phone is connected through wifi and the watch with Bluetooth, the shortcuts work correctly.  So it doesn't make sense being about battery optimization. Another thing i noticed is the app is not requesting permission for background running when installed. It should. I don't know the code but if the commands work when the app is open, they should work from the tile. Maybe some SO stuff changed...

**Comment by dshokouhi** [comment]
> I was investigating. Tried to reinstall the app both in the phone and in the watch. The home assistant app crashes more with wear os 4. I still think it's a bug in the app

yes your logs actually showed you were impacted by this [known issue](https://github.com/home-assistant/android/issues/3325) which only occurs when the app is open and does not impact tiles



> . If the phone is connected through wifi and the watch with Bluetooth, the shortcuts work correctly. So it doesn't make sense being about battery optimization.

We get 1 URL and use it in the same way, every time even on the phone. The failed to connect error message does not make sense but if thats the error we get its all we have to go by. Give that you say it only happens when the app is not used for some time those symptoms directly describe battery optimization. The call simply doesnt have enough time to complete.



> Another thing i noticed is the app is not requesting permission for background running when installed. It should

Not supported on Wear OS. Google has not allowed it, the activity simply does not exist on the watch. Samsung added something that is not documented and has no way to trigger other than informing the user to do it manually.



> I don't know the code but if the commands work when the app is open, they should work from the tile. Maybe some SO stuff changed...

Yes I agree and this is the case for all other users, seems Samsung has changed something in Wear OS 4 as our code has not changed and in fact toggling entities is shared code with the phone.

We can only go by what the logs tell us at this point, maybe when the Pixel Watch is also updated with Wear OS 4 can we see if the issue impacts other devices.

**Comment by ciclapt** [comment]
After further investigating, I found another case opened by another person with the same issues as mine. In the end I followed the same strategy and it fixed the issue. I'm guessing the upgrade from Wear OS 3.5 to 4 doesn't come out as clean as it should. So the only solution I have found was to factory reset the watch and reconfigure everything. Wear OS 4 has a new backup implementation but its not as efective as it should. A lot more configuration than it should. So that's that. Thank you for your support!

**Comment by guillaumecl** [comment]
Hello, i Just wanted to say that I'm having the exact same issue as @ciclapt. 

The shortcuts used to work properly but now only work when connected to wifi, which is annoying for me since I use my watch to unlock my door remotely before I have the wifi connected.

I also am on wear os 4 (galaxy watch 4)

I will try the factory reset workaround.

**Comment by guillaumecl** [comment]
In case this helps anyone, I wanted to add that the factory reset also fixed the problem in my case.

**Comment by dshokouhi** [comment]
For anyone reading this (or those who already tried) instead of factory resetting the watch. Please first try and clear data in the HA app on the watch and log back in. Notice how I did not say uninstall and reinstall because that triggers auto back up which we want to avoid here and rule out as an issue. If clearing data still produces the same issue and only a factory reset will clear things up will be helpful in understanding what the actual issue is.
