### ISSUE TITLE
Unable to open portainer tab due to certificate authority is not trusted

### ISSUE THREAD

**Issue by IvanGavrilenko** [home-assistant/android#3910]
**Home Assistant Android app version(s):**
2023.9.2-full
**Android version(s):**
Android 13
**Device model(s):**
OnePlus NE2211
**Home Assistant version:**
Home Assistant 2023.9.2 docker installation
**Last working Home Assistant release (if known):**
N/A
**Description of problem, include YAML if issue is related to notifications:**
I've added a portainer tab to HA docker installation via adding following code to configuration.yaml:

```panel_iframe: 
  portainer:
    title: Portainer
    url: "https://192.168.1.2:9443"
    icon: mdi:docker
    require_admin: true```

And in computer or mobile browser it works quite well, but HA mobile app shows only icon of the additional tab, and if I try to open the tab shows error of certificate authority is not trusted with buttons exit -exits the app and strings -opens app settings.

<!--
- For Wear OS devices we will need the LogCat logs from the device.
- For Android Auto the logs can be retrieved from the connected device.
- Logs from the device can be taken from Settings > Companion App Troubleshooting > Show and Share Logs
-->
**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![Screenshot_2023-10-04-00-29-45-74_c3a231c25ed346e59462e84656a70e50](https://github.com/home-assistant/android/assets/37136246/5036ec0c-21f5-427a-a078-0aa61e394d7d)

**Additional information:**

**Comment by IvanGavrilenko** [comment]
![Screenshot_2023-10-04-00-29-45-74_c3a231c25ed346e59462e84656a70e50](https://github.com/home-assistant/android/assets/37136246/e94339f0-84c6-4217-b58a-db82a7fcac69)

**Comment by dshokouhi** [comment]
your issue is that your certificate is not valid locally, this will not work with the app. The app will not bypass a SSL certificate. Are you able to use `http` locally instead?

**Comment by IvanGavrilenko** [comment]
> your issue is that your certificate is not valid locally, this will not work with the app. The app will not bypass a SSL certificate. Are you able to use `http` locally instead?

Yes, using http helped - the panel opens correctly
