### ISSUE TITLE
Automation notification notifying 3 times for the same notification

### ISSUE THREAD

**Issue by mjb83** [home-assistant/android#3912]
As mentioned in the title, my issue is when my automation is triggered the notification sound that gets pushed to my Android (Samsung) phone mobile app gets repeated 3 times. I can't for the life of me find a setting for this or an explanation as to why it would repeat the same notification 3 times. 

I just got an A54 but previously it was doing the same thing on my Note 20 ultra 5g.

Here is my YAML code:

alias: Front door open
description: ""
trigger:
  - type: opened
    platform: device
    device_id: xxxyyyzzz
    entity_id: binary_sensor.front_door_sensor_contact
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
condition: []
action:
  - device_id: xxxyyyzzz
    domain: mobile_app
    type: notify
    message: Front door was opened
    title: Door Alert
mode: single

Any help... very much appreciated!!!!

**Comment by dshokouhi** [comment]
Check your home assistant log book for why the automation triggered multiple times. Outside of that you can try checking notification channel settings to see if the default sound just makes the same sound 3 times. Closing as this is not an app issue.
