### ISSUE TITLE
Proxy WiFi to proxy mobile

### ISSUE THREAD

**Issue by arne182** [home-assistant/android#3914]
**Home Assistant Android app version(s):**

**Android version(s):**
13
**Device model(s):**
Samsung Galaxy s22 Ultra 
**Home Assistant version:**
Latest
**Last working Home Assistant release (if known):**
None
**Description of problem, include YAML if issue is related to notifications:**
When the companion app tries to connect it does not work if changing from WiFi to mobile data. Closing and restarting the app does work and sometimes it does show an incorrect authentication had occurred but this is not always. It seems to be the changing of proxy settings that the companion app does not handle correctly.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
I do not think the app can solve this issue, typically changing proxy settings involves clearing data because the app uses WebView . I believe we have other closed issues with the same reason.

**Comment by arne182** [comment]
Yes, looks like one of those closed issues. Why has the issue been closed instead of being fixed? It does not seem right to have to close the whole app every time the connection is changed .

**Comment by dshokouhi** [comment]
WebView will cache proxy settings which requires things needing to be reset in order for them to change, its just the way WebView works and why the issues were closed.

**Comment by arne182** [comment]
The strange thing is that the proxy for mobile and for WiFi is exactly the same. So I do not understand why the webpage version works but the app does not. Any ideas?

**Comment by jpelgrom** [comment]
Do you mean changing between WiFi and mobile data perhaps?

When editing a proxy, the network connection type (WiFi or mobile data) doesn't change.

**Comment by arne182** [comment]
Editing is a known problem, that one I can understand. But what I have is a mobile data connection with the same proxy settings as my WiFi. So the connection in my mind should be the same for the app. But when walking out of range of by WiFi I get the same common error as in the closed issues and when I restart the app it works until I go back to my WiFi and then again I need to force close the app. I have set the companion app to never close and always be connected but I think that having to force close it every time I change to and from WiFi is not the solution to keep it permanently connected especially when the proxy connection details has not changed

**Comment by dshokouhi** [comment]
This doesnt sound like something a normal user will have configured. If you bypass your proxy setup does everything work as expected?

**Comment by arne182** [comment]
If I bypass my proxy there is no connection at all to home assistant as it is not accessible from the internet. The proxy adds another level of security. It is a standard WiFi and mobile data setting. From the multiple closed issues it seems like an option to reset the whole app if no connection is found after... Minutes would help everyone

**Comment by dshokouhi** [comment]
can you get us companion app logs of the issue please? reproduce it then grab the logs according to the issue template. Lets make sure the URL switching is working as intended

**Comment by arne182** [comment]
Exception while trying to map notification bundle
10-06 19:51:31.259 13896 13896 E NotificationManager: android.os.BadParcelableException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.idm.fotaagent.enabler.ui.notification.manager.NotificationType$6)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.Parcel.readSerializableInternal(Parcel.java:5074)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.Parcel.readValue(Parcel.java:4616)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.Parcel.readValue(Parcel.java:4324)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.Parcel$LazyValue.apply(Parcel.java:4422)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.Parcel$LazyValue.apply(Parcel.java:4381)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.BaseBundle.getValue(BaseBundle.java:374)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.BaseBundle.getValue(BaseBundle.java:357)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.BaseBundle.getValue(BaseBundle.java:350)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.BaseBundle.get(BaseBundle.java:674)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:324)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:320)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:333)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.updateActiveNotificationCount(NotificationSensorManager.kt:240)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.onNotificationRemoved(NotificationSensorManager.kt:175)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:501)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:527)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:539)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2362)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.Looper.loopOnce(Looper.java:226)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.Looper.loop(Looper.java:313)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.app.ActivityThread.main(ActivityThread.java:8757)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at java.lang.reflect.Method.invoke(Native Method)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
10-06 19:51:31.259 13896 13896 E NotificationManager: Caused by: java.lang.ClassNotFoundException: com.idm.fotaagent.enabler.ui.notification.manager.NotificationType
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at java.lang.Class.classForName(Native Method)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at java.lang.Class.forName(Class.java:454)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:683)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.Parcel$2.resolveClass(Parcel.java:5054)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1731)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1622)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1852)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1437)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:428)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	at android.os.Parcel.readSerializableInternal(Parcel.java:5057)
10-06 19:51:31.259 13896 13896 E NotificationManager: 	... 26 more
10-06 19:51:31.259 13896 13896 E NotificationManager: Caused by: java.lang.ClassNotFoundException: com.idm.fotaagent.enabler.ui.notification.manager.NotificationType
10-06 19:51:31.259 13896 13896 E NotificationManager: 	... 36 more
10-06 19:51:31.267 13896 13896 D SurfaceView@9a8ef2d: updateSurface: has no frame
10-06 19:51:31.274 13896 13896 D SurfaceView@9a8ef2d: updateSurface: has no frame
Is it just me or is it difficult to catch an error if the UI is frozen and asking to be killed. At least this is on starting.

**Comment by dshokouhi** [comment]
> `Exception while trying to map notification bundle`

that is unrelated to the described issue

> Is it just me or is it difficult to catch an error if the UI is frozen and asking to be killed. At least this is on starting.

Thats not an error crash but an ANR. Can you double check that Android System Webview is up to date and may also be a good time to check that all custom cards are up to date. Another thing to try is to disable custom cards one at a time to see if any of them are the cause of the delayed issue.

The logs shown are not complete. Please stop the app, open it again and reproduce the issue then grab the logs. We have some log statements around when switching from internal to external URL that we would like to validate to make sure its behaving as expected.

**Comment by arne182** [comment]
false
10-06 22:34:18.631 25226 25226 D SensorManager: unregisterListener
10-06 22:34:18.631 25226 25226 D PressureSensor: Pressure sensor listener unregistered
10-06 22:34:18.691 25226 25226 E NotificationManager: Exception while trying to map notification bundle
10-06 22:34:18.691 25226 25226 E NotificationManager: android.os.BadParcelableException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.idm.fotaagent.enabler.ui.notification.manager.NotificationType$6)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.Parcel.readSerializableInternal(Parcel.java:5074)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.Parcel.readValue(Parcel.java:4616)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.Parcel.readValue(Parcel.java:4324)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.Parcel$LazyValue.apply(Parcel.java:4422)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.Parcel$LazyValue.apply(Parcel.java:4381)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.BaseBundle.getValue(BaseBundle.java:374)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.BaseBundle.getValue(BaseBundle.java:357)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.BaseBundle.getValue(BaseBundle.java:350)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.BaseBundle.get(BaseBundle.java:674)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:324)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:320)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:333)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.updateActiveNotificationCount(NotificationSensorManager.kt:240)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.onNotificationRemoved(NotificationSensorManager.kt:175)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:501)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:527)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.service.notification.
android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:539)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2362)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.Looper.loopOnce(Looper.java:226)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.Looper.loop(Looper.java:313)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.app.ActivityThread.main(ActivityThread.java:8757)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at java.lang.reflect.Method.invoke(Native Method)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
10-06 22:34:18.691 25226 25226 E NotificationManager: Caused by: java.lang.ClassNotFoundException: com.idm.fotaagent.enabler.ui.notification.manager.NotificationType
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at java.lang.Class.classForName(Native Method)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at java.lang.Class.forName(Class.java:454)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:683)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.Parcel$2.resolveClass(Parcel.java:5054)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1731)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1622)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1852)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1437)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:428)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	at android.os.Parcel.readSerializableInternal(Parcel.java:5057)
10-06 22:34:18.691 25226 25226 E NotificationManager: 	... 26 more
10-06 22:34:18.691 25226 25226 E NotificationManager: Caused by: java.lang.ClassNotFoundException: com.idm.fotaagent.enabler.ui.notification.manager.NotificationType
10-06 22:34:18.691 25226 25226 E NotificationManager: 	... 36 more
10-06 22:34:18.758 25226 25226 E NotificationManager: Exception while trying to map notification bundle
10-06 22:34:18.758 25226 25226 E NotificationManager: android.os.BadParcelableException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.idm.fotaagent.enabler.ui.notification.manager.NotificationType$6)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.Parcel.readSerializableInternal(Parcel.java:5074)
10-06 22:34:18.758 25226 25226 E NotificationManagerandroid.os.Parcel.readValue(Parcel.java:4616)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.Parcel.readValue(Parcel.java:4324)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.Parcel$LazyValue.apply(Parcel.java:4422)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.Parcel$LazyValue.apply(Parcel.java:4381)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.BaseBundle.getValue(BaseBundle.java:374)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.BaseBundle.getValue(BaseBundle.java:357)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.BaseBundle.getValue(BaseBundle.java:350)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.BaseBundle.get(BaseBundle.java:674)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:324)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle$default(NotificationSensorManager.kt:320)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.mappedBundle(NotificationSensorManager.kt:333)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.updateActiveNotificationCount(NotificationSensorManager.kt:240)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at io.homeassistant.companion.android.sensors.NotificationSensorManager.onNotificationRemoved(NotificationSensorManager.kt:175)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:501)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:527)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:539)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2362)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.Looper.loopOnce(Looper.java:226)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.Looper.loop(Looper.java:313)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.app.ActivityThread.main(ActivityThread.java:8757)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at java.lang.reflect.Method.invoke(Native Method)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
10-06 22:34:18.758 25226 25226 E NotificationManager: Caused by: java.lang.ClassNotFoundException: com.idm.fotaagent.enabler.ui.notification.manager.NotificationType
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at java.lang.Class.classForName(Native Method)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at java.lang.Class.forName(Class.java:454)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:683)
10-06 22:34:18.758 25226 25226 E java.lang.Class.forName(Class.java:454)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:683)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.Parcel$2.resolveClass(Parcel.java:5054)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1731)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1622)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1852)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1437)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:428)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	at android.os.Parcel.readSerializableInternal(Parcel.java:5057)
10-06 22:34:18.758 25226 25226 E NotificationManager: 	... 26 more
10-06 22:34:18.758 25226 25226 E NotificationManager: Caused by: java.lang.ClassNotFoundException: com.idm.fotaagent.enabler.ui.notification.manager.NotificationType
10-06 22:34:18.758 25226 25226 E NotificationManager: 	... 36 more
10-06 22:34:19.307 25226 25226 D SensorReceiver: Received intent: android.net.wifi.STATE_CHANGE
10-06 22:34:19.310 25226 12493 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: false
10-06 22:34:19.324 25226 12493 D ActivitySM: Unregistering for activity updates.
10-06 22:34:19.324 25226 12493 D ActivitySM: Registering for activity updates.
10-06 22:34:19.353 25226 25226 D SensorReceiver: Received intent: android.net.wifi.STATE_CHANGE
10-06 22:34:19.358 25226 11300 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: false
10-06 22:34:19.369 25226 11300 D ActivitySM: Unregistering for activity updates.
10-06 22:34:19.369 25226 11300 D ActivitySM: Registering for activity updates.
10-06 22:34:20.109 25226 12493 I BluetoothAdapter: STATE_ON
10-06 22:34:20.223 25226 11300 I BluetoothAdapter: STATE_ON
10-06 22:34:20.225 25226 25286 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-06 22:34:20.228 25226 11299 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-06 22:34:20.417 25226 22884 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-06 22:34:20.829 25226 12493 D SensorManager: registerListener :: 6, LPS22HHTR Barometer, 200000, 0, 
10-06 22:34:20.829 25226 12493 D PressureSensor: Pressure sensor listener registered
10-06 22:34:20.829 25226 11300 D SensorManager: registerListener fail (2) :: 6, LPS22HHTR Barometer, 200000, 0, io.homeassistant.companion.android.common.sensors.PressureSensorManager@ab6006b
10-06 22:34:20.829 25226 11300 D PressureSensor: Pressure sensor listener registered
10-06 22:34:20.833 25226 12493 D SensorManager: registerListener :: 19, Step Counter Sensor, 200000, 0, 
10-06 22:34:20.833 25226 12493 D StepsSensor: Steps sensor listener registered
10-06 22:34:20.833 25226 11300 D SensorManager: registerListener fail (2) :: 19, Step Counter Sensor, 200000, 0, io.homeassistant.companion.android.common.sensors.StepsSensorManager@160f7c8
10-06 22:34:20.833 25226 11300 D 200000, 0, io.homeassistant.companion.android.common.sensors.StepsSensorManager@160f7c8
10-06 22:34:20.833 25226 11300 D StepsSensor: Steps sensor listener registered
10-06 22:34:20.842 25226 25226 D SensorManager: unregisterListener
10-06 22:34:20.842 25226 25226 D StepsSensor: Steps sensor listener unregistered
10-06 22:34:20.869 25226 12493 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-06 22:34:20.870 25226 12493 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-06 22:34:20.879 25226 11300 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-06 22:34:20.890 25226 11300 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-06 22:34:20.906 25226 25226 D SensorManager: unregisterListener
10-06 22:34:20.906 25226 25226 D PressureSensor: Pressure sensor listener unregistered
10-06 22:34:21.056 25226 11299 I SensorReceiver: Sensor updates and sync completed
10-06 22:34:21.087 25226 12493 I SensorReceiver: Sensor updates and sync completed
10-06 22:34:21.101 25226 25226 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
10-06 22:34:21.109 25226 25226 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
10-06 22:34:21.428 25226 12493 I SensorReceiver: Sensor updates and sync completed
10-06 22:34:21.615 25226 11299 E WebSocketRepository: Unable to connect
10-06 22:34:21.615 25226 11299 E WebSocketRepository: java.net.ConnectException: Failed to connect to /192.168.188.196:8123
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
10-06 22:34:21.615 25226 11299 E WebSocketRepository4:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at java.lang.Thread.run(Thread.java:1012)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: Caused by: java.net.ConnectException: failed to connect to /192.168.188.196 (port 8123) from /100.81.140.60 (port 55090) after 10000ms: isConnected failed: ECONNABORTED (Software caused connection abort)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at libcore.io.IoBridge.isConnected(IoBridge.java:347)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:237)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at libcore.io.IoBridge.connect(IoBridge.java:179)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
10-06 22:34:21.615 25226 11299 E WebSocketRepository: 	at java.net.Socket.connect(Socket.java:646)
10-06 22:34:21.615 25226

**Comment by arne182** [comment]
If I look at it correctly it does not switch to an internal IP  because 192.168.188.196 is the external IP also inside the WiFi and it still wants to connect with the mobile data IP and does not check that I am no longer on 100.81.140.60 but I'm the new IP range of 192.168.188.186. I have had it work before if I do not have a sporty data connection with a lot of drops that connecting to the WiFi and back to mobile does give the desired behaviour. Will see if I can catch that log tomorrow

**Comment by dshokouhi** [comment]
internal connection switching only switches based on the connected WiFi SSID and nothing else.

`10-06 22:34:19.310 25226 12493 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: false`

you do not have URL switching configured properly in the app

`10-06 22:34:21.615 25226 11299 E WebSocketRepository: java.net.ConnectException: Failed to connect to /192.168.188.196:8123`

This is probably the error you need to solve, the companion app cannot fix this error.

**Comment by arne182** [comment]
I have now added the internal IP as well but as you see from the screen shot they are exactly the same
![Screenshot_20231007_080211_Home Assistant](https://github.com/home-assistant/android/assets/844102/e35cc76c-aba9-48c9-b86f-c0bd08909d94)

**Comment by dshokouhi** [comment]
Yes so that means this is a network issue as you can see there is a failed to connect error. That is not an error the app can solve.

**Comment by arne182** [comment]
The joke is that if I just a web browser it connects to that address. Any idea what is up with the negative counting?
![Screenshot_20231007_170610_Home Assistant](https://github.com/home-assistant/android/assets/844102/fb3cc4e0-3e81-4dc7-9e64-542718c1b7d7)

**Comment by dshokouhi** [comment]
> The joke is that if I just a web browser it connects to that address.

Browsers don't behave the same as WebView, WebView handles caching differently and also allows for API interaction.



> Any idea what is up with the negative counting?

Not sure that is not an app provided screen but one presented by the HA frontend. Is this the error you are seeing?

**Comment by arne182** [comment]
I think it might be better now that the WiFi said is added even though it is the same address
