### ISSUE TITLE
Haptic feedback still active for knob navigation

### ISSUE THREAD

**Issue by blakadder** [home-assistant/android#3928]
**Home Assistant Android app version(s):**
2023.10.2-full

**Android version(s):** 12

**Device model(s):** TicWatch Pro 5

**Home Assistant version:** 2023.10.0

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

Haptic feedback turned off in settings but it's still active when using knob navigation

**Comment by jpelgrom** [comment]
Do you mean using the crown / rotary input? This is system behavior and not affected by the in app setting, which only refers to toggling items.

**Comment by blakadder** [comment]
Yes, couldn't remember how it was called :D My "Using crown" vibration is turned off in watch settings and isn't active when using the launcher or other apps such as Play store, Google Keep, Messages, Contacts, etc. It is active in HA Companion and HA Assista

**Comment by jpelgrom** [comment]
Sounds like a bug in Google's library for rotary input ;)

**Comment by blakadder** [comment]
As additional note the haptic strength when "Using crown" option is activated is significantly weaker than the one produced by HA companion which is equivalent to the regular notification vibration.

**Comment by jpelgrom** [comment]
Looked into this and this won't be changed. This isn't something for Home Assistant to handle - we are using the default settings from Google and a comment on a PR suggests [developers shouldn't change this](https://github.com/google/horologist/pull/1452#discussion_r1238725704). Also discussed with @dshokouhi and it looks like his Pixel Watch does not vibrate when using the crown when the system setting is off so it may be a device-specific issue.

I suggest [opening an issue for the library](https://github.com/google/horologist/issues/new) (`rotaryWithScroll` doesn't respect device setting for crown haptics).

> Haptic feedback turned off in settings

I can see the confusion but these settings in the Home Assistant app are only for interacting with entities. We could make that more obvious. You also don't get toasts messages when scrolling or haptics when tapping other buttons.

**Comment by blakadder** [comment]
Do you have any ideas on why the vibrations in companion are stronger than in all of the other apps?

The confusion stemmed from the fact that the crown haptic feedback is weaker in all the other apps while in companion it's identical to the touch vibration when the option is enabled.

Furthermore I'm not sure I know what toast messages option does or what toast messages are but that's not the topic here.

**Comment by jpelgrom** [comment]
> Do you have any ideas on why the vibrations in companion are stronger than in all of the other apps?

I guess there is a difference between the effect used by classic views, and Compose, which Home Assistant uses. 

> what toast messages option does or what toast messages are

These are messages shown for a short time confirming the action you just did. Turn it on and toggle an entity to try it ;) Point taken that these settings should be more descriptive.

**Comment by blakadder** [comment]
> > Do you have any ideas on why the vibrations in companion are stronger than in all of the other apps?
> 
> I guess there is a difference between the effect used by classic views, and Compose, which Home Assistant uses. 

Looks like it. I just went through all the apps I have on the phone with the vibrations on and HA is the only one with the violent one

> > what toast messages option does or what toast messages are
> 
> These are messages shown for a short time confirming the action you just did. Turn it on and toggle an entity to try it ;) Point taken that these settings should be more descriptive.

Thanks for the explanation. Now I can turn it off :D

**Comment by jpelgrom** [comment]
Found a similar setting on my Galaxy Watch 4 and observed the same, contributed to the issue you created in the horologist repository :)

Closing this one now, if changed in the library the app will get it automatically.

**Comment by marazmarci** [comment]
For future reference, here's the newly reported issue: https://github.com/google/horologist/issues/1750
