### ISSUE TITLE
Profile is displayed incorrectly in RTL languages

### ISSUE THREAD

**Issue by tzagim** [home-assistant/android#3929]
**Home Assistant Android app version(s):** 2023.9.2-minimal
**Android version(s):** 13
**Device model(s):** samsung s23 ultra
**Home Assistant version:** 2023.10.1

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

When opening the profile in the application and the device language is set to RTL (Hebrew, Arabic) the screen moves to the right and is not displayed immediately, and actions cannot be performed.

To reproduce the problem, change the language to Hebrew or Arabic and enter the profile.

**Comment by dshokouhi** [comment]
can you reproduce the issue using chrome for android on the same device?

**Comment by tzagim** [comment]
@dshokouhi
partially.
There is also a black screen there but it is on the left side and not on the right side.
That's probably why I didn't notice the problem until now in the browser.

**Comment by dshokouhi** [comment]
ok this is most likely a frontend issue then as the profile screen is not controlled by the app, also can you share a screenshot of what you see in the app? good to have for reference.

I would try checking open frontend issues to see if its not already reported

**Comment by tzagim** [comment]
![bug](https://github.com/home-assistant/android/assets/2285958/64e63aeb-0b81-475e-a6e9-d4a8d94eb799)
Thank you!
