### ISSUE TITLE
Every(!) touch to graphs lead to detail value display even if not intended

### ISSUE THREAD

**Issue by jubie25** [home-assistant/android#3932]
**Home Assistant Android app version(s):**
2023.9.2-full (and older)

**Android version(s):**
Android 13, Android 14

**Device model(s):**
Google Pixel 7, Pixel 5

**Home Assistant version:**
2023.10.1 and older

**Last working Home Assistant release (if known):**
not remembering. Never?

**Description of problem, include YAML if issue is related to notifications:**
*Every* touch on the display targeting a graph leads to instantly display an overlay window showing detail values to that point. This is true even if the touch is a swipe gesture. The popping up overlay window is rather persistent. Only a touch again within the graph makes is go away (and only if placed wise). This limits daily user experience and lead to confusing unexperienced users (wall mounted display)

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
In this example even two overlays disturb swipe gesture.
![grafik](https://github.com/home-assistant/android/assets/72253640/4f1ea008-0ca1-4632-9b71-d1f06c5f1b0b)

**Additional information:**
Proposal:
Detailed overlay infos should come up only after long press.
Maybe a switch to totally disable those overlays makes sense (for wall mounted info displays).

**Comment by jpelgrom** [comment]
Can you also reproduce this issue in Chrome on the same device?

The app doesn't do anything with graphs so it is likely to be a frontend issue.

**Comment by jubie25** [comment]
Yes, it's the same behavior. This screenshot was recorded with chrome on the same smartphone. The overlays appeared when doing a swipe gesture.  
![grafik](https://github.com/home-assistant/android/assets/72253640/37af3ef3-e840-4a80-a822-facb14c1f842)

**Comment by jubie25** [comment]
fyi: Usually I use a firefox derivate (Fenec). The same here.

**Comment by jpelgrom** [comment]
Thanks for confirming. Please [open a frontend issue instead] (https://github.com/home-assistant/frontend/issues/new/choose), this is not app specific.

> Usually I use a firefox derivate (Fenec)

The app internally uses WebView which is based on Chromium, which is why I asked about Chrome.
