### ISSUE TITLE
Unable to display image not located in /www dir, in notification

### ISSUE THREAD

**Issue by nappyjim** [home-assistant/android#3933]
**Home Assistant Android app version(s):**

**Android version(s):**
14

**Device model(s):**
Google Pixel 7 Pro

**Home Assistant version:**
Supervisor: 2023.10.0
OS: 10.5
Frontend 20231002.0 - latest

**Last working Home Assistant release (if known):**
NA

**Description of problem, include YAML if issue is related to notifications:**
I am trying to attach in image to a notification.  I am not able under normal circumstances to have the image be placed in the /www folder.   If I DO place it in the /www folder, the picture appears on the notification.

But with the image in the folder it has to normally reside, the notification does not show the image and I get a render error in the logs.   

The image will reside in /config/custom_components/mail_and_packages/images/amazon/

I have added this dir to my external allow list:
````
homeassistant:
  allowlist_external_dirs:
    - /config/custom_components/mail_and_packages/images/amazon
````

I have formatted my notification as such:
````
{
    "title": "",
    "message": "Picture test",
    "data": {
        "sticky": "false",
        "priority": "Normal",
        "ttl": 0,
        "tag": "picture_test",
        "color": "blue",
        "image": "/config/custom_components/mail_and_packages/images/amazon/1.jpg"
    }
}
````

**Companion App Logs:**

```
10-11 23:14:04.870 20164 20164 D MessagingService: Creating notification with following data: {sticky=false, tag=picture_test, color=blue, image=/config/custom_components/mail_and_packages/images/amazon/1.jpg, webhook_id=981d46d926e4a9e33795aaaaef55b8a5625a00cfb4465d9d4ae2670fdf43b2a3, message=Picture test, server_id=1}
10-11 23:14:04.877 20164 20164 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: false
10-11 23:14:04.877 20164 20164 D ServerConnectionInfo: Using external URL
10-11 23:14:04.880 20164 20901 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: false
10-11 23:14:04.880 20164 20901 D ServerConnectionInfo: Using external URL
10-11 23:14:05.033 20164 20901 D TrafficStats: tagSocket(115) with statsTag=0xffffffff, statsUid=-1
10-11 23:14:05.723 20164 20901 D OpenGLRenderer: --- Failed to create image decoder with message 'unimplemented'
10-11 23:14:05.732 20164 20164 D MessagingService: Show notification with tag "picture_test" and id "-785838285"
10-11 23:14:07.400 20164 20901 D LogcatReader: Read logcat for pid 20164
```

**Screenshot or video of problem:**

**Additional information:**
To cut down on folder nesting I even copied the image to the /config folder and tried it from there, it did not work either.

**Comment by dshokouhi** [comment]
> 10-11 23:14:05.723 20164 20901 D OpenGLRenderer: --- Failed to create image decoder with message 'unimplemented'

interesting slightly different error than what we saw in https://github.com/home-assistant/android/issues/3926#issuecomment-1758164173

**Comment by jpelgrom** [comment]
What is your Home Assistant URL in the app set to? Does that URL + path work in a browser on your phone?

**Comment by nappyjim** [comment]
> What is your Home Assistant URL in the app set to? Does that URL + path work in a browser on your phone?

Not sure exatly what you are looking for. In my System > Network settings my hostname is homeassistant.  In the Home Assistant URL, I am using the Nabu Casa cloud.  If I try to go to that URL + path,  I do NOT get the image either.  I created a post in HA forums about this (https://community.home-assistant.io/t/why-does-this-external-url-not-display-the-image/625248)

If I put the image in my /www folder and use the nabu casa cloud url + /local/1.jpg the image does show in my browser.   But any directory other than /local, and it does not show the image, just opens up my lovelace.

**Comment by nappyjim** [comment]
My reply above had to deal with going to url on my computer. I tried on my phone and I just get a blank screen. See screenshot

![Screenshot_20231012-103300](https://github.com/home-assistant/android/assets/71914301/221003c0-53d6-4887-be64-b1dc4e252034)

**Comment by dshokouhi** [comment]
> If I try to go to that URL + path, I do NOT get the image either.

So this is the actual issue you need to solve before it can work with the app. The URL needs to be accessible and working remotely. When I was looking at hte forums I incorrectly assumed you had already used the external URL.

interesting that it works with local URL but not Nabu Casa URL.

are there any HA core errors at the time?

not sure if it matters but maybe the URL needs to be defined here as well?

https://www.home-assistant.io/docs/configuration/basic/#external_url

Feels like some kind of network setting needs to be adjusted somewhere.

**Comment by nappyjim** [comment]
So what I just noticed when accessing my HA remotely, if I go into settings, I see the URL is my naba casa cloud + /config.

And coincidentally I am trying to access the /config directory.  I wonder if the actual /config directory is called something else (kind of like /www would be url+/local, not url+/www)

I checked core logs, no errors.

**Comment by dshokouhi** [comment]
Just helped another user out in #3943 and it turns out the path to the folder was not correct. Can you double check the actual path in file explorer?

**Comment by nappyjim** [comment]
> Just helped another user out in #3943 and it turns out the path to the folder was not correct. Can you double check the actual path in file explorer?

I had the path correct.   I honestly think its because the HA web interface already as a /config directory. So when I am trying to browse the /config folder, it keeps directing me to the web interface

![image](https://github.com/home-assistant/android/assets/71914301/7fffdd2b-6c1f-4051-a3dc-4189b2dfa946)

**Comment by dshokouhi** [comment]
oh right, I am not sure how that will work out then. I think the custom component already offers a `camera` entity for you to use right? In this case we are limited to the relative URL path and how it loads in a browser.

**Comment by nappyjim** [comment]
Getting back round to this, I am closing because as you said, its more a HA issue, not mobile app issue.  Thank you  (and yes, later on I found the component does offer a camera entity, so I still got what I needed)
