### ISSUE TITLE
Location information not updating

### ISSUE THREAD

**Issue by kantlivelong** [home-assistant/android#3935]
**Home Assistant Android app version(s):**
2023-10.2-full

**Android version(s):**
LineageOS 20 (Android 13) w/ Google Apps (MindTheGapps)

**Device model(s):**
OnePlus 8 Pro

**Home Assistant version:**
2023.10.2

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
I recently updated my phone from LineageOS 18 to 20. After the update I installed the Home Assistant app and things were working fine as far as I could tell. Today I noticed that my location information is not updating.

I've verified my settings are correct and followed https://companion.home-assistant.io/docs/troubleshooting/faqs/#device-tracker-is-not-updating-in-android-app. I also cleared my GPS coordinates from `core.restore_state` and  state shows up as "Unknown" which would be expected until location info is posted. 

I went on a 20 minute drive with the HA app open while switching to Google Maps. The OS shows HA accessing location yet nothing is gets posted. Google Maps shows the correct GPS location.

Attached is a short log file that I have thus far. One thing that might be of interest is that I'm repeatedly seeing:
`LocBroadcastReceiver: Background location updates appear to have stopped, restarting location updates`

[homeassistant_companion_log_9-12-2023_22-1-41.txt](https://github.com/home-assistant/android/files/12888738/homeassistant_companion_log_9-12-2023_22-1-41.txt)

I have access to adb/logcat if there's anything else I can provide let me know.

**Comment by dshokouhi** [comment]
Custom ROM is not supported with location tracking. Sorry.

**Comment by kantlivelong** [comment]
For those who run also into this:

I was able to get this working by using NikGapps Core ( https://nikgapps.com/ ). It appears as if the suggested GApps package (MindTheGapps) from LineageOS does not include it.
