### ISSUE TITLE
FER - Self Signed Certificates - 

### ISSUE THREAD

**Issue by Paddy3911** [home-assistant/android#3938]
**Is your feature request related to a problem? Please describe.**
There is currently no option to use self-signed certificates. This should be implemented as a priority.

**Describe the solution you'd like**
There should be the option to suppress errors with self-signed certificates.

**Describe alternatives you've considered, if any**
-

**Additional context**
-

**Comment by dshokouhi** [comment]
all you need to do is import the certificate and it will work.

https://companion.home-assistant.io/docs/troubleshooting/faqs/#using-a-self-signed-certificate-leads-to-a-blank-page-in-android
