### ISSUE TITLE
Add settings to enable near-realtime sensor updates when charging

### ISSUE THREAD

**Issue by Twanislas** [home-assistant/android#394]
Hi !

I believe the following settings could be very useful :
- Update sensors in realtime when charging and connected to wifi
- Update sensors in realtime when charging and **not** connected to wifi

The second one is an attempt to factor in the data usage as well. I don't care a thousand updates every 30 sec when I'm on wifi but maybe I don't want that on carrier data...

"realtime" being something along 1m or 30s of course.

This would allow (for example) :
- Realtime location tracking when driving (and plugged to a power source in the car) and thus fast reaction when coming home (open the garage door, turn on outside lights, ...)
- Frequent updates to the proximity sensor (TTS notifications announcing I'm nearing home, turn on the heating when < 20 km from home and driving towards, ...)

Thanks for your consideration :)

**Comment by JBassett** [comment]
For what it's worth if you are using your phone for GPS navigation and you have background location enabled you should be getting an update close to every 30 seconds already.

**Comment by Twanislas** [comment]
Maybe it's only since the last update ?

I actually monitor this from time to time and had been relying on the Google Maps integration because indeed updates were done every 30s or so in there. Last time I checked the HA map was updating roughly every 5 minutes.

I'll make sure to test that again as this may solve part of this issue's requests :)

Is there any place or log I could grep to see all pushes to HA from the app in realtime ?

Thanks anyways @JBassett :)

**Comment by JBassett** [comment]
If you enable debug logging of `homeassistant.components.mobile_app.webhook` you will get logs of every webhook that the application sends in you Home Assistant Core logs.

**Comment by Twanislas** [comment]
That's perfect and will help greatly tshooting !
Thank you :)

**Comment by dshokouhi** [comment]
So we have had quite a bit of enhancements to sensors recently. Most if them (if they can) are updated immediately upon a state change and we no longer send updates when the state has not changed to cut down on the amount of calls being made.  All sensors also report an update if they have them anytime one of them trigger. The only exception is the battery level and we have a more precise feature request for that in #671 

For location tracking we also have settings to adjust for the minimum amount of time that location has been reported.

 I think we may be good to close this one?

**Comment by Twanislas** [comment]
Yes we're good.

It's been a while now that I rely on HA's location tracking instead of Maps as it has become way more precise. To be honest, I forgot about this issue, my apologies.

Thanks a lot for having a look at it ! ;)
