### ISSUE TITLE
Next Alarm sensor constantly changes its value once the phone's screen is off

### ISSUE THREAD

**Issue by dollop80** [home-assistant/android#3940]
**Home Assistant Android app version(s):**
2023.10.2-full
**Android version(s):**
12
**Device model(s):**
POCO X3
**Home Assistant version:**
2023.10.3
**Last working Home Assistant release (if known):**
HA 2023.9.1 and Home Assistant Android 2023.9.2
**Description of problem, include YAML if issue is related to notifications:**
Once the Android phone screen is turned off the Next Alarm sensor is changing instantly to a time about 7-8 minutes in the future and continues to change. Once the screen is turned on - the sensor reports correct alarm clock time. Check the screenshot - the alarm clock time is set in the phone and wasn't changed, but the sensor reports some really strange values

**Companion App Logs:**
10-14 20:39:04.975 24747 24831 D LightSensor: Light sensor listener registered
10-14 20:39:04.978 24747 24747 D LightSensor: Light sensor listener unregistered
10-14 20:39:04.990 24747 24831 D NextAlarm: Next alarm is scheduled by com.google.android.deskclock with trigger time 1697338800000
10-14 20:39:05.007 24747 24831 D StepsSensor: Steps sensor listener registered
10-14 20:39:05.015 24747 24790 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:05.016 24747 24790 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:05.022 24747 24747 D StepsSensor: Steps sensor listener unregistered
10-14 20:39:05.131 24747 24790 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:05.162 24747 24790 I SensorReceiver: Sensor updates and sync completed
10-14 20:39:06.441 24747 24747 D IntegrationRepository: setAppActive(): false
10-14 20:39:06.531 24747 24747 D SensorReceiver: Received intent: io.homeassistant.companion.android.UPDATE_SENSORS
10-14 20:39:06.536 24747 24789 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:06.591 24747 24759 W System  : A resource failed to call destroy. 
10-14 20:39:06.621 24747 24789 D LightSensor: Light sensor listener registered
10-14 20:39:06.624 24747 24747 D LightSensor: Light sensor listener unregistered
10-14 20:39:06.646 24747 24789 D NextAlarm: Next alarm is scheduled by com.google.android.deskclock with trigger time 1697338800000
10-14 20:39:06.657 24747 24747 D DecorView[]: onWindowFocusChanged hasWindowFocus false
10-14 20:39:06.677 24747 24789 D StepsSensor: Steps sensor listener registered
10-14 20:39:06.689 24747 24747 D StepsSensor: Steps sensor listener unregistered
10-14 20:39:06.692 24747 24831 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:06.696 24747 24831 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:06.864 24747 24831 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:06.888 24747 24831 I SensorReceiver: Sensor updates and sync completed
10-14 20:39:07.460 24747 24747 D SensorReceiver: Received intent: android.intent.action.SCREEN_OFF
10-14 20:39:07.461 24747 24747 D SensorReceiver: Sensor is_interactive corresponding to received event android.intent.action.SCREEN_OFF is disabled, skipping sensors update
10-14 20:39:07.464 24747 24747 D ButtonWidget: Broadcast received: 
10-14 20:39:07.464 24747 24747 D ButtonWidget: Broadcast action: android.intent.action.SCREEN_OFF
10-14 20:39:07.464 24747 24747 D ButtonWidget: AppWidgetId: -1
10-14 20:39:07.469 24747 24747 D MediaPlayCtrlsWidget: Broadcast received: 
10-14 20:39:07.469 24747 24747 D MediaPlayCtrlsWidget: Broadcast action: android.intent.action.SCREEN_OFF
10-14 20:39:07.469 24747 24747 D MediaPlayCtrlsWidget: AppWidgetId: -1
10-14 20:39:07.496 24747 24747 D SensorReceiver: Received intent: android.app.action.NEXT_ALARM_CLOCK_CHANGED
10-14 20:39:07.502 24747 24831 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:07.517 24747 24789 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:07.518 24747 24795 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=e7f775f2-ec6f-445c-84ac-4dc71131bbee, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
10-14 20:39:07.551 24747 24831 D LightSensor: Light sensor listener registered
10-14 20:39:07.558 24747 24747 D LightSensor: Light sensor listener unregistered
10-14 20:39:07.580 24747 24831 D NextAlarm: Next alarm is scheduled by com.miui.securitycenter with trigger time 1697305747250
10-14 20:39:07.602 24747 24831 D StepsSensor: Steps sensor listener registered
10-14 20:39:07.613 24747 24747 D StepsSensor: Steps sensor listener unregistered
10-14 20:39:07.615 24747 24789 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:07.618 24747 24789 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:07.775 24747 24789 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:07.815 24747 24789 I SensorReceiver: Sensor updates and sync completed
10-14 20:39:08.867 24747 24747 D SensorReceiver: Received intent: android.intent.action.SCREEN_ON
10-14 20:39:08.868 24747 24747 D SensorReceiver: Sensor is_interactive corresponding to received event android.intent.action.SCREEN_ON is disabled, skipping sensors update
10-14 20:39:08.883 24747 24747 D SensorReceiver: Received intent: android.app.action.NEXT_ALARM_CLOCK_CHANGED
10-14 20:39:08.885 24747 24747 D ButtonWidget: Broadcast received: 
10-14 20:39:08.885 24747 24747 D ButtonWidget: Broadcast action: android.intent.action.SCREEN_ON
10-14 20:39:08.885 24747 24747 D ButtonWidget: AppWidgetId: -1
10-14 20:39:08.888 24747 24789 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:08.891 24747 24820 W WM-Processor: Didn't find WorkSpec for id WorkGenerationalId(workSpecId=b700619f-3b84-4d70-9b9c-c4dabb8b370b, generation=0)
10-14 20:39:08.898 24747 24747 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:08.899 24747 24747 D ButtonWidget: Updating all widgets
10-14 20:39:08.912 24747 24747 D MediaPlayCtrlsWidget: Broadcast received: 
10-14 20:39:08.912 24747 24747 D MediaPlayCtrlsWidget: Broadcast action: android.intent.action.SCREEN_ON
10-14 20:39:08.912 24747 24747 D MediaPlayCtrlsWidget: AppWidgetId: -1
10-14 20:39:08.913 24747 24747 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:08.916 24747 24790 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:08.918 24747 24747 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: true
10-14 20:39:08.918 24747 24783 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=517aebf0-0370-4674-a2be-5e638f234ddc, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
10-14 20:39:08.969 24747 24789 D LightSensor: Light sensor listener registered
10-14 20:39:08.974 24747 24747 D LightSensor: Light sensor listener unregistered
10-14 20:39:09.013 24747 24789 D NextAlarm: Next alarm is scheduled by com.google.android.deskclock with trigger time 1697338800000
10-14 20:39:09.047 24747 24789 D StepsSensor: Steps sensor listener registered

**Screenshot or video of problem:**
![image](https://github.com/home-assistant/android/assets/11781188/28ef4af6-3538-4eb5-8490-5771bb378780)

**Additional information:**
I have been using google clock instead of xiaomi clock for about 2 years, because I'm aware of xiaomi clock issues.

**Comment by dshokouhi** [comment]
The app has no control over what apps set an alarm. In your case `com.miui.securitycenter`. You can set an allow list for the sensor to help avoid this.

```
10-14 20:39:07.580 24747 24831 D NextAlarm: Next alarm is scheduled by com.miui.securitycenter with trigger time 1697305747250
```

https://companion.home-assistant.io/docs/core/sensors#next-alarm-sensor
