### ISSUE TITLE
Copy, cut and paste won't work 

### ISSUE THREAD

**Issue by Patbonamy** [home-assistant/android#3941]
**Home Assistant Android app version(s):**

**Android version(s):**
12
**Device model(s):**
Mi 10 lite 5G
**Home Assistant version:**
Latest 
**Last working Home Assistant release (if known):**
Never
**Description of problem, include YAML if issue is related to notifications:**
Hello,
When I use the file editor the copy and cut doing nothing I cannot paste the text because it is empty.
It working on my Android Tablet but not on my phone.

**Companion App Logs:**

```
```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
This is out of control for the android app, most likely the issue is also reproducible using Chrome for Android on the same device. Please check open frontend issues to see if it was already reported there.

https://github.com/home-assistant/frontend

**Comment by Patbonamy** [comment]
> This is out of control for the android app, most likely the issue is also reproducible using Chrome for Android on the same device. Please check open frontend issues to see if it was already reported there.
> 
> https://github.com/home-assistant/frontend

I have no problem with chrome on the same device.
No issue in the frontend.
