### ISSUE TITLE
Move to a different beacon library thats more compatible with HA iBeacon integration

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#3948]
**Is your feature request related to a problem? Please describe.**

Yes the current library does not guarantee the bluetooth name can be sent out and this causes issues with the iBeacon integration.

**Describe the solution you'd like**

Switch to a library that will send the name so it can be more compatible with the iBeacon integration. See [discussion](https://github.com/home-assistant/core/issues/80357#issuecomment-1764352401) for more info.

**Describe alternatives you've considered, if any**

Update HA core to allow for devices without names which may introduce performance issues if a user enables it and has a lot of beacons nearby.

**Additional context**

**Comment by jpelgrom** [comment]
Should this be linked to #4027 so it's closed if that PR is merged, as it provides another solution to the reason this issue was created?

**Comment by dshokouhi** [comment]
> Should this be linked to #4027 so it's closed if that PR is merged, as it provides another solution to the reason this issue was created?

yes it should :)

**Comment by swann05** [comment]
Hi, i'm sorry but i feel like it takes the wrong path here. Having an app creating an iBeacon which is not fully usable with a smart house environment feels a little frustrating... I'm no coder, so I just understand that it will be a lot work but in the end if you want to have something fully versatile, i feel like it should be done.
Advertising the name does it more user friendly and doesn't block any communication with other devices.. You have the case for Ibeacon tracker integration now but there is and there will be other case in the future...
https://github.com/home-assistant/core/issues/80357#issuecomment-1345629881
https://github.com/home-assistant/core/issues/80357#issuecomment-1764352401
Please consider someone who seems to have a way better comprehension than me here.

**Comment by dshokouhi** [comment]
@swann05 the issue in HA core is specifically related to the ibeacon integration and not just the android app, changes made to the android app are for the HA core PR. That was the sole reason as to why this request was created in the first place, as you can see there is already work under way for the iBeacon integration.

Please stick to the current open request for beacon name that you had already commented on for updates so the beacons can work with other tools.
