### ISSUE TITLE
Android Auto: Wrong "state" icon color for "Locks"

### ISSUE THREAD

**Issue by tmason818** [home-assistant/android#3949]
**Home Assistant Android app version(s):** 1023.10.2-full

**Android version(s):** Android 13, Android Auto 10.6.634024

**Device model(s):** Pixel 7

**Home Assistant version:** 2023.10.3

**Last working Home Assistant release (if known):** n/a

**Description of problem, include YAML if issue is related to notifications:**
Seems that the Home Assistant device state icon indication for "Lock" is backwards (when compared to other similar device icons). In the screenshot the FRONT DOOR Lock is **illuminated Yellow** to indicate a "not-open" state while the Garage Door icon(s) are **not-illuminated** to indicate a "not-open" state.

Or, perhaps, device icons for Garage Doors are backwards and should be yellow to indicate "not-open" but throughout the Android Companion App Garage Doors are typically  illuminated when "not-closed".

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![image](https://github.com/home-assistant/android/assets/123908508/a2ce7b29-f88f-45e5-a9f0-b47409dd2735)

**Additional information:**

**Comment by dshokouhi** [comment]
This was a breaking change in the release the active state of the lock was updated to match Android system behavior.

https://github.com/home-assistant/android/pull/3862
