### ISSUE TITLE
Wear OS: receiving `clear_notification` on the watch

### ISSUE THREAD

**Issue by Flink** [home-assistant/android#3952]
**Home Assistant Android app version(s):**
2023.10.2-full

**Android version(s):**
14
Wear OS 4

**Device model(s):**
Pixel 6 Pro
Pixel Watch 2

**Home Assistant version:**
2023.10.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

As stated in the title, my watch is receiving `clear_notification` notifications and displays them instead of “ignoring” them as it happens on the phone.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

![photo_2023-10-19_11-57-51](https://github.com/home-assistant/android/assets/5648/55fb59ab-dfd4-4186-a325-772abd734e52)

**Additional information:**

**Comment by dshokouhi** [comment]
This feature is not supported on Wear OS.

https://companion.home-assistant.io/docs/wear-os/#notifications

**Comment by Flink** [comment]
My problem is not to support the notification for dismissing existing permanent notification, but instead to not relay it to the watch as it’s really annoying (I’m using https://community.home-assistant.io/t/yet-not-another-door-window-sensor-open-warning-notification-with-auto-close-and-reminder/448007 to monitor my windows and each time a window is closed, this `clear_notification` is sent which is completely transparent on the phone but annoying on the watch).

**Comment by jpelgrom** [comment]
If it doesn't appear on the phone, it is not a relayed notification. You're probably sending the notification to multiple or all devices, which includes the watch only service.

Can you confirm what you have entered for "Device to notify" or "Notification Group" in the linked blueprint?

**Comment by jpelgrom** [comment]
The watch notify target is for watch only notifications. Notifications from your phone will still come through (assuming you've enabled them in the watch settings).

**Comment by Flink** [comment]
I did some tests and found a way that actually works :slightly_smiling_face: In “Device to notify” I put the watch and in the “Notification group” I put a dedicated notify group for phones. I also had to change `notify.notify` at https://github.com/panhans/homeassistant/blob/main/blueprints/automation/panhans/entity_state_persistent_notification.yaml#L227 by `notify.{{ group_target }}`. I’ll probably issue a PR for this.

Anyway, thanks for your help @jpelgrom :grin:
