### ISSUE TITLE
Picture-in-picture does not work from Webpage card

### ISSUE THREAD

**Issue by awilson133** [home-assistant/android#3955]
**Home Assistant Android app version(s):**

**Android version(s):**
Android 14
HA App version 2023.10.2-full

**Device model(s):**
Pixel 7a

**Home Assistant version:**
2023.10.3

**Last working Home Assistant release (if known):**
Unknown

**Description of problem, include YAML if issue is related to notifications:**

When using a site with PIP capabilities in the Webpage card, those capabilities do not work.

Example:

- Opening this site in Chrome allows PIP to work without issue on Android: https://googlechrome.github.io/samples/picture-in-picture/
- Putting the same site inside of a webpage card displays the error message that the "Picture-in-picture API is disabled"
- Fullscreen video buttons work as intended

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by awilson133** [comment]
This is an issue upstream in Chrome webview, not in HA. Closing.

**Comment by awilson133** [comment]
This is an issue upstream in Chrome webview, not in HA. Closing.

**Comment by dshokouhi** [comment]
Just out of curiosity is there a logat error associated with this after reproducing?

**Comment by jpelgrom** [comment]
For future reference: https://bugs.chromium.org/p/chromium/issues/detail?id=852853
