### ISSUE TITLE
Allow to filter automations by last run date

### ISSUE THREAD

**Issue by danielgomezrico** [home-assistant/android#3957]
Having the possibility to filter by last run date will give you more debugging tools to see what's happening on your automations

**Describe the solution you'd like**
Add to the filters tab, an option that will show a time range and will show only automations that run in that time

**Comment by dshokouhi** [comment]
This is the android app repo, we do not take frontend requests. Please open either a discussion with the frontend team or a forum post in the feature request

**Comment by danielgomezrico** [comment]
Can you please give me more details? Is the android app is only like a web page that renders the frontend? 

I don't understand why this feature makes no sense here

**Comment by danielgomezrico** [comment]
Thanks for the explanation, now I understand 👍🏻
