### ISSUE TITLE
Support for Quest 3

### ISSUE THREAD

**Issue by CoreyJ87** [home-assistant/android#3964]
I tried to use the companion app on the quest 3 using the instructions that are out there for the quest and quest 2. It blew up. I assume theres some kind of updates that would need to be done for it to work with the 3? I would love to have it work. Thanks

**Comment by dshokouhi** [comment]
can you please get us the logcat logs when it blew up? I don't have a quest 3 here to test with but would need to see that. Did it install at least? any other info would be helpful.

**Comment by CoreyJ87** [comment]
Yeah it installed. I was able to get to the login page. i entered my login and pressed login. Then it threw an error. Let me get back to you on the specific error msg and logcat.

**Comment by dshokouhi** [comment]
yea a screenshot of the error would be good too, please also ensure you are using the latest version of the app. I just noticed sidequest had an old version so I just added teh latest on it.

**Comment by CoreyJ87** [comment]
Oh that was probably it. I just updated to the lastest version and it worked perfectly. Thanks so much.

**Comment by dshokouhi** [comment]
Thanks for confirming it worked

**Comment by CoreyJ87** [comment]
> Thanks for confirming it worked

No problem. I did edit my last post. Does appear there are a bunch of sensors not working. Although charging is probably the one im most interested in.

**Comment by dshokouhi** [comment]
Let's not combine multiple issues into the same one. What you see is safe to ignore. It takes time for the sensors to first update and on top of that the sensors stuck in the unknown state is a known HA core issue. The next app or HA core update will cause those sensors to re-register and the correct state will be shown.
