### ISSUE TITLE
Wear OS app stuttering

### ISSUE THREAD

**Issue by MasterTim17** [home-assistant/android#3967]
**Home Assistant Android app version(s):**
2023.10.2-full
2023.10.2-11484

**Android version(s):**
12
11

**Device model(s):**
oneplus 7t
xiaomi watch 2 pro

**Home Assistant version:**
2023.10.0

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
when i open the app on my smartwatch, it responds slowly and sometimes crashes

**Companion App Logs:**
i did wifi debugging with `adb logcat | grep homeassistant`. the log is in the attachment
[a.txt](https://github.com/home-assistant/android/files/13067566/a.txt)

**Screenshot or video of problem:**

https://github.com/home-assistant/android/assets/52961929/cbe30279-f836-467a-a215-695e57195f50

**Additional information:**

**Comment by dshokouhi** [comment]
The slowness of first launch is expected while all entities and states are loaded. If you want to speed that up avoid loading the rest of the home screen by enabling the Show only Favorites option in settings.

Unfortunately due to the filter on the logs they are not complete, please reproduce the issue and grab the logs again without the `homeassistant` filter as it removes important elements from the logs. Most likely your home screen crash is a duplicate of https://github.com/home-assistant/android/issues/3325

If you look at the timing you can see multiple entries are missing.

```
10-20 15:07:55.529 10354 10354 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 10354
10-20 15:07:55.529 10354 10354 E AndroidRuntime: 	at 
io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$1.invoke(MainView.kt:250)
10-20 15:07:55.529 10354 10354 E AndroidRuntime: 	at 
io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$1.invoke(MainView.kt:66)
10-21 16:05:20.523  9276  9276 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 9276
10-21 16:05:20.523  9276  9276 E AndroidRuntime: 	at 
io.homeassistant.companion.android.common.util.AudioRecorder.stopRecording(AudioRecorder.kt:84)
10-21 16:05:20.523  9276  9276 E AndroidRuntime: 	at 
io.homeassistant.companion.android.common.assist.AssistViewModelBase.stopRecording(AssistViewModelBase.kt:177)
10-21 16:05:20.523  9276  9276 E AndroidRuntime: 	at io.homeassistant.companion.android.conversation.ConversationViewMo
del.onConversationScreenHidden(ConversationViewModel.kt:298)
10-21 16:05:20.523  9276  9276 E AndroidRuntime: 	at io.homeassistant.companion.android.conversation.views.Conversation
ViewKt$LoadAssistView$1$1$1$1.invoke(ConversationView.kt:87)
10-21 16:05:20.523  9276  9276 E AndroidRuntime: 	at io.homeassistant.companion.android.conversation.views.Conversation
ViewKt$LoadAssistView$1$1$1$1.invoke(ConversationView.kt:81)
10-21 16:05:20.523  9276  9276 E AndroidRuntime: 	at io.homeassistant.companion.android.conversation.views.Conversation
ViewKt$ConversationResultView$3$1$1$1.invoke(ConversationView.kt:144)
10-21 16:05:20.523  9276  9276 E AndroidRuntime: 	at io.homeassistant.companion.android.conversation.views.Conversation
ViewKt$ConversationResultView$3$1$1$1.invoke(ConversationView.kt:144)
10-23 09:08:05.676 13078 13078 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 13078
10-23 09:08:05.676 13078 13078 E AndroidRuntime: 	at 
io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$1.invoke(MainView.kt:250)
10-23 09:08:05.676 13078 13078 E AndroidRuntime: 	at 
io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$1.invoke(MainView.kt:66)
10-23 09:09:13.019  3818  3818 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 3818
10-23 09:09:13.019  3818  3818 E AndroidRuntime: 	at 
io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$1.invoke(MainView.kt:250)
10-23 09:09:13.019  3818  3818 E AndroidRuntime: 	at 
io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$1.invoke(MainView.kt:66)
10-23 09:09:48.139  3992  3992 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 3992
10-23 09:09:48.139  3992  3992 E AndroidRuntime: 	at 
io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$1.invoke(MainView.kt:250)
10-23 09:09:48.139  3992  3992 E AndroidRuntime: 	at 
io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$1.invoke(MainView.kt:66)
10-23 09:12:27.563  4117  4117 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 4117
10-23 09:12:27.563  4117  4117 E AndroidRuntime: 	at 
io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$1.invoke(MainView.kt:250)
10-23 09:12:27.563  4117  4117 E AndroidRuntime: 	at 
io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$1.invoke(MainView.kt:66)
10-23 09:21:39.902  4407  4407 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 4407
10-23 09:21:39.902  4407  4407 E AndroidRuntime: 	at 
io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$1.invoke(MainView.kt:250)
10-23 09:21:39.902  4407  4407 E AndroidRuntime: 	at 
io.homeassistant.companion.android.home.views.MainViewKt$MainView$1$1.invoke(MainView.kt:66)

```

**Comment by MasterTim17** [comment]
thank you for answering. after 20 starts of homeassistant it got much more responsive. i now only enabled the view of favorite entites, which makes loading faster.

**Comment by Atesh5** [comment]
Same Issue here, but switching to "Favorites only" doesn't help.

Behavior with "Favorites only" ON:
Won't crash, won't show anything (even no Favorites)

Behavior with "Favorites only" OFF:
Trying to load all Entities, but crashes after max. 10 seconds, always. If you are fast enough before the crash, you can do whatever you want to, but suddenly the crash will come.

I didn't have this problem (or any other problem) in the past. It started with one of the last updates.

It tried everything that came into my mind.
I.ex. Kick my watch from HA and reassign it from scratch. Uninstall the App and install again.
I even reset my watch completely, so no doubt it came with an Update.

Its Galaxy Watch S4.
