### ISSUE TITLE
Android Service Button Widgets does not list SWITCH entities for nodered.trigger service

### ISSUE THREAD

**Issue by farrad** [home-assistant/android#3985]
**Home Assistant Android app version(s):** 2023.10.2-full

**Android version(s):** 13

**Device model(s):** Xiaomi Redmi Note 8 Pro

**Home Assistant version:** 2023.10.5

**Last working Home Assistant release (if known):** not known

**Description of problem, include YAML if issue is related to notifications:**
Target: Have Service Button Widget which update Node-RED (switch) entity exposed to Home Assistant (which then fires an attached Node-RED flow)

**How to reproduce:**
When creating new / updating existing Service Button Widget:
1. Service: `nodered.trigger`
2. Entity ID: contains only `group.***` entities, but no `switch.***` entities.
3. If typing manually, the service call would not work (respective service call works fine via HA Developer tools web interface)

**Companion App Logs:**

```

```
[homeassistant_companion_log_9-30-2023_12-14-44.txt](https://github.com/home-assistant/android/files/13204592/homeassistant_companion_log_9-30-2023_12-14-44.txt)

**Screenshot or vid
![Screenshot_20231030-120751_Home Assistant](https://github.com/home-assistant/android/assets/4819602/69122e82-968c-4c91-9521-84724bf79c54)
eo of problem:**

**Additional information:**
`switch.***` entities are generally received by the HA Companion (e.g. when selecting `switch.toggle` service, all the `switch.***` entities are listed in the Entity ID field of the Widget editor

**Comment by dshokouhi** [comment]
Are these services found in the HA services tab? Are there any errors in the companion app logs?

**Comment by dshokouhi** [comment]
not sure if related but check this issue and comment too

https://github.com/zachowj/hass-node-red/issues/224#issuecomment-1781730119

did you follow the breaking change mentioned?

**Comment by farrad** [comment]
@dshokouhi Thank you for your quick reply.

> not sure if related but check this issue and comment too
> 
> [zachowj/hass-node-red#224 (comment)](https://github.com/zachowj/hass-node-red/issues/224#issuecomment-1781730119)
> 
> did you follow the breaking change mentioned?

My issue does not have to do with this breaking change.
The issue is that I do not get HA entities of type 'switch' listed in the Service Button Widget for the `nodered.trigger` service, while I am getting them listed for another service e.g. `switch.toggle` in the same Service Button Widget.

**Comment by farrad** [comment]
> also what version of Node Red do you have? is it hte latest? Seems like there was a release last month with some fixes the service schema.

I am running version 3.1.0

**Comment by farrad** [comment]
> Are there any errors in the companion app logs?

In the attached Companion App log I do not see any nodered services listed in the `ButtonWidgetConfigAct: Services found:` structure (while I do see for instance the `switch.toggle`).

Any idea how the services list is created in the Widget?

**Comment by dshokouhi** [comment]
> Any idea how the services list is created in the Widget?

Yes its created by HA core giving us a list of valid services to use along with its data, if the node red service call is not valid then it will not be filled in and will not contain the correct field data. If you dont see nodered in the list of services that means the HA API is unaware of the service call and the app will not work with it.

**Comment by dshokouhi** [comment]
closing as things are working as expected, issue is probably with the custom integration not being included in the server response
