### ISSUE TITLE
App does not offer connections page when it fails to connect to HA

### ISSUE THREAD

**Issue by GraffJosh** [home-assistant/android#3994]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My device couldn't find my homeassistant instance, and displayed the retry page. There was no option to go to the app's settings page where I could adjust the URL of the instance. 

![image](https://github.com/home-assistant/frontend/assets/15370055/e2072a57-d8e0-4578-a374-663d5ac9b2c6)

### Describe the behavior you expected

I expected to be able to configure the app without needing to connect to the HA instance. 

### Steps to reproduce the issue

1. Unknown networking error prevents access to HA Instance
2. Open App
3. Try to configure networking. 
...

### What version of Home Assistant Core has the issue?

2023.10.5

### In which browser are you experiencing the issue with?

App 2023.10.2-full

### Which operating system are you using to run this browser?

Android 14

**Comment by GraffJosh** [comment]
Sure. I'll reopen if it happens again.

**Comment by MasterCATZ** [comment]
this happens all the time , either reboot phone or uninstall app to regain access to the settings section 

I really do miss phones that contain a menu button , even more so apps that just do not have a settings button to click ...
