### ISSUE TITLE
Energy Usage on Energy Dashboard unreadable since update

### ISSUE THREAD

**Issue by Raarrrinator** [home-assistant/android#3998]
After updating to Android app version 2023.10.2-full I noticed that the scale of the graph of Energy Usage in the Energy Dashboard changed, making it unreadable.

Please see screenshot as example:

![Screenshot_20231104_144618_Home Assistant](https://github.com/home-assistant/android/assets/69963716/c80694c6-0058-415d-b333-d239c907906f)

**Comment by dshokouhi** [comment]
Can you reproduce the issue using chrome for Android on the same device?

**Comment by Raarrrinator** [comment]
> Can you reproduce the issue using chrome for Android on the same device?

When using chrome the graph is like before the app update:
![Screenshot_20231104_152827_Chrome](https://github.com/home-assistant/android/assets/69963716/9d1a83fb-2c07-4d19-9c36-6b56a8142b61)

**Comment by dshokouhi** [comment]
This still isn't something the app controls, everything from the dashboard is part of WebView. I recommend looking at open frontend issues to see if one already exists. If not please open a new frontend issue following their issue template that was skipped here.

I would also double check that android system webview is up to from the play store.
