### ISSUE TITLE
Persistent notifications stop working after HA docker update

### ISSUE THREAD

**Issue by Solarunit** [home-assistant/android#3999]
**Android version(s):** 11

**Home Assistant version:** 2023.11.1 docker

**Description of problem, include YAML if issue is related to notifications:**

I noticed that android persistent notifications are very unreliable

Companion app from f-droid version 2023.10.2-minimal: 
Persistent connection: always

When you update HA docker from 2023.11.0 to 2023.11.1  Persistent notifications stopped working, if you force stop the app and open app again, notifications would start working again.

**Comment by dshokouhi** [comment]
please dont skip over parts of the issue template, everything is required to help you out especially the docs.

**Comment by Solarunit** [comment]
So I updated container today and notifications still work, I gonna close it then
