### ISSUE TITLE
zwave logs windows not working

### ISSUE THREAD

**Issue by royto** [home-assistant/android#400]
**Home Assistant Android version:**
1.7.0
**Android version:**
9.0
**Phone model:**
One plus 5T
**Home Assistant version:**
0.105.3
**Last working Home Assistant release (if known):**

**Description of problem:**
When opening logs for zwave, a blank window is opened ...
**Additional information:**
NA

**Comment by robbiet480** [comment]
Screenshot please. Did this ever work inside the app? Does it work in Chrome on Android?

**Comment by royto** [comment]
It works in chrome. It open a new window
![Screenshot_20200212-231511](https://user-images.githubusercontent.com/6990995/74382483-d12a0000-4ded-11ea-92bc-87dcbcb0cb96.jpg)

If I use as a chrome app also but logs are directly displayed in a modal
![Screenshot_20200212-231625](https://user-images.githubusercontent.com/6990995/74382591-ff0f4480-4ded-11ea-9a3b-399c38b16059.jpg)

In app, 
![Screenshot_20200212-232101](https://user-images.githubusercontent.com/6990995/74382832-60371800-4dee-11ea-9d50-dea8cb9a1ad7.jpg)

**Comment by dshokouhi** [comment]
Good catch! Haven't look at zwave till now, seeing the same thing on my screens

**Comment by robbiet480** [comment]
Same here. Looking into it.

**Comment by robbiet480** [comment]
Looks like when pressing either the Load or Tail button, it opens a window with `about:blank`.

@balloob Seems this is a frontend issue, but before I transfer this over there can you confirm this isn't something wrong with how we are handling new windows in the app?

**Comment by balloob** [comment]
Z-Wave log shouldn't be opened in a new window

**Comment by robbiet480** [comment]
Just checked on iOS, nothing happens when pressing either button. This error gets logged:

`Unhandled Promise Rejection: TypeError: null is not an object (evaluating 't.document') zwave-network.ts:52`

**Comment by balloob** [comment]
We're creating a blank window and write to it from the other window. Makes sense that the app not supports it.

**Comment by royto** [comment]
Is it a frontend issue ? If yes, who is in charge of creating it ?

**Comment by balloob** [comment]
Z-Wave panel has no current maintainer.

**Comment by royto** [comment]
Still not working ...

**Comment by penright** [comment]
Not working for me either. 
I think I understand what @balloob  was saying. For our stores, we use a .NET browser. Bottom line we wanted control over where the employee was going with browser apps. When backend developers open a blank page (about:blank) then throw stuff onto that page was causing us issues. We fixed it by switching to chromium and doing our own wrapper. 

So what and how can it be changed to work across all platforms. The log under the "server controls" tab works, can we make the zwave panel just like it?
