### ISSUE TITLE
After installing update, position tracking is disabled until confirming update information

### ISSUE THREAD

**Issue by maja76** [home-assistant/android#4002]
**Home Assistant Android app version(s):**

**Android version(s):**

**Device model(s):**

**Home Assistant version:**

newest 

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

After auto-updating Andoid-App via google playstore, app does not send sensor data to the home assistent server until starting the app and confirming informations about the last update.

This is very bad, if you track little children or ill persons. They will auto get their app-updates from the play store, then position tracking stops until somebody takes their mobile phones, starts the home assistant app and confims the information about the update.

So if something happend and you search the person after an app update, you could not find them, because info is not tracked any more :(

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Any reason why you decided not to fill out the issue template? Everything is required to help you out. I do not see this issue on my pixel 8 pro, the tracker continues to update after the app is updated. We will need logs to see what happened after the update.

**Comment by maja76** [comment]
We have this issue on lot of Android phones with different Android versions. Not only now, since a long time. 
When the Android app updates, position tracking won't work any more. 
Sometimes it is enough to confirm the information about the update. 
But also sometimes it seems, that the sensor settings for positions are lost.

**Comment by dshokouhi** [comment]
> We have this issue on lot of Android phones with different Android versions. Not only now, since a long time. When the Android app updates, position tracking won't work any more. Sometimes it is enough to confirm the information about the update. But also sometimes it seems, that the sensor settings for positions are lost.

this does not answer any of the questions in my comment, if you wnat our help please make sure to give us all requested information.

**Comment by dshokouhi** [comment]
closing due to lack of response from author
