### ISSUE TITLE
WearOS: Add support for notification cleared event

### ISSUE THREAD

**Issue by JosephAbbey** [home-assistant/android#4004]
**Home Assistant Android app version(s):**

**Android version(s):** 14

**Device model(s):** Pixel 7 and pixel watch

**Home Assistant version:** 2023.11.1

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

**Additional information:**
My phone pushes the event fine but my watch does not.
Specific event: `mobile_app_notification_cleared`

**Comment by dshokouhi** [comment]
This actually is not a bug but we can treat it like a feature request. Currently Wear OS has limited notification support. Make sure to check the docs for current supported functionality

https://companion.home-assistant.io/docs/wear-os/#notifications

**Comment by JosephAbbey** [comment]
Ah, sorry, I only looked in the core docs. If it is not currently possible then that's ok. Thanks.

**Comment by dshokouhi** [comment]
We can keep this request open actually :) I was just saying its not a bug but a feature request
