### ISSUE TITLE
Problem with Quest 3 sensors

### ISSUE THREAD

**Issue by CoreyJ87** [home-assistant/android#4005]
Hi everyone. I made this post a couple weeks ago. https://github.com/home-assistant/android/issues/3964
I was able to get it installed and working. Although, the sensors never showed up. Im missing all but the ones related to charging. I did do an update recently @dshokouhi. Still the sensors did not show up. Im on the newest HAOS version of HASS and the newest version of the app from sidequest. 

 Heres the pics of the ones that are showing and not showing. 

<img width="1139" alt="Screenshot 2023-11-06 at 1 54 58 PM" src="https://github.com/home-assistant/android/assets/247750/8fe4a60a-3612-424d-81e4-cbb54405ac39">
<img width="535" alt="Screenshot 2023-11-06 at 1 55 12 PM" src="https://github.com/home-assistant/android/assets/247750/84e0a770-6561-4ed9-9cf3-ffe5d252d029">
<img width="448" alt="Screenshot 2023-11-06 at 1 55 20 PM" src="https://github.com/home-assistant/android/assets/247750/e33e8621-dbba-4b67-bd61-08c4c24b710e">

Any idaes? thanks

**Comment by dshokouhi** [comment]
if you open the app on the Quest 3 and navigate to Settings > Companion App > Manage Sensors do you see them enabled there?

**Comment by dshokouhi** [comment]
also please restore teh issue template and fill it out completely please. All the info is required to help you out.

**Comment by CoreyJ87** [comment]
Let me check and will do. Sorry

**Comment by CoreyJ87** [comment]
Whelp. Im an idiot. I did not realize you had to turn on all those sensors. That was the problem. Thanks so much.
