### ISSUE TITLE
"Cannot connect" pop-up doesn't trigger if app configured to connect to HSTS domain name over http://

### ISSUE THREAD

**Issue by LinAGKar** [home-assistant/android#4010]
**Home Assistant Android app version(s):** 2023.10.2

**Android version(s):** 13.1

**Device model(s):** Oneplus 8T

**Home Assistant version:** 2023.10.5

**Last working Home Assistant release (if known):** N/A

**Description of problem, include YAML if issue is related to notifications:** 

I recently updated the server address in the app. It's still able to access the server perfectly fine (I can still control stuff via widgets), however if I try to open the app, it just and opens `https://<server_host>/?external_auth=1` in a web browser, even though it's configured to connect over HTTP (does Home Assistant use HSTS preload?). If I correct the address to http://, it just shows a 60 s countdown. The app remains completely blank, which makes it impossible to access there server settings and change it back.

**Companion App Logs:** Inaccessible

```

```

**Screenshot or video of problem:** 

**Additional information:**

**Comment by dshokouhi** [comment]
Sounds like something may have been corrupted, can you try the start fresh steps to rule out bad data please?

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app



> I recently updated the server address in the app. It's still able to access the server perfectly fine (I can still control stuff via widgets), however if I try to open the app, it just and opens `https://<server_host>/?external_auth=1` in a web browser, even though it's configured to connect over HTTP (does Home Assistant use HSTS preload).

Teh app only loads the browser when it detects the URL the app has does not match the URL the WebView was redirected to. If this behavior persists check your networking setup.



> If I correct the address to http://, it just shows a 60 s countdown. The app remains completely blank, which makes it impossible to access there server settings and change it back.

The HA frontend is actually displaying this message and its not coming from the app, if after 10 seconds the cannot connect pop-up does not show up that is because the app was notified by the frontend that it had connected.

Given the strangeness of both issues I think a start fresh may help clear somethings up here.

**Comment by LinAGKar** [comment]
>Teh app only loads the browser when it detects the URL the app has does not match the URL the WebView was redirected to.

Presumably that webview uses HSTS then, causing the mismatch.

If I try to setup with fresh (tried it in a different user Profile) with the server address I changed to, it says SSL handshake failed, even though I entered http://, so I guess there is a webview with HSTS there too.

>The HA frontend is actually displaying this message and its not coming from the app

That's not in the app, it's in the web browser.

It's not corruption, I know what setting to change, the problem is that the app doesn't let you access the companion app settings if it can't connect to the server.

**Comment by dshokouhi** [comment]
> Presumably that webview uses HSTS then, causing the mismatch.

we use the standard WebView updatable via the Google Play Store, the same one every app on your device uses



> If I try to setup with fresh (tried it in a different user Profile) with the server address I changed to, it says SSL handshake failed, even though I entered http://, so I guess there is a webview with HSTS there too.

whats your networking setup like that? Redirects like that sound like something on possibly a proxy or DNS end? I am able to connect to local dev servers on http just fine without being redirected to https and getting a handshake error.





> the problem is that the app doesn't let you access the companion app settings if it can't connect to the server, so you can't change how it connects to the server.

The app only shows the cannot connect pop-up with access to settings if either the HA frontend threw an error or the frontend did not respond in 10 seconds. If you don't see a pop-up none of those conditions were met. Turn on airplane mode and open the app again to trigger the pop-up to edit settings. From the sound of things I'd say some things are able to connect while others are not which is not normal but also evidenced by the fact that widgets work. The companion app makes use of all HA API's so make sure you are not blocking any of them.

**Comment by LinAGKar** [comment]
The address I have it configured to now is in the HSTS preload list. That I guess causes the WebView to immediately redirect to https (even in airplane mode), which then causes the WebView URL to no longer match the configured server URL, which you mentioned makes it open the browser. That then means it doesn't hit wither of the conditions that trigger the "cannot connect pop-up".

**Comment by dshokouhi** [comment]
I am not sure if this is something the app will be able to solve

**Comment by dshokouhi** [comment]
Looking at this stackoverflow post and the suggestion I am not sure this will work for majority of users.

https://stackoverflow.com/questions/37379933/does-androids-webview-support-hsts

According to the fix we need to modify our Network security config to enforce HSTS?

https://koz.io/network-security-policy-configuration-for-android-apps/#hsts-enforcement

However I dont think we can blindly turn this on as it will probably cause issues with lots of other setups

https://github.com/home-assistant/android/blob/master/app/src/main/res/xml/network_security_config.xml

I am not even sure if this is the right fix, as you can see this file needs to be kept as generic as possible to support a wide range of setups.

i know we can do domain specific overrides however if that is really required then that might mean this is something to be done in a fork?

**Comment by jpelgrom** [comment]
@dshokouhi It sounds like the 'issue' is that the webview _is_ enforcing HSTS, as it redirects automatically to https even though http is entered.

**Comment by jpelgrom** [comment]
@LinAGKar What you are asking for effectively sounds like a way to bypass HSTS in the app so you can navigate to the settings - in that case, why did you configure it?! I'm afraid this is a case of know what you're doing, unless you have configured multiple servers there isn't a way to get the app settings before it loads the web UI. (If you have configured multiple servers, send a notification from another server and open the app that way.)

**Comment by LinAGKar** [comment]
>in that case, why did you configure it

Yeah, that was my mistake, I did not consider HSTS when setting the domain. I've since reset the app, but it would be nice if such a situation was more easily recoverable.

I'm guessing you would end up in a similar state if you actually have the server listening on https and redirect to that (either with HSTS preload or with an HTTP redirect on the server), and accidentally enter the server address with http://.

>What you are asking for effectively sounds like a way to bypass HSTS in the app so you can navigate to the settings

Not necessarily, it would eventually realize that it can't access the server and show the pop-up, but it's prevented from getting the that point by opening the browser because. the URL mismatch check @dshokouhi mentioned.  Is it the check at https://github.com/home-assistant/android/blob/dfc30d535757098abef6643f688552109c020a2c/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L463C29-L463C29 that's referred to? Could that be altered so it does not trigger when `webView.url` differs from `it` by the scheme, so it won't open the browser if the server has an http->https redirect.

```java
if (!(webView.url.toString().contains(it.toString()) || webView.url.toString().replaceAll("^https:", "http:").contains(it.toString())) {
```

I just realized that the pop-up does show up if you then return the app and wait for ten seconds, so I guess I was just too impatient (though there was also no indication that the app was doing anything when returning to it).

**Comment by dshokouhi** [comment]
> https://github.com/home-assistant/android/blob/dfc30d535757098abef6643f688552109c020a2c/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L463C29-L463C29 that's referred to? Could that be altered so it does not trigger when `webView.url` differs from `it` by the scheme, so it won't open the browser if the server has an http->https redirect.

we should not alter existing logic that has worked well for many users for a long time. We also need to be mindful of mixed content that also won't play well.



> I just realized after writing the above that the pop-up does show up if you then return the app and wait for ten seconds, so I guess I was just too impatient. Though there was also no indication that the app was doing anything when returning to it, a loading spinner would be nice.

We don't need a spinner animation as we are loading the site and users just need 10 seconds of patience. Its not like your browser shows a spinning animation loading a site.

Given that the pop-up shows up as expected and the app was misconfigured I am going to close this issue now.

**Comment by LinAGKar** [comment]
>Its not like your browser shows a spinning animation loading a site

Yes, it definitely does.

>users just need 10 seconds of patience

No, they don't just need patience, they need to be aware that they need to wait. 10 seconds is a humongous amount of time for loading an app or a website.

**Comment by dshokouhi** [comment]
> 10 seconds is a humongous amount of time for loading an app or a website.

it used to be 5 seconds but some slower setups noticed that they would see the pop-up and immediately it would dismiss so we decided to up it to 10 seconds to avoid that issue.
