### ISSUE TITLE
Location unknown

### ISSUE THREAD

**Issue by Mikescotland** [home-assistant/android#4014]
**Home Assistant Android app version(s):**
2023.11 full
**Android version(s):** 
12
**Device model(s):**
Huawei mate 20x 5g
**Home Assistant version:**
2023.11.2
**Last working Home Assistant release (if known):**
2023.11.2
**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**
After automatic Google Play update, person entity loses tracking device. You need to go to the user settings in HA and chose once again

**Comment by dshokouhi** [comment]
> After automatic Google Play update, person entity loses tracking device. You need to go to the user settings in HA and chose once again

Are you saying the device tracker entity is completely gone? I am not sure what you are referring to here.

**Comment by Mikescotland** [comment]
> > After automatic Google Play update, person entity loses tracking device. You need to go to the user settings in HA and chose once again
> 
> Are you saying the device tracker entity is completely gone? I am not sure what you are referring to here.

No.
I'm saying that home assistant instance looses the chosen entry, resulting with "unknown" location. You have to go to Users > [name] and choose again the tracking device. It's empty, blank, like for a moment during update companion app deletes / refreshes (don't know how to name it).
Device is still there, but not chosen as tracking device.

**Comment by dshokouhi** [comment]
thats very strange, please follow all of our start fresh steps and let us know if the issue persists

https://companion.home-assistant.io/docs/troubleshooting/faqs#starting-fresh-with-the-android-app

we need to make sure the device registration is not corrupted.

**Comment by dshokouhi** [comment]
Closing due to lack of response from author
