### ISSUE TITLE
Add Vietnamese translation to Lokalise

### ISSUE THREAD

**Issue by vinhtantran** [home-assistant/android#4021]
**Is your feature request related to a problem? Please describe.**
Front end and Core both have Vietnamese translations on Lokalise for localization. iOS companion app is there, but not Android.

**Describe the solution you'd like**
Add Vietnamese language as a project in Lokalise for contribution.

**Describe alternatives you've considered, if any**
None

**Additional context**
None

**Comment by dshokouhi** [comment]
@vinhtantran  I have added the vietnamese language however I am not able to find your user to assign the language to you. Let me know what username you are under so I can add the language for you.

**Comment by vinhtantran** [comment]
> @vinhtantran I have added the vietnamese language however I am not able to find your user to assign the language to you. Let me know what username you are under so I can add the language for you.

Hello. My lokalise account is my email address. That's the username here at Gmail dot com. Thank you very much.

**Comment by dshokouhi** [comment]
added for your account, no problem :)
