### ISSUE TITLE
Duplicate toggles when enabling companion app sensors

### ISSUE THREAD

**Issue by ianmtaylor1** [home-assistant/android#4028]
**Home Assistant Android app version(s):**

2023.10.2-full

**Android version(s):**

14 (Security update November 5, 2023)

**Device model(s):**

Google Pixel 5

**Home Assistant version:**

* Home Assistant OS 11.1
* Home Assistant Core 2023.11.3
* Home Assistant Supervisor 2023.11.3
* Frontend 20231030.2

**Last working Home Assistant release (if known):**

Unknown

**Description of problem, include YAML if issue is related to notifications:**

Multiple duplicate toggles appear when enabling phone sensors in Settings > Companion App > Manage Sensors. (See screenshot for sleep confidence, for example.)

**Companion App Logs:**

(Can post if requested. I don't want to potentially share location info. I am happy to filter the logs for keywords.)

**Screenshot or video of problem:**

![Screenshot_20231122-200900](https://github.com/home-assistant/android/assets/2293284/2e86c650-e6b1-48c9-8281-ca11d7be2d20)

**Additional information:**

Steps to replicate:

1. In fresh install of app, log into home assistant server.
2. Go to Settings > Companion App > Manage Sensors > (pick a sensor)
3. Click to enable. Notice only one toggle.
4. Log out from server.
5. Log into server again.
6. Go to Settings > Companion App > Manage Sensors > (pick a sensor)
7. Click to enable. Notice one toggle labeled with your server name and duplicate toggles.
8. One duplicate will be added each time you log out and back in.

**Comment by jpelgrom** [comment]
Thanks for the detailed report! The additional toggles are harmless, but it is supposed to clean them up on logout.

When logging out, do you use the "log out" button on the profile page or the "delete server" button in the app settings? If you only used one of the buttons: does the issue also happen for you when using the other?

**Comment by ianmtaylor1** [comment]
Thanks for your reply. I used the log out button on the profile page. When I used the delete server button just now, it did not create a duplicate. However, I also can't seem to recreate the problem using the log out button anymore either, when yesterday following the steps I listed created duplicate toggles.
