### ISSUE TITLE
Stop updating dashboard after hours or days

### ISSUE THREAD

**Issue by xuefer** [home-assistant/android#4037]
**Home Assistant Android app version(s):**
2023.10.4-minimal (can't do latest version since every time i upgrade it take some time and luck to reproduce)

**Android version(s):**
5.1.1

**Device model(s):**
AD500A

**Home Assistant version:**
Home Assistant 2023.10.5
Chrome  95.0.46.38.74 (the latest version to support Android 5.1.1)
Android System Webview  95.0.46.38.74 (ditto)

**Last working Home Assistant release (if known):**
Unknown

**Description of problem, include YAML if issue is related to notifications:**

Simply stop updating dashboard sensor states until reloaded. I would suggest it to ping/pong and discover timeout actively instead of relying on system tcp timeout

**Companion App Logs:**

```
```
(Can't get one for now, when i realize it happen again, the logcat history got flushed by other log content

**Screenshot or video of problem:**

**Additional information:**
Not happening on another device running on new version of android/chrome/webview, connected with same home assistant server

**Comment by dshokouhi** [comment]
> Android System Webview 95.0.46.38.74 (ditto)

this is very old and needs to be updated, if it cannot be updated then we may not be able to fix the issue as we depend on the WebView for the frontend.

**Comment by dshokouhi** [comment]
> Not happening on another device running on new version of android/chrome/webview, connected with same home assistant server

yea this further suggests this is not an issue the app can solve as if you cannot update WebView nothing we can do. You may try your luck with the HA frontend but it may be a compatibility issue. 

Hopefully not if that is the case then we may need to change our min SDK as WebView is important to update.

**Comment by xuefer** [comment]
> > Android System Webview 95.0.46.38.74 (ditto)
> 
> this is very old and needs to be updated, if it cannot be updated then we may not be able to fix the issue as we depend on the WebView for the frontend.

I understand, but version is limited by android os version. it's impossible to install newer version of webview

Is communication timeout check done actively by app/frontend side?

**Comment by dshokouhi** [comment]
> Is communication timeout check done actively by app/frontend side?

the app relies on the HA frontend to tell us if its disconnected....all that logic is handled by the frontend the app just displays the dashboard

are you able to reproduce the issue using chrome for android on the same device?

Looking at: https://en.wikipedia.org/wiki/Template:Google_Chrome_release_compatibility you are correct that your version of WebView cannot be updated beyond 95

![image](https://github.com/home-assistant/android/assets/1634145/fd7e6204-c593-4b96-983a-ec86e4672e39)

According to [HA docs](https://www.home-assistant.io/docs/frontend/browsers/#android) your version should still be supported so this might be a HA frontend issue.

**Comment by xuefer** [comment]
> > Is communication timeout check done actively by app/frontend side?
> 
> the app relies on the HA frontend to tell us if its disconnected....all that logic is handled by the frontend the app just displays the dashboard
Good tips

> 
> are you able to reproduce the issue using chrome for android on the same device?
I'll keep it open on chrome for some days and see if it reproduce. Will open a new bug report if it's frontend issue

> According to [HA docs](https://www.home-assistant.io/docs/frontend/browsers/#android) your version should still be supported so this might be a HA frontend issue.

**Comment by xuefer** [comment]
reproduced in chrome, reporting to frontend, found https://github.com/home-assistant/frontend/issues/17409 (which meantion https://github.com/home-assistant/frontend/compare/dev...leonardmgh:homeass-frontend:fix-halfopen-websocket )
closing this one
