### ISSUE TITLE
Can not connect with self-signed certificatae

### ISSUE THREAD

**Issue by zi4k4j74yn** [home-assistant/android#4041]
**Home Assistant Android app version(s):**
2023.10.2

**Android version(s):**
11

**Home Assistant version:**
2023.12

**Last working Home Assistant release (if known):**
none

**Description of problem, include YAML if issue is related to notifications:**
I am using a self-signed certificate. I can connect via the browser, but not via the app. The error message is:

> The Home Assistant Certificate authority is not trusted, please review the Home Assistant certificate or the connection settings and try again.

I have added the self signed cert.pem file to Android as described in https://companion.home-assistant.io/docs/troubleshooting/faqs/#using-a-self-signed-certificate-leads-to-a-blank-page-in-android. In addition, I have added the certificate not only as a wifi certificate as described here (https://support.google.com/pixelphone/answer/2844832?hl=en&visit_id=638376149107289420-2882375700&rd=1), but also as a user CA certificate.

**Companion App Logs:**

```
12-08 07:32:41.257  5026 12863 I cr_X509Util: Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
12-08 07:32:41.259  5026 12864 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -202
12-08 07:32:41.279  5026  5026 E AuthenticationFragment: onReceivedSslError: primary error: 3 certificate: Issued to: CN=SelfSigned;
12-08 07:32:41.279  5026  5026 E AuthenticationFragment: Issued by: CN=SelfSigned;
12-08 07:32:41.279  5026  5026 E AuthenticationFragment:  on URL: https://192.168.1.2:8123/auth/authorize?response_type=code&client_id=https://home-assistant.io/android&redirect_uri=homeassistant://auth-callback

```

**Comment by dshokouhi** [comment]
So the app does indeed accept user imported CA.  I think you may be hitting this issue, try to double check how you imported the CA. The app cannot receive an error message, we can't fix those.

https://developer.android.com/privacy-and-security/security-ssl#SelfSigned

**Comment by dshokouhi** [comment]
We will not be bypassing Android certification check.

**Comment by zi4k4j74yn** [comment]
Is there anything I can do on the user's side or does this effectively mean self-signed certificates cannot be used?

**Comment by dshokouhi** [comment]
Self signed certificates can indeed be used and are supported given they are imported properly so they can be recognized and error free. The error you posted suggested you didn't import it correctly.

May also be helpful to understand what device this is as it was left out in the issue template.

**Comment by dshokouhi** [comment]
interesting, if you find anything in addition to add to our troubleshooting section please submit a PR to update it to help the next person :)
