### ISSUE TITLE
Pixel Watch 2 first shortcuts tile not showing up

### ISSUE THREAD

**Issue by endyb66** [home-assistant/android#4042]
**Home Assistant Android app version(s):**
Phone: 2023.10.2-full 
WearOS: 2023.10.2-11484

**Android version(s):**
Phone: 14
WearOS: 13

**Device model(s):**
Phone: Google Pixel 8
WearOS: Google Pixel Watch 2

**Home Assistant version:**
2023.12.1

**Last working Home Assistant release (if known):**
-

**Description of problem, include YAML if issue is related to notifications:**
On my Google Pixel Watch 2 only the objects added to the second shortcuts tile do show up on the Home Assistant view on the watch. All objects (entitities, scripts etc.) added to the first shortcuts tile do not show up. Either I just missunderstand something (maybe how to switch between shortcuts tile #1 and shortcuts tile #2) or this may be a bug.

**Comment by dshokouhi** [comment]
Please do not skip the issue template all of it is required to help you out. Please add back the template and fill it out completely.

**Comment by dshokouhi** [comment]
@endyb66 we still need more information from this. Please attach logs and screenshots of the tile itself and the app settings show the tile should have data.  Also have you tried removing the tile and adding it back to see if that resolves the issue?
