### ISSUE TITLE
"You need to use the Home Assistant Companion app on your mobile phone to commission Matter devices"

### ISSUE THREAD

**Issue by davidebeatrici** [home-assistant/android#4043]
**Home Assistant Android app version(s):** `2023.10.2-minimal` (F-Droid)

**Android version(s):** `14`

**Home Assistant version:** `2023.12.1`

**Screenshot or video of problem:**

<details>
<summary>Screenshot</summary>

![Home Assistant Companion app](https://github.com/home-assistant/android/assets/5897523/1aa45f29-e678-4bd7-aef1-a9b6d0e7ff9d)
</details>

**Additional information:**

- I would like to "commission" a custom ESP32 board that is running Tasmota. Reference: https://tasmota.github.io/docs/Matter
- I have no Google apps/services installed.

Related: https://community.home-assistant.io/t/how-could-i-commission-a-matter-device-to-home-assistant-without-google/648272

**Comment by jpelgrom** [comment]
Specifically, you need the full version of the app with Play Services to commission devices, at least for now. This is mentioned more specifically in [the documentation](https://www.home-assistant.io/integrations/matter/#i-do-not-see-the-button-commission-using-the-companion-app).

**Comment by davidebeatrici** [comment]
Is the limitation there because the app currently relies on a Google API in order to connect to the Matter device?

**Comment by jpelgrom** [comment]
Correct, commissioning currently uses Apple's and Google's APIs to transfer WiFi/Thread credentials and connect devices to a fabric.

**Comment by dshokouhi** [comment]
Closing as this is not something we can fix

**Comment by davidebeatrici** [comment]
Wouldn't it be feasible to connect the Matter device directly to Home Assistant, considering the protocol is open-source?

**Comment by jpelgrom** [comment]
Technically possible, yes, but this choice was made at the time due to limited time and resources in the community and ease of use. Open for discussion later but as it involves a significant core investment as well that should take place on the forums :)

**Comment by davidebeatrici** [comment]
Makes sense.

**Comment by ouinouin** [comment]
Seems like matter is not the freedom that everybody expected, relying on some keying from the great internet is not a sign of a protocol that will improve our freedom and ease of use. moreover the esp32 things matter certified are no more reflashable. more e waste to come...

**Comment by davidebeatrici** [comment]
I strongly agree.

About flash-locked devices: a notable example is the [SONOFF MINIR4M](https://templates.blakadder.com/unsupported/sonoff_MINIR4M.html), which only adds Matter "support" compared to the [MINIR4](https://templates.blakadder.com/sonoff_MINIR4.html).

> Despite using a compatible ESP32-C3 Sonoff has locked the chip to prevent serial flashing of new firmware due to Matter certification requirements.

**Comment by shayanz23** [comment]
we need play services to use matter? then what about matter is open specifically? I'm switching back to zigbee over this scam.

**Comment by Hollywood777** [comment]
Just ran into the same problem: have everything Google-free: Linux on Computer, LineageOS on phone and Home-Assistant as Smart-Home-Platform. Now matter integration is needed, since many device providers unfortunately switch from ZigBee to Matter. Now the trouble starts: I need a "googelized" phone in order to register a Matter device to HA - isn't this
against the whole philosophy of HA?
