### ISSUE TITLE
Missing in translation - reconnect

### ISSUE THREAD

**Issue by misa1515** [home-assistant/android#4050]
**Home Assistant Android app version(s):**
2023.11.2

**Android version(s):**
not relevant

**Device model(s):**
not relevant

**Home Assistant version:**
2023.12.2

**Last working Home Assistant release (if known):**
not relevant

**Description of problem, include YAML if issue is related to notifications:**
Missing word in translation (please see attached screenshot)

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![1702505311180](https://github.com/home-assistant/android/assets/61636045/4e444777-c81c-4f77-92d0-1279eea55111)

**Additional information:**
Please add missing words to lokalise

**Comment by jpelgrom** [comment]
Hi 👋

Your screenshot is from the frontend, so [please open an issue there](https://github.com/home-assistant/frontend/issues/new/choose). Based on a quick search, it looks like they are [hardcoded to English](https://github.com/home-assistant/frontend/blob/1dc61320a61716213922826a1002e9b6443266ab/src/layouts/ha-init-page.ts#L18) so good find!
