### ISSUE TITLE
Would a "minimal" version with built-in Webview be possible?

### ISSUE THREAD

**Issue by spudje** [home-assistant/android#4057]
The companion app is used on many (dashboard) devices. Some of them don't have the google services (hence the minimal version of the app) and some even are very locked down and don't allow for updating webview, e.g. Lenovo Smart Clock 2.

Since more and more GUI components (HACS addons) start to break on older webview versions, I was wondering whether we could come up with a solution for that.

**Describe alternatives you've considered, if any**

Is it possible to build a "minimal" Android companion app that also includes its own (up to date) webview, so it no longer depends on the webview of the device on which the app is running?

**Additional context**

I was a bit frustrated when my Clock dashboard totally broke down after updating card-mod, and started this discussion. You'll find some background there: https://community.home-assistant.io/t/please-stop-forcing-us-to-buy-brand-new-dashboard-hardware-and-make-gui-stuff-work-on-older-webview-again/655827

**Comment by dshokouhi** [comment]
No WebView needs to be a system wide installed app updatable via the play store
