### ISSUE TITLE
Password problem.

### ISSUE THREAD

**Issue by nickbrothwell** [home-assistant/android#4061]
**Home Assistant Android app version(s):**

**Android version(s):**

**Device model(s):**

**Home Assistant version:**
    Green
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Can't log in to my account. I know I'm putting in correct details because I used same last night. I just need password reset but this seems to be impossible

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
We cannot help with such little data provided, please fill out the issue template completely and share a screenshot of your issue.

**Comment by nickbrothwell** [comment]
![Screenshot_20231218_183525_Firefox](https://github.com/home-assistant/android/assets/154108058/c12d13bc-92a2-45c8-931b-a31189301e89)

**Comment by nickbrothwell** [comment]
![Screenshot_20231218_183739_Firefox](https://github.com/home-assistant/android/assets/154108058/8de9c6f1-fef9-472e-a3c7-c1d46173d23a)

**Comment by nickbrothwell** [comment]
Just can't get access to anything. I added Hacs last night. Nothing else. Wondering what I've done wrong?

**Comment by dshokouhi** [comment]
I dont think I have ever seen an email address as a user name like that, are you sure thats teh actual user name?

**Comment by nickbrothwell** [comment]
Would it normally be my name? Been trying that too and still no luck. What would the prompt be. Sorry I've never had to sign in before last night

**Comment by dshokouhi** [comment]
> Would it normally be my name? Been trying that too and still no luck. What would the prompt be. Sorry I've never had to sign in before last night

that all depends on what you used when you onboarded, sounds like you may need to reference the locked out docs.

https://www.home-assistant.io/docs/locked_out/

the same login for a browser will indeed work in the app

**Comment by nickbrothwell** [comment]
I have been thru all those docs. They lead me to a full reinstall of OS. Seems drastic. It looks like the box is still running fine but I just can't reach it. Already feeling like I want to bin it!

**Comment by dshokouhi** [comment]
are you still logged in on the browser somewhere? If so you should be able to check

Settings > People > Users

will show your actual user name

**Comment by nickbrothwell** [comment]
So I deleted and reinstalled app and now this is where I am
![20231218_193225](https://github.com/home-assistant/android/assets/154108058/00e57d70-0d39-499f-a148-7d7c2bc4c3d0)

**Comment by dshokouhi** [comment]
use the IP address, seems like your local network is not resolving the hostname there properly

**Comment by nickbrothwell** [comment]
I tried googling jow to find that. How would I enter that. Sorry I really know nothing about this stuff. https://168.xxxxxx I think? I'm trying here really sorry

**Comment by jpelgrom** [comment]
Based on your previous screenshot, the IP address/URL you should enter is `http://192.168.0.44:8123`

**Comment by nickbrothwell** [comment]
![20231218_194707](https://github.com/home-assistant/android/assets/154108058/2a179b2e-1c78-4599-a29d-1c2fd534af0d)
You're being very patient. I shall give up shortly

**Comment by nickbrothwell** [comment]
Sorry helps if you do it right. Just puts me back to login page and I'm back to the beginning again. It won't let me in. Like my login just got deleted

**Comment by jpelgrom** [comment]
Looks like you entered `https`, that should be `http` :) The app won't magically work if the browser login doesn't work though. I'm afraid at this point you'll have to follow the locked out instructions that were previously linked, even if that means a full reinstall.

**Comment by nickbrothwell** [comment]
Ya I realised after. I was just hoping I could avoid full reinstall. Shame

**Comment by dshokouhi** [comment]
Closing as this is not an app issue
