### ISSUE TITLE
Next Alarm returns an incorrect value

### ISSUE THREAD

**Issue by info-path** [home-assistant/android#4063]
**Home Assistant Android app version(s):**
2023.10.2-full

**Android version(s):**
14

**Device model(s):**
Samsung Galaxy S22

**Home Assistant version:**
2023.12.3

**Last working Home Assistant release (if known):**
Don't remember - Last year maybe with my old phone Samsung S10e, but it worked at the time :)

**Description of problem, include YAML if issue is related to notifications:**
Unable set / unset Next Alarm sensor. 

**Issue**: If I set the alarm to `7:20`, this sensor shows a strange time of one minute less `2023-12-19T06:19:43+00:00`. The seconds shown always correspond to the second of the actual time I set the alarm. So with each repeated setting, the seconds change. Expected value: `2023-12-19T06:20:00+00:00`.

If I deactivate the alarm, the sensor value does not change, it remains at the alarm setting. Expected value: `unknown`.

**Note**: I use the Samsung Clock app to set the alarm. Before this test, I removed all data and cache from the app and restarted the phone.

**Companion App Logs:**

```
12-18 22:44:42.763 12309 12503 D NextAlarm: Next alarm is scheduled by com.sec.android.app.clockpackage with trigger time 1702966783100
```

**Screenshot or video of problem:**

<img width="850" alt="pnone-next-alarm" src="https://github.com/home-assistant/android/assets/18407314/53da1170-fa7b-4d70-bb4d-b4547d7c846d">

<img width="250" alt="samsung-companion" src="https://github.com/home-assistant/android/assets/18407314/3b27ed51-80de-4840-b298-347ee7b6f4e5">
<img width="250" alt="samsung-alarm" src="https://github.com/home-assistant/android/assets/18407314/977f8b75-2c05-47ee-99d6-7a77a58e2050">

**Comment by dshokouhi** [comment]
this is a known issue with Samsung apps as they set their own time for the API, the only fix is ot use another app like Google Clock or Sleep as Android. Lots of closed issues on this one too

**Comment by info-path** [comment]
Thanks for the immediate reply! So, I've tried Google Clock and it looks like the clock settings are working correctly, thanks for the tip! 

I have a different problem though. If I cancel the alarm (all alarms are off), it shows a strange value `2023-12-19T08:30:00+00:00` (Package:` com.android.providers.calendar`), but I'm not sure I have something set somewhere. I don't have any alarm in the Samsung app, and I don't know of anything in the calendar. I restarted the phone, the problem persists. Any tips?

**Comment by dshokouhi** [comment]
that is again a Samsung specific issue, the calendar entries in their app set an alarm as well you will need to remove those. The Google Calendar app does not have this behavior. This sensor is at the mercy of others apps who can and will set alarms as they need to. The best that can be to avoid other alarms is to use the allow list and dictate the apps you want updates from.

One thing to keep in mind is that API only returns the next scheduled alarm, think as time in a linear format here where only 1 app can be provided at a time. The allow list will simply skip those updates so the data retrieved may still not be as expected.

**Comment by info-path** [comment]
oh, so the problem is Samsung. That's not good news.

I'm playing around with Google Clock right now and I set the Allow List in the Companion App like this:

**Sensor settings >> Allow list >> Clock (com.google.android.deskclock)**

Now it works, but only if I set the alarm lower than the previous one. If I lower the alarm by e.g. 1 hour, the sensor value will change and display correctly. But if I set the alarm for later, e.g. add an extra hour, the value doesn't change.

**Comment by dshokouhi** [comment]
Let me quote myself one more time here, its not issues iwth the google app its quite simply you ahve other apps setting alarms, the allow list only skips updates, that does not mean updates are still there.

> One thing to keep in mind is that API only returns the **next** scheduled alarm, think as time in a linear format here where only 1 app can be provided at a time. 

So say for example you have allow list configured for App A however App B sets an alarm every 30 seconds that you are ignoring. This means that you will only have a 30 second window of when your alarm time will be sent as the other app has earlier alarms that you are ignoring. This means data may seem stuck as a result. Your options are to either remove all offending apps and entries they have set or dont use an allow list and use the package name as a condition for the automation. You will not see the google clock app jumping times when package returns for it.

All this will vary from user to user and device to device because a lot of htis is out of hte apps control. We just provide as much data as possible to the user so they can work around what they need to here.

You can also look at the Companion app logs to see when things are skipped or not.

**Comment by info-path** [comment]
thanks for trying to clear that up. I confess I don't really understand it, I thought that the Allow list on the Next Alarm sensor works by reading this information only from the selected specific application. 

If that's not how it works, there's not much I can do about it. Especially if the alarm is affecting other apps, even though I haven't enabled them.

I don't use the default Samsung apps (except for the clock, but I've abandoned those now on your recommendation). They can't be uninstalled and if they block my alarm settings, there's nothing to solve. 

Although the Next Alarm sensor used to work reliably, I have to accept that I will no longer use it. Thanks for your help.
