### ISSUE TITLE
Wear OS entity state complications - option to select complication type SHORT_TEXT

### ISSUE THREAD

**Issue by alexhk90** [home-assistant/android#4070]
**Is your feature request related to a problem? Please describe.**

Previously, entity state complications showed in small icons (presumably as `SHORT_TEXT`); for example (complication at the top of the watch face is an HA entity state):
![image](https://github.com/home-assistant/android/assets/13845698/63f8c2e7-3e53-455d-9a31-57ec51f5d471)

However, in more recent versions (last few months), the same entity complication now appears in a long icon (presumably as `LONG_TEXT`); for example (complication at the top of the watch face is the same HA entity state as the one above): 
![image](https://github.com/home-assistant/android/assets/13845698/b17e6fb4-5c4a-4280-b2d6-5dadc7f5f786)

Looking at the recent code changes, this appears to be the relevant change: 
https://github.com/home-assistant/android/pull/3465

While `LONG_TEXT` is probably the better default as it allows more content/data to be displayed, ideally the user should be able to choose which size they want to use for each complication. 

**Describe the solution you'd like**

The user should have an option to specify the complication type, i.e. to explicitly select between `LONG_TEXT` and `SHORT_TEXT` (and perhaps ultimately [other types](https://developer.android.com/training/wearables/watch-faces/adding-complications#types-fields) such as `RANGED_VALUE` as already suggested in https://github.com/home-assistant/android/issues/3091). Ideally this would be another configurable option when selecting the entity state complication, i.e. under "Choose entity", "Show entity name" and "Show entity unit".  

**Describe alternatives you've considered, if any**

Change the default complication type back to `SHORT_TEXT`, i.e. revert the change here: 
https://github.com/home-assistant/android/pull/3465/files#diff-5067b07fe10432aabf32417bce0fa4391680fb8d851d8cb98339bf7d69c657d2
However, this would be considered a regression by any users who are now taking advantage of `LONG_TEXT` being the new default complication type. 

**Additional context**

As noted in the current documentation: 
https://companion.home-assistant.io/docs/wear-os/#complications
> Depending on the watchface, the complication may also show the entity name and icon, and supports 'short text' and 'long text' complication types.

This feature request is to allow the user to select between the 'short text' and 'long text' complication types, instead of deferring the decision to the watchface.

**Comment by dshokouhi** [comment]
Actually the app is telling the watchface what complication type are supported and the watchface picks the default. The default is not controlled all the app is doing is relaying what complication types are supported. Those types are actually entered into the manifest so I am not sure we will have control over this. Ultimately the watchface should give the user the choice here I think.

https://github.com/home-assistant/android/blob/master/wear/src/main/AndroidManifest.xml#L216

**Comment by alexhk90** [comment]
Interesting; thanks. I don't see any obvious way of specifying this when selecting the HA "Entity state" complication from the watchface. Though I've only used one watchface so perhaps other watchfaces do allow the user to explicitly specify the complication type, in which case this may actually be a feature request for the watchface rather than for HA. 

It would be slightly clunky, but perhaps HA could expose separate "Entity state (long text)" and "Entity state (short text)" complications which would tell the watchface they only supported `LONG_TEXT` and `SHORT_TEXT` respectively?

**Comment by dshokouhi** [comment]
Personally speaking its going to be very hard to convey this to the user in the complication selection screen. I don't think we should accept this request as its the watchfaces responsibility to show the complication to the user in what it sees is the best fit. No other app allows users to select the complication type, ultimately its up to the watchface in how much control it wants to give to the user.

**Comment by dshokouhi** [comment]
Closing as this should be handled by the watchface.
