### ISSUE TITLE
Nabu Casa Disconnected from Companion App - will not reconnect

### ISSUE THREAD

**Issue by dwdonnelly** [home-assistant/android#4071]
Can Not Reconnect to Nabu Casa.

First noticed Companion App disconnected when Presence Sense stopped working about 1 week ago.  Presence Sense has been working flawlessly for about 10 months.

Companion App shows connected:
![image](https://github.com/home-assistant/android/assets/42418057/a28f9720-17a7-4657-b8e3-0e2d12d4e450)

Nabu Casa's website shows not connected:

![image](https://github.com/home-assistant/android/assets/42418057/eddcc4a5-7ce6-48c4-8f6c-8a93f4f0b71e)

Have followed guidance to toggle the remote control to reengage Nabu Casa - did not work.

![image](https://github.com/home-assistant/android/assets/42418057/c8b2dea0-4251-47a0-b860-88203430a036)

Researched in other posts in the Home Assistant Community there might be an issue with the renewal of the account.  My account renews in 30-ish days.

your assistance in this suse.

**Android version(s):**
One UI 5.1
Android Ver 13

**Device model(s):**
Samsung Note 20 Ultra

**Home Assistant version:**
Core: 2023.12.3
Supervisor: 2023.12.0
Operating System: 11.2
Frontend:  20231208.2

**Last working Home Assistant release (if known):**

**Companion App Logs:**
Not totally sure how to upload logs.
```

**Comment by dshokouhi** [comment]
I think you need to reach out to Nabu Casa support. The app cannot help get your instance connected to the cloud.

**Comment by dwdonnelly** [comment]
@dshokouhi   Will do.  Many thanks.  Happy and safe holidays.

**Comment by dwdonnelly** [comment]
Would like to leave this ticket/issue open until Nabu Casa responds.

**Comment by dshokouhi** [comment]
> Would like to leave this ticket/issue open until Nabu Casa responds.

There is really not much the app can do here, especially if the Home Assistant UI shows it is not connected. The app will not be able to fix this. I am going to close this issue for now as it may either be solved the NC cloud team or the HA frontend/core. There won't be any app changes needed for this.

**Comment by dwdonnelly** [comment]
That makes sense.  Thanks!

**Comment by dwdonnelly** [comment]
@dshokouhi  Just to wrap things up.......Nabu Casa investigated - and suggested I reboot the HA Server.  Rebooted hardware/software HA server - now Nabu Casa states I am connected.  Strange - but appears fixed.  Thank you for all your help.
