### ISSUE TITLE
"Service Button" widget missing on Samsung devices when adding widgets from home screen

### ISSUE THREAD

**Issue by Pytonballoon810** [home-assistant/android#4075]
**Home Assistant Android app version(s):**
2023.10.2-full
**Android version(s):**
14
**Device model(s):**
Samsung Galaxy S21
**Home Assistant version:**
Core
2023.12.3
Supervisor
2023.12.0
Operating System
11.2
Frontend
20231208.2
**Last working Home Assistant release (if known):**
Not known...
**Description of problem, include YAML if issue is related to notifications:**
The "Service Button" widget is missing from the widget editor. The editor however shows that there should be 6 widgets next to the name of the app.  

**Companion App Logs:**
There are no logs as the button for adding the widget is just missing

**Screenshot or video of problem:**
![WhatsApp Image 2023-12-26 at 14 11 59_050c2756](https://github.com/home-assistant/android/assets/84274397/4eaaaac9-ac91-484b-aaf8-10bfb97ba1fc)
![WhatsApp Image 2023-12-26 at 14 11 59_ec9c0a04](https://github.com/home-assistant/android/assets/84274397/dec34d4d-a44f-4e35-83dd-9bed3caddc7c)

**Additional information:**
I already tried:
- Reinstalling HA app
- Updating android system and Samsung "sub OS"
- Restarting my device

**Comment by dshokouhi** [comment]
This strange why would the widget be missing from the list? It's definitely there in my Pixel 8 pro and pretty sure other Samsung users have the widget visible as well. Are you by chance using a custom launcher?

**Comment by Pytonballoon810** [comment]
Nope not using a custom launcher. My nothing Phone 1 also has the widget. No idea why its missingFrom: Daniel Shokouhi ***@***.***>Sent: Tuesday, December 26, 2023 4:37:28 pmTo: home-assistant/android ***@***.***>Cc: Philipp Hofmann ***@***.***>; Author ***@***.***>Subject: Re: [home-assistant/android] "Service Button" widget missing on Android (Issue #4075)
This strange why would the widget be missing from the list? It's definitely there in my Pixel 8 pro and pretty sure other Samsung users have the widget visible as well. Are you by chance using a custom launcher?

**Comment by Pytonballoon810** [comment]
Nope not using a custom launcher. My nothing phone 1 also has the widget.

**Comment by dshokouhi** [comment]
instead of checking app logs please try checking logcat on the device itself you can do so by either using Android Studio or the app logcat reader. Both of which will require hooking up to a computer. There could be a system OS error the app is not getting.

**Comment by jpelgrom** [comment]
This is the only widget that is smaller by default but not sure why a launcher would hide it 🤔

Have you tried adding the widget from the app settings (Settings > Companion app > Manage widgets > Add widget)? While that won't do anything to fix your main issue, that should at least allow you to use it.

**Comment by Pytonballoon810** [comment]
> Have you tried adding the widget from the app settings

Just did that. It works for now but still weird since it clearly shows that there should be 6 widgets shown.

**Comment by richmck** [comment]
This issue is still in 2023.12.4-full.
Running HA Andriod on S21+ and on Tab S8+ with up to date OS and OneUI 6.
Service Button is available in "Recommended" menu, but not in Home Assistant" menu.
Both stock devices, no custom launchers.
Same missing icon, with "6" displayed.

**Comment by ptorngren** [comment]
Same here, running  2023.12.4-full on Android Samsung S22 with standard launcher. Works by using the Settings -> Companion app, as suggested by @jpelgrom

**Comment by jpelgrom** [comment]
If anyone here is familiar with logcat, could you check if any relevant errors show up when opening the widgets list in the launcher? That might give us a hint on if/how this can be handled by the app - the app tells what widgets it has but the launcher decides what to show. It won't show in the in-app logs and as @dshokouhi and I don't have Samsung devices with Android 14 we can't check.

**Comment by juicejuice** [comment]
Hi all, just chiming in - I have this issue on my new Samsung Galaxy S24 running current OneUI 6.1 firmware. The "Service Button" widget does not appear in any of the widget menus that appear after long-pressing the launcher screen. This problem seems specific to the Samsung Launcher as my Pixel 7 Pro has no issues using the Google Launcher. Both are running same version (latest version) of HA Companion app. The workaround mentioned for the Companion app is a little clunky but works just fine.

**Comment by dshokouhi** [comment]
> Not sure why it doesn't show under the HA section though

the only way to answer that at this point is for someone with an impacted device to get us the [requested logs](https://github.com/home-assistant/android/issues/4075#issuecomment-1899034818)

**Comment by juicejuice** [comment]
> As a workaround. Just go to the widget menu like normal, and search for service. It'll show up. Not sure why it doesn't show under the HA section though

Genius! That works too :)
