### ISSUE TITLE
Impossible navigation 

### ISSUE THREAD

**Issue by genrihb** [home-assistant/android#4076]
Hi all.  I discovered a bug in the Android mobile application.  Perhaps only for me.  When editing the panel, when adding tabs on the right, do not make more than 5 tabs.  I did about 10. Then I restarted Home Assistant after installing the addon.  That's all.  When I entered the mobile application, I found myself on the first of the tabs.  and I can’t move anywhere except changing this tab.  You can't get into settings, you can't get into add-ons or other panels.  I was looking for a solution on the Internet.  First of all, I thought about the addon that I installed last.  And I didn’t even think about the number of tabs.  Reinstalling the mobile app did nothing.  I thought about Google web viewer, reinstalled it to the developer version, it didn’t help.  And only by deleting the changes made in Home Assistant one by one, I realized that it was a matter of the number of tabs.  So, if you cannot navigate the Home Assistant in the mobile application, then deleting unnecessary tabs in the “overview” panel or another using another computer can really help.  Because I logged in from 3 other phones and got the same thing: the inability to move around in Home Assistant.  This happened today.  Be warned!

**Home Assistant Android app version(s):**
2023.12.4
**Android version(s):**
14
**Device model(s):**
SM-F946B/DS
**Home Assistant version:**
Core
2023.12.4
Supervisor
2023.12.1.dev2104
Operating System
Пользовательский интерфейс
20231208.2
**Last working Home Assistant release (if known):**
2023.12.4
**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
> When editing the panel, when adding tabs on the right, do not make more than 5 tabs. I did about 10. Then I restarted Home Assistant after installing the addon. That's all. When I entered the mobile application, I found myself on the first of the tabs. and I can’t move anywhere except changing this tab. You can't get into settings, you can't get into add-ons or other panels. I was looking for a solution on the Internet. First of all, I thought about the addon that I installed last. And I didn’t even think about the number of tabs. Reinstalling the mobile app did nothing.

This sounds like a HA frontend issue and not an app issue



> I thought about Google web viewer, reinstalled it to the developer version, it didn’t help

indeed not an app issue if you can reproduce using Chrome for android

Please open a new frontend issue as the app cannot solve this, I also suggest searching for open issues https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

The frontend has it own issue template so please make sure to fill that out completely and do mention you can reproduce using a browser on the same device
