### ISSUE TITLE
Asus Laptop with Windows 11 is not allowing data to be accessed from the operating system to Home Assistant.

### ISSUE THREAD

**Issue by rlknappjr** [home-assistant/android#4079]
"Does Not Apply"
**Home Assistant Android app version(s):**

**Android version(s):**

**Device model(s):**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![20231228_152920](https://github.com/home-assistant/android/assets/145170602/b1e6e61f-4d1f-44d7-9eed-61c1f3592d14)
I installed Android Home Assistant on my windows 11 computer and the above screen became available in home assistant for my Asus laptop.  But the revalues never change. When I unplug ac plug it stays the same. If the power is removed and the percentage drops it does not change.
 
![20231228_174327](https://github.com/home-assistant/android/assets/145170602/0726ccd8-7105-4a9f-82db-61bb7a9b42c5)

In this list it says that it is a Microsoft Corporation and Subsystem for Android(TM)

**Additional information:**

I am sorry if this is not everything you might need. Please contact me if there is more information.  I am relatively new to Home Assistant and need step by step instructions to pull out data you might need.

Thank you for the help. I really do appreciate it.

**Comment by jpelgrom** [comment]
Is the app open? By default the Windows Subsystem for Android will shutdown shortly after closing apps, also stopping any sensor updates.

(Also a limited number of sensors work correctly on Windows, but as I recall battery should be OK.)

If you're looking for frequent updates with limited battery usage, a 3rd party app/integration that runs natively on Windows might be better.

**Comment by rlknappjr** [comment]
I am interested in the 3rd party software that might allow the feedback to home assistant.  Currently I have the Android Subsystem running and I am not getting the reading updated in home assistant when I have the power cord removed from the laptop. I have looked at the application and cannot determine if there is any setting that I need to change. Any help in this would be apricated. I am a retired computer programmer but his has been many years since I was in the business, so there are many changes in the programs since I wrote code. Thank you for the support and help.

**Comment by dshokouhi** [comment]
im afraid the app is at the mercy of Windows android subsystem properly translating the Battery Manager API to windows laptops, without that I am afraid this may not work properly. Some other sensors do indeed work but not all do, thats up to Microsoft to fix IMO.

**Comment by jpelgrom** [comment]
Going to close this as WSA [will no longer be supported by Microsoft soon](https://learn.microsoft.com/en-us/windows/android/wsa/) and it is unlikely that it will receives significant updates. As mentioned by @dshokouhi Windows needs to implement the battery manager API properly, if that is broken/incorrect that isn't something the app can fix.
