### ISSUE TITLE
Missing translation in lokalise - Android Auto - connection_type, etc.

### ISSUE THREAD

**Issue by misa1515** [home-assistant/android#4081]
Hello,
please add missing words to translation in lokalise (screenshot attached).
(version 2023.12.5-full)

Thank you in advance.
![AndroidAuto](https://github.com/home-assistant/android/assets/61636045/5ab1e58a-1fae-472e-a32c-e060825df02c)

**Comment by jpelgrom** [comment]
This is an attribute, which is not translatable.
