### ISSUE TITLE
Missing translation in lokalise - app memory - more words

### ISSUE THREAD

**Issue by misa1515** [home-assistant/android#4082]
Hello,
please add missing words to translation in lokalise (screenshot attached).

**Home Assistant version:** 2023.12.5-full

Thank you in advance.
![AppMemory](https://github.com/home-assistant/android/assets/61636045/7268e3c4-ffe5-45a1-b384-770e290c72a6)

**Comment by jpelgrom** [comment]
This is an attribute, which is not translatable.
