### ISSUE TITLE
Missing translation in lokalise -  autobattery - unavailable

### ISSUE THREAD

**Issue by misa1515** [home-assistant/android#4083]
Hello,
please add missing words to translation in lokalise (screenshot attached).

**Home Assistant version:** 2023.12.5-full

Thank you in advance.
![AutoBattery](https://github.com/home-assistant/android/assets/61636045/2bf5a532-2d37-4f29-924d-1cb773d1a55a)

**Comment by jpelgrom** [comment]
This is a sensor value, which is not translatable. None of your sensors which are unavailable will have a translated state, the _frontend_ might show a translated string.
