### ISSUE TITLE
Missing translation in lokalise -  battery health - good

### ISSUE THREAD

**Issue by misa1515** [home-assistant/android#4084]
Hello,
please add missing words to translation in lokalise (screenshot attached).

**Home Assistant version:** 2023.12.5-full

Thank you in advance.
![BatteryHealth](https://github.com/home-assistant/android/assets/61636045/07b08164-83ba-4d93-9fc1-75edebac56f1)

**Comment by jpelgrom** [comment]
This is a sensor value, which is not translatable.
