### ISSUE TITLE
Missing translation in lokalise -  battery status - discharging

### ISSUE THREAD

**Issue by misa1515** [home-assistant/android#4085]
Hello,
please add missing words to translation in lokalise (screenshot attached).

**Home Assistant version:** 2023.12.5-full

Thank you in advance.
![BatteryStatus](https://github.com/home-assistant/android/assets/61636045/93450df3-12f0-41ec-bf24-a9c46a1757b4)

**Comment by jpelgrom** [comment]
This is a sensor value, which is not translatable.
