### ISSUE TITLE
Missing translation in lokalise - beacon monitor - monitoring

### ISSUE THREAD

**Issue by misa1515** [home-assistant/android#4086]
Hello,
please add missing words to translation in lokalise (screenshot attached).

**Home Assistant version:** 2023.12.5-full

Thank you in advance.
![BeaconMonitor_Monitoring](https://github.com/home-assistant/android/assets/61636045/ace197c8-0b1d-494b-ae98-3ef14ba40c04)

**Comment by jpelgrom** [comment]
This is a sensor value, which is not translatable.
