### ISSUE TITLE
Missing translation in lokalise -  BLE transmitter - more words

### ISSUE THREAD

**Issue by misa1515** [home-assistant/android#4087]
Hello,
please add missing words to translation in lokalise (screenshot attached).

**Home Assistant version:** 2023.12.5-full

Thank you in advance.
![BleSender](https://github.com/home-assistant/android/assets/61636045/533590ca-1f2b-41b7-9cb5-9823e5f34910)

**Comment by jpelgrom** [comment]
These are sensor values and attributes, which are not translatable.
