### ISSUE TITLE
Missing translation in lokalise -  bluetooth connection - more words

### ISSUE THREAD

**Issue by misa1515** [home-assistant/android#4088]
Hello,
please add missing words to translation in lokalise (screenshot attached).

**Home Assistant version:** 2023.12.5-full

Thank you in advance.
![BluetoothConnection](https://github.com/home-assistant/android/assets/61636045/d583cb9a-f09d-4b64-bf6a-c17c2315677b)

**Comment by jpelgrom** [comment]
These are sensor attributes, which are not translatable.

Please stop spamming issues @misa1515
