### ISSUE TITLE
Notifications should use the same 'collapse_key'

### ISSUE THREAD

**Issue by bieniu** [home-assistant/android#409]
**Home Assistant Android version:** 1.7
**Android version:** 10
**Phone model:** OnePlus 6
**Home Assistant version:** 0.105.3
**Last working Home Assistant release (if known):** None
**Description of problem:**
I think that notifications from HA should be grouped using the same `collapse_key` or `collapse_key` should be configurable by user.

`collapse_key` is a parameter of FCM [AndroidConfig](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidconfig)

**Comment by dshokouhi** [comment]
Was this by chance solved when notification [groups](https://companion.home-assistant.io/docs/notifications/notifications-basic/#thread-id-grouping-notifications) were added? This was a new beta feature a couple weeks ago

**Comment by JBassett** [comment]
@dshokouhi yep.
