### ISSUE TITLE
Set "Unknown"  all entities when no update for more than X hours

### ISSUE THREAD

**Issue by SeLLeRoNe** [home-assistant/android#411]
**Home Assistant Android version:**
1.7.0 (121)
**Android version:**
9
**Phone model:**
OnePlus5 (ONEPLUS A500)
**Home Assistant version:**
0.105.3
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
Not really a problem, before the App implementation I was using Tasker in combination with some automation.
The goal was to have the wifi/battery/device status all set to Unknown when those devices didn't receive an update for more then 6 hours.

This was allowing me to keep track of the device situation (even to understand if they were not connected (or even not on I would say) and to do automations based on that aswell.

I know that this might be more HA side of things rather then the App itself, but I also thought that here it would have more visibility and relevance rather then posting it on the forum where it would have been lost in minutes.

Also, not sure if it's doeable, when the phone is going off it might be forced to send a last position state and battery state?

Thanks

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by dshokouhi** [comment]
So every entity in HA has a `last_changed` and `last_updated` attribute that you can use to determine how long its been since an update.  I think that would achieve what you are looking to do here?

**Comment by klejejs** [comment]
> So every entity in HA has a `last_changed` and `last_updated` attribute that you can use to determine how long its been since an update. I think that would achieve what you are looking to do here?

I have actually tried this before, but unfortunately device_tracker.see is not supposed by mobile_app device trackers, so it is not possible to manually change the state.

**Comment by dshokouhi** [comment]
Yup you won't be able to use `device_tracker.see` as its only for legacy device trackers.  These steps are more for you to create a template sensor or use in an automation in order to determine if it hasn't been updated in x hours.

**Comment by SeLLeRoNe** [comment]
That's actually my point, intead of having to create different additional entities to do this it might be better to have a default behaviour for specific "Mobile App related" entities.

Otherwise yes, I can create the input_text and input_boolean (battery level and wifi/battery status), it's the same thing I've been doing with tasker using webhooks, but I do believe there should be a better way for this to happen.

Because I can do it, no problem, not all are "tecky" and like to tinker with stuff, so a "fail-over" should still be in place to don't have a phone reporting "100%" of battery when has been off for a day :)

**Comment by dshokouhi** [comment]
yea maybe instead of `unknown` a better state would be `unavailable` we may be able to set that when a device is powered off I think.  The rest a timeout could work.  I wonder how iOS handles this 🤔

**Comment by SeLLeRoNe** [comment]
Not really sure about which one is better, because Unknown would be valid for example if the phone had no connection for X hours (let's say 6 and let's say it had simply no internet), it's more unknown rather then the value being unavailable.. Anyway, I guess it's fine both way :)

**Comment by klejejs** [comment]
Unknown or unavailable are great options and I would love for them to be implemented, but in this case integration.person should also support this feature and ignore the device_tracker entity if it is in this state, because then router can specify, if the device is home or not.

**Comment by SeLLeRoNe** [comment]
That's a good point, not sure if it's already like that but a device_tracker in unknown or unavailable status should be "skipped" by the person assigned devices (if there are others available).

Until now, to have the "unknown" status on a mobile after X hours without update I had the battery sensor configured as a template:
```
    value_template: >-
      {% if state_attr('device_tracker.andrea_oneplus5', 'battery_level') %}
        {{ state_attr('device_tracker.andrea_oneplus5', 'battery_level') }}
      {% elif not is_state('input_text.andrea_oneplus5_battery', 'unknown') %}
        {{ states('input_text.andrea_oneplus5_battery') | int }}
      {% else %}
        unknown
      {% endif %}
```


And an automation that was switching off all the input_booleans related to the device (wifi and charging status) running every minute
```
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{% if states.input_text.andrea_oneplus5_battery is defined %} {{(as_timestamp(now()) - as_timestamp(states.input_text.andrea_oneplus5_battery.last_changed)) > 43200 }} {% endif %}'
action:
  - service: input_text.set_value
    data_template:
      entity_id: input_text.andrea_oneplus5_battery
      value: "unknown"
  - service: input_boolean.turn_off
    data_template:
      entity_id: input_boolean.andrea_oneplus5_charging
  - service: input_boolean.turn_off
    data_template:
      entity_id: input_boolean.andrea_oneplus5_wifi
```

I can get back to this configuration, but the battery sensor provided by the App lose all it's functionality and it would be just an additional entity that I need to "tweak" to make better.

Maybe a good plus would be the ability to chose:
- Normal mode - Have all entities separated (as they are now, for less tecky users)
- Advanced mode - Have all the informations inside the single device_tracker and let each "House Admin" create the entities using templates the way they want them.

In my personal case, the second option would be perfect, because I will have only the device tracker and all battery/charging/wifi information would be attribtues inside the entity allowing me to mantain the above setup without having to "re-invent it".

Also, not sure how the battery icon is defined in the sensor (I saw it goes with the % and charging state) when it goes low/unknown, here is how I use it, it might be useful maybe to someone (or maybe can be done the same in the App generated sensor) ^^
```
    icon_template: >
      {% if state_attr('device_tracker.andrea_oneplus5', 'battery_level') %}
        {% set battery_level = state_attr('device_tracker.andrea_oneplus5', 'battery_level') | int %}
      {% elif not is_state('input_text.andrea_oneplus5_battery', 'unknown') %}
        {% set battery_level = states('input_text.andrea_oneplus5_battery') | int %}
      {% else %}
        mdi:battery-unknown
      {% endif %}
      {% if battery_level is defined %}
        {% if battery_level == 100 %}
          {% if is_state('binary_sensor.andrea_oneplus5_charging', 'on') %}
            mdi:battery-charging-100
          {% elif is_state('input_boolean.andrea_oneplus5_charging', 'on') %}
            mdi:battery-charging-100
          {% else %}
            mdi:battery
          {% endif %}
        {% elif battery_level >= 10 %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if is_state('binary_sensor.andrea_oneplus5_charging', 'on') %}
            mdi:battery-charging-{{ battery_round }}
          {% elif is_state('input_boolean.andrea_oneplus5_charging', 'on') %}
            mdi:battery-charging-{{ battery_round }}
          {% else %}
            mdi:battery-{{ battery_round }}
          {% endif %}
        {% elif battery_level >= 5 %}
          {% if is_state('binary_sensor.andrea_oneplus5_charging', 'on') %}
            mdi:battery-charging-outline
          {% elif is_state('input_boolean.andrea_oneplus5_charging', 'on') %}
            mdi:battery-charging-outline
          {% else %}
            mdi:battery-outline
          {% endif %}
        {% elif battery_level >= 0 %}
          {% if is_state('binary_sensor.andrea_oneplus5_charging', 'on') %}
            mdi:battery-charging-outline
          {% elif is_state('input_boolean.andrea_oneplus5_charging', 'on') %}
            mdi:battery-charging-outline
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% else %}
          mdi:battery-unknown
        {% endif %}
      {% endif %}
```

**Comment by SeLLeRoNe** [comment]
Is this going to be implemented?

**Comment by dshokouhi** [comment]
So looking into this more closely.  I don't think this is something the app itself should handle.  If the device has shut down or is out of network then we can't send anything back home so HA core should be responsible for this behavior due to that alone.  The app does have a `last_update` sensor that could be used to make the templates easier since it updates all the time (except for when the update is only SensorWorker, like if your device is idle for a while).  Since HA core does not accept feature requests on github we also can't move this issue so I suggest creating a feature request on the forums as something like this in HA core will benefit all `mobile_app` devices.

Now what the app can do is report when it can't reach home but thats on device itself via something like a notification, which is what #1265 is set to achieve.

**Comment by SeLLeRoNe** [comment]
I see and I agree.
Too bad the core FR is not on GitHub, the forum one is very dispersive and even if I create it there, it will be lost and forgotten.

But I see your point, I will play with templates myself to try to achieve that.
