### ISSUE TITLE
Image not replaced on watch, when replacement notification sent using a tag

### ISSUE THREAD

**Issue by colmbuckley** [home-assistant/android#4112]
**Home Assistant Android app version(s):**
Phone: 2023.12.4-full
Watch: 2023.12.4 (but I don't *think* this is a watch app issue)

**Android version(s):**
Phone: Android 14; UQ1A.240105.004
Watch: Wear OS 4; TWD9.231205.001

**Device model(s):**
Phone: Google Pixel 8 Pro
Watch: Google Pixel Watch 2

**Home Assistant version:**
Home Assistant OS 11.2
Home Assistant Core 2023.12.4

**Last working Home Assistant release (if known):**
I don't think this ever worked properly.

**Description of problem, include YAML if issue is related to notifications:**
I am running the Home Assistant companion app on my Android phone, and I use my paired Wear OS watch to view and interact with HA notifications. While I do also have the Wear OS HA app installed on my watch, I believe that this issue is not related to the Wear OS HA app but rather to notification sync from phone to watch using native capabilities.

When I send a notification to my *phone* using `notify.device`, with an attached image, the phone correctly displays the image in the notification screen. As I have set my watch to also display Home Assistant companion app notifications, the same notification and image are displayed on my watch. **NOTE:** this is the regular Wear OS notification mirroring, I am not sending this notification to the watch device explicitly.

So far so good.

When I send a "replacement" notification (by using the same tag) with new text and image, the phone displays the new notification with the new image correctly. But the watch only changes the text of the notification, *not* the image.

Example:
* I created the two simple images below, and placed them in `/media/test` (as `red.jpg` and `blue.jpg` respectively).
* I sent the first notification using:
```
service: notify.colm
data:
  title: Test Red
  message: Red Test Message
  data:
    image: /media/local/test/red.jpg
    tag: test-image
    channel: Test
    group: Test
    importance: high
```
* This causes the "red" text and image to display correctly on both phone and watch (`colm` is a notification group which goes to my phone; *not* my watch) - see first set of screenshots.
* I then sent a replacement notification using:
```
service: notify.colm
data:
  title: Test Blue
  message: Blue Test Message
  data:
    image: /media/local/test/blue.jpg
    tag: test-image
    channel: Test
    group: Test
    importance: high
```
* (Note: the tag, channel and group are unchanged, but the title, message and attachment are all new)
* This causes the title, message and attachment to be correctly replaced on the *phone*, but on the *watch* only the title and message are updated; the image stays unchanged (ie: it stays "red").

I think it is likely that this is a bug in Wear OS's notification sync mechanism rather than Home Assistant (given that the  updated notification displays correctly on the phone) but I'm starting here to see if others can replicate the issue, and hopefully identify which upstream component a bug might be filed against.

**Companion App Logs:**
```
01-03 12:19:34.743 27754 27866 D WebSocketRepository: Websocket: onMessage (text)
01-03 12:19:34.744 27754 27866 D WebSocketRepository: Message number 17315 received
01-03 12:19:34.748 27754 27785 D WebSocketRepository: Sending message 19413: {type=mobile_app/push_notification_confirm, webhook_id=e331a28e7a1d3b61556e5eb263dc9316832d8642adfa2fe893568ab81b3f4b42, confirm_id=2fac8bc04622f6b1bae2c09cf4420f9c, id=19413}
01-03 12:19:34.748 27754 27785 D WebSocketRepository: Message number 19413 sent
01-03 12:19:34.755 27754 27866 D WebSocketRepository: Websocket: onMessage (text)
01-03 12:19:34.756 27754 27866 D WebSocketRepository: Message number 19413 received
01-03 12:19:34.762 27754 27754 D MessagingService: Creating notification with following data: {image=/media/local/test/red.jpg, tag=test-image, channel=Test, group=Test, importance=high, message=Red Test Message, title=Test Red, webhook_id=e331a28e7a1d3b61556e5eb263dc9316832d8642adfa2fe893568ab81b3f4b42, server_id=2}
01-03 12:19:34.776 27754 27754 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: true, usesWifi is: true
01-03 12:19:34.776 27754 27754 D ServerConnectionInfo: Using internal URL
01-03 12:19:34.783 27754 29818 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: true, usesWifi is: true
01-03 12:19:34.783 27754 29818 D ServerConnectionInfo: Using internal URL
01-03 12:19:34.794 27754 29818 D TrafficStats: tagSocket(346) with statsTag=0xffffffff, statsUid=-1
01-03 12:19:34.872 27754 27754 D MessagingService: Show notification with tag "test-image" and id "629525600"
01-03 12:19:34.881 27754 27754 D MessagingService: Show group notification with tag "group_Test" and id "1281536626"
01-03 12:19:48.400 27754 29818 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: true, usesWifi is: true
01-03 12:19:48.403 27754 29818 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: true, usesWifi is: true
01-03 12:19:48.407 27754 29818 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: true, usesWifi is: true
01-03 12:19:48.410 27754 29818 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: true, usesWifi is: true
01-03 12:19:48.411 27754 29818 D WebSocketRepository: Sending message 19414: {type=ping, id=19414}
01-03 12:19:48.411 27754 29818 D WebSocketRepository: Message number 19414 sent
01-03 12:19:48.465 27754 27866 D WebSocketRepository: Websocket: onMessage (text)
01-03 12:19:48.466 27754 27866 D WebSocketRepository: Message number 19414 received
01-03 12:19:50.636 27754 27866 D WebSocketRepository: Websocket: onMessage (text)
01-03 12:19:50.636 27754 27866 D WebSocketRepository: Message number 17315 received
01-03 12:19:50.639 27754 27785 D WebSocketRepository: Sending message 19415: {type=mobile_app/push_notification_confirm, webhook_id=e331a28e7a1d3b61556e5eb263dc9316832d8642adfa2fe893568ab81b3f4b42, confirm_id=97a4f33fafd03e5ea17aa7625c48b1a6, id=19415}
01-03 12:19:50.639 27754 27785 D WebSocketRepository: Message number 19415 sent
01-03 12:19:50.655 27754 27866 D WebSocketRepository: Websocket: onMessage (text)
01-03 12:19:50.655 27754 27866 D WebSocketRepository: Message number 19415 received
01-03 12:19:50.659 27754 27754 D MessagingService: Creating notification with following data: {image=/media/local/test/blue.jpg, tag=test-image, channel=Test, group=Test, importance=high, message=Blue Test Message, title=Test Blue, webhook_id=e331a28e7a1d3b61556e5eb263dc9316832d8642adfa2fe893568ab81b3f4b42, server_id=2}
01-03 12:19:50.667 27754 27754 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: true, usesWifi is: true
01-03 12:19:50.667 27754 27754 D ServerConnectionInfo: Using internal URL
01-03 12:19:50.671 27754 26274 D ServerConnectionInfo: localUrl is: true, usesInternalSsid is: true, usesWifi is: true
01-03 12:19:50.671 27754 26274 D ServerConnectionInfo: Using internal URL
01-03 12:19:50.697 27754 27754 D MessagingService: Show notification with tag "test-image" and id "629525600"
01-03 12:19:50.702 27754 27754 D MessagingService: Show group notification with tag "group_Test" and id "1281536626"
```

**Screenshot or video of problem:**
First notification:
![screenshot-phone-red](https://github.com/home-assistant/android/assets/5861002/f7bde91f-5a46-4f00-9dd2-5395e2a7e932)
![screenshot-watch-red](https://github.com/home-assistant/android/assets/5861002/b03c10bc-eebe-4967-98a4-bbcc9e83bf1c)

Second notification:
![screenshot-phone-blue](https://github.com/home-assistant/android/assets/5861002/b3f5dc76-2e8c-4fab-b450-a27e7145ce4d)
![screenshot-watch-blue](https://github.com/home-assistant/android/assets/5861002/cba5a9a0-6a23-4e5e-acc3-17d244593f15)

**Additional information:**
![red.jpg](https://github.com/home-assistant/android/assets/5861002/46a24c47-938f-4e67-98ec-c54029e214b3)
![blue.jpg](https://github.com/home-assistant/android/assets/5861002/f5898603-83e8-4d16-b972-0227ace317fd)

**Comment by colmbuckley** [comment]
Oh; I am using a persistent connection with "always" on.

**Comment by dshokouhi** [comment]
Closing due to lack of response from the author. The app does not control relayed notifications which I assume is what is being referred to here.

**Comment by colmbuckley** [comment]
Yes, apologies. Google have acknowledged this bug and are working on it.

**Comment by jpelgrom** [comment]
Do you have a Google issue tracker link you could post here, or did you report it some other way?

**Comment by colmbuckley** [comment]
I reported it internally. I’m not sure if it was reflected on the public bugtraq.

**Comment by colmbuckley** [comment]
(For the record, the build containing the fix for this issue was pushed to Pixel Watch 2 at least, earlier this month.)
