### ISSUE TITLE
Next alarm sensor not triggering automation

### ISSUE THREAD

**Issue by kalda123** [home-assistant/android#4114]
**Home Assistant Android app version(s):**
latest
**Android version(s):**
Latest
**Device model(s):**
Google Pixel 8 Pro
**Home Assistant version:**
Latest
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Hi, Im having issue with next_alarm sensor, Im using it as a trigger to my morning rutine automation. I found out that this sensor has a correct value till last second - alarm is usualy set to 6:20 and at 6:19:59 the value changes to unavailable and back to new value after couple of second, resulting in the automation not starting. Do you have any idea how to solve this? Thank you.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![image](https://github.com/home-assistant/android/assets/95139261/f06dd57a-3fab-4436-a802-8b6b21127dda)

**Additional information:**

**Comment by dshokouhi** [comment]
Check that server time is up to date it may be off

**Comment by kalda123** [comment]
So in the end it really was a time synchronization error, but not on the server, but on the phone.  Thank you

**Comment by therealmrfox** [comment]
The same issue has puzzled me for a long time! 

Here's [my hack](https://github.com/home-assistant/core/issues/108859#issuecomment-2019048063) to work around it.
