### ISSUE TITLE
Error on installing a uodate if another update in Progress

### ISSUE THREAD

**Issue by florian-sabonchi** [home-assistant/android#4115]
![Screenshot_20240105-143302](https://github.com/home-assistant/android/assets/54689374/f2eebeb5-f22d-45c3-9075-75cb84054c66)

**Home Assistant Android app version(s):**

**Android version(s):**

14

**Device model(s):**
Google Pixel 6

**Home Assistant version:**

Core
2023.12.4
Supervisor
2023.12.0
Operating System
11.2
Frontend
20231208.2

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Please open a HA frontend issue for this, the app cannot solve it.
