### ISSUE TITLE
Weird Y axis scaling and ticks in energy dashboard 

### ISSUE THREAD

**Issue by jpfaff** [home-assistant/android#4121]
**Home Assistant Android app version(s):**

**Android version(s):** 13

**Device model(s):** Pixel 4a

**Home Assistant version:** 2024.1.1

**Last working Home Assistant release (if known):** 2023.12.x

**Description of problem, include YAML if issue is related to notifications:**Actually not sure if this is an app or frontend problem but it works on my browser so here we go.
In the energy dashboard the gas consumption graph has a strange y axis scaling / ticks.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
Problem:
![Screenshot_20240106-200941](https://github.com/home-assistant/android/assets/2955477/ba51f900-7e5e-4614-bdc3-c8aa59fb254a)

Expected:
![Screenshot_20240106-201004](https://github.com/home-assistant/android/assets/2955477/6f4ab293-4824-4065-8e86-ba410c0c1b7c)

**Additional information:**

**Comment by dshokouhi** [comment]
> but it works on my browser so here we go.

by browser do you mean chrome for android on the same device? 

Chances are this is a frontend issue but good to check a browser on the same device as thats a more realistic test than desktop browser

**Comment by jpfaff** [comment]
The screenshot is actually Firefox on the same device.

Just checked with chrome. I get the same as in the app.

It looks like the y axis values are limited to 2 decimal places on the app / chrome and 3 on firefox. 

You can probably close here and I file a bug in the frontend.

**Comment by dshokouhi** [comment]
> You can probably close here and I file a bug in the frontend.

yes thats what I'll do as they have a different template than us and request different information. Also check for open issues it may already be known.
