### ISSUE TITLE
[to_do lists] Marking an item as completed follows the item to the bottom of the list

### ISSUE THREAD

**Issue by titiviking** [home-assistant/android#4130]
**Home Assistant Android app version(s):**
2023.12.5-full
**Android version(s):**
Android 13
**Device model(s):**
OnePlus 8 Pro
**Home Assistant version:**
2024.1.2
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
In the shopping list, when marking an item as being completed (because added to the groceries basket), the list jumps towards then bottom of the list, following the item that was marked.
This means that every item marked, requires to manually scoll back all the way to the top to find back the remaining items that need to be picked up...
This is very inconvenient and not user friendly (at least for a shopping list).

A setting should be added (per list?) to either follow the item, or simply stay at the top of the list when an item is marked.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
Todo lists are not app specific. The correct place for a feature request like this is the [frontend discussions](https://github.com/home-assistant/frontend/discussions) on GitHub.
