### ISSUE TITLE
samsung AOD widgets not updating 

### ISSUE THREAD

**Issue by bednim** [home-assistant/android#4131]
using companion app on samsung device, adding HA template widget to AOD screen (good lock app allows you to do so) with temp reading - while entity changes in the HA - on the AOD screen it does not change at all.

**Comment by dshokouhi** [comment]
what happened to the issue template that gest presented? all data is important to help you out. When it comes to Samsung did you make sure to turn off all the extra settings tehy enable? I think Data Saver is one that impacts the widget.

either way we need more data to go by here. Please fill out the issue template and get us logs when the issue occurs

**Comment by bednim** [comment]
Apologies regarding template.

AOD indeed changes after, around minute - I'm not sure how I missed that earlier 🤔
