### ISSUE TITLE
Support for image entities in the camera widget

### ISSUE THREAD

**Issue by watermarkhu** [home-assistant/android#4139]
Starting from [2023.7](https://www.home-assistant.io/blog/2023/07/05/release-20237/#image-entities), [image entities](https://developers.home-assistant.io/docs/core/entity/image/) where introduced as a simplified version of the camera entity. 

The current camera widget however does not support these image entities, and it only allows for camera entities to be selected in the configuration menu.

**Comment by dshokouhi** [comment]
so do we need to rename this widget to be "Picture Widget" to be more accurate? 😂  Look like we just need to slightly modify the API call for this.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/image/__init__.py#L45

**Comment by jpelgrom** [comment]
We actually don't need to make any changes to the API call, `image` entities also have a `entity_picture` attribute we can use that works the same as a camera's.
