### ISSUE TITLE
Sync Android and HA thread credentials

### ISSUE THREAD

**Issue by cburghardt** [home-assistant/android#4148]
I have a merged Thread network with Apple and the HA OTBR. Only the Google network which is created by a Google Nesthub is still separate. The debug - sync thread credentials option in the App menu says that the device and HA use different preferred networks - the device wants to use the Google network. So there should be an option to fix this.
I understand that this could be fixed by deleting the Google Play services data on the device but this should not be necessary.

**Comment by jpelgrom** [comment]
Sorry, no way to change the preferred network on the device is an API limitation and out of scope for the app.

If Google adds options for this we can revisit it, but I suspect if they add options it'll be only in the UI and not something apps can change.
