### ISSUE TITLE
Show clock instead of 3 dots

### ISSUE THREAD

**Issue by RutgerBeyen** [home-assistant/android#4153]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like:**
Request the possibility to show the clock/time in the upper right corner of the top bar in stead of the three dots. I'm using the companion app on a wallpanel and trying to use the limited screen size to a maximum as the top bar is now partially empty.

**Describe alternatives you've considered, if any:**
Clock as card inside a dashboard, but this wastes precious space

**Additional context:**
This is possible in the website version of HA by using the solution mentioned here: https://community.home-assistant.io/t/replacing-the-three-dots-in-the-header-with-a-clock/271170

**Comment by dshokouhi** [comment]
This is a request for the HA frontend, the app does not have control on that header.
