### ISSUE TITLE
No app alerts when reconnecting wifi, “device not connected to local push notifications”

### ISSUE THREAD

**Issue by tigermick** [home-assistant/android#4164]
**Home Assistant Android app version(s):**
2023.12.4-minimal

**Android version(s):**
Android 13

**Device model(s):**
OnePlus 7 pro GM1911

**Home Assistant version:**
Core : 2024.1.5
Supervisor : 2023.12.1
OS : 11.4
User interface : 20240104.0

**Last working Home Assistant release (if known):**
I don't know because, I set a new configuration with new hardware

**Description of problem, include YAML if issue is related to notifications:**
Despite the solution provided in [https://community.home-assistant.io/t/solved-device-not-connected-to-local-push-notifications/476750/5 6](https://community.home-assistant.io/t/solved-device-not-connected-to-local-push-notifications/476750/5), no notifications are received after reconnecting the wifi.

Steps to reproduce:

    Disconnect wifi
    Time spent
    Connect wifi

I have 2 phones in my home.
Persistent notifications are set to “always” on my phone on my Oneplus 7 pro, the notification is visible on both devices.
1 device has Google Play Services (samsung), other does not have it (Oneplus 7 pro).

With Samsung phone, everything still works fine.
With Oneplus 7 pro phone, everything works fine at first but when I leave the house, the wifi is disconnected (my home assistant only works via LAN). when I come back at home (wifi reconnection), no notification is received and I get this message : "device not connected to local push notifications” if I try to run manually an automation.

Fix: force kill the Companion app, open it again. Then notifications resume working.

this post on home assistant forum explain this too : [https://community.home-assistant.io/t/no-app-alerts-when-reconnecting-wifi-device-not-connected-to-local-push-notifications/617679](https://community.home-assistant.io/t/no-app-alerts-when-reconnecting-wifi-device-not-connected-to-local-push-notifications/617679)

**Comment by dshokouhi** [comment]
where are the requested logs, why did you remove the entire section? without logs we cannot be of help.

**Comment by tigermick** [comment]
Sorry, this is not my topic in the home assistant forum at first ...
I just have the same problem and the thread owner doesn't seem to have opened an issue here ...
so I wanted to create one in its place...

And I'm just seeing, there is a new HA android client update ...
I will try again and give you my log if the problem is still there.

**Comment by dshokouhi** [comment]
closing as we did not get the requested logs, please make sure the issue template is completed otherwise we will not be able to help.
