### ISSUE TITLE
Timer for the reconnection time runs backwards

### ISSUE THREAD

**Issue by florian-sabonchi** [home-assistant/android#4172]
![Screenshot_20240128-095457](https://github.com/home-assistant/android/assets/54689374/c66dae56-8f6f-4a04-98ac-1bb6deeae41d)

**Home Assistant Android app version(s):**

**Android version(s):**
14
UQ1A.240105.002.2024012600

**Device model(s):**
Pixel 6

**Home Assistant version:**

Core
2024.1.5
Supervisor
2023.12.1
Operating System
11.4
Frontend
20240104.0

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
This screen is provided by the frontend, the app doesn't manage this timer. Please [open a frontend issue instead](https://github.com/home-assistant/frontend/issues) and make sure to fill out the template.
