### ISSUE TITLE
Send an event when notification dismissed

### ISSUE THREAD

**Issue by wbilger** [home-assistant/android#418]
As title says, just a feature request.
Would it be possible to send an event when a notificatin is swiped away (dismissed).

**Comment by robbiet480** [comment]
[This would be taken care of by my proposal to unify and upgrade push notifications in Home Assistant Company for Android and iOS](https://github.com/home-assistant/companion.home-assistant/issues/176).

**Comment by wbilger** [comment]
Sounds great, awesome work!

**Comment by mario-tux** [comment]
I understand that the cited proposal (https://github.com/home-assistant/companion.home-assistant/issues/176) would solve this problem too but, until now, it is not yet implemented.

Getting a simple event (like any action already supported) when the notification is dismissed would allow to send the same notification on multiple personal devices (smartphone, tablet, ....) and to dismiss the same notification from all of them when it is swiped from one.

Please consider to include this further event: waiting for a better notification management, it would be very helpful.
