### ISSUE TITLE
Cadillac Lyriq Android Automotive Missing Menu

### ISSUE THREAD

**Issue by Jizzay1** [home-assistant/android#4187]
**Home Assistant Android app version(s):**

**Android version(s):**

**Device model(s):**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Newly purchased Cadillac Lyriq which uses Android Automotive Operating System (AAOS). Installed Home Assistant via the car's play store app. Successfully able to logic and connect to my home assistant instance at home. 

When opening HA app on car I get a list of entities by category (buttons switches etc) and can search and a operate correctly. 

Issue: I've seen other reference a menu that should appear that would allow me to select a dashboard. No menu of any kind appears in the HA app. 

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Did you install it from the Google Play store in the car?

**Comment by Jizzay1** [comment]
> Did you install it from the Google Play store in the car?

Correct - installed HA app from the Google play store app in the car.

**Comment by dshokouhi** [comment]
ok unfortunately Google had asked us to remove it so we are waiting on them to allow us to restore it. If you are able to install the  minimal version of hte app from another app store that will allow you to access settings.

Closing this as we cannot fix this for ow.
