### ISSUE TITLE
Where I find the "zone based tracking toggle" ?

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [home-assistant/android#4189]
**Home Assistant Android app version(s):**
Latest
**Android version(s):**
Latest
**Device model(s):**
Samsung Z-Fold
**Home Assistant version:**
Latest
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

I read in the companion app documentation the following regarding location updates when entering or exiting a zone

"Location updates are sent from your device to Home Assistant in a number of situations:

When you enter or exit a zone defined in Home Assistant. For Android ensure the zone based tracking toggle is enabled in the Companion App section in Configuration."

I did look everywhere in the companion app settings within the app but I can not find the "zone based tracking toggle" can anyone tell me where I can find this in the Android app???

Thanks Upfront!

**Companion App Logs:**
None
```

```

**Screenshot or video of problem:**
![Screenshot_20240204_201503_Chrome](https://github.com/home-assistant/android/assets/97987488/513dd8fb-59ad-4696-a06b-a98198918b2c)

**Additional information:**
None

**Comment by dshokouhi** [comment]
the answer is actually on the same page

https://companion.home-assistant.io/docs/core/location#android-location-sensors

Settings > Companion app > manage sensors

the actual sensor name is called Location zone

you can also search the sensor list for "zone" and find it

**Comment by smarthomefamilyverrips** [comment]
> the answer is actually on the same page
> 
> https://companion.home-assistant.io/docs/core/location#android-location-sensors
> 
> Settings > Companion app > manage sensors
> 
> the actual sensor name is called Location zone
> 
> you can also search the sensor list for "zone" and find it

@dshokouhi Thank you! That one already was on actually, I will check a bit more because I believe that my location not updates while entering or exiting a zone.

At least I know now I have the correct setting "toggled" on

**Comment by dshokouhi** [comment]
for troubleshooting location issues check these steps first then keep reading to look at the location tracking history to help find out why those reports may be getting skipped

https://companion.home-assistant.io/docs/troubleshooting/faqs/#device-tracker-is-not-updating-in-android-app
