### ISSUE TITLE
Search box doesn't work for searching home assistant logs

### ISSUE THREAD

**Issue by alexd321** [home-assistant/android#4190]
**Home Assistant Android app version(s):**
2024.1.5-full
**Android version(s):**
14
**Device model(s):**
Samsung S21 Ultra
**Home Assistant version:**
2024.1.6
**Last working Home Assistant release (if known):**
Never known it to work
**Description of problem, include YAML if issue is related to notifications:**
Tapping anywhere in or near the search box on the logs page for Home Assistant does nothing, so cannot search logs

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
https://github.com/home-assistant/android/assets/69210910/5090d2eb-ba0d-4f27-b0fd-add0d78a9c5f

**Additional information:**

**Comment by dshokouhi** [comment]
can you reproduce using chrome for android on the same device?

**Comment by alexd321** [comment]
Identical issue in chrome (and Edge)

**Comment by alexd321** [comment]
Other search boxes (e.g. manage sensors) do work, just logs that's broken

**Comment by dshokouhi** [comment]
> Identical issue in chrome (and Edge)

ok please create a new issue with the HA frontend and follow their issue template as they request different information. The app will not be able to fix this.

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml
