### ISSUE TITLE
Scrolling on a dashboard often accidentally triggers inputs

### ISSUE THREAD

**Issue by rvandegrift** [home-assistant/android#4191]
**Home Assistant Android app version(s):** 2024.1.2-minimal

**Android version(s):** LineageOS 20 / Android 13

**Device model(s):** Pixel 5a 5G

**Home Assistant version:** 2023.12.3

**Last working Home Assistant release (if known):** N/A

**Description of problem, include YAML if issue is related to notifications:**
When scrolling a dashboard on the companion app, touches that start scrolling are often used as input for the underlying widget.

This is really problematic with the Thermostat card, since input along the circle it displays changes the set points.  So I regularly change thermostats by accident, just by scrolling down on a dashboard.

This might affect other widgets, but I only notice it with Thermostats.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
These symptoms sound like https://github.com/home-assistant/android/issues/3565

**Comment by rvandegrift** [comment]
Yes, I agreed - thanks
