### ISSUE TITLE
request_location_update only works when the app is in the foreground (4 phones across 3 models tested)

### ISSUE THREAD

**Issue by Gymratz** [home-assistant/android#4193]
**Home Assistant Android app version(s):**
2024.1.5-full

**Android version(s):**
Android 14, 12, 10

**Device model(s):**
SM-S908U, SM-A326U, SM-G965U1

**Home Assistant version:**
Core: 2024.2.0b8 (currently, but same issue before beta)
Supervisor: 2024.01.1
OS: 11.5
Frontend: 20240205.0

**Last working Home Assistant release (if known):**
Never, to best of my knowledge.

**Description of problem, include YAML if issue is related to notifications:**

Running the following service:
service: notify.mobile_app_person_phone
metadata: {}
data:
  message: "request_location_update"

Works only if the Home Assistant application is in the foreground.
If the application is running but not in the foreground, it seems to be "queued" for at least a short period and opening the app will then execute the command.

If application is in the foreground, execution of the command is immediate.
Normal background "Single Accurate Location" frequency executes without error.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Please check that all battery saving settings are disabled. As you have Samsung devices there will be more than one option to turn off. The app needs to run in the background in order to process those commands. Also make sure to follow the critical format outlined in the docs to ensure they are received timely.

**Comment by Gymratz** [comment]
Thank you, @dshokouhi - I believe everything is set up correctly here.
I checked this site https://dontkillmyapp.com/samsung as was suggested in a prior bug report that wasn't ever validated as being resolved.
I've got all battery saving items on my phone turned off.
One reason that I believe this is not related to background is that all other commands that I've tested do not have the same issue (limited testing, to be fair).
For example, I can execute "command_screen_on" and visually see that this works.

That being said, I will enable the "app sensors" to see if the states show anything unexpected.

**Comment by dshokouhi** [comment]
if you believe the notification is arriving on time you can confirm that with the notification history section of the app. Also the dontkillmyapp site may not contain all that you need to turn off. Samsung adds stuff in recent versions so look for things like power saving, data saving etc...

`command_screen_on` just turns on the screen and does not return any data, so the symptoms of having to open the app still suggests the app is put to sleep before it can send any data or even make a request to Google to give an immediate location update.

did you also make sure to grant the app location access all the time? Now might be a good time to double check the location settings if you have not done so already

https://companion.home-assistant.io/docs/troubleshooting/faqs/#device-tracker-is-not-updating-in-android-app

**Comment by Gymratz** [comment]
Triple checked the battery optimizing, data, sleep, etc., and everything is either completely off or excludes HA app.  Things <look> good there.

Notification History shows receipt of the commands.
![image](https://github.com/home-assistant/android/assets/53660071/8667ca04-e067-462e-b11a-1c3c323497b2)

Location Tracking history shows none sent at those times.
![image](https://github.com/home-assistant/android/assets/53660071/b3b4e566-301e-4c88-8356-5f4101485e5d)

Yet, they all started trying immediately when I brought phone back to life.

(Hopefully these sensors help to reflect that - can see when screen was turned off versus back on - and that while the app got the notification when it was sent, it didn't act on it until the second App Importance changed back to Foreground).
![image](https://github.com/home-assistant/android/assets/53660071/c4d41710-8686-4ea0-b23b-9339bbeec784)

**Comment by dshokouhi** [comment]
check the app logs as well in teh same troubleshooting section lets look to see if the request was made to Google, for location issues like this try to get 10 minutes of log time

also the duplicate and old location updates may indeed be valid from the history but I would expect to see those return immediately, the logs will help show what happened there

if your location has not changed in 15 minutes we do indeed skip those updates but it should reflect in the history and logs

logs do not go to far back so you may need to reproduce again after the app is open

**Comment by Gymratz** [comment]
Log was all still there - so I can add logs for the same time we've been looking at.
This section seems odd to me - specifically "registerCallbackForPendingTransactions" happens a couple milliseconds after screen on, and before the things that are supposed to happen, do.

`02-06 11:59:36.097  5464  5464 D SensorReceiver: Received intent: android.intent.action.SCREEN_ON
02-06 11:59:36.098  5464  5464 D ButtonWidget: Broadcast received: 
02-06 11:59:36.098  5464  5464 D ButtonWidget: Broadcast action: android.intent.action.SCREEN_ON
02-06 11:59:36.098  5464  5464 D ButtonWidget: AppWidgetId: -1
02-06 11:59:36.103  5464  5464 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: true, usesWifi is: true
02-06 11:59:36.103  5464  5464 D MediaPlayCtrlsWidget: Broadcast received: 
02-06 11:59:36.103  5464  5464 D MediaPlayCtrlsWidget: Broadcast action: android.intent.action.SCREEN_ON
02-06 11:59:36.103  5464  5464 D MediaPlayCtrlsWidget: AppWidgetId: -1
02-06 11:59:36.110  5464  5464 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: true, usesWifi is: true
02-06 11:59:36.113  5464  5464 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: true, usesWifi is: true
02-06 11:59:36.113  5464 23189 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: true, usesWifi is: true
02-06 11:59:36.121  5464  5464 D SurfaceView@cacb0ac: 212644012 updateSurface: has no frame
02-06 11:59:36.121  5464  5464 I ViewRootImpl@fde5bf6[WebViewActivity]: registerCallbackForPendingTransactions
02-06 11:59:36.122  5464  6494 I ViewRootImpl@fde5bf6[WebViewActivity]: mWNT: t=0xb400007df1e7cbf0 mBlastBufferQueue=0xb400007c21e404f0 fn= 2 caller= android.view.ViewRootImpl$6.onFrameDraw:5539 android.view.ViewRootImpl$2.onFrameDraw:2103 android.view.ThreadedRenderer$1.onFrameDraw:788 
02-06 11:59:36.123  5464  5464 D LocBroadcastReceiver: Got single accurate location update: Location[<<SCRUBBED>>]`

[log.txt](https://github.com/home-assistant/android/files/14185846/log.txt)
(More complete log starting before command sent, and ending after they finally ran)

**Comment by dshokouhi** [comment]
so it does indeed look like the app is still being put to sleep as we do not see any data being relayed after the app gets teh notification

```
02-06 11:55:22.623  5464 19896 D FCMService: From: 331041709873
02-06 11:55:22.632  5464  5464 D MessagingService: Request location update
```

so here we can see the request being processed and from there the app fires an intent to be received and updated upon. However nothing happens which is the symptom of the app being put to sleep. You can even see the gap in time where nothing happens.

```
02-06 11:55:22.635  5464 18218 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: true, usesWifi is: true
02-06 11:55:22.637  5464  5536 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=d4a5926c-6e55-4b3a-aa12-ff560f94dbd2, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
02-06 11:55:22.698  5464  5502 D NextAlarm: Next alarm is scheduled by com.android.providers.calendar with trigger time 1707255000000
02-06 11:55:22.698  5464  5502 D NextAlarm: Skipping update from com.android.providers.calendar as it is not in the allow list
02-06 11:55:22.713  5464 10900 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: true, usesWifi is: true
02-06 11:55:22.716  5464 10900 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: true, usesWifi is: true
02-06 11:55:22.975  5464 10900 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: true, usesWifi is: true
02-06 11:55:23.052  5464 23189 I SensorReceiver: Sensor updates and sync completed
02-06 11:57:27.833  5464 19989 W FirebaseMessaging: Unable to log event: analytics library is missing
02-06 11:57:27.834  5464 19989 D FCMService: From: 331041709873
02-06 11:57:27.842  5464  5464 D MessagingService: Request location update
02-06 11:58:41.000  5464 20237 W FirebaseMessaging: Unable to log event: analytics library is missing
02-06 11:58:41.001  5464 20237 D FCMService: From: 331041709873
02-06 11:58:41.007  5464  5464 D MessagingService: Request location update
02-06 11:59:35.956  5464  5464 I ViewRootImpl@fde5bf6[WebViewActivity]: handleAppVisibility mAppVisible = false visible = true
02-06 11:59:35.956  5464  5464 I ViewRootImpl@fde5bf6[WebViewActivity]: stopped(false) old = true
02-06 11:59:35.956  5464  5464 D ViewRootImpl@fde5bf6[WebViewActivity]: WindowStopped on io.homeassistant.companion.android/io.homeassistant.companion.android.webview.WebViewActivity set to false
02-06 11:59:35.961  5464  5464 D WebviewActivity: Matter/Thread step changed to NOT_STARTED
02-06 11:59:35.966  5464  5464 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: true, usesWifi is: true
02-06 11:59:35.967  5464  5464 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: true, usesWifi is: true
```



> This section seems odd to me - specifically "registerCallbackForPendingTransactions" happens a couple milliseconds after screen on, and before the things that are supposed to happen, do.

this is safe to ignore as its to deal with the `view` of the app and not a background service

**Comment by dshokouhi** [comment]
have you had a chance to see if there were more battery related settings to turn off? Our logs show things work as expected as the symptoms do indeed relate to the app going to sleep before it can make the location request.

**Comment by dshokouhi** [comment]
closing due to lack of response from author

**Comment by hardwareadictos** [comment]
Well this is still happening on October, was happening on my Pixel 7 on android 14 and now also on 15. Once app is killed on the background no more location reporting breaking all my "out of home" automations. Disabled battery saving on android settings, all permissions are enabled and on Companion app y just enabled all that the "Troubleshooting" docs suggest. Seems and Android side issue but, did someone managed to fix this? I am missing something?

**Comment by EdmisP** [comment]
Can confirm issue with Pixel 6pro and Pixel 7 phones

**Comment by nalpo** [comment]
Same problem with my Pixel 5.

**Comment by Jan19901002** [comment]
Hey,

I have the same problem..

Did someone find a solution?
