### ISSUE TITLE
Misspelled "Set up" in settings

### ISSUE THREAD

**Issue by adam5532** [home-assistant/android#4195]
**Home Assistant Android app version(s):**
2024.1.5-full

**Android version(s):**
14
**Device model(s):**
Galaxy S21 5G
**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
In Companion App settings, NFC Tags and Manage Tiles sections, "Set up" is misspelled as "Setup". "Setup" is a noun and can not be used here. The compound verb is spelled "Set up" (two words).

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by adam5532** [comment]
Hi Daniel,
> are all of those incorrect?
I will check when I edit the file.

> feel free to make edits to that file directly

When I click "Edit in place", it says:
"You need to fork this repository to propose changes.
Sorry, you’re not able to edit this repository directly—you need to fork it and propose your changes from there instead."

I am signed into my GitHub account.
Please let me know how to proceed.

Thanks!
Adam

**Comment by dshokouhi** [comment]
so github should walk you through the steps but yes you would first fork the repository then when making changes it will ask to create a "patch" branch where the edits will be. From there it will ask to submit a pull request where we will review.

**Comment by adam5532** [comment]
Hi Daniel,
I'm quite an experienced programmer, but don't have much experience with GitHub. I find it exceedingly unintuitive and frustrating. I've forked it, and see that I can now edit and commit changes when ready, but I can't find the most basic thing: searching the file text for a string. The search window at the top wants to find repositories and not strings. Chrome's "find in page" doesn't seem to search the edit window. If I open it in github.dev instead, I can sort of search for strings, except that it returns results for all the files in the repository, and there's now no "Commit changes" button. Your help is appreciated!
Thanks,
Adam

**Comment by dshokouhi** [comment]
when you are in the editor, make sure to click in the edit field and then you can press "ctrl+f" and the editor search prompt will show up, it does look a bit hidden on first glance

![image](https://github.com/home-assistant/android/assets/1634145/73d3b240-55a3-406e-9623-9cf7c3d39e4e)
