### ISSUE TITLE
The wifi_connection sensor updates in the app, but does not update on the server  

### ISSUE THREAD

**Issue by shokwaav** [home-assistant/android#4199]
**Home Assistant Android app version(s):**

**Android version(s):** Android 14

**Device model(s):** Google Pixel 6 Pro and Pixel 7a

**Home Assistant version:** 2024.2.1-full

**Last working Home Assistant release (if known):** 2024.1

**Description of problem, include YAML if issue is related to notifications:**
The Wifi connection sensor shows updates to the wifi connection name in the app, but it doesn't update on the server.
Other wifi related sensor such as the BSSID updates fine.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Where are the logs? Without logs we can't help.

**Comment by shokwaav** [comment]
Sorry about that, when trying to replicate the issue for the logs it seems to have fixed itself. I'll try to get the log if I notice it happening again.
