### ISSUE TITLE
Allow installation on android tv and allow use of microphone built in into most remotes to trigger home assistant local voice assistant.

### ISSUE THREAD

**Issue by GrzegorzDrozd** [home-assistant/android#4209]
**Is your feature request related to a problem? Please describe.**

I have multiple devices in multiple rooms that all have convenient way to trigger local assistant. They all have a button that enables microphone for easy assistant interactions. They all use similar OS and would require just one solution. I have android tv in my sony tv, I have 2 chrome casts in two different dumb tv. All of them have microphone in their remotes.

**Describe the solution you'd like**

Install companion app. Replace default google assistant with HA. Use remote and voice to interact with HA.

**Describe alternatives you've considered, if any**

Various devices that are all buggy or listen all the time - concern for privacy. 

**Additional context**

**Comment by dshokouhi** [comment]
As the home assistant frontend does not support remote navigation we can't support Android TV. You are free to sideload the APK and use it as is.

**Comment by GrzegorzDrozd** [comment]
Could the assistant feature be extracted from source code and offer just assistant ?

**Comment by yoe** [comment]
@dshokouhi Can you expand a bit on why it's not possible to support Android TV? What does the "remote navigation" thing mean? What would it take to change this? Is perhaps a separate, limited, app an option?

Personally, I would like to be able to use the HA app on my Android TV device to check the status of a few of the things in my HA installation, and/or toggle certain switches; and while, yes, sideloading is theoretically possible, it's a bit of a mess and installing directly from an app store would be preferable if that's achievable.

**Comment by GrzegorzDrozd** [comment]
> @dshokouhi Can you expand a bit on why it's not possible to support Android TV? What does the "remote navigation" thing mean? What would it take to change this? Is perhaps a separate, limited, app an option?

I think the issue is that Home Assistant UI is actually a website and browsers on Android are lacking good remote-to-finger emulation :/ BUT maybe using phone as a input?

**Comment by GrzegorzDrozd** [comment]
On the other hand: I think for majority of users notifications + assistant to ask questions would be enough :)
