### ISSUE TITLE
Send deviceID, deviceName with data when action click

### ISSUE THREAD

**Issue by wbilger** [home-assistant/android#421]
Would it be possible to send deviceID and deviceName (name as entered in App) with data when an action is clicked.
Would make possible to send a notification back to device that clicked notifiaction action, not just to user that clicked.

**Comment by robbiet480** [comment]
[This would be taken care of by my proposal to unify and upgrade push notifications in Home Assistant Company for Android and iOS](https://github.com/home-assistant/companion.home-assistant/issues/176).

**Comment by wbilger** [comment]
Sounds great, awesome work!

**Comment by dshokouhi** [comment]
`device_id` is now included with the event since #693
