### ISSUE TITLE
Missing icons issue when returing from backgroud after a while

### ISSUE THREAD

**Issue by Paxy** [home-assistant/android#4225]
**Home Assistant Android app version(s):**
2024.1.5-full
**Android version(s):**
13 TKQ1
**Device model(s):**
Poco F5
**Home Assistant version:**
2024.2.3
**Last working Home Assistant release (if known):**
I think versions before 2024. did not have the same issue.
**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
Screen with the issue:
![Screenshot_2024-02-24-15-31-14-370_io homeassistant companion android](https://github.com/home-assistant/android/assets/10741777/caf58202-27c3-4bf7-b57f-a8fa1b243351)

Normal screen (after the app kill and start):
![Screenshot_2024-02-24-15-32-34-233_io homeassistant companion android](https://github.com/home-assistant/android/assets/10741777/4bd50c77-879a-41f5-a6bd-30e52bf02331)

**Additional information:**
After some time, when HASS android app go into background, when I activate app I am missing some icons.
As soon as I kill the app and start it again, everything is ok.
When I try to change tabs, I see even more icons missing on different screens.
In MIUI, the HASS app is set to "No restrictions" for battery savers, so the system does not kill any app's process.
The chrome version does not have the same issue, but I am not sure it is kept alive in the background.

**Comment by dshokouhi** [comment]
This is not an issue the app can solve you need to file an issue with the HA frontend
