### ISSUE TITLE
Incorrect icon for mdi:home-assistant 

### ISSUE THREAD

**Issue by chelming** [home-assistant/android#4252]
**Home Assistant Android app version(s):**

**Android version(s):**
14
**Device model(s):**
Pixel 8 Pro
**Home Assistant version:**
2024.03
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
If a blueprint allows you to customize the notification icon and defaults to mdi:home-assistant, the old logo is d displayed when `notification_icon: "mdi:home-assistant"` is used.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![Screenshot_20240307-055416.png](https://github.com/home-assistant/android/assets/7746625/6b9feed7-a587-45ac-b190-a1fc8cbd4b36)

one with notification_icon and one without.
**Additional information:**

**Comment by jpelgrom** [comment]
This is not incorrect, as the MDI don't hasn't updated: https://pictogrammers.com/library/mdi/icon/home-assistant/. They plan to remove brand icons like this in the future so the 'fix' would be not setting the icon (or something that doesn't exist) so the app uses its own icon.

**Comment by dshokouhi** [comment]
Closing as this is working as expected. Try using junk characters for the icon, the app will default to the correct icon if we cannot determine a proper icon.

example: `mdi:abcd123`

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/notifications/NotificationFunctions.kt#L222-L226
