### ISSUE TITLE
Can't change borad since HA 2024.3.0

### ISSUE THREAD

**Issue by Mike710Shine** [home-assistant/android#4257]
**Home Assistant Android app version(s):**

**Android version(s): 13

**Device model(s): Xiaomi MI 10 Pro

**Home Assistant version: 2024.3.0

**Last working Home Assistant release (if known): 2024.2.5

**Description of problem, include YAML if issue is related to notifications:**
Since the update to Home Assistant 2024.3.0 i can't change to an other Board then the default board. In the left upper corner i only have an arrow but when id touch on it nothing happens. In the Version 2024.2.5 it works.

```

```

**Screenshot or video of problem:**
![Screenshot_2024-03-08-11-44-20-483_io homeassistant companion android-edit](https://github.com/home-assistant/android/assets/157489998/5a589ae2-63df-4daf-8117-a94c1ecdfd1b)

**Additional information:**

**Comment by dshokouhi** [comment]
You need to turn off sub view on the dashboard.
