### ISSUE TITLE
Location is not reporting in Android companion app (version 2024.1.5-full) 

### ISSUE THREAD

**Issue by BubblesOnBrain** [home-assistant/android#4280]
**Home Assistant Android app version(s):**  2024.1.5-full

**Android version(s):** 14 update: 3/5

**Device model(s):** Pixel 8 Pro, Pixel 7

**Home Assistant version:**

**Last working Home Assistant release (if known):** unknown, stopped working 3/15

**Description of problem, include YAML if issue is related to notifications:**
Locations are not updating for 2 android based phones (also having an issue with an IOS device as well)

**Companion App Logs:**

Seeing all  "failed to send" error messages in location tracking log. 

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
please attach the logs, otherwsie we cannot proceed with troubleshooting.

**Comment by dshokouhi** [comment]
Closing due to lack of response from author
