### ISSUE TITLE
Android App UI in Italian but settings in Spanish 

### ISSUE THREAD

**Issue by lucaberti** [home-assistant/android#4285]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

My Android app is set to Italian language, but all of a sudden the app specific settings switched to Spanish. There is no way to go back to Italian, not even by killing and reopening the app.

### Describe the behavior you expected

Setting in Italian

### Steps to reproduce the issue

1. Set HA in Italian
2. Enter in app specific settings and change some
3. Go back to dashboard
4. Reopen app specific Settings

### What version of Home Assistant Core has the issue?

core 2024.3.1
App 2024.1.5-full

### Which operating system are you using to run this browser?

Android

**Comment by dshokouhi** [comment]
closing due to lack of response from author

**Comment by lucaberti** [comment]
Sorry, I was away for a while... And sorry for have it posted in the worng place ;)
Indeed the language selection was on "Espaniol". Shoul not the main and the compainon app sync language?

**Comment by dshokouhi** [comment]
> Sorry, I was away for a while... And sorry for have it posted in the worng place ;)
> Indeed the language selection was on "Espaniol". Shoul not the main and the compainon app sync language?

No they won't be kept in sync you have to change it
