### ISSUE TITLE
Battery voltage problem

### ISSUE THREAD

**Issue by danutchereches** [home-assistant/android#4286]
**Home Assistant Android app version(s):** 20240307.0

**Android version(s):** 14

**Device model(s):** OnePlus Nord 3

**Home Assistant version:** 2024.3.1

**Last working Home Assistant release (if known):** N/A

**Description of problem, include YAML if issue is related to notifications:**
The reported battery voltage is wrong.

**Screenshot or video of problem:**
![image](https://github.com/home-assistant/android/assets/1137243/79a7cb9f-d002-4de1-bcc3-931aa1ca3cfd)

**Additional information:**
Similar to issue #2846 a voltage divisor might be necessary.

**Comment by dshokouhi** [comment]
> a voltage divider might be necessary.

please adjust the setting `Battery Current Divisor` on the page in the screenshot to fix the issue, that is exactly what this for ;)

**Comment by dshokouhi** [comment]
sorry misread, but please try the current setting to see if that helps. Reopening for now

**Comment by danutchereches** [comment]
> please try the current setting to see if that helps

It helps with the power, but the voltage is still wrong.

Also, I think the precision is also an issue, as the voltage basically is rounded to 3 or 4 volts.

**Comment by dshokouhi** [comment]
> Also, I think the precision is also an issue, as the voltage is rounded to 3 or 4 volts.

so the value that you see in the attribute is the raw data we get we just add a divider as most devices report in micro volts and we convert to voltage however that does not seem to be the case here. First device I have seen to have different unit for volts. Its quite possible your device may not report precisely but we can see what happens after adding a divider here.

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt#L349

**Comment by danutchereches** [comment]
> Its quite possible your device may not report precisely

I think you're right.
I tried Accu​Battery and it reports only 3 or 4 volts.

If `EXTRA_VOLTAGE` is an int, it makes sense.

**Comment by jpelgrom** [comment]
> Its quite possible your device may not report precisely

To add more context to this: the app does not round the value reported by the system.

> If `EXTRA_VOLTAGE` is an int, it makes sense.

The value is an integer but it is supposed to be in millivolts, so you can get something like `3.141 V`. Unfortunately for you it looks like OnePlus has decided to report volts instead.
