### ISSUE TITLE
Only create notification when it is already open

### ISSUE THREAD

**Issue by khenderick** [home-assistant/android#4295]
**Is your feature request related to a problem? Please describe.**

At this moment, we can use an automation to send a notification to a companion app. Using a well specified tag, we can later update the notification with newer contents. I use this for notifying that a person is detected on my property. I update the notification as better images become available. When the person is gone for a while, it updates the notification to indicated it is no longer active and more a FYI.

When I decide that I'm fine with this situation (e.g. it's an expected visitor), I can swipe away the notification. Possibly after having clicked on the notification to briefly watch the live feed. However, my automation is unaware and will send updates, basically creating a new notification.

**Describe the solution you'd like**

It would be nice if an automation could indicate towards the app that it should only create a notification if a notification with that tag is already open, or discard the notification otherwise. I can then let my automation that detects a new person specify that a notification must be created with the given tag, and my automation that updates the notification with new images can specify that it only needs to update if the notification is still present.

**Describe alternatives you've considered, if any**

It is possible to receive a notification cleared event in HA. This works only if the notification is cleared (e.g. swiped away), but not if it has been clicked on. Even if it would be possible to execute a script or something if the action was clicked, it would still require a lot of work on HA side to keep track of the fact that certain notifications would be gone, and others would still be active.

**Additional context**

N/A

**Comment by dshokouhi** [comment]
> It would be nice if an automation could indicate towards the app that it should only create a notification if a notification with that tag is already open, or discard the notification otherwise. I can then let my automation that detects a new person specify that a notification must be created with the given tag, and my automation that updates the notification with new images can specify that it only needs to update if the notification is still present.

this sounds like something you should be keeping track of and not the app. You send the notification to the app so you know when you want it to update. If you must know if the notification is currently active you can use the active notification sensor to see the notification data posted or you can use the received and cleared events that the app can send.

**Comment by jpelgrom** [comment]
Going to close this as an extremely specific use case, which is not something the app should handle, for which there are viable alternatives as mentioned by @dshokouhi
