### ISSUE TITLE
REQUEST: read NFC tags and fire service

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/android#431]
I really like this app : HassNFC, it's a small Android app that reads NFC tags and fires a service, would be great if this could also be implemented in this great app..

More info: https://community.home-assistant.io/t/hass-nfc-control-home-assistant-with-nfc-tags/54227

**Comment by pergolafabio** [comment]
It's also included in ariela, works different there, they created a sensor... Based on the value you read on nfc, the sensor changes

**Comment by balloob** [comment]
We should do neither, we should get a new webhook event for mobile app `nfc_card_scanned` that allows mobile app integration to build up known NFC cards and their IDs.

**Comment by dshokouhi** [comment]
Sounds like something else to harmonize maybe? iOS uses NFC in universal links: https://companion.home-assistant.io/docs/integrations/universal-links

**Comment by GrandNewbien** [comment]
Universal links would by far be the best thing for Android. You can call any service you want then.

**Comment by David-Development** [comment]
Is anyone working on this already? Maybe I could try looking into how this could be implemented by using the universal links as @GrandNewbien suggested?  If someone wants to help, feel free. This would be my first contribution to this project

**Comment by pergolafabio** [comment]
i can help with testing , not coding,

using NFC tags every day, but still with the Hass NFC app , instead of the official one

**Comment by David-Development** [comment]
@pergolafabio Just created a first draft of how nfc support could look like. There are a few more things to discuss but the current state already works quite well on my phone so feel free to test it. (check out the [branch](https://github.com/David-Development/android-1/tree/nfc-support), build the app, run it on your phone, open the app, go to the app configuration, scroll down, click on "NFC Tags" to start generating new nfc tags). Happy testing 🙂

**Comment by pergolafabio** [comment]
cool, following that one
will it be soon in beta? i prefer to test then

**Comment by pergolafabio** [comment]
gonna, close, not needed anymore now
