### ISSUE TITLE
Allow to add Home wifi also by MAC

### ISSUE THREAD

**Issue by distante** [home-assistant/android#4311]
**Is your feature request related to a problem? Please describe.**

I have a portable mini router that I take when I go to visit family or vacations, so I can connect it to some guest wifi and act like a filter between my devices and the (possible public) open wifi. 

It has the same SSID of my home network, so I just have to set it once and all my other devices connect direct to it. This also allows me to use my wifi baby tapo cam in an untrusted network while blocking unknown devices and internet access. 

The problem I have, is that the home assistant companion app keeps trying to log in to the local ip address, which will never be successful. 

**Describe the solution you'd like**

The companion app should allow us to add a mix of SSID and Mac address, so if the SSID is a match but the Mac address don't, the would not consider it a home wifi. 

**Describe alternatives you've considered, if any**

Stablish a VPN connection to my home but it would just work for one device at the time and I need to toggle it too often. 

**Additional context**

Nothing.

**Comment by jpelgrom** [comment]
I think this is already supported by using a BSSID: http://companion.home-assistant.io/docs/troubleshooting/networking?_highlight=bssid#setting-up-the-app. This treats a single access point as your home WiFi instead of anything with the network name.

**Comment by dshokouhi** [comment]
> so if the SSID is a match but the Mac address don't, the would not consider it a home wifi.

in this case don't add the SSID but only add the BSSID you wish to connect to. If you have 3 MACs that share the same SSID and only want 2 to connect youll want to add the 2 BSSID instead of the SSID mixed with the BSSID

**Comment by distante** [comment]
Thank you for your replies @jpelgrom and @dshokouhi 

The BSSID has to be added manually, letter by letter correct? I have not seen any "Add My_Wifi" button that adds it as BSSID and adding `BSSID:1A:2B:3C:4D:5E:6F` will not let me know to which SSID that BSSID has.

Doesn't the companion app already has that data and it just needs to show it?

**Comment by dshokouhi** [comment]
> The BSSID has to be added manually, letter by letter correct?

yes it needs to be entered like the docs describe



> I have not seen any "Add My_Wifi" button that adds it as BSSID and adding `BSSID:1A:2B:3C:4D:5E:6F` will not let me know to which SSID that BSSID has.

you wont see a add button for BSSID, only SSID as that is the most common case. As this is something only you as the user will know its up to you add it as you need for your network. The app cant make that distinction and since there are so many cases to account for we leave it in your hands

**Comment by distante** [comment]
Ah OK. I though it was possible to add the current connected network BSSID.

 I will need to make a list of all the allowed BSSIDs. And pass them to each of my family devices manually.

**Comment by dshokouhi** [comment]
closing as support was already added for this
