### ISSUE TITLE
Sort automations by "last triggered"

### ISSUE THREAD

**Issue by tomwaldnz** [home-assistant/android#4314]
**Is your feature request related to a problem? Please describe.**

Sometimes I would like to know why a device is in a particular state - for example "why did my air conditioner turn off"? This is often done by one of my 200+ automations. It would be useful to be able to sort automations by "last triggered" date so I can work out which automation I need to fix.

**Describe the solution you'd like**

In the Android automations page it would be useful to be able to sort by last triggered date.

**Describe alternatives you've considered, if any**

Scrolling to search manually works but is quite slow with a large number of automations.

**Additional context**

**Comment by jpelgrom** [comment]
This screen is handled by the frontend. Please create a feature request for the frontend instead: https://github.com/home-assistant/frontend/discussions
