### ISSUE TITLE
Assist on Wear OS TTS volume control

### ISSUE THREAD

**Issue by gianlucasullazzo** [home-assistant/android#4317]
**Is your feature request related to a problem? Please describe.**
On my Galaxy Watch 4 (and presumably this applies to all Wear OS devices configured to use Assist as the default watch assistant), there is no option to adjust the volume level. This results in an extremely low voice volume (especially when compared to the "Hey Google" assistant on the same device). I'm utilizing Nabu Cloud for both Text-to-Speech (TTS) (using FabiolaNeural) and Speech-to-Text (STT) services. When I tested the TTS functionality through the mobile app notification service, the volume was significantly louder than that of the Assistant.

**Describe the solution you'd like**

I would like to have the ability to adjust volume level for HA:Assist.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
> there is no option to adjust the volume level.

on my pixel watch

Settings > Sounds > Adjust media volume level

do you not have that on Samsung?

**Comment by gianlucasullazzo** [comment]
> do you not have that on Samsung?

Hi @dshokouhi and thanks for your reply. Yes the watch has the functionality to adjust the volume but it seems it does not have any effect on Assist volume.

**Comment by dshokouhi** [comment]
and you tried adjusting every volume stream? specifically the media/music stream as that is used for TTS audio. There is more than 1 volume on the device.

**Comment by gianlucasullazzo** [comment]
yes of course..all volumes are set to max level

**Comment by dshokouhi** [comment]
is google assistant volume low?

adjusting volume level is not something the apps can do on Wear OS, its a special permission that is not offered on Wearables. So we have to look into what other options there are. Have you tried a different TTS service?

**Comment by gianlucasullazzo** [comment]
Let me summarize:

- Google Assistant is good, as it is loud enough to be heard in a noisy room. 

- Text-to-speech using the `notify.mobile_app_galaxy_watch4` service with the `media_stream: alarm_stream_max` setting is quite acceptable, almost as loud as Google. 
- The text-to-speech by Samsung and the text-to-speech by Google (embedded in the watch OS) are the same in terms of volume.
- However, the HA: Assistant is very low in volume. It is not able to be heard if other people are speaking in the room.

**Comment by gianlucasullazzo** [comment]
I just recorded a short session beetween google assistant and HA:Assist. This is the "spectrum" of the audio trace:
![image](https://github.com/home-assistant/android/assets/75364722/4e65c504-dc6b-4a0c-89df-bc7c62f15660)

**Comment by dshokouhi** [comment]
what about a different Assist TTS service? Even though it works fine on the phone the audio file it provides  may be low for a wearable.

**Comment by gianlucasullazzo** [comment]
I have deleted all other TTS providers because I was not satisfied with the quality of Italian pronunciation. However, I can try using Google Translate or Polly again.

**Comment by dshokouhi** [comment]
unfortunately thats really the only thing you can do. Either change the TTS engine in Assist

![image](https://github.com/home-assistant/android/assets/1634145/352a26df-4383-421e-8101-e8b2b5cb21a0)

or adjust the Media volume stream on the watch directly

![image](https://github.com/home-assistant/android/assets/1634145/3935a264-2d3b-4c9d-9308-18188d79c797)

the app does not control device volume and is not allowed to but if you hear the correct volume using Google Assistant then that points to an issue with the TTS engine thats providing the audio file.

**Comment by jpelgrom** [comment]
Just tested this on a Galaxy Watch 4, with media volume at about 50% and they sound similar in volume to me - if I had to choose I'd even say Assist is louder. The speaker is easy to block with your arm though 

Even with HA Cloud there are a lot of choices for TTS. Could you share your settings / try using the default to rule out the voice (Home Assistant Cloud + Italian (Italy) + ElsaNeural)?

![watch volume setting](https://github.com/home-assistant/android/assets/8148535/294c4608-713f-440f-aba7-f3f24e5bf446)

![TTS setting](https://github.com/home-assistant/android/assets/8148535/c107e561-9245-40cc-992f-ee18b2cc6170)

**Comment by gianlucasullazzo** [comment]
> Just tested this on a Galaxy Watch 4, with media volume at about 50%

in my watch it seems the media volume level does not affect at all Assist volume

> The speaker is easy to block with your arm though

I exclude this because I also tried with watch not on body

> Could you share your settings

Yes, of course. What settings do you need?
![image](https://github.com/home-assistant/android/assets/75364722/1a966d07-041a-4de8-a588-7ab886a0bb8a)
![photo1712179668](https://github.com/home-assistant/android/assets/75364722/3de88af0-fde0-426c-9fec-b66ce040cd85)

**Comment by jpelgrom** [comment]
> Yes, of course. What settings do you need? ![image](https://private-user-images.githubusercontent.com/

Can you try changing the voice from FabiolaNeural to ElsaNeural (default)? Does it make any difference?

Also which version of the app are you using? You can check on your watch when scrolling to the bottom of the main screen > Settings > version at the bottom. I'm using the beta which does include a change related to audio for Assist which may be causing the difference.

**Comment by gianlucasullazzo** [comment]
> Can you try changing the voice from FabiolaNeural to ElsaNeural (default)? Does it make any difference?

No difference



> Also which version of the app are you using?

![image](https://github.com/home-assistant/android/assets/75364722/4b9383bb-3ce0-4182-ad8f-cc00f9fd2554)

**Comment by dshokouhi** [comment]
have you tried restarting the wear OS device to see if that helps?

**Comment by gianlucasullazzo** [comment]
> have you tried restarting the wear OS device to see if that helps?

Yes, but no success..Consider I'm a software engineer and restart saved my life many times..but not in this case🤣

**Comment by dshokouhi** [comment]
yea were trying to think of what else to check because volume control in specific is not allowed on Wear OS because the permission to control DnD does not exist there and controlling volume will alter DnD status. It _should_ be linked to media but thats not the case. I think at this point the best bet is to try different combinations of voices on the watch to see if any might be better or not. Try different languages and engines. This is not going to be easy to nail down unfortunately.

**Comment by dshokouhi** [comment]
@gianlucasullazzo we had some updates to Assist related to audio focus, can you update teh watch app and see if that makes the situation better for you?

**Comment by gianlucasullazzo** [comment]
Hi @dshokouhi, thanks for reaching out on this. I just have updated the app but volume seems not louder..actually it seems lower :(

**Comment by NithinKumaraNT** [comment]
Hi @dshokouhi , I also face the exact same issue as @gianlucasullazzo. For the Google engine TTS setting their seems to be amplify the speech output for google assistants. You can find this under,
General > Text-to-speech > TTS engine settings > Amplify speech volume.
When this is enabled, the google tts volume is louder.

May be this hint would enable you to debug the issue :)

**Comment by jpelgrom** [comment]
Assist does not use the watch TTS services but audio files generated on the server, so that toggle unfortunately seems irrelevant here.

**Comment by xandervanerven** [comment]
I had this exact problem on my wear os watch, for me the solution was:
Bixby was not setup , apparently when you set it up a new volume setting appears in the general volume 
![Screenshot_20240607_021649_settings](https://github.com/home-assistant/android/assets/6200539/78acdd7e-b48f-4b76-b9e1-78ae7fab80fe)
settings for bixby voice assistant. This volume was 50% for me, changed this volume to 100%. Now my Assist volume is very loud. Seems like the assist app is somehow affected by the bixby volume setting. Hope this might help someone with similar issues.

**Comment by gianlucasullazzo** [comment]
Fantastic!!It worked. Thanks for sharing
