### ISSUE TITLE
The app is ignoring my theme on my new phone pixel 8 pro

### ISSUE THREAD

**Issue by ELY3M** [home-assistant/android#4324]
![PXL_20240405_184613499~2](https://github.com/home-assistant/android/assets/10571497/9600cbca-3cfc-4060-9a62-50d435264efd)

I am not happy with what I see on pixel 8 pro 
Pixel 8 pro is on left

is there any way for me to override or have it ignore newer materials theme?    

**Home Assistant Android app version(s):**
latest.  I updated  everything to latest

**Android version(s):**
14
**Device model(s):**
Pixel 8 pro
**Home Assistant version:**
latest.  I updated  everything to latest

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
I want to know how to override the theme and go back to my old theme.   
I want my theme to be like black with blue borders like on phone on the right in the pic.    

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
https://github.com/home-assistant/android/assets/10571497/9600cbca-3cfc-4060-9a62-50d435264efd

**Additional information:**

**Comment by dshokouhi** [comment]
Can you reproduce the issue using chrome for android on the same device?

Also please provide the app version number if you are unable to reproduce using chrome for android on the same device

**Comment by ELY3M** [comment]
![Screenshot_20240405-140532](https://github.com/home-assistant/android/assets/10571497/1a49ce86-e314-42a4-88fd-0abcd8208d55)

**Comment by ELY3M** [comment]
I just opened it in chrome on pixel 8 pro.....   I hated how it looks....       
i will check on pixel 6

**Comment by dshokouhi** [comment]
you may need to change the theme per device, have you updated it in your user profile on each device? The theme in the 2 top pics looks completely different. Themes are set on a per device basis I think?

**Comment by ELY3M** [comment]
yes I did changed to my own dashboard on both devices.

**Comment by dshokouhi** [comment]
not dashboard, but theme

![image](https://github.com/home-assistant/android/assets/1634145/582ec707-40ac-4112-9d4e-76df2a86caac)

**Comment by ELY3M** [comment]
![Screenshot_20240405-141312.png](https://github.com/home-assistant/android/assets/10571497/ff3eeffc-d9a0-4bd7-9621-f2e49361cd3f)


Thank you!!!  I got it fixed.

**Comment by dshokouhi** [comment]
no problem happy to help!

**Comment by ELY3M** [comment]
ok, I am closing my issue
