### ISSUE TITLE
The ui in the app goes all black beta app android release 

### ISSUE THREAD

**Issue by skynet-network** [home-assistant/android#4329]
**Home Assistant Android app version(s):**

**Android version(s):14

**Device model(s):samsung s23

**Home Assistant version:2024.4.1

**Last working Home Assistant release (if known):2024.4.0

**Description of problem, include YAML if issue is related to notifications: UI is black after it reloads clearing cache in the Android ha app will fix it temporary
![Screenshot_20240406_164919_Home Assistant](https://github.com/home-assistant/android/assets/81412812/a5075cdd-a3c8-4ac2-886a-1b0fbd024347)

**Companion App Logs:**
attached
```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Can you reproduce using chrome for Android on the same device?

**Comment by skynet-network** [comment]
my tenant has the same issue on his  one plus android phone and the ui have
long loading time

It happens sporadically  especially when you loads a ui page you recently
has open.

**Comment by dshokouhi** [comment]
> my tenant has the same issue on his one plus android phone and the ui have long loading time It happens sporadically especially when you loads a ui page you recently has open.

This does not answer my question. Please check if you can reproduce using Chrome for Android on the same device. If not make sure Android System WebView is up to date in the play store and try disabling custom cards too.

**Comment by dshokouhi** [comment]
Closing due to lack of response from author.

**Comment by ruant** [comment]
I too have sort of the same issue.
The app stops loading "data", completely unresponsive, restarting the app and it starts loading "data" again.
It looks like it's trying to load data when I switch to another dashboard, but it's just hanging.
Sometimes it says something "unable to load" or something, then it looks like it's auto refreshing the entire app automatically and it loads fine.

I've tried using web only for a while, there is no issues then, so it's only through the companion app.

I'm on a Pixel 8 Pro phone, with the latest Android updates. (And webview)
Current Companion app version is: 2024.4.1-full
Home Assistant version is: 2024.4.4

**Comment by dshokouhi** [comment]
> The app stops loading "data", completely unresponsive, restarting the app and it starts loading "data" again.
> It looks like it's trying to load data when I switch to another dashboard, but it's just hanging.
> Sometimes it says something "unable to load" or something, then it looks like it's auto refreshing the entire app automatically and it loads fine.

These are actually frontend messaging and not provided by the app and definitely not he same behavior as described by the author.



> I've tried using web only for a while, there is no issues then, so it's only through the companion app.

by this you mean you used chrome for android on the same device?

Since the unable to load messages come from the frontend you should check the frontend repo for known open issues.  Also recommend disabling custom cards to rule them out as an issue as well.

**Comment by ruant** [comment]
Yeah, disregard my comment.
I dug around a bit and found I messed up some network/firewall stuff that wreaked havoc on my network making my phone loose connection completely at moments.
Not sure why it seemed to work fine on chrome for android, and not in the app.

Anyway, thanks for the reply, and sorry for the extra comment from me 🙏
