### ISSUE TITLE
Status bar not readable when using light theme 

### ISSUE THREAD

**Issue by anybody84** [home-assistant/android#433]
**Home Assistant Android version:** 1.7.2

**Android version:** 9

**Phone model:** Samsung Galaxy S9

**Home Assistant version:** 0.105.4

**Last working Home Assistant release (if known):**

**Description of problem:** When I'm using a light theme and the header is white or grey the status bar becomes not readable because all characters are also white/grey. I think they should change to dark ones automatically. 

**Screenshot of problem:**
![Screenshot_20200215-182540_Home Assistant](https://user-images.githubusercontent.com/37036776/74593088-281b1980-5028-11ea-89f2-577b14d2632c.jpg)

**Comment by federicoodorizzi** [comment]
Any update about this?

**Comment by bachoo786** [comment]
any updates on this? thank you.

**Comment by dshokouhi** [comment]
Hey would you guys be able to try the debug APK from: https://github.com/home-assistant/android/actions/runs/200575777 to see if it fixes the issue?

**Comment by bachoo786** [comment]
> Hey would you guys be able to try the debug APK from: https://github.com/home-assistant/android/actions/runs/200575777 to see if it fixes the issue?

Hi just tried the debug APK and facing the same issue.  See screenshot attached.  Thanks. 
![Screenshot_20200808-190523_Home Assistant](https://user-images.githubusercontent.com/6251030/89717011-21070f80-d9aa-11ea-8a57-1b0aec8b62f6.jpg)

**Comment by dshokouhi** [comment]
ok wasn't sure if it would, thanks for checking :)

**Comment by bachoo786** [comment]
No worries 👍

**Comment by dshokouhi** [comment]
just to confirm what theme are you guys using? is it the `Google Light Theme` that was mentioned in #715 ? or are there others too?

**Comment by bachoo786** [comment]
That's right its the Google light theme

**Comment by chriss158** [comment]
@dshokouhi i have a simple fix ready. Should i open up a pull request or would you add this to #713

**Comment by dshokouhi** [comment]
@chriss158 I think #713 is ready now, so maybe best for another PR so it doesn't require another review?

**Comment by chriss158** [comment]
Ok will open up a PR 👍
