### ISSUE TITLE
Home Assistant keeps stopping on login

### ISSUE THREAD

**Issue by onetoomany** [home-assistant/android#4332]
I’ve installed the root certificates from Let’s Encrypt, but apart from that I’ve got a completely vanilla cheap tablet. I had done a complete factory reset before installing Home Assistant. The previous version was working fine before I did the factory reset, so I think the issue is with the current version.

Welcome to Home Assistant App
Select Your Home Assistant Server - https://etc/…
Login screen user / pass → Login
Connect to Home Assistant, Device Name … Continue
“Home Assistant has stopped”, Open App Again

Version Mar 30 2024. Android 12.0, 1 5, 2023

Android log files attached.
[logcat.zip](https://github.com/home-assistant/android/files/14896988/logcat.zip)

**Comment by jpelgrom** [comment]
> completely vanilla cheap tablet

Android <8 by any chance (this is why the template you deleted is useful!)? If so this is a duplicate of #4323.

**Comment by prokopec-simon** [comment]
Had same issue with <8 Android (6.0), same issue as @jpelgrom mentions. Can confirm that downloading the 2024.4.1 Pre-release apk fixes the bug. Thank you for the fast fix. Probably worth keeping one issue open so people can find info about the issue easily before a full release is out.

**Comment by bleara** [comment]
I have just updated my Samsung TabS2 T813 Android 7.0 to use the latest release 2024.3.5 and I get the same “Home Assistant has stopped”, Open App Again problem. It has worked OK for years for me. I will try the pre release.

**Comment by bleara** [comment]
The 2024.4.1 Pre-release does fix the issue for me.

**Comment by dshokouhi** [comment]
Closing as duplicate of #4323. We should not keep issues open if they are already resolved. Fix will be rolling out soon.
