### ISSUE TITLE
Unable to connect - Retry screen not working properly 

### ISSUE THREAD

**Issue by Moohan** [home-assistant/android#4337]
**Home Assistant Android app version(s):** Version 2024.3.5-full
io.homeassistant.companion.android

**Android version(s):** 14 (Build number: AP1A.240305.019.A1)

**Device model(s):** Google Pixel 6

**Home Assistant version:** 2024.4.1 (has been present in previous versions too.

**Last working Home Assistant release (if known):** Unknown 

**Description of problem, include YAML if issue is related to notifications:** When there's a connection issue and I click 'refresh URL' the refresh screen doesn't seem to work: The 'refresh now' button doesn't have any effect and eventually the countdown will pass zero and start counting negatives, as in the screenshot.

The solution is just to close and reopen the app (when the connection is working).

**Screenshot or video of problem:** ![Screenshot_20240408-184822.png](https://github.com/home-assistant/android/assets/5982260/445df003-07aa-4868-b6ba-fe56ee76188d)

**Additional information:**

**Comment by dshokouhi** [comment]
This is actually a screen not controlled by the app, can you access your server in a browser on the same device?

**Comment by Moohan** [comment]
Tricky to replicate, as it seems to happen when I have basically no connection. I tried turning off WiFi and data but that produces a different message!

If I can't think of a way to replicate it reliably I'll just try to remember to check in a browser next time I see it organically.

**Comment by Moohan** [comment]
I just had the same issue (it's when my phone has a connection but it's super weak / unusable).

I tried my external address in a browser (chrome) and just had a white screen with the HA logo... Not sure if that's useful 🤷🏻‍♂️

![Screenshot_20240413-102535.png](https://github.com/home-assistant/android/assets/5982260/3e7ec213-f56d-4e99-86d5-f2cd873c1931)

**Comment by dshokouhi** [comment]
> I just had the same issue (it's when my phone has a connection but it's super weak / unusable).

thats not something the app can fix, the app got some communication and started to load and the frontend failed from there. Even a retry will fail if the connection is still not good. Its good enough to not cause the app to show the cannot connect pop-up.



> I tried my external address in a browser (chrome) and just had a white screen with the HA logo... Not sure if that's useful 🤷🏻‍♂️

yes the app is going to need the URL to work

going to close this issue as its not something the app can fix, if you believe its still an issue you can try filing a frontend issue

**Comment by Moohan** [comment]
[like]  James McMahon reacted to your message:
________________________________
