### ISSUE TITLE
Change of orientation redraws entire screen & app

### ISSUE THREAD

**Issue by grinddking** [home-assistant/android#4343]
**Home Assistant Android app version(s):**
2024.4.1-full
**Android version(s):**
Android 14
**Device model(s):**
Pixel 8 Pro
**Home Assistant version:**
2024.4.3
**Last working Home Assistant release (if known):**
n/a
**Description of problem, include YAML if issue is related to notifications:**
Adjusting or moving the device to landscape view in order to view more of the app horizonally results in redrawing the entire application. This causes a lot of issues if you are trying to find things on the screen and decide it might be easier to read in landscape mode. Your place on the screen will be lost when it redraws and will go back to the top of the app forcing you to find your place again in the application. This is especially cumbersome in the Frigate addon if you are trying to view past events and use the onscreen controls. This is affected across the whole app, it may have something to do with pinch-zoom functionality being applied, I am not sure. 

**Companion App Logs:**
[homeassistant_companion_log_3-13-2024_13-18-45.txt](https://github.com/home-assistant/android/files/14968315/homeassistant_companion_log_3-13-2024_13-18-45.txt)

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Does this only happen in frigate? What about a regular dashboard without any cameras? I can only reproduce this in the frigate tab but not in the main dashboard.

**Comment by dshokouhi** [comment]
Looks like this also happens on a desktop for any add-on  or ingress page too

**Comment by dshokouhi** [comment]
@grinddking please create a new issue with the HA frontend team so they can look into this issue. The app will not be able to fix it unfortunately. I think if you use a browser on your phone you will see the same issue there. 

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

**Comment by grinddking** [comment]
> @grinddking please create a new issue with the HA frontend team so they can look into this issue. The app will not be able to fix it unfortunately. I think if you use a browser on your phone you will see the same issue there.
> 
> https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

Thank you for the support, will do!
