### ISSUE TITLE
Improve Android widget personalization

### ISSUE THREAD

**Issue by vlaraort** [home-assistant/android#4345]
**Is your feature request related to a problem? Please describe.**
The current widgets (especially the service buttons), can only be customized changing a couple of colours and adding text, the size of the icon can't be personalized nor setting a custom colour.  The design is not very pretty in my opinion so it would be nice if some more personalizations could be done in the widgets

**Describe the solution you'd like**
Posibles customizations:
- Icon size
- Text size
- Icon position
- Background, text, icon colour.

**Describe alternatives you've considered, if any**
The alternative is to use the widget as is, but it does not match with my themes - layouts

**Additional context**
I have talked about the service button, that is the one that I use, but probably all widgets can be revisited.

**Comment by dshokouhi** [comment]
@vlaraort we should not combine multiple requests into the same one. Please submit a separate request for each feature you would like to see added. I also recommend looking at the features again because we do have some of these things already implemented. I will keep this request open so you can update it accordingly.

**Comment by vlaraort** [comment]
What do you mean? It only one feature request involving improving the widgets

**Comment by dshokouhi** [comment]
> What do you mean? It only one feature request involving improving the widgets

its a very generic request about the design of the widget and you list multiple things to change like icon size and background etc... each point needs to be its own request as the request will get closed if one item is completed and we will not keep it open for multiple items. You also mention revisiting the other widgets but I dont think you realize some of the features are already there.

**Comment by dshokouhi** [comment]
Closing as the request was not updated to contain a single feature as previously requested.
