### ISSUE TITLE
Stop high precision when connected wifi

### ISSUE THREAD

**Issue by merlino1975** [home-assistant/android#4349]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Stop high precision wgen connected in my wifi
**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
you can use the existing notification command to turn off high accuracy mode

https://companion.home-assistant.io/docs/notifications/notification-commands/#high-accuracy-mode

use this in your own automations :)
