### ISSUE TITLE
Direct Server Selection Widgets for Home Assistant Companion App

### ISSUE THREAD

**Issue by schulti** [home-assistant/android#4355]
The current method for **switching between multiple servers** in the **Home Assistant Companion App** requires users to either swipe with three fingers or navigate through a menu. This process can be somewhat cumbersome, especially for users managing multiple servers frequently.

Proposed Solution:
Introduce customizable **widgets for iOS and Android** that users can place on their **home screens**. Each widget would represent a specific server, allowing users to switch directly to their desired server with a single tap.

This feature would significantly enhance usability and accessibility for users who need to manage multiple servers regularly.

Benefits:
- Enhanced Accessibility: Simplifies the process of switching between servers, making it more accessible and less time-consuming.
- Customization: Users can set up their home screen with server-specific widgets according to their preferences and usage patterns.
- Improved User Experience: Reduces the steps required to switch servers, improving overall app usability and user satisfaction.

Implementation Considerations:
The widgets should be easy to set up and configure from within the app’s settings.
Each widget could display basic information about the server status or have customizable labels for clarity.

**Comment by dshokouhi** [comment]
> The current method for **switching between multiple servers** in the **Home Assistant Companion App** requires users to either swipe with three fingers or navigate through a menu.

you can already do this using the shortcuts feature

https://companion.home-assistant.io/docs/integrations/android-shortcuts



> Introduce customizable **widgets for iOS and Android**

this request can only be done for android, for iOS I suggest looking at existing app features to see if its already possible before requesting
