### ISSUE TITLE
Add control of device settings/peripherals

### ISSUE THREAD

**Issue by robert-alfaro** [home-assistant/android#436]
Being able to control mobile device's settings and peripherals such as screen brightness/timeout, Wifi, Bluetooth, etc. would be amazing.

Automations act upon the sensor data from mobile to send a control message back to the device to execute some action based on e.g. gps, battery, connected ble device name/mac, etc.

Currently I use an custom Android app named (see [Hass Phone Control](https://community.home-assistant.io/t/hass-phone-control/97182) on community forum) which uses Firebase Cloud Messaging to perform this behavior -- would be awesome to integrate such functionality and flexibility into the official companion app. The below example is just the beginning of what all could be possible.

### Example
If mobile exits Home zone, then an automation triggered on this state change sends message with the following control requests:
  - turn wifi off
  - turn bluetooth on
  - launch app, e.g. Google Play Music

Perhaps that automation (or another) has a condition to check battery level or charge state and could also send:
  - set brightness to 100%
  - set screen timeout to 5 minutes

Upon mobile entering Home or Work zone, another automation could reverse/set things appropriately.

**Comment by dshokouhi** [comment]
Is this app Hass Phone Control open source? Don't see it anywhere. but the forum  I wonder if the author would be willing to contribute here? :)

**Comment by robert-alfaro** [comment]
> Is this app Hass Phone Control open source? Don't see it anywhere but the forum I wonder if the author would be willing to contribute here? :)

He recently opened the source upon my request (personally I'm trying to get included with some Android development.. I'm a firmware/backend guy). The source is Java but obviously can be made kotlin.

https://github.com/Gerben321/homeassistant-phone-control-app

**Comment by apop880** [comment]
I'd love this idea as well. I currently use an app called Automate (similar to Tasker) for some of this (for example, for putting my phone in Vibrate mode when I get to work), but it would be great to unify everything in one place.

**Comment by thops** [comment]
I would love to be able to configure "do not disturb" settings.

**Comment by dshokouhi** [comment]
So this request is a bit of a catch-all and doesn't ask for a specific setting to control. I think to start with we will close this issue by enabling control of turning on/off one setting like DND.  Then we should send in requests for the rest of the commands this way we are not stuck with keeping one issue open while we handle all the possible cases.

I can definitely see a use case for DND as it can be tied to something like your `alarm_control_panel`.  BT, WiFi and screen brightness feel very trivial to me personally.  Launching an app is now possible since #1007 has been merged.
