### ISSUE TITLE
Incorrect location fetching on the full android version with no google services

### ISSUE THREAD

**Issue by lone-cloud** [home-assistant/android#4367]
I'm running the latest version of the full android home assistant apk that I fetched from the gh releases. I'm currently running a degoogled GOS with no google services on the latest android 14 on a pixel 8.

I acknowledge that I read the readme here which reads that the full version requires google services for the location and push notifications to work. While this does make sense for push notifications, by default GOS reroutes location requests to itself instead of allowing google services to resolve it. See here: https://grapheneos.org/usage#sandboxed-google-play
As such, the full version of the home assistant should not be breaking when fetching the location on phones without google services. Home assistant is currently the only app that I've seen that's behaving like this and it's also spamming this to my log:

```
1714253916.691 10444 10503 W GooglePlayServicesUtil: io.homeassistant.companion.android requires the Google Play Store, but it is missing.
1714253916.691 10444 10503 W GoogleApiManager: The service for com.google.android.gms.internal.location.zzdz is not available: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}

```

**Comment by dshokouhi** [comment]
Sorry there is no support for custom roms on the full version.

**Comment by lone-cloud** [comment]
@dshokouhi should I recreate this issue for the minimal version then? The app should still be attempting to get the location. All of the other apps that require the location still work for me. It's only the home assistant app that has this questionable hardwired dependencies on the google services.

**Comment by dshokouhi** [comment]
> @dshokouhi should I recreate this issue for the minimal version then? The app should still be attempting to get the location. All of the other apps that require the location still work for me. It's only the home assistant app that has this questionable hardwired dependencies on the google services.

The minimal version has 0 Google dependencies. Make sure you install the correct version.
