### ISSUE TITLE
wear verision without  google wearos requirement

### ISSUE THREAD

**Issue by calvinweb** [home-assistant/android#4379]
**Is your feature request related to a problem? Please describe.**

Some android watch dosn't use google wearos. So it will be unable to install it 
**Describe the solution you'd like**

add build without wearos requirement and auth via webview manually
**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
What watch are you talking about? None of the wear os watches have WebView. That sounds like a normal Android watch.

**Comment by calvinweb** [comment]
> What watch are you talking about? None of the wear os watches have WebView. That sounds like a normal Android watch.

I got the watch without google wearos from OPPO, It supports Webview.
I think showing a QR code for auth url is also ok if Webview is unavailable

**Comment by dshokouhi** [comment]
That is not wear os but something else that we won't be supporting. You can try to sideload the app but there is no support.

**Comment by calvinweb** [comment]
> That is not wear os but something else that we won't be supporting. You can try to sideload the app but there is no support.

The os refuse to install it due to lack of google wearos shared libraries
