### ISSUE TITLE
HA icon should be visible in side menu in Android Auto

### ISSUE THREAD

**Issue by mkrzosek** [home-assistant/android#4389]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

A lot of aplication in Android Auto can show in side menu. Unfortunatelly HA doesn't. It will be very useful if we have fast shortcut to HA

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
can you share a picture of what you are referring to? my HA icon is visible in teh side menu

**Comment by mkrzosek** [comment]
![20240418_173237](https://github.com/home-assistant/android/assets/43292478/a391d3de-3a28-464f-b54d-2ffd50689c53)

**Comment by mkrzosek** [comment]
> can you share a picture of what you are referring to? my HA icon is visible in teh side menu

Thanks for fast answer. I've attached  photo from this case.

**Comment by dshokouhi** [comment]
Those are OS controlled only. Usually first is maps, second is phone, 3rd is music and 4th is last accessed app. This is not something we can do. In your small screen you dont get 4 icons.

**Comment by mkrzosek** [comment]
In case that I have 2 icons only, it shown last app as a second. But for HA it doesn't works. Do you know where I can address this feature request to Android Auto?

**Comment by dshokouhi** [comment]
what happens if you open another app after havng opened the HA app? my HA app is always there when I switch between HA and the map.

**Comment by mkrzosek** [comment]
HA never cames out on sidebar  :-(

**Comment by dshokouhi** [comment]
maybe try your settings in the car or in the android auto app?

**Comment by mkrzosek** [comment]
I've tried, but not find anything what helps. There is a workaround that I can change the layout that the icons are at the bottom, then HA is visible, but it is not acceptable/comfortable for me.

**Comment by dshokouhi** [comment]
ok youll need to reach out to your car manufacturer, you can try one of those wireless android auto devices that  may let you override the display size? other than that we wont be able to help here unfortunately.
