### ISSUE TITLE
[FR] Use `device_class: enum` for string sensors with known enumerable values.

### ISSUE THREAD

**Issue by karwosts** [home-assistant/android#4393]
**Is your feature request related to a problem? Please describe.**

When writing automations with mobile app sensors, like the battery state, the UI does not offer any suggestions for possible states of these sensors:

![image](https://github.com/home-assistant/android/assets/32912880/1c55a1bf-679a-4ccc-ae00-2dcfabbed7dc)

**Describe the solution you'd like**
Since these sensors have fixed possible states which can be enumerated, set the sensor device_class to `enum` and enumerate the states. This will improve the UI experience. E.g.:

![image](https://github.com/home-assistant/android/assets/32912880/7165b303-fe08-47e4-b9ca-9d7c01ac81e6)

![image](https://github.com/home-assistant/android/assets/32912880/45e78afd-5386-4d4b-9029-95ba9ac4553a)

**Describe alternatives you've considered, if any**

**Additional context**

This was primarily raised in relation to battery_state sensor, but probably there are others as well that could also have the same treatment, such as battery health, charger type, etc. 

Thank you!

**Comment by dshokouhi** [comment]
Thanks for the request :) when you say "enumerate the strings" does that mean we need to store the possible states in the `mobile_app` integration or can we provide that somehow from the app directly? We can definitely set the device class easily but if HA core changes are needed then it may not be as straightforward for us :)

**Comment by karwosts** [comment]
That's a bit beyond my understanding. All I know is whatever creates the sensor (the integration?), it can list the possible options for the sensor under attribute `options:`. 

If I filed this in the wrong place, and it should be a part of the mobile_app integration, I apologize.

**Comment by dshokouhi** [comment]
> Is the app capable of publishing an attribute for this sensor?

yup we can indeed handle that here :) that is a much better approach instead of maintaining the values in the integration directly 😂

**Comment by jpelgrom** [comment]
> that is a much better approach instead of maintaining the values in the integration directly 😂 

\* much better _for the companion app's specific use case_ as an user of a generic integration uncoupled from the core version; for normal integrations it makes less sense

**Comment by dshokouhi** [comment]
@karwosts do you happen to know when this functionality was added? Trying to determine if we need to consider the HA core version here or not for this change. Looks like the device class `enum` has existed for some time.

**Comment by karwosts** [comment]
https://github.com/home-assistant/core/pull/82489

**Comment by dshokouhi** [comment]
ok so we probably should consider the HA version, based on the merge date 2023.1.0 i think.

also ran a quick test based on the data and easy enough changing device class and adding the `options` attribute is all we need to do. 

![image](https://github.com/home-assistant/android/assets/1634145/07fbd556-df78-4aa5-b07b-04b9ec48c8dd)
