### ISSUE TITLE
Samsung S23 not updating location 

### ISSUE THREAD

**Issue by Smittybk1** [home-assistant/android#4408]
**Home Assistant Android app version(s):**
2024.4.1

**Android version(s):**
Android 14

**Device model(s):**
Samsung S23 Ultra

**Home Assistant version:**
2024.4.1

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

Location is not reported to HA. I don't see my location on the map. I've followed all instructions and enabled everything in the instructions. I have added myself as a person and chose my phone as the tracker.

**Companion App Logs:**
![Screenshot_20240516_144937_Home Assistant](https://github.com/home-assistant/android/assets/119863238/cc2cfe15-8b76-4f94-b5fe-76dafe663460)

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
your screenshot shows the updates were successfully sent to the server, please supply screenshots of the actual issue and also look at HA core logs. As of now we dont know what the issue is

**Comment by Smittybk1** [comment]
My other 2 location devices report, trigger automations, and show on the map in HA. The Android device in question does not do any of that even though it shows sent as per the pic

**Comment by dshokouhi** [comment]
@Smittybk1 it is definitely sending updates to the server and they are being received, double check the entity in question it may have a different name than what you think. If you cant figure it out, then log out and log back in and give the device a unique name and use that.

**Comment by Smittybk1** [comment]
Will do

**Comment by Smittybk1** [comment]
Thank you for your reply. I found the actual issue now. Since you can't change the radius of the "home" zone in HA, I created a zone named "house" so that automations will only trigger when I'm closer to my address. I see that "home" zone is reporting me as entering the zone, but "house" zone is not showing me as entering that zone. My other devices both report house and home zone being entered. Any ideas?

**Comment by dshokouhi** [comment]
> Since you can't change the radius of the "home" zone in HA

yes you can, you need to override per the docs: https://www.home-assistant.io/integrations/zone/#home-zone





> I see that "home" zone is reporting me as entering the zone, but "house" zone is not showing me as entering that zone. My other devices both report house and home zone being entered. Any ideas?

the app is only responsible to report GPS coordinates to HA core, HA core will translate that into whichever zone the device is in. The map in location history will show you where the device is reported.

**Comment by Smittybk1** [comment]
Thanks for the help! Working now. There was a time where you could not override home zone. Thank you
