### ISSUE TITLE
Register another URL in Companion App to open itself via `https://` URL

### ISSUE THREAD

**Issue by bilogic** [home-assistant/android#4410]
**Is your feature request related to a problem? Please describe.**

Yes, I cannot form any `https://...` URL link that will open my CA. https://my.home-assistant.io opens up in browser instead of companion app (CA). This is because the CA expects the URL to start with `homeassistant://...` which creates another problem because many apps/software do not render `homeassistant://...` as a clickable link

**Describe the solution you'd like**

I would like to have a `https://...` link that will open my companion app.
An easier solution, but not within my control is to have add another registered URL in the CA e.g. `direct.home-assistant.io`, thus, when I click on `https://direct.home-assistant.io/{where-the-user-wanna-go}`, it redirects to `homeassistant://navigate/{where-the-user-wanna-go}`

**Describe alternatives you've considered, if any**

Update the form on https://my.home-assistant.io to accept `homeassistant://navigate/{where-the-user-wanna-go}`. Currently when I try to set my URL as `homeassistant://navigate/{where-the-user-wanna-go}`, it becomes `homeassistant://`

**Additional context**

None

**Comment by dshokouhi** [comment]
We already are registering the my home assistant links. Did you turn it off by chance? 

![Screenshot_20240516-201429.png](https://github.com/home-assistant/android/assets/1634145/af2d3b6b-aa1e-49ff-9ed7-5df3150835ee)

**Comment by bilogic** [comment]
How do I do that? I tried logging out and in again on the companion app and no effect.

**Comment by bilogic** [comment]
Wait, do you mean it is fixed to my.homeassistant.io only? What if I have https://ha.abc.com?

**Comment by dshokouhi** [comment]
> Wait, do you mean it is fixed to https://my.home-assistant.io only? What if I have https://ha.abc.com?

No we don't register for your own URL.

**Comment by bilogic** [comment]
Ok,

1. I formed the URL https://my.home-assistant.io and have it sent to telegram
2. It leads me to the page where I enter my custom URL, this is presented in some sort of browser
3. I added my URL and clicked on it, it stays in that browser, doesn't jump to companion app

**Comment by bilogic** [comment]
So, I tested

1. OK - https://api.whatsapp.com/............ 
2. Not OK - https://my.home-assistant.io
3. Not OK - https://www.home-assistant.io

OK = opens in WhatsApp app
Not OK = does not open in companion app, instead opens in a page powered by Chrome

Taken together it tells me telegram isn't the one blocking these URLs from the respective app, my logical conclusion is to point at the companion app, all permissions already given and I can see URLs 2 and 3 under `Supported web addresses` in the `Set as default`.

If this is an existing feature, then this issue will be a bug report

**Comment by dshokouhi** [comment]
If this is to be a bug report then we need much more information like app version, device info, logs. What URL you are actually using. A my home assistant link is usually configured in a manner like you see on the HA website.

**Comment by bilogic** [comment]
I tested on another android device, same issue: no URL leads to companion app (CA) and I don't think it can happen, here's why:

1. If CA is installed properly, https://my.home-assistant.io should open app immediately since it appears in `Supported web addresses`
2. But for some reason, it does not open the CA on both my devices, instead asking me to input my custom URL
3. Since custom URL is not registered by any app nor CA, it will always open in Chrome

Perhaps can point out where if my understanding and deduction is incorrect?

**Comment by bilogic** [comment]
@dshokouhi 

Alright, I got it figured out. We were talking about 2 very different things.

1. I wanted a `https://` that opens the companion app (CA)
2. You were referring to URLs that the CA registered
3. In typical apps that I have seen, registered URLs lead to the app opening itself, but I don't think this is the case for CA
4. In order to open the CA, the URL has to be `homeassistant://navigate/...` and this is not `https://...`
5. Thus, this will remain a feature request and I have updated my OP

**Comment by jpelgrom** [comment]
The app needs to include the URLs it wants to register for to deep link (open app directly) in the manifest file, which is included when the app is built. So overriding _your_ Home Assistant URL won't be possible.

Deeplinks for HA, also for apps, are handled via my.home-assistant.io. If you need this we should add it there instead of making it Android specific. Going to close this as a duplicate of https://github.com/home-assistant/my.home-assistant.io/issues/172.

> Not OK - https://my.home-assistant.io

The landing page won't work. A specific page like https://my.home-assistant.io/redirect/energy should open the app.

**Comment by bilogic** [comment]
@jpelgrom

I found and implemented a working solution on my domain.

**Comment by bilogic** [comment]
> The landing page won't work. A specific page like https://my.home-assistant.io/redirect/energy should open the app.

Thanks this worked and is the answer to my question.

**Comment by bilogic** [comment]
@jpelgrom 

How do I go to a specific page of mine? https://my.home-assistant.io/redirect/lovelace results in 404 page not found

**Comment by jpelgrom** [comment]
The issue I linked to as duplicate is a request to allow arbitrary pages with my. Currently you can only use the predefined destinations.

**Comment by smos08** [comment]
> [@jpelgrom](https://github.com/jpelgrom)
> 
> I found and implemented a working solution on my own domain. HA can implement this for the community too.

how did you end up resolving this, i am in the exact same situation

**Comment by bilogic** [comment]
## Answer to OP
1. Create a file here `/config/www/companion-app.html`, I used the VSCode add-on to do this
    ```HTML
    <html>
        <head>
            <META HTTP-EQUIV="Refresh" CONTENT="0;URL=homeassistant://navigate/energy">
        </head>
        <body>
            Please wait while we redirect to the companion app
        </body>
    </html>
    ```
2. Load https://your-ha-domain.com/local/companion-app.html on your mobile and watch your CA open up in the energy page
3. This is clearly something HA can help with, e.g. provide https://your-ha-domain.com/app/energy that dynamically creates the HTML above
4. Short of that, I think the only way is to create a custom HA component, try googling `how to create homeassistant component router.register_resource`
