### ISSUE TITLE
Todo items overlap on a small display in portrait mode

### ISSUE THREAD

**Issue by Akron** [home-assistant/android#4417]
**Home Assistant Android app version(s):**

**Android version(s):** 13
**Device model(s):** Unihertz Jelly Star
**Home Assistant version:** 2024.5.4
**Last working Home Assistant release (if known):**
**Description of problem, include YAML if issue is related to notifications:**

When opening the todo list integration in portrait mode on a small screen (Android mobile app on a Unihertz Jelly Star) scrolling down, closed todo-list items overlap (also with open items). This seems to cascade, so the more scrolling is done (up and down) the items overlap multiple times.

**Companion App Logs:**
**Screenshot or video of problem:**
![Overlaps in Todo-List integration](https://github.com/home-assistant/android/assets/506957/cbc4c2b8-6006-4249-a813-a040cb6a23aa)

**Additional information:**
- This behaviour does not occur in landscape mode.
- This behaviour does not show up in a browser.
- This behaviour didn't occur in older versions (maybe starting 2024)
- It seems to be limited to the todo list integration

**Comment by jpelgrom** [comment]
> This behaviour does not show up in a browser

Did you test this in a browser _on the same device_? There is nothing special about the interface displayed in the app here, it should behave the same as Chrome on the same device. If you did, can you check if [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview) is up-to-date?

**Comment by Akron** [comment]
Thank you for your fast response!
Yes, I tested it both on Kiwi and Chrome on the same device - no overlaps occur. The Android WebView is on Version 124.0.6367.179 from 13th of may 2024.

**Comment by dshokouhi** [comment]
This isnt a screen controlled by the app so we wont be able to fix this, you may need to file a HA frontend issue so the team can look into it.

**Comment by dshokouhi** [comment]
is this fixed for you in the latest HA core version?

**Comment by Akron** [comment]
Yes, it is fixed with 2024.6.1! Thank you very much!
