### ISSUE TITLE
Lock screen to avoid random touch during scrooling

### ISSUE THREAD

**Issue by jjindrich** [home-assistant/android#4419]
Looking for feature to lock screen. Like it has some Launchers to avoid moving icons randomly. 

Expexted behaviour:
When app will start screen will be locked, meaning touch will be ignored. You will not be possible to switch inputs etc. You will be ale to scrool only. Ideally it will be possible to switch tab. But nothing else.

When you will hit special gesture, like hold touch, screen will enable to full functionality.

Reason for this feature to avoid make unexpected changes during scrooling.

**Comment by dshokouhi** [comment]
the app already has a lock app feature but that prevents access to dashboard entirely. If you want something more than that then you need to make a request with the HA frontend as you are asking for something more like Kiosk mode which is not something the app will be able to do.

**Comment by jjindrich** [comment]
Please where I can find app lock feature?

**Comment by dshokouhi** [comment]
Settings > companion app > select your server > lock app
