### ISSUE TITLE
Grouped Notifications Lose Individual Notification Color

### ISSUE THREAD

**Issue by j0hann3s** [home-assistant/android#4420]
**Home Assistant Android app version(s):**
2024.4.1-minimal

**Android version(s):**
Android 14

**Device model(s):**
Pixel 8 Pro

**Home Assistant version:**
2024.5.4

**Last working Home Assistant release (if known):**
-- not known --

**Description of problem, include YAML if issue is related to notifications:**

Sending notifications to the same notification group (not channel) with different icon colors results in all notifications getting a white notification color, instead of keeping their individual icon colors.

Notification 1:
```
{
    "domain": "notify",
    "service": "username",
    "data": {
        "title": "Go To Work",
        "message": "Time to go to work.",
        "data": {
            "subject": "",
            "tag": "123",
            "channel": "Silent",
            "group": "Monday",
            "notification_icon": "mdi:calendar",
            "importance": "default",
            "color": "#000080",
            "clickAction": "noAction",
            "sticky": true,
            "persistent": true,
            "actions": [
                {
                    "action": "done",
                    "title": "MARK READ"
                }
            ]
        }
    }
}
```
Notification 2:
```
{
    "domain": "notify",
    "service": "username",
    "data": {
        "title": "Go Do Some Other Stuff",
        "message": "Time to go and do some other stuff.",
        "data": {
            "subject": "",
            "tag": "456",
            "channel": "Silent",
            "group": "Monday",
            "notification_icon": "mdi:calendar",
            "importance": "default",
            "color": "#d73a4a",
            "clickAction": "noAction",
            "sticky": true,
            "persistent": true,
            "actions": [
                {
                    "action": "done",
                    "title": "MARK READ"
                }
            ]
        }
    }
}
```

**Screenshot or video of problem:**

Both notifications by themselves (without a group defined):

![073ab888-6b0c-4e79-955e-45c3ada21abb](https://github.com/home-assistant/android/assets/30905949/834b05d7-c44d-4e51-b021-d4a6785c6d7e)

Both notifications grouped together:

![0fa37128-7d07-43e8-8810-30ba21eb9701](https://github.com/home-assistant/android/assets/30905949/fe173d93-c94a-4319-ba96-c69742be667c)

**Comment by jpelgrom** [comment]
Checked again and the app always sets a color, so closing as cannot fix
