### ISSUE TITLE
Issue with Do Not Disturb mode

### ISSUE THREAD

**Issue by gloumy68** [home-assistant/android#4421]
**Home Assistant Android app version(s):**
2024.4.1-full
**Android version(s):**
Android 14
**Device model(s):**
Google Pixel 5
**Home Assistant version:**
2024.5.5
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
I use for some month the do not distrub sensor of my Google Pixel 5 phone to launch some automation when I enabled or disabled the mode on my phone. And some automation use the state of the sensor to execute or not some action.

Work great on my phone and my wife phone (Pixel 6) for some month, and since 2-3 weeks I have some problems with my sensor :
When I stop DND on my phone, HA detect that I disabled DND correctly and launch the automation, but a few minutes later, the sensor detect ‘priority_only’ again but I don’t change the mode on my phone.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![6acd552f0ba9d9a748f4de7c5cd9ceda6a36c87e](https://github.com/home-assistant/android/assets/161340198/965a8341-a068-4b8d-aa7e-8068a66465e6)

**Additional information:**

**Comment by dshokouhi** [comment]
> but a few minutes later, the sensor detect ‘priority_only’ again but I don’t change the mode on my phone.

more than likely something else on your phone is still setting it to `priority_only` we are always reading the state from the API directly, not sure there is anything we can do to help here. Maybe your phone is setting it but its not visible to you? As you are seeing it change to `off` then randomly change later it looks to be working as described.  Can you get us logs from when the issue occurs? We can at least tell if the system is firing the intent we expect to see so we know its indeed being changed.

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/sensors/DNDSensorManager.kt#L67-L74

**Comment by dshokouhi** [comment]
Closing due to lack of response from author
