### ISSUE TITLE
Old notifications appearing in Android Auto when first connecting

### ISSUE THREAD

**Issue by gary-sargent** [home-assistant/android#4422]
**Home Assistant Android app version(s):**

**Android version(s):**
Android 14

**Device model(s):**
Samsung S23 Ultra

**Home Assistant version:**
2024.5.3
Companion App 2024.5.3-full

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
When my phone connects to the car via Android Auto, all of the existing Home Assistant notifications which are set to notify in Android Auto appear as new notifications in Android Auto. Previously only new notification received since connecting are displayed. You can disconnect from Android Auto and reconnect, and the same notifications all appear again one after another. If I clear out the notifications on the phone before connecting then this does not happen. Seems to have started around April/May.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

Steps to reproduce:
1. Have some HA notifications on the mobile which are flagged "car_ui: true" (in my case I also have "importance: high" and "ttl: 0")
2. Connect to Android Auto

Expected: Existing notifications on phone are not shown in Android Auto
Actual: All existing notifications on the phone are shown in Android Auto immediately after connection

**Comment by garysargentpersonal** [comment]
Hi @jpelgrom,

I don't get many other notifications to be able to test around this. I got a calendar notification which popped up on android auto. I unplugged the device and plugged it back in. I didn't get the repeat notifications like I did with the Home Assistant ones.

Cheers,

Gary.

**Comment by jpelgrom** [comment]
Here's a thought: can you try setting [`alert_once`](http://companion.home-assistant.io/docs/notifications/notifications-basic/#alert-once) (and `tag`) on your notification and see if it makes any difference?

**Comment by gary-sargent** [comment]
Last night I observed the same issue with another applications notifications so looks like this isn't a HA issue as you suspected. Must be an Android Auto defect. I've logged this on the Android Auto Community site. Will close this here. Thanks all.
