### ISSUE TITLE
Dashboard rendering issue

### ISSUE THREAD

**Issue by eeNano** [home-assistant/android#4428]
**Home Assistant Android app version(s):**
2024.4.1-full
**Android version(s):**
14
**Device model(s):**
Samsung Galaxy A14
**Home Assistant version:**
Core: 2024.5.5
Supervisor: 2024.05.1
OS: 12.3
FrontEnd: 20240501.1
**Last working Home Assistant release (if known):**
(same)
**Description of problem, include YAML if issue is related to notifications:**
The interface started to render with errors this morning, only where a thermostat card is present, the other dashboards have no problems. In desktop everything is runing fine

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![WhatsApp Image 2024-05-30 at 12 49 39](https://github.com/home-assistant/android/assets/98494663/8bf1f4bf-4179-4b52-bb6d-de012ff6468d)

**Additional information:**

**Comment by jpelgrom** [comment]
This looks very similar to #4357 

The dashboard is rendered by an app called Android System WebView - can you check if it is updated?  Because it is a dashboard and as you say it started today, it is very unlikely that this is a bug with the companion app.

**Comment by eeNano** [comment]
Thanks for the answer, I didn't update the webview app for a while and it seems that there is no updated version for my phone yet. The curious thing is it happened from last night to this morning without any change on my phone. I will keep watching on the forum to see if other users have some clue. Thanks!

**Comment by Tommi1977** [comment]
Same issue herr

**Comment by dshokouhi** [comment]
do you guys still see this issue in HA core 2024.6.x?

**Comment by eeNano** [comment]
Hi Daniel, I have updated everything on the raspberry and it seems to be working fine on the cellphone again without changing anything on it, should I close this issue?

**Comment by dshokouhi** [comment]
yup lets close this issue, generally speaking dashboard issues are inherently frontend (or custom card) related. We can only check a few things from the app side
