### ISSUE TITLE
Zoom level incorrect when opening app

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/android#4446]
**Home Assistant Android app version(s):**
2024.6.1-Full
**Android version(s):**
12
**Device model(s):**
Samsung S10+
**Home Assistant version:**
2024.6.1
**Last working Home Assistant release (if known):**
2024.5.x
**Description of problem, include YAML if issue is related to notifications:**
When opening app, zoom level on dashboard is incorrect (card outside visible area). 
In addition, three dots for editing are not visible on primary dashboard.

![Screenshot_20240609_191227_Home Assistant.jpg](https://github.com/home-assistant/android/assets/57034871/f3f6911f-7ade-43d6-9d02-e438d416bdc0)

Second dashboard working:
![Screenshot_20240609_191808_Home Assistant.jpg](https://github.com/home-assistant/android/assets/57034871/d1e23191-1616-4b39-bfde-ec829cdd9987)

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
do you see the same issue using chrome for android on the same device? if using a custom card I would suggest reaching out to the custom card author. Generally speaking these dashboard display issues are out of control of the app. We do have a pinch to zoom feature but that does not seem to cause an issue here as you would need to enable it and pinch to zoom.

**Comment by AleXSR700** [comment]
Pinch to zoom let's me adjust to the correct zoom level. It was enabled already. But even without using it, the second dashboard is zoomed correctly when opening.

The card that is not displayed properly is a very basic one
```
type: custom:auto-entities
view_layout:
  grid-area: card01
filter:
  include:
    - entity_id: script.climate*
    - entity_id: automation.climate*
card:
  type: entities
  state_color: true
```

Same kind is shown correctly on the second dashboard (although there is is the second card on the page and not the second one).

Same thing happens in chrome for Android. First dashboard is wrong size, second one is correct.

I am using grid layout, but that has not changed since 2024.5.x releases.

```
grid-template-columns: auto auto
grid-template-rows: auto
grid-template-areas: |
  "card01 card02"
mediaquery:
  "(max-width: 1000px)":
    grid-template-columns: auto
    grid-template-rows: auto
    grid-template-areas: |
      "card01"
      "card02"
      "card03"
  "(max-width: 1600px)":
    grid-template-columns: auto auto
    grid-template-rows: auto
    grid-template-areas: |
      "card01 card02"
```

And I am using a similar grid layout on the second dashboard also

```
grid-template-columns: auto auto auto
grid-template-rows: auto
grid-template-areas: |
  "card01 card02 card03"
mediaquery:
  "(max-width: 1000px)":
    grid-template-columns: 100%
    grid-template-areas: |
      "card01"
      "card02"
      "card03"
  "(max-width: 1600px)":
    grid-template-columns: auto auto auto
    grid-template-rows: auto
    grid-template-areas: |
      "card01 card02 card03"
```

**Comment by dshokouhi** [comment]
> Same thing happens in chrome for Android. 

that suggests a HA frontend issue. I would recommend filing an issue there so they can fix it, we wont be able to fix it here.
