### ISSUE TITLE
Privacy for notifications

### ISSUE THREAD

**Issue by iulko** [home-assistant/android#4447]
Notifications in HA app could not pass any informations in them for privacy sake, just wake up the app to fetch the data. The same is introduced in Signal app, this is a quote from CEO of signal:

"In Signal, push notifications simply act as a ping that tells the app to wake up. They don't reveal who sent the message or who is calling (not to Apple, Google, or anyone). Notifications are processed entirely on your device. This is different from many other apps. "

**Comment by dshokouhi** [comment]
you can just use local push notifications if you dont want your data to go through firebase.

https://companion.home-assistant.io/docs/notifications/notification-local/
