### ISSUE TITLE
Crash on launch & background task after battery optimisations

### ISSUE THREAD

**Issue by brokeh** [home-assistant/android#4449]
**Home Assistant Android app version(s):**

**Android version(s):** 12

**Device model(s):** Samsung Galaxy S10e

**Home Assistant version:** 2024.6.1-full

**Last working Home Assistant release (if known):** 2024.6.1-full

**Description of problem, include YAML if issue is related to notifications:**

Yesterday I got a notification from the battery optimiser that I hadn't used the Home Assistant companion app for a while (which is not true, I actively use it a few times a week, but ignore that) and that it would be put to sleep in the background. I stupidly allowed this to happen even though I do rely on it as a background service. The battery optimiser also removes all permissions from the app with the expectation that it'll ask for them again on the next use.
Now, the application crashes every 15 minutes in the background, and also instantly on launch. 

I use mTLS authentication for accessing my instance and I believe the battery optimisation has also removed access to the mTLS certificate I have registered to it from the system.

I tried clearing the app cache storage but that didn't help. Even clearing the full app data didn't help. It'd ask me a few times to enter the server details and select the mTLS certificate, and after a few tries would get straight back into crashing again. I had to fully uninstall and reinstall the app to get it working again, so there may be something in the system that has revoked the proper access to the certificate.

Here is the callstack of the crash from the logcat logs.
```
D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10370; state: ENABLED
D KeyChain: isKeyChainUri: home assistant
D OpenGLRenderer: RenderThread::requireGlContext()
E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 16883
E AndroidRuntime: java.lang.AssertionError: could not resolve KeyChainService
E AndroidRuntime:        at android.security.KeyChain.bindAsUser(KeyChain.java:1165)
E AndroidRuntime:        at android.security.KeyChain.bindAsUser(KeyChain.java:1070)
E AndroidRuntime:        at android.security.KeyChain.bind(KeyChain.java:1056)
E AndroidRuntime:        at android.security.KeyChain.getCertificateChain(KeyChain.java:909)
E AndroidRuntime:        at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl.doLoad(KeyChainRepositoryImpl.kt:65)
E AndroidRuntime:        at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl.access$doLoad(KeyChainRepositoryImpl.kt:14)
E AndroidRuntime:        at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl$load$3.invokeSuspend(KeyChainRepositoryImpl.kt:41)
E AndroidRuntime:        at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl$load$3.invoke(Unknown Source:8)
E AndroidRuntime:        at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl$load$3.invoke(Unknown Source:4)
E AndroidRuntime:        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
E AndroidRuntime:        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
E AndroidRuntime:        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
E AndroidRuntime:        at io.homeassistant.companion.android.common.data.keychain.KeyChainRepositoryImpl.load(KeyChainRepositoryImpl.kt:36)
E AndroidRuntime:        at io.homeassistant.companion.android.HomeAssistantApplication$onCreate$3.invokeSuspend(HomeAssistantApplication.kt:78)
E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
E AndroidRuntime:        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
E AndroidRuntime:        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
E AndroidRuntime:        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2bbf122, Dispatchers.IO]
D Debug   : low && ship && 3rdparty app crash, do not dump
W ActivityManager: crash : io.homeassistant.companion.android,10370
```

As an aside, I don't see the Home Assistant Companion app listed in the list of apps that I can set to be excluded from battery optimisations so I don't know if I can stop this from happening again.

**Companion App Logs:** Unable to get them since the app was crashing. I had a rummage through `/data/data/io.homeassistant.companion.android` but didn't see anything that looked relevant.

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
> Yesterday I got a notification from the battery optimiser that I hadn't used the Home Assistant companion app for a while (which is not true, I actively use it a few times a week, but ignore that) and that it would be put to sleep in the background. I stupidly allowed this to happen even though I do rely on it as a background service. The battery optimiser also removes all permissions from the app with the expectation that it'll ask for them again on the next use.
> Now, the application crashes every 15 minutes in the background, and also instantly on launch.

sounds like something got corrupted. try the start fresh steps in order (even if it seems you have followed them already) and see if it fixes the issue.

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

its also possible that whatever you enabled add the app to some sort of list Samsung maintains. Where that is or what you need to change I have no idea but I would dig into device settings looking for things like power saving, data saving , sleeping apps etc.. youll need to dig into your device and see where that  was set. Its somewhere but Samsung likes to add a lot of features like this and its hard to keep up.

**Comment by brokeh** [comment]
Thanks. I removed the app from the list of sleeping apps, although that happens automatically when it's next used too.
I'm guessing the problem is that the permissions are also revoked as part of the app getting put to sleep, regardless of it it is still in the sleeping list or not they aren't restored automatically and must be re-granted. It's entirely possible that Samsung don't handle that properly for user certificates given how infrequently they are used as a feature.

I've already uninstalled and re-installed the app to resolve the issue, so doing the _starting fresh_ steps won't work now. I however don't expect they'd help. I already wiped the data and that didn't help and the crash was before it could even contact the server so I suspect removing the device from the HA dashboard also wouldn't do anything,

**Comment by jpelgrom** [comment]
This is an odd one, considering that the app should catch this exception:

https://github.com/home-assistant/android/blob/cdaf17f9a616d72ab9ef2377f65dbc82d846d6a5/common/src/main/java/io/homeassistant/companion/android/common/data/keychain/KeyChainRepositoryImpl.kt#L64-L69

(via @dshokouhi)

**Comment by brokeh** [comment]
I'm not well versed in JVM languages but my understanding is that an [AssertionError](https://docs.oracle.com/javase/7/docs/api/java/lang/AssertionError.html) derives from [Error](https://docs.oracle.com/javase/7/docs/api/java/lang/Error.html), not [Exception](https://docs.oracle.com/javase/7/docs/api/java/lang/Exception.html) and so catching all `Exception` is not sufficient and you must also catch `Error`.

**Comment by jpelgrom** [comment]
Thank you - how was that missed. Still doesn't explain why this is showing up suddenly 🤔
