### ISSUE TITLE
Make VOICE_COMMAND response optional

### ISSUE THREAD

**Issue by tswsl1989** [home-assistant/android#4457]
**Is your feature request related to a problem? Please describe.**

I do not use (and do not wish to use) the assist feature. Now that the companion app responds to voice assistant requests from bluetooth devices (I think from #4331) , the assist dialog frequently opens while turning headphones off (which requires holding the button for longer than the time required to trigger a "long press" response). 

**Describe the solution you'd like**

Allow the assist feature to be turned off so that the companion app no longer responds to the relevant intents - or at least, does not respond in any user visible manner.

**Describe alternatives you've considered, if any**

The default voice assistant app is set to None and there are no other options in Android settings to stop Home Assistant responding to the long press on the headphone button(s).

**Additional context**

**Comment by yann1420** [comment]
I support this feature request as I'm also bothered by this phenomenon.
