### ISSUE TITLE
WebRTC two way audio not working when connected to local IP address

### ISSUE THREAD

**Issue by ReX1983** [home-assistant/android#4468]
**Home Assistant Android app version(s):**

**Android version(s):** 13

**Device model(s):** Xiaomi Mi 10

**Home Assistant version:** 2024.6.3

**Last working Home Assistant release (if known):** N/A

**Description of problem, include YAML if issue is related to notifications:**

WebRTC (go2rtc) supports two-way audio, e.g. it is now possible to answer a video doorbell directly from within Home Assistant.

Unfortunately, Chromes give access to the microphone only to HTTP websites (see more [here](https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#two-way-audio)). 

This is a pity, as when at home you want to connect your HA companion app to your LAN IP address, so no HTTPS.

I have found a workaround ([here](https://stackoverflow.com/questions/52759992/how-to-access-camera-and-microphone-in-chrome-without-https)) that works for both Chrome and Chrome mobile. 

The workaround requires access to the Chrome (or WebView) flags, and this seems not possible from within the HA companion app (at least I can't find a way to access the flags page).

Can we get access to the flags or can this flag be automatically populated with the internal address?

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![image](https://github.com/home-assistant/android/assets/37460549/22006dc4-fec9-4117-bbf8-28b5c3f69080)

**Additional information:**

**Comment by jpelgrom** [comment]
WebView doesn't support flags in user builds (= the app you have on your device), and even if it did this is something internal to WebView and not exposed via APIs to apps.
