### ISSUE TITLE
Restart notifications show integration 'internal' names instead of 'display' names

### ISSUE THREAD

**Issue by camedomotic-unofficial** [home-assistant/android#4471]
**Home Assistant Android app version(s):** 2024.6.1-full

**Android version(s):** 10

**Device model(s):** Honor 10 (COL-L29)

**Home Assistant version:** 2024.6.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

I noticed that when the Home Assistant server is restarting and the integrations are still loading, the web version of Home Assistant shows the notifications in the black rectangles correctly reporting the "display name" of the integrations (e.g. "BMW Connected Drive") while the mobile app uses the internal names (e.g. "bmw_connected_drive" - see attached screenshot for clarity), that sounds wrong.

I know this is a very low priority issue, but still worth of being tracked ☺️.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

<img width="870" alt="image" src="https://github.com/home-assistant/android/assets/162296454/20731169-97df-433a-9909-3c5e5f507bde">

**Additional information:**

**Comment by dshokouhi** [comment]
That message does not come from the app. Most likely a HA frontend issue. Do you see the same issue using chrome for Android on the same device?

**Comment by fredericks1982** [comment]
Thanks for your feedback. Yes, it's the same on Chrome for Android too (i.e. I see the wrong message)

**Comment by dshokouhi** [comment]
ok that means its a HA frontend issue, please check for open issues and if one does not exist please file a new issue in their repo

https://github.com/home-assistant/frontend/issues
