### ISSUE TITLE
Automation entity state does not match phone state

### ISSUE THREAD

**Issue by labatt** [home-assistant/android#4476]
**Home Assistant Android app version(s):**
2024.6.3-full

**Android version(s):**
Android 12

**Device model(s):**
Samsung Galaxy S10

**Home Assistant version:**
2024.6.3

**Last working Home Assistant release (if known):**
2023.12.06

**Description of problem, include YAML if issue is related to notifications:**

Please see issue 
https://github.com/home-assistant/core/issues/119711. I'm not sure if this is an issue with the core or with the Android app but nobody has responded to my core issue in a week.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
As the issue is with the automation and not the entity state, this is not an issue the app can fix.
