### ISSUE TITLE
TTL = 0 doesn't work

### ISSUE THREAD

**Issue by VNRARA** [home-assistant/android#4486]
**Home Assistant Android app version(s):**

**Android version(s):** 

**Device model(s):**  Samsung galaxy s24

**Home Assistant version:** 2024.6.3

**Last working Home Assistant release (if known):** nAn

**Description of problem, include YAML if issue is related to notifications:**

https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidConfig.FIELDS.ttl
Reports we can use ttl: 0
but actually using it gives back the error that it has to be greater than 0.

![image](https://github.com/home-assistant/android/assets/3942672/c1074bb6-510f-4bbc-b783-92c6e4785b4f)

![image](https://github.com/home-assistant/android/assets/3942672/51903f8b-b578-4e4a-988d-2699dc4a38c3)

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
This is strange. Ttl 0 works fine for me. The error suggests it may be coming from firebase?

**Comment by VNRARA** [comment]
Should it be possible to do ttl: 0 when using command_activity?

**Comment by dshokouhi** [comment]
Yes and it works just fine for me for all my notifications on the same HA core version. Something else seems to be at play here.

**Comment by VNRARA** [comment]
Yeah, it was constantly giving me the errror with ttl: 0 untill I changed it to ttl: 1. Now i've changed it back to 0 and it works again?

**Comment by dshokouhi** [comment]
Sounds like a firebase server error which is not something the app can fix.

**Comment by VNRARA** [comment]
It keeps showing up: 

2024-07-31 16:38:30.447 ERROR (MainThread) [homeassistant.components.mobile_app.notify] TTL must be a non-negative duration in milliseconds. This message is generated externally to Home Assistant.

**Comment by dshokouhi** [comment]
and this happens randomly? sometimes you dont get the error and sometimes you do?

**Comment by VNRARA** [comment]
These are the logs I'm getting: 

Logger: homeassistant.components.mobile_app.notify
Bron: components/mobile_app/notify.py:199
integratie: Mobiele app (documentatie, problemen)
Eerst voorgekomen: 00:43:16 (12 gebeurtenissen)
Laatst gelogd: 18:45:38

TTL must be a non-negative duration in milliseconds. This message is generated externally to Home Assistant.
An unknown server error was returned. Raw server response: "<!DOCTYPE html> <html lang=en> <meta charset=utf-8> <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"> <title>Error 502 (Server Error)!!1</title> <style> *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px} </style> <a href=//www.google.com/><span id=logo aria-label=Google></span></a> <p><b>502.</b> <ins>That’s an error.</ins> <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds. <ins>That’s all we know.</ins> ". Status code: 502. This message is generated externally to Home Assistant.
