### ISSUE TITLE
Tasmoadmin Addon does not open URLs, eg. device web page or documentation, when running in Homeassistant App 

### ISSUE THREAD

**Issue by nobthenob** [home-assistant/android#4488]
**Home Assistant Android app version(s):**

**Android version(s):**
  14

**Device model(s):**
GALAXY Tab S7 FE

**Home Assistant version:**
2024.6.4 
Tasmoadmin 4.1.1

**Last working Home Assistant release (if known):**
Cannot remember,any version, where it worked.

**Description of problem, include YAML if issue is related to notifications:**

In list view Tasmoadmin does not open the device web page or documentation URL

The issue does only exist with the Android App of HA
When I run HA in a browser, everything works as expected: The Tasmota device page is opened in a new browser window.
 
Is there any way to get it working?

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

I also opened an issue here: https://github.com/hassio-addons/addon-tasmoadmin/issues/414
but was told to report it for the App.

Thx, nob

**Comment by dshokouhi** [comment]
so you tested this using chrome for android on the same device?

**Comment by nobthenob** [comment]
I tested it with Firefox on the Android device, where the links work.

**Comment by dshokouhi** [comment]
can you please try chrome for android? android system webview is based on chromium so good to be precise here. Also can you check that android system webview is upto date in the play store?

**Comment by dshokouhi** [comment]
I also wonder if this comment is still valid: https://github.com/home-assistant/android/issues/164#issuecomment-566438343 as its a similar issue

**Comment by nobthenob** [comment]
Using HA in Chrome, like in Firefox opens the links of Tasmoadmin.

**Comment by dshokouhi** [comment]
one other thing to consider, teh app does not handle new windows or pop-ups, so I am not sure how this will work with the app. We cant open in chrome because then auth will be missing.

**Comment by dshokouhi** [comment]
> > I also wonder if this comment is still valid: [#164 (comment)](https://github.com/home-assistant/android/issues/164#issuecomment-566438343) as its a similar issue
> 
> I have no idea. I don't understand what this 5 year old issue was about. Sorry.

comment was more for developers than yourself :)

**Comment by jpelgrom** [comment]
> I also wonder if this comment is still valid: [#164 (comment)](https://github.com/home-assistant/android/issues/164#issuecomment-566438343) as its a similar issue

Isn't this handled, with any links that want to open in a new window (eg `<a href="something" target="_blank">link</a>`) will be redirected to the browser? At least when doing that in a card on my dashboard, both for relative urls, urls with the same domain, and urls with other domains.

@nobthenob When you click the link, what happens? Does nothing happen, do you get a white screen, ...? Any chance you could share a recording or (redacted) URL as an example?

**Comment by nobthenob** [comment]
Sorry for late answer.  
The Tasmoadmin Add-On provides at least two location where I suppose links are used:
The Help Menu contains an entry to open the Tasmoadmin Doku, among others.
Secondly the list view of devices shows the device names as link. if I click on one of these it just shows a small one line pop up menu saying "Call surface".
But otherwise nothing happening in both case, no Browser open or anything.

I cannot see the actual URLs behind, but I would guess that in first case it is supposed to call 
https://tasmota.github.io/docs/
This is the URL I see, when I use HA in a Browser.

In second case, the URL should be  local  URL of the related tasmota device in my home network e.g. http://192.168.178.50, again this is what the Browser version of HA is calling.

Hope, that helps.
nob

**Comment by jpelgrom** [comment]
So I've tried reproducing this using the addon, but it does not support Ingress? How are you viewing this in the app? The expected behavior would be that it sends you to the browser the moment you start interacting with a non-Ingress web UI.

**Comment by dshokouhi** [comment]
@nobthenob just a reminder about the above comment, this issue is at risk of being closed due to lack of responses.

**Comment by jpelgrom** [comment]
Closing due to no response and unable to reproduce
