### ISSUE TITLE
Search bar in Settings-Dashboards/Devices/Automations does not react to touch

### ISSUE THREAD

**Issue by r0d0dendr0n** [home-assistant/android#4489]
**Home Assistant Android app version(s):**
2024.6.4-full (beta)
latest stable (2024.6.1-full?)

**Android version(s):**
10

**Device model(s):**
PocoF1

**Home Assistant version:**
Docker latest (image bb85a3c4dacc)

**Last working Home Assistant release (if known):**
Docker 2023.8

**Description of problem, include YAML if issue is related to notifications:**
The search part of the window title does not respond to touch, like in issue 4190, except this time it's in Settings/Dashboards and Settings/Devices and Settings/Automations. It works in Logs. In other words I cant look specificaly for devices or automations, which comes in handy from time to time. I still can use the general search in Settings.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
Like in issue 4190, this search bar is managed by the frontend so [please see a frontend issue](https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) instead, the app can't fix this by itself.
