### ISSUE TITLE
Next Alarm sensor stopped updating (using Google Clock on Samsung S23)

### ISSUE THREAD

**Issue by maleadt** [home-assistant/android#4492]
I've been a happy user of the Home Assistant companion app, using the Next Alarm sensor to drive several automations. Recently, that sensor has stopped updating properly. Several things changed in my set-up (I added a WearOS device, started using the sensor allowlist to get rid of updates pushed by the Samsung Modes & Routines app that I started using), none of which _should_ affect the Next Alarm sensor updating, as far as I understand at least.

**Home Assistant Android app version(s):** 2024.6.1-full

**Android version(s):** 14

**Device model(s):** Samsung S23

**Home Assistant version:** 2024.6.4

I am using the Google Clock app because, as already noted in other issues here, the Samsung clock app has known issues wrt. sensor reporting.

Demonstration of the issue: https://github.com/home-assistant/android/assets/383068/94e52886-723a-4283-8a73-c0c15fd1607f. Here, I first change the upcoming alarm, then disable all alarms, both without any reflecting change in the companion app. Toggling the sensor doesn't help. What does help, is rebooting the phone, but that's not practical of course.

Logs of that recording: 
[homeassistant_companion_log_6-2-2024_16-49-6.txt](https://github.com/user-attachments/files/16070319/homeassistant_companion_log_6-2-2024_16-49-6.txt). FWIW. the 1719951300000 timestamp in there reported by the Samsung Modes & Routines app is the start of Sleep Mode, at 10:15PM, which is the alarm I'm hiding by using the allowlist.

Sensor allow list: 
<img src="https://github.com/home-assistant/android/assets/383068/89eae455-1672-44b9-8b18-b61e4e7d7d70" width="300">
As shown, this includes the Google Clock app, and shows that it has successfully received the initial 7:05 AM setting from that app.

Since everything used to work fine, it's probably related to one of the changes in my environment, but I'm not sure how to start to debug this.

**Comment by dshokouhi** [comment]
if you see updates stopping entirely, remove all items from your allow list then find out what other apps are setting an alarm as its most likely causing a conflict

**Comment by maleadt** [comment]
I guess I'm confused about how the allowlist is supposed to work then. If I remove all items from it, setting an alarm in the Google Clock app indeed is reflected in the HomeAssistant Companion app:

```

**Comment by dshokouhi** [comment]
> I guess I'm confused about how the allowlist is supposed to work then.

The API is very literal in the sense that it only returns the next scheduled alarm. There can only be 1. So the allow list will skip unwanted updates.



> However, I need to use an allowlist to get rid of the "bogus" alarm set by the Samsung Modes & Routines app (`com.samsung.android.app.routines`).

just remove whatever is in that app causing it to set alarms and it should be ok.

**Comment by maleadt** [comment]
> There can only be 1. So the allow list will skip unwanted updates.

Ah, that's pretty annoying. Thanks for explaining.
