### ISSUE TITLE
card feature selection - can't be removed

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/android#4493]
**Home Assistant Android app version(s):**
2024.6.1-full

**Android version(s):**
Android 14

**Device model(s):**
Google Pixel 6, Pixel 8 Pro, others

**Home Assistant version:**
2024.7.0

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Features (the one shown in the Screenshot below) cannot be removed out of the Companion App.
This is the case on Area Cards, and Tile Cards with corresponding features, as well as Thermostat Cards.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![grafik](https://github.com/home-assistant/android/assets/26391061/dc553698-6dfd-4baf-b447-546fb353f35f)

**Additional information:**

**Comment by jpelgrom** [comment]
Does this work correctly in Chrome on the same phone? (The dashboard shouldn't behave differently in the app, this is probably a frontend issue.)

**Comment by ChristophCaina** [comment]
Yes, Same behave in the Browser using my mobile. 
Thanks :)
I will Open this in the Frontend.
