### ISSUE TITLE
Missing notifications in the android phone

### ISSUE THREAD

**Issue by mihaitaiosub** [home-assistant/android#4494]
**Home Assistant Android app version(s):**

**Android version(s):**13

**Device model(s):**Samsung Galaxy S20 FE 5G

**Home Assistant version:**2024.6.1-full

**Last working Home Assistant release (if known):*
The application is very good, I've been using it for several years because I have the whole house automated. The only problem is that when you set some notifications to receive on the phone, they work, you receive them, but only if the phone is with the display on or a few minutes after the display is closed. After the phone is not used for a few minutes, notifications are only received when the phone is turned on and the screen is unlocked. All other notifications from other applications is ok

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Please provide a yaml example. Sounds like you either do not have background access granted or you are not following the critical format to speed up delivery

**Comment by mihaitaiosub** [comment]
The application has background access
![Screenshot_20240706_065337_Home Assistant](https://github.com/home-assistant/android/assets/77276378/f57e088c-5e07-4af3-9ea0-f9c6bb490dfe)

**Comment by dshokouhi** [comment]
That answers one question, can you please provide a yaml example of the notification?

**Comment by mihaitaiosub** [comment]
How can i provide a yaml example of the notification?I do not know how.

**Comment by dshokouhi** [comment]
> How can i provide a yaml example of the notification?I do not know how.

A notification is sent from the server to the device using yaml. We need that.

**Comment by mihaitaiosub** [comment]
Ok,but where i can find this example?

**Comment by dshokouhi** [comment]
From your automation?

**Comment by mihaitaiosub** [comment]
Ok, I understand now. But I specify once more, the notifications work ok when the phone has the display on. The problem only appears after 1-2 minutes after the display closes.
service: notify.mobile_app_sm_g781b
data:
  message: Alarma armata perimetru

**Comment by dshokouhi** [comment]
Please follow the critical format to speed up delivery of the notification

https://companion.home-assistant.io/docs/notifications/critical-notifications#android

**Comment by mihaitaiosub** [comment]
It would seem that the problem is solved. Thank you very much for your help!
