### ISSUE TITLE
Some parts are written in English even though the language is Korean

### ISSUE THREAD

**Issue by rsb1813** [home-assistant/android#4495]
**Home Assistant Android app version(s):**
2024.6.1
**Android version(s):**
13
**Device model(s):**
SM-T970
**Home Assistant version:**
2024.7.1
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

![Screenshot_20240706_234648_Home Assistant](https://github.com/home-assistant/android/assets/173606603/88bf2e21-f858-42ee-b738-f788431a95d6)

**Additional information:**

**Comment by jpelgrom** [comment]
Home Assistant is translated by volunteers. Where there is no translation, it will fall back to English. [You can contribute to translations here](https://developers.home-assistant.io/docs/translations/).

**Comment by rsb1813** [comment]
Originally, it was displayed normally in Korean, but suddenly, even though the language setting is Korean, it is displayed in English.

**Comment by jpelgrom** [comment]
If the text is translated on other devices, try fully closing (from the recent apps screen) and reopening the app. It may be possible that the frontend translations haven't fully loaded.
