### ISSUE TITLE
Support certificate mismatch connection

### ISSUE THREAD

**Issue by kaovilai** [home-assistant/android#4496]
**Is your feature request related to a problem? Please describe.**

When my router doesn't support Nat Loopback, and I've used port forwarding along with let's encrypt, I would not be able to use local IP without cert mismatch.

Using DNS rewrite can be unreliable if device doesn't strictly use your custom DNS only.

Something like `curl --insscure` should work well enough imo for this scenario. I'm not concerned about internal network snoops on my password protected local network.

**Describe the solution you'd like**

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
Are you asking us to bypass certificate errors? Because we won't be doing that.

**Comment by kaovilai** [comment]
I am asking to bypass cert errors on certain trusted networks. Conditional checks can include public IP of the device, mac address of wifi access point or router.

Another would be perhaps allowing specification of DNS server to use at the app level (OS level is not reliable, such as on Fire Tablet devices which inject extra dns servers), which I can use a local dns server to rewrite IP so that I won't have to see this issue or override cert.

**Comment by dshokouhi** [comment]
> I am asking to bypass cert errors on certain trusted networks.

Apologize but we will not be bypassing any certificate errors, the app requires valid certificates.
