### ISSUE TITLE
Calendar card resizing issue

### ISSUE THREAD

**Issue by Sensorn** [home-assistant/android#4497]
**Home Assistant Android app version(s):2024.6.1-full**

**Android version(s):14**

**Device model(s):Samsung Galaxy S22 Ultra**

**Home Assistant version:2024.7.1**

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:When using the new resizing tool for a calendar card in section view, it looks like the attached screenshot**

**Companion App Logs:**

```

```

**Screenshot or video of problem:![Screenshot_20240707_233027_Home Assistant](https://github.com/home-assistant/android/assets/168321218/c3726bb0-534a-4305-9e98-7dfe855be186)**

**Additional information:**

**Comment by dshokouhi** [comment]
Can you reproduce using chrome for Android on the same device?

**Comment by Sensorn** [comment]
> Can you reproduce using chrome for Android on the same device?

Created a new card in Chrome but got the same result. I have also restarted HA, but no difference.
![Screenshot_20240708_011608_Chrome](https://github.com/home-assistant/android/assets/168321218/551ea0a1-e671-4550-9a45-31f97878c750)

**Comment by jpelgrom** [comment]
Because you're seeing the same issue in Chrome, this is most likely a frontend bug. Please create a [frontend issue](https://github.com/home-assistant/frontend/issues) instead.
