### ISSUE TITLE
Wear OS: Update app to target API 33 by August 30 for play store policy

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#4500]
Skipping the template here. 

We need to update Wear OS to API 33 by August 30 or the app wont be updated in the play store after that date.

![image](https://github.com/home-assistant/android/assets/1634145/73fb21b3-4d09-4c10-a93d-9de3ee358ed0)

This API level had the requirement for requesting notification permissions which needs to be done during onboarding, amongst other things.

**Comment by jpelgrom** [comment]
Looking at the behavior changes I only see 2 (documented) items that are relevant for us:

 - https://developer.android.com/develop/ui/views/notifications/notification-permission: This won't be too hard, we should probably ask for it when the app is opened (≈ current behavior) and maybe add a quick option for it in settings to make it easier to find. On some devices (Samsung) this may be linked to the ability to receive phone notifications on the watch as well so probably best to keep the description general.
 - https://developer.android.com/about/versions/13/behavior-changes-13#body-sensors-background-permission: Looks like we may need to disable the heart rate sensor on devices running API 33+, as HA won't be allowlisted for background use anywhere and only having it work while the app is open is pretty useless.

**Comment by dshokouhi** [comment]
ouch thats not going to be fun regarding teh heart sensor. I remember a feature request for adding the update sensors command to the watch so users can get the heart rate sensor updating more frequently.

adding heart rate sensor to health services may work but i fear it may lead to more battery drain because it updates frequently, going to require some testing there.

**Comment by dshokouhi** [comment]
Regarding the heart rate sensor I just found something specific to Wear OS. Looks like users will be able to grant the app background permission :)

https://developer.android.com/training/wearables/versions/4/changes#background-body-sensor-permission

https://developer.android.com/health-and-fitness/guides/health-services/background-body-sensors

`Note: BODY_SENSORS_BACKGROUND is a restricted permission which cannot be held by your app until the installer adds your app to an allowlist, or until the user lets your app have the permission.`

**or until the user lets your app have the permission.** So this must correspond to the "All the time" setting I imagine.

**Comment by jpelgrom** [comment]
I cannot choose all the time after targeting API 30. Is there a manufacturer difference or am I making an error?

**Comment by dshokouhi** [comment]
yea looks like the option is hidden a bit

`On Android 13 (API level 33) and higher, the runtime permission dialog doesn't include the "Allow all the time" option. Instead, users must enable all-the-time background sensor access from system settings, as shown in figure 1. When you request the BODY_SENSORS_BACKGROUND permission after granting the BODY_SENSORS permission, you can help users navigate to this settings page. If users decline all-the-time access, they should be able to continue using your app.`

https://developer.android.com/health-and-fitness/guides/health-services/background-body-sensors#target-android13-higher

looks like body sensors has to be granted before body sensors background here
