### ISSUE TITLE
Shortcut URL Hash Support

### ISSUE THREAD

**Issue by Nerwyn** [home-assistant/android#4502]
**Is your feature request related to a problem? Please describe.**

Some custom cards (like [bubble card](https://github.com/Clooos/Bubble-Card)) use URL hashes to display popups, which can be navigated to directly in desktop and mobile browsers. Unfortunately, the Home Assistant Android app shortcuts do not support hashes, and they are ignored if included in the `Dashboard view or Dashboard` field.

**Describe the solution you'd like**

Include URL hash in `Dashboard view or Dashboard` path for Home Assistant Android app shortcuts.

**Describe alternatives you've considered, if any**

Navigate to the page with the custom card and then navigate to it from there.

**Additional context**

The shortcuts setting page for reference.
<img src="https://github.com/home-assistant/android/assets/43071698/65886ed0-d8fb-4905-8bde-3d352c769f7d" width="300"/>

**Comment by dshokouhi** [comment]
Are you sure the hash is ignored? If you load the URL in a new tab in Chrome for Android does it work?

**Comment by Nerwyn** [comment]
The URL with hash works in Chrome, Brave, and Firefox for Android. It does not work as a shortcut.

**Comment by dshokouhi** [comment]
ok are you at least being navigated to the correct dashboard?

**Comment by Nerwyn** [comment]
The shortcut is navigating to the correct dashboard when the hash is included.

**Comment by dshokouhi** [comment]
this is probably not limited to shortcuts probably also impacts `clickAction` in a notification. Also not seeing anything in our code that strips things after a hash so not sure how thats happening.

**Comment by dshokouhi** [comment]
if you enable chrome remote debugging and hook up to chrome do you see the hash still in the URL? looks like we are indeed saving the string as is and loading it as is so im curious if the browser still sees the hash there.

**Comment by Nerwyn** [comment]
Do you mean in Chrome for Android or the Home Assistant app? Chrome for Android reports the URL with hash.
![Screenshot 2024-07-09 232226](https://github.com/home-assistant/android/assets/43071698/e85133b7-e2e5-4b48-a9a7-fdcf73a8bdde)

**Comment by dshokouhi** [comment]
> Do you mean in Chrome for Android or the Home Assistant app? Chrome for Android reports the URL with hash. ![Screenshot 2024-07-09 232226](https://private-user-images.githubusercontent.com/43071698/347248947-e85133b7-e2e5-4b48-a9a7-fdcf73a8bdde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MTA3NTIsIm5iZiI6MTcyMDcxMDQ1MiwicGF0aCI6Ii80MzA3MTY5OC8zNDcyNDg5NDctZTg1MTMzYjctZTJlNS00YjQ4LWE5YTctZmRjZjczYThiZGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE1MDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZDg5YjBhMTI3NTc0YzJmOGZlNmNlZmY1MzcyMWY2YjU5MDg2MzY1OTA0ZWQ2MGFiYjZjZWFhMDY2MmI5MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kly34C4V1MdHF7G-PyQYclK6mdS6pV59L-fJUll4JXw)

The HA app actually, you need to enable remote debugging in companion app settings to access it there. You should hopefully see the URL with the hash still there.

**Comment by Nerwyn** [comment]
Confirmed working in the latest beta! Thank you!
