### ISSUE TITLE
App cannot connect when not at home but connected to an SSID with the same name as at home

### ISSUE THREAD

**Issue by uphillbattle** [home-assistant/android#451]
**Home Assistant Android version:**
1.7.2-128

**Android version:**
9

**Phone model:**
Samsung Galaxy S8

**Home Assistant version:**
0.105.5

**Last working Home Assistant release (if known):**

**Description of problem:**
I’ve set up the app with both the «Home Assistant URL» (set to my nabu casa URL) and the «Internal Connection URL». I assume that when I’m connected to my «Home Network WiFi», the internal connection URL is used.

At my cabin, I have network WiFi with the same SSID as at home (to make WiFi connection there easier for my family). So at my cabin, the Home Assistant Companion app uses the internal connection URL, I assume, and as a result, I can’t remotely connect to Home Assistant because it is not local even though the SSID suggests that it should be.

So, could the app be updated to try the external URL if the internal one fails?

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by uphillbattle** [comment]
Oh, and by the way, the problem is exactly the same with the iOS companion app.

**Comment by SteveDinn** [comment]
Obvious course of action here is to determine the AP based on its BSSID. But then we'd also have to account for mesh wifi systems that have the same SSID but various different BSSIDs.

**Comment by gadgetchnnel** [comment]
Could this be solved by adding an option to take location into account, so it only uses the internal URL when you are at the home location?

**Comment by SteveDinn** [comment]
I would say it should not have to depend on location data because some users would have denied the app the permission or simply have the location tracking turned off. This is a feature that should work independantly of whether location is or is not being tracked.

**Comment by gadgetchnnel** [comment]
@SteveDinn It seems that detecting the current SSID needs the Location permission anyway (see https://github.com/home-assistant/home-assistant-android/issues/281).

**Comment by KBerstene** [comment]
Not a great option, but the app could attempt to fall back on the external address if the internal address fails.

**Comment by jpelgrom** [comment]
FYI support for using a BSSID to detect when to use the internal/external URL is being added in #2883
