### ISSUE TITLE
Zigbee Group names are invisible

### ISSUE THREAD

**Issue by krissrex** [home-assistant/android#4511]
**Home Assistant Android app version(s):** 2024.6.1-full 

**Android version(s):** 14

**Device model(s):** Samsung Galazy Z-flip 4

**Home Assistant version:** 2024.7.2

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**  user interface does not display the names of zigbee groups in zha.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![Screenshot_20240713_115113_Home Assistant](https://github.com/user-attachments/assets/783209e7-8086-4eaf-9257-3c3981a1cd08)

**Additional information:**
Same issue with light mode as dark mode theme.

**Comment by dshokouhi** [comment]
Do you see the same issue using chrome for Android on the same device?

**Comment by krissrex** [comment]
Yes, it looks the same in Android Chrome.

**Comment by jpelgrom** [comment]
As you're seeing the same outside the app, this suggests this is a frontend issue. Please [check for open issues](https://github.com/home-assistant/frontend/issues), and it not known report it there, as this cannot be fixed by the app.
