### ISSUE TITLE
Crash when adding Zwave device by QR code

### ISSUE THREAD

**Issue by br0nd** [home-assistant/android#4514]
**Home Assistant Android app version(s):**

**Android version(s):** 2024.6.1-full (android 14)

**Device model(s):** Pixel 8 

**Home Assistant version:** 2024.7.2

**Last working Home Assistant release (if known):** 

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**
Can attach the logs, but based on a quick scan, since the app is crashing, don't think the log is catching the crash
```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by br0nd** [comment]
FYI several other people have reported this issue in a bug on the front end (mistakenly), so this does not seem isolated to me. https://github.com/home-assistant/frontend/issues/21323

**Comment by dshokouhi** [comment]
You skipped over the app version. Also this issue is fixed in the app beta and will be part of our next release.

**Comment by br0nd** [comment]
> You skipped over the app version. Also this issue is fixed in the app beta and will be part of our next release.

Thank you for the update! Updated bug with app version, was this already reported? I tried to find reference to this issue but didnt seem to find it

**Comment by dshokouhi** [comment]
> > You skipped over the app version. Also this issue is fixed in the app beta and will be part of our next release.
> 
> Thank you for the update! Updated bug with app version, was this already reported? I tried to find reference to this issue but didnt seem to find it

Reported on discord but the user never created a report
