### ISSUE TITLE
Add bluetooth status and connection sensor

### ISSUE THREAD

**Issue by jokerigno** [home-assistant/android#452]
**Is your feature request related to a problem? Please describe.**
No problem. Just a new feature.

**Describe the solution you'd like**
Add support for BT status and paired device to use for automation:

- Send location when connected to car BT
- Enable/disable voice messages while using headphones
- Use BT for room location

**Describe alternatives you've considered, if any**
Nope

**Additional context**
That's all folks.

**Comment by recklessnl** [comment]
> Use BT for room location

This is actually a great use case for this and could make room presence detection easier, especially if the sensor provides signal strength as well.

For example, let's say you have two floors. On both floors you have a low energy bluetooth device that your phone connects to (like a raspberry pi). Based on the name of the bluetooth connection AND the signal strength, you could create automations for that and guess in what room the phone is located.

This seems like it will make this type of presence detection more straightforward for users. Would be a great feature!

**Comment by samueldefilippo** [comment]
It is also interesting to use the BT of the cell phone to detect the presence of other BT devices.
Like my machine at work.

**Comment by uphillbattle** [comment]
I would like to make an automation that opens my garage door as I enter the "home" zone - but only if I'm in my car (it would be silly if the garage door opens as I come home after walking the dog). I believe a good way to distinguish between being in the car or on foot would be if my phone's Bluetooth is connected to the car's. This would be easily determined with a Bluetooth sensor in the HA companion app.

**Comment by jurgenweber** [comment]
Just like @uphillbattle I would like to detect what car the person is in, presence automation would be fabulous also.

**Comment by fti7** [comment]
I LOVE IT :heart_eyes: Thx @dshokouhi
