### ISSUE TITLE
Overview dashboard menu item not always showing

### ISSUE THREAD

**Issue by tomvanswam** [home-assistant/android#4522]
**Home Assistant Android app version(s):**
2024.6.1-full

**Android version(s):**
14

**Device model(s):**
Google Pixel 8 Pro

**Home Assistant version:**
Core 2024.7.2
Supervisor 2024.06.2 
Operating System 12.4
Frontend  20240710.0

**Last working Home Assistant release (if known):**
Not known, having this issue for a long time.

**Description of problem, include YAML if issue is related to notifications:**
"Overview" menu (default dashboard) item not always present in hamburger menu.
Unfortunately I cannot reproduce this, tried clearing cache, stopping app, restarting phone and it is just hit and miss if I get the overview dashboard item in the menu.
![Screenshot_20240717-072143](https://github.com/user-attachments/assets/1ece53a7-db79-40a7-8dab-fe4effa952ae)
![Screenshot_20240718-110042](https://github.com/user-attachments/assets/12c33f78-77e5-4e75-aa40-2a28ff5ed9e2)

** Additional info
The missing "Overview" menu item is especially annoying in combination with the fact the back function on the Android Companion App works on the "browsing history" instead of the hierachical navigation level in the app. See [this community thread](https://community.home-assistant.io/t/better-navigation-to-root-level-ui-e-g-dashboards/750835?u=tomvanswam)

**Comment by dshokouhi** [comment]
Can you reproduce using chrome for android on the same device? This is not an app issue but a frontend issue, the app has 0 control over teh HA interface.

**Comment by tomvanswam** [comment]
Just checked.
On the same device:
Chrome: shows overview
Firefox: shows overview
App: Does not show overview

**Comment by dshokouhi** [comment]
we still have 0 control over what the frontend chooses to display

**Comment by tomvanswam** [comment]
I'll open a similar issue on the front-end repo, when I get back from holidays

**Comment by jpelgrom** [comment]
Did you change the default dashboard by any chance? That will remove 'Overview' from the menu and is a per device/browser setting.

**Comment by tomvanswam** [comment]
I did not (it showed light gray "Dashboard"), however changing it to "Overview (Default)" the menu option appeared
