### ISSUE TITLE
App dashboard does not refresh when connection lost

### ISSUE THREAD

**Issue by nasserakhter** [home-assistant/android#4536]
**Home Assistant Android app version(s):** 2024.7.3-full

**Android version(s):** android v9 (fireOS 9)

**Device model(s):** Fire tablet 7 (2019)

**Home Assistant version:** 2024.7.3-full

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

Basically, my firehd tablet has the home assistant dashboard loaded on it (using the app). However, if the connection ever drops, such as Wi-Fi timeout or whatnot, the dashboard does not try to reconnect. So until i navigate to another screen and then back, the dashboard will always show the old state values from when it was last connected.

The expectation is it would first of all wait for a network connection and then do some sort of incremental backoff so that it would at least refresh after losing connection rather than require manual navigation. And addtionally, it shows old state values, which is misleading especially when it doesn't say any sort of error message.

Also for what its worth, i also have an embedded webpage to a custom clock HTML, and when the connection came back that page reloaded just fine, its just the state values that were stale.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
do you see the same issue in a browser on the same device? Frontend issues are not typically fixed by the app like the one described.

**Comment by nasserakhter** [comment]
nope, when using the web interface, it reconnects when the server comes back online.

**Comment by dshokouhi** [comment]
ok thanks for checking, this is still out of scope for the app to fix. Please file an issue with the HA frontend

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml
