### ISSUE TITLE
Add application to RuStore

### ISSUE THREAD

**Issue by maxifly** [home-assistant/android#4538]
Are you planing add this application to other store exept GooglePlay?
I would really like you to upload the application to RuStore

**Comment by dshokouhi** [comment]
> Are you planing add this application to other store exept GooglePlay?

yes we are live in F-droid, Amazon and also a few different automotive stores.



> I would really like you to upload the application to RuStore

Until today I have never heard about this app store. Unless they offer an API to automate things I am not sure we will consider, if there is an API its still questionable if we will because it involves some work.

**Comment by balloob** [comment]
We’re not currently interested in publishing to other stores

**Comment by maxifly** [comment]
> yes we are live in F-droid, Amazon and also a few different automotive stores.

Where can I find out the full list of these stores?

**Comment by dshokouhi** [comment]
> > yes we are live in F-droid, Amazon and also a few different automotive stores.
> 
> Where can I find out the full list of these stores?

: https://companion.home-assistant.io/download
