### ISSUE TITLE
Fontawesome, new resource folder only registered after clearing app data

### ISSUE THREAD

**Issue by SVNKoch** [home-assistant/android#4539]
**Home Assistant Android app version(s):**
2024.7.3-full
**Android version(s):**
Android 8.1
**Device model(s):**
OnePlus 5t
**Home Assistant version:**
Core 2024.7.4
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
https://github.com/thomasloven/hass-fontawesome/issues/42#issuecomment-1428280502
HACS Component Fontawesome allows for custom icons. These need to be placed in the folder `custom_icons` eg `<Home Assistant Config>/custom_icons/lamp.svg`. After a restart, the browser shows the icons as expected.
In the android app these icons are still blank though. It appears this new folder is maybe not properly registered to the app?
When the data of the app is cleared, and you re-setup the app, then the icons show as expected.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
Icons missing:
![Screenshot_20240730-235007__01](https://github.com/user-attachments/assets/d0a61a97-e4e6-4234-a2d5-7cca8f727b5b)
after resetting data:
![Screenshot_20240730-234900__01](https://github.com/user-attachments/assets/c23f1428-0c71-42e6-ac24-293cb761921d)

**Additional information:**
HACS 134.0, **Fontawesome 2.1.3** (otherwise we will have other issues right now)

**Comment by dshokouhi** [comment]
The android app respects the caching level set by the HA frontend, you will need to work with the custom card author instead of opening an issue here.
