### ISSUE TITLE
Nabu Casa | Paying subscription with gift cards

### ISSUE THREAD

**Issue by serrq** [home-assistant/android#4553]
I would like to pay subscription with crypto currencies, and these shops support them.

• https://www.coinsbee.com/en/shop

• https://www.bitrefill.com/eu/en/gift-cards/

Please adding this payment method to the other ones (prepaid balance).

• https://www.nabucasa.com/pricing/

**Comment by dshokouhi** [comment]
This is not a nabu casa request area.
