### ISSUE TITLE
Mobile Network Strength Sensor

### ISSUE THREAD

**Issue by camsaway** [home-assistant/android#4572]
**Is your feature request related to a problem? Please describe.**

Not a problem. But more information I want access to. I want to be able to track mobile network availability and signal quality.

**Describe the solution you'd like**

The Phone Sensor -SIM1 and SIM2 to have extra attribute(s) that show mobile network Strength and connection mode, etc.

**Describe alternatives you've considered, if any**

I don't have any other ideas/alternatives.

**Additional context**

Below screenshot from network cell info shows the things I'd like to track RSRP (signal strength) and DataNetwork(e.g. LTE, 5G, etc)

![Screenshot_20240811_144732_Network Cell Info Lite](https://github.com/user-attachments/assets/83cf4fd2-f043-48ed-ac16-ce89a884f7b7)

**Comment by igorsantos07** [comment]
If the attributes are already there, you could simply create a template sensor exposing those values directly as a sensor, and on new HA versions, even link it to the original device.

**Comment by dshokouhi** [comment]
a sensor like this would never update immediately, it would update during the normal sensor update interval. Would that even be useful here?

**Comment by camsaway** [comment]
Unfortunately the attributes aren't there yet. That's what this request is
for. (Screenshot is from another app to show that the data does exist)

In terms of frequency, it's a fair point. I hadn't considered that.  15min
default update and 1 min fast update should do for my use case though I
think. I'm not trying to create some sort of coverage mapping tool.

So in short, I still think it would be useful to add the attribute.

Regards


Cameron Gray

079 528 4802

***@***.***


https://www.linkedin.com/in/camerongray76

**Comment by dshokouhi** [comment]
> The Phone Sensor -SIM1 and SIM2 to have extra attribute(s) that show mobile network Strength and connection mode, etc.

this should not be an attribute but a separate sensor for signal strength

**Comment by camsaway** [comment]
Happy either way but all the other info is as attributes under the SIM card
sensor (with multiple simcards you will get multiple values) so I was just
proposing to continue this pattern.

Regards


Cameron Gray

079 528 4802

***@***.***


https://www.linkedin.com/in/camerongray76
