### ISSUE TITLE
Notifications reliability

### ISSUE THREAD

**Issue by iulko** [home-assistant/android#4574]
On Android if you use websocket notifications they come from the server with no problem, they are more secure in private. What the websocket notifications have a problem with is their reliability.  Can something be done so that when we are witchout internet/disconnected/HA instance not reachable at the moment, that the notifcations would wait for us to get them? 
Right now they are gone forever. Only place they are left is the notifications history, but im not even sure about that.

**Comment by dshokouhi** [comment]
please do not skip the issue template, everything there is important to help yout out. PLease add back all requested info.

**Comment by dshokouhi** [comment]
the server does indeed keep notifications until the app gets them, if you see them in notification history the app already got them.

**Comment by dshokouhi** [comment]
you do not know that is the case as you have not provided enough information to tell what the actual issue is. In this case logs are required from both companion app and HA core at the time of issue occurrence.

**Comment by dshokouhi** [comment]
> I do know that it is the case. Please stop being condescending in your responses.

I have asked now for the 3rd time that requested data be provided and you  have not done so and are demanding that an issue exists. I have actually used Websocket notifications for testing recently and I know that it is working. There is an issue template for a reason when you create an issue as developers need more information. You have not even provided the app version or device model nor an example of the automation or logs. All of which are required. Logs and required data help tell teh full picture.

**Comment by jpelgrom** [comment]
Hi,

Notifications are sent by your server, and behavior for 'keeping' them is thus controlled by the server. Currently, if a local push channel (websocket) is active it will [try to send](https://github.com/home-assistant/core/blob/74a09073c2bcf5cf73bd43b6dfca45bd21f65d64/homeassistant/components/mobile_app/notify.py#L131) it using that channel. If the app does not confirm it has been received [within 10 seconds](https://github.com/home-assistant/core/blob/74a09073c2bcf5cf73bd43b6dfca45bd21f65d64/homeassistant/components/mobile_app/push_notification.py#L60), it will be [sent to Firebase instead](https://github.com/home-assistant/core/blob/74a09073c2bcf5cf73bd43b6dfca45bd21f65d64/homeassistant/components/mobile_app/push_notification.py#L56) (if you're using the `full` flavor of the app). In other words: this is not a bug.

I'm not 100% sure why this setup was chosen in the past, but for most setups it will probably be the most reliable way to get the notification to your device _fastest_. 

If you want to have this behavior changed (for the reasons you mentioned, or perhaps when using the `minimal` flavor which has no Firebase fallback), that requires a change in the server/Home Assistant core. Please open a [new core feature request](https://community.home-assistant.io/c/feature-requests) for it :)
