### ISSUE TITLE
Refresh on Home Assistant landing page doesn't work

### ISSUE THREAD

**Issue by agners** [home-assistant/android#4576]
On a fresh Home Assistant OS installation, the OS shows a landing page first while downloading the latest version of Home Assistant Core. This landing page is a minimal web server and refreshes once Core got loaded (see the landing page's [script.js](https://github.com/home-assistant/landingpage/blob/2024.04.0/rootfs/usr/share/www/static/scripts.js#L66)). It seems that refreshing once Core got downloaded doesn't work automatically. It seems to work when using browsers on a desktop.

**Home Assistant Android app version(s):**
2024.8.1-full

**Android version(s):**
Android 14

**Device model(s):**
Pixel 8 Pro

**Home Assistant version:**
2024.8.1

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

![image](https://github.com/user-attachments/assets/849f44b4-9941-4cff-9391-79bb5eebf1aa)

**Additional information:**

**Comment by dshokouhi** [comment]
does this work as expected in chrome for android on the same device?

**Comment by agners** [comment]
Hm, it seems that the Android app navigates to `/auth/authorize?response_type=code&client_id=https://home-assistant.io/android&redirect_uri=homeassistant://auth-callback`. This then makes the relative URL poll `./manifest.json` to actually poll `/auth/manifest.json`, which never becomes available :cry: :see_no_evil:  .

The landing page always serves index.html, no matter what path is browsed. We probably should redirect, or just poll the absolute path `/manifest.json`.

So this is really a landing page implementation issue. Closing here.

> does this work as expected in chrome for android on the same device?

Sorry, was just typing the above. I didn't try, but if I would have it would have worked since manually I'd have typed `http://homeassistant.local:8123 :sweat_smile:
