### ISSUE TITLE
after a while sensors stop updating!

### ISSUE THREAD

**Issue by schuballaa** [home-assistant/android#4581]
**Home Assistant Android app version(s):**
2024.7.3-full
**Android version(s):**
14
**Device model(s):**
Xaumi 11T Pro
**Home Assistant version:**
13.0 OS
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
after a Wihle, Companion does not update Sensors Anymore. (Backround, battery opti settenings Done)
I also Tried to set stay Connection and update every minute...

But after a While Handy Device Stats arnt uptated anymore...

If i manualy Open the App on my Handy its workes again!

I thaugt its maby killing app in Backround, so i installed Logcat, and there i saw errors things like this:
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Companion App Logs:**
[homeassistant_companion_log_7-14-2024_11-46-17.txt](https://github.com/user-attachments/files/16611384/homeassistant_companion_log_7-14-2024_11-46-17.txt)
```

```

**Screenshot or video of problem:**
(after manuall open App on Handy)
![photo_2024-08-14_12-12-14](https://github.com/user-attachments/assets/7a7fe3a2-0786-4034-be6e-c337137d6030)

**Additional information:**

**Comment by dshokouhi** [comment]
Sorry certificate errors are not ones the app can solve, you will need to solve it by either creating a new certificate or importing the CA to the devices trust store.

```
08-14 11:44:56.562 12425 12461 E LaunchPresenter: Issue updating Registration
08-14 11:44:56.562 12425 12461 E LaunchPresenter: io.homeassistant.companion.android.common.data.integration.IntegrationException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

**Comment by dshokouhi** [comment]
if the app gets a certificate error, its a valid error. Not sure why it happens when the app is closed but the app requires a valid certificate all the time. Maybe its related to your own networking setup?

**Comment by schuballaa** [comment]
i use chertbot fpr my cert witch works without problems for years. with my new handy i get this error, so i think its a bug (if cert error it should stop working even if i manual open the app...)

manual open = works for a while
app in backround = works ... but after a while stops working...

i do not thing that this is an cert or network error

if you do not want to help i hafe so workaround with tasker and mqtt... not so profesional...

**Comment by schuballaa** [comment]
[https://schuballaa.de:8123/lovelace/default_view](url) the cert is ok...

**Comment by dshokouhi** [comment]
> i do not thing that this is an cert or network error
> 
> if you do not want to help i hafe so workaround with tasker and mqtt... not so profesional...

if android gives the app a certificate error the app cannot ignore it, due to the nature of home assistant certificate errors can only be solved by the user unless you are using Nabu Casa which in that case NC will correct the issue. The app cannot fix the issue, so its not that we dont want to help, its that we literally cannot. We have seen in the past users having a similar issue and they were able to solve it in their own network. Probably some proxy or other issue unrelated to HA.

https://developer.android.com/privacy-and-security/security-ssl#UnknownCa

The app has already done the recommended  code  changes  by Google to accept user imported CA's so we have done all that we can to solve this issue.

**Comment by dshokouhi** [comment]
Some examples of users with a similar issue: https://github.com/home-assistant/android/issues?q=is%3Aissue+trust+anchor+is%3Aclosed

Here is an actual example of a user saying how they solved their own issue https://github.com/home-assistant/android/issues/3153
