### ISSUE TITLE
Connection problem on no home network with the same SSID

### ISSUE THREAD

**Issue by DavidAntonin** [home-assistant/android#4582]
Hi, 
I ran into a problem connecting on a network that has the same SSID as my home network. The app expects to be accessed via the local address, but logically that doesn't work. The only solution for me so far is to switch to mobile data. Is there any other solution to this? Force the app to connect via the external address when the internal one doesn't work despite the SSID being marked as the home network.

**Comment by jpelgrom** [comment]
You can use the BSSID instead in this situation, to mark a specific access point as home and not others: http://companion.home-assistant.io/docs/troubleshooting/networking?_highlight=bssid#setting-up-the-app (see info box at the end).
