### ISSUE TITLE
Adding Second Home Assistant Instance does not work

### ISSUE THREAD

**Issue by gravok** [home-assistant/android#4583]
**Home Assistant Android app version(s):**
*2024.7.3-full*
**Android version(s):**
*14*
**Device model(s):**
*Pixel 6 Pro*
**Home Assistant version:**
*Core 2024.8.1*
*Supervisor 2024.08.0*
*Operating System 13.0*
*Frontend 20240809.0*
**Last working Home Assistant release (if known):**
*N/A*
**Description of problem, include YAML if issue is related to notifications:**
I try to add a second Home Assistant Server to my companion app via "Add Server" Button.
I am able to reach my instance, and can complete the authentification. However, after the authentification the server is not added.

In the UI there is no error message, or indication why the addition failed.

I checked Companion App Logs, however there seems to be no related entry to this process.
I checked the Logs of my second Home Assistant Instance - which also do not contain anything related to this.

Due to being run unencrypted at the moment I can easily trace the ongoing traffic:

```http
GET /auth/providers HTTP/1.1

HTTP/1.1 200 OK
[...]
```

```http
POST /auth/login_flow HTTP/1.1

HTTP/1.1 200 OK
[...]
```

```http
POST /auth/login_flow/0df0fb554e42abb314c4cf1874678fd9HTTP/1.1

HTTP/1.1 200 OK
[...]
{"type":"create_entry","flow_id":"0df0fb554e42abb314c4cf1874678fd9","handler":["homeassistant",null],"description":null,"description_placeholders":null,"result":"a5e32a2cefe8457eba2de65a860b48c9"}
```

I would provide more useful information, however as I stated above, none of the logs contained any information about a problem from what I could tell. The apps seemingly just stops communicating with the second server after a successful login.

**Companion App Logs:**
N/A

**Screenshot or video of problem:**
Not done any yet

**Additional information:**

**Comment by jpelgrom** [comment]
What happens in the app immediately after logging in?

Do you see your dashboard, or do you see a screen to register your device name?

**Comment by jpelgrom** [comment]
Hmm, and there is absolutely nothing in the app logs or on the server logs after this? You said related - anything that you might consider unrelated could still be helpful. I'm unable to reproduce it so far.
