### ISSUE TITLE
Wear OS wont update Heart Rate Sensor after arround 30 minutes

### ISSUE THREAD

**Issue by GammaPotato** [home-assistant/android#4584]
**Android version(s):**
```
Samsung Galaxy Watch 6 Classic (SM-R960)
One-UI: 5.0 Watch 
System Version: 13
Software Version: R960XXU1AXC2

Samsung Galaxy S24 Ultra (SM-S928B/DS)

One-UI: 6.1
Android Version: 14
Basebandversion: S928BXXS3AXGF
```

**Home Assistant version:**
```
2024.8.1      Core
2024.08.0     Supervirsor
13.0          Operating System
20240809.0    Fronted
```

**Description of problem, include YAML if issue is related to notifications:**

For Some reason The Wear OS App dont send heart rate Sensor after arround 30 minutes when the screen is off. All Other Sensors gets updated but not the heart rate sensor. i Turned off the "Adaptive Battery" and "Put apps to sleep". Also "remove permissions when background" is off too.

to Fix that i have to Activate the screen and open the HA App on the watch. and minimize it again. The sensor gets update every 1 to 3 minutes for next 30 minutes. After that. Same problem. Also Generally no Sensor updates when i close the app on Task Manager. 

is it possible to add it in to the Background services? HA on watch is not showen to run in background. Watch OS has a own feature to check that. and HA on watch stays in normal Task manger and not in Background services. 

**Companion App Logs:**

[homeassistant_companion_log_7-16-2024_21-34-14.txt](https://github.com/user-attachments/files/16640990/homeassistant_companion_log_7-16-2024_21-34-14.txt)

*Text is in German. Im from Austria*
![Screenshots watch](https://github.com/user-attachments/assets/42429207-23d0-4928-ba13-2fb803ac9056)

**Comment by dshokouhi** [comment]
as you have a samsung watch you need to open the samsung companion app on your phone and grant the HA app background access

**Comment by dshokouhi** [comment]
also make sure the app has access to body sensors all teh time wehn you go to the permission screen.

Also as an FYI the heart rate sensor will be going away soon due to google policy changes: https://github.com/home-assistant/android/pull/4552

**Comment by GammaPotato** [comment]
Both apps have background access. Why remove it? Just build in the ability for the app to run in the background, like in my screenshot. I have seen many apps that can run in the background as long as they want when they have this function.

**Comment by dshokouhi** [comment]
> I have seen many apps that can run in the background as long as they want when they have this function.

per the upcoming policy change teh only way for an app to be  approved to run in the background for those sensors is on a case by case basis with each manufacturer

https://developer.android.com/about/versions/13/behavior-changes-13#body-sensors-background-permission

`Note: This is a "hard-restricted" permission that cannot be held by an app until the device's installer allowlists the permission for your app.`

**Comment by dshokouhi** [comment]
unfotunately your logs are from the phone and not the watch so we wont be able to see if there is an error from the sensor, did you check the permission for the app to ensure its granted all the time? This is for the sensors permission

**Comment by GammaPotato** [comment]
There is no button to find the logs on watch

And yes. Premissons for background are granted. Body sensors background to. ALL permissions granted for everytime.

**Comment by dshokouhi** [comment]
> There is no button to find the logs on watch

yes there is no easy way to get logs off the watch, the only way is to connect to android studio

My heart rate sensor updates all the time without issue

![image](https://github.com/user-attachments/assets/e0e1a203-ae09-44f9-9fec-3d28a7f2e512)


also our sensor worker does indeed run in the background as evidenced by all other sensors updating so its possible there is an error but I am not sure at this point. The symptoms sound like a permission or background access issue. Logs may tell us whats happening.

**Comment by GammaPotato** [comment]
im connected to android studio. can u Tell me how to get the HA logs ?

**Comment by dshokouhi** [comment]
ok you want to open the Logcat window and make sure your device is selected in the drop down. In the search panel you can type  in `HRSensor` and we should see some log lines like:

https://github.com/home-assistant/android/blob/master/wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt#L109

or

https://github.com/home-assistant/android/blob/master/wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt#L111

that will tell us if were getting data or not

youll need to reproduce the issue as well which may not be as easy when hooked up to the debugger.

if you see log lines with values changing then we need to look at the time of occurrence in teh logs and grab all the logs at the time the value was supposed to change. Again this will only be helpful if hte issue is reproduced and we can see that in teh logs

**Comment by GammaPotato** [comment]
i have the live logs and i try to get that issue. the first thing what i see is this here

2024-08-16 22:50:26.858 16285-16467 HRSensor                io.homeassistant.companion.android   D  Re-registering listener as it appears to be stuck

**Comment by dshokouhi** [comment]
that log line means we didnt get any HR events for 1 minute and we are re-registering to get more updates, if that is all you see then that means the device is not telling the app it has updates and there is not much we can do there in those cases.

Are you seeing it stop completely or just infrequent updates? Does it stop for days at a time?

**Comment by GammaPotato** [comment]
Got this log. some errors are shown. And the updates stop randomly. after a couple hours there can be updates for up to 10 minutes and then for hours nothing. In this log: Since biggining i get no update on the HR sensore

[HA Watch Logs.txt](https://github.com/user-attachments/files/16641660/HA.Watch.Logs.txt)

**Comment by GammaPotato** [comment]
Oh and since start of the log no HR Sensor data got updated.

**Comment by dshokouhi** [comment]
i dont see any heart rate data coming into the app at all, and you double checked the Sensors permission for the app. Outside of that and the setting from teh samsung companion watch app on the phone.  I am afraid your device is simply not reporting to the app that it has data during these intervals. Which still feels like its being blocked by background activity in some way because our code is not reachable at times.

**Comment by GammaPotato** [comment]
I told ya it has all permissions...
```
      com.google.android.c2dm.permission.RECEIVE: granted=true
      android.permission.FOREGROUND_SERVICE: granted=true
      android.permission.RECEIVE_BOOT_COMPLETED: granted=true
      android.permission.INTERNET: granted=true
      android.permission.ACCESS_NETWORK_STATE: granted=true
      io.homeassistant.companion.android.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION: granted=true
      android.permission.VIBRATE: granted=true
      android.permission.ACCESS_WIFI_STATE: granted=true
      android.permission.WAKE_LOCK: granted=true
        android.permission.POST_NOTIFICATIONS: granted=true, flags=[ USER_SET|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED]
        android.permission.ACCESS_FINE_LOCATION: granted=true, flags=[ USER_SET|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED]
        android.permission.BODY_SENSORS: granted=true, flags=[ USER_SET|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED]
        android.permission.BLUETOOTH_CONNECT: granted=true, flags=[ USER_SET|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED]
        android.permission.ACCESS_COARSE_LOCATION: granted=true, flags=[ USER_SET|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED]
        android.permission.READ_PHONE_STATE: granted=true, flags=[ USER_SET|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED]
        android.permission.BODY_SENSORS_BACKGROUND: granted=true, flags=[ USER_SET|REVOKE_WHEN_REQUESTED|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED|RESTRICTION_INSTALLER_EXEMPT]
        android.permission.BLUETOOTH_ADVERTISE: granted=true, flags=[ USER_SET|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED]
        com.google.android.clockwork.settings.WATCH_TOUCH: granted=true, flags=[ USER_SET]
        android.permission.ACTIVITY_RECOGNITION: granted=true, flags=[ USER_SET|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED]
        android.permission.RECORD_AUDIO: granted=true, flags=[ USER_SET|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED]
        android.permission.ACCESS_BACKGROUND_LOCATION: granted=true, flags=[ USER_SET|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED|RESTRICTION_INSTALLER_EXEMPT]
        android.permission.BLUETOOTH_SCAN: granted=true, flags=[ USER_SET|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED]
```

**Comment by dshokouhi** [comment]
> I told ya it has all permissions...

unfortunately it does not tell us if its granted all the time

` android.permission.BODY_SENSORS: granted=true, flags=[ USER_SET|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED]`

![image](https://github.com/user-attachments/assets/c7360994-79fa-44f4-8990-102fbd9a64e3)

the other logs are meaningless if you cant confirm the HRSensor line getting actual data to send

**Comment by GammaPotato** [comment]
Permission is set

![Screenshot_20240816_231850_permissioncontroller.png](https://github.com/user-attachments/assets/e95e7039-c28f-4a5e-bcab-24f6bcad44c1)

**Comment by GammaPotato** [comment]
Got this in log right now but sensor got no updates. still no update since 33 Minutes

```
2024-08-16 23:20:05.196 16285-18669 HRSensor                io.homeassistant.companion.android   D  Re-registering listener as it appears to be stuck
2024-08-16 23:20:05.198 16285-18669 SensorManager           io.homeassistant.companion.android   D  unregisterListener :: io.homeassistant.companion.android.sensors.HeartRateSensorManager@bb71f47
2024-08-16 23:20:05.200 16285-18669 SensorManager           io.homeassistant.companion.android   D  registerListener :: 83, Samsung HR None Wakeup Sensor, 200000, 0, io.homeassistant.companion.android.sensors.HeartRateSensorManager@bb71f47
2024-08-16 23:20:05.209 16285-18669 HRSensor                io.homeassistant.companion.android   D  Heart Rate sensor listener registered
```

**Comment by GammaPotato** [comment]
this moment all sensors got randomly updated. i did nothing. this is the log while this happend. i didnt understand everything but i think there got something killed?

[HA Watch Logs 2.txt](https://github.com/user-attachments/files/16641843/HA.Watch.Logs.2.txt)

**Comment by dshokouhi** [comment]
yes this last log did get an event to send back

`2024-08-16 23:22:24.600 18741-18741 HRSensor                io.homeassistant.companion.android   D  HR event received with accuracy: high and value: 69.0 with event count: 1`

we can even see at times it gets an update after sensors were already updated which means the next update that gets sent to the server will contain the update

```
2024-08-16 23:23:00.710 18741-18785 SensorReceiver          io.homeassistant.companion.android   I  Sensor updates and sync completed
2024-08-16 23:23:00.914 18741-18741 HRSensor                io.homeassistant.companion.android   D  HR event received with accuracy: high and value: 68.0 with event count: 1
```

so in this case it looks like its working as expected. I suspect the issue is just the device not sending the app updates at certain time. Why I am not sure.

One thing i noticed in the OP `Also Generally no Sensor updates when i close the app on Task Manager.` Thats to be expected, closing the app means the work manager schedule will cease to exist. The app needs to be able to run in teh background at all times. We do not recommend closing the app.

**Comment by GammaPotato** [comment]
> we can even see at times it gets an update after sensors were already updated which means the next update that gets sent to the server will contain the update

i did some changes to the android system with adb. i will tell ya tomorrow if that fixed it.

and i dont close the app. Whats the normal update rate for the HR sensor?

**Comment by dshokouhi** [comment]
Roughly every 15 minutes but it can vary, the sensor will also update anytime any other sensor that is push based updates like the interactive sensor.

https://companion.home-assistant.io/docs/wear-os/sensors

**Comment by GammaPotato** [comment]
> the sensor will also update anytime any other sensor that is push

not here. all sensors get updates but only the HR sensor not while the others are updating

i test some changes now and try to send refresh commands from HA

![chrome_tacmujcQ1p](https://github.com/user-attachments/assets/16d4e479-cc33-475a-8031-ceca1d3ccc3b)

**Comment by dshokouhi** [comment]
> > the sensor will also update anytime any other sensor that is push
> 
> not here. all sensors get updates but only the HR sensor not while the others are updating

Im explaining how frequently sensor updates are requested, in your case your sensor is simply not reporting any data which is unexpected. However as seen by the logs we are at least requesting it alongside all other sensors which is how it works.

**Comment by GammaPotato** [comment]
*After couple hours of testing i have this result:*
![Sensor Trigger and Updates](https://github.com/user-attachments/assets/a001eb22-29b7-4f5a-a8de-a4345b689cd1)

i set up some counter for:
```
SensorWorker
Screen off Trigger
Screen on Trigger
Sensor Update command (send per Notification)
Hr Updates
```
The hole day im missing a lot off Data but the Samsung health app has Data for the hole time. 
![photo_2024-08-17_19-20-52](https://github.com/user-attachments/assets/143191e6-5f6f-4c6a-91e5-f942800c6974)

The Importance Sensor tells most time:
```
perceptible
cached
Top_sleeping
```

i think the problem is not only on the Watch side.

**Comment by GammaPotato** [comment]
3 days later. No Answer. Fixed by uninstalling HA from my Galaxy Watch 6. The app is not corecctly working for Samsung.
