### ISSUE TITLE
Loading screen flows of the screen

### ISSUE THREAD

**Issue by CFenner** [home-assistant/android#4590]
**Home Assistant Android app version(s):**
2024.7.3-full

**Android version(s):**
8.1.0

**Device model(s):**
NS Panel Pro

**Home Assistant version:**
2024.8.2

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:*

The open home foundation logo flows off the screen when *loading data* appears.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![tempImageWjb6ck](https://github.com/user-attachments/assets/dcb01a52-292f-4c14-a247-4375adfa155b)
![tempImageUOvCYY](https://github.com/user-attachments/assets/0b9b37e5-d869-4b73-bb64-c793277ad386)
![tempImageSgW1TZ](https://github.com/user-attachments/assets/00cbbc0c-6b47-4986-846a-19cc4be3a9ed)
![tempImageuraAps](https://github.com/user-attachments/assets/56306df8-0af8-4c3b-800a-daa5737ba261)

**Additional information:**

**Comment by dshokouhi** [comment]
That is not an app provided screen but an HA frontend screen. You'll want to file this issue with the HA frontend team

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml
