### ISSUE TITLE
Home Internet-Failed, Home WiFi-operational, App on LTE tries to connect via Cloud only

### ISSUE THREAD

**Issue by DijkstraSolutions** [home-assistant/android#4599]
**Home Assistant Android app version(s):**
2024.7.3-full

**Android version(s):**
14

**Device model(s):**
Google Pixel 7 Pro

**Home Assistant version:**
2024.8.2

**Last working Home Assistant release (if known):**
not known

**Description of problem, include YAML if issue is related to notifications:**
This is a client-side issue only. It appears the app does not run communications over the WiFi connection even though the WiFi's are defined correctly (does not authenticate as per my settings).  They only appear to disable/enable the authentication (away from home, authenticate).

**Additional information:**

To reproduce:

With everything correctly set up, disable the Internet on the home router. LTE is enable on your phone and so is WiFi. Your WiFi networks are correctly defined, but the connection still attempts over LTE only and you connection to Home Assistant is now disrupted. Disable your LTE and everything works again. Once you enable LTE again, connection to Home Assistant failed.

Expected behavior:

When on the defined wifi networks, traffic should travel locally.

This was discovered during a power outage for the region and the cable modem was offline (house had power due to generator, so WiFi, home assistant worked via web browser and Phone App once LTE was disabled).

Other thing I just thought of, don't think this would make a difference as the App should decide which path to communicate, but the HotSpot on the phone was also turned on.

**Comment by dshokouhi** [comment]
> It appears the app does not run communications over the WiFi connection even though the WiFi's are defined correctly (does not authenticate as per my settings). They only appear to disable/enable the authentication (away from home, authenticate).

please get us the logs it will tell us the decision making process here. For example we dont use Wifi if it has no data to use.

you may want to follow this request instead: https://github.com/home-assistant/android/issues/3961

**Comment by dshokouhi** [comment]
After re-reading indeed you need to follow #3961 as your device is not using wifi. Android by default does not use Wifi if there is no internet and the phone has a mobile connection.
