### ISSUE TITLE
[Unknown] Digital assistant app->Voice input: None

### ISSUE THREAD

**Issue by OdinVex** [home-assistant/android#4600]
**Home Assistant Android app version(s):** 2024.7.3-full

**Android version(s):** 11

**Device model(s):** OnePlus Nord N10 5G+

**Home Assistant version:** (OS) 13.1

**Last working Home Assistant release (if known):** ---

**Description of problem, include YAML if issue is related to notifications:** Android Settings->Apps & notifications->Default apps->Digital assistant app (Home Assistant)->Voice input: None, HA does not show up as a possible input.

**Companion App Logs:**

```
Unrelated
```

**Screenshot or video of problem:**
---

**Additional information:**
Home Assistant has all permissions, it just isn't showing up as a Voice input for Digital assistant app.

**Comment by jpelgrom** [comment]
>Voice input for Digital assistant app.

Can you share a screenshot of the settings screen? I'm not seeing a separate voice input option here, although Assist isn't available as a voice input service so I wouldn't expect it.

![Screenshot_20240831-205040.png](https://github.com/user-attachments/assets/eebde8a5-4373-493a-a289-f05a3deec40f)

> This is the Play Store version, though I'll be switching to F-Droid's eventually.

Assist functionality is the same for both flavors

**Comment by jpelgrom** [comment]
> (edit: TTS, "Ok, Assistant, add bread to my shopping list" without manually opening the software)

Wake word is another open request, and not easily supported by non-system apps like HA.

The digital assistant role can be set so you can access Assist anywhere using the button/gesture to open the assistant app, that's all. For more information see [Assist](https://www.home-assistant.io/voice_control/). A general purpose voice input service is out of scope (and also not what most other assistant apps offer).

Going to close this as there is no issue here :)
