### ISSUE TITLE
Geocoded Location Entity does not expose longitude and latitude correctly

### ISSUE THREAD

**Issue by lukshan13** [home-assistant/android#4602]
**Home Assistant Android app version(s):**
v2024.7.3-full

**Android version(s):**
14 May
**Device model(s):**
Pixel 7 Pro
**Home Assistant version:**
haOS on RPi 4B, 
Core - 2024.8.3
Supervisor - 2024.08.0
Operating System - 13.1
Frontend - 20240809.0

**Last working Home Assistant release (if known):**
N/A
**Description of problem, include YAML if issue is related to notifications:**
The entity exposed by the companion app for Geocoded location does not have a separate longitude and Lattitude attribute. Instead, they are presented in an attribute called 'location' as a tuple as such: [long, lat]. HA sees them the same way, with it reporting as long, lat. 

The Maps card on HA needs a separate long and lat attribute in order to display the location. It's not able to process this combined location. 

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![image](https://github.com/user-attachments/assets/939983f5-3d63-4926-b90d-97d022a7cfd0)

![Screenshot 2024-09-02 at 18 28 14](https://github.com/user-attachments/assets/afa95f1a-7d2c-4c0a-8685-35377f6e2ad7)

![Screenshot_20240902-182614](https://github.com/user-attachments/assets/13d96c68-71c4-4143-ba0d-3c638e03e6e7)

**Additional information:**

**Comment by dshokouhi** [comment]
This is not a bug but as designed. The reason for combining the attributes is so the entity does not appear on the map. If you want that you can create a template entity.

**Comment by jpelgrom** [comment]
> If you want that you can create a template entity.

Better: use the device tracker
