### ISSUE TITLE
Dialogs with Default Scrollbars, Don't Show Their Scrollbars. Only Custom Scroll Indicators are Visible

### ISSUE THREAD

**Issue by SVNKoch** [home-assistant/android#4604]
**Home Assistant Android app version(s):**

**Android version(s):** 8

**Device model(s):** OnePlus 5T

**Home Assistant version:** 2024.8.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

Some dialogs use a custom scrollbar indicator. They show up on android.
Some other dialog use the default scrollbar indicator. Those don't show up, thus the dialog has no scrollbar indication.
This requires 2 fixes IMO: 1) show a scrollbar for the default one, 2) change all scrollbars to the custom ones. Also see https://github.com/home-assistant/frontend/issues/15664

Here are two Dialogs side by side
Left: Settings > Devices & Services > Helper > Create Helper
Right: Settings > Devices & Services > Integration > Add Integration
In Firefox on Windows:
![grafik](https://github.com/user-attachments/assets/20a19680-a768-498e-9888-375d19e826cd)

In the Android companion app:
![grafik](https://github.com/user-attachments/assets/4df81cf3-aa40-4752-bc93-acee05b667a7)

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Frontend issues are actually for the frontend team to fix. The app does not fix these issues. The correct place is the frontend.
