### ISSUE TITLE
Notifications keep coming in after removing 2nd HA server

### ISSUE THREAD

**Issue by TheGabeMan** [home-assistant/android#4605]
**Home Assistant Android app version(s):**
2024.7.3-full

**Android version(s):**
Android 14 updated up to August patches

**Device model(s):**
Pixel 7

**Home Assistant version:**
2024.8.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

I have my own HA server running and my partner (not living with me) has a HA install at here place running. For testing purpose I add here HA server as 2nd HA server in the app. My server is accessed through NabuCase, her server I connected to over TailScale. After doing testing, creating automations, receiving notifications of her devices I was done and I removed her server from the HA app.

But I still kept receiving notifications from her HA Server. Rebooting my phone, removing tailscale, force closing HA app didn't work. I had to clear cache and clear storage in the HA app and then reconnect my HA server to get rid of the notifications of her system.

So the issue is solved for me now, but not sure if this is supposed to work like this.

**Comment by jpelgrom** [comment]
> but not sure if this is supposed to work like this

Yes, this is working as designed but I can see the confusion. Notifications are delivered using Firebase - public cloud - and after initial registration, do not depend on the server being in the app. Firebase generates a push notification token/receiver _for your device_, not server in the app. To stop receiving notifications, delete the integration on your server end as well.
