### ISSUE TITLE
huawei phone no location problem.

### ISSUE THREAD

**Issue by drveni** [home-assistant/android#4613]
im using huawei mate 50 pro no google services.

it is an application on a mobile phone. no matter how much I searched on the internet, I did not find a solution. Namely, it is about the location of the mobile phone which, when the mobile phone enters the zone, does something. or if it comes out
the mobile phone has everything. there are also applications, the battery is not killed in the background. the thing just doesn't work.
when I go to the server itself and look, it says senosr location Unknown. but battery status or other info work.

is the google services missing on the cell phone and that's why it doesn't work and there is no support, or is it supposed to work but it doesn't. Note that navigation and other apps that use location work.

I didn't have this problem when I had a cell phone with google services. so the only thing is the assumption that they don't work on those mobile phones. in principle, there are many mobile phones on the market that do not have Google services and are not Chinese. they simply exist in custom rom. so please just confirm if it doesn't work because there is no google service or simply it doesn't work exclusively on huawei mobile phone?

thanks for any help or information.

**Comment by dshokouhi** [comment]
You need a device with Google services in order for location to work.

https://companion.home-assistant.io/docs/core/android-flavors
