### ISSUE TITLE
Getting duplicate notifications when user of the app is Administrator

### ISSUE THREAD

**Issue by Dzoker2** [home-assistant/android#4617]
I am logged into the Android Companion App with my username for which in Settings/People in the HA has the Administrator toggle set to On. I have various Automation's with Actions to notify my Phone and whenever one of the Automation's are triggered, I get duplicate notifications on my phone. Setting the Administrator toggle in Settings/people to Off, causes when the same Automation's are triggered to send only one Notification to my phone.

**Comment by Dzoker2** [comment]
Turning the Administrator toggle off and On again in HA resolved the duplicate notifications!

**Comment by dshokouhi** [comment]
just a FYI that has nothing to do duplicate notifications, most likely the issue lies in the automation or more specifically the action used. Strange placebo effect though.
