### ISSUE TITLE
Offline location cache

### ISSUE THREAD

**Issue by Cyberes** [home-assistant/android#4627]
**Is your feature request related to a problem? Please describe.**

Sometimes I travel through regions of no cellular service. This results in large gaps in my HA location history.

**Describe the solution you'd like**

The app could cache location points when it is unable to reach the server. When it is able to reach the server again it will upload these cached points.

**Describe alternatives you've considered, if any**

[Phonetrack](https://github.com/julien-nc/phonetrack) does this sort of thing but it would be super convenient if I didn't have to run 2 tracking apps at once and could use the HA app for everything.

**Additional context**

None.

**Comment by dshokouhi** [comment]
> Sometimes I travel through regions of no cellular service.

as the app relies on Google services for location, if you got no cell service then Google will not be able to tell the app where you are and we therefore cannot record it.

**Comment by Cyberes** [comment]
Huh. And it doesn't get the raw position from the phone's GPS?

**Comment by dshokouhi** [comment]
no we use google play services to be battery friendly and have an easy to maintain implementation

https://companion.home-assistant.io/docs/core/android-flavors

many developers use google services.

**Comment by jpelgrom** [comment]
There's also another issue: the `mobile_app` integration is designed to handle current states. It doesn't allow inserting historical states. (Not sure about the device tracker platform either). If this request is something that should be considered, which I personally don't think should as HA isn't a location tracking app, that will need to be changed first.

**Comment by dCypherNx** [comment]
some times the my server goes offline(due broadband provider issues at server side), so a buffer can be usefull

**Comment by dshokouhi** [comment]
Closing as there is no support for backlogging location data in the server side
