### ISSUE TITLE
There are some issues regarding the display of the iframe widget.

### ISSUE THREAD

**Issue by LeiDuang** [home-assistant/android#4638]
**Home Assistant Android app version(s):** 2024.7.3-fill

**Android version(s):** Android 14

**Device model(s):** Xiaomi 12 Pro

**Home Assistant version:** Core 2024.8.1

**Last working Home Assistant release (if known):** /

**Description of problem, include YAML if issue is related to notifications:**

I created an "type: iframe" widget in Home Assistant with the URL set to "https://typhoon.slt.zj.gov.cn/wap.htm". Everything works fine when accessing it from a Windows or mobile web browser, as shown in Image 2 on the Android phone's built-in browser. However, when viewing it in the Home Assistant app, as shown in Image 1, it is evident that the background elements of the website are not displayed correctly. Please assist in investigating and resolving this issue. Thank you.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![1](https://github.com/user-attachments/assets/378b22a2-a983-449b-839d-27e9351c7936)
![2](https://github.com/user-attachments/assets/1eb13792-0de3-4009-92d6-cd5a3cdc978f)
**Additional information:**

**Comment by dshokouhi** [comment]
> Please assist in investigating and resolving this issue. Thank you.

as this is happening in WebView first check that android system webview is fully upto date in the play store

next you can try enabling chrome remote debugging to attempt to see whats wrong to fix the issue with the iframe.

https://companion.home-assistant.io/docs/integrations/android-webview#remote-debugging

another thing you can consider is if its a mixed content issue the app will not allow mixed content so if your instance is connected over `https` but the image itself is `http` it may not load properly, similar issue: https://github.com/home-assistant/android/issues/838

unfortunately this not in scope of the android app as we display the dashboard using Webview and everything is rendered via the home assistant frontend
