### ISSUE TITLE
Camera dosent load on reboot

### ISSUE THREAD

**Issue by ivorsmorenburg** [home-assistant/android#4643]
Appnisnt able to recover from a reboot or upgrade leaving widgets unresponsive for ever an example is the camera

**Home Assistant Android app version(s):**
master
**Android version(s):**
10
**Device model(s):**
OnePlus 8T
**Home Assistant version:**

**Last working Home Assistant release (if known):**
Never that I have seen
**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```
No applies, Camera isn't resgistered on SCREEN_ON Intent
```

**Screenshot or video of problem:**
![oddlookingcameraafterreboot](https://github.com/user-attachments/assets/5ff9c701-b512-432b-9d49-3063d962474f)

**Additional information:**

Seems when the device is killed the camera widget isn't coming back leaving that odd looking placeholder

**Comment by jpelgrom** [comment]
Please don't leave the issue template empty and provide more details. Does unresponsive only include updates or also the actions, does it show any errors? etc
