### ISSUE TITLE
Improve placeholder for camera widget (keep previous when unable to load)

### ISSUE THREAD

**Issue by ivorsmorenburg** [home-assistant/android#4644]
Appnisnt able to recover from a reboot or upgrade leaving widgets unresponsive for ever an example is the camera

**Home Assistant Android app version(s):**
master
**Android version(s):**
10
**Device model(s):**
OnePlus 8T
**Home Assistant version:**

**Last working Home Assistant release (if known):**
Never that I have seen
**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![oddlookingcameraafterreboot](https://github.com/user-attachments/assets/6df1e7f8-2f5d-401b-b2a7-3b6f443c9d49)

Alternatives proposed: 
![Screenshot_7](https://github.com/user-attachments/assets/f2de5cea-1479-41d3-b2b1-2107987daef5)
![placeholderalt](https://github.com/user-attachments/assets/3c2e25a5-647c-45bf-9153-a89eeaa8afb9)

**Additional information:**

The camera is using the Launcher Icon in a transparent background. I feel this can be improved by doing something more user friendly.

This can be tested by #4640

**Comment by jpelgrom** [comment]
Please don't leave the issue template empty. I'm also changing this to a feature request as this is working as designed.
