### ISSUE TITLE
Entity Widget isn't updating after a reboot or lost connection leaving out of sync visible even if has correct updated data until you tap

### ISSUE THREAD

**Issue by ivorsmorenburg** [home-assistant/android#4645]
**Home Assistant Android app version(s):**

**Android version(s):**

**Device model(s):**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
Please don't leave the issue template empty. Isn't this a duplicate of #4643 as you're saying the camera widget is an example in the text?

**Comment by ivorsmorenburg** [comment]
No is not a duplicate, it does not refresh and keeps the small sync problem red icon on.

**Comment by ivorsmorenburg** [comment]
Duplicated :)
