### ISSUE TITLE
Auto restart App after X minutes

### ISSUE THREAD

**Issue by iulko** [home-assistant/android#4660]
**Is your feature request related to a problem? Please describe.**

The problem we encounter when using persistent connection is that sometimes app get unreliable and makes too many connections or gets stuck in some ways (battery drain bug)

**Describe the solution you'd like**

Android have a way to restart an app automatically. We would configure an automatic restart of the app after X minutes.
**Describe alternatives you've considered, if any**

**Additional context**

This would be a workaround for a future and current problems with the app

**Comment by dshokouhi** [comment]
If there is an issue with the persistent connection it should be fixed instead of worked around. Please describe the issues you experience and if there is a bug create one for the instead. There already is a known issue. Are you experiencing this issue? 

https://github.com/home-assistant/android/issues/4363

**Comment by dshokouhi** [comment]
> There is this bug, there is battery bug, there are bugs where app freezes,

There should be bugs for these, if not then file a bug so it can be fixed.

> there is a bug where 50 connections to instance are made (i have no idea how can you write a bug like this, code have to be terrible)

If you can discover such a bug then you should be able to write the details and provide all necessary information to reproduce the issue. There is no reason to be disrespectful, that is how you get ignored.

> so im giving a quick bandage solution to fix all this that will not be fixed for next 3 years so that we can enjoy stable app, also this would fix any future bugs like this. 40 lines in the code vs 3 years.

Closing as we should not accept this bandage solution



> * We cant do it because it needs changed in homessitant server (where it will be buried on the forums)

Certain changes do indeed require HA core changes there is no getting around that.



> * Give us more data when none is needed

developers who request more data need more data, as a user you do need to provide it or the issue will be closed.



> * Ignoring

being disrespectful will indeed lead to this
