### ISSUE TITLE
Data saver mode prevents zone enter/exit events from firing

### ISSUE THREAD

**Issue by wbyoung** [home-assistant/android#4664]
**Home Assistant Android app version(s):** 2024.7.3-full

**Android version(s):** 14 (security update September 5th 2024)

**Device model(s):** Pixel 7

**Home Assistant version:** 2024.9.2

**Last working Home Assistant release (if known):** N/A

**Description of problem, include YAML if issue is related to notifications:**

The app does not send location updates for entering/exiting zones when _Data Saver_ is enabled even if _Unrestricted Data_ is enabled for the app. This makes sense as the phone is probably not looking for new cell phone towers and calculating updates.

It seems like two possible solutions exist for this:

1. In my troubleshooting of this issue, I came across some developer docs that seem to suggest it's possible to detect if data saver mode is enabled on the device. It may be worthwhile to include a warning in the companion app settings screen that this can cause issues for location updates on some devices and also prevents geofencing from working on others.
2. Just update [the troubleshooting guide](https://companion.home-assistant.io/docs/troubleshooting/faqs#device-tracker-is-not-updating-in-android-app) to include additional details about zones not working reliably with _Data Saver_ mode enabled.

**Comment by dshokouhi** [comment]
We actually do mention data saver and at the time that feature only existed on Samsung devices, we can update the docs to remove the mention of Samsung as that note now applies to all devices that have such a feature.

```
Some manufacturers may add additional battery saving features (ex: Power Saving), make sure to disable all of those as well. You can usually access these from the system settings app.
Turn on unrestricted data for the app.
Samsung devices: you will need to disable data saver for Home Assistant as well.
```

this is mentioned as steps 4 and 5 from your link above.

**Comment by wbyoung** [comment]
Yes, that would be ideal. I was on that page a bit while troubleshooting my issue. Since I didn't know the history you just shared, I figured the Samsung specific instructions didn't apply to me.
