### ISSUE TITLE
phone state sensors not listed on tablets without phone modem

### ISSUE THREAD

**Issue by JoernBerkefeld** [home-assistant/android#4668]
**Home Assistant Android app version(s):**

**Android version(s):** 14 / one UI 6.1

**Device model(s):** Samsung Galaxy Tab S9+

**Description of problem, include YAML if issue is related to notifications:**

There is an option to get the status of your Android device regarding phone calls. That status (phone state) reflects calls made via the phone app but also via video apps like MS Teams and Google Meet (idle, offhook, ringing).

Unfortunately, the companion app only shows the option to enable this particular sensor if the device has a modem / a sim card. Many tablets don't because it's usually the more expensive option. 

My problem: I would like to enable video lights (e.g. Elgato) in my office whenever I make a video call. That works fine for calls I make via my phone but these days I tend to use my tablet for that - which does not offer me to enable the respective sensor. I checked app permissions and manually assigned them, yet, when I tried this on my phone, the option to enable the sensor was there and it triggered a redirect to the permissions page because there the app also was lacking the right permission. Hence, it must be a check on "can this tablet make calls via its own modem or not" or maybe "does it support sim cards".

These days, you can even make a phone call from your android tablet, using your phone as a modem... Means that check seems outdated.

I have zero knowledge of how this can be achieved but would really appreciate if somebody could disable the relevant condition check in the companion app which prevents me from seeing these sensors there; and consequently allows me to activate them.

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
The phone state sensor is ones for devices with a modem. Use the audio mode sensor as it has certain states when using the other apps.

**Comment by JoernBerkefeld** [comment]
Thank you @dshokouhi !

That sensor updates fine for ms Teams - any chance you know why Google meet calls don't trigger an update?

**Comment by dshokouhi** [comment]
> Thank you @dshokouhi !
> 
> That sensor updates fine for ms Teams - any chance you know why Google meet calls don't trigger an update?

Use the audio mode sensor. Phone sensor is for things that report via the Telephony Manager API the sensor uses.

**Comment by JoernBerkefeld** [comment]
i actually meant the sensor that you proposed. Today, I realized that I didn't see an update because of sensor update frequency. By chance "your" sensor updated "in time" on my phone which made me realize my mistake.

i updated the sensor update cycle to fast when charging - which is still not perfect but solves my task for the most part. 

thanks again for your insights! :)
