### ISSUE TITLE
Wear OS: Direct connection to HomeAssistant server without phone and gms

### ISSUE THREAD

**Issue by wpak18** [home-assistant/android#4676]
Hi,

I got a Samsung Watch LTE, i really like Wear OS HomeAssistant version but its missing one main feature.
I dont want to use google gms to push all notification throught google servers, it will be hard to integrate standalone direct connection with it? 

I have Lineage OS and Wear OS debloated from all stock apps, only standalone left (watch working like a phone without bluetooth connection to phone). On my phone HomeAssistant working perfect without gms.

**Comment by dshokouhi** [comment]
Sorry Google services is a requirement for all the features we use on Wear OS.
