### ISSUE TITLE
Location notification badge is always shown in android 

### ISSUE THREAD

**Issue by jakob30061** [home-assistant/android#4677]
**Home Assistant Android app version(s):**
2024.7.3-full

**Android version(s):**
Lineage OS 21 - Android 14

**Device model(s):**
Samsung S20 FE 5G (r8q)

**Home Assistant version:**
2024.9.3 (core)
20240909.1 (frontend)

**Last working Home Assistant release (if known):**
-

**Description of problem, include YAML if issue is related to notifications:**
I have explicitly set the permissions for location to "always" so I can use zones. On the stock samsung os this only showed the location notification if really used by home assistant. On lineage this notification is always showed even if not used right now. Other apps with the same permission doesn't have this issue. (tested by disabling the permission for ha)
It could be the issue of my custom rom but only ha has this issue so i'm opening this issue here. Has anyone some ideas or the same issue?

**Screenshot or video of problem:**
![Screenshot_20240930-135611_Home Assistant](https://github.com/user-attachments/assets/4c1aeaa0-070d-4bde-9a8f-1f442b7af8da)
Active sensors in home assistant
![Screenshot_20240930-135708_Permission controller](https://github.com/user-attachments/assets/3fa5be99-1269-40ab-a024-f818cd20216b)
Location permission in home assistant (but last used a minute ago)
![Screenshot_20240930-135725_Permission controller](https://github.com/user-attachments/assets/ab5e523f-a0c4-44b2-8893-2ec299bd0632)
Same permission of another app
![Screenshot_20240930-140007_Spotify](https://github.com/user-attachments/assets/95278c32-8980-4515-ba85-2ae74bcca6b6)
Top right corner is the location badge (always there if i enable location sensor in home assistant)

**Comment by dshokouhi** [comment]
Location is used all the time not just for device training but other features line WiFi sensors internal URL switching etc..

**Comment by jakob30061** [comment]
Thanks for the quick response. Do you have any clue why the location was used one minute ago but it still shows the location badge in android?

I just personally like to see if an app is using the location in this moment. 
![Screenshot from 2024-09-30 15-23-28](https://github.com/user-attachments/assets/1f568dbd-eada-4adb-a5f4-928f1dd47743)

**Comment by dshokouhi** [comment]
I would ignore that screen. There is a reason why stock ROM don't show that dot. Apps can use location all for lots of other reasons that users may not understand.
