### ISSUE TITLE
Notification uses FCM even though "Persistent Connection" was set to "Always"

### ISSUE THREAD

**Issue by gthbusrr** [home-assistant/android#4683]
**Home Assistant Android app version(s):** `2024.9.4-full`

**Android version(s)**: `14`

**Device model(s)**: `Galaxy Z Fold6` `SM-F956W`

**Home Assistant version**: `2024.9.3`

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
Notification uses FCM even though "Persistent Connection" was set to "Always". This usually happens after my phone lost internet connection.
I would have used the `minimal` version but I want location tracking functionality. It'd be grand if either
a. There's an option to disable FCM completely
b. UnifiedPush is used rather than FCM

**Companion App Logs:**

```
I was stuck on the `Collecting logs...` screen...
```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
It's perfectly ok to get fcm messages as that is the fallback. This is working as expected.

**Comment by gthbusrr** [comment]
@dshokouhi 
It was not mentioned in the [Local Push Documentation](https://companion.home-assistant.io/docs/notifications/notification-local) at all. Also, Is it possible to allow user to choose whether or not we want a fallback?
