### ISSUE TITLE
Latest update 2024.9.4-full, background and people icons no longer load.

### ISSUE THREAD

**Issue by mattbruman** [home-assistant/android#4685]
**Home Assistant Android app version(s):**

**Android version(s):**
14
**Device model(s):**
One Plus 9 Pro
**Home Assistant version:**
2024.9.2
**Last working Home Assistant release (if known):**
2024.9.2
**Description of problem, include YAML if issue is related to notifications:**

Since the companion app updated my people image icons and my HA Dashboard background no longer loads. It was working fine before the update. I have cleared the cache on the app but I don't have to clear data as I would rather not have to set up my tiles and sensors again.

![Screenshot_2024-10-02-12-47-20-09_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/ebf97200-68ae-4397-8b6b-747c70cd88be)

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Can you try to force stop the app and open it again to see if it fixes the issue? that should force it to fetch new cache. also is that a custom card loading images? tough to tell in teh screenshot

**Comment by mattbruman** [comment]
> Can you try to force stop the app and open it again to see if it fixes the issue? that should force it to fetch new cache. also is that a custom card loading images? tough to tell in teh screenshot

Yes it's mushroom card. I was about to add my code to the main post.

I had forced closed it before posting but just did it again and it fixed it. Thanks. Guess it needs a few closes and cache clears.

`type: custom:mushroom-person-card
entity: person.matt
primary_info: none
layout: vertical
fill_container: false
icon_type: entity-picture
secondary_info: none`

**Comment by mattbruman** [comment]
Clearing cache and force closing multiple times fixed it.
