### ISSUE TITLE
TTS using notifications can't be heard when connected to Android Auto

### ISSUE THREAD

**Issue by erickson-brian57** [home-assistant/android#4688]
**Home Assistant Android app version(s):**
 2024.7.3-full

**Android version(s):**
 14

**Device model(s):**
 Samsung Galaxy S23

**Home Assistant version:**  
Core 2024.9.3
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
The TTS message generated by the below YAML can't be heard when the phone is connected to Android Auto.  The cars audio system is on. Pandora playing or not makes no difference.  The TTS notification is supposed to use the media stream but I suspect the TTS message is being played over the bluetooth audio.  That's where the TTS message is heard when not connected to Android Auto.  No error messages of any kind are produced.

I mistakenly first filed this under homeassistant: core and it was closed with the comment that it's working as intended.  I don't know about that but I don't think it's working as it should.

action: notify.mobile_app_<myphone>
metadata: {}
data:
message: TTS
data:
tts_text: The front door is open
ttl: 0
priority: high

Adding:  
   media_stream: alarm_stream
 is a workaround but the TTS message plays through the phone speakers.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
> I mistakenly first filed this under homeassistant: core and it was closed with the comment that it's working as intended. I don't know about that but I don't think it's working as it should.

[the comment](https://github.com/home-assistant/core/issues/127149#issuecomment-2387696383) is correct. The code has always used the media stream and in the car that only happens when any media off your phone is playing via BT. it will not interrupt the radio. This is working as intended when connected via BT it will play over the BT media stream.
