### ISSUE TITLE
Quality tools

### ISSUE THREAD

**Issue by CedrickFlocon** [home-assistant/android#47]
As all open source project we need to add quality tools. 
It's an open discussion to find out the best setup. 

e.g.
[SonarQube](https://sonarcloud.io/about)
[Detekt](https://github.com/arturbosch/detekt)
[Klint](https://github.com/pinterest/ktlint)

**Comment by marciogranzotto** [comment]
I'm not very familiar with SonarQube or Detekt, but where Ktlint shines for me is that it follows the official Kotlin guidelines and there's no much configuration to be done.

For reference, as said on [this article](https://sourcelevel.io/blog/ktlint-or-detekt-which-linter-to-choose):
> Ktlint gives you less stuff to discuss. It follows the official style. When you let the lint too open for configuration, people create their “official” style, as happened to eslint. Too many style guide versions can lead to inconsistency and counterproductive discussions.

**Comment by CedrickFlocon** [comment]
In my point of view we could use SonarQube for code coverage, bug and code smell.
And KLint for formating.

**Comment by marciogranzotto** [comment]
Makes sense. I'll update my ktlint branch with the master changes and reopen the PR so we can get this part done. Then we can add another PR for SonarQube later.
