### ISSUE TITLE
Companion app hard freezes couple of seconds upon login

### ISSUE THREAD

**Issue by Sleor** [home-assistant/android#4701]
**Home Assistant Android app version(s):**
2024.9.4-full
**Android version(s):**
14
One UI 6.1
Kernel  6.1.75-android14-11
**Device model(s):**
Samsung Galaxy S24  SM-S921B/DS
**Home Assistant version:**
Core 2024.10.1
Frontend 20241002.2
**Last working Home Assistant release (if known):**
Unknown on this device
**Description of problem, include YAML if issue is related to notifications:**
Setup of app and connecting to Home Assistant without issue. However after opening app it shows my default dashboard but then the companion app completely freezes after couple of seconds. App is unusabe to me. Deleting cache and/or data does not solve it, re-installing app also does not fix it. 

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Do you have any custom cards? Can you try disabling to see if the issue goes away? I would also try and update Android system WebView in the play store to the latest version.

**Comment by Sleor** [comment]
No I am not running any custom cards, it is not a very advanced setup for now. Android webview is latest version (no canary, no beta, no dev that is).

**Edit:** Issue is resolved, root cause was in my default start dashboard (energy), where I had placed a webpage card for my heating. The controller is quite an old device with an outdated GUI.. Looks like I will be updating the remote heater control.

Thanks for the pointer !
