### ISSUE TITLE
Need ecobee API!

### ISSUE THREAD

**Issue by ggould1210** [home-assistant/android#4703]
It is now not possible to obtain an ecobee API.  Consequently, the ecobee Smart Home Premium thermostat cannot be added to HA as an integration.

The Homekit workaround is not helpful for Android users because Homekit needs to be paired with HA.  This does not work because pairing Homekit and HA can only be done with a QR Code.  The supplied QR Code does not work with Android devices.

**Comment by jpelgrom** [comment]
Hi 👋

You typically don't need an Apple devices to use HomeKit devices with Home Assistant, so I suggest looking at: https://www.home-assistant.io/integrations/homekit_controller/

In case you still want something with the ecobee API, this requires an integration. Integrations are something that needs to be added to Home Assistant core/the server, not the Android app. You can post Home Assistant core feature requests on the forums: https://community.home-assistant.io/c/feature-requests/13
