### ISSUE TITLE
Missing genitiv apostrophe in some UI strings

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/android#4704]
**Home Assistant Android app version:**

2024.9.4-full

There are three UI strings (found via Lokalize) that are missing an apostrophe to indicate the genitive and form a wrong plural instead:

     sensor_description_app_standby
     "The apps current standby bucket.  …"

This should be "The app's …" as seems to refer to the Companion app itself.

     sensor_description_geocoded_location
     "… Googles Location API. …"

     sensor_description_detected_activity
     "… Googles Activity Recognition API"

Both contain "Googles" which should be "Google's" instead.

**Comment by dshokouhi** [comment]
Hello all our english strings are managed in this file and not in Lokalize

https://github.com/home-assistant/android/blob/master/common/src/main/res/values/strings.xml

If you like you should be able to create some edits and submit as a PR so we can get these corrected.

**Comment by NoRi2909** [comment]
@dshokouhi I'm quite fluent in Lokalize, but that would be my first edit on Github.
So perhaps you can fix this in this case? :-)

**Comment by NoRi2909** [comment]
Here is an additional bug with the wrong plural vs. genetive:

     sensor_description_audio_sensor
     The state of the devices ringer mode
