### ISSUE TITLE
"Music" volume level should be "Media", make naming consistent

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/android#4708]
**Home Assistant Android app version:**
2024-10.1-full (beta)
**Android version:**
15
**Device model(s):**
Pixel 6

The entity for setting the "Media volume" on an Android device is currently named "Volume level music" in the Companion app:

     sensor_name_volume_music
     "Volume level music"

     sensor_description_volume_music
     "Volume level for music on the device"

In both strings "music" should be replaced with "media" as this setting also applies to video playback.
As the latter desciption has more space available using "playing media" or "media playback" instead makes sense.

Please also check if it makes sense to change the IDs of both entities as well.

Here how it looks like in Android's system settings in Android 15 on a Pixel 6:

![Screenshot_20241009-073317](https://github.com/user-attachments/assets/d3813020-0f76-4bae-8404-fc13af5d62d6)

You also might to use this change to make all those strings match what is shown in the Android settings

     sensor_name_volume_alarm
     "Alarm volume"

     sensor_name_volume_call
     "Call volume"

     sensor_name_volume_music
     "Media volume"

     sensor_name_volume_notification
     "Notification volume"

     sensor_name_volume_ring
     "Ring volume"

     sensor_name_volume_system
     "System volume"

     sensor_name_volume_dtmf
     "DTMF volume"

"Volume level" then still remains in all the corresponding, longer description texts.

**Comment by dshokouhi** [comment]
Our sensor names actually match the API used, in this case it is indeed a Music Stream. Google may have changed the name in a Pixel but that may not be the same name all other devices use. As the actual API used is a music stream, we should not change this. The sensor descriptions also typically copy the API description which in this case it is correct.

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/sensors/AudioSensorManager.kt#L384

https://developer.android.com/reference/android/media/AudioManager#STREAM_MUSIC

**Comment by NoRi2909** [comment]
I think we have a misunderstanding here, this is not about music streaming at all.

My bug is about rewording the Sensor names as they show up in the Companion app so they match what the user sees in the device settings:

      sensor_name_volume_alarm
      "Alarm volume"

      sensor_name_volume_call
      "Call volume"

      sensor_name_volume_music
      "Media volume"

      sensor_name_volume_notification
      "Notification volume"

      sensor_name_volume_ring
      "Ring volume"

      sensor_name_volume_system
      "System volume"

      sensor_name_volume_dtmf
      "DTMF volume"

This is currently showing up here with the old names:

![Screenshot Sensors](https://github.com/user-attachments/assets/49c51b52-74c6-4e53-ab88-85598f14da2f)

Now compare to the device settings screen shot I posted above.
Those should match. It's a UI issue that needs to be solved so we keep the same consistency in the translations.

Because those string all get translated, there is no API issue here, it's all front-end stuff.

**Comment by dshokouhi** [comment]
> I think we have a misunderstanding here, this is not about music streaming at all.

yes we do the code used to return the state for the sensor in question is labeled as music stream internally and our sensor names are designed to match that.  This is not the only sensor to follow this naming convention. You are free to edit the name of any entity you have and change it as you like.

 

> Now compare to the device settings screen shot I posted above.

Thats assuming all other devices call it the same, for the purpose of our app we go by the internal android names for sensor names and their descriptions as that is where the data is coming from. Different manufacturers are free to call the stream whatever it is they like. This is not the first time you will see a mismatch like this and using 1 device for comparison is not correct as different devices use different terminology.

**Comment by NoRi2909** [comment]
@dshokouhi We're still not in the same boat here :-)

You can keep "Music" if you don't want to change that to "Media" as it is actually called on all current Android devices.#
Really not that important to me right now. But for consistent translation I need some official text pairs that I can follow.

So what  we're talking about is just changing:

      Volume level DTMF          ->   DTMF volume
      Volume level alarm         ->   Alarm volume
      Volume level call          ->   Call volume
      Volume level music         ->   Music volume
      Volume level notification  ->   Notification volume
      Volume level ringer        ->   Ring volume
      Volume level system        ->   System volume

This is simplifying the UI in the Companion app and making it consistent with the official Google names in the UI.

I need to translate those into German, and there certainly will be other languages following in the future.
They all will have to follow what is on stock Android as this is Google's master copy.
There is no German etc. API documentation either, I have to stick to what we see on screen.

As you can see those names are also remove a lot of noise from the UI.
And "volume level" is currently repeated in the corresponding sensor descriptions, too.
So this is all just duplicating the same information at the moment.

**Comment by dshokouhi** [comment]
> This is simplifying the UI in the Companion app and making it consistent with the official Google names in the UI.

now with this suggestion the new issue is that the entity ID will no longer match the name and also documentation needs to be updated.

I think for this you should translate as is to prevent having to update so many other places
