### ISSUE TITLE
Wrong use of "click" for a touchscreen app, plus better wording for permissions

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/android#4728]
**Home Assistant Android app version:**
2024.10.1-full (beta)
**Android version:**
15

There are several strings in the Android app that incorrectly use the term "click" when referring to tapping or selecting a button.
As there is no mouse used, there is also no mouse-click or clicking here.

`tile_vibrate`
Vibrate when **clicked**

`webview_error`
There was an error loading Home Assistant, please review the connection settings and try again. We will attempt to try another provided URL when you **click** on Refresh.

`message_missing_all`
The Wear app is missing on your watch, **click** the button below to install the app.

`message_some_installed`
The Wear app is installed on some of your Wear devices: (%1$s)\n\n**Click** the button below to install the app on the other devices.

`notification_permission_summary`
Home Assistant does not have permission to send you notifications. **Click** here to enable sending notifications.

`background_access_disabled`
Home Assistant does not have access to run in the background. Without this permission the app will not be able to reliably send data back to your server. **Click** here to request permissions.

`location_disabled_notification_message`
The following enabled option(s) require you to enable location. If you do not enable the location, the sensor(s)/setting(s) will not work!\n\n%1$s\n**Click** to enable location.

`location_disabled_notification_short_message`
Some setting(s) do not work. **Click** to enable location.

The latter two also need a fix regarding "location".
Both should be "Tap to enable location permissions" (as I understand it).

Edit: Just one more small suggestion you might fix in one swoop here:

For the notification rate limit there are two counters:

`successful` and `errors`

Would be cool if you changed the latter to "Failed", that pairs better with "Successful", especially in translations.

**Comment by jpelgrom** [comment]
FWIW, I don't agree that the usage of click is incorrect. There are many input types possible on Android including a mouse. The goal should be "do users understand it?" and no one is going to be confused when reading click [something].

Guidelines we use suggest avoiding the use of click or tap completely, so I've considered that and reworded/removed strings.
