### ISSUE TITLE
Show Identity Resolving Key from devices connected to Android?

### ISSUE THREAD

**Issue by MikeMM70** [home-assistant/android#4729]
**Is your feature request related to a problem? Please describe.**

It is difficult to find the IRK (Identity Resolving Key) for my BLE watch without an iPhone. (I haven't figured out how)
**Describe the solution you'd like**

I'd like to see a section in the companion app settings that shows the Identity Resolving Key for Bluetooth devices paired with the phone that the companion app is running on.  
**Describe alternatives you've considered, if any**

My watch doesn't seem to pair/bond BLE without the use of it's app, FitCloudPro. I paired the watch with my Windows 10 PC, but no IRK was shown in the registry [(](https://github.com/home-assistant/home-assistant.io/issues/33676) so I'm guessing this wasn't a BLE pairing?
**Additional context**

I expect this issue/feature request to be closed, so don't feel bad about it when you do, thank you for reading.

**Comment by dshokouhi** [comment]
i dont think this is visible to apps

**Comment by jpelgrom** [comment]
Looking at [BluetoothDevice.java](https://android.googlesource.com/platform/packages/modules/Bluetooth/+/6da0d41e4319d33c9dd429fddc2f4653001e3d96/framework/java/android/bluetooth/BluetoothDevice.java) in the Android source I don't see any references to it, let alone a public function to get it, and like @dshokouhi I also can't find other ways online that suggest this is available to apps.

**Comment by MikeMM70** [comment]
[Bluetooth/le/ScanFilter.java](https://android.googlesource.com/platform/packages/modules/Bluetooth/+/6da0d41e4319d33c9dd429fddc2f4653001e3d96/framework/java/android/bluetooth/le/ScanFilter.java)  Line 66 is the first reference.  I don't "speak" java so I don't know how helpful this code is, but thank you @jpelgrom for pointing me in the right place to look.

**Comment by jpelgrom** [comment]
The line you linked is for when an app is scanning for devices and wants to filter the results, it doesn't provide any way to get the value.

**Comment by MikeMM70** [comment]
Thanks, I told you I don't speak the language!  But seriously, thank you for looking.
