### ISSUE TITLE
Notifications work fine when connected to local internal wifi network, but I am never receiving them when outside of it.

### ISSUE THREAD

**Issue by recklessnl** [home-assistant/android#473]
**Home Assistant Android version:** 1.7.2-128

**Android version:** Android 9

**Phone model:** Note 9

**Home Assistant version:** 105.5 (latest as of today)

**Last working Home Assistant release (if known):** N/A

**Description of problem:**

I have the following notification setup that works very well in my local network:

```
{
    "message": "Camera snapshot:",
    "data": {
        "sticky": true,
        "color": "orange",
        "ttl": 0,
        "priority": "high",
        "image": "http://192.168.1.23/local/image.jpg"
    }
}
```
As you can see, the image is retrieved locally. **This works 100% of the time on my personal internal wifi network.** However, once I go outside of my network and connect to LTE, I do not get ANY notifications at all.
I DO receive them once I return back home and re-connect to the local wifi, but then no image will be attached. Obviously I want to receive these notifications from anywhere, regardless of where I am.

I run Home assistant behind a reverse proxy, using Caddy. I can access it just fine, the app itself works great on LTE, and I can control everything the same as if I were on my own network. But notifications, for some reason, are not received once I'm on LTE.

**Comment by dshokouhi** [comment]
@recklessnl could you please list the full Android app version found on the App Configuration page? You should see the format like 1.x.x(xxx)

**Comment by recklessnl** [comment]
@dshokouhi  Application version: 1.7.2-128

**Comment by recklessnl** [comment]
I can confirm that this also does not work in version 1.8.0-144.

**Comment by JBassett** [comment]
Can you try referencing the image via relative path?
```
{
    "message": "Camera snapshot:",
    "data": {
        "sticky": true,
        "color": "orange",
        "ttl": 0,
        "priority": "high",
        "image": "/local/image.jpg"
    }
}
```
We do have code to just leave image off if it can't retrieve the url passed.

**Comment by recklessnl** [comment]
I can't use a relative path because it's a camera snapshot that is being sent out. Which is a very valuable notification to have, **especially** when outside of the house and your own network.

Ideally, the Android app would make a local cache out of the image and pass on that cached image. When the notification is then swiped away, the image can be deleted. This would make it a lot easier for users to receive locally generated images like camera snapshots coming from a local LAN IP.

**Comment by JBassett** [comment]
If you are looking for the current camera snapshot you can use the following where `camera.name_of_camera` is the camera entity:
```
{
    "message": "Camera snapshot:",
    "data": {
        "sticky": true,
        "color": "orange",
        "ttl": 0,
        "priority": "high",
        "image": "/api/camera_proxy/camera.name_of_camera"
    }
}
```

This causes the app to request the latest snapshot of the camera and it's authenticated with HA.  This means nothing is left unsecure in the local directory.
