### ISSUE TITLE
Grammar problem in "location_disabled_notification_short_message"/"location_tracking_summary"

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/android#4739]
**Home Assistant Android app version:**
2024.10.3-full (beta)

The string `location_disabled_notification_short_message` is currently

"Some setting(s) do not work"

If you read this as singular the grammar is broken, should be "does" in that case.
It's also quite difficult to properly translate into German (or other languages).

Perhaps using just plural is fine, too:

"Some settings do not work"

You might want to apply the same fix to:

`location_tracking_summary`

"View a history of location tracking updates to troubleshoot the device tracker(s)"

In English there is no problem, but in other languages that "the" changes for singular and plural.
I also do not immediately understand if "trackers" refers to external devices or built-in routines.
Rewording might help other users, too.

**Comment by jpelgrom** [comment]
Device trackers are a [core part of Home Assistant](https://www.home-assistant.io/integrations/device_tracker/), so we won't remove this reference.

**Comment by NoRi2909** [comment]
@jpelgrom But as you wrote "device trackers" you could use plural in the string, too?

Probably just using:
"View a history of location tracking updates to troubleshoot any device trackers"

I was not asking you to remove that entirely …

**Comment by jpelgrom** [comment]
You can only troubleshoot the app device tracker so using the singular version here is correct.

**Comment by NoRi2909** [comment]
@jpelgrom Cool, that completely solves the issue.

Problem was that before I picked up the German translation someone else fully translated that word to

`Geräte-Tracker` (singular in the `device_tracker` string)
"Geräte-Trackern" (dative, plural)

the latter because of the "with …".

With singular I can translate that as

"Aktualisierungsverlauf der Standortverfolgung anzeigen, um Probleme mit dem Device Tracker zu beheben"

**Comment by NoRi2909** [comment]
@jpelgrom  You could do me one more favor: That "with" below means "together with" or "at the same time", right?

sensor_setting_geocode_include_location_updates_title
"Update sensor with location sensors"

German has so many more words than English that by picking the wrong one of the possible translations you can completely alter the meaning (when there is no context that helps)  …

**Comment by jpelgrom** [comment]
> That "with" below means "together with" or "at the same time", right?

Yes, correct.

No need to keep @ mentioning in issues when there is a single conversation.

**Comment by NoRi2909** [comment]
One last thing you can fix easily along with the stuff above:

The button labels `nfc_btn_read_tag` and `nfc_btn_write_tag` tend to become longer in translations. In German this results in the "Write NFC tag" no longer fitting a single line, and no longer being centered:

![Companion](https://github.com/user-attachments/assets/3bb69596-1f8d-436f-be91-5e6ee0187333)

I already changed this  in Lokalise for the German UI to just "Read tag" and "Write tag", but you might want to make the same change so future translators don't run into the same issue in other languages.

NFC is already mentioned twice on that page so it should be pretty clear what these buttons are about. 😃
