### ISSUE TITLE
Work profile sensor not saving state if true and app quits or device is restarted, sensor resets to false

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/android#4755]
**Home Assistant Android app version:**
2024.10.4-full (beta)

**Android version(s):**
15 QPR beta

**Device model(s):**
Pixel 6

I do have a work profile enabled on my Pixel 6, however the Companion app is running in my private profile.

According to the settings for the Work profile sensor it should detect whether the profile is enabled or not:

![Screenshot_20241024-170547](https://github.com/user-attachments/assets/5ee5e3ad-706d-4641-a473-951103870358)

Either it is not working as it should or the explanation is misleading and it actually detects if the Companion app is running under the work profile or not.

**Comment by dshokouhi** [comment]
> however the Companion app is running in my private profile.

does it work as expected if the HA app was installed in the main profile? this could be a case where teh app is simply not running?

for this sensor the app waits for the OS to send updates to the app, in a private profile it probably works as intended.

**Comment by NoRi2909** [comment]
I've installed the Home Assistant app in my Work profile as well: Same result.

Here the sensor also reports `false` for the Work profile.

So it does neither work in the main (private) nor in the secondary (work) profile.

**Comment by NoRi2909** [comment]
Update: I had the app running for 2-3 weeks now, and some device restarts in between. The sensor always showed `false`

Just toggled the sensor off and back on. Now it displays `true`. 

Interestingly I also turned the sensor on under the work profile itself and that did not switch it to `true`.

I'll try again tomorrow and see if that falls back to `false` somehow.

**Comment by NoRi2909** [comment]
Restarted the Pixel 6 …

And we're back to false. And toggling the sensor off and back on does not cause it to become `true`.

**Comment by dshokouhi** [comment]
please check companion app logs while reproducing the error so we can see if there are any errors or if teh OS is simply not notifying the app about the change

**Comment by dshokouhi** [comment]
also why did you remove bits and pieces of the issue template? all of it is important to help troubleshoot.

**Comment by NoRi2909** [comment]
Sorry, here comes the log:

[homeassistant_companion_log_9-24-2024_19-1-6.txt](https://github.com/user-attachments/files/17510314/homeassistant_companion_log_9-24-2024_19-1-6.txt)

I toggled the sensor off and on in that period, too.

**Comment by dshokouhi** [comment]
looks like the OS did not send the app the intent we expect to get to update the sensor

<https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/DevicePolicyManager.kt#L45>

this is the only way the sensor can be updated

Can you see if you enable the Last Notification sensor and grant its permission and then do your test to see if that gives a proper state update? This issue sounds similar to another one with missing intents so id like to see if thats teh same thing here.

**Comment by NoRi2909** [comment]
I've enabled the last notification sensor and also disabled its allow list requirement.
I already tested this before so the permission to access all notifications was already enabled.
Then toggled Work profile off and back on, no change with the sensor result: Still `false`.

But now I disabled my Work profile by selecting "Pause work apps" in the app drawer and turned it back on.
This did the trick of flipping the sensor to `true`. That was the trick that made it work above, too!

Now restarted the phone and after that the sensor is back to `false`.

Repeated turning the Work profile off and back on: Sensor switches to `true`.

So it looks like you're only getting some 'Work profile was re-enabled' information from the OS, not the current state which is always enabled after a restart, e.g.

**Comment by dshokouhi** [comment]
> and also disabled its allow list requirement.

you dont need to do that actually, just having the permission is good enough

> Now restarted the phone and after that the sensor is back to `false`.

So the app does indeed assume things are `false` by default until an intent is brought in. You can test this by force stoppign the app while its `true` and then open teh app and iit will switch to `false`

I am not sure we can really fix that as teh state of work profile cannot be read we can only make the assumption based on the OS update.

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/DevicePolicyManager.kt#L26

are you only seeing this issue when you restart?

**Comment by NoRi2909** [comment]
Yes, force-stopping the app does indeed reset the sensor to `false` just like a complete phone reboot.
I can confirm that the sensor reverts to `false` after each reboot, too.

So the only way to toggle the sensor to `true` is to disable and re-enable the work profile while using the phone.

The system will probably send the same information during boot, but as the Companion app is not running at that moment you don't get that information.

But I see that if I force-quit the Companion app, do the work profile off-on shuffle and reopen the app the sensor is true again!

So there is no chance for you to subscribe to that information somehow to get it after boot, too?
I apologize for my stupid questions, I'm not familiar with app development on Android …

**Comment by dshokouhi** [comment]
from what i have seen its only possible by the intents that get sent one time. They are also not a sticky intent which means we cant just read teh value like we do with battery level. There is also no corresponding API its an odd sensor and only a few are setup like this.

**Comment by dshokouhi** [comment]
> OK, then it's probably a better idea to remove the sensor for the moment as it does not provide any reliable information.

while it may not seem useful for your own use case I think it works for others so theres no need to remove it. You can just disable it. Some sensors just work in a different way than others.
