### ISSUE TITLE
Android - Did not receive auth message within 10 seconds

### ISSUE THREAD

**Issue by Dzoker2** [home-assistant/android#4758]
Hi, I've been seeing these error for quite a while now. It happens at least once a day. The 10.8.0.2 is my OpenVPN IP that is assigned when my phone is on mobile network and connect to home router OpenVPN. 

Error:
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/http.py:519
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:56:53 (1 occurrences)
Last logged: 18:56:53

[140493247140128] from 10.8.0.2 (Home Assistant/2024.10.3-14058 (Android 14; SM-G998U)): Disconnected: Did not receive auth message within 10 seconds

I have all the latest version of HA and Companion App.

Also getting this

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:135
integration: HTTP (documentation, issues)
First occurred: October 26, 2024 at 11:11:29 (338 occurrences)
Last logged: October 26, 2024 at 14:06:15

Login attempt or request with invalid authentication from 10.8.0.2 (10.8.0.2). Requested URL: '/api/websocket'. (Home Assistant/2024.10.3-14058 (Android 14; SM-G998U))

**Comment by dshokouhi** [comment]
does this only happen on VPN? what about off VPN?

**Comment by Dzoker2** [comment]
Hi, It only happens on VPN and only on one phone (I have 2)

**Comment by Dzoker2** [comment]
Hi, any other questions?
ty

**Comment by dshokouhi** [comment]
if it only happens on one phone ad only on VPN that does not suggest the app can correct the issue but the issue may lie on the device or network configuration.

**Comment by Dzoker2** [comment]
Thank you for your fast reply... When you mentioned "network configuration" what exactly do you have in mind? Is is something I can check/reconfigure in HA, the app or something else?
Does it have to do anything around the 10.8.0.2 with is the IP that is only assigned when I connect my phone to OpenVPN (OpenVPN on my router at home)?

Thank you

**Comment by dshokouhi** [comment]
if it only happens on VPN then you should look at your VPN configuration, that is not something controlled by the app. The app always sends auth messages when necessary

**Comment by Dzoker2** [comment]
Hmmm.. the VPN configuration on my phone is exactly the same as the phone that is having no issues and they both connect to the same OpenVPN server (on my router)... this could be a difficult one to trace

**Comment by dshokouhi** [comment]
closing in favor https://github.com/home-assistant/core/issues/114575 in this case the auth seems to be related seems like a HA core issue as even iOS has the issue
