### ISSUE TITLE
Battery drain on 2024.10.6

### ISSUE THREAD

**Issue by syphernl** [home-assistant/android#4764]
**Home Assistant Android app version(s):**
2024.10.6

**Android version(s):**
14

**Device model(s):**
OnePlus 11 5G

**Home Assistant version:**
2024.10.4

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

After updating my app from 2024.10.5 to 2024.10.6 I am experiencing battery draining because it appears that the device is prevented from going to sleep. "Device kept active" in battery stats is currently 5h, which coincides with when I last rebooted my phone.

In the location tracking settings I see it is sending Single precise locations (which often indicates "Too many updates") every 5 seconds which probably explains why my battery is going down so quickly...

Regarding locations this is the only one turned on. For now I have turned it off to see if the draining stops.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
start here: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-app-battery-drain

> In the location tracking settings I see it is constantly sending Single precise locations which probably explains why my battery is going down so quickly...

yea you should turn that off per the link above

**Comment by jpelgrom** [comment]
(For what is worth: I don't see any changes between these versions that should impact battery usage. https://github.com/home-assistant/android/compare/2024.10.5...2024.10.6)

**Comment by syphernl** [comment]
FWIW the issue on my end was the fact that "Include in sensorupdates" was enabled for Single Precise Location. 
As far as I remember this was always the case (I don't remember switching it on), but for some reason since 2024.10.6 this somehow became problematic.

After turning "Include in sensor updates" off, the constant flood of location updates (and thus battery drain) went away.

**Comment by degrashopper** [comment]
in my case disabling "Include in sensor updates" on Single Precise location did not make a change.
device is a samsung S22 with androind 14. Location settings worked without issues for months.

**Comment by dshokouhi** [comment]
@degrashopper hows your data usage for the app? is it high as well? are you also on the mentioned app version which is in the beta?

**Comment by degrashopper** [comment]
@dshokouhi no 2024.10.3-full (stable). Sorry i thought that .6 was the latest stable. usage as of 1 nov 105 mb. oct was 225 mb and sept 160 mb

**Comment by dshokouhi** [comment]
> @dshokouhi no 2024.10.3-full (stable). Sorry i thought that .6 was the latest stable. usage as of 1 nov 105 mb. oct was 225 mb and sept 160 mb

do you have cameras and other things that may stream on your dashboard like a weather radar map, I thnnk your issue may be related to #979 

as the original issue is solved I am closing this. if you still experience drain after tweaking your dashboard you can follow #3595 as that is another battery drain issue
