### ISSUE TITLE
In widgets no more entity_id selection

### ISSUE THREAD

**Issue by gatonero** [home-assistant/android#4787]
**Android version(s):**
13.0

**Device model(s):**
Pixel 8a

**Home Assistant version:**
 Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.4

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
On the widget screen of the companion app is no more field to select the entity
**Companion App Logs:**

**Screenshot or video of problem:**

![Screenshot_20241106-155355](https://github.com/user-attachments/assets/e835a765-397e-4615-98cb-c12794318e17)

**Additional information:**

**Comment by dshokouhi** [comment]
you need to select an action first before that gets populated

**Comment by gatonero** [comment]
Even with an action selected there is no way to select or insert an entity.
![Screenshot_20241107-095120](https://github.com/user-attachments/assets/f4d6fec2-c74e-415b-9bc2-b546702d8950)

**Comment by dshokouhi** [comment]
you may not have any entities that support `switch.toggle` action

![image](https://github.com/user-attachments/assets/d3bb3658-416f-46ef-83e8-4264fe04202e)

try a different action

**Comment by gatonero** [comment]
I have a lot of switches and used them before on that phone ans a Huawei also. On both phones the entities are no more accessible, when creating new widges. The old ones are still working with the same actions and entities.

**Comment by dshokouhi** [comment]
please get us the app logs when you have the widget configuration open, there may be a failure but tough to tell as you did not include them originally and it appeared you did not select an action initially.

Additionally if you go in the HA action UI do you see entities populating for this service call?

**Comment by gatonero** [comment]
I just tried it again and now it works. Maybe the cause of this issues sat behind the keybopard. ;-)
![Screenshot_20241130-202748](https://github.com/user-attachments/assets/308d342d-ac8e-4578-b73f-1ab011ee0c31)
