### ISSUE TITLE
Custom:fold-entity-row dash card does not show all entities in Companion App

### ISSUE THREAD

**Issue by RobusX** [home-assistant/android#4788]
**Home Assistant Android app version(s):**

**Android version(s):** 14

**Device model(s):** Galaxy A34 5G

**Home Assistant version:**   2024.10.4

**Last working Home Assistant release (if known):** 2024.9.3

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

With the latest release of the Companion App, entities in the custom:fold-entity-row card are not displayed correctly. Many entities are often missing after pressing the drop-down symbol. This issue does not occur on the standalone PC (Laptop) dashboard connected to the Home Assistant server running on Windows 10.

```

**Screenshot or video of problem:**

**Additional information:**
Card code which many times within Companion APP displays only first entity within  custom:fold-entity-row (named "Out Lights Update OFF") or no entities after dropdown is pressed (look where custom:fold-entity-row with "Outside Lights" starts below):

type: entities
title: ""
state_color: true
show_header_toggle: false
entities:
  - type: custom:multiple-entity-row
    entity: sensor.out_temp
    name: Out Temp
    secondary_info: last-changed
    entities:
      - entity: sensor.max_temp_out_daily
        name: Max
        styles:
          width: 45px
          margin-top: "-24px"
          margin-right: "-10px"
      - entity: sensor.min_temp_out_daily
        name: Min
        styles:
          width: 45px
          margin-top: "-24px"
          margin-left: 30px
  - type: custom:multiple-entity-row
    entity: sensor.out_meter1_2670_humidity
    name: Out Hum
    secondary_info: last-changed
    entities:
      - entity: sensor.max_hum_out_daily
        name: Max
        styles:
          width: 45px
          margin-top: "-24px"
          margin-right: "-10px"
      - entity: sensor.min_hum_out_daily
        name: Min
        styles:
          width: 45px
          margin-top: "-24px"
          margin-left: 30px
  - type: custom:multiple-entity-row
    entity: binary_sensor.aqara_motion_sensor_balcony_occupancy
    name: Motion Sensor Balcony
    icon: mdi:motion-sensor
    secondary_info: last-changed
  - type: custom:fold-entity-row
    head:
      entity: light.pir_outside_lights
      name: Outside Lights
      state_color: true
      toggle: true
    entities:
      - type: custom:template-entity-row
        entity: input_boolean.lights_pir_out_update_off
        name: Out Lights Update OFF
        toggle: true
      - type: custom:template-entity-row
        entity: light.2pmstaircase_out
        icon: mdi:lightbulb
        name: PIR Staircase Out
        toggle: true
        secondary: |
          Power: {{ states('sensor.2pmstaircase_out_power') }} W
      - type: custom:template-entity-row
        entity: light.2pm_gar_out
        icon: mdi:lightbulb
        name: PIR Garage Out
        toggle: true
        secondary: |
          Power: {{ states('sensor.2pm_gar_out_power') }} W
      - type: custom:template-entity-row
        entity: light.pir_balcony
        icon: mdi:lightbulb
        name: PIR Balcony
        toggle: true
        secondary: |
          Power: {{ states('sensor.pir_balcony_power') }} W
      - type: custom:template-entity-row
        entity: light.2pm_balcony_left
        icon: mdi:lightbulb
        name: PIR Balcony Left
        toggle: true
        secondary: |
          Power: {{ states('sensor.2pm_balcony_left_power') }} W
      - type: custom:template-entity-row
        entity: light.2pm_balcony_right
        icon: mdi:lightbulb
        name: PIR Balcony Right
        toggle: true
        secondary: |
          Power: {{ states('sensor.2pm_balcony_right_power') }} W

**Comment by dshokouhi** [comment]
you need to take this up with the custom card author
