### ISSUE TITLE
PiP inconsistent experience

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#479]
**Home Assistant Android version:**
1.8.0-144
**Android version:**
10
**Phone model:**
Pixel 4 XL
**Home Assistant version:**
0.105.5
**Last working Home Assistant release (if known):**
N/A new feature
**Description of problem:**

The PiP experience is not consistent and has issues with the camera not loading in the PiP window despite showing in full screen.  Sometimes when I go full screen in the video and navigate to home screen I just see a blank PiP window.  Sometimes I see part of the UI in the PiP window.  Sometimes I see the actual video.  ~~When I tap on the PiP window and tap again to expand it the video is very tiny and near the top.~~  Sometimes when I go back home from this odd view the video loads properly.  I have tried to wait a few minutes to see if the feed was loading slow and I also waited for the feed to load in the video player before going full screen.  Something here does not seem to be consistent. 

Steps to reproduce:
1. Open any stream enabled camera
2. Tap on the video and go full screen
3. Go to home screen

Observe the below screenshots

~~1. Tap on PiP window~~
~~2. Tap on the button to expand~~

~~See the below screenshot where the video is tiny and bunched up at the top~~

1. Open another stream enabled camera
2. Go full screen
3. Wait for the video feed to load
4. Go to home screen

See below screenshots of video not loading at all or loading with parts of the UI

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
Part of UI visible with video:
![image](https://user-images.githubusercontent.com/1634145/75395996-55798a00-58a8-11ea-997c-3e4c26380db2.png)

No video displayed in PiP window:
![image](https://user-images.githubusercontent.com/1634145/75396011-5f9b8880-58a8-11ea-909e-5d40f6275612.png)

~~Odd video size when PiP is expanded:~~
![image](https://user-images.githubusercontent.com/1634145/75396037-6b874a80-58a8-11ea-88b5-3d7a6cd0af69.png)

Working screenshot:
![image](https://user-images.githubusercontent.com/1634145/75396105-940f4480-58a8-11ea-8c6b-c06d4b6f6584.png)

**Additional information:**
All cameras tested use the `stream` integration.

**Comment by neopilou** [comment]
@dshokouhi 
Do you use the "more-info-card" to display videos from your cameras?

**Comment by dshokouhi** [comment]
@neopilou yup that is how I am accessing the video.  Navigating to more-info pop-up to get the full screen button.  I am not using any frontend cards.  In most of the testing I did here was actually from Developer Tools > States.  Sorry I forgot to mention that when I created this issue.

**Comment by neopilou** [comment]
I reproduce:

 - When "more-info-card" is used, android' internal player stops when we enter PIP mode (on chrome, the video does not go to full screen with this "more-info-card", this card seems to be the source of this issue)

 - When we view the videos from "Developer Tools> States", the video appears not resized (but the view of the app is correctly resized) and at the very top of the screen when we leave PIP mode. This does not happen when going through unused entities via the 3 dots on the HA home page and everything is ok when we viewing a video from the HA home screen from a "picture-entity card" or a "picture-glance card".

**Comment by dshokouhi** [comment]
Thanks @neopilou I am seeing the same behavior as you are actually.  Viewing from picture-entity is a more consistent experience.  I do occasionally see the blank box but not all the time from this card.  I do also notice that the resized video does not happen from this card.  That is more consistent from Dev Tools > States.  So it sounds like this might be more of a front end issue?

**Comment by neopilou** [comment]
I have a fix for small video size from "Developer Tools> States" when PiP is expanded (back in app)

**Comment by JBassett** [comment]
Can we refine the defect with @neopilou 's change merged?

**Comment by dshokouhi** [comment]
@JBassett updated with ~~strikethrough~~ for parts that are completed

**Comment by dshokouhi** [comment]
The experience is now slightly better too it seems.  The first time I go to states panel, open a camera more info section, go full screen then go home I get a blank screen.  Then when I expand on the PiP window and go back to full screen the issue with tiny video is fixed.  I then go back again to home screen and camera properly loads in PiP.  So it seems the first time PiP is not loading but subsequent attempts load.  I also make sure the camera is properly loaded and playing in fullscreen before swiping home.  So looks like we just need to correct the first attempt to make the experience complete :)
