### ISSUE TITLE
Left sidebar do not work in app

### ISSUE THREAD

**Issue by porzioev** [home-assistant/android#4795]
Good morning everyone.

When in the main screen of the app, in the setted dashboard, I'm not able to use the upper left ⬅️ arrow (I tap on it, but nothing happens) to show the sidebar to navigate for example in the settings or automations.

Tnx.

**Comment by dshokouhi** [comment]
You need to turn off the sub view option on that dashboard.

**Comment by porzioev** [comment]
this is not marked as subview
