### ISSUE TITLE
Beta version: Recent German translations missing

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/android#4797]
**Home Assistant Android app version:**
2024.11.3-full (beta)

**Android version(s):**
15

**Device model:**
Pixel 6

**Home Assistant version:**
2024.11.1

**Description of problem, include YAML if issue is related to notifications:**

The beta that just rolled out does not contain the German translations of the most recently added strings, notably the Health Connect sensors.

![Screenshot_20241110-141727](https://github.com/user-attachments/assets/b9ed78d2-8bff-4ffc-8d87-a1bf0261ec37)

As they were added in Lokalise two days ago they should be present to verify the translations during the beta phase.

**Comment by jpelgrom** [comment]
The beta was cut 3 days ago immediately after sensors were merged, so it makes sense there are no translations in there. They'll be included in the next beta.

**Comment by NoRi2909** [comment]
OK, I just wanted to make sure that nothing had slipped this time because in all recent betas the strings were up-to-date. Thanks!
