### ISSUE TITLE
Next Alarm Sensor randomly has weird data for a couple seconds

### ISSUE THREAD

**Issue by mathiskir** [home-assistant/android#4798]
**Home Assistant Android app version(s):**2024.10.3-full

**Android version(s):**13 (One UI 5.1)

**Device model(s):**Samsung Galaxy S20 FE 5G

**Home Assistant version:** Core 2024.11.1; Supervisor 2024.11.2; Operating System 13.2; Frontend 20241106.2

**Last working Home Assistant release (if known):**/

**Description of problem, include YAML if issue is related to notifications:**
[Verlauf Home Assistant (2).csv](https://github.com/user-attachments/files/17693176/Verlauf.Home.Assistant.2.csv)
The Next Alarm Sensor has weird data in between for like 20 seconds everytime. I didn't change the alarm in that time.
It triggers my morning automations with that.
You can see that really good in the csv attached.
I can't provide phone logs, because  when i go to the logs in the settings they only go till 22:33 and  since then nothing weird happenend

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by mathiskir** [comment]
let me know if i can somehow get earlier logs

**Comment by dshokouhi** [comment]
This is too be expected. The sensor will report what ever value there is. It all depends on the app setting the alarm. The package attribute will help you understand what app set the value you see.
