### ISSUE TITLE
Return from ha addon to home

### ISSUE THREAD

**Issue by SamJongenelen** [home-assistant/android#480]
**Home Assistant Android version:**
1.7.2.128
**Android version:**
10

**Phone model:**
Pixel2
**Home Assistant version:**
0.106
**Last working Home Assistant release (if known):**
Na
**Description of problem:**When an addon is opened (eg Terminal) and return is pressed

Actual: white canvas is displayed.
Expected: return to previous screen
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
@SamJongenelen can you please attach a screenshot of the issue?

**Comment by dshokouhi** [comment]
Sounds very similar to #400 I wonder if this terminal or addon is a pop-up

**Comment by SamJongenelen** [comment]
I think it is a pop-up, yes.  I am on mobile, any tips on making screen recordings?

Shtr:
-Click addon (terminal)
-Blank canvas opens
-Terminal canvas opens (pop-up?)

**Comment by SamJongenelen** [comment]
![Screenshot_20200228-232247](https://user-images.githubusercontent.com/3382443/75591900-4568d280-5a81-11ea-9b16-b1e5ecf19a8b.png)

**Comment by SamJongenelen** [comment]
I can confirm this issue is resolved
