### ISSUE TITLE
When trying to add widget to Android 15 screen the widget jumps to the top and cannot be ad

### ISSUE THREAD

**Issue by danq8** [home-assistant/android#4810]
- Have checked for update to app and also checked it's the same in the beta.
- Definitely on latest HA
- Have searched for any other bug reports that say the same thing, but couldn't find any.

**Home Assistant Android app version(s):**

**Android version(s):**
Android 15
**Device model(s):**
Pixel 6a
**Home Assistant version:**
Core
2024.11.1
Supervisor
2024.11.2
Operating System
13.2
Frontend
20241106.2
Stock launcher
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
When trying to add a HA widget, when placing on the screen, the widget jumps to the top left and then any attempt to move or resize the widget does nothing, clicking on the widget, or the edit button makes the widget disappear.

**Companion App Logs:**

```
11-13 10:48:42.018  6864  6864 D CameraWidget: Broadcast received: 
11-13 10:48:42.018  6864  6864 D CameraWidget: Broadcast action: android.appwidget.action.APPWIDGET_ENABLED
11-13 10:48:42.018  6864  6864 D CameraWidget: AppWidgetId: -1
11-13 10:48:42.020  6864  6864 D CameraWidget: Broadcast received: 
11-13 10:48:42.020  6864  6864 D CameraWidget: Broadcast action: android.appwidget.action.APPWIDGET_UPDATE
11-13 10:48:42.020  6864  6864 D CameraWidget: AppWidgetId: -1
11-13 10:48:42.044  6864  6864 D CameraWidget: Broadcast received: 
11-13 10:48:42.044  6864  6864 D CameraWidget: Broadcast action: android.appwidget.action.APPWIDGET_DELETED
11-13 10:48:42.044  6864  6864 D CameraWidget: AppWidgetId: 47
11-13 10:48:42.047  6864  6864 D CameraWidget: Broadcast received: 
11-13 10:48:42.047  6864  6864 D CameraWidget: Broadcast action: android.appwidget.action.APPWIDGET_DISABLED
11-13 10:48:42.047  6864  6864 D CameraWidget: AppWidgetId: -1
11-13 10:48:43.669  6864  8844 D AidlBufferPool: bufferpool2 0xb4000075b1722af8 : 5(36700160 size) total buffers - 4(29360128 size) used buffers - 1437/1444 (recycle/alloc) - 71/1616 (fetch/transfer)
11-13 10:48:47.308  6864  6864 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1731494914299, currentMillis: 1731494927308)
11-13 10:48:47.366  6864  6864 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1731494914299, currentMillis: 1731494927366)
11-13 10:48:47.366  6864  6864 D IntegrationRepository: setAppActive(): true
11-13 10:48:49.077  6864  8844 D AidlBufferPool: bufferpool2 0xb4000075b1722af8 : 5(36700160 size) total buffers - 4(29360128 size) used buffers - 1519/1526 (recycle/alloc) - 75/1709 (fetch/transfer)
11-13 10:48:49.588  6864  6864 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
11-13 10:48:49.588  6864  6864 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
11-13 10:48:50.521  6864  6864 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=android.widget.PopupWindow$PopupDecorView$$ExternalSyntheticLambda1@7e11b71
11-13 10:48:50.526  6864  6894 D LogcatReader: Read logcat for pid 6864
11-13 10:48:50.562  6864  6864 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: true, expireMillis: 1731494914299, currentMillis: 1731494930562)
11-13 10:48:50.562  6864  6864 D IntegrationRepository: setAppActive(): true
```

**Screenshot or video of problem:**

https://github.com/user-attachments/assets/f309d097-747f-4c14-bce8-f544d8433f94

**Additional information:**

**Comment by danq8** [comment]
Hi Daniel,
Many thanks for taking a look at this.
I'm on the stock launcher, nothing much custom on the phone at all.
I've attached the video to the main request.
Cheers

**Comment by dshokouhi** [comment]
ok i cannot reproduce here on any of the app widgets on my pixel 9 pro xl.

**Comment by danq8** [comment]
My phone is on the 5th November 2024 update, if that helps.

**Comment by dshokouhi** [comment]
yup same here

**Comment by danq8** [comment]
OK, I thought I'd try every app/widget on my phone... most work, but it is doing the same thing for BBC weather, CNN, google drive and a couple more mainstream apps as well....
Definitely something odd on Android 15, and if there's a google widget doing it, then guessing it's something further up the chain. I'll see if I can report it direct to Google (y)

**Comment by danq8** [comment]
OK, there's a workaround, and Google already knows about it... https://www.reddit.com/r/GooglePixel/comments/1g6bpk9/widgets_broken_after_android_15_update/
