### ISSUE TITLE
Unable to reach 2nd URL set in parameter

### ISSUE THREAD

**Issue by Nico-Hard** [home-assistant/android#4819]
Hello,

I set a netbird VPN in home assistant. works fine.

On android, I have now 2 servers :
- 1st : Netbird URL --> to be used when I start the VPN
- 2nd : Local IP --> to be used on specific SSID (set with my home SSID)

However, the APP is always trying to reach the 1st URL, even if I am connected to the WIFI, which lead to an error as the VPN is disable when I am at home.

Not sure this is a bug but if the 1st URL is not reachable, the app should try to reach the 2nd, right ?

----
_Else, but this is an improvement suggestion, Is it possible to have a "welcome page" permitting to select the server/URL I want to connect on ?_

**Comment by dshokouhi** [comment]
Please get the app logs they show the decision making process

**Comment by Nico-Hard** [comment]
I did another setup, playing with the standard URL and internal URL. Looks to be working now.
