### ISSUE TITLE
Various string updates needed for translations

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/android#4823]
**Home Assistant Android app version:**
2024.11.4-full (beta)

**Android version:**
15

**Device model:**
Pixel 6

**Home Assistant version:**
2020.11.2

**Description of problem, include YAML if issue is related to notifications:**

When adding an Picture widget, the popup menu for the Tap action offers two options:
- Refresh
- Open

![Screenshot_20241117-203433](https://github.com/user-attachments/assets/12f67b16-68c3-420e-a5ca-fb964547ed9e)

The two strings these come from seem to be

- `refresh`
- `state_open`

While in English the state "open" is spelled exactly like the action "open" this does not work in other languages.
In German the state is "offen" while the action is "öffnen".

So we need a separate `open` string for the action.

**Comment by NoRi2909** [comment]
Side note as it's a similar problem for translation:
The `finish` string is meant as the verb, I assume?

So far I haven't found that in the UI.
But it's currently translated as "Fertig", meaning "done" which I assume is incorrect.

**Comment by NoRi2909** [comment]
And two more strings for a little consistency cleanup:

"Get total calories burned from Health Connect"
"Get active calories burned from Health Connect"

These are inconsistent with all the other Health Connect sensors that don't use "Get …"
So you can just drop it on these two as well. 

In German the verb is a bit longer with "abrufen" and changes the grammar.

**Comment by dshokouhi** [comment]
> "Get total calories burned from Health Connect"

Actually this one needs to be completely updated to match the other daily health connect sensors since it also resets at midnight

> "Get active calories burned from Health Connect"

For this one we should match the others with "Last recorded ...."

**Comment by dshokouhi** [comment]
> The `finish` string is meant as the verb, I assume?

This one looks unused on first glance

**Comment by NoRi2909** [comment]
I just saw you added the string 'improv_permission_title' with "Search devices".

I assume this should be "Nearby devices":

![markup_1000000647](https://github.com/user-attachments/assets/dd07c20b-7311-4888-a652-4ba8200c6110)

https://support.google.com/android/answer/9417604

**Comment by jpelgrom** [comment]
No, this is search devices intentionally as a general title. Same for permissions to work on all API versions / manufacturers.

**Comment by NoRi2909** [comment]
OK, thanks for the quick update. Then I keep it generic in German, too.
