### ISSUE TITLE
After update to Android 15: battery percent and charging state does not update (untill reboot of phone) and shortcuts are missing after reboot

### ISSUE THREAD

**Issue by XalaTheShepard** [home-assistant/android#4825]
The problem
Dear all,

Last week I have updated my Xiaomi 14 to Android 15.
After the update to Android 15, the battery percentage does no longer update after a while (e.g. for a few minutes turning of the wifi and afterwards turning it back on again). Only after a reboot of the phone, the battery percent updates again (untill I turn of the wifi temporarily again). All other phone sensors (network connected, location, ...) still work flawless, except from the battery sensors. 
Please find attached the companion logs and a screenshot of the issue. 

Furthermore, after every reboot the Home Assistant shortcuts on my phone are gone. I have to add them again, but after another reboot they are gone again.

I am running the latest version of HA core (which is not the issue) and the latest version of the companion app on my phone.

These issues are directly related to the update to Android 15, because before the update everything used to work perfectly.
I have given all permissions to the HA mobile app and the updates every minute.

Many thanks for having a look at this issue.

Kind regards,

Robin

What version of Home Assistant Core has the issue?
2024.11.2

What was the last working version of Home Assistant Core?
2024.11.2

What type of installation are you running?
Home Assistant OS

Integration causing the issue
Mobile app Android 15
![Xiaomi 14 Android 15 Battery state not updated](https://github.com/user-attachments/assets/5fcbbed0-6f38-46c0-b338-738f1ba424ef)
[homeassistant_companion_log_10-18-2024_16-50-19.txt](https://github.com/user-attachments/files/17803253/homeassistant_companion_log_10-18-2024_16-50-19.txt)

**Comment by XalaTheShepard** [comment]
Issue is stated also in this topic: https://github.com/home-assistant/core/issues/130870

**Comment by dshokouhi** [comment]
None of these are fixable by the app. The app cannot control when shortcuts are removed from the launcher, nor can the app control if the API reports invalid data.

**Comment by dshokouhi** [comment]
@XalaTheShepard what version of the app do you have installed?

**Comment by XalaTheShepard** [comment]
I am running version 2024.10.3 of the Android app

**Comment by XalaTheShepard** [comment]
Solved: 

1) Log out in the HA app
2) Clear cache of the phone app
3) Delete all information of the phone app
4) Delete the device in the mobile app integration
5) Delete HA app on the phone
6) Reboot phone
7) Reinstall HA app on the phone
8) Log in into the HA app again

Now all sensors are working again as expected.
