### ISSUE TITLE
Most notification channels do not update their names when app languages changes

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/android#4826]
**Home Assistant Android app version:**
2024.11.5-full (beta)
**Android version:**
15
**Device model:**
Pixel 6
**Home Assistant version:**
2024.11.2

**Description of problem, include YAML if issue is related to notifications:**

When changing the app language between English and German the name of the 'Beacon monitor scanning' notification channel does update after changing the language (and re-enabling it). So that is working as expected. 👍 

For the 'Persistent connection' notification channel this is not the case , it stays at the name that was given to it when first enabled.
The old German translation was "Dauerhafte Verbindung" ("_permanent_ connection") which I recently changed to "Anhaltende Verbindung" ("_persistent_ connection") all over Home Assistant. So we now have that consistency everywhere, but the notification channel is stuck at its old German name, too.

Same seems to apply to the 'High accuracy mode' and 'Sensor worker' channels (note that we have camel-cased that in German to become a name), They are also stuck at their German names when switching the app language back to English:

![Screenshot](https://github.com/user-attachments/assets/19fef988-ab37-42ff-a7cd-655a33164b89)

Finally the 'General' channel needs a localizable string as it shows up with the English name in German, too. Now in German "General" is the military rank only, while the correct translation here is "Allgemein". Probably quite similar in other, future languages.

**Comment by dshokouhi** [comment]
General does indeed need to be updated but the others need to be triggered again meaning you need to turn on persistent connection, trigger a sensor update and turn on high accuracy mode. With the desired language after you confirm the strings are in the app version

**Comment by NoRi2909** [comment]
The updated German strings are already in that beta, I see them in the UI. But regardless it should have changed between English and German names when I switched the app language.

I will try again this evening by enabling and disabling the different functions to see if that triggers the language change.

I did try for quite a while yesterday and did not see any effect, only with the Beacon Monitor Scanning that changed on every languages switch without a hitch.

**Comment by dshokouhi** [comment]
> But regardless it should have changed between English and German names when I switched the app language.

channels can only have 1 name at a time, they need to be updated each and every time when you switch languages for it to take place. Sounds like you may have had the notification up and switched languages which caused the update to send.

those values you see are not from the app in this screen but what was provided to android at the time the channel was created and/or updated

**Comment by dshokouhi** [comment]
you need to trigger the notifications in question to appear everytime you switch the language when the strings are actually provided

**Comment by NoRi2909** [comment]
I managed the 'High Accuracy Location' channel to update its name by toggling the switch under Background Location.
Didn't think about that setting hidden there as there are two sensors with "High accuracy" in their names.
So that one is OK just like 'Beacon monitor scanning'

Regarding the "Persistent Notification" and "Sensor worker" channels, they don't seem to react to anything I tried, remaining stuck on the German names they got when first created.

Toggling 'Persistent Connection' between Never and Always does not have any impact here, it just makes the notification appear and disappear. But it remains at the old German name from several weeks ago.

Regarding 'Sensor worker' there is no setting I'm aware of that disables or enables this channel, there just the 'Manage sensor worker notification' button at the bottom of the Sensor update frequency panel.

**Comment by dshokouhi** [comment]
> Regarding the "Persistent Notification"

ah yes we are preventing updating it here: https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt#L220



> and "Sensor worker" channels

we are doing the same prevention here: https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorWorkerBase.kt#L97

but also we are not using a translated string here: https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorWorkerBase.kt#L100

and to close the loop General is not translated yet: 

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/notifications/NotificationFunctions.kt#L78

Beacon monitor for example has a string and we are always setting the channel so we probably can remove those checks there

https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/bluetooth/ble/MonitoringManager.kt#L83

thank you for the detailed analysis of the strings in other languages :) 🙏
