### ISSUE TITLE
After Android 15 a Samsung UI6. 1 is not posible to update/instal

### ISSUE THREAD

**Issue by ledeckyr** [home-assistant/android#4828]
**Home Assistant Android app version(s):the Last version from google store

**Android version(s):14

**Device model(s):Samsung S23FE

**Home Assistant version: the Last from store

**Last working Home Assistant release (if known): prevoiuse

**Description of problem, include YAML if issue is related to notifications: After update Android and Samsung UI6.1 during weekend have more aplications problem with aplication update. For HA i tried delete instaled version a try to intstal the last version from Google store.  But withou success. 
Rade

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
I'm sorry what issue are you facing? The description doesn't make much sense. Maybe also a screenshot can help

**Comment by ledeckyr** [comment]
If is any chance for sending any logs, write me procedur. Thanks Radek

**Comment by dshokouhi** [comment]
> If is any chance for sending any logs, write me procedur. Thanks Radek

you skipped over those steps in the issue template

Settings > companion app > troubleshooting > show and share logs.

so the app is not installing? i see you say after android 15 update but your device does not have android 15 yet. Did you install a custom ROM by chance?

**Comment by ledeckyr** [comment]
Hi, the information About Android 15 was my misteake. I didn't instal custom ROM. IT is bussines device with the company profil and some restrictions. And the sharing of logs is disable. Today I recived a new update od Google play and  Samsung UI againg. And next aplications have a problem with actualization... Google task too. I think that the issue is generál.

**Comment by dshokouhi** [comment]
this is not anything the app can fix especially if other apps like Google Task has an issue. I suggest reaching out to your companies IT team and have them troubleshoot.
