### ISSUE TITLE
Integrate with Sleep as Android

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#483]
**Is your feature request related to a problem? Please describe.**

I would like to track my sleep and alarm status in Home Assistant from the Sleep as Android app.  The app has a lot of features that can be integrated such as we can have a binary sensor for when sleep tracking is turned on.  We can have another binary sensor for when the alarm is actually triggered instead of knowing when it is set.  We can detect when a user snoozes the alarm to have some things in HA trigger.  For me personally I am using tasker to track sleeping tracking and I use it to automate the alarm in armed night.  You can also detect when a lullaby has started or stopped.  We can also trigger an event for time to bed.  Lots of cool things that you can't do with #56 

**Describe the solution you'd like**

- Binary sensor for sleep tracking `on` or `off`
- Binary sensor for when the alarm is triggered (`on`) and dismissed (`off`)
- Events for when the alarm is snoozed (can be handy to know if you snooze too much and trigger special script)
- Event for time to bed notification (trigger going to bed scene)

**Describe alternatives you've considered, if any**
Currently using Tasker to achieve this with events/intents and HTTP Post

**Additional context**
https://sleep.urbandroid.org/documentation/developer-api/intents-and-content-providers/

Contains all that we can do.

**Comment by balloob** [comment]
I don't think that we should aim to integrate with every possible app with an API on Android. We should try to integrate as much as possible with the Android system, mapping 3rd party apps to Home Assistant to other apps.

**Comment by RikP** [comment]
You can already integrate sleep for android with HA using IFTTT:
https://sleep.urbandroid.org/documentation/integration/ifttt/
https://www.home-assistant.io/integrations/ifttt/

**Comment by dshokouhi** [comment]
@RikP yea I actually mentioned that I am currently using Tasker to achieve this.  The issue with IFTTT is its cloud based and has lag.  With Tasker its pretty quick but you also need to setup the profile and tasks and it becomes a lot of work on just one device, then you need to spread that out against the other users too.  The same issue will be there for IFTTT as you need to set up all the applets and connect the apps etc... My thought here was to eliminate that and make it easier to setup and automate when one is sleeping.

**Comment by sparkydave1981** [comment]
This would make nighttime automations really easy to create.  It is a widely used app

**Comment by dshanske** [comment]
Isn't there a way to track next alarm regardless of alarm app?

**Comment by dshokouhi** [comment]
@dshanske thats completely different than this and already requested in #56 :)   Sleep as android offers much more than just the alarm for integration.

**Comment by dshanske** [comment]
I am a user of Sleep as Android and would love integration... I am just wondering if there is a way to make this work easily.

**Comment by DoctorOctagonapus** [comment]
IFTTT has just announced they're crippling their free version, so a direct integration would be amazing.

I suspect you'd need to raise a feature request with the Sleep As Android devs as well, looks like IFTTT is the only automation style integration they support.

**Comment by ljasinskipl** [comment]
Actually it shouldn't be to difficult. Just let us use custom webhooks

**Comment by IATkachenko** [comment]
Other option is use MQTT and my custom component https://github.com/IATkachenko/HA-SleepAsAndroid 
It fires Home Assistant events (to trigger automations) based on events from Sleep as Android that published at MQTT server. Sensor and supporting of several Sleep as Android devices in single installation is also provided.

**Comment by sparkydave1981** [comment]
> Other option is use MQTT and my custom component https://github.com/IATkachenko/HA-SleepAsAndroid
> It fires Home Assistant events (to trigger automations) based on events from Sleep as Android that published at MQTT server. Sensor and supporting of several Sleep as Android devices in single installation is also provided.

Yes, I have been using your Integration for a few months now and it has been brilliant.  Thank you!
