### ISSUE TITLE
Check for HTTP Status Code when connecting to external URL 

### ISSUE THREAD

**Issue by pisanvs** [home-assistant/android#4831]
**Is your feature request related to a problem? Please describe.**
I have my Home Assistant instance routed through Cloudflare, the other day my certificate expired and I received no notice. This made it so accessing externally didn't work, but when I was at home, with a local URL configured, the app went straight to the external URL with the Cloudflare error instead of attempting to connect to the local URL, which was accesible.

**Describe the solution you'd like**

The app should check the status code returned by the external URL, and attempt to visit the internal URL **as a fallback** in case of an error code. 

**Describe alternatives you've considered, if any**

N/A

**Additional context**

My network setup is admittedly, not ideal. But still, I believe it is good practice to check status codes and enable fallbacks in the spirit of maximizing availability.

**Comment by dshokouhi** [comment]
> I have my Home Assistant instance routed through Cloudflare, the other day my certificate expired and I received no notice.

you should use: https://www.home-assistant.io/integrations/cert_expiry/



> The app should check the status code returned by the external URL, and attempt to visit the internal URL **as a fallback** in case of an error code.

Internal URL only gets tried if user is on WiFi and we fall back to external when its not available. Not the other way around.

**Comment by pisanvs** [comment]
Huh, that's weird! I'll check my configuration then, probably a network issue. 

Closing this issue then, and thanks for the suggestion, I'll start using it from now on.
