### ISSUE TITLE
Next Alarm not reset on white-list usage after alarm deletion

### ISSUE THREAD

**Issue by GottZ** [home-assistant/android#4832]
**Home Assistant Android app version:**
2024.10.3-full

**Android version:**
14

**Device model:**
SM-S908B (Samsung Galaxy S22 Ultra)

**Home Assistant version:**
core-2024.11.2

**Description of the problem:**
When using the white-list feature inside the app to select packages for the next alarm feature, the following reproducible issue occurs:

**Reproduction steps:**
1. set an alarm via a package that is not white listed to the next midnight.
   (or just have com.samsung.android.calendar running.. as it sadly does that)
2. set an alarm to a time between now and midnight using a white-listed app.
3. the alarm should be sent to home assistant successfully.
4. disable the alarm you just created in that white-listed app.
5. the companion app will not remove the wrong next alarm state, as it receives a non-white-listed package name, even though the "new" alarm is further in future than the removed one.

**More visual explaination:**
initial state:
now:
Thu Nov 20 12:00:00 GMT+01:00 2024
white-listed alarm:
Thu Nov 20 15:00:00 GMT+01:00 2024
non-white-listed alarm:
Thu Nov 21 00:00:00 GMT+01:00 2024
next alarm shown:
Thu Nov 20 15:00:00 GMT+01:00 2024

changed state after alarm removal:
now:
Thu Nov 20 12:00:00 GMT+01:00 2024
non-white-listed alarm:
Thu Nov 21 00:00:00 GMT+01:00 2024
next alarm shown:
Thu Nov 20 15:00:00 GMT+01:00 2024

**expected behavior:**
As soon as android returns a non-white-listed app with an alarm that is further in future than the last alarm that was set via a white-listed app, the common sense should be, to set the state to "unknown" due to known limitations with this Android API.

**Comment by dshokouhi** [comment]
Sorry the allow list can only skip updates. Can't pretend like they don't exist in the API. You'll need to remove the offending alarms from the package in question.
