### ISSUE TITLE
Always show first view option says on app start when it should be when opened

### ISSUE THREAD

**Issue by tag6** [home-assistant/android#4840]
**Home Assistant Android app version(s):**
20241106.2

**Android version(s):**
MIUI 14.0.9

**Device model(s):**
Xiaomi Redmi Note 10 Pro

**Home Assistant version:**
2024.11.3

**Last working Home Assistant release (if known):**
Never worked

**Description of problem, include YAML if issue is related to notifications:**
Situation 1: Click anything in Home Assistant so that you are not in the start page. Switch to another app. Switch back to Home Assistant. It reloads and shows the start page.

Explanation why situation 1 is really bad: Use the Home Assistant ToDo-Lists for grocery list. Switch to some other app, like the bonus system of the supermarket. Or to some messenger to ask inside your family regarding some detail. Use the supermarket app to scan the next product when doing own checkout. When you switch back to Home Assistant Companion app, it reloads. You are not in you ToDo-List anymore. You have to select the ToDo-list and scroll to the right place again. This of course happen for every single article in the list if you scan the barcode of every product.

Situation 2: Use anything in Home Assistant Companion app at home and walk outside of your Wifi reception area. On the next action Home Assistant companion app will reload and show the start page. IIRC it also happens when switching router inside the same Wifi network. Especially when debugging network things, it would be very helpful to see the right data or log when things change.

Both situations are annyoing. Other apps usually don't do this. If I want it to refresh, I move it out of the process list and start it again manually.

**Companion App Logs:**

Do you really need logs? Please tell me if it is not easy to reproduce.

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Did you turn on the setting to show first view always?

Settings > companion app > always show first view

**Comment by dshokouhi** [comment]
> Situation 2: Use anything in Home Assistant Companion app at home and walk outside of your Wifi reception area

as long as you have an internal and external URL provided in the app this is to be expected, some setups will not work on the same URL on/off wifi and the app must reload in those cases.

**Comment by tag6** [comment]
Thank you very much!

I activated "always show first view" because it said "on App start", but coming to foreground is no App start, and network change also. 

Using only external URL and deactivated internal URL, everything works fine.

Should have reported this much earlier 😄.

So I suggest to improve the text of the setting "Beim App-Start immer die erste Ansicht anzeigen". Maybe it's just a translation that is misleading a bit.

**Comment by dshokouhi** [comment]
> I activated "always show first view" because it said "on App start", but coming to foreground is no App start, and network change also.

ah yes the title says "on app start" but the description says when open, will update the title to make it more precise

![image](https://github.com/user-attachments/assets/9496ad71-0025-44bf-bf43-7ba37fe632e0)
