### ISSUE TITLE
The input number field does not allow changing back to negative values after being switched to positive.

### ISSUE THREAD

**Issue by RobusX** [home-assistant/android#4843]
**Home Assistant Android app version(s):**  2024.10.3-full

**Android version(s):** 14

**Device model(s):**  Galaxy A34 5G

**Home Assistant version:** 2024.10.4

**Last working Home Assistant release (if known):** For many releases the same issue present

**Description of problem, include YAML if issue is related to notifications:**

I am using a heating automation which in the dashboard displays an outside temperature threshold (mostly a negative value) as an input number.  This threshold determines when a switch between two heating types occurs.

The problem is that when using an input number field (created with a helper) of type "input field" (not "slider"), in the companion app it is not possible to enter/ change a negative value because the "-" sign is missing on the bottom keypad.
When the "-" sign is removed (due to a change to a positive temperature value), it is not possible to enter a new negative temperature value.

With the slider, this issue does not exist, but using the slider makes it difficult to adjust the value in smaller increments, making it less suitable compared to the input field.

Second picture at the bottom shows HA server side, where is no such problem.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![Screenshot_20241123_214636_Home Assistant](https://github.com/user-attachments/assets/fd8a8447-dfec-40a6-99ef-f73a49316cf0)
![ha_server](https://github.com/user-attachments/assets/6abd6df2-f1cb-436a-b25c-e634191b1892)
![threshold](https://github.com/user-attachments/assets/28e74aca-0a47-4842-bc80-86fba28bbf1c)

**Additional information:**

**Comment by jpelgrom** [comment]
Do you see the same issue when using Home Assistant in a browser on your phone?

Keyboards shouldn't behave different for the app vs browsers, this is most likely a frontend issue.

**Comment by RobusX** [comment]
Yes, when using the HA app in an Android browser, the same issue exists.
I tried it with Chrome. There are no up/down arrows for temperature adjustment, also no  "-" sign.

**Comment by dshokouhi** [comment]
> Yes, when using the HA app in an Android browser, the same issue exists.

that means this is a frontend issue a similar issue was opened but as nobody responded to stale bot it was closed. I recommend opening a new issue 

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

ref: https://github.com/home-assistant/frontend/issues/19893
