### ISSUE TITLE
Sliding to the left to access wider trace graphs is not possible on Android.

### ISSUE THREAD

**Issue by RobusX** [home-assistant/android#4844]
**Home Assistant Android app version(s):** 2024.10.3-full

**Android version(s):**  14

**Device model(s):** Galaxy A34 5G

**Home Assistant version:**  2024.10.4

**Last working Home Assistant release (if known):** Not known

**Description of problem, include YAML if issue is related to notifications:**

When attempting to view the left side of a wider graph trace, it is not possible to slide to the left. 
However, sliding to the far-right part of the graph works without any issues.
First picture below shows sliding attempt to the left while bottom one shows sliding to the right.

The same issue exists when HA within a browser (tried with Chrome) has been opened on the Android phone.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![Screenshot_20241123_215147_Home Assistant](https://github.com/user-attachments/assets/8ed35d54-a2f2-4411-972c-80766fb0cac5)
![Screenshot_20241124_082004_Home Assistant](https://github.com/user-attachments/assets/b251fb60-38a7-4e6d-a9d2-b47a721f4f96)

**Additional information:**

**Comment by dshokouhi** [comment]
> The same issue exists when HA within a browser (tried with Chrome) has been opened on the Android phone.

that means this is a frontend issue, please check for open issues before logging an issue with the HA frontend

https://github.com/home-assistant/frontend/issues
