### ISSUE TITLE
Companion App Assist End of Speech Timeouts, never detects End of Speech

### ISSUE THREAD

**Issue by gribouk** [home-assistant/android#4847]
**Home Assistant Android app version(s):**
2024.10.3-full

**Android version(s):**
14

**Device model(s):**
Samsung Galaxy S22 Ultra
Samsung Galaxy S24Ultra

**Home Assistant version:**
2024.11.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
I’ve been using the companion app at my android galaxyS22 phone. The problem is that when adressing the assist with the voice command it always times out with the end of the speach detection failure. No metter what I say, I have to wait for 15s till it determines that the message is over. It just does not detect the end of speach. With remote satelite, one can work around this issue playing with mic settings. Is there anything I can do for the Android?

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
End of speech is supposed to be detected by your pipeline/server, and then the app will stop recording. Without introducing a lot of additional logic this isn't something that can be solved by the app (it currently is simply sending audio based on what the server tells the app, nothing more).
