### ISSUE TITLE
Navigate Back Command doesn't always take you directly to the last View

### ISSUE THREAD

**Issue by dafunkydan** [home-assistant/android#4858]
**Home Assistant Android app version(s):**
2024.10.3-full

**Android version(s):**
15

**Device model(s):**
Google Pixel 6a

**Home Assistant version:**
2024.11.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
On Views like e.g. editing Automations*, Navigating Back does not Work. 
Better said: every Input, Selection within that Window seems to counts as Navigation. Therefore, you need to press many Times Back to actually navigate Back. From A User-Perspective: If my Wife says it doesn't work, then it doesn't work 😀

Reproduce: 
- Open an Automation. Press back - you will get back.
- Open an Automation. Add another Action, edit a Field in that Action. Press back, Press back, Press back, Press back - you will get back. It can easily sum up to like 50 necessary Back-Commands, til you get back, depending on your Actions on that View.

Expected Behavior: Pressing back Leads to navigating to the last Screen.

_*Also on more Pages, especially when related to Device Infos. Need to reproduce the exact Steps later_

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
The app does not have specific back handling for these screens and will follow the frontend (you'll see the same in a browser when using the back option). Please look for an issue/create an issue here: https://github.com/home-assistant/frontend/issues

**Comment by dafunkydan** [comment]
Indeed, sorry and Thanks!
For Reference: https://github.com/home-assistant/frontend/issues/17820
