### ISSUE TITLE
An option to toggle always retry external connection

### ISSUE THREAD

**Issue by Daniel-dev22** [home-assistant/android#4859]
**Is your feature request related to a problem? Please describe.**

If I only use a single domain for both remote and local access and the difference is what DNS ip is resolved whenever I switch networks from local to data for example I have to wait for the retry external address prompt for it to poll DNS for the domain and connect. Otherwise it's stuck on "connecting.." for a period of time.

**Describe the solution you'd like**

It would be great for it to either automatically detect there's only external access configured and retry automatically without waiting for multiple seconds before prompting the user or for some setting that allows the user to select which to automatically retry for x seconds before the prompt for retrying external or internal. 

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
The pop-up is working as designed sometimes it can take up to 10 seconds for the app to connect to the server.
