### ISSUE TITLE
Missing screen mover (data not showed completelly)

### ISSUE THREAD

**Issue by misa1515** [home-assistant/android#4864]
**Home Assistant Android app version(s):**
2024.11.5-full

**Android version(s):**
14 UP1A.230905.011

**Device model(s):**
2306EPN60G
OS version 1.0.9.0.UMFMIXM

**Home Assistant version:** 
2024.11

**Last working Home Assistant release (if known):**
Not relevant (saw always same too in previous versions)

**Description of problem, include YAML if issue is related to notifications:**
On attached screenshot you can see complete data of version history (right area marked by red rectangle).

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![AndroidWebHaStatOverview](https://github.com/user-attachments/assets/ae19aedb-f23e-4cd1-83a9-b49ed8753ae9)

**Additional information:**

**Comment by dshokouhi** [comment]
this app has nothing to do with HA Analytics, the correct place to file those issues are in https://github.com/home-assistant/analytics.home-assistant.io
