### ISSUE TITLE
Sensors not updating from mobile app to HA, notification response fails with "Failed to notify HA of picked option"

### ISSUE THREAD

**Issue by livlif2dfullest** [home-assistant/android#4865]
**Home Assistant Android app version(s):**
2024.10.3-full

**Android version(s):**
14

**Device model(s):**
Galaxy Z Fold5 SM-F946U

**Home Assistant version:**
Core 2024.11.3
Frontend 20241106.2

**Last working Home Assistant release (if known):**
Same, the only change I made was switched HA from one drive to another.  Shutdown container, copied everything to new drive and restarted container, now app doesn't handle actionable notifications, nor are sensors created.

**Description of problem, include YAML if issue is related to notifications:**
At this point, when I execute an actionable notification and click a button in the toast, I get "Failed to notify HA of picked option"
When I force close the app, delete the Mobile App integration, clear all data from the app, cache and data, turn off WiFi, and then re-launch HA app, prompted for server, enter in https://domain-name, not using Nabu-casa, have my own registered domain that I can access via Internet.  Prompted for credentials, enter them, logs in successfully and displays default dashboard.  Mobile App Integration only shows 1 device and 1 entity device_tracter.name.  So sensors are not getting created, waited 24 hours and still no new sensors from mobile app.

**Companion App Logs:**
I replaced my domain with "domain-name"
[homeassistant_companion_log_11-2-2024_8-55-51.txt](https://github.com/user-attachments/files/17980175/homeassistant_companion_log_11-2-2024_8-55-51.txt)
```
Some errors extracted from above logs:

12-02 08:48:34.974 29739 29772 E IntegrationRepository: Issue getting new version from core.
12-02 08:48:34.974 29739 29772 E IntegrationRepository: io.homeassistant.companion.android.common.data.integration.IntegrationException: retrofit2.HttpException: HTTP 404 
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.getConfig(IntegrationRepositoryImpl.kt:533)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$getConfig$1.invokeSuspend(Unknown Source:14)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:99)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: Caused by: retrofit2.HttpException: HTTP 404 
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:529)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
12-02 08:48:34.974 29739 29772 E IntegrationRepository: 	at java.lang.Thread.run(Thread.java:1012)

12-02 08:48:35.203 29739 29772 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false, usesWifi is: false
12-02 08:48:35.324 29739 29772 E SensorReceiver: Issue registering sensor battery_level
12-02 08:48:35.324 29739 29772 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: Error calling integration request register_sensor
12-02 08:48:35.324 29739 29772 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.registerSensor(IntegrationRepositoryImpl.kt:761)
12-02 08:48:35.324 29739 29772 E SensorReceiver: 	at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$registerSensor$1.invokeSuspend(Unknown Source:15)
12-02 08:48:35.324 29739 29772 E SensorReceiver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-02 08:48:35.324 29739 29772 E SensorReceiver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
12-02 08:48:35.324 29739 29772 E SensorReceiver: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
12-02 08:48:35.324 29739 29772 E SensorReceiver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
12-02 08:48:35.324 29739 29772 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
12-02 08:48:35.324 29739 29772 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
12-02 08:48:35.324 29739 29772 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
12-02 08:48:35.324 29739 29772 E SensorReceiver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
`io.homeassistant.companion.android.common.data.integration.IntegrationException: retrofit2.HttpException: HTTP 404 `

please follow our start fresh steps to rule out configuration issues

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by dshokouhi** [comment]
> Click "I UNDERSTAND" for Security vulnerably warning. Should be "vulnerability". Dashboard displays

sounds like something on your HA core setup is not right, the vulnerability warning is only on HA core versions from years ago. Sounds like the issue you need to solve. Maybe you need to reinstall via docker?

**Comment by livlif2dfullest** [comment]
I shut down docker
docker compose down
Then pruned all images
docker image prune
Then did docker compose up -d -remove-orphans
It showed a new docker image was pulled for HA (weird I have to do this since the core version showed 2024-11-3 in HA)
Followed same steps for new instance install.
I still see the vulnerably warning and the mobile app still isn't creating new sensors or handling notification actions correctly.

Are you saying I need to start with a brand new instance, meaning start from scratch, re-adding all my integrations, etc?

**Comment by dshokouhi** [comment]
the 404 error is coming from your server, the app cannot fix it. It must be fixed from the server side. Double check the entire URL is accessible including the APIs

**Comment by livlif2dfullest** [comment]
If I need to go thru the code that is giving me the 404, I can do that, just wondering if there was something specific you were aware of, off the top of your head, in troubleshooting this to save me some time.

**Comment by dshokouhi** [comment]
looks like the failure is triggered during device registration (or in this case update) `/api/mobile_app/registrations`

https://developers.home-assistant.io/docs/api/native-app-integration/setup#registering-the-device-1

**Comment by livlif2dfullest** [comment]
OK, is there logging I can turn on to get the Url, if you know off the top of your head, otherwise I can modify the code to display the Url I need to test to see if I can determine why it's getting a 404 and thank you for looking up that API cal, that is very helpful 😊

**Comment by dshokouhi** [comment]
check logs on HA core and maybe enable debug logging for mobile app integration, you can also try checking network logs

the expectation on the app end is that the APIs return successful data, 404 is not anything we can fix

**Comment by livlif2dfullest** [comment]
Though this isn't the first time this has happened, last time I created a new instance from scratch to resolve it. I will spend some time on troubleshooting this, as more than likely it will happen again, so if I can find a fix so it doesn't happen to me or someone else I'll do that

**Comment by livlif2dfullest** [comment]
Rebooted the host, same issue.
I turned on mobile app debugging
homeassistant.components.mobile_app: debug
and did the fresh start instructions, but nothing was logged.  When I look in the integrations, it is showing that the Mobile App debug logging is enabled.  So not sure why that's not working, same issue though still not working in regards to no sensors being created and mobile notification actions not working.  I'll look into the code and see if I can troubleshoot further.

Thank you for the help.  If you think of anything, please feel free to let me know :)

**Comment by dshokouhi** [comment]
you should see that failure in HA core logs as I mentioned previously, if you enable debug logging there you will indeed at least see the registration successful. Have you tried bypassing nginx to rule it out as an issue?

**Comment by dshokouhi** [comment]
maybe this will help you: https://companion.home-assistant.io/docs/troubleshooting/networking#addendum-reverse-proxy-via-nginx

**Comment by livlif2dfullest** [comment]
I finally figured it out.  I had created a location for the /api/webhook, which has been there since I've been using HA for a few years now, working the whole time, however, once I deleted that location and reverted other settings (changing those settings didn't fix anything but I don't know if it might of been a combination of changes or just the last change of deleting the /api/webhook location) I was able to register the HA mobile app successfully and all the sensors were created while connecting remotely (off WiFi).  Here's screenshots of my setup in case I hit this issue again or someone else does and it helps them:
![NginxProxy1Details](https://github.com/user-attachments/assets/94d57951-146b-4a57-a26d-1b32762b9014)
![NginxProxy2CustomLocations](https://github.com/user-attachments/assets/79389a59-f4e5-4131-88f2-2c4fa96d44d3)
![NginxProxy3SSL](https://github.com/user-attachments/assets/06dc14b3-69ad-4c10-990b-6a433b8614a1)
![NginxProxy4Advanced](https://github.com/user-attachments/assets/4d4a4ed0-714a-4943-896f-ac33cd20ffd6)
