### ISSUE TITLE
"Dismiss" on notification sent to element behind toast

### ISSUE THREAD

**Issue by TheToddLuci0** [home-assistant/android#4876]
**Home Assistant Android app version(s):**
2024.10.3
**Android version(s):**
GrapheneOs - 2024120400 (android 15)
**Device model(s):**
Pixel 7
**Home Assistant version:**
13.2
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

When attempting to click "dissmis" on an in-app toast, the click was sent to the elements behind the notification. In this case, that resulted in inadvertently triggering a HAOS update before reading the changelogs. The update button was completely covered, so there should be no way it could have been a miss click.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![Screenshot_20241204-135738.png](https://github.com/user-attachments/assets/b474cd76-9058-42d3-bbbc-9315596a5380)

**Additional information:**

**Comment by dshokouhi** [comment]
Please log a frontend bug for this as the app cannot fix

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml
