### ISSUE TITLE
Android companion app crashes after uprading core to 24-12-0 when opening Settings -> Devices & services

### ISSUE THREAD

**Issue by jeback1** [home-assistant/android#4883]
**Home Assistant Android app version(s):**
2024.10.3-full
**Android version(s):**
13
**Device model(s):**
Google Pixel 4a
**Home Assistant version:**
Haos
RaspberryPi 4
Core: 2024.12.0
Supervisor: 2024.11.4
Operating System: 14.0
Frontend: 20241127.4
**Last working Home Assistant release (if known):**
Core: 2024.11.2
**Description of problem, include YAML if issue is related to notifications:**
Clicking Settings -> Devices & services causes the Android app to disappear.  
Reverted to Core: 2024.11.2 and it's working as expected

**Companion App Logs:**
I'm not certain that this is the right fragment of the log, but here's what I found:

12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: FATAL EXCEPTION: main
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: Process: io.homeassistant.companion.android, PID: 25179
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothLeScanner.startScan(java.util.List, android.bluetooth.le.ScanSettings, android.bluetooth.le.ScanCallback)' on a null object reference
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: 	at com.wifi.improv.ImprovManager.findDevices(ImprovManager.kt:243)
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: 	at io.homeassistant.companion.android.improv.ImprovRepositoryImpl.startScanning(ImprovRepositoryImpl.kt:65)
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: 	at io.homeassistant.companion.android.webview.WebViewPresenterImpl$startScanningForImprov$1$1.invokeSuspend(WebViewPresenterImpl.kt:488)
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
12-05 13:21:10.666 10059 25179 25179 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2d35519, Dispatchers.Main]
12-05 13:21:10.669  1000  1991 25561 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
12-05 13:21:10.669  1000  1991 11254 W ActivityTaskManager:   Force finishing activity io.homeassistant.companion.android/.webview.WebViewActivity
12-05 13:21:10.698  1000  1991  2130 I ActivityManager: Showing crash dialog for package io.homeassistant.companion.android u0
12-05 13:21:10.700  1000  1991  2152 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
12-05 13:21:10.740  1000  1991  2130 D CoreBackPreview: Window{cc4132c u0 Application Error: io.homeassistant.companion.android}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper@8889f5c, mPriority=0}
12-05 13:21:11.172  1000  1991  2132 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{d0aeef6 u0 io.homeassistant.companion.android/.webview.WebViewActivity} t11882 f}}
12-05 13:21:11.193  1000  1991  2132 W ActivityTaskManager: Activity pause timeout for ActivityRecord{d0aeef6 u0 io.homeassistant.companion.android/.webview.WebViewActivity} t11882 f}}
12-05 13:21:12.538  1000  1991  2130 D CoreBackPreview: Window{cc4132c u0 Application Error: io.homeassistant.companion.android}: Setting back callback null
12-05 13:21:12.539  1000  1991 11254 W WindowManager:   Force finishing activity io.homeassistant.companion.android/.webview.WebViewActivity
12-05 13:21:12.558  1000  1991  2132 V WindowManager: Unknown focus tokens, dropping reportFocusChanged
12-05 13:21:12.566  1000  1991 11254 I ActivityManager: Killing 25179:io.homeassistant.companion.android/u0a59 (adj 900): crash
1
```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
duplcate of https://github.com/home-assistant/android/issues/4882 and others, wll be fixed in the next app update out shortly 2024.12.1
