### ISSUE TITLE
Crash when UWB disabled

### ISSUE THREAD

**Issue by niall895** [home-assistant/android#4886]
**Home Assistant Android app version(s):**
2024.10.3-full
**Android version(s):**
14
**Device model(s):**
SM-S928B/DS
**Home Assistant version:**
2024.12
**Last working Home Assistant release (if known):**
Unknown
**Description of problem, include YAML if issue is related to notifications:**
App crashes when opening 'Devices & Services' in the settings menu.
This only occurs when Ultra-wideband (UWB) is disabled in the phone settings AND the 'nearby devices' permission is granted for the companion app.

**Comment by dshokouhi** [comment]
duplcate of https://github.com/home-assistant/android/issues/4882 and others, wll be fixed in the next app update out shortly 2024.12.1
