### ISSUE TITLE
Crash Android app after going to devices

### ISSUE THREAD

**Issue by kzajac83** [home-assistant/android#4887]
**Home Assistant Android app version(s):**

**Android version(s):**

**Device model(s):**

**Home Assistant version:**

**Last working Home Assistant release (if known):**
Before December HA core /os upgrade. 

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

Have last version android app and HA. 
December HA core upgrade  (in meantime was OS upgrade)  cause that going to settings and devices is not possible because Android app fail. Today upgrade HA core not help. 

In web browser from phone working fine. 

[log_app_android.txt](https://github.com/user-attachments/files/18045632/log_app_android.txt)

**Comment by dshokouhi** [comment]
duplcate of https://github.com/home-assistant/android/issues/4882 and others, will be fixed in the next app update out shortly 2024.12.1
