### ISSUE TITLE
Push Notification and "Default app" opening URLs

### ISSUE THREAD

**Issue by emandtf** [home-assistant/android#4907]
**Home Assistant Android app version(s):** 2024.12.1-full

**Android version(s):** 13

**Device model(s):** Samsung Note 20 Ultra

**Home Assistant version:** 2024.11.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**
A push notification sent using:

> action: notify.mobile_app_sm9860
  data:
  message: MESSAGE
  title: TITLE
  data:
    provider: push
    source: person.emandtf
    clickAction: /shopping-list
    url: /shopping-list
    tag: shopping_list
    sticky: true
    persistent: true
    timeout: 1800
    visibility: public
    vibrationPattern: 150 1000 150 1000 150

reaches the device but if I click on it it won't open HA Companion App but the default browser instead.
I noticed that "_Default app --> Supported web addresses_" (I translated this path from my language) settings in HA Companion app's info page has only:

- my.home-assistant.io
- www.home.assistant.io

as domains for choosing to open HA Apps instead of the browser.

Possibile solution:

1. Android's Push Notification Intents have to be directly handled by App Companion to resolve the deep-link from inside the App....
2. ...OR Local and Remote domains needs to be added to that List

**Comment by dshokouhi** [comment]
do you have a proxy setup? the only time the app opens a browser is if the URL is not relative, this only happens in some setups where a users proxy may change the URL.

default apps does not matter here

**Comment by emandtf** [comment]
No any proxy or something else, just HA installed on my server and HA Companion App installed in my phone.
As I said sending a "notify.mobile_app_... " push notification for opening Shopping List, results in an opening of the default browser at correct URL, but "http://..../shopping-list" is not a valid URL for HA Companion App.

**Comment by dshokouhi** [comment]
Can you please clean up the example and use only the relevant parts that are acceptable to android? 

I cannot reproduce here so its either in your automation or your network setup. How do you access your server remotely? Nabu Casa?

**Comment by dshokouhi** [comment]
> Obliviously I'm expecting the deeplink to be opened INSIDE Companion App and not outside.

not a deep link for us, we deliberately take user to browser when the URL changes from what we expect which only happens in some user network setups

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt#L1582-L1594

Can you check notification history in the app to see what data the app received? Settings > companion app > notification history

**Comment by emandtf** [comment]
All are "acceptable" arguments for Android...or additional/custom Data arguments doesn't ruins anything 😅
Additional parts are just "accessories" about timeout, vibration, etc...and setting them or not doesn't change anything.

However this is the minimum code for testing it (quoting here obliviously ruins indentations):

> action: notify.mobile_app_sm9860
data:
  message: MESSAGE
  title: TITLE
  data:
    clickAction: /shopping-list
    url: /shopping-list

With this example I receive a Push, then I click it and Chrome is opened on my Samsung phone at the correct internal link (http://192.168../shopping-list, because I am currently connected to Local WiFi and Companion App creates right deeplink....but when clicked the action is done OUTSIDE Companion App. Same things happen on Mobile Data but Companion App uses External IP/DDNS as domain name as expected)

**Comment by emandtf** [comment]
> Can you check notification history in the app to see what data the app received? Settings > companion app > notification history

Sure.
This is the Companion App's Log record for the test I provided few minutes ago.

![SmartSelect_20241215_194705_Home Assistant](https://github.com/user-attachments/assets/b559c757-0318-4104-8526-418adcf8cb8b)

**Comment by dshokouhi** [comment]
are you certain the relative URL is correct there? Can you try a different URL?  `/shopping-list` does not exist anymore.

the following format works for me:

```
action: notify.mobile_app_dannys_pixel_9_pro_xl
data:
  message: test
  data:
    clickAction: /todo?entity_id=todo.shopping_list
```

**Comment by emandtf** [comment]
I know that TODo has replaces ShoppingList Integration, but the official Doc of TODO doesn't tell anything about Push Notifications like ShoppingList done instead (attached picture) 
![SmartSelect_20241215_200417_Chrome](https://github.com/user-attachments/assets/1f5cb72d-1178-495f-9b8b-eb2fd7295319)

So there isn't any place where to know the right new-URL or any info about the need to modified all "deep links" for Push Notifications 🤷‍♂️

Morove:  trying to manually open "http://192.../shopping-list" from my browser I'm well redirected to newer "todo=..." link.

So I suppose TODO Docs needs an update/fix and an example with the appropriate "deep link" for push notifications, and the old ShoppingList Doc page need some advice about this specific breaking change 😅

**Comment by dshokouhi** [comment]
> So there isn't any place where to know the right new-URL or any info about the need to modified all "deep links" for Push Notifications 🤷‍♂️

yes the docs need to be updated with correct info. This only impacts the shopping list.

> Morove: trying to manually open "http://192.../shopping-list" from my browser I'm well redirected to newer "todo=..." link.

thats where the app is failing and we cant correct, we will indeed load the browser when its redirected like that



> So I suppose TODO Docs needs an update/fix and an example with the appropriate "deep link" for push notifications, and the old ShoppingList Doc page need some advice about this specific breaking change 😅

please feel free to submit a docs update to correct that, this is not something the app can fix
