### ISSUE TITLE
Auto restart App once a day

### ISSUE THREAD

**Issue by pskowronek** [home-assistant/android#4910]
**Is your feature request related to a problem? Please describe.**
When running HA companion app on android 24/7 on older Android devices, after 2-3 days the application slows down to the point the Android OS is asking whether to restart the app or wait. Clearly, there's a problem with either HA Web JS and GC, but it can also be a problem with old Android and its webview.  It would be nice if there was an option to automatically restart or close the app at defined time (once a day for example).

**Describe the solution you'd like**
When option added, one could define when to close (or restart if possible) the app at certain time & day. Depending how HA app was set up on device, it could automatically start if restart from HA app was not possible.

**Describe alternatives you've considered, if any**
A notification that could be sent from HA to a companion app to either close or restart itself.

**Additional context**
Many people are re-using old android devices to display HA dashboards, where there are limited options to update android OS. So, having a way to refresh the app without user intervention would be nice. Third party apps that could kill HA app require rooted phones I think.
There was a similar request here: https://github.com/home-assistant/android/issues/4660 - but I guess it strayed away.

**Comment by dshokouhi** [comment]
I don't think this is a good idea for the app. Sounds like a job for tasker.

**Comment by dshokouhi** [comment]
Do you see the same issue using chrome for android on the same device?

**Comment by pskowronek** [comment]
> I don't think this is a good idea for the app. Sounds like a job for tasker.

But I guess, would this require a rooted device?
BTW, if you carefully google out for such an option you find it quite of them. It could be buried somewhere in debug menu or something to cope with older devices.

> Do you see the same issue using chrome for android on the same device?

As I said, this is one of older devices - minimal number of apps, i.e. stock - not rooted, only HA companion app installed. I assume that this a quite common practice to use such devices as dashboards for HA.

**Comment by dshokouhi** [comment]
> As I said, this is one of older devices - minimal number of apps, i.e. stock - not rooted, only HA companion app installed. I assume that this a quite common practice to use such devices as dashboards for HA.

every android device has a default browser and its typically chrome, the app itself uses webview which is based off chromium and that is the only way to properly test and see if there is a frontend issue which needs to be fixed.

>  Clearly, there's a problem with either HA Web JS and GC, but it can also be a problem with old Android and its webview

in order to confirm this we need to check the same behavior on a browser from the same device.

**Comment by pskowronek** [comment]
@dshokouhi I don't think there's anything that could be fixed in HA comp app. Device is like 6 years old (Huawei p10 lite).
As it comes to my feature request - it would be also a feature that people could use, like close the companion app via HA (every night for example), or to remotely reload/refresh dashboards after editing them etc.

**Comment by dshokouhi** [comment]
> it would be also a feature that people could use, like close the companion app via HA (every night for example),

This hampers app functionality like sensor updates so we should not consider that.



> or to remotely reload/refresh dashboards after editing them etc.

this needs to be handled by the HA frontend.

**Comment by pskowronek** [comment]
> > it would be also a feature that people could use, like close the companion app via HA (every night for example),
> 
> This hampers app functionality like sensor updates so we should not consider that.

But how, having root one could restart the app with Tasker :) and the affect would be the same.

> 
> > or to remotely reload/refresh dashboards after editing them etc.
> 
> this needs to be handled by the HA frontend.

Yes maybe, but from practice, restart the app is sometimes a solution, right? Having HA displayed around house via old tablets or smartphone, then you need to go around to restart them or the app.
BTW, reload via HA fontend - people asking for this feature for years on HA forum, and so far only workaround solutions exist based that check if there's 'button' refresh in notification msg box.

> This is not a request we should consider, other apps like Tasker are better suited for task management requests

It requires root most probably which limits the options.

**Comment by dshokouhi** [comment]
> Yes maybe, but from practice, restart the app is sometimes a solution, right? Having HA displayed around house via old tablets or smartphone, then you need to go around to restart them or the app.
> BTW, reload via HA fontend - people asking for this feature for years on HA forum, and so far only workaround solutions exist based on JS that checks if there's 'button' refresh in notification msg box.

no thats not a solution, and also requesting the app to make a change based on the frontend not adding it yet is also not something we should consider.

I am going to close this request now as we should not add workarounds but actually fix the issue, please report frontend issues if you see them to the frontend so they can fix things properly.

**Comment by pskowronek** [comment]
> no thats not a solution, and also requesting the app to make a change based on the frontend not adding it yet is also not something we should consider.

it was NOT "based on the frontend not adding it" - it was a comment to a suggestion that frontend should add it.
Whether slowness or unresponsiveness is UI (webview) fault or not, it is a common practice to preemptively periodically restart apps (services) especially if they run 24/7. 

> should not add workarounds but actually fix the issue, 

Again, the whole point is different. Like any app or service that runs continuously 24/7 may experience memory leaks of resource build up, it can be either on app level, or on system level (android), or even custom layers added by phone vendors, so preemptive restart is they way, especially for older unsupported androids.

Final word (won't bother anymore) - it is not an app that is only used to check 'how things are going', but it is also used to display dashboards - in former case, I agree that restart idea is odd, but in case of 24/7 duty it is not.
