### ISSUE TITLE
Android (non standard ROM) maximum screen brightness higher than 255

### ISSUE THREAD

**Issue by LukasTycho** [home-assistant/android#4914]
**Home Assistant Android app version(s):**
2024.12.1-full

**Android version(s):**
12 SKQ1.210908.001
MIUI Global 13.0.16.0 (SKFEUXM)

**Device model(s):**
Xiaomi Redmi Note 10 Pro (M2101K6G)

**Home Assistant version:**
Core: 2024.12.4
Supervisor: 2024.12.0
Operating System: 14.0
Frontend: 20241127.8

**Last working Home Assistant release (if known):**
n/a

**Description of problem, include YAML if issue is related to notifications:**
Home Assistant only allows for screen brightness changes of a mobile Android device up to a maximum value of 255. On my phone that only equates to roughly a third of the maximum brightness. The maximum value my phone reports is 2047 (see screenshot). I am aware that the official Android API reference defines brightness to be 0...255, however "non standard ROMs" (like the MIUI on my phone) don't always seem to comply with this range. I have read about multiple users with this problem both in HA and other applications. I would love it if it were possible to change the maximum value that can be sent out by HA.

**Companion App Logs:**
n/a

**Screenshot or video of problem:**
<img width="415" alt="image" src="https://github.com/user-attachments/assets/af79a5d9-ec46-4ded-85d1-f98709d0b9fe" />

**Additional information:**
[Forum entry with this problem from late september](https://community.home-assistant.io/t/screen-brightness-only-30/587636/12)

**Comment by dshokouhi** [comment]
We can't account for every thing a custom ROM decides to do that is different from developer documentation. In this case we respect the docs which satisfy the majority of use cases.
