### ISSUE TITLE
[Android 15] Hard to add controls to "device controls"

### ISSUE THREAD

**Issue by potchin** [home-assistant/android#4916]
**Home Assistant Android app version(s):**
2024.12.1-full
**Android version(s):**
15
**Device model(s):**
Pixel 8
**Home Assistant version:**
2024.12.4
**Last working Home Assistant release (if known):**
N/A
**Description of problem, include YAML if issue is related to notifications:**

Since the upgrade to Android 15 its nearly impossible to add new controls to the "device controls" page, accessed via the "device controls" quick settings link if you use button navigation rather than gestures. Both the "Add controls" and "Save" buttons are almost completely covered by the navigation buttons.

To reproduce:
 - ensure android button navigation is enabled (so triangle, square and circle are on the bottom)
 - pull down the quick settings shade from the top edge
 - click "device controls"
 - three dots menu 
 - "Edit controls"
 - Observe the "Add controls" button is obscured by the android navigation buttons

![Screenshot_20241218-192019](https://github.com/user-attachments/assets/50b73b45-be55-419b-b51e-52e7b675a289)

I _think_ its related to the [edge-to-edge change](https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge) in Android 15

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
This is a system screen and not controlled by the Home Assistant app, so unfortunately we cannot fix this issue. You may want to open a bug report in the [Google issue tracker](https://issuetracker.google.com/issues) (I couldn't find an existing report for this).

**Comment by potchin** [comment]
thanks. Opened a [bug](https://issuetracker.google.com/issues/384954750) there :crossed_fingers:
