### ISSUE TITLE
Next Alarm Sensor ignoring allow list

### ISSUE THREAD

**Issue by SebboGit** [home-assistant/android#4924]
**Home Assistant Android app version(s):**
2024.12.1-full
**Android version(s):**
14
**Device model(s):**
Samsung Galaxy S24+
**Home Assistant version:**
Core 2024.12.5
Operating System 14.1
Supervisor 2024.12.0

**Description of problem, include YAML if issue is related to notifications:**
I'm using the Next Alarm Sensor for some automations which has been working fine so far. I have recently added a Samsung Routine that is based on a time pattern and after that I've noticed the automations triggering at weird times. I checked the Next Alarm Sensor and noticed the next alarm HA is picking up is by package com.samsung.android.app.routine. So far I have not needed the allowlist because there was no other app except the actual clock/alarm app setting any alarms.
So I have searched for the clock app (com.sec.android.app.clockpackage) "Uhr" in the allowlist and selected it. Nothing else is selected (as you can see on the screenshot below) but HA still uses com.samsung.android.app.routine for the next alarm. I have restarted the app and deleted the cache without any success.

**Screenshot or video of problem:**
![Screenshot_20241222_232638_Home Assistant](https://github.com/user-attachments/assets/4ea8b0a8-fad2-434b-a8ed-875bc2d3778b)

**Comment by dshokouhi** [comment]
allow list will skip unwanted updates, we cant get rid of them, you will need to go in the samsung application and remove the alarms. That is the only way to get it to work as desired
