### ISSUE TITLE
Developer tools - YAML - button alignment 

### ISSUE THREAD

**Issue by z-master42** [home-assistant/android#4933]
**Home Assistant Android app version(s):**
2024.12.1-full

**Android version(s):**
14

**Device model(s):**
Nothing Phone (2)

**Home Assistant version:**
2024.12.5

**Description of problem, include YAML if issue is related to notifications:**
It's more cosmetic, but as far as I can remember, all buttons to reload parts of the YAML configuration in the developer tools are left-aligned, except the button for groups, group entities and notification services. These are center aligned.
This is only the case in the companion app

**Screenshot or video of problem:**
![Screenshot_20241225-132003](https://github.com/user-attachments/assets/84dabd0b-69fb-4dae-9ba0-12da545fbb11)

**Comment by jpelgrom** [comment]
This is a screen from the frontend and the app cannot change this, you could create a frontend feature request on community.home-assistant.io.

> This is only the case in the companion app

It probably depends on the screen size and zoom setting, you can try adjusting this to see the same behavior in a browser.

**Comment by z-master42** [comment]
Ah, I wasn't aware of that.

You're right, I tried it with the browser on my cell phone. It's the same as via the app. Only when I go into landscape mode is this entry also left-aligned.

I'll try my luck over there.
