### ISSUE TITLE
Unlock on home wifi doesn't work anymore

### ISSUE THREAD

**Issue by spudje** [home-assistant/android#4934]
**Home Assistant Android app version(s):**
2024.12.5-full

**Android version(s):**
15

**Device model(s):**
Google Pixel 8

**Home Assistant version:**
2024.12.5

**Last working Home Assistant release (if known):**
I think it still worked in the android app version 2024.11.x

**Description of problem, include YAML if issue is related to notifications:**

App asks for authentication (fingerprint) even though phone is on home wifi and Unlock on home wifi doesn't work anymore is enabled. Home wifi SSID is correctly set in the app. This used to work flawlessly.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by jpelgrom** [comment]
On the home network settings page, does it show a blue WiFi icon with checkmark next to your Wi-Fi name? Just tested it and it seems to work as expected for me.

**Comment by spudje** [comment]
Yes, it does. Come to think of it. it may actually be a Android 15 issue. I only recently updated to Android 15 as well. Do I (re)activate some permission?

**Comment by jpelgrom** [comment]
Also using a Pixel with Android 15 here, so that shouldn't be the issue. The icon with checkmark shows the app recognizes it is connected so I'm not sure why it isn't working. Do you have a list of steps to reproduce it, like specific screens or waiting for x time?

**Comment by spudje** [comment]
Maybe I need to enable a sensor? For some reasons all sensors were deactivated after an app update. I thought I re-enabled all relevant ones.

**Comment by dshokouhi** [comment]
Looks like another report of this on the forums 

https://community.home-assistant.io/t/companion-app-not-recognizing-home-wi-fi/816994

**Comment by jpelgrom** [comment]
Could you reproduce the issue and share the log from the app? It should include a couple of lines that point to why exactly it thinks it needs to lock.

> Maybe I need to enable a sensor?

No, this feature doesn't use sensors.

> Could my employer's intune app have disabled this?

Not as far as I'm aware.

**Comment by jpelgrom** [comment]
I've noticed a difference that may be relevant here - do you have an internal URL entered? If not, could you try filling it and see if that works (you can use the same value as Home Assistant URL)?

**Comment by spudje** [comment]
It works again.
