### ISSUE TITLE
[Light] Predefined color editor doesn't work

### ISSUE THREAD

**Issue by ESP4Ever** [home-assistant/android#4935]
**Home Assistant Android app version(s):**
2024.12.1-full

**Android version(s):**
13

**Device model(s):**
SM-T870

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
In edit mode the "-", "+" and "V" buttons have no effect.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
![Screenshot_20241226_172404_Home Assistant](https://github.com/user-attachments/assets/1387b3a8-ba28-48f6-b18e-0926c432f403)

**Additional information:**

**Comment by jpelgrom** [comment]
This screen is provided by the frontend. Please [create a frontend issue](https://github.com/home-assistant/frontend/issues) as this won't be unique to the app and will also happen in a browser.
