### ISSUE TITLE
Wifi has to be disabled to connect over 4g even when not connected to wifi.

### ISSUE THREAD

**Issue by Mechotronic** [home-assistant/android#510]
**Home Assistant Android version:**
1.8.0-144
**Android version:**
8.0.0 (3.18.71)
**Phone model:**
LG-H872
**Home Assistant version:**
0.106.5
**Last working Home Assistant release (if known):**
n/a
**Description of problem:**
When on a cellular connection, and with no wifi connected, wifi must be disabled to connect, otherwise the Retry prompt keeps appearing for a connection error. I can connect immediately after turning off wifi on the phone. 
**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![Screenshot_2020-03-10-10-50-18](https://user-images.githubusercontent.com/29634711/76326201-b2b90680-62be-11ea-9d41-f1700e7c4059.png)
![Screenshot_2020-03-10-10-50-05](https://user-images.githubusercontent.com/29634711/76326206-b482ca00-62be-11ea-9e3b-1b53b173bb62.png)

**Additional information:**

**Comment by Hataru80** [comment]
Same problem
