### ISSUE TITLE
Ambient noise volume level sensor

### ISSUE THREAD

**Issue by Hypfer** [home-assistant/android#512]
**Is your feature request related to a problem? Please describe.**
Nope. Just an enhancement

**Describe the solution you'd like**
Periodically poll the microphone and calculate the ambient noise dB.

**Describe alternatives you've considered, if any**
None

**Additional context**
It could be interesting to monitor noise pollution. The[ Apple Watch 4](https://support.apple.com/en-gb/guide/watch/apd00a43a9cb/watchos) does that and notifies you when you're in unhealthy environments for too long. I think HA could do even more with that information.

**Challenges**
- Not all phones are created equal. They all behave slightly different when it comes to sound sensitivity
- We'd need to check the impact on battery life (if any)

**Comment by hmmbob** [comment]
Polling my microphone? I trust HA for a lot, but I wouldn't like the app to do this from a privacy point of view. IF this is implemented, please make it optional and with explicit permissions before doing anything.

**Comment by Hypfer** [comment]
There's no reasonable way to access the microphone on android without explicit permission anyways. No need to be alarmed.
Generally speaking, you can (and are encouraged to) always look at the source to verify that there's nothing bad going on.

Anyways, I assume that this feature will probably require additional settings such as calibration offsets, intervals etc so I assumed that there would of course also be a switch to explicitly enable it.
