### ISSUE TITLE
Precision selection combo or Smart Precision feature

### ISSUE THREAD

**Issue by McGiverGim** [home-assistant/android#518]
**Is your feature request related to a problem? Please describe.**
The precision value taken for the tracking is very strict, so sometimes you abandon a zone and any automation related with this is not executed until a lot of time later because the new positions are discarded.
For example, I have a zone in the train station of Madrid. When my wife takes the train (and abandons the station) I have an automation. In my case it is not triggered until one hour later, when my wife gets to the destination station, at 200 Km of the origin station.
Maybe this is an edge case, with a High Speed train that can get to more than 300 Km/h, tunnels, the metal of the train, etc. but Google Maps is able to track her with fair good precision for at least be able to throw an automation when abandoning the zones.

**Describe the solution you'd like**
I think that a simply selection box with precision `ALL/LOW/MED/HIGH` to let the user select what he can use, with `HIGH` by default and maybe a warning if changed will be enough. 

If for some reason the project don't want to give this option to the users, maybe an implementation of a Smart Precision can be done. I don't know how much data we have in the app, but if we have enough, we can do something like that:

1. If the accuracy of the new location is smaller than the minimum accuracy defined, send the location, like now. This is the actual behaviour and does not change nothing.
2. If the accuracy of the new location is bigger than the minimum accuracy, then:
2.1. If the old location was inside a zone, and the new location is detected like away, then send the new location if the distance > (np_accuracy + z_radius)
![image](https://user-images.githubusercontent.com/2673520/76734598-90facc00-6763-11ea-85ff-be061ae06d54.png)

2.2. If the new location is inside a zone, and the old location was away or in a different zone, then send the new location if (distance + np_accuracy) < z_radius:
![image](https://user-images.githubusercontent.com/2673520/76734656-b38ce500-6763-11ea-9a08-9fd296f5cc34.png)

In this way, we only send the location when the new position is completely inside the new zone/away, including the accuracy. This give us more margin in the accuracy, especially when going from a zone to away, to detect correctly the change of state and start automations that now are being blocked by an accuracy too exigent. This will only be used when changing zone, while staying in the zone only the point 1 is used, like now, so the GPS coordinates will be the same than now the major part of the time. And can be an option "Smart zone detection" or similar deactivated by default.

**Describe alternatives you've considered, if any**
Only the two commented: a selection box in the config or a Smart Precision detection.

**Additional context**
None.

**Comment by balloob** [comment]
I don't like the idea of a new option, but I do like the idea of the advanced zone check.

**Comment by dshokouhi** [comment]
Is this still needed now that the user can define their own accuracy setting? They are able to set each sensor independently to give it better precision.

**Comment by McGiverGim** [comment]
No, I suppose that not. Closing...
