### ISSUE TITLE
Not rendering icons correctly placed with xpos/ypos

### ISSUE THREAD

**Issue by GreyEarl** [home-assistant/android#523]
**Home Assistant Android version:**
1.8.0-155

**Android version:**
Android 10 (March 2020) - Samsung

**Phone model:**
Samsung G970F

**Home Assistant version:**
 0.107.0

**Last working Home Assistant release (if known):**
Implemented on the current HA version for the first time

**Description of problem:**

The Android application is not rendering icons correctly that are placed with xpos and ypos layout. On mobile browsers like Chrome the icons are displayed correctly.

Using a [custom Lovelace card](https://github.com/AmoebeLabs/flex-horseshoe-card) for this. However, I don't know whether the card implementation is bad or the way HA app is rendering the HTML/CSS.

On Chrome in desktop mode (showing correctly):
![image](https://user-images.githubusercontent.com/33351068/77250968-d4fe3d00-6c4b-11ea-867e-0e4713d93137.png)

**Screenshot of problem:**

Home Assistant app:
![ha](https://user-images.githubusercontent.com/33351068/77251020-24dd0400-6c4c-11ea-8745-583806820894.jpg)

Chrome in Android:
![correct](https://user-images.githubusercontent.com/33351068/77251031-33c3b680-6c4c-11ea-9422-a4834a9b2e69.jpg)

**Comment by dshokouhi** [comment]
Does this issue in exist in other apps that use webview like kiosk browser or something?

**Comment by GreyEarl** [comment]
I tried Kiosk browser and the issue is there as well. So, it seems a Webview issue, nothing to do with Home Assistent, correct?

**Comment by dshokouhi** [comment]
Or could be a custom card issue? Did you try asking the author?
