### ISSUE TITLE
Navigation Bar doesn't match theme

### ISSUE THREAD

**Issue by hhromic** [home-assistant/android#524]
**Home Assistant Android version:**

1.8.0

**Android version:**

Android 9.0

**Phone model:**

Samsung Galaxy A70

**Home Assistant version:**

1.107.4

**Last working Home Assistant release (if known):**

Never saw this working properly before.

**Description of problem:**

The background color of the Navigation Bar (where the "back", "home", "menu" virtual buttons are) does not match the current theme being used in the Home Assistant UI. See screenshots attached.

**Traceback (if applicable):**

```
N/A
```

**Screenshot of problem:**

Even though I am using the Google Dark Theme, the Navigation Bar remains light-themed and thus doesn't look well integrated with the rest:

<img src="https://user-images.githubusercontent.com/5802993/77252720-b305ba00-6c4d-11ea-8937-07cbe7f097b1.png" width="240px">

Other applications do work as expected and they seem to use the dominant background color to set the color of the Navigation Bar. For example:

Google Calendar (dark gray color):

<img src="https://user-images.githubusercontent.com/5802993/77252775-1a236e80-6c4e-11ea-8b2f-74b4b96e3fd3.png" width="240px">

Phone Dialer (fully black color):

<img src="https://user-images.githubusercontent.com/5802993/77252783-20b1e600-6c4e-11ea-8cae-69243124fcb4.png" width="240px">

**Additional information:**

Maybe related to #272 , where a similar problem was reported for the Status Bar.

**Comment by dshokouhi** [comment]
Do you get the expected results when you use the service call `frontend.set_theme` ?  I don't know if the navigation bar is part of the theme here but the status bar is and it matches the default selected theme only for now.

**Comment by hhromic** [comment]
Thanks for replying!

I just tested now calling `frontend.set_theme()` and indeed the *Status Bar* (on top) changes to a dark gray color (matching the dark theme I have) after closing and re-opening the app:

<img src="https://user-images.githubusercontent.com/5802993/77263416-42cc5800-6c90-11ea-96d7-86cd255191df.png" width="240px">

However the *Navigation Bar* remains unaffected. I think whatever is being done to the Status Bar should be applied as well to the Navigation Bar and all should look fine.

Let me know if you need me to do further tests.

**Comment by hhromic** [comment]
I was checking the Status Bar color pull-request (#268) and perhaps just adding:

```kotlin
window.navigationBarColor = color
```

to:

https://github.com/home-assistant/home-assistant-android/blob/f6618527d4f5f1233e7e0515f9816eb3ac282e5b/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L392-L394

might help with this issue?

Ref: https://developer.android.com/reference/android/view/Window.html#setNavigationBarColor(int)

**Comment by balloob** [comment]
@dshokouhi the poster is talking about the navigation bar (buttons at the bottom) and not the status bar (which was also incorrect in his screenshot).

This is not a feature that is currently implemented, so it's an enhancement, not a bug.

**Comment by bachoo786** [comment]
> Do you get the expected results when you use the service call `frontend.set_theme` ? I don't know if the navigation bar is part of the theme here but the status bar is and it matches the default selected theme only for now.

I tried that but my navigation bar is messed in the HA Android app. I can't read the time. See image below.
![Screenshot_20200326-180437_Home Assistant](https://user-images.githubusercontent.com/6251030/77680736-46abf300-6f8c-11ea-840b-a5d913f83ee3.jpg)
