### ISSUE TITLE
Better error message when Home Assistant instance has expired SSL Cert

### ISSUE THREAD

**Issue by khoberg** [home-assistant/android#528]
**Is your feature request related to a problem? Please describe.**
Home Assistant Android doesn't give a good error message when the Home Assistant instance it's connecting to has an invalid SSL certificate. It gives a generic 'Unable to connect to home assistant' message, which didn't help trace back the cause of that. It was also opening a browser to the login page which was working fine in my default browser and I was able to log in. My default browser must have cached things or didn't recheck date on cert. I finally figured out the issue when switching my default browser on Android and seeing the cert issue.

It also got into a state when I hit refresh and it opened the browser where if I went back to the app, it would get stuck refreshing forever (didn't actually wait for a timeout, so might have been one) with no way to cancel other than killing the app and reopening

**Describe the solution you'd like**
Have a clearer error message for why connection failed to help troubleshoot the issue.

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
Fixed in #637
