### ISSUE TITLE
Webpage Card Javascript: calling URL (Node Red Enpoint) no response

### ISSUE THREAD

**Issue by SVNKoch** [home-assistant/android#533]
**Home Assistant Android version:**
1.8.0-144
**Android version:**
8.1.0
**Phone model:**
Oneplus 5T
**Home Assistant version:**
HassOS 3.12 (Supervisor Version 209)
**Last working Home Assistant release (if known):**
-
**(Node Red Version):**
6.1.3
**Description of problem:**
Embadding a local webpage which uses javascript to call an endpoint on Node Red not working on Android but in Browser (on mobile and PC). This is not because it can't change the page, as I've tried another locale file to display and an external one as well. Below you can find resources to reproduce the issue.
In the android app nothing happens when clicking the button.
**Traceback (if applicable):**

```

```

**Screenshot of problem:**
Response on PC Lovelace:
![grafik](https://user-images.githubusercontent.com/39488412/77827698-79362700-7117-11ea-93a6-925cdedefa63.png)
Response on calling End Point directly on PC Browser: 
![grafik](https://user-images.githubusercontent.com/39488412/77827708-881cd980-7117-11ea-9c35-9f9df1fbd798.png)
In the android app nothing happens when clicking the button.

**Additional information:**
Reproduce:
two html files in the www folder
this one gets displayed in the Webpage Card: (change IP and credentials for node red)
```
<!DOCTYPE html>
<html>
    <body>

    <input type="button" value="Test" onclick="test()">
    <input type="button" value="Example" onclick="example()">
    <input type="button" value="Light" onclick="light()">

    <script>
        function test() {window.location = 'http://IP:8123/local/localtest.html';}
        function example() {window.location = 'https://example.org/';}
        function light() {window.location = 'http://user:password@IP:1880/endpoint/notify';}
        </script>
    </body>
</html>
```
a page to test that local pages work "localtest.html":
```
<!DOCTYPE html>
<html>
    <body>
        <h1>Local Pages do work</h1>
    </body>
</html>
```
and finally in Node Red the Endpoint:
![grafik](https://user-images.githubusercontent.com/39488412/77827617-fe6d0c00-7116-11ea-93e3-0432f40c3315.png)

> [{"id":"d97365bb.9fa0b","type":"http in","z":"15700980.19085f","name":"","url":"/notify","method":"get","upload":false,"swaggerDoc":"","x":504,"y":943,"wires":[["56cbb333.d2cadc","847d82b5.bb3c9","35c41bf3.2bf40c"]]},{"id":"847d82b5.bb3c9","type":"http response","z":"15700980.19085f","name":"response code","statusCode":"200","headers":{},"x":793,"y":989,"wires":[]},{"id":"35c41bf3.2bf40c","type":"debug","z":"15700980.19085f","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":763,"y":943,"wires":[]}]

Expected behaviour:
clicking the button redirects to a page with the following content: {} and the End Point gets triggered.

**Comment by dshokouhi** [comment]
Could this be an issue with mixed content? Are you using the app in `https` and the URLs are in `http? That could be the cause of this as there is no mixed content in the android app currently.  Not sure if this is currently an issue with the android app since the latest release.
