### ISSUE TITLE
Rotating the screen at Login screen crashes the App 

### ISSUE THREAD

**Issue by uxdesignerhector** [home-assistant/android#537]
**Home Assistant Android version:** 1.8.0.-157

**Android version:** 9

**Phone model:** Mi A1

**Home Assistant version:** 0.107.5

**Last working Home Assistant release (if known):**

**Description of problem:**
Rotating the phone crashes the App at the login screen. The screen freezes and shows initial screen text strings above the login screen.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
Gif:
![bug](https://user-images.githubusercontent.com/48013939/78123943-4178f900-740f-11ea-91a1-3be509bb1a2f.gif)

Screenshot:
![crashing](https://user-images.githubusercontent.com/48013939/78124259-b815f680-740f-11ea-921d-01cd9a3a5d93.png)

**Additional information:** I'm accessing to home-assistant locally.

**Comment by JBassett** [comment]
Fixed in https://github.com/home-assistant/android/pull/636
