### ISSUE TITLE
Higher DPI splash screen/icon

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [home-assistant/android#540]
**Is your feature request related to a problem? Please describe.**

Hello!

Currently after we start HA application there is a loader/splash screen for some sec before the real PWA loads into the webview _(I just think that this is the working method but not sure in it yet.)_. That image is a HA icon, nothing more. On xyzHDPI devices that image is a little bit blurry seems far from the native pixel density of the device. _(I'm using with my Galaxy S8.)_

**Describe the solution you'd like**

Could it be possible to use higher resolution image for it, or use multiple images for multiple pixel density?

Thanks for your answer!

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by JBassett** [comment]
We don't have a splash screen for the application.  What you are seeing is the the PWA loading.  This might be a frontend issue not an app issue?

**Comment by Tamas-Toth-ebola** [comment]
Really!!! Thanks for the clarification! I have verified and saw that on web, the PWA really uses a loader screen with that HA icon, what is - usually - on mobile devices is not enough high DPI. Will check it some hours later on my other small but 4k monitor just to check how much could this be annoying on desktop in real life but the result obviously what you told.

In this case should I report it into the HA frontend?

**Comment by dshokouhi** [comment]
Closing as this is a frontend issue and should be reported there if it is still an issue.
