### ISSUE TITLE
App in background keeps unused websocket connection open

### ISSUE THREAD

**Issue by balloob** [home-assistant/android#542]
From https://github.com/home-assistant/frontend/issues/5328#issuecomment-607906917

**Home Assistant Android version:** 1.8

**Android version:**

**Phone model:** all?

**Home Assistant version:** 0.108

**Last working Home Assistant release (if known):** -

**Description of problem:**

It looks like when the app is going in the background, the websocket connection of the frontend remains open, but we no longer execute JavaScript to read the messages. This results in warnings in the backend because there are more than 512 pending messages.

If possible, on suspend, we should close the websocket connection and restore it when we're visible again.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by electrofloat** [comment]
That is exactly the same thing that is happening when using not the app but Chrome android "add to homescreen" (webapp) feature.

**Comment by dshokouhi** [comment]
Would this be fixed by 0.112?

**Comment by balloob** [comment]
Yep!
