### ISSUE TITLE
Notification lost if the phone is off-line

### ISSUE THREAD

**Issue by mario-tux** [home-assistant/android#553]
**Home Assistant Android version:** 1.8.0-144

**Android version:** 8.0.0

**Phone model:** Samsung S7

**Home Assistant version:** 0.108.4

**Last working Home Assistant release (if known):**

**Description of problem:** I get the notification on my phone only if it is on-line and connected; if I trigger it from HA when it is off-line (plane mode), even if I switch it on after few seconds, the notification is lost. The param `ttl` didn't change the behavior: I've tried 0, 60000, nothing.... 

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Can you please share the notification service data that you used?

**Comment by mario-tux** [comment]
Sorry, today I can't reproduce the problem. I'm going to close this. I will open another report if I fase again a more reproducible issue. Thanks for the prompt reply.
