### ISSUE TITLE
Lock screen does not appear when the app is resumed from background

### ISSUE THREAD

**Issue by sjvc** [home-assistant/android#555]
**Home Assistant Android version:**
1.8.0-159
**Android version:**
10
**Phone model:**
Pixel 2 XL
**Home Assistant version:**
0.108.4
**Last working Home Assistant release (if known):**

**Description of problem:**
Lock screen does not appear when the app is resumed from background. It only appears if the app has been closed using back button.

**Traceback (if applicable):**
- Open the app (lock screen appears)
- Unlock using your finger
- After it's unlocked, press device home button
- Open the app again
- Now lock screen does not appear

**Screenshot of problem:**

**Additional information:**
Also, as a suggestion, it would be great if no button needs to be touched to show the fingerprint reader. If the fingerprint reader is shown immediately it's faster to use.

**Comment by dshokouhi** [comment]
Maybe a good idea is to put a programmable timeout for when the lock screen should appear.

**Comment by sjvc** [comment]
> Maybe a good idea is to put a programmable timeout for when the lock screen should appear.

Before this app I was using my own (https://github.com/sjvc/Home-Assistant-Launcher). I set a timeout of 10 seconds, and I was very happy with it. But I think it would be better if it's programmable like you said. Perfect!
