### ISSUE TITLE
Mobile Alarm Sensor

### ISSUE THREAD

**Issue by Nossnevs** [home-assistant/android#56]
The mobile alarm time would be a great to have in home assistant! This works in other apps so should be possible for this app also.

**Comment by tiagofreire-pt** [comment]
For example, on Samsung native alarm app, the broadcast intents are:

com.samsung.sec.android.clockpackage.alarm.ALARM_STOPPED_IN_ALERT
com.samsung.sec.android.clockpackage.alarm.ALARM_ALERT

**Comment by martijnvdwoude** [comment]
I've been testing this in a small stand-alone app to do exactly this and it works great.

On many phones you could use the `android.app.action.NEXT_ALARM_CLOCK_CHANGED` intent. In `onReceive` of the `BroadcastReceiver` you can then get the `nextAlarmClock` from the `AlarmManager`.

On Home Assistant's side I have added a `input_datetime`:
```
android_alarm:
  name: Android alarm
  has_date: true
  has_time: true
```
Request body of the POST to `/api/services/input_datetime/set_datetime` would be like:
```
{
    "entity_id": "input_datetime.android_alarm",
    "datetime": "2019-12-01 08:00:00"
}
```

Then you can use a trigger for automations like:
```
value_template: "{{ states('sensor.date_time') == ( states.input_datetime.android_alarm.attributes.timestamp | int - 900 ) | timestamp_custom('%Y-%m-%d, %H:%M', True) }}" # Trigger 15 minutes before android alarm datetime
```

This works really well, the intent gets fired whenever the next alarm changes. This includes the moment an alarm goes off, but also when alarms get disabled.

**Comment by Knoxie** [comment]
Does this work with Google home alarms?

I'd love to run an automation when my Google home alarm is turned off

**Comment by balloob** [comment]
@martijnvdwoude we wouldn't hack it together with set state. The alarms should be exposes as a sensor via mobile_app with the timestamp device class.

**Comment by martijnvdwoude** [comment]
@balloob Ah, yes much better. I just checked this repo out today, have just been digging through the code this afternoon. Might take a stab at it though!

**Comment by eifinger** [comment]
As another reference @Johboh implemented a standalone app for this some while ago: https://github.com/Johboh/hassalarm
