### ISSUE TITLE
Android widget light_turn off

### ISSUE THREAD

**Issue by samprass** [home-assistant/android#563]
Hi, setting a widget with home assistant app for Android  version 1.8.0-144. When choosing light_turn off and selecting the all entity it seems to have a comma and white after it. With this the widget doesn't work, removing the comma and white space the widget works as expected.
Hopefully someone with more talent than myself can fix this issue.

Thanks in advance

**Comment by hhromic** [comment]
Can confirm this too on my side :+1:
