### ISSUE TITLE
Use MDI Icons for Widgets

### ISSUE THREAD

**Issue by timmo001** [home-assistant/android#564]
**Describe the solution you'd like**

Triggered by #562 

It would be nice to have the icons from the [Material Design Icons](https://materialdesignicons.com/) as we use in the frontend available for the widget and other places icons can be used.

**Additional context**

Docs for android: https://dev.materialdesignicons.com/getting-started/android

**Comment by ttaidapos** [comment]
This is huge!  Yes please :)

**Comment by Anleifr** [comment]
Was looking if I could use any other MDI icon for my widgets than the four or five that are available... ended up here, so guessing this is not implemented yet. Would bee very nice indeed. :)

**Comment by pandemixxx** [comment]
I can confirm this. Added mdi icons to entities, but wear os app didn't sync. Reinstalled the app on the watch, but having the same outcome.
