### ISSUE TITLE
Registration allows setting of Device Name

### ISSUE THREAD

**Issue by Nik71git** [home-assistant/android#568]
**Home Assistant Android version:** 1.8.0-144

**Android version:** 9 PKQ1.180904.001

**Phone model:** Xiaomi Redmi Note 5

**Home Assistant version:** 0.108.9

**Last working Home Assistant release (if known):**

**Description of problem:**Hello. still, with app android release 1.8.0-144 and Home Assistant release 0.108.9, is necessary to rename device whenever you logout from app and login again. People like me and my family who own two or more identical devices (Xiaomi Redmi note 5) need to do that otherwyse automations, script and tracking not working fine anymore since you rename in different ways every device and restart HA. Logout is a security issue since in case of stolen device it has login already done and can take control of devices such alarm and gate opening. The problem is the app and not HA in my humble opinion, it would be nice if device are registered by their integrations not by name but by mac address for instance...

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
@Nik71git in the android app under app configuration there is a lock option which will require either fingerprint, face unlock or pin/password.  I think this will solve your issue of having to log out each time right?

**Comment by rradar** [comment]
This title is the best :100:

**Comment by Nik71git** [comment]
> This title is the best 💯

Too long? ;-)

**Comment by dshokouhi** [comment]
Closing as duplicate of #385
