### ISSUE TITLE
Release APK

### ISSUE THREAD

**Issue by rradar** [home-assistant/android#570]
**Is your feature request related to a problem? Please describe.**
I run a FOSS OS on my phone and don't use any big brother services which includes the play store

**Describe the solution you'd like**
A apk can be released for all who like to try/use the app but don't have a contract with google

**Describe alternatives you've considered, if any**
As already requested a couple of times it can('t) be included to F-Droid #42 #124 #532 

**Additional context**

**Comment by balloob** [comment]
Duplicate
