### ISSUE TITLE
Multiple server support

### ISSUE THREAD

**Issue by deece** [home-assistant/android#571]
**Is your feature request related to a problem? Please describe.**
I maintain 5 Home Assistant Instances (across separate properties). Once I've added 1 instance to the app, I cannot add the other instances.

**Describe the solution you'd like**
The ability to connect the app to multiple Home Assistant Instances, and a quick way (maybe even automatic based on SSID or location) to swap between instances.

**Describe alternatives you've considered, if any**
Currently using multiple web UI shortcuts.

**Additional context**

**Comment by allanpersson** [comment]
Duplicate of #296 and #565
