### ISSUE TITLE
Location tracking communication

### ISSUE THREAD

**Issue by fineemb** [home-assistant/android#572]
**Is your feature request related to a problem? Please describe.**
Judging from the current usage, location tracking will communicate with third-party servers. This is not very friendly to me

**Describe the solution you'd like**
Can it be similar to GPS Logger,
HASS and application direct communication

**Comment by andriej** [comment]
Isn't it issue with geotracking? If you disable entity, it shouldn't.

**Comment by dshokouhi** [comment]
@fineemb where did you pick up that the app sends location data to a third party?  The app only uses a HA provided FCM server to send notifications.  All other communication is sent directly to HA.  FCM requires use of a server.

more details on notifications here: https://companion.home-assistant.io/docs/notifications/notification-details

fcm server code here: https://github.com/home-assistant/mobile-apps-fcm-push

**Comment by andriej** [comment]
@dshokouhi I assume it has to convert lat and long data to 'address' somewhere in between. Is it also managed via FCM or it's done by HA?

**Comment by dshokouhi** [comment]
@andriej its an internal android API for geocoded location: https://developer.android.com/reference/android/location/Geocoder

Whatever the phone sends to us we return that to your HA instance.

The heart of the logic I believe is right here: https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt

I think google maps uses the same API?

**Comment by balloob** [comment]
Yep. all provided by Android.
