### ISSUE TITLE
Geocoded location is sent even though "background location updates" are off

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/android#573]
**Home Assistant Android version:**
Latest non-beta
**Android version:**
9
**Phone model:**
Moto G8 Plus
**Home Assistant version:**
0.109.1
**Last working Home Assistant release (if known):**
unk
**Description of problem:**
Home Assistant does show the sensor.moto_g_8_plus_geocoded_location with accurate location away from home, even though the app is set up to not do background location updates
**Traceback (if applicable):**
n/a

**Screenshot of problem:**
n/a
**Additional information:**
Background location updates are off, but zone based tracking is on. Just one zone set (home zone). The built-in Home Assistant map will show the approximate location where the device left the zone and will keep "hanging" at that location until the device returns into the zone (this tells me the device_tracker entity isn't updated - which appears as correct behaviour.)

The sensor.moto_g_8_plus_geocoded_location however will be populated regularly with accurate information, which is unexpected behavior.

Unless https://github.com/home-assistant/android/pull/516 didn't make it to the non-beta app yet, this is unresolved.

**Comment by dshokouhi** [comment]
@hmmbob it did not make it to public version, still in beta. Last public release was in February, please update to the beta or wait for the next release.  There is no set date for next release.
