### ISSUE TITLE
Norwegian language/translation for Companion app

### ISSUE THREAD

**Issue by hulkhaugen** [home-assistant/android#580]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Add the Norwegian language (nb-NO) for translation at Lokalise

**Describe alternatives you've considered, if any**

N/A

**Additional context**

Should be pretty straight forward.

**Comment by JBassett** [comment]
Added and you should have access now.

**Comment by hulkhaugen** [comment]
Has there been any change to this? I can't seem to find it anymore.

**Comment by JBassett** [comment]
> Has there been any change to this? I can't seem to find it anymore.

@hulkhaugen there were duplicate languages in Lokalise, you have been added to Norwegian again.
