### ISSUE TITLE
Error (Red Card) for custom cards

### ISSUE THREAD

**Issue by theone11** [home-assistant/android#581]
**Home Assistant Android version:**
1.8.0-144 (latest)

**Android version:**
various  - see phone models below

**Phone model:**
PIPO P1 tablet - 7.1.2
Teclast 98 tablet - 6
OnePlus 5T - 9

**Home Assistant version:**
0.109.4 (latest)

**Last working Home Assistant release (if known):**

**Description of problem:**
On my PIPO P1 tablet I get red card - ERROR "custom element doesn't exist - <element name>"  for **all** custom cards/elements I use (different kinds).
When browsing HA through chrome browser (latest version) on the same tablet all looks OK - custom cards/elements appear as they should.

On my Teclast and Oneplus devices all is working OK both with app and with browser.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/3348953/81062934-9365e080-8edf-11ea-90ce-cd30ca3b99ec.png)
![image](https://user-images.githubusercontent.com/3348953/81062946-9a8cee80-8edf-11ea-8579-2c7da3639933.png)
![image](https://user-images.githubusercontent.com/3348953/81062988-ab3d6480-8edf-11ea-943c-620892f9ef8d.png)
![image](https://user-images.githubusercontent.com/3348953/81063064-d7f17c00-8edf-11ea-8268-97aa7a749660.png)

**Additional information:**

**Comment by dshokouhi** [comment]
@theone11 can you check on that device if the app Android System Webview is up to date?

**Comment by theone11** [comment]
@dshokouhi It was not installed so I installed restarted tablet but still **not working**.

On my other tablet it was already installed (working) and on my OnePlus 5T it is installed but shown as disabled (also working).

**Comment by balloob** [comment]
This is a problem with your Android device. We use the installed webview which is automatically kept up to date by Google. If your device doesn't use it / doesn't keep it up to date, there is nothing we can do.
