### ISSUE TITLE
Make Geolocation Opt-In

### ISSUE THREAD

**Issue by tinloaf** [home-assistant/android#582]
**Home Assistant Android version:**
1.8.0-144

**Android version:**
10 (Recent LineageOS)

**Phone model:**
Xiaomi Mi 8

**Home Assistant version:**
0.109.3

**Last working Home Assistant release (if known):**
n/a

**Description of problem:**
The fact that the app continually (reverse-) geocodes the current GPS location means that my location is permanently being sent to Google Maps. This is something that (in my opinion) an app should not do without at least informing me about it, in fact I think this should be an opt-in option. At the very least, there should be a way of disabling it (opt-out).

I realize I can just revoke the location permission (which I have just done), but now my automations related to zones don't work anymore. 

I could imagine that a considerable part of HA's user base is quite privacy-conscious and would be as surprised as I was to learn that their location is permanently being sent to Google.

**Traceback (if applicable):**
n/a

**Screenshot of problem:**
n/a

**Additional information:**
n/a

**Comment by andriej** [comment]
I'm also keen more on opt-in rather than default opt-out policy, even tho all localisation messages are going thru google servers anyway ;-)

**Comment by tinloaf** [comment]
No, they are not. I've just had that very same discussion twice on Discord. You can turn off your "location history" and Google's Wifi-assisted GPS localization. That way, no GPS locations should be disclosed to Google (or anybody else, for that matter). It's kind of weird that even Google offers the option to not send GPS locations to themselves, but the HA app has a mandatory GPS-to-Google-sending thing.

**Comment by Troon** [comment]
I'll vote for this one too. The `geocoded_location` isn't particularly accurate or useful in my experience, and I'd appreciate being able to turn it off.

**Comment by nagyrobi** [comment]
+1 for this

**Comment by skylarmt** [comment]
> It's kind of weird that even Google offers the option to not send GPS locations to Google, but the HA app has a mandatory GPS-to-Google-sending thing.

Not actually weird or surprising, considering HA is refusing to support phones without Google services, even when offered payment to do so. See also issues #42, #124, and #676.
