### ISSUE TITLE
app hangs on opening

### ISSUE THREAD

**Issue by Xilvaro** [home-assistant/android#585]
I've restarted and updates everything. And it doesn't matter if I'm on my wifi or 4G the app kind of hangs when opening. And some actions it also hangs. I'm running the latest version of HA. The latest version of Android on my Oneplus 7T and version 1.80.-165 of the app. 

I've added a screenshot :)

**Comment by Xilvaro** [comment]
![Screenshot_20200508-212526](https://user-images.githubusercontent.com/51399385/81441747-9af0e800-9172-11ea-90cb-46f06af48939.jpg)

**Comment by dshokouhi** [comment]
Can you try to start fresh with the app and see if it works properly?  

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by klejejs** [comment]
I sometimes have the same issue, but I have noticed that it is because of slow server, and it is not related to the app, nor the internet connection.

**Comment by Xilvaro** [comment]
Strange enough the issue resolved itself. 

After some reboots and fiddling with NodeRED (in docker, not the add-on) it just seems to work like normal again. 

Anyway, I want to thank you guys for the quick responses!
