### ISSUE TITLE
Allow multiple Home Network WiFi SSIDs

### ISSUE THREAD

**Issue by jsg91** [home-assistant/android#586]
**Is your feature request related to a problem? Please describe.**
Some family members use the 5Ghz Wifi and others the 2.4. I'd like to be able to enter both home SSIDs and then does not matter to which one the device is connected, it sill uses the internal URL

**Describe the solution you'd like**
Allow entering multiple WiFi SSIDs

**Describe alternatives you've considered, if any**
Take care to which the device is connected and when changed, change it in the HA Android App

**Additional context**

**Comment by allanpersson** [comment]
See https://github.com/home-assistant/android/pull/485
Will for my understanding be available in next release of the android app (in a few days maybe) 🙏

**Comment by jsg91** [comment]
Whoops just checked the open feature and pull requests :) Thanks @Timmmeeeh
