### ISSUE TITLE
Biometrics Visual & Accessibility improvements

### ISSUE THREAD

**Issue by ncodee** [home-assistant/android#587]
Regarding the recent stable update (1.9.0-167), It's great that this has been implemented, but can we get something more subtle, the splash screen is quite obnoxious to look at.

Also, I don't understand why it requires a 2nd tap to initiate the biometrics. 

It should be prompted upon opening the app, and not require a secondary action by the user.

Many thanks

**Comment by sysr-q** [comment]
I agree, it would be nice to just have it automatically initiate biometric unlock when you open the app. This would be inline with all but one of the online banking apps I have on Android.

Open the app, get presented with the fingerprint unlock screen, with cancel button to just look at the lock screen. Some of the bank apps also let you see some information from the lock screen without unlocking, it would be nice to potentially display a certain Lovelace panel (read-only) before the app unlocks and loads.
