### ISSUE TITLE
New Version does not connect

### ISSUE THREAD

**Issue by angeltonio** [home-assistant/android#588]
Error: invalid client id or redirect uri, does not show me the login window

**Comment by dshokouhi** [comment]
Please don't delete the issue template all requested information is important to help you out. Was the app working for you before the update? Did you try: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by angeltonio** [comment]
It´s working now..I need Internet to that..you can closed this issue....thanks
