### ISSUE TITLE
Websites requesting access to the device camera are denied without prompt

### ISSUE THREAD

**Issue by KieranDrain** [home-assistant/android#596]
**Home Assistant Android version:**
1.9.0-167

**Android version:**
Lineage OS 17.1  (Android 10)

**Phone model:**
OnePlus 3T

**Home Assistant version:**
0.109.6

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**

When accessing a website (via a Lovelace website card) which needs access to the device cameras an access denied error is thrown (screenshot attached). when accessing the same lovelace card via the web browser a prompt is seen to confirm the camera to be used and it works.

The following site can be used to reproduce the issue:
https://davidwalsh.name/demo/camera.php

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

Example of a failure message for one application.
![Example-Failure](https://user-images.githubusercontent.com/7551657/82129127-6d322180-97b8-11ea-87f9-2ce649f59306.png)

Example of a successful attempt via the browser
![Example-Success-via-browser](https://user-images.githubusercontent.com/7551657/82129128-6e634e80-97b8-11ea-9263-ea3068763ca7.png)

**Additional information:**

Most applications just get denied access to the camera and show nothing. The Grocy app in the first screenshot provdes more info to confirm access to the camera was denied.

**Comment by dshokouhi** [comment]
Is this still an issue in the latest release that just went out? Looking at the code we should be prompting for camera permissions when needed.

**Comment by KieranDrain** [comment]
I'm not sure if this is resolved however I do not use grocy anymore to test. I suspect the issue is still there as now the test web page i tried before does not work at all and does not prompt. There are too many variables I'm unable to test to effectively support troubleshooting this further.
