### ISSUE TITLE
White box appears when keyboard is displayed

### ISSUE THREAD

**Issue by engrbm87** [home-assistant/android#597]
**Home Assistant Android version:**
1.9.0-167
**Android version:**
10
**Phone model:**
OnePlus 6T
**Home Assistant version:**
0.110.0b4
**Last working Home Assistant release (if known):**
0.109
**Description of problem:**
A White box appears when the keyboard is displayed to enter a value in any field.
**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![Screenshot_20200514-203815](https://user-images.githubusercontent.com/5123967/82295083-dd5ac600-99b7-11ea-949a-4fad3642e8db.jpg)

**Additional information:**

**Comment by engrbm87** [comment]
This issue is still showing with the latest version of HA 0.110
Please fix it.

**Comment by dshokouhi** [comment]
If its an issue with full screen enabled I would say its worth it to check it out.

**Comment by barrymossel** [comment]
Experiencing the same. Only in fullscreen mode. Don't know any other apps to test if it's Android related or HA app related.

**Comment by Eeeeeediot** [comment]
This happens on a Samsung S20 Ultra in full screen mode too. The S20 doesn't have a notch - it has a hole-punch camera.

**Comment by neopilou** [comment]
Don't worry, notch or hole-punch is a screen cutout.

**Comment by JBassett** [comment]
Fixed via: https://github.com/home-assistant/android/pull/613
