### ISSUE TITLE
Widget enhancements

### ISSUE THREAD

**Issue by WedHumpDay** [home-assistant/android#598]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
**Widgets are large with white backgrounds by default and do not take phones theme. Would be great if widgets could have a black or transparent background matching themes.**

**Describe alternatives you've considered, if any**

**Additional context**
![image](https://user-images.githubusercontent.com/36989651/82356086-bfe22800-99c8-11ea-8ba5-f76d9b48619b.png)

**Comment by JBassett** [comment]
Fixed in https://github.com/home-assistant/android/pull/749
