### ISSUE TITLE
Add check for google services

### ISSUE THREAD

**Issue by rradar** [home-assistant/android#600]
**Is your feature request related to a problem? Please describe.**
#231 #358 #412 #599 ... and more to come

**Describe the solution you'd like**
Check for existing google services on the device. If none found show a proper message that this app requires google services and give a information that the last working build of this app for free(d) devices is v1.6

Even better solution provided by @jleeuwes [here](https://github.com/home-assistant/android/issues/231#issuecomment-583729339
) would be to have the error message appearing but the **app still running** with all the functionalities but only stripped from the few (push notification* and ?) which are require the google services.

*Actually even this could be managed. [Signal](https://signal.org/en/) for example uses a automatic fall back for notifications if no google services are available.

**Describe alternatives you've considered, if any**
I installed [HA Client](https://github.com/estevez-dev/ha_client) on the same phone and it works without google on my phone.

**Additional context**
Right now a **not very specific** error message is shown when trying to use this app on a google free phone:
![image](https://user-images.githubusercontent.com/34582688/82384693-4aa63f80-9a28-11ea-897e-a45cd181a91c.png)

**Comment by jleeuwes** [comment]
I created a low-effort fork https://github.com/jleeuwes/home-assistant-android-without-google in which I just take a stable version from time to time and rip out all Google Play / FCM related code. I use it on my LineageOS phone. The ripping-out commits like https://github.com/jleeuwes/home-assistant-android-without-google/commit/246a42ff6efd2d9fa0a2241ebc3fd970ca73a0b1 might be helpful when implementing this issue.

**Comment by balloob** [comment]
This is the third time you have opened an issue @rradar. You even link to old issues. You do not respect us and our time. You can do with your time what you want, but you won't be able to spam us anymore as I have just blocked you.
