### ISSUE TITLE
Android : Invalid client ID or redirect URI

### ISSUE THREAD

**Issue by aaruni96** [home-assistant/android#601]
**Home Assistant Android version:** : 1.9.0-167

**Android version:** 10

**Phone model:** Motorola Moto G6 

**Home Assistant version:** 0.110.2

**Last working Home Assistant release (if known):** Dont remember

**Description of problem:** Unable to login from the mobile app. Gives the error `invalid client ID or redirect uri`

**Traceback (if applicable):**

```
2020-05-25 09:52:55 ERROR (MainThread) [homeassistant.components.auth.indieauth] Timeout while looking up redirect_uri https://home-assistant.io/android
2020-05-25 09:52:55 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 127.0.0.1
```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/7453256/82791177-96fcdf80-9e6d-11ea-9aa2-1d1f60385818.png)

**Additional information:**
Problem confirmed with RevengeOS+opengapps / android-studio virtual device / Android 9 + stock google service.

**Comment by dshokouhi** [comment]
Closed by https://github.com/home-assistant/core/pull/36131 please update HA to 0.110.3
