### ISSUE TITLE
Overwrite previous notification, e.g. at most one notification visible

### ISSUE THREAD

**Issue by odin-** [home-assistant/android#604]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Overwrite previous notification, e.g. at most one notification visible

**Describe alternatives you've considered, if any**
N/A

**Additional context**
No.

**Comment by escoand** [comment]
Maybe this is what you're looking for: https://companion.home-assistant.io/docs/notifications/notifications-basic/#replacing-notifications

**Comment by dshokouhi** [comment]
Thank you @escoand ! This feature does indeed exist just need to make sure you send the same `tag` as described in the linked docs.  Unless I misunderstood this closing as its already there :)
