### ISSUE TITLE
Swipe gesture to navigate between tabs on lovelace dashboard(s)

### ISSUE THREAD

**Issue by aicarmic** [home-assistant/android#607]
**Is your feature request related to a problem? Please describe.**
On mobile, depending on your setup a user's navigation likely includes switching between your tab views often. This currently requires reaching your thumb to the top of the screen.

**Describe the solution you'd like**
Add support for horizontal swiping across the screen to navigate between lovelace dashboard tabs. It would be a really elegant and a nice alternative to do this via gestures, which feel more natural on mobile:
![tab-nav](https://user-images.githubusercontent.com/1105554/83695623-aa1f5600-a5b7-11ea-9dbf-696b2874e5f1.gif)

**Describe alternatives you've considered, if any**
None that come to mind.

**Additional context**
Navigation gestures are a common trend/theme coming to Android 10 and many apps, as explained here: https://www.youtube.com/watch?v=Ljtz7T8R_Hk

Thanks for your consideration!

**Comment by balloob** [comment]
https://github.com/home-assistant/android/issues?q=is%3Aissue+sort%3Aupdated-desc+swipe+is%3Aclosed

**Comment by aicarmic** [comment]
whoops. sorry @balloob for the dup, I searched for "swipe" before filing, but must have left `is:open` in my search filter. stfn...
