### ISSUE TITLE
Back button should behave like the back button 

### ISSUE THREAD

**Issue by brettp** [home-assistant/android#608]
**Home Assistant Android version:** 
Latest released as of this report. 

**Android version:**
Latest released as of this report. 

**Phone model:**
Pixel 3

**Home Assistant version:**
Latest released as of this report. 

**Last working Home Assistant release (if known):**
Never. 

**Description of problem:**
The back button in the Android app should go back a screen instead of closing the app. This is standard and expected behavior for Android. 

**Traceback (if applicable):**
None. 
```

```

**Screenshot of problem:**
None.

**Additional information:**
None.

**Comment by dshokouhi** [comment]
Similar to #338  this may very well be a front end issue here too.  Do you see the same behavior in chrome?

**Comment by balloob** [comment]
This is a frontend issue.
