### ISSUE TITLE
Screen does not go to sleep if you have video stream showing

### ISSUE THREAD

**Issue by mmatesic01** [home-assistant/android#61]
Hi,
When using this app, if I leave it on tab with video stream(live Picture glance entity ), screen does not turn off after expected inactivity.
When leaving in that state on web page view through any of web browsers this does not happen, screen turn off as expected.
Can you fix this?

**Comment by NicoBijl** [comment]
I am not sure if 'turn off after inactivity' is the expected behaviour. My screen does not turn off either when I watch youtube or netflix for that mather..

And, when for example watching the camera on my daughters room to see if she is asleep, I like the fact that the screen stays on.

**Comment by robbiet480** [comment]
Similar to #277
