### ISSUE TITLE
Support Android 11 Quick Access Device Controls feature

### ISSUE THREAD

**Issue by leroyboerefijn** [home-assistant/android#619]
With Android 11, the Quick Access Device Controls feature is introduced. See https://developer.android.com/preview/features/device-control for more information.

I know that Android 11 is currently still in Beta, but it would be nice to support this feature already before the official release to mature the support.

**Comment by ofalvai** [comment]
I started playing with the new API and put together a very WIP app: https://github.com/ofalvai/hass-android-controls
The basics are working very well, clone my repo and build the app locally if you're interested.

**Comment by dshokouhi** [comment]
Is this something that will also be supported by the Google Home app which I imagine most of us already have setup?  I was just reading the linked docs and noticed they called it out.  If we already have nabu casa or a manual setup of `google_assistant` I believe it should pull everything synced up from that integration right?

IIRC the live example when they announced this was that it would work with accounts connected to the assistant already.

**Comment by JBassett** [comment]
Yes but that means all commands still need to pass through the cloud to update Home Assistant.  If we implement ourselves we can stay 100% local.

**Comment by Devenda** [comment]
What's the status on this now that Android 11 had officially been released?

The WIP above looks promising!

**Comment by ofalvai** [comment]
I stopped working on this because a recent Android 11 emulator update removed the entire Device Controls feature from the power menu of the emulator build, and none of my real devices are upgradable to Android 11 yet. If you have any idea how to use this API on emulator, let me know.

**Comment by k1n6b0b** [comment]
Looks like progress is being made! https://github.com/home-assistant/android/pull/1027

**Comment by JBassett** [comment]
Fixed with https://github.com/home-assistant/android/pull/1027

**Comment by galadril** [comment]
@ofalvai did you find out how to test Quick Access Device Controls on an emulator??

**Comment by ofalvai** [comment]
@galadril No, I couldn't figure out how to enable the feature. My guess is this feature is not part of the generic Android version that runs on emulators, but it's enabled by manufacturers on their flavors of Android.

**Comment by galadril** [comment]
@ofalvai thanks for your response.. too bad.. i would love to build on this feature, but dont have an Android 11 device yet....
PS, i found actually an issue on Google here:
https://issuetracker.google.com/issues/168973367

**Comment by Sissi91** [comment]
Does anyone know how I could see the position of my blinds, or maybe also adjust the position of them in the Power menu?
I can controll my blinds, so open/close them. but I don't see a position in the Power menu and I also can't set the position. 

On the picture I found it seems to be possible (button top row, right side)

![image](https://user-images.githubusercontent.com/34167143/111810184-04cf3780-88d6-11eb-93be-02d6331a253f.png)

If somebody has done something in that way, that would be just great.

**Comment by dshokouhi** [comment]
@Sissi91 please do not comment on old closed issues.  If you have a feature request please submit a new feature request.  The cover position is not implemented yet so a feature request should be submitted for it.

**Comment by Sissi91** [comment]
> @Sissi91 please do not comment on old closed issues.  If you have a feature request please submit a new feature request.  The cover position is not implemented yet so a feature request should be submitted for it.

Thank you, I posted it it here: https://github.com/home-assistant/android/issues/1439
