### ISSUE TITLE
Persistent notifications are dismissed when clicked

### ISSUE THREAD

**Issue by kmlucy** [home-assistant/android#621]
**Home Assistant Android version:**
1.9.0-172
**Android version:**
10 (June update)
**Phone model:**
Pixel 3a
**Home Assistant version:**
0.110.7
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
I'm trying the new persistent notifications, and they work well in that you can't swipe the notification away. But if you tap the notification, it is dismissed.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**
I've done the full clear data/delete integration/re-setup and am still getting this error.

**Comment by JBassett** [comment]
I think you are mixing up persistent and sticky.
Persistent - Can't swipe to dismiss notification.
Sticky - Even after clicking notification stays.
You should be able to use both in combination if that's what you are looking for.

**Comment by dshokouhi** [comment]
Yup `sticky` along with `persistent` and `tag` does make the notification stay when its selected.  Looks like we have total control over the notification now, thats amazing!  I will add a note to my docs PR about this to avoid confusion :)

**Comment by kmlucy** [comment]
@JBassett I wasn't even aware those were two separate options. `sticky` plus `persistent` is what I was going for and is working perfectly. Thanks!
