### ISSUE TITLE
App name shows key placeholder

### ISSUE THREAD

**Issue by balloob** [home-assistant/android#628]
Got this email:

> Since the last update the app name is as the attached picture. Doesn't look right huh?

![Screenshot_20200614-120019](https://user-images.githubusercontent.com/1444314/84612066-4ed14b80-ae74-11ea-89aa-9406178e9bae.png)

**Home Assistant Android version:**

**Android version:**

**Phone model:**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem:**

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by fredrikbaberg** [comment]
I also have this issue. Started with "+1" on main post, but I realised the following information may be helpful:

* Language: Swedish (same as in screenshot)
* Sony Xperia XZ2 Compact, running Android 10
* App version: 1.10.0-183

**Comment by JBassett** [comment]
@fredrikbaberg can you try the latest build 1.11.0?

**Comment by fredrikbaberg** [comment]
@JBassett updated, app name seems correct now. Thank you.

I was not the one who sent the email, so can´t speak for original bug report, but for me this is resolved now.

**Comment by JBassett** [comment]
If someone else sees this issue they can create another issue but for now I think we are good.
