### ISSUE TITLE
Home assistant and Huawei mediapad m6

### ISSUE THREAD

**Issue by andreynet** [home-assistant/android#639]
Hello, I am from Russia and my English is bad)) 

https://community.home-assistant.io/t/home-assistant-app-on-huawei-p40-pro/203974

In my Huawei mediapad M6 android 10
There is a problem, and I don’t know how to solve it, Google services are installed, can this be fixed somehow?  Thank!

**Comment by andriej** [comment]
It's highly probable that it's due to lack of Google Services on newest Huawei devices.

**Comment by andreynet** [comment]
I think it's true, but Huawei one year not install Google. Service in device, I hope HA app do work on my device)=)

**Comment by dshokouhi** [comment]
Your device needs to have google services installed in order for the app to work.  Some devices like a Amazon Fire Tablet also do not have google services but if we install google play store along with services and apps like google maps then it can work to some extent.  Support is really only provided for devices that had google services pre-installed.  You also need to check that you have apps like Android System Webview installed.  These are all common for devices with google services pre-installed.

**Comment by andreynet** [comment]
> Your device needs to have google services installed in order for the app to work. Some devices like a Amazon Fire Tablet also do not have google services but if we install google play store along with services and apps like google maps then it can work to some extent. Support is really only provided for devices that had google services pre-installed. You also need to check that you have apps like Android System Webview installed. These are all common for devices with google services pre-installed.

I have a Google service manual install, but android webview don't work on this device)

**Comment by dshokouhi** [comment]
> android webview don't work on this device

Then the app will not work there, your device needs to support these things in order for the app to function.  If your device is rooted there is an xposed framework module that will pre-install android system webview but thats really the only thing you can try to see if it will work.
