### ISSUE TITLE
Notify - Duplicate device name with two devices.

### ISSUE THREAD

**Issue by Nornode** [home-assistant/android#641]
**Home Assistant Android version:**
One release (from Market)
One Beta tester: 1.9.0-180

**Android version:**
Android 10 Oxygen 10.3.4

**Phone model:**
**2 * Oneplus 6**

**Home Assistant version:**
111.4

**Last working Home Assistant release (if known):**
Not known.

**Description of problem:**
Only one notification service, not two.
I want to notify only one, and know which one I notify.

**Traceback (if applicable):**

```
2020-06-29 09:25:48 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name ONEPLUS A6003
2020-06-29 09:25:48 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name ONEPLUS A6003
```

**Screenshot of problem:**
-
**Additional information:**
-

**Comment by dshokouhi** [comment]
@Nornode you need to go in to App Configuration for both devices and set the device name to be unique for each device.  Once you do that restart HA and you won't have a duplicate notify service call.

More details can be found here: https://companion.home-assistant.io/docs/troubleshooting/faqs/#notify-service-call-is-too-similar-or-not-showing-up-in-android

**Comment by Nornode** [comment]
Yes, I know that can be made. - _What you suggest is a workaround, not a fix._
Regarding entity_id's, it is working as expected. Every duplicate entity_id is suffixed with a `_X` where X is the number of the device.
Now, doing as. you suggest, adjusting this device name would also mean that I have to change all references to these already existing entity_ID's.

**Comment by dshokouhi** [comment]
The entity IDs are already registered so they won't change when you update the device name. 

You are free to rename them if you wish from the integrations screen. From there you can see a list of all entity IDs per device.
