### ISSUE TITLE
Android app is not connecting after timeout

### ISSUE THREAD

**Issue by engrbm87** [home-assistant/android#642]
**Home Assistant Android version:**
1.9.0
**Android version:**
10
**Phone model:**
Oneplus
**Home Assistant version:**
0.112
**Last working Home Assistant release (if known):**
0.111.4
**Description of problem:**
The automatic disconnection introduced in 0.112 causes the android app to disconnect. If the app is still in the background it won't reconnect when switching to the app again.
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Duplicate of https://github.com/home-assistant/frontend/issues/6227

This will need to be fixed by HA frontend
