### ISSUE TITLE
Battery State shows discharging while connected on A/C charger

### ISSUE THREAD

**Issue by Guyohms** [home-assistant/android#644]
**Home Assistant Android version:**
1.9.0-167
**Android version:**
10
**Phone model:**
Pixel 3a
**Home Assistant version:**
0.112
**Last working Home Assistant release (if known):**
Was working with 0.111 but the issue was there before I upgraded to 0.112 (today)
**Description of problem:**
When this phone is connected to a charger, the battery state doesn't update to `charging`.
The attribute `is charging` stays `false` but the attribute `charger type` successfully change from `unknown` to `ac`.

It was working and stopped maybe a week ago.

I tried to : 
- Restart the phone
- Restart Home Assistant
- Delete the cache and storage of the android app and re-register with HA.

**Traceback (if applicable):**

```
No error log related
```

**Screenshot of problem:**
Pixel 3a Not connected:
![image](https://user-images.githubusercontent.com/44414660/86306042-35086600-bbe1-11ea-9f19-1448b7492d1c.png)

Pixel 3a Connected:
![image](https://user-images.githubusercontent.com/44414660/86306072-4b162680-bbe1-11ea-9f19-d6cb4364d1cb.png)

Pixel XL Connected:
![image](https://user-images.githubusercontent.com/44414660/86306144-79940180-bbe1-11ea-8969-f405591a33e2.png)

**Additional information:**
Strangely, it works flawlessly with another phone (Pixel XL).

**Comment by dshokouhi** [comment]
Sounds similar to #551

**Comment by Guyohms** [comment]
> Sounds similar to #551

Well, I have this behaviour on the phone that reports the charging status correctly (Pixel XL).

This issue is different because the app is correctly updating the phone status otherwise. In fact, like stated in the issue, the `charger_type` attribute updates instantly.

**Comment by Guyohms** [comment]
I just tried to connect the phone and it's now working as it should !

I really don't know what changed since a few days... Strange.

Let's call this closed for the moment !

**Comment by dshokouhi** [comment]
I am pretty sure based on the description here its identical to #551 keep watch of the sensor and in a few days it may happen again.  If it does then you are indeed hitting #551 

More than likely you restarted your phone which as you can see in #551 fixes the issue for a few days.
