### ISSUE TITLE
Location does not update

### ISSUE THREAD

**Issue by jurgenhaas** [home-assistant/android#645]
**Home Assistant Android version:** 1.9.0-167

**Android version:** 9

**Phone model:** Fairphone 3

**Home Assistant version:** 0.112.0

**Last working Home Assistant release (if known):**

**Description of problem:** Having 5 Android phones in the family, I recently added the FP3 with /e/OS to the local stack too and it works surprisingly well. I know, without Google Services we won't get notifications to work. But the other waay round, sending sensor and tracking information back to Home Assistant should be possible.

As it dodn't work for a couple of weeks I started digging into the issue queue here and came across the recommendation to start over (see https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app) and to ensure the location and battery related settings too (see https://companion.home-assistant.io/docs/troubleshooting/faqs/#location-is-not-updating-in-android-app)

I've followed that advise step by step and I'm getting battery level and state into HA but not the location. All the settings are correct and I don't know what to check next.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
@jurgenhaas if your device does not have google play services then the app will not work, the official app requires google play services in order to work.  Google services is how it pulls location data.
