### ISSUE TITLE
1.10.0 : vibrationPattern applied on all notifications and cannot be edited/removed

### ISSUE THREAD

**Issue by Guyohms** [home-assistant/android#654]
**Home Assistant Android version:**
1.10.0

**Android version:**
10

**Phone model:**
Pixel XL

**Home Assistant version:**
0.112.0

**Last working Home Assistant release (if known):**
-
**Description of problem:**
I tried the new `vibrationPattern` feature first by copying the example in the companion docs. It worked right away.
Then I wanted to change the pattern. Nothing changed.
So I removed the `vibrationPattern` line from my automation and it still vibrate with the timing from the example.

Later on, I realized that all my notifications are now vibrating using this timing!

**Traceback (if applicable):**

```
N/A
```

**Screenshot of problem:**

**Additional information:**
I tried to clear the app cache and tried to turn off/on the vibration setting on this particular notification channel.

**Comment by dshokouhi** [comment]
@Guyohms the vibration pattern gets set the very first time you use it on any channel. If you did not specify a channel then it gets set for the default channel that all notifications use which is the general channel.  This is as designed by android and we have a note about that in the companion docs.

https://companion.home-assistant.io/docs/notifications/notifications-basic/#notification-channels

You need to recreate your channel with the proper vibration pattern....once set you can't change it unless you remove and re-add the channel.  If you are still experiencing issues then please comment back with the service data you used each time.  We will need to see how its flowing.  Just keep in mind that some of these settings only get used once per channel and become the default for that channel.  I know its a bit confusing but I tried to capture that in the note in the docs.

**Comment by Guyohms** [comment]
Ok!
I went straight to the vibration section of the documentation, so I missed this note...

So if I want a different pattern for let's say each notification, I would need to create a channel for each...

For the moment, if I want to reset the general channel to it's default, I need to send this ?

```yaml
data:
  message: remove_channel
  data:
    channel: general
```

**Comment by dshokouhi** [comment]
I am not 100% certain that would work for the default channel but you can try it! worse comes to worse just clear data in the app and start again :)

**Comment by Guyohms** [comment]
You were right, I had to clear data to reset the General channel.

While the note you linked is clear, I think the documentation could be clarified a little. I suggest:

- Reordering the topics so that the 3 special cases are located just under the note
- Adding a link to the channel note on each case so people like me who used the index links to go directly to one topic can be informed of this behavior
- Specifying on each case that the setting is specific to a channel (the example code doesn't even show the channel information)
- For the vibration pattern, changing the misleading text that suggest this option is per notification and not per channel

From the docs:
>You can set the vibration pattern per notification by setting the vibrationPattern property.

- Adding to the channel note that if no channel is specified the "General" channel will be applied and cannot be undone unless by clearing data.

**Comment by dshokouhi** [comment]
@Guyohms please feel free to submit a PR to update the docs accordingly.  Anyone can edit them just like anyone can edit the main HA docs.  There is a link on the page that says "Edit on github" click on that and make the necessary changes so we can get it updated :)
