### ISSUE TITLE
Make use of the notification channels

### ISSUE THREAD

**Issue by bratanon** [home-assistant/android#658]
**Is your feature request related to a problem? Please describe.**
We are many users that uses the notifications. I have a ton of them, but some are more important to me then others. 
In case of a fire, intruder, or leak, I want to be notified even if I have activated the "do not disturb" function for the night. 
Currently all notifications are in the same channel called "General", which leave me with the choice to either get a lot of notifications during the night that wake me up, or none.

**Describe the solution you'd like**
Give users a change to categorize notifications with the Android notification channels. That would give users the possibility to assign a severity level to the notifications, and for example, set aside the "do not disturb" feature for very important notifications.

Just a few would work for now, like:
- Emergency
- Info

**Describe alternatives you've considered, if any**
None

**Additional context**
There is a guide here that explains this.
https://developer.android.com/training/notify-user/channels

**Comment by balloob** [comment]
This is already supported https://companion.home-assistant.io/docs/notifications/critical-notifications
