### ISSUE TITLE
Home assistant Android APP kiosk mode

### ISSUE THREAD

**Issue by PablexXXXX** [home-assistant/android#660]
Hi everyone. I was trying to get a dedicated tablet to be used only with Home Assistant. I was able to achieve this only by 3rd parties APPs. It would be great to add this natevly in the APP. Does it make any sense? Is it a lot of work to put the app as a device admin? Does it make sense? By the way. Thanks for this awesome app.

**Comment by balloob** [comment]
This is already possible. Sidebar -> App Configuration -> Fullscreen.

**Comment by PablexXXXX** [comment]
Full screen is one thing, nice thing but kiosk mode is different. In kiosk mode you can't leave the app. The home, back o recent button also wouldn't respond.
