### ISSUE TITLE
Incorrect current location and geocoded location

### ISSUE THREAD

**Issue by klejejs** [home-assistant/android#661]
**Home Assistant Android version:**
1.11.0-215
**Android version:**
10
**Phone model:**
Samsung S10e
**Home Assistant version:**
0.112
**Last working Home Assistant release (if known):**

**Description of problem:**
I have been home all day but Home Assistant shows that I have visited 2 different places. It seams like it jums to a random place 30km away for a second and then jumps back immediately. Also geocoded location is fixed on the random place now, not my home address, where I have been all the time.
At first I thought it might be GPS reporting incorrect location, but my google timeline doesn't show those movements.
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by sassa4ras** [comment]
I'm having a similar issue. The app randomly assigns me a location 300 meters to the east, in the midst of a large body of water. It seems to swap back and forth from there and my true location in my home. 

Same as @klejejs the google location history does not show me randomly swimming 200 meters offshore.

**Comment by vampik** [comment]
I have a similar issue. Me and my wife has Motorola G7 Plus (mine has Android 9 and her has Android 10). Home Assistant version is 0.113, app version 1.11.2. Background location update is enabled as well as zone based tracking. But location updates only on zone entering or leave, There is no updates while device is moving out of the zone. There is no tracks on the map. The funniest thing is that geocoded location sometimes gets updated, but device location on the map is not.
My mother has Samsung SM-J120F with Android 5, and here the app works correctly - constantly updates location. I see her tracks on the map, but not ours.
I've trying installing Tasker and sending io.homeassistant.companion.android.background.REQUEST_ACCURATE_UPDATE intent every 5 minutes. It works for some time. But after some time application starts ignoring this intents and doesn't update location.
Battery optimizations are disabled. Location permissions and unlimited data connection permissions are granted.
Previously everything was working perfectly until an update.
I don't know what has breaked the thing - Android app update or Home Assistant update. But something has definitely broke the location tracking feature.

**Comment by Kaibob2** [comment]
Same here. HA Version 0.113.1 and two mobile phones with Companion 1.11.2-221 in identical configuration. One is a Samsung Galaxy S9 the other a Huawei Honor 9. The device tracker sensors of both mobiles work perfect and are updated regularly. The routes on the map are much more detailed than with the google maps location sharing which i used before and still runs parallel.
(I've setup two new Users for the Companion data to have a comparison).
On the S9 the geocode sensor works quite reliable, but the updates happen much less than with the "old" google sensor. On the Honor 9 the sensor get's almost never updated (maybe 2 times a day) but I haven't found the pattern when it does yet.
All permission and energy savings and whatever are configured correctly on both devices. Forcing an update with "request_location_update" works, but only updates the device tracker.

**Comment by vampik** [comment]
Well, my case is opposite. geocode sensor is updated regularly but device tracker is almost never updated (maybe 2 times a day)

**Comment by vampik** [comment]
It seems that I've found the source of the issue. Device tracker location updates are discarded because of being inaccurate. Geocode sensor seems to ignore accuracy despite the is a check in the code` if (it.accuracy > LocationBroadcastReceiver.MINIMUM_ACCURACY)`, it seems that this check doesn't work.
The result is that geocode sensot gets updated regularly (ignoring accuracy) but device tracker location doesn't update (discarding inaccurate updates).
I propose to make MINIMUM_ACCURACY a user configurable setting.

**Comment by vampik** [comment]
It stopped working for us not because of an update but because previously we were driving with a GPS navigation app, so the location updates were accurate. Now we usually don't use navigation app for familiar ways, so the phone gets its location mainly from the cell towers and it is not accurate enough for Home Assistant Android app.

**Comment by vampik** [comment]
To check this I tried downgrading to 1.8.0 which was known to work perfectly but it doesnt.

**Comment by vampik** [comment]
Oh, my bad. I'm using 1.8.0 now and minimum accuracy to geocoded address was added only in 1.9.0.
That's why geocode sensor is updated regularly but device tracker is almost never updated.

**Comment by vampik** [comment]
Nevertheless please make MINIMUM_ACCURACY a user configurable setting instead of a constant.

**Comment by McGiverGim** [comment]
It seems the developers don't want it configurable. I discussed differents solutions, including that, in https://github.com/home-assistant/android/issues/497 and added a feature request for a "smarter" or configurable zone tracking here https://github.com/home-assistant/android/issues/518

**Comment by vampik** [comment]
> It seems the developers don't want it configurable.

It's a pity if it's true. My coding skills are not good enough to implement this option. Right now I just workarounded this by making my own custom build with MINIMUM_ACCURACY = 5000. But it obviously lacks push notifications so I'd prefer an official solution to this issue.

**Comment by vampik** [comment]
MINIMUM_ACCURACY = 200 is definitely too small because it works only:
1) in the city center which is very crowded by Wi-Fi access points and cell towers
2) if you leave a GPS navigation or map app open, which will vastly drain the battery

I've set it to 5000 because we often travel to a rural area with no Wi-Fi access points around and rarely located cell towers giving very inaccurate location. With MINIMUM_ACCURACY = 200 this gives a track with only 2 points - departure point and destination.

**Comment by vampik** [comment]
I'm also looking for a way to exclude some specific bogus locations.
Google "teleports" you to a very distant location when you enter the subway. Looking for a way to exclude this location from updates. BTW this can't be filtered by the accuracy because this location is reported as very accurate (insert facepalm.jpg here).

**Comment by vampik** [comment]
> Google "teleports" you to a very distant location when you enter the subway.

And the resulting track looks like this which is very confusing

![1](https://user-images.githubusercontent.com/726409/88912013-53f12b00-d267-11ea-8d50-3920d0b786c9.png)

**Comment by vampik** [comment]
Hmm.. It seems that the issue persists even if I set MINIMUM_ACCURACY = 5000.
Geocoded location get updated regulary, but device tracker location is not (I was travelling all the day and has the track with only two points).
Now I use custom build 1.11.2-2-gf468ece-223 with MINIMUM_ACCURACY = 5000.

**Comment by klejejs** [comment]
I have recently returned from a vacation and now staying home again. I have noticed that since the last update it has gotten worse. If previously when I reported this issue, the location was jumping incorrectly a few kilometers away from my current location, then now it is a few 10 or 100 of kilometers. Not sure why. The phone now is different though. The reported Samsung S10e works great, but I have 2 Sony XZ1C and they both have jumping location. Interestingly though, the location on both of them jumps to the same incorrect location despite being logged in as 2 seperate accounts in HA.
Do you want me to open another issue? Could the issue be connected to hardware in some way?

**Comment by anyuta1166** [comment]
> 
> 
> I have recently returned from a vacation and now staying home again. I have noticed that since the last update it has gotten worse. If previously when I reported this issue, the location was jumping incorrectly a few kilometers away from my current location, then now it is a few 10 or 100 of kilometers. Not sure why. The phone now is different though. The reported Samsung S10e works great, but I have 2 Sony XZ1C and they both have jumping location. Interestingly though, the location on both of them jumps to the same incorrect location despite being logged in as 2 seperate accounts in HA.
> Do you want me to open another issue? Could the issue be connected to hardware in some way?


May be this is not a hardware issue, but geolocation provider (Google) issue.

Please see this thread: https://community.home-assistant.io/t/ability-to-discard-bogus-locations/217619/7

**Comment by klejejs** [comment]
Do you think Google timeline has a privilege to show only the past locations not current ones so it is possible for them to discard values that seem out of place? Could it be a fix for HA location problem? What if the app would collect all locations but then remove the unlikely ones from history?

For example, what if it would work like this:

1. First (legitimate) location is received and it shows on map.
2. Second (bogus) location is received after 15 minutes and it also shows up on map but it is 20km away.
3. Third (legitimate) location is received and it is the same as the first one. It is also shown on map but at that point the second one is calculated to be unlikely one and it is deleted from the history.

Yes, at some point the bogus locations would be showing up on map, but they would at least be deleted from history and the history view would be correct.

In that case the fix should be implemented in HA Core.

What do you think of the solution? Is it valid? Should it be looked into?

**Comment by anyuta1166** [comment]
> In that case the fix should be implemented in HA Core.

Yes, the fix indeed should be implemented in HA Core. If you have any suggestions please post them in my feature request, not here

https://community.home-assistant.io/t/ability-to-discard-bogus-locations/217619/7

**Comment by anyuta1166** [comment]
> (This solution to me seams more valid than users manually specifying bogus locations)

Yeah. It's very hard to catch all such locations. And more then that, they seems to be slightly varying, not fixed coordinates.
