### ISSUE TITLE
Mobile app no longer works?

### ISSUE THREAD

**Issue by i00** [home-assistant/android#666]
## The problem

When connecting to home assistant via the Android app (via forwarded ports); it now brings up a chrome page stating CONNECTION_REFUSED; but when I go to the same page (stated in the error) via Chrome on my mobile I can access it with no issues.

## Environment

- Home Assistant Core release with the issue: 0.112
- Last working Home Assistant Core release (if known): Def worked in 0.110 ... not sure about 0.111
- Operating environment (OS/Container/Supervised/Core): Docker
- Integration causing this issue: ?
- Link to integration documentation on our website: ?

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by balloob** [comment]
Are you using a custom certificate?

**Comment by Altycoder** [comment]
The andriod app has also stopped working for me.  I'm running home assistant 0.112.4 in docker and an nginx reverse proxy also in docker.  I have a letsencrypt certificate for my duckdns domain and this has all been working fine until the latest app update.

The certificate still has >40d until expiry.

Devs please let me know which config files you need to debug this please.

**Comment by dshokouhi** [comment]
@Altycoder and @i00 can you guys please share a screenshot of the error?  Also are you guys using the internal connection URL? If so please tell us the format of the URL.

**Comment by Altycoder** [comment]
I have the app set up to use the following internal url: http://192.168.1.9:8123

My external url is set up as: https://mydomain.duckdns.org:8123 (where "mydomain" is set to my domain - although you can see this in the screenshot anyway haha).

I have my wifi SSID set as well

![Screenshot_20200716-165044](https://user-images.githubusercontent.com/1990152/87693250-a705b100-c784-11ea-8059-306c9afbfc2f.jpg)

If I remove the internal url and just leave the extrnal url I can't connect at all.  This was all working fine until very recently and the certificate for my url is still way in date.

**Comment by dshokouhi** [comment]
What version of the android app are you running? Also did you by chance update HA core around the time this issue happened? If so what version of HA core were you previously running.

**Comment by Altycoder** [comment]
I've not updated HA core recently and I'm running latest version of app from the play store 1.11.0-215

I've just refreshed my letsencrypt certificate and still no joy

**Comment by Altycoder** [comment]
When I have more time tomorrow I'm going to try setting up a new URL and refreshing the whole letsencrypt / duckdns set up in case something is just out of sync somehow.

**Comment by dshokouhi** [comment]
What version of HA core are you running?

**Comment by Altycoder** [comment]
> What version of HA core are you running?

see my original post above?

**Comment by dshokouhi** [comment]
since you mentioned it was working before, can you try to start fresh with the app to make sure its not a data issue?

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by balloob** [comment]
Also try to disconnect from your home wifi and use mobile data.

**Comment by JBassett** [comment]
Since you left your URL in the screenshot I tried to reach it but I also timed out.  I don't think this is an Application issue.

**Comment by Altycoder** [comment]
> Also try to disconnect from your home wifi and use mobile data. 

that's what I've been trying to do :-)

**Comment by Altycoder** [comment]
> Since you left your URL in the screenshot I tried to reach it but I also timed out.  I don't think this is an Application issue.

you might be right, I'm going to roll back my nginx container tomorrow to see if that's the problem

**Comment by Altycoder** [comment]
> since you mentioned it was working before, can you try to start fresh with the app to make sure its not a data issue?
> 
> 
> 
> https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

thanks I tried all that earlier today.

I can't reach my site via a browser either now so I'm starting to lean towards an nginx issue as I updated that container yesterday. A rollback of nginx will be my first task in the morning

**Comment by balloob** [comment]
Ok, closing this issue since it's not app related.

**Comment by Altycoder** [comment]
ok, turns out the container I was using for nginx and letsencrypt had updated the structure of the config files which had screwed up my server so apologies for the red herring.

**Comment by i00** [comment]
I am still having this issue...

My screenshot would be the same as the one posted above with a different URL (that I do not want to disclose)... My URL is the same for local and external access; and as stated previously work in chrome.

@Altycoder  ... I also use ngnix to reverse proxy my HA instance and have it attach the lets encrypt cert ... how did you resolve this?

Thanks
