### ISSUE TITLE
Battery percentage updates in inregular intervals

### ISSUE THREAD

**Issue by freemann** [home-assistant/android#671]
**Home Assistant Android version:**
1.11.0-215

**Android version:**
10.X (most recent OxygenOS version)

**Phone model:**
OnePlus  7 Pro

**Home Assistant version:**
Home Assistant 0.112.4

**Last working Home Assistant release (if known):**
Unknown

**Description of problem:**
While charging the battery percentage is updated in strange intervals of X minutes/percentages steps.
I use a automation to not fully charge my battery untill 70% and now it regularly overshoots to 80%+
Previously I used Automate to send the battery percentage over mqtt and that works flawlessly.

Would by nice if the app could send every percentage change to HA :)

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![Screenshot - 15_07_2020 , 17_17_04](https://user-images.githubusercontent.com/601053/87563003-05685c00-c6bf-11ea-9dca-27c5e2559a56.png)
**Additional information:**

**Comment by dshokouhi** [comment]
We have had quite a bit of improvements in the past release that should give better updates now for all sensors. Can you try on version 2.2.1?  We can't expect to get each and every percentage change but you should see updates flowing through frequently at least every 15-20 minutes when the sensor worker runs.   You may just need to tweak your automation a tiny bit if its still an issue. Try to account for the update interval if possible.

**Comment by freemann** [comment]
I tested the new sensors and there "response time".
Noticed that almost all sensors are changed instandly and battery percentage only once every +/- 10min.

Charging state, BT connections and connected devices, WiFi connection state/SSID are changed within 30 secs and especially next alarm is very fast with <5 secs. Only battery percentage is changed once every +/- 10min.

How can it be that this sensor is slow while all other sensors are changing almost instantly ?

**Comment by dshokouhi** [comment]
Thats because the event for the battery percentage includes too many changes.  It makes the app wake up and send sensor updates sometimes 10 times in 10 seconds. That event gets triggered in pretty much anyway that impacts the battery including turning on/off the screen.

One thing about the events you mentioned, anytime one of those trigger all of the sensors on the device get an update including the battery level.

**Comment by freemann** [comment]
OK, So because of the battery use its a choice to only update once every 10min. to use less battery?
But while charging, battery use shouldn't an issue, the device is on jus so a 1 min. update shouldn't be a problem?

I had a Automate flow running;
While charge state is charging, then send API call every 30 secs.
While charge state is not charging, then send API call every 300 secs.

Maybe make it a bit more flexible to run the sensor worker while not charging once every 10min and while charging every 1 min?

**Comment by freemann** [comment]
Noticed that when the app is closed, the battery (and probably other) sensors are not updated.

Any thoughts about the option to run the sensor update more regularly when devices is charging?
