### ISSUE TITLE
Copy text from code editor does not work

### ISSUE THREAD

**Issue by pipip** [home-assistant/android#672]
**Home Assistant Android version:**
1.11.2-221

**Android version:**
9

**Phone model:**
Honor 7x, MediaPad M5 lite

**Home Assistant version:**
0.112.5

**Last working Home Assistant release (if known):**
no

**Description of problem:**
- Navigate to any code editor / text input box (e.g.: code editor for any card) 
- Select some rows of text
- Copy
--> only some part of the text is copied (most part is missing)
(copy multi row content from any other application I use works fine) 

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Do you see the same behavior if you use chrome on Android?

**Comment by pipip** [comment]
@dshokouhi  indeed. I did not try this before but you are right. copy text from home assistant code editor also does not work in chrome (other websites work fine)

**Comment by dshokouhi** [comment]
Closing as duplicate per above issue.
