### ISSUE TITLE
Can't connect to Home Assistant when wifi has no internet connection

### ISSUE THREAD

**Issue by tinuthir** [home-assistant/android#675]
**Home Assistant Android version:**
1.11.2-221

**Android version:**
10

**Phone model:**
Google Pixel 3

**Home Assistant version:**
Home Assistant 0.112.4

**Last working Home Assistant release (if known):**
Unknown

**Description of problem:**
I have a Home Assistant instance that runs just fine (not complex at all) and I interact with it both via web interface on my computer and via the Android app.

Now we had an Internet outage, which meant that when the Android phone was connected to the wifi, it didn't have access to the internet, so the phone _simultaneously connected to the mobile Internet_.

In this setup, the phone cannot reach Home Assistant despite the correct IP address being setup in the app.

I use a Google Pixel 3 on Android 10 (no beta) for this.

Reproducing is easy:

1. Have a working Home Assistant instance running. It must _not_ be accessible via the Internet.
2. Install the Home AssistantAndroid companion app and set it up so that you can connect to your Home Assistant
3. Unplug the _phone or cable line_ from your router (not the power - make sure the power stays on)
4. As a result, your phone should be connected both to the wifi (with no Internet access) and mobile Internet
5. Open the Android companion app.

Expected result: the Home Assistant interface appears
Actual result: a connection error appears

The simplest fix would be to (somehow) implement a fallback in the app - if a connection isn't possible via the Internet connection, try the local wifi _without_ the internet connection.

**Comment by skylarmt** [comment]
I think that's an Android system thing and isn't controllable by apps.

**Comment by dshokouhi** [comment]
Well if your device reports that wifi has no data then it wont use wifi it will use mobile for data.  I think it maybe an OS feature but maybe the app can determine if wifi has no connectivity to send the correct URL.

**Comment by tinuthir** [comment]
The thing is that the phone already has two active data connections when wifi _is_ connected to the Internet. Data connections aren't cut when the Internet is available via wifi, at least as I understand it (to ensure, as far as possible, seamless connectivity). 

So while it could, of course, be OS behavior, that doesn't preclude the app from perhaps checking the following:

- Is wifi available (regardless of Internet connection)? --> connect to Homeassistant via wifi
- If no connection is possible: is the wifi connected to the Internet? --> connect to Homeassistant via wifi's Internet connection (this would be a use case when in someone else's wifi and trying to 
- If no connection is possible: fall back to mobile Internet connection and try to connect to Homeassistant via that path

Obviously, there are other logical constructs you could use to determine the priority here. I just feel like most of us would connect to Homeassistant via the _local wifi_, with no internet connection needed, so that should maybe be the app's first path to success before trying anything else.

Caveat: if at all possible.

**Comment by tinuthir** [comment]
Some potentially interesting resources:
https://android-developers.googleblog.com/2016/07/connecting-your-app-to-wi-fi-device.html
https://stackoverflow.com/questions/42492136/force-android-to-use-wifi-network-with-no-internet
https://stackoverflow.com/questions/58085988/connecting-an-android-app-to-a-wifi-without-internet-access
Definitely looks like something that's non-trivial, unfortunately.

**Comment by tinuthir** [comment]
Understood, though I will admit this is disappointing. That means that someone who runs a Home Assistant instance that isn't connected to the Internet for security reasons will be unable to run it from their phone, which is most likely perpetually connected to the Internet. 

Mind you, this isn't me at all. My network will be connected to the Internet. I'm just saying there's a valid use case here.

My thought isn't, by the way, to route _all traffic_ through the non-connected wifi. Only the data for one specific app. But, as you've stated, that doesn't seem to be possible, which means that I misunderstood the resource. Which is a bummer.

**Comment by tinuthir** [comment]
Can be closed. Sorry to hear it won't be possible.
