### ISSUE TITLE
[Feature Request][Bounty] Google Services-free version

### ISSUE THREAD

**Issue by anonimou0** [home-assistant/android#676]
Hello @balloob @dshokouhi @JBassett @homeassistant ,

I know you guys have been very vocal about not maintaining a Google Play Services free version of the app for Android. I guess this is the most recurring opened issue. I would like to approach it in another way and I would discuss with you and, if you do not agree, as you are the maintainer of the project, you will always have the power to close this issue.

My goal is propose a bounty to anyone outside of the current dev team to come up with a pull request with this feature. That way, it wouldn't take your time developing it. Of course, the bounty is applicable to you too if you guys want to jump in. 

I propose 4 bounties and I will discuss them:

1. [$15] Produce a Pull Request with the minimum change possible that just checks if the phone has Google Services on it and disable "push notifications" and "location features", as they require it. That way, code maintenance on the dev team would be, possibly, the minimum. Pretty much what was done by @jleeuwes on https://github.com/jleeuwes/home-assistant-android-without-google , but embedded in the app.

2. [$25] Location features. Many apps can use microG for location and other Nlp services. The goal on this bounty would be check if Google Services is present and if not, use other location providers on the phone. [[ I don't know it's done, but even closed apps that are extremely location dependent like Uber, and browser integration work seamlessly with microG ]]

3. [$35] Push notifications. As pointed out here https://github.com/home-assistant/android/issues/42#issuecomment-581090179 there are alternatives that can be implemented to get this functionality.

4. [$15] Fdroid build with at least bounty number 1. This probably will need the team to be involved in other to avoid previously problems (https://github.com/home-assistant/android/issues/42#issuecomment-584212855). However, once set up, it would automatically generate new builds.

If any of those gets done, I will double my bounty. One share will be for the pull request person and the other share will be for home assistant team.

I'm marking here people that previously requested similar things so they could jump in and donate too. Let's support these guys and support open source projects. @jurgenhaas @rradar @skylarmt @add1989 @nagyrobi @bisby

============================================================

I don't even know how to operationally pay out the bounties. But we can figure something out if this gets traction.

============================================================

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open the app without Google Play Services and get the Unable to Register message.

**Describe the solution you'd like**
A possible to use the mainstream Home Assistant app with the latest features, even with some limitations.

**Describe alternatives you've considered, if any**
Alternatives would be using forks for the app or even other platforms for home automation.

**Additional context**
Additional context 1. We, privacy "freaks", as the dev team might consider us, consider Google Play Services spyware. Of course it provides convenience on the development and with the features provided. However, it takes with it your privacy. Even it may provide "the best experience", it is not privacy friendly at all. 

Additional context 2. I'm building my house and would love to use HA on it. I've done some testing with it and with it only. However, privacy is a deal breaker to me. I still didn't test other platforms. HA works fine for me on my tests. HA has probably the larger community on the home automation. That's why I would like to stick with it. However, I will not compromise my privacy for it. That's why this FR.

**Comment by balloob** [comment]
As you did see the other issues, you know we do not want this part of the app.

**Comment by skylarmt** [comment]
> we do not want this part of the app.

Who exactly is "we"?  Because it appears that your users want it badly enough they're willing to pay, even in this economy.

Hell, this issue has actually been in the news. I even heard one of my comments quoted on a radio program! It really seems to be the project leadership vs. the entire community and I think we all want to know why.  Is Google paying you off or something?

**Comment by add1989** [comment]
I would happily pay to support a version of the app free from Google Play Services. I'm not a 'freak', I just don't want to use anything where I am not in control of my own data.

**Comment by nagyrobi** [comment]
+1 for this.

**Comment by nagyrobi** [comment]
Push notifications actually suck, the way they work today. I get doorbell notifications in the app 8-10 minutes later than the actual doorbell press. Completely useless.
A totally different notification system would be better imho.

**Comment by jurgenhaas** [comment]
Thanks @anonimou0 for this proposal. I'm doubling your bounty and really hope that the maintainers reopen this issue. Please! Your product is great - it will be even better with a strong community.

**Comment by balloob** [comment]
https://gitlab.com/grote/libre-assistant
