### ISSUE TITLE
Tries to connect to local IP address even if on a VPN

### ISSUE THREAD

**Issue by gregg098** [home-assistant/android#677]
**Home Assistant Android version:**
1.11.2-2-gf468ece-223
**Android version:**
10
**Phone model:**
Samsung Galaxy S10+
**Home Assistant version:**
0.113.2
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
In the app, I set the Home Assistant URL to my Nabu Casa address. Then I set the Home Network WiFi SSID to my home wifi name, and then the internal connection URL is http://[local ip]:8123/

This works fine, unless I use a VPN at home (Wireguard through a personal VPS and also Private Internet Access). Then it still tries to use the local address, even though all traffic is routed over a VPN, which makes it unable to connect.

The error message has the options of Wait, Refresh, and Setttings. It would be nice to have a "Force Remote" or something like that to force it to use the main URL for this session, regardless of Wifi connection.

**Traceback (if applicable):**

```
N/A
```

**Screenshot of problem:**

**Additional information:**

**Comment by vampik** [comment]
I think this is a VPN software issue. You should exclude your home subnet form routing via VPN.
I don't know how it is done in Wireguard and is it even possible here because I personally use Shadowsocks.
Shadowsocks has an option to not route RFC1918 networks via VPN.

**Comment by vampik** [comment]
A small update.
I've just googled this:

> Try using this, it will exclude all private IPs from the tunnel:
> 
> AllowedIPs = 0.0.0.0/5, 8.0.0.0/7, 11.0.0.0/8, 12.0.0.0/6, 16.0.0.0/4, 32.0.0.0/3, 64.0.0.0/2, 128.0.0.0/3, 160.0.0.0/5, 168.0.0.0/6, 172.0.0.0/12, 172.32.0.0/11, 172.64.0.0/10, 172.128.0.0/9, 173.0.0.0/8, 174.0.0.0/7, 176.0.0.0/4, 192.0.0.0/9, 192.128.0.0/11, 192.160.0.0/13, 192.169.0.0/16, 192.170.0.0/15, 192.172.0.0/14, 192.176.0.0/12, 192.192.0.0/10, 193.0.0.0/8, 194.0.0.0/7, 196.0.0.0/6, 200.0.0.0/5, 208.0.0.0/4, ::/0

**Comment by vampik** [comment]
So it is definitely not a Home Assistant issue.

**Comment by gregg098** [comment]
> I think this is a VPN software issue. You should exclude your home subnet from routing via VPN.
> I don't know how it is done in Wireguard and is it even possible here because I personally use Shadowsocks.
> Shadowsocks has an option to not route RFC1918 networks via VPN. Works perfectly with Home Assistant. On home Wi-Fi traffic goes directly to local IP, and it goes through my personal VPS in any other cases.

Understood. This is possible with Wireguard and PIA, but it would be nice just to add some kind of option to try the other URL if one fails, regardless of VPN, Wifi network, etc.

**Comment by gregg098** [comment]
> So it is definitely not a Home Assistant issue.

Its a user experience enhancement.

**Comment by vampik** [comment]
> but it would be nice just to add some kind of option to try the other URL if one fails, regardless of VPN, Wifi network, etc.

Agree, this is a nice proposal.

**Comment by vampik** [comment]
Consider changing type from bug to enhancement.

**Comment by gregg098** [comment]
Wont let me change the label. I added a feature request (#678). Closing this issue.
