### ISSUE TITLE
Geolocation Issues

### ISSUE THREAD

**Issue by Thrasher2020** [home-assistant/android#681]
**Home Assistant Android version:**

1.11.2-221

**Android version:**

10

**Phone model:**

Pixel 3

**Home Assistant version:**

0.113.2

**Last working Home Assistant release (if known):**

Not worked on any since 0.110.x

**Description of problem:**

Random locations - 200 miles apart. Also now decides it can't pick a zone. Move 20 miles in 10 seconds from home to work. Almost like it's caching HOME.

**Traceback (if applicable):**

N/A

**Screenshot of problem:**

![image](https://user-images.githubusercontent.com/65713394/88968148-ccc3a780-d2a6-11ea-8287-6225b2c5e880.png)

**Additional information:**

It's flipped from my home to 200 miles away in 30 seconds too ... i.e. where I am versus HOME. Again, like if it doesn't know where I am it picks home :(

**Comment by dshokouhi** [comment]
Can you try again with the latest app version and let us know if its working as expected?

**Comment by Thrasher2020** [comment]
Hi,

So far so good - I've not flipped between work and home yet. 3 hours so far, "normally" it would have done it numerous times.

**Comment by Cheerion** [comment]
Latest version is installed (beta) but still an issue.

It also often occours that we leave the home zone and the geo location gets updated once and then no more.
At the moment, my wife is between home and her work for 2 hours now.

I didn't have this before...

**Comment by jdbrookes** [comment]
Is this issue related to the issue below where the device_tracker entity for the app sometimes doesn't update along with the geocoded sensor entity?

https://community.home-assistant.io/t/device-tracker-not-updateing-gps-location-gecodedlocation-does/210003
