### ISSUE TITLE
ACTION_REQUEST_ACCURATE_LOCATION_UPDATE doesn't work as expected

### ISSUE THREAD

**Issue by anyuta1166** [home-assistant/android#703]
**Home Assistant Android version:**

2.0.0-3-g11982f9-238-full

**Android version:**

9

**Phone model:**

Motorola G7 Plus

**Home Assistant version:**

0.113

**Last working Home Assistant release (if known):**

**Description of problem:**
ACTION_REQUEST_ACCURATE_LOCATION_UPDATE doesn't work as expected

In the following code it was called twice from the sensors update routine. The same happens when you send the intent from Tasker.

```

08-05 03:31:50.831 12957 12957 D LocBroadcastReceiver: Got single accurate location update: Location[fused 55,637371,37,357052 hAcc=12 et=+2d11h35m11s629ms alt=201.8000030517578 vAcc=2 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
08-05 03:31:50.831 12957 12957 W LocBroadcastReceiver: Location not accurate enough on retry 1 of 5
08-05 03:33:51.050 12957 12957 D LocBroadcastReceiver: Got single accurate location update: Location[fused 55,637371,37,357052 hAcc=12 et=+2d11h37m11s843ms alt=201.8000030517578 vAcc=2 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
08-05 03:33:51.050 12957 12957 W LocBroadcastReceiver: Location not accurate enough on retry 2 of 5
08-05 03:46:56.353 16786 16786 D LocBroadcastReceiver: Got single accurate location update: Location[fused 55,637371,37,357052 hAcc=12 et=+2d11h50m17s153ms alt=201.8000030517578 vAcc=2 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
08-05 03:46:56.353 16786 16786 W LocBroadcastReceiver: Location not accurate enough on retry 1 of 5
08-05 03:49:07.816 16786 16786 D LocBroadcastReceiver: Got single accurate location update: Location[fused 55,637371,37,357052 hAcc=12 et=+2d11h52m28s603ms alt=201.8000030517578 vAcc=2 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
08-05 03:49:07.816 16786 16786 W LocBroadcastReceiver: Location not accurate enough on retry 2 of 5
```
First try - "Location not accurate enough on retry 1 of 5".
Second try happens 2 minutes after - "Location not accurate enough on retry 2 of 5"
No more retries are happening resulting in no location update at all.

**Comment by vampik** [comment]
The disadvantage is also that even if all 5 retries happened, we would get location update only 10 minutes after the initial request.

**Comment by vampik** [comment]
I've fixed this for myself by eliminating retries and using first received location.

**Comment by dshokouhi** [comment]
Does that location still take the accuracy into account? I remember we had a lot of users having issues with the device tracker reporting them away from home with a very low accuracy rating.  So accuracy was added so we can attempt to get a more precise location.

**Comment by JBassett** [comment]
I think we might be about to get a wake lock up keep the device awake when we request an accurate location.

**Comment by vampik** [comment]
> 
> 
> Does that location still take the accuracy into account? I remember we had a lot of users having issues with the device tracker reporting them away from home with a very low accuracy rating. So accuracy was added so we can attempt to get a more precise location.

@dshokouhi The are many questions.

1) When app is opened, it does 5 attempts. But when the app is closed, it does only 2 attempts thus never giving us a location update
2) The interval between retries is insane 2 minutes, so even if the app is opened and did 5 attempts, we get location only 10 (!) minutes after the initial request
3) The code expects accuracy = 1 which is insane. Maybe we should expect accuracy < MINIMUM_ACCURACY instead?
4) And finally make MINIMUM_ACCURACY user configurable.

Because I get the opposite result to those users. I get pretty accurate location reports but they are discarded at all (if the app is closed) or delayed by 10 minutes (if the app is opened).

**Comment by JBassett** [comment]
> 1. When app is opened, it does 5 attempts. But when the app is closed, it does only 2 attempts as you see in the log thus never giving us a location update
The wake lock might fix that.

> 3\. The code expects accuracy = 1 which is insane. Maybe we should expect accuracy <= MINIMUM_ACCURACY instead?

How did that happen?!  That definitely should be  <= MINIMUM_ACCURACY


> 4\. And finally make MINIMUM_ACCURACY user configurable.
There are a couple of constants that probably should be moved into preferences.  I know there has been concern about settings overload for a new user if we make everything configurable.  Perhaps we need a basic and an advanced page.  The advanced page would let you change as much as possible but could be ignored by the average person.

**Comment by dshokouhi** [comment]
> How did that happen?! That definitely should be <= MINIMUM_ACCURACY

Looking at the code it looks like it happened after the minimal version was introduced as the file in question is new.



> There are a couple of constants that probably should be moved into preferences. I know there has been concern about settings overload for a new user if we make everything configurable. Perhaps we need a basic and an advanced page. The advanced page would let you change as much as possible but could be ignored by the average person.

I think this would be a happy medium between those who just want it to work and those who want to tweak it so it updates as fast as possible.  I think if the user wants to hammer their phone we should let them do it (with a warning).

**Comment by vampik** [comment]
@JBassett @dshokouhi 
What's about this?

> The interval between retries is insane 2 minutes, so even if the app is opened and did 5 attempts, we get location only 10 (!) minutes after the initial request

Could the interval between retries be changed, or it solely depends on Android system?

**Comment by JBassett** [comment]
> Could the interval between retries be changed, or it solely depends on Android system?

We can attempt to request the OS give us updates more quickly but as you have seen they aren't guaranteed.

**Comment by vampik** [comment]
The funniest thing is that now ACTION_REQUEST_ACCURATE_LOCATION_UPDATE is now accidently working when the app is opened because location updates returned after the request are processed twice:

1) by handleLocationUpdate function - accepted if accuracy <= MINIMUM_ACCURACY

2) by LocationCallback of requestSingleAccurateLocation - always discarded because it wants accuracy = 1

When the app closed, location updates are processed only by LocationCallback resulting in no location updates when the app is closed.

**Comment by vampik** [comment]
Also pay attention to bug #698. After some time handleLocationUpdate stops receiving location updates even if the app is opened in the background. I suspect that it is the OS killing the background process.
