### ISSUE TITLE
Autmoatically Start App on Boot

### ISSUE THREAD

**Issue by drking7** [home-assistant/android#708]
**Is your feature request related to a problem? Please describe.**
App not updating all information unless opened

**Describe the solution you'd like**
The option to have app automatically start without having to resort to a third party app launcher

**Describe alternatives you've considered, if any**
Currently using a third party app launcher.  Would be handy to have this as a feature built into the app itself

**Additional context**
Running Android 10 on a Galaxy Note 9

**Comment by dshokouhi** [comment]
> App not updating all information unless opened

This bit actually sounds more like a bug.  When the device restarts the location tracking and sensor updates should continue to update since that is a service.

**Comment by drking7** [comment]
Unfortunately, it doesn't update data such as location, battery, wi-fi, etc on the phone unless the app is started.  This happens on two Note 9 phones running Android 10.

**Comment by dshokouhi** [comment]
@drking7 can you double check that you met these musts? https://companion.home-assistant.io/docs/troubleshooting/faqs/#location-is-not-updating-in-android-app 

Last I checked the app would send those updates, also please confirm the app version you are on.  This may just be a bug but need to investigate more :)

**Comment by dshokouhi** [comment]
Today I restarted my pixel and unlocked the phone and after about a minute from boot the sensors updated so this seems to be working as expected for me.

**Comment by drking7** [comment]
This can be closed.  It appears one of the Samsung battery optimizations was causing the issue.
