### ISSUE TITLE
0.114b1 - Dark Mode Not Respected

### ISSUE THREAD

**Issue by ctalkington** [home-assistant/android#710]
**Home Assistant Android version:**
2.1.0

**Android version:**
10.0

**Phone model:**
Samsung Galaxy S9+

**Home Assistant version:**
0.114.0b1

**Last working Home Assistant release (if known):**

**Description of problem:**

Dark mode is a new HA feature but its not respected with "auto" setting in the HA app. I suspect its an issue with android webview needing a special flag set. It works in Chrome for Android.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
I just checked this out as well. If dark mode in HA is set to "auto" it does not work but manually setting it to "dark" does the trick.

**Comment by balloob** [comment]
From https://stackoverflow.com/a/60485832:

```java
if (WebViewFeature.isFeatureSupported(WebViewFeature.FORCE_DARK)) {
    WebSettingsCompat.setForceDark(myWebView.settings, WebSettingsCompat.FORCE_DARK_ON)
}
```

**Comment by dshokouhi** [comment]
@balloob so far that just forces dark mode we are supposed to be able to use `FORCE_DARK_AUTO` but at least in the emulator its not switching and defaults to light theme.

![image](https://user-images.githubusercontent.com/1634145/89695095-a2d23c80-d8c7-11ea-8a0b-fce4feb3925c.png)
