### ISSUE TITLE
Notifications can no longer have blank titles

### ISSUE THREAD

**Issue by markgaze** [home-assistant/android#718]
**Home Assistant Android version:**

2.1.0-4-ge42d4c2-243-full

**Android version:**

10

**Phone model:**

Pixel 4XL

**Home Assistant version:**

0.113.3

**Last working Home Assistant release (if known):**

Worked on previous build of the app

**Description of problem:**

Notifications can no longer have an empty `title`.

The notify integration allows for `title` to be optional, as documented here: https://www.home-assistant.io/integrations/notify/

Since updating to the latest build overnight, my notifications all include a title of "Missing" which I can see in #712 (when converting from HTML)

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

![Screenshot_20200809-112225.png](https://user-images.githubusercontent.com/16718355/89729997-a46c4380-da32-11ea-8ed6-c5a86c40cd6d.png)

Notification shows like the above when sending:

```
message: Test
```

**Additional information:**

**Comment by chriss158** [comment]
Ah i See. Will fix this :thumbsup:

**Comment by markgaze** [comment]
Awesome, thank you!

**Comment by chriss158** [comment]
Thanks @JBassett  👍

**Comment by JBassett** [comment]
@chriss158 hope you don't mind, we just want to get a release out before Core releases 114 so we have support for the dark mode as soon as people start using it!

**Comment by chriss158** [comment]
No problem 👍  Just one thing i wanted to fix is missing content on collapsed notification. On my oneplus the message is missing if collapsed. No problem on the emulated pixel 3a device.

**Comment by dshokouhi** [comment]
@chriss158 BTW feel free to join us on discord #devs_mobile_apps we normally try to discuss these things there about what else may need to be included in a release.

**Comment by markgaze** [comment]
Tested on the new version and it works, only weird thing was the first notification said "None" rather than the `message` but subsequent ones were fine. Thanks for the quick turnaround on this issue 😊
