### ISSUE TITLE
Skip biometric auth prompt

### ISSUE THREAD

**Issue by noam148** [home-assistant/android#719]
**Home Assistant Android version:**
2.1.0

**Android version:**
10.0

**Phone model:**
Xiaomi A2 Lite

**Home Assistant version:**
0.113.3

**Description of problem:**
When the biometric auth prompt shows up and you leave the app by switching to another app. After returning to HomeAssistant the biometric auth promt is gone and have access to the app (with blue enabled)

**Screenrecord of problem:**
[https://youtu.be/x2CQS05EcQM](https://youtu.be/x2CQS05EcQM)

**Additional information:**
`biometricPrompt.authenticate(promptDialog)` inside `Authenticater.kt` will be called but something in 
`BiometricPrompt.java` goes something wrong at: `private void authenticateInternal(@NonNull PromptInfo info, @Nullable CryptoObject crypto)`. But not enough time to find out

**Comment by JBassett** [comment]
Should be fixed by #722
