### ISSUE TITLE
the device_tracker entity for the app sometimes doesn't update along with the geocoded sensor entity

### ISSUE THREAD

**Issue by terrance-liang** [home-assistant/android#724]
Hi developers, 

Gratefully thanks for your efforts on the android app, the rapid progress can be seen by millions of android users.

however, recently we crashed with this issue as the title, See details In the community post,

https://community.home-assistant.io/t/device-tracker-not-updateing-gps-location-gecodedlocation-does/210003

_Originally posted by @jdbrookes in https://github.com/home-assistant/android/issues/681#issuecomment-669890636_

**Comment by dshokouhi** [comment]
Can you confirm what app version is having this issue?

**Comment by terrance-liang** [comment]
> Can you confirm what app version is having this issue?

Hi, thanks for caring about this issue. In my case, it's 2.1.0-239-full, from GooglePlay

**Comment by dshokouhi** [comment]
Update to 2.1.1 which was released recently, it contains a location accuracy fix.  See if that helps.

**Comment by terrance-liang** [comment]
Hi @dshokouhi, thanks for the updating, It's been two days I updated to 2.1.1, it's likely well functioning.

**Comment by dshokouhi** [comment]
Thanks for getting back to us, going to close this issue now.  If you see any issues in the future please feel free to open a new issue.
