### ISSUE TITLE
Status bar is not readable when the Android Night Light function is enabled

### ISSUE THREAD

**Issue by anybody84** [home-assistant/android#725]
**Home Assistant Android version:** 2.1.0-7

**Android version:** 10

**Phone model:** Samsung Galaxy S9

**Home Assistant version:** 0.113.3

**Last working Home Assistant release (if known):** n/a

**Description of problem:** Status bar is not readable when the Android Night Light function is enabled. 

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/37036776/89757941-ee166600-dae6-11ea-9c26-2500689dfa1d.png)

**Additional information:** With the PR [#716](https://github.com/home-assistant/android/pull/716) there has been resolved an issue [#433 ](https://github.com/home-assistant/android/issues/433). However, now the status bar is not readable when using a light theme in HA and the Night Light function on the mobile. It seems like a decision about the font color on the status bar is being made based on the HA theme and not on the status bar background color.

**Comment by chriss158** [comment]
Can you explain what the night light function does? Never heard of that function. On my one plus i have a night mode function which disables just the blue light, but doesn't change the color of the statusbar or system.

**Comment by anybody84** [comment]
@chriss158, sorry for confusing you. It was rather about Dark Theme, not the Night Light. So, if it's enabled the status bar becomes unreadable.
This is how it looks when it's off:

![image](https://user-images.githubusercontent.com/37036776/89884520-f4314300-dbc9-11ea-84d9-c44c6a8d657b.png)

And when it's on:

![image](https://user-images.githubusercontent.com/37036776/89884570-0ad79a00-dbca-11ea-81f6-f2af50040185.png)

It affects also the bottom bar:

![image](https://user-images.githubusercontent.com/37036776/89885018-a9fc9180-dbca-11ea-84d7-b749f7a9f29b.png)

[This](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme) also can be useful if you need more details.

**Comment by dshokouhi** [comment]
@anybody84 so to confirm you have dark mode on the device enabled and what theme are you using? Google light theme?

**Comment by anybody84** [comment]
@dshokouhi, yes, correct, Google light theme.
Just FYI - I also use dark mode enabled on my device + Google dark theme, but for these combination everything looks good.

**Comment by chriss158** [comment]
If i enable dark mode and using the google light theme, it will work on the emulated pixel 3a device. 
Looks like samsung overwrites the statusbar color in dark mode not matter which color is set by the app. Do you have other apps with the same behaviour?
So you have a dark statusbar and light theme? Normally it should be a light statusbar and the light theme.
Can you test the opposite. Using normal/day mode and set a dark theme. Is then the statusbar light or dark ?

**Comment by dshokouhi** [comment]
@chriss158 so just now I was able to reproduce it on my pixel locally.  I loaded up "Google Light Theme", called `frontend.set_theme` to ensure the status bar would change, force closed and opened the app to make sure it pulled in teh value.  Then enabled dark theme on my device

![image](https://user-images.githubusercontent.com/1634145/90063273-f533a480-dc9d-11ea-94c3-0fc20672b99f.png)

**Comment by anybody84** [comment]
@chriss158, no, I don't have any other apps with the same behaviour. When I use the normal/day mode on my device and a dark theme, then the status bar is also dark with white characters, which also looks good.

**Comment by chriss158** [comment]
Please check if set the theme "Backend-selected" in your profile of the HA mobile app. Then set frontend.set_theme to Google Light Theme.

**Comment by anybody84** [comment]
Not really. I always have backend-selected theme on my mobile app and an automation which uses frontend.set_theme service to change the theme. When I do it manually it helps until I restart the app. Then the issue appears again.

**Comment by chriss158** [comment]
Ok now i reproduced it. Looks like change of statusBarColor is not respected.
