### ISSUE TITLE
Creating widget action - "ADD FIELD" and "ADD WIDGET" buttons are invisible

### ISSUE THREAD

**Issue by juicejuice** [home-assistant/android#729]
**Home Assistant Android version:** 2.1.1-249-full

**Android version:** Reproducible on 9.0 and 10.0

**Phone model:** Samsung Galaxy Note 10+ 5G and Galaxy Tab A 7

**Home Assistant version:** 0.113.3

**Last working Home Assistant release (if known):** HA Android 2.1.0-239-full

**Description of problem:** After updating to latest release of HA Android app, it becomes difficult to add a new widget as the two action buttons are invisible. It seems you can still tap the empty space where the button should be and it will perform the relevant action.

**Traceback (if applicable):**

```

```

**Screenshot of problem:** 
![Screenshot_20200811-164144_Home Assistant](https://user-images.githubusercontent.com/5318048/89865881-e0013c00-dbf1-11ea-9729-d8abb6815d2b.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
Seems to be an issue when the device theme is set to light, in dark mode it looks to be fine.
