### ISSUE TITLE
Unable to add widgets

### ISSUE THREAD

**Issue by michalszymura** [home-assistant/android#733]
**Home Assistant Android version:** 2.1.1-1-g4354e81-250-full

**Android version:** 9.0

**Phone model:** Samsung Galaxy S8+

**Home Assistant version:** 0.113.3

**Last working Home Assistant release (if known):**

**Description of problem:** 
I am unable to add any widget.
There is no button to add the widget.
When hitting back it just cancels the creation of a widget.

**Screenshot of problem:**
![Screenshot_20200811-173908_Home Assistant](https://user-images.githubusercontent.com/10345171/89925238-0aa3c280-dbfb-11ea-8f03-cd476d7dc113.jpg)

**Comment by dshokouhi** [comment]
This was actually just recently fixed in #732  please wait for the new build to publish to the play store :) the version will be 2.1.1-3
