### ISSUE TITLE
Next Alarm Filter

### ISSUE THREAD

**Issue by fti7** [home-assistant/android#737]
**Is your feature request related to a problem? Please describe.**
The new Next Alarm Sensor on Android reports all Alarms, including Timers etc.
![image](https://user-images.githubusercontent.com/7014664/90019538-d7bb0680-dcae-11ea-942b-611231234940.png)

**Describe the solution you'd like**
It would be very cool to filter Apps from which this Data is reported. Like only from Sleep as Android or the System Wakeup Clock

**Comment by dshokouhi** [comment]
I am not sure we can get that data, we are just grabbing whichever is the next scheduled alarm from the AlarmManager.

https://developer.android.com/reference/android/app/AlarmManager.AlarmClockInfo

**Comment by fti7** [comment]
In Tasker, you can specify Filter for Packages/Apps

https://tasker.joaoapps.com/userguide/en/help/eh_alarm_changed.html
"You can restrict the app that triggers this event by specifying the Package field. Use the helper to easily select the app to use there."
So should be possible somehow :-)

**Comment by dshokouhi** [comment]
We have to check the pending intent that gets sent back, I tried to see if I can quickly grab but did not seem that easy.  Maybe someone else with more know how can do that.  Too bad taskers source isn't open to see how they did it.

**Comment by dshokouhi** [comment]
I spoke too soon, will add the package name as an attribute :) Thanks for the request!  Adding a filter may be a bit much since we don't have sensor settings but this should give you what you need for now :)

![image](https://user-images.githubusercontent.com/1634145/90025824-6c9c1080-dc6b-11ea-84f4-90cb25577e0b.png)

**Comment by fti7** [comment]
@dshokouhi  thanks! yes should be possible with an attribute + an automation
But if you ever add Sensors Settings, please consider to filter it also on the Phone itself :-)
