### ISSUE TITLE
Dark mode not showing properly

### ISSUE THREAD

**Issue by klejejs** [home-assistant/android#738]
**Home Assistant Android version:**
2.1.1-4-g7b0e28f-253-full
**Android version:**
10
**Phone model:**
Sony XZ1 Compact, running stock android
**Home Assistant version:**
0.114
**Last working Home Assistant release (if known):**
-
**Description of problem:**
When system-wide dark mode is enabled on the phone, everything in app seams inverted. Colors are not fully black, some pictures are inverted and choosing dark mode in HA settings turns on light mode. Opening in browser works fine.
**Traceback (if applicable):**

```

```

**Screenshot of problem:**
This is how it looks in the app:
![WhatsApp Image 2020-08-12 at 16 37 04](https://user-images.githubusercontent.com/24546950/90021675-42be0a80-dcba-11ea-9ebc-3fb9528db2fe.jpeg)
This is how setting look in the app, when dark mode is enabled:
![WhatsApp Image 2020-08-12 at 16 37 04 (1)](https://user-images.githubusercontent.com/24546950/90021727-52d5ea00-dcba-11ea-83c5-d3c974492601.jpeg)
This is how it looks normally in browser, with system-wide dark mode enabled:
![WhatsApp Image 2020-08-12 at 16 37 04 (2)](https://user-images.githubusercontent.com/24546950/90021843-71d47c00-dcba-11ea-870f-4a292b8beb95.jpeg)

**Additional information:**

**Comment by dshokouhi** [comment]
Do you have force override dark mode enabled in your developer settings? This is odd I don't see the same behavior on my Pixel, I wonder if Sony is doing something different here.

**Comment by klejejs** [comment]
I will check, I think it really might be connected to webview, as the software I have is a custom rom very similar to Pixel and also Chrome displays it fine.

**Comment by klejejs** [comment]
I figured it out. It was a webview problem. Had to update the application.

**Comment by dshokouhi** [comment]
Thanks for letting us know :) I think its time to add "update webview" to our troubleshooting steps lol
