### ISSUE TITLE
Add separator between entity state widget state and attribute

### ISSUE THREAD

**Issue by klejejs** [home-assistant/android#756]
**Is your feature request related to a problem? Please describe.**
Currently entity state and attribute in entity state widget are just appended in one sentence.

**Describe the solution you'd like**
An option in setup screen to choose a separator to put between entity state and attribute in the widget.

**Additional context**
I know all of the widget issues I have submitted are very simple fixes and I would be glad to fix them, but, as I have never used Kotlin before, I trust someone else could do that. It would be much easier and quicker for them, than for me to setup the environment and understand the language. Thank you in advance. ;)

**Comment by dshokouhi** [comment]
@klejejs I actually just got started with Kotlin....its not that bad if you want to dive in :)

**Comment by klejejs** [comment]
@dshokouhi Ok, if you say so, I might try to dive in this weekend.
