### ISSUE TITLE
Show Entity States in an Persistent Android Notification

### ISSUE THREAD

**Issue by fti7** [home-assistant/android#759]
**Is your feature request related to a problem? Please describe.**
No, just an Enhancement

**Describe the solution you'd like**
I would like to see some/multiple HA Sensors/States directly as an Persistent Android Notification.
Like Room Temperatures and Security Status Entities
This would be very handy if you quickly want to see them (Also without unlocking the Phone)

Many Apps like Weather Forecast, Bitcoin Tracker, Advanced Battery Sensors are already using this approach.

Optional Features:
* Open App/URL on Tap on the Notification (e.G. to jump an an specific Lovelace page)
* Show last Updated time of an Sensor

Other good benefit would be that the HASS App will have higher Priorities in Android for their Background Jobs.
Apps like Tasker etc. also creates an low-prio Persistent Notifcation to prevent to get killed

Example:
![image](https://user-images.githubusercontent.com/7014664/90248793-a6227680-de39-11ea-8959-db20b89501f6.png)

**Comment by dshokouhi** [comment]
So if we did decide to move forward with a persistent notification for better location/sensor tracking I think this feature would give it a good purpose too. The only issue is that the states will not be in sync since we have to poll the state in order to update it and we don't want it to drain so we would need to find a happy medium there.

**Comment by dshokouhi** [comment]
So the app is unable to get entity state updates as it can be battery draining and we currently have to poll for updates.  However one thing you can do today is to send yourself a persistent notification and update the content of the notification to achieve the same effect.  You control the data and the frequency of updates from HA itself by just updating the notification as you need to.
