### ISSUE TITLE
Ghost Screen Bug

### ISSUE THREAD

**Issue by JoseMlCuevas** [home-assistant/android#760]
After some last updates, the app begins to show ghost screen, I don't know why or the reason, I uninstalled CUSTOM HEADER, THEMES,  etc. but nothing, I touch screen and it disappears but few moments come back, the ghost screen appear on any part of the screen, not always on top, I reinstalled the app, Update the Hassio but it still there, With other apps don't happen that happens with HA app. Please check the link to see the screen
Any idea?

https://1drv.ms/u/s!AqeKnbJNYNG7gdFnSTLTWlGi1JzxXw?e=Zryvqf

Thanks

**Comment by dshokouhi** [comment]
When you submit an issue a issue template should be presented that requests information we need in order to properly help you out.  This issue lacks a lot of information we request.  Could you add that information here please?   Make sure to fill in everything.

The template is located here: https://github.com/home-assistant/android/issues/new?assignees=&labels=bug&template=Bug_report.md&title=

**Comment by JoseMlCuevas** [comment]
Sorry, I forget that information. Here is the information:

**Home Assistant Android version:**
2.1.1-249-full
**Android version:**
android 8.0
**Phone model:**
Android car Radio 
px5
**Home Assistant version:**
0.114
![IMG_5663](https://user-images.githubusercontent.com/50666586/90279277-e9c7b100-de36-11ea-8df6-01df29f637f8.jpg)
![IMG_5733](https://user-images.githubusercontent.com/50666586/90279289-f21fec00-de36-11ea-9a34-50cd48295d2f.jpg)

**Comment by dshokouhi** [comment]
Can you check on that device if Android System Webview is up to date? It should be on v84

**Comment by JoseMlCuevas** [comment]
In this case, I'm not sure because it doesn't show anything about it, Android car Radio cannot be updated. It shows only that:

![about](https://user-images.githubusercontent.com/50666586/90403642-457c7f00-e06f-11ea-93b5-5ce66adc23cf.jpg)

![RAdio about](https://user-images.githubusercontent.com/50666586/90403680-4d3c2380-e06f-11ea-8d4a-86fa75bfbae8.jpg)

**Comment by dshokouhi** [comment]
Sorry I meant this application should be up to date: https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US

**Comment by JoseMlCuevas** [comment]
I Will Install and I let know you what happened. Thank you

**Comment by JoseMlCuevas** [comment]
HI, I installed the last Webview but the problem continues, I notice that the problem is only on the frontend maybe when it refresh or something like that because when I use the menu you can see the ghost under the menu, please check the picture.
![WhatsApp Image 2020-09-23 at 13 57 15](https://user-images.githubusercontent.com/50666586/94050827-c7657380-fda4-11ea-8ac7-131897518c01.jpeg)

**Comment by JoseMlCuevas** [comment]
In fact, you right, the problem was the Webview, the problem was that it was disabled, and never update, to update I had to disable chrome first to Webview update. So the problem is resolved.  Thank you very much dshokouhi.
