### ISSUE TITLE
Phone permissions should be requested when we attempt to enable the phone sensor.

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/android#762]
**Is your feature request related to a problem? Please describe.**
It is not easily apparent that if you were already onboarded in the app that you need to grant phone permissions, currently we only ask for them during onboarding.  As this is already in beta I am opening this as a feature request.  We may want to apply similar logic to the location sensors if they have a similar issue.

**Describe the solution you'd like**
The app should prompt the user for the proper permissions when we attempt to enable a disabled sensor that requires certain permissions to be granted.

**Additional context**
Just makes the app more friendlier so users don't wonder why the sensor is not reporting anything once enabled because it does not have permissions.

**Comment by klejejs** [comment]
When I enabled phone state sensor, the permission window actually popped up for me. It wasn't onboarding, I haven't cleared the app data for decades.

**Comment by dshokouhi** [comment]
Oh really? hmm ok maybe this is already fixed lol 

We have had a lot of changes being done lately so hard to keep track, trying to make sure I don't forget.  Closing now.
