### ISSUE TITLE
When in dark mode android status bar has dark tint

### ISSUE THREAD

**Issue by blair287** [home-assistant/android#767]
**Home Assistant Android version:**

**Android version:**

10

**Phone model:**

OnePlus 7

**Home Assistant version:**

0 114

**Last working Home Assistant release (if known):**

Dunno

**Description of problem:**

When android in dark mode status bar is tinted darker than theme colour but when android in light theme status bar colour matches. This is using a custom theme not the new theme in 0.144.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

![Screenshot_20200815-123308](https://user-images.githubusercontent.com/44187409/90311609-9320ac80-def4-11ea-9bcd-23c6c17c6173.jpg)
![Screenshot_20200815-123442](https://user-images.githubusercontent.com/44187409/90311610-94ea7000-def4-11ea-92a6-dd323b4883df.jpg)

This is in light theme on Android system colour matches.
![Screenshot_20200815-124319](https://user-images.githubusercontent.com/44187409/90311641-ff031500-def4-11ea-8282-1e8e57fd9356.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
This was fixed in #749 should be available in the latest app beta.

**Comment by blair287** [comment]
> This was fixed in #749 should be available in the latest app beta.

How do I get the beta please?

**Comment by dshokouhi** [comment]
https://play.google.com/apps/testing/io.homeassistant.companion.android
