### ISSUE TITLE
Add carrier information as sensor

### ISSUE THREAD

**Issue by jonpaterson** [home-assistant/android#768]
**Is your feature request related to a problem? Please describe.**
Trigger different notifications based on carrier. Useful for roaming and multi carriers such as Google Fi.
**Describe the solution you'd like**
sensor with carrier name / ID
**Describe alternatives you've considered, if any**
since we have phone state this should be able to be retrieved as per https://developer.android.com/reference/android/telephony/SubscriptionManager?hl=pt-br#getActiveSubscriptionInfoList%28%29
**Additional context**

**Comment by dshokouhi** [comment]
I think carrier information can be useful.  Maybe even if device is roaming and/or mobile data turned off. We do need to be mindful of privacy related information.  Telephony provides a lot of stuff so lets proceed with caution when adding things here.

**Comment by skynetua** [comment]
We can extend current PhoneState sensor with this attributes using existing telephony manager. But they are available only for currently active sim.
Or we can create new sensors, like sim_1, sim_2 in ios companion using subscription manager. However it will require min api >= 22

**Comment by dshokouhi** [comment]
I think matching the current iOS sensors would be great personally, we can always mention what android version certain sensors are available in.
