### ISSUE TITLE
Android beta node red text unable to read.

### ISSUE THREAD

**Issue by blair287** [home-assistant/android#769]
**Home Assistant Android version:**

See below screen shot

**Android version:**

10

**Phone model:**

OnePlus 7

**Home Assistant version:**

0.114

**Last working Home Assistant release (if known):**

**Description of problem:**

I know it's a beta just wanted to give a heads up in node red the text is white and is practically impossible to read on any nodes that are not dark colours. 

On the none beta app text is black and much easier to read. Not sure why the app is changing the text colour.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

![Screenshot_20200815-182828](https://user-images.githubusercontent.com/44187409/90318053-84062280-df25-11ea-8134-702aeeb77c9e.jpg)
![IMG_20200815_182846](https://user-images.githubusercontent.com/44187409/90318057-85cfe600-df25-11ea-836a-728aa1ab0a40.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
Can you please fill in the rest of the issue template?  Some important bits are missing.  Specifically check that you are indeed running the latest beta, we had some additional dark theme fixes. Should be on `2.1.1-19`

**Comment by blair287** [comment]
> Can you please fill in the rest of the issue template? Some important bits are missing. Specifically check that you are indeed running the latest beta, we had some additional dark theme fixes. Should be on `2.1.1-19`

Sorry I am definitely running the lastest beta I joined the beta on Google play and updated app. 

![Screenshot_20200816-100708](https://user-images.githubusercontent.com/44187409/90330904-44cce580-dfa8-11ea-89f3-e4f9be419756.jpg)

**Comment by dshokouhi** [comment]
Can you check the same behavior in Chrome for Android? Make sure the profile is set to dark so the theme is dark.

**Comment by blair287** [comment]
> Can you check the same behavior in Chrome for Android? Make sure the profile is set to dark so the theme is dark.

Chrome in dark mode on Android is ok text is black as it should be.

Might have also seen the widgets on dark mode the icons are not showing but I'll check it out before opening an issue.

![Screenshot_20200817-002503__01](https://user-images.githubusercontent.com/44187409/90346385-52be4d00-e020-11ea-8d92-d7076ad26e2e.jpg)

**Comment by dshokouhi** [comment]
is the situation better now? I think now that we can set the proper theme of the app it should no longer be an issue.
