### ISSUE TITLE
Next Alarm State Unavailable, Local Time empty

### ISSUE THREAD

**Issue by holdestmade** [home-assistant/android#774]
**Home Assistant Android version:**
2.1.1-18-grc6610a-267-full
**Android version:**
10
**Phone model:**
Huawei P20
**Home Assistant version:**
0.113.1
**Last working Home Assistant release (if known):**
na
**Description of problem:**
The Next Alarm sensor always shows as `Unavailable`, even with an alarm set. The `Time in Milliseconds` attribute does populate though but `Local Time` and `Package` does not
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
What app did you use to set a alarm? Also what time for `Time in Milliseconds` do you see? Is it just 0?

**Comment by holdestmade** [comment]
Just the built in clock app. The Time in Milliseconds changes from 0 to a large number of milliseconds to the alarm, this is for 8am tomorrow: 1597647600000

**Comment by dshokouhi** [comment]
Ok I wonder if this is because a manufacturer override.  Are you able to get the logcat details? I think you may be hitting an exception after we grab the trigger time.

**Comment by holdestmade** [comment]
Not sure what logcat is ?

**Comment by dshokouhi** [comment]
Your time in milliseconds is correct...mine is `1597756500000` and its in 2 days..

Logcat is how you get the android logs so we can see what the cause of the error is.  Currently we are getting the correct trigger time however the call to get the package name is failing and thats why we dont see a proper state and other data.  What is the built in clock app? Its not the Google Clock is it?

**Comment by holdestmade** [comment]
It's just the Clock app that came with the phone

**Comment by holdestmade** [comment]
The milliseconds is right if you take the last 4 zeros off

**Comment by dshokouhi** [comment]
We are converting that value to UTC time and not local time.  Local time happens elsewhere.  See below where it converts it properly

![image](https://user-images.githubusercontent.com/1634145/90338153-4e505080-df9c-11ea-93b3-d4b50183e811.png)

**Comment by holdestmade** [comment]
Ah, got ya

**Comment by dshokouhi** [comment]
Can you run a quick test and see if using this app to set the alarm time works better? https://play.google.com/store/apps/details?id=com.google.android.deskclock&hl=en_US

Trying to see why we get one value and not the others.

**Comment by holdestmade** [comment]
Yes, works OK with that one:

`2020-08-17T07:30:00.000Z`

Local Time: Mon Aug 17 08:30:00 GMT+01:00 2020
Time in Milliseconds: 1597649400000
Package: com.google.android.deskclock
friendly_name: EML-L09 Next Alarm
icon: mdi:alarm
device_class: timestamp

**Comment by dshokouhi** [comment]
Ok so this is an issue with the actual alarm app that Huawei uses, it seems they are not using the `AlarmManager` API properly here.  I will submit an update to perform the state calculations before grabbing the package and we can see if that fixes this.

**Comment by holdestmade** [comment]
OK thanks, I'll just use the google app for now

**Comment by dshokouhi** [comment]
Can you try the debug APK from here to see if the state and other attributes populate? I don't expect to see `package` from the Huawei app but you should get everything else.

https://github.com/home-assistant/android/actions/runs/210963634

**Comment by nelsonblaha** [comment]
I think I have this on my OnePlus 6 in Lineage 18.1. It may be a OnePlus issue in my case as well, but it causes a misleading/annoying permanent "enable 1 sensors" switch at the top of Manage Sensors that can never be set.

**Comment by dshokouhi** [comment]
> I think I have this on my OnePlus 6 in Lineage 18.1. It may be a OnePlus issue in my case as well, but it causes a misleading/annoying permanent "enable 1 sensors" switch at the top of Manage Sensors that can never be set.

The one sensor is actually the BLE transmitter that by default is excluded from enabling all sensors due to battery concerns. You will need to enable it separately then the toggle will remain on.
