### ISSUE TITLE
Add description to "Next Allarm sensor"

### ISSUE THREAD

**Issue by Gobolin80** [home-assistant/android#777]
If is it possible, it would be nice to add the "description of the Next Alarm" to the attributes in next alarm sensor.
It would be very usefull to create an automation for a SPECIFIC alarm (ie: working days alarm).
now it is impossible to identify if the "next alarm" is the one that interests me.
Thank you too much for you beautiful work!

**Comment by dshokouhi** [comment]
Not sure if this is possible, the API does not get that description from the app.

I thought maybe this would provide it but it does not: https://developer.android.com/reference/android/app/AlarmManager.AlarmClockInfo#describeContents()

**Comment by dshokouhi** [comment]
Closing as this is just not possible with the API's that we have, the best solution here would be to use separate apps so you can determine what the alarm is based on the `package` attribute.
