### ISSUE TITLE
Black App Theme - switch low contrast

### ISSUE THREAD

**Issue by lopitos1joao** [home-assistant/android#782]
App version: 2.2.1-247-full (android).
Android phone version: 10
Brand and model: Xiaomi Mi 8 

Problem: I updated the app. Now it has default black theme. 

Some button's are not showing very well. 
![Screenshot_2020-08-17-16-19-56-980_io homeassistant companion android](https://user-images.githubusercontent.com/60098253/90416887-f5bba900-e0aa-11ea-8a3d-61b8a85b36b8.jpg)
This is an image from app. 

![IMG_20200817_162232](https://user-images.githubusercontent.com/60098253/90416958-0704b580-e0ab-11ea-9481-8a175edecb1c.jpg)
This is the same screen shot from web browser. 

Same problems at Supervisor screen and others.

It's only a Theme issue. If I press the switch it works and display:
![Screenshot_2020-08-17-17-01-41-945_io homeassistant companion android](https://user-images.githubusercontent.com/60098253/90417239-5d71f400-e0ab-11ea-94c0-718f0a80c508.jpg)

**Comment by dshokouhi** [comment]
What version of HA is this?

**Comment by lopitos1joao** [comment]
HA version: 0.113.3

**Comment by dshokouhi** [comment]
This will probably be fixed by #780 also when you update to HA 0.114 dark theme will work a lot better as the frontend now supports it.

**Comment by lopitos1joao** [comment]
I have news. I have updated to version 0.114.2 it works. New screen shot:
![IMG_20200817_182520](https://user-images.githubusercontent.com/60098253/90425055-0e31c080-e0b7-11ea-9d60-658a57253eb2.jpg)

I will close this.

**Comment by lopitos1joao** [comment]
Work fine after update of HA to last stable version. Thanks.
