### ISSUE TITLE
Cover buttons are reversed

### ISSUE THREAD

**Issue by vangorra** [home-assistant/android#787]
**Home Assistant Android version:**
2.2.1-274-full
**Android version:**
10
**Phone model:**
Pixel 4
**Home Assistant version:**
0.114.2
**Last working Home Assistant release (if known):**
Always working. Works in browser.
**Description of problem:**
Cover open/close buttons are disabled in the wrong way. If the cover is closed then only the closed button is enabled.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![Screenshot_20200819-062809~2](https://user-images.githubusercontent.com/1752370/90641515-2d7b3b80-e1e6-11ea-8518-e875ff07bdbc.png)

**Additional information:**

**Comment by dshokouhi** [comment]
Could you share a screenshot of how it looks different in chrome for android?  Personally I see the same results 

android app:
![image](https://user-images.githubusercontent.com/1634145/90649910-0fb2d400-e1f0-11ea-8cf7-e33cd1149cc6.png)

web:
![image](https://user-images.githubusercontent.com/1634145/90649958-1b9e9600-e1f0-11ea-9365-de82c9a601fd.png)

**Comment by vangorra** [comment]
Here it is in chrome on Android.
![Screenshot_20200819-074925~2](https://user-images.githubusercontent.com/1752370/90650368-a5e6fa00-e1f0-11ea-832c-893479ae78f7.png)


I figured it out. When your phone is using the dark theme, the companion app mixes up the buttons.

**Comment by dshokouhi** [comment]
Hmm so we actually only display a webview to the HA frontend and don't change anything.  Are the buttons really disabled or do you think its a theming issue?  We do have #780 which should correct some of the issues we have around themes but I am not sure on this issue.

**Comment by vangorra** [comment]
Just checked. It's a theming issue, I can stop press the button and it works.

**Comment by dshokouhi** [comment]
Closing as all theming issues should be resolved in 2.3.0, if it is still an issue please comment back with a screenshot again so we can look into it :) Only asking for a screenshot so we can see how it looks with all the recent changes.

In 2.3.0 you can now set the theme of the app independently from the system and the frontend so it should be good now.
