### ISSUE TITLE
Add DND switch to get & set Do Not Disturb status

### ISSUE THREAD

**Issue by os131** [home-assistant/android#807]
**Is your feature request related to a problem? Please describe.**
I'm setting DND each evening and remove it as soon as I wake up. I wish it could be automated using HA. My phone have no possibilities to schedule DND.

**Describe the solution you'd like**
Just add a switch for the purpose

**Describe alternatives you've considered, if any**
I can use tasker to do it but I do prefere grouping every automatioon in one place

**Additional context**

**Comment by dshokouhi** [comment]
I think for now we can probably get the state of DND on the device, currently we do not have a way for HA to send data to the app so we can perform actions.  I can see it being useful to control some things like to remove the device from DND if the alarm was tripped.  

We do also have notification channels which can allow you to override DND for certain notifications in case you are not aware :)
