### ISSUE TITLE
No icons in widgets

### ISSUE THREAD

**Issue by Norien** [home-assistant/android#808]
**Home Assistant Android version:**
2.2.1-274-full
**Android version:**
10
**Phone model:** 
Pixel 2 XL
**Home Assistant version:**
0.114.3
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
Widgets never have icons but otherwise work perfectly
**Traceback (if applicable):**
N/A

**Screenshot of problem:**
![Screenshot_20200824-095139](https://user-images.githubusercontent.com/8930713/91052439-73be0980-e5ef-11ea-84a2-12ce1aeb285d.png)

**Additional information:**
Icons were present upon initial setup of widget but dissapeared upon phone restart and have never come back!

**Comment by dshokouhi** [comment]
Were these widgets created before or after we added the material icon list? I personally have not seen the issue where they disappear upon restart.  I wonder if they just need to be recreated to persist?

**Comment by Norien** [comment]
Yupp, looks like problem is solved with new update. Thanks guys!
