### ISSUE TITLE
Weird colors when dark mode is on

### ISSUE THREAD

**Issue by bokub** [home-assistant/android#820]
**Home Assistant Android version:** 2.2.1-274-full

**Android version:** 10

**Phone model:** Huawei P20

**Home Assistant version:** 0.112.2

**Last working Home Assistant release (if known):**

**Description of problem:**

Hi,

I use a custom card on my home assistant which is [rgb-light-card](https://github.com/bokub/rgb-light-card).

This card displays colored circles to change the color of my lights, like this:

<img width="500" src="https://user-images.githubusercontent.com/17952318/91273986-54a1b200-e77e-11ea-81c6-7c96c56cd0c4.png" />

What's weird is that when I enable "dark mode" in my Android settings, the light colors are converted to a dark version, which is not expected:

<img width="500" src="https://user-images.githubusercontent.com/17952318/91274409-ed383200-e77e-11ea-825f-f252ce33e4d8.png" />

Note that it happens **only** in the Android app, and not in the mobile browser

**Is that a problem with the app? Or with the card?**

<details>
  <summary>BTW, the HTML of the card is very simple</summary>
    <img src="https://user-images.githubusercontent.com/17952318/91275174-13120680-e780-11ea-975b-d59a5e0d8547.png" />
</details>

**Comment by dshokouhi** [comment]
This should be fixed in the latest beta, please check that version or wait for the next play store release. If you still have an issue comment back here and we can reopen this.

**Comment by bokub** [comment]
I can confirm that the bug is fixed in the latest beta 🎉 

Thanks
