### ISSUE TITLE
notify.mobile_app_vog_l29

### ISSUE THREAD

**Issue by tgrendal71** [home-assistant/android#821]
**Home Assistant Android version:**
2.2.1-19g101e519-293-full

**Android version:**
10
**Phone model:**
Huawai p30 pro
**Home Assistant version:**
0.114.2
**Last working Home Assistant release (if known):**
Never 
**Description of problem:**
I only se one phone notify.mobile_app_vog_l29, but i have two huawai p30 pro phones. see screenshots. Messages is beeing send to worng phone 

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/41505917/91277324-f6c39900-e782-11ea-9ba5-f575c0161226.png)
![image](https://user-images.githubusercontent.com/41505917/91277467-2672a100-e783-11ea-9676-868794449987.png)

**Additional information:**

**Comment by klejejs** [comment]
Did you restart Home Assistant after registering both phones in the app?

**Comment by tgrendal71** [comment]
Yes. 
I have restarted it many times. I haqve also rebotet the host many times (raspberry pi 3b+)

**Comment by dshokouhi** [comment]
You need to rename your device since you have multiple devices of the same model.

https://companion.home-assistant.io/docs/troubleshooting/faqs/#notify-service-call-is-too-similar-or-not-showing-up-in-android

**Comment by dshokouhi** [comment]
Closing this issue now, please reply back if you still have an issue after following the linked steps above.
