### ISSUE TITLE
Issue with focus on input_text field

### ISSUE THREAD

**Issue by jaswalters** [home-assistant/android#825]
**Home Assistant Android version:**
2.2.1-274-full
**Android version:**
10
**Phone model:**
Pixel 4
**Home Assistant version:**
0.114.3
**Last working Home Assistant release (if known):**
Never Attempted
**Description of problem:**
I created a lock management interface. When using the web interface this works fine. If you type a code in the code field and click submit it runs its course.

The issue in the app is that if you type in a code it does not know the code is in the field unless you click outside of the input_text field. So even though you entered a code in the code field and click submit it does not know the code exists unless you click outside of the input_text field.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/34176786/91356937-73279d80-e7be-11ea-8628-3d93a3e89d36.png)

**Additional information:**

**Comment by dshokouhi** [comment]
does this issue happen in chrome for android?

**Comment by jaswalters** [comment]
> does this issue happen in chrome for android?

Yes

**Comment by bramkragten** [comment]
This is a custom card? We wont accept that issue on the frontend.

(use the event `value-changed` instead of `change`)

**Comment by jaswalters** [comment]
I'm confused. You asked a question and then closed before I could respond. This is not a custom card. It is the input_text if that is what you are asking. The submit button is a custom card but that is not the issue. The issue is from within the app the data is not being recognized unless you click outside of the entities card. The entities card is not custom.

**Comment by jkrangel** [comment]
@bramkragten This is not a custom card - I am having the same issue as @jaswalters with a standard entities card and the built in text_input entity. As @jaswalters noted, this only happens on the iOS app
