### ISSUE TITLE
Native UI

### ISSUE THREAD

**Issue by fernandex00** [home-assistant/android#829]
is there native ui plans for this app?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

With a native ui, the loading times will be reduced as they don't need to load the page every moment

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment]
What device are you experiencing bad load times with?  The app is designed to use the HA frontend as a webview so given you don't have a bunch of custom stuff it should load very fast.

**Comment by poelzi** [comment]
I was using ha-client for some time now which I find more pleasant since the loading time is much lower. Unfortunately, it is not developed anymore.
Maybe some better state caching could decrease loading time.
