### ISSUE TITLE
Lock app function only when not at home

### ISSUE THREAD

**Issue by masterfish1** [home-assistant/android#840]
**Is your feature request related to a problem? Please describe.**
I really like the idea of the "Lock app" function but don't feel it necessary to be active at home or in certain zones, for example.

**Describe the solution you'd like**
An option to only have "Lock app" activated when at home, perhaps simply based on whether the phone is connected to the Home Network SSID, for example. 

**Describe alternatives you've considered, if any**
None

**Additional context**
N/A

**Comment by masterfish1** [comment]
Still hoping this can be possible.

**Comment by dshokouhi** [comment]
So I saw that you mentioned zones in the original request however that won't work well for our minimal users who cannot have a location tracker. I think it makes sense to use the connected wifi SSID defined as the Home SSID in App Configuration for this. Based on the title that seems to be the goal here anyways :)

**Comment by kongo09** [comment]
Wouldn't the home SSID not be enough for a device tracker to identify the home zone?

**Comment by dshokouhi** [comment]
> Wouldn't the home SSID not be enough for a device tracker to identify the home zone?

these users can already use the wifi connection sensor to translate if they are at home, the device tracker from `mobile_app` itself is tied to GPS location and is only available in the full flavor of the app.

**Comment by kongo09** [comment]
One other option would be to tie this to the HA URL used.
- internal URL: no lock
- external URL: lock
No complexities with zones, trackers and the like.

**Comment by dshokouhi** [comment]
> One other option would be to tie this to the HA URL used.
> - internal URL: no lock
> - external URL: lock
> 
> No complexities with zones, trackers and the like. 

This would actually follow the same conditions the URL switching does today. Internal URL gets used based on the connected wifi SSID.

**Comment by alexeiw123** [comment]
> One other option would be to tie this to the HA URL used.
> 
> * internal URL: no lock
> * external URL: lock
> 
> No complexities with zones, trackers and the like.

Some users access home assistant using the same URL internally and externally, using NAT loopback.

This feature would be great.
