### ISSUE TITLE
Only connect when not on Local Network

### ISSUE THREAD

**Issue by giffordj** [home-assistant/android#852]
**Home Assistant Android version:**
2.3.0-306-full
**Android version:**
10
**Phone model:**
Oneplus 6t
**Home Assistant version:**
0.114.4
**Last working Home Assistant release (if known):**

**Description of problem:**
Only connects when using an outside network, doesn't connect when local wifi.
Using https://hass.jg555.com, with cloudflare.
**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![Screenshot_20200831-111402](https://user-images.githubusercontent.com/19445255/91752469-4509db00-eb7b-11ea-83da-0bf661126a12.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
Could you give us more details about your local network? I see you are attempting to use `https` locally.  Do you need to accept the SSL cert in a browser? If so then this won't work, your best bet is to use NAT loopback on a router.  More on the networking aspect here in case it can help: https://companion.home-assistant.io/docs/troubleshooting/networking

**Comment by giffordj** [comment]
Using cloudflare, the certificate is on there servers which provides the auth correctly, but home on wifi, you have to accept the certificate. I tried modifying the dns entries, but that broke all the addons. 

I'm using a juniper firewall, did the loopback nat, but still asked for the certificate since it wasn't hitting cloudflare. I'm going to see if there is a way to force the android to use the mobile data connection for this app only.

**Comment by giffordj** [comment]
Came up a with a simple solution. On the OnePLUS 6t under wifi & internet, there is an option for private dns. If you bypass the local DNS, it will do a lookup using an external DNS. By doing this, it uses the WAN IP, and gets the correct SSL certificate. I specified google as my private dns.

**Comment by alexanderhale** [comment]
@dshokouhi would it be possible to add a configuration option in the companion app to "auto-accept" invalid SSL certificates? I have the same issue where I can access the Home Assistant UI in the browser if I accept certificates, but it is not possible to do so in the app.

The "proper" solutions I've read about are NAT loopback or split-brain DNS, both of which require setup - if it was possible to accept bad SSL certificates in the app, that would be much easier.

**Comment by memphisraynz** [comment]
Hi, I was trying to find a place to request this as well. If there could be an option to ignore SSL for internal networks. I can only guess this is the reason I get the above error. Internal URL is set and works, but receives an SSL error as the internal URL is https://192.168.x.x:8123/

**Comment by grigio** [comment]
yeah https://192.168.x.x:8123/ works in mobile browser but not with the mobile app.

I'd like to do something with Traefik a passthrough but I didn't find a way yet

**Comment by giffordj** [comment]
I ended up setting up cloudflare on the dynamic connection. Not easy, but
it works flawlessly now.

**Comment by dshokouhi** [comment]
Closing this issue as we don't support bypassing certificate checks, glad you guys were able to find a solution!

Ref: https://github.com/home-assistant/android/issues/448#issuecomment-724724968
