### ISSUE TITLE
Do not hold proximity sensor lock

### ISSUE THREAD

**Issue by pkern** [home-assistant/android#856]
**Is your feature request related to a problem? Please describe.**
With version 2.3.0-306-full the proximity sensor is kept open indefinitely until the app is terminated.

**Describe the solution you'd like**
Proximity sensory usage should be opt in, not opt out. Otherwise a distracting dot will be shown on the display while the display is on.

**Describe alternatives you've considered, if any**
n/a

**Additional context**
See https://github.com/home-assistant/android/pull/801#issuecomment-684019752

**Comment by dshokouhi** [comment]
What device are you experiencing this issue with? We unregister from the sensor the moment we get a `onSensorChanged` event from Android regardless of the reading.

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt#L84

**Comment by pkern** [comment]
Unfortunately I cannot answer you this question but I will forward the link. Thank you. (The fast response is really appreciated and I'm sorry that I can't go into more detail and am also unable to just step through the program to see where that hangs. I do know from the log that the sensor is held active for hours specifically by Home Assistant.)

**Comment by skynetua** [comment]
I'm not sure, but probably we need to register/unregister receiver for application context and not like:
`mySensorManager.registerListener(this, proximitySensors, SENSOR_DELAY_NORMAL)`

For now we can re-create sensor manager object before receiver unregistered.
Correct me if i'm wrong.

**Comment by dshokouhi** [comment]
@skynetua we actually are creating it based off the latest context we have: https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt#L47  

The issue here is that the `onSensorChanged` event is never being triggered for this device so more than likely this user never see's any data from this sensor in Home Assistant.  Maybe we can help alleviate this by using a boolean value to keep track of when we create the listener so we don't create multiple.  That however won't fix this issue if we never get the expected event.

**Comment by pkern** [comment]
In this case there are many proximity sensor events.

I have some trouble understanding the lifecycle here but it looks like `SensorWorker` is spawned periodically every 15m, enqueues an update of all sensors and then terminates. Could it be that it registers a listener and within the short period of time that it takes to inquire all sensors it never receives an update and then the whole worker is suspended/terminated as `doWork()` finishes? As I understand it the proximity sensor will only send an update if there's actually a state change. That seems to be implied by the demo code. The demo code is also clear that the listener needs to be deregistered when the app is suspended/paused. And that does not seem to happen with the current build of Home Assistant.

**Comment by asjmcguire** [comment]
For what it's worth, on my Pixel3a - the app is excluded from battery optimisation, the sensor is enabled in the app - but it has never shown any other state than "near" in Home Assistant.

**Comment by dshokouhi** [comment]
So the proximity sensor by default is now disabled since #875 is merged. Its up to the user if they want to enable the sensor or not.  Existing users who do not wish to have this sensor will need to disable it.  Going to close this now that the sensor is opt in. Thanks for the report!

**Comment by pkern** [comment]
Thank you. Does your default infrastructure correctly apply to existing installations?

And should I open a separate bug about the sensor lock being held when the feature is turned on. But it feels like there's still a bug here if the proximity event never fires.
