### ISSUE TITLE
states.sensor.XXX_geocoded_location.attributes.Location is now a string??

### ISSUE THREAD

**Issue by i00** [home-assistant/android#859]
## The problem

The geocoded_location.location sensor used to have location expressed as an array of 2 numbers for example:
[-27.468556999999997, 153.0240753]
Thus calling: {{ states.sensor.XXX_geocoded_location.attributes.Location[0] }} would return -27.468556999999997
Now it is a string:
'[-27.468556999999997, 153.0240753]'
Thus calling: {{ states.sensor.XXX_geocoded_location.attributes.Location[0] }} returns '['

## Environment

- Home Assistant Core release with the issue: 0.114.4
- Last working Home Assistant Core release (if known):
- Operating environment (OS/Container/Supervised/Core): Container
- Integration causing this issue: Mobile App?
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/mobile_app/ ?

## Problem-relevant `configuration.yaml`

```yaml
{{ states.sensor.XXX_geocoded_location.attributes.Location[0] }}
```

## Traceback/Error logs

```txt

```

**Comment by dshokouhi** [comment]
@i00 thanks for confirming....was this working fine previously right? do you happen to know what app version it was working on and what version you have today?

**Comment by skynetua** [comment]
It is changed after #809. We store all attribute values as string to db.
`@ColumnInfo(name = "value")
  val value: String`

**Comment by dshokouhi** [comment]
thanks @skynetua I see the same issue on `boolean` attributes too, need to wrap my sensor templates in strings now.  Did not notice this until now :)

**Comment by i00** [comment]
@skynetua ... so is this going to be fixed?..
Can't the sensor be aware of what the data is for each property (ie. .Location is a array of numbers) and cast the properties out to the correct data type?

**Comment by skynetua** [comment]
@i00 it can, I'm not sure we need to fix it right now. We have got statement not to send non-static values as attributes but as separate sensors. So probably it will be changed soon.

**Comment by dshokouhi** [comment]
I think for the meantime we can use some jinja magic to strip the string quotes right?

**Comment by i00** [comment]
Thanks for the merge fixes my issue :D as i can now use the new lat / long attributes.
