### ISSUE TITLE
Excessive calls to webhook update_location 

### ISSUE THREAD

**Issue by balloob** [home-assistant/android#861]
**Home Assistant Android version:** dev (latest stable = 2.3.0). Also in 2.3.0

**Android version:** Q

**Phone model:** emulator

**Home Assistant version:** 115 dev

**Last working Home Assistant release (if known):**

**Description of problem:**

I see excessive calls to the `update_location` webhook with identical location reports. This from dev shows 17 [logs](https://gist.github.com/balloob/bd75828c5b507a6a96761a26574bf383). I've seen prod logs with 34/35 calls.

@bramkragten and I have tracked it down to be introduced by #816. This is already halved in dev thanks to @anyuta1166 in #843 but 17 calls is still too much.

CC @JBassett

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by balloob** [comment]
I think short term we should consider reverting #816 and #843 while we work on a more suitable solution.

**Comment by anyuta1166** [comment]
Well, I've made the fix for myself but it is kinda ugly, so I didn't make a pull request.
I have separated updateSensors into 2 functions: updateSensors (all except location) and updateLocationSensor (update loication).
Works fine for me except it is very ugly.

**Comment by anyuta1166** [comment]
I can prepare a PR if you wish. Ugly solution is better than reversal.

**Comment by anyuta1166** [comment]
The core issue is that update of **any** sensor triggers updating **all** sensors.

**Comment by mcfrojd** [comment]
When i look at my logs i can see my wifes phone (she is at home) send a whoppng 102 location updates in a 4 second time period.
Link to redacted log: https://pastebin.com/DTdZPuvM
I guess this might be the big reason for the app to have started to use a lot more battery lately
