### ISSUE TITLE
Some issues with geo location sensor

### ISSUE THREAD

**Issue by sajikur** [home-assistant/android#868]
**Home Assistant Android version: 2.3.3-full

**Android version: 10

**Phone model: OnePlus 5T

**Home Assistant version: HassOS 4.12 HA version 0.144.4

**Last working Home Assistant release (if known): all

**Description of problem: geo sensor is stuck in home location. Compass phone is blocked. No geo data send to HA

**Traceback (if applicable):**

```

**Screenshot of problem:**

**Additional information: I've switch off geolcation location, backgroud and zone location and compass is turned on. Sometime need to reboot phone to read this geo informations

**Comment by anyuta1166** [comment]
And I've told many times to either increase MINIMUM_ACCURACY or make it user configurable...

MINIMUM_ACCURACY = 200 is too low to accept cell-tower based geolocation updates.

**Comment by sajikur** [comment]
> And I've told many times to either increase MINIMUM_ACCURACY or make it user configurable...
> 
> MINIMUM_ACCURACY = 200 is too low to accept cell-tower based geolocation updates.
> 
> This way we mainly receive only GPS-based updates (only when a GPS navigation app is opened) and Wi-Fi-based updates (only when ( Wi-Fi is on **or** background Wi-Fi tracking is enabled ) **and** there are Wi-Fi APs known by Google nearby).
> 
> No GPS & no Wi-Fi APs nearby = FAIL.

perfect! Well, how many meters are the right value?

**Comment by anyuta1166** [comment]
> perfect! Well, how many meters are the right value?

It is discussable. I've set it to 5000 for sure. My family often travel to a rural area and accuracy values of 2-3 km are common there.

Anyway, the accuracy threshold is not user configurable now. I've built my own build with manual code changes.

**Comment by sajikur** [comment]
I take advantage of your availability. Can the google maps component on HA 
conflict with geo location on ANDROID APP? Thanx

In data 2 settembre 2020 11:07:33 Anna Tikhomirova 
<notifications@github.com> ha scritto:

**Comment by dshokouhi** [comment]
So this bug report is for a HA integration? The logs suggest its not the app but the Google Maps integration which is not the same thing.  These 2 integrations are completely separate.

**Comment by sajikur** [comment]
I've both. So I thought could be a conflict between two requests on Google api
In data 2 settembre 2020 14:43:37 Daniel Shokouhi 
<notifications@github.com> ha scritto:

**Comment by anyuta1166** [comment]
There is no conflict.
Obviously you are not getting location info from Home Assistant app because accuracy is above the threshold.
And logs from HA integration confirm that.

**Comment by dshokouhi** [comment]
So at one point there was a proposal to allow the user to configure the minimum accuracy: https://github.com/home-assistant/android/pull/168

The decision instead was to implement a more sane default value at the time: https://github.com/home-assistant/android/pull/181

Maybe its time we make this configurable?

FWIW the minimum accuracy we see is actually double that of the default radius in HA.  On top of that when we check the final location we double it again to 400m, at least for the device tracker. It might be a good value to lets users adjust for their own location.  The issue originally was that no accuracy was used and users in California were being marked as in the US, and you can imagine that is not good either.  Sometimes I would get teleported from my own house to 2 miles away and that was also not good.

Maybe a smarter approach would be to disregard the accuracy check if the last reported location was close to what we currently got?  This way if you are at home (and we all know GPS isn't good indoors) it will continue to send frequent updates instead of waiting a long time for the accuracy to get better.  I noticed myself sometimes my accuracy is at 20 then it jumps to 342 then it jumped again 80000 (yes 80k) its very very jumpy but its also the data we get back from Google.

@sajikur can you please update your post and remove the traceback and instead supply a screenshot or some data from the android app? That way this issue doesnt get moved/closed on accident.

**Comment by sajikur** [comment]
> 
...
> 
> @sajikur can you please update your post and remove the traceback and instead supply a screenshot or some data from the android app? That way this issue doesnt get moved/closed on accident.

done! ;)
in this moment app works correctly, Geolocation from app and add on sharing google position are the same (I've both)
![Cattura](https://user-images.githubusercontent.com/6140894/92016460-a89a3100-ed52-11ea-9f28-3f68be2254d0.PNG)

**Comment by dshokouhi** [comment]
This is to be expected.  Both Google Maps and the Android app uses the fused location provider.  Anytime any location request is sent to the phone all of them get the update.  That is why if you use google maps navigation you get near real time updates into HA because its the same location data.

**Comment by anyuta1166** [comment]
> The decision instead was to implement a more sane default value at the time

The default is not sane for me. Even in the city with Wi-Fi turned off I see accuracy values of 500-1000 m.

> Maybe its time we make this configurable?

I hope so.

> the minimum accuracy we see is actually double that of the default radius in HA.

I wish the radius of the default location in HA would be configurable too, but that the question to the core, not android app.

**Comment by dshokouhi** [comment]
> I wish the radius of the default location in HA would be configurable too, but that the question to the core, not android app.

It most certainly is for any zone: https://www.home-assistant.io/integrations/zone/#home-zone and https://www.home-assistant.io/integrations/zone/#radius

**Comment by anyuta1166** [comment]
> It most certainly is for any zone: https://www.home-assistant.io/integrations/zone/#home-zone

> have a radius of 100 meters. To override this, create a zone configuration and name it ‘Home’.

Oh, I didn't know that I can override the default radius. I thought it is impossible. Thank you very much for the hint!

**Comment by sajikur** [comment]
so what's your advice? Disable google maps sharing with google and HA accounts?

**Comment by sajikur** [comment]
> 
> 
> This is to be expected. Both Google Maps and the Android app uses the fused location provider. Anytime any location request is sent to the phone all of them get the update. That is why if you use google maps navigation you get near real time updates into HA because its the same location data.

so what's your advice? Disable google maps sharing with google and HA accounts?

**Comment by dshokouhi** [comment]
Its up to you on what works best for your situation.  One thing you can do with the google maps integration today is to set a custom accuracy, thats something we dont currently offer in the app.

https://www.home-assistant.io/integrations/google_maps/#max_gps_accuracy

**Comment by sajikur** [comment]
I've an automation that informs with telegram msg when a family smartphone 
reach or leave a zone. Many times we have a msg bombing (reach leave reach 
leave reach leave...). Any ideas?

In data 2 settembre 2020 22:29:30 Daniel Shokouhi 
<notifications@github.com> ha scritto:

**Comment by andriej** [comment]
Regarding the topic - is there any chance for phone location to have 'keepalive' and make it's location unavailable in HA?
Example: phone is at home, report it's location and goes off/airplane mode. 
In HA all automations will act as it's owner is still there, even if it's not.

**Comment by sajikur** [comment]
I think it's impossible to do

In data 3 settembre 2020 09:25:47 Andrzej <notifications@github.com> ha 
scritto:

**Comment by anyuta1166** [comment]
I think so. Goes off/airplane mode means no internet connection. But we need internet connection to send the state to HA.

**Comment by andriej** [comment]
So it's something to be implemented for mobile_app on HA's side (HA didn't receive updates in regular interval - make sensor unavailable)

**Comment by anyuta1166** [comment]
> HA didn't receive updates in regular interval - make sensor unavailable

This currently may happen if you left the phone intact for some time and it goes into doze mode. Than updates are sent at irregular intervals until you wake up the phone by grabbing and unlocking it.
@dshokouhi made an attempt to make updates to be regular by adding a foreground notification, but it seems that it doesn't work, at least for me and my phone.

**Comment by sajikur** [comment]
This is the problem. Sharing position out from HA is correct. With ha 
automation creates msg bombing with 2 last position, home and work

In data 3 settembre 2020 09:44:32 Anna Tikhomirova 
<notifications@github.com> ha scritto:

**Comment by JBassett** [comment]
> So it's something to be implemented for mobile_app on HA's side (HA didn't receive updates in regular interval - make sensor unavailable)

That's probably something that would need to be added at the device_tracker level for all device trackers to optionally take advantage of.



> This is the problem. Sharing position out from HA is correct. With ha automation creates msg bombing with 2 last position, home and work In data 3 settembre 2020 09:44:32 Anna Tikhomirova <notifications@github.com> ha scritto:
> […](#)
> HA didn't receive updates in regular interval - make sensor unavailable This currently may happen if you left the phone intact for some time and it goes into doze mode. Than updates are sent at irregular intervals until you wake up the phone by grabbing and unlocking it. @dshokouhi made an attempt to make updates to be regular by adding a foreground notification, but it seems that it doesn't work, at least for me and my phone. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Not saying we shouldn't attempt to fix, but https://www.home-assistant.io/blog/2020/07/22/release-113/#automations--scripts-bonus-cool-down might help.

**Comment by anyuta1166** [comment]
> That's probably something that would need to be added at the device_tracker level for all device trackers to optionally take advantage of.

Only after updates from app will always be regular and reliable.

As I said earlier if you leave the phone intact for some time it goes into doze mode. Than updates are sent at irregular intervals until you wake up the phone by grabbing and unlocking it. If you implement this logic (HA didn't receive updates in regular interval - make sensor unavailable) - it will flap between available and unavailable all night.

Unfortunately, sensor worker with foreground notifications didn't help. The phone still doesn't trigger periodic work every 15 minutes as it should when it sleeps.

**Comment by dshokouhi** [comment]
> The phone still doesn't trigger periodic work every 15 minutes as it should when it sleeps.

Its not designed to trigger exactly at every 15 minutes, its up to the device on when it wants to allow it given defined conditions.  Its just that after 15 minutes its ready for the next update.

```
Periodic work is intended for use cases where you want a fairly consistent delay between consecutive runs, and you are willing to accept inexactness due to battery optimizations and doze mode

The interval period is defined as the minimum time between repetitions. The exact time that the worker is going to be executed depends on the constraints that you are using in your WorkRequest object and on the optimizations performed by the system.
```

**Comment by anyuta1166** [comment]
> Its not designed to trigger exactly at every 15 minutes, its up to the device on when it wants to allow it given defined conditions. Its just that after 15 minutes its ready for the next update.

So my device wants to trigger it in up to 2 hours intervals when it sleeps. How will it work with this logic (HA didn't receive updates in regular interval - make sensor unavailable)? As I said it will flap between available and unavailable all night.

**Comment by anyuta1166** [comment]
> Theres a separate feature request to set all entities to unknown or unavailable if we didn't receive updates but I think that should be handled in `mobile_app` and not the app.

Yes, I know. And I repeat, it will not work correctly while the app sends the updates at irregular intervals - from 15 minutes up to 2 hours.

**Comment by sajikur** [comment]
The problem is this: the following two automations are used to detect the entry or exit from a zone. The GOOGLE MAPS addon correctly indicates the position (sometimes with delay) and for this you see it in the code. If I enter the position given by the app in the code, the sms bombing starts. So I think it's an app bug


  - alias: 'Attiva notifiche Casa Francesca1'
    initial_state: on
    trigger:
      - platform: zone
        entity_id: device_tracker.google_maps_xxxxxxxxxxxxxxxxxxxxxxxxxx
        #entity_id: device_tracker.mi_a1
        zone: zone.home
        # Event is either enter or leave
        event: enter
        
    action:
#       - service: ifttt.trigger
#         data_template: {"event":"batterie", "value1":"Francesca è arrivata/partita a/da Casa"}
       - service: notify.tele
         data:
           message: "Francesca è arrivata a Casa"        

#--------------------------------------------------------------------------------------------------------------------------------------------
           
  - alias: 'Attiva notifiche Casa Francesca2'
    initial_state: on
    trigger:     
      - platform: zone
        entity_id: device_tracker.google_maps_xxxxxxxxxxxxxxxxxxxxxxxxxx
        #entity_id: device_tracker.mi_a1
        zone: zone.home
        # Event is either enter or leave
        event: leave 
    
    action:
       - service: notify.tele
         data:
           message: "Francesca è partita da Casa"

**Comment by rs443** [comment]
Just noticed in my logs that a location request with an accuracy of 317 was recorded, which logged me as away for a few minutes. Should MINIMUM_ACCURACY = 200 discard that?

`2020-09-06 18:25:46 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload for type update_location: {'location_name': '', 'gps': [N.2593577, E.3161809], 'gps_accuracy': 317, 'speed': 0, 'altitude': 78, 'course': 0, 'vertical_accuracy': 2}`

![home](https://user-images.githubusercontent.com/46565725/92334053-a6094580-f08a-11ea-804e-31036868972b.JPG)

I like the idea of a user configurable variable.

**Comment by dshokouhi** [comment]
@rs443  we double it when our last attempt:

https://github.com/home-assistant/android/blob/master/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L350
