### ISSUE TITLE
Feature Request - Public IP sensor whilst on 4G/LTE

### ISSUE THREAD

**Issue by pandanz** [home-assistant/android#882]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem but is a feature request that would enable other services to be accessed whilst away from home.

**Describe the solution you'd like**
It would be great for the Android App to provide a sensor to home assistant with the public IP address the phone is currently using whilst on 4G/LTE.

The use case is, so i can allow that single IP address through my firewall to access services via Nginx into my home network. This will minimise my potential exposure of opening up my firewall. I use Nabu Casa for HA but I would use this feature for other services. I can dynamically update my firewall via API/SSH so i would create an automation that is triggered based on the public IP address changing.

**Describe alternatives you've considered, if any**
I currently use a VPN when I need to access services however having a single IP address allowed which can dynamically change in my firewall makes access much simpler.

**Comment by skynetua** [comment]
I've played around with this feature a bit and could get only internal ip in my cellular network. I'm not sure that any provider assign real public ip. Probably we need to use some external services, like `https://api.ipify.org?format=json` if we are going to add this.
