### ISSUE TITLE
HA Companion for Android doesn't respect theme choice

### ISSUE THREAD

**Issue by dunxd** [home-assistant/android#883]
**Home Assistant Android version:**
2.3.3-full
**Android version:**
10
**Phone model:**
Motorola One XT1941-4
**Home Assistant version:**
0.114.4
**Last working Home Assistant release (if known):**

**Description of problem:**
When selecting Light theme, this is applied in the application settings page, but not any pages for controlling Home Assistant.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![Screenshot_20200905-141222](https://user-images.githubusercontent.com/16608541/92305741-e761fe00-ef81-11ea-9476-89d097d777ee.png)
![Screenshot_20200905-141344](https://user-images.githubusercontent.com/16608541/92305755-0bbdda80-ef82-11ea-9412-30aad7a68876.png)

**Additional information:**
Numerous reports of this in Play store reviews.

**Comment by dshokouhi** [comment]
What setting is your HA profile theme set to?

**Comment by dunxd** [comment]
I don't know where to find that setting. It will be whatever is the default as I don't recall seeing this option.

**Comment by dshokouhi** [comment]
Go to your Home Assistant profile, open up the menu at the top left then hit the icon at the very bottom for the user profile where you set the device theme and other user settings.

**Comment by dunxd** [comment]
Ok. I found it by clicking on my username at the bottom of the Home Assistant Companion menu. It was set to dark, but I don't recall changing it. Changing it to Auto or fixed it to respect the setting in App configuration across the whole interface.

It's rather confusing to have a second option for this. I guess this changes this issue from a bug to an enhancement - only have one place to change display settings.

**Comment by dshokouhi** [comment]
We have to offer 3 options because not all users use their device the same.  Some like the system theme to be light, some want it dark, some want HA to be the opposite, some want HA to be light and settings to be dark etc...  By having all these options its the best of both worlds for all users.  Also the frontend option is not the same as what is offered in the app, the app has to offer a way to let the user see things how they like.  If you look into the theming issues in GitHub you can get a better understanding of why this route was chosen.

**Comment by dunxd** [comment]
What I mean is that there are two separate places to apply settings relating to the theme used.

- the App configuration page
- the User profile page

I can understand why there might be two settings, but to keep them in two separate places is very confusing, hence all the reviews complaining about the theme not working. Would it be possible to link the two pages together somehow, or put some explanation so users can find their way around more easily?
