### ISSUE TITLE
Feature Request: Caller number

### ISSUE THREAD

**Issue by SeraphimSerapis** [home-assistant/android#892]
**Is your feature request related to a problem? Please describe.**
To implement something like a call log across multiple devices, I'd love to have access to phone numbers I call/that call me via a sensor.

**Describe the solution you'd like**
A sensor that exposes the phone number of incoming/outgoing calls.

**Describe alternatives you've considered, if any**
None

**Additional context**
A similar solution can be achieved for landlines using the [FritzBox Callmonitor](https://www.home-assistant.io/integrations/fritzbox_callmonitor/) integration.

**Comment by daniele-athome** [comment]
Is this feature present on the Google Play version? I can't find it nor the required permission... (using version 2021.1.2-full on Android 9)

**Comment by dshokouhi** [comment]
> Is this feature present on the Google Play version? I can't find it nor the required permission... (using version 2021.1.2-full on Android 9)

This was removed as soon as it was added because our app doesn't meet google criteria for the permission request. We had no choice but to remove it to continue publishing updates. It may make an appearance in the minimal version.

**Comment by daniele-athome** [comment]
I see. Isn't there some approval process to request exceptions you could use? This is indeed a legitimate and reasonable use of the permission IMHO.

**Comment by dshokouhi** [comment]
We did and they did not accept our app for them.

**Comment by daniele-athome** [comment]
Ok thank you. A real shame :-(
