### ISSUE TITLE
[0.115.0b0] media browser thumbnails not displayed

### ISSUE THREAD

**Issue by ctalkington** [home-assistant/android#893]
**Home Assistant Android version:** 2.3.3

**Android version:** 10

**Phone model:** Samsung S9+

**Home Assistant version:** 0.115.0b0

**Last working Home Assistant release (if known):**

**Description of problem:**

the new media browser doesnt show media item thumbnails. works in chrome for android though. must be webview issue?

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

![Screenshot_20200907-192140_Home Assistant](https://user-images.githubusercontent.com/209757/92421683-6c464680-f13f-11ea-95da-1f4ae20076ca.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
Is it a mixed content issue? The app can't display `http` images over `https` connection, we had a few bugs around this.

**Comment by ctalkington** [comment]
oh that likely makes sense. wonder if well need a proxy for these images to enable consistent behavior

**Comment by dshokouhi** [comment]
Yea might be same issue as #566 and #206 based on research it may be integration specific but I am not 100% sure :)
