### ISSUE TITLE
App Configuration menu item not working correctly on HA 0.115.0b0

### ISSUE THREAD

**Issue by jesserockz** [home-assistant/android#896]
**Home Assistant Android version:** `beta-355-567e60a-full`

**Android version:** `10`

**Phone model:** `Moto One Vision`

**Home Assistant version:** `0.115.0b0`

**Last working Home Assistant release (if known):** `0.114.4`

**Description of problem:**
The `App Configuration` item that is inserted into the sidebar in the app is not working properly in the new HA beta release.
It works if you put the sidebar into the new "edit mode" by holding one of the items, then tapping `App Configuration` and I believe this has to do with that new functionality.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Thanks for the report this is actually a frontend issue already reported here: https://github.com/home-assistant/frontend/issues/6827

**Comment by jesserockz** [comment]
Ah thanks, didn't think to look in the frontend repo.
