### ISSUE TITLE
Add `minimal` to F-Droid 

### ISSUE THREAD

**Issue by licaon-kter** [home-assistant/android#897]
Now that the flavor exists, can this be used on F-Droid?

A simple Yes/No will suffice as the app builds fine.

Ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7387

**Comment by balloob** [comment]
Yes

**Comment by robbiet480** [comment]
@licaon-kter Please leave a comment on this issue once it is published on F-Droid.org. I see the merge request has been merged but can’t find it on F-Droid.org.

Thanks!

**Comment by licaon-kter** [comment]
Cycles can be seen realtime (UTC) here: https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=30&from=&hidebots=0&hideanons=1&hideliu=1&limit=500

**Comment by licaon-kter** [comment]
It's live...refresh your F-Droid repos. ;)

**Comment by stikonas** [comment]
Thanks, I can finally try this app :). Before this minimal flavour that app was not full FOSS.

**Comment by robbiet480** [comment]
Still not seeing it on search.f-droid.org?

**Comment by licaon-kter** [comment]
Strange yes: https://f-droid.org/packages/io.homeassistant.companion.android.minimal/

I'll open an issue asap

Also, always use the F-Droid client to get timely updates notifications and info on new apps ;)
