### ISSUE TITLE
[HELP] Possible to create a widget to make an announcement over google home devices?

### ISSUE THREAD

**Issue by scottismyname** [home-assistant/android#909]
I'm basically trying to create a widget to have one of my google home's speak a specific phrase.  In the home assistant web page, I can do this by going to the services page under development and using the following:

service: tts.google_translate_say
service data:
entity_id: media_player.living_room_home
message: 'May the Force be with you.'

I'm not sure if the android app allows a widget to be created like this? It's possible maybe the template widget, but I have no idea how to do so.  Choosing the service tts.google_translate_say under the service widget option doesn't even allow me to select an entity_id

Any help would be appreciated.

**Comment by dshokouhi** [comment]
Use the service call widget: https://companion.home-assistant.io/docs/core/android-widgets#service-call 

you may need to use the `Add Field` option to manually set the options you don't get.

![image](https://user-images.githubusercontent.com/1634145/92634842-bdfae800-f289-11ea-8447-b28975f72986.png)

**Comment by scottismyname** [comment]
@dshokouhi I tried this but it does not seem to be working.  The following is showing up in my log. I Have a feeling I'm just not formatting the data correctly:
voluptuous.error.MultipleInvalid: required key not provided @ data['entity_id']

**Comment by dshokouhi** [comment]
did you make sure to set the field to `entity_id` when you added it?

**Comment by scottismyname** [comment]
Yes, I attempted to setup again, and took a screenshot right before saving:
![Screenshot_20200909-133406](https://user-images.githubusercontent.com/9275733/92650422-56509700-f2a1-11ea-9e7e-60fdd8b11ce2.png)

**Comment by dshokouhi** [comment]
When you tap on `Add Field` only enter `entity_id` or `message` then enter the valid data in the new forms that get created

**Comment by scottismyname** [comment]
Ok now I feel like an idiot.  Thank you so much, it's working 👍
