### ISSUE TITLE
Last reboot sensor reports changing values

### ISSUE THREAD

**Issue by Hypfer** [home-assistant/android#910]
**Home Assistant Android version:** beta-367-3a39428-full

**Android version:** 9

**Phone model:** Moto Z3 Play

**Home Assistant version:** 0.114.3

**Last working Home Assistant release (if known):** /

**Description of problem:**

The last reboot sensor changes its value by a few seconds, even though the device isn't rebooted.
It's probably not a rounding error, since there can be 5s+ differences.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/974410/92634219-3dada480-f2d4-11ea-8f48-788a356a36d8.png)
![image](https://user-images.githubusercontent.com/974410/92634371-7ea5b900-f2d4-11ea-9395-9faf20a9be90.png)
![image](https://user-images.githubusercontent.com/974410/92634381-85ccc700-f2d4-11ea-862e-cbd17b834138.png)

**Additional information:**

It doesn't happen with the exact same version of the app running on a Samsung SM-T510 tablet with Android 10 so might either be a quirk with this particular phone _or_ Android 9.
Of course, the issue could also be load-related.

Looking a the code, there's really not much that could go wrong so I'm very confused
https://github.com/home-assistant/android/blob/c221e85fa4e5fbf0157bc3ce21394c1723cd3d36/app/src/main/java/io/homeassistant/companion/android/sensors/LastRebootSensorManager.kt#L53-L61

**Comment by dshokouhi** [comment]
You know I have yet to see this issue on my Pixel...this might be one of those device differences.  One thing we can consider doing is removing the seconds completely as I had already stripped out microseconds but it can still flip flop if its at that sweet spot.

**Comment by dshokouhi** [comment]
Another thing we can do is to check the value we last stored compared to the new value and only change it if its more than a few minutes difference.

**Comment by Hypfer** [comment]
As mentioned in the discord, the time used to calculate this value is by default getting synced with the mobile network.
So I've turned off the mobile network time sync option in the android settings and this is how the sensor looks like now:
![image](https://user-images.githubusercontent.com/974410/92700013-97eb4b80-f34e-11ea-8ab0-e32704836bb1.png)

E-Plus/O2/Telefonica Germany is known for recurring issues regarding the network time. This also explains why the Wifi-only Tablet doesn't show this behaviour, nor do other phones on non-broken carriers.

Maybe some cell towers have a slight clock offset or something like that? In any case, I guess we do have to fix this in the app since the carrier certainly is not able to carrier properly and won't be anytime soon.
