### ISSUE TITLE
Dark/Light theme not working 

### ISSUE THREAD

**Issue by seanomat** [home-assistant/android#913]
Pixel 3a, Android 10 (now 11, same thing),
Android System WebView 85.0.4183.81
Language: German
CompanionApp 2.3.3.-full
Home Assistant: HASSIO 0.114.4, default Theme
Custom components: HACS

Since the last update to the app, the change between light and dark theme does not have any visual effect:

![Screenshot_20200905-055913](https://user-images.githubusercontent.com/49898524/92690921-0fff4480-f342-11ea-8bfd-24101ca43531.png)
![Screenshot_20200905-055732](https://user-images.githubusercontent.com/49898524/92690923-1097db00-f342-11ea-86b2-31bc49e61b88.png)

Changing the theme in the user-settings in Home Assistant however works as expected:

EDIT: more precisely, the theme switching does work in the browser

![Screenshot_20200905-065004](https://user-images.githubusercontent.com/49898524/92691185-7c7a4380-f342-11ea-8574-23f7495677a3.png)
![Screenshot_20200905-064953](https://user-images.githubusercontent.com/49898524/92691186-7d12da00-f342-11ea-92d8-42ca3a518f2c.png)

**Comment by seanomat** [comment]
Man these screenshots are huge! No idea how to resize them

**Comment by dshokouhi** [comment]
There was a fix for the theme selection not working in localized versions of the app.  It is currently fixed in the current beta.  Keep in mind also that asides from the app setting you also want to make sure your user profile in HA matches what you expect.

**Comment by dshokouhi** [comment]
Sorry just realized I told you to come here to file a bug :) Reference: https://community.home-assistant.io/t/light-and-dark-theme-no-longer-follow-phone-theme/224072

**Comment by seanomat** [comment]
Yeah, just installed the new version 2.5.0 and theme switching in the app works again. Thank you!

**Comment by dshokouhi** [comment]
Thanks for reporting back!

**Comment by hockeymikey** [comment]
Updating to a web view version past 70ish worked for me.

**Comment by seanomat** [comment]
This ugly problem seems to have reared it:s head again.

Switching between light and dark theme in companion settings does nothing.

When I switch the language from German to English everything works as expected
