### ISSUE TITLE
Android 5.1/6 cant login!

### ISSUE THREAD

**Issue by sxx1314** [home-assistant/android#914]
**Home Assistant Android version:**
beta-367-3a39428-full
**Android version:**
Android 5.1/6
**Phone model:**
meilan note2
meilan 5s
**Home Assistant version:**
homeassistant 114.4  （docker）
**Last working Home Assistant release (if known):**
All versions cannot log in.
**Description of problem:**
Android 7/8/9/10 can log in normally, but Android5/6 cannot log in.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![S00910-19182457](https://user-images.githubusercontent.com/8444252/92722935-e9212c80-f39a-11ea-9577-3de028ceb803.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
Is this a custom ROM? Do you have Android System Webview installed as a system app?

**Comment by sxx1314** [comment]
> Is this a custom ROM? Do you have Android System Webview installed as a system app?


Using via browser is normal. Via is only 500kb, it depends on the system webview.

**Comment by dshokouhi** [comment]
I am talking about this app which is required to be a system installed app

https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US
