### ISSUE TITLE
Report battery state of connected bluetooth devices

### ISSUE THREAD

**Issue by insertjokehere** [home-assistant/android#916]
**Is your feature request related to a problem? Please describe.**
I have a terrible memory, and a pair of bluetooth headphones that need charging every few days. I often find myself turning on my headphones, only to find that they are out of battery

**Describe the solution you'd like**
In addition to reporting which bluetooth devices are connected, can the battery level of connected devices (if the device reports a battery level) be exposed as a sensor in Home Assistant? That way, I can send myself a notification reminding myself to charge my headphones when I get home

**Describe alternatives you've considered, if any**
I currently have a hacked-together solution using Tasker (listening for the `android.bluetooth.device.action.BATTERY_LEVEL_CHANGED` intent) and Appdaemon API calls, but it would be great if this worked "out of the box"

**Comment by kevjs1982** [comment]
Like insertjokehere I've hacked this sort of thing together but Tasker can be a bit unreliable.

What would be really useful in addition to the battery level is knowing where (Lat/Lng) they were last seen (for my use case the turn on/off location are the most useful but I can see that updating this as the phones location is updated would be sensible too), and what device they were last connected too, and when they were last seen

Useful for answering "where on earth did I leave my headset?" or "who's been using my headset?" type questions, but also triggering automations - my cycling headsets been turned off at the office, turn the lights off at home.

**Comment by dshokouhi** [comment]
We have recently made a release that allows users to register for any intent and retrieve the data from them.  You should now be able to do this using the Last Update Trigger sensor and registering for the intent you selected.  The app will then fire an event under `android.intent_received` along with all intent data for you to utilize.

https://www.home-assistant.io/blog/2021/03/04/android-2021-q1-releases/#intents-and-activities

Closing this issue as the original request is now handled by the app being able to send intent data to HA.
