### ISSUE TITLE
App Icon Long Press Action

### ISSUE THREAD

**Issue by jspanitz** [home-assistant/android#918]
**Is your feature request related to a problem? Please describe.**
There are certain things I will do on a regular basis that would be nice to be able to trigger them quickly.  I would like to have a app icon long press be able to trigger actions / scripts / automations / etc. 

**Describe the solution you'd like**
When pressing the HA App Icon a series of configurable selections should pop up which can then be selected to perform specific tasks.  These would be existing HA actions / scripts / automations.

**Describe alternatives you've considered, if any**
None other than opening HA and manually performing the same tasks.

**Additional context**

**Comment by skynetua** [comment]
@jspanitz  I'll add this soon.

**Comment by dshokouhi** [comment]
So how would this differ from using a button widget taht would allow you to trigger an automation/script/action?  It would be on the home screen still but with feedback to tell you if the call was successful or not.

**Comment by seanmccabe** [comment]
> So how would this differ from using a button service call widget taht would allow you to trigger an automation/script/action? It would be on the home screen still but with feedback to tell you if the call was successful or not.

Given I don't use widgets + I hate them, this would be very useful

**Comment by denilsonsa** [comment]
(Note: I'm not an Android developer, forgive any mistakes, this is based on my experience as an Android user.)

Long-press actions are essentially shortcuts, and they can be dragged and dropped onto the home screen. In addition, they can be put inside home screen folders (widgets can't). [Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher) displays both widgets and shortcuts in the "add widget" screen, and clearly labels shortcuts as such. Shortcuts can also be launched from other apps (again in Nova Launcher, it's possible to map home screen gestures to an arbitrary shortcut).

> So how would this differ from using a button service call widget [...]?

For the purposes of launching a service call, there is a large intersection between widgets and shortcuts. However, shortcuts are very lightweight, and can be used for stuff that widgets can't.

**Comment by skynetua** [comment]
@denilsonsa you are talking about pinned shortcuts. There are also static and dynamic shortcuts that shown in long-press menu. These are a bit different things. 
https://developer.android.com/guide/topics/ui/shortcuts

**Comment by jspanitz** [comment]
> @jspanitz I'll add this soon.

Just curious where this is in the pipeline

**Comment by jspanitz** [comment]
@skynetua Just curious where this is in the pipeline if at all

**Comment by mdegat01** [comment]
So with this enhancement we'd be able to create shortcuts to scripts and things and drop them on our home screen? I don't really use the long press menu on apps all that often but I would really like shortcuts. I'm not a big fan of widgets since they look kind of clunky and I can't put them into folders. Shortcuts look and work just like app icons so they're great.

Just trying to understand if the resolution of this issue will result in that or if I should create a separate feature request for that capability.

**Comment by seanmccabe** [comment]
No.
But you could have the Home Assistant app on the homescreen and be able to use shortcuts, there is still a limit on the number of app shortcuts available, so you couldnt have a ton of scripts ready to go.
The action would more likely be, hold app icon, get shortcuts to actions i.e. script, automation

**Comment by dshokouhi** [comment]
So I started to take a peak at whats entailed here.  2 things that stand out to me.  Apps are limited to publishing a total of 5 dynamic and static shortcuts combined.  Given the nature of static shortcuts it makes sense to only do dynamic for our purposes.  Most phone launchers only support displaying 4 shortcuts in the list too.

https://developer.android.com/guide/topics/ui/shortcuts#shortcut-limitations

With that said I am not sure how far along you are @skynetua but maybe I can get a MVP submitted to just take a user to a specific lovelace page as we already have part of the launch code ready. Afterwards we can add support for other actions like running a script but users need to know its limited to a total of 5 but possible only 4.

Also regarding the setup, shortcuts will need to be setup before being created as we need to provide an intent. The good thing is using our App Configuration we can store and let users adjust certain things as they see fit.

**Comment by skynetua** [comment]
@dshokouhi unfortunately I've lost my ssd with everything I did. I believe I'll come back to coding as soon as this pandemic ends and I return to my office. You can do it from scratch off you want. I'll share my experience if any questions occur.
