### ISSUE TITLE
Activate Script when Alarm Clock goes off.

### ISSUE THREAD

**Issue by asjmcguire** [home-assistant/android#923]
**Is your feature request related to a problem? Please describe.**
Right now, it is possible to use an overly complicated template to detect if now is the time the alarm was supposed to go off. But this is not a terribly user friendly solution, considering the on-going work the Home Assistant developers have been doing to reduce the amount of actual coding a new user needs to do to be able to make Home Assistant do things.

**Describe the solution you'd like**
The ability to simply choose an existing script you would like Home Assistant to trigger when the alarm goes off. This would also mean, that each person in a household could simply choose the script applicable to them, rather than having to code multiple automations that are monitoring the time of the next alarm. The app might also offer the possibility of only triggering the script, if the device is detected as being in the "home" state.

**Describe alternatives you've considered, if any**
Googling for 2 days to find examples of the overly complex automation needed to detect if now is the time the alarm is going off. This for example - is the accepted solution: 
`{{now().strftime("%a %h %d %H:%M %Z %Y") == (((state_attr('sensor.joes_galaxy_s10_next_alarm', 'Time in Milliseconds') | int / 1000) + 0*60 ) | timestamp_custom('%a %h %d %H:%M %Z %Y'))}}` from the thread https://community.home-assistant.io/t/how-to-use-next-alarm-sensor/221686/5 my current method of avoiding this need to template the automation, is to expose the script to Google Assistant, and then tell the Alarm Clock to trigger the Assistant Routine when the alarm is dismissed - but this of course, relies on there being an internet connection, and the whole ethos of Home Assistant is to keep things as local as possible.

**Additional context**
The phone, already knows what time it is now, and the time of the next alarm, it doesn't make sense for the phone to sit there doing nothing, leaving the server to waste cpu cycles constantly evaluating the template, when the phone knows now == alarm time.

**Comment by dshokouhi** [comment]
So IMO I think this is something that should be solved in HA core and the frontend.  There are many integrations that also provide a date/time sensor and they all suffer from the need to use templates for these sensors.  Sensors that are based on a date/time are required to send their state in UTC format so the frontend can display it in a neat way.  This could be a great WTH topic to help find the other integrations that can benefit from this.

Also the app does not keep track of the alarm itself, what the app does is send the next scheduled alarm event as soon as it is scheduled.  For example when you snooze your alarm it triggers a next alarm event and the app does not know if it was snoozed only that it is the next alarm that was scheduled.  Try to plan for this state change instead of doing the evaluation but keep in mind that if you set an earlier alarm then it will trigger the next alarm event so you may want to make a condition based on time.

**Comment by Skeletorjus** [comment]
I know this isn't exactly what you're looking for, but with Home Assistant 0.115 it is possible to evaluate a time triggered automation against a input_datetime, and it's also possible to set a input_datetime to a epoch timestamp.

With that in mind you can make an automation with a state trigger on `sensor.your_next_alarm` and puts it in a input_datetime like this:
```
service: input_datetime.set_datetime
entity_id: input_datetime.your_next_alarm
data:
  timestamp: >-
    {{ (state_attr('sensor.your_mobil_next_alarm', 'Time in Milliseconds') /
    1000) | int }}
```
You can then make an automation with this trigger to run your script:
```
trigger:
  - platform: time
    at: input_datetime.your_next_alarm
```

The only problem I've seen with this is that the epoch timestamp rendered by the template always is off within the range of +/- one minute, but I guess that's a separate issue.

**Comment by Mincka** [comment]
I like the OP idea but I think it would be even more powerful to set directly alarms (with or without recurrence) or timers (with looping option) in the app itself.

The app would be able to trigger anything at a predefined time in HA by calling the services (like it's done for the Service Button), so including a script (even with parameters).

Alternative: one of the scheduler or alarm projects available as custom components (so handle this in HA and not the app). Non-official and less user friendly.

Personally, I think phone alarms (current "next_alarm") should be kept to make your phone ring or whatever. Anyway, @Skeletorjus gave an alternative for what OP would like to do exactly.

**Comment by dshokouhi** [comment]
It is now possible to detect when an alarm has started going off with the addition of the Sleep as Android sensors in the latest beta.  If you use the app and use it to set an alarm you can get sensors that tell you various states of the alarm, such as if it was snoozed or dismissed or even when it is active. I think that might be good to close this for the original request as you can use HA to set off scripts based on this new sensor.

If the app were to try and keep track of the alarm that means we would use the alarm manager API to keep track of it in a battery friendly way which would then result in unwanted alarm events.  I think the correct approach here would be to use sleep as android as that app already has the logic desired.

**Comment by asjmcguire** [comment]
Thank you!
I am happy to accept this closes the request. I already use Sleep As Android.

**Comment by Mincka** [comment]
Is it possible to have metadata associated to the alarm like its name?
Maybe I am wrong but I don't see a way to associate a specific alarm with a specific script.

Like you said earlier, it would be a mess if you have multiple alarms.
> Try to plan for this state change instead of doing the evaluation but keep in mind that if you set an earlier alarm then it will trigger the next alarm event so you may want to make a condition based on time.

If I need to set an associated condition with the time (and/or date) in HA, I am just setting an "alarm" in HA itself. 
TBH with myself, I think what I really need there is more a native scheduler in HA. Thanks again for the hard work and the new features!
