### ISSUE TITLE
Wifi not working correctly

### ISSUE THREAD

**Issue by TECHNOFAB11** [home-assistant/android#924]
**Home Assistant Android version:**
2.4.0-full

**Android version:**
OxygenOS 10.3.4.GM57AA (Android 10)

**Phone model:**
OnePlus 7

**Home Assistant version:**
| | |
|---|---|
|arch|x86_64|
|dev|false|
|docker|true|
|hassio|false|
|installation_type|Home Assistant Container|
|os_name|Linux|
|os_version|5.4.0-0.bpo.4-amd64|
|python_version|3.8.3|
|timezone|Europe/Berlin|
|version|0.114.4|
|virtualenv|false|

**Last working Home Assistant release (if known):**
None

**Description of problem:**
I had a lot of problems over the last months with getting ip banned via the app. I was wondering why, as it shouldn't ban local addresses. Thanks to the authenticated sensor I saw that the app connected via the public url all the time (weirdly enough the widgets didn't as far as I can tell). Now I looked into the sensor settings in HA Android and there seems to be a WiFi issue. It knows that WiFi is on, it knows my internal IP, but it still says "not connected". HA has all permissions, but it still doesn't seem to be able to get the wifi information (BSSID is always 02:00:00:00...) like seen on the screenshots. 

**Traceback (if applicable):**
```
```

**Screenshot of problem:**
![Screenshot 1](https://user-images.githubusercontent.com/34860318/93016198-a2604c00-f5bf-11ea-8dec-9283a42c64a3.jpg)
![Screenshot 2](https://user-images.githubusercontent.com/34860318/93016199-a2f8e280-f5bf-11ea-8bed-072b9b783a44.jpg)

**Additional information:**

**Comment by dshokouhi** [comment]
Your SSID has `is_hidden` set to true so more than likely the API is not able to retrieve the SSID (at least that is my guess).  All the app is doing is grabbing the API data and sending the data to HA.  We don't change any of the data unless we get nothing in response from the API.  If you set your network not to be a hidden network do you see the sensor functioning as expected?

**Comment by smartviperbg** [comment]
Same here with Huawei P30 Pro and P30 lite with last updatet androids. Before update the home assistant app it's working great and shows all of my networks.

**Comment by Maltavius** [comment]
Have the same issue on my Wife's Samsung S8
Sometimes it works and sometimes it's just Unkown SSID
![image](https://user-images.githubusercontent.com/10133945/94363432-5b478000-00c2-11eb-81f3-76a3b979e82a.png)

The Network doesn't have a hidden SSID

**Comment by txusebe** [comment]
same issue on my Samsung A8 althought my xiaomi works great

**Comment by GianCann** [comment]
I have the same problem with my HUAWEI P20 Lite.
The connection to 'Internal URL' (when connected to my WiFi) don't work because the App don't obtain the SSID:
![120355331_10221681299815618_6172283856357135251_o](https://user-images.githubusercontent.com/45897944/94435529-881b9600-019b-11eb-9255-e4c4f3467ee1.jpg)

**Comment by JBassett** [comment]
Does the application have background location permissions?  This seems like an issue of missing permissions.

**Comment by GianCann** [comment]
> Does the application have background location permissions?

In my case, yes: HA have permissione to get position from the phone.

**Comment by Maltavius** [comment]
Yes it has permissions unless those can change without doing anything.
As you can see from the screenshot above it changed over night without us doing anything.

**Comment by GianCann** [comment]
Ok, I found the problem related to 'unknown" SSID.
Is needed to power on the GPS function of the smartphone to read the SSID.

Anyway (in my case), with the correct SSID, the App don't connect to internal url of HA due to wrong SSL certificate released and valid for the external domain url, but invalid when you use internal url (directly IP address).

**Comment by dshokouhi** [comment]
> Is needed to power on the GPS function of the smartphone to read the SSID.

So you had location permissions granted for the app and also had GPS disabled?

**Comment by GianCann** [comment]
> So you had location permissions granted for the app and also had GPS disabled?

Yes. With the old Android API it's possible to read the SSID with the GPS disabled.

Now, it's no more possible.

I don't want to have GPS enable all the time on my smartphone, for many reasons.

**Comment by TECHNOFAB11** [comment]
> Your SSID has `is_hidden` set to true so more than likely the API is not able to retrieve the SSID (at least that is my guess). All the app is doing is grabbing the API data and sending the data to HA. We don't change any of the data unless we get nothing in response from the API. If you set your network not to be a hidden network do you see the sensor functioning as expected?

I just checked again (phone was in repair) and it still says that the WiFi is hidden. Fun thing is that it isn't. I have some hidden networks, but the one I'm using is showing the SSID. It's using 5Ghz though, thats the only difference I can see to a completely normal wifi connection (can't change it tho because Android 10 doesn't allow me to specify which to use). And I'm using custom IP settings (static IP, gateway, dns (Google DNS) ).

I also tried it with my Tablet (Huawei MediaPad M5 lite 10, running Android 8) and it works on there. It also correctly reports the wifi as not hidden.

Seems like it's an issue with Android 10, probably because of the more locked down permissions I'd guess.

**Comment by dshokouhi** [comment]
I wonder how we should handle the case where the sensor is attempting to update and GPS is turned off, not sure how to best notify the user in that case?

**Comment by poofyteddy** [comment]
This is a bummer.
I have the same issue and this change of android break my device_tracker that was based on the wifi name when the gps was off...

I would go with a "red' warning in the sensor setting, something like `this sensor require GPS to be turned on to get full functionality`
Any idea if there is a work around ? some extra permission we could grant with adb ?

**Comment by dshokouhi** [comment]
We now properly notify the user after #1187 when they attempt to use a feature that requires location and permissions.  Closing this issue now.
