### ISSUE TITLE
Biometric authentication can be bypassed

### ISSUE THREAD

**Issue by darookee** [home-assistant/android#925]
**Home Assistant Android version:**
2.4.0-full

**Android version:**
Android 11

**Phone model:**
Pixel 3

**Home Assistant version:**
0.114.4

**Last working Home Assistant release (if known):**

**Description of problem:**
While loading the app, pressing the 'back' key on the phone hides the fingerprint dialog but does not close the app (as it does, when HA is already loaded). After that the blur is still there but you can interact with the HA interface!

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
https://imgur.com/ZrlAQKp
Video: https://youtu.be/lB8Vn9dBpBg
(The video starts right before hitting the back-button, because privacy...)

**Additional information:**

**Comment by dshokouhi** [comment]
I am unable to reproduce this on my Pixel 4 running Android 11.  As soon as I hit the back button the app is closed and opening it forces me to accept the authentication prompt.  That is the only way I can get into the app once its enabled.

Heres a screen recording of what I see: https://drive.google.com/file/d/1qg8jOOhXjoBVn1ze_gD5pJVRITAnaCeL/view?usp=sharing

**Comment by JBassett** [comment]
I was able to reproduce, you need to hit back at just the right time.  Sometimes it takes me a couple of tries.

**Comment by dshokouhi** [comment]
I wonder if its because of fingerprint vs face unlock? It uses the same API just odd because looking at the code it seems like we do it all right :/ i wonder if its an API issue?  Still can't reproduce on any screen i hit the back button on. I guess its a sweet spot issue.
