### ISSUE TITLE
charger_type sensor reporting unknown, should be "none" or "not charging"

### ISSUE THREAD

**Issue by BoneheadFraggle** [home-assistant/android#930]
**Home Assistant Android version:** 2.4.0-full

**Android version:** 11

**Phone model:** Pixel 2

**Home Assistant version:**0.115.b09

**Last working Home Assistant release (if known):**

**Description of problem:** sensor.[my phone]_charger_type sensor is reporting state "unknown" when the phone is not charging. I think it would make more sense to report "none" or "not charging"

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![Charger Type](https://user-images.githubusercontent.com/2287810/93063845-1f9ac800-f677-11ea-8019-72dffbac6817.png)

**Additional information:**

**Comment by dshokouhi** [comment]
We are actually following Android's API here so unknown is to be expected when nothing is plugged in.

https://developer.android.com/reference/android/os/BatteryManager#BATTERY_STATUS_UNKNOWN
