### ISSUE TITLE
App flashes white screen on startup

### ISSUE THREAD

**Issue by LeChuck2909** [home-assistant/android#931]
**Is your feature request related to a problem? Please describe.**
When starting the app, the whole screen of the smartphone flashes white for a very short time. Followed by the default loading screen which is white as well.

**Describe the solution you'd like**
It would be great if 1. the initial white flash could be avioded. 2. The default loading screen is bright/dark e.g. according to the OS settings.

**Describe alternatives you've considered, if any**

**Additional context**
As Home Assistant became my daily companion, there are offen situations, where i start the app late at night or even in bed already. While all other light sources are dimmed including using a dark theme for the front end of HA, i cant avoid my eyes being flashed when starting the companion app. 

Thank you guys.

**Comment by dshokouhi** [comment]
I think this might be from the HA frontend?

**Comment by LeChuck2909** [comment]
ok, when i try to recreate this on a desktop pc, i see the loading screen indeed, but as this happens so quickley i can not say, if this are two distinct situations as described or the loadingscreen only. never the less, if theres a fix in 0.115 already, this would be great.

**Comment by LeChuck2909** [comment]
ok, so after i have update to 0.115.0 i found the subsequent default loading screen have now a dark background, thats great, but the initial white flashed screen is still present. so my yes got still blended when staring the app in low light enviroment.

**Comment by geniusled** [comment]
Hello, i have been experiencing this exact behavior to this day. 
Amdnroid 9
Companion app 2025.5.3-full
@dshokouhi you seemed uncertain about this issue, any chance their night still be something going on?

**Comment by altacountbabi** [comment]
I'm still having this issue, I think its an issue with the webview having a white background by default, this doesn't happen if I access the home assistant frontend in the browser because most browsers use a dark background as the default webview background
