### ISSUE TITLE
Read NFC Tag actually writes

### ISSUE THREAD

**Issue by pixeye33** [home-assistant/android#940]
Home Assistant Android version:
2.4.1-full

Description of problem:
Inside the "NFC Tags" screen, when i click "Read NFC tag" and present a non-hass tag : the app writes the tag !
I would expect the app to write tag only when using the "write nfc tag" button.

**Comment by aaamoeder** [comment]
I also see this behaviour.. I'm on 114.4 and the latest beta build of the android companion app

**Comment by BoneheadFraggle** [comment]
Same here. Pixel 2/Android 11/2.4.1-full
