### ISSUE TITLE
Can not clear grouped notifications with single swipe

### ISSUE THREAD

**Issue by the0ckid82** [home-assistant/android#943]
**Home Assistant Android version:**
beta-376-60ecbaf-full
**Android version:**
11
**Phone model:**
pixel 3 xl
**Home Assistant version:**
0.114.4
**Last working Home Assistant release (if known):**

**Description of problem:**
When there are multiple notifications from HA they get grouped together and collapsed, previously you could swipe the group to clear them all, now on android 11 you have to expand the group and clear them 1 by 1 
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**
I believe this change happened with android 11

**Comment by dshokouhi** [comment]
Can you share the YAML example of the notification please?  The only way they should be grouped together is by using the `group` tag: https://companion.home-assistant.io/docs/notifications/notifications-basic/#thread-id-grouping-notifications

Thats at least the way it worked in Android 10.

**Comment by the0ckid82** [comment]
![image](https://user-images.githubusercontent.com/5402500/93393272-151f3080-f827-11ea-823f-62fdadeac2ed.png)
![image](https://user-images.githubusercontent.com/5402500/93393298-210af280-f827-11ea-8e25-96870005c621.png)

all my notifications are setup thru node-red but that really shouldn't make a difference, and none of them use the groups. even with out using groups after the 3rd notification they automatically get grouped and once that happens you can no longer just swipe the group to dismiss them the group must be expanded and then they can individually be dismissed 

![image](https://cdn.discordapp.com/attachments/467471316916764672/755902094363590716/Screenshot_20200916-142419.png)

![image](https://cdn.discordapp.com/attachments/467471316916764672/755902448450928640/Screenshot_20200916-142616.png)

**Comment by dshokouhi** [comment]
This may be a new thing in android 11 we will have to see if we can circumvent.  For now try adding the `group` and see if it works as intended now.  I have not seen google mention they changed how notifications are grouped like this but I do know they changed a lot of things around how they are presented.

**Comment by the0ckid82** [comment]
no problem minor work around for now is the clear all button still works .. not really a huge inconvenience for me but my 7 month pregnant wife has decided that this is the most annoying thing in the world right now

**Comment by dshokouhi** [comment]
haha I am annoyed by the large spacing around `Notification` `Conversation` and `Silent` theres so much unused space over there!

**Comment by hansharhoff** [comment]
Just a note that this occurs on my girlfriend's oneplus 8 but not my oneplus 6t. both running Android 11.

**Comment by dshokouhi** [comment]
> Just a note that this occurs on my girlfriend's oneplus 8 but not my oneplus 6t. both running Android 11.

Please don't comment on old and closed issues, instead open a new issue with the template filled out.
