### ISSUE TITLE
%key_id string shown when using biometric unlock

### ISSUE THREAD

**Issue by BoneheadFraggle** [home-assistant/android#944]
**Home Assistant Android version:** 2.4.1-full
**Android version:** 11
**Phone model:** Pixel 2
**Home Assistant version:** 0.115.0b12
**Last working Home Assistant release (if known):** -
**Description of problem:**
When starting the app with biometric unlock enabled, the dialog says "[%key_id:321654987xx%] måste låsas upp".
Måste låsas upp is Swedish for must be unlocked, so that's fine, but I don't think the key_id string should be there. I guess it is supposed to be the phone name or the app name?
**Traceback (if applicable):**

```

```

**Screenshot of problem:**
Sorry, the phone won't allow screenshots when the biometrix dialog is active.

**Additional information:**

**Comment by dshokouhi** [comment]
Looks like we need to fix this issue from Lokalize directly: https://github.com/home-assistant/android/blob/master/app/src/main/res/values-sv/strings.xml#L14

Someone actually kept the key string in there.

**Comment by dshokouhi** [comment]
Hmm more than 1 location too: https://github.com/home-assistant/android/blob/master/app/src/main/res/values-sv/strings.xml#L32 

I wonder how many other languages have this issue
