### ISSUE TITLE
Menu icons disappear when scrolling to bottom

### ISSUE THREAD

**Issue by DomiStyle** [home-assistant/android#947]
**Home Assistant Android version:** 2.4.1-full

**Android version:** 10

**Phone model:** Samsung Galaxy S9+

**Home Assistant version:** 0.115.0

**Last working Home Assistant release (if known):** about 0.113.0

**Description of problem:** Menu icons disappear and become glitched when arriving at the bottom after scrolling

**Traceback (if applicable):** -

**Screenshot of problem:**

![Screenshot_20200917-210437_Home_Assistant](https://user-images.githubusercontent.com/975131/93519225-433b6800-f92e-11ea-82da-fa1def461e79.png)
![Screenshot_20200912-103004_Home_Assistant](https://user-images.githubusercontent.com/975131/93520572-fa37e380-f92e-11ea-8878-79a9372cdaf3.png)

**Additional information:**
I have had this problem since a few versions, not sure if an app update or HA update caused it but it started happening around the release of 0.114.0 or slightly before that.
It doesn't happen on my Android tablet but does on my phone. I tried reinstalling the app (including wiping all data/cache) and disabling various Lovelace modules.

**Comment by dshokouhi** [comment]
Check that android system webview is up to date on your phone.  Also if it is up to date then check the same behavior in chrome for android and let me know if it happens there too.

**Comment by DomiStyle** [comment]
Good idea, is the system webview version equal to the Chrome version?

It does indeed also happen in the browser included with LineageOS (Jelly).
I got this from the user agent of the included browser:

`
Mozilla/5.0 (Linux; Android 10; SM-G965F Build/QQ3A.200805.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/85.0.4183.101 Mobile Safari/537.36
`

My tablet has Chrome 84.0.4147.89 and things look fine there.

**Comment by dshokouhi** [comment]
If it happens in the browser and the app then it is a [frontend](https://github.com/home-assistant/frontend) issue and not an app issue. Are you using any custom cards? Maybe check that they are all up to date.

**Comment by DomiStyle** [comment]
@dshokouhi I tried disabling various custom cards already and found none that causes this issue.

I think this is an issue with the Lineage included webview (com.android.webview). The HA app works fine with the Google webview (com.google.android.webview) from the Play Store.

Switching to the Google webview has solved this problem for now.
