### ISSUE TITLE
Automation editor text input fields buggy

### ISSUE THREAD

**Issue by Aasikki** [home-assistant/android#948]
**Home Assistant Android version:**
2.4.1-full

**Android version:**
10.0.7

**Phone model:**
Oneplus 7 Pro

**Home Assistant version:**
0.115.0

**Last working Home Assistant release (if known):**
As far as I know this has always been an issue.

**Description of problem:**
Automation editor has lots of bugs with input fields with multiple lines:

- When deleting characters with backspace the cursor won't jump to next line automatically after emptying one line.

- It's very hard to try and select all characters in the input field, as everything just gets deselected right after trying to do so.  After multiple tries it is possible to select everything though.

- When trying to paste the previously copied entry after successfully selecting everything, pasting doesn't work correctly; only part of what was copied is pasted and/or lines are incorrect.

- After typing in service data field and pressing space, the editor goes to YAML mode and gives a warning about UI editor not supported for this config, even though I had no chance to fully type in what I was about to type.

- After typing the service data in YAML and formatting it correctly, after going back to edit with UI the warning still remains and If I move the action up with the arrow buttons the warning doesn't follow and is transferred to the action now at the bottom.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
It is hard to take screenshot of this particular issue.

**Additional information:**
There might be more bugs. This is very annoying as I like to use mobile to do small edits to my automation as it allows me to be at the place where the automation occurs so I don't need to walk back and fourth from my PC. English is not my first language and I haven't had to type much technical stuff before so I hope I was clear enough!

**Comment by dshokouhi** [comment]
These are actually issues with the frontend since it uses code mirror and the problem exists there, we won't be able to fix it in the app.

See:
https://github.com/codemirror/CodeMirror/issues/6349
https://github.com/codemirror/CodeMirror/issues/3545

**Comment by letroll** [comment]
Why use code mirror on smart device?

**Comment by dshokouhi** [comment]
@letroll please take your concern to the HA frontend repo codemirror is unrelated to the app as it is part of the frontend.
