### ISSUE TITLE
home-assistant android 2.4.1: no notifications

### ISSUE THREAD

**Issue by Xa4-J** [home-assistant/android#952]
**Home Assistant Android version:2.4.1

**Android version: 9

**Phone model: Samsung Note 8

**Home Assistant version: 0.112.2

**Last working Home Assistant release (if known): Home Assistant Android version:2.1.1

**Description of problem:**Notifications no longer works on android app 2.4.1. If I install the old version 2.1.1 it works.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Can you please show an example of what is not working?

**Comment by Xa4-J** [comment]
I don't know what the problem was, but the notifications stopped working at my note 8 after the app update. After I removed the app and installed the old version it worked again. I have now performed the update via Playstore again (just like before) and now it works. No idea why it didn't work at first. So problem is solved but I cannot explain it.
