### ISSUE TITLE
Elite ibeacon compatible wij esphome

### ISSUE THREAD

**Issue by rdehuyss** [home-assistant/android#960]
Please add the feature to emit ibeacons.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when presence detection is not working and triggering the alarm.

**Describe the solution you'd like**
Emit ibeacons from the app so that can be used as presence detection by esphome. Automatic room_presence detection as esphome devices are located in areas

**Describe alternatives you've considered, if any**
Other apps like beacon simulator

**Additional context**

**Comment by Alfiegerner** [comment]
There are a couple of Android apps that do this, e.g. Beacon Simulator and Beaconscope, but neither persist with Bluetooth or phone restarts. 

Beacon simulator source: https://github.com/vhiribarren/beacon-simulator-android

Beaconscope transmitter source: 
https://github.com/davidgyoung/ningo-android/blob/master/app/src/main/java/com/davidgyoungtech/beaconscanner/BeaconTransmitter.java

**Comment by dshokouhi** [comment]
> I'm thinking this could sit as another Bluetooth sensor

Agreed, this way it will persist between restarts as it will be part of our foreground service.

> and an MVP initial build I was thinking that most details could be defaulted:
> 
> * beacon type is defualted to iBeacon
> * UUID, major and minor all defaulted
> * Power and frequency defaulted

MVP is always a good idea, once things get reviewed and merged with the bare minimum its easier to add features later on :)


> * Force Bluetooth on.  when sensors are refreshed, check if bluetooth, if off start bluetooth and restart transmitting.  For those using beacon functionality for home and room presence this would be extremely useful

Not sure how much this makes sense given that sensors update every 15 minutes and anytime any of the enabled sensors triggers an update.  Some users may have very frequent updates getting triggered so behavior could be sporadic there when you have all sensors enabled.  One thing that the full version of the app offers is a command to control bluetooth on the device remotely so could be useful to use that :)



> Is that worth tackling?

I say definitely and we are here to help, you can find the team members on discord #devs_mobile_apps

We can always use more contributers!!!

> Or would feature parity be a consideration?

It doesn't have to get built with iOS side by side one thing we can do during PR review is to get with the iOS team and come down with some basics if we can do it.  It really depends on the data we get and how we want to implement things.  In some cases it doesn't make sense to try and match features given the difference between the platforms.  It really depends on what data we want to present.  If both offer the same then we can agree to a format so the team can take on at a later point in time.  When we had NFC added we actually had all these discussions in the PR itself.

**Comment by Alfiegerner** [comment]
@dshokouhi  thanks very much, I think I have enough to make a start (no promises thought time is tight :) ).

On the Force bluetooth auto restart option, what i'm looking for here is something to solve the use case that Bluetooth gets turned off (mostly accidentally in my case), that it gets auto-restarted automatically.

It's not necessarily part of this feature / sensor though - but would be very valuable for this ,  as false negatives by bluetooth being off accidentally has a bug UX impact.

I imagine this is also a problem a with GPS sensor and location being turned off, same presence related porblem ... For now I guess we leave this out, and we can discuss further down the line.

**Comment by dshokouhi** [comment]
> On the Force bluetooth auto restart option, what i'm looking for here is something to solve the use case that Bluetooth gets turned off (mostly accidentally in my case), that it gets auto-restarted automatically.

The existing bluetooth state sensor updates immediately upon a state change, you can then use the bluetooth notification command turn it back on :)

https://companion.home-assistant.io/docs/core/sensors#bluetooth-sensor

https://companion.home-assistant.io/docs/notifications/notification-commands#bluetooth

**Comment by Alfiegerner** [comment]
@dshokouhi Perfect! Nice functionality, and nice to have it as a solved problem.

Will be in touch, thanks.

**Comment by philsson** [comment]
I found my way here looking to see if there was a feature request for a publishing BLE beacon in the app. It would really be awesome. I've tried presence detection with other apps successfully, although they don't automatically start on phone reboot and I also would rather skip extra apps. A beacon on 1 or 4hz seem to draw close to no battery. I guess this is very low power as BLE beacons on a small batteri can transmit for over a year once every few seconds.

**Comment by patdemko** [comment]
I'm also interested in this functionality in the HA android app to use with room assistant when home since the others apps I've found (mentioned above) are not reliable.  I'd also like the ability to have it only transmit the beacon when I'm in a specific location (i.e Home) so to save on battery life of the phone as well as not transmit something others could use as a tracker when I'm not using it.  As long as there's a switch to activate / deactivate it via Home assistant that could easily be solved via an automation of some kind if it's not built into the app.

**Comment by Alfiegerner** [comment]
> I'm also interested in this functionality in the HA android app to use with room assistant when home since the others apps I've found (mentioned above) are not reliable. I'd also like the ability to have it only transmit the beacon when I'm in a specific location (i.e Home) so to save on battery life of the phone as well as not transmit something others could use as a tracker when I'm not using it. As long as there's a switch to activate / deactivate it via Home assistant that could easily be solved via an automation of some kind if it's not built into the app.

Good news is that it's on it's way.  I have a pre-release version I'm testing and so far so good.  On the robustness front I've noticed an issue today that I've fixed with BT state change not being handled.  At least having the functionality somewhere we can fix it if required is a big plus, as the other apps I don't think were intended as full time beacon emitters.

It can be turned off / on via command notifications from HA automations, e.g. off when out of Home.  

Forthcoming attractions :)

**Comment by philsson** [comment]
> > I'm also interested in this functionality in the HA android app to use with room assistant when home since the others apps I've found (mentioned above) are not reliable. I'd also like the ability to have it only transmit the beacon when I'm in a specific location (i.e Home) so to save on battery life of the phone as well as not transmit something others could use as a tracker when I'm not using it. As long as there's a switch to activate / deactivate it via Home assistant that could easily be solved via an automation of some kind if it's not built into the app.
> 
> Good news is that it's on it's way. I have a pre-release version I'm testing and so far so good. On the robustness front I've noticed an issue today that I've fixed with BT state change not being handled. At least having the functionality somewhere we can fix it if required is a big plus, as the other apps I don't think were intended as full time beacon emitters.
> 
> It can be turned off / on via command notifications from HA automations, e.g. off when out of Home.
> 
> Forthcoming attractions :)

This is really great news! Excellent work and many thanks for this awesome addition.

**Comment by dshokouhi** [comment]
@Alfiegerner are we good to close this one too?  Or does this need something else?

**Comment by Alfiegerner** [comment]
@dshokouhi yep, feature completed, thanks.
