### ISSUE TITLE
Sleep mode for notifications

### ISSUE THREAD

**Issue by Mincka** [home-assistant/android#962]
**Is your feature request related to a problem? Please describe.**
Sometimes, you just want to put some specific app to sleep for a limited time. It's also useful when multiple devices are targeted by the notify service and you just want to disable it for yourself temporarily.

**Describe the solution you'd like**
Implement a sleep mode for notifications like it's done on other apps like Outlook or Wyze. You just tap the bell icon (mdi:bell) and it's replaced with bell sleep icon (mdi:bell-sleep). The notifications are now paused for the application. I think a basic implementation would be great to begin (not like the Outlook one where you can use timers or schedules).

A sensor could also be created to map the status of this sleep mode for the app.

**Describe alternatives you've considered, if any**
Fiddle with the application settings in Android. Way more complicated and easy to forget.

**Comment by dshokouhi** [comment]
This is already a feature of stock android to snooze notifications, you should be able to do the same with this app.

**Comment by Mincka** [comment]
Not the same purpose. Snooze a specific notification != Mute a notification channel
Snooze means *Replay* a notification later (with predefined periods: 15, 30 minutes, 1, 2 hours).
If you snooze a notification, it does not mute/silence a channel and you still get following the notifications before the snoozing period. I tried with HA and another app.

**Comment by dshokouhi** [comment]
So if you need to go in your phone and tell it to mute/silence a notification channel how is that different than using a widget for a input boolean and having your automation handle the logic?  Also wouldn't setting your phone to DND ignore the notifications too?  Sorry just trying to see the use case given the features of the android OS.

**Comment by Mincka** [comment]
There is no feedback of the state on an action widget. That would require to use two widgets to check the status.
Moreover, you would need to add this logic to each automation sending notifications, with a logic that would need to check for each device in the notification group which ones are in mute or not.
DND is too mute all the notifications. You could use the priorities but it is not done for punctual needs.

Like I said, sometimes, I just want to easily mute an app while staying available for others. That's the idea for Outlook or Wyze. I am bothered by multiple e-mails or multiple events but you want to focus on other apps, so you just put the app "to sleep".

Before using the notifications on HA, I was using Pushover, which also supports an internal DND mode. There is one additional thing that is useful with Pushover, that's the log of the notifications. Once you come back from a DND / mute mode, you can catch up the notifications (still more useful than the native "snooze" Android feature). Maybe this one is for another topic: merge / review the concept of Notifications as presented in the HA Android app. It is not clear for new users if you expect to see a log of Android or HA core notifications in the Notifications panel.

**Comment by dshokouhi** [comment]
So giving this request some thought.  The idea is to have something like a toggle in App Configuration to pause notifications from posting on the device (or commands being ran) until the user comes back to App Configuration to resume notifications?  Just wondering if we should do something like a persistent notification to make it more apparent notifications are not posting until its enabled or to just create a sensor that represents the state of this new toggle.  There are some new considerations here given the new commands that are ran silently as well as how to inform a user.  I don't use either of the apps you mentioned so feel free to post screenshots of what you'd expect.

**Comment by Mincka** [comment]
In pushover, there is a half moon symbol and when you click on it, you can pick between predefined durations. 
When the DND mode is enabled, the symbol is a white half moon.

<img src="https://user-images.githubusercontent.com/6184289/104837732-c4901080-58b6-11eb-8c75-fdf69e22caa4.png" width="200" >&nbsp;<img src="https://user-images.githubusercontent.com/6184289/104837740-d2de2c80-58b6-11eb-9591-d136edddb670.png" width="200" >

It looks like it's not possible to set "forever" so there is less risk to forget it. It's a design consideration I guess. I think it's a good choice to always have an automatic reset to default because your really should fix something if you need to permanently disable the notification in the app through this feature... Your suggestion to have a persistent notification to be aware of this state is also valid I guess but it could be also annoying since you don't want to see HA at all for a few hours.

Pushover don't use a persistent notification while in DND mode. It just silently disable it once the predefined period is over.
