### ISSUE TITLE
Drawing error on android 10 after scrolling down

### ISSUE THREAD

**Issue by JasperE84** [home-assistant/android#965]
**Home Assistant Android version:**
2.4.1-full

**Android version:**
Android 10 / [Lineage 17.1](https://forum.xda-developers.com/s7-edge/development/beta-lineageos-17-0-s7-edge-build-1-t3979973)

**Phone model:**
SM-G935F (Samsung S7 Edge / hero2lte)

**Home Assistant version:**
0.114.1

**Description of problem:**
There's an issue rendering the UI. Upon app start everything is fine, and controls/buttons can be used. But the rendering can go bad after scrolling up 'too much'. If I avoid scrolling up beyond the menu header everything is fine. But if I swipe up a little too far the UI goes invalid. 
(I know I'm running a custom Lineage rom, but out of the tens of apps on my phone, the home assistant android app is the only app with an issue like this.)

**Screenshot of problem:**
I have made a screen recording and shared it using Google Drive to demonstrate the descriptiong above. [Click to watch](https://drive.google.com/file/d/18g-S_aQgTfjIlpqXGMfJmuaMToTRxAsc/view?usp=sharing).

**Comment by dshokouhi** [comment]
If you are running lineage OS then you need to stop using their provided webview and use Android System Webview, we had a user with a similar issue and that fixed it for them.

**Comment by JasperE84** [comment]
That's excellent, simply installing that fixes it, thanks!

**Comment by JasperE84** [comment]
Solved
