### ISSUE TITLE
No history and sensor updates after a few hours

### ISSUE THREAD

**Issue by TheNogl** [home-assistant/android#981]
**Home Assistant Android version:**
2.4.1
**Android version:**
Android 6 & Android 10
**Phone model:**
Huawei P8, Huawei P9, OnePlus 7T
**Home Assistant version:**
0.115.2
**Last working Home Assistant release (if known):**
not known
**Description of problem:**
After a few hours of the app being open, history of sensors is not shown anymore, when clicking on it. It is stuck at "loading history". 
A few hours after this, sensor values do not get updated at all. This only happens in the app, in the browser this problem does not occure.
Closing the app, and reopening it solves all the issues. But I want to set up something similar to this [Thermostat](https://www.reddit.com/r/homeassistant/comments/ig39jo/diy_fireplace_thermostat_with_shelly/), so this won't be a permanent solution for the issue.
**Traceback (if applicable):**

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Did you make sure to disable battery optimisations for the app? Please follow these steps.

https://companion.home-assistant.io/docs/troubleshooting/faqs/#location-is-not-updating-in-android-app

**Comment by TheNogl** [comment]
Yes battery optimisation is disabled.

I think you are thinking of the wrong thing, it is not the android sensors sending to homeassistant, these work fine, but android stops receiving sensor data from homeassistant

**Comment by dshokouhi** [comment]
Check that android system webview is up to date, the app doesn't control what we get from the frontend but the webview controls how its displayed.
