### ISSUE TITLE
Remove periodic "sensor updating" and empty notifications

### ISSUE THREAD

**Issue by anduchs** [home-assistant/android#983]
**Is your feature request related to a problem? Please describe.**
Every once in a while a "sensor updating" or an empty notification appears for 1-2 seconds.
Whilst that's not a problem on the phone it triggers my Xiaomi-Band every time, which is kind of disturbing.

**Describe the solution you'd like**
Silence these notifications

**Describe alternatives you've considered, if any**
Have the notifications appear from a "different" application so I can block this one whilst keeping the actual notifications working.

**Additional context**

**Comment by rs443** [comment]
Foreground service was introduced in #854 to make sensor updates more reliable.

Can't you disable the SensorWorker notification in Android? Works for me.

**Comment by dshokouhi** [comment]
We can't remove the foreground service as it's for sensor updates reliability. As @rs443 mentioned you can turn off the channel but keep in mind if the updates become unreliable you may need to turn it back on. We also can't make it come from another application.

**Comment by anduchs** [comment]
Thanks a lot for the quick help ! I'd give you carma if that was a thing here !

**Comment by Hypfer** [comment]
To add some context for why this is necessary:

https://dontkillmyapp.com/
