### ISSUE TITLE
No HTML formatting in Grouped message section

### ISSUE THREAD

**Issue by cholek3** [home-assistant/android#985]
**Home Assistant Android version:**
2.5.0-full
**Android version:**
10
**Phone model:**
Samsung Galaxy S20
**Home Assistant version:**
0.115.2
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
I don't know if it is a bug or Android limitation (sort of), but when using HTML formatting in message, it only shows in expanded view, not in collapsed view. Screenshots attached.
It works fine for TITLE.

**Traceback (if applicable):**
N/A

**Screenshot of problem:**
![001](https://user-images.githubusercontent.com/43534386/94488235-24648d80-01da-11eb-8b43-30cf60347e39.png)
![002](https://user-images.githubusercontent.com/43534386/94488249-2dedf580-01da-11eb-982b-c10f8b245e1d.png)

**Additional information:**

**Comment by dshokouhi** [comment]
This is to be expected formatting for message is only applied to the expanded view:

https://developer.android.com/training/notify-user/expanded

We had some more discussion on this here too: https://github.com/home-assistant/android/issues/711

**Comment by cholek3** [comment]
> We had some more discussion on this here too: #711
> 
> Edit: Actually just noticed its when the items are grouped together it does not show it in collapsed

Yes, it's only happening in Group messages.

**Comment by cholek3** [comment]
There is also different behaviour between Android's Dark and Light modes. In Dark mode, TITLE html formatting also changes between collapsed and expanded view.
![20200930_072807](https://user-images.githubusercontent.com/43534386/94663546-b0250980-0301-11eb-9cf6-07427955d45a.gif)
![20200930_073201](https://user-images.githubusercontent.com/43534386/94663590-bb783500-0301-11eb-9029-00e37ba0237d.gif)
