### ISSUE TITLE
Allow Android intent to open apps

### ISSUE THREAD

**Issue by Hellis81** [home-assistant/android#990]
**Is your feature request related to a problem? Please describe.**
It would be great if you could send an actionable notification from HA and have a link to open an app

**Describe the solution you'd like**
Allow/enable android intents to open apps from HA companion app

**Describe alternatives you've considered, if any**
Not sure if there are any alternatives. 

**Additional context**

**Comment by dshokouhi** [comment]
Actually this is a duplicate of #956 closing in favor of it
