### ISSUE TITLE
Empty notifications from home assistant

### ISSUE THREAD

**Issue by simontb** [home-assistant/android#993]
**Home Assistant Android version:** 2.5.0-full

**Android version:** 11

**Phone model:** Pixel 4

**Home Assistant version:** 0.115.0

**Last working Home Assistant release (if known):**

**Description of problem:** I frequently get empty notifications from home assistant, although I didn't set-up any. There is an icon in the notifications area on the top left as well. The icon is also on the lock screen.

Mostly I haven't even opened the app for multiple hours.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![Screenshot_20200929-102430~2.png](https://user-images.githubusercontent.com/6491719/94726802-0aec4e80-035e-11eb-84c5-ebfd6e19adb2.png)

**Additional information:**

**Comment by dshokouhi** [comment]
This notification disappears after a few seconds right?

I believe this is what happens when the system kills our app and the sensor worker is no longer able to pull in the translated strings. 

https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt#L34

**Comment by simontb** [comment]
Yes it does. Sorry, forgot to mention that.

Although the notification disappears quickly, it still bothers me.

Okay, that would explain why there's no content, but not why the notification is shown at all.

**Comment by dshokouhi** [comment]
This is the foreground sensor worker more details are in the blog post including how to turn it off and why it exists: https://www.home-assistant.io/blog/2020/09/12/android-240-release/#foreground-service-worker

**Comment by tispokes** [comment]
Hi I experience this several times a day. Locale de.
I also triggers a notification on my smart watch garmin venu 2+, that it what is bothering me. But I want the usual notifications on my watch.

**Comment by dshokouhi** [comment]
> Hi I experience this several times a day. Locale de. I also triggers a notification on my smart watch garmin venu 2+, that it what is bothering me. But I want the usual notifications on my watch.

this issue was closed over 3 years ago, please open a new issue making sure to fill out the issue template completely. We also cannot help troubleshoot your smart watch as its just relaying notifications.
